### ISSUE TITLE
ask questions about CombinedChartViewController.h 

### ISSUE THREAD

**Issue by 931743010** [danielgindi/Charts#1001]
CombinedChartDrawOrderBar use MultipleBarChartViewController.h
i want 
![4e213111-8136-4070-a896-52187dca848e](https://cloud.githubusercontent.com/assets/9315727/14977817/09389b44-114a-11e6-80a5-33d2a0cc9c8f.png)

actually
![img_0669](https://cloud.githubusercontent.com/assets/9315727/14977839/2f020694-114a-11e6-99fa-62272f9ddadd.PNG)

help help

[CombinedChartViewController.m.zip](https://github.com/danielgindi/Charts/files/246503/CombinedChartViewController.m.zip)

**Comment by liuxuan30** [comment]
currently the master branch does not support grouped bar support, it's still in review.
You can try my branch: https://github.com/liuxuan30/Charts/tree/GroupedBarsCombinedChart
I have not synced to latest code base, so expect differences with master.

**Comment by 931743010** [comment]
Can you tell me which files have been changed, it's hard to find

**Comment by 931743010** [comment]
![8e61a681-6805-437c-b1e3-701691ed88c9](https://cloud.githubusercontent.com/assets/9315727/14979256/c926c58a-1153-11e6-9d20-c1029ac7fb77.png)
it‘s all red；Best to help me with the latest version of the latest version; because I do not know the relationship between them

**Comment by 931743010** [comment]
@liuxuan30   thank you very much

**Comment by liuxuan30** [comment]
I didn't sync with master right now. It just lacks some new features or bugfixes from master. If you only care the combined chart, you just use my branch as the whole library.

I will try find some time to sync, but don't expect an ETA, I'm sorry.

**Comment by 931743010** [comment]
@danielgindi  help Adopt him request

**Comment by liuxuan30** [comment]
he knows it, but it is a huge effort, so please be patient.

**Comment by 931743010** [comment]
yes,we should be patient.   
he just got married .congratulations.
@liuxuan30  能说中文不，说英文老费劲了；问下 集成你的 这个库   怎么做到和我第一个图 一样的效果呢？ 目前我尝试下来好像是不行的
Can i speak Chinese？ say English so laborious; ask how to integrate your this library to be able to do with my first figure the same effect? At the moment I try to down it looks like it's not.

**Comment by liuxuan30** [comment]
I encourage you use English :)
For your first image, your bars has some overlap in each group, so I guess you have to override bar chart renderer's code to get what you want. This requires you have some knowledge how it is rendered.

**Comment by 931743010** [comment]
@liuxuan30  thanks for Enthusiastic answer
;I have another question to ask.
; How to display only 6 months of form. Show more through sliding

**Comment by liuxuan30** [comment]
that's seprerate question. Search old issues and you will find answers.

**Comment by 931743010** [comment]
@liuxuan30    waiting for help！ this demand has not accepted? Before your version is 2.2.2; has been unable to use。

**Comment by 931743010** [comment]
@liuxuan30  sorry i just see swift 2.3 version    .i see  swift3.0 version  has this funtion ;so sorry

**Comment by liuxuan30** [comment]
Use Chart 3.0 to support this, thanks
