### ISSUE TITLE
How to let the Y axis shows is not only a number, but the custom string

### ISSUE THREAD

**Issue by yandeguangzy** [danielgindi/Charts#1003]
![6dd26621-948a-4ca5-9bdd-33082472fc7a](https://cloud.githubusercontent.com/assets/9551154/15004249/38bdc022-11e7-11e6-993d-0bcb42f75ccf.jpeg)

thank you!

**Comment by liuxuan30** [comment]
well... it is designed to display some value strings, so one easy way is to supply your own formatter, or you just override `drawValues` whatever you like to display.

**Comment by dxclancy** [comment]
as he says, look at BarChartData valueFormatter (ChartBaseDataSet)
