### ISSUE TITLE
Change the width of chart

### ISSUE THREAD

**Issue by Exlinct** [danielgindi/Charts#1005]
How can i fix width of chart by a constant like demo and if it has too many it can scroll horizontal
![simulator screen shot may 4 2016 4 18 43 pm](https://cloud.githubusercontent.com/assets/19178551/15010082/6dcd6fec-1214-11e6-8ecc-81bba118288a.png)
![simulator screen shot may 4 2016 4 22 12 pm](https://cloud.githubusercontent.com/assets/19178551/15010083/6e1c7bd2-1214-11e6-8878-fa40eede8f9b.png)

**Comment by liuxuan30** [comment]
by default, it will display all data, so the bar width is dynamic. you can just set the scaleX so it can scroll directly.

**Comment by dxclancy** [comment]
You can also do something like this:
const CGFloat barWidthPoints = ; // you decide
    CGFloat range = self.barChartView.width/barWidthPoints;
    [self.barChartView setVisibleXRangeWithMinXRange:range maxXRange:range];
but this may affect pinch zoom

**Comment by Exlinct** [comment]
thank you for suggestion :D
