### ISSUE TITLE
Change x-axis in bubble chart

### ISSUE THREAD

**Issue by Exlinct** [danielgindi/Charts#1007]
Can i customize the x-axis in bubble chart by input value ?
![simulator screen shot may 4 2016 5 18 25 pm](https://cloud.githubusercontent.com/assets/19178551/15011537/9203982a-121c-11e6-92a8-43bd798cde90.png)

**Comment by liuxuan30** [comment]
what you mean? It's too generic, of course you can custom everything :)

**Comment by pqhuy87it** [comment]
/// - parameter xIndex: The index on the x-axis.
    /// - parameter val: The value on the y-axis.
    /// - parameter size: The size of the bubble.
    public init(xIndex: Int, value: Double, size: CGFloat)
i want to set x-axis like y-axis so how can i do it ?

**Comment by Exlinct** [comment]
/// - parameter xIndex: The index on the x-axis.
/// - parameter val: The value on the y-axis.
/// - parameter size: The size of the bubble.
public init(xIndex: Int, value: Double, size: CGFloat)
i want to set x-axis like y-axis so how can i do it ?

**Comment by liuxuan30** [comment]
In short: currently x axis is index based axis, you can't.
In depth: we do have plans for supporting float x axis, but no ETA yet. If you are familiar with the library enough, you can write a whole new logic that takes x axis just like y axis.

**Comment by Exlinct** [comment]
ok thank you for answer
