### ISSUE TITLE
On Y Axis "0" may be displayed as "-0"

### ISSUE THREAD

**Issue by manuelneves** [danielgindi/Charts#1008]
ChartYAxisRenderer.swift

f may be -0 sometimes.
            let first = ceil(Double(yMin) / interval) * interval

(lldb) p yMin
(Double) $R1 = -531.21598815917969
(lldb) p interval
(Double) $R2 = 3000
(lldb) p Double(yMin) / interval
(Double) $R3 = -0.1770719960530599
(lldb) p ceil(Double(yMin) / interval)
(Double) $R4 = -0
(lldb) p first
(Double) $R5 = -0

This can be fixed like this:
            for (f = first, i = 0; i < n; f += interval, ++i)
            {
                 if (f == 0) { // make sure that 0 is always positive (f could be -0)
                                  f = 0;
                }
                
                _yAxis.entries[i] = Double(f)
            }

**Comment by liuxuan30** [comment]
I remember it has been fixed a long time. which version are you using?

**Comment by manuelneves** [comment]
You are right. I can see that you put in the same fix i suggested. 
We were using an older version.
Thanks!
