### ISSUE TITLE
Override with Wrong Argument Label?

### ISSUE THREAD

**Issue by Redoubts** [danielgindi/Charts#1009]
I have a question about `Classes/Highlight/HorizontalBarChartHighlighter.swift`

In it, you try to override
`public func getBase(x: Double) -> Double` from `BarChartHighlighter` [(link)](https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Highlight/BarChartHighlighter.swift#L176)
with
`public override func getBase(y: Double) -> Double` [(link)](https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Highlight/HorizontalBarChartHighlighter.swift#L93)

is it right to use `y` as the argument label, both semantically and as an override? Later you [use it on an x value](https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Highlight/BarChartHighlighter.swift#L59) which makes me suspicious if this is a bug or not.

**Comment by liuxuan30** [comment]
I guess it's not - compiler just cares about the function name, parameter types and return types

**Comment by danielgindi** [comment]
@Redoubts you are confused - it is not the label of the argument. It's the local name of the argument.
The first argument does not have a label unless explicitly specified.
