### ISSUE TITLE
BarChart Can‘t display Markers 

### ISSUE THREAD

**Issue by Maxcucurbit** [danielgindi/Charts#1017]
Hello！
When I use barChart class， and set barChart.drawMarkers = YES; then i clicked bar in barChart，BarChart Can‘t display Markers ，How fix it？
@danielgindi

**Comment by danielgindi** [comment]
First, please take a look at the demo first to see how to use markers.
Secondly - you do not have to **TAG** me. You can just ask your question, someone will try to help you sooner or later.
