### ISSUE TITLE
Enhancement: Linked x-axis or stacked y-axis.

### ISSUE THREAD

**Issue by aastein** [danielgindi/Charts#1022]
I need to plot data over the same range, but with drastically different values. It would be great if there was a way to stack/merge plots so the x-axis limits remain the same with any gestures. This means y-axis scaling and values would remain independent. It would also be great if the vertical line used to focus on a single data point could extend to all of the plots. 

Image showing what this enhancement could be applied to:
![thumb_img_1396_1024](https://cloud.githubusercontent.com/assets/18291415/15204906/2568cad2-17d0-11e6-973f-a6bdf6fd35e5.jpg)

**Comment by liuxuan30** [comment]
well it's a highly special chart, looks like put 3 different charts together, just with same xIndex. That's a workaround.

For the native support, I guess it's beyond the purpose of this library and arch.

**Comment by aastein** [comment]
Thanks @liuxuan30,I think I may have to do that. 

For now, how can I use chartTranslated(chartView: ChartViewBase, dX: CGFloat, dY: CGFloat) to implement a work around? How can I use the dX and dY values to resize the other charts?

**Comment by aastein** [comment]
Here is an example work around incase anyone is curious. 

Notes: 
- Uses protocol in ChartViewBase
- It is a very inefficient because it reloads the other charts every time another chart is resized. 
- Added a chartIdentifier public variable to ChartViewBase to get the correct indexes. 
- Disables the axis grids. They will not display the same on each chart if enabled. 
- As the other charts are reloaded, the y-axis range is reset/scaled on those other charts to just barely fit the data in range. So the y-axis gets pretty squished if the x-axis range is too small. It is similar to using autoscale.
------------------------------------------------------------------------------------------------------------------------------------

         // chartTranslated is part of the ChartViewBase protocol 
        func chartTranslated(chartView: ChartViewBase, dX: CGFloat, dY: CGFloat) {
        
        if chartView.identifier == "cciChartView" {
            
            // get the range for displayed values
            let minX = cciChartView.lowestVisibleXIndex
            let maxX = cciChartView.highestVisibleXIndex

            // create array from the index ranges in view of the relevant data, from the complete data set
            viewTempOpenData = Array(tempOpenData[minX...maxX])
            viewTempCloseData = Array(tempCloseData[minX...maxX])
            viewTempLowData = Array(tempHighData[minX...maxX])
            viewTempHighData = Array(tempLowData[minX...maxX])

            // reload the chart
            setChart(viewTempHistData, open: viewTempOpenData, close: viewTempCloseData, high: viewTempHighData, low: viewTempLowData)
        }
    }

**Comment by aastein** [comment]
I have implemented a fix, it is not implemented in the library so i guess it's technically a work around, but the behavior is the same as any real fix. 

For panning:
1. Add an identifier variable to your ChartViewBase class
2. Use chartTranslated, a ChartViewBase protocol method, in your chart delegate to get the translation of the chart your fingers are touching
3. Use the logic in performPanChange, a function in BarLineChartViewBase, on the other charts. 

For pinch zooming:
1. Add an identifier variable to your ChartViewBase class
2. Use chartScaled, a ChartViewBase protocol method, in your chart delegate to get the scale of the chart your fingers are touching. 
3. Change this line

> delegate?.chartScaled?(self, scaleX: scaleX, scaleY: scaleY)

to this

> delegate?.chartScaled?(self, scaleX: scaleX, scaleY: scaleY, location: location)

in BarLineChartViewBase.swift and update the protocol method it is calling in ChartViewBase to be this:

optional func chartScaled(chartView: ChartViewBase, scaleX: CGFloat, scaleY: CGFloat, location: CGPoint)

3. Use this part of the logic inpinchGestureRecognized, a function in BarLineChartViewBase, on the other charts, when you call chartScaled in your chart delegate. 

```
var matrix = CGAffineTransformMakeTranslation(location.x, location.y)
                    matrix = CGAffineTransformScale(matrix, scaleX, scaleY)
                    matrix = CGAffineTransformTranslate(matrix,
                        -location.x, -location.y)
                    
                    matrix = CGAffineTransformConcat(_viewPortHandler.touchMatrix, matrix)
                    
                    _viewPortHandler.refresh(newMatrix: matrix, chart: self, invalidate: true)
```

**Comment by liuxuan30** [comment]
try `setVisibleXRangeMaximum`

**Comment by aastein** [comment]
that was the first thing I tried. It didn't work, I like my solution better because it actually links the user input.

**Comment by liuxuan30** [comment]
if setVisibleXRangeMaximum not work, then a bug I guess, though I don't know why and how to fix. Sorry that you had a lot of info that I can't digest in a short time.
You can keep your solution, or try fix the real issue :)

**Comment by aastein** [comment]
It's not entirely a bug. Even if that feature worked as intended it would not present the desired behavior. 

If I pan on chart A, with chart A zoomed in, so that new data is shown I want the same type of "scrolling through the data" animation of charts B and C. 

With setVisibleXRangeMaximum working correctly, charts B and C would be reloaded with the correct data limits, but the scrolling or zooming animation wouldn't be present.

**Comment by danielgindi** [comment]
I think that with the current callbacks and methods - you could easily sync the viewports between charts...
