### ISSUE TITLE
Scrolling in a scroll view is blocked if the chart in the scroll view is not fully zoomed out. 

### ISSUE THREAD

**Issue by aastein** [danielgindi/Charts#1023]
Case 1 (expected) : View loads with the chart fully zoomed out, all data is displayed. In this case it is possible to scroll in any direction in the scroll view if the gesture was initiated over the chart. 

Case 2 (unexpected) : View loads with the chart fully zoomed out, all data is displayed. User pinch-zooms so only the x-axis is re-scaled. The y-axis remains "fully zoomed out". In this case it is not possible to scroll in any direction in the scroll view if the gesture was initiated over the chart. I would expect vertical scrolls in the scroll view to work, because with one finger on the chart, it is not possible to navigate up or down.

**Comment by liuxuan30** [comment]
I remember it's intended to be blocked in pan gesture recognizer
