### ISSUE TITLE
Error: "Assignment to readonly property" when updating charts data

### ISSUE THREAD

**Issue by fazal07** [danielgindi/Charts#1024]
set1 = (LineChartDataSet *)_chartView.data.dataSets[0];
set1.yVals = yVals; ("Assignment to readonly property")
_chartView.data.xValsObjc = xVals; ("Assignment to readonly property")
[_chartView notifyDataSetChanged];

I am using charts library in objective-c project via cocoa-pod

**Comment by liuxuan30** [comment]
```
    /// the array of y-values that this DataSet represents.
    public var yVals: [ChartDataEntry]
    {
        get
        {
            return _yVals
        }
        set
        {
            _yVals = newValue
            notifyDataSetChanged()
        }
    }
```
maybe clean and rebuild.

**Comment by fazal07** [comment]
@property (nonatomic, readonly, copy) NSArray<ChartDataEntry *> * _Nonnull yVals;
in charts-Swift.h

**Comment by danielgindi** [comment]
You are not using `master`, but the latest release. We will make a release soon.
Wrapping up some stuff...
