### ISSUE TITLE
Extend beyond values (feature request)

### ISSUE THREAD

**Issue by 128keaton** [danielgindi/Charts#1025]
![simulator screen shot may 12 2016 6 43 40 pm](https://cloud.githubusercontent.com/assets/1402918/15233856/82564a5c-1871-11e6-8b6e-b50135e9cf7d.png)
Is there anyway I can extend like above?

![newui-test strip](https://cloud.githubusercontent.com/assets/1402918/15237772/e3696926-1896-11e6-8316-09c2ee5a974c.png)

**Comment by liuxuan30** [comment]
the first question would be, what's your chart view's frame and contentRect.
You can disable yAxis.drawLabelsEnabled and try. Normally lien chart will stretch to the full width of contentRect, which is inside the chart view's frame.

**Comment by aastein** [comment]
Why not parameterize the equation, then add endpoints to your data set generated from the parameterized equation?

**Comment by 128keaton** [comment]
@aastein I'm not sure if it is data related, but I highly doubt that. If it ends up being a data issue, I'll take that into consideration

@liuxuan30 it appears that the frame is full size:
![screen shot 2016-05-12 at 10 17 17 pm](https://cloud.githubusercontent.com/assets/1402918/15236954/5453562c-188f-11e6-9d70-c2a71f850583.png)

I'll check the content rect

**Comment by aastein** [comment]
Are lines supposed to extend past the defined data points per the existing functionality? I don't have any problem extending lines to the edges of my views if I have data points defined at the edges. Is it that your x-axis limits extend to the edge of the view, but your data points lie within those limits?

If this is the case:
---------------------120=========================-==102---------------------
ViewEdge--------------------------------------------------------------------------ViewEdge
(xMin)------0-------1-----2------3------4------5------6------7------8-------9------(xMax)

Why not do:
dummyPoint==120============================102==dummyPoint
ViewEdge--------------------------------------------------------------------------ViewEdge
(xMin)------0-------1-----2------3------4------5------6------7------8-------9------(xMax)

**Comment by 128keaton** [comment]
@aastein hmm, I guess you are right. Maybe this should be a feature request. It would look a ton better if the fill and line extended beyond the point.

I took your suggestion, but the following makes the points disappear:
`self.insulinChart?.setVisibleXRange(minXRange: 0, maxXRange: self.view.frame.width)`

**Comment by aastein** [comment]
I believe you are using maxXRange incorrectly:

"Limits the maximum and minimum value count that can be visible by pinching and zooming. e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed at once without scrolling"

So youre setting the maximum amount of values that can be displayed equal to the view frame width. Pretty sure that's not right.

**Comment by 128keaton** [comment]
@aastein ah, I assumed, since it was a float value, it was not a count, but a scaling size.

**Comment by 128keaton** [comment]
I see that there is a layer fill option? Could I use this? (I couldn't figure out how)

**Comment by liuxuan30** [comment]
I don't see what feature is requested?
To me it seems like the minOffset is not 0. You can try. There is minOffset, extraLeftOffset, etc.

**Comment by 128keaton** [comment]
@liuxuan30 I've pretty much given up on this, and have taken the UI in a nicer direction. Thanks for this, maybe it will help someone else.

**Comment by liuxuan30** [comment]
you only need time and the debug skills, the library is too much to understand in a short time. Take your time!

**Comment by 128keaton** [comment]
@liuxuan30 I've rebuilt the UI to reflect something different. Not tinkering around with this library. Consumed my thoughts and time.

**Comment by danielgindi** [comment]
Actually any charting library is an overkill for your UI. If I had to implement what you've shown us in the screenshot, I wouldn't have bothered even looking for a charting library.
Just about 10 lines to draw these arrows and dashed line, and a few more for the gradiented bars.

**Comment by 128keaton** [comment]
@danielgindi don't make assumptions off of little information. This is a diabetes logging application, having graphs to show blood glucose and insulin doses are very informative.
