### ISSUE TITLE
Can't set text of Legend?

### ISSUE THREAD

**Issue by Maxcucurbit** [danielgindi/Charts#1027]
Only by this way:
 set1 = [[BarChartDataSet alloc] initWithYVals:yVals label:_legendText];
Have a better way to set text of legend？such as  chartView.legend.text = @“xxxx”.

**Comment by 128keaton** [comment]
@Maxcucurbit I don't think so. Why would setting that way cause an issue?
(`set1 = [[BarChartDataSet alloc] initWithYVals:yVals label:_legendText];`)

**Comment by Eflet** [comment]
You can use this:
`[chart.legend setExtraWithColors:@[UIColor.redColor] labels:@[@"testLegend"]`

**Comment by Maxcucurbit** [comment]
@Eflet  my bad, thanks
