### ISSUE TITLE
How to draw this bar Chart

### ISSUE THREAD

**Issue by anhltse03448** [danielgindi/Charts#1039]
I have an issue when draw this bar chart. It is very different when i search bar chart in google.
Can you help me :) 
Bar Chart in [http://postimg.org/image/nd2s7dimp/](url)

If can't load file, please copy and paste 
tks for help :)
@liuxuan30

**Comment by anhltse03448** [comment]
@danielgindi please help me :)

**Comment by danielgindi** [comment]
It's a candle-stick chart. You can choose to draw it with bars or with lines.

**Comment by anhltse03448** [comment]
I don't understand clearly. Please help me more :( @danielgindi

**Comment by danielgindi** [comment]
See the demo app.

**Comment by danielgindi** [comment]
See the demo app.

**Comment by anhltse03448** [comment]
I read demo but don't understand. Please help me for more detail info

**Comment by liuxuan30** [comment]
I can't see the picture: 404

What you don't understand? As Daniel has pointed out a candle-stick chart

**Comment by anhltse03448** [comment]
Tks for your help. I solved this issue :)
