### ISSUE TITLE
Enhancement: Horizontal Combined Chart

### ISSUE THREAD

**Issue by Robarelli** [danielgindi/Charts#1041]
Use case: we have data on a bunch of snow layers at a given site and have measured the depth and thickness of each layer. We also measure temperatures at variable depth levels. See an example [here](http://www.sierraavalanchecenter.org/sites/default/files/2013-12-09-rubicon.jpg) (disregard the data to the right of the chart). As seen in the example, the chart needs to be horizontal to visualize depth and the bars need to be touching and have variable height to represent thickness of the layer as it goes deeper.

I understand this is a unique case, but would this be possible with Charts in it's current state or in a future release? Can it be extended to achieve such functionality? If not, do you know of any packages that may contain this sort of functionality?

Thanks in advance

**Comment by liuxuan30** [comment]
I think it is absolutely possible based on the current arch, as long as you know how it works, and you can write your own then.

**Comment by SvenMuc** [comment]
I'm strugeling currently with the same issue. Do we need a new class like CombinedHorizontalChart? Or is it already possible with the current implementation? The CombinedChart displays the graphs just in vertical direction aus far aus I understood the implementation.

**Comment by liuxuan30** [comment]
seems not. A combined chart while x and y are both switched.
