### ISSUE TITLE
Changing the size of the interception (dots) font in Line Chart ?

### ISSUE THREAD

**Issue by YHSX88** [danielgindi/Charts#1043]
![screen shot 2016-05-16 at 23 34 41](https://cloud.githubusercontent.com/assets/16823745/15303235/5bd651fa-1bbf-11e6-8ebf-9b21f7d4d583.png)
Hi Guys 

I searched and I could not find which is the property to set the font size in line Chart for the Intercepted Dots values ?

please help 

Thanks in advance

**Comment by Maxcucurbit** [comment]
BalloonMarker *marker = [[BalloonMarker alloc] initWithColor:[UIColor colorWithWhite:180/255. alpha:1.0] font:[UIFont systemFontOfSize:12.0] insets: UIEdgeInsetsMake(8.0, 8.0, 20.0, 8.0)];
   
 marker.font = [UIFont systemFontOfSize:22];

**Comment by YHSX88** [comment]
Hi Maxcucurbit

I created the class "BalloonMarker.swift"

then I initialized by writing: 
`let daFont = UIFont(name: "Monaco", size: 12)`
` let bMarker = BalloonMarker(color: UIColor.greenColor(), font: daFont!, insets: UIEdgeInsets(top: 8.0, left: 8.0, bottom: 20.0, right: 8.0))`
And finally I'm assigning the marker.
` lineChart.marker = bMarker`
I and I'm getting error:
**fatal error: unexpectedly found nil while unwrapping an Optional value**
(lldb) 

If you can guide me what is wrong it will be great if not I thank you

**Comment by danielgindi** [comment]
If you are talking about the value text in the chart - not the marker - then it is probably `valueFont` you are looking for.

**Comment by YHSX88** [comment]
That was it thank you

**Comment by danielgindi** [comment]
You're welcome! :-)
