### ISSUE TITLE
How to achieve this effect

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1044]
![60444b52-2824-464b-a1db-df65d5ff97f3](https://cloud.githubusercontent.com/assets/13211527/15315051/0188ef26-1c48-11e6-8a62-02ee270c2f20.png)

**Comment by liuxuan30** [comment]
stacked bar chart already support the colors and value text. However I don't understand how the top value text is calculated. Anyway, you can override `drawValues` to do so

**Comment by shenyufei** [comment]
How to use this stacked bar chart, why I did not find? In the charts there? @liuxuan30
