### ISSUE TITLE
How to draw OHLC chart ( Open high low close ) ?

### ISSUE THREAD

**Issue by anhltse03448** [danielgindi/Charts#1045]
I want to draw OHLC chart. But I don't know how to draw this chart by ios-chart.  Please help me to solve this problems
@danielgindi

**Comment by danielgindi** [comment]
See demo app. Please don't tag me for nothing.

**Comment by anhltse03448** [comment]
Please help me for more detail info. I don't know how to draw OHLC chart.

**Comment by danielgindi** [comment]
"See demo app"
