### ISSUE TITLE
Marker out of view

### ISSUE THREAD

**Issue by blmyself** [danielgindi/Charts#1046]
![qq20160517-0](https://cloud.githubusercontent.com/assets/914295/15317489/4ee8b862-1c54-11e6-992b-9ee3cd09a43d.png)
I try to adjust the marker offset property, but it is doesn't work.
The rotated xAxis label is also out of the view.
Anybody know how to fix it?

**Comment by liuxuan30** [comment]
This is a legend more than a marker. Anyway, you should take a look at how marker rect is calculated.

**Comment by danielgindi** [comment]
It's a legend in a marker :-)

**Comment by danielgindi** [comment]
You are using the BalloonMarker from the demo, which had an oversight of not looking at offset. I will push a fix to this, but you will need to update your marker's code.

**Comment by blmyself** [comment]
The rotated xAxis label is also out of the view?

**Comment by avityagi5** [comment]
It seems that it is still replicating.
The marker is clipping from left and right.

**Comment by shinurag** [comment]
I have made some changes for solving this issue, Please have a look

`
public class BalloonMarker: ChartMarker
{
    public var color: UIColor?
    public var arrowSize = CGSize(width: 15, height: 11)
    public var font: UIFont?
    public var insets = UIEdgeInsets()
    public var minimumSize = CGSize()
    public var chartViewSize = CGSize()
    
    private var labelns: NSString?
    private var _labelSize: CGSize = CGSize()
    private var _size: CGSize = CGSize()
    private var _paragraphStyle: NSMutableParagraphStyle?
    private var _drawAttributes = [String : AnyObject]()
    
    public init(color: UIColor, font: UIFont, insets: UIEdgeInsets)
    {
        super.init()
        
        self.color = color
        self.font = font
        self.insets = insets
        
        _paragraphStyle = NSParagraphStyle.defaultParagraphStyle().mutableCopy() as? NSMutableParagraphStyle
        _paragraphStyle?.alignment = .Center
    }
    
    public override var size: CGSize { return _size; }
    
    public override func draw(context context: CGContext, point: CGPoint)
    {
        if (labelns == nil)
        {
            return
        }
        
        //var rect = CGRect(origin: point, size: _size)
        let offset = self.offsetForDrawingAtPos(point)
        var rect = CGRect(
                        origin: CGPoint(
                            x: point.x + offset.x,
                            y: point.y + offset.y),
                        size: _size)
        
        rect.origin.x -= _size.width / 2.0
        rect.origin.y -= _size.height
        
        let balloonEnd = (point.x + offset.x) + rect.size.width
        var setArrowPosition = CGFloat(0.0)
        
        if balloonEnd > chartViewSize.width
        {
            rect.origin.x -= (balloonEnd - chartViewSize.width)
            setArrowPosition = (balloonEnd - chartViewSize.width)
        }
        else if rect.origin.x < 0
        {
            setArrowPosition = rect.origin.x
            rect.origin.x = 0
        }

        CGContextSaveGState(context)
        
        CGContextSetFillColorWithColor(context, (color?.CGColor)!)
        CGContextBeginPath(context)
        
        CGContextMoveToPoint(context,
            rect.origin.x,
            rect.origin.y)
        
        CGContextAddLineToPoint(context,
            rect.origin.x + rect.size.width,
            rect.origin.y)
        
        CGContextAddLineToPoint(context,
            rect.origin.x + rect.size.width,
            rect.origin.y + rect.size.height - arrowSize.height)
        
        CGContextAddLineToPoint(context,
            rect.origin.x + setArrowPosition + (rect.size.width + arrowSize.width) / 2.0,
            rect.origin.y + rect.size.height - arrowSize.height)
        
        CGContextAddLineToPoint(context,
            (rect.origin.x) + setArrowPosition + rect.size.width / 2.0,
            rect.origin.y + rect.size.height)
        
        CGContextAddLineToPoint(context,
            (rect.origin.x + setArrowPosition) + (rect.size.width - arrowSize.width) / 2.0,
            rect.origin.y + rect.size.height - arrowSize.height)
        
        CGContextAddLineToPoint(context,
            rect.origin.x,
            rect.origin.y + rect.size.height - arrowSize.height)
        
        CGContextAddLineToPoint(context,
            rect.origin.x,
            rect.origin.y)
        CGContextFillPath(context)
        
        rect.origin.y += self.insets.top
        rect.size.height -= self.insets.top + self.insets.bottom
        
        
        UIGraphicsPushContext(context)
        
        labelns?.drawInRect(rect, withAttributes: _drawAttributes)
        
        UIGraphicsPopContext()
        
        CGContextRestoreGState(context)
    }
    
    public override func refreshContent(entry entry: ChartDataEntry, highlight: ChartHighlight)
    {
        let label = (entry.valueLabel.isEmpty) ? entry.value.description : entry.valueLabel
        labelns = label as NSString
        
        _drawAttributes.removeAll()
        _drawAttributes[NSFontAttributeName] = self.font
        _drawAttributes[NSParagraphStyleAttributeName] = _paragraphStyle
        
        _labelSize = labelns?.sizeWithAttributes(_drawAttributes) ?? CGSizeZero
        _size.width = _labelSize.width + self.insets.left + self.insets.right
        _size.height = _labelSize.height + self.insets.top + self.insets.bottom
        _size.width = max(minimumSize.width, _size.width)
        _size.height = max(minimumSize.height, _size.height)
    }

`

This class object will be access like this.

`    BalloonMarker *marker = [[BalloonMarker alloc] initWithColor:[UIColor lightGrayColor] font:[UIFont systemFontOfSize:10.0] insets: UIEdgeInsetsMake(2.0, 2.0, 10.0, 2.0)];
    marker.minimumSize = CGSizeMake(60.f, 30.f);
    marker.chartViewSize = CGSizeMake(_chartView.frame.size.width, _chartView.frame.size.height);
    _chartView.marker = marker;
`
