### ISSUE TITLE
Issues with y axis values

### ISSUE THREAD

**Issue by neerajcsa** [danielgindi/Charts#1047]
Y axis values are displaying in different format, sometimes in Integer and sometimes in double though i have provided all the dataset in double format.
Please see the attachments.
![simulator screen shot may 17 2016 3 08 23 pm](https://cloud.githubusercontent.com/assets/7921708/15318102/1b8e0150-1c42-11e6-96cb-0cab3e1d3eae.png)
![simulator screen shot may 17 2016 3 08 25 pm](https://cloud.githubusercontent.com/assets/7921708/15318105/1c69b20e-1c42-11e6-88a7-8b2202d482b6.png)

**Comment by danielgindi** [comment]
The value you pass in is **always** double. It's just how it formats it that changes. You can see the demos to learn how to pass in custom formatters, or configure the default formatters. For example you can choose how many decimal places to show etc.

**Comment by neerajcsa** [comment]
@danielgindi : As u can can see above in screenshots, values are double and integer both even though i haven't change value formatter and also i passed double values for all the x values.

**Comment by danielgindi** [comment]
These are not integers, these are Doubles.

**Comment by neerajcsa** [comment]
Then why it is showing without decimal value even though i haven't change the formatter.

**Comment by liuxuan30** [comment]
@neerajcsa it's much easier to find out what's the formatter is on your side. You should check the NSNumberFormatter properties first, for instance, `minimumFractionDigits`
