### ISSUE TITLE
Overlapping issues in x and y axis values

### ISSUE THREAD

**Issue by neerajcsa** [danielgindi/Charts#1048]
I am facing overlapping issue in x and y axis values.
Please see the screenshots which i have attached.
![simulator screen shot may 17 2016 7 35 01 pm](https://cloud.githubusercontent.com/assets/7921708/15325393/e11575be-1c67-11e6-934c-8644dfe4a78a.png)

**Comment by liuxuan30** [comment]
seems a known issue.

**Comment by neerajcsa** [comment]
@danielgindi  : could u help me in this also?

**Comment by hardikdevios** [comment]
i guess its very tough to check whether its overlapping or not in case of `Linechart` .
So my workaround is for this to hide the first label, at least it will look cleaner for now.

**Comment by liuxuan30** [comment]
overlapping seems not avoidable, if we insist to display them, expecially center aligned. Something we can do is like add a white background so it will cover the axis label.

**Comment by alexrmacleod** [comment]
@hardikdevios Please tell me how you hid the first label. for some reason I can't figure it out. thx

**Comment by liuxuan30** [comment]
@alexrmacleod I guess he just find the `drawValues`'s main loop, and filt the first entry e.g. i == 0

**Comment by dawangjiaowolaixunshan** [comment]
16M . 8M   how do you make it out ...?  ... can you tell me ..

**Comment by neerajcsa** [comment]
@dawangjiaowolaixunshan : Use this...

//Format number into K,M,B
-(NSString *)abbreviateNumber:(double)number {
    
    NSString *abbrevNum;
    
    //Prevent numbers smaller than 1000 to return NULL
    if (number >= 1000) {
        NSArray *abbrev = @[@"K",@"M", @"B",@"T"];
        
        for (NSInteger i = abbrev.count - 1; i >= 0; i--) {
            
            // Convert array index to "1000", "1000000", etc
            NSInteger size = pow(10,(i+1)*3);
            
            if(size <= round(number)) {
                // Removed the round and dec to make sure small numbers are included like: 1.1K instead of 1K
                number = number/size;
                NSString *numberString = [self doubleToString:number];
                
                // Add the letter for the abbreviation
                abbrevNum = [NSString stringWithFormat:@"%@%@", numberString, [abbrev objectAtIndex:i]];
            }
            
        }
    } else {
        
        // Numbers like: 999 returns 999 instead of NULL
        abbrevNum = [NSString stringWithFormat:@"%lld", (long long)number];
    }
    
    return abbrevNum;
}

- (NSString *) doubleToString:(double) val {
    NSString *ret = [NSString stringWithFormat:@"%.2f", val];
    unichar c = [ret characterAtIndex:[ret length] - 1];
    
    while (c == 48) { // 0
        ret = [ret substringToIndex:[ret length] - 1];
        c = [ret characterAtIndex:[ret length] - 1];
        
        //After finding the "." we know that everything left is the decimal number, so get a substring excluding the "."
        if(c == 46) { // .
            ret = [ret substringToIndex:[ret length] - 1];
        }
    }
    
    return ret;
}

**Comment by chenjhg** [comment]
@neerajcsa ,i face a problem ,custom x and y axis values ,did you slove it ,expect you reply
