### ISSUE TITLE
Without drawLimitLinesBehindDataEnabled, limit lines go outside chart area

### ISSUE THREAD

**Issue by iangmaia** [danielgindi/Charts#1052]
I noticed that, with drawLimitLinesBehindDataEnabled set to false (default), the limit line I have on a right axis will go outside the chart area (only vertically):
![simulator screen shot 18 may 2016 15 18 55](https://cloud.githubusercontent.com/assets/2152244/15360373/9cd21758-1d0d-11e6-85f6-33b329d5b902.png)

If I set it to true, it behaves correctly and there's no issue, but then the line is below the candle sticks (obviously -- I guess that what's the flag is about), which is a behaviour I don't necessarily want.

**Comment by liuxuan30** [comment]
I'm not sure if it's a bug, but the chart limit line is not clipped in your case... and your limit line value is lower than the min y. @danielgindi what you think

**Comment by iangmaia** [comment]
The limit line should be clipped if the value is lower than minY I think, this was the behaviour a couple of versions ago.

**Comment by liuxuan30** [comment]
well, in the code, if you turn on it, it is drawing without clipping. You can change it to achieve your purpose. I'm not sure why it is implemented such way but it should have reasons
