### ISSUE TITLE
Is there a way to get a different background colour for different values of the x axis?

### ISSUE THREAD

**Issue by gregveres** [danielgindi/Charts#1053]
Hi,

I have looked through the docs but can't find anything like this. I am looking to highlight certain parts of the graph. I have a line graph that uses dates for the X axis. I would like to have a few date ranges highlighted as being important. 

For instance, if the date range was a month, could I have the background colour of the weekends different than the back ground colour of the weekdays? 

I was thinking that maybe the way to attack this is to have a line chart and a bar chart super-imposed on the same X axis. The bar chart could have values of 0 for the days I don't want highlighted and values of "other data set max Y" for the days that I do want highlighted.

any suggestions? 

thanks
Greg

**Comment by liuxuan30** [comment]
should be a dup to https://github.com/danielgindi/Charts/issues/645? There is a similar solution, but not implemented officially I remember

**Comment by liuxuan30** [comment]
also you can check https://github.com/danielgindi/Charts/issues/701, though it's the other direction

**Comment by gregveres** [comment]
Thank you. I will check out that solution tomorrow.
