### ISSUE TITLE
Cant understand  .axisMaxValue

### ISSUE THREAD

**Issue by ADevelopStudio** [danielgindi/Charts#1054]
Wanted to put percentage limits of 100% to graph to show values more obvious.  
because, for instance, if value of 6% is the max in this data, it  looks like 99% ( I mean it fills whole bar, not just small part of it)
form demo example of BarChart: 
```
   ChartYAxis *leftAxis = _chartView.leftAxis;
    leftAxis.axisMaxValue = 100.0;
```
it working fine! however on my own code (Swift) it is not working at all...
```
        let leftAxis = barChartView.leftAxis
        leftAxis.axisMaxValue = 100.0
```
Which is strange because the one:
```
  leftAxis.axisMinValue = 0.0;
```
is working...
May be I do not understand something...
<img width="382" alt="screen shot 2016-05-20 at 14 38 08" src="https://cloud.githubusercontent.com/assets/5238454/15417377/836c9f04-1e98-11e6-9730-5931eae4e58c.png">

**Comment by danielgindi** [comment]
Maybe your values are not percentages? Just the formatter is showing the percentage?

**Comment by ADevelopStudio** [comment]
chartData.getYMax() returns "5.56"
SO I tried both 
        leftAxis.axisMaxValue = 1
        leftAxis.axisMaxValue = 100
result is the same

**Comment by danielgindi** [comment]
Check which y axis is your data dependent on. Also maybe you should just disable the right y axis?

**Comment by ADevelopStudio** [comment]
To be honest not 100% sure that did you mean. 
I tried to disable each of them separately and together. but can't see any difference.
If I use 
        rightAxis.drawAxisLineEnabled = true
        rightAxis.drawGridLinesEnabled = true
or 
        leftAxis.drawAxisLineEnabled = true
        leftAxis.drawGridLinesEnabled = true
I see values on every side - so can't understand 

> Check which y axis is your data dependent on

**Comment by danielgindi** [comment]
Check the first line chart demo and the dual-axis one.
You can have different y-axis range on the right axis. And if your dataset depends on the left-axis, and the left-axis is the one that should be configured for this.

**Comment by danielgindi** [comment]
Basically setting `axisMaxValue` on the correct axis should do the trick. You just have to find out which axis that is :-)
