### ISSUE TITLE
Pie Chart label position

### ISSUE THREAD

**Issue by ashish1703** [danielgindi/Charts#1055]
Hi everyone,

is there a way to achieve what is been displayed in the following link:
https://www.shinobicontrols.com/blog/pie-chart-labels-that-are-out-of-this-slice

Any help in this regard would be kind.

Thanks

**Comment by danielgindi** [comment]
Yes, see the demo.

**Comment by ashish1703** [comment]
The demo is with 'Shinobi Charts' no?, i want to work this out with 'IOS Charts' library.
Please share any implementation example with IOS Charts library.

Thanks
