### ISSUE TITLE
How can I remove the gap between the bar

### ISSUE THREAD

**Issue by kyo313** [danielgindi/Charts#1056]
![8a252e21-f9f8-4235-8cf8-55c47c88bf12](https://cloud.githubusercontent.com/assets/3380876/15428366/89401160-1ecd-11e6-926a-4fd1784d5eb6.jpg)
but I want the chart like follow,how can I remove the gap between the bar
![fa8f006d-d9c8-41d5-8925-7ff70054a9dc](https://cloud.githubusercontent.com/assets/3380876/15428410/c9823244-1ecd-11e6-9222-65d2447805d9.jpg)

**Comment by danielgindi** [comment]
Duplicate https://github.com/danielgindi/Charts/issues/666
