### ISSUE TITLE
After upgrading to Xcode 7.3.1, getting bridging issue

### ISSUE THREAD

**Issue by hth** [danielgindi/Charts#1057]
After upgrading to `Xcode 7.3.1` getting bridging issue on `2.2.4` release. Migrated from `2.2.2` and `Xcode 7.3.0`

       /../../ProjectName-Bridging-Header.h:6:9: error: 'Charts/Charts-Swift.h' file not found
       #import <Charts/Charts-Swift.h>
                ^
       <unknown>:0: error: failed to import bridging header '/../../ProjectName-Bridging-Header.h'

Is anybody noticing similar issue?

**Comment by danielgindi** [comment]
Seems like an Xcode bug.

Try to remove the Charts project from your project and re-add it, to force Xcode to refresh whatever it is that's broken.
