### ISSUE TITLE
Very odd line at top of graph

### ISSUE THREAD

**Issue by 128keaton** [danielgindi/Charts#1058]
![screen shot 2016-05-20 at 4 34 09 pm](https://cloud.githubusercontent.com/assets/1402918/15442774/c56855a0-1ea8-11e6-8167-a16efd7395af.png)
Something I noticed recently. drawBorders = false
Any ideas as to what it is? 

![screen shot 2016-05-20 at 4 35 17 pm](https://cloud.githubusercontent.com/assets/1402918/15442788/dad9f93e-1ea8-11e6-8e58-14a964495e2a.png)

**Comment by danielgindi** [comment]
Maybe the "zero line", maybe the grid... You can just disable everything, or disable one by one and debug.
