### ISSUE TITLE
Realm.io Horizontal combine bar chart - iOS

### ISSUE THREAD

**Issue by yazh-rym** [danielgindi/Charts#1062]
In swift there is no **Horizontal combine bar chart** code. I don't know how to do it in swift. Moreover it won't work as like objective c code. Please help me.

![screen shot 2016-05-23 at 7 11 44 pm](https://cloud.githubusercontent.com/assets/17271560/15472694/189ed0e6-211a-11e6-9af6-cd24c99e3196.png)

**Comment by danielgindi** [comment]
It's not about Swift or ObjC, it just that currently CombinedChart does not support horizontal bar chart, as it makes no sense - it's on a different axis.
It's like combining Pie chart with Combined chart
