### ISSUE TITLE
LineChart set a great amount data to LineChartDataSet, cpu increase highly to 97%

### ISSUE THREAD

**Issue by dogvscat** [danielgindi/Charts#1063]
`var yVals = [ChartDataEntry]()
        for yIndex in 0..<count {
            yVals.append(ChartDataEntry(value: Double(value[yIndex]), xIndex: yIndex))
        }
  
let lineChartDataSet = LineChartDataSet(yVals: yVals, label: "Audio Wave")
        lineChartDataSet.drawCubicEnabled = true
        lineChartDataSet.cubicIntensity = 0.2
        lineChartDataSet.drawCirclesEnabled = false
        lineChartDataSet.lineWidth = 1.8
        lineChartDataSet.circleRadius = 4.0
        lineChartDataSet.circleColors = [UIColor.whiteColor()]
        lineChartDataSet.colors = [UIColor.greenColor()];
        lineChartDataSet.fillColor = UIColor.whiteColor();
        lineChartDataSet.fillAlpha = 1.0;
        lineChartDataSet.drawHorizontalHighlightIndicatorEnabled = false
        lineChartDataSet.drawVerticalHighlightIndicatorEnabled = true
        lineChartDataSet.highlightColor = UIColor.whiteColor()
        lineChartDataSet.highlightLineWidth = 2.0
        
        let lineChartData = LineChartData(xVals: xVals, dataSet: lineChartDataSet)

`
and count may be a great number.while i setLineData,the cpu and memeory rise up highly

**Comment by danielgindi** [comment]
Currently CoreGraphics is rendering over the CPU instead of the GPU. This is slow.
I hope to create a simple 2D drawing layer over GPU, but there's no ETA for that...
#29

**Comment by dogvscat** [comment]
1.  "huge numbers of datapoints (10K or more)" - we are working on it :) I can't say about Android, as moving it to GL will be an even bigger PITA, but it is already having pretty good performance by leveraging the hardware layer, which is doing all drawing on the GPU.  so when will you move it to GL?

2. as dorsoft said "I've managed to make a candle stick chart with 10k data points pan/zoom smoothly. by changing CandleStickChartRenderer.swift, line 76,77 from:
var minx = max(dataSet.entryIndex(entry: entryFrom, isEqual: true), 0);
var maxx = min(dataSet.entryIndex(entry: entryTo, isEqual: true) + 1, entries.count);
to
var minx = max(_minX, 0);
var maxx = _maxX + 1;"
i modify this in linechart, but it seems to be no effect on cpu or memory. 

3. limit scale and only show a certain number of datapoints at a time.
  i have set the `maxVisibleValueCount` to 20, and drawValues to be true,but it also does not work. Any idea ?

**Comment by liuxuan30** [comment]
Towards second one, have you checked `dataSet.entryIndex(entry: entryFrom, isEqual: true)`'s time complexity? I am on a windows machine now so I can't see it. If it's O(1), then the change should not impact the performance.

**Comment by dogvscat** [comment]
@liuxuan30  i haven't tested it, and now i still don't know how to solve my problem. Android uses idea of point 3 to solve this problem. so i wonder how to use this properly with iOS? @danielgindi

**Comment by woolfel** [comment]
Has anyone else found a work around for rendering charts with more than 10K datapoints? I can render charts with 1-3K datapoints fine, but more than that it's very slow. With more than 36K datapoints, it never responds. thanks.

**Comment by liuxuan30** [comment]
36K? Jesus, what's the screen size.. I do think performance is issue, but right now you could use 3.6K or 360 to render..?

**Comment by woolfel** [comment]
I know it's a bit excessive. It's accelerometer and gyroscope data recorded by the phone. I've thought of a few work arounds, but wanted to see what other solutions people have tried. The most obvious is to only show 1000 datapoints and use swipe gesture to scroll through the dataset.

**Comment by danielgindi** [comment]
CoreGraphics cannot handle 36K of datapoints. We may use a different rendering engine to solve that- but you still need to use less datapoints.

There's no user who can make use of this amount of data in a chart.

You need to approximate the data, like GitHub does on their statistic charts on the site.

**Comment by woolfel** [comment]
thanks for taking time to respond. I thought about averaging, smoothing or other ways of approximating the data. I was curious to see what others have tried with crazy large datasets. thanks

**Comment by danielgindi** [comment]
Well one way or another- approximating is the way to go.
Think about it this way: How will 36,000 points will look on a 400-500 px wide screen?
The answer is- it will look like 400-500 points.

Take a look at the DataApproximator in Charts.
It is actually implemented better in v3, where there are real x values.

**Comment by woolfel** [comment]
thanks, I will take a look at DataApproximator.

**Comment by woolfel** [comment]
I just clone the latest version and didn't see an example using DataApproximator. If there isn't one, I'm happy write a sample and make a pull request. Thanks

**Comment by danielgindi** [comment]
There isn't one, you are welcome to create one!
בתאריך שבת, 13 באוג׳ 2016 ב-14:43 מאת Peter Lin <notifications@github.com>:

**Comment by UnAmico0** [comment]
> thanks, I will take a look at DataApproximator.

have you  save the problem?

**Comment by UnAmico0** [comment]
> thanks, I will take a look at DataApproximator.

Have you solved this problem?

**Comment by goors** [comment]
Same here 5000 points ... cpu 100%
