### ISSUE TITLE
carthage compatibility

### ISSUE THREAD

**Issue by hibento** [danielgindi/Charts#1064]
Hi there,

had anyone tried to use carthage with the latest Release or Master-Commit?

Using the latest Release with the following cartfile `github "danielgindi/Charts" ">= 2.2.4"` downloads only the Charts.zip - missing the ChartsRealm.zip. Therefore there's no build possible using Xcode.

Trying to build both Frameworks from Scratch with a cartfile `github "danielgindi/Charts" "master"` produces the following errors:

    *** Building scheme "Charts-iOS" in Charts.xcodeproj
    *** Building scheme "ChartsRealm-iOS" in ChartsRealm.xcodeproj
    ** BUILD FAILED **

     The following build commands failed:
	Ld /Users/hibento/Library/Developer/Xcode/DerivedData/ChartsRealm-enpgindewbfzssctelkxhkdhnmis/Build/Intermediates/Charts.build/Release-iphonesimulator/Charts-OSX.build/Objects-normal/x86_64/Charts normal x86_64
	Ld /Users/hibento/Library/Developer/Xcode/DerivedData/ChartsRealm-enpgindewbfzssctelkxhkdhnmis/Build/Intermediates/Charts.build/Release-iphonesimulator/Charts-OSX.build/Objects-normal/i386/Charts normal i386
    (2 failures)
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    A shell task (/usr/bin/xcrun xcodebuild -project /Users/hibento/Repositories/myApp/Carthage/Checkouts/Charts/ChartsRealm/ChartsRealm.xcodeproj -scheme ChartsRealm-iOS -configuration Release -sdk iphonesimulator -destination platform=iOS Simulator,id=78CDC99B-81C9-412D-8A43-7B32A76360CA -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
    ** BUILD FAILED **

     The following build commands failed:
	Ld /Users/hibento/Library/Developer/Xcode/DerivedData/ChartsRealm-enpgindewbfzssctelkxhkdhnmis/Build/Intermediates/Charts.build/Release-iphonesimulator/Charts-OSX.build/Objects-normal/x86_64/Charts normal x86_64
	Ld /Users/hibento/Library/Developer/Xcode/DerivedData/ChartsRealm-enpgindewbfzssctelkxhkdhnmis/Build/Intermediates/Charts.build/Release-iphonesimulator/Charts-OSX.build/Objects-normal/i386/Charts normal i386
    (2 failures)

I wiped the Carthage Folder (including its cache) and deleted all derived data folders from Xcode - nothing changes. 

Has anyone tried the latest release or commit with carthage?

**Comment by petester42** [comment]
What happens if you use the `--no-use-binaries` option?

**Comment by hibento** [comment]
That´s weird - I tried this several times (like in #874) proposed - didn't work. Now I tried it again and it worked perfectly. Carthage at it´s best...

@petester42 Thank you.

**Comment by petester42** [comment]
Ya Carthage is sometimes a little bit finicky. I was using it for a while but switched back to cocoapods because it was less trouble.
