### ISSUE TITLE
The rotated xAxis label out of the view

### ISSUE THREAD

**Issue by blmyself** [danielgindi/Charts#1068]
![qq20160524-0](https://cloud.githubusercontent.com/assets/914295/15501695/6d5a4378-21e1-11e6-9bb7-9407509f1148.png)
The last label in xAxis out of the linechartview. How to fix it?  Thanks a lot.

**Comment by Xwoder** [comment]
chartView.xAxis.avoidFirstLastClippingEnabled = YES;

**Comment by liuxuan30** [comment]
hmm, if you don't rotate it, it will be clipped too. You can try avoidFistLastClipped (search, I don't remeber it very clear)
