### ISSUE TITLE
Real-time Charts

### ISSUE THREAD

**Issue by elavarasanFluke** [danielgindi/Charts#1069]
Is it possible to create a LineChart that is continuously updated as data is loaded every 5 seconds, with the chart smoothly scrolling to the left as new data points are plotted? And when user scrolls back the line chat should load the previous data. 

Is there any other way other that adding and removing the dataset?

**Comment by danielgindi** [comment]
You do not have to add/remove the dataset, there are methods for adding single entries. And methods for scrolling with animation etc.
There are some issues out there about this, please use "Search"...
