### ISSUE TITLE
Changing size of centre section - pie chart

### ISSUE THREAD

**Issue by dwinnbrown** [danielgindi/Charts#1071]
I'm using your great library for a pie chart in my current project but have found that the text is not completely covering the 'pie' section. Is there anyway I can adjust the size of the central section of the piechart or make the text fit on to the 'pie' section?

Thanks

**Comment by danielgindi** [comment]
Yes, you can look into the setup code for the pie chart in the demo.
Basically there's a `holeRadiusPercent` property, controlling how much of the pie is used for the "hole" in the middle of the pie.

**Comment by dwinnbrown** [comment]
Thanks for the reply! That’s just what I was looking for. Out of interest is there a property to adjust the diameter of the inner radius that is tinted? Now that I have reduced the hole in the middle, the white tint has increased quite a bit.

Thanks

**Comment by dwinnbrown** [comment]
Sorry i just found the:
pieChartView.transparentCircleRadiusPercent
property!
