### ISSUE TITLE
CodeSign for "Framework" in SDK "iOS 9.3"

### ISSUE THREAD

**Issue by shhejianjian** [danielgindi/Charts#1072]
when i run this project to my iphone, one error says:"CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.3'".
i don't know how to solve it,who can help me?thank you.

**Comment by danielgindi** [comment]
Select your codesigning certificate in project settings

**Comment by cnzlh** [comment]
![image](https://cloud.githubusercontent.com/assets/5771860/18430006/2a10d788-7909-11e6-830b-41b83fa0d8aa.png)
![image](https://cloud.githubusercontent.com/assets/5771860/18430036/52acd85e-7909-11e6-8a2e-18a7ea77389f.png)
why not work?
