### ISSUE TITLE
automatically calculated labels with a custom roof (axisMaxValue only if exceeding it)

### ISSUE THREAD

**Issue by everlof** [danielgindi/Charts#1074]
Is there any way to use "automatically calculated" axis values, but limit the maximum to a number?

For example if Im plotting percentage. If I have 30%, 35%, 35%, I want it to calculate the axis values automatically, maybe max 45% and min 20%, perhaps.

But if I have, 80%, 95%, 95%, I want maybe 70% as min and 100% as max, since it doesnt make sense to use higher than 100%.

Is there any way to get a combination of these two?

**Comment by danielgindi** [comment]
```
if axisMaxValue > 100.0 && !isAxisMaxCustom
{
  axisMaxValue = 100.0
}
```
