### ISSUE TITLE
Sync zoom in 2 chart

### ISSUE THREAD

**Issue by anhltse03448** [danielgindi/Charts#1078]
I draw 2 chart in 2 UIView on 1 ViewController. 
When I zoom in above chart, i want to second Chart zoom too. 
I am using function zoom but I don't know position to zoom (only know scale X and scale Y).
Some one help me plz :)

**Comment by anhltse03448** [comment]
@liuxuan30  please help me bro :)

**Comment by anhltse03448** [comment]
@liuxuan30  help me please :)

**Comment by anhltse03448** [comment]
@danielgindi  please help me :)

**Comment by liuxuan30** [comment]
hey @anhltse03448, don' abuse using "@". Someone will help answer questions if possible, but don't do things like this :)

If you want to sync in 2 charts, you should take a look at ChartTransformer and ChartViewPortHandler for some API support. Also, there are people asking such issues several times, you can serach them in old issues.

About zoom, you have to get some knowledge how it works and then you will know how to do it in code.
