### ISSUE TITLE
set the Y range 

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#1079]
i want the minimum and maximum values to be exactly the start and the begining of the y range. 
i need it to fixed every time. how can i do it?

**Comment by orensha** [comment]
Hi, that's the closest thing i could find at least by the name of the method. it doesn't work. is there any way of doing this? 

for example CorePlot has this line:

plotSpace.yRange = [CPTPlotRange plotRangeWithLocation:CPTDecimalFromFloat(minValue)
                                                        length:CPTDecimalFromFloat(_yLength)];

**Comment by danielgindi** [comment]
To limit the y range - you can use axisMinValue/axisMaxValue.
If you do not limit it - it will automatically be the min/max values of your y axis.
So I don't see where the problem lies...

**Comment by orensha** [comment]
i needed to transform the actual value to the container frame point. thats why i needed it to be fixed. but i found that you enabled it with "getPixelForValue". thanks.
