### ISSUE TITLE
Chart Demo not Compiling

### ISSUE THREAD

**Issue by chandraf22** [danielgindi/Charts#1083]
Hi, I just dowloaded the charts framework. I was trying to run the charts demo objective c project to check it out, but it is showing too many error in the charts project swift files. 

common ones are shown for selectors in function calls, _eg: line 73 in AnimatedViewPort.swift. The xcode is asking to for Expected , and other expressions here._

my xcode swift details are :

_**Apple Swift version 2.1.1 (swiftlang-700.1.101.15 clang-700.1.81)
Target: x86_64-apple-darwin14.5.0**_

Please help, this seems to be a nice framework, i would definitely like to use it!

**Comment by petester42** [comment]
Update to the latest Xcode.

**Comment by chandraf22** [comment]
Thanks, It works fine now!

On Fri, May 27, 2016 at 8:48 PM, Pierre-Marc Airoldi <
notifications@github.com> wrote:

> Update to the latest Xcode.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/danielgindi/Charts/issues/1083#issuecomment-222174372>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMTDpNHTwyyRkbmoyWQjlQKCyM7iGGosks5qFwtGgaJpZM4IoQMz>
> .
>



-- 
Regards

Chandrachudh.K
Mob: 09789895724
