### ISSUE TITLE
Pie Chart : Multiline label on legend is cutting off

### ISSUE THREAD

**Issue by ram2386** [danielgindi/Charts#1084]
Your library is very very helpful for drawing the chart, thanks for sharing it. I am getting the issue when display the legend of Pie Chart at the bottom of the screen which cut if it is more than two line. For more information please find the below screenshot for the same. 

![simulator screen shot 27-may-2016 7 38 08 pm](https://cloud.githubusercontent.com/assets/217577/15610983/c5ac8e9e-2445-11e6-95c5-6e544ee5e20d.png)

Actually the legend will display in Multiline fashion. Please find the below screenshot which display the legend correctly.

![simulator screen shot 27-may-2016 7 38 14 pm](https://cloud.githubusercontent.com/assets/217577/15611026/0139f00a-2446-11e6-8937-412495ff0c03.png)

For that I had set the "wordWrapEnabled" property of "PieChartView->Legend", but sometimes it works and sometimes it does not.

Technical Details
OS : iOS 9.1
Device : iPhone 6
ID : XCode 7.3.1

Please let me know if you required any further information from my side for the same.

**Comment by danielgindi** [comment]
It works, but you have to call `notifyDataSetChanged` after setting it. Setting `data` property of course calls `notifyDataSetChanged` automatically.
