### ISSUE TITLE
Pie Chart with value lines

### ISSUE THREAD

**Issue by fraggjkee** [danielgindi/Charts#1085]
Hello,

I am trying to replicate the "**Pie Chart with value lines**" demo but for some reason Xcode doesn't see any properties related to this feature:

![2016-05-27 17 33 56](https://cloud.githubusercontent.com/assets/1222517/15611062/38f978fe-2431-11e6-84b4-a85e79163fa2.png)

Looks weird, right? In the meantime, the Demo project works quite well despite the fact that both are based on the same version - 2.2.4. I am using Objective-C and Cocoapods. 

Here's what I see when open the `PieChartDataSet` class using Xcode:

![2016-05-27 17 37 23](https://cloud.githubusercontent.com/assets/1222517/15611162/ae1ccc62-2431-11e6-8eb4-c6c5f5053d28.png)

Any ideas how to fix this? Thanks in advance.

**Comment by fraggjkee** [comment]
The same problem with `valueFormatter`, `valueFont` and `valueTextColor`... Is it a bug in Cocoapods or may be you changed the `PieChartDataSet`'s APIs recently? 

<img width="714" alt="2016-05-28 17 07 07" src="https://cloud.githubusercontent.com/assets/1222517/15627759/d4ed8b2c-24f6-11e6-8861-7caa899d7b32.png">

**Comment by ashish1703** [comment]
I am using 2.2.5 and is working fine.
See if you have added the references of the libraries in the right way.
