### ISSUE TITLE
ChartHighlight init data in function of highlightValue error

### ISSUE THREAD

**Issue by hanjt** [danielgindi/Charts#1096]
` h = ChartHighlight(xIndex: h!.xIndex, value: Double.NaN, dataIndex: -1, dataSetIndex: -1, stackIndex: -1)`
The code in ChartViewBase.swift will be crash, because of -1outside of array in function of drawMarkers. The crash code is `let highlight = _indicesToHighlight[i]` 
Yesterday I pull request and the id is #1094, but the Travis CI could not complete build. I don't know why.
Now I have to use v2.2.4 to avoid the crash. Could you help me to use v2.2.5?

**Comment by liuxuan30** [comment]
Travis is having problems, so you won't see it's green. 

- We could discuss in the PR, so closing this one
