### ISSUE TITLE
application doesn't compile for iphone 4s and iphone 5 device.

### ISSUE THREAD

**Issue by cuddle-sujeet** [danielgindi/Charts#1098]
the error says "chartLegend has no member chartLegendPosition" while the same code compiles for all the other ios devices. I am using xcode 7.3.1 and recently updated the pod.

**Comment by petester42** [comment]
Maybe there are cached stuff. Try cleaning the project and also deleting the derived data. My assumption would be that it should actually fail on all platforms but you have an old version cached.

**Comment by liuxuan30** [comment]
try clean & rebuild. Also, be careful with iOS7, you have to use source code.

**Comment by cuddle-sujeet** [comment]
Thanks for your instant support. After deleting the derived data it actually failed on all the  device. The problem was that I was using deprecated property.
