### ISSUE TITLE
BarChart bottom not on the Xaxis

### ISSUE THREAD

**Issue by dsencheng** [danielgindi/Charts#1102]
[https://github.com/danielgindi/Charts/issues/1101](url)
When I set  `leftAxis.axisMinValue = 0.0
 `   , i hope BarChart bottom on the Xaxis , no space between them.

**Comment by MonkeyRing** [comment]
leftAxis.spaceToBottom = 0.0

**Comment by dsencheng** [comment]
`leftAxis.spaceToBottom `  i did't find this attribute
@MonkeyRing

**Comment by liuxuan30** [comment]
could you try ChartsDemo? I did it, it should work. BTW, don't make duplicated issues.

**Comment by dsencheng** [comment]
You tried? normal? Obviously you do not understand the problem correctly. I found the problem and solved. You will only close the issue. ---- from: translate.google.com
你试过了？正常？显然你没有正确理解问题。我找到了问题并且解决了。你只会关闭问题。
@liuxuan30

**Comment by dsencheng** [comment]
@MonkeyRing 
Thanks.It's right. `leftAxis.spaceBottom = 0.0;` in IOS
