### ISSUE TITLE
Sync selected value in 2 chart

### ISSUE THREAD

**Issue by anhltse03448** [danielgindi/Charts#1105]
Hi all, 
I have 3 charts in 1 viewcontroller. 3 charts have same xAxis. When I select value in the first chart, I want to select the second and the third too. Please help me :) 
[http://postimg.org/image/ujejhvemz/](url)
Copy link and paste to see :)
(Draw red line in image)

**Comment by liuxuan30** [comment]
create the ChartHighlight object and pass it to the second and third charts to highlight it.
