### ISSUE TITLE
BarChartDataSet.values  is a get-only

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1108]
A newly downloaded Demo, one is the latest version, why OC is Flexible and swift get-only is it? what should I do
![1b88823e-65c4-4170-b63f-54d4ef76c9a6](https://cloud.githubusercontent.com/assets/13211527/15812514/7730ac78-2be8-11e6-918b-e4886418c2dd.png)
![840d82d7-1e91-447c-8bb8-15dcefd2c6fd](https://cloud.githubusercontent.com/assets/13211527/15812520/82dc9faa-2be8-11e6-96c2-656d984008d9.png)

**Comment by danielgindi** [comment]
It is not read-only https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Data/Implementations/Standard/ChartDataSet.swift#L74

**Comment by danielgindi** [comment]
You may need to cast

**Comment by shenyufei** [comment]
But why do I see here readonly? Or how can I convert? @danielgindi 
![606c56a3-6596-4369-9981-96010a775da4](https://cloud.githubusercontent.com/assets/13211527/15880969/d114e84e-2d64-11e6-8a5f-9a78739f4ee5.png)

**Comment by danielgindi** [comment]
Look at `BarChartDataSet`
