### ISSUE TITLE
custom string value at top of bar.

### ISSUE THREAD

**Issue by cuddle-sujeet** [danielgindi/Charts#1109]
I have gone through the issue: How to let the Y axis shows is not only a number, but the custom string #1003
whose solution states that I should set valueFormatter in ChartDataSet.
My Problem is that I need to set the values on top of these bar with a custom stringvalue coming from webService. From the implementation I see that the value formatter is being applied to the "values"  of the chartDataEntry.

Can't we some how use the DataValue as provided in the chartDataEntry init method.
BarChartDataEntry(value: value, xIndex: index, data: displayValue)

I need to set this "displayValue" on top the barChart.

**Comment by cuddle-sujeet** [comment]
Also I have noticed that the same can be done in android as the CustomerFormatter.

String getFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler) .

where the formatter has the access to the "entry" which is same as the "data" in swift method BarChartDataEntry(value: value, xIndex: index, data: displayValue).

**Comment by arjenbolten** [comment]
Did you manage to solve it?
I have the same problem

**Comment by cuddle-sujeet** [comment]
@arjenbolten No ..had to move to other alternative, I am using the ChartMarker to show the information as bubbles on top of it.

**Comment by liuxuan30** [comment]
Just use `dataSet.valueFormatter` in Chart 3.0. it's more flexible now.
