### ISSUE TITLE
Embedded Binaries charts.framewor But nothing happen!

### ISSUE THREAD

**Issue by 03128crz** [danielgindi/Charts#1111]
![snip20160607_7](https://cloud.githubusercontent.com/assets/3424553/15848176/e45fcd30-2cbd-11e6-82f4-40cd18a9885d.png)

But nothing Embedded
![snip20160607_8](https://cloud.githubusercontent.com/assets/3424553/15848189/01c0fbc4-2cbe-11e6-81b0-6dc1d291d571.png)

**Comment by liuxuan30** [comment]
could you please try search old issues? You can hit the + button to add it
