### ISSUE TITLE
BarChartDataEntry with Int instead of Double

### ISSUE THREAD

**Issue by wema1043** [danielgindi/Charts#1112]
Is it possible to get a BarChart with Ints?

`public init(values: [Double], xIndex: Int)
`
I can use only Doubles.

**currently it will be shown this way:**
Bar1: 15,_0_
Bar2: 20,_0_
Bar3: 7,_0_

**But I want:**
Bar1: 15
Bar2: 20
Bar3: 7

how can i do this?

**Comment by hardikdevios** [comment]
```
        chartDataSet.valueFormatter = NSNumberFormatter()
        chartDataSet.valueFormatter?.alwaysShowsDecimalSeparator = false
```

`chartDataSet` is a object of **BarChartDataSet**. i guess you know about it.

**Comment by wema1043** [comment]
thanks you!
