### ISSUE TITLE
Slow Build Time 

### ISSUE THREAD

**Issue by hardikdevios** [danielgindi/Charts#1113]
![screen shot 2016-06-07 at 6 49 27 pm](https://cloud.githubusercontent.com/assets/6657591/15858985/c3ae643e-2ce0-11e6-84d5-4369ba977b6d.png)

As you can see the list of files with MicroSeconds and the line number of function which causes compiler to slow which affects the build time for e.g 2 Seconds taken by first file, So Two files is mostly affected both are on Top, Though i am not having much issue with this but as the lib progress you guys have to consider this.

**Comment by danielgindi** [comment]
That function is very simple, but what you are seeing is a tree. The "time" column is inclusive to all other functions being called from that line... And so the "Build duration" is 2s in your screenshot. Thus proving that it's not a line in `animationUpdate` that causes an issue - It's just a point where the compiler chose to start digging in from.

**Comment by hardikdevios** [comment]
Ohk just to tell you that the whole build time is 25s. This is happened if you dont change and build it will 2s but if you do any changes in any file it will recompile all and takes more than 20s second. And animationupdate line is not causing the issue its the function which causes the issue not that line.
