### ISSUE TITLE
Disable scrolling parent scrollview when readed end of the chart

### ISSUE THREAD

**Issue by A1exandre** [danielgindi/Charts#1115]
Hi,

I have a scrollview with a chart inside that has dragging enable.

Currently, when I scroll the chart all the way to the end, the chart stops scrolling and the parent scrollview starts to scroll. Which makes sense in many cases.

However, in my case, I'd like to forbid the parent scrollview from scrolling at anytime when I scroll my chart.  A "dontScrollParentViewWhenDraggingToEndOfChart" setting would be nice.

Currently I just fixed this issue by editing the pangesturerecognized function in BarLineCharViewBase to force  _outerScrollView?.scrollEnabled = false even if the chart is dragged to its end. However, it's quite a dirty fix.

Thanks!

**Comment by petester42** [comment]
To me this seems out of scope of the library. We can't have setting for each scenario of view heirarchy. Overriding the pan gesture recognizer callbacks is just fine that is what they are meant for. It's not dirty fix.
