### ISSUE TITLE
Single LineChartDataSet in LineChartView

### ISSUE THREAD

**Issue by greenmood** [danielgindi/Charts#1116]
Hi,

Thanks for a great lib and a great job! I wanted to ask is it possible to display a single LineChartDataSet in Chart view as a point? In my current project, there's a case, where there's only one value in the graph, so it would be great to display it somehow.

**Comment by KodiKraig** [comment]
I am accomplishing this right now I believe. You are saying you only have one yValue for the graph and its not displaying it?

**Comment by greenmood** [comment]
yes.

**Comment by danielgindi** [comment]
Maybe add more x-indices. When there's only one value, the width of the chart is singular.

**Comment by greenmood** [comment]
but what if i have only one value? one Position with x and y. Is there a property, which i haven't found, that for example makes a circle on graph if there's only one value passed to framework?
