### ISSUE TITLE
chartValueSelected on TVOS

### ISSUE THREAD

**Issue by alappe** [danielgindi/Charts#1117]
Hey,

I'm trying to get the selected entry of a chart on TVOS. Since I get a cross-hair when I use the remote, I asummed that's possible, but `chartValueSelected` on my `ChartViewDelegate` doesn't get called, it seems. Is there anything else I am missing or is it not supported on TVOS?

**Comment by danielgindi** [comment]
If you are able to get the crosshair - it should call `chartValueSelected`... Please make sure that it is getting called on iOS too.
It will be pretty hard for me to complete compatibility with tvOS as I don't have one - it was done by one of the contributors :-)
I'm not even sure that there's a way to select anything...

**Comment by alappe** [comment]
@danielgindi Thanks for your response. Using the apple-TV variant in the simulator works pretty well and with the remote-window, one can also move the crosshair.

I again double-checked my code now, and this time i found my mistake: I didn't reference my view as the delegate of the chart, it's working now… thank you!
