### ISSUE TITLE
Customizing the x-axes labels.

### ISSUE THREAD

**Issue by jleach** [danielgindi/Charts#1120]
Hi: 

I have a data point every 10min for a 24h period. I want my x-axis labels to be "12AM 4 8 12PM 4 8". What's the best way to implement this?

**Comment by dxclancy** [comment]
I'm not a collaborator and don't have time to look at the API to see if this is directly supported, but couldn't you merely determine this when setting XVals, assuming it allows empty strings?
    for (int i = 0; i < count; i++)
    {
        // if the xVal is one of the values 12AM 4 8 12PM 4 8 add it otherwise add empty string
        [xVals addObject:every4thHourOrEmptyString];
    }

you can also implement the   public var valueFormatter: ChartXAxisValueFormatter? and pass back  string you want.

**Comment by jleach** [comment]
After some searching I tried to `func drawLabels` in `ChartXAxisRenderer`. Seems to be working well enough.
