### ISSUE TITLE
Line chart gap

### ISSUE THREAD

**Issue by Talgat777** [danielgindi/Charts#1121]
Hi guys,

Is there a way to have a gap in line chart if there is no data provided. Something like this:
![screen shot 2016-06-10 at 11 20 06 am](https://cloud.githubusercontent.com/assets/5118302/15954815/510e645a-2efd-11e6-8fd6-9209b9e19609.png)

Thanks in advance!

**Comment by liuxuan30** [comment]
currently it does not support, I had request for it, but no progress #280
