### ISSUE TITLE
Can't hide small slice labels from pie chart.

### ISSUE THREAD

**Issue by yigitserin** [danielgindi/Charts#1122]
Hi there,

In my pie charts, sometimes there are slices under 1% , they are so small so they intersect each other and procude a bad visual experience. How do I hide labels and percent values from smaller slices?

**Comment by amin234** [comment]
same isue

**Comment by liuxuan30** [comment]
are you asking for https://github.com/danielgindi/Charts/pull/944?

**Comment by yigitserin** [comment]
Yes, is it possible currently?

**Comment by yigitserin** [comment]
I would like to, but I don't understand how do I implement it.

**Comment by liuxuan30** [comment]
Not sure your question, you can check out his branch to use it, or manually porting the feature

**Comment by Perjan** [comment]
hey guys, any news?

**Comment by liuxuan30** [comment]
I think it's a dup, and #944 is still pending merge
