### ISSUE TITLE
Rounding error on Y-axis when all Y values are zeroes

### ISSUE THREAD

**Issue by duzenko** [danielgindi/Charts#1123]
I can't get the Y-axis labels right using the latest version of the library
By default they include trailing zeroes:
![simulator screen shot jun 10 2016 7 08 13 pm](https://cloud.githubusercontent.com/assets/1481807/15970723/bd83d412-2f3e-11e6-809c-a54ae398229d.png)
Now I try to pass a custom number formatter so as to get rid of the zeroes and it works for that data set 
```
                NSNumberFormatter *formatter = [[NSNumberFormatter alloc] init];
                formatter.maximumSignificantDigits = 3;
                [chart set_defaultValueFormatter:formatter];
```
But when I pass all zeroes to a line chart I get an ugly rounding error:
![simulator screen shot jun 10 2016 6 46 35 pm](https://cloud.githubusercontent.com/assets/1481807/15970147/eafa04be-2f3b-11e6-8ea2-24b39efa7165.png)
Is there another way to get rid of the trailing zeroes, or am I doing something wrong?

**Comment by liuxuan30** [comment]
have you tried `allowRepeatingValue`?

**Comment by duzenko** [comment]
What is that? Can't see it here: https://jitpack.io/com/github/PhilJay/MPAndroidChart/v2.2.5/javadoc/

**Comment by liuxuan30** [comment]
it's in iOS portion, I am not sure if you can see it on android side

**Comment by duzenko** [comment]
What class is this method in and what does it do?

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/issues/315

**Comment by duzenko** [comment]
Sorry, which of my two problems is this supposed to help? Trailing zeroes or rounding error?

**Comment by liuxuan30** [comment]
oops, I thought you are having deplcated zeroes. Are you asking about the number formatter？You can take a look at maximumFractionDigits and minimumFractionDigits

**Comment by duzenko** [comment]
I think I explained my problem in the first post.
There is an ugly rounding error when I use formatter

**Comment by liuxuan30** [comment]
as I said, maximumFractionDigits and minimumFractionDigits seems solution to me

**Comment by duzenko** [comment]
Enlighten me - what values do I need to assign to maximumFractionDigits and minimumFractionDigits?

**Comment by liuxuan30** [comment]
hmm, if you only want max two, like 0.11, it will avoid situation like 0.111111111111.
if you need minimum digits like 2, "1" would be "1.00".
So in your case, I would guess minimumFractionDigits = 0 and maximumFractionDigits = 1 or 2. Does this works for you?

**Comment by duzenko** [comment]
Regret it does not

Test code
```
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view, typically from a nib.
    LineChartView *chart = [[LineChartView alloc] init];
    chart._defaultValueFormatter.maximumFractionDigits = 2;
    chart._defaultValueFormatter.minimumFractionDigits = 0;
    [self.view addSubview:chart];
    
    int N = 5, M = 11;
    NSMutableArray *vals = [NSMutableArray arrayWithCapacity:N], *xVals = [NSMutableArray arrayWithCapacity:M];
    for (int i=0; i<M; i++) {
        if (i < N) {
            ChartDataEntry *entry = [[ChartDataEntry alloc] initWithValue:98+i xIndex:vals.count];
            [vals addObject:entry];
        }
        [xVals addObject:[NSNumber numberWithInt:i]];
    }
    LineChartDataSet *dataSet = [[LineChartDataSet alloc] initWithYVals:vals];
    LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSet:dataSet];
    [chart setData:data];
    chart.frame = CGRectMake(0, 30, self.view.frame.size.width, 100);
}
```
Result:
![simulator screen shot jun 17 2016 11 31 30 am](https://cloud.githubusercontent.com/assets/1481807/16144977/1d65f942-347f-11e6-9cc9-684676ace39c.png)

**Comment by liuxuan30** [comment]
OK first of all, if you see something contains `_` as prefix, that's what not usually you should use outside the library, it's private or internal, so nothing guaranteed if you directly use it..
What you should use at y axis is `valueFormatter`, not `_defaultValueFormatter`.
If you want the same formatter for value labels, use set.valueFormatter

**Comment by duzenko** [comment]
Changed to 
```
    chart.leftAxis.valueFormatter.maximumFractionDigits = 2;
    chart.leftAxis.valueFormatter.minimumFractionDigits = 0;

```
No effect. Same thing as on the picture from the previous post

**Comment by liuxuan30** [comment]
that's simply not true: I used ChartsDemo and you can see it has 23, 23.16, and 23.2 on the chart.
![value](https://cloud.githubusercontent.com/assets/4375169/16155843/11c79370-3466-11e6-9ff2-d5b6336bfe88.png)

**Comment by duzenko** [comment]
What is not true? My data are integer numbers and I don't want decimals after dot on the Y axis

**Comment by liuxuan30** [comment]
look I think it's all about the value formatter you are using... The library will take all values into double type, so even you mean integer, it's still double. 

If you don't want decimals, simply set maximumFractionDigits = 0.

you need to take a look at the number formatter documentation, it's all there.

**Comment by duzenko** [comment]
maximumFractionDigits = 0 simply does not work as per the code above

**Comment by duzenko** [comment]
I need to show values as float if they're float and as integer if they are integer - the data comes from web and I don't know that beforehand

**Comment by iamabhiee** [comment]
How can I set integers for values label in Horizontal Bar chart?
