### ISSUE TITLE
Failing to build the project

### ISSUE THREAD

**Issue by inzo111** [danielgindi/Charts#1124]
Hello all,

I have a problem in building a project using Charts, i tried to add it manually and using coacoapods, both failed. I get 27 errors
<img width="257" alt="screen shot 2016-06-11 at 14 24 23" src="https://cloud.githubusercontent.com/assets/18231944/15985310/9e7908ec-2fe0-11e6-8b5a-312cf016d9e5.png">

**Comment by liuxuan30** [comment]
update your Xcode seems a solution to me
