### ISSUE TITLE
Space at the bottom of the Line Chart View in landscape view

### ISSUE THREAD

**Issue by YHSX88** [danielgindi/Charts#1125]
Hi Guys ,  I have problem with the line chart and I can't seem to figure it out from where this can be,
This is in wRegular hCompact
![screen shot 2016-06-11 at 18 58 50](https://cloud.githubusercontent.com/assets/16823745/15986033/ba9321fe-3006-11e6-9aa0-d8b3944d79a8.png)

Basically Im stretching the chart view but after I rotate the screen. with 4 constrains to hold the view.

and the result is this:

![screen shot 2016-06-11 at 18 47 29](https://cloud.githubusercontent.com/assets/16823745/15986069/42e57a70-3007-11e6-8ecc-b3428e7aec58.png)

Can someone tell me please if this is something related to Charts repo or is me doing something wrong ?

Please someone help :)

**Comment by liuxuan30** [comment]
well chart will draw only within your chart view object, so you should check your layout first to make sure the view frame is correct
