### ISSUE TITLE
custom chart label layout

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/Charts#1128]
sorry to trouble, I'm not familiar with this smart lib,

could I custom chart label layout position, like below image.

![chart1](https://cloud.githubusercontent.com/assets/7262199/15998611/40d01c2e-3172-11e6-8d09-a53c63d353b6.jpg)

change to this layout?

![chart2](https://cloud.githubusercontent.com/assets/7262199/15998622/517046bc-3172-11e6-8f8f-00ca4d09e84f.jpg)

thanks for your time.

**Comment by shujucn** [comment]
You can write your own legend

**Comment by L-Jovi** [comment]
@shujucn  hi, thanks for your reply, what config could I custom to change position layout?

**Comment by liuxuan30** [comment]
you can check legend's position properties, if that does not satisfy, you have to write your own for now.

**Comment by L-Jovi** [comment]
@liuxuan30  thanks :)
