### ISSUE TITLE
Disable touch events, so do not show Label

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1129]
The disable touch events has been solved,my technical question.

I do not want to display the following Label, shown in PNG.
What  should I do? Thank you ...
Also, if we talked in great detail the better.😋
![d2ecca22-1460-498c-8587-49bf9f24b829](https://cloud.githubusercontent.com/assets/13211527/16001883/4052d4ca-3187-11e6-9616-aefa111f35bf.png)

**Comment by jshin49** [comment]
Hello @shenyufei I wonder why you closed the issue. Can you tell me how you solved the disabling the label problem? Many thanks.

**Comment by liuxuan30** [comment]
legend.enabled = false
