### ISSUE TITLE
PieChart percent values are always rounded up to integer, I would like to show them as float.

### ISSUE THREAD

**Issue by yigitserin** [danielgindi/Charts#1131]
Hi there,

I am using a piechart but having problems with labels of each slice. What I want to achieve is this:
[My goal](http://s31.postimg.org/3pf8ccc7v/Ekran_Resmi_2016_06_13_22_08_31.png)

And this is what I have so far:
[My progress](http://s32.postimg.org/v06k833o5/Ekran_Resmi_2016_06_13_22_17_59.png)

So here are my questions:

1.  How to show labels as Float instead of Int? [SOLVED]
2.  How to show the percent signs near the labels? [SOLVED]
3. How to hide labels for small slices? 

These are my settings so far:

                piechart.highlightPerTapEnabled = false

                piechart.rotationEnabled = false

                piechart.usePercentValuesEnabled = true

                piechart.drawSliceTextEnabled =  false

                piechart.drawHoleEnabled = false

**Comment by yigitserin** [comment]
Solved 1 and 2 by using:

                let formatter = NSNumberFormatter()
                formatter.numberStyle = .PercentStyle
                formatter.maximumFractionDigits = 1
                formatter.multiplier = 1.0
                data.setValueFormatter(formatter)

Still need a way to disable labels for slices under X% percent of pie.

**Comment by liuxuan30** [comment]
last is dup I guess, closing. check #944

**Comment by paulowolking** [comment]
let formatter = NSNumberFormatter()
            formatter.numberStyle = .PercentStyle
            formatter.maximumFractionDigits = 1
            formatter.multiplier = 1.0
            data.setValueFormatter(formatter)

It is still a valid solution ? Me did not work.
