### ISSUE TITLE
Issues with xcode 8.0 beta

### ISSUE THREAD

**Issue by miladyalda** [danielgindi/Charts#1132]
I get this message when I run my code with Xcode 8.0 beta

 for Charts requires a development team. Select a development team in the Target Editor.
Code signing is required for product type 'Framework' in SDK 'iOS 10.0'

**Comment by opswhisperer** [comment]
This is an Xcode8 thing, Just select your targets and re-set your Team

**Comment by miladyalda** [comment]
which swift version is framework written with?

**Comment by liuxuan30** [comment]
it started at swift 1.2 I remember, and now it's on 2.2

**Comment by danielgindi** [comment]
When Xcode 8.0 will be released - it will move on to Swift 3 :-)

**Comment by butterpuf** [comment]
xcode 8.0 is released. Can you tell when compatible pod will be released for Charts?
