### ISSUE TITLE
BalloonMarker overlapping issue

### ISSUE THREAD

**Issue by keithyeohh** [danielgindi/Charts#1137]
Hi guys,

I am having a few issues with line chart view.

1) The BalloonMarker not manage to show the full view on the last point.

Attached with Screenshot:
https://www.dropbox.com/s/414bavrenqnxnsg/Photo%2014-06-2016%2C%201%2022%2056%20PM.jpg?dl=0

2) How can I change the text color of BalloonMarker, as I not manage to see any property related to label. Or BalloonMarker is actually an UIImage property?

`BalloonMarker *marker   = [[BalloonMarker alloc] initWithColor:[UIColor blueColor]
                                                                  font:[UIFont boldSystemFontOfSize:14.f]
                                                                insets:UIEdgeInsetsMake(8.0, 8.0, 20.0, 8.0)];`
`marker.minimumSize      = CGSizeMake(80.f, 40.f);`
`self.lcView.marker      = marker;`

**Comment by liuxuan30** [comment]
You can  take a look at ChartMarker class, that's the root class, you can derive your own. BalloonMarker is just a example. You can change anything you want
