### ISSUE TITLE
How to show bar chart value labels only on selection

### ISSUE THREAD

**Issue by yigitserin** [danielgindi/Charts#1139]
I looked into documentations and issues but couldn't find it. 

My question is, how do hide bar chart labels initially but show them only on one of them is selected like this?

[Image](https://camo.githubusercontent.com/78b4bc4e50e151970961daf56e81c4c0db72d27c/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67)

**Comment by yigitserin** [comment]
I used  `barChart.maxVisibleValueCount = 0` to hide labels, then used a marker. But is this method optimal?

**Comment by liuxuan30** [comment]
in your data set, set.drawValuesEnabled = false to disable showing the value labels. marker depends on your logic, so you could use it, or override drawHighlighted to draw some text
