### ISSUE TITLE
Support Swift 3.0 (Xcode 8)

### ISSUE THREAD

**Issue by acegreen** [danielgindi/Charts#1140]
I took a jab at this myself but was unable to resolve all the changes. Thanks in advance

**Comment by liuxuan30** [comment]
well you have to wait... if you like, convert to 2.3, would be much easier if you want to use Xcode 8

**Comment by acegreen** [comment]
@liuxuan30 Don't feel rushed. This is just a ticket so we can all reference it and against it for pull requests.

**Comment by liuxuan30** [comment]
then we probably keep it open until resolved :)

**Comment by danielgindi** [comment]
It's still beta, not it's not a release. There will soon be a branch for Swift 3

**Comment by pixelspark** [comment]
Here's a pull request for Swift 3. This successfully compiles on OSX (other platforms probably as well, but untested): https://github.com/danielgindi/Charts/pull/1169
