### ISSUE TITLE
when scaled  touch move can't toggle highlight

### ISSUE THREAD

**Issue by juvham** [danielgindi/Charts#1141]
as title

**Comment by liuxuan30** [comment]
can you be more specific? Like screenshots, explanations..

**Comment by juvham** [comment]
when after do pan or scale  action  

touch move can't change the highlight  

so add a  long pressgesture for that 

when long press is recongnized   pan just for highlight   otherwise  pan for  scroll

**Comment by juvham** [comment]
when after do pan or scroll  action  

touch move can't change the highlight  

so add a  long pressgesture for that 

when long press is recong

**Comment by liuxuan30** [comment]
if you zoomed in, the scrolling behaviour will not trigger highlight, only can tap gesture highlight, is this what are you asking?

**Comment by juvham** [comment]
Yes

发自我的 iPhone

**Comment by liuxuan30** [comment]
ok, sounds solved. It is by design, but you can change the code to meet your goal
