### ISSUE TITLE
When the X-Axis's text is too long, it will cover the radar chart.

### ISSUE THREAD

**Issue by GitHubWanglei** [danielgindi/Charts#1143]
When the X-Axis's text is too long, it will cover the chart.
![1ce4a7df-1110-4640-916b-99ffd4410354](https://cloud.githubusercontent.com/assets/16434720/16072832/7463ef30-3315-11e6-87f7-becc6e82a123.png)
How can I solve this problem?

**Comment by liuxuan30** [comment]
check out x axis renderer of radar chart `renderAxisLabels()`, I am not sure if this is by design or a bug

**Comment by GitHubWanglei** [comment]
I have set the label position of X-Axis in my objective-c project like this:
```
//设置 xAxi
    ChartXAxis *xAxis = self.radarChartView.xAxis;
    xAxis.labelFont = [UIFont systemFontOfSize:12];//字体
    xAxis.labelTextColor = [self colorWithHexString:@"#057748"];//颜色
    xAxis.labelPosition = XAxisLabelPositionBottom;
    xAxis.wordWrapEnabled = YES;
    xAxis.labelWidth = 100;
```
But it had no effect.How can I set the label position correctly? Have any other properties or methods to solve this problem?

**Comment by liuxuan30** [comment]
I think it's about the anchor point of the label, so you may want to take a look at how the origin point is calculated, radar chart maybe a little tricky, because it could rotates, so just take a look at renderAxisLabels() if you can make some change first.

**Comment by GitHubWanglei** [comment]
In the `ChartXAxisRendererRadarChart.swift` file, I found the `renderAxisLabels()` method, in this method, I found some lines like this:
```
let p = ChartUtils.getPosition(center: center, dist: CGFloat(chart.yRange) * factor + xAxis.labelRotatedWidth / 2.0, angle: angle)

drawLabel(context: context, label: label!, xIndex: i, x: p.x, y: p.y - xAxis.labelRotatedHeight / 2.0, attributes: [NSFontAttributeName: labelFont, NSForegroundColorAttributeName: labelTextColor], anchor: drawLabelAnchor, angleRadians: labelRotationAngleRadians)
```
I found the point p is thie X-Axis label's center, so, I think the point p should add some offset relative to the radarChartView's center, but how can I get the radarChartView's center.
The point p position and the problem in the image like this:
<img width="612" alt="9e27b1b1-0974-4943-b2ae-955faf46dcaa" src="https://cloud.githubusercontent.com/assets/16434720/16175071/564171f0-3615-11e6-9fad-70c89fcac9d5.png">

@liuxuan30 @danielgindi Can you fix this issue?

**Comment by GitHubWanglei** [comment]
I found when the label is English text, it's no issue. like this:
![85d20bdd-dcd6-40b0-80c1-306ab2fa349d](https://cloud.githubusercontent.com/assets/16434720/16181850/9bb3662c-36d2-11e6-8e7b-de8d777641c8.png)
But when I use Chinese text, the issue will occur, like this:

![1b3e69f2-dc21-4dc1-b7c9-640f56868532](https://cloud.githubusercontent.com/assets/16434720/16181903/2bfd991e-36d3-11e6-88c0-a105a342a27e.png)
What's wrong with this? @liuxuan30 @danielgindi

**Comment by liuxuan30** [comment]
hey you don't have to "@" at anyone, someone seeing this will try to help.
I am not sure why right now, maybe the text render engine, I don't know.

Since you know where is the code, you can try first...

Quite busy recently

**Comment by GitHubWanglei** [comment]
Thank you for your reply.

**Comment by danielgindi** [comment]
You have two questions in your screenshots:
1. How can I get this center? - Call `centerOffsets` on the chart view, or `contentCenter` on the viewport.
2. Why the missing offsets of the labels? Well, this must be how the text renderer handles the Chinese glyphs. It is given the correct instructions, as you can see with English, but renders incorrectly. It could be a bug in how CoreGraphics draws Chinese glyphs, but it is most probable that it is a bug in the specific font. **So I would try a different font.**
