### ISSUE TITLE
specify certain point custom color

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/Charts#1144]
hi, what config could I custom color of certain point in bar chart and line chart?
like image below which custom the red color of certain point.

![image](https://cloud.githubusercontent.com/assets/7262199/16077338/c98efaf8-332a-11e6-8e45-8c5ddf1c6f40.png)

thanks for your time.

**Comment by liuxuan30** [comment]
well... if it's not about highlight, then you have to change the code I guess. Can it be highlight?

**Comment by L-Jovi** [comment]
I think that point may always display,
and I find my colleague implement it by `highchart`, but I have no idea to do it in iOS with our smart Charts, by the way, I don't want to use webview :D

and idea?

thanks for your reply :)

**Comment by liuxuan30** [comment]
you can create a ChartHighlight object to highlight some bars in code, so you don't have to use gestures, and you have to turn it off. Will you need gestures in the future? 

The idea is simple, get touch events -> create ChartHighlight object -> render the highlight

**Comment by L-Jovi** [comment]
well.. a foolish question, is touch events defined in `Utils/ChartPlatform.swift`?

I find many swift files which having event method..

thanks for patience ..

**Comment by liuxuan30** [comment]
touch events handled in BarLineChartViewBase I remember. If it's pie chart, it's in pie chart base

**Comment by danielgindi** [comment]
You don't have to handle touches to add highlights. You can just set the highlighted entries...

**Comment by L-Jovi** [comment]
I implemented it, thanks for your patience :)
