### ISSUE TITLE
using ChartXAxisValueFormatter doesn't enable 3 lines x axis labels

### ISSUE THREAD

**Issue by youvalv** [danielgindi/Charts#1148]
Hi :)
I have to mention this is a great project!

My string output yields 3 lines
the bottom line is always cut

![simulator screen shot 16 jun 2016 4 32 37 pm](https://cloud.githubusercontent.com/assets/5232799/16118552/4a7c4df4-33e0-11e6-87f4-72781878dbda.png)

```
- (NSString *)stringForXValue:(NSInteger)index
                     original:(NSString *)original
              viewPortHandler:(ChartViewPortHandler *)viewPortHandler
{
    if (index < self.chartData.count)
    {
        heartRate = [NSString stringWithFormat:@"\n%@ %@", self.chartData[xIndex][HD_META_DATA_COL][[HD_HR_SERIES integerValue]], HD_HR_SERIES_NAME];
        NSString* returnString = [NSString stringWithFormat:@"%@\n%@ %@%@",
                              [HDDateUtil formatShortDayForDate:readingDate textForToday:@"TODAY"],
                              [[HDDateUtil format12HourForDate:readingDate] uppercaseString],
                              [[HDDateUtil formatPeriodOfDayForDate:readingDate] uppercaseString],
                              heartRate];
    }
    else
    {
        return original;
    }
}
```

**Comment by liuxuan30** [comment]
well it can show two lines already, so I am guessing this is a bug. Were you able to fix it? I am kind of busy this week so I can't take a look at this very soon.

The problem seems like when calculating the x axis labels size, the height for multiple lines is not correct.  It's in Chart x axis renderer's computeAxis() method. 

```swift
        let labelSize = widthText.sizeWithAttributes([NSFontAttributeName: xAxis.labelFont])
        
        let labelWidth = labelSize.width
        let labelHeight = labelSize.height
```
It seems like it does not take multiple lines into account? Can you start from here and if this is the cause, and maybe a fix?

**Comment by youvalv** [comment]
Tried to take a look, but I'm yet to be proficient in SWIFT. Don't want to mess up the code
if it helps, word wrapping doesn't help as well. when reaching 3rd line it is cut too. 
meaning: 
- used a very long text without line breaks (\n) and playing with the zoom of the graph caused it to break into lines. 3rd  line and forward is cut

**Comment by danielgindi** [comment]
The X axis **does** draw multiline text. It is just having some difficulties in your case to calculate the required space for the labels.
You could just add an extra spacing to the chart, using `extraBottomOffset` property.
