### ISSUE TITLE
Chart Clipping

### ISSUE THREAD

**Issue by ziadtamim** [danielgindi/Charts#1149]
The chart is clipping from top:

![screen shot 2016-06-16 at 2 21 19 pm](https://cloud.githubusercontent.com/assets/1026099/16120117/631afb12-33d6-11e6-835b-8a20fb2e2836.png)

**Comment by liuxuan30** [comment]
what did you do then? By default, it should not happen. We need more info. Take a look at ChartDemo, and seee if you are not following the correct workflow first

**Comment by ziadtamim** [comment]
@liuxuan30 I guess that I am following the same workflow as on the ChartDemo 

      `self.xAxis.gridColor = UIColor.whiteColor().colorWithAlphaComponent(0.2)
        self.xAxis.drawAxisLineEnabled = false
        self.xAxis.drawLabelsEnabled = false
        self.xAxis.drawGridLinesEnabled = false
        
        self.leftAxis.drawZeroLineEnabled = true
        self.leftAxis.drawGridLinesEnabled = false
        self.leftAxis.zeroLineColor = UIColor.whiteColor().colorWithAlphaComponent(0.2)
        self.rightAxis.drawGridLinesEnabled = false
        
        self.leftAxis.axisMinValue = 0
        self.rightAxis.axisMinValue = 0
        
        self.legend.enabled = false
        self.doubleTapToZoomEnabled = false`

![screen shot 2016-06-16 at 4 27 08 pm](https://cloud.githubusercontent.com/assets/1026099/16124670/cda9de24-33e7-11e6-89c8-c5bbf46bf44f.png)

Do you think that is related the high values?

**Comment by liuxuan30** [comment]
where do you call configure()? One common mistake is if you first set chart data, then configure chart property, you have to call notifyDataSetChanged, so normally configure chart first, and set chart data, because it will call notifyDataSetChanged in the data setter.

However I am not sure if this is the case. You can try it out.

On the other hand, if you use ChartsDemo, and just set axisMinValue, will it cut the highest value? I am thinking if you touches axisMaxValue

**Comment by ziadtamim** [comment]
@liuxuan30 I am calling configure() first. I still experience the same issue on my end.

**Comment by liuxuan30** [comment]
Also, have you set the axis dependency? I see you are having two axises, and different range.

**Comment by ziadtamim** [comment]
Yes, I am using it.

**Comment by ziadtamim** [comment]
@liuxuan30 Do you have an idea from where this can come from?

**Comment by liuxuan30** [comment]
not yet, just com back from WWDC, so lots of things left behind..

**Comment by danielgindi** [comment]
I think that it is related to this issue #407. Please use horizontal-bezier instead of the normal cubic bezier, it will better suit your needs if you don't understand beziers :-)
