### ISSUE TITLE
Unable to build project in new environment and it shows build error

### ISSUE THREAD

**Issue by arasu01** [danielgindi/Charts#1152]
I'm using Charts.xcodeproj in my project and I have duplicated release configuration and created a new configuration in my project.

![build_config](https://cloud.githubusercontent.com/assets/6689319/16183616/9ebecdbc-36d1-11e6-9312-d9244065a7ce.png)

When a build the project with Debug build configuration I'm not getting any errors, but when it was build using "Adhoc" configuration I'm getting error "No Such Module Charts".

@danielgindi Please let me know how to fix this.

**Comment by liuxuan30** [comment]
could you try search old issues with key word "No Such Module Charts"?
