### ISSUE TITLE
I want datasetvalues according leftAxis and RigthAxis different display

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1153]
As the picture show. 

This is based on LeftAxis BarChart display, this is based on RigthAixs LineChart show, please answer in detail about the specific steps, thank you

![dcf36403-4e82-4292-a712-db262de9fb08](https://cloud.githubusercontent.com/assets/13211527/16185577/70203150-36f7-11e6-983f-eca75379fd3c.png)

**Comment by liuxuan30** [comment]
what you are asking? The chart seems good already

**Comment by shenyufei** [comment]
I want to make the kind of picture, just think, but not made this way.😅 @liuxuan30

**Comment by liuxuan30** [comment]
this is a chart I believe this library already supported

**Comment by shenyufei** [comment]
I also know that have already been made, but the only similarity I see that Demo is based on the left y-axis to achieve, this image is displayed on the left, respectively, based on the y-axis and y-axis to the right of the display, there is no Demo, so I do not know how to write, you give some tips, such as how to assign the right of the y-axis and the like. Detail, thank you very much。  @liuxuan30

**Comment by liuxuan30** [comment]
If I understand correctly, you just have to assign `axisDependency` in data set object, so the data set will know which axis (left or right) is being used.
e.g. barChartDataSet.axisDependency = .Left

**Comment by shenyufei** [comment]
Dude, you finally understand me, thank you very much, I hasten to try, but you are still not detailed enough, after all, we are a novice, I have much more to see for a long time, if you can be more detailed, so much the better, ha ha
