### ISSUE TITLE
Charts setup in Obj C project question

### ISSUE THREAD

**Issue by 9SL9** [danielgindi/Charts#1154]
I've read the Usage section many times but I'm still having issues. One question remains before I bring my issue to you all.

What is not clear from the instructions is do I need to follow the usage section **AND** use cocoa pods (i.e. copy the the Charts project, add the framework in build options etc etc).

Thanks

**Comment by liuxuan30** [comment]
I think you can choose one. That's enough. Either pods or manually, or carthage
