### ISSUE TITLE
How can I select the close value in the candle chart view?

### ISSUE THREAD

**Issue by GitHubWanglei** [danielgindi/Charts#1155]
When the candle be selected, I want the close value be selected. What should I do?
![e8c38fb7-adde-45cf-98f2-7bbde58043c1](https://cloud.githubusercontent.com/assets/16434720/16186900/d2a09434-36ff-11e6-8324-269343f3a600.png)

**Comment by liuxuan30** [comment]
hmm, please check the candle stick chart renderer func drawHighlighted, you should be highlight anything you like there

**Comment by GitHubWanglei** [comment]
Thank you very much!
 I have solved this problem in func drawHighlighted, just change the y value in the func:
```
let lowValue = CGFloat(e.low) * animator.phaseY
let highValue = CGFloat(e.high) * animator.phaseY
let y = (lowValue + highValue) / 2.0
```
