### ISSUE TITLE
how can i add a button in redmark and i can click ..

### ISSUE THREAD

**Issue by dawangjiaowolaixunshan** [danielgindi/Charts#1156]
![image](https://cloud.githubusercontent.com/assets/11595694/16194599/eec77100-3727-11e6-965c-f085fa475d52.png)

   LineChartDataSet *set3 = nil;
    set3 = [[LineChartDataSet alloc] initWithYVals:yVals2 label:@"比较产品收益率"];
    set3.axisDependency = AxisDependencyRight;
    [set3 setColor:RGBcolor(0X6d, 0Xc5, 0Xfd)];
    [set3 setCircleColor:UIColor.whiteColor];
    set3.lineWidth = 1.0;
    set3.circleRadius =0;

**Comment by liuxuan30** [comment]
then add a button! It's a UIView and you can do anything you like right?
