### ISSUE TITLE
Adding Entries dynamicly 

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#1157]
Hi, i cant find example to adding entries dinamicly in the project, where can i find it?

**Comment by youvalv** [comment]
Can you explain your use case a little bit more?

**Comment by orensha** [comment]
yap, i'm showing rates in my graph and when i get update i need to insert the point also to the graph.

**Comment by youvalv** [comment]
just update the dataset without animation

**Comment by liuxuan30** [comment]
there are api to add entry, check it out
