### ISSUE TITLE
Suggest combo type chart support gouped bar type

### ISSUE THREAD

**Issue by AliThink** [danielgindi/Charts#1159]
Suggest combo type chart support grouped bar type,thx ^_^
And some bugs when use ChartMarker in combo type chart.

**Comment by liuxuan30** [comment]
what is combo type？

**Comment by AliThink** [comment]
@liuxuan30 thx for reply. I mean CombinedChartView

**Comment by liuxuan30** [comment]
grouped bar support is on the way, but still, no ETA. It is supposed to be in 3.0

**Comment by AliThink** [comment]
thx, hope to see her ASSP ^_^ it's really nessary.

**Comment by liuxuan30** [comment]
if you really need it, you can take a look at my PR: #269.

I don't have time to sync it with master branch, so, you can take a look and give a try, if you don't need recent features.
