### ISSUE TITLE
How to add images on some points?

### ISSUE THREAD

**Issue by xtreme8210** [danielgindi/Charts#1160]
Hi, is it possible to show some pictures at some points?  Please help
![2016-06-21 11 31 18](https://cloud.githubusercontent.com/assets/2245528/16217203/c6a7047a-37a3-11e6-8b75-8eab4c9c37ca.png)

**Comment by liuxuan30** [comment]
Someone has asked before.

There are two options:
1. use ChartMarer.image
2. customize the renderer

I would choose option 1 I guess
