### ISSUE TITLE
Adding an average line to a BarChartView

### ISSUE THREAD

**Issue by boonerite** [danielgindi/Charts#1162]
Hi,
Is it possible to add a horizontal line that defines the average value of the values of the bars collectively?

Also, how do we set the position of the value of each bar to be inside, instead of sitting floating on top of the bar?

**Comment by liuxuan30** [comment]
it's called ChartLimitLine here, and you can simply calculate a number to it.
for the second question, try disable drawValueAboveBarEnabled
