### ISSUE TITLE
Does it support discontinuity?

### ISSUE THREAD

**Issue by uditiiita** [danielgindi/Charts#1164]
Hey,
I am looking for a library to plot line charts but I need discontinuity feature in it. Like if I want to plot tan(x) using this library, can you please suggest how can I do that?

**Comment by liuxuan30** [comment]
what you mean discontinuity? line breaking?

**Comment by uditiiita** [comment]
Yes. Can I implement have that using Charts? Basically  I want to plot tan(x) function using this library. Can I do that?

**Comment by liuxuan30** [comment]
well, the library can't right now, but definitely you can modify the code to do it. The reason it's not supported officially is because it's kind of complicated when thinking about filling rect features.

**Comment by danielgindi** [comment]
You can supply whatever dataset you want. If you want to plot complicated functions - you might want to use some kind of bar chart (like the candle chart), or subclass it.
