### ISSUE TITLE
Compile error on iPhone 4s simulator

### ISSUE THREAD

**Issue by IceHawk66** [danielgindi/Charts#1165]
First of all, I can compile my app on iPhone 6 and iPhone 5s without any issues. On iPhone 4S simulator the build fails with these errors:

> ld: warning: ignoring file /Users/icehawk/Library/Developer/Xcode/DerivedData/Series_Log-ezkivtqtsxghfjbwjdpxuktbujgr/Build/Products/Debug-iphonesimulator/Charts.framework/Charts, file was built for x86_64 which is not the architecture being linked (i386): /Users/icehawk/Library/Developer/Xcode/DerivedData/Series_Log-ezkivtqtsxghfjbwjdpxuktbujgr/Build/Products/Debug-iphonesimulator/Charts.framework/Charts
> Undefined symbols for architecture i386:
>   "Charts.ChartDataEntry.__allocating_init (value : Swift.Double, xIndex : Swift.Int) -> Charts.ChartDataEntry", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
>   "Charts.PieChartDataSet.__allocating_init (yVals : [Charts.ChartDataEntry]?, label : Swift.String?) -> Charts.PieChartDataSet", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
>   "Charts.ChartData.__allocating_init (xVals : [__ObjC.NSObject]?, dataSet : Charts.IChartDataSet?) -> Charts.ChartData", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
>   "type metadata accessor for Charts.PieChartData", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
>   "type metadata accessor for Charts.PieChartView", referenced from:
>       type metadata accessor for Charts.PieChartView! in DetailTVC.o
>   "type metadata accessor for Charts.ChartDataEntry", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
>       type metadata accessor for [Charts.ChartDataEntry] in DetailTVC.o
>   "type metadata accessor for Charts.PieChartDataSet", referenced from:
>       Series_Log.DetailTVC.updateChart (Charts.PieChartView, values : [Swift.Double]) -> () in DetailTVC.o
> ld: symbol(s) not found for architecture i386
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any advice on how to fix this? Thanks in advance.

**Comment by domingguss** [comment]
tried clearing derived data?

**Comment by IceHawk66** [comment]
yes

**Comment by liuxuan30** [comment]
Undefined symbols for architecture i386

Please check your CPU arch and maybe set the correct one.
