### ISSUE TITLE
 Horizontal-BarChart: change color of bar's value

### ISSUE THREAD

**Issue by tanyaberezovsky** [danielgindi/Charts#1167]
Hi Daniael. I'm wondering is it possible to change color of bar's value in Horizontal-BarChart.
For example, how to set different color for numbers 6.9/86.7/66.7.
[https://goo.gl/mXqM2X](url) 

Thanks Daniel.

**Comment by liuxuan30** [comment]
check out ChartsDemo, I suppose there are examples thereby passing colors array into data sets

**Comment by tanyaberezovsky** [comment]
@liuxuan30 Thank you! I fixed it:)
        chartDataSet.valueTextColor = UIColor.whiteColor()
