### ISSUE TITLE
can't add swipe gesture

### ISSUE THREAD

**Issue by ballard** [danielgindi/Charts#1170]
I want to add 2 custom gestures to line chart: pinch and swipe.
Both gesture recognizers are placed on the view with line chart.
Pinch gesture works but swipe not...it can be solved somehow?

updated: using pan instead of swipe works

**Comment by liuxuan30** [comment]
you should provide the handler of pinch and pan gesture in your sub chart view class. There are already these two gestures

**Comment by ballard** [comment]
pan gesture implemented well but .Changed state of pinch is not fired...
