### ISSUE TITLE
Add percent label for pie chart

### ISSUE THREAD

**Issue by stevedubz** [danielgindi/Charts#1172]
I have a pie chart and it displays the correct percents per item. The only problem is that it only displays a number like "55.0" and not "55.0%". I noticed you did this in one of your screenshots for the pie chart but I can't figure out how.

**Comment by kvnbautista** [comment]
//PiePolylineChartViewController`

 NSNumberFormatter *pFormatter = [[NSNumberFormatter alloc] init];
    pFormatter.numberStyle = NSNumberFormatterPercentStyle;
    pFormatter.maximumFractionDigits = 1;
    pFormatter.multiplier = @1.f;
//erase %
    pFormatter.percentSymbol = @"";

**Comment by kvnbautista** [comment]
Add where ever you want to add the percent to.
pFormatter.percentSymbol = @" %";

**Comment by hardikdevios** [comment]
```
  lazy var formatter:NSNumberFormatter = {
        let a = NSNumberFormatter()
        a.numberStyle = .PercentStyle
        a.maximumFractionDigits = 0
        a.multiplier = 1
        a.percentSymbol = " %"
        return a
    }()
```

After that 
`    pieChatView.data?.setValueFormatter(formatter)`

**Comment by stevedubz** [comment]
Thanks guys for the help

**Comment by paulowolking** [comment]
It is still a valid solution ? Me did not work.

**Comment by SylarRuby** [comment]
@hardikdevios  

For: `pieChatView.data?.setValueFormatter(formatter)`

> Cannot convert value of type NumberFormatter to expected argument type IValueFormatter

**Comment by appnupNet** [comment]
@SylarRuby 
let myFormatter = DefaultValueFormatter(formatter: formatter)
pieChatView.data?.setValueFormatter(myFormatter)
