### ISSUE TITLE
how can i add a % on leftAxis

### ISSUE THREAD

**Issue by dawangjiaowolaixunshan** [danielgindi/Charts#1174]
@property (nonatomic,strong) LineChartView *chartLineView;
//    _chartLineView.leftAxis._defaultValueFormatter.roundingMode = kCFNumberFormatterRoundUp;

 _chartLineView.leftAxis.gridLineDashLengths = @[@2.f, @2.f];
    _chartLineView.leftAxis.gridColor = DHHexColor(0xe0dfdf);
    _chartLineView.leftAxis.axisMinValue = minValue;
    _chartLineView.leftAxis.axisMaxValue = max;
   
    _chartLineView.leftAxis.valueFormatter.paddingCharacter = @"%"; // don't work  .

![image](https://cloud.githubusercontent.com/assets/11595694/16371695/bca50c5c-3c7a-11e6-9765-52e66e8ea626.png)

// want this  
![image](https://cloud.githubusercontent.com/assets/11595694/16371705/d44ac518-3c7a-11e6-8a04-93ac8f0e3cf0.png)

**Comment by liuxuan30** [comment]
use valueFormatter

**Comment by mattkorp** [comment]
leftAxis.valueFormatter.negativeSuffix = @" %";
    leftAxis.valueFormatter.positiveSuffix = @" %";
