### ISSUE TITLE
axis values are rounded

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#1175]
when i decrease the chart height, the values are rounded. so if  the values are like 0.9568 then i get 1.0 in all values. how can i solve this?

**Comment by orensha** [comment]
Hey, its not happening when i decrease the size, sorry. it happens when i add another instance of ChartView. now is it more famillier?

**Comment by orensha** [comment]
can two instances of chartView co-exist next to each other?

**Comment by orensha** [comment]
without this happening?

**Comment by liuxuan30** [comment]
you can use axis.valueFormatter your values. don't ask irrelevant questions in one post.
