### ISSUE TITLE
hide description label on charts

### ISSUE THREAD

**Issue by ahmedsafadii** [danielgindi/Charts#1176]
<img width="227" alt="63d38047ead84b36845b66e6e98e6ab0" src="https://cloud.githubusercontent.com/assets/6974081/16372630/39836b30-3c56-11e6-9454-b88f72c55d64.png">

how could i remove that ?

**Comment by ahmedsafadii** [comment]
found it

self.barChartView.descriptionText = ""

**Comment by dbmrq** [comment]
Just in case anybody else is having trouble with this and ends up here, it seems like since 3.0.5 this was changed to `chartView.chartDescription?.text = ""`.

**Comment by simonzwicker** [comment]
Thanks @dbmrq search too long for this little label 🤦‍♂️
