### ISSUE TITLE
To judge whether the initial state

### ISSUE THREAD

**Issue by Sun-Hong** [danielgindi/Charts#1178]
When scaling chart, how to judge whether it returns to the initial state?

**Comment by Sun-Hong** [comment]
the parameters of it "- (void)chartScaled:(ChartViewBase *)chartView scaleX:(CGFloat)scaleX scaleY:(CGFloat)scaleY" doesn't work.

**Comment by DivineDominion** [comment]
What code do you have in `chartScaled:scaleX:scaleY`?

**Comment by liuxuan30** [comment]
you could try chartViewPortHandler.scaleX/scaleY
BTW, chartScaled should work. I checked the code. If you say it's not working,  could you help try debug?
it's in @objc private func pinchGestureRecognized(recognizer: NSUIPinchGestureRecognizer)

If you are not triggering the zooming with gesture, it won't work.
