### ISSUE TITLE
Chart always crash when marker added and highlightFullBarEnabled is true

### ISSUE THREAD

**Issue by jordanshuffman** [danielgindi/Charts#1185]
I have tested this on the demo as well as in my own app, it appears that the combined chart is crashing at  `getEntryForHighlight` 

It appears that `highlight.dataIndex` is -1 and causing an index out of bounds error. Not sure what the proper way to fix this is, as I have inserted a bounds check, but it then crashes inside of `ChartData`

**Comment by xradeon** [comment]
https://github.com/danielgindi/Charts/pull/1094/files

**Comment by liuxuan30** [comment]
This is a known issue. be careful using @xradeon's change, if using 0 has effects on your charts.

**Comment by liuxuan30** [comment]
@jordanshuffman could you please take a look at #737, if this are the same issue?

**Comment by liuxuan30** [comment]
also, could you please provide steps to reproduce with ChartsDemo? I may have some time in the weekend

**Comment by jordanshuffman** [comment]
@liuxuan30 Yes this appears to be the same issue, although in #737 it is irrelevant if you set the highlight to be false on data set and true on others. Even with 1 data set in a combined chart it will crash.

In order to repro, you just need to add in CombinedChartViewController.m
```
BalloonMarker *marker = [[BalloonMarker alloc] initWithColor:[UIColor colorWithWhite:180/255. alpha:1.0] font:[UIFont systemFontOfSize:12.0] insets: UIEdgeInsetsMake(8.0, 8.0, 20.0, 8.0)];
    marker.minimumSize = CGSizeMake(80.f, 40.f);
    _chartView.marker = marker; 
```

in the view did load before `[self updateChartData];`

**Comment by liuxuan30** [comment]
Alright, I finally got some time looking into this..
Yes, CombinedChartView did set self.highlightFullBarEnabled = true by default, and ChartMarker will crash for sure. Because those -1 values.
For now, please set self.highlightFullBarEnabled = false to avoid the crash. I am trying to find a fix

**Comment by liuxuan30** [comment]
So it's not only combined chart, but all charts, as long as `highlightFullBarEnabled = true`

**Comment by danielgindi** [comment]
Is this still happening on Charts 3.0?

**Comment by danielgindi** [comment]
I couldn't reproduce this on Charts 3.0, it anyone experiences this - please re-open the issue.

**Comment by islamshazly** [comment]
highlightValueWithXIndex = true ; 
is still crash on ios 'Charts' ,'2.2.5'

**Comment by liuxuan30** [comment]
2.2.5 will crash for sure. try master.
