### ISSUE TITLE
[Bug] Double BarChart second value text mispaced

### ISSUE THREAD

**Issue by skywinder** [danielgindi/Charts#1191]
I would like to create chart as in screenshot^
![screen shot 2016-06-29 at 11 07 39](https://cloud.githubusercontent.com/assets/3356474/16445158/0f599312-3dea-11e6-8a3e-ca8cfc7aa826.png)

But can't place label in right position in case of `0`
Please, have a look at screenshot in comment for details

**Comment by skywinder** [comment]
Update: I found a solution, by adding 2 values in one `BarChartDataEntry`

But now I found a Bug: If bottom (second) value is 0 - them text is not displayed in the bottom, and overlapped top text. Please have a look at screenshot right value as example. I can provide code, to reproduce this issue, if needed.

![screen_shot_2016-06-29_at_18_16_40](https://cloud.githubusercontent.com/assets/3356474/16457999/2d2c9e8e-3e26-11e6-9d81-b67992f2c16b.jpg)

**Comment by petester42** [comment]
Thanks for the bug report!

**Comment by skywinder** [comment]
@petester42 I already fixed it. Please wait for my little fix for this issue in 5 minutes 😉

**Comment by skywinder** [comment]
🎉

**Comment by danielgindi** [comment]
@PhilJay do you know anything about this bug?

**Comment by PhilJay** [comment]
Looks really weird, but I have not seen it anywhere personally.

Not sure it's a bug either. Stack values >= 0 are placed to the left of the zero line in stacked bars, negative values below the zero line. Workaround could be to add the "4" of the last bar as "-4" and then format it to "4".

**Comment by skywinder** [comment]
@PhilJay It could be my option for workaround. Bit I found proper solution to fix this bug. please kindly check #1195 do you think, that this change could produce potential bugs?
