### ISSUE TITLE
Trim the legend view 

### ISSUE THREAD

**Issue by a-radwan** [danielgindi/Charts#1192]
If we have too many datasets , the legend grows and shrink the chart view . 
I tried to set  to 0.2 but it didn't work correctly (the legend appeared on the above the chart).

I read that you don't want to support scrolling. 

So is it possible to trim the legend ? or to set a limit for number if lines ,height or values.

**Comment by liuxuan30** [comment]
I guess you have to modify the code... we are having feedbacks for legend, but short of people to improve.
