### ISSUE TITLE
reduce height of grids

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1198]
![screen shot 2016-06-30 at 11 52 32 am](https://cloud.githubusercontent.com/assets/20103595/16478845/087e373e-3eba-11e6-82b9-662380b7c32a.png)
I want to reduce grids height in chart, how can I?
plz help me

**Comment by liuxuan30** [comment]
you mean x axis or y axis? you are giving a horizontal bar chart, so height and width is flipped..

**Comment by Prathame5h** [comment]
![screen shot 2016-06-30 at 11 52 32 am](https://cloud.githubusercontent.com/assets/20103595/16551426/3f67d7e0-41d6-11e6-8a37-944933af90cd.png)

can we manage this height which in circle?

**Comment by liuxuan30** [comment]
hmm, I don't think so... this is calculated, and related to your view's height. 
like section width = total width / count

**Comment by danielgindi** [comment]
Each grid strip width equals 1.0 on the X axis and 1.0 on the Y axis.
If you want the Bars to be wider relative to those strips, you could adjust the `barWidth` (or `barSpacing`, in Charts 2.0)
