### ISSUE TITLE
Remove labels from Radar Chart

### ISSUE THREAD

**Issue by WayneBruton** [danielgindi/Charts#1199]
Hi,

I am trying to remove the labels on a radar chart.
![screen shot 2016-06-30 at 10 36 21 am](https://cloud.githubusercontent.com/assets/14802667/16482084/99b43002-3eae-11e6-9153-f125b3a24870.png)

I have been trying for ages but cannot find it. I am sure it is something rather simple. As can be seen on the screenshot, all the labels for the data are very busy and not really needed.

Any help would be most appreciated.

Kind regards

Wayne

**Comment by liuxuan30** [comment]
dataSet.isDrawValuesEnabled or data.setDrawValues(false)

**Comment by liuxuan30** [comment]
just try to play with ChartsDemo, it's there
