### ISSUE TITLE
drawvalue when stack is selected

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1200]
![screen shot 2016-06-30 at 5 16 29 pm](https://cloud.githubusercontent.com/assets/20103595/16487131/8e2583a2-3ee6-11e6-9fbb-e1d9cc854924.png)
I want to drawvalue when particular stack is selected, so how can i?

**Comment by liuxuan30** [comment]
1. use chart marker
2. customize the highlight logic to do so
depends on your requirement

**Comment by Prathame5h** [comment]
is there demo in swift language which i understand?

**Comment by liuxuan30** [comment]
maybe google, there will be
