### ISSUE TITLE
Support Realm 1.0.1 (Objective-C)

### ISSUE THREAD

**Issue by SketchK** [danielgindi/Charts#1201]
When I created my project and pod install 'Charts/Realm', something was wrong.  
the information is 
```
- `Realm` required by `Podfile`
- `Realm (= 1.0.1)` required by `Podfile.lock`
- `Realm (= 0.97.0)` required by `RealmSwift (0.97.0)`
- `Charts/Realm` required by `Podfile`
```
As we all known, the newest version of Realm is 1.0.1, so can you support the newest version of Realm!
Thank you

**Comment by liuxuan30** [comment]
would you be able to file a PR?

**Comment by liuxuan30** [comment]
Realm 1.0.2 has merged into master. And we don't support Realm 1.0.1 (Objective-C)

**Comment by SketchK** [comment]
Good Job！！！ Thank you
