### ISSUE TITLE
Can we use custom image instead of Circle in line chart?

### ISSUE THREAD

**Issue by tejas-ardeshna** [danielgindi/Charts#1206]
1) I am creating line chart for temperature, so i need to set thermometer image instead of point in graph. is that possible?
2) I want to change BG like this is that possible:

![screen shot 2016-07-01 at 12 12 57 pm](https://cloud.githubusercontent.com/assets/12891361/16513840/71ae793c-3f85-11e6-8c3b-06ef4a70ff58.png)

**Comment by liuxuan30** [comment]
#629, https://github.com/danielgindi/Charts/issues/641

**Comment by abjurato** [comment]
This feature is enabled by PR #1261

**Comment by stardustWK** [comment]
![image](https://user-images.githubusercontent.com/9332833/32322223-c27f6582-bf91-11e7-8441-2ce1984b719e.png)
any idea about this chart
