### ISSUE TITLE
HorizontalBarChart in Combined Chart

### ISSUE THREAD

**Issue by ashish1703** [danielgindi/Charts#1207]
How can i draw a horizontal bar chart with lines using combined bar chart.
 Please help..!!

**Comment by liuxuan30** [comment]
currently the answer is no support for this. If you want it, you have to implement on your own.
BTW, what's the purpose of using a horizontal bar chart with a line chart? I don't see it's easy to read.

Only a few people asked for this, but no one gives a good reason that this kinds of charts are meaningful.
