### ISSUE TITLE
I have a question BarChart

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1208]
![f5bbadb2-e9b7-4b71-9914-eadfc9c104fa](https://cloud.githubusercontent.com/assets/13211527/16516615/8b72ea9e-3fab-11e6-9105-ecf7ee0a5517.png)

![5a1aa736-aa16-4493-b402-5a546ea6d0be](https://cloud.githubusercontent.com/assets/13211527/16516765/689e2118-3fac-11e6-8189-933e411161f0.png)

As shown, the BarChart why I have the background color?

**Comment by liuxuan30** [comment]
I tried with ChartsDemo, not reproducing. Can you double check with ChartsDemo?
I put below code in stacked  bar chart view controller `- (void)setDataCount:(int)count range:(double)range()` func:

```Objective-C
    else
    {
        set1 = [[BarChartDataSet alloc] initWithYVals:yVals label:@"Statistics Vienna 2014"];
//        set1.colors = @[[UIColor redColor]]; <--- both are fine, but you should use colors for stacked bar chart
        [set1 setColor:[UIColor redColor]];
        set1.stackLabels = @[@"Births", @"Divorces", @"Marriages"];
...
```

**Comment by shenyufei** [comment]
Not the case, this is BarChart, not Stacked bar, you take a closer look at my code is barchardataEntry (value), not values, but why he had the appearance of stacked bar? I have seen ChartsDemo, this is CombinedChart.    @liuxuan30

**Comment by liuxuan30** [comment]
well.. I don't know what have you changed, but one simple fact is that ChartsDemo is fine. I am not using ChartsDemo as an excuse, but it's much more efficient you can try it and compare with your code. 

You could try add some breakpoint in bar chart renderer to see how it renders your bars.

**Comment by shenyufei** [comment]
I checked for a long time, but still did not check out what is wrong, I did not set anything else, I again wrote a Demo, but still, as the code is very simple, I do not see where the wrong, why is it so?

`
let month:[String] = ["1", "2", "3", "4", "5", "6", "7", "8", "9",
                          "10", "11", "12"]
    
    @IBOutlet weak var comboChart: CombinedChartView!
    override func viewDidLoad() {
        super.viewDidLoad()
    setchart()
        // Do any additional setup after loading the view.
    }

func setchart()  {
        let data = CombinedChartData(xVals: month)
        data.lineData = returnLine()
        data.barData = returnBar()
        comboChart.data = data
        
    }

    func returnLine() -> LineChartData {
        let d = LineChartData()
        var entries = [ChartDataEntry]()
        for i in 0...month.count - 1{
            let val1 = ((Double)(arc4random_uniform(UInt32(35))) + 100)
            entries.append(ChartDataEntry(value: val1, xIndex: i))
        }
        
        let set = LineChartDataSet(yVals: entries, label: "LineDataSet")
        set.setColor(UIColor.greenColor())
        set.lineWidth = 2.5
        set.axisDependency = .Right
        d.addDataSet(set)
        return d
    }
    
    func returnBar() -> BarChartData {
        let d = BarChartData()
        var entries = [BarChartDataEntry]()
        for i in 0...month.count - 1{
            let val1 = ((Double)(arc4random_uniform(UInt32(35))) + 100)
            entries.append(BarChartDataEntry(value: val1, xIndex: i))
        }
        let set = BarChartDataSet(yVals: entries, label: "BarDataSet")
        set.setColor(UIColor.blueColor())
        set.axisDependency = .Left
        d.addDataSet(set)
        return d
    }
`

**Comment by liuxuan30** [comment]
I believe you turned on `drawBarShadowEnabled`. It's true by default for combined chart.

**Comment by liuxuan30** [comment]
I am filing a PR for the default value
