### ISSUE TITLE
I have an immature small suggestion

### ISSUE THREAD

**Issue by dsencheng** [danielgindi/Charts#1209]
I think `_autoScaleMinMaxEnabled...` should be after `calcModulus ()` in `BarLineChartViewBase.drawRect()`, because _leftAxis._axisMinimum will be recalculated。`YAxisRenderer?.computeAxis(yMin:yMax:)` no recalculation。

Rarely appeared the error Ymax text in `YAxis`
sorry, english is not good.

**Comment by danielgindi** [comment]
Can you test if you experience a problem like this in Charts 3.0?

**Comment by danielgindi** [comment]
@PhilJay I think that `autoScaleMinMaxEnabled` does not work at all in 3.0

**Comment by PhilJay** [comment]
I am afraid that was missed.
It was related to the way the `calcMinMax()` method used to work, am I right? Where it allowed to provide a minimum and maximum "x-position" to calculate the min and max values.

**Comment by danielgindi** [comment]
Yeah... We need to find a way to allow recalculating min/max as the viewport moves, according to the lowest/highest visible x

**Comment by PhilJay** [comment]
Maybe we can provide an additional `calcMinMax(float minX, float maxX)` method for the `ChartData` class?

**Comment by danielgindi** [comment]
Or maybe make the `calcMinMax` test for `autoScaleMinMaxEnabled`?

**Comment by PhilJay** [comment]
So you would move the `autoScaleMinMaxEnabled` flag to the `ChartData` class? Or how would you do the "testing"?

**Comment by danielgindi** [comment]
Oh yeah that's problematic lol

So change the signature to `calcMinMax(float minX, float maxX)` like you suggested, and add an overload on `BarLineChartViewBase`?

**Comment by PhilJay** [comment]
Yes something like that. Good thing is we have methods like `dataSet.getEntryForXValue(...)` which allow us to find the first and last `Entry` to be used for calculation based on the provided `minX` and `maxX`.

**Comment by PhilJay** [comment]
Android fixes are out (2 commits):

 - https://github.com/PhilJay/MPAndroidChart/commit/336dfb93e5c6cb681aa8c660de780617a90480be

- https://github.com/PhilJay/MPAndroidChart/commit/1bbf4be1eed520a1da075d2e5a5d4cfb686ff4bd
