### ISSUE TITLE
Error when using Charts library with Xcode 8 bet and Swift 3.0

### ISSUE THREAD

**Issue by ash-1202** [danielgindi/Charts#1210]
Updated the charts library with pods to version 2.2.5 and when i am compiling in xcode 8 beta it gives error that code needs to converted to Swift 3.0. 

Can you let us know if the Charts library has been ported to Swift 3.0 or not.

**Comment by CIsOnTop** [comment]
Same issue here and when doing the convert it still pops up with hundreds off errors... this is a big issue for my project that already had Charts working great in it in Swift 2.0...

**Comment by liuxuan30** [comment]
check out Swift-3.0/Swift-2.3 branch, someone already filed a PR. 

As you see swift has many changes with each version, and not backward compatible, so one clear message is, until Xcode 8 or Swift 3.0 is officially released, the master branch won't merge swift 3.0, same rule for Swift 2.3
