### ISSUE TITLE
how to set marker for line chart

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1211]
![screen shot 2016-07-02 at 2 40 21 pm](https://cloud.githubusercontent.com/assets/20103595/16539511/0513be02-4063-11e6-9019-56db2fad4d8c.png)

how to set marker for line chart values in swift can you please send me code?

**Comment by liuxuan30** [comment]
check ChartsDemo.

**Comment by Prathame5h** [comment]
i want to implement it in swift not in objective - c, i don't know about objective-c, so please help me

**Comment by liuxuan30** [comment]
well, you should be fine read Objc code, the function names are all the same. BTW, ChartMarker is pure swift code.
