### ISSUE TITLE
How can I not be highlighted when I touch ended ? 

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1216]
in other words,How do I listen for my fingers in the process of moving the highlight loosened
You can monitor the status of the gesture ?

**Comment by liuxuan30** [comment]
```   
 /// Called when a value has been selected inside the chart.
    /// - parameter entry: The selected Entry.
    /// - parameter dataSetIndex: The index in the datasets array of the data object the Entrys DataSet is in.
    optional func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: ChartHighlight)
    
    // Called when nothing has been selected or an "un-select" has been made.
    optional func chartValueNothingSelected(chartView: ChartViewBase)
```
take a closer look at how the delegate methods are implemented

**Comment by MonkeyRing** [comment]
##### Thank you for your answer.

I know these two delegate methods , but these two methods and can not play real-time monitoring whether the finger left the screen . I need to know ```panGes.state == Began || panGes.state == Ended ```such sensing mechanism

**Comment by liuxuan30** [comment]
then you probably could provide your own gesture handler for fine-grained control? The handlers are private, so you can provide you own
