### ISSUE TITLE
UnsafeMutablePointer.moveInitializeFrom with negative count

### ISSUE THREAD

**Issue by MansoorB** [danielgindi/Charts#1218]
UnsafeMutablePointer.moveInitializeFrom with negative count

Getting this error from time to time in class ChartYAxisRenderer.swift class. How does one solve this?

**Comment by liuxuan30** [comment]
Could you give more info? like trace, context, reprodue steps maybe? Exist in ChartsDemo?

**Comment by MansoorB** [comment]
Should present with more information in first hand. Anyways, here it comes

Below line gets printed to the console. This is at line 155 from class ChartYAxisRenderer
"fatal error: UnsafeMutablePointer.moveInitializeFrom with negative count"


In the debugger navigator there is Thread 1 with following 
"2 ChartXAxisRenderer.renderGridLines(context: CGContext) -> ()" 

When visiting the issue above. It takes me to line 250 at class and method mentioned above. 
Line 250 is 
"for i in self.minX.stride(to: self.maxX, by: xAxis.axisLabelModulus)"

"3 BarLineChartViewBase.drawRect(CGRect) -> ()" takes me line 221 at class it was mentioned.
The line is "_xAxisRenderer?.renderGridLines(context: context)"



I guess its crashes when I pass data to "LineChartData(xVals: [String?]?, dataSet: IChartDataSet?)". The thing is the array that being passed do not have negative value.

**Comment by MansoorB** [comment]
Now it points at "yAxis.entries.removeRange(n..<yAxis.entries.count)" at class ChartYAxisRenderer and method computeAxisValues.

**Comment by liuxuan30** [comment]
eh, any special value to reproduce? a sample is even better. With the info I am not to say what's the problem..

**Comment by danielgindi** [comment]
Does this still happen with Charts 3.0?
