### ISSUE TITLE
Horizontal bar chart crashing after tap when more than one data set

### ISSUE THREAD

**Issue by dvd110** [danielgindi/Charts#1221]
I have tested this on the demo project. To reproduce modify HorizontalBarChartViewController.m with two data sets:

-(void)setDataCount:(int)count range:(double)range
{
    NSMutableArray *xVals = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < count; i++)
    {
        [xVals addObject:months[i % 12]];
    }
    
    NSMutableArray *yVals1 = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < count; i++)
    {
        double mult = (range + 1);
        double val = (double) (arc4random_uniform(mult));
        [yVals1 addObject:[[BarChartDataEntry alloc] initWithValue:val xIndex:i]];
    }
    
    NSMutableArray *yVals2 = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < count; i++)
    {
        double mult = (range + 1);
        double val = (double) (arc4random_uniform(mult));
        [yVals2 addObject:[[BarChartDataEntry alloc] initWithValue:val xIndex:i]];
    }
    
    BarChartDataSet *set1 = nil;
    BarChartDataSet *set2 = nil;
    
    if (_chartView.data.dataSetCount > 0)
    {
        set1 = (BarChartDataSet *)_chartView.data.dataSets[0];
        set1.yVals = yVals1;
        _chartView.data.xValsObjc = xVals;
        [_chartView notifyDataSetChanged];
    }
    else
    {
        set1 = [[BarChartDataSet alloc] initWithYVals:yVals1 label:@"DataSet"];
        set1.barSpace = 0.35;
        
        set2 = [[BarChartDataSet alloc] initWithYVals:yVals2 label:@"DataSet2"];
        set2.barSpace = 0.35;
        
        NSMutableArray *dataSets = [[NSMutableArray alloc] init];
        [dataSets addObject:set1];
        [dataSets addObject:set2];
        
        BarChartData *data = [[BarChartData alloc] initWithXVals:xVals dataSets:dataSets];
        [data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:10.f]];
        
        _chartView.data = data;
    }
}

Suggestion: 
HorizontalBarChartHighlighter.swift, line 79. I think it should be 'super.getXIndex(x)' instead of 'getXIndex(x)'.

**Comment by liuxuan30** [comment]
Two things:
1. what's the crash trace?
2. towards your suggestion, is this related to crash or not? #1213 is pending for your suggestion

**Comment by dvd110** [comment]
Yes it's related to crash. #1213 is the same issue. Thanks.
