### ISSUE TITLE
two CombinedChartView's in the same screen changes axis format in the first 

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#1222]
Hi, you told me to use NSNumberFormater but the axis number  changes regardles of the number formatter.

so you can see the chart before i'm adding the second graph.
![screen shot 2016-07-04 at 7 15 02 pm](https://cloud.githubusercontent.com/assets/16323011/16566281/c27ddb76-421b-11e6-866d-aa8dd403f991.png)

and when im adding the second graph the axis are rounded to 1
![screen shot 2016-07-04 at 7 15 22 pm](https://cloud.githubusercontent.com/assets/16323011/16566370/6ad6931c-421c-11e6-9160-0bd0f37a56b8.png)

i debugged it and saw that its happening when i initialize the second chart's chartData with a diefferent data. what do you say?

**Comment by liuxuan30** [comment]
"when im adding the second graph the axis are rounded to 1" 
if you create a new chart, you have to set up the value formatter again.
You may want to check your code
