### ISSUE TITLE
Unable to run on iOS/tvOS 10.0 beta

### ISSUE THREAD

**Issue by EpicDraws** [danielgindi/Charts#1223]
After doing the automatic conversion to Swift 2.3, I am unable to launch in either the simulator or on device on both iOS and tvOS due to the following issue:

dyld: Symbol not found: __TMVVSS17UnicodeScalarView9Generator

Once I was able to hack around this issue, I got another similar error around DisabledRangeIndex which I couldn't find in code to try to work around. Did all the standard steps: clean, delete derived data, reset simulator, etc. to no avail. I am presuming this is an issue with either the beta or this library.

**Comment by liuxuan30** [comment]
I don't see this on my side, especially with swift 2.3. 
You can take a look at swift 2.3 and 3.0 branch, no one reports issue like yours. So I guess maybe you should narrow down the issue with more details, like which platform has the issue, can we reproduce it with ChartsDemo, etc.

**Comment by liuxuan30** [comment]
I assume `__TMVVSS17UnicodeScalarView9Generator`and `DisabledRangeIndex` is your code, not this library
