### ISSUE TITLE
BarChartView bars do not start at the x-axis.

### ISSUE THREAD

**Issue by jleach** [danielgindi/Charts#1225]
I can not get an iOS-charts bar chart to put the bars zero (the bottom of the bars) on the x-axis. They seem to float just above the x-axis. As you can see in the attached image the bars are not sitting flush with the x-axis. One difference in my sample project is, if you look at the screenshot (in the screenshots directory) the y-axis zero label is on the x-axis while in the attached image it floats above the x-axis.

This issue might relate to #947

I've created this StackOverflow issue for public support and to better illustrate the issue
http://stackoverflow.com/review/suggested-edits/12906546

And I've created this GitHub project to re-create the issue:
https://github.com/jleach/BarChartBug

![eatqp](https://cloud.githubusercontent.com/assets/390891/16603817/18257ada-42d4-11e6-972a-ab86e4f6cd09.jpg)

**Comment by liuxuan30** [comment]
for newer release, you have to call axisMinValue = 0, startAtZero is deprecated

**Comment by jleach** [comment]
@liuxuan30 Why did you close this issue? startAtZero is *not* being used. I have `axisMinValue = 0` in both the example project on GitHub and when I created the image above.

**Comment by liuxuan30** [comment]
@jleach I have updated my first post. Does it solve your issue?

**Comment by liuxuan30** [comment]
BTW, I can't compile your project, saying 
```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
```

**Comment by jleach** [comment]
@liuxuan30 I tried both your suggestions and it has no effect. 

Do you mean check in the Pods directory or just add Charts directly to the project?

**Comment by liuxuan30** [comment]
I just need to know how to compile your project, it's complaining about pod, but I don't know what I have to do

**Comment by liuxuan30** [comment]
alright, I went to your project folder and run pod install and waiting Setting up CocoaPods master repo.
Now is my work time, so hopefully I can get you something in the noon or maybe later.

**Comment by liuxuan30** [comment]
@jleach pod install stucks like forever

**Comment by jleach** [comment]
@liuxuan30 I just checked in the Pods directory; it should not have any more dependencies. Try a `git pull` and see if that solves the problem.

**Comment by liuxuan30** [comment]
@jleach man, `dataSet.axisDependency = .Right`
```
        // create a data set
        let dataSet = BarChartDataSet(yVals: data, label: "")
        dataSet.drawValuesEnabled = false
        dataSet.colors = barColors
        dataSet.axisDependency = .Right <-- where is it?
        return dataSet
```

**Comment by liuxuan30** [comment]
I spend 3x time trying to get your project running, at last I create a new project and copy your code instead and fix the storyboard missing connections.
Next time, please create a one-click runable project.. :)

**Comment by jleach** [comment]
That was it. I appreciate your help; I would not have caught this. I assume that because I did `chartView.leftAxis.enabled = false` and `chartView.rightAxis.enabled = true` that it new my intention was to have a right axis but I see now it needs to be sent in multiple places. Thanks again.
