### ISSUE TITLE
Location have a little problem

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#1228]
![1ed65815-4b54-472f-bc31-7ab952cf633a](https://cloud.githubusercontent.com/assets/13211527/16609406/94d90f26-4386-11e6-8ae6-b4b3a8d89aa4.png)
As shown,This is a cell, constraint I set width = screenWidth, but he was shifted.

I also wrote other, such MultipleLine, StackedBar, CombinedChart, settings are the same, but there is no problem, I don't know which property is wrong? I did not set other things.

![4d6f06e1-f415-4ebb-9cf4-be8b73cb4643](https://cloud.githubusercontent.com/assets/13211527/16609475/046b9d68-4387-11e6-8169-3d118d8b4405.png)

![890572f6-c9ac-4750-99c3-868f0798fbeb](https://cloud.githubusercontent.com/assets/13211527/16609482/11fbceee-4387-11e6-9d51-79b7a22670ec.png)

![3242526d-030d-481a-bfff-7e25b23e0c98](https://cloud.githubusercontent.com/assets/13211527/16609579/cf7d297c-4387-11e6-8d15-ba913cae57e0.png)

**Comment by liuxuan30** [comment]
well the first chart left y axis labels are all 0s. you can start from there

**Comment by shenyufei** [comment]
oh, I found my problem, I did want to set barmaxWidth, so add the code. That was my mistake.

`chartView.setYAxisMaxWidth(ChartYAxis.AxisDependency.Left, width: 5.0)`
