### ISSUE TITLE
About the Lable number of x and y

### ISSUE THREAD

**Issue by SuperGuo751** [danielgindi/Charts#1231]
Hello blogger
How to do can limit the number of '_leftAxis.Value' And '_xAxis.axisLabelModulus'
I have a number of data, but I just want to in the x: 0 and x: at the end of show '_xAxis. Label'
'x' default is 6 But I just want 3 do
Hope you can help me, thank you.

**Comment by SuperGuo751** [comment]
My English is not very good, hope you can understand.

**Comment by liuxuan30** [comment]
call setLabelsToSkip()
