### ISSUE TITLE
xVals隐藏问题

### ISSUE THREAD

**Issue by junwangInChina** [danielgindi/Charts#1232]
![2016-07-07 18 21 43](https://cloud.githubusercontent.com/assets/2849111/16650240/c16a9c14-446f-11e6-83b2-1999f349c4fe.png)
使用图表时，会自动生成这个，能隐藏么？

**Comment by wxy325** [comment]
chartView.legend.enabled = false

**Comment by junwangInChina** [comment]
谢谢。
