### ISSUE TITLE
Label value is cut off in horizontal bar

### ISSUE THREAD

**Issue by hiralnaik** [danielgindi/Charts#1235]
Hi there

First of all awesome library. I recently started using this library in my project. I am having issue with label on bar graph. For some reason, label text is cut off in the horizontal bar graph. Could you please help me with it ?

For heads up, value is cutting of for NUMBER not the "Year" text.

<img width="231" alt="screen shot 2016-07-07 at 9 51 44 pm" src="https://cloud.githubusercontent.com/assets/7863227/16677749/a912e07c-448d-11e6-9ce5-5fb9fa6fbda4.png">

Thanks
Hiral

**Comment by hiralnaik** [comment]
Oops resolved.

**Comment by araujotadeu** [comment]
@hiralnaik I have the same problem, how did you solve it?

**Comment by hiralnaik** [comment]
@araujotadeu 

`self.chartView.extraRightOffset = CGFloat(30.0)
self.chartView.extraTopOffset = CGFloat(30.0)
self.chartView.extraLeftOffset = CGFloat(30.0)
self.chartView.extraBottomOffset = CGFloat(30.0)`

you can set offset for each direction.

Thanks
Hiral

**Comment by araujotadeu** [comment]
Thank for the help Hiral!
