### ISSUE TITLE
Now working if “Compile Sources As” option to “Objective C++”

### ISSUE THREAD

**Issue by RevanthReddyT** [danielgindi/Charts#1237]
I have a project which has been written in Objectic-C and C++. When we use C++ we have changed “Compile Sources As” option to “Objective C++” in Build settings. i am not able to use Charts in by application even i have created bridge.
The project is not getting identified because of “Compile Sources As” option to “Objective C++”.
Is there any way i can you Charts in my project.

**Comment by liuxuan30** [comment]
http://stackoverflow.com/questions/32541268/can-i-have-swift-objective-c-c-and-c-files-in-the-same-xcode-project can this help?
