### ISSUE TITLE
only Have a X-Value,the PieChart too bigger, twinkle

### ISSUE THREAD

**Issue by roselind** [danielgindi/Charts#1239]
If PieChart only have 1  X-Value ,  the PieChart  is loaded , too larger .
Beyond the set frame,  twinkle
Sorry I do not know how to upload GIF, please open  https://github.com/roselind/pieChart

**Comment by roselind** [comment]
[https://github.com/roselind/pieChart](url)

**Comment by danielgindi** [comment]
Which version does this happen with?

**Comment by roselind** [comment]
pod 'Charts', '~> 2.2.3'

**Comment by danielgindi** [comment]
That's old. Very old.
You didn't even bother to search for old issues, to see it we knew about it, if it was fixed, Nd if there were releases... Did you?

**Comment by roselind** [comment]
OK，I  try  update Version. it not this issue, thank you !
I found it old version  setting this property： 
   chartView.rotationEnabled = NO;
   chartView.highlightPerTapEnabled = NO;
 this issue does not appear.
