### ISSUE TITLE
Value not display for Multiple DataSet in LineChart

### ISSUE THREAD

**Issue by nhjariwala** [danielgindi/Charts#1240]
Earlier I have only 1 DataSet and it works perfectly its showing value for chart. But later I added another DataSet then value disappear. I have tried to implement several thing like:

            set1.drawValuesEnabled = true
            set2.drawValuesEnabled = true
            xAxis.drawLabelsEnabled = true

But still no success.
Thanks

**Comment by liuxuan30** [comment]
well.. first thing I will suggest is checking out ChartsDemo. Should be your code issue

**Comment by nhjariwala** [comment]
Please have look the code

            lineChartView.descriptionText = ""
            lineChartView.noDataText = "No Data"
            lineChartView.drawGridBackgroundEnabled = false
            
            lineChartView.dragEnabled = false
            lineChartView.setScaleEnabled(false)
            lineChartView.pinchZoomEnabled = false
            
            let xAxis:ChartXAxis = cell.lineChartView.xAxis
            xAxis.labelPosition = ChartXAxis.LabelPosition.Bottom
            xAxis.labelFont = UIFont.systemFontOfSize(10.0)
            xAxis.drawGridLinesEnabled = false
            xAxis.setLabelsToSkip(0)
            xAxis.drawLabelsEnabled = true

            
            let leftAxis: ChartYAxis = cell.lineChartView.leftAxis
            leftAxis.removeAllLimitLines()
            leftAxis.axisMinValue = 0.0
            leftAxis.gridLineDashLengths = [5.0, 5.0]
            
            lineChartView.rightAxis.enabled = false
            lineChartView.animate(xAxisDuration: 1.5, easingOption: .EaseInOutQuart)
            
            var xVals = Array<String>()
            for i in 0  ..< xData.count  {
                xVals.append(xData[i])
            }
            
            var yValsTemp = Array<Float>()
            for var i = 1 ; i <= giftAidData.count ; i += 1 {
                yValsTemp.append(giftAidData[i]!)
            }
            
            var zValsTemp = Array<Float>()
            for var i = 1 ; i <= giftAidDataLastYear.count ; i += 1 {
                zValsTemp.append(giftAidDataLastYear[i]!)
            }
            
            var yVals = Array<ChartDataEntry>()
            for i in 0  ..< yValsTemp.count  {
                yVals.append(ChartDataEntry(value: (String(stringInterpolationSegment: yValsTemp[i]) as NSString).doubleValue, xIndex: i))
            }
            
            var zVals = Array<ChartDataEntry>()
            for i in 0  ..< zValsTemp.count  {
                zVals.append(ChartDataEntry(value: (String(stringInterpolationSegment: zValsTemp[i]) as NSString).doubleValue, xIndex: i))
            }
            
            let set1: LineChartDataSet = LineChartDataSet(yVals: yVals, label: "This year")
            set1.setColor(UIColor(red: 255/255, green: 80/255, blue: 88/255, alpha: 1))
            set1.setCircleColor(UIColor(red: 255/255, green: 80/255, blue: 88/255, alpha: 1))
            set1.lineWidth = 1.0
            set1.circleRadius = 4.0
            set1.drawCircleHoleEnabled = true
            set1.valueFont = UIFont.systemFontOfSize(9.0)
            set1.fillAlpha = 62/255.0
            set1.drawValuesEnabled = true
            set1.fillColor = UIColor.greenColor()
            
            let set2: LineChartDataSet = LineChartDataSet(yVals: zVals, label: "Last year")
            set2.setColor(UIColor(red: 0/255, green: 184/255, blue: 226/255, alpha: 1))
            set2.setCircleColor(UIColor(red: 0/255, green: 184/255, blue: 226/255, alpha: 1))
            set2.lineWidth = 1.0
            set2.circleRadius = 4.0
            set2.drawCircleHoleEnabled = true
            set2.valueFont = UIFont.systemFontOfSize(9.0)
            set2.fillAlpha = 62/255.0
            set2.drawValuesEnabled = true
            set2.fillColor = UIColor.greenColor()
            
            var set = Array<LineChartDataSet>()
            set.append(set1)
            set.append(set2)
            
            let data: LineChartData = LineChartData(xVals: xVals, dataSets: set)
            lineChartView.data = data

**Comment by nhjariwala** [comment]
@liuxuan30 I have checked the demo but still no success and I have posted my code here can you please give me some hint ? Because I have already tried what demo suggest.

Thanks hoping for best

**Comment by liuxuan30** [comment]
I'm sorry, the code above seems fine with only a glimpse.. what you need to do is to debug the code to see, if the two data sets had valid entries.
If you have a sample project, I could help, but with only the code, I can't say what's wrong..

**Comment by nhjariwala** [comment]
@liuxuan30 Thanks for your hint. I had try to debug the code and found something really strange. I have 53 data on `XAxis` and have 2 `DataSet` for that. What I found was:

- I have disable `_chartView.setScaleEnabled(false)` thus I was not able to scale the chart if I enable it after single tap on chart the data will appear.

- If I display only 49 data (i.e 49 data on `XAxis`) then the value appear but more than 49 data on "XAxis" data will not appear (in the case of `_chartView.setScaleEnabled(false)`)

I don't want user to scale the chart thus I have to disable `_chartView.setScaleEnabled(false)` and want to display all the 53 data on `XAxis`.

Any idea .. ?

**Comment by liuxuan30** [comment]
Remember all data sets share the same x values, I don't know how your data lay out. Usually you don't have to set setScaleEnabled. It will display all values at beginning. What you could do is, debug ChartsDemo dual line charts to see how it works.

**Comment by johanntony** [comment]
i think i found the same problem how to do it .the data is correct but graph is not

**Comment by alrose** [comment]
I found the solution. 
set the Chart maxVisibleCount to a bigger number.
