### ISSUE TITLE
CandleChartView screen  show count limit

### ISSUE THREAD

**Issue by LuoPengFei** [danielgindi/Charts#1243]
I want to draw a CandleStickChartView as follow:
<img width="321" alt="2016-07-13 11 02 18" src="https://cloud.githubusercontent.com/assets/10494635/16792221/fe4da968-48f8-11e6-891f-de4f7bbe1a07.png">

but get the following chart after  show data directly
<img width="368" alt="2016-07-13 11 02 05" src="https://cloud.githubusercontent.com/assets/10494635/16792268/8eb7196c-48f9-11e6-8789-e5fc359e78b8.png">
 someone can provide some ideas I want to let me draw the chart?

**Comment by liuxuan30** [comment]
call setVisibleXRangeMaximum() after setting chart data
