### ISSUE TITLE
Line Chart label count not calculating properly

### ISSUE THREAD

**Issue by rameswar54** [danielgindi/Charts#1244]
```
multiLineChartView.leftAxis.axisMinValue = 0
multiLineChartView.leftAxis.axisMaxValue = 100
multiLineChartView.leftAxis.labelCount = 4
```

If label count set to either 3 or 4, both shows the same result i.e 
![chart issue](https://cloud.githubusercontent.com/assets/7326600/16794089/401f86c8-48f3-11e6-93a1-5f7e539b6ad5.png)

Which is correct for label count `3`. However it should show the range `[25, 50, 75 and 100]`, if the label count is `4` I believe. Correct me if I'm wrong.

Label count `5` with the above min and max values provides the range` [20, 40, 60, 80 and 100]`.

**Comment by liuxuan30** [comment]
have you turned on yAxis.isForceLabelsEnabled?

**Comment by rameswar54** [comment]
Thanks. It worked by forcing the label count and then changing the label count to 5.

I have one more question, though it is different just adding here the [link](http://stackoverflow.com/questions/38345008/charts-disabling-hiding-the-first-node-point-in-line-chart). The feature asked in the link, is it possible or else can it be taken as an idea.

Thanks again for the help.

**Comment by liuxuan30** [comment]
hiding the first circle seems not freq. asked, so currently the quick way is to override the loop ignoring i = 0
