### ISSUE TITLE
Line Chart : Can I drag a vertical line to any point on the screen and get values? Instead of individual touches

### ISSUE THREAD

**Issue by VidhiMittal2012** [danielgindi/Charts#1246]
Hi Am working on line charts and wish to have a functionality where the user can simply drag a line on the chart to the point he wants to and that should update a label instead of a single touch. is this possible?

**Comment by liuxuan30** [comment]
you want drag a line to another place? This seems a standalone logic to do so. Think about the UICollectionViewCell dragging to reorder. Is that the similar behavior?

**Comment by VidhiMittal2012** [comment]
![screen shot 2016-07-14 at 2 36 57 pm](https://cloud.githubusercontent.com/assets/18116283/16834219/7869b8fe-49d0-11e6-87c8-c2c58d8dcc89.png)


This is what I mean. Like the vertical indicator I should be able to drag and the chart itself should scroll. The workarounds i've tried so far do one of them but not both...

**Comment by liuxuan30** [comment]
the scroll behavior is already supported. By default, the chart shows all the values so it can't scroll. If you zoom in, it can scroll. You can also use setVisibleXRangeMaximum and setVisibleXRangeMinimum at first, so you can scroll without a manual zoom in
