### ISSUE TITLE
Custom label for LineChart

### ISSUE THREAD

**Issue by cohendl** [danielgindi/Charts#1248]
Is it possible to change the labels on the LineChart that doesn't involve NSNumberFormatter?  For example, I'm mapping integers to Emoji's in a rating system and would like to display the Emoji rather than the integer.

Thanks!

**Comment by dxclancy** [comment]
See my posts on this elsewhere.

**Comment by liuxuan30** [comment]
There is PR for such requests I remember, it's still not finished yet. You can take a look https://github.com/danielgindi/Charts/issues/641, or just search what @dxclancy mentioned.

**Comment by cohendl** [comment]
I wasn't asking for PR, just wondering if it was possible.  Sounds like the answer is no at this time?

**Comment by dxclancy** [comment]
yea it is possible.

**Comment by cohendl** [comment]
Do you have a link to thread that explains how or the class/method I can use please?  Thanks!

**Comment by dxclancy** [comment]
So, I suggested that you look at my posts.  If you don't know how to filter issues based on a user, you should learn.  It will be helpful to you.

Filtering based on me turns up several related to NSNumberFormatter, which need only a quick scan, including #943 which includes the following:

> If not, the simplest that too do it to write a subclass of NSNumberFormatter that overrides stringFromNumber and pass that value to an NSDateFormatter, or perform you own custom formatting.

So, in other words, you mentioned wanting something other than NSNumberFormatter to format emojis.  In this case, if you know where you would pass an NSNumberFormatter, you can instead pass your own subclass of NSNumberFormatter that returns emojis.
