### ISSUE TITLE
Line Chart(Dual YAis):if i drag the slider,double line only leave the one line #bug

### ISSUE THREAD

**Issue by LiuLing12138** [danielgindi/Charts#1250]
the line chart(Dual YAis) in the iOS demo , the double line leave the one when i drag the slider. But the Android demo is ok. Two line change together when i drag slider .

**Comment by liuxuan30** [comment]
please reorganize your words, we can barely understand.

**Comment by LiuLing12138** [comment]
啊，就是我看charts的demo，在第二个例子，就是line chart（Dual YAis）里面，刚进去图表setdata的初始化之后，显示的是两条折线，但是我拖动slider控件之后，就只剩下红色的折线了。只有初始化的时候是两条线。
![image](https://cloud.githubusercontent.com/assets/11567481/16860524/926d08aa-4a6b-11e6-97b4-8021754dfb32.png)
![image](https://cloud.githubusercontent.com/assets/11567481/16860528/a0c1415a-4a6b-11e6-9ccc-0f1036090ad4.png)
