### ISSUE TITLE
Marker near edges got clipped

### ISSUE THREAD

**Issue by soapsign** [danielgindi/Charts#1251]
I am using the BallonMarker. It seems that the marker will got clipped near edges. Can the api provide information about the bounds of the graph view, so that the marker got a change to decide how to handle that situation ?

**Comment by liuxuan30** [comment]
I don't think marker will get clipped by the libary unless you have a bigger marker view and clipped by UIView itself.
I checked the code, drawMarkers(context: context) is after CGContextRestoreGState(context)

**Comment by liuxuan30** [comment]
BTW, there is a contentRect in ChartViewHandler class, defines the chart (excluding axis area) rect
