### ISSUE TITLE
Set custom x-value spacing in graph

### ISSUE THREAD

**Issue by KodiKraig** [danielgindi/Charts#1254]
I am trying to achieve custom x spacing such as the way the y axis acts. The reason is I want to graph a best fit line on a line graph but it really doesn't work properly without the actual x values corresponding to the distance between them displayed on the graph. If this not an option by default could you please point me in the direction as to which classes I might need to modify in the library. Thank you!

**Comment by liuxuan30** [comment]
just wait for 3.0 if you can't get it working
