### ISSUE TITLE
fillColor for negative values

### ISSUE THREAD

**Issue by manuelneves** [danielgindi/Charts#1255]
Hello,
is there a way to specify one fill color for positive values and another for negative values?
Thanks!

**Comment by liuxuan30** [comment]
I guess not. it's too advanced right now... but it's technically possible, just go to the fill function and change the color when you detect it's positive/negative rect

**Comment by dcdspace** [comment]
Can you provide example code please?

**Comment by itsmejainh** [comment]
Interesting and useful feature! Any progress on this enhancement ? 

Any code samples would help too! 

thanks much!

**Comment by isaranjha** [comment]
+1
