### ISSUE TITLE
how to hide stacked bar chart label having 0 values

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1256]
hello, i have some zero values for stacked bar chart which looking weird in my stack chart , so how can i hide labels having 0 values? plz help me
because of 0 values other values are getting overwrite see in following chart
![screen shot 2016-07-19 at 10 41 34 am](https://cloud.githubusercontent.com/assets/20103595/16939290/d744f14c-4d9d-11e6-9d1e-44920df656fe.png)

**Comment by dxclancy** [comment]
You can pass a value formatter that returns an empty string for values to small.

**Comment by liuxuan30** [comment]
or you filt zero values.. as you can't see them, barely
