### ISSUE TITLE
LineChart overlap value label and y-Axis

### ISSUE THREAD

**Issue by FryFanti** [danielgindi/Charts#1257]
I want move value label to prevent overlap with y-Axis values in LineChart.

![schermata 2016-07-19 alle 10 55 23](https://cloud.githubusercontent.com/assets/610596/16944205/bd1a56f2-4d9f-11e6-95ab-27e23f7e8687.png)

**Comment by liuxuan30** [comment]
I would format those values shorter and increase xOffset for the y value labels

**Comment by liuxuan30** [comment]
be careful changing xOffset,

```swift
    public func requiredSize() -> CGSize
    {
        let label = getLongestLabel() as NSString
        var size = label.sizeWithAttributes([NSFontAttributeName: labelFont])
        size.width += xOffset * 2.0
        size.height += yOffset * 2.0
        size.width = max(minWidth, min(size.width, maxWidth > 0.0 ? maxWidth : size.width))
        return size
    }
```
as it counts the whole y axis width as `size.width += xOffset * 2.0`, it pads left and right
