### ISSUE TITLE
horizontal bar graph value different decimal places each time

### ISSUE THREAD

**Issue by hiralnaik** [danielgindi/Charts#1260]
Hi There 

I am always seeing different decimal places on the bar. I want to stick with 1 decimal only. Can someone please help with it ?

<img width="175" alt="screen shot 2016-07-21 at 4 40 37 pm" src="https://cloud.githubusercontent.com/assets/7863227/17042390/f9fbe9dc-4f61-11e6-90b9-797d39d60d16.png">

`var yVals = [ChartDataEntry]()
yVals.append(BarChartDataEntry(value: previousYear, xIndex: 0))       yVals.append(BarChartDataEntry(value: currentYear, xIndex: 1))`

Thanks
Hiral

**Comment by dxclancy** [comment]
Valueformatter

**Comment by hiralnaik** [comment]
I tried with it but it is still showing random decimal places. 

Here is the code 

`self.setupBarLineChartView(self.chartView)
        self.chartView.delegate = self
        self.chartView.descriptionText = ""
        self.chartView.noDataTextDescription = "Data not available"
        self.chartView.drawBarShadowEnabled = false
        self.chartView.drawValueAboveBarEnabled = true
        
        let xAxis = self.chartView.xAxis
        xAxis.labelPosition = ChartXAxis.LabelPosition.Bottom
        xAxis.labelFont = UIFont(name: "HelveticaNeue", size: 8)!
        xAxis.drawAxisLineEnabled = true
        xAxis.drawGridLinesEnabled = false
        xAxis.gridLineWidth = 0.3
        xAxis.wordWrapEnabled = true
        
        let leftAxis = self.chartView.leftAxis
        leftAxis.enabled = false
        leftAxis.labelFont = UIFont(name: "HelveticaNeue", size: 8)!
        leftAxis.drawAxisLineEnabled = true
        leftAxis.drawGridLinesEnabled = false
        leftAxis.gridLineWidth = 0.3
        leftAxis.axisMinValue = 0.0 // this replaces startAtZero = YES
        
        let rightAxis = self.chartView.rightAxis
        rightAxis.enabled = false
        rightAxis.labelFont = UIFont(name: "HelveticaNeue", size: 7)!
        rightAxis.drawAxisLineEnabled = true
        rightAxis.drawGridLinesEnabled = false
        rightAxis.axisMinValue = 0.0; // this replaces startAtZero = YES
        
        self.chartView.legend.horizontalAlignment = ChartLegend.HorizontalAlignment.Left
        self.chartView.legend.form = ChartLegend.Form.Circle
        self.chartView.legend.formSize = 8.0
        self.chartView.legend.font = UIFont(name: "HelveticaNeue", size: 8)!
        self.chartView.legend.xEntrySpace = 4.0
        self.chartView.animate(yAxisDuration: 1.5)
        
        self.chartView.extraRightOffset = CGFloat(30.0)
`




`func setDataCount(currentYear : Double, previousYear : Double) {
        
        var xVals = [NSObject]()
        
        xVals.append("Previous Year")
        xVals.append("Current Year")
        
        var yVals = [ChartDataEntry]()
        yVals.append(BarChartDataEntry(value: previousYear, xIndex: 0))
        yVals.append(BarChartDataEntry(value: currentYear, xIndex: 1))
        
        var set1 : BarChartDataSet? = nil
        
        if self.chartView.data?.dataSetCount > 0 {
            let temp = self.chartView.data?.dataSets[0] as! BarChartDataSet
            set1 = temp
            set1!.yVals = yVals
            self.chartView.data?.xValsObjc = xVals
            self.chartView.notifyDataSetChanged()
            
        } else {
            set1 = BarChartDataSet(yVals: yVals, label: "Dataet")
            set1?.colors = [UIColor.cbiBlueColor(), UIColor.orangeColor()]
            set1?.barSpace = 0.25
            var dataSets = [BarChartDataSet]()
            dataSets .append(set1!)
            
            let data : BarChartData = BarChartData(xVals: xVals, dataSets: dataSets)
            data.setValueFont(UIFont(name: "HelveticaNeue", size: 8)!)
            data.setValueTextColor(UIColor.blackColor())
            self.chartView.data = data
        }
        
        let percentage = self.calculatePercentageChangeForDisplay(currentYear, comparedValue: previousYear)
        let value = CBIFormattingUtility.sharedInstance.percentChangeFormatter.stringFromNumber(percentage)
        self.growthLabel.text = value
        
        self.growthLabel.textColor = UIColor.cbiYellowColor()
        if percentage != 0 {
            self.growthLabel.textColor = percentage < 0 ? UIColor.cbiRedColor() : UIColor.cbiGreenColor()
        }
    }
`

**Comment by liuxuan30** [comment]
use maximumFractionDigits = 1

**Comment by hiralnaik** [comment]
I tried maximum fraction digit to 1 but it is still not happening. I don't know what happen ?

**Comment by liuxuan30** [comment]
where do you set it?

**Comment by hiralnaik** [comment]
I mean I put it in my code and run it but it is still not doing it. 

I set it right after rightAxis.rightAxisMinVal = 0.0. 

I set it maximum fraction digit to 1 but still not doing it. 

I don't know if I miss anything in the code.

**Comment by liuxuan30** [comment]
it should be used in your data set's value formatter.

**Comment by liuxuan30** [comment]
also, are you saying two digits after decimal? Not quite clear what are you asking, so I took a guess you want to show only one digit. Like 5.00 -> 5.0

**Comment by hiralnaik** [comment]
Yes I want to display 5.0. But it is displaying 5.234, 5.23, 5.2 etc.

**Comment by liuxuan30** [comment]
then use maximumFractionDigits = 1.

**Comment by hiralnaik** [comment]
Thanks for look into it but I am 100% sure it is not happening with my Swift code. Below is the view controller code, if you can please take a look what am i doing wrong ? 


`import UIKit
import Charts
class GraphViewController: UIViewController, ChartViewDelegate {
    @IBOutlet var chartView: HorizontalBarChartView!
    @IBOutlet weak var growthLabel: UILabel!
    @IBOutlet weak var volumeDepletionLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    /**
     Setup UI Elments for the view controller
     */
    func setupUI() -> Void {
        self.chartView.delegate = self
        self.chartView.descriptionText = ""
        self.chartView.noDataTextDescription = "Data not available"
        self.chartView.drawBarShadowEnabled = false
        self.chartView.drawValueAboveBarEnabled = true
        
        let xAxis = self.chartView.xAxis
        xAxis.labelPosition = ChartXAxis.LabelPosition.Bottom
        xAxis.labelFont = UIFont(name: "HelveticaNeue", size: 8)!
        xAxis.drawAxisLineEnabled = true
        xAxis.drawGridLinesEnabled = false
        xAxis.gridLineWidth = 0.3
        xAxis.wordWrapEnabled = true
        
        let leftAxis = self.chartView.leftAxis
        leftAxis.enabled = false
        leftAxis.labelFont = UIFont(name: "HelveticaNeue", size: 8)!
        leftAxis.drawAxisLineEnabled = true
        leftAxis.drawGridLinesEnabled = false
        leftAxis.gridLineWidth = 0.3
        leftAxis.axisMinValue = 0.0 // this replaces startAtZero = YES
        
        let rightAxis = self.chartView.rightAxis
        rightAxis.enabled = false
        rightAxis.labelFont = UIFont(name: "HelveticaNeue", size: 7)!
        rightAxis.drawAxisLineEnabled = true
        rightAxis.drawGridLinesEnabled = false
        rightAxis.axisMinValue = 0.0; // this replaces startAtZero = YES
        rightAxis.valueFormatter = NSNumberFormatter()
        rightAxis.valueFormatter?.maximumFractionDigits = 1

        self.chartView.legend.horizontalAlignment = ChartLegend.HorizontalAlignment.Left
        self.chartView.legend.form = ChartLegend.Form.Circle
        self.chartView.legend.formSize = 8.0
        self.chartView.legend.font = UIFont(name: "HelveticaNeue", size: 8)!
        self.chartView.legend.xEntrySpace = 4.0
        self.chartView.animate(yAxisDuration: 1.5)
        
        self.chartView.extraRightOffset = CGFloat(30.0)

    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    /**
     Set Data for the graph
     
     - parameter currentYear:  current year depletion or volume
     - parameter previousYear: previous year depletion or volume
     */
    func setDataCount(currentYear : Double, previousYear : Double) {
        
        var xVals = [NSObject]()
        
        xVals.append("Previous Year")
        xVals.append("Current Year")
        
        var yVals = [ChartDataEntry]()
        yVals.append(BarChartDataEntry(value: previousYear, xIndex: 0))
        yVals.append(BarChartDataEntry(value: currentYear, xIndex: 1))
        
        var set1 : BarChartDataSet? = nil
        
        if self.chartView.data?.dataSetCount > 0 {
            let temp = self.chartView.data?.dataSets[0] as! BarChartDataSet
            set1 = temp
            set1!.yVals = yVals
            self.chartView.data?.xValsObjc = xVals
            self.chartView.notifyDataSetChanged()
            
        } else {
            set1 = BarChartDataSet(yVals: yVals, label: "Dataet")
            set1?.colors = [UIColor.cbiBlueColor(), UIColor.orangeColor()]
            set1?.barSpace = 0.25
            var dataSets = [BarChartDataSet]()
            dataSets .append(set1!)
            
            let data : BarChartData = BarChartData(xVals: xVals, dataSets: dataSets)
            data.setValueFont(UIFont(name: "HelveticaNeue", size: 8)!)
            data.setValueTextColor(UIColor.blackColor())
            self.chartView.data = data
        }
        
        let percentage = self.calculatePercentageChangeForDisplay(currentYear, comparedValue: previousYear)
        let value = CBIFormattingUtility.sharedInstance.percentChangeFormatter.stringFromNumber(percentage)
        self.growthLabel.text = value
        
        self.growthLabel.textColor = UIColor.cbiYellowColor()
        if percentage != 0 {
            self.growthLabel.textColor = percentage < 0 ? UIColor.cbiRedColor() : UIColor.cbiGreenColor()
        }
    }
    
    internal func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: ChartHighlight) {
        
        print("Hello There")
    }
    
    /**
     Calculating percentage change for the SKU
     
     - parameter currentValue:  current depletion
     - parameter comparedValue: previous depletion
     
     - returns: percentage value
     */
    func calculatePercentageChangeForDisplay(currentValue : Double, comparedValue : Double) -> Double {
        
        if comparedValue <= 0 {
            if currentValue == 0 {
                return 0
            } else if currentValue > 0 {
                return 1
            } else {
                return -1
            }
        } else {
            return (comparedValue == (0)) ? (currentValue - comparedValue) : (currentValue - comparedValue) / comparedValue
        }
    }
}
`

**Comment by hiralnaik** [comment]
Oops never mind. I just resolved the issue. It is issue with my code. 

`let data : BarChartData = BarChartData(xVals: xVals, dataSets: dataSets)
            data.setValueFormatter(CBIFormattingUtility.sharedInstance.valueChangeFormatterForGraph)
            data.setValueFont(UIFont(name: "HelveticaNeue", size: 8)!)
            data.setValueTextColor(UIColor.blackColor())
            self.chartView.data = data`
