### ISSUE TITLE
Trend line in scatter chart?

### ISSUE THREAD

**Issue by bharat-madept** [danielgindi/Charts#1263]
Hey Daniel 
Thanks for this beautiful library, i'm loving it.
I just want to ask Is there a way to draw trend line in scatter graph? If no, do you have any plan to implement this feature?

**Comment by liuxuan30** [comment]
of course you can. You can take a look at how ChartLimitLine is implemented, and implement your trend line.
The problem is, what trend lines are we going to support, as 'trend line' can be as much complex as it is.
