### ISSUE TITLE
How to select a value in line chart data point and same for bar chart

### ISSUE THREAD

**Issue by AmberKCopper** [danielgindi/Charts#1265]
I want to check if the data point is selected by user or not. So that i can modify properties of that point in line chart or bar in bar chart.

**Comment by liuxuan30** [comment]
check the delegate protocol.

**Comment by AmberKCopper** [comment]
Yea i know the chatValueSelected on that method I want to modify circle radius and other properties of combined chart data point how do i do that

**Comment by AmberKCopper** [comment]
And the circleradius dont has something like to have circle border I want the outer circle to be hollow but with boundary

**Comment by liuxuan30** [comment]
so when you find highlighted, you can override `drawHighlighted` in that chart renderer to change the shape

**Comment by AmberKCopper** [comment]
In chartValueSected i get index of tapped data but cant get instance of lineDataSet to change circleRadius etc theres no property in chartViewBase for lineData. I want highlight this way. Thankyou

**Comment by liuxuan30** [comment]
are you talking about combined chart? If so, the combined chart is like putting different charts into one, called CombinedChartData. Once you know the highlight, you are able to know the position of your line data set. Take a look at CombinedChartData

**Comment by AmberKCopper** [comment]
Yea combinedchart.. Thanks ill look into it and ask :)
Can we also have hollow circleradius for line chart means boundary to be colored and the circleholeradius to be colored

**Comment by liuxuan30** [comment]
hmm.. not sure what you mean.. you have to check the code how it is used.. if not, you can override the methods to do whatever you like
