### ISSUE TITLE
Get scroll position of dragable line chart

### ISSUE THREAD

**Issue by delsner** [danielgindi/Charts#1272]
Probably a very simple question: I have created a simple dragable/scrollable linechart and need to get the current scroll position to determine whether I have reached the end of the chart. For more details see: http://stackoverflow.com/questions/38606896/get-scroll-position-of-dragable-linechart

**Comment by delsner** [comment]
it doesn't necessarily need to be the scroll position but more importantly an indicator telling that I have reached the newest (most right) value in the line chart.

**Comment by liuxuan30** [comment]
would `highestVisibleXIndex` solve your problem? If the highest visible xIndex is the the last data entry xIndex.

**Comment by delsner** [comment]
Unfortunately not as the highest visible xindex is the same for one entire screen width of chart entries. I tried reverse calculating the total possible translation (max transX) and subtract it by the current transX, but I do not get the exact value for the possible translation. Note that I add more data when scrolling to the left which changes the total possible translation while scrolling.

**Comment by liuxuan30** [comment]
Why highestVisibleXIndex does not work for you?

I couldn't find a more dedicated API for this right now. But I think what we could try here is to manually calculate the current offset, like contentOffset concept, though we don't have contentOffset property.

`contentRect` is the rect that defines the area of the chart content, excluding the axis stuff. By computing the matrix and contentRect, we should know when it reaches last entry.

Sorry it has been some time doing the matrix calculation, a little rusty. You can take a look at `ChartViewPortHandler` and `ChartTransformer` for the APIs that  handles the data value coordinate space and pixel value coordinates.

One example I can come up right now: 

1. we know the last entry, so we know the highest xIndex; this xIndex can be project to pixel coordinate system via `pointValueToPixel(inout point: CGPoint)`, so we know the edge of the last data x coordinate, and we can figure out a way to calculate when user scrolls to last?

**Comment by liuxuan30** [comment]
I think I have seen such issues, but couldn't find the old issues now

**Comment by delsner** [comment]
It doesn't work because I am using a `dragOffset` of half a screen width. Thus, when scrolling I the `highestXIndex` stays the same for half a screen width when I reach the end, even though I can keep scrolling until the `dragOffset` is fully scrolled through. Sounds complicated, see http://stackoverflow.com/questions/38606896/get-scroll-position-of-dragable-linechart for a screenshot. I will have a look at `pointValueToPixel`. Thanks so far. By the way apparently the issue is common also in the android library: http://stackoverflow.com/questions/28036212/how-to-get-the-scroll-offset-on-mpandroidchart

**Comment by liuxuan30** [comment]
you should be careful using `dragOffset` and other properties without comments and instructions, unless you know what it is.

**Comment by delsner** [comment]
`self.chartView.setDragOffsetX(self.view.frame.width / 2)`

**Comment by liuxuan30** [comment]
hmm.. seems I can't provide more help here.. maybe ask @danielgindi

**Comment by danielgindi** [comment]
Well if you're adding a dragoffset - then of course `highestVisibleXIndex` won't be good for what you want, as it does not "bounce". 

But you need to work with the viewport here.
Check out `limitTransAndScale` and `canZoomOutMore`. These do what you want, but not exactly:
`limitTransAndScale` calculates the new position in the given constraints - and you can reverse it to fetch the min/max values and determine if you're at the beginning/end.
`canZoomOutMore` is a convenience function that tells, well, if you can zoom out more...

So what I'm saying is- if you make a PR with the counterparts for `canZoomOutMore`, I'll be happy to merge it in :-)

**Comment by macram** [comment]
Hello, is the limitTransAndScale method available in Charts 2.3.1? Or is there another way to know the chart content width, or the visible part of the chart, or the visible entries?
