### ISSUE TITLE
How can i add null values to my chart?

### ISSUE THREAD

**Issue by rashidasgari** [danielgindi/Charts#1273]
I was wondering if there is a way to add null values to two chart. Meaning i want to have gaps in my chart. I have LineChart with two data sets. Something like this
![photo_2016-07-27_23-46-11](https://cloud.githubusercontent.com/assets/2284986/17188893/597ca044-5454-11e6-894a-26e9ada990fe.jpg)

**Comment by liuxuan30** [comment]
Line breaking feature is not supported yet, but you could use two data sets to simulate the gap.
To add null, just create the xIndex but not insert any entry for that xIndex

**Comment by rashidasgari** [comment]
[value addObject:[[ChartDataEntry alloc] initWithValue:val xIndex:i]];
This is how im adding the data to my datasets. How can i add xIndex without any value?!

**Comment by liuxuan30** [comment]
you just nat call [ChartDataEntry alloc] initWithValue:val xIndex:i] on i
[0,1,2,3,4]
[1,  ,3,4,5]

**Comment by rashidasgari** [comment]
Could you please be a little more clear? What is X and Y and how do you assign it to a LineChartDataSet?

**Comment by rashidasgari** [comment]
Finally figured it out. Assuming there are P = M + N point on the chart, i added the first series from 0 to N index and the second one from N to M.
