### ISSUE TITLE
Start at zero and draw cubic

### ISSUE THREAD

**Issue by Tj3n** [danielgindi/Charts#1275]
Hi, I'm having a small issue where i wanted to use `.startAtZeroEnabled` and dataSet's `.drawCubicEnabled` together, but the line got drop below the line and invisible, may anyone help with this or how can i disable showing the first value in left axis which is negative value if disable `.startAtZeroEnabled`?

**Comment by liuxuan30** [comment]
first, use HorizontalBezier can avoid it; second, startAtZeroEnabled and drawCubicEnabled are deprecated if you need HorizontalBezier
