### ISSUE TITLE
Unable to convert charts to Swift3

### ISSUE THREAD

**Issue by edwardconcertcare** [danielgindi/Charts#1277]
I tried to work on this with Xcode 8 beta with swift 3. I install this with cocopods and when I open the workspace file itself, Xcode asked for swift code conversion and I have converted using the tool. Then, when I ran it, it threw error and I fixed those issues. When I ran the project again, it threw error. It did not conclude, it went on like this. Some time, I got fed up of this conversion and left this library. 

I checked in swift2. it work properly. Please give us swift3 support for us to integrate it in our project. Waiting for the community reply.

Thanks.

**Comment by liuxuan30** [comment]
take Swift 3 branch for beta testing.

**Comment by edwardconcertcare** [comment]
I checked out swift3 also and it does not seem to work with Xcode 8 beta

**Comment by liuxuan30** [comment]
Simply saying 'it does not work' can't help at all. The swift 3.0 branch is converted by Xcode 8 beta, and I don't know why you said 'it was not converted' or 'does not work'.

As I mentioned in another post, if you are testing Swift 3.0, you need to remove the whole Realm support #1269.

One more thing, if you have you apps that needs this library, you can leverage Xcode 8 beta to convert the code for you. If you needs Realm, then you have to wait. If you are just simply trying to launch ChartsDemo, there is no need for swift 3.

**Comment by butterpuf** [comment]
xcode 8 is released what can i do to make it work?

**Comment by butterpuf** [comment]
conversion to swift 2.3 and 3.0 fails. Enable legacy version used is not working. as well

**Comment by ericjsalazar** [comment]
I am also having issues getting Charts to work with the new Xcode 8. Are there any recommendations or answers on how to get it to work?

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Converting it to swift 2.3 or swift 3.0 through Xcode leads to over 500 issues.

Thanks in advance.

**Comment by edwardconcertcare** [comment]
I have tried to convert charts like that. But, that was not a successful one. It threw more than hundred errors. I was not able to fix it. That's why, I mailed you. May be, we need to take each and everything manually and convert it.
 
That would be a better idea.
 
-----Original Message-----

**Comment by liuxuan30** [comment]
why don't you check out working branches?

**Comment by butterpuf** [comment]
swift 3.0 branch worked for me
