### ISSUE TITLE
[FR] make Marker a protocol

### ISSUE THREAD

**Issue by farfromrefug** [danielgindi/Charts#1278]
I am using Charts in an Objective C library project. The issue is that Marker is a swift class so i can't subclass it in Objective-C. I also can't make a swift class in my Objective-C project because it is a static library.
The solution for Marker to work in any kind of project would to make ChartViewBase's marker an "id" of Protocol "Marker". Then you could simply Make BallonMarker inherite from "BaseMarker" which would implements the "Marker" protocol.

If you are ok with the idea i will make a simple PR.

Thanks

**Comment by liuxuan30** [comment]
Why you can't make a swift class in your Objective-C project? I think it's doable

**Comment by farfromrefug** [comment]
I am actually creating a module for an cross-platform framework called Titanium Mobile.
For now the module are made of a static library loaded at runtime. So in this case i actually can't use the framework nor source code (you can put swift code in static lib).
So i don't really have a solution as of right now. 
Would be the same thing if someone were to make a PhoneGap module.

I am thinking about switching the Titanium modules to framework but it would take time to implement.
That's why i think make Marker a framework would be the best solution for all.

**Comment by liuxuan30** [comment]
@danielgindi what you think?

**Comment by danielgindi** [comment]
Already done on v3 :-)

**Comment by farfromrefug** [comment]
@danielgindi that s awesome :D will try it as soon as possible!
