### ISSUE TITLE
Everyone welcome to try out `v3` branch before Charts 3.0 is released!

### ISSUE THREAD

**Issue by aftabahmed1286** [danielgindi/Charts#1279]
Hi PhilJay,

Very eager to know when the iOS Charts Version 3.0 Beta will be rlease as Android Charts 3.0 Beta is already available. Please let us know on this.

Thanks,
Aftab

**Comment by danielgindi** [comment]
As you can see in the v3 branch - it is in progress currently.
My daughter was born two month ago, so my time was full - and I'm back at it now. 
We'll finish this version soon. then Phil and I have some more testing and fixes to do, and I guess it could be ready in a week.

**Comment by aftabahmed1286** [comment]
Thanks! And Congratulation on becoming a father.  God Bless your daughter.

**Comment by danielgindi** [comment]
Thank you :-)

**Comment by liuxuan30** [comment]
I will be father in January :)

**Comment by danielgindi** [comment]
Well @liuxuan30, you may want to sleep well now, save the energy for later. You are gonna want to spend every second with the little one and forget to sleep :-)

**Comment by danielgindi** [comment]
Guys you are all welcome to try the `v3` branch, let us know what you think!

**Comment by liuxuan30** [comment]
@danielgindi maybe a blog to talk about the changes for old users?

**Comment by danielgindi** [comment]
I will try to write something down...
בתאריך יום ו׳, 12 באוג׳ 2016 ב-3:56 מאת Xuan <notifications@github.com>:

**Comment by mccpower** [comment]
is it possible to do the integration for this v3 through CocoaPods?
