### ISSUE TITLE
Change Label Text Color PieChart

### ISSUE THREAD

**Issue by michaeljules** [danielgindi/Charts#1280]
I am trying to change the label text color on a pieChart, with: 

`self.pieChartView.xAxis.labelTextColor = UIColor.blackColor()`

Which results in the error: 

 public override var xAxis: ChartXAxis
    {
        fatalError("PieChart has no XAxis")
    }

Any help is appreciated.

**Comment by liuxuan30** [comment]
"PieChart has no XAxis", this is a recent change, check out ChartsDemo as example
