### ISSUE TITLE
legend set different form for different set

### ISSUE THREAD

**Issue by Sailinghj** [danielgindi/Charts#1282]
Current legend form is for the whole legend, like:
`chartView.legend.form = ChartLegendFormCircle`

How can I set form such as set 1 is circle, set 2 is square, set 3 is line?

![1](https://cloud.githubusercontent.com/assets/8357912/17320168/b940e50c-58c4-11e6-8221-04047292dd83.png)

**Comment by liuxuan30** [comment]
take a look at 
```swift
@objc(ChartLegendForm)
    public enum Form: Int
    {
        case square
        case circle
        case line
    }
```

**Comment by liuxuan30** [comment]
I looked into the code, you can modify `drawForm()` in chart legend renderer to support this, but needs you to modify some code.
I think this could be a new feature? @danielgindi
