### ISSUE TITLE
weird behavior resizing the pie.

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#1286]
Hi @PhilJay @danielgindi @liuxuan30 ! -First of all thanks for the amazing work!

 Now I have a little issue with the animation at the to resize the pie, please check the gifs below.

![2016-08-03](https://cloud.githubusercontent.com/assets/5713880/17375730/dda96dac-5977-11e6-9008-7dff2c76f2bf.gif)

As you can see in the animation, there is a moment when the donut turns into an oval at the moment this is growing or shrinking, It seems that when the pie is changing the size first increase or decrease  the value over the x value and then over the y. 

I want to show an increased size just as smooth as the other views,

![2016-08-03-1](https://cloud.githubusercontent.com/assets/5713880/17375758/f78f9cb4-5977-11e6-865b-57e0d55c7f9f.gif)

In this case, it seems that the growing is synchronous among x and y and this create a natural animation when the chart is becoming bigger.

- Do you think that I can get the same behaviour on the Pie ? 
- Could you guys please give me some guidance about when you control the render on the pie just to be able to modify according my necessities?

**Thanks in advance.**

**Comment by liuxuan30** [comment]
hmm.. I am not very familiar with this pie animation.. but looks weird.. is this on android or ios

**Comment by marioduran** [comment]
it is iOS @liuxuan30

**Comment by liuxuan30** [comment]
you guys are same team? From the screenshot it looks like android :)

**Comment by marioduran** [comment]
yes :) we are on the same iOS team @liuxuan30 and we hope that in our final release it doesn't look too much like an Android so we don't get fired haha :P

**Comment by liuxuan30** [comment]
alright :) I guess you have to debug first.. we don't have the env to test... you could get started with the animtor job. I wonder if it's a bug or mistake that starts x then y

**Comment by danielgindi** [comment]
Cool bouncy effect ;-)

**Comment by danielgindi** [comment]
After playing with UIView animations a little - it seems that this is how it animates. It caches the image and stretches it.
