### ISSUE TITLE
2 lines on the charts with the same values

### ISSUE THREAD

**Issue by AndreyPanov** [danielgindi/Charts#1289]
Hello!
I have two lines on the chart if it have the same value, I can't see green line.
![2016-08-04 14 32 09](https://cloud.githubusercontent.com/assets/783564/17400452/06068da2-5a59-11e6-9f48-e940e0b73b70.png)
I want something like:
![2016-08-04 14 34 34](https://cloud.githubusercontent.com/assets/783564/17400453/062cb8f6-5a59-11e6-9913-7b0fdd74f745.png)
How can I do that?

**Comment by liuxuan30** [comment]
well... if they are same value, it should be one line from the accuracy perspective, I don't find only one purple line presents causes issues.
Second, if you really want to do so, I think the easiest way is to add a small delta to your green line data, like delta = line width

**Comment by AndreyPanov** [comment]
Do you have any property for delta set? There are a lot of "delta"s in the library ;)

**Comment by liuxuan30** [comment]
I mean you can manually + delta when you creating data entries. like `entry.value += lineWidth`
