### ISSUE TITLE
Please add Swift demo project also

### ISSUE THREAD

**Issue by rajeshm20** [danielgindi/Charts#1292]
Please add swift demo project as the documentation not available for this repo. It'll be great support.

**Comment by liuxuan30** [comment]
Why not check out Objective-C demo?

**Comment by rajeshm20** [comment]
Sorry..I started writing code for iOS only in swift, find it little hard to match with objective c.

**Comment by liuxuan30** [comment]
there is a OS X demo written in swift, so should be fine
