### ISSUE TITLE
xAxis.axisMaxValue is never considered

### ISSUE THREAD

**Issue by velthune** [danielgindi/Charts#1293]
As in title, I set the property but does not change anything:

    let view = LineChartView()
    view.xAxis.axisMinValue = 6
    view.xAxis.axisMaxValue = 14

on 'axisMinValue' change, graph is drawn as I expect, but changing 'axisMaxValue' nothing happens.

**Comment by liuxuan30** [comment]
currently it's just for y axis. for x axis, use setVisibleXRange()

@danielgindi will v3 solve this issue?

**Comment by velthune** [comment]
No, I've already tried using "setVisibleXRange", but still doesn't work unfortunately

**Comment by liuxuan30** [comment]
@velthune it should work, I have tested it.
> If you call this method, chart must have data or it has no effect

**Comment by velthune** [comment]
Can you try with this values? 
    X - VALS
        [-1...15] with -1 and 15 includes

    Y - VALS
        X: -1 Y: 0.0
        X: 1 Y: 0.0
        X: 3 Y: 0.0
        X: 5 Y: 0.0
        X: 7 Y: 0.0
        X: 9 Y: 48.0
        X: 11 Y: 24.0
        X: 13 Y: 0.0
        X: 15 Y: 0.0

These are values, and I want too see graph in range [0...14]

I use:

    self.viewChart.xAxis.axisMinValue = 0
    self.viewChart.setVisibleXRange(minXRange: 14, maxXRange: 14)

**Comment by liuxuan30** [comment]
> you have to call setVisibleXRange() after chartView.data = chartData

**Comment by liuxuan30** [comment]
my bad, seems I misunderstand. 

>     /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling
    public func setVisibleXRange(minXRange: CGFloat, maxXRange: CGFloat)
