### ISSUE TITLE
Seek help with CandleStickChartView

### ISSUE THREAD

**Issue by MaDaLing** [danielgindi/Charts#1297]
Thanks for providing a powerful charts library, in the process of using CandleStickChartView met a question want to seek help:
I want to a screen display sixty data, but the data may be less than 60, but still want to display sixty data same size.  For example, there are now two data,  I want results as shown below,
<img width="367" alt="2016-08-07 11 05 47" src="https://cloud.githubusercontent.com/assets/20888836/17463347/4a326268-5cf6-11e6-97cc-9d52c6fda8a2.png">
 we do not want as shown below,
<img width="374" alt="2016-08-07 10 46 04" src="https://cloud.githubusercontent.com/assets/20888836/17463349/530dae56-5cf6-11e6-8a12-8b198854e1e6.png">
 is there any idea to do it?

**Comment by liuxuan30** [comment]
well.. the chart has logic to stretch or squeeze the size depending on the data volume and render area.. so when you have small data but large space, it shows you the second one. One quick workaround is generate 60 x values but not insert entry for the last 58 x values.

@danielgindi I guess it's kind of enhancements for candle stick chart?

**Comment by MaDaLing** [comment]
I tried using zoomout (), but it looks like does not work

**Comment by MaDaLing** [comment]
My problem is solved,
set  _minScaleX default value 0  &
using  zoom(scaleX: CGFloat, scaleY: CGFloat, x: CGFloat, y: CGFloat) will meet need
