### ISSUE TITLE
PieChartView Narrow with one value

### ISSUE THREAD

**Issue by shadyk** [danielgindi/Charts#1298]
Hello,

I am facing an issue when using the pie chart view when data entry is only one. The pie chart is getting narrow. 
![untitled-1](https://cloud.githubusercontent.com/assets/1674473/17472005/e9fc6474-5d50-11e6-9b58-bba969f586f3.jpg)

**Comment by liuxuan30** [comment]
I don't see this in ChartsDemo. Please double check and update library if needed
