### ISSUE TITLE
How to select the first pie in bar chart?

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1301]
I know the delegate 'chartValueSelected' , however it's called when user touches the bar chart, now I need the bar chart's first pie to be highlighted by defaul.

**Comment by liuxuan30** [comment]
manually create ChartHighlight object and pass to chart, check out `highlightValue()` in ChartViewBase

**Comment by Huang-Libo** [comment]
I finally found a method to do this job : 
- (void)highlightValueWithXIndex:(NSInteger)xIndex dataSetIndex:(NSInteger)dataSetIndex callDelegate:(BOOL)callDelegate;
