### ISSUE TITLE
add financial bar chart (Open-high-low-close chart)

### ISSUE THREAD

**Issue by clear-m** [danielgindi/Charts#1302]
[Financial bar chart (Open-high-low-close chart)](https://en.wikipedia.org/wiki/Open-high-low-close_chart) is one of the most valuable chart for financial data visualization and analysis.

Please add it to your brilliant library )

**Comment by liuxuan30** [comment]
is this met with candle stick bar chart?

**Comment by clear-m** [comment]
Yes - the data and the meaning are the same as in candle stick charts - but the visual part differs - it is another representation of the same data ) but it differs for different people - that's why both charts types are popular especially in financial industry

**Comment by danielgindi** [comment]
It is already there. You can customize the Candle stick chart to render it this way.
https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Data/Implementations/Standard/CandleChartDataSet.swift#L109

**Comment by sergeydi** [comment]
What is the actual way to show **financial bar chart**?
