### ISSUE TITLE
how to let centerAttributedText line feed in bar chart ?

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1304]
I have set centerAttributedText in bar chart, and sometimes the centerAttributedText is too long, so it's covered by bar chart, then I set paragraphStyle's lineBreakMode to NSLineBreakByTruncatingTail, however it did not work. Is there a way to solve the problem?
![img_2917](https://cloud.githubusercontent.com/assets/12227130/17540808/077bdab0-5eec-11e6-9820-007e6ed5f10c.PNG)

**Comment by Huang-Libo** [comment]
Now I manually add line feed when the text is too long..

**Comment by danielgindi** [comment]
Or use this: https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Charts/PieChartView.swift#L549
For defining the bounds for the text for word wrapping. :-)

**Comment by Huang-Libo** [comment]
That's it! `centerTextRadiusPercent` property.
