### ISSUE TITLE
I want set circle empty in Line Chart. Which properties i have to change?

### ISSUE THREAD

**Issue by anismansuri63** [danielgindi/Charts#1307]
In android plateform it is done by these code.

set2 = new LineDataSet(yVals2, "All Student");
          //  set2.setAxisDependency(YAxis.AxisDependency.RIGHT);
            set2.setColor(ContextCompat.getColor(MainActivity.this, R.color.legend_indicator_all));
            set2.setCircleColor(ContextCompat.getColor(MainActivity.this, R.color.legend_indicator_all));
            set2.setLineWidth(1f);
            set2.setCircleRadius(4f);
            set2.setFillAlpha(65);
            set2.setFillColor(ContextCompat.getColor(MainActivity.this, R.color.legend_indicator_all));
            set2.setDrawCircleHole(true);
            set2.setHighLightColor(ContextCompat.getColor(MainActivity.this, R.color.legend_indicator_all));

I also implemet same code in Ios.
What am i missing here?
![screen shot 2016-08-10 at 4 54 01 pm](https://cloud.githubusercontent.com/assets/16034467/17552060/3350b3ca-5f1b-11e6-915a-21d6ca5b94e9.png)

**Comment by liuxuan30** [comment]
when not try set2.setDrawCircleHole(false); ?
