### ISSUE TITLE
Symbol not found: __TMVVSS17UnicodeScalarView9Generator   Referenced from: Frameworks/Charts.framework/Charts

### ISSUE THREAD

**Issue by remyagiri** [danielgindi/Charts#1311]
dyld: Symbol not found: __TMVVSS17UnicodeScalarView9Generator
  Referenced from: Frameworks/Charts.framework/Charts

This issue is from Charts as I just created an empty project and tried Charts integration.
Build will be successful, but app crashes while launching.
Found another thread with same issue : 
https://github.com/danielgindi/Charts/issues/1223

**Comment by liuxuan30** [comment]
would you post the sample project?

**Comment by danielgindi** [comment]
You are probably using a precompiled version of the framework - and it references symbols that do not exist in your local Swift.lib. Please re-compile.

**Comment by mekhi** [comment]
I also encountered this problem(Xcode8,iOS10)

dyld: Symbol not found: __TMVVSS17UnicodeScalarView9Generator
  Referenced from: /private/var/containers/Bundle/Application/9EC6BB4C-BDE6-4ADB-9ED7-CD42308A205/xxx.app/Frameworks/Charts.framework/Charts
  Expected in: /private/var/containers/Bundle/Application/9EC6BB4C-BDE6-4ADB-9ED7-CD42308A205/xxx.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/9EC6BB4C-BDE6-4ADB-9ED7-CD42308A205/xxx.app/Frameworks/Charts.framework/Charts

**Comment by danielgindi** [comment]
So you are also using a precompiled framework. We are not going to provide precompiled frameworks anymore, as this causes trouble with different compilers.

**Comment by mekhi** [comment]
So, what should I do？

**Comment by mekhi** [comment]
So, what should I do？ @danielgindi

**Comment by danielgindi** [comment]
Not use a precompiled framework, let Xcode compile it
