### ISSUE TITLE
xAxis.axisMaxValue not working

### ISSUE THREAD

**Issue by gjarpere** [danielgindi/Charts#1312]
It is likely that BarLineChartViewBase calculating _axisMaximum for x axis every time in despite of xAxis._customAxisMax setted. Here is a code:

        // calculate / set x-axis range
        _xAxis._axisMaximum = Double((_data?.xVals.count ?? 0) - 1)

**Comment by danielgindi** [comment]
@PhilJay

**Comment by automactic** [comment]
I just met the same issue while making some line chats. I don't want the first and last entry to be plotted on the axis, so I tried to set axisMinValue and axisMaxValue, but axisMaxValue is not working

@gjarpere a walk around is to use setVisibleXRangeMinimum(CGFloat)

**Comment by danielgindi** [comment]
A work around is to move to Charts 3.0 in beta ;)
בתאריך יום ה׳, 11 באוג׳ 2016 ב-18:39 מאת Chris Li <notifications@github.com
