### ISSUE TITLE
How to add more than 3 lines in chart 

### ISSUE THREAD

**Issue by rajeshm20** [danielgindi/Charts#1314]
how to add more than 3 lines in chart
![screen shot 2016-08-11 at 6 23 03 pm](https://cloud.githubusercontent.com/assets/8141399/17589162/bbf56cc2-5ff0-11e6-86ab-3537abb03d47.png)

**Comment by petester42** [comment]
Add a forth dataset.

**Comment by rajeshm20** [comment]
I have but...Chart doesn't show the 4th line..but only legend only showing up
![screen shot 2016-08-11 at 6 50 00 pm](https://cloud.githubusercontent.com/assets/8141399/17589833/76141b32-5ff4-11e6-98a0-093a0686bd2c.png)

**Comment by rajeshm20** [comment]
is there any limit for number lines in Chart?

**Comment by petester42** [comment]
Shouldn't be. What is the dataset for triglycerides?

**Comment by rajeshm20** [comment]
tcTriGlyc:  ["150", "170", "166", "180", "230"]
tcCholstrl:  ["195", "178", "189", "170", "188"]

**Comment by rajeshm20** [comment]
TriGlycerides:  ["150", "170", "166", "180", "230"]
Cholesterol:  ["195", "178", "189", "170", "188"]

**Comment by petester42** [comment]
I would assume that you correctly created the data set but have not added the values correctly. I can't know without seeing the code.

**Comment by rajeshm20** [comment]
Here is the code...i have fetch the data from sqlite using sharedInstance()


>     @IBOutlet var lineChartView: LineChartView!
    
    var showDates:[String] = []
    var showLdl:[String] = []
    var showHdl:[String] = []
    var showTriglyc:[String] = []
    var showCholestrl:[String] = []

    func fetchBP() {
        
        showDates = sharedInstance.getTCUptdDate()
        showLdl = sharedInstance.getTCLdl()
        showHdl = sharedInstance.getTCHdl()
        showTriglyc = sharedInstance.getTCTriGlyc()
        showCholestrl = sharedInstance.getTCCholestrol()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        fetchBP()


        let dates = showDates
        let ldl = showLdl.flatMap{Double($0)}
        let hdl = showHdl.flatMap{Double($0)}
        let triGlyc = showTriglyc.flatMap{Double($0)}
        let Cholestrl = showCholestrl.flatMap{Double($0)}

        
        lineChartView.legend.font = NSUIFont.italicSystemFontOfSize(12)
        
        
        var dataEntries: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: ldl[i], xIndex: i)
            dataEntries.append(dataEntry)
        }
        
        
        let lineChartDataSet = LineChartDataSet(yVals: dataEntries, label: "LDL")
        
        
        var dataEntries2: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: hdl[i], xIndex: i)
            dataEntries2.append(dataEntry)
        }
        
        
        let lineChartDataSet2 = LineChartDataSet(yVals: dataEntries2, label: "HDL")
        
        
        var dataEntries3: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: triGlyc[i], xIndex: i)
            dataEntries3.append(dataEntry)
        }
        
        
        let lineChartDataSet3 = LineChartDataSet(yVals: dataEntries3, label: "TriGlycerides")
        
        
        var dataEntries4: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: Cholestrl[i], xIndex: i)
            dataEntries4.append(dataEntry)
        }
        
        
        let lineChartDataSet4 = LineChartDataSet(yVals: dataEntries3, label: "Cholestrol")

        
        
        
        let lineChartData = LineChartData(xVals: dates, dataSets: [lineChartDataSet, lineChartDataSet2, lineChartDataSet3, lineChartDataSet4])
        
        lineChartView.data = lineChartData
        lineChartData.setValueFont(NSUIFont.boldSystemFontOfSize(9))
        
        lineChartView.animate(xAxisDuration: 2.0)
//        lineChartView.animate(yAxisDuration: 2.5)
        
        lineChartDataSet.setCircleColor(UIColor.init(red: 255/255, green: 69/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet.setColor(UIColor.init(red: 255/255, green: 69/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet2.setCircleColor(UIColor.init(red: 255/255, green: 140/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet2.setColor(UIColor.init(red: 255/255, green: 140/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet3.setCircleColor(UIColor.init(red: 139/255, green: 0/255, blue: 139/255, alpha: 1))
        
        lineChartDataSet3.setColor(UIColor.init(red: 139/255, green: 0/255, blue: 139/255, alpha: 1))
        
        lineChartDataSet4.setCircleColor(UIColor.init(red: 123/255, green: 104/255, blue: 238/255, alpha: 1))
        
        lineChartDataSet4.setColor(UIColor.init(red: 123/255, green: 104/255, blue: 238/255, alpha: 1))

    }

**Comment by rajeshm20** [comment]
`    @IBOutlet var lineChartView: LineChartView!
    
    var showDates:[String] = []
    var showLdl:[String] = []
    var showHdl:[String] = []
    var showTriglyc:[String] = []
    var showCholestrl:[String] = []

    func fetchBP() {
        
        showDates = sharedInstance.getTCUptdDate()
        showLdl = sharedInstance.getTCLdl()
        showHdl = sharedInstance.getTCHdl()
        showTriglyc = sharedInstance.getTCTriGlyc()
        showCholestrl = sharedInstance.getTCCholestrol()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        
        
        fetchBP()


        let dates = showDates
        let ldl = showLdl.flatMap{Double($0)}
        let hdl = showHdl.flatMap{Double($0)}
        let triGlyc = showTriglyc.flatMap{Double($0)}
        let Cholestrl = showCholestrl.flatMap{Double($0)}

        
        lineChartView.legend.font = NSUIFont.italicSystemFontOfSize(12)
        
        
        var dataEntries: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: ldl[i], xIndex: i)
            dataEntries.append(dataEntry)
        }
        
        
        let lineChartDataSet = LineChartDataSet(yVals: dataEntries, label: "LDL")
        
        
        var dataEntries2: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: hdl[i], xIndex: i)
            dataEntries2.append(dataEntry)
        }
        
        
        let lineChartDataSet2 = LineChartDataSet(yVals: dataEntries2, label: "HDL")
        
        
        var dataEntries3: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: triGlyc[i], xIndex: i)
            dataEntries3.append(dataEntry)
        }
        
        
        let lineChartDataSet3 = LineChartDataSet(yVals: dataEntries3, label: "TriGlycerides")
        
        
        var dataEntries4: [ChartDataEntry] = []
        
        for i in 0..<dates.count {
            let dataEntry = ChartDataEntry(value: Cholestrl[i], xIndex: i)
            dataEntries4.append(dataEntry)
        }
        
        
        let lineChartDataSet4 = LineChartDataSet(yVals: dataEntries3, label: "Cholestrol")

        
        
        
        let lineChartData = LineChartData(xVals: dates, dataSets: [lineChartDataSet, lineChartDataSet2, lineChartDataSet3, lineChartDataSet4])
        
        lineChartView.data = lineChartData
        lineChartData.setValueFont(NSUIFont.boldSystemFontOfSize(9))
        
        lineChartView.animate(xAxisDuration: 2.0)
//        lineChartView.animate(yAxisDuration: 2.5)
        
        lineChartDataSet.setCircleColor(UIColor.init(red: 255/255, green: 69/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet.setColor(UIColor.init(red: 255/255, green: 69/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet2.setCircleColor(UIColor.init(red: 255/255, green: 140/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet2.setColor(UIColor.init(red: 255/255, green: 140/255, blue: 0/255, alpha: 1))
        
        lineChartDataSet3.setCircleColor(UIColor.init(red: 139/255, green: 0/255, blue: 139/255, alpha: 1))
        
        lineChartDataSet3.setColor(UIColor.init(red: 139/255, green: 0/255, blue: 139/255, alpha: 1))
        
        lineChartDataSet4.setCircleColor(UIColor.init(red: 123/255, green: 104/255, blue: 238/255, alpha: 1))
        
        lineChartDataSet4.setColor(UIColor.init(red: 123/255, green: 104/255, blue: 238/255, alpha: 1))

    }
`

**Comment by danielgindi** [comment]
You have set entries3 to dataSet4

**Comment by rajeshm20** [comment]
Oh...my...Thanks a lot Daniel...my carelessness...

**Comment by rajeshm20** [comment]
It's working now....How is your daughter?...God Bless..
![screen shot 2016-08-11 at 7 08 53 pm](https://cloud.githubusercontent.com/assets/8141399/17590353/1e114290-5ff7-11e6-844c-28435118e82c.png)

**Comment by rajeshm20** [comment]
Thanks @petester42 , @danielgindi !

**Comment by petester42** [comment]
🎉

**Comment by danielgindi** [comment]
@rajeshm20 she is amazing and makes us happier every day, thank you!
