### ISSUE TITLE
Also played well, before package, NO error, the recent packaging error, the error is "NO Scuh module 'charts", don't know is what reason to solve, use the xcode 7.1 (7 b91b)

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/Charts#1316]
Also played well, before package, NO error, the recent packaging error, the error is "NO Scuh module 'charts", don't know is what reason to solve, use the xcode 7.1 (7 b91b)
![2016-08-11 4 54 04](https://cloud.githubusercontent.com/assets/11886729/17610154/bc7c8a22-606d-11e6-92f5-d4f179faa208.png)

How to solve, thank you

**Comment by liuxuan30** [comment]
first update your Xcode.

**Comment by shanyulaile** [comment]
I upgraded my xcode to 7.3.1 operation can be successful, but when the package or the above problems, upgrade to version which can be solved?I am using charts version 2.1.6
