### ISSUE TITLE
X data as a Date

### ISSUE THREAD

**Issue by vishaldeshai** [danielgindi/Charts#1317]
Hello,

Can we set date data on x axises?

thanks in advance
VIshal

**Comment by danielgindi** [comment]
Of course. Please take a look at the Time Line Chart demo, in v3 branch.

**Comment by vishaldeshai** [comment]
can you tell me why i am getting 2 days earlier data of initial date data?

**Comment by danielgindi** [comment]
Not really. Check your `axisMinimum`

**Comment by cartmanguo** [comment]
If the time interval between dates are not the same value, some entries are missing.In the timeline demo,the time interval between dates are always 3600
#1348
