### ISSUE TITLE
If the all value is 1 or 0, the ChartYAxis is error

### ISSUE THREAD

**Issue by roselind** [danielgindi/Charts#1321]
version：2.2.5
![df977d8e-6abe-4280-8881-2cbdb026ebb5](https://cloud.githubusercontent.com/assets/9067932/17686145/a31860e2-639c-11e6-9909-780e0f7e9c76.png)

**Comment by danielgindi** [comment]
ChartYAxis is not "error". These are the values it can render, between 0 and 1.
You can control that with `granularity`. You could have found issues here that talk about it...

**Comment by roselind** [comment]
If I set the following properties：
leftAxis.granularity = 0.01;
leftAxis.granularityEnabled = YES;
leftAxis.startAtZeroEnabled = YES;
leftAxis.axisMinValue = 0.01;
the all data  is 1  , ChartYAxis  value is 0，0，0，1，1，1

If I set the following properties：
leftAxis.granularity = 1;
leftAxis.granularityEnabled = YES;
leftAxis.startAtZeroEnabled = YES;
leftAxis.axisMinValue =0.01;
the all data  Less than 1   , ChartYAxis  value is null
 
![1](https://cloud.githubusercontent.com/assets/9067932/17694014/5a4298d2-63d4-11e6-9e62-f4ef4f3e58f4.png)


if the all data  is 0   , No line drawing
![d3b67d8a-3d4f-4122-b3ce-93424e2a44b6](https://cloud.githubusercontent.com/assets/9067932/17694061/99e02496-63d4-11e6-9950-58b3c37db90e.png)
