### ISSUE TITLE
v2.2.5 demo code is different with pod installed version

### ISSUE THREAD

**Issue by gaoshanyu** [danielgindi/Charts#1322]
Hey guys, I just find the demo code is different with pod installed version. The demo I downloaded from the [main page](https://github.com/danielgindi/Charts):
![screen shot 2016-08-16 at 11 35 54 am](https://cloud.githubusercontent.com/assets/10546774/17687358/edcd843c-63a6-11e6-8c09-2ed4770b30bf.png)

**Installed framework use "pod 'Charts'" to my project**:
![screen shot 2016-08-16 at 11 36 47 am](https://cloud.githubusercontent.com/assets/10546774/17687421/61ab62a2-63a7-11e6-9507-0f3e28fe1341.png)
![screen shot 2016-08-16 at 11 35 34 am](https://cloud.githubusercontent.com/assets/10546774/17687427/68536244-63a7-11e6-9640-aded653eb402.png)

I want to create a marker for my bar chart, but the demo confused me. If the pod version is correct, can anyone give a sample code for marker? Thanks for any help.

**Comment by danielgindi** [comment]
Yes, Charts 3.0 on `master` branch is different from 2.2.5.

**Comment by gaoshanyu** [comment]
Hey man, can you give me a sample of v2.2.5 for ChartMarker for bar chart? I've spend a lot of time on this but still not found solution. @danielgindi

**Comment by danielgindi** [comment]
It is included in 2.2.5's demo code

**Comment by gaoshanyu** [comment]
OK, I got it. Waiting for the special v3. Thank you so much.
