### ISSUE TITLE
I am not able to design multicolor bar chart

### ISSUE THREAD

**Issue by ios-sagar** [danielgindi/Charts#1324]
Hi,
I am using this library,
its a good one
I have around 6 pie charts and 6 bar charts
among them 2 bar charts are with two colours (like male-female ration in each dept.)
so my X-axis contains departments and Y-axis contains values.

I want male in one colour and female in other colour for particular dept.
can you pls guide for the same,

I asked same query on SO, but no answer yet.
here is the link, which contains my sample code as well.

http://stackoverflow.com/questions/38658402/multiple-colours-to-bar-charts-swift-one-above-the-other

**Comment by danielgindi** [comment]
This is a stacked bar chart. In Charts' demos, you can see a stacked bar chart.

Basically, each `BarChartDataEntry` received either one value, or an array of values. Pass in an array of values - and you are good to go!

`let entry = BarChartDataEntry(values: [4.6, 3.8], xIndex: 0)`

**Comment by ios-sagar** [comment]
I tried the same,
I can see the values in one above, but I failed to update the different colours.
I want different colours to set

**Comment by danielgindi** [comment]
```
dataset.colors = [UIColor.cyanColor(), UIColor.greenColor()]
dataset.stackLabels = ["Inactive inventory", "Active inventory"]
```

**Comment by gaganindersingh** [comment]
@danielgindi Please check the screenshot. I am able to draw the charts but only values are displaying no bars.
![screen shot 2016-08-25 at 11 48 41 pm](https://cloud.githubusercontent.com/assets/5109848/18561849/2db9a21e-7b9f-11e6-8413-4d65f8ce6850.png)

**Comment by gaganindersingh** [comment]
Anyway, I was using the wrong formatter for x-axis. The x-axis value should be in day of year format.
