### ISSUE TITLE
Correct date on x axis

### ISSUE THREAD

**Issue by MansoorB** [danielgindi/Charts#1325]
I have bunch of data that have dates on it with following format for example "9 Jan 12:00", "9 Jan 12:05", "9 Jan 12:10" etc. More accurately its in raw format and Im using NSNumberFormatter to get it in right format. 

For example Dates = ["8 Jan 14:15", "9 Jan 12:00", "9 Jan 12:05", "9 Jan 12:10", "10 Jan 12:00", "10 Jan 12:05", "10 Jan 12:10", etc..] Basically bunch of data

The problem is that the X axis plotting wrong interval. It starts plots "8 Jan 14:15", "9 Jan 06:55" etc.

I want it to start with "9 Jan 12:00", "9 Jan 18:00", "10 Jan 12:00", "10 Jan 18:00", "11 Jan 12:00", etc..

**Comment by liuxuan30** [comment]
not having a chance looking at v3 yet. not sure if it supports this.. @danielgindi ?

**Comment by MansoorB** [comment]
Looking through v3. So far haven't found anything that handles the x axis data

**Comment by jiadw007** [comment]
Use DefaultAxisValueFormatter.
charView.xAxis.valueFormatter = DefaultAxisValueFormatter.with(block:{
(value, axis) ->String in
//value is time interval
let date = Date(timeIntervalSince1970: value)
let dateFormatter = DateFormatter()
return dateFormatter.date(from: date)
})
You can also write dateFormatter as extension
