### ISSUE TITLE
Undefined symbols for architecture armv7:

### ISSUE THREAD

**Issue by devilon** [danielgindi/Charts#1327]
在一个旧的项目上，运行是会报错，
一个不怎么好的解决方案：
TARGETS-----Build Settings --------Architectures -------  Valid Architectures----  双击打开  ---------  把armv7 删了，才能运行于真机，Charts库不支持armv7，即iPhone4、iPhone4S。
希望作者能跟进改善一下。

**Comment by liuxuan30** [comment]
No, it supports.
