### ISSUE TITLE
Combined Chart Grouped Bar Width Not Changing

### ISSUE THREAD

**Issue by jj-12** [danielgindi/Charts#1328]
It appears that grouped bar charts do not change their width when added to the graph.  That is, the space that should be taken up by an entire group of bars is taken up by one single bar.  

An example of this is shown in **https://www.codebeaulieu.com/96/How-to-create-a-Combined-Bar-and-Line-chart-using-ios-charts**

Although the author has some unnecessary code, there is nothing in there that seems as if it should break the view.  If you notice on the image at the end of that tutorial, six groupings of bars are supposed to be showing, but only 4.5 are in view.  If you remove one of the bar sets from the bar data array, then it shows properly in the chart view.  

I have used this tutorial as well as the documentation/demos available in the Charts repo, and I am seeing the same issue.  Is there a way to manually half the width of the bar?  It appears in your Chart Demos there used to be a way, but those fields don't seem to be available in the current version.

Thanks, I love the work you guys have done!

**Comment by liuxuan30** [comment]
your screenshot seems very old, at that time, grouped bars in combined chart is not supported. The good news is in v3, we officially support it. So you should check out master branch to test it.
