### ISSUE TITLE
Redundant conformance of 'RLMResults' to protocol 'SequenceType' on RealmChartsUtils

### ISSUE THREAD

**Issue by hernanmn** [danielgindi/Charts#1329]
Hi

Thanks for your support, I am using the last version of Xcode, so I needed to embebed source code, when I tried to compile I got the error mentioned. and also 

Redundant conformance of 'RLMArray' to protocol 'SequenceType'

Both errors at RealmChartUtils.swift

Thanks in advance for your support

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/issues/1269

**Comment by danielgindi** [comment]
It actually seems like `RLMArray` already has conformance to `SequenceType` in its newer version, while the older one didn't. I've added it in an extension (RealmChartUtils.swift)

I'll update to latest Realm and fix this.

In the meantime - let's keep this open

**Comment by liuxuan30** [comment]
oops, I was thinking the swift 3.0, SequenceType is changed to Sequence I remember

**Comment by danielgindi** [comment]
Solved.
RLMArray does not conform to SequenceType, but our private extension has probably collided with something in the beta version of Swift 3.0. 
I've removed the extension, and used an enumerator locally.

**Comment by liuxuan30** [comment]
@danielgindi I also had a commit for keeping the extension to work.
