### ISSUE TITLE
values from array for x axis on barchart

### ISSUE THREAD

**Issue by seal62** [danielgindi/Charts#1331]
I am using the new version of Charts and can figure out how to take a string value from an array and use it as the x-axis value. Using the examples provided I have the below, which generates a bar chart with these y values but x is just 0, 1, 2, 3 etc.. how do I change that to use the days array values? looking at the BarChartEntry class it only accepts Doubles? 

```
let values: [Double] = [8, 104, 81, 93, 52, 44, 97]
let days: [String] = ["mon", "tues", "weds", "thurs", "fri", "sat", "sun"]
        
var entries: [ChartDataEntry] = Array()
        
for (i, value) in values.enumerate()
        {
            entries.append(BarChartDataEntry(x: Double(i), y: value))
        }
        
```

**Comment by WickdProfit** [comment]
@seal62 , You mean the labels for the x axis?  You don't set the x-axis label on the BarChartEntryData, you set it on the BarChartData object.  See the tutorial at the end of this comment as well as the demo classes in this repo for examples.

e.g., ```let data: BarChartData = BarChartData(xVals: days)```

Hope this helps,

https://www.codebeaulieu.com/96/How-to-create-a-Combined-Bar-and-Line-chart-using-ios-charts

**Comment by seal62** [comment]
@jj-12 thank you for the response but I think you are talking about Charts 2.2.5 which allowed you to init the BarChartData with xVals. Charts 3.0 only allows init with dataSet but does not include arguements for xVals

`let data = BarChartData(dataSet: [IChartDataSet?])`

Unfortunately all the tutorials I can find online use the old version of Charts, there doesnt seem to be anything on 3.0 which uses a new method of generating the charts

**Comment by sammetaphani** [comment]
Same issue.

**Comment by seal62** [comment]
this was answered here - https://github.com/danielgindi/Charts/issues/1340

**Comment by shivang2902** [comment]
@seal62 Can you please look into my issue [Directly refer the last 2 comments]
https://github.com/danielgindi/Charts/issues/2262
