### ISSUE TITLE
Integer for ChartDataEntry

### ISSUE THREAD

**Issue by ptaking** [danielgindi/Charts#1332]
How can I pass Int value to ChartDataEntry? My chart needs exact value instead of `,0`
![nh ch p man hinh 2016-08-18 luc 16 36 54](https://cloud.githubusercontent.com/assets/12915431/17769268/06f03dc6-6562-11e6-9022-53b62175204f.png)

**Comment by LuoPengFei** [comment]
let dataEntry = ChartDataEntry(value:Double(values[i]), xIndex: i)
I think it will be OK

**Comment by ptaking** [comment]
Actually, I want to display as Integer.
![nh ch p man hinh 2016-09-01 luc 11 42 30](https://cloud.githubusercontent.com/assets/12915431/18155600/35382568-7039-11e6-877b-81f9cdf246fd.png)

**Comment by MaDaLing** [comment]
let yFomatter: NSNumberFormatter = NSNumberFormatter()
        yFomatter.minimumIntegerDigits = 1
        yFomatter.minimumFractionDigits = 0
data.valueFormatter = yFomatter

**Comment by ptaking** [comment]
Thanks, MaDaLing
![nh ch p man hinh 2016-09-01 luc 15 56 09](https://cloud.githubusercontent.com/assets/12915431/18161570/ae20f34c-705c-11e6-9b55-0b9f34140c88.png)
