### ISSUE TITLE
xAxis labels not align with values in Multiple Bar Chart

### ISSUE THREAD

**Issue by PreechaS** [danielgindi/Charts#1334]
<img width="369" alt="screen shot 2559-08-18 at 11 40 55 pm" src="https://cloud.githubusercontent.com/assets/17841404/17782552/484752d2-659e-11e6-8662-a662b18b8c58.png">
**let barData = BarChartData(dataSets: [resultDataSet, attemptDataSet])
barData.barWidth = 0.3
barData.groupBars(fromX: 0, groupSpace: 0.2, barSpace: 0.05)
chartView.notifyDataSetChanged()**

<img width="371" alt="screen shot 2559-08-18 at 11 38 44 pm" src="https://cloud.githubusercontent.com/assets/17841404/17782637/bc00c53c-659e-11e6-9ebd-c85c2e0686bd.png">
try to remove one DataSet, it work correctly.

**let barData = BarChartData(dataSets: [resultDataSet])
barData.barWidth = 0.3
barData.groupBars(fromX: 0, groupSpace: 0.2, barSpace: 0.05)
chartView.notifyDataSetChanged()**

**Comment by liuxuan30** [comment]
is this v3 or old version?

**Comment by PreechaS** [comment]
I'm not quite sure which version, but certainly the latest one because I send this issue a few hours after downloading the latest version.

**Comment by liuxuan30** [comment]
It's easy to find out just check when and where you download the source code

**Comment by PreechaS** [comment]
Master on Aug.19

**Comment by danielgindi** [comment]
@PhilJay I think this relates to the other one https://github.com/danielgindi/Charts/issues/1359

**Comment by danielgindi** [comment]
Does this still happen in `master`?

**Comment by danielgindi** [comment]
This is a duplicated of #1359, we'll post updates there
