### ISSUE TITLE
Line Chart x axis and y axis Line Color change?

### ISSUE THREAD

**Issue by vishaldeshai** [danielgindi/Charts#1337]
Hello,

Can we change color of x and y  axis?

thanks in advance.

**Comment by LuoPengFei** [comment]
lineColor:axisLineColor
valueColor:labelTextColor

**Comment by vishaldeshai** [comment]
thanks 🎱

**Comment by vishaldeshai** [comment]
above two lines are not working proper for time Line Charts

**Comment by LuoPengFei** [comment]
axisLine ？ gridLine ?

**Comment by vishaldeshai** [comment]
axisline

**Comment by LuoPengFei** [comment]
![2016-08-19 3 33 17](https://cloud.githubusercontent.com/assets/10494635/17802367/817b379c-6622-11e6-9720-24446a9b8a4e.png)
