### ISSUE TITLE
Where can I find the exact color value of vordiplom colors?

### ISSUE THREAD

**Issue by nhantrivinh** [danielgindi/Charts#1343]
I need this to match some color scheme in the app I am working on. Can't find it after a long search.

**Comment by liuxuan30** [comment]
why vordiplom colors is related to this library?

**Comment by nhantrivinh** [comment]
I have built out the app. I need the hex value or whatever of the first four colors. 

chartDataSet.colors = ChartColorTemplates.vordiplom()

**Comment by danielgindi** [comment]
It is defined, as you can guess, in `ChartColorTemplates`
