### ISSUE TITLE
Label drawing glitch when changing data

### ISSUE THREAD

**Issue by mecid** [danielgindi/Charts#1347]
I have chart label glitches when changing chart data via calendar in the top.

`
  self.summaryChart.data = BarChartData(xVals: xVals, dataSet: dataset)

  self.summaryChartHeight.constant = CGFloat(xVals.count * 40)

  self.delay(300) { self.summaryChart.notifyDataSetChanged() }
`

![img_0525](https://cloud.githubusercontent.com/assets/324372/17900295/c7107060-696f-11e6-86a2-9b65d760d965.jpg)

**Comment by liuxuan30** [comment]
hmm, there are labels overlap.  Is this stacked bar or anything?  Need step to reproduce, using ChartsDemo is even better.

**Comment by mecid** [comment]
@liuxuan30 This is not stacked bar. This is chart configuration code.
`
   summaryChart.userInteractionEnabled = false
            summaryChart.legend.enabled = false
            summaryChart.descriptionText = ""
            
            summaryChart.xAxis.labelFont = UIFont.preferredFontForTextStyle(UIFontTextStyleBody)
            summaryChart.xAxis.labelTextColor = UIColor.flatWhiteColor()
            summaryChart.xAxis.labelPosition = .Bottom
            
            summaryChart.leftAxis.enabled = false
            summaryChart.rightAxis.enabled = false
            
            summaryChart.xAxis.drawAxisLineEnabled = false
            summaryChart.xAxis.drawGridLinesEnabled = false
            
            summaryChart.leftAxis.spaceTop = CGFloat(0.3)
`

And this is dataset creating code:

`
       let dataset = BarChartDataSet()
            dataset.valueFont = UIFont.preferredFontForTextStyle(UIFontTextStyleCaption1)
            dataset.valueTextColor = UIColor.flatWhiteColor()
            dataset.resetColors()
            
            let percentNumberFormatter = NSNumberFormatter()
            percentNumberFormatter.numberStyle = NSNumberFormatterStyle.PercentStyle
            dataset.valueFormatter = percentNumberFormatter
            
            let sum = samples.count
            var xVals: [String] = []
            var index = 0
            
            for (status, count) in self.groupHeartRateSamples(samples, activity: .Regular) {
                let value = Double(count) / Double(sum)
                dataset.addEntry(BarChartDataEntry(value: value, xIndex: index))
                dataset.addColor(status.color())
                xVals.append(status.description)
                index = index + 1
            }
`

**Comment by mecid** [comment]
Problem appear only with clear color background for chart.
