### ISSUE TITLE
Data entries are missing on the chart

### ISSUE THREAD

**Issue by cartmanguo** [danielgindi/Charts#1348]
![579364ae58f9452bcffac0fdbbf76373](https://cloud.githubusercontent.com/assets/4699162/17916987/ae6fdd86-69ea-11e6-8d70-3a419fa39b29.jpg)
As you see in the screenshot,some entries are missing,I print all the entries in the dataset,they all exist.Is this because some properties i did not set?

**Comment by cartmanguo** [comment]
I found that this problem happens when the timeintervals on the xaxis  are not equal(such as 2,6,11).If I change the timeinterval to 1,then this problem will not appear.Also If  timeintervals
are not equal,the chart may skip some values,if show circle on each entry,some entries are not displayed on the chart

**Comment by cartmanguo** [comment]
I upload a demo app to demonstrate this problem,in case if you need
https://github.com/cartmanguo/Chartsss

**Comment by danielgindi** [comment]
What version of Charts is this?

**Comment by cartmanguo** [comment]
I'm using 3.0
There's a demo:https://github.com/cartmanguo/Chartsss

**Comment by danielgindi** [comment]
You're not using Charts 3.0. Your project itself isn't Swift 3.0.
Please test on latest `master`, and if there's a problem open an issue with sufficient information.
