### ISSUE TITLE
Pie Chart Graph Unusual Visual When Data Of Zero

### ISSUE THREAD

**Issue by nhantrivinh** [danielgindi/Charts#1351]
![piechartgraphzerodata](https://cloud.githubusercontent.com/assets/12175043/17937530/a79523a6-6a4c-11e6-82b3-9af9c2c2717b.jpg)

If I were to set chart without data entry, I get this weird mess at the bottom left corner of the pie chart graph's view every time. This did not happen when I worked with bar graph, it just showed an empty graph with no bar(s).

**Comment by danielgindi** [comment]
Which version of Charts is this?

**Comment by nhantrivinh** [comment]
2.2.5

I am running this in Xcode 7.3

**Comment by danielgindi** [comment]
Please test with Charts 3.0, as I didn't manage to reproduce this, and this might be the reason...

**Comment by nhantrivinh** [comment]
Where do I get that Charts 3.0? The latest release is 2.2.5. I did a pod update and it is still 2.2.5.

**Comment by danielgindi** [comment]
Download `master` branch and compiler, or tell your podspec to sync with master

**Comment by nhantrivinh** [comment]
How do I tell my pod spec to sync with master?

**Comment by nhantrivinh** [comment]
Hey guys, I have never done this before and I couldn't find the info myself. An act of kindness would be much appreciated. Thanks.

**Comment by danielgindi** [comment]
You've never done a search? In Google? Or even github issues here?

**Comment by nhantrivinh** [comment]
I tried all of them.

**Comment by danielgindi** [comment]
Does not seem like you did.
Google => https://guides.cocoapods.org/using/the-podfile.html => "To use the master branch of the repo:"...
