### ISSUE TITLE
Horizontal Bar Chart not showing values

### ISSUE THREAD

**Issue by mecid** [danielgindi/Charts#1356]
I am using horizontal bar chart for showing daily Heart Rate chart.
Chart userInteractionEnabled = false. 
Chart height constraint = value count * 30.
When i have 100 or more values, value labels not showing, if i have less than 100 values labels showing. How can i fix this?

![thumb_img_0531_1024](https://cloud.githubusercontent.com/assets/324372/17971496/2bb94a8c-6aec-11e6-99ff-4009320669e7.jpg)
![thumb_img_0532_1024](https://cloud.githubusercontent.com/assets/324372/17971497/2bf09b7c-6aec-11e6-97a9-bdcffdaad8e1.jpg)

**Comment by mecid** [comment]
@danielgindi any idea?

**Comment by danielgindi** [comment]
There's a property that limits labels showing according to value density. Can't remember right now- I'll put its name here when I'm in front of a computer

**Comment by mecid** [comment]
@danielgindi chart.leftAxis.labelCount ?

**Comment by mecid** [comment]
@danielgindi chart.leftAxis.labelCount not working, anything else?

**Comment by mecid** [comment]
@danielgindi any news?

**Comment by danielgindi** [comment]
`maxVisibleCount`. You can look at the demos, many of them use this.

**Comment by mecid** [comment]
@danielgindi not working for me.

**Comment by danielgindi** [comment]
You're welcome :-)
