### ISSUE TITLE
BarChartView can't show max y value's top label, only show half

### ISSUE THREAD

**Issue by hh-in-zhuzhou** [danielgindi/Charts#1357]
I found that function calcMinMax() in BarChartView.swift，the max y axis value is equal to the data's max y value ,so it has not enough space to show whole label, I fixed it:

file: BarChartView.swift

internal override func calcMinMax()
    {
        guard let data = self.data as? BarChartData
            else { return }
        
        if fitBars
        {
            _xAxis.calculate(
                min: data.xMin - data.barWidth / 2.0,
                max: data.xMax - data.barWidth / 2.0)
        }
        else
        {
            _xAxis.calculate(min: data.xMin, max: data.xMax)
        }
        
        // calculate axis range (min / max) according to provided data
        _leftAxis.calculate(
            min: data.getYMin(.Left),
            max: data.getYMax(.Left)*1.1)      //  here: multiply 1.1
        _rightAxis.calculate(
            min: data.getYMin(.Right),
            max: data.getYMax(.Right)*1.1)   // here: multiply 1.1 too
    }

**Comment by danielgindi** [comment]
Please if you have something fix - add screenshots, and issue a PR.

Anyway, I don't see any issue (at least with Charts 3.0 which I've tested). The max-y label draws just fine :-)
