### ISSUE TITLE
Distance between chart legend and the chart is to big in case of rotated labels

### ISSUE THREAD

**Issue by SvenMuc** [danielgindi/Charts#1360]
Hi,

I have a horizontal bar chart as shown in the picture. As soon as I rotate the x-axis labels the distance between the legend and the chart increases. Any ideas how to reduce the gap?

`chart.xAxis.labelRotationAngle       = -90.0 `

![chart_legend](https://cloud.githubusercontent.com/assets/13385716/17982494/4914db16-6b08-11e6-91be-c4d3f74beb69.png)

**Comment by danielgindi** [comment]
What version of Charts is this?

**Comment by danielgindi** [comment]
@PhilJay is it possible that offsets/calculations of xAxis affect the yAxis in horizontal charts?

**Comment by PhilJay** [comment]
Hey man, sorry for the late reply, I was on vacation (once again). Yes, that could be the case, this should be investigated!

**Comment by SvenMuc** [comment]
>What version of Charts is this?

 I'm using version 2.2.5

**Comment by kientux** [comment]
+1

This happens with line chart too.

**Comment by danielgindi** [comment]
I can't reproduce this on Charts 3.0. Seems solved to me :-)

**Comment by srswanson** [comment]
I am experiencing the same issue with line charts in Charts 3.0.1.

    windChartView.legend.orientation = .horizontal
    windChartView.legend.verticalAlignment = .top
    windChartView.legend.horizontalAlignment = .center
    windChartView.legend.font = UIFont.preferredFont(forTextStyle: UIFontTextStyle.footnote)

    windChartView.xAxis.labelRotationAngle = 90 (also happens with -45 and 45)

**Comment by SvenMuc** [comment]
This bug is not yet solved. I can reproduce it with the latest Charts 3.x versions. If I merge the fix from my pull request #2138 everything works as expected.

@danielgindi @PhilJay @liuxuan30 
When are planning to merge the fix/pull request #2138 into to official version?

**Comment by thierryH91200** [comment]
see also #2414

**Comment by liuxuan30** [comment]
sorry. It has been busy all the time.
I need some recalls. I remember it's not just for horizontal bar chart right? such as #2414 as above?

Can we apply it to other charts? If they are different issue and #2214 is just for horizontal bar chart, I think I could help merge recently. But we need to figure out the scope first.

**Comment by SvenMuc** [comment]
@liuxuan30 they look somehow related. But I'm not sure if the same fix solves both issues.

#2414 deals with offset issue with 90° rotated labels in a line chart
#2138 deals with offset issue with 90° rotated labels in a horizontal bar charts
