### ISSUE TITLE
There are two lines. The first number starts from scratch, but only one is from zero. The other one has a certain amount of cheap quantity. How do I get the other one from zero.

### ISSUE THREAD

**Issue by dawangjiaowolaixunshan** [danielgindi/Charts#1363]
There are two lines. The first number starts from scratch, but only one is from zero. The other one has a certain amount of cheap quantity. How do I get the other one from zero.

             for (int i = 0; i < count; i+= 1) {
                 NSMutableDictionary *dict = [NSMutableDictionary dictionary];
                 DHfundDataModel *mode3 = fundDataArry[i];
                 DHbaseDataModel *mode4 = baseDataArry[i];
                 dict[@"date"] = [mode3.tdate substringFromIndex:5];
                 //funData
                 double valueFun = [mode3.fund_nav doubleValue] / mode1Value - 1 ;
                 // base
                 double valueBase = [mode4.pchg doubleValue] / mode2Value - 1 ;

                // thirst one is zero ...   valueBase is blue ... valueFun..origen.
                 if (i==0) {
                     valueFun= 0.0;
                     valueBase = 0.0 ;
                     
                 }
                 [funDataSum addObject:@(valueFun)];
                 [baseDataSum addObject:@(valueBase)];
                 
             
                 dict[@"ben"] = [NSString stringWithFormat:@"%f",valueFun];
                 dict[@"bi"] = [NSString stringWithFormat:@"%f",valueBase];
                 
                 [chartData addObject:dict];
             }
             
             [self setDataWithArray:chartData wihtMinValue:minValue  withMax:maxValue ];

![image](https://cloud.githubusercontent.com/assets/11595694/18024739/38b082b0-6c44-11e6-9dc6-a6828073a3e9.png)

**Comment by danielgindi** [comment]
Add a 0.0 value....
