### ISSUE TITLE
swift 3 branch does not compile with Xcode 8 beta 6

### ISSUE THREAD

**Issue by alpascual** [danielgindi/Charts#1364]
Downloading the swift 3 branch and trying to compile with Xcode 8 beta 6 is not possible. Looking at the code, there are many files that didn't migrate to the latest swift 3.0. Do you accept PRs?

**Comment by danielgindi** [comment]
Please post it here: https://github.com/danielgindi/Charts/issues/1291

**Comment by liuxuan30** [comment]
should be working now... macOS portion is pending.
