### ISSUE TITLE
Charts is ~20M when built. Desired?

### ISSUE THREAD

**Issue by Undo1** [danielgindi/Charts#1365]
I just noticed that the new version of my app (which adds Charts, from Cocoapods) is much bigger than it previously was. After some digging, I found that the Charts framework is the culprit, weighing in at ~20MB in a built IPA file. 

Does this sound correct? Is there a way to trim it down? I'm only using a *very* simple line chart, so I suspect there's stuff in here I don't really need.

**Comment by hardikdevios** [comment]
+1 even it takes time to Compile

**Comment by danielgindi** [comment]
Charts is just code, so it won't take so much.
Your app isn't Swift right?
Xcode adds libSwift to your app, which adds around 20MB to your project. That's normal, don't worry about it.

**Comment by Undo1** [comment]
@danielgindi My app is pure Swift, with the exception of XLForms (which was present before).

**Comment by Undo1** [comment]
To be clear about what I'm seeing:

```
MyApp 3 2016-08-27 09-37-49/Payload/MyApp 3.app/Frameworks » du -sh *                                                                                                                                                                                                                                                               parkererway@Development-9
 20M	Charts.framework
7.2M	MathParser.framework
2.9M	XLForm.framework
292K	libswiftContacts.dylib
 41M	libswiftCore.dylib
784K	libswiftCoreGraphics.dylib
252K	libswiftCoreImage.dylib
536K	libswiftDarwin.dylib
340K	libswiftDispatch.dylib
4.6M	libswiftFoundation.dylib
484K	libswiftObjectiveC.dylib
544K	libswiftUIKit.dylib
-----------------------------
```

**Comment by danielgindi** [comment]
The code itself, uncompiled, weight only a few hundred KBs, so I see no reason for this...

**Comment by danielgindi** [comment]
Now this is for the demo app, in debug mode. Highly unoptimized, with lot's of debugger overhead code...

<img width="725" alt="screen shot 2016-08-29 at 11 03 10 pm" src="https://cloud.githubusercontent.com/assets/366926/18065527/e050c058-6e3c-11e6-982d-d00ba55d8f28.png">

**Comment by Undo1** [comment]
Me neither. If it helps, I'm installing it with Cocoapods, and no Realm support (just `pod 'Charts'`)

**Comment by danielgindi** [comment]
I see that MathParser.framework also takes up 7MBs. I'm not familiar with that framework, but it seems to be something that's even less code than a charting library. Should be a few KBs compiled.
I think there's something that's just very weird with your configuration...

**Comment by danielgindi** [comment]
Or could it be because of BitCode? Maybe the intermediate language that Apple uses to re-compile on their servers is MB hungry.

**Comment by Undo1** [comment]
I'll try compiling without Bitcode, that's an interesting hypothesis.

**Comment by Undo1** [comment]
Turning off Bitcode did nothing - if anything, it made it *worse* (!?). I'm going to agree that I have something bizarre in my project settings. I notice that even the `libswift*` frameworks in your screenshot are much smaller than mine.

**Comment by dxclancy** [comment]
FWIW, in my archive from April, Charts is 10MB.

**Comment by danielgindi** [comment]
@dxclancy "highly unoptimized" means larger binary

**Comment by danielgindi** [comment]
@Undo1 maybe you can post on Apple's forums about this?

**Comment by Undo1** [comment]
This seems to have been fixed by removing Cocoapods (completely) and manually including the .xcodeproj files for the various frameworks. I'm seeing Charts at 4.4MB in the archive now.

Thank you for you time on this!

**Comment by StarRain-L** [comment]
Excuse me,I met the same problem,and I didn't use cocopod,   I just copy "Charts-master" file to my project,can you help me how to solve  this issue?Don't know why my archive export so big.
![eb28a52a-a44c-4cdb-9e7b-ada5a8cfc69f](https://cloud.githubusercontent.com/assets/8908244/21598245/313e17e4-d194-11e6-95fa-dca391b6a8ea.png)

**Comment by liuxuan30** [comment]
As I mentioned in your earlier post #2015, Charts itself is about 6.5M after optimization. The dylib you are posting is Swift libraries, which are essential to run any swift code, so far you can do nothing until swift is ABI stable and release with the OS, not the app. Once swift is packed into iOS, app does not need to embed swift lib any more.

**Comment by StarRain-L** [comment]
You mean I don't care, this is no problem?Just see the blogger, wonder if something is wrong with my  archive export.

**Comment by liuxuan30** [comment]
It should be the least thing you need to worry.

**Comment by StarRain-L** [comment]
Ok, then I can try to archive export the secure, thank you very much,
