### ISSUE TITLE
Cannot use PieChartDataSet or PieChartDataEntry when include with Cocoapod

### ISSUE THREAD

**Issue by LeChatNoir69** [danielgindi/Charts#1366]
Hi,

I've included Charts with cocoapod successfully in my Objective-C project. I can use ChartView object without complication error.

But when it come to user for example PieChartDataEntry, I got a compilation error (undeclared). 

I've removed the Chart line from my podFile, made a pod install (to effectively remove library) and import it the "old school" method and this time, it's ok.

I think there is an issue with the cocoapod method

**Comment by SalehAlDhobaie** [comment]
I'm the same issue here. :(

**Comment by danielgindi** [comment]
The code on `master` is Charts 3.0, which is in beta, not released to Pods.

**Comment by nthegedus** [comment]
@danielgindi so, there is no way to create a PieChartView?

**Comment by danielgindi** [comment]
Of course there is, with a basic `ChartDataEntry`. Why are you not exploring the demos for 2.2.5?

**Comment by LeChatNoir69** [comment]
The point is when you install using cocoapod, you download the demoProject of the github portal. And here you see the new classes so you try to use it.
Just a matter of time. When the V3 will be released, there won't be confusion anymore.

Thank you for the great job daniel by the way !

**Comment by wirakoon78** [comment]
There is a big difference between ChartDataEntry and PieChartDataEntry.
