### ISSUE TITLE
Charts 3.0 and Swift 2.3 branch?

### ISSUE THREAD

**Issue by UberJason** [danielgindi/Charts#1370]
Hello,

I've been working directly off of the master branch, which seems to be the new Charts 3.0 API (there were several big API differences between master and the last 2.2.5 release). Now I'm trying to migrate my project to Swift 2.3 ahead of the iOS 10 release, so I changed my dependency to use the Charts "Swift-2.3" branch - but it appears that this branch is still based on the old 2.2.5 API. Is this the case? Are there any plans to bring the Swift-2.3 branch in line with the Charts 3.0 API? Apologies if this is documented somewhere - I couldn't find any sort of roadmap for the project.

**Comment by danielgindi** [comment]
Swift 2.3/3.0 are **beta** right now, and we do not support it officially as you should not compile against it right now. It changes from beta version to beta version.

There are, however, temporary Swift 2.3/3.0 branches, which are there for people wanting to experiment with beta stuff right now. It is based on Charts 3.0 because that is the version that is most likely to be released right before (or right with) the new Xcode/iOS/Swift.

It takes time and effort to create and maintain those branches, and these are maintained by good people here who invest their time in it, I certainly do not have the time for it :-)

So if you'd like, you can create a PR for a new branch of your liking. It will be automatically removed when `master` will be migrated to Swift 3.0.

**Comment by UberJason** [comment]
Hi Daniel,

That was my question - I was in fact asking about the temporary Swift-2.3 branch, which does _not_ appear to be based on Charts 3.0. But it sounds like you are not really involved with that branch, so wouldn't know the story there, is that accurate?

**Comment by liuxuan30** [comment]
@danielgindi Charts 3.0 is developing while I am maintaining the swift 3.0 branch, so it's kind of scattered. Charts v3.0 code is not merged into swift 3.0 branch yet.

As swift 3.0 changes so much from beta to beta, it looks like we don't have the man power to do a full conversion again.. merging master into swift-3.0 may cause more troubles than I think.

@UberJason May I know your needs? Swift 3.0 branch is just for apps to test iOS 10 only. Once swift 3.0 is released, we will directly convert it from master.

**Comment by UberJason** [comment]
Thanks @liuxuan30. My needs are not strong enough to impact your roadmap, I don't think. I built a chart using Charts 3.0 from master a couple weeks ago, and we're updating our project to iOS 10 this week going forward (we regard the last betas in August as stable enough to let us start that work), and I just noticed that the Swift-2.3 branch of the Charts project wasn't based on the Charts 3.0 API. For now I've forked master and converted it to Swift 2.3 for our own needs, and when we're ready to go to full Swift 3.0 after launch, as well as once you've updated Charts 3.0 to be Swift 3, I'll at that time probably revert to using the real Charts library.

**Comment by liuxuan30** [comment]
yeah, 2.3 is much easier to convert, I will consider to sync swift 2.3 branch with master when got time, or you could file a PR if possible. Thanks

**Comment by liuxuan30** [comment]
Swift-2.3 branch is synced with master

**Comment by UberJason** [comment]
Thanks very much, @liuxuan30!

**Comment by UberJason** [comment]
Hi,

No pressure at all, just curious if you guys have a timeline for:
* Charts 2.2.5 formally running with Swift 3 in master, and
* Charts 3.0 with Swift 3 (which you mentioned would be difficult a couple weeks back)

As I mentioned previously, I built a chart with Charts 3.0 (Swift 2.2) a month or so ago, and we're hoping to update our own project to Swift 3 in the next week. If you plan to do Charts 3.0 with Swift 3 soon, we may wait; if that's far off in the future, I'll consider either going back to Charts 2.2.5 on Swift 3, or temporarily forking Charts 3.0 and manually converting it to Swift 3. So no pressure, just would love to know, thanks!

**Comment by liuxuan30** [comment]
Charts 2.2.5 with swift 3.0 is already in Swift 3.0 branch. Please take a look at #1291 for information

**Comment by UberJason** [comment]
Thanks - to clarify, how about Charts 3.0 in Swift 3? I also posted this in the other thread.

**Comment by danielgindi** [comment]
Charts 3.0 in Swift 3.0 is on `master` branch

**Comment by UberJason** [comment]
🎉
