### ISSUE TITLE
please  tell me how do i  handling these problems，thanks！

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1373]
how do i custom value different colors  in  LineChart？
and how do i custom unit in chartView in x-axis  or  y-axis？   for example UI
![image](https://cloud.githubusercontent.com/assets/20593532/18084377/9aa8a4ec-6ed9-11e6-9853-84c78fa45d1b.png)

**Comment by liuxuan30** [comment]
Please check out ChartsDemo for the unit, seems a formatter is enough.
For the color, if you are talking about highlight, it's `highlightColor`. If you only want specific color is different, check out `circleColors`

**Comment by yushan023** [comment]
For the color,it's not highlightColor. It's normalColor, it can show different color on chartView in the same time.

**Comment by liuxuan30** [comment]
well to me the last circle is highlighted. anyway, `circleColors` is the answer

**Comment by yushan023** [comment]
thanks a lot. I find the circleColors is Array.But the problem is the last circle must be shining. 
i won't set hightlighted.can you teach me?

![ed0ac298-b472-4042-b94e-65da48a19295](https://cloud.githubusercontent.com/assets/20593532/18296358/ae95f498-74db-11e6-9625-41e8a3c245eb.png)

**Comment by liuxuan30** [comment]
circleColors is array.. then why don't you set the last color as orange.. am I missing anything or you don't think about it

**Comment by yushan023** [comment]
First, I didn't find circleColors before this property.Thanks you for helping me before.
Not the last one is yellow.Sometimes it is in the middle.This is no problem.

But I have a problem not solved.
"circleHoleColor"  can only be  set  once.Once set this property, the curve on the other round also become this attribute.
setting  "circleHoleColor" Which means that light.I only want a yellow light.And you said the highlightColor of is not what I want.

**Comment by liuxuan30** [comment]
```swift
    /// The radius of the drawn circles.
    var circleRadius: CGFloat { get set }
    
    /// The hole radius of the drawn circles.
    var circleHoleRadius: CGFloat { get set }
    
    var circleColors: [NSUIColor] { get set }
    
    /// - returns: the color at the given index of the DataSet's circle-color array.
    /// Performs a IndexOutOfBounds check by modulus.
    func getCircleColor(_ index: Int) -> NSUIColor?
    
    /// Sets the one and ONLY color that should be used for this DataSet.
    /// Internally, this recreates the colors array and adds the specified color.
    func setCircleColor(_ color: NSUIColor)
    
    /// Resets the circle-colors array and creates a new one
    func resetCircleColors(_ index: Int)
    
    /// If true, drawing circles is enabled
    var drawCirclesEnabled: Bool { get set }
    
    /// The color of the inner circle (the circle-hole).
    var circleHoleColor: NSUIColor? { get set }
    
    /// True if drawing circles for this DataSet is enabled, false if not
    var drawCircleHoleEnabled: Bool { get set }
```
Which version are you using? As you see, lots of properties to use, so maybe try them to figure out what best for you

**Comment by yushan023** [comment]
My boss want me to do so,the following figure.
![805e1c25-928f-49c2-b071-cc7850419153](https://cloud.githubusercontent.com/assets/20593532/18371890/a5e4ca00-766a-11e6-982b-9ef62f1d0674.png)
But I just realized it.

**Comment by yushan023** [comment]
I want to achieve this.
![805e1c25-928f-49c2-b071-cc7850419153](https://cloud.githubusercontent.com/assets/20593532/18371984/6051d586-766b-11e6-9db9-e89bafafa5bb.png)
 If is yellow must use "circleHoleColor" this property.But once set this property, the red will also corresponding change.
I don't want to let the red also have become "circleHoleColor" this property, I just want to set this property "circleHoleColor" yellow.
At present, I can only be implemented as such, the following figure.
![abcd007d-b9a1-4fbb-bc37-5243aef51f3e](https://cloud.githubusercontent.com/assets/20593532/18371988/6d538e5a-766b-11e6-9705-bbd403a972c4.png)

**Comment by liuxuan30** [comment]
Ah I see. circleHoleColor is not array, it's just the hole color. Guess you have to override `drawCircles` to get what you want.

**Comment by yushan023** [comment]
I think override "drawCircles"  this method also can not solve Because the yellow is not necessarily at the end.Can  use pictures on it？
