### ISSUE TITLE
Charts errors in xcode beta 6

### ISSUE THREAD

**Issue by Mouflin-Guillaume** [danielgindi/Charts#1375]
Hello,

I want to use Charts libraries in my projet on xCode beta 6 but I have got some errors in different files.
When this lib will be update for beta 6? 

<img width="257" alt="screen shot 2016-08-30 at 15 05 10" src="https://cloud.githubusercontent.com/assets/11991496/18090066/4dc28398-6ec3-11e6-8c5e-c05358d7d6bf.png">

**Comment by danielgindi** [comment]
https://github.com/danielgindi/Charts/issues/1291
