### ISSUE TITLE
infinite recursion in HorizontalBarChartHighlighter

### ISSUE THREAD

**Issue by dbquarrel** [danielgindi/Charts#1377]
The else branch here calls itself recursively forever. It should be a call to super. Might want to check all similar code to see if it has the same issue. Issue is triggered when you have grouped charts and click just outside the bars. 

    public override func getXIndex(x: CGFloat) -> Int
    {
        if let barData = self.chart?.data as? BarChartData
            where !barData.isGrouped
        {
            // create an array of the touch-point
            var pt = CGPoint(x: 0.0, y: x)
            
            // take any transformer to determine the x-axis value
            self.chart?.getTransformer(ChartYAxis.AxisDependency.Left).pixelToValue(&pt)
            
            return Int(round(pt.y))
        }
        else
        {
            return getXIndex(x)
        }
    }

**Comment by danielgindi** [comment]
Irrelevant, this code does not exist anymore...

**Comment by dbquarrel** [comment]
When did it go? It's in what came out of cocoapods for me.

**Comment by liuxuan30** [comment]
in master branch, as v3 is merged

**Comment by dbquarrel** [comment]
I'm asking because cocoapods is installing this as 2.2.5 and that's what you get if you use a cocoapods install and there's no newer one. So either I'm using cocoapods wrong (possible) or there's some kind of issue with that config. I can see in the repository here that it's been updated, yes, but I had no way of knowing beforehand. I thought I had the most up to date version and there's other broken things constantly so it's never clear what you can rely on.

**Comment by liuxuan30** [comment]
v3.0 is not released, so pods not updated yet. 
I just remember I merged the fix: https://github.com/danielgindi/Charts/pull/1213. If possible, you can fix it on your side. But it seems pod will not be update for this fix.
