### ISSUE TITLE
Charts-Swift.h is different

### ISSUE THREAD

**Issue by qiaoxiaolan** [danielgindi/Charts#1380]
Why your Charts-Swift.h like this: `SWIFT_CLASS("_TtC6Charts14ChartDataEntry")
@interface ChartDataEntry : ChartDataEntryBase
`
mine like this: `SWIFT_CLASS("_TtC6Charts14ChartDataEntry")
@interface ChartDataEntry : NSObject
`

The superClass and functions are different.
I used CocoaPods,the Charts version is 2.2.5 too.

**Comment by LMkillme** [comment]
me too, I used CocoaPods,the Charts version is 2.2.5 , haven't "RadarChartDataEntry"

**Comment by brendenk1** [comment]
I also had to remove my cocoa pods integration because it was an incomplete implementation. I was using Pie Charts and it was missing PieChartDataEntry.

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/issues/1366 https://github.com/danielgindi/Charts/issues/1358

**Comment by liuxuan30** [comment]
for different header, please do a full clean and rebuild, also double check the code. never seen this..

**Comment by qiaoxiaolan** [comment]
[#1366](https://github.com/danielgindi/Charts/issues/1366) [#1358](https://github.com/danielgindi/Charts/issues/1358) This helped me. Thank @liuxuan30 .
