### ISSUE TITLE
How to show/hide one of the line chart during runtime

### ISSUE THREAD

**Issue by nonameplum** [danielgindi/Charts#1381]
Hi,

I have UISwitches in the UI that allow a user show/hide (3) lines of the linechart.
At the beginning I want to show only one line chart when `viewDidLoad`. But the problem is that hiding during `viewDidLoad` is not working. When view is loaded and user is changing visibility of the lines using switches then it works.

```swift
func showLine(label: String, visible: String) {
    lineChartView.data?.getDataSetByLabel(label, ignorecase: false)?.visible = visible
    lineChartView.setNeedsDisplay()
}
```

When I move code from the `viewDidLoad` to the `viewDidAppear` then it also works but there is visual side effect that user sees that line are hiding which I would like to avoid.

I found that there is also another way using ugly hack. When I wrap body of the `showLine` method to the `dispatch_after` with e.g. 0.2 sec.

Is there a way to resolve this problem?

**Comment by liuxuan30** [comment]
are you hiding specific lines or line chart views, I am confused.

**Comment by nonameplum** [comment]
Exactly. I want to hide only specific lines

**Comment by liuxuan30** [comment]
Either add/remove the specific line chart data sets or leverage
```
    /// Set the visibility of this DataSet. If not visible, the DataSet will not be drawn to the chart upon refreshing it.
    var visible: Bool { get set }
```
