### ISSUE TITLE
Undeclared or undefined identifiers while trying to compile project

### ISSUE THREAD

**Issue by alexmocanu** [danielgindi/Charts#1383]
I'm trying to integrate this library into my Swift OSX project but every time I try to compile it I get errors like these:

    Renderers/ChartYAxisRenderer.swift:272:111: Use of undeclared type 'NSTextAlignment'
    Renderers/ChartYAxisRenderer.swift:299:105: Use of unresolved identifier 'NSFontAttributeName'
    Renderers/ChartYAxisRenderer.swift:480:38: Use of unresolved identifier 'NSFontAttributeName'
    Renderers/ChartYAxisRenderer.swift:470:72: Use of unresolved identifier 'NSForegroundColorAttributeName'
    Charts/PieRadarChartViewBase.swift:558:41: Use of unresolved identifier 'CACurrentMediaTime'

There seems to be some missing imports in some classes. In the end, as a quick fix, I ended up adding the imports bellow to all files with these issues:

    import QuartzCore
    import AppKit
    import Cocoa

Charts 2.2.5
OSX 10.11
Xcode 7.3.1

**Comment by liuxuan30** [comment]
I don't think so.. Have you run the OSX ChartsDemo project? It should be working.

**Comment by danielgindi** [comment]
I guess he dragged the code files, instead of dragging the Charts.xcodeproj to his project.

**Comment by thierryH91200** [comment]
I see the same issue as well.

in places where there are errors
"Import Cocoa"
and it works

you can follow this link : https://github.com/thierryH91200/Charts-Mac

#1197

**Comment by liuxuan30** [comment]
can be closed?

**Comment by alexmocanu** [comment]
The issue was on my side. I dragged the code files themselves instead of the xcodeproj file.
