### ISSUE TITLE
BarChartData Class is Missing InitWithXVals

### ISSUE THREAD

**Issue by brendenk1** [danielgindi/Charts#1385]
Currently on master branch and the project has no way to set x values for bar chart that is not a double value. I am at a loss.

**Comment by chuynadamas** [comment]
Hey @brendenk1 I'm not a chart collaborator, but I'm using the library for a while and the 3.0 doesn't use the x values as an array, now you set the x value on every entry.  :)

**Comment by liuxuan30** [comment]
suppose we could close
