### ISSUE TITLE
Need help in setDrawValues

### ISSUE THREAD

**Issue by SuhailRanger** [danielgindi/Charts#1391]
The method [data setDrawValues:YES]; 
draw values from yValues i want to draw them from xValues like attached image.

Please reply if you have any suggestion or any link that guide me.

![image](https://cloud.githubusercontent.com/assets/21708788/18194163/4c928866-7101-11e6-9454-10069dc78a00.png)

**Comment by liuxuan30** [comment]
I don't know where you got stuck. Have you tried latest master?

**Comment by SuhailRanger** [comment]
Let me explain the scenario : 

yValues = [2.0, 3.0, 6.0, 7.0]
xValues = ["06/05","07/05","08/05","09/05"]

Now when i use  [data setDrawValues:YES]; 
it draws values from yValues like 6.0 i want to draw "06/05" in place of it. :(

**Comment by danielgindi** [comment]
The you should use formatters, to convert between the doubles and the dates. A double can represent any value you want. Please look at the demo of Charts 3.0
