### ISSUE TITLE
How to create a Pie chart, no 'how to' ?   .   The demo app sucks, doesn't compile.

### ISSUE THREAD

**Issue by unittesting0** [danielgindi/Charts#1392]
I'm interested to create a pie chart and can't find any code how to do this, anyone can help me?

How to initialize the chart, it's attributes.

And how to set Data?

**Comment by danielgindi** [comment]
This kind  of negative attitude won't get you any help. Now the only answer that anyone here wants to give you is "The demo app works. You are (probably) a grown man, figure out how to compile a simple Xcode project on your own."

**Comment by unittesting0** [comment]
@danielgindi if you want I can record my screen and show it to you that the demo app doesn't compile!

**Comment by liuxuan30** [comment]
@unittesting0 then please record, I wonder how it won't compile. Why don't you just search the error message or key words? Or at least post the error log? Just saying 'won't compile' does not help at all.
