### ISSUE TITLE
How to customize left axis with string values?

### ISSUE THREAD

**Issue by Sunitadaffodil** [danielgindi/Charts#1394]
I need to display 10K instead of 10000. so i need to customize the left axis labels with string values

**Comment by liuxuan30** [comment]
use a custom `valueFormatter`

**Comment by Sunitadaffodil** [comment]
I know it could be done using valueFormatter but it accepts only NSNumberFormatter. so could u pls tell how..if we can use other custom formatter or can do the same using NSNumberFormatter.

**Comment by liuxuan30** [comment]
you need to subclass NSNumberFromatter and override the method to get what you want. BTW, remember to check out current master branch, it is `public protocol IAxisValueFormatter : NSObjectProtocol` now
