### ISSUE TITLE
HorizontalBarChartView not show value at bar

### ISSUE THREAD

**Issue by xialina** [danielgindi/Charts#1396]
![2016-09-06 9 53 52](https://cloud.githubusercontent.com/assets/4034309/18259585/287d386c-7418-11e6-8097-57cae441580c.png)

![simulator screen shot 2016 9 6 9 53 02](https://cloud.githubusercontent.com/assets/4034309/18259551/b8c4dad4-7417-11e6-96fc-94ce243223aa.png)

**Comment by liuxuan30** [comment]
can you explain 'not show value at bar' ? I see there are values at y and x axis, but x axis is not aligned center. 
BTW, which version are you using?
