### ISSUE TITLE
Barchart,,,,draw specific value

### ISSUE THREAD

**Issue by yoonyoungji** [danielgindi/Charts#1397]
Thank you for awsome ios charts
I use this graph so effectively.
But I have a small problem. I want to show specific value that user tabs the graph
(I want to draw highlight bar's point value )
My bar graph set all value is hide , but I want to draw value that user tab specific value
please, help... Would you explain some example or code? :)

**Comment by liuxuan30** [comment]
How about using ChartMarker?

**Comment by yoonyoungji** [comment]
I want to know about ChartMarker how to use......Another Issues recommend to override draw highlight .. but I don't understand what to do...

**Comment by liuxuan30** [comment]
Check ChartsDemo... Read `drawHighlighted` code
