### ISSUE TITLE
Negative Bar Chart

### ISSUE THREAD

**Issue by resurrection-crisis** [danielgindi/Charts#1401]
![screen shot 2016-09-06 at 3 08 40 pm](https://cloud.githubusercontent.com/assets/19650723/18269005/e81a4914-7443-11e6-9c9f-e8245151bc7d.png)

First of all thank you for great charts.
How to achieve the same using negative stack bar chart? I want to move the left axis to the centre as in the image.

**Comment by danielgindi** [comment]
See the demo, there are examples of this chart.
Basically, just add negative values, and make sure that the Y axis is not constrained to a minimum of 0.0
