### ISSUE TITLE
Query: How to create an area graph?

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1402]
I am trying to create an area graph with the min and max value for each points.But did not found anywhere .I guess setting the background color in the area between two  line graph should solve this.

Tried setting fillColor for two data sets as.

```
.fillColor = UIColor.lightGrayColor()
.drawFilledEnabled = true
```

This did not work.How is this possible?

**Comment by danielgindi** [comment]
Check out the sample in Charts 3.0

**Comment by anishparajuli555** [comment]
Is this available in swift 2.3?

**Comment by anishparajuli555** [comment]
i cant find charts 3.0?

**Comment by anishparajuli555** [comment]
Can you help me in converting this code to swift?
```
 set2.fillFormatter = [ChartDefaultFillFormatter withBlock:^CGFloat(id<ILineChartDataSet>  _Nonnull dataSet, id<LineChartDataProvider>  _Nonnull dataProvider) {
            return _chartView.leftAxis.axisMaximum;
        }];
```

**Comment by anishparajuli555** [comment]
@danielgindi 
 I have tried converting the demo in swift..Setup all the necessary things..But doesn't work...Please have a look at this question.

http://stackoverflow.com/questions/39449992/cant-draw-area-graph-using-ios-charts
