### ISSUE TITLE
Customize popup on entry tap

### ISSUE THREAD

**Issue by ShaiGivati464** [danielgindi/Charts#1403]
Is there a way to customize the appearance and text in the popup shown on tap some entry? Is there an example for it in the demo?

**Comment by danielgindi** [comment]
Yes there is. The BalloonMarker in the demo is a sample of that.
Also in Charts 3.0 it becomes much easier to create custom markers from different sources - a UIView, a UIImage etc. So check out the demos of Charts 3.0 also.
