### ISSUE TITLE
drawSliceTextEnabled = YES not working

### ISSUE THREAD

**Issue by sleith** [danielgindi/Charts#1404]
Hi, 
i use pod chart to install it.
And try copy from demo for setupPieChartView function.
and also added chartView.drawSliceTextEnabled = YES;
But i can still see the text in the slices.
Please help

thanks

**Comment by irpainel** [comment]
@sleith , I found the answer
Check the reply in: https://github.com/danielgindi/Charts/issues/17

**Comment by danielgindi** [comment]
`YES` is the default. You might want to `NO`
