### ISSUE TITLE
I can't see the zero(float Num)  on ChartYAxis

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1407]
the lastest verson has bug??

![f685879e-39c6-446a-b6f3-a52ed7daf428](https://cloud.githubusercontent.com/assets/20593532/18304904/94745e1a-7517-11e6-91c7-a8f4758f60d2.png)

**Comment by liuxuan30** [comment]
do check `NSNumberFormatter` APIs

**Comment by yushan023** [comment]
thanks a lot!
