### ISSUE TITLE
Query: Enable gridelines at specific location points.

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1410]
I have disabled gridlines as

```
lineChart.rightAxis.drawGridLinesEnabled = false
lineChart.xAxis.drawGridLinesEnabled = false
```

And the result is as below:
![screen shot 2016-09-07 at 5 47 01 pm](https://cloud.githubusercontent.com/assets/7752578/18311307/53b6f066-7523-11e6-8b48-57d3d24675b8.png)

However, i need to show vertical gridlines  at specific locations..How can i acheive this?

**Comment by liuxuan30** [comment]
for specific location 'grid line', check out 'ChartLimitLine'

**Comment by anishparajuli555** [comment]
I am able to draw horizontal grid lines but not vertical.

```
let limitSet1 = ChartLimitLine(limit: 232, label: "")
lineChart.rightAxis.addLimitLine(limitSet1)
```

**Comment by liuxuan30** [comment]
vertical? xAxis.addLimitLine

**Comment by anishparajuli555** [comment]
@liuxuan30 nope..That doesnot works...No Line appears

**Comment by liuxuan30** [comment]
It should work. limit lines can be added on both x and y axis. Unless you say 'ChartsDemo' does not work neither.

**Comment by anishparajuli555** [comment]
@liuxuan30 Thanks..It works...i had problem setting the Limit value.
