### ISSUE TITLE
How to set background color of bars

### ISSUE THREAD

**Issue by nexig** [danielgindi/Charts#1411]
I need to set my bars look like this 
![image](https://cloud.githubusercontent.com/assets/10259698/18313082/28a7b8c6-750d-11e6-866d-285b03b5ac33.png)

any idea how to set white space above filled bar ?

**Comment by liuxuan30** [comment]
how about 
```
    /// the color used for drawing the bar-shadows. The bar shadows is a surface behind the bar that indicates the maximum value
    public var barShadowColor = NSUIColor(red: 215.0/255.0, green: 215.0/255.0, blue: 215.0/255.0, alpha: 1.0)
```

**Comment by nexig** [comment]
It works perfect. 

Thaks

**Comment by Vektrat** [comment]
Hello,

I was having the same issue and stumbled upon this post. However the shadow color does not seem to exactly cover that of the bar, but it extends a bit more, is there any other related offset I need to adjust for it to fit the bars? You can see the overflowing shadow on the bottom in the image.

<img width="321" alt="screen shot 2016-09-14 at 08 52 31" src="https://cloud.githubusercontent.com/assets/434196/18502662/9eef17a4-7a58-11e6-80a8-f3fdcec413ed.png">

Thank you in advance!
