### ISSUE TITLE
Query : When it will be available in CocoaPods?

### ISSUE THREAD

**Issue by chandni-solanki07** [danielgindi/Charts#1412]
When it will be available in Cocoa pods as right now version 2.2.5 is available.

I am really waiting for version 3.0 for its cool new features which I need to integrate in my project.

Thanks.

**Comment by liuxuan30** [comment]
having to wait until significant bugs got fixed. If you like the v3 features, why not just check out master branch? pods and carthage will always be late as they releases

**Comment by marc-inn** [comment]
Bumping question. Can I ask you about estimated time for pods (We have convention in our project to use only pods and 3rd version of lib, has important feature for us)? Btw. The best charting library in the mobile world!

**Comment by cpboyd** [comment]
If you need to use CocoaPods, couldn't you just use the following?

```
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Swift3.0-ChartV3'
```

**Comment by marc-inn** [comment]
Superb! Thank you  👍

**Comment by liuxuan30** [comment]
'Swift3.0-ChartV3' is not available yet. Use others

**Comment by petester42** [comment]
When v3 is released Ill push the update to the pod.
