### ISSUE TITLE
Custom X-Axis Values

### ISSUE THREAD

**Issue by gaganindersingh** [danielgindi/Charts#1413]
I am using Charts in Objective-c project. Trying to draw a LineChart with X-Axis value that represents time. Like 12:45, 12:50 etc. Using the sample code i am able to draw the graph but the values in the x-axis are not exact. I have x-axis values with one minute interval. The map is showing currently 2,4,6,8,10,12 only on the x-axis. How can i customize the values?

**Comment by yushan023** [comment]
IChartAxisValueFormatter  delegate    
![55642c8d-e928-4795-bf31-f1634836b146](https://cloud.githubusercontent.com/assets/20593532/18333286/36af5c4c-75a0-11e6-90b5-9323dece0101.png)
![7a8a103e-b189-4202-ae76-7cc9590661e3](https://cloud.githubusercontent.com/assets/20593532/18333296/436207dc-75a0-11e6-916a-f099174e2131.png)

you also see demo in PositiveNegativeBarChartViewController.h

**Comment by liuxuan30** [comment]
do you mean in x axis values, you have 1,2,3,4,5...10, but it just shows 2,4,6,8,10?

**Comment by baodiaoshounansha** [comment]
me to , i want to know author how to get data to the "value".it looks like that i didnot find where i can custom the "value"

**Comment by anishparajuli555** [comment]
I am also thinking how to draw custom values in x-axis as 
![screen shot 2016-09-08 at 11 58 28 am](https://cloud.githubusercontent.com/assets/7752578/18338868/a2eb0166-75bb-11e6-9555-e374841ec512.png)

**Comment by liuxuan30** [comment]
have you guys checked Chart v3.0 ChartsDemo - Time Line Chart? Same thing?

**Comment by anishparajuli555** [comment]
@liuxuan30 Thats just a value formatter. Doesn't fill.For now,How can i customize the background Color? Or put a custom view ?

**Comment by gaganindersingh** [comment]
I have implemented the value formatter now from the demo project but here comes the problem again.
![screen shot 2016-09-10 at 3 01 47 am](https://cloud.githubusercontent.com/assets/5109848/18409863/1275420c-7770-11e6-95ca-d09bea0e2695.png)

**Comment by danielgindi** [comment]
It's actually `IAxisValueFormatter`. Pull the code from master and try the demo.

**Comment by anishparajuli555** [comment]
@danielgindi 
Hey i have been stuck in this for a long time and its urgent to solve..Can you help me in converting the code to fill Line graph.

 ```
set1 = [[LineChartDataSet alloc] initWithValues:yVals1 label:@"DataSet 1"];
        set1.axisDependency = AxisDependencyLeft;
        [set1 setColor:[UIColor colorWithRed:255/255.0 green:241/255.0 blue:46/255.0 alpha:1.0]];
        set1.drawCirclesEnabled = NO;
        set1.lineWidth = 2.0;
        set1.circleRadius = 3.0;
        set1.fillAlpha = 1.0;
        set1.drawFilledEnabled = YES;
        set1.fillColor = UIColor.whiteColor;
        set1.highlightColor = [UIColor colorWithRed:244/255.0 green:117/255.0 blue:117/255.0 alpha:1.0];
        set1.drawCircleHoleEnabled = NO;
        set1.fillFormatter = [ChartDefaultFillFormatter withBlock:^CGFloat(id<ILineChartDataSet>  _Nonnull dataSet, id<LineChartDataProvider>  _Nonnull dataProvider) {
            return _chartView.leftAxis.axisMinimum;
        }];
        
        set2 = [[LineChartDataSet alloc] initWithValues:yVals2 label:@"DataSet 2"];
        set2.axisDependency = AxisDependencyLeft;
        [set2 setColor:[UIColor colorWithRed:255/255.0 green:241/255.0 blue:46/255.0 alpha:1.0]];
        set2.drawCirclesEnabled = NO;
        set2.lineWidth = 2.0;
        set2.circleRadius = 3.0;
        set2.fillAlpha = 1.0;
        set2.drawFilledEnabled = YES;
        set2.fillColor = UIColor.whiteColor;
        set2.highlightColor = [UIColor colorWithRed:244/255.0 green:117/255.0 blue:117/255.0 alpha:1.0];
        set2.drawCircleHoleEnabled = NO;
        set2.fillFormatter = [ChartDefaultFillFormatter withBlock:^CGFloat(id<ILineChartDataSet>  _Nonnull dataSet, id<LineChartDataProvider>  _Nonnull dataProvider) {
            return _chartView.leftAxis.axisMaximum;
        }];

```

I am having problem in converting this code to swift 

  ```
  set2.fillFormatter = [ChartDefaultFillFormatter withBlock:^CGFloat(id<ILineChartDataSet>  _Nonnull dataSet, id<LineChartDataProvider>  _Nonnull dataProvider) {
            return _chartView.leftAxis.axisMaximum;
        }];

```

**Comment by anishparajuli555** [comment]
@danielgindi Is there a way i can set background color in x-Axis Values?
