### ISSUE TITLE
implement the same behavior as Android api

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/Charts#1418]
like android gesture of __LongPressed__ effect, I don't know the same implement in our side by swift.

please notice [this link](https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/listener/OnChartGestureListener.java#L33).
`void onChartLongPressed(MotionEvent me);`

thanks for your time.

regards :)

**Comment by petester42** [comment]
What is the behaviour of long pressing on the android version?

**Comment by L-Jovi** [comment]
the master branch as latest.

**Comment by petester42** [comment]
There is no long press right now. What does the android version do when you long press.

**Comment by L-Jovi** [comment]
@petester42  thanks for your reply,

I want to resolve conflict of gesture, now I put our smart chart inside [react-native-swiper](https://github.com/leecade/react-native-swiper) as one slide,

and I want to implement that when I __longPress__ at chart component, then sliding horizontally just trigger chart's behaviour while the whole slide tab don't be triggered.

**Comment by petester42** [comment]
You could possibly do this with the `UIGestureRecognizerDelegate` but I'm not really sure what you want to achieve. 

I'm also unsure what you want from us. You want ChartViews to have a `UILongPressGestureRecognizer`?

**Comment by L-Jovi** [comment]
thanks for your patience.

I think `UILongPressGestureRecognizer` is what I need as the same behaviour in Android side,
I want to display x axis and y axis value when user __ longPress__ on chart component and sliding horizontally,

but now if I do it, the gesture will be captured from `react-native-swiper` component, the whole slide tab will be changed.

**Comment by danielgindi** [comment]
You actually **should** use a `UILongPressGestureRecognizer`.
That's how it's done in iOS. In Android you need to subclass, so a special listener is provided. In iOS you control the whole gesture experience with ease.
