### ISSUE TITLE
How to create two bars one over another for Horizontal bar charts?

### ISSUE THREAD

**Issue by gleutar** [danielgindi/Charts#1423]
I would like to create something like this (image). [
<img width="587" alt="Horizontal bar chart" src="https://cloud.githubusercontent.com/assets/2440162/18386898/d218e654-7699-11e6-9061-e1c69cf02e1d.png">
](url)

I know how to create one bar (lets say only the blue one) but I want to show the "limit" that should have been accomplished (grey bar) behind every blue bar. Is there a way?

Thanks a lot! :)

P.s.: Feel free to edit the title of the issue to make it more understandable

**Comment by liuxuan30** [comment]
about the grey bars, you could try 'drawBarShadowEnabled` and `barShadowColor`.
However with your visual effect, seems you have to override some renderer methods to get what you want.
Another trick is creating two chart views and put them together. However I don't see it's a good one and not easy to maintain.
