### ISSUE TITLE
Best method to use this in Objective c project

### ISSUE THREAD

**Issue by gaganindersingh** [danielgindi/Charts#1425]
I have tried now every method to include Charts in my Objective-c Project.
- I used pods. It worked for iPhone5 simulator and when i tried to run on iPhone6s i have got errors.
-I used dragging the Charts project as well. No luck.
-Finally i tried to add the Classes only. worked for iPhone5 and error at @import Charts; for iPhone 6s simulator.

Can anyone please address this issue.

**Comment by danielgindi** [comment]
If you drag the code, there's no point in adding an `@import`.
If you're compiling for iOS 7, you **can't** use `@import`, and must drag the code.
You could drag the `xcodeproj` into your project, without dragging the code. And then using an `@import`, if you're compiling for iOS 8 or later.

There are many issues created (and closed) about this - please use the search option...
