### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by tomjmul** [danielgindi/Charts#1426]
Please think about providing some documentation rather than relying on another project in another language, written for a different platform. Lack of documentation is compounded by the fact that whilst the library is written in Swift, the demos are written in ObjC.

**Comment by danielgindi** [comment]
Demos are (partially) in ObjC to demonstrate working with Charts in ObjC. 
iOS works with both languages, and iOS programmers should be able to at least read it.

The samples could be written in Java for all I care. Syntax is just syntax. The logic and the function names to not change, as the library is Cross Platform.
It IS written in ObjC so you could run it - as they are demos. That's the point.

Documentation - we will not manage separate documentation repositories for Android and iOS for the same library. There's absolutely no reason for it.
And as the inline code documentation evolves, the documentation on Pods get also better so you can look there.

As long as you're looking for samples - look at the demos.

**Comment by liuxuan30** [comment]
Acutally I came across http://stackoverflow.com/documentation, seems interesting. We could explore if we could use it for documentation

**Comment by pbassut** [comment]
@danielgindi I disagree we should be reading documentation for a project implemented in another platform/language just to get the basics going. Which are different in many ways of getting a java library setup.

I mean, you say yourself in the README that the API is 95% the same as the android version. Those 5% will generate some headaches for sure.

There's not even a guide to get a basic chart working! I could read the docs for the API itself, that's okay. But what should I import? What methods should I implement? Is there a delegate? A dataSource? Is it a array-based datasource?

That's the first well-known open-source project I come across that does not have a documentation.

Keep up the awesome work!
