### ISSUE TITLE
How to write a limit for each bar in horizontal bar chart?

### ISSUE THREAD

**Issue by gleutar** [danielgindi/Charts#1429]
Is there a way to create limits for each bar in the horizontal bar chart so that the limit is not from top to bottom. 

![image](https://cloud.githubusercontent.com/assets/2440162/18430296/28539e34-78d8-11e6-93e4-268219bcb333.png)

For example, the limit line here is 10. I would like to show this line only for July (so that it starts below June and goes to August) and add other lines for the other months. Is there a way?

**Comment by liuxuan30** [comment]
override the methods or create you own ones. It's no magic. Take a look at how grid line calculate the postions so you know the two edge point.
