### ISSUE TITLE
PieChartDataEntry class not found - Swift/CocoaPods

### ISSUE THREAD

**Issue by sdnakhla** [danielgindi/Charts#1431]
Using Charts 2.2.5 via CocoaPods, I am unable to locate the PieChartDataEntry class.  I see DataEntry classes for all other chart types, and see the PieChartData and PieChartDataSet files as well.  However, I do not see the PieChartDataEntry file referenced in the demo project.

**Comment by petester42** [comment]
PieChartDataEntry is a Charts 3.0 feature. You will have to wait if you really need this class. You can still create a pie chart with a ChartDataEntry in 2.2.5
