### ISSUE TITLE
Cannot compile for targets below iPhone 5s

### ISSUE THREAD

**Issue by dkcas11** [danielgindi/Charts#1434]
Hi,

Trying to compile for any device below 5s (5, 4s) gives me the error for my LineChartView, saying "LineChartView is unavailable: cannot find Swift declaration for this class".

This is totally weird and doesn't make any sense.

Using Realm and imported Charts and ChartsRealm.
Haven't even put any data in the LineChartView yet..

Xcode 7.3.1

Thanks.

**Comment by petester42** [comment]
Hmm. Interesting maybe a missing architecture since iPhone 5s is when they switch to 64-bit.

**Comment by liuxuan30** [comment]
yes, check your arch
