### ISSUE TITLE
Graph cutting off from axisLine while setting axis min ,max Value

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1435]
I have few problems encountered while setting ChartLimitLine and  axis min ,max Value

I am using `ChartLimitLine` to enable gridline at certain locations..And is working as expected.But 
1) How do i send the ChartLimitLine To back of the view as to feel more like gridline?
2) I see my graph cutting off while setting the Left Axis Min,Max Value. But is working while none are set.Is there a way i can bring those graphs to front of the view?

![screen shot 2016-09-13 at 2 47 31 pm](https://cloud.githubusercontent.com/assets/7752578/18467999/c346862e-79c1-11e6-9533-a798a9e70a56.png)

Here we can clearly see the line graph and scatter graph cutting off with min max settings on.
![screen shot 2016-09-13 at 2 46 10 pm](https://cloud.githubusercontent.com/assets/7752578/18468016/d4c4d37e-79c1-11e6-9048-e9005f7dc05a.png)

**Comment by liuxuan30** [comment]
1. `drawLimitLinesBehindDataEnabled`
2. You set left axis max / min value to 94% and 67% and the line will be cut for sure.

**Comment by anishparajuli555** [comment]
@liuxuan30 I agree..but,I think it would be better if those cut off data come to the front of the view and see whole part not a portion?

**Comment by liuxuan30** [comment]
not sure what you mean. cut off data will not be seen at all, that's the purpose of setting axis min/max value.

**Comment by anishparajuli555** [comment]
i have set y-axis max and min in high charts too..And it shows well the points..Is there any fix for this?
![screen shot 2016-09-14 at 11 37 02 am](https://cloud.githubusercontent.com/assets/7752578/18501386/c3031b2e-7a6f-11e6-928a-e098b34b15df.png)
