### ISSUE TITLE
Error when running `pod lib lint` from another project

### ISSUE THREAD

**Issue by arifken** [danielgindi/Charts#1436]
I'm not sure yet if this is an issue for Charts or for CocoaPods, but just wanted to see if anyone here has run into this:

Essentially to recreate this, what you have to do is create a pod library that lists Charts as a dependency in its podspec

You then run `pod lib lint` for the pod project that uses Charts as a dependency, and you'll see the following error:

```
-> Installing Charts (2.2.5)
 > Git download
 > Git download
     $ /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/danielgindi/Charts.git /var/folders/ym/_8y3bx0d2mb3xs7gkljqk7j00000gq/T/d20160913-77485-12jkhmc --template= --single-branch
     --depth 1 --branch v2.2.5
     Cloning into '/var/folders/ym/_8y3bx0d2mb3xs7gkljqk7j00000gq/T/d20160913-77485-12jkhmc'...
     Note: checking out '276076f1180a0676e4766fe27bb3fa48864df8dc'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b <new-branch-name>

 > Running prepare command
   $ /bin/bash -c  set -e sed -i '' -e 's/import Charts//g' ChartsRealm/Classes/**/*.swift
   sed: ChartsRealm/Classes/**/*.swift: No such file or directory
```

It looks like prepare command is not running the `sed` command relative to the cloned project, but I tried to reproduce this with another pod dependency that used the same prepare_command and no dice.  Just wondering if anyone has seen this! thanks

**Comment by petester42** [comment]
No I have not. But then again I've never used charts as a dependency for another library. I'll check it out soon.

**Comment by arifken** [comment]
Thanks! in the meantime, i'll see if i can run it through my development CocoaPods and see if i can get some more info

**Comment by arifken** [comment]
I think this is a CocoaPods issue actually- started a discussion here: https://github.com/CocoaPods/CocoaPods/issues/5873 . So i'll close this one.

**Comment by petester42** [comment]
I saw that in the cocoapods issue you mentioned that you fixed the issue by using "FORK_XCODE_WRITING". How did you setup your podspec for it to work. I added a .env file but no dice. I am having trouble getting cocoapods to lint the Charts podspec.

Thanks!
