### ISSUE TITLE
conflict with scrollView

### ISSUE THREAD

**Issue by ScottishFold** [danielgindi/Charts#1438]
I put a barChartView in a scrollView,then I move up barChartView,the position of touchPoint to highlight the barChartView is not right,it's above the barChartView,is there any solution to solve this problem?Thank you.

**Comment by liuxuan30** [comment]
have no idea what are you saying.

**Comment by ScottishFold** [comment]
@liuxuan30   Here is the screenshot.Touch area A can highlight the value ,but touch area B can not.
I add this barChartView in a scrollView.Please give me some help.

**Comment by liuxuan30** [comment]
eh, to me if area A can work, area B should too. I need you to debug on your side. Like adding break point which view got the touch.

**Comment by danielgindi** [comment]
You should adjust `maxHighlightDistance` to your needs.
