### ISSUE TITLE
How To use Swift3.0 In Xcode8

### ISSUE THREAD

**Issue by GxiangExt** [danielgindi/Charts#1439]

**Comment by Punith1234** [comment]
same here.. please update to swift 3.0

**Comment by edutgn75** [comment]
the same problem... A lot of issues for swift 3.0. I have try to convert some code but it has a lot of incompatible instructions... It's strange because in the project file "Readme.md" we can see "* Xcode 7.3 / Swift 2.2 / 3.0"

**Comment by CaliosD** [comment]
OMG....I've already updated to Xcode 8 before reading this issue.....When could this be fine again, please? @_@

**Comment by petester42** [comment]
You can use the swift-3.0 branch until we finalize charts v3. If there have been changes with final Xcode 8 then let us know or a send us a pull request 😉

**Comment by CaliosD** [comment]
Thanks for your advice~! Since I used cocoapods, I finally found a temporary solution: in pod targets -> Charts -> Build Settings -> Use Legacy Swift Language Version -> Choose "No", and that's done ! Just save it here in case anyone else needs it. 😄
