### ISSUE TITLE
Xcode 8 and swift 3.0

### ISSUE THREAD

**Issue by dobybest** [danielgindi/Charts#1440]
Hello,

The new Xcode 8 is asking me to convert the project (Charts) to swift 3.0 , it's ok to go with conversion or you guys will do the conversion ?

Thanks

**Comment by stardustWK** [comment]
just get the code on swift 3 branch

**Comment by RajaveluC** [comment]
I took the code from swift 3 branch. I am still not able to compile my project in XCode 8. Any suggestions?

**Comment by danielgindi** [comment]
https://github.com/danielgindi/Charts/issues/1291
