### ISSUE TITLE
XCode 8: Crash in xAxis Renderer after upgrade

### ISSUE THREAD

**Issue by nicholassmith** [danielgindi/Charts#1441]
I just upgraded to XCode 8 and I'm finding there's a segfault on this line:
`let labelSize = widthText.sizeWithAttributes([NSFontAttributeName: xAxis.labelFont])`

Is this a known issue? Do I need to grab the code from repo instead of Carthage?

**Comment by ac1217** [comment]
can you run successfully on Xcode8 then dont need to do any configuration? when i run , it appear a lot of errors!

**Comment by nicholassmith** [comment]
I can now, I had to start from scratch with Carthage and when it had cloned I opened the Charts project and manually changed the Xcode errors and warnings. I then did Carthage build && Carthage archive. 

I'll put some better instructions up later.

**Comment by nicholassmith** [comment]
So using carthage:
- `carthage checkout Charts`
- Then you need to open the `Charts.xcodeproj` & `ChartsRealm.xcodeproj` in XCode, it'll ask if you want to convert to Swift syntax so select yes. I went for 2.3, I don't know if going for 3.0 makes any difference. This resolves a build settings issue for carthage.
- `carthage build --no-skip-current --platform iOS && carthage archive Charts`

Then just include it in your project as you would with any Carthage project. I had to update my code as I using the stable release version and master has some breaking API changes, YMMV.
