### ISSUE TITLE
ChartV3 autoScaleMinMaxEnabled not scaling candle charts correctly.

### ISSUE THREAD

**Issue by moon47usaco** [danielgindi/Charts#1442]
Version 3 from https://github.com/danielgindi/Charts/tree/Swift3.0-ChartV3.

When I have `combinedChartView.autoScaleMinMaxEnabled = true` in version 3 it does not appear to be taking into account the highs and lows of the candles.

It is also scaled really tight to where the absolute MinMax is right up against the views bounds. It should provide just a little padding as version 2 does.

Screens:

V2 correct scale:
![v2](https://cloud.githubusercontent.com/assets/15712871/18539129/f99b1c0c-7b3e-11e6-80d9-2afb732d1cbf.jpg)

V3 high and low extremes are cut off:
![v3](https://cloud.githubusercontent.com/assets/15712871/18539134/0d319520-7b3f-11e6-8adb-fa4b018faf9d.jpg)

V3 plot of high and low extremes of same data, MinMax of visible right against view, needs padding:
![v3zig](https://cloud.githubusercontent.com/assets/15712871/18539232/db4e1474-7b3f-11e6-8231-c54e475755fd.jpg)

**Comment by danielgindi** [comment]
The bug with candle charts has been fixed, but regarding extra spacing you can adjust that yourself through the several methods available (i.e. `spaceTop`/`spaceBottom`/`extraOffsets`)
