### ISSUE TITLE
Customize scatter chart color for each data in dataSets

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1443]
I want to set different color for each data in dataSet `set1`. Setting the color of dataSet as  `[set1 setColor:ChartColorTemplates.colorful[0]];`, sets every color to same.Is there a way to set each dataSet color to different and may be shapes too?
 
```
- (void)setDataCount:(int)count range:(double)range
{
    NSMutableArray *yVals1 = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < count; i++)
    {
        double val = (double) (arc4random_uniform(range)) + 3;
        [yVals1 addObject:[[ChartDataEntry alloc] initWithX:(double)i y:val]];
        
    }
    
    ScatterChartDataSet *set1 = [[ScatterChartDataSet alloc] initWithValues:yVals1 label:@"DS 1"];
    [set1 setScatterShape:ScatterShapeSquare];
    [set1 setColor:ChartColorTemplates.colorful[0]];
    set1.scatterShapeSize = 8.0;
    NSMutableArray *dataSets = [[NSMutableArray alloc] init];
    [dataSets addObject:set1];
    
    ScatterChartData *data = [[ScatterChartData alloc] initWithDataSets:dataSets];
    [data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:7.f]];
    
    _chartView.data = data;
}
```

**Comment by liuxuan30** [comment]
`dataSet.colors` can do the job I think.

**Comment by anishparajuli555** [comment]
@liuxuan30  I dont think i can set holeColors this way?

**Comment by liuxuan30** [comment]
hole colors? I don't see it. Anyway.. code is there, so if existing properties can't solve you problem, time to override :)

**Comment by anishparajuli555** [comment]
@liuxuan30 Yes scatterShapeHoleColor ...ahh....I have to override for every problems i face..

**Comment by liuxuan30** [comment]
basically, there are too many requirements to satisfy with just a few people. If you find something useful, you are more than welcome to file a PR following the code style :)
