### ISSUE TITLE
Graph clipping  while setting Y-axis min ,max Value

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1444]
I have set chart yaxis  max, min value and i see only half the scatter shape and line graph..How do i fix this? I need to show the shape without clipping.

Below is the screenshot of issue i am facing.
![screen shot 2016-09-15 at 11 52 27 am](https://cloud.githubusercontent.com/assets/7752578/18539963/f6a700a0-7b3a-11e6-9e77-1f4bb4056be3.png)

**Comment by liuxuan30** [comment]
well that's may be a tough one since you explicitly set axisMaxValue. All shapes are clipped outside contentRect.

**Comment by anishparajuli555** [comment]
@liuxuan30  is there any other way to provide y axis range without this clipping problem?

**Comment by danielgindi** [comment]
Adjust `spaceTop`/`spaceBottom` or `setExtraOffsets`
