### ISSUE TITLE
Compiling on New XCode 8

### ISSUE THREAD

**Issue by fustalol** [danielgindi/Charts#1445]
Hello.
I've added Charts on my Obj-C project, but now I cannot build It since XCode 8 because Charts is not swift 2.3-3.0 compilant. All the errors are inside Charts.
What can I do?

**Comment by RajaveluC** [comment]
People are still working on it. Support is coming soon.

https://github.com/danielgindi/Charts/issues/1291

**Comment by fustalol** [comment]
Thank you, we'll wait.
