### ISSUE TITLE
BarChart right/left bar cut in half

### ISSUE THREAD

**Issue by venux92** [danielgindi/Charts#1446]
Hi, I refer to this issue (closed) similar to my problem.
https://github.com/danielgindi/Charts/issues/323

In BarChart the first and last bar are cut in half.
Is there any solution regarding this ?

Thanks in advance
![screen shot 2016-09-15 at 6 06 51 pm](https://cloud.githubusercontent.com/assets/20675272/18543331/9d30d284-7b72-11e6-9c0d-16780e3a3bbe.png)

**Comment by aoverholtzer** [comment]
I ran into this too and just figured it out: `BarChartView` has a new property `fitBars` that defaults to false. Set it to true and your bars are not cut in half.

_However_, there’s a new problem, at least on my chart: the last bar is entirely missing. I think the problem is in `BarChartView.calcMinMax()`, which contains:

>         if fitBars
>         {
>             _xAxis.calculate(
>                 min: data.xMin - data.barWidth / 2.0,
>                 max: data.xMax - data.barWidth / 2.0)
>         }

I think the second (max) calculation should read `max: data.xMax + data.barWidth / 2.0 `.

**Comment by venux92** [comment]
I tried to set fitbars=true but like you I got the last bar missing.

To get the last bar in full, if I set the axisMaximum to +0.5 my max value I got it full but still got the first one "half" even if I set the axisMinimum to -0.5.

If anyone has a solution, thanks in advance.

**Comment by liuxuan30** [comment]
What version are you using? Please do try ChartsDemo first to make sure you don't have configuration issue.

**Comment by francoisduchemin** [comment]
I have the same problem. When I set `barChartView.fitBars = true` the labels are no longer correctly positioned...

With `barChartView.fitBars = false`:
![simulator screen shot 23 sep 2016 22 44 01](https://cloud.githubusercontent.com/assets/11538281/18800817/607a17ba-81df-11e6-9b53-f7ed74914a29.png)

With `barChartView.fitBars = true`:
![simulator screen shot 23 sep 2016 22 43 31](https://cloud.githubusercontent.com/assets/11538281/18800818/607a23ea-81df-11e6-9cb3-663f8fc23ade.png)

**Comment by liuxuan30** [comment]
@francoisduchemin try latest master. I don't see this issue in ChartsDemo

**Comment by sree127** [comment]
@venux92 @francoisduchemin I ran into the same issue even after setting `fitBars`. It seems setting`axisMaximum` was causing the issue. Removing that fixed the issue. 

With and without `axisMaximum` enabled respectively :

![Enabled](https://cloud.githubusercontent.com/assets/3157263/18915484/c82efccc-85ae-11e6-8d59-44caae0f73e9.png)
![After removing axisMaximum](https://cloud.githubusercontent.com/assets/3157263/18915485/c835c7a0-85ae-11e6-835d-7d5743103fb6.png)

**Comment by liuxuan30** [comment]
@sree127 you mean `xAxis.axisMaximum`? I am not sure if it's a bug right now. But taking a look at y axis, if you set axisMaximum, it will be cut by design?

**Comment by tuantmdev** [comment]
I ran into a same issue, i didn't customize `axisMaximum`, tried `fitbars = YES` but it's not work

![Imgur](http://i.imgur.com/sNLTBDt.png)

**Comment by francoisduchemin** [comment]
For me the issue was this line:
barChartView.xAxis.setLabelCount(12, force: true)

If I don't put this line, only 6 labels are displayed.
I have changed it to barChartView.xAxis.setLabelCount(12, force: false) and now it works fine :)

**Comment by venux92** [comment]
@sree127 You're right, I remove
xAxis.axisMinimum and xAxis.axisMaximum
I have fitBars=true, If I remove fitBars=true I got the first bar cut in half.
And everything is perfect now

![screen shot 2016-10-06 at 5 14 06 am](https://cloud.githubusercontent.com/assets/20675272/19125687/c3de1c18-8b83-11e6-82c3-6596f085a061.png)

**Comment by liuxuan30** [comment]
Looks like current `axisMaximum` has bug as #1603 not sure if it's the root cause. But seems you have solved i.t
