### ISSUE TITLE
Distinguish LineGraph callback.

### ISSUE THREAD

**Issue by anishparajuli555** [danielgindi/Charts#1448]
i have a `CombinedChartView` with multiple linegraphs and a scatter graph.

```
 let data: CombinedChartData = CombinedChartData(xVals: xAxisdateTimeArr)
 data.lineData = self.setLineData(foreCastData,highlightTime: highlightTime)
 data.scatterData = self.getScatterData(foreCastData,highlightTime: highlightTime)
 chartView.data = data
```

DataSource for line graph is as below

```
  func setLineData() ->LineChartData{
          ..........
        var dataSets : [LineChartDataSet] = [LineChartDataSet]()
        dataSets.append(set1)
        dataSets.append(set2)
        dataSets.append(set3)
        let data: LineChartData = LineChartData(xVals: xAxisdateTimeArr, dataSets: dataSets)
        return data
    }
```

I need to show a popup only when 1st line graph is selected.
But the delegate method is called for each line graph in chartView.
`   func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: ChartHighlight){} `

how do i distinguish the callback of a line graph?

**Comment by liuxuan30** [comment]
it tells you which entry and dataSetIndex and highlight, I think it's enough

**Comment by danielgindi** [comment]
It tells you exactly what you need for that, as @liuxuan30 said

**Comment by iArsalanshah** [comment]
i handled delegate using below condition
`if let data = chartView.data, data.isKind(of: PieChartData.self) { ... }`
