### ISSUE TITLE
Adding additional X index values without the initWithXVals

### ISSUE THREAD

**Issue by nicholassmith** [danielgindi/Charts#1451]
So to get my app working with XCode 8 & Charts I grabbed the source to get to the latest build and managed to get it working, however I need to add X Values that extended past the Y values (to show further into the past and future) so I used the initWithXVals with an array that allowed that to happen and plotted Y vals against that.

Is there anyway to do that with the latest changes?

**Comment by liuxuan30** [comment]
Which version? Chart 3.0 or 2.2.5? Not really understand your issue.

**Comment by mrsensen** [comment]
@liuxuan30 V3.0  This version does not have the xVal initialization method.How to add the xAxis label value?

**Comment by nicholassmith** [comment]
@liuxuan30 V3.0, latest commit to master basically. Previously I could initialise a set of X vals then plot a set of Y values with them which meant there could be more X values than Y values. This allowed me to build a graph showing time progression with the ability to show the current date and the distance to the last entry.

**Comment by danielgindi** [comment]
Just set the minimum/maximum value for the `chart.xAxis. You do not have to add entries.

**Comment by nicholassmith** [comment]
That worked perfectly, thanks @danielgindi!
