### ISSUE TITLE
iOS 10 and swift 3.0 issues

### ISSUE THREAD

**Issue by AlexyIbrahim** [danielgindi/Charts#1453]
Version 2.2.5 is not working with swift v3.0, tried to convert my code to swift 3.0 but the Charts library is still generating errors, any ideas ?

**Comment by trsneed** [comment]
Use swift 2.3 until 3.0 update is ready.

**Comment by parasdaff** [comment]
I upgraded to XCode 8 and updated my pods using Cocoapods, I got 138 build errors. Please find in the attachment.
![screen shot 2016-09-16 at 3 12 47 pm](https://cloud.githubusercontent.com/assets/20792433/18581920/5c2b67f0-7c20-11e6-80db-e0747443055f.png)

**Comment by AlexyIbrahim** [comment]
I managed to solve the issue temporarily, as @trsneed said use Swift 2.3 for the time being, while converting your project select Swift 2.3, it worked for me

**Comment by parasdaff** [comment]
thanks  @AlexyIbrahim, Hope this library will be updated soon for supporting swift 3.

**Comment by stephanecodo** [comment]
You need to download the correct branch of the project (top left, over the files, select Branch and then 'Swift 3.0').

**Comment by danniss10** [comment]
Use the correct branch in your podfile:

pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Swift-3.0'

**Comment by petester42** [comment]
see #1291
