### ISSUE TITLE
How to show ChartMarker in CombinedChart?

### ISSUE THREAD

**Issue by Shunshine07** [danielgindi/Charts#1454]
How to display marker in case of combined chart with different units. 

For example, I have combine chart, in line chart the speed is km/min, and in bar chart the speed is km/h. I want to display in marker 50 Km/h when the marker will display in bar chart and when marker display in line chart its should be 20 km/min. 

Also marker do not display correctly when right axis of Y is enable. It still takes left Y axis reference.

Also in case of Stacked Bar Chart, for different stacks it is showing the total upper value - That is sum of all stacks. But how to display it with different different stacks?

Anyone can help me ?

Thanks in advance.

**Comment by liuxuan30** [comment]
Which version you are using? Please take a look at how ChartMarker is used and implemented and you should know it.

**Comment by chandni-solanki07** [comment]
its latest 3.0.

**Comment by liuxuan30** [comment]
I suggest you migrate to Chart 3.0. Marker is redesigned.

**Comment by danielgindi** [comment]
Please note that you need to set the axisDependency of the dataset to match the right yAxis.
Also - you should migrate to Charts 3.0 :-)
