### ISSUE TITLE
[MC] System group container issue

### ISSUE THREAD

**Issue by danniss10** [danielgindi/Charts#1455]
Using the Swift 3 version of Charts, whenever I try display my chart, my app freezes and I get an error message like this:

2016-09-16 10:50:46.524560  [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2016-09-16 10:50:46.534088  [MC] Reading from public effective user settings.

Anyone have any ideas as to how to fix this?

**Comment by liuxuan30** [comment]
I don't see it's about Charts library. Try google

**Comment by stancho-dynoden** [comment]
did you find the problem because I have the same message, but my app is not crashing, very strange. I only upgraded my app to swift 2.3 for now

**Comment by populartheapp** [comment]
I am integrating Facebook Login in my app (FacebookSDKs-iOS-4.16.0)

When calling the faceBookLoginManger i am receiving this message/error in the console.

[MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
 
[MC] Reading from public effective user settings.

What does it mean and how can it be fixed?

**Comment by farshadtx** [comment]
This is a log from OS Level.
try this: http://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs/39461256#39461256

#StupidXcode #Apple
