### ISSUE TITLE
Please provide swift 2 version for this project

### ISSUE THREAD

**Issue by dipen0807** [danielgindi/Charts#1457]
It will be really great if I can get the swift 2 version somehow, please help. Any link where I can get it, will also be very helpful.

**Comment by simonbengtsson** [comment]
The [latest release](https://github.com/danielgindi/Charts/releases/tag/v2.2.5) 2.2.5 is for swift 2.2?

**Comment by petester42** [comment]
Yes it is. I'm working on a release for swift 2.3.

**Comment by liuxuan30** [comment]
@petester42 what do we need to do, just tag a release should be enough? Charts2.2.5-swift2.3 branch should be good to go

**Comment by petester42** [comment]
I want to convert the project structure to match the master so Carthage works for sure. I tried it today but got some weird xctest errors. I'll fix it tomorrow and then tag a release.

**Comment by liuxuan30** [comment]
ok, cool

**Comment by petester42** [comment]
closed by v2.3.0
