### ISSUE TITLE
Swift 3.0 and Realm

### ISSUE THREAD

**Issue by sochalewski** [danielgindi/Charts#1458]
First, love to see coming Charts support for Swift 3.0.
This day Realm 1.1.0 was released, so `Charts.podspec` needs to be updated, because of this:

```bash
[!] Unable to satisfy the following requirements:

- `RealmSwift` required by `Podfile`
- `RealmSwift (= 1.1.0)` required by `Podfile.lock`
- `RealmSwift (~> 1.0.2)` required by `Charts/Realm (2.2.5)`
```

`ss.dependency "RealmSwift", "~> 1.0.2"` should be changed to `1.1.0` or even `1.1` 👍

**Comment by petester42** [comment]
addressed in #1422
