### ISSUE TITLE
(v3.0)Demo: no such module realm 

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1460]
I have downloaded the latest version on master branch， I want to run the iOS demo on iOS10 (use Xcode8)，but I get an error: no such module realm，how can I fix this problem ?

**Comment by danielgindi** [comment]
Xcode 8?

**Comment by leejayID** [comment]
I also met the same problem

**Comment by Huang-Libo** [comment]
@danielgindi 
yes, Xcode 8, Production Release

**Comment by nhantrivinh** [comment]
Same problem

**Comment by liuxuan30** [comment]
according to https://github.com/danielgindi/Charts/pull/1422, to run ChartsDemo, `anything realm based will need a carthage bootstrap. everything else should work as before`

**Comment by shenyufei** [comment]
So is there any way I can now use it 3.0? For example, pull a branch?
 Because I am a novice, you can not write, 
for example, (github "danielgindi / Charts" ~> 2.2.5, swift 3.0), 
 how to write in pods, I can use charts in swift3.0

**Comment by Huang-Libo** [comment]
@shenyufei 
v3.0 with swift hasn't been released, so there do not have v3.0 in pod. Anyway, you can force pod to download Charts' master branch like this:
`pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Swift3.0-ChartV3'`
However, it just has many issue with this, so the best way to use v3.0 is just to clone the repository to your mac and then drag Charts.xcodeproj to your project.

**Comment by liuxuan30** [comment]
if you need Realm, you need to run 'carthage bootstrap'

**Comment by danielgindi** [comment]
The README states that you should "Run carthage checkout in the project folder, to fetch dependencies (i.e Realm).".

You do not have to do that if you don't need Realm.
