### ISSUE TITLE
ios10 the charts can not display!

### ISSUE THREAD

**Issue by HuangXiaoxing** [danielgindi/Charts#1461]
when i run the app in ios 10,but the charts can not dispaly in the view.otherwise, on ios 9,it can be looked at

**Comment by Huang-Libo** [comment]
@HuangXiaoxing
I run my app with charts's swift-3 branch on iOS10 + Xcode8, seems no problem

**Comment by HuangXiaoxing** [comment]
charts's swift-2.3 OK too?

**Comment by HuangXiaoxing** [comment]
@Huang-Libo

**Comment by Huang-Libo** [comment]
@HuangXiaoxing 
I haven't ever used swift-2.3 branch.

**Comment by HuangXiaoxing** [comment]
@Huang-Libo 
I have got the promble，thank you

**Comment by danielgindi** [comment]
Have you tried with `master`?

**Comment by liuxuan30** [comment]
guys, when you say 'not display' you should include all details. There is nothing dark magic between Xcode 7 and 8. If you can build and run, it should work

**Comment by githubkiven** [comment]
@HuangXiaoxing     How do you solve?
