### ISSUE TITLE
 After the upgrade iOS10  Charts-iOS  Change the case

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#1463]
Charts-iOS will not be code signed because its settings don't specify a development team.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.   What should I do？thank you。

**Comment by nicholassmith** [comment]
Are you installing via Carthage?

**Comment by Huang-Libo** [comment]
+1

**Comment by githubkiven** [comment]
Don't use Carthage

**Comment by githubkiven** [comment]
@nicholassmith

**Comment by githubkiven** [comment]
When I open ChartsDemo，choose Swift version   ，I should choose which？A：Convert to Swift 3 
B:Convert to Swift 2.3    C:Convert Later

**Comment by githubkiven** [comment]
In the system of iOS10 Why are there many wrong？

**Comment by lkk2016** [comment]
asd

**Comment by githubkiven** [comment]
No such module 'Realm.Dynamic'

**Comment by danielgindi** [comment]
Take the code from `master` branch - it is already converted to Swift 3.0 (but for Charts 3.0 beta)
