### ISSUE TITLE
macOS demo bar chart's first and last bar got half cut

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1468]
on master branch, macOS demo bar chart's first and last bar got half cut. Another post https://github.com/danielgindi/Charts/issues/1446 mentioned similar, however it's about `fitBars=true`. OS X demo disabled fitBar still face same issue. 
Will look into if free or someone can catch.

![macosbug](https://cloud.githubusercontent.com/assets/4375169/18620643/35be5048-7e49-11e6-882e-d2df0accca5d.png)

**Comment by danielgindi** [comment]
@PhilJay I'm guessing that a bar at x=0.0, will get cut on the left as there's a bar width that gets from  -0.5 to 0.5 right?

**Comment by PhilJay** [comment]
Yes, exactly. The `fitBars(true)` method should fix that. :-)

**Comment by danielgindi** [comment]
There was a bug with `fitBars` implementation here, fixed :-)

**Comment by liuxuan30** [comment]
@danielgindi I did check fitBars are turned off and having the issue. Do you mean we should turn on fitBars?
