### ISSUE TITLE
balloon marker

### ISSUE THREAD

**Issue by yoonyoungji** [danielgindi/Charts#1469]
I draw multibar graph. Thank you!!
I want to make customized chart. so I want to know how to use balloon marker. 
I search relation to balloon marker issues, and many people talk about preferring to chart-demo 
I use all of chart classes, product.... so I use ballonmarker In swift but your chart-demo use ballon marker in object-c
please tell me what can i do...

**Comment by liuxuan30** [comment]
read the code and write a swift one should not be hard for you
