### ISSUE TITLE
v2.2.5 not support swift2.3

### ISSUE THREAD

**Issue by woohyuknrg** [danielgindi/Charts#1470]
Use Xcode8 & swift2.3, add pod 'Charts', '2.2.5', then pod update, after updated pod, compile project, there are 13 same error: Value of optional type 'xxx?' not unwrapped; did you mean to use '!' or '?'?
Please fix, tks.

**Comment by Huang-Libo** [comment]
@woohyuknrg 
You can use swift-2.3 branch instead of cocoaPods

**Comment by githubkiven** [comment]
@Huang-Libo In Podfile how should I do?

target “abc” do

platform:ios,'8.0'

pod 'Charts/Realm'
use_frameworks!

end

**Comment by githubkiven** [comment]
@Huang-Libo I should add anything else?

**Comment by Huang-Libo** [comment]
@githubkiven 
It depends on your cocoaPods' version.

**Comment by aljux** [comment]
@githubkiven 
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Swift-2.3'

**Comment by shenyufei** [comment]
@aljux  
Hello, I use your suggestion.
But it is error,`warning: Could not find remote branch Swift-2.3 to clone. fatal: Remote branch Swift-2.3 not found in upstream origin`
What should i do? I'm a novice, please detail~thank you~

**Comment by petester42** [comment]
I will hopefully have a charts 2.3 release out tonight or tomorrow. Everything seems to work locally. Thanks for the patience.

**Comment by shenyufei** [comment]
I mean to use in Xcode 8  swift 2.3, can I use the old version to let him run it?
 Such as Charts version 2.2? I've only pod 'Charts', does not add a suffix。 like ` ~> '2.20'`
I have asked other third party, gave me an answer, is this  `pod 'SnapKit', '~> 0.22.0'` .

**Comment by liuxuan30** [comment]
why don't you search swift 2.3 as keywords? there is already branch for 2.2.5 + 2.3

**Comment by shenyufei** [comment]
Here is not it? This is the search results, so I am here to ask questions.
I did as recommended, but it  is error of result.

**Comment by liuxuan30** [comment]
apparently not enough: https://github.com/danielgindi/Charts/issues/1291:
>What branch to use?
Swift 3.0 + Charts 3.0 -> Master // this is recommended to pick :)
Swift 2.3 + Charts 2.2.5 -> Chart2.2.5-Swift2.3 branch
Swift 3.0 + Charts 2.2.5 -> Chart2.2.5-Swift3.0 branch
Swift 2.3 + Charts 3.0 feature ready -> Chart3.0-Swift2.3 branch

**Comment by shenyufei** [comment]
Nice, 
But I do not understand the branch, I use cocoa pods, should be how to write?
 I've seen this, but I do not know how to use Pods, so I came here to ask questions. 
I would have said I don't understand.  Thank you~

**Comment by petester42** [comment]
Im almost done creating a release for swift 2.3 with charts 2.2.5 so hang on tight. There were some complications with cocoapods and xcode 8/realm

**Comment by githubkiven** [comment]
@Huang-Libo Pod should be that version？cocoapods-1.0.1？

**Comment by petester42** [comment]
I had to use 1.1.0.rc.2 to publish the v2.3.0 pod
