### ISSUE TITLE
How to set the  LineChart disconnect style, I add NAN to Entry, isInBoundsRight function is crashed.

### ISSUE THREAD

**Issue by mekhi** [danielgindi/Charts#1471]
Hi,I want to show the LineChart disconnect style like this.

![qq20160919-1](https://cloud.githubusercontent.com/assets/8685295/18621632/ee776f84-7e58-11e6-8a43-11e33d00bfd9.png)

In  MPAndroidChart, set Entry(float.NAN, i) can be done, but in Charts, I also set "(CGFloat)NAN", it crashed.
```objc
[yVals addObject:[[ChartDataEntry alloc] initWithValue:(double)NAN xIndex:i]];
```
![qq20160919-0](https://cloud.githubusercontent.com/assets/8685295/18621656/3f5056b4-7e59-11e6-88c7-7ae40ce08d3a.png)

Thanks in advance:)

**Comment by Huang-Libo** [comment]
@mekhi 
v3.0 seems support break line mode.@liuxuan30

**Comment by liuxuan30** [comment]
@danielgindi did v3.0 add this? I don't remember.
However, if you use multiple data sets, it can be solved, though a little complicated composing the data sets.

I do implemented line breaking feature in my previous compnay, however, I don't find a time to port it.

**Comment by mekhi** [comment]
@liuxuan30 I solved the problem temporarily,set the line which near to point color is **clearColor**. According to "*NAN value*" to determine which lines we should hide(clearColor).

I think this is not a good solution, only can temporarily solve the problem, if Charts implemented line breaking feature, That'd be great. :)

**Comment by liuxuan30** [comment]
clear color will do the trick but highlight will expose it. Consider one line segment per data set

**Comment by danielgindi** [comment]
Charts do not support this currently.
You need to add another dataset to your data `Data` object.

**Comment by Huang-Libo** [comment]
@danielgindi Have you considered to support **line-break with one dataSet** feature？

**Comment by liuxuan30** [comment]
Well, it has been asked last year. Seems not a lot of people asking, and multiple data sets seem did the trick, so not a high priority

**Comment by hfahmy** [comment]
This is needed
