### ISSUE TITLE
Some missing methods in swift 3 version

### ISSUE THREAD

**Issue by StefanNestorov** [danielgindi/Charts#1472]
Hi, i tried to upgrade my project with the latest version of charts (swift 3.0 from the main branch) but some methods and properties are missing like:
 xValCount, lowestVisibleXIndex, highestVisibleXIndex, data.xVals.count, on ChartViewBase i think;  xAxis.setLabelsToSkip() on xAxys and some others.
Do you plan to update this things soon ?

**Comment by danielgindi** [comment]
Charts 3.0 is a breaking change, as there are structural changes. There are not x values anymore.
I will release some notes on how to upgrade.

**Comment by StefanNestorov** [comment]
Ok, do you plan to update the older version of the library to swift 3 ?

**Comment by danielgindi** [comment]
@StefanNestorov It's too much work, I cannot look back that far :-)

**Comment by StefanNestorov** [comment]
Thank you for answering, just one more important question for me - in my app values in the xAxys are not linear for example ...1 2 3 4 1 2 3 4 1 2 3 4 ... and in some places i have actual entry with xIndex and y value. With the old version i achieved this, but will this be still possible in the new version ? Because as i understand you dont supply x values anymore ?

**Comment by liuxuan30** [comment]
the old version with swift 3 is in Swift 3.0 branch.

**Comment by Huang-Libo** [comment]
@StefanNestorov Maybe formatter can handle this problem?
