### ISSUE TITLE
Compiled with older version of Swift language (2.0) 

### ISSUE THREAD

**Issue by hilalbaig** [danielgindi/Charts#1473]
Build/Products/Debug-iphonesimulator/Charts/Charts.framework/Charts compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64

**using: Swift 2.3 + Charts 2.2.5 -> Chart2.2.5-Swift2.3 branch**

**Comment by danielgindi** [comment]
Do a Clean & Build

**Comment by hilalbaig** [comment]
Thanks for the quick responce. I did but not working.
Now i switched to master. Its working. Thanks

**Comment by shenyufei** [comment]
@hilalbaig 
hello, I'm a novice, I have same problem
I use cocoa pods, what should i do。please detail
such as , pod 'SnapKit', '~> 0.22.0'.
Others give me a suggestion, `pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Swift-2.3'`
But is error,  `warning: Could not find remote branch Swift-2.3 to clone.
fatal: Remote branch Swift-2.3 not found in upstream origin`

**Comment by patrickferreira** [comment]
Also having this issue. Any ideas?

**Comment by petester42** [comment]
'Swift 2.3' is not a valid branch. The proper charts versions is 2.3 for swift 2.3 support. For cocoapods use as follows: `pod 'Charts', '~> 2.3'`

**Comment by patrickferreira** [comment]
I managed to figure it out.
Had just updated to Charts 3.0, but XCode was giving me a hard time.

Had to delete derived data from my XCode project, as explained here:
http://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8
