### ISSUE TITLE
How to show xAxis All value and Rotate Label?

### ISSUE THREAD

**Issue by paneaktae** [danielgindi/Charts#1475]
How to do it? Thank you.

**Comment by Huang-Libo** [comment]
@paneaktae  
Seams impossible..
Just imagine that there are many label on xAxis, how can every label be showed?
For Rotate label,  maybe you need to Render chart by yourself.

**Comment by danielgindi** [comment]
There no one deterministic way to make sure all labels always show. You can always run out of space.
Make your own considerations - as you know how the user might use your app, what zoom levels you are supporting, how long are the labels, how wide is the space between grid lines etc.

You may find that a certain rotation for the labels is well suited for you and looks good on your chart design, and that above a certain zoom level you want to show less labels. You have a few properties that can help with that. Please look at the demos.

**Comment by paneaktae** [comment]
@danielgindi  @Huang-Libo  I can tried xAxis setLabelsToSkip(0) this work to showed all X value.
