### ISSUE TITLE
[LineChart] How to Darw "NSString" on xAxis? without Realm.io

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#1477]
In the "Charts" old version, I use This API to draw xAxis : ` ChartDataEntry *entry = [[ChartDataEntry alloc] initWithValue:val xIndex:i];`

but, in the new Version, It disappeared!    I mean,This  API
I only find This API 
`ChartDataEntry *entry = [[ChartDataEntry alloc] initWithX:11.01 y:35];`
Two parameters are of type **double** !

I try to use Realm.io 
But  my project loaded in first time, the boss demanded that without the data, the data is added gradually.
Then the Xcode error: Nan
That's to say: when using Realm must be initialized data, this way doesn't work for me

How should I handle? Thank you!

**Comment by Huang-Libo** [comment]
+1 
I have the same problem.
My xAxis shows date before, now all have been changed to double value...

**Comment by danielgindi** [comment]
Duplicate:
https://github.com/danielgindi/Charts/issues/1481

Also please look at the demos, or the migration notes

**Comment by dadigua2333** [comment]
@danielgindi 
Thanks for your reply,I also noticed the "formatter"
My demand is that the X axis display 12:02 12:04 12:06.
When I load data like this,Please note that X decimal
 `    ChartDataEntry *entry = [[ChartDataEntry alloc] initWithX:11.01 y:35];
         ChartDataEntry *entry1 = [[ChartDataEntry alloc] initWithX:12.01 y:40];
     ChartDataEntry *entry2 = [[ChartDataEntry alloc] initWithX:13.08 y:40];`
It's Nothing on the x axis!

But when  I remove the decimal, It's ok!
