### ISSUE TITLE
stringForValue value argument

### ISSUE THREAD

**Issue by seyfeddin** [danielgindi/Charts#1478]
I wrote my own formatter and mapped every value with a month string. But every time my overridden stringForValue:axis: method is called, value of value argument is incremented by 0.7, not 1.0.

Am I doing something wrong?
```
0.000000
0.700000
1.400000
2.100000
2.800000
3.500000
-0.700000
0.000000
0.700000
1.400000
2.100000
2.800000
3.500000
4.200000
0.000000
0.700000
1.400000
2.100000
2.800000

```

**Comment by Huang-Libo** [comment]
@seyfeddin 
If you are using v3.0, you need to see this issue by Daniel 
https://github.com/danielgindi/Charts/issues/1474


If you are using formatters:
- Replace any chart.valueFormatter = formatter with chart.valueFormatter = ChartDefaultValueFormatter(formatter: formatter) or chart.valueFormatter = [[ChartDefaultValueValueFormatter alloc] initWithFormatter:formatter];
- Replace any axis.valueFormatter = formatter with axis.valueFormatter = ChartDefaultAxisValueFormatter(formatter: formatter) or axis.valueFormatter = [[ChartDefaultAxisValueValueFormatter alloc] initWithFormatter:formatter];

**Comment by danielgindi** [comment]
Steps on the axis to render are not limited to just 1.0. The user can zoom in or out, and can show different granularity of the grid.
You can limit that by adjusting the `granularity` property. Look at the demos :-)
