### ISSUE TITLE
LineChart. Labels for Y axis and Double format

### ISSUE THREAD

**Issue by bizibizi** [danielgindi/Charts#1479]
I created Y axis with array of Double.
So, sometimes I have values on Y axis  with 1 decimal number sometimes with 2 decimal numbers. Can I set its format?

And the second question. Can I add some extra label to it values?
I have percentages. 10, 20, 30... Can I add '%' sign after the value? Like 10%, 20% for Y axis

**Comment by Huang-Libo** [comment]
@bizibizi 
If your are using v3.0, you need to read this issue:https://github.com/danielgindi/Charts/issues/1474
else you can use system's format API

**Comment by bizibizi** [comment]
no, I am using 2.x

**Comment by bizibizi** [comment]
I am trying that:

        let numberFormatter = NSNumberFormatter()
        numberFormatter.numberStyle = NSNumberFormatterStyle.DecimalStyle
        numberFormatter.positiveSuffix = "%"
        numberFormatter.negativeSuffix = "%"
        numberFormatter.maximumFractionDigits = 1
        numberFormatter.minimumFractionDigits = 1
        chartView.leftAxis.valueFormatter? = numberFormatter


But I do not see any affect.

**Comment by bizibizi** [comment]
Tried to set it before / after/ in the middle. But it is not works
