### ISSUE TITLE
(v3.0 LineChart) xAxis with String/double label issue

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1481]
My xAxis shows date string before, with v2.x; today I update Charts to v3.0, I find that I can only  show double value instead, then I set x's  values to 1.0, 2.0, 3.0...but the values showed on xAxis are .8, 1.6, 2.4, 3.2......
![2016-09-20 12 08 46](https://cloud.githubusercontent.com/assets/12227130/18639496/b65deaec-7ec6-11e6-8f09-59d0f59eef83.png)

**Comment by nhantrivinh** [comment]
would like to know how to set string in the x axis as well

**Comment by danielgindi** [comment]
You just need to use a formatter.
A double can represent any value. If you want to represent a date, you can get the `NSTimeInterval` of a date. `NSTimeInterval` is actually a `double`.

Please look at the time chart demo!
