### ISSUE TITLE
(v3.0-Swift3.0)crash because of image not found

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1487]
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/90F539AA-0361-4745-824D-38B3DE77F379/KNAdministratorBeta.app/Frameworks/Charts.framework/Charts
  Reason: image not found
(lldb) 

Project can build successfully, but crash when launching.
(Enterprise release)

**Comment by Huang-Libo** [comment]
<img width="762" alt="2016-09-20 11 03 41" src="https://cloud.githubusercontent.com/assets/12227130/18656382/4abe4572-7f23-11e6-8266-646a7410e4b9.png">

**Comment by SarjuHansaliya** [comment]
This helped me.
Plus If someone come across this issue please also check in "Link Binary in Library".

![screen shot 2016-09-24 at 4 22 01 pm](https://cloud.githubusercontent.com/assets/6604146/18807989/3098c3fe-8273-11e6-9d74-e934b105f85a.png)
