### ISSUE TITLE
(v3.0 + swift3.0) charts' top are cropped/overlapped in ChartsDemo

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#1489]
![img_3294](https://cloud.githubusercontent.com/assets/12227130/18658948/c1083df8-7f39-11e6-8caf-37bf3540134f.JPG)
![img_3295](https://cloud.githubusercontent.com/assets/12227130/18658949/c1347a80-7f39-11e6-8aa1-7efe8c98cac1.JPG)

**Comment by liuxuan30** [comment]
do you set axisMaxValue?

**Comment by danielgindi** [comment]
Thanks :-) That pointed me in the direction of a calculation bug for the spacing percentage
