### ISSUE TITLE
[BUG] LineChart--- about "LineChartModeCubicBezier"

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#1490]
When I chose this pattern:
`    LineChartDataSet *data1 = [[LineChartDataSet alloc] initWithValues:xVals];
    data1.mode = LineChartModeCubicBezier;`

If I had four points,Between the third and fourth lines will disappear.
Also not completely disappear, for instance, the distance between them is 10 cm, but only draw the curve of 2 cm. Transparency is not related to alpha.

but   LineChartModeLinear   is ok!

**Comment by liuxuan30** [comment]
a screenshot will help exlain what are you saying.

**Comment by liuxuan30** [comment]
you could also try horizontalBezier mode.
