### ISSUE TITLE
Why the coordinate points and the X axis the above data is not aligned?

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#1492]
I want **"point C** "and **"X_value C"** on the same vertical line, but now **"point C"** and **"unknowValue"** are on the same line.
 In this picture below,as you see , I just added 4 points to chart.I want them to align one by one.

![666](https://cloud.githubusercontent.com/assets/12544035/18944007/7e5fbdb4-8655-11e6-8e3c-4433837cadb6.jpg)

My second question is:

I want the X axis to always show the point I set.But when I zoom in on the Chart scale.
As shown below.
The data on the X axis is not my addition.
How to clear them?

![2222](https://cloud.githubusercontent.com/assets/12544035/18734340/2a9b6d54-80a6-11e6-9e74-84ea58762e3b.png)

**Comment by danielgindi** [comment]
I honestly don't understand your questions

**Comment by Huang-Libo** [comment]
@danielgindi 
Forgive his English is not good...Maybe I can do some translation for you.
He @dadigua2333  may means :
1. The time on xAxis is not what he has set in `initWithX:y:` function.The answer: the value on xAxis has been rounded in `AxisRendererBase.swift`.You can learn more in https://github.com/danielgindi/Charts/issues/1503.
2. There many label with same value(eg: 12:05) on xAxis. The answer: user `granularity` to handle this problem.

**Comment by dadigua2333** [comment]
@Huang-Libo 
谢谢你的翻译~ 我的英文实在是不太好.用百度翻译 写上来的.

@danielgindi 
I will immediately edit my question. Thanks for your reading.

**Comment by danielgindi** [comment]
We need a code example to understand what's going on. Labels show the string that you return from the formatter. You can see a working demo in the Time Line Chart .
It is possible that you've set `centerAxisLabelsEnabled` to `true`, which is meant for centering below bars etc.

**Comment by liuxuan30** [comment]
I think he wants to say that the `point c`'s x value is some value other than `12:16`, it wants the x axis to show point c's x value.
