### ISSUE TITLE
Give id for node

### ISSUE THREAD

**Issue by sudhir9026** [danielgindi/Charts#1493]
Hello 
I want give to id for every node in line chart when click on node then call chartValueSelected function. in this function want got id of node.

now i am using BarChartDataEntry *newEntry = [[BarChartDataEntry alloc]initWithValue:[dict[@"medsTaken"] floatValue] xIndex:i]; in loop 

so how to do this.

thanks

**Comment by danielgindi** [comment]
That's what the `data` argument is for!

**Comment by sudhir9026** [comment]
for (int i = 0; i < [myArray count]; i++)
    {
        NSDictionary *dict = sortedArray[i];        
       BarChartDataEntry *newEntry = [[BarChartDataEntry alloc]initWithValue:[dict[@"value"] floatValue] xIndex:i];
// I have dict[@"id"] also that i want to keep in data And use when select this node
        [yAxisValues addObject:newEntry];
    }

LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithYVals:yAxisValues label:@""];
// Set all Properties
// after that
NSMutableArray *dataSets = [[NSMutableArray alloc] init];
    [dataSets addObject:set1]; 
    LineChartData *data = [[LineChartData alloc] initWithXVals:xAxisValues dataSets:dataSets];
