### ISSUE TITLE
How do I set the value of the x-axis after update ?

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1496]
###  the screenshot 

<img width="605" alt="2016-09-20 6 11 28" src="https://cloud.githubusercontent.com/assets/8415820/18666306/b6e5c2ae-7f5d-11e6-8f31-b97d27205bfb.png">

**Comment by MonkeyRing** [comment]
xcode 8    Chart2.2.5-Swift3.0

**Comment by Huang-Libo** [comment]
@MonkeyRing  https://github.com/danielgindi/Charts/issues/1474

**Comment by liuxuan30** [comment]
well you should use Chart 3.0. Chart 2.2.5 will EOL soon. Also, just refresh your chart data x values.

**Comment by MonkeyRing** [comment]
@liuxuan30   ok ,thx .  Charts 3.0 release yet?

**Comment by liuxuan30** [comment]
no it's in master

**Comment by MonkeyRing** [comment]
ok . thx

**Comment by MonkeyRing** [comment]
@liuxuan30     

i  still can't found this  after i changed master 

<img width="978" alt="2016-09-21 9 47 06" src="https://cloud.githubusercontent.com/assets/8415820/18694911/942d28be-7fe0-11e6-8d0f-c1ffa35370ee.png">

<img width="955" alt="2016-09-21 9 46 47" src="https://cloud.githubusercontent.com/assets/8415820/18694942/d2e0a252-7fe0-11e6-8ee6-935ffac222fb.png">

**Comment by liuxuan30** [comment]
Chart 3.0 has changed a lot. Use latest API

**Comment by MonkeyRing** [comment]
ok  :) 👍 @liuxuan30

**Comment by rs10693** [comment]
Hello @MonkeyRing ,

Are you set xValue in any graph.?

**Comment by MonkeyRing** [comment]
Not yet , I just want to set the x-axis of a chart of the X-coordinate data.   
As I always shot as the usage before the update to 3.0.
But after the update to 3.0, you can not find the property of the xValus. 
In 3.0v,  i had already knew about how to set the x-axis, and the use of IAxisValueFormatter.  :)

**Comment by rs10693** [comment]
@MonkeyRing  So can you please explain me i have create 1 array for store all xvalue and then after fetching using for loop but in bar chart and line chart pass double value so i can't converted in to string. like,

    for (int i = 0; i < yAxisArray.count; i++)//individual bar value
    {
        double yVal = [[yAxisArray objectAtIndex:i] doubleValue];
        double xVal = [[xVals objectAtIndex:i] doubleValue];
        
        NSLog(@"%f", xVal);
        
        [yVals1 addObject:[[BarChartDataEntry alloc] initWithX:xVal y:yVal]];
    }

**Comment by MonkeyRing** [comment]
you should set xvals like this 
```
Class ChartViewController : UIViewController, IAxisValueFormatter //step1
  {
     var xVals = [String]()  // step2,   Declare a global variable array for time
      override func viewDidLoad() {
         super.viewDidLoad()
         setupChartStyle()    // step 3
       }
    
       func setupChartStyle() {
          combinedChartView.chartDescription?.text = ""
          combinedChartView.noDataText = "加载中..."
          combinedChartView...
          combinedChartView.xAxis.valueFormatter = self   // Important statement, don't forgot this st.
        }
    
       func setChartData() {
            for i in 0..<data.count {
                xVals.append("Time string formatted")    // In this step, you can format time strings.
            }
       }
}
```
####Formatter Xvals Implementation && IAxisValueFormatter Method
```
// return xVals value  
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return xVals[Int(value) % xVals.count]
    }
// OR
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return xVals[Int(value)]
    }
```
 ####  After taking time to string array to achieve x-axis formatting method and return

**Comment by rs10693** [comment]
can you describe in objective-c. @MonkeyRing bcoz i found **IAxisValueFormatter** this class in swift. so how to use in obj-c i don't knw.

**Comment by MonkeyRing** [comment]
@rs10693   see the ChartsDemo .  the ChartsDemo is described in objective-c

**Comment by MonkeyRing** [comment]
@rs10693   
![1](https://cloud.githubusercontent.com/assets/8415820/18830283/a9833830-8412-11e6-9370-95fac2ce80e5.png)

![snip20160926_6](https://cloud.githubusercontent.com/assets/8415820/18830315/c5db3118-8412-11e6-9484-03fb88defbf1.png)
![snip20160926_7](https://cloud.githubusercontent.com/assets/8415820/18830324/d44bd2e8-8412-11e6-9b8d-8488e955c3f2.png)


you can see the ChartsDemo . there are the simpleCode

**Comment by rs10693** [comment]
Hello @MonkeyRing 

Thanks for help but now 1 problem m facing so please help me.

i given a Screen shot and see, in that all barchart are combine. 
![chart](https://cloud.githubusercontent.com/assets/16097116/18860431/02d77f08-849b-11e6-9215-7fed67d4e2a3.jpg)

**Comment by liuxuan30** [comment]
@rs10693 Please refer to ChartsDemo first. Seems you don't setup chart data properly.

**Comment by rs10693** [comment]
Hello @liuxuan30 @MonkeyRing

Thank you very much to both of you. now it's perfect.

**Comment by oscams** [comment]
perfect solution!
