### ISSUE TITLE
when click node call chartValueSelected funtion

### ISSUE THREAD

**Issue by sudhir9026** [danielgindi/Charts#1499]
I want When i click on node than call chartValueSelected in LineChart but at this time I click anywhere inside the chart this function calling even i am clicking on line than also call.

**Comment by Huang-Libo** [comment]
@sudhir9026 You mean that you need chart to be highlighted **olny** when the node is tapped?

**Comment by sudhir9026** [comment]
yes

**Comment by Huang-Libo** [comment]
@sudhir9026 
This demand seems strange, because a node is not that easy to be tapped, it's a very small dot. Maybe Charts do not have this mode, I guess.

**Comment by sudhir9026** [comment]
but this is very confusing. my requirement is when click on node  then open to detail of this node.

**Comment by Huang-Libo** [comment]
@sudhir9026 
Charts will highlight the nearest node where you tapped,

**Comment by liuxuan30** [comment]
as @Huang-Libo said, it will find the nearest value to highlight. You could do something in delegate to ignore the highlight you don't need.

**Comment by RajAggrawal0507** [comment]
I have a candle chart and having the same problem. Whenever I click anywhere in the chart, nearest candle selected.
