### ISSUE TITLE
noDataText overflows

### ISSUE THREAD

**Issue by EdwinOtten** [danielgindi/Charts#1500]
### Issue ###
The noDataText and noDataTextDescription of the ChartViewBase are centered. When these strings are too long to fit on one line the text simply runs off-screen, as shown in the screenshot below:

<img src="https://cloud.githubusercontent.com/assets/5310778/18667592/884564a8-7f31-11e6-993b-05c460730c7c.png" width="318">

### Cause ###
The issue is caused by the method used to render the noDataText. In ```/Charts/ChartViewBase.swift``` around line 316 and 328 you can see that ```ChartUtils.drawText()``` is being used, which does not support multiline.

### Suggested fix ###
I suggest using ```ChartUtils.drawMultilineText()``` to be able to handle long texts. I already got this working on my fork and will create a pull request referencing this issue. Below you can see an example of this fix:

<img src="https://cloud.githubusercontent.com/assets/5310778/18667598/8c72e276-7f31-11e6-836d-a4589df2950f.png" width="318">

**Comment by EdwinOtten** [comment]
It appears that drawMultilineText is already being used in the newer 3.0 preview, since I'm using 2.2.5 (latest tagged release), I committed a fix for that version.

**Comment by danielgindi** [comment]
Please try to migrate to Charts 3.0 :-)

**Comment by EdwinOtten** [comment]
For sure! I'm just holding of until the official 3.0 release.

Well.. at least if someone needs the fix specifically on 2.2.5 they can
find it here ;-)

Op di 20 sep. 2016 15:45 schreef Daniel Cohen Gindi <
notifications@github.com>:
