### ISSUE TITLE
Cannot invoke initializer for type 'LineChartData'

### ISSUE THREAD

**Issue by dhamukrish** [danielgindi/Charts#1502]
I am getting below error when try to use in Swift 3. Please advise.

`Cannot invoke initializer for type 'LineChartData' with an argument list of type '(xVals: [Double], dataSet: LineChartDataSet)'`

The below code working perfectly fine in Swift 2.x

```
  private func setChart(lineChartView: LineChartView, dataPoints: [Double], values: [Double]) {
    
    var dataEntries: [ChartDataEntry] = []
    
    for i in 0..<dataPoints.count {
      let dataEntry = ChartDataEntry(value: values[i], xIndex: i)
      dataEntries.append(dataEntry)
    }
    
    let lineChartDataSet = LineChartDataSet(yVals: dataEntries, label: "Altitude")
    let lineChartData = LineChartData(xVals: dataPoints, dataSet: lineChartDataSet)
    
    lineChartDataSet.setColor(UIColor.blueColor())
//    lineChartDataSet.drawCubicEnabled = true
    lineChartDataSet.mode = .CubicBezier
    lineChartDataSet.drawCirclesEnabled = false
    lineChartDataSet.lineWidth = 1.0
    lineChartDataSet.circleRadius = 5.0
    lineChartDataSet.highlightColor = UIColor.redColor()
    lineChartDataSet.drawHorizontalHighlightIndicatorEnabled = true
    
    lineChartView.data = lineChartData
  }
```

**Comment by julyb** [comment]
Did you find any solution to this? I am having the same problem!

**Comment by liuxuan30** [comment]
try master, or Chart2.2.5-Swift3.0 branch. It seems fixed if I remember correctly.

**Comment by dhamukrish** [comment]
I am facing the issue from branch "Chart2.2.5-Swift3.0". I have rebuilt the whole project after downloaded again from this branch. Please advise.

**Comment by liuxuan30** [comment]
try https://github.com/danielgindi/Charts/tree/v2.3.0

**Comment by petester42** [comment]
The API for that has changed in 3.0

**Comment by dhamukrish** [comment]
I need your help on this. 
Are you referring Swift 3.0? If so, where can I get the documentation or example?

**Comment by danielgindi** [comment]
Please make a *little* effort... Read the README, look at the issues...
For example, this one: https://github.com/danielgindi/Charts/issues/1474

**Comment by dhamukrish** [comment]
All good now with Swift 3 And Chart 3.0. Below is working code snippets.

```
  fileprivate func setChart(_ lineChartView: LineChartView, dataPoints: [Double], values: [Double]) {
    
    var dataEntries: [ChartDataEntry] = []
    
    for i in 0..<dataPoints.count {
      let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
      dataEntries.append(dataEntry)
    }
    
    let lineChartDataSet = LineChartDataSet(values: dataEntries, label: "Altitude")
    lineChartDataSet.setColor(UIColor.blue)
//    lineChartDataSet.drawCubicEnabled = true
    lineChartDataSet.mode = .cubicBezier
    lineChartDataSet.drawCirclesEnabled = false
    lineChartDataSet.lineWidth = 1.0
    lineChartDataSet.circleRadius = 5.0
    lineChartDataSet.highlightColor = UIColor.red
    lineChartDataSet.drawHorizontalHighlightIndicatorEnabled = true
    
    var dataSets = [IChartDataSet]()
    dataSets.append(lineChartDataSet)
    
    let lineChartData = LineChartData(dataSets: dataSets)

    lineChartView.data = lineChartData
  }
```

Thanks for your help.

**Comment by reformer** [comment]
@dhamukrish @danielgindi , its ok if the values of graphs in double (includes x-axis, y-axis and data values. But now i have x axis values in string of array contains months name. Then how to deal with it? Resolved solution and i got other tutorials  also given example of all double values. ChartDataEntry accepting 3 parameter double, double and anyobject parameter but 3rd one i seen useless to me.  In previous version we write   `  let lineChartData = LineChartData(xVals: dataPoints, dataSet: lineChartDataSet)` this line, in this line i supply xVals is in string also. Now this method is    `let lineChartData = LineChartData(dataSets: dataSets)` .  In my code i supply 2 array,    `  let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
                let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0]` Using both array how i draw the graph. Please at least document how to pass values for basic graph drawing.

**Comment by Pulkit2017** [comment]
Not working
