### ISSUE TITLE
Issue with BarDataEntry Method

### ISSUE THREAD

**Issue by astrike30** [danielgindi/Charts#1504]
I was going through [this](https://www.appcoda.com/ios-charts-api-tutorial/) tutorial for the (fabulous) Charts framework. In there example code they use this method: 
`let dataEntry = BarChartDataEntry(values: values[i], xIndex: i)`  

In this for loop: 
`for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(values: values[i], xIndex: i)
            dataEntries.append(dataEntry)
        }`

However I get this error in Xcode `Argument labels '(values: values[i], xIndex: i)' do not match any available overloads`. I'm not sure if the method was deprecated somewhere along the line and I could really use any help.

Thanks in advance for any help and for the terrific framework!

**Comment by danielgindi** [comment]
The tutorial is for Charts 2.*, while the current code on `master` branch is Charts 3.0.
Charts 3.0 is in beta, coming closer to a release everyday (We're just finishing up with the last important bugs).

You're can contact the tutorial makers and ask them to update it for Charts 3.0.
I know there are more than a few tutorials out there, and hoping that they will be updated!
