### ISSUE TITLE
Bar chart "floats" above x-axis when axisMinValue set to 0

### ISSUE THREAD

**Issue by narciero** [danielgindi/Charts#1506]
I am using branch 2.2.5-Swift3.0 in Xcode 8...everything worked fine in v2.2.5 (swift 2.2) however once i migrated to swift 3 i get this odd behavior - nothing in the chart has changed. I simply changed `alwaysStartAtZero` to `rightAxis.axisMinValue = 0`

<img width="374" alt="screen shot 2016-09-20 at 9 38 52 pm" src="https://cloud.githubusercontent.com/assets/9964211/18694753/b18d460c-7f7a-11e6-9f6e-a5dccda31de0.png">

**Comment by danielgindi** [comment]
Do you have `leftAxis` enabled as well? If so, either disable it, or set a matching `axisMinValue`

**Comment by narciero** [comment]
I have leftAxis.enabled set to false. I will post all the values I have set

**Comment by liuxuan30** [comment]
did you set `axisDependency` to right ?

**Comment by narciero** [comment]
@liuxuan30 that did the trick, thanks!
