### ISSUE TITLE
Info.plist Utility Error

### ISSUE THREAD

**Issue by lc418998951** [danielgindi/Charts#1507]
error: could not read data from '/Users/dszy/Desktop/111/dszy-project/Charts/Source/Supporting Files/Info.plist': The file “Info.plist” couldn’t be opened because there is no such file.

**Comment by lc418998951** [comment]
Xcode upgrade to 8.0 drag charts to the project

**Comment by petester42** [comment]
We need more details to help you. If you checkout the master branch you will see 2 demos (macOS and iOS) which both use the "drag to project" setup. Just look at what is done there and you should be able to figure it out.

**Comment by Huang-Libo** [comment]
@lc418998951  Maybe you dray a incorrect folder，you need to check `Charts/Source/Supporting Files/Info.plist` is exist.

**Comment by lc418998951** [comment]
No such module Realm

**Comment by petester42** [comment]
You need to use carthage if you want to support realm. It's simple as running `carthage bootstrap` to get everything setup.

**Comment by petester42** [comment]
The only thing you need to add to your project is the Charts.xcodeproj. Download the source code from here, copy it to your project's folder, open your xcode project, drag Charts.xcodeproj to your project. If you need realm you will have to run `carthage bootstrap` in the Charts folder.

**Comment by lc418998951** [comment]
My version is old, I now update to xcode8, however I just off the Charts. Xcodeproj cover previous Charts xcodeproj. Thus the first wrong, download files, drag the replacement of all documents except the demo, error Realm.I need the pods import Realm?

**Comment by petester42** [comment]
Please look at how the demo projects include the Charts framework. If you need realm carthage is required. I have given enough details to fix your issue. You will have to do some searching to find out why your setup does not work.

**Comment by danielgindi** [comment]
Do not drag any folder, and do not drag source files. Only drag the `Charts.xcodeproj` to your project.
