### ISSUE TITLE
Fatal error while loading Bar Chart

### ISSUE THREAD

**Issue by codyfazio** [danielgindi/Charts#1511]
My app keeps crashing with the error " **_fatal error: Double value cannot be converted to Int because it is either infinite or NaN."_**  The crash happens in the return line of the function below, found in ChartUtils.  It's for a bar chart if it makes any difference! Any thoughts?

 internal class func decimals(_ number: Double) -> Int
    {
        if number == 0.0
        {
            return 0
        }
        
        let i = roundToNextSignificant(number: Double(number))
        return Int(ceil(-log10(i))) + 2
    }

**Comment by danielgindi** [comment]
Did you add a NaN value?

**Comment by codyfazio** [comment]
No, but actually the number returned from roundToNextSignificant() is.

**Comment by oliviabrown9** [comment]
The exact same issue is happening for me, running the latest version including the "Safeguard for nan/inf"
