### ISSUE TITLE
Xcode 8.0,many errors......

### ISSUE THREAD

**Issue by longdw** [danielgindi/Charts#1513]
When I convert my project to swift3.0,it appears many errors that I can't slove them.Help......

**Comment by summerness** [comment]
same problem

**Comment by nicolla1003** [comment]
When will be official Swift 3.0 support with pods?

**Comment by rs10693** [comment]
Ya you are right so many error on Classes files. i am not using pod

**Comment by Huang-Libo** [comment]
@nicolla1003 Advice you don't use pod now, just clone the version you need and drag it to your project.

**Comment by rs10693** [comment]
ya i am doing this. @Huang-Libo

**Comment by rs10693** [comment]
G
![screen shot 2016-09-21 at 5 52 17 pm](https://cloud.githubusercontent.com/assets/16097116/18710734/57155e76-8024-11e6-9bb8-7a2e3ef99273.png)
![screen shot 2016-09-21 at 5 53 17 pm](https://cloud.githubusercontent.com/assets/16097116/18710735/57182818-8024-11e6-8608-d6cf8493cfa2.png)

etting all error in "CGContextSetLineDash" and solve to any other error. so please help me so we can request to pull with swift-3.

**Comment by petester42** [comment]
Use master. It is swift 3.0 already.

**Comment by rs10693** [comment]
yes i am using master.

**Comment by petester42** [comment]
Well if are then you are not using it because the Charts-iOS target doesn't even exist in master it's just Charts.

**Comment by rs10693** [comment]
What should i do to resolve this issue.? I am trying from last 5 hour. @petester42

**Comment by petester42** [comment]
Delete anything charts related in your project and charts itself. Download charts from master again and try to add it again. You can check the charts demo project which integrate charts properly.

**Comment by rs10693** [comment]
In bridging file getting  **Module 'Charts' not found** 

I am importing like @import Charts;

**Comment by rs10693** [comment]
Solved all error but can you say 1 thing, How to set data in to line chart  and bar chart.

before swift-3 we use 
LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];

but right now this method doesn't work.

**Comment by Huang-Libo** [comment]
@rs10693 for v3.0：
```
[[LineChartData alloc] initWithDataSets:lineChartDataSetArr]
```

**Comment by rs10693** [comment]
ya you are right @Huang-Libo but i want to set X value of graph right now set by default value like 0, 2, 4 so on.

**Comment by Huang-Libo** [comment]
@rs10693 
x value is set in `[[ChartDataEntry alloc] initWithX: y: `function, and you can use a formatter to format it.

**Comment by rs10693** [comment]
Ok i'll try thank you very much for your support. and one more question any update for BalloonMarker class. @Huang-Libo

**Comment by Huang-Libo** [comment]
@rs10693 May you can see Migrating to Charts 3.0 in this issue https://github.com/danielgindi/Charts/issues/1474

**Comment by rs10693** [comment]
Sure. @Huang-Libo

**Comment by rs10693** [comment]
Hi,

I am trying to set date in [[ChartDataEntry alloc] initWithX: y: but in lib you are passing double value so only display  single digit and i want to display like **09-25, 09-24** so on. plz help me. @Huang-Libo

**Comment by Huang-Libo** [comment]
@rs10693  You can find a example about how to format xAxis's value in `Time Line Chart` Demo.

**Comment by rs10693** [comment]
Hello @Huang-Libo 

I am create a array and in that m stored all date which i received from back-end so can you elaborate to how to convert **string to double** because of that class is instancetype_nonnull.

**Comment by rs10693** [comment]
Hello @Huang-Libo 

I am trying like this,

xVals = ["26-09","25-09","24-09"];
 for (int i = 0; i < yAxisArray.count; i++)//individual bar value
    {
        double yVal = [[yAxisArray objectAtIndex:i] doubleValue];
        double xVal = [[xVals objectAtIndex:i] doubleValue];
        [yVals1 addObject:[[BarChartDataEntry alloc] initWithX:xVal y:yVal]];
        
    }

so i want to display String in xAxis and now i am using **granularity** so xAxis are not display. pls help me it's very urgent.

**Comment by liuxuan30** [comment]
@rs10693 could you exlain under what situation xAxis not display? Have you zoomed in?

**Comment by Huang-Libo** [comment]
@rs10693
Use NSTimeInterval to store your xAxis' value,
```
@property(readonly) NSTimeInterval timeIntervalSince1970;
```
It's the interval between the date object and 00:00:00 UTC on 1 January 1970.

**Comment by rs10693** [comment]
Hello @Huang-Libo 

Thank you very much. now it's perfect.

**Comment by rs10693** [comment]
Hello @liuxuan30 
Refer #1496 and then you facing any problem then told me.
