### ISSUE TITLE
Setting x-values of BarChartView in Chart 2.2.6

### ISSUE THREAD

**Issue by hilalbaig** [danielgindi/Charts#1514]
Previously i used to pass an custom array of **x values** like this 
`_barChartView.data.xVals = xValsArray;`  to **BarChartView**. But upgrading to **Chart 2.2.6**, i am unabale to find its alternative, Can you please help.

**Comment by hilalbaig** [comment]
Sorted out :) You have to set it along y, more convenient!

`        [yVals1 addObject:[[ChartDataEntry alloc] initWithX:xVal y:val1]];
`

**Comment by hilalbaig** [comment]
Brothers, How can i set array of Strings on BarChartView x-axis.

**Comment by danielgindi** [comment]
There's no "2.2.6". There's 3.0. 
Read [this](https://github.com/danielgindi/Charts/issues/1474) carefully.
