### ISSUE TITLE
Charts.framework iOS

### ISSUE THREAD

**Issue by mristau** [danielgindi/Charts#1515]
There is no IOS Framework anymore, can i just add that MacOS one, or do i have to wait until this is fixed, i cloned the Swift 3.0 version as i migrated my app to swift 3 already

Or did i do something wrong

**Comment by Huang-Libo** [comment]
@mristau You can use the default framework, or change it in Build Setting-BaseSDK.

**Comment by danielgindi** [comment]
Just drag `Charts.xcodeproj` to your project. Then under "Embedded Frameworks" tap the "+" button, and select Charts framework

**Comment by mristau** [comment]
Thanks, it worked perfectly, was just unsure because before it had own target for iOS and MacOS each
