### ISSUE TITLE
I can't run this demo!

### ISSUE THREAD

**Issue by longdw** [danielgindi/Charts#1516]
1. Well,I have downloaded the master code,but  I can't run the ChartsDemo.When I build this project,it appears errors such as can't find Realm.

2.Looking at following codes,

```
NSMutableArray *xVals = [[NSMutableArray alloc] init];
    for (int i = 0; i < 12; i++)
    {
        [xVals addObject:[NSString stringWithFormat:@"%d月", (i + 1)]];
    }
    
    NSMutableArray *yVals1 = [[NSMutableArray alloc] init];
    NSMutableArray *yVals2 = [[NSMutableArray alloc] init];
    
    int i = 0;
    for (ChartContractCellViewModel *cellVc in array) {
        
        [yVals1 addObject:[[BarChartDataEntry alloc] initWithValue:cellVc.thisData xIndex:i]];
        [yVals2 addObject:[[BarChartDataEntry alloc] initWithValue:cellVc.lastData xIndex:i]];
        
        i++;
    }
```
Another question is that BarChartDataEntry's method has been changed in the new version,and I can't set object like initWithValue:object,can set double only.

**Comment by longdw** [comment]
I solved the first question when I delete all of Relam codes.Please help me to solve the second.

**Comment by petester42** [comment]
If you carefully read the ReadMe it says you have to run `carthage checkout` for realm to work

**Comment by liuxuan30** [comment]
@petester42 guess we have to put this notice as larger as we can people don't read README, don't search old issues.. just ask where something breaks :)

**Comment by petester42** [comment]
Ya... I could add a prebuild script that checks you have run carthage and if you havent it will run the command for you. Or maybe use carthage to checkout submodules but I dont like that.
