### ISSUE TITLE
Re: Fatal error while loading Bar Chart #1511

### ISSUE THREAD

**Issue by codyfazio** [danielgindi/Charts#1517]
I'm sorry, it looks like the problem persists.  I actually tried adding the new check in before I posted last time, but was still having issues. My number seems to be fine, but the value returned from roundToNextSignificant() is Inf, which is causing the crash. Should another check be performed after the value comes back? 

 internal class func roundToNextSignificant(number: Double) -> Double
    {
        if number.isInfinite || number.isNaN || number == 0
        {
            return number
        }
        
        let d = ceil(log10(number < 0.0 ? -number : number))
        let pw = 1 - Int(d)
        let magnitude = pow(Double(10.0), Double(pw))
        let shifted = round(number * magnitude)
        return shifted / magnitude
    }
    
    internal class func decimals(_ number: Double) -> Int
    {
        if number.isInfinite || number.isNaN || number == 0
        {
            return 0
        }
        
        let i = roundToNextSignificant(number: Double(number))
        return Int(ceil(-log10(i))) + 2
    }

**Comment by danielgindi** [comment]
Why didn't you just re-open the issue?...

**Comment by danielgindi** [comment]
What exactly is your setup? As we do not see any reason for an Infinite value to get in there

**Comment by danielgindi** [comment]
Please do some debugging. There are safeguard in place, like checking for `labelCount == 0` etc. Shouldn't happen.

**Comment by codyfazio** [comment]
Sorry, this is my first time posting an issue. I didn't realize I could reopen one.  I've been trying to figure this out for 3 days, because I assumed it was something on my end. I thought maybe if I reached out, you might have some insight. I've been using the framework for months, and it's only until the change to Swift 3 that it started crashing.

**Comment by codyfazio** [comment]
I figured it out. During the migration my chartDataSet was cast as IChartDataSet. Removing the cast fixed the issue. Thanks for your help and sorry to bother.
