### ISSUE TITLE
ChartUtils methods are marked internal and cannot be use to create custom charts 

### ISSUE THREAD

**Issue by mpiannucci** [danielgindi/Charts#1518]
For example, the `ChartUtils.getPosition` method is very useful when creating a custom `Renderer` but it may not be used unless I develop my work in the actual Charts git repo instead of just in my own project.

Please consider opening up these utilities for use in subclasses.  

These functions are also marked public in the Android version so it would help with consistency as well.

**Comment by mpiannucci** [comment]
Actually even more than that, there are a lot of random methods marked internal that make subclassing existing chart types really difficult. (EG the `initialize` function in `PieRadarChartViewBase`)

**Comment by danielgindi** [comment]
Why not call the `super` constructor?
Many internal methods are in fact internal. Some internal methods are meant to be "protected", not for public use by the user by available to subclasses - but Apple decided that `protected` is not useful enough to be in Swift.
Anyway - there was already an issue about that - https://github.com/danielgindi/Charts/issues/357

If there are methods that you think are legitimate to become `public`, raise them here for discussion and make a PR later
