### ISSUE TITLE
Charts classes not found in swift class in my Objc Xcode project

### ISSUE THREAD

**Issue by indieshack** [danielgindi/Charts#1519]
I have an older Objective C Xcode project that has more recent classes added as Swift classes (per Apple's recommendation). I followed the instructions to drag the Charts Xcode project file to my project. The "import charts" directive doesn't raise an error, but when I try to instantiate one of the Charts classes (e.g. BarChartView) I get an error on compilation: "BarChartView is unavailable: cannot find Swift declaration for this class". 

I'm not a newby, I've been programming ObjC for years and more recently Swift. Any ideas what I could be doing wrong? Also, is adding the realms framework mandatory to getting Charts to compile - I don't need to use realms.

Thanks

**Comment by liuxuan30** [comment]
To run ChartsDemo, ChartsRealm is needed. I would suggest you try ChartsDemo first, it's objc project demo.

**Comment by indieshack** [comment]
I did - demo project runs fine - I need to add Charts to an existing project

**Comment by petester42** [comment]
You have to add charts to the embed binaries section of your project. Please read the ReadMe, it details this very well.

**Comment by indieshack** [comment]
Just an FYI in case someone else has this issue, it's actually a real problem to use Charts in an Objective C project which uses Swift classes. I'm using Xcode 8, compiling for iOS10 and the instructions given really do NOT work. This project needs to be refactored to created static/and or dynamic libs. It's a shame really.

**Comment by petester42** [comment]
It really shouldn't be. The demo project is an objective-c project with swift classes. You cannot refactor Charts to a different lib type. Swift only supports dynamic frameworks which Charts is.
