### ISSUE TITLE
Line chart with preview

### ISSUE THREAD

**Issue by maxz044679** [danielgindi/Charts#1520]
how to create chart like this. give me some example please.......... Thank you.
![3](https://cloud.githubusercontent.com/assets/6409183/18735247/a9cf4e24-80a6-11e6-886e-90aff0ad63a3.png)

**Comment by Huang-Libo** [comment]
@maxz044679 You can use two line chart that are associated, maybe the difficulty is to get the range you selected at the bottom.

**Comment by maxz044679** [comment]
I had try, but i don't know how to get viewport or position of first chart and input to second chart (Sorry,I'm not good at English)
