### ISSUE TITLE
how to show the Chart without data?

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#1522]
My app is used to measuring temperature, initialization, there is no data. Data every two minutes to add one point.
In the old version of the Chart, I set data is nil, can show Chart with leftAxis and xAxis.
But the new version, error:
![333333](https://cloud.githubusercontent.com/assets/12544035/18735426/5b639d58-80b0-11e6-8f90-ba0c691913f6.png)

how to deal?

**Comment by danielgindi** [comment]
This one has been dealt with already, in the latest commits. When did you last pull?

**Comment by dadigua2333** [comment]
I use Xcode 7.3.1 to build. i got you .thanks

**Comment by danielgindi** [comment]
👍
