### ISSUE TITLE
The latest version can not run

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1523]
![479c0fd4-e57e-45c7-91b3-01964d82eb8f](https://cloud.githubusercontent.com/assets/20593532/18735531/0a503d62-80b1-11e6-810e-c0276123c10b.png)

**Comment by petester42** [comment]
you need to run `carthage checkout` for realm as mentioned in the readme.

**Comment by yushan023** [comment]
I wouldn't use Carthage, is there any other way?

**Comment by petester42** [comment]
no
