### ISSUE TITLE
Bar charts X-Axis labels repeating if the number of bars reduce

### ISSUE THREAD

**Issue by aftabahmed1286** [danielgindi/Charts#1524]
Hi @danielgindi ,

I see 2 issues on my end
![danielgindi](https://cloud.githubusercontent.com/assets/15074638/18735624/e18a7c76-809c-11e6-9fc3-69bde581dd2d.png)
. The issues are as follows:

1. In Demo Charts I have tried to reduce the number of bars, I see the XAxis labels are repeating more than once for a bar. I need it just one for a single bar.
2. The XAxis label needs to be aligned exactly to the centre of the respective bar. Here it is one sided to the left. 

Please help resolve these.

Thanks in advance!

**Comment by Huang-Libo** [comment]
@aftabahmed1286 
This is a old demo, you may try latest beta version (v3.0) with Swift3.0

**Comment by danielgindi** [comment]
They may be repeating if there's no other value to show there... As you didn't provide a formatter that says "January and a 1/2", you might want to use `granularity` to say what's the smallest value you want to for the axis intervals.
