### ISSUE TITLE
Method doesn't override any method from its superclass

### ISSUE THREAD

**Issue by ompagi** [danielgindi/Charts#1526]
![screen shot 2016-09-22 at 10 41 39 am](https://cloud.githubusercontent.com/assets/21188799/18736504/d726a61e-80b1-11e6-89ca-27482bc90cda.png)

I have some issue with the function i commented. If i uncomment it, it comes up with the doesn't override issue.
Tried to delete the override keyword and it comes up with .../Pods/Charts/Source/Charts/Utils/ChartPlatform.swift:111:21: Method 'touchesCancelled(_:withEvent:)' with Objective-C selector 'touchesCancelled:withEvent:' conflicts with method 'touchesCancelled(_:withEvent:)' from superclass 'UIResponder' with the same Objective-C selector

**Comment by danielgindi** [comment]
Compiling for macOS?

**Comment by ompagi** [comment]
@danielgindi Compiling for Iphone IOS

**Comment by vaibhav-varshaaweblabs** [comment]
I'm having the same issue

**Comment by K24LFY** [comment]
I'm having the same issue  compiling for Iphone IOS

**Comment by danielgindi** [comment]
What version of Xcode are you using?

**Comment by K24LFY** [comment]
Xcode 7.3.1 and Xcode 8.0 both try

**Comment by K24LFY** [comment]
@danielgindi Xcode 7.3.1 and Xcode 8.0 both try

**Comment by danielgindi** [comment]
You should compile Charts 3.0 only on the latest Xcode 8.0 (**not beta!**)

**Comment by ompagi** [comment]
@danielgindi What's the version for Xcode 7.3 and Swift 2.2

**Comment by K24LFY** [comment]
@danielgindi Chart 2.3.0 has same issue

**Comment by K24LFY** [comment]
@danielgindi Charts 2.3.0 has same issue

**Comment by liuxuan30** [comment]
@ompagi Chart 2.2.5 with release tags.

**Comment by liuxuan30** [comment]
@K24LFY what methods are reporting this? From what I worked on the migration, it looks like you are using wrong code base so you see such issues.

**Comment by petester42** [comment]
It looks like you are using cocoapods from the screenshot. So I tested it. I tried all combinations of swift/objective-c project and they all work when using the most recent release (2.3.0). Charts 3.0 is not release so if you have integration problems then you will have to wait until 3.0 is released or always use the most recent code from master.

**Comment by ankitkapasi** [comment]
I am having this same problem.

Xcode 8
pod 'Charts', git: 'https://github.com/danielgindi/Charts.git', branch: 'Chart2.2.5-Swift2.3'

```
		public final override func touchesCancelled(touches: Set<NSUITouch>, withEvent event: NSUIEvent?)
        {
			self.nsuiTouchesCancelled(touches, withEvent: event)
		}
```

_Build Error: Method does not override any method from its superclass._ 

If I remove the **override**, then it says _Overriding declaration requires an 'override' keyword_

**Comment by petester42** [comment]
Ya i'm gonna delete stale branches those are not up to date. You should be using `pod 'Charts', '~> 2.3'` for swift 2.3

**Comment by ankitkapasi** [comment]
@petester42 thanks. Will do.

**Comment by boonerite** [comment]
Hi,
I have tried the methods above, on Xcode 8, using Swift 2.3, updated pod as 2.3 also but still gets this:
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Not too sure where I am missing
My own codes has been converted to 2.3 using Xcode, but I did not pick Charts frame work in the prompt (for auto convert)

![image](https://cloud.githubusercontent.com/assets/20061336/19256575/cb4cbe6c-8f9a-11e6-8b6c-2f7dca6819ab.png)
![image](https://cloud.githubusercontent.com/assets/20061336/19256589/e87c47dc-8f9a-11e6-9a0a-a218c460d409.png)

**Comment by petester42** [comment]
Try using version 1.1.0 of cocoapods for better Xcode 8 support. 1.0.0 has issues with Xcode 8

**Comment by zhouzichao0709** [comment]
Same issue here. Xcode 7.3.1 Swift 2.2, pod 2.3.0

**Comment by andrey-16** [comment]
Faced the same issue in one old project written in Swift 2.3 and compiled by XCode 7.3.1.

The issue is that "touchesCancelled" overrides method of UIResponder class:
public func touchesCancelled(touches: Set<UITouch>?, withEvent event: UIEvent?)

And mistakenly (or not) has the "touches" parameter not as optional as required by the function declaration of UIResponder.
Correcting the "touches: Set<UITouch>" to "touches: Set<UITouch>?" helps to resolve the issue. Though I'm not sure if it can introduce other incompatibility issues with earlier versions of CocoaTouch. I'm not sure when exactly Apple changed the declaration of touchesCancelled.

**Comment by DanH-SyncInteractive** [comment]
Try changing:
`public final override func touchesCancelled(touches: Set<NSUITouch>, withEvent event: NSUIEvent?)`

to

`public final override func touchesCancelled(touches: Set<NSUITouch>?, withEvent event: NSUIEvent?)`
