### ISSUE TITLE
Multiple bar is not working

### ISSUE THREAD

**Issue by Shunshine07** [danielgindi/Charts#1529]
hi,

I have integrated Charts 2.3.0 using pods. My problem is Multiple bar is not working properly.
Though I am passing array of datasets. But it is showing me Bar chart instead of Multyple Bar.

I am using swift 2.3 and Xcode  8.
Is it updated version in Cooca Pods?

A quick help can be appreciated.

Thanks.

**Comment by petester42** [comment]
Yes 2.3.0 has been released on cocoapods. 

Can you check the demo to see if multiple bars works there. I believe there is an example of it there. 

If it is really broken I'll mark this as a bug so we can address it.

**Comment by chandni-solanki07** [comment]
In demo, the Multiple Bar is working. But when I have gone through the code, I found that charts library code is different in cocoa version 2.3.0 and the demo that they have provided.

So they have updated the version but I think there might be something missing that also need to be updated. Not sure about it.

**Comment by danielgindi** [comment]
The `master` branch contains the pre-release Charts 3.0.
