### ISSUE TITLE
Error in ChartsPlatform.swift

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [danielgindi/Charts#1533]
There's an error in ChartsPlatform.swift file on line number 111

`public final override func touchesCancelled(touches: Set<NSUITouch>, withEvent event: NSUIEvent?)`

**Comment by akashkumar3001** [comment]
what was your solution i am having this problem?

**Comment by vaibhav-varshaaweblabs** [comment]
Comment the funvtion

**Comment by petester42** [comment]
The real solution is use the proper version of charts. Which right now is 2.3

**Comment by innac-hyuna** [comment]
I has used pod 'Charts', '~> 2.3.0' but I have the same problem. Any ideas?
