### ISSUE TITLE
Granularity in line chart not working (Chart3.0-Swift2.3 )

### ISSUE THREAD

**Issue by marc-inn** [danielgindi/Charts#1534]
When I enable granularity in line chart, xAxis labels are gone. Without granularity labels are working correctly.

<img width="366" alt="screen shot 2016-09-22 at 16 13 48" src="https://cloud.githubusercontent.com/assets/3593905/18751529/aa0c7644-80df-11e6-8c35-bf9e5078af0f.png">

**Comment by danielgindi** [comment]
What value did you set for granularity?
You can see it working in the demos.

**Comment by marc-inn** [comment]
As far as I see the labels are not shown, when the granularity is set to true (with default 1.0), and the values are within scope of 1 (i.e. x = 0.1, x = 0.2, x = 0.8). It is working properly when the x-values have bigger range.

**Comment by danielgindi** [comment]
Granularity of 1 for x - 0.1, 0.23, 0.42 is obviously not a good choice.............

**Comment by marc-inn** [comment]
You are right, but the for me it will be more intuitive to display edge granularity (in that case: 0 and 1). In my case I need to present data with floating points values on xAxis and labels should visible every whole number. 

I solved that by adding additional LineChartDataSet with edge values to LineChartData.

Thanks
Btw. your library is the best!
