### ISSUE TITLE
How to show x-axis labels only when value is a DataEntry in Line Chart?

### ISSUE THREAD

**Issue by Lorenzo-R** [danielgindi/Charts#1536]
I use the x value of data entries to represent time in a `LineChart` and a `xAxis.valueFormatter` to format the `TimeInterval` value into a date string. However I'd like the labels on the `xAxis` to show only the dates relative to a data entry (as it was before with `xIndex`), and hide all the ones that are currently shown in the space between two entry. I tried using `xAxis.granularity`, but it also prevents some "significant" dates (relative to an entry) to be shown.
I hope there's a way to solve this problem.

I am currently using the master of 19/09/2016, waiting for 3.0 release to come out!

Thanks a lot for the awesome library!

**Comment by Huang-Libo** [comment]
@Lorenzo-R Maybe you should modify the source code in `AxisRendererBase.swift` file, the interval's value is rounded in there:
```
// Find out how much spacing (in y value space) between axis values
let rawInterval = range / Double(labelCount)
interval = ChartUtils.roundToNextSignificant(number: Double(rawInterval))
```

```
let intervalMagnitude = ChartUtils.roundToNextSignificant(number: pow(10.0, Double(Int(log10(interval)))))
let intervalSigDigit = Int(interval / intervalMagnitude)
if intervalSigDigit > 5
{
    // Use one order of magnitude higher, to avoid intervals like 0.9 or 90
    interval = floor(10.0 * Double(intervalMagnitude))
}
```

**Comment by nickjwallin** [comment]
See my comment on a similar issue here: https://github.com/danielgindi/Charts/issues/1732#issuecomment-256761902

The difference for you would be that in `- (NSString *)stringForValue:(double)value axis:(ChartAxisBase *)axis`, you would convert the value from double to `NSInteger`, for example, and then check if that NSInteger corresponds to a DataEntry you care about. (You'll have to keep track of your data entries I suppose).

For example:
```
- (NSString *)stringForValue:(double)value axis:(ChartAxisBase *)axis
{
    if (axis == _yAxis)
    {
        // create a string
    }
    else
    {
        NSInteger index = [NSNumber numberWithDouble:value].integerValue;
        // if (index is something you care about) (
        //   return a date string for it
        // }
    }
}
```

You'll have to play with the granularity to prevent overlap of values, maybe. This may be difficult to get working, but hopefully this helps you get started!

**Comment by liuxuan30** [comment]
thanks @nickjwallin seems I can close it. Feel free to reopen if not resolved
