### ISSUE TITLE
can i set data's starting point?

### ISSUE THREAD

**Issue by ttoggaiman** [danielgindi/Charts#1537]
Usually, It seems like the barchart starts from 0 and shows data. For example, if the value on the Y-axis is 9, the bar would show up from 0 to 9. But I would like to present the bar from the middle not from 0. For example, if the value is 3.9,  I would like to have a bar from 3 to 9. How can I do that?
![0303](https://cloud.githubusercontent.com/assets/22382653/18791280/114a0138-81ed-11e6-9620-e50ccb854b8e.jpg)

**Comment by Huang-Libo** [comment]
@ttoggaiman Seems strange..

**Comment by ttoggaiman** [comment]
is there any idea?--

**Comment by petester42** [comment]
Maybe you could try the candle stick graph with the extended lines off or maybe a stacked bar chart with a transparent bottom bar.

**Comment by petester42** [comment]
We don't support bar charts since that is not how bar charts should display a data set.

**Comment by liuxuan30** [comment]
If you refer to kind of waterfall chart, you have to override a couple of methods to do so. It's not a normal bar chart in your case. 
or you could try @petester42 mentioned candle stick chart. Similar
