### ISSUE TITLE
Charts.framework iOS not exist

### ISSUE THREAD

**Issue by sumlitLin** [danielgindi/Charts#1538]
In the previous version when i hit the "+" under the "Embedded Binaries" section, there exist Charts.framework iOS , But in the latest version  i can't find it ,it's only have Charts.framework macOS ,Should I choose  Charts.framework macOS  ？

**Comment by sumlitLin** [comment]
but i develop iOS Application

**Comment by petester42** [comment]
Yes you should. It's is one framework for all platforms. The basic setup is macOS but it has been setup to work on all platforms. Having 1 framework makes the development more manageable.
