### ISSUE TITLE
how can i draw only bar chart without x-axis, y-axis , grid line

### ISSUE THREAD

**Issue by ttoggaiman** [danielgindi/Charts#1539]
bar chart have x-axis,y-axis, grid line , value label , bar image 

i want to draw only bar image ,...   and want to undraw or hide x-axis, y-axis, grid line ..

how can i that?

**Comment by liuxuan30** [comment]
try axis.enabled = false
basically you should look for switches named 'xxxEnabled'

**Comment by ttoggaiman** [comment]
thanks!!!

**Comment by RamblinWreck77** [comment]
This answer is invalid for Swift 3. 

The vast majority of "switches" @liuxuan30  are get-only
