### ISSUE TITLE
I want to control  width between bar 

### ISSUE THREAD

**Issue by ttoggaiman** [danielgindi/Charts#1542]
I would like to show two data using the chart control. The thing is that the space between charts is narrow. How can I widen the space between the charts like the picture below?

![1212](https://cloud.githubusercontent.com/assets/22382653/18791719/d2ee74c6-81ee-11e6-918e-89fd036559b5.jpg)

**Comment by liuxuan30** [comment]
try `barSpace`. But you should remember, you can't control the absolute value, it's just a percentage

**Comment by ttoggaiman** [comment]
thanks you!!!!

**Comment by gaganindersingh** [comment]
how to use this property?
