### ISSUE TITLE
Grouped bars in Combined chart

### ISSUE THREAD

**Issue by pilot34** [danielgindi/Charts#1543]
Hello! Thank you for the great library.

In Charts 3.0 you added method `open func groupBars(fromX: Double, groupSpace: Double, barSpace: Double)` to group columns from different dataSets in `BarChartData`

But what if I have such `BarChartData` inside `CombinedChartData` combined with `LineChartData`? I need to recount coordinates for line too, but I'm afraid there is no such method.

## Example

![](https://monosnap.com/file/CXZ5fMM0fbe6sDKVnGZpwUEQZRfowC.png)

I have 2 x-values here. Line have both values and 2 groups of bars have values. But line is displayed wrong.

Should be smth like that: 

![](https://monosnap.com/file/qmCI5MZLLtYYhHvyoxL8sOkTXSbMGq.png)

**Comment by pilot34** [comment]
What do you think about a support  of grouped columns with lines?

**Comment by liuxuan30** [comment]
I don't understand what's your issue. You should follow how ChartsDemo or the API to implement combined chart.
