### ISSUE TITLE
How to add charts cocoapods dependency for Swift 3 project?

### ISSUE THREAD

**Issue by damacster** [danielgindi/Charts#1544]
Simply adding pod 'Charts' pulls version 2.30, which works with Swift 2.3.

is there a cocoapods dependency for a Swift 3 only project?

**Comment by damacster** [comment]
Never mind, it's coming in version 3.0.

**Comment by petester42** [comment]
You can point your podfile to master for now if you NEED 3.0. But ya it's coming.
