### ISSUE TITLE
Problem with the xValue begins at 0

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#1547]
Hi @liuxuan30 @danielgindi !

I just found a new kind of issue with the bar charts, I have a little set with 12 groups of bars, every group has two bars. Now I'm setting my groups since the x = 0.

```swift
        for i in 0..<dataPoints.count{
            let dataEntry = BarChartDataEntry(x: Double(i), y: values[i])            
            dataEntries.append(dataEntry)
        }
```

As you can see here in the image the last element is not completely drawing over the chart check the black rectangle.

![screen shot 2016-09-23 at 5 07 39 pm](https://cloud.githubusercontent.com/assets/5713880/18803075/a90b4ada-81b2-11e6-9a87-a8070a1f0490.jpg)

I'm using the last commit over master, which is 180c418 and i guess the problem is the same function that before, in this case over the ```BarChartView```

```swift
    internal override func calcMinMax()
    {
        guard let data = self.data as? BarChartData
            else { return }
        
        if fitBars
        {
            _xAxis.calculate(
                min: data.xMin - data.barWidth / 2.0,
                max: data.xMax + data.barWidth / 2.0)
        }
        else
        {
            _xAxis.calculate(min: data.xMin, max: data.xMax)
        }
        
        // calculate axis range (min / max) according to provided data
        _leftAxis.calculate(
            min: data.getYMin(axis: .left),
            max: data.getYMax(axis: .left))
        _rightAxis.calculate(
            min: data.getYMin(axis: .right),
            max: data.getYMax(axis: .right))
    }
```

The ```data.xMax``` is just taking acount of the last element in ```x``` wich is 11 ( counting the 0 as 1 ) and that's the reason why at the end the chart is clipping the last groups of bars. This is just my first assumption please tell me if you think that the problem is in another side. 

Thanks in advance.

**Comment by liuxuan30** [comment]
tried fitBars = true?

**Comment by chuynadamas** [comment]
Hi @liuxuan30 I'm using that property :) but the problem stills there :(

**Comment by liuxuan30** [comment]
:( one more bug.. though I didn't see it in ChartsDemo

**Comment by danielgindi** [comment]
Pull the latest master please, search for duplicate issues in the future
