### ISSUE TITLE
horizontal bar graphs with different colors and offset values

### ISSUE THREAD

**Issue by seecahkhing** [danielgindi/Charts#1552]
Hi,

Do you have any advise if Charts can possibly do something like below:
<img width="480" alt="horizontalbargraph" src="https://cloud.githubusercontent.com/assets/213741/18809005/e5dddcf6-82a3-11e6-9be4-4f6cfa14e161.png">

Thanks

**Comment by danielgindi** [comment]
Yes, it's a horizontal stacked bar chart- look at the demos, there's one like this :-)

**Comment by seecahkhing** [comment]
Thanks a lot @danielgindi .. got it...
