### ISSUE TITLE
Chart clip the Ballon Marker

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#1553]
Hi @liuxuan30 @danielgindi 

I found a little bug with the markers, when you select one wich is close with the right bound of the chart, this will clip the popup just like you can see in the image below

![screen shot 2016-09-24 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/5713880/18810429/13892f0a-825b-11e6-8eae-f7170e5fdb6e.png)

**Comment by liuxuan30** [comment]
I'm wondering if this is the last value that marker is for? I checked the code, marker is not clipped. Seems like cutting by view itself

**Comment by chuynadamas** [comment]
Hi @liuxuan30 
Yep, is the last value, also I want to ask if there is any way to don't crop the first and the last bubble, something like fitBars but for the bubble ?

**Comment by liuxuan30** [comment]
I remember someone had the same issue and post some code, but I can't find it now. Needs to change `draw()` not to clip, or use `drawExtra()`

**Comment by chuynadamas** [comment]
Hi @liuxuan30 I looking for the drawExtras() func, but there is empty over  ```BarChartRenderer``` :( 

```swift
    open override func drawExtras(context: CGContext)
    {
        
    }
```
Is that the function that you are talking about ?

**Comment by chuynadamas** [comment]
Hi @liuxuan30, I guess that the problem is the following lines in the function ``` internal func drawMarkers(context: CGContext) ```  You guys are only checking if the middle point is inside the viewPortHandler, but you are not checking if the whole marker is inside the viewPort, there is anyway to check the width and the height of the markers, before draw it?  

```swift
            // check bounds
            if !_viewPortHandler.isInBounds(x: pos.x, y: pos.y)
            {
                continue
            }
```

**Comment by liuxuan30** [comment]
:( clipping the marker and judging if the marker should be draw are different right?
judging: not sure if using width could lead to markers on the edge might got cut, so some people would complain.. using middle point is kind of trade off. You can override :)

for clipping - what I mean is you could draw those things you don't want get clipped inside drawExtra, which needs you to override and implement drawing marker there.

**Comment by chuynadamas** [comment]
Hi @liuxuan30 , I'm getting the same behaviour also with the ```clipToBouns``` turned off, I guess that one that the marker was judged, we can check if the whole rect is inside the bounds of the view, and if is not, we need to move it to avoid the clipping, what do you think ?

**Comment by liuxuan30** [comment]
`drawMarkers()` is outside clipping already. You can check on your side.
What's your views stack? all views that turn off `clipToBounds`?

**Comment by danielgindi** [comment]
The marker is not clipped by the chart, but by the view. You can use the `offsetForDrawing` for offsetting the marker to be always visible. This is what `MarkerImage` and `MarkerView` are doing by default.
