### ISSUE TITLE
Argument labels '(value:, xIndex:)' do not match any available overloads, Cannot invoke initializer for type 'BarChartData' with an argument list of type '(xVals: [String], dataSets: [BarChartDataSet])'

### ISSUE THREAD

**Issue by thexande** [danielgindi/Charts#1554]
I am attempting to build a basic bar chart with this library and Xcode 8 / swift 3 combo. 

The library is integrated, and now I am attempting to populate a bar chart view with data from one of the more popular tutorials for this library online located here: [http://www.thedroidsonroids.com/blog/ios/beautiful-charts-swift/](beautiful-charts-swift)

Unfortunately, this demo is for an older version of this lib and the methods seem to have changed. 

I have tried to look through the repo for an example of these methods, but the example app is written in objective c. Perhaps someone familiar with the new methods can point me in the right direction. 

The two methods that are causing build errors are the following: 

```swift
            // Create single chart data entry and append it to the array
            let saleEntry = BarChartDataEntry(value: sale.value, xIndex: i)
```

produces the error: 

```
~/TestChartViewController.swift:32:29: Argument labels '(value:, xIndex:)' do not match any available overloads
```

and when we try to create the bar chart data using the following method: 

```swift
        // Create bar chart data with data set and array with values for x axis
        let chartData = BarChartData(xVals: salesMonths, dataSets: [chartDataSet])
```

Produces the following error:

```
~/TestChartViewController.swift:46:25: Cannot invoke initializer for type 'BarChartData' with an argument list of type '(xVals: [String], dataSets: [BarChartDataSet])'
```
Here is my TestChartViewController class:

```swift
import UIKit
import Charts

class TestChartViewController: UIViewController {
    @IBOutlet var barChart: BarChartView!
    override func viewDidLoad() {
        super.viewDidLoad()
        barChart.noDataText = "You need to provide data for the chart."
        // Do any additional setup after loading the view.
        
        // Get and prepare the data
        let sales = DataGenerator.data()
        
        // Initialize an array to store chart data entries (values; y axis)
        var salesEntries = [ChartDataEntry]()
        
        // Initialize an array to store months (labels; x axis)
        var salesMonths = [String]()
        
        var i = 0
        for sale in sales {
            // Create single chart data entry and append it to the array
            let saleEntry = BarChartDataEntry(value: sale.value, xIndex: i)
            salesEntries.append(saleEntry)
            
            // Append the month to the array
            salesMonths.append(sale.month)
            
            i += 1
            
    }
        // Create bar chart data set containing salesEntries
        let chartDataSet = BarChartDataSet(values: salesEntries, label: "Profit")
        
        // Create bar chart data with data set and array with values for x axis
        let chartData = BarChartData(xVals: salesMonths, dataSets: [chartDataSet])
        
        // Set bar chart data to previously created data
        barChart.data = chartData
        
    } 
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

And this is my dataGenerator class: 

```swift
import Foundation

struct Sale {
    var month: String
    var value: Double
}

class DataGenerator {
    
    static var randomizedSale: Double {
        return Double(arc4random_uniform(10000) + 1) / 10
    }
    
    static func data() -> [Sale] {
        let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        var sales = [Sale]()
        
        for month in months {
            let sale = Sale(month: month, value: randomizedSale)
            sales.append(sale)
        }
     
        return sales
    }
}
```

THANKS ALL!!!

**Comment by thexande** [comment]
For anyone interested, I have created a simple app demonstrating the issue. Check out my repo here: https://github.com/thexande/IOS_Charts_Swift_3_demo/commits/master

**Comment by liuxuan30** [comment]
Do you use pod for the library? There are few reports similar to this. You need to take a look at what version or branch of this library you are using, and double check the super class method

**Comment by liuxuan30** [comment]
BTW, I don't see `let chartData = BarChartData(xVals: salesMonths, dataSets: [chartDataSet])` exists in Chart 3.0

**Comment by RanjitKadam** [comment]
@thexande did you solved this issue, I too have the same problem. @liuxuan30 can you help

**Comment by thexande** [comment]
Never solved it. Started fresh and the demo works. Did you look at the demo @RanjitKadam ?

**Comment by RanjitKadam** [comment]
which demo? I dont see any iOS swift demo here. I using xcode 8.0

**Comment by thexande** [comment]
There is no ios demo but the mac/desktop demo is written in swift. Checkout charts-demo-osx in the root dir.

**Comment by RanjitKadam** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16592090/19019015/e7a1ee56-8893-11e6-82f7-13772be4313e.png)


check this out. I ran the demo and first and last bars are sticking, which is not correct

**Comment by thexande** [comment]
Hmm. Looks like a new issue. This one got closed, so the mods wont look at it. I would say open a new one with screenshots/errors and try your luck.

**Comment by RanjitKadam** [comment]
but @thexande , I am not understanding this piece of code, Can you help me out.

 ```
let ys1 = Array(1..<10).map { x in return sin(Double(x) / 2.0 / 3.141 * 1.5) }
        let ys2 = Array(1..<10).map { x in return cos(Double(x) / 2.0 / 3.141) }
        
        let yse1 = ys1.enumerated().map { x, y in return BarChartDataEntry(x: Double(x), y: y) }
```

**Comment by thexande** [comment]
Which piece?

**Comment by RanjitKadam** [comment]
I have added the code above, please check it out

**Comment by thexande** [comment]
Looks like It is just  creating some data to put in the chart man.

**Comment by RanjitKadam** [comment]
i want x and y values form this array below.. So how can I do it

```
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
        let unitsSold = [10.0, 4.0, 6.0, 3.0, 12.0, 16.0]
```

**Comment by thexande** [comment]
Looks like you need to brush up on some Swift man. Check out enumeration, map, for loops etc. The sample you pasted in has the format required, so just feed it the array you have in the format you pasted from the demo. 

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html
https://www.weheartswift.com/higher-order-functions-map-filter-reduce-and-more/

**Comment by RanjitKadam** [comment]
ok thanks @thexande , I will go through it

**Comment by AshishKapoor** [comment]
Guys you can checkout : https://github.com/AshishKapoor/cex-graphs for a running example.

**Comment by jrkuhn** [comment]
To anyone who comes across this again, for iosCharts 3.0, the new way to get a value's index is:
`entry.x  //get xIndex of ChartDataEntry
entry.y  //get yIndex of ChartDataEntry`
I am dumbfounded that the library couldn't recommend me the deprecated way of 'entry.xIndex' from iosCharts 2.0

Thanks to @AshishKapoor for sharing his example, that's how I found this. Check out his CGMainViewController.swift file in his repository above for his full implementation
