### ISSUE TITLE
Chart clip the Ballon Marker

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#1555]
Hi @liuxuan30 @danielgindi 

I found a little bug with the markers, when you select one wich is close with the right bound of the chart, this will clip the popup just like you can see in the image below

![screen shot 2016-09-24 at 1 06 23 pm](https://cloud.githubusercontent.com/assets/5713880/18810429/13892f0a-825b-11e6-8eae-f7170e5fdb6e.png)

I guess that this is easy fix, Once that I can solve I'll apply the PR to see if you like my fix :) 
Thanks in advance.

**Comment by liuxuan30** [comment]
seems dup to https://github.com/danielgindi/Charts/issues/1553
