### ISSUE TITLE
Extraneous space between axis and bars when there is data with value of 0

### ISSUE THREAD

**Issue by royherma** [danielgindi/Charts#1557]
Using version `2.2.4` for Swift (because i haven't converted to Swift 3.0 yet)

This seems to be a issue with this version strictly, as it worked fine in my previous version. See screenshots below for example:

WORKS - Version 2.1.4

![simulator screen shot sep 25 2016 12 05 46 am](https://cloud.githubusercontent.com/assets/3466248/18813581/ef7c53ae-82b3-11e6-9757-b3d8af968b21.png)

BROKEN - Version 2.1.4

![simulator screen shot sep 24 2016 11 51 20 pm](https://cloud.githubusercontent.com/assets/3466248/18813582/f59e866c-82b3-11e6-88f9-cc76aa24039c.png)

Any possibilities to fix this?

And תודה רבה דניאל, אחלה של פריימוורק!

**Comment by liuxuan30** [comment]
I am quite not sure since it's an old release. But what you could try is (as I remember) setAxisMinValue = 0; check axis dependency;

There is a release that use `setAxisMinvalue` rather than `startAtZeroEnabled`
