### ISSUE TITLE
[Chart 3.0 BUG] xAxis labels disappear after a deep zoom in

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1564]
xAxis labels disappear after a deep zoom in
Step to reproduce:
1. Open ChartsDemo Time Line Chart
2. zoom in a lot, until the xAxis label disappears

After triage, I found there are two issues:
1: `centerAxisLabelsEnabled` will be false after entryCount = 1.
Change to below, xAxis.entries will have only 1 entry after zoom in.
```swift
    open var centerAxisLabelsEnabled: Bool
    {
        get { return _centerAxisLabelsEnabled && entryCount > 0 }
    }
```
2: I found in 
```swift
open func computeAxisValues(min: Double, max: Double)
    ...
    let last = interval == 0.0 ? 0.0 : ChartUtils.nextUp(floor(yMax / interval) * interval
    if interval != 0.0 && last != first // condition is false due to last equals first now
    {
        for _ in stride(from: first, through: last, by: interval)
        {
            n += 1
        }
    }
    ...
```
After zoom in a lot `first` and `last` are the same value, causing `n` to be default value, which is 1 (centerAxisLabelsEnabled is 1 now instead of 0 because above code change in # 1)

**Comment by danielgindi** [comment]
That is fixed. However, you should limit the maximum zoom in to a reasonable number.
If the zoom is in to a position where the difference between two axis labels is "0.000000000000001", it's not a zoom that is useful to the user.

**Comment by danielgindi** [comment]
I guess that by "deep zoom in" you are referring to a zoom so deep the the distance between two labels is zero or close to zero. That's not a usable zoom anyway. Please limit the max zoom in available to the user.

**Comment by liuxuan30** [comment]
yeah 'deep zoom in' means zoom in until you can't see any data entry in a line chart.

**Comment by Crossarchon** [comment]
import UIKit
import Foundation
import Charts

@objc(BarChartFormatter)
public class BarChartFormatter: NSObject, IAxisValueFormatter{
    var months: [String]! = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    
    
    public func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        
        return months[Int(value)]
}
    
    
class BarGraphViewController: UIViewController {

    @IBOutlet weak var barChartView: BarChartView!
   
    var months: [String]!
    
    func setChart(dataPoints: [String], values: [Double]) {
        let formato:BarChartFormatter = BarChartFormatter()
        let xaxis:XAxis = XAxis()
        barChartView.noDataText = "Please provide data for the chart. You need to record your BMI data for the year."
        var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<dataPoints.count {
            
            let dataEntry = BarChartDataEntry(x: Double(i+2), y:values[i], data: months as AnyObject?)
            dataEntries.append(dataEntry)
            
            formato.stringForValue(Double(i), axis: xaxis)
        }
        
        xaxis.valueFormatter = formato
    
    let chartDataSet = BarChartDataSet(values: dataEntries, label: "BMI")
    
    let chartData = BarChartData()
    chartData.addDataSet(chartDataSet)
    barChartView.data = chartData
    barChartView.chartDescription?.text=""
    barChartView.xAxis.valueFormatter = xaxis.valueFormatter
    }
    override func viewDidLoad() {
        super.viewDidLoad()

        months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        let bodyMassIndex = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0] //mock data points here
        
        setChart(dataPoints: months, values: bodyMassIndex)
        // Do any additional setup after loading the view.
    }
Following your steps isn't quite working. any insight?

**Comment by castus** [comment]
I have the same problem, I have three bars with points (x: 0, y: 1), (x: 1, y: 2), (x: 2, y: 3) and when I'm zooming the whole bar disappears. The same with labels, they disappears even earlier than bars. How to prevent this?
