### ISSUE TITLE
Cocoapods integration with objective c projects - can't resolve

### ISSUE THREAD

**Issue by kevnm67** [danielgindi/Charts#1568]
Thanks for providing a great framework!  Until last week I've had no issues using charts via cocoapods in a primary obj c project.  I've been using charts in my project for 6 months... 
I've read through all open issues related to errors compiling Charts in objective c projects but haven't been able to resolve my issue.  

- Do I need to uninstall charts cocoapods integration and use it as an embedded framework?

**Comment by petester42** [comment]
You probably need to update cocoapods yo at least 1.1.0.rc2 and also check that  the "use legacy swift" flag in build settings is the right value.
