### ISSUE TITLE
CombinedChartView fitBars property

### ISSUE THREAD

**Issue by noldidrita** [danielgindi/Charts#1569]
I've just migrated to  Charts 3.0 and I'm having a problem with the CombinedChartView. The first and the last bar are cut in half (i.e their width is not calculated properly). In BarChartView I fix this problem by setting fitBars to true, however in CombinedChartView I can't seem to find this property. Moreover, not only in this one, as well as the normal BarChartView and HorizontalBarChartView, the count of the horizontal labels seems to be miscalculated. (Card is appearing twice, although I only inserted it once)

 Any solution? 

![screen shot 2016-09-27 at 4 12 38 pm](https://cloud.githubusercontent.com/assets/9396312/18877341/43715318-84cd-11e6-991a-ef91daa9588a.png)

**Comment by liuxuan30** [comment]
Can you try latest master branch's ChartsDemo? Don't forget to run `carthage bootstrap` to install dependencies.
I do see other people reporting this, however, with latest ChartsDemo, I don't see it on bar chart or combined chart.

For the labels - please try latest master as well..

**Comment by sree127** [comment]
@noldidrita For the `Card` repeating twice, try setting the `granularity to 1`.

**Comment by noldidrita** [comment]
Settings the granularity helped for the first issue. However the issue about the bar width still persists. I just ran pod update with the following line in the pod file:
    pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
Now that I check again, the same issue is also present in BarChartView as well, fitBars did not actually fix the issue. Any tips?

![screen shot 2016-09-28 at 3 47 59 pm](https://cloud.githubusercontent.com/assets/9396312/18915944/fd5b2bda-8592-11e6-9a26-9b1d07f28ec0.png)

**Comment by liuxuan30** [comment]
@noldidrita if you use latest master, then I need you to check if ChartsDemo has the same issue? I can't reproduce it. 
To run ChartsDemo, run `carthage bootstrap` frist

**Comment by jvmk** [comment]
I'm new to this library but from what I've learned so far, a bar is painted such that its horizontal middle point equals the x value in BarChartDataEntry. This in turn means that your x-axis minimum point must be _the minimum x value in your data set minus half your bard width_ in order for the first bar not to be cut in half. Example: if your bar width is 0.9 and your minimum x value in your data set is 0, your x-axis minimum point must be 0 - 0.9 / 2 = -0.45. Set this like so: `combinedChart.xAxis.axisMinimum = -0.45`. The reverse is true for the x axis maximum value, i.e. it must be at least your dataset's maximum x value plus half the bar width. Hope this helps.

**Comment by danielgindi** [comment]
When having brs in the Combined chart, you need to pad the axis:
```
        chart.xAxis.spaceMin = 0.5
        chart.xAxis.spaceMax = 0.5
```
Because bars are centered on the position of the value, and a bar on the zero means it's centered on the 0 and goes to the left and right of it.

**Comment by ryanwaggoner** [comment]
Setting spaceMin / spaceMax causes labels to be misaligned

**Comment by everlof** [comment]
@ryanwaggoner Yes, I got the same problem.

I solved it by this (ugly) workaround in my formatter:

`let newValue = ( value + chart.xAxis.spaceMin ) * ( chartData.xMax / ( chartData.xMax + 1))`

**Comment by milakovicmilosOviva** [comment]
@everlof  Have you set spaceMin and spaceMax? Can you post your complete implementation of formatter?

**Comment by everlof** [comment]
@milakovicmilosOviva Here it is (mine's bigger since I have some other logic, for other cases, but this should be the gist of it).

```
open class DateValueFormatter: NSObject, IAxisValueFormatter { 

       var dateBase: Double

        init(dateBase: Double) {
                self.dateBase = dateBase
        }

        public func stringForValue(_ value: Double, axis: AxisBase?) -> String {
                guard let chart = chart else { return "No `chart`" }
                guard let chartData = chart.data else { return "No `chartData`" }
                let newValue = ( value + chart.xAxis.spaceMin ) * ( chartData.xMax / ( chartData.xMax + 1))
                return dateFormatter.string(from: Date(timeIntervalSince1970: ((newValue) * 3600 * 24) + dateBase))
        }
}
```

Then initiate it with `date.timeIntervalSince1970` for the first value.
