### ISSUE TITLE
 Method does not override any method from its superclass

### ISSUE THREAD

**Issue by avinash2pandey** [danielgindi/Charts#1572]
Pods/Charts/Source/Charts/Utils/ChartPlatform.swift:111:30: Method does not override any method from its superclass

in xcode 7.3

**Comment by petester42** [comment]
see #1526

**Comment by avinash2pandey** [comment]
Hey petester,
we didn't find the solution. we are using "Charts 2.3.0" in xcode 7.3.1 and swift 3.0.

**Comment by petester42** [comment]
Charts 2.3.0 is for Xcode 8 only and it is for swift 2.3.
