### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by avinash2pandey** [danielgindi/Charts#1573]
Pods/Charts/Source/Charts/Utils/ChartPlatform.swift:111:30: Method does not override any method from its superclass

in xcode 7.3

we didn't find the solution. we are using "Charts 2.3.0" in xcode 7.3.1 and swift 3.0 from pod.

**Comment by liuxuan30** [comment]
First, do not create dulicated issues;
Second, Please read README carefully and use search function for this.
At last, you see "Charts 2.3.0" is for Xcode 8.
