### ISSUE TITLE
Line Chart X-Axis values as a string

### ISSUE THREAD

**Issue by asmcn** [danielgindi/Charts#1576]
I migrated our project to v2.3 to v3.0 and line chart x axis string values is removed. What should I do for string values on x-axis?

**Comment by sree127** [comment]
You need to use `Valueformatter` for that. Check that thread : 

[](https://github.com/danielgindi/Charts/issues/1527)

**Comment by liuxuan30** [comment]
anyone that migrates the library, please use search function.
