### ISSUE TITLE
Can I set a text label underneath each bar of a bar chart?

### ISSUE THREAD

**Issue by indieshack** [danielgindi/Charts#1577]
I've managed to get Charts working in my projects and the graphs look great. I need to create a series of vertical bar charts, which I can do fine, but I can't see how to set an individual string LABEL under each bar, it's only displaying numerically based on the positioning of a grid, and not the positioning of the bars. I assume I should be setting the label in the third argument of the BarChartDataEntry constructor, but it's not obvious where to enable display of that label.
Thanks

**Comment by liuxuan30** [comment]
if you draw it under each bar, won't it overlap with x axis?
if you don't need x axis labels, then take a look at `open override func drawValues(context: CGContext)` in BarChartRenderer, where it calculates the value position. You might need to override it.

**Comment by indieshack** [comment]
Let me get this straight - the label argument in the BarChartDataEntry constructor has no purpose?

**Comment by liuxuan30** [comment]
not yet?
