### ISSUE TITLE
i want to add % in value

### ISSUE THREAD

**Issue by KushThakkar** [danielgindi/Charts#1579]
I want to  like this:  "100.0%" instead of "100.0"

![screen shot 2016-09-29 at 11 28 45 am](https://cloud.githubusercontent.com/assets/17953979/18942718/6cc90d84-8638-11e6-8789-baf848cd0783.png)

i try this code:

self.arrPos[i] = CGFloat(Int(pos * 100.0)) / CGFloat(arrTotal[i] as! Double)
self.arrNeg[i] = CGFloat(Int(neg * 100.0)) / CGFloat(arrTotal[i] as! Double)

cell.barChartView.data = self.setChartBarGroupDataSet(arrAgeGrop, values: arrPos, values2:arrNeg, sortIndex: 1)

**Comment by danielgindi** [comment]
You use formatters to show whatever label you want. Please look at the demos.

**Comment by KushThakkar** [comment]
thanks. its done using formatters.
