### ISSUE TITLE
malloc: *** error for object : Invalid pointer dequeued from free list*** set a breakpoint in malloc_error_break to debug

### ISSUE THREAD

**Issue by Aruna-Sree** [danielgindi/Charts#1580]
After xcode upgradation to 8.0 charts not working in iOS 8 devices but workign fine in iOS 9+ device.
Getting some fatal errors or sometimes EXE_BAD_ACCESS.

Can you please suggest me how to fix this issue?

malloc: *** error for object : Invalid pointer dequeued from free list*** set a breakpoint in malloc_error_break to debug

**Comment by danielgindi** [comment]
Without more information we cannot help you. It might not even be a Charts issue.
You should enable **zombies** in your scheme. Google it.
Then when you have results - if you still think it belongs here - please come back and re-open the issue with more info.

**Comment by Yongle-Fu** [comment]
malloc: Heap corruption detected, free list is damaged at 0x2824a2af0
*** Incorrect guard value: 142660547833812
SwiftZenLite(97465,0x1e82cc680) malloc: *** set a breakpoint in malloc_error_break to debug

**Comment by Yongle-Fu** [comment]
#17	0x00000001016f2490 in CGContextRef.drawText(_:at:align:anchor:angleRadians:attributes:) at /Users/yongle/project/C/zenlite_sdk/ios/examples/ZenLiteSDKExample/Pods/DGCharts/Source/Charts/Utils/ChartUtils.swift:168
