### ISSUE TITLE
BarChart xAxis labels disappear after zooming

### ISSUE THREAD

**Issue by ajimenezjulio** [danielgindi/Charts#1583]
Hello, i have already seen a possible solution for this problem in #1564, but after trying i can't solve the problem, what are the lines that i have to fix for the barChart??

**Comment by liuxuan30** [comment]
try latest master, should be fixed

**Comment by wajihkm** [comment]
Actually it didn't resolved, I'm facing this issue  'Charts-3.0.0', 
I resolved it by ordering the "xValues".
Without ordering you will face it when you have a big xRange with little distributed data among xAxis.
