### ISSUE TITLE
Last LineChart y-label not being rendered

### ISSUE THREAD

**Issue by ryanschneider** [danielgindi/Charts#1585]
In 3.0 (using master from commit 3a2da1b) I'm seeing that the last y-label in my charts is not being rendered.

I've tracked down was I think is the cause to this line:

https://github.com/danielgindi/Charts/blob/a34d55a5c9d16c1f4f6f48f2148b4e88902c55d0/Source/Charts/Renderers/LineChartRenderer.swift#L552

I think the `stride(from:to:by)` should be a `stride(from:through:by)` (use `through`, not `to`), like so:

```swift

    open override func drawValues(context: CGContext)
    {
                //....
                for j in stride(from: _xBounds.min, through: Int(ceil(Double(_xBounds.max - _xBounds.min) * phaseX + Double(_xBounds.min))), by: 1)
                {
                    guard let e = dataSet.entryForIndex(j) else { break }
```

This edit works locally for me, I'll send a PR for the change as well here in a minute, but haven't done an extensive audit for the other chart types to see if a similar issue exists there.

**Comment by liuxuan30** [comment]
This is dup to https://github.com/danielgindi/Charts/issues/1323

**Comment by ryanschneider** [comment]
Closing as dupe of #1323.
