### ISSUE TITLE
IChartAxisValueFormatter cound't found

### ISSUE THREAD

**Issue by kocakmstf** [danielgindi/Charts#1588]
Hi,

I'm using cocoapods and getting this error. 

/Formatters/DateValueFormatter.h:16:43: Cannot find protocol declaration for 'IChartAxisValueFormatter'; did you mean 'ChartXAxisValueFormatter'?

**Comment by Legendgp** [comment]
![Snip20210910_1](https://user-images.githubusercontent.com/16458733/132796882-0341eb75-ddc1-460f-960a-32154211ff67.png)
![Snip20210910_2](https://user-images.githubusercontent.com/16458733/132796886-939a4591-f1ff-4dad-ad5f-5259934dfd71.png)
