### ISSUE TITLE
Member 'index' cannot be used on value of protocol type 'collection'; use a generic constraint instead

### ISSUE THREAD

**Issue by malaypatel11** [danielgindi/Charts#1593]
if colorString.hasPrefix("#")
        {
            var argb: [UInt] = [255, 0, 0, 0]
            let colorString = colorString.unicodeScalars
            var length = colorString.count
            var index = colorString.startIndex
            let endIndex = colorString.endIndex
            
            **index = <#T##Collection corresponding to `index`##Collection#>.index(index, offsetBy: 1)**
            length = length - 1
            
            if length == 3 || length == 6 || length == 8
            {
                var i = length == 8 ? 0 : 1
                while index < endIndex
                {
                    var c = colorString[index]
                    **index = <#T##Collection corresponding to `index`##Collection#>.index(index, offsetBy: 1)**
                    
                    var val = (c.value >= 0x61 && c.value <= 0x66) ? (c.value - 0x61 + 10) : c.value - 0x30
                    argb[i] = UInt(val) * 16
                    if length == 3
                    {
                        argb[i] = argb[i] + UInt(val)
                    }
                    else
                    {
                        c = colorString[index]
                        **index = <#T##Collection corresponding to `index`##Collection#>.index(index, offsetBy: 1)**
                        
                        val = (c.value >= 0x61 && c.value <= 0x66) ? (c.value - 0x61 + 10) : c.value - 0x30
                        argb[i] = argb[i] + UInt(val)
                    }
                    
                    i += 1
                }
            }

**Comment by liuxuan30** [comment]
No idea why asked here. closing

**Comment by malaypatel11** [comment]
Because these error comes in your framework that's why I am asked here.

**Comment by liuxuan30** [comment]
your code and title does not match well, and I  don't know what's the problem you are talking, either reproducing or where it crashes.

**Comment by malaypatel11** [comment]
http://pasteboard.co/1knihIRyg.png
can you see above image so you can better idea.

**Comment by danielgindi** [comment]
It seems like an error that should have been raised in compile time. Strange.

**Comment by danielgindi** [comment]
I see no crash there. And no complaint.
You are probably compiling with Xcode 7 or something like that.

**Comment by malaypatel11** [comment]
Yes thats compile and build failed. I am using Xcode 8 and swift 3.0.

**Comment by liuxuan30** [comment]
Please download the code again, I never saw code like yours on my side:
```swift
        if colorString.hasPrefix("#")
        {
            var argb: [UInt] = [255, 0, 0, 0]
            let colorString = colorString.unicodeScalars
            var length = colorString.count
            var index = colorString.startIndex
            let endIndex = colorString.endIndex
            
            index = colorString.index(after: index)
            length = length - 1
            
            if length == 3 || length == 6 || length == 8
```
