### ISSUE TITLE
cannot convert value of type<> to expected arguments RLMResults<RLMObjects>

### ISSUE THREAD

**Issue by superandrew** [danielgindi/Charts#1594]
Hi, not sure this is an issue.

Running Charts with realm, trying to copy in swift what is setup in objc in the demo project, I have this error:

```!Swift
let results = realm.objects(MinMaxMeasure)
        
let set: RealmLineDataSet = RealmLineDataSet(results: results, xValueField: "Myvalue", yValueField: "MyValue", label: "MySeries")

```

the error says:

```
cannot convert value of type Results<MinMaxMeasure> to expected arguments RLMResults<RLMObjects>
```

I get the point, but cannot understand if this depends from a wrong version of swift, a bug, or something I am not doing properly.

Also, If I instantiate a RLMRealm instead of a Realm Object, I get no compilation errors, however I have a EXC_BAD_ACCESS on Realm.verify inside the Realm framework.

I am trying to run in a XCode 8 /Swift3 project.

![screen shot 2016-10-02 at 14 52 00](https://cloud.githubusercontent.com/assets/71364/19020672/d24e4510-88af-11e6-85de-e60c40c26e34.png)

**Comment by superandrew** [comment]
So I thint I am using the objective-c realm instead of realmswift, is that correct? Is my setup wrong? Is RealmCharts able to use RealmSwift? And if so, how?

Thank you very much for helping.

**Comment by superandrew** [comment]
Just in case anyone stumbles in a similar issue: I was instantiating Realm this way:

```let realm = try! RLMRealm()```

instead of

```let realm = try! RLMRealm.default()```

I still don't understand why Charts cannot use RealmSwift or if there is something in my setup which is wrong. It's a very complicated library to setup for 2016 standard in my opinion.

**Comment by petester42** [comment]
From what I know Charts does not use RealmSwift is because it also has to work with Objective-C as well.

**Comment by danielgindi** [comment]
@petester42 is right. When building the data source for Realm, we had this problem. The Realm team added a future TODO for interoperation between Realm and RealmSwift, maybe even by just accessing RealmSwift internal pointers or wrapping Realm objects. But currently these are two separate, and having duplicate code here makes this even a bigger mess.
When they'll be ready - so will we...

**Comment by danielgindi** [comment]
Duplicate #898

**Comment by danielgindi** [comment]
https://github.com/realm/realm-cocoa/issues/4232
