### ISSUE TITLE
LeftAxis above bars in BarChartView

### ISSUE THREAD

**Issue by nthegedus** [danielgindi/Charts#1595]
I'm having a problem using BarChartView, but it only happens when I distribute my app on Testflight. Take a look:

This graph is OK, but it was builded using Xcode
![img_3816](https://cloud.githubusercontent.com/assets/1063383/19021203/f0216d96-8892-11e6-9df9-16df8c12dbe2.PNG)

This second one, have the leftAxis above the bars. This version was downloaded by Testflight
![img_3815](https://cloud.githubusercontent.com/assets/1063383/19021209/064633ae-8893-11e6-81b4-30f8aa7a8b30.PNG)

I'm using the 2.3.0 version, and I'm generating the build using fastflane, and fastlane is using the same version as I.
![screen shot 2016-10-02 at 11 28 20 am](https://cloud.githubusercontent.com/assets/1063383/19021223/6b260c18-8893-11e6-9720-8bdb59cd3f52.png)

Does anyone have an ideia about what's happening? 

Thanks

**Comment by nthegedus** [comment]
After many code reviews, I realized that I was using `XAxisLabelPositionBottom` in `leftAxis.labelPosition`. I don't know why it didn't get an error, but I just change to `YAxisLabelPositionOutsideChart`, and I worked fine as well.

**Comment by petester42** [comment]
Glad to hear. 👍
