### ISSUE TITLE
Grid and  xaxis label issues.

### ISSUE THREAD

**Issue by RanjitKadam** [danielgindi/Charts#1596]
Hello, firstly thanks for the lib,

secondly, I have issues with lib, which I have listed by creating a stackOverFlow question,

http://stackoverflow.com/questions/39817831/issues-with-ios-chart-library

Thanks
Ranjit

**Comment by liuxuan30** [comment]
try leftAxis.axisMinValue = 0.0

**Comment by RanjitKadam** [comment]
thanks
