### ISSUE TITLE
Adjust circle for selected point

### ISSUE THREAD

**Issue by nicholassmith** [danielgindi/Charts#1597]
Is it possible to adjust the displayed circle for a point on a line chart? I've looked at the public API in the headers and can't see an obvious way. Do I need to use a marker view to achieve it?

**Comment by apurva** [comment]
I am looking for the same solution, as it could solve the highlighting issue being discussed here: https://github.com/danielgindi/Charts/issues/1495 

Does anyone know how to get the screen co-ordinates of a selected point on a line graph?

**Comment by nicholassmith** [comment]
It seemed like it wasn't doable, I ended up using a secondary data set to show the highlighted value with a different circle.

**Comment by liuxuan30** [comment]
Check out LineChartRenderer's `drawCircles()` and `drawHighlighted`. Looks like you have to override it for now, as not many people asking this.

**Comment by apurva** [comment]
Thanks for the tip! I am guessing the secondary dataset would have only one value (the one that would be highlighted). Could you tell me how you are able to set the x position of the dataset to align with the x position of the selected item in the main graph?

**Comment by liuxuan30** [comment]
not very clear your question

**Comment by nicholassmith** [comment]
@apurva there's a delegate which is triggered when a value is selected (I'm not at my development machine so I'll post later what it is exactly). That returns a `ChartDataEntry` which contains the Y & X values, you create a `ChartDataSet` with that entry and it'll draw over the other entry.

**Comment by apurva** [comment]
@nicholassmith Thanks again! That worked for me and I am able to show a filled circle for the highlighted point.

 For others reading this, the delegate methods to do this in are - chartValueSelected: & chartValueNothingSelected:
