### ISSUE TITLE
Swift based library, but OC based Demo. Have you ever thought of provide a Swifty Demo?

### ISSUE THREAD

**Issue by zhugejunwei** [danielgindi/Charts#1598]
I like this library very much!! I want to use it in a better way, in other words, I want to learn how you use it in Swift. Can you provide a Swfity Demo some day?

**Comment by petester42** [comment]
The OS X demo is swift. Having the demo be objective-c helps us make sure we didn't break objective-c support. 

Short answer is that we have no plans to do so as the resulting code would be exactly the same just with different syntax.
