### ISSUE TITLE
Pod pointing to master branch code created issue in BarChartDataEntry

### ISSUE THREAD

**Issue by monica18p** [danielgindi/Charts#1599]
I migrated to Charts 3.0 by specifying the pod as
`pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'`
but didn't find any specification about the changes made for the following shown error.
<img width="923" alt="screen shot 2016-10-03 at 11 34 21 am" src="https://cloud.githubusercontent.com/assets/6171473/19028812/d2d8f134-895d-11e6-9de4-83a4cd2f7b6e.png">

Can somebody please help me out with this

**Comment by petester42** [comment]
See  #1474 for migration info.

**Comment by mrkilimanjaro** [comment]
How about posting a fix rather than posting a link that does not address the issue, and closing the issue?  #1474 has no explanation on how to fix the first error on this screen shot above.

**Comment by petester42** [comment]
Because the fix is mentioned in the migration guide. See the bold text in the quote:

> Breaking changes / how to migrate:
> 
> - All dataset constructors have changed - they do not take an array of x-indices anymore.
> - **# All entry constructors have changed - they take in an X and a Y.**
> - Pie and Radar chart entries now have their own classes. So exchange the Entry classes withPieChartDataEntry/RadarChartDataEntry

And here is the source code that shows the initializers: 
https://github.com/danielgindi/Charts/blob/master/Source/Charts/Data/Implementations/Standard/BarChartDataEntry.swift#L33-L61
