### ISSUE TITLE
Support for swift 3.0

### ISSUE THREAD

**Issue by Bharati555** [danielgindi/Charts#1600]
When the support for swift 3.0 will be released.

**Comment by samrayner** [comment]
Open source projects are inherently difficult to provide a timeline for as the contributors are usually not paid to work on them. I'm sure they will officially release a new version as soon as they can.

That said, in the meantime, you can already use the master branch of Charts in a Swift 3 project. Assuming you're using CocoaPods, put this in your Podfile and do a `pod update`:

```
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
```

**Comment by gklka** [comment]
You can also prevent Xcode errors by enabling legacy swift version:

![screen shot 2016-10-03 at 12 37 45](https://cloud.githubusercontent.com/assets/866694/19034858/48d62a34-8966-11e6-83fb-37aacb035c9e.png)

**Comment by liuxuan30** [comment]
still have bugs.. just wait

**Comment by Bharati555** [comment]
ok done Thanx
