### ISSUE TITLE
BarChart View issues

### ISSUE THREAD

**Issue by RanjitKadam** [danielgindi/Charts#1601]
Hello All, 

I am getting few issues which I am not able to tackle

Below is my code

```
func createChart(xValues:[Int],yValues:[Int])
    {

       xValues = [27,28,29,30,1,2,3]
      yValues = [5,0,0,4,1,0,0]
        var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<xValues.count {            
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(yValues[i]))
            dataEntries.append(dataEntry)
        }
        
        
        let data = BarChartData()
        let ds1 = BarChartDataSet(values: dataEntries, label: "Tickets Sold")
        ds1.colors = [THEMECOLOR]
        data.addDataSet(ds1)
        
        let formatter = ChartStringFormatter()
        formatter.nameValues = xValues
        barChartView.xAxis.valueFormatter = formatter
        
        barChartView.xAxis.drawGridLinesEnabled = false
        barChartView.legend.enabled = false
        
        barChartView.data = data
        
        barChartView.fitBars = true
        
        barChartView.rightAxis.enabled = false
        
        barChartView.xAxis.labelPosition = .bottom
        
       self.barChartView.chartDescription?.text = ""
        
       barChartView.legend.enabled = false 
        
       barChartView.animate(xAxisDuration: 2.0, yAxisDuration: 2.0)
    }

```

I am getting a graph this way

![screen shot 2016-10-03 at 4 44 57 pm](https://cloud.githubusercontent.com/assets/16592090/19035714/d0f6e684-8988-11e6-9792-3650e8215125.png)

But I am expecting some thing like this 

![untitled123](https://cloud.githubusercontent.com/assets/16592090/19035721/ec5811c8-8988-11e6-9bd1-1a21c39c02d3.png)

The problems which I want to fix are

1) I see a space at the bottom where the bar starts from x axis
2) I want the labels on bars to be Int and not Double
3) I want to change the width of bars.

Thanks

**Comment by ios-sagar** [comment]
I am facing the problem same as you for point 2.
I also wanted to show integer values, not the double.

for your point 1 answer is,

set leftAxis and rightAxis minimum value to 0.
like I did below,

barChartClass.barChartView.leftAxis.axisMinValue = 0
barChartClass.barChartView.rightAxis.axisMinValue = 0

for point no 2 & 3 if you get the answers do let me know as well.

**Comment by ios-sagar** [comment]
Dude, I found the answer for your point 3 as well.
Check for property 
public var barSpace: CGFloat = 0.15

and increase this value as per the requirement.
which will reduce the width of your bars.

**Comment by RanjitKadam** [comment]
hey @ios-sagar , for point 2 use valueFormatter property of BarChartDataSet
