### ISSUE TITLE
Pods failing for swift3.0

### ISSUE THREAD

**Issue by raubreywhite** [danielgindi/Charts#1602]
Hi,

I tried adding this line to my pod file to install the swift 3.0 version:

pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'Chart2.2.5-Swift3.0'

It installs properly, but the downloaded version doesn't seem to be swift3, as Xcode gives me over 2000 error messages for Charts...

Any ideas as to how I can get the beta/unstable swift3 charts version into my Xcode project via pod files?

Thanks!

**Comment by petester42** [comment]
Use master. It is swift 3.0 compatible. But it is charts 3.0. We don't have plans to support 3.0 for 2.2.5

**Comment by raubreywhite** [comment]
Ok, I just changed it to downloading from the master brach. Unfortunately, it's the same problem. I open my .xcworkspace file and Xcode wants me to convert charts into swift3. If I refuse, it then spawns over 2000 compiler errors...

**Comment by raubreywhite** [comment]
And I'm not seeing any errors from the pod update either:

MacBook-Pro:Disease raw996$ pod update
Update all pods
Updating local specs repositories

CocoaPods 1.1.0.rc.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

Analyzing dependencies
Pre-downloading: `Charts` from `https://github.com/danielgindi/Charts.git`, branch `master`
Downloading dependencies
Installing Charts (3.0.0)
Using SORandom (1.0.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 2 dependencies from the Podfile and 2 total
pods installed.

**Comment by petester42** [comment]
Is "use legacy swift" set to yes in your project?

**Comment by petester42** [comment]
if all else fails. Set "use legacy swift" to false, delete our pods directory and run `pod install` again.

**Comment by raubreywhite** [comment]
I just set "use legacy swift" to false, deleted your pods directory, and ran pod install again.

I think I now have the swift3 version (it isn't nagging me to convert from swift 2.3 to swift 3) but there are still a crazy amount of errors...

![screenshot](https://cloud.githubusercontent.com/assets/1532091/19052105/d591ee3c-89b5-11e6-929d-62622b5bb8d1.jpg)

**Comment by raubreywhite** [comment]
Ok, I just created a new project from scratch and repeated all of the above stuff, and it worked :-) So I now have an empty project with charts, so I will copy all of my old code into the new project. It must be something stupid with Xcode, where it refuses to let go of the old compiler errors.

Thanks for the help!
