### ISSUE TITLE
Setting AxisBase.axisMaximum results in an axisRange of zero

### ISSUE THREAD

**Issue by TomSidebottom** [danielgindi/Charts#1603]
When I set axisMaximum for the ordinate on a graph to a value, the range of the values plotted on the ordinate appeared was collapsed to zero. The code for AxisBase.axisMaximum is:

    open var axisMaximum: Double
    {
        get
        {
            return _axisMaximum
        }
        set
        {
            _customAxisMax = true
            _axisMaximum = newValue
            axisRange = abs(_axisMaximum - newValue) // Always results in a range of zero.
        }
    }

This results in axisRange is always being set to zero, because newValue has the same value as _axisMaximum. Making the following change fixed the problem:

    open var axisMaximum: Double
    {
        get
        {
            return _axisMaximum
        }
        set
        {
            _customAxisMax = true
            _axisMaximum = newValue
	   axisRange = abs(_axisMaximum - _axisMinimum)
        }
    }

**Comment by liuxuan30** [comment]
wow, I see it. Will fix it
