### ISSUE TITLE
How to use a date/string for the X value

### ISSUE THREAD

**Issue by hdoria** [danielgindi/Charts#1604]
The new Charts version only accepts double for the x value. How can I use a date (or string) for the X value?

ChartDataEntry: public init(x: Double, y: Double)

**Comment by Carielle** [comment]
[This](https://github.com/danielgindi/Charts/issues/1527) issue talks about how to use axis value formatters to use strings as axis labels. 

However, I'm still confused about how I can put one string under each bar in a bar chart, instead of the strings lining up with axis gridlines.

**Comment by liuxuan30** [comment]
@Carielle I don't understand why you said this. In ChartsDemo, the x axis label is centered in each bar's center.

**Comment by madhikarma** [comment]
Hey @hdoria how did you get on? Did you find the new `IAxisValueFormatter` in Charts v3.0.0 to customise the text to a string?

Just in case: create one a subclass of `IAxisValueFormatter`, implement `func stringForValue(_ value: Double, axis: AxisBase?) -> String ` and return the string you want there then set your `xAxis.valueFormatter` to it.

Let us know how you get on and whether to close this issue.

**Comment by hdoria** [comment]
@madhikarma did exactly like you said. Thanks.
