### ISSUE TITLE
Chart not centered/middled when having less values

### ISSUE THREAD

**Issue by sree127** [danielgindi/Charts#1605]
If a chart has only few `Data Entries`, the chart items are moving to extreme ends rather than starting in the middle. Is this the default chart behaviour? Or is there a way to achieve this? 

![screen shot 2016-10-04 at 1 35 57 pm](https://cloud.githubusercontent.com/assets/3157263/19066632/c87a1fb2-8a37-11e6-94e1-06e7825dcae4.png)

While adding the entries, I tried giving an offset to x like below :
```
     for(index, object) in response.enumerated() {
            

            let some = BarChartDataEntry(x: Double(index) + 1.0, yValues: [Double(10), Double(10), Double(10)])
            dataEntry.append(some)
        }
```

Still the chart is not moving from the extreme ends? Also set these 2 properties : 

```
chartView.fitBars = false
xAxis.avoidFirstLastClippingEnabled = true
```

@liuxuan30 @danielgindi @Huang-Libo Any leads?

**Comment by liuxuan30** [comment]
Would you try ChartsDemo? I didn't see it in ChartDemo
