### ISSUE TITLE
Using version 3.0 with Carthage?

### ISSUE THREAD

**Issue by lateAtNight** [danielgindi/Charts#1607]
Is it possible to use version 3.0 with Carthage? I have `github "danielgindi/Charts" ~> 3.0` in my Cartfile but it ends up checking out v2.1.4a. Is this because version 3.0 hasn't been officially released yet? Sorry if its an obvious question - new to Carthage.

**Comment by petester42** [comment]
You need to point to master and not to 3.0 until it is released. This can be done like so `github "danielgindi/Charts" "master"`
