### ISSUE TITLE
customAxisMin and customAxisMax not found on object ChartYAxis

### ISSUE THREAD

**Issue by osolano** [danielgindi/Charts#1608]
Hello,

After i did an update on the library I got an error
```
Property 'customAxisMin' not found on object of type 'ChartYAxis' *
Property 'customAxisMax' not found on object of type 'ChartYAxis' *
```
Was this property updated with a new name?
Is it now called axisMaxValue and axisMinValue?

**Comment by petester42** [comment]
I believe what you are looking for is `axisMinimum` and `axisMaximum` from [here](https://github.com/danielgindi/Charts/blob/26363c43049a1a3c017e92df3b8caab060cc3278/Source/Charts/Components/AxisBase.swift#L315-L344). If so we will add that change to #1474.

**Comment by madhikarma** [comment]
Hey @osolano Did you try the above solution and the use the new 'axisMinimum' in Charts v3.0.0? Let us know if it worked for you and whether we can close this issue.

**Comment by osolano** [comment]
That did it for me. I switched over to axisMinimum and axisMaximum and everything worked fine thanks! I'll close this issue.

**Comment by ankitkapasi** [comment]
This didn't work for me. My points and line dont get plotted. I see the data is fine from logging it out to the console. Any advice? 

I just migrated to Xcode8 swift 2.3 and am pointing to the 2.3.0 tag.
