### ISSUE TITLE
App Crash: could not cast to 'Charts.PieChartData': in 2.3.0 when upgrading to XCode 8.0

### ISSUE THREAD

**Issue by LiftEd-Admin** [danielgindi/Charts#1609]
Seems related to closed issue #410 (https://github.com/danielgindi/Charts/issues/410) but not fixed by https://github.com/danielgindi/Charts/commit/d6cb47e0955df0cb7bab598e283c9b1636f06117

Error in console:

Could not cast value of type 'Charts.ChartData' (0x100e0e838) to 'Charts.PieChartData' (0x100e183e0).

Crash on line 182 of PieChartView.swift:  private func calcAngles():
        let yValueSum = (_data as! PieChartData).yValueSum

Error occurs on updated Charts CocoaPod to 2.3.0 and swift 2.3 when upgrading primarily Objective-C codebase from XCode 7 to XCode 8

Objective-C Code triggering this issue:

  double resultForPercentage = somevalue;
  ChartDataEntry *entry1 = [[ChartDataEntry alloc] initWithValue:resultForPercentage xIndex:0];
  ChartDataEntry *entry2 = [[ChartDataEntry alloc] initWithValue:(100.0f - resultForPercentage) xIndex:1];
  PieChartDataSet *set1 = [[PieChartDataSet alloc] initWithYVals:@[entry1,entry2]];

  goalCell.graphView.data = [[ChartData alloc] initWithXVals:@[@"",@""] dataSets:@[set1]];

which then eventually calls:  PieChartView.swift:  private func calcAngles():
          let yValueSum = (_data as! PieChartData).yValueSum

**Comment by petester42** [comment]
You need to use `PieChartData` as the class instead of `ChartsData` so:

`goalCell.graphView.data = [[PieChartData alloc] initWithXVals:@[@"",@""] dataSets:@[set1]];`

**Comment by LiftEd-Admin** [comment]
Confirmed that petester42's suggestion worked.

FYI:  The code above worked fine in Charts 2.1.6, it was updating to XCode 8 + Swift 2.3 + Charts 2.3.0 that triggered this error.  Glad it was a simple fix, thanks again!
