### ISSUE TITLE
Issue with YAxis max and min in the RadarChart

### ISSUE THREAD

**Issue by paul-pinto92** [danielgindi/Charts#1610]
Hi there,

I'm facing an issue with the maximum value of the yAxis on the Radar Chart : 
I want it to be from **0** to **4** so here's what i did : 

`radarChartView.yAxis.axisMaximum = 4`
`radarChartView.yAxis.axisMinimum = 0`

but when i run the program here's what i get : 
<img width="377" alt="screen shot 2016-10-05 at 11 37 16" src="https://cloud.githubusercontent.com/assets/19780782/19108212/24aa20da-8af0-11e6-9cf1-4b4915e89450.png">

May someone explain to me how to achieve what i want please ? :)

**Comment by PeterBurenkov** [comment]
Hi @paul-pinto92 , I think it's a workaround, but still. Try set `axisMaximum=3`

**Comment by paul-pinto92** [comment]
Hi @PeterBurenkov,

That's close but not quite it : 

<img width="378" alt="screen shot 2016-10-05 at 13 18 12" src="https://cloud.githubusercontent.com/assets/19780782/19111161/542c3312-8afe-11e6-9ed5-022bcd398631.png">

as if the Radar Chart has to have 6 values on the axis. I'm surely missing something. 

Thank you for your reply though.

**Comment by PeterBurenkov** [comment]
`maxValue = 4, axisMaximum = maxValue * 2/3` works for me :)
there is option `yAxis.labelCount = 4` but it doesnt work for me also

**Comment by paul-pinto92** [comment]
Thanks man ! That's one way to do it.
Then I dove into the source code and found why, in the YAxisRendererRadarChart,  i had 6 labels and why `yAxis.labelCount = 4` does not work. 

You need to enable force labels like so : 
`radarChartView.yAxis.forceLabelsEnabled = true`
then you put the amount of labels you want : 
`radarChartView.yAxis.labelCount = 5`
and finally you ask for a maximum : 
`radarChartView.yAxis.axisMaximum = 4`

so this code 
`radarChartView.yAxis.forceLabelsEnabled = true`
`radarChartView.yAxis.labelCount = 5`
`radarChartView.yAxis.axisMaximum = 4`
`radarChartView.yAxis.axisMinimum = 0`

gives you this : 
<img width="376" alt="screen shot 2016-10-05 at 13 59 32" src="https://cloud.githubusercontent.com/assets/19780782/19112345/a3c0664a-8b04-11e6-91d0-426df4a4a922.png">

Thank you again for your help 👍

**Comment by PeterBurenkov** [comment]
@paul-pinto92 great! it helped me a lot!
the only one thing... 
```
radarChartView.yAxis.forceLabelsEnabled = true
radarChartView.yAxis.labelCount = 5
```
this lines should be swapped since setter set the option to `false`

 ```
open var labelCount: Int
    {
        get
        {
            return _labelCount
        }
        set
        {
            _labelCount = newValue
            
            if _labelCount > 25
            {
                _labelCount = 25
            }
            if _labelCount < 2
            {
                _labelCount = 2
            }
            
            forceLabelsEnabled = false
        }
    }
```

**Comment by paul-pinto92** [comment]
Hey nice catch ! Thanks !

**Comment by mattgallivan** [comment]
I don't believe this is fixed although it says that it is in the Changelog?

**Comment by Kavisha-Dev** [comment]
@PeterBurenkov  and @paul-pinto92 's solution worked for me. 
I have 5 labels & my max y-axis is required to be 5. So i set 👍 
`yAxis.labelCount = 6
        yAxis.forceLabelsEnabled = true
        yAxis.axisMinimum = 0
        yAxis.axisMaximum = 5`

Worked for me.
