### ISSUE TITLE
Charts/Classes/Utils/ChartUtils.swift error

### ISSUE THREAD

**Issue by jackywongcw** [danielgindi/Charts#1611]
Hello,

Not sure if anyone encountered this before (I've searched from the issue)
//
fatal error: Double value cannot be converted to Int because it is either infinite or NaN
(lldb) 
//

I got this error message when I'm entering a screen to display the chart.

// here's your method
    internal class func decimals(_ number: Double) -> Int
    {
        if number.isNaN || number.isInfinite || number == 0.0
        {
            return 0
        }
        
        let i = roundToNextSignificant(number: Double(number))
        
        if i.isInfinite
        {
            return 0
        }
        
        return Int(ceil(-log10(i))) + 2 
    }
//
        return Int(ceil(-log10(i))) + 2 // <------------------------ 
Unable to convert the return value to int, so I tried using *Int(round(ceil(-log10(i))) + 2)*, gives the same error. Could it be something wrong with the calculations inside?

Please advice. 
Thank you!

**Comment by petester42** [comment]
This had been fixed by #1558
