### ISSUE TITLE
[NOT AN ISSUE] Release for Charts 3.0

### ISSUE THREAD

**Issue by troupmar** [danielgindi/Charts#1612]
May I just ask when Charts 3.0 for Swift 3.0 will be released? We just moved from using Pods to Carthage and unfortunately the framework cannot be imported when using Xcode 8.0 / Swift 3.0. There was not such problem when using Pods.

Thanks so much for the reply and sorry for using "Issues" for this reason.

**Comment by ptaking** [comment]
My personal project was suspended :D Still waiting :D

**Comment by petester42** [comment]
Yes it can be used with Carthage right now. Just use `"master"` instead of the version requirement.
