### ISSUE TITLE
ChartViewDelegate's chartValueSelected is tied up with Highlights

### ISSUE THREAD

**Issue by UberJason** [danielgindi/Charts#1614]
I noticed that the ChartViewDelegate method `chartValueSelected` is tied up with Highlights, meaning it fires when you highlight a bar and doesn't fire when you de-highlight a bar (instead, `chartValueNothingSelected` is called). That's great, but when `highlightEnabled` is set to false, neither method fires when a bar is tapped. It would be awesome if these two could be untangled in that situation - if `highlightEnabled` is false, tapping the bar should always fire `chartViewSelected`, just like it's a simple tap gesture recognizer.

**Comment by liuxuan30** [comment]
maybe some format for your text.. hard to read. 
It depends on different needs. Some people thought `highlightEnabled` is false should not trigger any highlight behavior at all..
you are the first to ask this.

**Comment by UberJason** [comment]
Maybe a second flag then, to decouple the tap gesture recognizer from the highlighter? Having a tap gesture recognizer that just fires on all taps feels more like a standard iOS API, it would be great to have this.

**Comment by danielgindi** [comment]
`chartViewSelected` is **not** a tap recognizer. If you want a `UITapGestureRecognizer`, then add one.
`chartViewSelected` is **not** fired when there's no selection, because there's no selection, I think it's plain English and it makes sense...
