### ISSUE TITLE
warning: Swift Charts 2.3.0 - error in module ChartsDebug info from this module will be unavailable in the debugger.

### ISSUE THREAD

**Issue by abjacs** [danielgindi/Charts#1615]
Hello! I converted my Swift project to 2.3 syntax and updated the Charts pod to 2.3.0.
Project compiles successfully within XCode 8, but throws an exception at runtime.

`   private func updateStylingChart( chart: LineChartView, data: [Double]) {`
 `  chart.backgroundColor = UIColor.clearColor()`   
 `       chart.leftAxis.removeAllLimitLines() // error`
 `       \\......`

Code executes without error when running on an iPhone 6s emulator, iOS 9.2/9.3.
Code crashes on iPhone 6s, iOS 9.3.3

**Debugger output:**
warning: Swift error in module ChartsDebug info from this module will be unavailable in the debugger.

Any help is appreciated!

**Comment by liuxuan30** [comment]
We need more crash trace here. Warning should not cause crash I think.

**Comment by abjacs** [comment]
**Ran bt command within lldb:**

* thread #1: tid = 0x8cf76, 0x0000000100100c44 SolarTrackr`MetricsController.(chart=0x0000000161034de0, data=13 values, self=0x00000001610140f0)(LineChartView, data : [Double]) -> () + 264 at MetricsController.swift:450, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000100100c44 SolarTrackr`MetricsController.(chart=0x0000000161034de0, data=13 values, self=0x00000001610140f0)(LineChartView, data : [Double]) -> () + 264 at MetricsController.swift:450
    frame #1: 0x00000001000ff2ec SolarTrackr`MetricsController.tableView(tableView=0x00000001600f6800, indexPath=0xc000000000000016, self=0x00000001610140f0) -> UITableViewCell + 3888 at MetricsController.swift:402
    frame #2: 0x0000000100100b1c SolarTrackr`@objc MetricsController.tableView(UITableView, cellForRowAtIndexPath : NSIndexPath) -> UITableViewCell + 92 at MetricsController.swift:0
    frame #3: 0x000000018661b030 UIKit`-[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 692
    frame #4: 0x000000018661b198 UIKit`-[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 80
    frame #5: 0x000000018660a298 UIKit`-[UITableView _updateVisibleCellsNow:isRecursive:] + 2360
    frame #6: 0x000000018661fc64 UIKit`-[UITableView _performWithCachedTraitCollection:] + 104
    frame #7: 0x00000001863b08c4 UIKit`-[UITableView layoutSubviews] + 176
    frame #8: 0x00000001862c01e4 UIKit`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 656
    frame #9: 0x0000000183c5298c QuartzCore`-[CALayer layoutSublayers] + 148
    frame #10: 0x0000000183c4d5c8 QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 292
    frame #11: 0x0000000183c4d488 QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 32
    frame #12: 0x0000000183c4cab8 QuartzCore`CA::Context::commit_transaction(CA::Transaction*) + 252
    frame #13: 0x0000000183c4c818 QuartzCore`CA::Transaction::commit() + 500
    frame #14: 0x0000000183c45ddc QuartzCore`CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 80
    frame #15: 0x000000018111c728 CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
    frame #16: 0x000000018111a4cc CoreFoundation`__CFRunLoopDoObservers + 372
    frame #17: 0x000000018111a8fc CoreFoundation`__CFRunLoopRun + 928
    frame #18: 0x0000000181044c50 CoreFoundation`CFRunLoopRunSpecific + 384
    frame #19: 0x000000018292c088 GraphicsServices`GSEventRunModal + 180
    frame #20: 0x000000018632e088 UIKit`UIApplicationMain + 204
    frame #21: 0x0000000100139e38 SolarTrackr`main + 144 at AppDelegate.swift:12
    frame #22: 0x0000000180be28b8 libdyld.dylib`start + 4

**Comment by danielgindi** [comment]
I would make sure that the framework is Embedded (read README), do a clean build, and make sure I'm not setting nil to anything that's not allowed to be nil
