### ISSUE TITLE
Method does not override any method from its superclass

### ISSUE THREAD

**Issue by derekibw** [danielgindi/Charts#1616]
after pod install, build error:

version:2.3.0, xcode 7.3.1

XXX/Pods/Charts/Source/Charts/Utils/ChartPlatform.swift:111:30: Method does not override any method from its superclass

**Comment by RonnyCoder** [comment]
Same Issue for me as well. @derekibw Please provide solution if you got it. Thanks in advance.
For Xcode 8 it works fine, but when we open code in Xcode 7.3 it give error *ChartPlatform.swift:111:30: Method does not override any method from its superclass*

**Comment by liuxuan30** [comment]
Update your Xcode to 8. Or use 2.2.5
