### ISSUE TITLE
Extract ChartsRealm and Realm from the Charts project

### ISSUE THREAD

**Issue by mcapelle** [danielgindi/Charts#1618]
It seems that Realm is a dependency for Charts only for the ChartsRealm feature.  
If it's correct could that feature be extracted from Charts to avoid to bring Realm in a project that doesn't need ChartsRealm?

Or is it a way to add Charts to an iOS project using Cocoapods without including ChartsRealm and Charts?

Thanks

**Comment by petester42** [comment]
You can definitely use charts without realm with cocoapods or Carthage. Even if you include the Xcodeproject you just need to only include the charts framework not the charts realm. 

Does that make sense.
