### ISSUE TITLE
RadarChartData xVals cant use

### ISSUE THREAD

**Issue by AnChiChang** [danielgindi/Charts#1619]
Before update iOS chart to newest version,  i can 

let radarChartData = RadarChartData(xVals: dataPoints, dataSet: radarChartDataSet)

however, after upgrade, can't set xVals in RadarChartData, only

let radarChartData = RadarChartData(dataSet: radarChartDataSet)

How can I set xVals in newest version. I had searched many document, but can't find how to do that, thanks advise.

**Comment by liuxuan30** [comment]
If you are using Chart 3.0, please refer to the new APIs. It is breaking changes for x values.

**Comment by leszarna** [comment]
I think people often go from google straight here. It would seem much better to answer ticket with 2 line example than to write answers like go to #1474. Most people doesn't use this library much, and searching some changelog is simply waste of time. It's not easy to find solution in 15 minutes for me so probably same for others.
