### ISSUE TITLE
can I Achieve this? Using this framework

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1622]
example one
![image](https://cloud.githubusercontent.com/assets/20593532/19209988/f0d1d50e-8d48-11e6-8b55-846206426937.png)
example two
![image](https://cloud.githubusercontent.com/assets/20593532/19209992/19184b38-8d49-11e6-9859-5ea37a7cafeb.png)

**Comment by yushan023** [comment]
example two I achieve.

**Comment by danielgindi** [comment]
See Line Chart example in the demo.

**Comment by liuxuan30** [comment]
it's just linear line or  cubic line. Check `LineChartDataSet.Mode`
