### ISSUE TITLE
Charts 3.0: How to set x-values for a line chart?

### ISSUE THREAD

**Issue by arienmalec** [danielgindi/Charts#1627]
I want a line chart that represents temporal data with x labels for each timeperiod (e.g., each day), and x-y values only for collected data.

In the previous version, I did this like so:

```swift
let d = LineChartData(xVals: presenter.xLabels, dataSet: dataSet)
//...
self.data = d
```

This constructor no longer exists, and despite searching around, I haven't seen a clear substitute.

What's the Charts 3.0 equivalent?

**Comment by danielgindi** [comment]
You haven't searched enough... You can see the demos, or this:
https://github.com/danielgindi/Charts/issues/1474

**Comment by arienmalec** [comment]
This is not terribly responsive. By "searching around" I did intend to mean that I had read the migration note, and looking at the demos.

Despite this, the answer to my question is not apparent.

All of the demos have one y value per x value. The `ChartDataEntry` object takes only an `x`,`y` pair.

I want a graph that has more x value than y values.

This is similar to https://github.com/danielgindi/Charts/issues/1584 although I'm not sure I understand the workaround described (setting min/max x axis values).

**Comment by liuxuan30** [comment]
@arienmalec not very clear what's your issue. If you want to set x values, just follow line chart or Time Line Chart in ChartsDemo. I'ts enough info
An entry only took only one x and y. It's point, having more x values than y values in entry does not make sense.

**Comment by arienmalec** [comment]
@liuxuan30 

As a concrete example, imagine an exercise log. On the x-axis, there are days. Y values are work performed. There are y values only for days when exercise was performed. The line graph displays the trend of exercise sessions.

This kind of time series chart is fairly common, and worked just fine in the previous version of Charts, by setting the xVals explicitly as noted above.

For comparison, I've attached an Excel graph that displays the pattern.
![time-series-line-graph](https://cloud.githubusercontent.com/assets/1158918/19240593/f9e350be-8ebf-11e6-8927-bcd14df270fa.png)

**Comment by liuxuan30** [comment]
With ChartsDemo I can have something like below that looks similar to yours.
![delete](https://cloud.githubusercontent.com/assets/4375169/19263603/b2d30118-8fcf-11e6-962f-6759c594a649.png)

You can also try Time Line Chart as well. It's two different x axis style.

**Comment by arienmalec** [comment]
Here's the solution for posterity:

Where the code was previously:

```swift
let d = LineChartData(xVals: xLabels, dataSet: dataSet)
//...
self.data = d
```

The Charts 3.0 version is:

```swift
let d = LineChartData(dataSet: dataSet)
self.data = d
self.xAxis.valueFormatter = XValsFormatter(xVals: xLabels)
xAxis.axisMinimum = Double(0)
xAxis.axisMaximum = Double(presenter.xLabels.count - 1)
```

```swift
class XValsFormatter: NSObject, IAxisValueFormatter {
    
    let xVals: [String]
    init(xVals: [String]) {
        self.xVals = xVals
    }
    
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return xVals[Int(value)]
    }
    
}
```
