### ISSUE TITLE
LineChartData is nolonger allow initWithXVals, what should I do?

### ISSUE THREAD

**Issue by aibui** [danielgindi/Charts#1629]
My old code to set custom x value.
LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
with the new version of graph this no longer work. Does anyone have a example?
my xVals is an array of string.

**Comment by hackjie** [comment]
@aibui i met same problem

**Comment by hackjie** [comment]
@aibui  https://github.com/danielgindi/Charts/issues/1625 hi, you can try a formatter class like demo, i succeed by this way

**Comment by liuxuan30** [comment]
Just convert to latest API syntax.

**Comment by raj-zealous** [comment]
@aibui  n @liuxuan30  get any solution of this issue ...please give suggestion or code .
