### ISSUE TITLE
How to make points interactive/draggable

### ISSUE THREAD

**Issue by 3ph** [danielgindi/Charts#1631]
Hi, I'm looking at using ios-charts for displaying bezier curves (charts). I would like to be able to adjust to control points interactively. Can somebody please point me into the right direction? What needs to be overriden, etc? Thanks

**Comment by liuxuan30** [comment]
hmm it's challenging. If I were you, I would do a prototype based on CoreGraphics, and if you do need the cool features in this library, then you have to walk through the library and find a way to integrate them.
