### ISSUE TITLE
PieChartView cannot show values name .

### ISSUE THREAD

**Issue by WYZKirk** [danielgindi/Charts#1632]
PieChartView cannot show value names as picture.
![piechartview](https://cloud.githubusercontent.com/assets/17986384/19228367/120b5eb6-8ef7-11e6-81d7-64e606a9ce18.jpg)
Charts 2.3.0 show the value names.
![charts2 3 0](https://cloud.githubusercontent.com/assets/17986384/19228795/15119c66-8efb-11e6-80a8-c728ab3d7b7b.jpg)

**Comment by liuxuan30** [comment]
I just check master branch, it's working. Check ChartsDemo.
Also, you should know Chart 2.3.0 is very different from Chart 3.0, if you are using Chart 3.0
