### ISSUE TITLE
[Travis] Travis won't build issue

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1633]
Seeing below log in Travis CI for a couple of weeks,
https://travis-ci.org/danielgindi/Charts/builds/165976532
Project:https://github.com/danielgindi/Charts
I filed this here https://github.com/realm/realm-cocoa/issues/4199#issuecomment-252541944
and they told to set up a token for travis: https://github.com/travis-ci/travis-ci/issues/4195
>
First you need an access token from GitHub. You can check how to do that [here](https://help.github.com/articles/creating-an-access-token-for-command-line-use/).
Once you have an access token all you need is travis encrypt GITHUB_ACCESS_TOKEN=YOUR_ACCESS_TOKEN --add env.global. To add an encrypted env variable to your .travis.yml.

Since it's kind of 'personal access token', @danielgindi I guess you have to create it to solve?

**Comment by danielgindi** [comment]
Actually travis is logged in to out repo...

**Comment by danielgindi** [comment]
And it syncs correctly. Something in the script that runs the tests fails now. As the tests themselves do succeed in Xcode, I suspect it is some kind of version mismatch? @petester42

**Comment by petester42** [comment]
I added my own ci token to Travis to fix the download issues. I'll check it out later.
