### ISSUE TITLE
Some acute questions about ZDLineChartView

### ISSUE THREAD

**Issue by XiaoHanGe** [danielgindi/Charts#1635]
The line chart line chart: before the feedback through the interface passing an array can achieve X axis free distribution, and no data will display the X axis, X axis now appear decimal phenomenon, if I had no data values when y is 0 in an array of X axis from data to return to normal the starting line data is redundant, please 
<img width="434" alt="7d512371-7dd7-4c33-a644-b7a3a6f3f3c3" src="https://cloud.githubusercontent.com/assets/14025157/19232054/263cbf6a-8f10-11e6-8358-49e30a36c118.png">
<img width="474" alt="b2fe64c7-548b-467f-8b56-15f58d10f18c" src="https://cloud.githubusercontent.com/assets/14025157/19232055/263fd380-8f10-11e6-8c0c-aaf875b3b399.png">

look:

**Comment by danielgindi** [comment]
We know nothing here about `ZDLineChartView`...
