### ISSUE TITLE
Cannot get my Linechart to work since Xcode 8 update

### ISSUE THREAD

**Issue by ericjsalazar** [danielgindi/Charts#1640]
Greetings all,

I've searched every issue and the documentation and cannot seem to get my code to work. I was wondering if you guys could help me fix my issue as described below.

First of all, with the change of formatters, I cannot get it to work. Here's an example of what I had:
![screen shot 2016-10-10 at 2 35 17 pm](https://cloud.githubusercontent.com/assets/17553821/19251943/d4a0252a-8ef6-11e6-94eb-53f1ea37aa0d.png)

The old code (short version) consisted of:
```
    SPRangeFormatter *rangeFormatter = (SPRangeFormatter *)leftAxis.valueFormatter;
    if (!rangeFormatter) {
        rangeFormatter = [[SPRangeFormatter alloc] init];
    }
    rangeFormatter.resultsDict = uniquePresentationResults;

    leftAxis.valueFormatter = rangeFormatter;
    NSString *resultOrder = [resultDict objectForKey:@"sortOrder"];
    [yVals addObject:[[ChartDataEntry alloc] initWithValue:[resultOrder intValue] - 1 xIndex:i]];
        }
    LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithYVals:yVals label:[parameterName capitalizedString]];
```
Where SPRangeFormatter is defined in its own class with a setter method:
```
- (void)setResultsDict:(NSDictionary *)resultsDict
{
    _resultsDict = resultsDict;
    
    if (!self.sortedResults) {
        self.sortedResults = [[NSMutableArray alloc] init];
    }
    [self.sortedResults removeAllObjects];
    
    [self.sortedResults addObjectsFromArray:[_resultsDict allValues]];
    NSSortDescriptor *sortOrderDescriptor = [[NSSortDescriptor alloc] initWithKey:@"sortOrder" ascending:YES];
    [self.sortedResults sortUsingDescriptors:@[sortOrderDescriptor]];
}
```
With the update, I've changed the code to the following:
```
    SPRangeFormatter *rangeFormatter = (SPRangeFormatter *)leftAxis.valueFormatter;
    if (!rangeFormatter) {
        rangeFormatter = [[SPRangeFormatter alloc] init];
    }
    NSLog(@"Results: %@", uniquePresentationResults);
    rangeFormatter.paramResultsDict = uniquePresentationResults;
    leftAxis.valueFormatter = [[ChartDefaultAxisValueFormatter alloc] initWithFormatter: rangeFormatter];
    NSString *resultOrder = [resultDict objectForKey:@"sortOrder"];
    int resultValue = [resultOrder intValue];
    if (resultOrder) {
        [allMutableVals addObject:[[ChartDataEntry alloc] initWithX:i y:resultValue]];
    }
```
When I build, I get the following error: 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ChartDefaultAxisValueFormatter setParamResultsDict:]: unrecognized selector sent to instance 0x15e2015b0'

If I comment out the formatter, the points I pass through will not be displayed on the graph and I get the following error:
<Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.

**Comment by danielgindi** [comment]
Why ` SPRangeFormatter *rangeFormatter = (SPRangeFormatter *)leftAxis.valueFormatter;`? 
If you haven't set `leftAxis.valueFormatter` to be an `SPRangeFormatter`, then it won't return a `SPRangeFormatter`. 
So your call to `.paramResultsDict` results in "unrecognized selector sent to instance ".

Have you read the migration notes (#1474)?
You have three options: Either create a `ChartDefaultAxisValueFormatter` and pass it your old formatter, subclass `ChartDefaultAxisValueFormatter`, or make `SPRangeFormatter` conform to the `IAxisValueFormatter` protocol and pass it to `leftAxis.valueFormatter`.

**Comment by ericjsalazar** [comment]
Thank you daniel. I've been struggling since the update and tried to resist asking until I had no other options.
