### ISSUE TITLE
Custom background color

### ISSUE THREAD

**Issue by sydneysrirak** [danielgindi/Charts#1641]
Hi,

Is there anyway to replicate this background color effect using Charts?

![screen shot 2016-10-11 at 3 36 59 pm](https://cloud.githubusercontent.com/assets/14045720/19257025/c6c98126-8fc8-11e6-8014-188792d3498a.png)
]

Thanks

**Comment by liuxuan30** [comment]
dup to https://github.com/danielgindi/Charts/issues/645
It's not implemented yet, but there are insights and ideas in #645

**Comment by sydneysrirak** [comment]
Ah I see, thanks!

**Comment by NamitaMahtta** [comment]
Has this feature been added yet?
