### ISSUE TITLE
this func -nsuiTouchesEnded does not work

### ISSUE THREAD

**Issue by comlog** [danielgindi/Charts#1642]
nsuiTouchesEnded  is not working 。 Drag and drop the data on the table when the hand leaves the page, did not perform nsuiTouchesEnded

**Comment by comlog** [comment]
nsuiTouchesEnded does not work,anyone knows it? why and how to save this problem?

**Comment by liuxuan30** [comment]
under what scenario it does not work? Simply saying 'not working' does not help

**Comment by danielgindi** [comment]
No response?..

**Comment by comlog** [comment]
yes,No response.nsuiTouchesEnded does not work
