### ISSUE TITLE
Didn't show last Y Axis

### ISSUE THREAD

**Issue by jinthreek89** [danielgindi/Charts#1645]
Hi, guys.
I can't see last y axis. What is the problem. Please help me.
![image](https://cloud.githubusercontent.com/assets/5479567/19278657/ac8a103a-9010-11e6-89dc-e82bbfe96a7d.png)

**Comment by WYZKirk** [comment]
I have this problem too.The last yAxis didnot show on LineChartView.
![linecharts](https://cloud.githubusercontent.com/assets/17986384/19294389/a94fd550-905e-11e6-8ef2-1d9f16ebf484.jpg)

**Comment by jinthreek89** [comment]
@WYZKirk , Thanks for your comment.

**Comment by liuxuan30** [comment]
Chart 3.0 right?

**Comment by WYZKirk** [comment]
Yes

**Comment by jinthreek89** [comment]
@liuxuan30 , I am using Charts 2.2.5

**Comment by liuxuan30** [comment]
For 2.2.5, please refer ChartsDemo, it should be your setup problems.
For 3.0, it's a known issue #1323
