### ISSUE TITLE
HorizontalBarChartView text for xValues -- charts 3.0

### ISSUE THREAD

**Issue by caat91** [danielgindi/Charts#1646]
I am working with an horizontal bar chart, with version 2.2.5 my original code was: 

```
    var dataEntries: [BarChartDataEntry] = []

    for i in 0..<dataPoints.count {
        let dataEntry = BarChartDataEntry(value: values[i], xIndex: i)
        dataEntries.append(dataEntry)
    }

    let chartDataSet = BarChartDataSet(yVals: dataEntries, label: "Affected")

   var formatedResults = [String]()

    for i in 0..<dataPoints.count {

        let label = dataPoints[i].company! as String
        formatedResults.append(label)
    }

    //Coloring the bars and creating the labels
    var colors = [UIColor]()

    for i in 0..<dataPoints.count {

        if (i % 2 == 0){
            colors.append(Colors.blue)
        }else{
            colors.append(Colors.gray)
        }
    }

    chartDataSet.colors = colors

    // Adds the data to the chart
    let chartData = BarChartData(xVals: formatedResults, dataSet: chartDataSet)
    barChartView.data = chartData
```

But with the version 3.0 I can not create my BarChartData that way, so I do not know how to set the names I want as the xValues. 

I am getting just 0/2/4... as the text, always even numbers every other bar and I have no idea how to get it fixed.

My current code: 
        var dataEntries: [BarChartDataEntry] = []

```
    for i in 0..<dataPoints.count {

        let dataEntry = BarChartDataEntry(x : Double(i), y : values[i])
        dataEntries.append(dataEntry)
    }

    let chartDataSet = BarChartDataSet(values: dataEntries, label: "Affected")

    var formatedResults = [String]()

    for i in 0..<dataPoints.count {

        let label =  dataPoints[i].company! as String
        formatedResults.append(label)
    }

    //Coloring the bars and creating the labels
    var colors = [UIColor]()

    for i in 0..<dataPoints.count {

        if (i % 2 == 0){
            colors.append(Colors.blue)
        }else{
            colors.append(Colors.gray)
        }
    }

    chartDataSet.colors = colors
    chartDataSet.drawValuesEnabled = false // Hides the values on the bars

    // Adds the data to the chart
    let chartData = BarChartData(dataSet: chartDataSet)
    chartData.barWidth = 0.5

    barChartView.data = chartData
```

Current Result: 

<img width="311" alt="horizontalbarchartview" src="https://cloud.githubusercontent.com/assets/2414186/19293518/097b3a58-8ff3-11e6-863e-4053703b6fd4.png">

**Comment by liuxuan30** [comment]
In chart 3.0, it does not work any more as it used to be. The x axis is redesigned and works more like y axis. 

What I know for the moment is, you can try `labelCount` and enable `forceLabelsEnabled`, because by default how many x axis labels are displayed are calculated by `computeAxisValues()`. You can also take a look at it and override it with your desired behaviors, like display every label.

@danielgindi Is there any other convenient way to configure this? I don't see there is property that controls `inertval` but only `granularity` or `labelCount`

**Comment by caat91** [comment]
My original chart looked like this: 

<img width="311" alt="screen shot 2016-10-11 at 8 39 04 pm" src="https://cloud.githubusercontent.com/assets/2414186/19297338/0c965438-9012-11e6-98b9-1f08142ba78a.png">

Is it possible to get that look, those company text labels on the new version?

**Comment by kientux** [comment]
@caat91 To show those company text labels, you must use function `stringForXValue` of protocol `ChartXAxisValueFormatter`. But the problem here is that you will get Company 2, Company 4, Company 6... only because of auto-calculating axis labels feature. I will try what @liuxuan30 suggested and feedback later.

**Comment by caat91** [comment]
@kientux your suggestion did the trick for me regarding the text labels, I just extended de IAxisValueFormatter protocol and added the stringForXValue methods.

I am still trying to figure it out the number of labels shown as @liuxuan30  suggested but haven't had much luck.

**Comment by liuxuan30** [comment]
well you have to debug a little, I don't see this in ChartsDemo. Need more info why not centered..
Just use shorter text and maybe check ChartsDemo

**Comment by Paradolle** [comment]
I meet the same issue using Charts 3.0 (in VerticalBarChartView as well), could you teach me how to write the extension in IAxisValueFormatter and added the 'stringForXValue' please? Thanks a lot

**Comment by danielgindi** [comment]
Please see the demos. Another way is to just init a `DefaultAxisValueFormatter` with a block.
