### ISSUE TITLE
Use of '@import' when modules are disabled

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#1647]
When I change. m file for .mm    The project will be an error 

![54e73dd5-c360-4d30-aa1f-55ca5079f58e](https://cloud.githubusercontent.com/assets/8455023/19296065/819537b4-906b-11e6-97e4-2c95e000491a.png)

![077f67f2-9f8d-4658-ab05-4e06e6dea1a5](https://cloud.githubusercontent.com/assets/8455023/19296022/3b020fc0-906b-11e6-9fd2-b7d3fc13e543.png)

**Comment by githubkiven** [comment]
@danielgindi

**Comment by githubkiven** [comment]
Please help me thank you

**Comment by petester42** [comment]
That is because the `.mm` extension means it's objective-c++ which we do not support. It should maybe work if you use the other import syntax `#import <Charts/Charts.h>`

**Comment by githubkiven** [comment]
@petester42   Thank you very much
