### ISSUE TITLE
Updating the last Candlestick entry.

### ISSUE THREAD

**Issue by moon47usaco** [danielgindi/Charts#1649]
I see lots of issues and resolutions for realtime charts that use addEntry and notifyDataSetChanged and that is all fine and good.

What about updating the current last entry. Say I have a 30 minute bar with open,high,low, close.

If it is 10:15am I will be getting updated prices of that bar for the next 15 minutes and I do not want to add an entry until 10:30am when the new bar starts. What I want to do is check the current price that comes in, several times in a minute, and update the open,high,low, close of the 10:00am bar if necessary.

**Comment by moon47usaco** [comment]
So I was thinking that I could pop the last entry off then addEntry to add it back it with the new values then notifyDataSetChanged. Unless there is a better way than that?

**Comment by liuxuan30** [comment]
you just get whatever data you want and simply refresh the whole chart.
If you take a look at `draw()` method, it simply render everything
