### ISSUE TITLE
Realm and Charts 3.0 tutorial

### ISSUE THREAD

**Issue by petester42** [danielgindi/Charts#1651]
I found a pretty in depth tutorial using charts 3.0 and realm. Might help some people. Can be found [here](https://medium.com/@skoli/using-realm-and-charts-with-swift-3-in-ios-10-40c42e3838c0#.qg3ekbstw)

**Comment by Huang-Libo** [comment]
@petester42 I cannot open the url.

**Comment by petester42** [comment]
https://medium.com/@skoli/using-realm-and-charts-with-swift-3-in-ios-10-40c42e3838c0#.3ffn15yz0

**Comment by liuxuan30** [comment]
#1474
