### ISSUE TITLE
Setting centerAxisLabelsEnabled with a granularity set does not centre

### ISSUE THREAD

**Issue by nicholassmith** [danielgindi/Charts#1652]
If you have a LineChart and you set a granularity for the X axis using `setGranularity:` and then use `setCenterAxisLabelsEnabled:YES` then the X Axis labels will no longer be centred. Removing the `setCenterAxisLabelsEnabled:YES` allows the labels to be correctly centred.

**Comment by liuxuan30** [comment]
Time Line Chart in ChartsDemo did the samething but it works fine.
Need more info, and please check ChartsDemo or provide steps to reproduce.

**Comment by danielgindi** [comment]
No response?..
