### ISSUE TITLE
Request to solve a sort of bug

### ISSUE THREAD

**Issue by XiaoHanGe** [danielgindi/Charts#1653]
I use the charts library inside the LineChartView custom chart .For example, I want to show the past 30 days from the date of the data, X axis will last month's 27 days in the month after 12, the following chart:
![2016-10-13 9 37 47](https://cloud.githubusercontent.com/assets/14025157/19333497/ec8bb1d4-9128-11e6-891c-b912ba1fa755.png)

**Comment by liuxuan30** [comment]
try `axisMinimum = 1`, `axisMaximum = 30`, and set a proper `labelCount`

**Comment by XiaoHanGe** [comment]
Thanks！

**Comment by XiaoHanGe** [comment]
@liuxuan30 Thank you！

**Comment by XiaoHanGe** [comment]
@liuxuan30  Can you give an example to solve this trouble I tried a day can not be customized DefaultValueFormatter？

**Comment by liuxuan30** [comment]
check  ChartsDemo.
