### ISSUE TITLE
Left and right slide bar chart only half and remove background grid

### ISSUE THREAD

**Issue by AnChiChang** [danielgindi/Charts#1654]
I am new bar chart view user, and have two questions:
1. why my left slide and right side bar only half?
2. can I remove background grid from my BarChartView?

<img width="455" alt="2016-10-13 10 10 05" src="https://cloud.githubusercontent.com/assets/11910534/19334276/673adff0-912d-11e6-87d1-6e03e15d6b9c.png">

**Comment by liuxuan30** [comment]
search old issue https://github.com/danielgindi/Charts/issues/1446
try `fitBars`

**Comment by petester42** [comment]
I fell like this comes up a lot. Why not have `fitBars` enabled by default?

**Comment by liuxuan30** [comment]
Me too. However I even found a new issue here:
In ChartsDemo Bar chart, `fitBars` is false, and it does not get cut off but just fewer left and right empty space. Weird.
@danielgindi would you please check this?

@AnChiChang at which commit you find the issue? Able to reproduce with ChartsDemo?

**Comment by AnChiChang** [comment]
I had download iOS chart yesterday. However, I setup barChartView.fitBar = true at my callback function after load data from backend system, didn't work. After remove the code into viewDidLoad then work perfect. That's my situation.

**Comment by liuxuan30** [comment]
remember setup your chart properties before you call `chartView.data = data` or manually call `notifyDataSetChanged`

**Comment by AnChiChang** [comment]
sure, thanks for reminding.

**Comment by danielgindi** [comment]
I don't think this is about `fitBars`, but about axis padding. Since a bar on the x=0 is actually centered on the 0, and half of it is to the left of 0...
So we have the axis padding to come to our help. It is by default 0.5 on both sides for bar charts. So I guess he is not using the release version...
