### ISSUE TITLE
xAxis when zooming

### ISSUE THREAD

**Issue by phucnd0604** [danielgindi/Charts#1655]
how to disable auto generate label when zooming
eg my xAxis is 100,200,300,400,500 but when zoom  it auto generate to 110, 120, 130 etc but i dont want it, just 100, 200, 300 , 400 , 500

**Comment by liuxuan30** [comment]
then what is the meaning of zooming in and how can users know where they are?

**Comment by phucnd0604** [comment]
but i dont need to know where they are because when they zooming in for example my axisx is people count like : 1, 2, 3, 4, 5. Then they show 1.2, 1.4 people etc but i dont want it.

**Comment by liuxuan30** [comment]
set `granularity = 1` 
```swift
    /// The minimum interval between axis values.
    /// This can be used to avoid label duplicating when zooming in.
    ///
    /// **default**: 1.0
    open var granularity: Double
    {
        get
        {
            return _granularity
        }
        set
        {
            _granularity = newValue
            
            // set this to `true` if it was disabled, as it makes no sense to set this property with granularity disabled
            granularityEnabled = true
        }
    }
```

**Comment by phucnd0604** [comment]
but this still not show the correct label, eg my labels is 1, 2, 10, 20 , 23, 30 then if i set granularity = 2 or 1 it still display 1, 2, 3, 4, ... etc when zooming. i just want to show exactly the labels like version 2 before

**Comment by liuxuan30** [comment]
Chart 3.0 changed the way how x axis works, you have to follow the new implementation.

I don't understand your question as you change it in every comment, first 100,200,300,400,500 then 1.2, 1.4 and then 1, 2, 10, 20 , 23, 30. 

If you want to use custom x values, then you should implement your own IAxisValueFormatter protocol to display whatever you want.

**Comment by phucnd0604** [comment]
right, actually i have a array of values by timestamp, then i custom to show the date with human formatter. but the time interval is not equal for every timestamp so if i set the minimun is 1s or 10s it will show 0h00s, 0h10s, 020s 0h30s, 0h40s ... when zoom in
but the original timestamp is only  0h00s, 0h30s, 0h40s.

**Comment by liuxuan30** [comment]
yes because in Chart 2.x, it uses 'index based' for x axis, however in 3.0, x axis behaves like y axis.

**Comment by liuxuan30** [comment]
also, I would argue what is x axis - it is axis shows static interval and grids normally; you have non-equal intervals, which should not be a good way to display in terms of x axis; the chart will be not easy to read; you can show it as values, but not x axis labels.
