### ISSUE TITLE
Legends for multiple dataSets and multiple bar charts allignment

### ISSUE THREAD

**Issue by chennuruashok** [danielgindi/Charts#1657]
I want to assign separate colors for multiple legends and also one legend on left side of graph and another one is on right side. How it can be possible. Also the two bar charts need to interact like as in screenshots. Kindly someone help with known solution. Thanks in advance
![screen shot 2016-10-13 at 3 04 12 pm](https://cloud.githubusercontent.com/assets/8543618/19344224/f464ba4e-9156-11e6-801e-e4df65936e1a.png)
![screen shot 2016-10-13 at 3 04 55 pm](https://cloud.githubusercontent.com/assets/8543618/19344225/f4d03bca-9156-11e6-88d0-f518781ad2cc.png)

**Comment by liuxuan30** [comment]
Simply write your own legend, either based on ChartLegend or start from scratch.

**Comment by chennuruashok** [comment]
thanx for your reply
but am asking in iOS. Can u plz help me with piece of code. and also the second screen shot, collaborate two charts how it can be possible

**Comment by liuxuan30** [comment]
No idea what is `collaborate two charts` and I just see one chart.
For Legend, search `ChartLegend` as example
