### ISSUE TITLE
Showing all xAxis labels in a BarChart no matter the number of bars

### ISSUE THREAD

**Issue by clus90** [danielgindi/Charts#1661]
I see from the Demo project that as you increase the number of columns,  xAxis' labels group and are shown under some of the bars. For me, each bar represents a City, is there any way to stop the grouping and enabling the chart to show all labels under each bar?

Thanks in advance!

**Comment by liuxuan30** [comment]
if I understand correctly, you are mentioning some x axis values are hidden. This is true because they may overlap. First you have to consider will you meet overlap issue, then if you are sure, you can set `labelCount` to be your x values count
