### ISSUE TITLE
We need an old version for Xcode 7.0 

### ISSUE THREAD

**Issue by atalhassan** [danielgindi/Charts#1664]
We are working on a project, and when we use cocoapods to install charts, it gives us errors, because we are using an older version of Swift.

Here are some screenshots 
 
<img width="1440" alt="screen shot 2016-10-16 at 4 29 32 pm" src="https://cloud.githubusercontent.com/assets/13560238/19421787/bc70ee3c-93bd-11e6-8ce9-10c1c6ad73fd.png">

**Comment by rodericj** [comment]
What does the entry in your podfile look like?

**Comment by liuxuan30** [comment]
You should update your Xcode for sure. If you don't - you can only use old versions e.g. 2.2.5.

**Comment by atalhassan** [comment]
This is my Podfile entry:

platform :ios, '9.0'
use_frameworks!

target 'Sleep ^' do
    pod 'Charts'    
    pod 'SwiftDate', '<= 2.0'
    pod 'Groot'
end

**Comment by atalhassan** [comment]
Can I just pod install an older version of Charts that compiles with Xcode 7.0?

**Comment by liuxuan30** [comment]
I am no expert of pod, but I believe you can search on google. either point to an old release or an old commit. If pod does not support this, then you can't.

**Comment by rodericj** [comment]
Yeah follow the pattern you see for SwiftDate on believe. Give that a go and see what happens.

**Comment by atalhassan** [comment]
Yeah it worked, this is what I did:

    pod 'Charts', '<= 2.2' 

Thank you all
