### ISSUE TITLE
Charts : iOS 10, Xcode 8 - Embedded Framework  iTunes Store operation failed while uploading on App Store

### ISSUE THREAD

**Issue by neerajcsa** [danielgindi/Charts#1665]
@danielgindi I have added **Charts 2.3.0** framework as embedded library in my project.
Archive validation failed when i am trying to upload it using Xcode 8, it was working perfectly fine in Xcode 7.x

![screen shot 2016-10-17 at 10 30 07 am](https://cloud.githubusercontent.com/assets/7921708/19425989/76d3c810-9456-11e6-9c54-2d8a905fa10e.png)

**Comment by petester42** [comment]
It seems like you set your application's bundle id to the same thing as charts.

**Comment by neerajcsa** [comment]
@petester42 My application's bundle id is different than Charts.I just don't understand why it is asking to verify Charts bundle id which i have added as a embedded library, in Xcode 7 this issue did not occur.

**Comment by petester42** [comment]
This might be an submission bug. I'd check on the apple dev forums for more information. This has nothing to do with our library
