### ISSUE TITLE
Half a  bar the first one of chart

### ISSUE THREAD

**Issue by Sun-Hong** [danielgindi/Charts#1666]
It appeared the question,such as described below.<br>I tried to set up many properties, but doesn't work, what should I do?<br>
![bug](https://cloud.githubusercontent.com/assets/14048658/19432682/440f2bba-9490-11e6-92d4-36b5436f400e.png)

**Comment by Sun-Hong** [comment]
After set this:<br>
```Object-C
double start = 0.5;
    
    self.chartView.xAxis.axisMinimum = start;
    self.chartView.xAxis.axisMaximum = start + yVals.count;
    self.chartView.xAxis.centerAxisLabelsEnabled = NO;
```
The charts shows normal.

**Comment by liuxuan30** [comment]
try `fitBars`
