### ISSUE TITLE
Charts.frameworkiOS did not show up

### ISSUE THREAD

**Issue by JunDang** [danielgindi/Charts#1667]
Hello,
    I am using XCode 8.0 and Swift 3. I downloaded the Charts.xcodeproj from the master branch. Then dragged the Charts.xcodeproj file in the XCode interface. When I clicked on the "Embedded Binary" section, only Charts.frameworkmacOS showed up. And I want to add the framework for iOS. How should I do that?

    I used CocoaPods to install the Charts before, however, it is said Charts 3.0 is not yet released to CocoaPods. I am wondering when it could be released?

    Thanks very much!
![screen shot 2016-10-17 at 9 55 40 am](https://cloud.githubusercontent.com/assets/8404682/19443175/e48c9708-9459-11e6-8831-94c1c7494441.png)

**Comment by liuxuan30** [comment]
it's the same since Xcode 8, just use Charts.
