### ISSUE TITLE
can I fix number of overlapping this problem？

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1670]
![image](https://cloud.githubusercontent.com/assets/20593532/19460557/47ed2fdc-950f-11e6-8a2a-c37b23a5f3a0.png)
Due to the overlapping digital,i can't see another number.
![image](https://cloud.githubusercontent.com/assets/20593532/19460572/7bea4770-950f-11e6-8fc8-04a5ecd05f37.png)
I don't want to figure in the circle.

**Comment by liuxuan30** [comment]
well, as you can see it happens for sure when your circle and value are at the same location. Either you not show values change the value text to right/left, or you write a dedicated method to avoid such situation.

**Comment by yushan023** [comment]
How can I change value text to right/left? Have this property?

**Comment by liuxuan30** [comment]
No, you have to override it.
