### ISSUE TITLE
In IOS 10 Xcode 8,I got some issues

### ISSUE THREAD

**Issue by svsharsha** [danielgindi/Charts#1673]
When converting my code code Swift 2.3 its OK.
But in swift 3.0 Its not working got many a issues.

So when could we expect next version of charts.

**Comment by PanMluvci** [comment]
![snimek obrazovky 2016-10-18 v 12 35 39](https://cloud.githubusercontent.com/assets/6050127/19474344/74db8cee-952f-11e6-9e8f-99759c872aa9.png)

**Comment by natanrolnik** [comment]
@svsharsha @PanMluvci you should point your Podfile to use master (not released yet):

`pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'`

**Comment by danielgindi** [comment]
Do not convert, we already have a Swift 3.0 version. Please take a peek at the README or at issues before posting.
