### ISSUE TITLE
How do I Use IValueFormatter to format XAxis labels in swift?

### ISSUE THREAD

**Issue by Aftab301286** [danielgindi/Charts#1676]

**Comment by Aftab301286** [comment]
I have 2 charts using valueformatters IAxisValueFormatter and IValueFormatter. Please tell me how I use these both formatters for the different charts in swift in the same class.

**Comment by Aftab301286** [comment]
I am trying to use single formatter but since I have 2 charts in the same class the labels are getting overridden for the chart that is rendering data lastly. Hence, I am trying to use 2 formatters for the 2 charts but I am not getting the right code to use the same.

**Comment by danielgindi** [comment]
Either create separate formatter classes or use initWithBlock

**Comment by RobMans426** [comment]
Hi, Daniel
How are you?

Now I am using PieChart for my project.
Then I have one issue.

I have this error "Can not convert value of type NumberFormatter to expected argument type IValueFormatter?"

How can I solve this?
Here is snapshots of my code.
` 
 let currencyStyle = NumberFormatter()

 self.currencyStyle.formatterBehavior = NumberFormatter.Behavior.behavior10_4
 self.currencyStyle.numberStyle = NumberFormatter.Style.currency
 self.currencyStyle.maximumFractionDigits = 0

....
 let data = PieChartData(dataSets: iDataSet)
 data.setValueFormatter(self.currencyStyle)

`

Please help me.

**Comment by Mukesh-kumar-sharma** [comment]
Please provide a correct solution before closing the tickets. I am facing huge problem while migrating from 2.3 to 3.0.1.

**Comment by 9you** [comment]
@Mukesh-kumar-sharma: May this help
```
    extension NumberFormatter: IValueFormatter {

        public func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String {
            return string(from: NSNumber(value: value)) ?? ""
        }
    }
```
