### ISSUE TITLE
ChartLimitLine background color

### ISSUE THREAD

**Issue by MetallicCornFlakes** [danielgindi/Charts#1678]
Is there any way to add a background view or color to a ChartLimitLine label? I need to get a background color behind my label for the average because the chart can go up and down behind the label and it can become very hard to see.

Trying to achieve something like this: 
<img width="198" alt="screen shot 2016-10-18 at 11 35 06 am" src="https://cloud.githubusercontent.com/assets/1590887/19491304/5baed1e8-9527-11e6-8af2-860786a84bb8.png">

**Comment by MetallicCornFlakes** [comment]
never mind I figured out the correct classes to subclass

**Comment by vincent-peng** [comment]
@ryangullotti 
Hi there, 
I ran into the exact situation. 
Do you mind if you can share how you achieve this please?
Thanks!
