### ISSUE TITLE
Setting a pieChartDataSet on 3.0

### ISSUE THREAD

**Issue by giuseppe4** [danielgindi/Charts#1681]
Hello,
I read issue #1474 about migration to 3.0 and other issues referred to it but I can't understand how to set data in PieChart on Swift 3.0 and Chart 3.0.

Could please anyone give me an example?

Thank you very much

**Comment by serefbulbul** [comment]
Hello,

This codes should work for you

`var values: [PieChartDataEntry] = []

let dataEntry = PieChartDataEntry(value: 1.0, label: "Bla bla")         
values.append(dataEntry)

let pieChartDataSet = PieChartDataSet(values: values, label: "Bla bla")
pieChartDataSet.sliceSpace = 1
pieChartDataSet.colors = [UIColor.red, UIColor.yellow, UIColor.blue]

self.pieChart.data = PieChartData(dataSet: pieChartDataSet)`

**Comment by giuseppe4** [comment]
Thank you very much! It works great! I didn't notice I was using 
`PieChartData(dataSet**s**: pieChartDataSet)` 

Thank you!

**Comment by Farzana2014** [comment]
Yes. Its work great. But i am facing problem to get the selected dataset index. 
i have two entry 

```
        let dataEntry = PieChartDataEntry(value: 1.0, label: "Bla bla")
        values.append(dataEntry)
        
        let dataEntry2 = PieChartDataEntry(value: 2.0, label: "Bla")
        values.append(dataEntry2)
```
I am using 
```

      func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        print(highlight.dataSetIndex)
    }
```
Always getting 0 as selected value. Why? How i can get the right selected index?
