### ISSUE TITLE
Pod install: SSL: certificate verification failed

### ISSUE THREAD

**Issue by maniacs-engineerica** [danielgindi/Charts#1682]
I can't install the library via CocoaPods, I am getting:

[!] /usr/bin/git clone https://github.com/danielgindi/Charts.git /var/folders/sr/4rckxqy11nl6n2jmt_00f3vr0000gn/T/d20161019-2029-d3k0of --single-branch --depth 1 --branch v2.3.0

Cloning into '/var/folders/sr/4rckxqy11nl6n2jmt_00f3vr0000gn/T/d20161019-2029-d3k0of'...
fatal: unable to access 'https://github.com/danielgindi/Charts.git/': SSL: certificate verification failed (result: 5)

What happen?
Thanks.

**Comment by petester42** [comment]
I would suggest using cocoapods 1.1 and see if it still happens. There was issue filed for cocoapods [here](https://github.com/CocoaPods/CocoaPods/issues/4778). This is not an issue with the library.

**Comment by RankoR** [comment]
Same for me in CocoaPods desktop app:
```
[!] Error installing YandexMobileMetrica
[!] /usr/bin/curl -f -L -o /var/folders/k6/vzwjw_xj28qdtsw9b6qk8vjw0000gn/T/d20170110-7601-1vi7avo/file.zip https://storage.mds.yandex.net/get-appmetrica-mobile-sdk/48248/YandexMobileMetrica-2.7.0-ios-7058b11a-d987-4519-8c64-028c75b67eab.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (51) SSL: certificate verification failed (result: 5)
```
That happens for one pod only, others are OK. BTW, if I execute this curl command manually, it downloads the file without errors.
I'm using version 1.1.1.

**Comment by binovsky** [comment]
Is there any solution for this?

**Comment by aelam** [comment]
I think it's about network, nothing wrong with CocoaPods or git
try with VPN 
or try my mirror http://git.oschina.net/lunwang/Charts

**Comment by petester42** [comment]
I would get help from cocoapods if anything. This is not an issue with this library

**Comment by liuxuan30** [comment]
check your proxy, VPN, that's usually where the cert messed up. If you are clean, then use another version of pod.. Or use some switch to turn off the check.

**Comment by binovsky** [comment]
This issue is definitely CocoaPods app related only, if you install CocoaPods with homebrew error won't occur.

**Comment by tizzyapunkt** [comment]
I can confirm what @binovsky said. Using the pod CLI installed via Homebrew does not throw the SSL error.
