### ISSUE TITLE
How to move data labels outside the chart.

### ISSUE THREAD

**Issue by hb2708** [danielgindi/Charts#1687]
@danielgindi 
I want the data labels to be outside the chart like below.

Please Guide 
![screen shot 2016-10-20 at 2 53 14 pm](https://cloud.githubusercontent.com/assets/13498448/19554317/a5b765c0-96d5-11e6-8b7c-9a18c8edc4ec.png)

**Comment by hb2708** [comment]
@danielgindi @petester42 I did succeeded in the above goal by doing some tweaks in library but i am still not able to find the correct way as changing the library is not a ideal way please guide

**Comment by liuxuan30** [comment]
just override them with your needs. Some customizations are needed if it does met your requirement.

**Comment by hb2708** [comment]
can't it be like different public setting in library without setting it by changing the code in library as if i update it to newer version i again need to do the change in new code of library

**Comment by liuxuan30** [comment]
Yes, that's true. because it's your customizations; however you could make a pull request for features you think it's helpful and get merged and you won't need to change again;

if you can't make it public, then what you should do is to subclass and override in your sub class. That's why we use OOP

**Comment by hb2708** [comment]
Is it ok if i create a pull request to master branch

**Comment by hb2708** [comment]
Hello i have created the pull request by updating my solution #1712 
let me know if any improvements required

**Comment by liuxuan30** [comment]
Thanks! Just wait and keep tuned. The review process will take some time for code styles or other things.
