### ISSUE TITLE
[LineChartView] Wrong position Highlight and xAxis

### ISSUE THREAD

**Issue by nthegedus** [danielgindi/Charts#1689]
I have a **LineChartView** with a few data, just three dates on xAxis and three values on yAxis. But the problem is that when I touch some place on the graph the Highlight appear, but it's not on the right position as the xAxis.

I tried with the DemoChart, and the same happened. I don't know if it's a bug, but in my opinion the highlight is doesn't point the right information.

Another thing is that the last value doesn't appear, even if I zoom it. Check out the prints:

Demo Chart, using the same data as my app
![demochart](https://cloud.githubusercontent.com/assets/1063383/19562629/c6b0df50-96bb-11e6-8a12-e0b1f7021a87.png)
My app
![myapp](https://cloud.githubusercontent.com/assets/1063383/19562728/28f924ce-96bc-11e6-93f1-4662e7dd27a8.png)

Maybe I could be wrong, but I think that before I changed to chart 3.0 it was working fine.

**Comment by liuxuan30** [comment]
Chart 3.0 has redesigned x axis, more like y axis. For lat value, try official 3.0.0 release

**Comment by nthegedus** [comment]
@liuxuan30 in really I'm using 3.0.0 I downloaded it again, and it still equals.

**Comment by liuxuan30** [comment]
I don't know what 'equals' means. Later release fixed the missing last label.
