### ISSUE TITLE
CombinedChart with grouped bars support

### ISSUE THREAD

**Issue by trungnguyen1791** [danielgindi/Charts#169]
Currently i'm using CombinedChart to generate lines and bars together. 
With multi set of lines, it work fine. But multi set of bars, it doesn't.
For example:
-  I have Xvals array with 6 items, and i want to show two datasets of bar type. So it must render two individual bars for each Xvals value. 
- Unfortunately it only render 3 couples of them ( the first three items in XVals)
![screen shot 2015-06-22 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/3167319/8280050/fd24fd64-1903-11e5-927f-3e739716bb42.png)

Can someone have same problems? How i can solve this? 
Thanks.

**Comment by danielgindi** [comment]
This is a known bug: https://github.com/PhilJay/MPAndroidChart/issues/449
It will hopefully be solved soon

**Comment by danielgindi** [comment]
Solved in Charts 3.0 (v3 branch), as you tell the data to calculate the groups, and they render as standard bars - so they can go well with other data types.
