### ISSUE TITLE
Charts 3.0 Carthage update issue

### ISSUE THREAD

**Issue by Sunitadaffodil** [danielgindi/Charts#1690]
I have Xcode 8.0 / Swift 3.0. Integrating charts first time in the running project using Carthage. 
Set the Cartfile :
 **github "danielgindi/Charts" ~> 3.0.0**

On Running the Carthage getting the Build Failed error:

*** Building scheme "Charts" in Charts.xcodeproj
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project “projectPath/Carthage/Checkouts/Charts/Charts/Charts.xcodeproj" -scheme Charts -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

**Error  debug :**
Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Noticed that even after adding the version to 3.00 , check out version is incorrect**
From Logs:
*** Checking out Charts at "v2.1.4a"

Please suggest.

**Comment by petester42** [comment]
Are you running `carhage update` after changing the version? And what version of Carthage are you using?

**Comment by Sunitadaffodil** [comment]
My Carthage version is 0.18.
And yes after setting the Cartfile for charts. I am running the `carthage update`

**Comment by PhilJay** [comment]
I just tried it myself and I am getting the exact same issue as described above. I'll label it as a bug.
@petester42 - @danielgindi told me you are the expert regarding Carthage, any idea what could cause this issue?

**Comment by petester42** [comment]
I don't know what could be causing the issue but ill look into it

**Comment by petester42** [comment]
Works fine for me. I'm using Carthage 0.18.1 and Xcode 8. Could you post your Cartfile and Cartfile.resolved?

**Comment by PhilJay** [comment]
I am also on XCode 8, Carthage 0.18.1

This is my `Cartfile`:
```
github "WenchaoD/FSCalendar"
github "skywinder/ActionSheetPicker-3.0"
github "ReactiveX/RxSwift" "3.0.0-beta.1"
github "dzenbot/DZNEmptyDataSet"
github "MortimerGoro/MGSwipeTableCell"
github "matthewpalmer/Locksmith"
github "onevcat/Kingfisher" ~> 3.0
github "BranchMetrics/iOS-Deferred-Deep-Linking-SDK"
github "danielgindi/Charts" ~> 3.0.0
```

This is my `Cartfile.resolved`:
```
github "skywinder/ActionSheetPicker-3.0" "2.2.0"
github "dzenbot/DZNEmptyDataSet" "v1.8.1"
github "WenchaoD/FSCalendar" "2.4.0"
github "onevcat/Kingfisher" "3.1.4"
github "matthewpalmer/Locksmith" "3.0.0"
github "MortimerGoro/MGSwipeTableCell" "1.5.6"
github "ReactiveX/RxSwift" "3.0.0-beta.1"
github "BranchMetrics/iOS-Deferred-Deep-Linking-SDK" "0.12.12"
github "realm/realm-cocoa" "v1.1.0"
github "danielgindi/Charts" "v3.0.0"
```

When performing `carthage update`, this is the error I am getting:
```
... other
*** Fetching Charts
... other
*** Checking out Charts at "v3.0.0"
*** xcodebuild output can be found in /var/folders/vf/d3_3_z712z1g6nyhwbbw0hl80000gn/T/carthage-xcodebuild.xPbwWp.log
... other
*** Building scheme "ChartsRealm" in Charts.xcodeproj
*** Building scheme "Charts" in Charts.xcodeproj
*** Building scheme "Charts-iOS" in Charts.xcodeproj
** CLEAN FAILED **

The following build commands failed:
 Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
 Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Path/To/My/Project/Carthage/Checkouts/Charts/Charts/Charts.xcodeproj -scheme Charts-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
 Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
 Check dependencies
(1 failure)
```

**Comment by petester42** [comment]
Im gonna suggest you delete your Carthage checkout folder. "Charts-iOS" scheme doesn't exist anymore so something is wrong with the checked out version.

**Comment by petester42** [comment]
Just tried your Cartfile and it works just fine. If anyone still has issues with this try deleting your Carthage folder running the `carthage update` command again.

**Comment by PhilJay** [comment]
Feeling silly now, deleting the `Carthage/Checkouts` folder did the trick. Thanks!

**Comment by krystiansliwa** [comment]
I have the same issue. When I use `github "danielgindi/Charts" ~> 3.0.1` I have error when building. 
It works when I specify tag like `github "danielgindi/Charts" "v3.0.1"` or commit.

For me Carthage ver: 0.18.1
