### ISSUE TITLE
Setting circleHoleColor to clear causes artifact

### ISSUE THREAD

**Issue by nicholassmith** [danielgindi/Charts#1691]
If you set the circle hole colour to be `[UIColor clearColor]` then the circle is drawn with an artifact as shown. 
![screen shot 2016-10-20 at 20 28 39](https://cloud.githubusercontent.com/assets/334006/19574874/0a062e20-9704-11e6-92bd-b06f209d0af8.png)

**Comment by liuxuan30** [comment]
can you provide full color data?

**Comment by nicholassmith** [comment]
Sure:
`[self.highlightedSet setHighlightColor:[UIColor clearColor]];
    self.highlightedSet.drawValuesEnabled = NO;
    self.highlightedSet.drawCirclesEnabled = YES;
    self.highlightedSet.circleHoleColor = [UIColor clearColor];
    self.highlightedSet.circleColors = [NSArray arrayWithObject:[UIColor whiteColor]];
    self.highlightedSet.circleHoleRadius = 7.5f;
    self.highlightedSet.circleRadius = 8.0f;
    self.highlightedSet.colors = [NSArray arrayWithObject:[UIColor whiteColor]];
`

There's another data set below it which is drawn with a plain white dot.

**Comment by liuxuan30** [comment]
I was able to reproduce in ChartsDemo with your code.

**Comment by nicholassmith** [comment]
I'm trying to avoid updating to a fresh version this week, can I just apply that change to my local copy of the Swift files?

**Comment by liuxuan30** [comment]
you can take my code if you can edit the code in your project.
