### ISSUE TITLE
Can I have two different Yaxis scale on combined chart

### ISSUE THREAD

**Issue by jrkingray** [danielgindi/Charts#1694]
Hi there, I have created a combined chart with line/bar.

![image](https://cloud.githubusercontent.com/assets/6878062/19616319/d4560f22-97c4-11e6-9be1-d33ff53c3b6e.png)

now, bar chart and line chart using same y scale as left axis(0-5).

Can I have line chart remain with it but have bar chart stick to right axis scale(0-10)?

linechart yaxis scale from(0-5), barchart yaxis scale from(0-10).

**Comment by liuxuan30** [comment]
try set `axisDependency`
