### ISSUE TITLE
What happened to X-Axis labels in 3.0?

### ISSUE THREAD

**Issue by ekampf** [danielgindi/Charts#1696]
Im trying to convert a stacked bar chart to Charts 3.0.
I'm creating a data entries as:
`BarChartDataEntry(x: Double(x), yValues: values, label: xlabels[x])`

But where is the label used?  How do I configure the chart do draw said label on the x-axis instead of the value?
`BarChartData` used to have an `xVals` property which is now gone.

**Comment by danielgindi** [comment]
You supply a formatter for the chart to know how to format your values.

Please read the migration notes (Under "Releases"). You could also see the demos.

Here: https://github.com/danielgindi/Charts/blob/master/ChartsDemo/Classes/Demos/BarChartViewController.m you can see different usages of axis formatters. The default formatter also accepts a simple `block` for formatting.

**Comment by ekampf** [comment]
@danielgindi  So what is the label value for?
My problem with formatted is that they only seem to get the axis value (Double) without context.
I can set a data object to my chart data entries, why not send it to the formatter too?

**Comment by ekampf** [comment]
So what is the label value for?
My problem with formatted is that they only seem to get the axis value
(Double) without context.
I can set a data object to my chart data entries, why not send it to the
formatter too?

**Comment by liuxuan30** [comment]
check ChartsDemo for different styles. label value and label text can be different
