### ISSUE TITLE
[Question] Multiple lines with different units

### ISSUE THREAD

**Issue by WoodySlum** [danielgindi/Charts#1698]
Hi, I want to draw multiple lines, but with several units (°C, %, hPa, minutes, ...).
Actually, all lines are on the same scale, which means that lines with low data source (for example voltage which is 0 ... 5 values) will appear as a straight line because another line has values between 900 ... 1000.

How can I set units for each lines ? Am I limited to 2 (Left Axis / Right Axis) ?

Screen sample : green line are too flat
![Example](http://img15.hostingpics.net/pics/922228SimulatorScreenShot22oct2016a204445.png)

**Comment by danielgindi** [comment]
"units" are just synthetic. In the end it's all numbers... The library accepts `Double`s for data.
As for axis labels - yes we are currently limited to 2 axes, left and right. I hope for 3.1 that we will eliminate this limitation as there's more and more requirement for this.

**Comment by danielgindi** [comment]
Updates on this will be posted there: https://github.com/danielgindi/Charts/issues/555
