### ISSUE TITLE
I update the pod to 3.0.0 but Xcode still wants to convert to Swift 3

### ISSUE THREAD

**Issue by portfort** [danielgindi/Charts#1699]
I do a pod update before opening a Swift 2 project in Xcode and pod update says

> Using Charts (3.0.0)

but when I open the project in Xcode it's still offering to convert Charts.framework (and when it does there's around 2600 issues next to it). I know I'm doing something wrong but I can't even begin to figure out what. I just want to update my app.

**Comment by danielgindi** [comment]
@petester42 is it possible that Pods think of Charts as Swift 2 and messes up the project configuration when fetching?

**Comment by petester42** [comment]
No. The problem is probably in the user's project. They have to make sure the "Use Legacy Swift" setting is "No" before installing any pods and in addition they need to be using cocoapods 1.1 with Xcode 8.

**Comment by petester42** [comment]
Yup just tried it and it works just fine. Make sure the "Use Legacy Swift" build setting is set to "No", make sure the cocoapods specs are up to date by using `pod repo update`, and then run `pod update`. And of course use cocoapods 1.1.

**Comment by portfort** [comment]
No, just couldn't get it working. I went back to Xcode 7.3 and old versions of everything. Maybe in a few months there will be some useful guides to migrating.
