### ISSUE TITLE
Can i use 2.2.5 version with Swift3

### ISSUE THREAD

**Issue by mecid** [danielgindi/Charts#1700]
How can i use 2.2.5 version with Swift3?

**Comment by danielgindi** [comment]
You might be able to - but the conversion from Swift 2 to 3 is tedious, and we do not intend to do so.
Please consider moving to Charts 3.0 - as it not only written in Swift 3.0, but it has also great new features and many bug fixes.

**Comment by mecid** [comment]
@danielgindi i dont like changes in 3.0 version and removing xVals.
Are you removed chats2.2.5-Swift3 branch?

**Comment by mecid** [comment]
@danielgindi maybe you can give me some answers on my questions before close the issue?

**Comment by petester42** [comment]
X values have not gone away. If you read the release notes of v3.0 you can see the migration. v2.3 of charts supports swift 2.3 and is the same interface as 2.2.5. Swift 3 will only be supported by charts v3 and we deleted the branches since we are no longer supporting them. They were temporary

**Comment by mecid** [comment]
@petester42 thanks for your response.
But this is wrong way, users must have the opportunity to select version.
I need to fix minor bug, but now cocoapods cant load the branch and i need to apply massive changes to my code base.

**Comment by petester42** [comment]
Users can select a version. Charts 2.3 supports swift 2.3. Charts 3.0 supports swift 3.0. 

You were using an unrealeased version of our library. If that affects your code base that sucks but that's sometimes what happens when you try out the bleeding edge. We can't be held responsible for something we said we wouldn't support. 

You are already converting your code to swift 3 which is a elaborate process. Why not also update to charts 3 since you are essentially refactoring your application anyways.

**Comment by mecid** [comment]
@petester42 i am uploaded app before iOS10 release. Now i fixed some bug, but i need to migrate to charts3 before release fix and this is ugly.

**Comment by petester42** [comment]
We are doing this on our own time. For us it didn't make sense for us to support both swift versions due to time constraints.

**Comment by liuxuan30** [comment]
@petester42 there used to be a branch for this, but it's gone..

**Comment by petester42** [comment]
Yes. I deleted it once 3.0 became final. Since we have no plans to support it we shouldn't keep a branch around since people will us it and ask for bug fixes and such for that branch. Just like this issue.

**Comment by liuxuan30** [comment]
ok, I see. 
@mecid maybe take swift 2.3 for iOS 10 first.. and then swift 3.0. It's not worthy to convert for swift 3.0, too many changes.

**Comment by mecid** [comment]
@liuxuan30 my app released with swift3...

**Comment by liuxuan30** [comment]
I checked my repo - https://github.com/liuxuan30/Charts/tree/Swift-3.0, it seems a Chart 2.2.5 + Swift 3.0 version.

**Comment by mecid** [comment]
@liuxuan30 thanks ;)

**Comment by L-Jovi** [comment]
@liuxuan30   thanks for your Swift-3.0 branch !

**Comment by liuxuan30** [comment]
@L-Jovi migrate to 3.0, it is pain but also more flexible!
