### ISSUE TITLE
X-Axis and Y-Axis is not shown in swift 3

### ISSUE THREAD

**Issue by saied685** [danielgindi/Charts#1701]
in swift 3 (xcode 8)
these lines of code is not work:

`let dataEntry = BarChartDataEntry(value: values[i], xIndex: i) `

and

```
let chartDataSet = BarChartDataSet(yVals: dataEntries, label: "Units Sold")
let chartData = BarChartData(xVals: months, dataSet: chartDataSet)
```

please help me
this makes to chart is not work properly
yVals and xVals and xIndex are unknown

![screen shot 2016-10-23 at 17 23 07](https://cloud.githubusercontent.com/assets/22411655/19626813/bdfad668-9945-11e6-9ad7-4e1ff7c49687.png)
[BarChartViewController.swift.zip](https://github.com/danielgindi/Charts/files/546377/BarChartViewController.swift.zip)

**Comment by saied685** [comment]
thanks

**Comment by Bigscaltest** [comment]
@saied685  Have you got any solution for this issue?
 If yes then please give me solution.
I have same issue for BarChart in swift 3.

Thanks

**Comment by liuxuan30** [comment]
please take a look at the func. Swift 3 changed a lot about naming, so it might changes.

**Comment by saied685** [comment]
Bigscaltest i have a solution ..stay in touch...i send this soluton ater some day...good luck

**Comment by saied685** [comment]
I found a solution...stay in touch...
Connect with me by this gmail
I send this solution after some day
On 25 Oct 2016 14:28, Bigscaltest <notifications@github.com> wrote:@saied685  Have you got any solution for this issue?
 If yes then please give me solution.
I have same issue for BarChart in swift 3.

Thanks

**Comment by saied685** [comment]
go to this link:
https://github.com/i-schuetz/SwiftCharts
