### ISSUE TITLE
Excuse me, BarChartData the " initWithXVals:(NSArray *data) dataSets:(NSArray *data)"  in Swift 3.0 V  "XVals"  is what method is the？I can't find the way，Help me。

### ISSUE THREAD

**Issue by zeng4250538** [danielgindi/Charts#1704]
Excuse me,
 BarChartData the "initWithXVals:(NSArray *data) dataSets:(NSArray *data)"  in Swift 3.0 V  "XVals"  is what method is the？I can't find the way，Help me。

Thank ！

**Comment by liuxuan30** [comment]
Just take a look at the source code.. Chart 3.0 seems removed it.

**Comment by petester42** [comment]
You now set the x value on the DataEntry which can be seen in here example [here](https://github.com/danielgindi/Charts/blob/master/ChartsDemo-OSX/ChartsDemo-OSX/Demos/BarDemoViewController.swift)
