### ISSUE TITLE
Conflict: Charts's Range conflict with Apple NSRange(Swift 3: Range). It makes me can not use the Apple's Range

### ISSUE THREAD

**Issue by c-xiaoqiang** [danielgindi/Charts#1705]

**Comment by liuxuan30** [comment]
Need more info. Please give details.

**Comment by MrMage** [comment]
I can confirm that Charts.Range obscures the Swift.Range type in files that have the Charts module imported. Not sure if this should be changed, though.

As a workaround, you should be able to use Swift.Range (or Foundation.NSRange, if that's really what you need).

**Comment by petester42** [comment]
That's the point of modules. You can specify the module if the type is ambiguous.
