### ISSUE TITLE
[BarChartDataEntry] axis to accept NSString

### ISSUE THREAD

**Issue by keithyeohh** [danielgindi/Charts#1706]
NSMutableArray *axisVals    = [[NSMutableArray alloc] init];
    
    // xAxisVals = an array of text. (e.g. @["Jan", "Feb", "Mar"])
    NSArray *xAxisVals      = [[NSArray alloc] initWithArray:records[@"xAxis"]];
    NSArray *yAxisVals      = [[NSArray alloc] initWithArray:records[@"yAxis"]];
    
    for( int i = 0; i < xAxisVals.count; i++ ){
        if( ([yAxisVals[i] doubleValue] - [yAxisVals[i] integerValue]) != 0 )
            [axisVals addObject:[[BarChartDataEntry alloc] initWithX:xAxisVals[i]
                                                                   y:[yAxisVals[i] integerValue]]];
        else
            [axisVals addObject:[[BarChartDataEntry alloc] initWithX:xAxisVals[i]
                                                                   y:[yAxisVals[i] doubleValue]]];
    }

After upgraded to v3.0.0, notice that the method name **initWithX:y:** only accepting double value. Not sure how can I apply NSString on it? I am using Objective-C for this.

**Comment by liuxuan30** [comment]
Chart 3.0 redesigned x axis. Now it behaves like y axis. Check  the release notes and udpate your code.

**Comment by keithyeohh** [comment]
@liuxuan30 appreciate for your reply. May I know is there any workaround to make the X axis to accept string?

**Comment by Kerwin1992** [comment]
I also have this problem.How do you deal with it?  @keithyeohh  @liuxuan30

**Comment by liuxuan30** [comment]
for Chart 3.0, you can't. You could conform to `IChartAxisValueFormatter` to format your axis values. Take a look at ChartsDemo - Time Line Chart

**Comment by keithyeohh** [comment]
@liuxuan30 noted with thanks!
