### ISSUE TITLE
Multiple bar Chart Xvalues Doesn't come centre to the grouped bars...

### ISSUE THREAD

**Issue by jk9958** [danielgindi/Charts#1707]
I tried the multiple barchart. There the X values doesn't get under the exact centre of the bars for that x value. Please help.

**Comment by liuxuan30** [comment]
try `xAxis.centerAxisLabelsEnabled = YES`

**Comment by jk9958** [comment]
Forgive me as I did not explain the issue clearly. 
![simulator screen shot 27-oct-2016 10 37 11 am](https://cloud.githubusercontent.com/assets/3157166/19755257/139e15b4-9c32-11e6-8529-54338dbbc08c.png)


In the above screenshot I have 6 bars (6 companies perfomance) in  a group. You can see that the year label on the bottom axis is not at the centre of the group. below is the calculation made.


        let grpSpace = 0.2
        let barSpace = 0.12
        let barWidth = 0.05

        let groupWidth = data.groupWidth(groupSpace: Double(grpSpace), barSpace: Double(barSpace))
        chartView.xAxis.axisMaximum =  Double(startYear) + (groupWidth * Double(12))
 //****** I have total of 12 groups******

        data.groupBars(fromX: Double(startYear), groupSpace: Double(grpSpace), barSpace: Double(barSpace))

**Comment by liuxuan30** [comment]
check out ChartsDemo - multiple bar chart for usage
