### ISSUE TITLE
Exception upon calling [ChartDataEntry initWithX:y:] via ObjC + Charts using Pods as Framework

### ISSUE THREAD

**Issue by SteeveBlack** [danielgindi/Charts#1708]
Using Charts 3.0 cocoa pod in an Objective-C project (pod as framework).

Podfile:

`source 'https://github.com/CocoaPods/Specs.git'`
`use_frameworks!`
`platform :ios, '8.1'`

`target "my_super_target" do`
`  pod 'Charts', '~> 3.0’`
`end`

When calling `[[ChartDataEntry alloc] initWithX:xValue y:yValue]]` (`xValue` and `yValue` are `double` types) the following exception is thrown:

`
-[Charts.ChartDataEntry initWithX:y:]: unrecognized selector sent to instance 0x7fb081ffb4b0
warning: Swift error in module Charts.
Debug info from this module will be unavailable in the debugger.
`

Checking the generated header in the framework, the selector is clearly defined:
`- (nonnull instancetype)initWithX:(double)x y:(double)y OBJC_DESIGNATED_INITIALIZER;`

Xcode version `8.0 (8A218a)` Reproduced always.

**Comment by danielgindi** [comment]
Try a Clean & Build...

**Comment by SteeveBlack** [comment]
Same issue after clean & rebuild.

**Comment by SteeveBlack** [comment]
Fixed by updating the Pod file, from `platform :ios, '8.1'` to `platform :ios, '10'`.
