### ISSUE TITLE
how to port calls to getEntriesAtIndex

### ISSUE THREAD

**Issue by rlimberger** [danielgindi/Charts#1709]
I am porting a project to 3.0 that made calls to getEntriesAtIndex on a line chart. what is the new way to do this in 3.0? looking at the BarLineChartViewBas i see getEntryByTouchPoint, which returns an entry, but no equivalent API that works with indexes. 

Thank you.

**Comment by liuxuan30** [comment]
:( do you remember what `getEntriesAtIndex` is for? I don't have 2.x version on my hand right now.

**Comment by danielgindi** [comment]
There are no indexes anymore, there are values. You can call `entriesForXValue`...
