### ISSUE TITLE
PieChart, label is a little of values ,labels is overlap

### ISSUE THREAD

**Issue by toywang** [danielgindi/Charts#1710]
<img width="311" alt="2016-10-25 10 51 57" src="https://cloud.githubusercontent.com/assets/11829956/19671419/2d30ea2a-9aa1-11e6-8098-8da7a74b168a.png">

**Comment by liuxuan30** [comment]
can you just hide those small numbers?

**Comment by toywang** [comment]
@liuxuan30  I can`t how resolve this problem, you can #944

**Comment by liuxuan30** [comment]
that's not merged yet..

**Comment by toywang** [comment]
嗯，对，你自己按照他写的写进charts的源码里面就行了，我试过了

**Comment by liuxuan30** [comment]
dup to #944
