### ISSUE TITLE
cancel group display in BarChart

### ISSUE THREAD

**Issue by cartmanguo** [danielgindi/Charts#1713]
I have two datasets which I display them in a group on barchart,and then I want to display only one of these dataset without putting it in a group,how can I do that?

**Comment by liuxuan30** [comment]
just not add the other data set.

**Comment by cartmanguo** [comment]
I just figured it out.
Actually you need to do more than that.
First remove the dataset you don't want,then change all the entry's x value in the existed dataset,because grouping sets will modify all the entry's x value,then call resetCustomAxisMax&Min,then set centerAxisLabelsEnabled to false,finally call notifyDataChanged()
