### ISSUE TITLE
<Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.

### ISSUE THREAD

**Issue by StevenMasini** [danielgindi/Charts#1714]
Hi Charts Team,

I already opened an issue for this before, but because you officially release the version 3.0 on Cocoapods, I think that bug should be corrected.

I'm still experimenting the same bugs when positioning the highlight bar manually using  `self.chartView.highlightValue(x: maxIndexPoint.x, dataSetIndex: 0, callDelegate: true)`

Same problem as reported in issue [#1626](https://github.com/danielgindi/Charts/issues/1626)

My console log shows 
`<Error>: Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored.Please fix this problem.`
`<Error>: CGContextAddLineToPoint: no current point.`

Any solution or work around ?

Thank you.

**Comment by liuxuan30** [comment]
I am closing this since you had one. Please give more details, like where it breaks, what's the value causes to be NaN, etc in #1626
