### ISSUE TITLE
CombinedChartView with CandleData - first/last candlesticks are cut in half

### ISSUE THREAD

**Issue by PSTDev** [danielgindi/Charts#1717]
Similar issue #1668 for CandleStickChartView was resolved recently, but same problem still exists for CombinedChartView with CandleData - first and last candlesticks are cut in half by default.

Same solution d276f554562261fce3144c92ae6a3836365d6e54 works for CombinedChartView too:

combinedChartView.xAxis.spaceMin = 0.5
combinedChartView.xAxis.spaceMax = 0.5

I think it should be part of CombinedChartView initialzation as for CandleStickChartView. At least in previous version of Charts (v2.2.5) CombinedChartView with CandleData shows full first/last candlesticks by default.

**Comment by liuxuan30** [comment]
do you have code I can reproduce? I tried ChartDemo's combined chart, it has candle stick but it's fine.

**Comment by PSTDev** [comment]
You can reproduce this issue if in ChartDemo's combined chart sample comment out other datasources and xAxis minimum/maximum modifications. Like this:

CombinedChartViewController.m
```

- (void)viewDidLoad
{
   ...

    //xAxis.axisMinimum = 0.0;

   ...
}

- (void)setChartData
{
    CombinedChartData *data = [[CombinedChartData alloc] init];
    //data.lineData = [self generateLineData];
    //data.barData = [self generateBarData];
    //data.bubbleData = [self generateBubbleData];
    //data.scatterData = [self generateScatterData];
    data.candleData = [self generateCandleData];
    
    //_chartView.xAxis.axisMaximum = data.xMax + 0.25;

    _chartView.data = data;
}
```

**Comment by liuxuan30** [comment]
Tried - only the first bar is cut in half

**Comment by danielgindi** [comment]
You should set `spaceMin`/`spaceMax` as @liuxuan30 said, and as is defined by default for bar charts or candlestick charts.
It is not set by default for Combined charts, as they may not contain bars... So you have to set it yourself.
