### ISSUE TITLE
How to set the xValues to the BarchartData ?

### ISSUE THREAD

**Issue by Ashmika** [danielgindi/Charts#1718]
In previous version i have set the xValues to barchartdata using the below code but now latest library only able to set the Datasets. So how to set the xValues as any value.
Old Version -
`BarChartData *data = [[BarChartData alloc] initWithXVals:xVals dataSets:dataSets];`

New Version-

`BarChartData *data = [[BarChartData alloc] initWithDataSets:dataSets];`

Please how i set the xValues of any type in new library.

**Comment by petester42** [comment]
You now set the x value on the DataEntry which can be seen in here example [here](https://github.com/danielgindi/Charts/blob/master/ChartsDemo-OSX/ChartsDemo-OSX/Demos/BarDemoViewController.swift)

**Comment by Ashmika** [comment]
Yes I have already use that one but its only accept the double value so for string or any xValue not accept by that. Even i use below code also to set value but seems not work properly.

`[yVals addObject:[[BarChartDataEntry alloc]initWithX:i y:val]];`

**Comment by liuxuan30** [comment]
you can conform to `IChartAxisValueFormatter` to format those x/y double values.

**Comment by Ashmika** [comment]
Its given error  if I am changing the x/y double to string format.

**Comment by Ashmika** [comment]
@liuxuan30  Yes its work I use the below code to change the value formatter. Thanks Really....Appreciate with your help..

```
- (NSString *)stringForValue:(double)value
                        axis:(ChartAxisBase *)axis
{
    return months[(int)value % months.count];
}

```

**Comment by nezihe** [comment]
@Ashmika , I have the same problem. I can not figure out where I need to change IChartAxisValueFormatter ? Any help appreciated. Thank you.

**Comment by Ashmika** [comment]
@nezihe  Sorry for late reply you should have to set it in the ex.LineChartViewController.m file.Where you use to set the data.Also set the delegate for that i.e IChartAxisValueFormatter

Also set the delegate to xaxis as below so that the method will be call.

` xAxis.valueFormatter = self;`

**Comment by nezihe** [comment]
@Ashmika Thanks for your help, I appreciate it. I managed to do it with your help!
