### ISSUE TITLE
Add UIButtons to data points in a line graph, plotting date and time in X-axis

### ISSUE THREAD

**Issue by ecoapps** [danielgindi/Charts#1719]
Reposting from StackOverFlow:
http://stackoverflow.com/questions/40258956/add-uibuttons-to-data-points-in-a-line-graph-plotting-date-and-time-in-x-axis

Can I implement the following with Charts??

----------------------------------------------------------------

I am trying to plot some data on a simple line graph. Below is my class for storing the data.

How do I plot my yValues with time or date which are strings?

Also, I would like to add title as a UIButton to each data point in the graph. Tapping on the UIButton should display the corresponding detailedNote is a small popup. I have searched and digged into a lot of Chart libraries for iOS but didn't find a way to add this simple functionality.

graph-with-buttons-at-data-points.png
https://i.stack.imgur.com/HlTZT.png

Also, what is the way to filter and plot data for "Today", "Last Week", "Last Month" or for any interval of time?

Can I do all of this with iOS libraries like Core Plot and UIBeizerPath without help from any 3rd party frameworks/libraries? I prefer to use UIBeizerPath as I can smoothen the graph.. https://medium.com/@ramshandilya/draw-smooth-curves-through-a-set-of-points-in-ios-34f6d73c8f9#.28frf03to

Can someone point me to the right resources.. Posting swift code is highly appreciated!

    class NoteEntry {
    var title: String?

    var detailedNote: String?

    var yValue: Float? = 0

    let timeString : String  = {
    let formatter = NSDateFormatter()
    formatter.dateFormat = "h:mm a"
    formatter.AMSymbol = "AM"
    formatter.PMSymbol = "PM"
    return formatter.stringFromDate(NSDate())
    }()

    let dateString: String = {
    let formatter = NSDateFormatter()
    formatter.dateFormat = "d"
    return formatter.stringFromDate(NSDate())
    }()

    let dayOfTheWeekString: String = {
    let formatter = NSDateFormatter()
    formatter.dateFormat = "EEE"
    return formatter.stringFromDate(NSDate())
    }()

    let monthAndYearString: String = {
    let formatter = NSDateFormatter()
    formatter.dateFormat = ""
    return formatter.stringFromDate(NSDate())
    }()

    }

**Comment by liuxuan30** [comment]
I guess the first thing you should do is to play with ChartsDemo - Time Line Chart. You will find answers there. Adding buttons are useless with this library.
