### ISSUE TITLE
How to show custom text on Y-axis of Line Chart?

### ISSUE THREAD

**Issue by rameswar54** [danielgindi/Charts#1720]
I'm using line chart view in my app. Here's the screenshot of the line chart.
![line chart](https://cloud.githubusercontent.com/assets/7326600/19725397/ee8a12bc-9ba2-11e6-86c8-d7f7f668a91d.png)

However I don't want the auto-calculated values on the y-axis (e.g 1.800, 2.000, 2.200), instead I want to put my unit value, e.g 'miles/h', 'meters/sec' etc.

How can I achieve this?

I also want to toggle values on a node when tapped. Is there a way to achieve this?

I've searched for the first one I didn't find it.

**Comment by thierryH91200** [comment]
It's not complicate

let leftAxis = scatterChartView.leftAxis
 leftAxis.valueFormatter = DoubleAxisValueFormatter(postFixe: "l/100")

and 

open class DoubleAxisValueFormatter : NSObject, IAxisValueFormatter
{
    open var postFixe :String = ""
    public init(postFixe: String)
    {
        self.postFixe = postFixe
    }

    public func stringForValue(_ value: Double, axis: AxisBase?) -> String
    {
        let formatter = NumberFormatter()
        formatter.minimumFractionDigits = 2
        formatter.maximumFractionDigits = 2
        formatter.localizesFormat = true
        let num = NSDecimalNumber(value: value)
        let strVal = formatter.string( from: num)
        let str = strVal! + " " + postFixe
        return str
    }
}

**Comment by liuxuan30** [comment]
edited @thierryH91200 post. good job!

**Comment by rameswar54** [comment]
Guys thanks for helping out, however I'm using version 2.2.5. Can you help out as I believe the above answer is valid only for 3.0 and above of charts version.
Thanks in advance.
