### ISSUE TITLE
 How to set the xValues to the BarchartData ?

### ISSUE THREAD

**Issue by Ashmika** [danielgindi/Charts#1721]
In previous version i have set the xValues to barchartdata using the below code but now latest library only able to set the Datasets. So how to set the xValues as any value.
Old Version -
`BarChartData *data = [[BarChartData alloc] initWithXVals:xVals dataSets:dataSets];`

New Version-
`
BarChartData *data = [[BarChartData alloc] initWithDataSets:dataSets];`

Please how i set the xValues of any type in new library.

I have already use that one but its only accept the double value so for string or any xValue not accept by that. Even i use below code also to set value but seems not work properly.

`[yVals addObject:[[BarChartDataEntry alloc]initWithX:i y:val]];`

**Comment by petester42** [comment]
Please don't create the same issue twice.
