### ISSUE TITLE
When zooming in, x-axis shows more labels than values

### ISSUE THREAD

**Issue by youvalv** [danielgindi/Charts#1722]
I would like to show only the labels that has values and not in between values
Couldn't find anything that will give me a hint in the demo project

**Comment by youvalv** [comment]
searched the issues list and found #1655 
very similar
I decided to revert back to version 2.3 since current functionality no longer suitable for my usage

I use the xAxis to display dates relevant to the Y-value. 
Dates granularity is by day, and scrolling is important (current functionality is that the xAxis labels are "switched" when the graph is scrolled instead of being populated and scrolled with the graph)

Luckily version 2.3 is still usable for me 
Thank you for a great library :)

**Comment by cilasgimenez** [comment]
And have you had recode issues with Swift 3 X Charts 2.3? I'm facing the exact same x labels problem after updated Charts.

**Comment by youvalv** [comment]
@cilasgimenez forcing this specific project to swift 2.3 (don't have anything else in swift 3 so I don't know if mixing swift versions is possible)
