### ISSUE TITLE
Set max highlight distance

### ISSUE THREAD

**Issue by nicomarca** [danielgindi/Charts#1725]
Hi,

I'm working on an interactive chart where the user is able to select a point from a scatter chart. It is working well, but i still have one issue : wherever the user tap on the chart, the closer point is selected (and i don't want that).
I saw on MPAndroidChart doc that a method called setMaxHighlightDistance(float distanceDp) exists, but I can't find an equivalent on IOS-Charts. Do you know one ?

Thanks

**Comment by liuxuan30** [comment]
take a look at `ChartHighlighter`. I am not sure if `closestSelectionDetailByPixel` or `getMinimumDistance` is the func you ask?
