### ISSUE TITLE
getMarkerPositionWithHighlight: always return CGPointZero

### ISSUE THREAD

**Issue by kientux** [danielgindi/Charts#1728]
In Charts v2, I used `-getMarkerPositionWithEntry:highlight:` to get position of highlight, relative to chart view ( #1399). In v3.0.0, that method is no longer available, and (maybe) it's replaced with `-getMarkerPositionWithHighlight:`. But it always return `CGPointZero`. I tried that in sample project:

``` Objective-C
#pragma mark - ChartViewDelegate

- (void)chartValueSelected:(ChartViewBase * __nonnull)chartView entry:(ChartDataEntry * __nonnull)entry highlight:(ChartHighlight * __nonnull)highlight
{
    CGPoint point = [chartView getMarkerPositionWithHighlight:highlight];
    NSLog(@"%f - %f", point.x, point.y); // Always print 0 - 0
    NSLog(@"chartValueSelected");
}
```

**Comment by kientux** [comment]
Okay, again, after minutes I found out that, I have to get `highlight.xPx` and `highlight.yPx` to make `CGPoint` location of the highlight. But I wonder what's the meaning of that method `-getMarkerPositionWithHighlight:`, and why it changed so much compare to previous version.

**Comment by abdulrahman18** [comment]
> Okay, again, after minutes I found out that, I have to get `highlight.xPx` and `highlight.yPx` to make `CGPoint` location of the highlight. But I wonder what's the meaning of that method `-getMarkerPositionWithHighlight:`, and why it changed so much compare to previous version.

@kientux  I tried highlight.xPx and highlight.yPx it's working for some chart bar only. Top position bar only working. Bottom level bars not working for this. Can you suggest which one is correct?
