### ISSUE TITLE
Bar on BarChart and CombinedChart doesn't start one Zero line

### ISSUE THREAD

**Issue by jndefosse** [danielgindi/Charts#1729]
Hello,

I use MPAndroidChart and Charts on my project. With Charts, when a use BarChart or CombinedChart with BarData, i show the ZeroLine with default parameter. When the chart is drawed, bars don't start at zero but before it. See the screenshot.

In MPAndroidChart, bars drawed correctly

Can you tell me how to fix it?

![capture d ecran 2016-10-27 a 09 16 34](https://cloud.githubusercontent.com/assets/5968328/19758029/92a6f1de-9c26-11e6-994f-ea93a4a8b67c.png)

**Comment by gangarharsh** [comment]
Use         
barChartView.leftAxis.axisMinimum = 0.0(Your minimum value)

**Comment by jndefosse** [comment]
The axisMinimum is setted to 0.0.

The Zero line is drawed at the top of AxisX and not on the AxisX.

Here an example where we see the AxisX and the Zero line. I will expect that there lines were the same line.

![graph2](https://cloud.githubusercontent.com/assets/5968328/19770502/cc3530c6-9c5f-11e6-9c1d-b2bf80ed87ea.png)

Here a second example where we see the graduation line for 0 with the Zero Line

![graph1](https://cloud.githubusercontent.com/assets/5968328/19770564/0183ce7c-9c60-11e6-9bb5-417fc9d23c7b.png)

Sorry for my English. It's hard to explain the problem

**Comment by liuxuan30** [comment]
@jndefosse I am a bit confused.. what's graduation line? I checked ChartsDemo, not seeing this. Are you able to reproduce with ChartsDemo?

**Comment by liuxuan30** [comment]
OK just found the reason:
in `drawZeroLine()`, it draws one point lower, so the 0 axis line and zero line not overlap
```swift
        context.move(to: CGPoint(x: viewPortHandler.contentLeft, y: pos.y - 1.0))
        context.addLine(to: CGPoint(x: viewPortHandler.contentRight, y: pos.y - 1.0))
        context.drawPath(using: CGPathDrawingMode.stroke)
```
@danielgindi any purpose for this?

**Comment by danielgindi** [comment]
Yes, it was for correcting an Android rendering anomaly. On iOS it's not supposed to happen...

**Comment by jndefosse** [comment]
Thanks
