### ISSUE TITLE
PieChartDataSet no slice space shown when an entry has 0 value

### ISSUE THREAD

**Issue by AshTag92** [danielgindi/Charts#1730]
Hi,

I noticed something while using this awesome library! 
Im using the pie chart and sometimes when I'm showing some data one of the entries will have a 0 value. I also have a set slice space as I quite like the look of it however when an entry as a 0 value the pie chart then ends up looking this:
![screen shot 2016-10-27 at 10 10 41](https://cloud.githubusercontent.com/assets/23095658/19761402/b0bedd24-9c2d-11e6-8609-b3663d3e4dd1.png)

However if all the entries do have a value above 0 it ends up showing the desired slice space: 
![screen shot 2016-10-27 at 10 10 46](https://cloud.githubusercontent.com/assets/23095658/19761418/c5fb1d74-9c2d-11e6-90ab-c2ac67a92836.png)

Am I missing something? Or is this intended? If so is there a way to still display a slice space when an entry has an empty value? 

I know I could not add the entry to the data set but then I want to make sure the colour is set specifically for each segment. However when the number of entries changes the colour chosen for a segment is different. I can't seem to understand how it decides which pie chart segment gets which colour from the colours array. 

Thanks again for any answers :)

**Comment by petester42** [comment]
Sounds like a if to me

**Comment by danielgindi** [comment]
Actually it's a feature that removes spacing when it won't fit or would cause weird looks. 0 value will cause double spacing with no value (which you specifically might want...), and an overly crowded pie with 30 values may have no space for slice spacing.

We need to make this an opt-in feature in my opinion, and default to `false`. Let the user decide and have more control.

**Comment by AshTag92** [comment]
I see yeah the reasoning behind it makes sense.

I agree making it an opt-in feature would be great.

**Comment by danielgindi** [comment]
(Actually, actual 0 values will not generate extra slice spacing, as they are being ignored for rendering. But it's possible to have almost-invisible values which generate slice spacing)

**Comment by danielgindi** [comment]
Done
