### ISSUE TITLE
HorizontalBarChart values not showing Charts 3.0

### ISSUE THREAD

**Issue by mecid** [danielgindi/Charts#1731]
I have code like this for Charts version 2.2
`
    private func setupHorizontalBarChart(samples: [HKQuantitySample]) {
        let formatter = HeartRateFormatter()
        formatter.activity = activity
        formatter.age = userAge

```
    let dataset = BarChartDataSet()
    dataset.valueFont = UIFont.preferredFont(forTextStyle: UIFontTextStyle.caption1)
    dataset.valueFormatter = DefaultValueFormatter(formatter: formatter)
    dataset.valueTextColor = UIColor.white
    dataset.resetColors()

    var xVals: [String] = []

    var index = 0

    for sample in samples.reversed() {
        xVals.append(timeFormatter.string(from: sample.endDate))
        let value = sample.quantity.doubleValue(for: HKUnit.heartRate())
        let rate = HeartRate(activity: activity!, value: Int(value), age: userAge)

        if dataset.addEntry(BarChartDataEntry(x: Double(index), y: value)) {
            dataset.addColor(rate.status.color())
            index = index + 1
        }
    }

    horizontalBarChartHeight.constant = CGFloat(30 * xVals.count)
    horizontalBarChart.data = BarChartData(dataSet: dataset)
    horizontalBarChart.xAxis.labelCount = xVals.count

    horizontalBarChart.xAxis.valueFormatter = DefaultAxisValueFormatter { (value, axis) -> String in
        return xVals[Int(value)]
    }
}
```

`

![2016-10-27 18 21 05](https://cloud.githubusercontent.com/assets/324372/19771214/2d6160a0-9c73-11e6-9415-ee5874267483.png)

But with latest version of Charts3.0

![14813278_1219891058050049_881733370_o](https://cloud.githubusercontent.com/assets/324372/19771274/6c93b7a0-9c73-11e6-8abc-2f7e4512cbbf.jpg)

How can i fix problem?

**Comment by liuxuan30** [comment]
are you talking about x axis labels, or bar values?

**Comment by danielgindi** [comment]
When posting screenshots to compare - please give screenshots with the same data. From the screenshots being very different it is hard to figure out the problem.
Anyway if you're talking about the labels missing every 2nd label - then please check your configuration. See the demo, it works and shows the values, so there isn't any missing functionality.

**Comment by mecid** [comment]
@danielgindi i gave this screens because data not important for this case.
More important chart configuration. Same code give different results.

**Comment by mecid** [comment]
@liuxuan30 as you see in my code snippet i was set 
`horizontalBarChart.xAxis.labelCount = xVals.count`

But this is not working for me.

And why bar chart values not showing?

**Comment by danielgindi** [comment]
It's about your configuration, so you should compare yours to one of the demos, or post a working sample project so we can test it. When you do - please re-open the issue.

**Comment by liuxuan30** [comment]
@mecid so I am confused what are you asking - either x value labels, or just data value labels? If you are talking about data values, then I think you might miss some setup.

My code just wants to fix the x value labels appears every 2nd.

**Comment by kkontus** [comment]
@liuxuan30 can you show me an example how to show label on every 2nd bar (because I need to show 6 bars with labels that have following format: 2016-06, 2016-07, 2016-08, 2016-09, 2016-10, 2016-11). Since labels are pretty long it would be great if I could show every 2nd label. Here are the screenshots of what I want to accomplish (first one is Android version 2.2.5 just to see what I need and the second is from an iOS app with v3.0.0)

for now I'm using:
`
barChartView.xAxis.valueFormatter = DefaultAxisValueFormatter { (value, axis) -> String in
            return self.dataPoints[Int(value)]
        }
`

![imageedit_2_5990845091](https://cloud.githubusercontent.com/assets/6008300/19930141/f288681c-a0fe-11e6-9683-fd1b549f0603.png)
![imageedit_4_6145158700](https://cloud.githubusercontent.com/assets/6008300/19930140/f2878f1e-a0fe-11e6-9b86-d91b8d3ae683.png)

**Comment by kkontus** [comment]
@liuxuan30 found the solution, I needed granularity
`barChartView.xAxis.granularity = 2.0`

btw, sorry for posting on closed issue, didn't see that

**Comment by nmdias** [comment]
Setting the labelCount to the number of values did it for me. Maybe it should've behaved the other way around? Show every label by default, and let the user adjust in case they don't fit.

**Comment by Schabaani** [comment]
@nmdias Sorry that post here. How did you add some string labels on left of [HorizonalBarChart](https://github.com/danielgindi/Charts/issues/2850)
