### ISSUE TITLE
Travis does not use github token for pull request build

### ISSUE THREAD

**Issue by petester42** [danielgindi/Charts#1734]
Because travis does not load the github token for pull requests, the build sometimes fails when we can't download the realm binaries.

**Comment by danielgindi** [comment]
Hmm I hate it when it's "sometimes"... I'm guessing that free Travis have a specific capacity

**Comment by petester42** [comment]
It's not ambiguous though. Since the github token is not loaded eventually the "max number of downloads" for unauthorized requests will be hit. When that happens the build fails since it has to actually build realm which takes longer than 10 minutes (the limit of Travis builds)

**Comment by petester42** [comment]
Seems like Travis now builds for more than 10 minutes so even Carthage fails to download dependencies we should still be good.
