### ISSUE TITLE
How to make Radar five top angle tap enabled?

### ISSUE THREAD

**Issue by Seppuu** [danielgindi/Charts#1735]
in Charts 2.3.0.I use chartView.getMarkerPosition get the Radar five top angle (x,y)position(I,pass five chartView.yAxis.axisMaximum as  param) ,then add five UIButton ,so ,I  can tap them.
in Charts 3.0 ,Pie/radar charts do not have a concept of X index anymore. What can I do ? How can I make "Party A""Party B"...tap enabled?

![fa45786d-0fd8-470e-a906-5e9987268ad2](https://cloud.githubusercontent.com/assets/12640162/19797520/2b583c24-9d1e-11e6-99e6-019f4cb6ef41.png)

**Comment by liuxuan30** [comment]
you could look at the tap gesture handler to add your hook?
