### ISSUE TITLE
Swift: Custom Xaxis and Yaxis problem.

### ISSUE THREAD

**Issue by sashalondon** [danielgindi/Charts#1740]
I am using the formatter to format the xAxis for the date and that works well. I have tried to format the yAxis but I get the same information as the xAxis format on the yAxis. How can I differentiate between the two axis in the formatter class?

```
public func stringForValue(_ value: Double, axis: AxisBase?) -> String {
    daysChosen = AnalysisDataStruct.segmentTimeChosen
    months = today.chartStringArrayOfDateForPrevious(numberOfDays: daysChosen).reversed()
    return months[Int(value)]
  }


Public func stringForYAxisTrueOfFalseValue(_ value: Double, axis: AxisBase?) -> String {
    if value == 0 {
      return "Not Present"
    } else {
      return "Present"
    }
  }
```

In the ChartViewController

```
  _ = Array(0...(numberOfReadings - 1)).map { x in return self.formato.stringForValue(Double(x), axis: self.xaxis) }
 self.xaxis.valueFormatter = self.formato

    _ = ys2.enumerated().map { x, y in return self.formato.stringForYAxisTrueOfFalseValue(Double(x), axis: self.yaxis) }
 self.lineChart2.leftAxis.valueFormatter = self.yaxis.valueFormatter
```

**Comment by liuxuan30** [comment]
Please explain what's the problem and better having a screenshot. I barely understand..

**Comment by danielgindi** [comment]
You can test for the `kind` of `axis`, or you can have two different formatter classes, which is the right way to do this.
If you're lazy and don't want to create another formatter class, you can initialize a Default formatter with a `block`, as mentioned in the release notes of 3.0.0.
