### ISSUE TITLE
Bars not showing bar chart

### ISSUE THREAD

**Issue by sjuvvalapalem** [danielgindi/Charts#1742]
Hi,

Ever since upgrading to 3.0, i am having trouble with the bars not showing in the bar chart.

One bar shows when the data has only one point. If i add more than one point then the bars donot show. 
This is happening  only when the xaxis has dates. if i change the data from dates to say integer then it works fine. 
Please see the attached screenshots.

A sample of the data would be similar to this
{
"09/04/2012":"245",
"02/05/2013":"227",
"04/07/2013':"234",
"07/08/2015":"244",
"10/11/2016":"2254"
}

Thanks,
Bob

![1](https://cloud.githubusercontent.com/assets/19563094/19830369/a186f2e2-9db3-11e6-8c65-5dc3b99a6a1d.png) 

As seen below i dont see the bars at all? what seems to be causing this?
![2](https://cloud.githubusercontent.com/assets/19563094/19830371/a73cfc2c-9db3-11e6-8559-7d33a205981a.png)

**Comment by sjuvvalapalem** [comment]
Any one has a solution for this? 
It seems strange that the bars are missing in 3.0. Looks like i am either missing a call or setting something, it would be super helpful if there is a solution for this.

Thanks,
Bob

**Comment by liuxuan30** [comment]
How do you set it up? Chart 3.0 has redesigned x axis, so lots of things changed. If you don't update your code, it might be missing. For now, please check ChartsDemo for different bar chart demos.

**Comment by sjuvvalapalem** [comment]
I will run the Demo charts again and see if i can reproduce the issue, but i believe the issue is similar to the other issue #1716 opened.

Let me get back to you once i make some changes and running the Charts Demo. 

It seems certain x-values are causing issues.

Thanks,
Bob

**Comment by avitus** [comment]
I'm having the same problem. My X-axis correctly shows the date in format YYYY-MM-DD but the bars are invisible.

**Comment by sjuvvalapalem** [comment]
@liuxuan30 ,
here is what i basically tried ... I made some changes to the ChartsDemo in 3.0 and it is doing exactly the same thing...

I made the following changes. instead of X value being a double, i am adding the datetime since 1970 which is the double value for the dates.
changed the xaxis formatter to a dd/MM .

Also attaching the code for the BarChartViewController.m that way you could check it.

See the screenshot below.
![simulator screen shot nov 1 2016 12 22 47 am](https://cloud.githubusercontent.com/assets/19563094/19881188/5ccfe394-9fc9-11e6-8c5b-ac0724a3dc55.png)

[BarChartViewController.m.zip](https://github.com/danielgindi/Charts/files/563466/BarChartViewController.m.zip)

Either i am missing something very simple or this is a bug.

Thanks,
Bob

**Comment by JeremyChiang** [comment]
Hi, I am not sure why this issue is closed, but like everyone who has described the symptoms here and in https://github.com/danielgindi/Charts/issues/1716, I am experiencing the same bug in our project. In short, the X-axis can't seem to handle large values such as time intervals, and it somehow messes up the rendering of the chart.

**Comment by liuxuan30** [comment]
@sjuvvalapalem the original ChartsDemo works fine right? I don't know the context about your changes. In Chart 3.0, x values are always double. If you changed anything, make sure if change all related field. You screenshot is just missing the bars, so I think you could check `drawDataSets` in bar chart renderer for more details. It's easier to debug on your side.

**Comment by sjuvvalapalem** [comment]
@liuxuan30 i have attached the changes i made in my reply earlier.
All i did was instead of double just added the Nstimeinterval for some dates and for some reason its not showing the bars.

I think this could be a bug. Please look at the attached zip document, you could easily figure out the changes i made and that should make sense.
Looking at the same issue for the other people, i suspect this could be a bug.
Any help on this is greatly appreciated as my project is being halted for this instead of getting pushed to the appstore.

Any solution to this would greatly help.

Thanks,
Bob

**Comment by sjuvvalapalem** [comment]
@liuxuan30 could you please make this issue Open? so that this gets more traction just like the others mentioned.

Thanks,
Bob

**Comment by liuxuan30** [comment]
I m sorry that I'm busy with my work recently, so I can't take a look at this very quickly.
It's better that you can reproduce it with ChartsDemo.
NSTimeInterval is double I remember, so it should not impact..

**Comment by sjuvvalapalem** [comment]
@liuxuan30 yes, it is a double. With the formatter, the dates show up correctly. the values above the bars show correctly.

Everything is working but the bars are not showing.

 If you are busy, Is there any one else who could look into this issue/bug? 

Thanks,
Bob

**Comment by liuxuan30** [comment]
alright, I did a quick check.
The x axis range is 
```
(lldb) po max - min
34041601.0
```
When rendering, barRect width is too small:
```
▿ (30.7373051480045, 132.310035326087, 8.28906013339292e-06, 257.842777173913)
  ▿ origin : (30.7373051480045, 132.310035326087)
    - x : 30.7373051480045
    - y : 132.310035326087
  ▿ size : (8.28906013339292e-06, 257.842777173913)
    - width : 8.28906013339292e-06 //  <-- you won't see it
    - height : 257.842777173913
```
So you don't see it.
The reason is, the x val is too big, so in `prepareBuffer()`, 
>let barWidthHalf = barData.barWidth / 2.0 // barWidth default is 0.85

then
```
let left = CGFloat(x - barWidthHalf)
let right = CGFloat(x + barWidthHalf)
barRect.size.width = right - left
```
it's trivial.

@danielgindi seems like we need to handle` barWidth` to cope with big values?

The temporary workaround is to uses bigger day units, not seconds for x values. Or you just turn it into 1,2,3,4,.. and let the formatter to format. In your data, your x vals are over one year, even in days, it's 365 bars and the bar would be thin too.

**Comment by frederic-adda** [comment]
Hi,
 I have the exact same problem, but the issue seems to be closed without giving any solution ...
If I use a line chart, the chart is drawing correctly but if I chose vertical bar chart, no bar appears.
So, what should we do ?
Thanks

**Comment by Pikacz** [comment]
setting BarChartData.barWidth to huge value (~10 000) solved problem for me

**Comment by brittanygraft** [comment]
I got around this issue by setting a border
chartDataSet.barBorderColor = UIColor.blue
chartDataSet.barBorderWidth = 30
Hope that helps

**Comment by mannyveloso** [comment]
Setting barBorderWidth seems to fix the issue.

**Comment by sjuvvalapalem** [comment]
Any solution for this issue? Setting barBorderWidth seems to work but it doesnt really work the right way because if there is only one or 2 data points the lines are too thin (assuming you set it the barBorderWidth to 1). If set to a higher number then all the bars are joined and mingled together and doesnt look good.

Any work on this is greatly appreciated.

**Comment by nikhilroy782** [comment]
@sjuvvalapalem @avitus did you find any solution for this.

**Comment by siltrifork** [comment]
It's been 2 years now since this bug was reported, and there's still not a fix?

**Comment by ChristianVinterly** [comment]
Not sure if this helps anyone, but I had the same problem and solved it by setting my bars to correct size relative to the range of the x-axis:
```
let data = BarChartData(dataSets: [dataSet])

let dataSetRange = dataSet.xMax - dataSet.xMin
let availableSpacePerBar = dataSetRange / Double(dataSet.entryCount)
data.barWidth = availableSpacePerBar * 0.8 // 80% of available space

chartView.data = data
```

**Comment by jimmythai** [comment]
@ChristianVinterly I encountered the same problem and tried your solution. It really worked for my bar chart👍

**Comment by PiyushEmproto** [comment]
> setting BarChartData.barWidth to huge value (~10 000) solved problem for me

This one works better then https://github.com/danielgindi/Charts/issues/1742#issuecomment-519056482 when u have some missing values in between your data range

**Comment by superandrew** [comment]
I just lost 3 hours for this, so keeping an eye on it. Ended by using indices.

**Comment by marshtupa** [comment]
Hi there! I Find new solution to solve this problem. 

> The main point is to round `timeIntervalSince1970` to amount of days.
> Because I don't need more than a day precision

```
extension TimeInterval {
    private static let secondsInDay: TimeInterval = 60 * 60 * 24
    
    func getDays() -> Double {
        let val = (self / TimeInterval.secondsInDay)
        return val.rounded(.towardZero)
    }
    
    func daysToSeconds() -> Double {
        return self * TimeInterval.secondsInDay
    }
}
```
How to create ChartDataEntry
```
ChartDataEntry(x: transaction.date!.timeIntervalSince1970.getDays(), y: someVal)
```
And formatter look like this
```

public class DateValueFormatter: NSObject, AxisValueFormatter {
    private let dateFormatter = DateFormatter()
    
    override init() {
        super.init()
        dateFormatter.dateFormat = "dd.MM"
    }
    
    public func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        let str = dateFormatter.string(from: Date(timeIntervalSince1970: value.daysToSeconds()))
        return str
    }
}
```

![Simulator Screen Shot - iPhone 11 - 2021-10-17 at 08 46 07](https://user-images.githubusercontent.com/45558274/137613532-5e8f4dfb-55c9-4cf0-b0fc-c23abb508787.png)

**Comment by dattatrayParthenon** [comment]
I'm still facing issue, I had tried all solutions mentioned different comments but docent work. setting bar width fixing issue of showing bar but selecting bar does not work.

**Comment by RRCummins** [comment]
> Not sure if this helps anyone, but I had the same problem and solved it by setting my bars to correct size relative to the range of the x-axis:
> 
> ```
> let data = BarChartData(dataSets: [dataSet])
> 
> let dataSetRange = dataSet.xMax - dataSet.xMin
> let availableSpacePerBar = dataSetRange / Double(dataSet.entryCount)
> data.barWidth = availableSpacePerBar * 0.8 // 80% of available space
> 
> chartView.data = data
> ```

This workaround works for me. This is still a bug.
