### ISSUE TITLE
Xcode 8.1 is reporting 'No such Module 'Charts'' 

### ISSUE THREAD

**Issue by cwoloszynski** [danielgindi/Charts#1743]
I am using the latest version of Charts (8ef870a6fa21ba585236096ac0ddc71d12d16204).  

Just migrated to Xcode 8.1 this AM.  Builds worked before this but after I am getting this new error.  

When I look at the Charts project, it appears as a 'macOS' target not iOS.  Any suggestions on how to fix this would be greatly appreciated.

**Comment by thierryH91200** [comment]
look at #1538

**Comment by cwoloszynski** [comment]
I suspect that Xcode 8.1 may have broken the ability to have a single Framework for multiple platforms.  In looking at the compilation details for Charts framework, it now (under 8.1) builds differently than iOS frameworks.    

The screen capture here shows XCGLogger output and the Charts output.  The XCGLogger code compiles each source with its own line; Charts only shows a generic compilation line.  The items after that show difference in architecture (x86 vs ARM), etc.  

![screenshot](https://cloud.githubusercontent.com/assets/579268/19836805/3f08f730-9e82-11e6-90b1-ba9e70d6353e.png)

**Comment by cwoloszynski** [comment]
Looks like I found my issue.  Somehow in the migration to Xcode, the target switched from an iOS simulator to 'MacOS'.  Once I realized this and switched back to an iOS target, it all built fine.
