### ISSUE TITLE
Carthage realm-cocoa ~> 1.1 dependency conflict

### ISSUE THREAD

**Issue by DanielAsher** [danielgindi/Charts#1747]
Hi,
Thanks for the great project! I'm very much looking forward to exploring and contributing.

I notice the ChartsDemo project has a realm-cocoa ~> 1.1 dependency that Charts does not require. Would it be possible to remove this requirement from the main library?

many thanks,
Daniel

**Comment by petester42** [comment]
https://github.com/danielgindi/Charts/issues/1748
