### ISSUE TITLE
ChartsDemo dependency on realm-cocoa ~> 1.1 issue

### ISSUE THREAD

**Issue by DanielAsher** [danielgindi/Charts#1748]
Hi,
Thanks for the great project! I'm very much looking forward to exploring and contributing.

I notice the ChartsDemo project has a realm-cocoa ~> 1.1 dependency that Charts does not require. Would it be possible to remove this requirement from the main library?

many thanks,
Daniel

**Comment by danielgindi** [comment]
The library has no dependency on Realm. It's only *the demo* that requires Realm, as it demonstrates Realm use too.
You can compile against Charts as you always did.

**Comment by DanielAsher** [comment]
Apologies for the double issue posting.
Perhaps I am misusing Carthage. It is certainly true that there is no dependency in the library, but I have found that a project using the Charts Cartfile will have realm-cocoa pinned at v1.1. I am unable to run `carthage update` with my realm-cocoa v2.0 dependency being respected.

**Comment by petester42** [comment]
Ya that would be an issue with Carthage. We can't specify subspecs like cocoapods so we need to include all possible dependencies in our Cartfile. You could send a pull request updating the realm version and I'll gladly merge it in.
