### ISSUE TITLE
limit line real time update

### ISSUE THREAD

**Issue by wajihkm** [danielgindi/Charts#1755]
Thanks for this nice library.

I added a limit line to a CombinedChart,
![1](https://cloud.githubusercontent.com/assets/18402145/19855425/ec196a2a-9f8d-11e6-8ebb-c15fb5ba8e8c.png)

it's dashed line labeled (average speed).
I added some new entries to line chart data and updated the limit of limitline
`limitLine.limit = newSpeedAvg`
this updated the line x position but still related to the initial canvas hieght,
So the last view was this:
![2](https://cloud.githubusercontent.com/assets/18402145/19855510/693aaf00-9f8e-11e6-8afe-c28cc403cc78.png)

So is this a bug or an error in my code ?
Thanks

**Comment by danielgindi** [comment]
What's the problem exactly? The y-axis changes? That's normal, if you added entries with higher Ys. You can limit the viewport to only show part of the axis, and force the user to scroll.

**Comment by wajihkm** [comment]
The problem is as you see,
the new limit value is `32.34`
But the line draw on near `80` value

**Comment by hhanesand** [comment]
@wajihkm Try removing the limit line and adding it back to the graph each time you change the limit!

**Comment by liuxuan30** [comment]
Since you changed the value, you can call `setNeedsDisplay()` to redraw the limit line. Removing is not necessary I suppose.

**Comment by NallapatiMalleswari** [comment]
How to draw Gradient limit line
