### ISSUE TITLE
How to set x-axis labels with ios charts

### ISSUE THREAD

**Issue by muYunFei** [danielgindi/Charts#1758]
What I want to do is label the x-axis with time values, e.g. 2:03, 3:03, 4:03, etc. In the tutorials I find online, this seems to be very easy; many of them use months of the year as the x-axis label.

However, in the swift3 update, charts now initializes values with x and y values, and I am not sure how to use labels in this version of the library. Does anyone know how to create labels in charts with swift3?

**Comment by WyattMufson** [comment]
https://github.com/danielgindi/Charts/issues/1340
