### ISSUE TITLE
Sorry， I no speak English， 3.0版本的LineChartView

### ISSUE THREAD

**Issue by graceydb** [danielgindi/Charts#1759]
Sorry， I no speak English， 3.0版本的LineChartView如果实现下面这个问题：x轴有200个点，y轴只有100条数据，绘制结果是：折线只占ChartView宽度的一半，在3.0版本以前是可以做到的，3.0版本不知道该怎么实现，请赐教

**Comment by matthewlui** [comment]
不妨pass in 一個200個Y全零的dataset作placeholder

**Comment by graceydb** [comment]
@matthewlui 不是很明白你说的，我试着增加一个dataset2做placeholder，200个y值全部为0，dataset1 100个y值，但它最终宽度总是使用数据量少的dataset1来填充，并不是dataset2的宽度
