### ISSUE TITLE
use lineCharts ,if i want show custom string at x, don't show int number, how to do it?

### ISSUE THREAD

**Issue by yuxingmin** [danielgindi/Charts#1760]

**Comment by AbhishekGCopper** [comment]
Use **IAxisValueFormatter** protocol and then implement the protocol method:
 **func stringForValue(_ value: Double, axis: AxisBase?) -> String**
where you return the string you want to represent on the xAxis. 
example:
let vowels = ["A", "E", "I", "O", "U"]
 func stringForValue(_ value: Double, axis: AxisBase?) -> String {
   // Check to make sure the value doesn't go out of index range
 if Int(value) < vowels.count && Int(value) >= 0 { 
      return vowels[Int(value)]
    } else {
      return "consonant"
    }
  }
