### ISSUE TITLE
How to get the chart data entry points

### ISSUE THREAD

**Issue by rameswar54** [danielgindi/Charts#1762]
Hi Guys,

As per my needs I have drawn this custom balloon marker. However I don't know how to fetch the values to display besides actual labels. Can you help me please. 

**Note: I'm using release version 2.2.5**

![screen shot 2016-11-01 at 6 40 19 pm](https://cloud.githubusercontent.com/assets/7326600/19890859/36febf06-a063-11e6-863b-e290f0f57175.png)

I'm able to fetch one data entry value from the 'refreshContent' method using 'entry.value' property, However I need to fetch all the data entry points to display actuals besides the label texts, e.g

Normal 10
Warning 3
Critical 1

etc.

Let me know if you need code.

**Comment by petester42** [comment]
Can't you just create your marker from the actual dataset values since you need them all?

**Comment by rameswar54** [comment]
Actually I'm not sure, where you're pointing at. I just tried to dig in to demo, tried this way. Can you please point somewhere to look at then, I'll try to search though.. And thanks for the comment.

**Comment by petester42** [comment]
You create a dataset to assign to your chart. From that dataset you could get all the values.

**Comment by rameswar54** [comment]
Oh k got it. Thanks. I'm already having a dataset which I'm supplying to the line chart.

And I believe I can get the index from 'chartValueSelected' method. Is that what you're saying. correct me if I'm wrong.

**Comment by petester42** [comment]
Ya that's what I'm saying. I don't remember the exact method name but you can get it somehow.
