### ISSUE TITLE
to run ChartsDemo

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1765]
i can't run successe at  ChartsDemo  proj, because i wasn't used `Carthage` to build this.  But , my Mac can't install `Carthage`, so,  If I do not use`Carthage`, I can not run.   If I can not go through `Carthage` compiled, you can run?

<img width="708" alt="2016-11-02 4 52 40" src="https://cloud.githubusercontent.com/assets/8415820/19922379/523e609a-a11d-11e6-8c45-ee2fc034ddaf.png">

**Comment by petester42** [comment]
No. You need Carthage since the demo has examples with realm. Since realm is a 3rd party library we are using Carthage to get it for the demo.

Why can't your mac install Carthage?

**Comment by liuxuan30** [comment]
jut homebrew update and homebrew install carthage.

**Comment by MonkeyRing** [comment]
I solved.  you can close this issue.
