### ISSUE TITLE
Charts 3.0 labelCount bug?

### ISSUE THREAD

**Issue by Asavarkhul** [danielgindi/Charts#1767]
When we want to display only 1 xAxis label, the labelCount force to show multiple label but we want to display only one line..

For example :

if labelCount = 2 (default minimum value)

<img width="563" alt="capture d ecran 2016-11-02 a 11 44 25" src="https://cloud.githubusercontent.com/assets/10169030/19925955/79aeb66e-a0f2-11e6-8c5d-77b98fdbd686.png">

But if we force this to 3 for example 

<img width="567" alt="capture d ecran 2016-11-02 a 11 44 33" src="https://cloud.githubusercontent.com/assets/10169030/19925974/8a49e34a-a0f2-11e6-97a8-6328b4e5885a.png">

Is this behavior a bug? or do we have miss something?

Here is our code :

```
var yVals = [BarChartDataEntry]()
var xVals = [String]()
            
if chartDataCompanies.count > 0 {
   let maxDataEntry: Int = 15
                
   //sort
   var chartDataCompanies = chartDataCompanies.values.filter({$0.solvedRate > 0.0 && $0.issuesCount > 0}).sorted(by: {$0.solvedRate > $1.solvedRate})
                
   //subArray
   let index = min(maxDataEntry, chartDataCompanies.count)
   let companies = chartDataCompanies[0..<index]
                
   for (index, data) in companies.enumerated() {
      yVals.append(BarChartDataEntry(x: Double(index), y: data.solvedRate))
      xVals.append(data.descriptionString)
   }
                
   let barDataSet = BarChartDataSet(values: yVals, label: nil)
   barDataSet.drawValuesEnabled = false
   barDataSet.colors =  PreferredChartsColors
                
   let chartData = BarChartData(dataSets: [barDataSet])
   chartData.setValueFont(UIFont.preferredFont(forTextStyle: UIFontTextStyle.subheadline))
   reloadChartViewWithData(chartData)
                
   self.chartView.xAxis.labelCount = xVals.count
   self.chartView.xAxis.valueFormatter = DefaultAxisValueFormatter { (value, axis) -> String in
      return xVals[Int(value)]
   }
} else {
   let barDataSet = BarChartDataSet(values: yVals, label: nil)
   let chartData = BarChartData(dataSets: [barDataSet])
   reloadChartViewWithData(chartData)
}
```

**Comment by liuxuan30** [comment]
looks like you don't turn on `axis.forceLabelsEnabled`. 
BTW, look at `computeAxisValues(min yMin: Double, max yMax: Double)` and you will know how it works.

**Comment by Asavarkhul** [comment]
@liuxuan30 Hello, can you try with this example project https://github.com/Asavarkhul/ChartsSampleProject this simply show how we implement it and show directly the bug

**Comment by liuxuan30** [comment]
I can' debug your code because you don't have Charts source code. But I do tried it in ChartsDemo - horizontal bar chart, it works I think. Would you try it first?
One thing to mention:
Set chartView.data = data at last after you configure your chart, or call `notifyDataSetChanged` manually. You put it in a thread, which may cause side effect.

**Comment by liuxuan30** [comment]
OK I found what's your problem:
you don't set granularity and you only have 1 x which is 0 - an embrassing number, so it calculates the x range is [-0.4, -0.2, 0, 0.2, 0.4], so it has several labels. 

You should set granularity like to 1, then you only get 1 label
Don't forget to change barWidth, so you bar don't seem too wide.
