### ISSUE TITLE
Custom Format YAxis

### ISSUE THREAD

**Issue by ajimenezjulio** [danielgindi/Charts#1768]
I am trying to use a custom format in YAxis, specifically I'm trying to put a "$" symbol and a thousands separator "," also I want to put the thousands separator on the value that is showing above the bars.

Looking in documentation, you use the NSNumberFormatter but I can't, XCode show me an error.

I'm using this code:
`let formatoNumeros: NSNumberFormatter = NSNumberFormatter()`
            `formatoNumeros.minimumFractionDigits = 0`
            `formatoNumeros.maximumFractionDigits = 2`
            `formatoNumeros.currencyGroupingSeparator = ","`
            `formatoNumeros.negativeSuffix = " $"`
            `formatoNumeros.positiveSuffix = " $"`
            `yaxis.valueFormatter = formatoNumeros`

The error appears on the line: `yaxis.valueFormatter = formatoNumeros` and it says: "Cannot assign value of type 'NSNumberFormatter' to type 'IAxisValueFormatter', also I've tried casting the variable but it cannot be posible and also have tried to use the NSNumberFormatter on the chartData, like this: `chartData.setValueFormatter(formatoNumeros)` but here XCode says that cannot assign value of type NSNumber.. to IValueFormatter.

And my questions is what would be the way or ways to customize the YAxis on BarCharts?

 PS. The language I'm using is swift

Thanks!

**Comment by liuxuan30** [comment]
that's because in Chart 3.0, axis changes to use `IAxisValueFormatter`, which is a protocol. You can conform to it then. If you don't want this high flexible formatter, then you can take `DefaultAxisValueFormatter`, and pass through a number formatter:
```swift
    public init(formatter: NumberFormatter)
    {
        super.init()
        
        self.formatter = formatter
    }
```
Just take a look at these classes

**Comment by GuriSarao** [comment]
I am getting this error - 

Cannot assign value of type 'DayAxisValueFormatter' to type '(any AxisValueFormatter)?'
