### ISSUE TITLE
[BUG] multiple bar chart in ChartsDemo not display full for last x value

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#1770]
multiple bar chart in ChartsDemo not display full for last x value.
When dragging the x slider, it grows and shrinks, not always full.
@danielgindi is this expected behavior? I would assume it should display fully.

![mb](https://cloud.githubusercontent.com/assets/4375169/19954201/3763b3a8-a1b1-11e6-90e2-265dc18b7d8b.png)

**Comment by SumoSimo** [comment]
Created [PR](https://github.com/danielgindi/Charts/pull/1771)
