### ISSUE TITLE
BarChartView - The first column and last column show only half?

### ISSUE THREAD

**Issue by zhigangxp** [danielgindi/Charts#1772]
The first column and last column show only half?
http://www.swellvector.com/Upload/image/20151202/0419.jpg

**Comment by danielgindi** [comment]
I think you could have done better than this...

Duplicate https://github.com/danielgindi/Charts/issues/1717 https://github.com/danielgindi/Charts/issues/1668 https://github.com/danielgindi/Charts/issues/1666 https://github.com/danielgindi/Charts/issues/1654 https://github.com/danielgindi/Charts/issues/1569 https://github.com/danielgindi/Charts/issues/1468 https://github.com/danielgindi/Charts/issues/1446

By default this shouldn't happen. You are probably using a early beta and not the release version.
