### ISSUE TITLE
How to make BarChart Bar Sizes proportional?

### ISSUE THREAD

**Issue by patreu22** [danielgindi/Charts#1774]
I have a BarChart with two data entries and want to have the Bar parts fitting the actual percentage. So in the example 1/3 of the bar should be green and 2/3 should be red.
I can't figure out why the step from 0 to 2 is smaller than from 2 to 3. 
Has anybody an idea?

My current modifications of the y-axis are these:
````
        barChart.leftAxis.granularity = 1
        
        let formatter = NumberFormatter()
        formatter.minimumFractionDigits = 0
        barChart.leftAxis.valueFormatter = DefaultAxisValueFormatter(formatter: formatter)

````

<img width="276" alt="bildschirmfoto 2016-11-03 um 09 52 51" src="https://cloud.githubusercontent.com/assets/11362357/19960162/567e4ca4-a1ab-11e6-8476-c412ed5c1b2b.png">

**Comment by liuxuan30** [comment]
maybe you should check out ChartsDemo for those stacked bar chart to get started. I don't know how do you set it up, but it looks like wrong.

**Comment by patreu22** [comment]
Well I checked the 3.0 ready Demo but the only difference is that I'm setting the granularity. Is there any way to determine the number of steps/values the left Axis should hold?

**Comment by liuxuan30** [comment]
@patreu22 check `computeAxisValues`

**Comment by patreu22** [comment]
Well check the left Axis.
The red bar has the value "2" (as you can see because I printed it out), the green has the value "3".
So imho the red bar should be 2/3 of the total bar and the green part should only be 1/3.

I don't think computeAxis can help in any way.

**Comment by liuxuan30** [comment]
My theory is if you set axisMinimum like 1.8, and the bar starts from 0, but only [1.8, 3] range is on the chart view, it will looks like yours. You need to check your yAxis.axisMinimum first.
