### ISSUE TITLE
Scroll UIImageView on X-axes along with x-vals

### ISSUE THREAD

**Issue by walinaqvi** [danielgindi/Charts#1775]
I just tried to add UIImageView on x-axes along with x-vals ,i get x coordinate of image from getPosition method of BarChartView and i'm hardcoding y coordinate something like this :

` CGPoint imagePos = [_chartView getPosition:[yVals objectAtIndex:i] axis:AxisDependencyRight];
        UIImageView *imageView  = [[UIImageView alloc] initWithFrame:CGRectMake(imagePos.x, 30, 10, 10)];`

and then i'm adding these images on BarChartView:
`[_chartView addSubview:imageView];`
its working fine when im not zooming or scrolling the Chart,the moment i'm scrolling the chart these images are fixed on same place and not scrolling along with X-Axes labels .

Is there any public property like UIScrollView,Where should i add these images ,So these images also scroll along with Bars of graph.

**Comment by liuxuan30** [comment]
that's because you add them with static coordinates. You should check how the renderer works

**Comment by waliHaider** [comment]
Can you tell me any other approach or is there any class that can be subclass to achieve this?

**Comment by liuxuan30** [comment]
I would say use CoreGraphics to do this, just like how this library do. You can take a look at x axis render how it draws the label

**Comment by walinaqvi** [comment]
I just added code to dram image in drawLabel method of ChartXAxisRenderer and it worked.

Thanks Xuan

**Comment by stoicsm** [comment]
@walinaqvi : Can you share your code with modification ? Thank you

**Comment by walinaqvi** [comment]
In ChartXAxisRenderer.swift i modified the signature of `drawLabel` method also added code to draw image 

```
internal func drawLabel(context context: CGContext, label: String, xIndex: Int, x: CGFloat, y: CGFloat, align: NSTextAlignment, attributes: [String: NSObject], constrainedToSize: CGSize, img:UIImage)
    {
                
        let rect = CGRect(x: x, y: y, width: 10, height: 10)
        img.drawInRect(rect);
        

        let ynew = y+15;
        let formattedLabel = _xAxis.valueFormatter?.stringForXValue(xIndex, original: label, viewPortHandler: viewPortHandler) ?? label
        ChartUtils.drawMultilineText(context: context, text: formattedLabel, point: CGPoint(x: x, y: ynew), align: align, attributes: attributes, constrainedToSize: constrainedToSize)

    }
```

and in ChartXAxisRendererBarChart.swift i passes appropriate image while calling method  `drawLabel`.
