### ISSUE TITLE
Unable to Override some properties of LineChartView in Charts version 2.2.5

### ISSUE THREAD

**Issue by rameswar54** [danielgindi/Charts#1777]
**Charts Version: 2.2.5**

I'm not able to override properties 'noDataText' and 'infoTextColor' of line chart view.

No matter what text color I set, it displays the default text and text color which is 'No chart data available' and 'Orange' color.

**Comment by liuxuan30** [comment]
well, you can do anything you like with the library code. This is specifically true since we dropped 2.2.5 support.

**Comment by NathanMrtns** [comment]
@liuxuan30 is it possible to override the property in ChartViewBase without unlocking the pod?

**Comment by NathanMrtns** [comment]
Just in case somebody still wondering about it. Here is an example:

```
class CustomBarChartView: BarChartView {
    override var noDataText: String {
        set {
            //Do nothing
        }
        get {
            //note that this will be a global solution for all CustomBarChartView
            return "Your new no data string"
        }
    }
}
```

And in the storyboard, you set yout view as CustomBarChartView.
