### ISSUE TITLE
Chart adds a -1 x-axis entry

### ISSUE THREAD

**Issue by narciero** [danielgindi/Charts#1782]
I have a LineChart's xAxis set up with follwing properties:
````
xAxis.axisMinimum = 0.0
xAxis.granularityEnabled = true
xAxis.labelPosition = .bottom
xAxis.labelTextColor = UIColor.genioWhite()
xAxis.axisLineColor = UIColor.genioGray()
xAxis.drawGridLinesEnabled = false
xAxis.valueFormatter = StringFormatter(["some date strings"])
````

I then add 3 entries with x-values of 0.0, 1.0, and 2.0 - however this is what my graph looks like:
<img width="374" alt="screen shot 2016-11-03 at 10 28 44 pm" src="https://cloud.githubusercontent.com/assets/9964211/19992509/e98377c2-a214-11e6-92bf-47dbedc89327.png">

While debugging my xAxis value formatter I found that magically an x axis entry of -1 is being created, hence the extra space to the left...the line chart should (as expected) fill the whole width since only 3 data points were added, yet there are 4

**Comment by tushuaidianzi** [comment]
能不能把这个demo发给我一下，谢谢

**Comment by liuxuan30** [comment]
Take a look at ChartsDemo for different line charts, including time line chart to get started. By default, it will calculate x axis range. If you don't want it, set `xAxis.axisMinimum = whatever you like`
