### ISSUE TITLE
With Xcode 8.1 can't build

### ISSUE THREAD

**Issue by Shunzi007** [danielgindi/Charts#1786]
> #import <Charts/Charts.h>
It tells "'Charts/Charts.h' file not found" when I use iPhone to debug. However it goes all right when use simulators.

**Comment by cilasgimenez** [comment]
I have the same issue when migrating to xcode 8.1. What i did was remove all Charts files and frameworks and install then using cocoaPods. All went fine after that.

**Comment by liuxuan30** [comment]
try clean and rebuild etc..
