### ISSUE TITLE
ChartLimitLine: How to customize label background and Position center of line

### ISSUE THREAD

**Issue by nhuomtangnextop** [danielgindi/Charts#1787]
ChartLimitLine: How to customize label background and Position center of line

**Comment by liuxuan30** [comment]
we don't support this right now. Take a look at `ChartLimitLine` class and override `open func renderLimitLineLabel` to have a rect to hold the text and your color.

**Comment by aakashtandukar** [comment]
if (maxvalue/2 > 80){
        ChartLimitLine.labelPosition = ChartLimitLabelPositionLeftBottom;
    }else{
       ChartLimitLine.labelPosition = ChartLimitLabelPositionLeftTop;
    }

just at alternative.
