### ISSUE TITLE
"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1"

### ISSUE THREAD

**Issue by azeemali1993** [danielgindi/Charts#1788]
Updated Xcode this morning to 8.1 and was greeted by this lovely error, 
"Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1"

changing "Use Legacy Swift Language Version" to "Yes,No and unspecified"... still will not let me compile. Any ideas?

**Comment by danielgindi** [comment]
Clean and rebuild? We do not provide pre-built binaries, so the binaries were built on your system

**Comment by rohanmurde** [comment]
I tried the 'clean and rebuild' method, but still unable to compile the module. Could you please suggest another method ?

**Comment by masuhara** [comment]
Same issue here
Xcode 8.1
Swift 3.0.1 (Apple Swift version 3.0.1 (swiftlang-800.0.58.6 clang-800.0.42.1))

**Comment by Guzlan** [comment]
I fixed this problem today. 
Go on to your app target and make sure charts is only in "Linked libraries and frameworks" and not in "Embedded Binaries". A better way to do this is remove charts from Linked libraries and embedded binaries, and just re add it to Linked libraries. Clean and build. 

Hope it helps !

**Comment by WilsonCP** [comment]
I'm facing this problem now, Module compile with 2.3 cannot be imported in 3.0.2. I've tried the suggestions above but nothing is working for me. Any help?
