### ISSUE TITLE
Realm update

### ISSUE THREAD

**Issue by kwstasna** [danielgindi/Charts#1789]
Hello.

I normally install pod `Charts/Realm` and i get printed in my terminal that Realm version 1.1.0 is installed.
But realm is updated to 2.0.3

Is any workaround?
I've tried `pod update RealmSwift` but no luck.

**Comment by hardeep** [comment]
This also causes Carthage to hang.

Using the latest version of Realm in my `Cartfile` causes a conflict with Chart's 1.1.0 requirement.

Deleting Realm from the `Cartfile` resolves my issue but I'm left with using Realm 1.1.0.

**Comment by apocolipse** [comment]
We don't use ChartsRealm, but we do use Realm and Charts, and the mismatch makes it impossible to use Carthage entirely.  

I'd strongly encourage you split ChartsRealm into a separate project entirely, CocoaPods is flexible enough for you to support both in 1 repo, but Carthage isn't, and many people prefer it to Pods.

**Comment by danielgindi** [comment]
We've updated to 2.1.1, and we will probably separate ChartsRealm to a separate repo.

Keep track of it here: https://github.com/danielgindi/Charts/issues/1756
