### ISSUE TITLE
PieChart values outside of chart?

### ISSUE THREAD

**Issue by cilasgimenez** [danielgindi/Charts#1790]
Hi everyone. It's not a issue but since the version v2.2.5 theres is an option to set values outside of piechart (connected with a line). I swear i tried to find any hint on how to do that, but i found nothing related to this. I have my chart all setted up and would like to show this lines. Any hint? Thanks!

**Comment by Leinadzet** [comment]
+1

**Comment by danielgindi** [comment]
It's in the demos my friend! There are two pie chart demos, one of this is with lines drawn to the values.

**Comment by cilasgimenez** [comment]
It really is! I didn't noticed the PiePolylineChartViewController.m.
If anybody face this too. Here's the part took from the demo and updated to swift 3:

```
        pieChartDataSet.valueLinePart1OffsetPercentage = 0.7;
        pieChartDataSet.valueLinePart1Length = 0.2;
        pieChartDataSet.valueLinePart2Length = 0.4;
        pieChartDataSet.yValuePosition = .outsideSlice
        pieChartData.setValueTextColor(.black)
```
Thanks danielgindi. If you don't mind, i'd like to ask you, if there's intend to make the demos written in actual swift supported version instead obj-c?
