### ISSUE TITLE
Fix the xAxis to use the values from my dataset 

### ISSUE THREAD

**Issue by sanjay2001** [danielgindi/Charts#1791]
I am unable to set the axis values to be the values that are in my dataset. There doesn't seem to be a way to restrict the behavior where the library does not auto calculate the data point labels to show on x-axis.
If I have [250,500,1000,2000,4000,8000] as X-axis values and some corresponding values to each on Y ...then my chart is not showing the above data points labels on x..it shows some values like ...[125, 1700,3275,4850,6426,8000]....

**Comment by patreu22** [comment]
Did you try 'barChart.drawValueAboveBarEnabled = true' ? It works for me, but my x-axis values are 0...z

**Comment by sanjay2001** [comment]
@patreu22 my issue seem to be more on what values actually get displayed, I wanted to show values exactly as they are in my array ...but after I call  [[LineChartDataSet alloc] initWithValues:values] the resulting data set has data that is different from ,y values i provided...looks like it re-calculates em..

**Comment by liuxuan30** [comment]
@sanjay2001 you are right, `open func computeAxisValues(min: Double, max: Double)` is calculating the x axis range. Take a look at the func and you will know. If you don't like it, set `ForceLabelsEnabled = true`
