### ISSUE TITLE
Histogram Example?

### ISSUE THREAD

**Issue by jscarney** [danielgindi/Charts#1792]
Has anyone figured out how to use this library to generate Histogram charts?  I need something like what you would get from Wolfram alpha (but not so flexible).  I can easily enough total up data occurrences in to bins manually but then need to align the bars to the number grid and specific integer values for x and y axis.

here is example of what you can do with Wolfram alpha

The bin is a range   x<= bin  < y
where bin is equals to or greater than the lower number and less than the upper number. 

![histogramexample](https://cloud.githubusercontent.com/assets/2711660/20033808/fd339286-a366-11e6-8d4d-a3d60fa8c1cc.jpg)

wolfram alpha is more powerful than I need.  Ideally I could
- specific the x an y axis to be integer
- specific the number of bins (bars) that span the range
- have the bars touch
- have the grid lines align with where the bars meet

anyone have any sample code that does any part of this?

**Comment by danielgindi** [comment]
I don't really know what you're talking about, but the screenshot is pretty simple. It's just playing with barWidth, and setting the x values to the correct values.
If you put the first x-value at 40, and make the barWidth 80, you will fill the whole 80 on the x-axis. Or you could set it to just x-value = 2.5 and barWidth = 5, and in the x-value formatter return the values * 20. That's judging from your screenshot where the units are 20.
