### ISSUE TITLE
can we set y axis max value to chart on horizontal bar graphs??

### ISSUE THREAD

**Issue by arunchaitanya24** [danielgindi/Charts#1794]
Need advise to implement this yaxis count to maximum ,so that we can show single horizontal bargraph in 100 scaled view. I used chartYMax but it is readonly property
![simulator screen shot nov 6 2016 3 03 18 pm](https://cloud.githubusercontent.com/assets/13051510/20036605/3797c5ca-a432-11e6-930f-6fa3875a0caa.png)

actually we need to show like this

<img width="533" alt="screen shot 2016-11-06 at 3 04 56 pm" src="https://cloud.githubusercontent.com/assets/13051510/20036617/851bbcfc-a432-11e6-8189-0e06fc0f365e.png">

can you please help on that

**Comment by Jakkawad** [comment]
how to solve this?
