### ISSUE TITLE
Skip Drawing Circles for LineCharts

### ISSUE THREAD

**Issue by denrase** [danielgindi/Charts#1795]
We have encountered a case were we needed to skip the drawing of circles for a line chart. Just using a different colors for those indexes was not sufficient. The solution is implemented simply by providing an array with indexes, which are skipped in the renderer.

```
/// Prevent circle drawing by index.
var circleIndexesNotToDraw: [Int] { get set }
```

**Comment by liuxuan30** [comment]
I am not quite clear, why `dataSet.drawCirclesEnabled` does not work?

**Comment by denrase** [comment]
Hello. I should have elaborated our use-case more clearly, sorry for the confusion and the late answer.

So we are drawing a graph where we just just want to draw some circles, for example maxima, minima, or any point of interest really. 
We have tried to make this work by setting clear color to the `circleColors` indexes that we don't want to draw, which worked fine. However, we also wanted to use the `circleHoleColor`, but it cannot be set as an array. The easy route was to just skip drawing circles that we don't need altogether.
In hindsight, setting `circleHoleColors` as an array would have been better solution.

Is that sufficient as an explanation? I would also take the time to to implement any suggestion that would get merged and cover our use-case. Or maybe there is already a way in the API to achieve this?

![graph_with_points](https://cloud.githubusercontent.com/assets/3984453/20361607/7ebd3094-ac38-11e6-9083-31b2ab0c3859.png)

**Comment by liuxuan30** [comment]
you can subclass and add circle hole colors and override the render method to feed your color.

**Comment by denrase** [comment]
Hey! We have tried it by overriding the render method, but we needed access to internal properties so that didn't work. But we came up with a simpler solution. We just draw two datasets. One with the lines and a second one with the styled circles. Thank you for your time, consider this issue solved. :)

**Comment by liuxuan30** [comment]
hmm.. I guess when you want to subclass, using source code is the best option to get rid of the 'interval' issues, and you have the code and know the details
