### ISSUE TITLE
How to add “%” to data in ios-chart

### ISSUE THREAD

**Issue by OuSS-90** [danielgindi/Charts#1797]
```
private func setChart(pieChartView: PieChartView, values: [Double]) {

    var dataEntries: [ChartDataEntry] = []

    let dataPoints = ["Apr","May","July"]

    for i in 0..<dataPoints.count {
        let dataEntry = PieChartDataEntry(value: values[i], label: dataPoints[i])
        dataEntries.append(dataEntry)
    }

    let pieChartDataSet = PieChartDataSet(values: dataEntries, label: "")
    pieChartDataSet.colors = [UIColor(red: 17/255, green: 128/255, blue: 127/255, alpha: 1.0),UIColor(red: 47/255, green: 164/255, blue: 59/255, alpha: 1.0),UIColor.orange]
    let pieChartData = PieChartData(dataSet: pieChartDataSet)
    pieChartView.data = pieChartData
    pieChartView.centerText = "Amount Spent"
    pieChartView.chartDescription?.text = ""
    pieChartView.usePercentValuesEnabled = true
    pieChartView.legend.horizontalAlignment = .center

}
```
<img width="371" alt="screen shot 2016-11-06 at 5 42 07 pm" src="https://cloud.githubusercontent.com/assets/10999097/20040224/7fdb232c-a44b-11e6-8f1f-27c82da82e5f.png">

How to add "%" in PieChart data ? NSNumberFormatter() is no longer available

**Comment by liuxuan30** [comment]
use `valueFormatter`!

**Comment by OuSS-90** [comment]
Thanks for reply,
I said NSNumberFormatter() is no longer available on swift 3.0

<img width="865" alt="screen shot 2016-11-07 at 10 54 13 am" src="https://cloud.githubusercontent.com/assets/10999097/20055452/ff2eb76e-a4d8-11e6-8b79-18aeff9460ee.png">

**Comment by RahuliOS88** [comment]
How can i set text like this
<img width="340" alt="screen shot 2016-12-28 at 6 31 31 pm" src="https://cloud.githubusercontent.com/assets/24807567/21519976/e54a0b02-cd2b-11e6-94ed-700b6e83a307.png">
?

**Comment by RahuliOS88** [comment]
<img width="340" alt="screen shot 2016-12-28 at 6 31 31 pm" src="https://cloud.githubusercontent.com/assets/24807567/21520005/1d6cd85c-cd2c-11e6-929d-bd858d20c994.png">
