### ISSUE TITLE
Auto scroll xAxis

### ISSUE THREAD

**Issue by SuhailRanger** [danielgindi/Charts#1798]
Hi

I have too many values in xAxis label and i set zoom level as total values/5.0,
now i want to scroll chart upto last page by default and user can scroll left to show older values.

**Comment by tushuaidianzi** [comment]
哎哎哎，一样的问题，改版了，改的差了，不忍直视

**Comment by SuhailRanger** [comment]
Thanks @tushuaidianzi for your reply but i resolved it using "moveViewToX" method of chart.
