### ISSUE TITLE
Zooming X and Y axis independently?

### ISSUE THREAD

**Issue by StGriner** [danielgindi/Charts#1799]
Is it possible to zoom the chart axis x and y independently? Because I am new to iOS development I do not have the knowledge yet to understand everything. Perhaps my requested function is already available or I just have to implement it by myself.
I would appreciate any hint. Thank you very much.

Best regards,
Stefan

**Comment by danielgindi** [comment]
* pinchZoomEnabled
* scaleXEnabled
* scaleYEnabled

You can see it in the demos.
