### ISSUE TITLE
How to change stackbar according to order?

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1803]
Green tag data at the bottom of the column, I want to change the order of the data, let the green in the above, but the legend below order remains the same, how to do?

<img width="367" alt="2016-11-08 4 28 28" src="https://cloud.githubusercontent.com/assets/8415820/20092068/03e2a63c-a5d1-11e6-88bb-251810eda88f.png">

I want 
First data index of an array of stack bar into the back, in turn from top down, rather than from down to up

**Comment by liuxuan30** [comment]
Have you tried reverse the order of the values when you add them? I remember it should work.
