### ISSUE TITLE
Swift 3 BarChart with image and title. 

### ISSUE THREAD

**Issue by farazhaider88** [danielgindi/Charts#1807]
iam using swift 3.0 there are two queries regarding this on barchart. 

1> i need to add string label in bar chart inside each chart, the function i previously using accepting only data but not string of titles.
2> i need to draw image at the end of each chart like below screenshot.

<img width="308" alt="screen shot 2016-11-08 at 10 27 19 pm" src="https://cloud.githubusercontent.com/assets/1468654/20109664/ef9be8f0-a602-11e6-9916-d5d6443fbda1.png">

**Comment by liuxuan30** [comment]
1. disable `drawBarShadowEnabled`
2. use `ChartMarker`

**Comment by muzamilhassan1987** [comment]
Will you please share some example difficult to implement

**Comment by liuxuan30** [comment]
Check out ChartsDemo, there are many

**Comment by nrvraghu** [comment]
![simulator screen shot sep 2 2017 10 40 51 am](https://user-images.githubusercontent.com/7722031/29993118-524bf564-8fcb-11e7-9ad7-433e0ba62757.png)
Is it possible to display images instead of text ("Jan")
Please help me on this

**Comment by liuxuan30** [comment]
currently No, but you can easily tweak some methods to do so
