### ISSUE TITLE
3.0.0 - adding X Values to LineChartData no longer supported?

### ISSUE THREAD

**Issue by adriansoghoian** [danielgindi/Charts#1808]
Hello, 

I'm migrating from 2.2.4 to 3.0.0 and am having issues adding xValues (strings in my case) to the chartData object. Previously I was able to do:

```
// yData: [Double]
// xData: [String]

// Adds in y-value entries to the dataset
for i in 0..<ydata.count { 
    let dataEntry = ChartDataEntry(value: ydata[i], xIndex: i)
    self.lineChartDataSet!.addEntry(dataEntry)
}
        
// Adds dataset to the ChartData object
self.lineChartData!.addDataSet(self.lineChartDataSet)
        
// Adds in string x-values for corresponding indices
for i in 0..<xdata.count {
    self.lineChartData!.addXValue(xdata[i])
}
```

It seems like the process for adding in xValues has changed (which is my case are date strings, like "Jan 20"). 

I've scoured the documentation and release notes and have been banging my head on this for awhile. Does anyone have any guidance for how to implement this in 3.0.0? 

Thanks very much!

**Comment by shorbenko** [comment]
Have you tried solution from #https://github.com/danielgindi/Charts/issues/1800?

**Comment by adriansoghoian** [comment]
Nope I hadn't, thanks very much for referring me. Closing this out.

**Comment by liuxuan30** [comment]
You can't in 3.0. It behaves like y axis now.

**Comment by adriansoghoian** [comment]
Note that if you have a chart that needs to dynamically redraw a new set of points (and corresponding string x-values), calling `notifyDataSetChanged` on the ChartView no longer worked. 

Instead, before supplying the new data I call `lineChartView.clearValues()` and this seems to work. I suspect there's a performance penalty but if there is, it's not noticeable for my use case. 

Hope this helps someone!
