### ISSUE TITLE
Can we make a 3D Barchart with this Library??

### ISSUE THREAD

**Issue by dileep017** [danielgindi/Charts#1809]
I want a 3D Barchart like the attachment.Please let me know if it possible.
<img width="365" alt="screen shot 2016-11-09 at 12 13 21 am" src="https://cloud.githubusercontent.com/assets/22934269/20112189/5fa3bfe8-a611-11e6-9253-77b5e2608c09.png">

**Comment by liuxuan30** [comment]
Currently no. Coregraphics does not work too.
