### ISSUE TITLE
Can i customize the X axis text a different color?

### ISSUE THREAD

**Issue by yushan023** [danielgindi/Charts#1810]
Can i customize the X axis text a different color?
For example：
![image](https://cloud.githubusercontent.com/assets/20593532/20125830/30043a24-a66b-11e6-8425-da5dee69023e.png)

![image](https://cloud.githubusercontent.com/assets/20593532/20125851/5d3d7d20-a66b-11e6-9082-b2f961c525d4.png)
![image](https://cloud.githubusercontent.com/assets/20593532/20125852/651470e4-a66b-11e6-80ec-67f4b550aba4.png)
I only did this custom text followed the demo, I don't know how to set up a different color

**Comment by lightwindy** [comment]
你应该用 "xAxis.labelTextColor = CQTextLightColor; "去改变label的颜色。
You should use "xAxis.labelTextColor = CQTextLightColor;" to change the label color.

**Comment by yushan023** [comment]
...  你看懂我的表达了吗？我不是不知道设置颜色的属性。我的问题是自定义，label设置不同的颜色。Did you read my expression?Not that I don't know set color properties.My problem is the custom, the label set a different color.

**Comment by lightwindy** [comment]
现在明白你的意思了，不同的xAxis值对应不同颜色的label. 应该是用valueFormatter, 但我不知道怎么弄。
Now I understand your meaning. Different xAxis value has different color. You should use valueFormatter do it. but I don't know how to do it.

**Comment by yushan023** [comment]
valueFormatter  只是让用户定义值而已

**Comment by liuxuan30** [comment]
don't you see 
```
open class AxisBase: ComponentBase
{
    public override init()
    {
        super.init()
    }
    
    /// Custom formatter that is used instead of the auto-formatter if set
    fileprivate var _axisValueFormatter: IAxisValueFormatter?
    
    open var labelFont = NSUIFont.systemFont(ofSize: 10.0)
    open var labelTextColor = NSUIColor.black
```
