### ISSUE TITLE
Line Chart: how to change background color through every odd label on YAxis?

### ISSUE THREAD

**Issue by SergeyGamayunov** [danielgindi/Charts#1812]
When I use `.setLabelCount(4, force: true)` I got a certain amount labels on YAxis. But how do I paint background through every odd label? Something like that:

![default](https://cloud.githubusercontent.com/assets/14821368/20134740/9c83f1be-a67d-11e6-8352-9ce7d64a06e8.png)

**Comment by liuxuan30** [comment]
You have to override some methods to get it done. There was a topic about the same thing for x axis:https://github.com/danielgindi/Charts/issues/645. There is a sample code in the issue.

**Comment by SergeyGamayunov** [comment]
@liuxuan30 Great solution, big thanks! 

PS What do you think would it work if I'll create extension for LineChartView instead of overriding method?

**Comment by liuxuan30** [comment]
I would choose overriding, because you don't have insert your extension
