### ISSUE TITLE
Updated Demo Example for swift3

### ISSUE THREAD

**Issue by farazhaider88** [danielgindi/Charts#1815]
is there any good tutorial for Bar chart with markers for swift 3, since most of the functions are changed, can we have now updated tutorials or demo example covering swift only.

i read "Charts with Swift 3 in iOS 10 (Sami Korpela)" but still it is not as helpful as i wish. Demo examples in Swift will be much great. 

thanks in advance..

**Comment by liuxuan30** [comment]
Check release notes. I think reading the code is the best way, since all info is there. It's just about redesign x axis, and works in similar way. The demo is updated too... I don't know why you ask about the marker.
