### ISSUE TITLE
What is the replacement for  xVals for  BarChartData? in swift 3.0

### ISSUE THREAD

**Issue by Aungbandlab** [danielgindi/Charts#1816]
BarChartData(xVals: dataPoints, dataSet: chartDataSet)

**Comment by Aungbandlab** [comment]
found the way thanks

**Comment by fnk0** [comment]
@Aungbandlab what is the way?

**Comment by diogoAntunes** [comment]
```
let labels = ["Label 1", "Label 2"]
chartView.xAxis.valueFormatter = DefaultAxisValueFormatter {
    return labels[Int($0)]
}
```

**Comment by Aungbandlab** [comment]
// MARK: axisFormatDelegate
extension StackBarChartCell: IValueFormatter {
    
    func stringForValue(_ value: Double,
                        entry: ChartDataEntry,
                        dataSetIndex: Int,
                        viewPortHandler: ViewPortHandler?) -> String {
        return String(format: "%.0f", value)
    }
}
