### ISSUE TITLE
LimitLine Label Value Overlap with BarChartData Label

### ISSUE THREAD

**Issue by perwyl** [danielgindi/Charts#1817]
<img width="103" alt="screen shot 2016-11-10 at 1 17 13 pm" src="https://cloud.githubusercontent.com/assets/1456117/20165427/0d5dec1c-a748-11e6-974f-2eadbd40ac87.png">

What settings should i change to 
1. extend the `LimitLine`beyond the xAxis/chart so that the limit label is visible and not blocked by the Chart Bars  or 
2. set some paddings before and after the `Chart Bars` and the length of `LimitLine` is not affected

I tried
- Setting the `ChartLimitLine.xOffset` and `ChartLimitLine.yOffset`, label will be chopped off 
- Setting `ChartView.clipsToBound', has no effect 

Thanks!

**Comment by liuxuan30** [comment]
I think it's not as easy as you think. There is always a chance the a bar value label overlaps with the limit line label if you put limit line label inside the chart. I would like to put them outside of the contentRect.
Currently we don't support this. I suggest you override `open override func renderLimitLines()` to adjust those offsets to meet your needs.

**Comment by gaborhertelendy** [comment]
Comment out the line below in xAxisRenderer.
Clean build folder and re-build.
Set the yOffset you want for the limit line label to push it out of contentRect.
No need for that clip, the limit line will stroke inside the contentRect. This way the label can be drawn outside. 

```
open override func renderLimitLines(context: CGContext)
    {
        guard
            let xAxis = self.axis as? XAxis,
            let transformer = self.transformer,
            !xAxis.limitLines.isEmpty
            else { return }
        
        let trans = transformer.valueToPixelMatrix
        
        var position = CGPoint(x: 0.0, y: 0.0)
        
        for l in xAxis.limitLines where l.isEnabled
        {
            context.saveGState()
            defer { context.restoreGState() }
            
            var clippingRect = viewPortHandler.contentRect
            clippingRect.origin.x -= l.lineWidth / 2.0
            clippingRect.size.width += l.lineWidth
//            context.clip(to: clippingRect)
            
            position.x = CGFloat(l.limit)
            position.y = 0.0
            position = position.applying(trans)
            
            renderLimitLineLine(context: context, limitLine: l, position: position)
            renderLimitLineLabel(context: context, limitLine: l, position: position, yOffset: 2.0 + l.yOffset)
        }
    }
```
