### ISSUE TITLE
How to set multiple Stackbar with Charts 3

### ISSUE THREAD

**Issue by PreechaS** [danielgindi/Charts#1819]
#1801 I can't figure out how to do it in Charts 3. 
It used to work well with the previous version of iOS-charts.(swift 2)

This is sample code and output so you may can tell me what is wrong.

        for i in 0..<12 {
            let value = Double(i)
            let attempt = BarChartDataEntry(x: value, y: value)
            attemptEntries.append(attempt)
            let result = BarChartDataEntry(x: value, yValues: [2*value, 3*value])
            resultEntries.append(result)
        }
        let attemptDataSet = BarChartDataSet(values: attemptEntries, label: Constants.Chart.TotalAttempt.Label)
        let resultDataSet = BarChartDataSet(values: resultEntries, label: Constants.Chart.Result.Label)

        let dataSets = [attemptDataSet, resultDataSet]
        let barData = BarChartData(dataSets: dataSets)

        chartView.data = barData

![simulator screen shot nov 9 2559 be 3 02 09 pm](https://cloud.githubusercontent.com/assets/17841404/20131101/ea29f0f2-a68d-11e6-9777-0691d83c9c89.png)

**Comment by liuxuan30** [comment]
Dup. #1801
