### ISSUE TITLE
BarChart moveToX wrong

### ISSUE THREAD

**Issue by anhtth** [danielgindi/Charts#1820]
Hi, 
I have an issue, I have 15 X, and one X has 3 barchart, I have change visible X (max = 1 and min = 1) so the chart can scroll, but when I call moveToX(11), the chart only scroll to X at index 3,  if I change, moveToX(46) it will move to index 11. Please help me. 
Tks alot

**Comment by liuxuan30** [comment]
I tried with ChartsDemo, it works fine.
Some thing to note:
1. 
>  Limits the maximum and minimum value count that can be visible by pinching and zooming.
  e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
  at once without scrolling.
  If you call this method, chart must have data or it has no effect.

So make sure you call it after you set chart data.

2. you have to move x + 11, not just 11. Chart 3.0 x axis is no longer index based.
