### ISSUE TITLE
Its possible change the thickness of the pie chart?

### ISSUE THREAD

**Issue by EmersonCarpes** [danielgindi/Charts#1822]

**Comment by cuddle-sujeet** [comment]
How did you changed the thickness of pie chart? I am also facing the same issue..
Thanks

**Comment by EmersonCarpes** [comment]
Yeah, just change the value of **chart.holeRadiusPercent = 0.7**

**Comment by cuddle-sujeet** [comment]
Thanks @EmersonCarpes
