### ISSUE TITLE
Help  ?    

### ISSUE THREAD

**Issue by MonkeyRing** [danielgindi/Charts#1823]
### How can I make it and a chart in the screenshot?       Somebody help me?  

<img width="917" alt="2016-11-11 2 43 20" src="https://cloud.githubusercontent.com/assets/8415820/20207055/9ec97252-a81f-11e6-81fd-f901cede5648.png">

**Comment by danielgindi** [comment]
I'm guessing you haven't looked at the demos, as everything is in there. 
Please take a look at the demo, and do not post issues with non-informative titles.

**Comment by MonkeyRing** [comment]
I have to see the demo, but the inside of the demo API did not achieve what I want effect, so, I'm a little overwhelmed, I'm sorry

**Comment by liuxuan30** [comment]
It's just a grouped + stacked bar chart, and some small lines for x axis. Just tweak the x axis renderer's `drawGridLines()`.

**Comment by MonkeyRing** [comment]
hmm, I have already solved.  thx :)
