### ISSUE TITLE
y axis label show wiered value 1.11022302462516e- when passed 0 as value

### ISSUE THREAD

**Issue by djprjpt** [danielgindi/Charts#1825]
i am passing 0 as a value but this y label shows wiered value in screenshot attached.

![screen shot 2016-11-11 at 7 15 53 pm](https://cloud.githubusercontent.com/assets/12673090/20216920/55d37ff6-a843-11e6-8846-ba805e19bbb7.png)

**Comment by djprjpt** [comment]
i am using library version 2.5.1 (2.3.0)

**Comment by liuxuan30** [comment]
Have you provide any value formatter? It should not happen. Please debug `computeAxisValues()` to see what values for the y axis, and debug `drawLabels` in y axis renderer to see how this weird number is generated by the formatter.

**Comment by djprjpt** [comment]
yes i have provided value formatter. Thanks providing the `axisMinValue` solved my issue. 
Thanks for response.
