### ISSUE TITLE
Gradient Background for LineChart. (Not Working)

### ISSUE THREAD

**Issue by iAviatorJose** [danielgindi/Charts#1826]
I tried the below Code 

```
  let colorTop =  UIColor(red: 255.0/255.0, green: 149.0/255.0, blue: 0.0/255.0, alpha: 1.0).CGColor
        let colorBottom = UIColor(red: 255.0/255.0, green: 94.0/255.0, blue: 58.0/255.0, alpha: 1.0).CGColor
        let gradientLayer = CAGradientLayer()
        gradientLayer.colors = [ colorTop, colorBottom]
        gradientLayer.locations = [ 0.0, 1.0]
        gradientLayer.frame = self.lineChartView.bounds
        lineChartView.layer.addSublayer(gradientLayer)

```
And ended up having a View where the gradient layer Hidding the lineChart.

Is it possible to have gradient backgrounds.

**Comment by liuxuan30** [comment]
May I ask what is "Not Working" for the library? I don't remember it support gradient background.. Another fact is, you are addinga gradient layer into the chart view, so you should check the layer stack and opaque/alpha property of your view, to make sure your layer can be seen.
