### ISSUE TITLE
Horizontal bar chart doesn't start at 0

### ISSUE THREAD

**Issue by SergeyGamayunov** [danielgindi/Charts#1827]
When I provide data for Bar Chart it appears with little offset. I thought about stacked Bar Chart, but it was wrong - that how I provide sample data for chart:

```
var barEntries = [BarChartDataEntry]()
barEntries.append(BarChartDataEntry(x: 0, y: 0))
barEntries.append(BarChartDataEntry(x: 4, y: 1))
barEntries.append(BarChartDataEntry(x: 8, y: 24))
barEntries.append(BarChartDataEntry(x: 12, y: 37))
barEntries.append(BarChartDataEntry(x: 16, y: 27))
barEntries.append(BarChartDataEntry(x: 20, y: 11))

let barDataSet = BarChartDataSet(values: barEntries, label: nil)
let barData = BarChartData(dataSet: barDataSet)
barData.barWidth = 4
barChartView.data = barData


```
All `barEntries` was created with `BarChartDataEntry` initializers for non-stacked bar. Now I have no idea why bar doesn't start at 0.

![2016-11-11_12-59-51](https://cloud.githubusercontent.com/assets/14821368/20258882/e1229d3c-aa62-11e6-9268-281a89ddca57.png)

PS I asked the same question in stackoverflow.com - you can provide your answer anywhere you want, here's the link: http://stackoverflow.com/questions/40545768/horizontal-bar-chart-doesnt-start-at-0

**Comment by liuxuan30** [comment]
try set xAxis.axisMinimum = 0

**Comment by SergeyGamayunov** [comment]
Thanks, you're almost right.

To move all bars to zero, we need set both:

```
barChartView.rightAxis.axisMinimum = 0.0
barChartView.leftAxis.axisMinimum = 0.0
```

It seems a little strange because as you can see I switched off left axis (actually with horizontal bar chart it is "top" axis)
