### ISSUE TITLE
A problem of CombinedChartView's YAxis

### ISSUE THREAD

**Issue by brxren** [danielgindi/Charts#1830]
I think there might be a problem with the YAxis of CombinedChartView.

I have a CombinedChartView with one bar and one line. 
The bar depends on the left YAxis.
The line depends on the right YAxis.
After the dependencies are well configured, I get the chart below, which is definitely not what I want.
The labels of the left YAxis and the right YAxis are the same even though y values are totally different.
I'm not sure if it's designed like that intentionally. If so, just ignore what I say below.

![simulator screen shot 2016 11 14 8 56 22](https://cloud.githubusercontent.com/assets/2941552/20265634/2cc3db94-aaad-11e6-98d2-45f0be4023e5.png)

I am confused, so I review the source code. Finally I find a problem of the function calcMinMax() in CombinedChartData.swift.

            if data.yMax > _leftAxisMax
            {
                _leftAxisMax = data.yMax
            }

            if data.yMin < _leftAxisMin
            {
                _leftAxisMin = data.yMin
            }

            if data.yMax > _rightAxisMax
            {
                _rightAxisMax = data.yMax
            }

            if data.yMin < _rightAxisMin
            {
                _rightAxisMin = data.yMin
            }

It seems that dataset's ydependency is NOT considered at all. So I change it.

            for i in 0 ..< sets.count
            {
                let dataset = sets[i]
                if dataset.axisDependency == .left
                {
                    if dataset.yMax > _leftAxisMax
                    {
                        _leftAxisMax = dataset.yMax
                    }
                    if dataset.yMin < _leftAxisMin
                    {
                        _leftAxisMin = dataset.yMin
                    }
                } else { // right
                    if dataset.yMax > _rightAxisMax
                    {
                        _rightAxisMax = dataset.yMax
                    }
                    if dataset.yMin < _rightAxisMin
                    {
                        _rightAxisMin = dataset.yMin
                    }
                }
            }

Now I get what I want.

![simulator screen shot 2016 11 14 8 55 02](https://cloud.githubusercontent.com/assets/2941552/20265620/1b0a0fcc-aaad-11e6-86e2-191e1bd94365.png)

I think it might be helpful to someone like myself.

**Comment by liuxuan30** [comment]
To me, I would say setting up `axisDependency` can solve it.

**Comment by brxren** [comment]
I've set up axisDependency, but it seems it doesn't work. As far as I know, it doesn't work in CombinedChartView. Other charts work well.

**Comment by liuxuan30** [comment]
I checked your issue, it seems like you are correct. Waiting for @danielgindi. I used combined chart in 2.x version, and it work like your way. I didn't check in Chart 3.0

**Comment by brxren** [comment]
OK, thank you so much.

**Comment by vaibhav-varshaaweblabs** [comment]
Same here, Combined Chart (Bar and Line) user to work smoothly in 2.x. Shows errors in 3.x

![screen shot 2016-11-16 at 10 02 09 am](https://cloud.githubusercontent.com/assets/21377276/20334886/c8559732-abe3-11e6-9ff9-63b6596451d9.png)

**Comment by liuxuan30** [comment]
@vaibhav-varshaaweblabs don't put irrelevant issues here. It's your code that's not compatible with 3.0 APIs.

**Comment by liuxuan30** [comment]
@brxren I guess you already found the root cause and fix? Mind to file a PR?

**Comment by brxren** [comment]
@liuxuan30 Should I wait for @danielgindi 's response?
BTW,  I'm a rookie here. Would you like to tell me what 'PR' is short for and how to file it?

**Comment by liuxuan30** [comment]
PR = pull requests. I feel it's like a bug.. but we could also wait :)

**Comment by brxren** [comment]
OK, got it.
I think it's not urgent. I have fixed it in my source code.
BUT I'm not sure if it will cause other problems, so waiting for @danielgindi is better.

**Comment by Rnorback** [comment]
Having this issue as well, will try brxren's fix.

**Comment by gGololicic** [comment]
I confirm having the same bug and it worked in previous versions (<3.0).
