### ISSUE TITLE
X-Axis for different different charts

### ISSUE THREAD

**Issue by chandni-solanki** [danielgindi/Charts#1831]
I have two charts one is Bar chart and another is Combined Chart in single screen. Both charts have their own x-axis like Bar chart has string value Jan to Dec for x-axis. And Combined chart has different string value like aaa,bbb,ccc etc.
Not getting idea from chart demo.

How to implement this with latest code?
Anyone can help me?

Thank you.

**Comment by liuxuan30** [comment]
I don't know what's the problem that you already have two chart views.. one is bar chart and one is combined chart.. they have their own x axis..
