### ISSUE TITLE
Error when adding embedded binaries

### ISSUE THREAD

**Issue by BazM01** [danielgindi/Charts#1832]
I have followed the 3rd party tutorial and everything works fine.

However I also have another working app and I am trying to add a graph to it. When I add the embedded binaries my project will no longer build and I get the error message...

clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas?

Thanks

**Comment by liuxuan30** [comment]
No idea only with your wild error message. Follow README carefully.
