### ISSUE TITLE
How to hide BarChart hide bottom  description  color & text ?

### ISSUE THREAD

**Issue by Aungbandlab** [danielgindi/Charts#1835]
https://camo.githubusercontent.com/78b4bc4e50e151970961daf56e81c4c0db72d27c/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d5043686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f6261726368617274332e706e67

**Comment by liuxuan30** [comment]
xAxis.drawLabelsEnabled = false; 
chartView.legend.enabled = false
