### ISSUE TITLE
Migration to Swift 3.x

### ISSUE THREAD

**Issue by vaibhav-varshaaweblabs** [danielgindi/Charts#1836]
I'm converting my Swift 2.x code to Swift 3.x. Following is my code snippet for which I'm facing errors.
Please help

```
@IBOutlet weak var chartView: CombinedChartView!
chartView.delegate = self;
chartView.chartDescription?.text = ""
chartView.noDataTextDescription = "You need to provide data for the chart."
```
Error on line - `chartView.noDataTextDescription`

```
let chartData = CombinedChartData()
chartData.xVals = dates
```

Error on line - `chartData.xVals`

**Comment by liuxuan30** [comment]
You shouldn't covert by yourself unless you know what you are dealing with. Why not just pick up the master branch?

**Comment by vaibhav-varshaaweblabs** [comment]
I have used the latest Charts library from `pod 'Charts'`

**Comment by liuxuan30** [comment]
Oh I see. It's your code xVals = ... does not exist anymore. Use the latest APIs and read the release notes! The x axis is redesigned, so the x stuff changed a lot.
