### ISSUE TITLE
How to use charts library in my objective c program?..

### ISSUE THREAD

**Issue by tamilanmanikandan** [danielgindi/Charts#1837]
i just wanna use chart library in my objective c program.. i need clear documentation to use chart library... kindly help me out from my problem...
That read me file i can't understand...

**Comment by liuxuan30** [comment]
It's the most basic requirement for a developer to understand README. Or how can we commnuicate if you can't understand README? The demo is written in Objective-C as well.
PLEASE AT LEAST take a look the folder name.. and README
