### ISSUE TITLE
Unable to subclass

### ISSUE THREAD

**Issue by ghost** [danielgindi/Charts#1838]
He there.
I wanted to create my own custom class from the BarLineChartViewBase. However I am unable to override the initialize function. Is there any other way through which I can achieve it?
Thanks.

**Comment by liuxuan30** [comment]
it's already public, so we don't know why you say can't override. You should check swift initialization doc to know the safety checks.

**Comment by vsujan92** [comment]
That means I need to make change in the framework itself as per my requirement for subclassing?

**Comment by liuxuan30** [comment]
@vsujan92 you can add charts source code into the library, and subclass them in your project should be fine. I am doing it also.
