### ISSUE TITLE
Radar charts custom labels

### ISSUE THREAD

**Issue by chipp** [danielgindi/Charts#1840]
Custom radar chart labels are broken.
I added this code to `ChartsDemo-OSX/ChartsDemo-OSX/Demos/RadarDemoViewController.swift`:
```swift
data.setLabels("a", "b", "c", "d", "e", "f", "g", "h", "k")
```

but RadarChartView ignores these labels.
<img width="612" alt="screenshot 2016-11-16 23 07 48" src="https://cloud.githubusercontent.com/assets/115227/20364595/c51191d6-ac54-11e6-94c4-b16131dcc5f2.png">

I think problem is in this line: [XAxisRendererRadarChart.swift#L57](https://github.com/danielgindi/Charts/blob/master/Source/Charts/Renderers/XAxisRendererRadarChart.swift#L57)

`XAxisRendererRadarChart` ignores `RadarChartData.labels` property.

**Comment by liuxuan30** [comment]
I think you should use valueFormatter to do that. Labels are just labels sometimes.

**Comment by chipp** [comment]
```swift
/// Sets labels that should be drawn around the RadarChart at the end of each web line.
    open var labels: [String]
```
ok...

**Comment by liuxuan30** [comment]
@chipp lol. ackward. But the code tells everthing :(

**Comment by tlimp** [comment]
any news here?

**Comment by chipp** [comment]
@tlimp this is my production solution:

```swift
chartView.xAxis.valueFormatter = RadarChartXValueFormatter(withLabels: labels)
```

```swift
class RadarChartXValueFormatter: NSObject, IAxisValueFormatter {

  init(withLabels labels: String...) {
    self.labels = labels
    super.init()
  }

  init(withLabels labels: [String]) {
    self.labels = labels
    super.init()
  }

  var labels: [String]

  func stringForValue(_ value: Double, axis: AxisBase?) -> String {
    let index = Int(value)
    return labels.indices ~= index ? labels[index] : ""
  }

}
```

**Comment by tlimp** [comment]
thanks, for the help. at least it renders the labels. but it also renders a large white space left and right padding/margin, so the chart gets illegible. margin/padding are much larger than needed by the labels
in a previous version (2.2.3 I guess) it worked as expected, making the chart as large as possible so the labels where still readable.

**Comment by lingzlu** [comment]
same issue here, have labels with roughly 10 characters and it's shrinking the chart a lot sometimes the chart is not readable at all :(

**Comment by mamilov** [comment]
The issue with white spaces is still present! Does anyone know how to remove those?
![image](https://user-images.githubusercontent.com/62982104/120191017-abf71600-c219-11eb-9ebf-40d835e22f4a.png)
