### ISSUE TITLE
Removing red selector cross on Line Chart nodes

### ISSUE THREAD

**Issue by jackalcool** [danielgindi/Charts#1844]
I'm trying to remove the red selector cross that appears when a LineChart node is selected but I haven't found any method / parameter to set to achieve this. It would be useful to explain how to remove that red selector, do you have any suggestions?

![chart](https://cloud.githubusercontent.com/assets/23527242/20395164/4807129a-ace2-11e6-84c5-7d1ca2412180.jpg)

**Comment by liuxuan30** [comment]
verticalHighlightIndicatorEnabled = false
horizontalHighlightIndicatorEnabled
