### ISSUE TITLE
Can not show decimal in y value on BarChart

### ISSUE THREAD

**Issue by Canmmy** [danielgindi/Charts#1848]
I had store my value in core data and display it at BarChart.
My category amount is in 8.5 and 420.10.

But the display at Bar Chart is 8 and 420.
How should I set the value in decimal?

![screenshots](https://cloud.githubusercontent.com/assets/6735523/20416281/da9f6634-ad78-11e6-9323-b5b6b4c8cb26.png)

**Comment by liuxuan30** [comment]
use valueFormatter.
