### ISSUE TITLE
Legend under the bar in bar Chart

### ISSUE THREAD

**Issue by satan87** [danielgindi/Charts#1850]
Hello,
I'm drawing a bar chart but the legend is not right under the bar ..
but i have
![image](https://cloud.githubusercontent.com/assets/5104971/20420134/79b94e10-ad29-11e6-8225-195cf29324a1.png)

and i would liek something like:
![image](https://cloud.githubusercontent.com/assets/5104971/20420130/705569f8-ad29-11e6-90d2-fdf8f8bee170.png)

Any idea how can i ahve the legend right under the right bar ?

Thanks,
Nico

**Comment by liuxuan30** [comment]
legend and x axis labels are totally different. You are asking for x axis label.
