### ISSUE TITLE
Issue with candle stick when used in combined chart

### ISSUE THREAD

**Issue by vsujan92** [danielgindi/Charts#1858]
Hello there.
When i tried to use combined chart with a line graph and candle stick graph, the first candle stick is drawn just half in the 0th index in x-axis.
<img width="510" alt="screen shot 2016-11-21 at 1 15 07 pm" src="https://cloud.githubusercontent.com/assets/19152943/20474093/dfdd3f2e-afec-11e6-81f7-aea8dfd32389.png">

How can I solve it?

**Comment by liuxuan30** [comment]
check https://github.com/danielgindi/Charts/issues/1717
