### ISSUE TITLE
Customize X-axis and grid lines

### ISSUE THREAD

**Issue by vsujan92** [danielgindi/Charts#1859]
Hello there.

Is there a way so that I can achieve like this?
<img width="641" alt="screen shot 2016-11-21 at 1 50 39 pm" src="https://cloud.githubusercontent.com/assets/19152943/20475011/a585768e-aff1-11e6-93a4-1e083a35f33e.png">

Here I want to plot two values for candle and line graph with respect to a single x-label. Similarly I want to draw grid lines just after the two points.

**Comment by liuxuan30** [comment]
No, this library does not support this. the bars are simply grouped bars with centerLabelsEnabled. However, the line does not support this.
