### ISSUE TITLE
Pie chart touch event conflict

### ISSUE THREAD

**Issue by AdityaDeshmane** [danielgindi/Charts#1860]
I am facing one issue with PieChart, I have added a button below pie chart (not inside pie chart view) but only bottom half of button is clickable. I figured out, it is due to pan gesture of pie chart which is conflicting with a button tap. Rightmost part of the button is completely clickable as pie chart ends before that.

**Comment by liuxuan30** [comment]
I wonder the button and the whole pie chart view has some overlap? Have checked the responder chain and view hierarchy?

**Comment by AdityaDeshmane** [comment]
![screen shot 2016-11-22 at 5 27 23 pm](https://cloud.githubusercontent.com/assets/6099412/20523105/92a017a2-b0d9-11e6-88de-58c56d531811.png)
Part of area below chart and legend is not clickable
