### ISSUE TITLE
Detect when finger leaves the chart area

### ISSUE THREAD

**Issue by jackalcool** [danielgindi/Charts#1861]
I have an instance of LineChartView and I'd like to know how to detect when a finger leaves the screen when swiping, dragging or moving in the chart area.

Currently I'm able to use a TapGestureRecognizer but it works only for single taps. Currently when I move the finger across the chart area among the various chart nodes I'm able to get multiple chartValueSelected() calls which is what I want, but how can I detect when the user is no more holding his finger on the chart area?

**Comment by liuxuan30** [comment]
I think you can detect the state:`UIGestureRecognizerStateEnded`, `UIGestureRecognizerStateCancelled`, `UIGestureRecognizerStateFailed`, `UIGestureRecognizerStateRecognized`
