### ISSUE TITLE
Realtime Scatterplot crashes when each ChartDataEntry is added dynamically on ScatterView.data

### ISSUE THREAD

**Issue by vaggos666** [danielgindi/Charts#1863]
Hello. Coming back to realtime plots I get the following error 

*"fatal error: Double value cannot be converted to Int because it is either infinite or NaN"* 

when trying to plot in real time using the following code. Please note that if I remove the comments from **func updateChartWithData(receivedData: Double)** and set each time a new **scatterView.data = chartData** everything works almost correctly (At least it does note crash) but I am losing the formating of the chart since I create all the time a new one, wheras if am adding a point each time using **scatterView.data?.addEntry(dataEntry, dataSetIndex: 0)** it crashes when **scatterView.setVisibleXRange( minXRange: 1, maxXRange: 100)** is set. 
Any help will be appreciated!

```
//TIMER generating random numbers for plotting....
myDataGeneratorTimer = Timer.scheduledTimer(timeInterval: 0.01, target: self , selector: #selector(updateValue), userInfo: nil, repeats: true)

// CODE for REAL-TIME plot
    func realtimePlot() {
        //generic chart config
        scatterView.delegate = self
         scatterView.chartDescription?.textColor = UIColor.white
        scatterView.gridBackgroundColor = UIColor.darkGray
        scatterView.noDataText = "No data provided"
        scatterView.drawGridBackgroundEnabled = true
        scatterView.rightAxis.enabled = false
        scatterView.doubleTapToZoomEnabled = false
        scatterView.legend.enabled = false
        
        //configure xAxis
        scatterView.xAxis.labelPosition = .bottom
        
        //configure yAxis
        scatterView.zoom(scaleX: 1.0, scaleY: 1.0, x: 0.0, y: 0.0)
        
        let set_a: ScatterChartDataSet = ScatterChartDataSet(values: [ChartDataEntry](), label: "Intensity")
        
        set_a.axisDependency = .left
        set_a.setColor(UIColor.red) // our circle will be dark red
        set_a.setScatterShape(.circle)
        set_a.scatterShapeSize = CGFloat(4.0)
        set_a.highlightColor = UIColor.white
        set_a.drawValuesEnabled = false
        
        scatterView.data = ScatterChartData( dataSets: [set_a])
    }

func updateValue() {
        //Random float generator
        let artficialData = (Float(arc4random()) / 0xFFFFFFFF) * (100.0 - 0.0) + 0.0
        self.updateChartWithData(receivedData: Double(artficialData))
    }

    var i = 0
    //var dataEntries: [ChartDataEntry] = []
    func updateChartWithData(receivedData: Double) {

        let dataEntry = ChartDataEntry(x: Double(i), y: Double(receivedData))
       
        //dataEntries.append(dataEntry)
        
        //let chartDataSet = ScatterChartDataSet(values: dataEntries, label: "Data received")
        //let chartData = ScatterChartData(dataSet: chartDataSet)
        //scatterView.data = chartData
       
        scatterView.data?.addEntry(dataEntry, dataSetIndex: 0)

        scatterView.setVisibleXRange( minXRange: 1, maxXRange: 100)
        scatterView.notifyDataSetChanged()
        scatterView.moveViewToX(Double(i))
        i += 1
    }
```

**Comment by liuxuan30** [comment]
first, read the comment:
```
    /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    ///
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    open func setVisibleXRange(minXRange: Double, maxXRange: Double)
```
Then, try this:
```
        scatterView.data = chartData // if you comment it out, make sure you set it somewhere
        scatterView.notifyDataSetChanged()
        scatterView.setVisibleXRange( minXRange: 1, maxXRange: 100)
        scatterView.moveViewToX(Double(i))
```

**Comment by vaggos666** [comment]
Just changing the order of *scatterView.notifyDataSetChanged()* and *scatterView.setVisibleXRange( minXRange: 1, maxXRange: 100)* did the job!

Thanks a lot.

Vangelis


On 22 Nov 2016, at 03:42, Xuan <notifications@github.com<mailto:notifications@github.com>> wrote:


first, read the comment:

    /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    ///
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    open func setVisibleXRange(minXRange: Double, maxXRange: Double)


Then, try this:

        scatterView.data = chartData // if you comment it out, make sure you set it somewhere
        scatterView.notifyDataSetChanged()
        scatterView.setVisibleXRange( minXRange: 1, maxXRange: 100)
        scatterView.moveViewToX(Double(i))

**Comment by liuxuan30** [comment]
glad to here that.
