### ISSUE TITLE
custom  gradient color of BarChatView

### ISSUE THREAD

**Issue by moyun-yinyun** [danielgindi/Charts#1868]
The superClass BarChartRenderer can't override drawDataSet,Please help me,  I am a noob.Thank you.

**Comment by liuxuan30** [comment]
Due to:
>open func drawDataSet(context: CGContext, dataSet: IBarChartDataSet, index: Int)

You can override for sure.. take some time reading https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html#//apple_ref/doc/uid/TP40014097-CH41-ID3
