### ISSUE TITLE
Marker Position

### ISSUE THREAD

**Issue by diogoAntunes** [danielgindi/Charts#1876]
I've implemented a custom **MarkerView**, but every time the delegate function is called:

```
func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        let position = chartView.getMarkerPosition(highlight: highlight)
}
```
The value of the position is always **(0.0, 0.0)**. But the marker is being designed:

![Image of MarkerView](http://i.imgur.com/ZP5c2gJ.png)

**Comment by liuxuan30** [comment]
```
    open func getMarkerPosition(highlight: Highlight) -> CGPoint
    {
        return CGPoint(x: highlight.drawX, y: highlight.drawY)
    }
```
Would you please debug highlight.drawX and drawY, to see what's the problem?

**Comment by Rnorback** [comment]
so the way to get the markerPosition now seems to be by getting the hightlight.xPx and highlight.xPy.

**Comment by Neral** [comment]
Yes, it seems that `highlight.drawX` and `drawY` always returns values **(0.0, 0.0)**.

As mentioned @Rnorback you could use `highlight.xPx` & `highlight.yPx`. Marker position could be converted to any view like this:

`let rectInTableView = chartView.convert(CGRect(x: highlight.xPx, y: highlight.yPx, width: 0, height: 0), to: tableView)`

**Comment by liuxuan30** [comment]
I guess you may have to debug why highlight.drawX is 0.0. In charts demo, I am seeing valid values.

**Comment by jndefosse** [comment]
Tested on LineChart1ViewController. 

Breakpoint at 
- (void)chartValueSelected:(ChartViewBase * __nonnull)chartView entry:(ChartDataEntry * __nonnull)entry highlight:(ChartHighlight * __nonnull)highlight

Result :
![capture d ecran 2017-09-19 a 10 25 44](https://user-images.githubusercontent.com/5968328/30582744-1c6cf0bc-9d25-11e7-9da2-ec0334023570.png)

**Comment by liuxuan30** [comment]
@jndefosse  It's an old issue; are you breaking at the beginning?
```swift
            let x = high.x // get the x-position
            let y = high.y * Double(animator.phaseY)
            
            if x > chartXMax * animator.phaseX
            {
                continue
            }
            
            let trans = dataProvider.getTransformer(forAxis: set.axisDependency)
            
            let pt = trans.pixelForValues(x: x, y: y)
```
There is chance that x, y is 0
