### ISSUE TITLE
X axis values

### ISSUE THREAD

**Issue by ossmalpha** [danielgindi/Charts#1877]
How is it possible to set values that are displayed on x axis?

**Comment by AdamMak** [comment]
With the latest update it has been made much easier. A new class has been added called IndexAxisValueFormatter

      ```
  let xAxis = lineChart.xAxis
        xAxis.granularity = 1.0
        xAxis.valueFormatter = IndexAxisValueFormatter(values: xAxisValues)
```
xAxisValues is just an array of strings. Hope that helps

**Comment by ossmalpha** [comment]
Thanks, this is solved.
