### ISSUE TITLE
Horizontal bar chart dose not show all xAxis labels. 

### ISSUE THREAD

**Issue by zyqhi** [danielgindi/Charts#1878]
![popo_2016-11-24 11-39-10](https://cloud.githubusercontent.com/assets/1908908/20585978/ab462fb4-b23a-11e6-9f99-974cc979ef61.jpg)
I have 10 labels need to show on xAxis, but only 5 was drawn, I can not figure out how to fix it.

￼

**Comment by liuxuan30** [comment]
it's calculated by design.
You can call `setLabelCount()` = your x vals count, or read `computeAxisValues()` carefully to know how it calculate the labels, then override it.
