### ISSUE TITLE
[Question] Scatter Chart && Bubble Chart: How to show out whole radius instead of hiding half radius of first data entry?

### ISSUE THREAD

**Issue by inix** [danielgindi/Charts#1879]
I want to show out whole radius of first data instead of hiding half radius, I have check `xAxis.xOffset`, 
`chartView.extraLeftOffset`,but it do not work.

Can anyone help me?

```
Xcode: v8.1
iOS: v9.2.1
Charts: v3.0.1
```

Picture:
![d579a288-dd29-4d9b-a653-c17d8300b33b](https://cloud.githubusercontent.com/assets/2264291/20594133/067e7f28-b270-11e6-96b1-f8e41ebcaf52.png)

Thanks

**Comment by liuxuan30** [comment]
try:https://github.com/danielgindi/Charts/pull/1891

**Comment by inix** [comment]
@liuxuan30 Thanks,I will check it.

**Comment by inix** [comment]
@liuxuan30  hi,I try your patch
```
xAxis.spaceMin = 0.5
xAxis.spaceMax = 0.5
```

in combined chart, `CombinedChartView.swift`
```
    open override func initialize()
    {
        super.initialize()
        
        self.highlighter = CombinedHighlighter(chart: self, barDataProvider: self)
        
        // Old default behaviour
        self.highlightFullBarEnabled = true
        
        _fillFormatter = DefaultFillFormatter()
        
        renderer = CombinedChartRenderer(chart: self, animator: _animator, viewPortHandler: _viewPortHandler)
		
		xAxis.spaceMin = 0.5
		xAxis.spaceMax = 0.5
    }
```
images:
OK:
![img_0314](https://cloud.githubusercontent.com/assets/2264291/20744566/a69fd7ee-b717-11e6-9552-3e5fe059114a.PNG)

Not OK:
![img_0315](https://cloud.githubusercontent.com/assets/2264291/20744567/a770fe0a-b717-11e6-8783-7ac40ab07cca.PNG)


Last item is OK,but the first item in graph still cut by half. 
Can you help check it?
Thanks

**Comment by liuxuan30** [comment]
you are posting combined chart while you are asking for scatter chart. It's totally different. 
For combined chart, check https://github.com/danielgindi/Charts/issues/1717.

**Comment by inix** [comment]
OK,I will check it. Thx
