### ISSUE TITLE
PieChart values

### ISSUE THREAD

**Issue by brenoBohm** [danielgindi/Charts#1884]
How can I put custom values in the PieChart? I'm swift rapid 3.0!

**Comment by Huang-Libo** [comment]
@brenoBohm 
Just take a look at demos.

**Comment by brenoBohm** [comment]
I have this:


```
func initGraph(){
        pieChart.backgroundColor = UIColor.white
        pieChart.usePercentValuesEnabled = true
        pieChart.holeRadiusPercent = 0.0
        pieChart.transparentCircleRadiusPercent = 0.0
        pieChart.drawCenterTextEnabled = false
        pieChart.drawHoleEnabled = false
        pieChart.rotationAngle = 0.0
        pieChart.rotationEnabled = true
        pieChart.centerText = ""
        pieChart.noDataText = ""
        pieChart.legend.enabled = false
        pieChart.animate(xAxisDuration: 1.0, yAxisDuration: 1.0 , easingOption: ChartEasingOption.easeInSine)
        pieChart.layer.borderColor = UIColor.darkGray.cgColor
        pieChart.layer.borderWidth = 0.3
        pieChart.layer.masksToBounds = true
        pieChart.chartDescription?.text = ""
        setData()
    }
```
    
    func setData(){
        var yVals: [BarChartDataEntry] = []
        if values.count > 0 {
            for i in (0...(values.count - 1)){
                yVals.append(BarChartDataEntry(x: values[i] ,y:values[i]))
            }
        }
        
        let setPie = PieChartDataSet(values: yVals, label:"")
        setPie.colors = [
            BIBlue(),
            UIColor.init(red: 163.0/255.0, green: 30.0/255.0, blue: 59.0/255.0, alpha: 1.0),
            UIColor.init(red: 0.0/255.0, green: 128.0/255.0, blue: 1.0/255.0, alpha: 1.0),
            UIColor.init(red: 120.0/255.0, green: 54.0/255.0, blue: 116.0/255.0, alpha: 1.0),
            UIColor.init(red: 72.0/255.0, green: 58.0/255.0, blue: 137.0/255.0, alpha: 1.0),
            UIColor.init(red: 170.0/255.0, green: 170.0/255.0, blue: 170.0/255.0, alpha: 1.0)
                        ]        
        let dataPie:PieChartData = PieChartData(dataSet:setPie)
        dataPie.setDrawValues(true)
        pieChart.data = dataPie
    }


![captura de tela 2016-11-28 as 13 35 36](https://cloud.githubusercontent.com/assets/23559296/20674333/aaea2182-b56f-11e6-935e-56ada09430fd.png)





And I need this: 



![captura de tela 2016-11-28 as 13 36 59](https://cloud.githubusercontent.com/assets/23559296/20674355/c5cc4eee-b56f-11e6-96ed-ee0ffb35c60f.png)

**Comment by liuxuan30** [comment]
The ChartsDemo can explain all. And code provided.
