### ISSUE TITLE
how to resolve label overlapping problem with stack bar chart

### ISSUE THREAD

**Issue by Prathame5h** [danielgindi/Charts#1885]
![simulator screen shot nov 26 2016 5 09 11 pm](https://cloud.githubusercontent.com/assets/20103595/20640065/8528475a-b3fb-11e6-9883-81925ca4b285.png)

**Comment by Prathame5h** [comment]
please tell me, how to resolve text overlapping problem with stack bar chart ?

**Comment by liuxuan30** [comment]
either hide it, or modify `drawValues()` for it. There is no easy way as you can see, your bar rect are too thin to contain a text

**Comment by chetanpanchal94** [comment]
I shier anyway I can get thickness of stack?
