### ISSUE TITLE
How to show marker on y-Axis data?

### ISSUE THREAD

**Issue by shahinali5678** [danielgindi/Charts#1887]
I have been using this but doesn't got any solution to show marker on y-Axis data. I have string which I want to show on the y-Axis data as a marker. If anyone can give me an idea
![screen shot 2016-11-28 at 11 54 59 am](https://cloud.githubusercontent.com/assets/14871644/20658270/960e8d1a-b561-11e6-92b7-02d3594c4fae.png)
On the price I want to show sold or brought as a String in a marker. For example, I need beside 13.68 I need bought or sold String.

**Comment by liuxuan30** [comment]
the `ChartMarker` gives you the freedom where and how to draw the marker.
