### ISSUE TITLE
Carthage build error with xcode 8.1 and  Charts 2.3.0 

### ISSUE THREAD

**Issue by feemi** [danielgindi/Charts#1893]
The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/ozcanf/gerritrepository/TEB-iOS/Carthage/Checkouts/Charts/Charts.xcodeproj -scheme Charts -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

When try to build from xcode. Gives error in this method."locationInView"

 Method with Objective-C selector conflicts with previous declaration with the same Objective-C selector

	extension NSTouch
    {
		/** Touch locations on OS X are relative to the trackpad, whereas on iOS they are actually *on* the view. */
		func locationInView(view: NSView) -> NSPoint
        {
			let n = self.normalizedPosition
			let b = view.bounds
			return NSPoint(x: b.origin.x + b.size.width * n.x, y: b.origin.y + b.size.height * n.y)
		}
	}

**Comment by Domsware** [comment]
What is your Carthage command? I installed Charts few hours ago with the same configuration as yours without any problem:

`github "danielgindi/Charts" ~> 2.3.0`

**Comment by feemi** [comment]
i just use carthage update

in my cartfile 
github "danielgindi/Charts" == 2.3.0

**Comment by Domsware** [comment]
I used `carthage update --platform ios` and the `github "danielgindi/Charts" ~> 2.3.0` Carthage command.

Could you try with this configuration?

**Comment by feemi** [comment]
github "danielgindi/Charts" ~> 2.3.0 just worked. it fetches 2.3.1 version.

**Comment by petester42** [comment]
Thanks for the help @domsware
