### ISSUE TITLE
Cannot build in big project using cocoapods

### ISSUE THREAD

**Issue by peterlondon1** [danielgindi/Charts#1894]
I can use Charts in a couple of projects, but trying to add it to a large project I get over 3,000 (!) compile errors

The first error is in AnimatedMoveViewJob.swift: "Expressions are not allowed at the top level"

Does anybody recognise this?

Are there are potential conflicts with other pods that might cause this?

Using    pod 'Charts', '~> 3.0'   platform :ios, '9.3'

![chartserrors](https://cloud.githubusercontent.com/assets/312881/20753422/38651e74-b6fe-11e6-9526-522802fc541d.png)

Xcode 8.1

**Comment by petester42** [comment]
If you can use it in other projects then it is probably a cocoapods issue or an issue with that specific project.

**Comment by peterlondon1** [comment]
It turns out I was trying to add the latest version of Charts (Swift 3) to a project that was still in Swift 2.3. Duh!

**Comment by petester42** [comment]
Glad you found the problem!
