### ISSUE TITLE
Scrolling x-axis labels

### ISSUE THREAD

**Issue by hassanmah** [danielgindi/Charts#1897]
Hey, 

I am trying to make this line graph scrollable, the only way I have found so far is 

`            chart.zoom(scaleX: 2.0, scaleY: 0.0, x: 0.0, y: 0.0)
`

But this causes the x-axis values to become decimals as in the attached image.

<img width="368" alt="screen shot 2016-11-30 at 17 29 29" src="https://cloud.githubusercontent.com/assets/3025707/20763610/a0f4f9d6-b722-11e6-8a63-41c23f894047.png">

Is there another way I can implement scrolling, without the values becoming decimals?

Thanks

**Comment by liuxuan30** [comment]
by default, the lien will show all you entries, so you won't need to help.
When you zoom in, then you can scroll. Zooming in will zoom in the x axis values as well.
About the decimals, you can set `granularity` to like 1.
If you really want to scroll, then you have to create a big view and zoom in at first, then you can scroll.
Double check your feature requirement
