### ISSUE TITLE
Can i change the value Above bar from double to int?

### ISSUE THREAD

**Issue by osj8876** [danielgindi/Charts#1898]
hello.

I want to change the value format from double to int.

It is possible?

![kakaotalk_photo_2016-12-01-09-15-52](https://cloud.githubusercontent.com/assets/12045407/20776916/d0b7d2cc-b7a6-11e6-92ad-fa53a4f4c2bb.jpeg)

just a barcharview supports the drawValueAboveBarEnabled.

thank you.

**Comment by liuxuan30** [comment]
just use `valueFormatter` in your data set.
