### ISSUE TITLE
no match color bar chart with label

### ISSUE THREAD

**Issue by osj8876** [danielgindi/Charts#1900]
hello

I draw the bar chart with label.

But bar charts of all is a blue.

Each represented a different color.

It is a bug?

Below the code : 

        var yVals = [BarChartDataEntry]()
        
        let dataFormatter = DateFormatter()
        dataFormatter.locale = Locale(identifier: "en_US")
        dataFormatter.dateStyle = .medium
        dataFormatter.dateFormat = "MMM dd"
        
        for i in 0..<data.count - 1 {
            let readData = data[i][1]
            yVals.append(BarChartDataEntry(x: Double(i), y: Double(readData)!))
        }
        
        let todayTime = dataFormatter.date(from: data[data.count-1][0])
        let tommorrowTime = dataFormatter.date(from: data[data.count-1][1])
        let dayAfterTommorrowtodayTime = dataFormatter.date(from: data[data.count-1][2])
        
        dataFormatter.dateFormat = "yyyy-MM-dd"
        
        var convertTime = dataFormatter.string(from: todayTime!)
        
        let dataSetToday = BarChartDataSet(values: yVals, label: convertTime)
        dataSetToday.colors = [UIColor.lightGray]
        
        for i in 0..<data.count - 1 {
            let readData = data[i][2]
            yVals.append(BarChartDataEntry(x: Double(i+9), y: Double(readData)!))
        }
            
        convertTime = dataFormatter.string(from: tommorrowTime!)
            
        let dataSetT​ommorrow = BarChartDataSet(values: yVals, label: convertTime)
        dataSetT​ommorrow.colors = [UIColor.red]
            
        for i in 0..<data.count - 1 {
            let readData = data[i][3]
            yVals.append(BarChartDataEntry(x: Double(i+18), y: Double(readData)!))
        }
            
        convertTime = dataFormatter.string(from: dayAfterTommorrowtodayTime!)
            
        let dataSetDayAfterTommorrow = BarChartDataSet(values: yVals, label: convertTime)
        dataSetDayAfterTommorrow.colors = [UIColor.blue]
            
        let dataSets: [BarChartDataSet] = [dataSetToday, dataSetT​ommorrow, dataSetDayAfterTommorrow]
        
        self.magneticForcastBarView.fitBars = true
        self.magneticForcastBarView.data = BarChartData(dataSets: dataSets)
        self.magneticForcastBarView.animate(xAxisDuration: 2.0, yAxisDuration: 2.0, easingOption: .easeInBounce)

thank you
![kakaotalk_photo_2016-12-01-16-21-21](https://cloud.githubusercontent.com/assets/12045407/20785183/3a003680-b7e2-11e6-8ce7-9aa4d3e31157.jpeg)

**Comment by liuxuan30** [comment]
dataSetDayAfterTommorrow.colors = [UIColor.blue]
you set it all blue and you ask why..
