### ISSUE TITLE
How to give xAxis customized labels for linechartview

### ISSUE THREAD

**Issue by sunilhts** [danielgindi/Charts#1903]
Previously we set through this method
LineChartData(xVals: xValsList, dataSets: dataSets)
but now LineChartData have only one init method that have only dataSets.. is there any other method for giving the xVals for the graph
How to set xVals for particular DataSet ???????

**Comment by r-dent** [comment]
I set the x-values of my entries to `Double`-casted `Int` values to mimic the index behavior of the 2.x version.
Then i set `chart.xAxis.labelCount` to the number of values and `chart.xAxis.forceLabelsEnabled` to `true`. But it breaks as soon as you zoom in. Very frustrating. 😕

**Comment by r-dent** [comment]
I think the new `IndexAxisValueFormatter` should be the way to go. But in my case it still did not behave as expected.

**Comment by liuxuan30** [comment]
if you just want customized labels for x axis, take a look at `computeAxisValues()`, where it generate the value labels. But now the entry will take (x, y) and no other way.
