### ISSUE TITLE
QUESTION - How mask the ranges values in a Graph

### ISSUE THREAD

**Issue by panchocantu** [danielgindi/Charts#1904]
Hello, 
I would like to know if there is any way to change the ranges between levels labels, for example in my app is displaying 2,000,000 and I will like show 2.0 to avoid the large number with a lot of zeros. 

![screen shot 2016-12-01 at 15 04 25](https://cloud.githubusercontent.com/assets/7904435/20812540/8d7f3370-b7d7-11e6-9fb0-53ffbd7875fe.png)

Thanks, 
Francisco

**Comment by liuxuan30** [comment]
use your own valueFormatter.
