### ISSUE TITLE
custom xAxis for line chart I need an example

### ISSUE THREAD

**Issue by Stay-in-Touch** [danielgindi/Charts#1905]
I have 4800 y values at 80 values/s. I want teh xAxis Lables to read 0s,15s,30s,45s at the 0,1200,2400 and 3600 positions. It is not at all clear to me how to approach this issue. I would like vertical grid lines from each label!

Living in a time of transition is uncomfortable, and many of the old examples and even running code no longer work. Is there an example of Swift 3 line charts that I could look at.
Thank you

**Comment by r-dent** [comment]
I would love to see such, too.

**Comment by Stay-in-Touch** [comment]
Making some progress....
`        // xAxis
        let xAxis = lineChartView.xAxis
        xAxis.labelPosition = .bottom
        xAxis.drawLabelsEnabled = true
        xAxis.labelTextColor = UIColor.red
        xAxis.labelFont = NSUIFont.systemFont(ofSize: 11.0)
        let labels = ["0s","15s","30s","45s",""]
        xAxis.valueFormatter = IndexAxisValueFormatter(values: labels)
        xAxis.setLabelCount(labels.count, force: true)
        lineChartView.scaleXEnabled = true`

This produces...
![image](https://cloud.githubusercontent.com/assets/7853284/20840229/85bb0190-b87d-11e6-9f94-4cc26c062c8c.png)

Note the 0s in red at the beginning of the x Scale. Problem now is to show the others.
The trick to getting the right number of grid lines is to add the "" for the last position of the scale.

**Comment by liuxuan30** [comment]
you can take a look at `computeAxisValues()`, where it generate the x axis value labels. 
I don't quite understand what you want, but looks like overriding the func and set the interval to be 15sec seems doable to me.
