### ISSUE TITLE
Chart Swift files not running on Obj-C XCODE8.0 install

### ISSUE THREAD

**Issue by craigflanagan** [danielgindi/Charts#1908]
Hi, I hope you can help me. I have used your charts before and love them. I have been trying
now for two days (yes its embarrassing) to get Charts to install on XCODE 8.0. I can get the demo running and have installed the Charts by dragging Charts.xcodeproj into my project. I have hit the plus to install the frameworks under embedded binaries on my target. I then compiled it and my project...no problems. 
![screen shot 2016-12-02 at 2 39 01 am](https://cloud.githubusercontent.com/assets/19899892/20826504/6a3a2570-b839-11e6-9721-5015463ca088.png)

I set EMBEDDED_CONTENT_CONTAINs_SWIFT to Yes:

![screen shot 2016-12-02 at 2 38 44 am](https://cloud.githubusercontent.com/assets/19899892/20826553/b7ab1e5e-b839-11e6-91a3-74de02bf13ed.png)

I then get stuck. Either the bridging header is unrecognized, or as Daniel suggested I remove the charts and open a swift file and reinstall the charts so sometimes I can get the header to be recognized but then the Charts elements are not recognized as follows:

![screen shot 2016-12-02 at 2 36 57 am](https://cloud.githubusercontent.com/assets/19899892/20826570/df3edf82-b839-11e6-801c-925b07f87a21.png)

Any help would be really greatly appreciated as I just can't figure out where I went wrong! Thank you. Craig

**Comment by liuxuan30** [comment]
I guess you have to take a look at ChartsDemo. You have to run carthage to download Realm to make ChartsDemo running. If you just need to take a look at project setting, then you don't need Realm.

**Comment by craigflanagan** [comment]
Thank you. I don't quite understand your response. Is it possible to install as I have tried without using carthage? I don't need Realm but I do want to Charts library to be recognized in my code. Craig

**Comment by liuxuan30** [comment]
If you need to run ChartsDemo, then you need Realm. carthage is just a way to let you run a single cmd and get it installed. If you don't want carthage, then you have to install Realm yourself and compile ChartsDemo.

Your issue is having a pattern we have seen a lot in closed issues, but we don't know what's wrong with yours. It's just not enough clues..

That's why I suggest you to run ChartsDemo at least it's fine and you can refer to it..
