### ISSUE TITLE
Can we resurrect Chart2.2.5-Swift3.0? 

### ISSUE THREAD

**Issue by joedaniels29** [danielgindi/Charts#1910]
Anyone have a fork? I was quite happy with that version, and it has mysteriously disappeared...

**Comment by petester42** [comment]
I am against the idea. I would rather people move to 3.0 as soon as possible.

**Comment by liuxuan30** [comment]
I second that, but I have one: https://github.com/liuxuan30/Charts/tree/Swift-3.0. 
If you pick this, you have to fix any bug you found... lol

**Comment by joedaniels29** [comment]
thanks, I ended up having a copy locally, and pushed it back up, the original branch is here https://github.com/joedaniels29/Charts/tree/Chart2.2.5-Swift3.0
Maybe  `v2.3.1` intended to  replace the branch?
