### ISSUE TITLE
Xcode 8.1 is reporting 'No such Module 'Charts' & Build/Compilation Errors

### ISSUE THREAD

**Issue by kzuik** [danielgindi/Charts#1914]
Note: I've already referred to the following which did not solve my problem or help:
https://github.com/danielgindi/Charts/issues/1538
https://github.com/danielgindi/Charts/issues/1743

When I type, @import Charts into my .swift file, an error appears saying "No such module". Also, when I try to compile the code, there are 138 errors in Charts. I'm not very familiar with Mac or Xcode, as I've only been using them for a couple of months.

I added the Podfile which contains the following: 

"platform :ios, "9.0"
use_frameworks!

target 'Zuiker-Final_Exam-12-2-16' do
  pod 'Charts', '~> 2.1'
end"

I'm not sure what the 2.1 refers to in the Podfile. Does that need to be updated?

I added the charts framework to Embedded Binaries and seem to have followed all instructions up to that point correctly. 

Any help would be appreciated.

<img width="351" alt="capture2" src="https://cloud.githubusercontent.com/assets/12646897/20860680/c574e03e-b94b-11e6-9ef6-a19c5a14a82d.PNG">
<img width="452" alt="capture3" src="https://cloud.githubusercontent.com/assets/12646897/20860681/c5753b42-b94b-11e6-99ae-068e2ac0bbbc.PNG">
<img width="131" alt="capture" src="https://cloud.githubusercontent.com/assets/12646897/20860682/c575b914-b94b-11e6-8ef5-d5528c2a584b.PNG">

**Comment by liuxuan30** [comment]
you should at least use latest code...

**Comment by hoyoung-jung** [comment]
I'm not sure if this was ever resolved or answered, but I am still getting this issue with the latest version of Charts on Xcode 9.3 and swift 4. I have followed the instructions directly from the README file, but still states that there are 'no such module Charts'. Any advice?
