### ISSUE TITLE
Charts does not install correctly

### ISSUE THREAD

**Issue by ahartman** [danielgindi/Charts#1915]
I create a new single-view project with latest Xcode 8.1 (8B62).
Pod init, insert pod 'Charts', pod install.
Build the project for good measure.
Now for a View, model 'Charts' is not available in the Custom Class model dropdown.
I tried every trick mentioned on Internet but to no avail.
What is wrong and how to fix?
Help appreciated.
Kind regards, André Hartman, Belgium.

**Comment by kutran** [comment]
"Charts" is the name of the module.  Are you talking about drop-down in the Storyboard?  I think what you are looking for is the individual charts such as CombinedChartView, LineChartView, PieChartView, RadarChartView, ScatterChartView, etc.

**Comment by liuxuan30** [comment]
you need to provide rich info to help illustrate what's your problem.. We barely understand.
