### ISSUE TITLE
Round number less than zero x values issue

### ISSUE THREAD

**Issue by chioma91** [danielgindi/Charts#1916]
I tried several methods and formatter to properly print x values with numbers smaller than zero. I can't print the "zero" digit before the dot, e.g:
Number ->Printed number

- 0.0 -> .0
- 0.7 -> .7

The issue is present both with not perfectly rounder numbers (eg. 0.3452) and with perfectly rounder numbers (eg 0.8)

```
let format = NumberFormatter()
format.minimumIntegerDigits = 1
let formatter = DefaultValueFormatter(formatter: format)
chartView.xAxis.valueFormatter = (formatter as? IAxisValueFormatter)
```

The code above doesn't work and also experiments with `granularity` did not work.

Swift/Charts 3.0.1

**Comment by Kristina777** [comment]
I have this problem too.

**Comment by liuxuan30** [comment]
I tried in ChartsDemo bar chart:
```objective-c
    leftAxisFormatter.minimumIntegerDigits = 1;
    
    ChartYAxis *leftAxis = _chartView.leftAxis;
    leftAxis.labelFont = [UIFont systemFontOfSize:10.f];
    leftAxis.labelCount = 8;
    leftAxis.valueFormatter = [[ChartDefaultAxisValueFormatter alloc] initWithFormatter:leftAxisFormatter];
```

```
(lldb) po formatter?.string(from:0.1)
▿ Optional<String>
  - some : "0.1 $"
```
It works fine.
Please debug on your side for below func, and carefully check the formatter whether the condition is not met and start a new one.
```swift
    open var valueFormatter: IAxisValueFormatter?
    {
        get
        {
            if _axisValueFormatter == nil ||
                (_axisValueFormatter is DefaultAxisValueFormatter &&
                    (_axisValueFormatter as! DefaultAxisValueFormatter).hasAutoDecimals &&
                    (_axisValueFormatter as! DefaultAxisValueFormatter).decimals != decimals)
            {
                _axisValueFormatter = DefaultAxisValueFormatter(decimals: decimals)
            }
            
            return _axisValueFormatter
        }
        set
        {
            _axisValueFormatter = newValue ?? DefaultAxisValueFormatter(decimals: decimals)
        }
    }
```

**Comment by chioma91** [comment]
I'm sorry but I said I'm writing in Swift but you replied with the objective-c example.

I think you haven't even read my code but, I don't know why, you closed the topic without giving an acceptable answer.

**Comment by liuxuan30** [comment]
I read the code and run tests and debug with ChartsDemo, saying it's fine and needs you to debug on your side to know why the formatter is replaced or changed so `minimumIntegerDigits` became 0.  Then I got a down thumb and saying I am not reading the question or code and using Objective-C where it's the main language in Apple's ecosystem and find it impossible to understand and give a down thumb.. I won't answer it at all in the first place.

**Comment by chioma91** [comment]
I'm sorry if I was a little hard with you, but I'm learning coding by my self, I opened a thread because I can't find a solution to my problem and you close the thread without giving me actually a real solution. And if you close immediately the thread I get much less chances to be reached by other people (I have no doubt that Charts API works well).
I know that obj-c is the main apple language, but sometimes is not so simple to translate in Swift, mostly for a beginner who started with it.

Anyway I found this holy solution, now I write it down.
Cheers man and good work with this wonderful API

**Comment by liuxuan30** [comment]
It's fine. I close the issues because we need to keep it clean knowing what are the true issues and what are questions. 
As I said, I have post the code that you should try. It should be the solution. I tried it myself already. The formatter won't change its `minimumIntegerDigits` after you set it, unless the formatter is being replaced or you changed some where else.
