### ISSUE TITLE
Highlighted values on piechart too high?

### ISSUE THREAD

**Issue by cilvet** [danielgindi/Charts#1919]
I am developing the iOS version of my android app, in which I used mpandroidcharts. So long everything has been perfect, but I noticed that highlighted values on piechart are way more highlighted than in the android app, I don't seem to find a way to change this, I might see myself forced to set the highlighting to unabled since it is way too large. Am I missing out on something?

**Comment by liuxuan30** [comment]
I don't see a screenshot to explain what's too high. But I made a guess you are asking:`dataSet.selectionShift`

**Comment by cilvet** [comment]
That was exactly it! thank you very much for the fast response, and sorry
for not being more specific.
