### ISSUE TITLE
Please Please Help, I can’t get Charts installed properly

### ISSUE THREAD

**Issue by craigflanagan** [danielgindi/Charts#1922]
I have been at this for many days now. At first I tried just dragging the library over to my
project but that didn’t work. Now I have migrated on to using cocoa pods using the following
pod file for my XCODE 8.1 Obj C project (just a basic single view controller app):

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, ’10’
target ‘coco2’ do
pod 'Charts', '~> 3.0.1’
end

When I open the workspace file after the successful running of the pod file I am faced with
a demand to update my project to SWIFT3.0. If I say yes then I get all softs of errors, if I say 
no stay at 2.3 (and set the compiler to the legacy swift compiler) I get the following:
![screen shot 2016-12-05 at 6 40 50 pm](https://cloud.githubusercontent.com/assets/19899892/20907517/c6c3b37a-bb1c-11e6-9f49-7540d33a4054.png)
Please help I am so stuck and frustrated and I know there are some good people out there willing to lend a hand. Craig

**Comment by kutran** [comment]
Did you check the following setting in Xcode?

![screen shot 2016-12-06 at 4 42 34 pm](https://cloud.githubusercontent.com/assets/1893046/20950198/25211988-bbd3-11e6-84b8-6cd4dae7a889.png)

**Comment by liuxuan30** [comment]
well you have to upgrade your project to swift 3.0 first.. Chart 3.0 is swift 3.0
