### ISSUE TITLE
stringForValue method return unexpected value when reload TableView data.

### ISSUE THREAD

**Issue by DanhDue** [danielgindi/Charts#1927]
Hi. Thank for beautiful library!
I drawing barchart inside UITableViewCell successfully.
But when I reload data for TableView then issue occur, stringForValue method return unexpect value. I try clear data before redraw chart but issue still occur.

I set BarChartDataEntry data:

```
for index in 0 ..< lstNamHocs.count
{
    if let soHSLB = lstNamHocs[index].soHSLB, let tongHS = lstNamHocs[index].tongsohs, tongHS != "0"
    {
        if let dSoHSLB = Double(soHSLB), let dTongHS = Double(tongHS)
        {
            let dataEntry = BarChartDataEntry(x: Double(index), yValues: [(dSoHSLB/dTongHS) * 100])
            dataEntries.append(dataEntry)
        }
    }
}
```

and override stringForValue method:

```
extension TableViewController: IAxisValueFormatter
{
    func stringForValue(_ value: Double, axis: AxisBase?) -> String
    {
        if value >= 0
        {
            return lstNamHocs[Int(value)].namHoc!
        }
        else
        {
            return ""
        }
    }
}
```

Please help me fix it.

Thanks!

**Comment by liuxuan30** [comment]
We have no knowledge for your lstNamHocs[Int(value)].namHoc! and what's expected... 
Please debug on your side to see what's unexpected to you..
