### ISSUE TITLE
Make releases so they follow the Semantic Versioning (SemVer)

### ISSUE THREAD

**Issue by isgarlo** [danielgindi/Charts#1930]
In order to add Charts as a dependency to the Swift Package Manager, the releases should be in the form of 3.0.1 and not v3.0.1.

http://semver.org/
https://swift.org/package-manager/#example-usage

**Comment by petester42** [comment]
Is there much use for swift package manager support if it cants support what the library needs? Charts depends on CoreGraphics which is only available on macOS.
