### ISSUE TITLE
Pie chart Outside values, Inside Value and legend value

### ISSUE THREAD

**Issue by hiralnaik** [danielgindi/Charts#1932]
Hi 

I want to display Pie chart with 3 different values. I want to display percentage value outside, actual value in side of pie and legend will be the text value. Is possible with current library ? I am using Charts 2.3.0. 

Check out the attached image. 
<img width="472" alt="screen shot 2016-12-07 at 12 31 48 pm" src="https://cloud.githubusercontent.com/assets/7863227/20985426/51ae1428-bc79-11e6-873c-1e1b48276978.png">

Thanks
Hiral

**Comment by liuxuan30** [comment]
Check Pie Bar Chart in ChartsDemo.. it seems supported.

**Comment by hiralnaik** [comment]
@liuxuan30  I don't get it. Can you please explain me more ?

**Comment by liuxuan30** [comment]
just run ChartsDemo to see. If you think it's not supported, then that's it.

**Comment by hiralnaik** [comment]
@liuxuan30 Thanks.
