### ISSUE TITLE
iOS Demo Fails to build

### ISSUE THREAD

**Issue by iamcam** [danielgindi/Charts#1933]
After following the carthage steps (which fail to install, it appears), the demo app fails to build

**Comment by hiralnaik** [comment]
- Close Xcode
- open terminal 
- Run this command `brew install carthage`
- Open ChartDemo
- Clean your project 
- Run

It should work.

**Comment by iamcam** [comment]
This bug may need to be re-opened.

Even with those steps, a fresh clone of the repo and fully updated carthage, the iOS demo app is unable to build the Realm dependencies .

In the Realm framework log:

```
Building dependencies...
Failed to write to /Users/cameron/delete/Charts/Carthage/Build/iOS/Realm.framework: Error Domain=NSCocoaErrorDomain Code=4 "The file “RLMObjectBase.h” doesn’t exist." UserInfo={NSSourceFilePathErrorKey=/private/var/folders/dq/ln022fyj07jcc30whsk5tyj80000gn/T/carthage-archive.xgRjNp/Carthage/Build/tvOS/Realm.framework/Headers/RLMObjectBase.h, NSUserStringVariant=(
    Copy
), NSDestinationFilePath=/Users/cameron/delete/Charts/Carthage/Build/iOS/Realm.framework/Headers/RLMObjectBase.h, NSFilePath=/private/var/folders/dq/ln022fyj07jcc30whsk5tyj80000gn/T/carthage-archive.xgRjNp/Carthage/Build/tvOS/Realm.framework/Headers/RLMObjectBase.h, NSUnderlyingError=0x7f8d30c67a70 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
*** Downloading realm-cocoa at "v1.1.0"
*** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
Command /bin/sh failed with exit code 1
```

This is the same error when running `carthage checkout`. I don't know carthage well enough to say if it's a carthage issue or something in the demo app config.


Running `carthage update` doesn't solve anything:
```
Failed to write to /Users/cameron/delete/Charts/Carthage/Build/iOS/Realm.framework: Error Domain=NSCocoaErrorDomain Code=513 "“Realm.framework” couldn’t be removed because you don’t have permission to access it." UserInfo={NSFilePath=/Users/cameron/delete/Charts/Carthage/Build/iOS/Realm.framework, NSUserStringVariant=(
    Remove
), NSUnderlyingError=0x7fba0a00f0b0 {Error Domain=NSPOSIXErrorDomain Code=66 "Directory not empty"}}
```

**Comment by iamcam** [comment]
@liuxuan30 Is this a Charts carthage configuration issue, or something else like Realm or Carthage on its own.

**Comment by liuxuan30** [comment]
have you try `carthage bootstrap`? I tried on my side, it works fine..

**Comment by liuxuan30** [comment]
be careful checking your error log:
>Error Domain=NSCocoaErrorDomain Code=513 "“Realm.framework” couldn’t be removed because you don’t have permission to access it."

**Comment by osolano** [comment]
I am also experiencing an issue running the ChartsDemo. I did the steps below 

```
brew install carthage
git clone https://github.com/danielgindi/Charts.git
cd Charts
bootstrap carthage
cd ChartsDemo
open ChartsDemo.xcodeproj

Run ChartsDemo Target on iPhone 6S Plus
```


and after running the demo on Xcode get this error..

```
dyld: Library not loaded: @rpath/RealmSwift.framework/RealmSwift
  Referenced from: /Users/olso/Library/Developer/Xcode/DerivedData/ChartsDemo-bmixrsqunixkxwatelccgbgoaytr/Build/Products/Debug-iphonesimulator/ChartsRealm.framework/ChartsRealm
  Reason: image not found
```

**Comment by liuxuan30** [comment]
@osolano could you check if Realm is installed on your machine?

**Comment by osolano** [comment]
@liuxuan30 

![image](https://cloud.githubusercontent.com/assets/280426/22261760/03a07eae-e223-11e6-8715-c13250be241d.png)

I also have the Realm Browser installed on my computer if that's what you mean. 

I tried carthage boostrap and still I get the issue above.

**Comment by osolano** [comment]
@liuxuan30  disregard. I followed instructions on this thread and everything started to work :)

https://github.com/danielgindi/Charts/issues/2066
