### ISSUE TITLE
Charts-2.3.0/Source/ChartsRealm/Data/RealmPieData.swift:19:8: No such module 'Realm'

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#1934]
mac os  10.11.6 
Xcode Version 8.1 (8B62)

This error occurs when I run the ChartsDemo,
Please help me ， Thank you。
![1da19bb2-b3c2-493b-ae73-071219b6a91f](https://cloud.githubusercontent.com/assets/8455023/20994852/0b0b9648-bd2e-11e6-98c8-43662b081260.png)

**Comment by liuxuan30** [comment]
You need to install Realm first..

    Close Xcode
    open terminal
    Run this command brew install carthage
    Open ChartDemo
    Clean your project
    Run
