### ISSUE TITLE
Barchart xAxis interval

### ISSUE THREAD

**Issue by A-Lim** [danielgindi/Charts#1937]
If my bar chart only a single y value, the interval of the xAxis values will repeat. However this works find if my bar chart has multiple y values. 

<img width="294" alt="screen shot 2016-12-08 at 4 32 12 pm" src="https://cloud.githubusercontent.com/assets/14160760/21003008/e63de06a-bd63-11e6-96d8-89ba81d54af7.png">

**Comment by liuxuan30** [comment]
hmm, use `granularity`
