### ISSUE TITLE
Displaying an overlay with extra / more detailed information on mouse hover

### ISSUE THREAD

**Issue by MrMage** [danielgindi/Charts#1940]
I am using Charts in a macOS application and would like to display extra information (or at least the data entry's x/y values and label) when the user hovers the mouse over a chart element, e.g. a bar in a bar chart - for example via a popover. I have looked around but could not find this functionality yet - highlighting seems to come closest, but only works on click and just colors the bar differently (rather than displaying more info).

Is functionality like this planned? If not, how would I best go about implementing it? Should I subclass e.g. BarChartView in my own code or try integrating this functionality so that it can be merged? Also, how would you recommend integrating the with the existing parts of the library?

Thanks,
Daniel

**Comment by MrMage** [comment]
Friendly ping :-)

**Comment by petester42** [comment]
So far all the interactions have been done using gesture recognitiers. I am not familiar with macOS but if there is a gesture for mouse move then it would be fairly simple. But from my iOS knowledge I don't think that would be a thing. Let us know!

**Comment by liuxuan30** [comment]
One idea is how to detect the hover and use highlighter to highlight the values you want, also ChartMarker might help. I don't know hover in macOS

**Comment by MrMage** [comment]
The problem is that highlighting only changes the color, while I want to e.g. display the actual values and their labels. I might end up just subclassing the graph view and creating my own popover.

How is ChartMarker supposed to be used?

**Comment by thierryH91200** [comment]
Look in the demo for ios. The solution is there.
The demo for macOS is minimalist
I think 90% of people program for ios
Otherwise I can send you a sample code

**Comment by MrMage** [comment]
I have looked at the iOS demo, but I can't find any example for overlays there. Could you please point me in the right direction?

**Comment by thierryH91200** [comment]
look in BalloonMarker and XYMarkerView or modify BalloonMarker

**Comment by MrMage** [comment]
Thanks, the BalloonMarker is very helpful. Closing this.
