### ISSUE TITLE
We are unable to split the label in two lines.

### ISSUE THREAD

**Issue by pammitinku** [danielgindi/Charts#1941]
If Label size is greater than 15 characters then graph is not build properly.
How can i split a label in two lines if its of larger length then the desired.

**Comment by liuxuan30** [comment]
please first explain `If Label size is greater than 15 characters then graph is not build properly.`
For your second question, enable `wordWrapEnabled`.
BTW, x axis even supports `labelRotationAngle`!

**Comment by pammitinku** [comment]
If label size is greater than 15 characters and label size is 8.0 then all the bars are not visible.

**Comment by liuxuan30** [comment]
Really? even the bars? Not having a chance to test yet.
