### ISSUE TITLE
Right and left margins

### ISSUE THREAD

**Issue by delox** [danielgindi/Charts#1942]
Is there a way to make a chartView fill the screen? Right now my view is constrained (0) to the left and right of the viewcontroller but there's still a gap left by the graph's drawing in both the left and the right, how do I avoid this?

I inspected the UI and the chart view is clearly taking up the whole space, it's the drawing that leaves the left and right margins

**Comment by liuxuan30** [comment]
`minOffset` default is 10. You can try. `extraLeftOffset` `extraRightOffset` is also can be used. However, I think you should give some margin by default.
