### ISSUE TITLE
Charts being overlaid inside UICollectionView using dequeueReusableCell

### ISSUE THREAD

**Issue by arronhunt** [danielgindi/Charts#1943]
When drawing graphs inside a UICollectionViewCell, the first and last graph overlay on top of each other. The orange is the first graph, the blue one is the last one (in a set of 12 cells).

Note that I'm a beginner to swift, so this could be an issue external to Charts. If so, please let me know and I'll remove. 

![screen shot 2016-12-09 at 4 40 38 pm](https://cloud.githubusercontent.com/assets/298336/21069392/4223b074-be2e-11e6-9a26-892cd6c8b229.png)

**Comment by liuxuan30** [comment]
I am confused, but have you cleaned your cell before reuse it?
