### ISSUE TITLE
How automatic showing marker？

### ISSUE THREAD

**Issue by chenfengfeng** [danielgindi/Charts#1944]
set.highlightEnabled = YES;
[self.chartView highlightValueWithX:6 dataSetIndex:0];
No effect..

can you help me😂

**Comment by chenfengfeng** [comment]
i can use
'highlightValueWithX:(double)x y:(double)y dataSetIndex:(NSInteger)dataSetIndex'
but
'highlightValueWithX:(double)x dataSetIndex:(NSInteger)dataSetIndex'
no working

but i can no working in
'chartTranslated:(ChartViewBase * _Nonnull)chartView dX:(CGFloat)dX dY:(CGFloat)dY'

Is not working in this method

**Comment by liuxuan30** [comment]
```swift
    /// draws all MarkerViews on the highlighted positions
    internal func drawMarkers(context: CGContext)
    {
        // if there is no marker view or drawing marker is disabled
        guard
            let marker = marker
            , isDrawMarkersEnabled &&
                valuesToHighlight()
            else { return }
```

**Comment by chenfengfeng** [comment]
thanks！
but i can only slide to the left, can not slide to the right
if run 
-(void)chartTranslated:(ChartViewBase * _Nonnull)chartView dX:(CGFloat)dX dY:(CGFloat)dY
{
     [self.chartView highlightValueWithX:index y:model.weight dataSetIndex:0];
}

**Comment by Rj707** [comment]
is there any working method to draw marker or highlight any value manually?? 
like highlightValueWithX bla bla.
