### ISSUE TITLE
(3.0 Regression) Scatter chart cuts off data at the edges

### ISSUE THREAD

**Issue by neerajbaid** [danielgindi/Charts#1946]
I am unable to scroll further to the right in order to fully display the rightmost data point. I have circled it in the below screenshot. This was not an issue in Charts v2.3.0.

![simulator screen shot dec 11 2016 1 32 38 pm](https://cloud.githubusercontent.com/assets/1578586/21083483/7387201e-bfa6-11e6-9cca-4cadcccf7251.png)

**Comment by liuxuan30** [comment]
can #1891 solve your problem?

**Comment by neerajbaid** [comment]
yup, that'll do it. thanks!
