### ISSUE TITLE
Find screen location for bars in a bar chart

### ISSUE THREAD

**Issue by peterlondon1** [danielgindi/Charts#1949]
Can anyone give me some help in determining the screen location for each bar in a bar chart - so that I can extend the bars under the axis in a particular way?

**Comment by vsujan92** [comment]
Refer to BarChartRenderer.

**Comment by liuxuan30** [comment]
You have some choices, like leveraging the ChartViewDelegate to know which bar is highlighted as a reference.
The core is it will convert data value into screen point value, by using `Transformer`'s `pointValueToPixel` and `pixelsToValues`. Just take a look at `Transformer`
