### ISSUE TITLE
Radar Chart axis maximum

### ISSUE THREAD

**Issue by Tobisaninfo** [danielgindi/Charts#1952]
When rotating the device the chart resizes the y-axis and ignore my max value. How can I prevent this behavior?

**Comment by liuxuan30** [comment]
Be more specific. If you are asking setting max value, refer to `axisMaximum`

**Comment by Tobisaninfo** [comment]
I already tried this line of code

        chart.yAxis.axisMaximum = 2.0

But this does not help at all.

**Comment by liuxuan30** [comment]
then be more specific. You don't give a screenshot or gif or code to reproduce with ChartsDemo.

**Comment by Tobisaninfo** [comment]
Here is some code snippet from my diagram:

let chartDataSet = RadarChartDataSet(values: dataEntries, label: "Current Test")
        let chartData = RadarChartData(dataSet: chartDataSet)
        chart.data = chartData
        
        //Options of radarChart
        chart.sizeToFit()
        chart.chartDescription?.text = ""
        
        chart.xAxis.valueFormatter = self
        
        chart.yAxis.labelCount = 3
        chart.yAxis.axisMinimum = 0.0
        chart.yAxis.axisMaximum = 3.0

I have 3 screenshots for you. The first is the correct one. The second is after the first rotation und the third one it after the second rotation. As you can see my maximum of 3.0 is now 9.0. That is my problem. 
Thanks for help.

![screen shot 2016-12-14 at 22 04 01](https://cloud.githubusercontent.com/assets/5264563/21201085/d7deae7e-c249-11e6-93cd-54a255c7d102.png)
![screen shot 2016-12-14 at 22 04 13](https://cloud.githubusercontent.com/assets/5264563/21201086/d80a29dc-c249-11e6-95ab-fa5324d15555.png)
![screen shot 2016-12-14 at 22 04 19](https://cloud.githubusercontent.com/assets/5264563/21201087/d80aa86c-c249-11e6-99a3-0fde6c21bc32.png)

**Comment by liuxuan30** [comment]
You need to call `notiftyDatasetChanged()` after you set axisMaximum, or put chart.data = data at last.

**Comment by Tobisaninfo** [comment]
I tried both things, but it doesn't change anything. Can I send you something, that helps you by solving this issue?

**Comment by liuxuan30** [comment]
Have you checked out ChartsDemo radar chart?
Well you can upload a sample project so we could take a look.

**Comment by Tobisaninfo** [comment]
I'm sorry, but your sample chart wasn't helpful for my issue.
I'll copy my code and try to focus on the chart. I hope you have every thing you need. 
I'm looking forward to hear from you. Thanks.
[sample-chart.txt](https://github.com/danielgindi/Charts/files/676311/sample-chart.txt)

**Comment by liuxuan30** [comment]
Sorry I don't have a swift project to use your code. Either you upload a full project zip or reproduce it with ChartsDemo.

**Comment by liuxuan30** [comment]
I looked at the code, no big issue found.
BTW, use
```swift
    open func setLabelCount(_ count: Int, force: Bool)
    {
        self.labelCount = count
        forceLabelsEnabled = force
    }
```
to set label count
