### ISSUE TITLE
Graph doesn't display on older iPads

### ISSUE THREAD

**Issue by keeshux** [danielgindi/Charts#1954]
I spent a few hours before posting this. My graph performs pretty well on all devices, except older iPads, where it doesn't appear at all. Actually the y-axis seems to update to the new data sets, only the graph isn't being drawn. This applies to both a real device (iPad 2) and simulators (iPad 2, iPad Retina).

Thanks in advance.

**Comment by liuxuan30** [comment]
well.. It should have nothing to do with older iPad, just the iOS version and APIs.. And you are the first one to report this.
Before we look into this, you need to debug more and give more info, at least you should be able to post a screenshot, showing that the UIView of your chart is correctly added, having meaningful frame, but nothing rendered.

**Comment by keeshux** [comment]
Sorry Xuan, I erroneously thought I had specified that, surprisingly, it's not an iOS-related issue. In fact the graph works as expected on iPad Air 2 with 9.3 (to name one), and not on an iPad 2 with 9.3 as well. Later I'll post the relevant code bits, I'm not at home now.

**Comment by liuxuan30** [comment]
Interesting.. don't forget to add a screenshot for iPad 2. And if you can debug more, please do it, that will help because I don't have iPad 2 (simulator neither).

**Comment by keeshux** [comment]
I narrowed it down. My scenario is that I was using TimeInterval values for the X axis, and strange things happen when X values are so huge and lie within a small range. Here's the relevant code:

```
let y = [2271590059.0, 3371668096.0, 2128116851.0, 2766080740.0, 2610847501.0, 1444402694.0, 4261313944.0, 2930941047.0, 575994230.0, 1206051462.0]

var entries = [ChartDataEntry]()
let now = Date.timeIntervalSinceReferenceDate
for i in 0..<10 {
    let entry = ChartDataEntry(x: now + Double(i), y: y[i])
    entries.append(entry)
    print(entry)
}
let dataSet = LineChartDataSet(values: entries, label: "foobar")
chart.data = LineChartData(dataSet: dataSet)
```

Looks fine on iPad Pro:

![big_near_xs_ipad_pro](https://cloud.githubusercontent.com/assets/805724/21233878/24c5c5ae-c2f1-11e6-9f1c-0350ed480a35.png)

Not quite on iPad Retina:

![big_near_xs_ipad_retina](https://cloud.githubusercontent.com/assets/805724/21233879/24d5709e-c2f1-11e6-8b0b-4e32ea7b3ce1.png)

Now, I can use a different X mapping, but it may still be something you want to look into.

**Comment by Fedenieto90** [comment]
Same happens to my with timestamps on the xAxis. I also have some repeated values that I pass to the xAxis. When there is only one value, it works:

<img width="374" alt="screen shot 2016-12-16 at 5 48 28 pm" src="https://cloud.githubusercontent.com/assets/5543129/21278231/c7dd59b0-c3b8-11e6-8260-558630828f7f.png">


But if I have more values, the graph disappears as shown below:
<img width="374" alt="screen shot 2016-12-16 at 5 48 01 pm" src="https://cloud.githubusercontent.com/assets/5543129/21278182/7825af26-c3b8-11e6-90b1-8e2a9e3a4574.png">

**Comment by liuxuan30** [comment]
I guess it's related:https://github.com/danielgindi/Charts/issues/1956, https://github.com/danielgindi/Charts/issues/1679? All uses big unix time stamp, and a 32 bit CPU?

**Comment by Fedenieto90** [comment]
The three values used for the second chart are:
1449761040
1449761040
1422468000

Notice that two of them are equal, but it shouldn't be a problem. The values are NSTimeIntervals.
