### ISSUE TITLE
Multiple y-data for single x-index

### ISSUE THREAD

**Issue by vsujan92** [danielgindi/Charts#1955]
Hello there.
I have a combined chart viewf which contains candle chart and line chart. What I need is multiple y values for single x-index. Is there certain way I could achieve this?

Here is the screenshot of the code.
<img width="649" alt="screen shot 2016-12-13 at 9 50 05 am" src="https://cloud.githubusercontent.com/assets/19152943/21127288/db49854c-c119-11e6-839b-ff6dfd487461.png">

In case of Bar chart, its allowed like this:
-> BarChartDataEntry(x: Double, yValues: [Double])

But for other chart, there is no such option for initialization. How can I achieve like for bar chart?

**Comment by liuxuan30** [comment]
For bar chart, yValues are only used for stacked bar chart. For other chart, it is not supported. Consider a simple fact: when you draw a dot (x, y), why do you need another y?
If you really need, then you can subclass a bunch of classes and add the array yourself.

**Comment by rolyanos** [comment]
@liuxuan30, hello, is it possible to do multiple y-axis in current version?

**Comment by liuxuan30** [comment]
NO
