### ISSUE TITLE
Two y axis plot on a side?

### ISSUE THREAD

**Issue by Bhupendra-tbox** [danielgindi/Charts#1961]
can we add two y axis on same side in Combine chart with different points ?

**Comment by liuxuan30** [comment]
there are left and right axis currently. But no same side y axis.

**Comment by Bhupendra-tbox** [comment]
Thanks can i inherit existing class & make them on same side?

**Comment by liuxuan30** [comment]
well sure you can. But this requires you know how this library works and override a bunch of methods. If you are a seasoned dev, it's not hard though.
