### ISSUE TITLE
bar chart from dates

### ISSUE THREAD

**Issue by abara-kedavra** [danielgindi/Charts#1963]
HI! I try to make a bar chart from numbers and dates. As I know now I can use only "Double" values. But if I convert "Double(date.timeIntervalSince1970)" I get only a point in a day during one second, and my bars are too thin. Is it possible to show dates in Charts like whole day ("d MMM")? This example from Sami Korpela tutorial from your main page. I just use dates from database (day/month/year 21.00). 

```
weak var axisFormatDelegate: IAxisValueFormatter?
////////
let timeIntervalForDate: TimeInterval = objects[i].date!.timeIntervalSince1970
let dataEntry = BarChartDataEntry(x: Double(timeIntervalForDate), y: Double(objects[i].number))
dataEntries.append(dataEntry)   
////////
let xaxis = barView.xAxis
xaxis.valueFormatter = axisFormatDelegate
//////////
extension ViewController: IAxisValueFormatter {
     
func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "d MMM"
        return dateFormatter.string(from: Date(timeIntervalSince1970: value))
    }
}
```

**Comment by liuxuan30** [comment]
I suggest rethink what you need. Yes the x axis only take double for now, but you can definitely use int to format.. currently the formatter will have issue if you zoom in

**Comment by StevenPeeters** [comment]
@liuxuan30, So it is not possible to create a Bar chart with strings on the x axis and numbers on the y axis? I'm trying to create something like that in OSx with swift 3

**Comment by jonnyijapan** [comment]
Nothing?
