### ISSUE TITLE
Bar Graph groupBars function issue

### ISSUE THREAD

**Issue by KodiKraig** [danielgindi/Charts#1966]
I am working with the BarChartView object with all default properties.

The problem is when groupBars(fromX: Double, groupSpace: Double, barSpace: Double) is called, the _xMin and _xMax are not being adjusted properly. When notifyDataChanged() is called, it is calling calcMinMax() that calls calcMinMax(dataSet d: IChartDataSet)() which is not reflecting the true xMin and xMax values that were previously set in groupBars(fromX: Double, groupSpace: Double, barSpace: Double). 
My current fix was to loop over the entries and call calcMinMax(entry e: ChartDataEntry, axis: YAxis.AxisDependency)() instead. Which seems to be working fine with my current Charts implementation but it is not the optimal solution to the problem. Not only are we increasing the time complexity by at least a whole factor, the ChartDataSet objects containing the entries are not reflecting the correct values for xMin and xMax.

**Comment by liuxuan30** [comment]
Will you be able to fix it and file a pull request, following the code style?

**Comment by liuxuan30** [comment]
Wait, do you call notifyDataChanged() after you call groupBars()?

**Comment by KodiKraig** [comment]
Yes I have tried that and I still have no luck.

**Comment by liuxuan30** [comment]
@danielgindi do you know if xMin/Max works this way?

**Comment by KodiKraig** [comment]
Im not sure I understand exactly what your getting at. The logic for min/max and the calculations are always correct in all situations(at least as far as I have experienced). It is just this one edge case from groupBars were we are manipulating the data entries x values internally. The min/max values of the dataset object containing all the entries isn't reflecting these changes.

**Comment by liuxuan30** [comment]
I wanted to ask @danielgindi if 
>The problem is when groupBars(fromX: Double, groupSpace: Double, barSpace: Double) is called, the _xMin and _xMax are not being adjusted properly. When notifyDataChanged() is called, it is calling calcMinMax() that calls calcMinMax(dataSet d: IChartDataSet)() which is not reflecting the true xMin and xMax values that were previously set in groupBars(fromX: Double, groupSpace: Double, barSpace: Double).
works like you said, or it's a bug. This call is introduced in Charts v3, so I need he review this.

**Comment by KodiKraig** [comment]
Oh I see, I didn't realize the @ sign. My apologizes. I agree thou, I was shocked that there were no issues previously opened about this considering its a rather serious problem to get the function working correctly.

**Comment by liuxuan30** [comment]
@danielgindi have you checked this?
