### ISSUE TITLE
How to pass data to the X axis??

### ISSUE THREAD

**Issue by chaochaoaijie** [danielgindi/Charts#1967]
//BarChartData *data = [[BarChartData alloc] initWithXVals:xVals dataSets:dataSets];
In the latest version,The Function initWithXVals:XXX dataSets:XXX does not exist.

so?How to pass data to the X axis??? I am a novice, thank you all.

**Comment by MonkeyRing** [comment]
Have a look at IndexAxisValueFormatter. As far as i know it is the recommended way to do this.
 I pointed this out in Issue #1909 .
