### ISSUE TITLE
Version 3.0.1: Fill gradient fills out the wrong side of the chart

### ISSUE THREAD

**Issue by 4np** [danielgindi/Charts#1968]
Where the fill gradient generally works as expected I noticed a single instance where it filled out the wrong side of the `LineChartView`. Unfortunately I do not have any steps to reproduce, but it would appear there is some bug with the fill logic.

![screen shot 2016-12-16 at 13 09 09](https://cloud.githubusercontent.com/assets/1049693/21262360/3c5d290a-c391-11e6-9609-1ca529dbc6ec.png)

The specific `LineChartDataSet` fill gradient logic involved:

```
        let set = LineChartDataSet(values: dataEntries, label: "")

        ...

        // add fill gradient
        let locations: [CGFloat] = [ 0.0, 1.0 ]
        let colors = [UIColor.white.cgColor, UIColor.cyan.cgColor] as CFArray
        let colorspace = CGColorSpaceCreateDeviceRGB()
        
        guard let gradient = CGGradient(colorsSpace: colorspace, colors: colors, locations: locations) else {
            return set
        }
        
        // fill with gradient
        set.fillAlpha = 1
        set.fill = Fill(linearGradient: gradient, angle: 90)
        set.drawFilledEnabled = true
        
        return set
```

**Comment by petester42** [comment]
If you could provide use the values of dataset that would make it easier to find the issue. Thanks!

**Comment by 4np** [comment]
Looking again at this specific issue I am noticing that most of the values are negative while the last part consists of positive values. It seems like the fill gradient is always applied to the surface between the DataSet's line and the x-axis instead of always below the DataSet line.

**Comment by 4np** [comment]
I can consistently reproduce by negating the values, consider the following screenshot. Left is the a chart, and on the right is the exact same chart but then with the values negated. 

![pasted_image_16_12_16_16_52](https://cloud.githubusercontent.com/assets/1049693/21268774/5f6e0c1a-c3b0-11e6-87d4-864435f61b33.jpg)

**Comment by liuxuan30** [comment]
I don't see any problem? The filling feature's arouding zero line. So it fill the rect among zero line and other lines.

**Comment by 4np** [comment]
@liuxuan30 : thank you for your answer, using a custom fill formatter solves the issue I am having 👍 

To document to whoever runs into this particular issue again: I have added my own fill formatter.

Update to the dataset:

```
        // create dataset
        let set = LineChartDataSet(values: dataEntries, label: "")
        ...
        
        // use custom fill formatter
        set.fillFormatter = MyFillFormatter()
```

And the fill formatter:

```
class MyFillFormatter: IFillFormatter {
    func getFillLinePosition(dataSet: ILineChartDataSet, dataProvider: LineChartDataProvider) -> CGFloat {
        guard let yMin = dataProvider.lineData?.yMin, let yMax = dataProvider.lineData?.yMax else {
            return 0
        }
        
        let yRange = yMax - yMin
        let spaceBottomFactor = dataProvider.getAxis(YAxis.AxisDependency.right).spaceBottom
        let yBottom = yMin - (yRange * Double(spaceBottomFactor))
        
        return CGFloat(yBottom)
    }
}

```

**Comment by MarcinDe** [comment]
I was able to make the fill always draw below the line by simply initializing my values to MinY and using native MyFillFormatter.
