### ISSUE TITLE
Multiline chart with common data point

### ISSUE THREAD

**Issue by gsuneelji** [danielgindi/Charts#1970]
How to distinguish a data point if two line datasets have a common data point.

This is what I expect
![expected](https://cloud.githubusercontent.com/assets/10258021/21268426/c3197e6a-c3d4-11e6-913f-bf4be98e6c05.png)

This is what it is rendered
<img width="309" alt="screen shot 2016-12-16 at 9 10 29 pm" src="https://cloud.githubusercontent.com/assets/10258021/21268427/c3223e7e-c3d4-11e6-98c5-5a61a570e7b3.png">

`override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        months = ["M", "T", "W", "TH", "F", "S", "SU"]
        setChart(months)
    }

    func setChart(dataPoints: [String]) {
        lineChartView.noDataText = "You need to provide data for the chart."
        
        var dataEntries1: [ChartDataEntry] = []
        let values1 = [5.0, 4.0, 3.0, 4.0, 3.0, 1.0, 2.0]
        for i in 0..<dataPoints.count {
            let dataEntry = ChartDataEntry(value: values1[i], xIndex: i)
            dataEntries1.append(dataEntry)
        }
        let chartDataSet1 = LineChartDataSet(yVals: dataEntries1, label: "Units Sold")
        chartDataSet1.setColor(UIColor.blackColor())
        chartDataSet1.setCircleColor(UIColor.blackColor())
        
        
        var dataEntries2: [ChartDataEntry] = []
        let values2 = [4.0, 2.0, 3.0, 5.0, 2.0, 3.0, 1.0]
        for i in 0..<dataPoints.count {
            let dataEntry = ChartDataEntry(value: values2[i], xIndex: i)
            dataEntries2.append(dataEntry)
        }
        let chartDataSet2 = LineChartDataSet(yVals: dataEntries2, label: "Quantities Sold")
        chartDataSet2.setColor(UIColor.redColor())
        chartDataSet2.setCircleColor(UIColor.redColor())
        
        
        let chartData = LineChartData(xVals: months, dataSets: [chartDataSet1, chartDataSet2])
        lineChartView.data = chartData
        lineChartView.xAxis.labelPosition = .Bottom
    }`

**Comment by KodiKraig** [comment]
Is this a question? I see a rendered pic with the only common data point circled.

**Comment by gsuneelji** [comment]
Yeah. This is a question/requirement. The first pic is what I expect, to clearly distinguish both colors. But the graph that is rendered using Charts (second pic), the black circle is overridden by red circle. I want the chart to display both black & red colors clearly at a common data point as shown in the first pic

**Comment by KodiKraig** [comment]
Try adjusting these properties as you add the data sets:
        data.circleRadius = CGFloat(5.0)
        data.circleHoleRadius = CGFloat(2.0)
The only problem is that it will increase the size at all points which is not exactly what you want I think. To increase an individual one you'll have to it custom considering the circleRadius is a property of the data set object.

**Comment by liuxuan30** [comment]
it's about orders for which render above which and make some changes about the circle or something..
