### ISSUE TITLE
I am gettign @import AppKit is missing in Charts-Swift.h under charts.framework

### ISSUE THREAD

**Issue by dileep017** [danielgindi/Charts#1971]
I tried to configure CI job for my build and tried to build now,while building the workspace i am getting the below errors,

/Users/***/***/workspace/"Projectname"/build/Release-iphoneos/Charts.framework/Headers/Charts-Swift.h:116:9: error: module 'AppKit' not found
@import AppKit;

Can some one please suggest how it is occurring and how to resolve?

**Comment by liuxuan30** [comment]
I searched it does not import AppKit at all... Would you double check? Refer ChartsDemo as well.

**Comment by dileep017** [comment]
I have referred to ChartsDemo,it didnt import any Appkit.

**Comment by dileep017** [comment]
But still getting the same error in my jenkins job.

**Comment by liuxuan30** [comment]
Yes, that's why we don't know what happened for your jenkins and where is it from.. You need to check yours
