### ISSUE TITLE
Labels on Mac OS X application : place and title

### ISSUE THREAD

**Issue by satan87** [danielgindi/Charts#1972]
Hello,

I'm trying to place labels on a chart, with specific title but so far i have no luck.

I use this to display the labels 
`self.barChartView.xAxis.drawLabelsEnabled = true`

and i got this 
![image](https://cloud.githubusercontent.com/assets/5104971/21275630/bf4e16d0-c39b-11e6-881c-f887f1dfce7a.png)

What i would like is for the label to be just under each bar.
i also would like to rename the labels with the right date.
In my example, not from 0 to 18 but from 1995 to 2016.

Any idea how to do this please ?

thanks,
Nicolas

**Comment by liuxuan30** [comment]
1. xAxis.labelPosition = XAxisLabelPositionBottom;
2. use valueFormatter to format 0-18 to 1995-2016.
You should check out ChartsDemo first pal
