### ISSUE TITLE
How to Show XAxis Label On YAxis Bar In BarView Charts?

### ISSUE THREAD

**Issue by alipishvaee** [danielgindi/Charts#1973]
IS There Any Solution For Showing Labels Inside Of Chart In A way That Each Label Show On its Relevent YAxis???

**Comment by liuxuan30** [comment]
Just subclass and provide your methods to display the values.

**Comment by alipishvaee** [comment]
is there any sample?i m newbie in IOS.

**Comment by liuxuan30** [comment]
well.. if you are new, I suggest slow down, read the code, and learn CoreGraphics APIs and try out. There is no sample for your question.
