### ISSUE TITLE
When I have two data, charts shows the three data automatically

### ISSUE THREAD

**Issue by MrReN** [danielgindi/Charts#1978]
![3e19e67ddcd1a63ebe0a9f3df9befa07](https://cloud.githubusercontent.com/assets/4970702/21309235/7083a4a0-c618-11e6-8403-7d986958907d.jpg)
Please

**Comment by danielgindi** [comment]
If you're talking about the x axis labels, then you can control that with `granularity = 1.0`. There are many issues mentioning this.
