### ISSUE TITLE
For X axis the values are not adding

### ISSUE THREAD

**Issue by raju123lexicon** [danielgindi/Charts#1979]
Actually when we adding x values to LineChartData() in  MultiLineGraph.This is not supporting in Swift 3 for adding X axis values,Please Could you tell me when it is fixed.

**Comment by danielgindi** [comment]
Please look at the demos. The API has changed a little with Charts 3.0 to match the new methodology. There is no more "x values", just "values". Values are on x+y axis, and their labels come from formatters.

You can also read the migration notes of Charts 3.0
