### ISSUE TITLE
no limitLineSegmentsBuffer in YAxisRenderer

### ISSUE THREAD

**Issue by leonidster** [danielgindi/Charts#1981]
Hi,

I migrated to Charts 3.0 from 2.x in our project.

I used the object limitLineSegmentsBuffer in YAxisRenderer class.

I have these lines of code to draw custom limit line:

        _limitLineSegmentsBuffer[0].x = viewPortHandler.contentLeft; // swift3 no limitLineSegmentsBuffer property
        _limitLineSegmentsBuffer[0].y = position.y;
        _limitLineSegmentsBuffer[1].x = viewPortHandler.contentRight;
        _limitLineSegmentsBuffer[1].y = position.y;

What is the alternative code for these lines?

**Comment by danielgindi** [comment]
That is a private member of the class. It's just an array of `CGPoint`, you can create your own.
