### ISSUE TITLE
Can't compile DemoProject

### ISSUE THREAD

**Issue by Jan-M-B** [danielgindi/Charts#1986]
Hi,

I am not able to compile the DemoProject, I am using Xcode 7.3.1.

I get more than 999+ errors:
http://www2.pic-upload.de/img/32328874/Bildschirmfoto2016-12-20um16.57.26.png

I haven't changed anything ...

Any idea?

Jan

**Comment by petester42** [comment]
You need Xcode 8. The project uses swift 3
