### ISSUE TITLE
ChartViewDelegate is not called.

### ISSUE THREAD

**Issue by imadeit** [danielgindi/Charts#1988]
Hi,

I tried to update to 3.0.1, and I am trying to draw LineChartView, but even I set delegate of LineChartView, the method:
func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: Highlight)

is never called.
I am confused what else should I do.
Is there anybody coming with the same problem?

Thanks!

**Comment by KodiKraig** [comment]
Are you setting the chart view's delegate upon initialization? 

`        lineChartView.delegate = self
`

**Comment by liuxuan30** [comment]
Try ChartsDemo and check what @KodiKraig said.

**Comment by HPRaval** [comment]
well i have checked demo...and method is not called with line chart in demo version also
