### ISSUE TITLE
Multiple colors issue in stacked bar line charts swift3

### ISSUE THREAD

**Issue by jiheneme** [danielgindi/Charts#1989]
Hi everyone,

I need to create a stacked bar chart with 3 dataSets like this : 

<img width="808" alt="capture d ecran 2016-12-21 a 10 53 42" src="https://cloud.githubusercontent.com/assets/24694992/21384599/7ae527bc-c76b-11e6-9eb4-d759e536fa8e.png">

But when I used this code : 
********************** Begin ******************************
    let chiffreAffaire = [3282.0, 4179.0]
    let chiffreAffaireDetails1 = [788.0, 889.0]
    let chiffreAffaireDetails2 = [300.0, 330.0]
    let chiffreAffaireDetails3 = [2247.0, 1843.0]

        var yse1 = chiffreAffaireDetails1.enumerated().map { x, y in return BarChartDataEntry(x: Double(x), y: y) }
        var yse2 = chiffreAffaireDetails2.enumerated().map { x, y in return BarChartDataEntry(x: Double(x), y: y) }
        var yse3 = chiffreAffaireDetails3.enumerated().map { x, y in return BarChartDataEntry(x: Double(x), y: y) }
        var yse = chiffreAffaire.enumerated().map { x, y in return BarChartDataEntry(x: Double(x), y: y) }

        let data = BarChartData()
        let ds1 = BarChartDataSet(values: yse1, label: "")
        let ds2 = BarChartDataSet(values: yse2, label: "")
        let ds3 = BarChartDataSet(values: yse3, label: "")
        let ds4 = BarChartDataSet(values: yse, label: "")
        
        data.barWidth=0.6
        
        ds4.setColor (UIColor.detailsBtnGreen)
        ds4.valueFont=UIFont(name:"Avenir-Book" ,size:20.0)!
        data.addDataSet(ds4)
      
        ds2.setColor (UIColor.pistachioGreen)
        ds2.valueFont=UIFont(name:"Avenir-Book" ,size:20.0)!
        ds2.valueTextColor=UIColor.white
        data.addDataSet(ds2)
        
        ds1.setColor (UIColor.pinkBar)
        ds1.valueFont=UIFont(name:"Avenir-Book" ,size:20.0)!
        ds1.valueTextColor=UIColor.white
        data.addDataSet(ds1)
        
        ds3.setColor(UIColor.royalBlue)
        ds3.valueFont=UIFont(name:"Avenir-Book" ,size:20.0)!
        ds3.valueTextColor=UIColor.white
        data.addDataSet(ds3)

        self.barChartView.data = data
********************** End ******************************

I had this result : 
<img width="806" alt="capture d ecran 2016-12-21 a 10 53 59" src="https://cloud.githubusercontent.com/assets/24694992/21384757/27a669f2-c76c-11e6-803b-ddb222dd41d5.png">

The problem is that it takes only the first and the last dataSet colors !

Someone can help me please ? 
Thanks in advance ( and sorry for my bad english ;-) )

**Comment by liuxuan30** [comment]
Please check out ChartsDemo, there are full examples.. As far as I know from your picture, there should only be one data set with multiple entries.

**Comment by HPRaval** [comment]
there is no example for swift 3. is there any?
