### ISSUE TITLE
Piechart issue

### ISSUE THREAD

**Issue by aps112** [danielgindi/Charts#1990]
I am trying to upgrade implement pie-chart in swift 3, its not working. Also didn't get any demos in swift3. Not able to get how to use **IChartDataSet**
<img width="709" alt="screen shot 2016-12-21 at 8 51 55 pm" src="https://cloud.githubusercontent.com/assets/3863295/21394662/88cb5fb4-c7bf-11e6-9621-734df0c4c2f6.png">

**Comment by danielgindi** [comment]
From your code I'm not even sure what you're trying to do. `PieChartDataSet` is the name of a class.

Please LOOK AT THE DEMOs.
If you don't know how to compile the demos, look at the README.
