### ISSUE TITLE
 How to add tips to RadarChartView

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#1991]
When I click RadarChartView A position on how to let it pop up a prompt box
![6f95807e-42d8-4b22-b63c-f545c5769d6f](https://cloud.githubusercontent.com/assets/8455023/21411733/acc617c2-c825-11e6-980d-a089bd4aa327.png)

Like the following picture effect
![69c144ea-8f67-455e-83ac-4bf8e795799c](https://cloud.githubusercontent.com/assets/8455023/21411744/ca07acce-c825-11e6-8e61-bfa8543b1818.png)
  

How to get the coordinates of the click point？
Please help me thank you

**Comment by githubkiven** [comment]
I'm using    charts    Version2.2.5

**Comment by liuxuan30** [comment]
well it's an old version, and it's called ChartMarker

**Comment by githubkiven** [comment]
@liuxuan30  thank you

**Comment by githubkiven** [comment]
Merry Christmas

**Comment by githubkiven** [comment]
ChartMarker Can only set the picture?Not a custom view？
![76a68836-5e1d-4f81-8082-69ec4be12720](https://cloud.githubusercontent.com/assets/8455023/21511475/548f0814-ccdc-11e6-8ca0-f4b5cce227e2.png)

**Comment by liuxuan30** [comment]
sure you can. But if you are asking 2.x version, you need to look at ChartMarker definition. I already forgot.
In the 3.x version, it's more flexible like `open class MarkerView: NSUIView, IMarker`
Just check the demos and `BalloonMarker`

**Comment by githubkiven** [comment]
@liuxuan30  thank you。
I will upgrade as soon as possible
