### ISSUE TITLE
Installation not clear, for me

### ISSUE THREAD

**Issue by SylarRuby** [danielgindi/Charts#1994]
Hi guys. Newbie here.

Instructions not clear for me. Ive added `pod 'Charts'` then `pod install`. With other modules, I would only `import XXX` and it'll show up. What else to do with Charts? I'm using Swift 3. Have I missed something?

Usage No.1, drag what file? Where is that?

**Comment by SylarRuby** [comment]
Is there a Swift demo/doc?

**Comment by petester42** [comment]
To better understand, you have used cocoapods before and you can't get charts to work?

**Comment by SylarRuby** [comment]
I've installed it but lost from there. Any demo in swift?

**Comment by patreu22** [comment]
https://www.raywenderlich.com/97014/use-cocoapods-with-swift

That's a nice guide. There's no difference between charts and any other Cocoapod.

**Comment by SylarRuby** [comment]
@patreu22 Thanks
