### ISSUE TITLE
Is there any way to change chart data label from bottom of table to top?

### ISSUE THREAD

**Issue by vahids** [danielgindi/Charts#1995]
let hum  = LineChartDataSet(yVals: dataEntriesHum, label: "hum")

"hum" width a little square icon will be placed in bottom of table, is there any way to move it on top ?
![chart](https://cloud.githubusercontent.com/assets/1405424/21419291/05cdc106-c83c-11e6-9b22-f1a60431f446.jpg)

**Comment by KodiKraig** [comment]
I would look through the Legend classes but I don't think there is an option for this, you will most likely have to implement it custom.

**Comment by MonkeyRing** [comment]
The following attributes can meet your requirements? you can try  

![one](https://cloud.githubusercontent.com/assets/8415820/21496863/8c5e2138-cc5c-11e6-978c-57a39026138a.png)

![two](https://cloud.githubusercontent.com/assets/8415820/21496876/9b083264-cc5c-11e6-97ac-5deac3a54241.png)

**Comment by liuxuan30** [comment]
If not, you can file a pull request to support more :)
