### ISSUE TITLE
I want touchpoint in the bar to do something

### ISSUE THREAD

**Issue by Minhoryu** [danielgindi/Charts#1996]
func getHighlightByTouchPoint:point, the point always the closest, I want the point is in the bar not the closest. How can I do it ? or how to get a bar frame? ChartHighlight.xPx and h.yPx can get the top center point, but can't get the bar width... I really need some help...

**Comment by KodiKraig** [comment]
Not sure if your talking about this or actually getting the drawing coordinates. Here I am getting the data point for each gesture via the delegation functions. Maybe this will help!

`    
func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        if let chart = chartView as? LineChartView {
            chart.chartDescription?.text = "x: \(entry.x) y: \(entry.y)"
        } else if let chart = chartView as? BarChartView {
            chart.chartDescription?.text = "x: \(entry.x) y: \(entry.y)"
        } else if let chart = chartView as? HorizontalBarChartView {
            chart.chartDescription?.text = "x: \(entry.x) y: \(entry.y)"
        } else if let chart = chartView as? ScatterChartView {
            chart.chartDescription?.text = "x: \(entry.x) y: \(entry.y)"
        }
    }
    
    func chartValueNothingSelected(_ chartView: ChartViewBase) {
        if let chart = chartView as? LineChartView {
            chart.chartDescription?.text = ""
        } else if let chart = chartView as? BarChartView {
            chart.chartDescription?.text = ""
        } else if let chart = chartView as? HorizontalBarChartView {
            chart.chartDescription?.text = ""
        } else if let chart = chartView as? ScatterChartView {
            chart.chartDescription?.text = ""
        }
    }
`

**Comment by liuxuan30** [comment]
well, please take a look at BarChartRenderer to see how the barRect is calculated: `fileprivate func prepareBuffer(dataSet: IBarChartDataSet, index: Int)`
