### ISSUE TITLE
Always display max 5 visible bars in BarChartView

### ISSUE THREAD

**Issue by Zwaaan** [danielgindi/Charts#1997]
Hi! I really love your charts! Been using it or a while but I can't figure out one thing

I have a BarChartView with pretty many bars. What I would like to do is to let the chart automatically scale/zoom the chart so only 5 bars is visible from the beginning. Now it displays alla the bars which is quite many! 

How can I achieve this?

**Comment by ryanschneider** [comment]
Assuming the `x` values of your entries are 0.0, 1.0, 2.0.. etc., try using:

`myBarChart.setVisibleXRange(minXRange: 5.0, maxXRange: 5.0)`

Where myBarChart is your BarChartView.  I haven't really used BarCharts, just line charts, but that works for me on those.

**Comment by liuxuan30** [comment]
And read the comment carefully:
```swift
    /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    ///
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    open func setVisibleXRange(minXRange: Double, maxXRange: Double)
    {
        let minScale = _xAxis.axisRange / maxXRange
        let maxScale = _xAxis.axisRange / minXRange
        _viewPortHandler.setMinMaxScaleX(
            minScaleX: CGFloat(minScale),
            maxScaleX: CGFloat(maxScale))
    }
```
>/// If you call this method, chart must have data or it has no effect.

I don't want to see another issue regarding the function does not work 😂
