### ISSUE TITLE
Can't compile under Xcode 8.1 with Swift 3.0

### ISSUE THREAD

**Issue by beeb** [danielgindi/Charts#1998]
Hey all,

I installed Charts with cocoapods but when I try to compile, I get a long long list of errors:

![errors](https://beeb.li/chartserrors.png)

Am I missing something? Do I require a newer version of Xcode? Are there specific build settings I should setup?

**Comment by petester42** [comment]
Are you using version 3.0 or above of charts?

**Comment by beeb** [comment]
I'm not too sure, I just added pod 'Charts' to my podfile. Isn't this supposed to get the latest version?

**Comment by beeb** [comment]
Oh wait.. It installed 2.2.5 for some reason. How can I get 3.0 with cocoapods?

**Comment by petester42** [comment]
If you do `~> 3.0` then it should work. Otherwise deleted the pod file.lock and install again

**Comment by beeb** [comment]
In fact I only see versions `2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.1.6, 2.1.5, 2.1.4, 2.1.4a,
   2.1.3, 2.1.2, 2.1.0, 2.0.9` as available.

**Comment by petester42** [comment]
Oh ok. You will need to update your local pod repo. This is a change with cocoapods 1.0. The command is `pod repo update`. You should see the new versions after that.
