### ISSUE TITLE
XAxis in top AND bottom position

### ISSUE THREAD

**Issue by patreu22** [danielgindi/Charts#1999]
Hey guys,

I'm looking for a way to draw the xAxis on top and bottom of the chart.
So I want to keep the values above the bars, but I would love to have a stroke under the charts too (without any labels). Is there any solution?

<img width="366" alt="bildschirmfoto 2016-12-22 um 22 10 15" src="https://cloud.githubusercontent.com/assets/11362357/21440513/9e8e4e04-c893-11e6-8233-74727060c67b.png">

Thats my current solution and I think it would look much better with the stroke under the bars.

Thx for your help! :)

**Comment by liuxuan30** [comment]
are you asking for axis line? I don't remember the current logic - whether the axis line is on the same side of the axis labels. But you could try to find out. If not, you can override and draw the other axis line.
