### ISSUE TITLE
Values are cut out of the window

### ISSUE THREAD

**Issue by patreu22** [danielgindi/Charts#2000]
Hey, 

I set up the labelSize of my X Values, but now it's to big to fit the charts frame. 
How do I change the BarChartViews behaviour to have enough space for my labels?

<img width="365" alt="bildschirmfoto 2016-12-22 um 22 15 42" src="https://cloud.githubusercontent.com/assets/11362357/21440640/35f7ccb6-c894-11e6-833c-062968f8d5a9.png">

**Comment by KodiKraig** [comment]
Did you play with all the offset properties like "barChartView.extraTopOffset", "barChartView.extraBottomOffset", etc.?

**Comment by liuxuan30** [comment]
Well this needs careful check:
By default, when calculating space, the font is being included:
```swift
    open func computeSize()
    {
        guard let
            xAxis = self.axis as? XAxis
            else { return }
        
        let longest = xAxis.getLongestLabel()
        
        let labelSize = longest.size(attributes: [NSFontAttributeName: xAxis.labelFont])
        
        let labelWidth = labelSize.width
        let labelHeight = labelSize.height
        
        let labelRotatedSize = ChartUtils.sizeOfRotatedRectangle(labelSize, degrees: xAxis.labelRotationAngle)
        
        xAxis.labelWidth = labelWidth
        xAxis.labelHeight = labelHeight
        xAxis.labelRotatedWidth = labelRotatedSize.width
        xAxis.labelRotatedHeight = labelRotatedSize.height
    }
```
Then in `internal override func calculateOffsets()`:
```swift
            if xAxis.isEnabled && xAxis.isDrawLabelsEnabled
            {
                let xlabelheight = xAxis.labelRotatedHeight + xAxis.yOffset
                
                // offsets for x-labels
                if xAxis.labelPosition == .bottom
                {
                    offsetBottom += xlabelheight
                }
                else if xAxis.labelPosition == .top
                {
                    offsetTop += xlabelheight
                }
                else if xAxis.labelPosition == .bothSided
                {
                    offsetBottom += xlabelheight
                    offsetTop += xlabelheight
                }
            }
```
The label height should be correct and have enough space to draw.
@patreu22 I need you carefully check your xAxis label height if the font is correct. And make sure you don't set a negative `xAxis.yOffset`. 
One more thing to mention is that, when you change anything that will impact the space, please call `notifyDataSetChanged()` or put `chart.Data = data` at last line.
Anything that would change the layout afterwards will not be included.

If you still find the issue, please use ChartsDemo to reproduce it, and post the code.

**Comment by patreu22** [comment]
Thanks for the nice explanations, I made it work now 👍

**Comment by kuwait** [comment]
I think there is an error here @liuxuan30. 

```
 let longest = xAxis.getLongestLabel()
 let labelSize = longest.size(attributes: [NSFontAttributeName: xAxis.labelFont])
```

Your calculating the right size for the wrong longest label. getLongestLabel counts the Chars of that string but there are characters bigger than other depending on the font you use. You should get the longestLabelSize with the font you are using.
