### ISSUE TITLE
it is not an issue. it is related to OHLC chart 

### ISSUE THREAD

**Issue by IshuPhogat** [danielgindi/Charts#2003]
hi @danielgindi ,
firstly thanks for making this great library. This is great.

But at this time I am facing a problem and want to your suggestion/help.
I have an app in which your chart's library has been implemented. This app is in Obj-C language.
Now I want to implement OHLC and many more chart view in it. This is my first project on chart and I made most of charts in it using @danielgindi charts . but i couldn't understand, How to make OHLC chart in it.

Please give me any suggestion.

thanks

**Comment by KodiKraig** [comment]
I have been working with Charts for awhile now but I am not sure what "OHLC" stands for. Could you elaborate?

**Comment by IshuPhogat** [comment]
A simple variant on the OHLC chart is the HLC high-low-close chart that identifies the range of the time unit's price action (high - low) and the end result of the time unit's price action (the close).

In technical analysis OHLC charts are often combined with charts of other types such as line charts (showing moving average), column charts (trading volume), and range areas (Bollinger Bands).

have a look on below images...

![screen shot 2016-12-26 at 10 27 32 am](https://cloud.githubusercontent.com/assets/16267051/21475783/8b3f48ec-cb56-11e6-8e6b-f24167725f0e.png)

group of this type of Bollinger Bands made a OHLC chart. and i want to made a chart like this :- 

![screen shot 2016-12-26 at 10 18 29 am](https://cloud.githubusercontent.com/assets/16267051/21475802/c78eae82-cb56-11e6-977c-a5b5a8a1cf27.png)

if you have any idea or suggestion that how will I draw a chart like the above image then please suggestion me.

Thanks

**Comment by liuxuan30** [comment]
Ah a more difficult chart!
This library provides a way to implement more charts based on the APIs. I would suggest you take a look at how candle stick chart is implemented first, and walk through the library to know how it works.

Normally, the process is:
1. figure out how to draw your chart. e.g. where to start, how to render, and where to end, and the next loop. This requires you to understand CoreGraphics APIs to draw the shape.
2. After you know how to draw the shape, you should start thinking about how to write you chart data and data entries to get the data you need when drawing.
3. Leverage the axis/contentRect concepts and APIs of this library to draw your chart.
