### ISSUE TITLE
How to display last label in X-Axis

### ISSUE THREAD

**Issue by mahin8514** [danielgindi/Charts#2007]
![simulator-screen-shot-dec-23 -2016 -3](https://cloud.githubusercontent.com/assets/24287570/21476097/4bf68c6e-cb5a-11e6-9b12-8db299640e02.jpg)

I want to display the last x-axis Time label for my chart. I used the code 
magneticChart.xAxis.setLabelsToSkip(239) to magneticChart.xAxis.setLabelsToSkip(238). Then it shows last time label. but the time intervals changed. and not getting the exact time of first label. I need both first and last label of time to be same.

**Comment by liuxuan30** [comment]
try `avoidFirstLastClippingEnabled`. BTW, it's old version of your library, so it's not supported in the future.
setLabelsToSkip works like a modules, it's not a guarantee to show the last label. like pos += interval.

**Comment by mahin8514** [comment]
avoidFirstLastClippingEnabled not solved my problem.

**Comment by vaibhav-varshaaweblabs** [comment]
Exactly, `avoidFirstLastClippingEnabled` does not help. The last label always gets cut

**Comment by liuxuan30** [comment]
OK.. Then we need more info:
1. what's your code base version? Latest master? I recall an old 3.x code base has such bug?
2. Can you reproduce it with ChartsDemo?

**Comment by liuxuan30** [comment]
Please take a look at #2006 since this one is dup. We will move to #2006
