### ISSUE TITLE
Demo issues

### ISSUE THREAD

**Issue by CoderZyc** [danielgindi/Charts#2008]
When i run the demo. Downloading realm-cocoa.framework binary at "v2.1.2 ,The request timed out

**Comment by liuxuan30** [comment]
:( try again later.. or manual install it.

**Comment by CoderZyc** [comment]
I'm sorry to disturb again. I had keep try for 2 days.I try manual install it,but it don't work,did i miss something?

**Comment by CoderZyc** [comment]
One more question，can i user CombinedChartView show data like a scrollView?

**Comment by liuxuan30** [comment]
by default, when you zoom in, the chart will scroll, but it's not like how UIScrollView works.

**Comment by CoderZyc** [comment]
Thank you very much.
