### ISSUE TITLE
How to set up a line chart, the starting point of the distance from the left margin, border distance end points

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/Charts#2013]
How to set up a line chart, the starting point of the distance from the left margin, border distance end points

Another problem is the previous version of the [[LineChartData alloc] initWithXVals: xVals dataSet: characters];Be replaced by which method, now  how to customize the content on X xVals
Thank you very much

**Comment by liuxuan30** [comment]
1. I don't understand, maybe `axisMinimum`
2. use valueFormatter to format your x values, now x axis behaves like y xis.
