### ISSUE TITLE
引入工程后包很大

### ISSUE THREAD

**Issue by StarRain-L** [danielgindi/Charts#2015]
有没有人遇见,工程引入后,打包的包很大

**Comment by liuxuan30** [comment]
It's about Swift as embedded library.

**Comment by StarRain-L** [comment]
![e49f6edf-9c19-4ae1-8cdc-3aec83a6156f](https://cloud.githubusercontent.com/assets/8908244/21535429/cf65ce28-cdaf-11e6-92a6-3209da560061.png)
ChartsDemo 这个打包都244M,,这是为什么呢

**Comment by liuxuan30** [comment]
Well, it depends.. xcarhive is not the binary you download from AppStore. So you can't say this way.

**Comment by StarRain-L** [comment]
谢谢回答,,,但是不是太明白,对于这个问题,应该怎么引用Charts.xcodeproj?

**Comment by liuxuan30** [comment]
Let me explain more with this opportunity:

xcarchive contains all the stuff, like dSYM, assets, binaries, third party frameworks, etc. And remember it has to support x64 and 386 CPU (fat mach-o). So usually, it depends on how many you have for third party and your assets (images, pdfs, videos, etc).

Take ChartsDemo as reference, you can right-click the package to see the components, and you will find that Charts framework takes about 23M. That's not small indeed, but remember it's not optimized yet.

When you export it or upload it to AppStore, it will optimize and make it like 6.5M:
![image](https://cloud.githubusercontent.com/assets/4375169/21535715/e65ebcd0-cdb3-11e6-8b81-737d62ad79c4.png)

So.. 6.5M is not that small depends on your app size.. But we don't take it as a high priority to reduce the size. We just code and let Xcode handle the rest.

You can read README to know how to import Charts.

**Comment by StarRain-L** [comment]
明白你说的,ChartsDemo 从github上下载下来时5.9M,运行后变成357M,通过显示包内容,分析了一下,swift依赖库可以删除吗?还有其它的可以删除吗?谢谢!!!
![912c0f09-b475-4968-b132-abad2446888d](https://cloud.githubusercontent.com/assets/8908244/21536059/7b64a78c-cdb8-11e6-9f64-0a0175ba0f25.png)
![8a38f90c-c886-4509-8e5a-5d24f11a088e](https://cloud.githubusercontent.com/assets/8908244/21536060/7d0091f0-cdb8-11e6-8f07-7f77d2459e9b.png)

**Comment by liuxuan30** [comment]
I don't think these are the things you should worry about. Leave it be.

**Comment by StarRain-L** [comment]
Charts.xcodeproj 拖进我的项目,项目打包增加了200M,如果上传AppStore不会这么大吗?谢谢!!!

**Comment by liuxuan30** [comment]
Well you should check it yourself. If size matters so much for you.

**Comment by StarRain-L** [comment]
谢谢,thank you !!!

**Comment by StarRain-L** [comment]
Excuse me.Project has been submitted to AppStore, now package is 58.4 M, before is 32.9 M, is this rise is normal, please?

**Comment by liuxuan30** [comment]
you can check when Apple approves and what's the size when you download.

**Comment by StarRain-L** [comment]
I can  check   the size when Apple approves,but I don't know how to  check  the size when you download. because i use TestFlight ! I'm sorry to trouble you again, but I don't know how to get it!!
show the ipa content
![222](https://cloud.githubusercontent.com/assets/8908244/21704943/7aaf6436-d3f7-11e6-9dee-34c6791e690a.png)
![1111](https://cloud.githubusercontent.com/assets/8908244/21704950/93a51224-d3f7-11e6-809d-f0ce095bff6e.png)

**Comment by petester42** [comment]
From what you posted most of the size comes from swift. If you can examine when charts is 17mb that is the only thing we can change. Everything else is something you're gonna have to bug apple about.

**Comment by liuxuan30** [comment]
I am not sure how TestFlight handles the package, but after you upload to AppStore, apple will help to extract the binary for different arch. e.g. for iPhone 5s and above, you don't have to download 32bit binary. You can try to check the binary from TestFlight if it contains both 32 and 64 bit arch.

As I mentioned earlier, on my side, Charts after optimization becomes only 6.5M:
![image](https://cloud.githubusercontent.com/assets/4375169/21796044/da722a4c-d740-11e6-8c28-d6ae881a9a02.png)
I would admit 6.5M is not ideal compared to Realm framework, but that's not our priority for now. If it's just about configuration to shrink the size, we would consider for sure.

Last but not least: I really don't understand why the size matters so much to you and you struggled for this and only mentioning Charts.. As you see, swift framework is much larger, and it's your call to use swift or not.. Personally, people does not care to download or not no matter the app size is 30M or 50M. If your boss asked for this, then you should probably write your own code.. or pick another company 😂

**Comment by liuxuan30** [comment]
Oh one more thing, the size you see it's 17M that's because you turned on bitcode. If you disable it, it will be 6.5M.
Bit code enabled framework will have 32 and 64 bit arch:
>Charts: Mach-O universal binary with 2 architectures: [arm_v7: Mach-O dynamically linked shared library arm_v7] [arm64]
Charts (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Charts (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64

**Comment by StarRain-L** [comment]
Thank you for your careful answer. Because this is a good framework, the boss said that the size of the package can accept , don't tangle. But I met another problem. Numerical value between 0 and 1, y coordinates will not display, does not support the decimal?Attached above.
![123](https://cloud.githubusercontent.com/assets/8908244/21799119/dca99e78-d752-11e6-8c65-f41ef6fdf619.png)

**Comment by liuxuan30** [comment]
This is irrelevant. So don't ask here. BTW, you should check ChartsDemo to get familiar. Just use valueFormatter to format to whatever you need.

**Comment by StarRain-L** [comment]
Thank you for your reply. See a lot of issues, know you don't reply. But it doesn't matter, enthusiastic netizens have answer!!!!!!

**Comment by karosLi** [comment]
cocoapods 1.5 是支持静态库的，所以我想要把charts打成静态库，然后放在我们私有库里，应该是没有问题的把，我还没试。不知道有没有其他人问这样的问题呢？
