### ISSUE TITLE
Please help me with the Pie Charts in Charts 3.0.1.

### ISSUE THREAD

**Issue by varadpathak20** [danielgindi/Charts#2016]
I want to show legends in my Pie chart. All the web tutorials have used this line...

let data: PieChartData = PieChartData(xVals: xVals, dataSet: dataSet)

Whereas, in charts 3.0.1 there's no such thing as "xVals"
Is there anyone else who has face this challenge?

**Comment by RahuliOS88** [comment]
I am also having the same issue....did u got any solution??

**Comment by liuxuan30** [comment]
Yes, Chart 3.0 it has redesigned x axis. Please take a look at ChartsDemo for how to use pie chart.

**Comment by RahuliOS88** [comment]
Can u please share the link of that...

**Comment by coolLeee** [comment]
do anyone find out how to figure out this question?
