### ISSUE TITLE
BarChart Issue for plotting the value on x-axis serially 

### ISSUE THREAD

**Issue by RahuliOS88** [danielgindi/Charts#2017]
Currently values are visible alternatively and i want serially.
I am having name array which i want to show on x-axis currently it is showing alternatively.
Do anyone has idea how to fix this issue??
<img width="283" alt="screen shot 2016-12-28 at 11 07 57 pm" src="https://cloud.githubusercontent.com/assets/24807567/21524631/800083ee-cd52-11e6-98b4-787edbf733e9.png">

**Comment by liuxuan30** [comment]
I don't understand the issue. Are you asking it just shows the every 2nd x axis label?
If so, use setLabelCount(count, True) to your x values count.

By default, it will skip some x values, to make it not crowded displaying text.
