### ISSUE TITLE
How to make the highlight line work with UIPanGestureRecognizer

### ISSUE THREAD

**Issue by haneen91** [danielgindi/Charts#2019]
I used the UIPanGestureRecognizer with chart , I acctivate it only when click on button to display entry information so in this case i stop the chart from drag ,then the highlight line disble .. how can i make the highlight line work with pangesture

**Comment by liuxuan30** [comment]
Check the pan gesture handler and tap gesture handler. The highlight starts from there.

**Comment by harpangell7** [comment]
Hey liuxuan30, can you tell me how to remove the highlight when the "dragging" stops?

**Comment by liuxuan30** [comment]
remove highlight? Just disable highlight. I don't see it will highlight when you pan  gesture stops in chart demo line chart
