### ISSUE TITLE
Convert line chart entry to take dictionary

### ISSUE THREAD

**Issue by haneen91** [danielgindi/Charts#2027]
Why library entry not used dictionary ? I try to convert the line chart entry to used dictionary but its not drawing the entry ?! But with candle chart entry its work with dictionary without any error

**Comment by liuxuan30** [comment]
Well... Because they are different charts. It should be your issue when 'it does not work for line chart'

**Comment by haneen91** [comment]
Sorry but I convert mpandroidchart entry to deal with dictionay ..for example candlestickchart and linechart now take the same entry but i change the render to know which dictionary value must display ..but for ios I cann't convert the class
