### ISSUE TITLE
Y axis dynamic sampling ?

### ISSUE THREAD

**Issue by Bhupendra-tbox** [danielgindi/Charts#2029]
Please any body help me for displaying y axis sampling (Min & Max) on visible data sets

**Comment by liuxuan30** [comment]
format your words. People can barely understand.

**Comment by Bhupendra-tbox** [comment]
Can we change min or max of y axis on scrolling? I have tried calMinMax() method but result is not accurate.

**Comment by liuxuan30** [comment]
there is axisMinimum/Maximum to change. Once you change, you can call `notifyDataSsetChanged` to trigger it re-calculate again.
