### ISSUE TITLE
module file's minimum deployment target is ios9.3

### ISSUE THREAD

**Issue by IZEROLEE** [danielgindi/Charts#2031]
This project supports iOS8.0 above, why I am in the framework of his import suggested: Module file's minimum deployment target is ios9.3 v9.3: ... I switched to 9.3 above can be compiled, and 9.3 following the following problems: Module File's minimum deployment target is ios9.3 v9.3: /Users/huzhongli/Library/Developer/Xcode/DerivedData/APPTUTTi-bwyaleibnlzpmkdzfvxfsliflnqb/Build/Products/Debug-iphonesimulator/Charts.framework/Modules/Charts.swiftmodule/x86_64.swiftmodule , Wait for a reply!

**Comment by liuxuan30** [comment]
check your project setting and set the minimum deployment target to 8.0. 
Take ChartsDemo as reference.
