### ISSUE TITLE
Error when trying to run ChartsDemo on iOS Simulator (image not found)

### ISSUE THREAD

**Issue by tedhogan** [danielgindi/Charts#2035]
Hi,

When I try to run the ChartsDemo on the iOS Simulator using Xcode 8.1, I get the following crash and error: 

dyld: Library not loaded: @rpath/RealmSwift.framework/RealmSwift
  Referenced from: /Users/username/Library/Developer/Xcode/DerivedData/ChartsDemo-fmyrryaldqtgmlfcymgmkxrlbxbx/Build/Products/Debug-iphonesimulator/ChartsRealm.framework/ChartsRealm
  Reason: image not found

I've run carthage checkout in the main directory to pull in Realm.  All of the targets build fine. Does anyone know what I could be forgetting? Thanks.

**Comment by xibo55** [comment]
Same problem here +1

**Comment by xibo55** [comment]
I have been able to work around this problem on simulator, by copying the missing RealmSwift framework files from ~/Carthage/Build/iOS/ directory. You will see 2 files in there. I am not sure so I just copied both of these files into the compile-time directory and put them along with other frameworks, in your case that destination directory would be: 

/Users/username/Library/Developer/Xcode/DerivedData/ChartsDemo-fmyrryaldqtgmlfcymgmkxrlbxbx/Build/Products/Debug-iphonesimulator/

Compile and it runs good for me on simulator. Hope this helps.

**Comment by liuxuan30** [comment]
Weird.. but you can try as @xibo55 said, or maybe a rebuild

**Comment by jpegjames** [comment]
@xibo55 and @liuxuan30: I'm still getting the same issue. I've tried to manually move the RealmSwift framework as well clearing and rebuilding and I can't get it to compile.

**Comment by yimingtang** [comment]
I think the project didn't use Carthage correctly.

Here are docs of Carthage and Realm. They show the right way to integrate Realm.

* https://realm.io/docs/swift/latest/#getting-started
* https://github.com/Carthage/Carthage#getting-started

To me, the quick fix is:

* Add `Realm.framework` and `RealmSwift.framework` to ChartsRealm.
* Add a `Run Script` phase to ChartsRealm to copy the two frameworks.

**Comment by liuxuan30** [comment]
I never met this issue before, just let carthage handles every thing and it built fine... adding @danielgindi or @petester42 to help

**Comment by petester42** [comment]
if I'm understanding correctly you want ChartsRealm to copy its dependencies? From my experience with Carthage this isn't really a thing. Usually you have to add the framework you want plus all of its dependencies to you app. 

I'd have to look at a bunch of other frameworks to see what is the norm but if copying the dependencies is something that makes people's lives easier then I'm all for it.
