### ISSUE TITLE
BarChart XAxis between Positive & Negative Values

### ISSUE THREAD

**Issue by simnik-git** [danielgindi/Charts#2036]
I am trying to get the xAxis of a Barchart into the center between positive and negative values.
Here is what I am trying to achieve:

![screen shot 2017-01-05 at 15 58 50](https://cloud.githubusercontent.com/assets/10733381/21684925/e5f60eb8-d35f-11e6-8193-fe9ab5685ca6.png)

I managed to get the Labels of the xAxis into the center and this is the closest I got so far:

<img width="366" alt="screen shot 2017-01-05 at 16 01 25" src="https://cloud.githubusercontent.com/assets/10733381/21685019/3f3c0f7c-d360-11e6-90ed-439775f95daf.png">

**Comment by liuxuan30** [comment]
I remember x axis labels can't be drawn in the middle.
If you want to do so, you have to override x axis renderer to draw around the zero line. Drawing zero line is a feature, so you can refer that to know what's the y point to draw it.
