### ISSUE TITLE
How to show limited visible xValues labels?

### ISSUE THREAD

**Issue by OptTrader** [danielgindi/Charts#2037]
Currently, I have a candlestick chart and a segmented control. Given that I fetched a lot of data depends on the time period, the x-Values count are massive as you see below.

![simulator screen shot jan 3 2017 1 08 32 pm](https://cloud.githubusercontent.com/assets/6761377/21705186/56cbff6e-d3f9-11e6-83b9-b53479ed08bb.png)

Is there a way that I can make only 4-5 dates visible on the chart like how you normally see a stock chart?

**Comment by liuxuan30** [comment]
have you changed lableCount or other stuff? By default, it will just show 6 label.
