### ISSUE TITLE
Label's point of view

### ISSUE THREAD

**Issue by newbiebie** [danielgindi/Charts#2038]
In the histogram, the tilt angle how I set the cylinder on top of the text?

**Comment by liuxuan30** [comment]
don't understand. Reopen with more details.

**Comment by newbiebie** [comment]
<img width="304" alt="2017-01-17 11 41 01" src="https://cloud.githubusercontent.com/assets/24471362/22006939/112ff4ce-dcaa-11e6-8557-ec458ee8f59f.png">
Angle of inclination of the above text

**Comment by liuxuan30** [comment]
have no idea what's "Angle of inclination of the above text"
