### ISSUE TITLE
xAxis.valueFormatter = self  create retain cycle

### ISSUE THREAD

**Issue by hotuanlinh89** [danielgindi/Charts#2039]
When you create CombinedChart. Config ChartXAxis.
ChartXAxis *xAxis = _chartView.xAxis;
    xAxis.labelPosition = XAxisLabelPositionBottom;
    xAxis.axisMinimum = 0.0;
    xAxis.granularity = 1.0;
    xAxis.valueFormatter = self;

It's create memory leak. Please help.

**Comment by liuxuan30** [comment]
refer this: https://github.com/danielgindi/Charts/issues/1854
You can either change to weak or not use self
