### ISSUE TITLE
labels on xAxis not showing up and incorrect values on yAxis

### ISSUE THREAD

**Issue by kasperSe7en** [danielgindi/Charts#2040]
HI, I have an issue with my labels and values on my yAxis in a BarChart

on my labels on the xAxis, I am trying to have this array 
`let labels :[String] = ["01/01/17","02/01/17","03/01/17",
                                "04/01/17","05/01/17","06/01/17","07/01/17"]`

Also, on the yAxis values, i don't want to have decimal points. e.g. `1.4` as all of the values are whole numbers.

any help would be much appreciated. 

Kane 
![codescreenshot](https://cloud.githubusercontent.com/assets/10401136/21720833/4067ac2c-d41d-11e6-9504-e49b2f540ef1.png)
![graphscreenshot](https://cloud.githubusercontent.com/assets/10401136/21720834/408a3b48-d41d-11e6-9fd6-fcf9cada2999.png)

see the attached images for my code and screenshot of the graph so far.

**Comment by mrugeshtank** [comment]
@kasperSe7en , have you solved this issue??
cause I'm also facing this
