### ISSUE TITLE
Will not compile in existing Objective-C Project.

### ISSUE THREAD

**Issue by jvanbrunt** [danielgindi/Charts#2041]
I have an Objective-C project that I am wanting to use Charts in but when I add it through Cocoapods my project will no longer build. I get 999+ swift compiler errors.

XCode 8.2.1
Cocoapods 1.1

<img width="259" alt="screen shot 2017-01-06 at 10 04 51 am" src="https://cloud.githubusercontent.com/assets/3064793/21721739/adaa8a8c-d3f7-11e6-9c7f-f1d90bcca43e.png">

Any help would be much appreciated.

Thanks

**Comment by liuxuan30** [comment]
Use Swift 3.0 and latest Charts code please.

**Comment by mikemike396** [comment]
So this library doesn't work with Obj C anymore? We are getting similar errors.

**Comment by liuxuan30** [comment]
It works with ObjC for sure. It's your project setting and env issues. We always make sure it works with latest Xcode.

**Comment by lazar108** [comment]
I ran into the same problem, check thexande answer on how to use the library 

https://github.com/danielgindi/Charts/issues/1548
