### ISSUE TITLE
LeftAxis Labels will disappear

### ISSUE THREAD

**Issue by cartmanguo** [danielgindi/Charts#2044]
I need to update the linechart dynamicly,when a new value arrives,I create an entry and add it the the dataset.This problem happends no matter autoScaleMinMaxEnabled property is on or off
Here's a screenshot:
![thumb_img_0001](https://cloud.githubusercontent.com/assets/4699162/21757786/d8326206-d66e-11e6-849f-d41a9ced888d.jpg)

**Comment by liuxuan30** [comment]
call `notifyDataSetChanged()` after you add new ones.

**Comment by cartmanguo** [comment]
actually,I called notifyDataSetChanged() everytime I add an enrty,so this is not the problem
I'll try to make a demo to reproduce this problem and show it to you

**Comment by cartmanguo** [comment]
here's a demo:https://github.com/cartmanguo/reproduceissuecharts
drag the charts project to it and run,tap the add bar button,you will see this problem I described.
Thanks. @liuxuan30

**Comment by liuxuan30** [comment]
You add entry by dataSet interfaces, without letting chartData know the max value would change.
you should add entries on data's level via API `lineChart.data?.addEntry(entry, dataSetIndex: 0)`

**Comment by cartmanguo** [comment]
still doesn't work...

**Comment by cartmanguo** [comment]
and if I set autoScaleMinMaxEnabled to true, the same thing happens in issue #2053

**Comment by liuxuan30** [comment]
@cartmanguo first, 'still does not work' can't help. And don't mix up different things together. I tried your project and `lineChart.data?.addEntry(entry, dataSetIndex: 0)` works on my side.

**Comment by cartmanguo** [comment]
I'm sorry If I mixed up two unrelated issues,I just think they both have something to do with caculating,apolygize again...
I changed that line to `lineChart.data?.addEntry(entry, dataSetIndex: 0)`,but the left axis labels still not displaying after I add the second entry,I use the latest commit of Charts
![2017-01-16 1 09 30](https://cloud.githubusercontent.com/assets/4699162/21971785/df4465be-dbee-11e6-8e53-205971110774.png)
Today I realize that maybe it's because I didn't set the `granularity` property,so I set it to 0.1,it seems to be ok now.

**Comment by liuxuan30** [comment]
Cool, i just used what you uploaded and it works after adding that line of code
