### ISSUE TITLE
yVals have decimal point

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/Charts#2045]
yVals incoming value with no decimal point, but when the show with decimal point, and only in the value of 95 a decimal point, how do I solve
![2p](https://cloud.githubusercontent.com/assets/11886729/21760503/af1165d4-d687-11e6-9ed4-0576c40bf268.jpg)

**Comment by liuxuan30** [comment]
change valueFormatter to a proper NSNumberFormatter, and change `maximumFractionDigits`, `minimumFractionDigits` to meet your goals.

**Comment by shanyulaile** [comment]
Dear liuxuan30

NSNumberFormatter *leftAxisFormatter = [[NSNumberFormatter alloc] init];
    leftAxisFormatter.minimumFractionDigits = 0;
    leftAxisFormatter.maximumFractionDigits = 1;
    self.linechartiew.leftAxis.valueFormatter = [[ChartDefaultAxisValueFormatter alloc] initWithFormatter:leftAxisFormatter];

I shall be carried out in accordance with the above Settings, did not achieve the desired results， is a set of values is there a problem?

**Comment by liuxuan30** [comment]
take a look at NSNumberFormatter's properties to find the one you need to change. I just meant that you can customize the formatter as you like. If you don't want decimals, just maximumFractionDigits = 0.
