### ISSUE TITLE
"BalloonMarker“ cannot be find in my project

### ISSUE THREAD

**Issue by silence3838438** [danielgindi/Charts#2051]
"BalloonMarker“ cannot be find in my project,which is written by Objective-C,furthermore,the error seems indicate that"Use of undeclared identifier 'BalloonMarker' ,and my question is that how I use the 'BalloonMarker 'and import the 'BalloonMarker' to my project on the basis on Objective-C ,I am looking forward to  your reply as soon as possible,thank you!

**Comment by liuxuan30** [comment]
It's in ChartsDemo, you can copy paste that.

**Comment by gmelcer** [comment]
When I copy it from Charts demo it gives me the following error:

/Users/george/Downloads/Charts-master/ChartsDemo/Objective-C/Components/BalloonMarker.swift:105:46: Cannot convert value of type '[NSAttributedStringKey : Any]' (aka 'Dictionary<NSString, Any>') to expected argument type '[String : Any]?'

Any suggestions?

**Comment by liuxuan30** [comment]
well, update whatever it complains in swift 4
