### ISSUE TITLE
Handling critical Y values with autoScaleMinMaxEnabled

### ISSUE THREAD

**Issue by Fahrenheit-sp** [danielgindi/Charts#2053]
Hi. I have a LineChartView with **autoScaleMinMaxEnabled** option enabled. I retrieve some data from internet and dynamically add entries to my chartView, based on the data retrieved. 
Here is some sample code:

```
let receivedEntry = ChartDataEntry(x: json["time"].doubleValue, y:json["value"].doubleValue)
set.addEntry(receivedEntry)
chartView.notifyDataSetChanged()
```

everything works just well, but if _receivedEntry.y_ is higher than my current yAxisMaximum, or lower than minimum, the new value gets drawn beyond the bounds (it means that some part of chart goes beyond the top of chartView, or beyond the bottom, depending on receivedEntry.y value), and gets autoscaled only if I translate or scale it manually.

I tried to set axisMaximum/axisMinimum manually, and then reset it by calling _resetAxisMinMax_, when I start scaling/translating chartView
```
func handleCriticalValues() {
        if receivedEntry.y >= chartView.rightAxis.axisMaximum - (chartView.rightAxis.axisRange * Double(chartView.rightAxis.spaceTop)) {
            chartView.rightAxis.axisMaximum = receivedEntry.y + (chartView.rightAxis.axisRange * Double(chartView.rightAxis.spaceTop))
            chartView.notifyDataSetChanged()
        }
        
        if receivedEntry.y <= chartView.rightAxis.axisMinimum + (chartView.rightAxis.axisRange * Double(chartView.rightAxis.spaceTop)) {
            chartView.rightAxis.axisMinimum = receivedEntry.y - (chartView.rightAxis.axisRange * Double(chartView.rightAxis.spaceTop))
            chartView.notifyDataSetChanged()
        }
    }
```
(this gets called right before _chartView.notifyDataSetChanged()_ from previous code sample). This solution works almost perfect, but when I translate chart to the current position, and critical value arrives, chart goes beyond the bounds anyway.

If any additional information or logs needed, please let me know. Thanks for any help and thanks again for such awesome library.

**Comment by liuxuan30** [comment]
Your code sample seems fine, the chart will recalculate and trigger a new draw(), but I am not sure what you mean 
>"but when I translate chart to the current position, and critical value arrives, chart goes beyond the bounds anyway."

You have to debug a little to see when you translate and add new entries, what's the order of the processing.

**Comment by Fahrenheit-sp** [comment]
@liuxuan30, thanks for your reply. I'll try to find anything weird, and give you an answer as soon as possible.

**Comment by cartmanguo** [comment]
This also happens in my app ,do you have a solution?@Fahrenheit-sp

**Comment by Fahrenheit-sp** [comment]
@cartmanguo actually no, I still have this issue

**Comment by JokerMZD** [comment]
+1 - have this issue in my app

**Comment by liuxuan30** [comment]
@Fahrenheit-sp Can you check if https://github.com/danielgindi/Charts/pull/2177 fix your issue?

**Comment by Fahrenheit-sp** [comment]
@liuxuan30, have not much time right now. Will check in a couple of days and reply. Thank you for your participation.

**Comment by JokerMZD** [comment]
@liuxuan30 , I've checked the latest Master code and issue still exist for iOS version.
Here is different behavior of iOS and Android versions of Charts. Dataset is the same.
iOS - http://take.ms/CCxxU
Android - http://take.ms/3aCHh

**Comment by liuxuan30** [comment]
@JokerMZD so issue is different

**Comment by aelam** [comment]
Is it needed to call notifyDataSetChanged 
After set.addEntry(receivedEntry)?

**Comment by Fahrenheit-sp** [comment]
@liuxuan30 sorry for the late reply. Actually, no. It doesn't fix the problem. And I've found one more issue with autoscale. (It appears in both cases, when I handle axisMinimum/maximum manually, and when axisMinimum/maximum are calculated automatically) sometimes, for a little period of time (second or so) chart gets drawn as if no autoscale enabled, and then gets redrawn as it should be (with autoscale enabled).

**Comment by liuxuan30** [comment]
@aelam it depends when you add it. If you chart is displayed, and you manually do that, you should

**Comment by aelam** [comment]
@lixuan  maybe try my PR to see if can solve this ?  I believe some import entries which are the maxY or minY are ignored

**Comment by aelam** [comment]
Debug the method calculateMinMaxY(fromX, toX) 
If the entry with index indexTo is visible and this entry is overlapped, then that is the problem

**Comment by aelam** [comment]
#2229

**Comment by JokerMZD** [comment]
@aelam  I've checked your pull request - it fixes my issue. Thanks.

**Comment by Fahrenheit-sp** [comment]
@aelam yes, that fixes it. Thank you a lot!

**Comment by liuxuan30** [comment]
@danielgindi I am not sure if #2229 will potentially impact other components though it fix some..

**Comment by aelam** [comment]
@xuan check out the android code. I believe it's an iOS version bug

**Comment by liuxuan30** [comment]
yeah, what I am concerned is this could be a big change if any other code relies on it

**Comment by aelam** [comment]
Just need to confirm if the indexTo needs to be included. Then it's clear

**Comment by aelam** [comment]
I think this got fixed, So close it ?
