### ISSUE TITLE
fixed increment

### ISSUE THREAD

**Issue by dimohamdy** [danielgindi/Charts#2059]
how can i manage to increment x axis to fixed increments (steps) without making values to be concatenated to the near biggest value..for example i would like to increment values with a steady form (1.0,1.1,1.2,1.3 ... 2.0,2.1,2.2 and so on) making the chart to scroll and not to condense UI values

**Comment by liuxuan30** [comment]
you can take a look at `computeAxisValues()` to know how it calculates x axis labels. You can override it to give a fixed step.
