### ISSUE TITLE
Radar chart title

### ISSUE THREAD

**Issue by alifarhangmehr** [danielgindi/Charts#2061]
Hi guys,
Sorry if my question is very stupid, but I struggled with almost a week and came up with nothing.
So I wanted to know how can I set the title of radar chart and also wants to know how can I change location of description and the chart it self, cuz it act really strange and I can not predict how the chart is going to show, is there any way to fix it into a view ? (it only happened with radar chart, the other fit to their view just fine)
here is my code :

  ```
 //Label
    let dataPoints = ["Strenght", "Cardio", "Stretch", "Versality", "Recovery"]
    //Points
    let values = [0.65, 1.0, 0.7, 0.65, 0.85]

var dataEntries: [RadarChartDataEntry] = []
        for i in 0..<values.count {
            let dataEntry = RadarChartDataEntry(value: values[I])
            dataEntries.append(dataEntry)
        }
        

        let chartDataSet = RadarChartDataSet(values: dataEntries, label: "Performance")
        
        radarChartView.yAxis.axisMinimum = 0.0
        radarChartView.yAxis.axisMaximum = 0.8
        
        radarChartView.xAxis.axisMinimum = 0.0
        radarChartView.xAxis.axisMaximum = 1.0

        chartDataSet.drawFilledEnabled = true

        let chartData = RadarChartData(dataSet: chartDataSet)
        chartData.labels = dataPoints
        radarChartView.data = chartData
```

**Comment by liuxuan30** [comment]
please give a screenshot so we know what you want.. And make sure you played with ChartsDemo radar chart

**Comment by alifarhangmehr** [comment]
<img width="183" alt="screen shot 2017-01-12 at 5 21 46 pm" src="https://cloud.githubusercontent.com/assets/17318570/21910879/fd78ef7e-d8eb-11e6-8bc6-54d6c616d04f.png">
 I just want to change the label on the edge of the chart (.0   1.0     2.0    3.0    4.0 ) to a string

**Comment by MatrixTeo** [comment]
Hi,

Take a look at the demo, add `- (NSString *)stringForValue:(double)value axis:(ChartAxisBase *)axis` delegate method and use `value` as the array index.

I don't know if it's an expected behavior, but currently it works.

**Comment by alifarhangmehr** [comment]
Thank you for reply, but I'm using swift and the whole process with obj-c and swift are different, so I can't even guess where should I set the values

I'm using a loop for injecting values to my chart and dataPoints are the array of labels that I need to show in the chart, but I don't know why its not working.

for i in 0..<values.count {
            let dataEntry = RadarChartDataEntry(value: values[i], data: dataPoints[i] as AnyObject?)
            dataEntries.append(dataEntry)
        }

**Comment by alifarhangmehr** [comment]
If only anyone can give me a swift code which can run a simple radar chart with labels around, my problem  is going to be solved.

**Comment by liuxuan30** [comment]
Just use `valueFormatter` to format to whatever you want.

**Comment by dalianmengzi** [comment]
Have you solved this problem? I met him too
