### ISSUE TITLE
Positioning the XAxis inconsistent with Y-axis and the Wiki in Swift 3

### ISSUE THREAD

**Issue by MartinMajewski** [danielgindi/Charts#2065]
Hi,

so I started using Charts and I like it overall, but there are some strange things regarding the API (not to speak that it is not 98% compatible with the Android API).

The first thing I wanted to do is to set the whole X axis to the bottom of my line chart.
Documentation says to use the getXAxis method, which does not exist.

Instead you have to do

`self.lineChartView.xAxis.labelPosition = .bottom`

which is kind of confusing and irritating, as it suggests to be a property for positioning the labels aka. the text representing the axis' values relative to the axis line (above the line, beneath the line, etc), not the axis itself. But it works and the X axis is now at the bottom.

Another inconsistency is the positioning of the chart descriptive text. Why to only use CGPoints here, instead or even better in addition to an easy enumerator like with the axis?

Best wishes,
Martin

**Comment by liuxuan30** [comment]
about the label position, I guess it just wants to indicate it defines where the x axis label can be.. I can't say it's bad.. and there is comment;

you are welcome to file PRs to make it better:)
