### ISSUE TITLE
Demo code can't run

### ISSUE THREAD

**Issue by zip520123** [danielgindi/Charts#2066]
I clone demo code and try to run.
follow readme."Having trouble running the demo?" 
Run 
```
brew install carthage
carthage checkout
```
got 
```
*** Cloning ios-snapshot-test-case
*** Cloning realm-cocoa
*** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
*** Downloading realm-cocoa.framework binary at "v2.1.1"
```
And I try to run it on my iPhone then crash.
```
dyld: Library not loaded: @rpath/RealmSwift.framework/RealmSwift
  Referenced from: /private/var/containers/Bundle/Application/0261FA92-7A16-4656-9F80-CE4DDE658031/ChartsDemo.app/Frameworks/ChartsRealm.framework/ChartsRealm
  Reason: image not found
Message from debugger: Terminated due to signal 6
```

**Comment by mossby** [comment]
Hey @zip520123 try this: 

First copy **Cartfile** from /Charts to /Charts/ChartsDemo folder

Then instead of 'carthage checkout' run:

'carthage update'

Now open the ChartsDemo project, select the Target and under the General tab go to Embedded Binaries delete the Realm.framework entry

Then drag Realm.framework and RealmSwift.framework from /Charts/ChartsDemo/Carthage/Builds/iOS into Embedded Binaries

Should work now!

**Comment by petester42** [comment]
I thought I added a script that automatically downloads the dependencies for the demo. Maybe I only added it to the framework. I'll look into it.

**Comment by mossby** [comment]
@petester42 Seems like RealmSwift.framework isn't embedded in the demo project. I realized too late but a simpler solution to my quick fix above might be just to drag RealmSwift.framework from /Charts-master/Carthage/Builds/iOS into Embedded Binaries

**Comment by zip520123** [comment]
It work.
Thank you @mossby :)

**Comment by 2016321** [comment]
@mossby bingo! good job :]

**Comment by liuxuan30** [comment]
oops, reopen as @petester42 is looking into it

**Comment by liuxuan30** [comment]
@petester42 looks like recent changes breaks Realm stuff:
```
dyld: Library not loaded: @rpath/RealmSwift.framework/RealmSwift
  Referenced from: /Users/xuanliu/Library/Developer/Xcode/DerivedData/ChartsDemo-bzvxrjdwvwmnisdtojvctdevowie/Build/Products/Debug-iphonesimulator/ChartsRealm.framework/ChartsRealm
  Reason: image not found
```
I pulled latest code and can't run as well..

**Comment by liuxuan30** [comment]
I saw @danielgindi added RealmSwift in RealmBaseDataSet.swift, but currently ChartsDemo does not have that framework under frameworks. 
I got one question: Does Realm and RealmSwift are both needed? @danielgindi 

Simply drag RealmSwift.framework into that folder and re-embed it and things went well then:
![image](https://cloud.githubusercontent.com/assets/4375169/22005784/f8c1b85e-dca0-11e6-9d24-574c10c39acb.png)

**Comment by petester42** [comment]
Realm swift is referenced in ChartsRealm.framework now

**Comment by liuxuan30** [comment]
@petester42 I had a PR https://github.com/danielgindi/Charts/pull/2083 for adding RealmSwift into project settings.
Since carthage already downloaded RealmSwift, will this PR be enough to run?

**Comment by liuxuan30** [comment]
😂 just saw yours, closing my poor one

**Comment by petester42** [comment]
I just submitted mine. It also fixes the test target not running.
