### ISSUE TITLE
Area chart with missing points

### ISSUE THREAD

**Issue by HPRaval** [danielgindi/Charts#2067]
I want to draw area chart with missing points so i have skipped y value at particular x index. But steel my area chart is continuous,

Here is my data
  ```
var yVal2 = [ChartDataEntry]()
        yVal2.append(ChartDataEntry(value: 1, xIndex: 0))
        yVal2.append(ChartDataEntry(value: 0, xIndex: 1))
        yVal2.append(ChartDataEntry(value: 3, xIndex: 2))
        //yVal2.append(ChartDataEntry(value: nil, xIndex: 3))
        yVal2.append(ChartDataEntry(value: 3, xIndex: 4))
        yVal2.append(ChartDataEntry(value: 1, xIndex: 5))
        yVal2.append(ChartDataEntry(value: 2, xIndex: 6))
        yVal2.append(ChartDataEntry(value: 1, xIndex: 7))
```

My Chart looks like this
![screen shot 2017-01-12 at 5 30 13 pm](https://cloud.githubusercontent.com/assets/24671241/21889022/e0bfb524-d8ec-11e6-8af5-8ee6e20cfe56.png)

But I want something like this

![screen shot 2017-01-12 at 5 31 20 pm](https://cloud.githubusercontent.com/assets/24671241/21889054/07afccb4-d8ed-11e6-9cf3-2cdc2ee2d111.png)

**Comment by liuxuan30** [comment]
ah hah, I used to develop such kinds of chart. Currently, this library does not support line breaking natively. But one workaround is that you use one data set for each line segment. e.g. in your screenshot, it should be 3 data sets ( 1 blue and 2 for red lines)
