### ISSUE TITLE
can't set different padding of each side 

### ISSUE THREAD

**Issue by aelam** [danielgindi/Charts#2068]
I can't only find the minOffset.
If it's a minPadding: UIEdgeInsets, will it be cooler?

**Comment by mossby** [comment]
Hey @aelam: the `minOffset` is a global padding property but there are also individual padding properties: `extraLeftOffset` `extraRightOffset` `extraTopOffSet` and `extraBottomOffset`

**Comment by aelam** [comment]
Thanks mossby , my mistake
