### ISSUE TITLE
Can horizontalBarChartView invert the Axis ?

### ISSUE THREAD

**Issue by Liaojiahao** [danielgindi/Charts#2070]
<img width="365" alt="1" src="https://cloud.githubusercontent.com/assets/7369640/21918515/034acdd6-d98d-11e6-82f1-5377ea984a6b.png">

<img width="365" alt="2" src="https://cloud.githubusercontent.com/assets/7369640/21918549/514d88d4-d98d-11e6-956c-44830620a306.png">

As images show,is there anyway to do?

**Comment by Liaojiahao** [comment]
@liuxuan30

**Comment by mossby** [comment]
The YAxis class has an `inverted` boolean property. Did you try setting the appropriate axis to `true`? @Liaojiahao

**Comment by Liaojiahao** [comment]
@mossby 
I had tried it, but that was not my expectation, i want to invert the xAxis instead...

**Comment by mossby** [comment]
Hmm, maybe you could write a helper to simply reverse your xAxis data model before you convert it into ChartDataEntry -> ChartDataSet, etc? @Liaojiahao

**Comment by liuxuan30** [comment]
I used to have this problem, and I reversed the order when I add them..

**Comment by Liaojiahao** [comment]
@liuxuan30   ,  @mossby 
Ok ,thank you ,
I finally reversed the data and also the ValueFormatter ...
