### ISSUE TITLE
Not enable to draw custom shape which is based on the XValue or YValue ? 

### ISSUE THREAD

**Issue by aelam** [danielgindi/Charts#2071]
Not enable to draw custom shape which is based on the XValue or YValue ?
Such as I want to draw a text and a shape based on the origin value
I have to search the origin values by the `CGPoint`
if there is a way to do this ?

```
public class BSPointShapeRenderer: NSObject, IShapeRenderer {
    
    open func renderShape(
        context: CGContext,
        dataSet: IScatterChartDataSet,
        viewPortHandler: ViewPortHandler,
        point: CGPoint,
        color: NSUIColor)
    {
```

**Comment by aelam** [comment]
When I read `ScatterChartRenderer.swift`  Line71:95
The CGPoint is the final point on `viewPortHandler`. 
After do
```
                guard let e = dataSet.entryForIndex(j) else { continue }
                
                point.x = CGFloat(e.x)
                point.y = CGFloat(e.y * phaseY)
                point = point.applying(valueToPixelMatrix)
```
And then I lose the way to recover the index!
maybe the `renderShape` interface should add a parameter of `Entry`?  to let implementers use it


```
        if let renderer = dataSet.shapeRenderer
        {
            context.saveGState()
            
            for j in 0 ..< Int(min(ceil(Double(entryCount) * animator.phaseX), Double(entryCount)))
            {
                guard let e = dataSet.entryForIndex(j) else { continue }
                
                point.x = CGFloat(e.x)
                point.y = CGFloat(e.y * phaseY)
                point = point.applying(valueToPixelMatrix)
                
                if !viewPortHandler.isInBoundsRight(point.x)
                {
                    break
                }
                
                if !viewPortHandler.isInBoundsLeft(point.x) ||
                    !viewPortHandler.isInBoundsY(point.y)
                {
                    continue
                }
                
                renderer.renderShape(context: context, dataSet: dataSet, viewPortHandler: viewPortHandler, point: point, color: dataSet.color(atIndex: j))
            }

```

**Comment by liuxuan30** [comment]
may I know what's the real issue? You got the point and color and data set already, it should be ready to draw custom shape now. If you need more params like radius, then you can override this methods and feed more. 
You can also sub class data set to add more properties.

**Comment by aelam** [comment]
I know the dataSet but I don't know the entry, because I don't know the index. I want to draw the YValue on the chart

**Comment by liuxuan30** [comment]
what you need from the entry? usually, x, y is used to get the screen value x,y. Now p is the (x,y), seems like you don't need entry.

**Comment by aelam** [comment]
it's not enough. I want to display the shape with YValue inside 
Look at the picture  

I'm thinking add some scatterData and with custom shape and the value is in the shape.
They are supposed to display when the chart is drawn, rather than on the highlighting timing

![7f8bcd8a-8ad2-4001-b48c-399a10560fd5](https://cloud.githubusercontent.com/assets/232337/21969167/e91741e6-dbd6-11e6-80de-aa6911614965.png)

**Comment by liuxuan30** [comment]
alright, the easy way to me is you override those methods, sub class the data classes, and add your own values so you are able to get them.

**Comment by nikwest** [comment]
I think this is a common problem. At least I have it too. I have a custom renderer which needs access to the actual entry of the dataSet, because in my case the shape depends upon the actual y value.
It is not really clear to me, why the complete dataset is passed to the renderer, but not the current index or entry, which should be drawn. I'll create my own sub classes for it, but it would be much easier to just pass an additional argument in IShapeRendere's renderShape(...) method.
