### ISSUE TITLE
BarChartView is unavailable, cannot find swift declaration

### ISSUE THREAD

**Issue by kjoneandrei** [danielgindi/Charts#2072]
Hi, I am integrating Charts 2.3 in a Swift 2.3 project and I get this error after following the set-up steps BarChartView is unavailable, cannot find swift declaration

do you have any ideas on how to solve this?

I did not used cocoaPods or anything else, just copied the Charts.xcodeproj to my project and added as an Embedded Framework

**Comment by kjoneandrei** [comment]
also installing it with cocoaPods leads to this error 
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuxuan30** [comment]
First, currently the master branch is swift 3.0 code. Pods seems to be swift 3.0 as well.
https://github.com/danielgindi/Charts/releases/tag/v2.3.0 is the last release for swift 2.3, no bug fix any more.
So you are encouraged move to Chart 3.0
