### ISSUE TITLE
How can I have a limit zone (in android library mpandroidchart) like feature in this iOS library

### ISSUE THREAD

**Issue by dhruv-jindal** [danielgindi/Charts#2073]

**Comment by mossby** [comment]
Do you mean limit lines? There are properties on the 3 axes (`leftAxis`, `rightAxis`, and `xAxis`) so you can do something like this:

```
let lowLimitLine = ChartLimitLine(limit: 100, label: "Low Threshold")
lowLimitLine.lineWidth = 1.0
lowLimitLine.lineDashLengths = [1, 2]
lowLimitLine.lineColor = UIColor.lightGray
lowLimitLine.valueTextColor = UIColor.lightGray
    
leftAxis.addLimitLine(lowLimitLine)
```
That will produce something like this:

<img width="463" alt="low thresh limit line" src="https://cloud.githubusercontent.com/assets/3187503/21956449/9401a9a8-da46-11e6-8f51-6ea7854b3dcc.png">

You can add as many limit lines as you like as far as I know! See also the first example in ChartsDemo.

@dhruv-jindal

**Comment by dhruv-jindal** [comment]
I already knew about limit lines and I am using that also in my app. What I want is something like this in the below pic : 

![screenshot_2017-01-16-10-13-42](https://cloud.githubusercontent.com/assets/2162047/21971249/c448b068-dbd4-11e6-897a-ddc4ed5b27e5.png)

I want to add 4 colours to the background of the chart. The colour zones depend on the y values.

**Comment by liuxuan30** [comment]
grid color stripe is not supported yet. However, you can add your own methods in `drawExtra()` or override some methods, to draw color grid. You can refer how the limit line is drawn, and you would know the coordinates to draw your rect then.

**Comment by dhruv-jindal** [comment]
Thank you for the reply. I will try that solutions of yours.

**Comment by bhargavsejpalindianic** [comment]
@liuxuan30 @danielgindi can you please add the example for the same
