### ISSUE TITLE
How to Resize Labels in Pie Chart Legend

### ISSUE THREAD

**Issue by brendenk1** [danielgindi/Charts#2075]
## Issue
The legend labels become clipped

I have tried to adjust the following properties to no avail:
`legend.wordWrapEnabled = true`
`legend.maxSizePercent = 0.8`

Any suggestions?

![screen shot 2017-01-13 at 1 41 13 pm](https://cloud.githubusercontent.com/assets/7902013/21941283/ff86e7a8-d995-11e6-921f-04355ed5d526.png)

**Comment by liuxuan30** [comment]
according to the doc,
>    /// flag that indicates if word wrapping is enabled
    /// this is currently supported only for `orientation == Horizontal`.
    /// you may want to set maxSizePercent when word wrapping, to set the point where the text wraps.
    /// 

And it seems like you are using vertical.
