### ISSUE TITLE
Value labels for multiple ChartDataSets all aligned at the beginning (left) of each bar in HorizontalBarChart

### ISSUE THREAD

**Issue by cdf1982** [danielgindi/Charts#2077]
Hi and thanks for this amazing project!

I have an HorizontalBarChart with 3 BarChartDataSets and I'm *close* to the result I want: *every bar showing a formatted value label for each data set*.
In the following screenshot, for instance, the second bar (14/01/17) shows 11192 as label for the first BarChartDataSet value, 8.25 for the second (which is actually 8250, but formatted according to my needs) and 1 for the third BarChartDataSet (which will often have very small values comparing to the other datasets, so usually its actual bar won't be visible, and only the label will be shown... which is fine for me).

![img_2585](https://cloud.githubusercontent.com/assets/11062186/21961960/c736504a-db17-11e6-9c50-e4d2bcb2e33a.jpg)

My problem, or better **my goal, is to have all three value labels aligned at the beginning of the bar, on the left, inside the bar**. Like this (sorry for the quick and dirty photoshopping):

![my_goal](https://cloud.githubusercontent.com/assets/11062186/21962003/3e6d6472-db19-11e6-828c-4c173a1e7630.jpg)

Currently I have barChartView.drawValueAboveBarEnabled = true, but setting it false only brings the label inside the bars, but on the right side, which actually causes an even worse positioning for the label of the third BarChartDataSet, the one with small values, since that label overlaps with the dates.

Is there a way to have the value labels drawn at the beginning (left) of the bars that I am missing?

Thanks in advance for your help!

Cesare

**Comment by liuxuan30** [comment]
you can override `drawValues()` to draw at your desired position.

**Comment by cdf1982** [comment]
@liuxuan30 it worked like a charm, thank you so much!
