### ISSUE TITLE
I want to add 4 colours to the background of the chart. The colour zones depend on the y values.

### ISSUE THREAD

**Issue by dhruv-jindal** [danielgindi/Charts#2079]
What I want is something like this in the below pic :

![screenshot_2017-01-16-10-13-42](https://cloud.githubusercontent.com/assets/2162047/21971358/eb1d4022-dbd5-11e6-89ef-24833a609b69.png)

**Comment by dhruv-jindal** [comment]
I am using your Android Version of the chart library. I want this for the iOS Version.

**Comment by liuxuan30** [comment]
Dup to https://github.com/danielgindi/Charts/issues/2073
>grid color stripe is not supported yet. However, you can add your own methods in drawExtra() or override some methods, to draw color grid. You can refer how the limit line is drawn, and you would know the coordinates to draw your rect then.

**Comment by dhruv-jindal** [comment]
Thank you for the reply. I will try that solutions of yours.

**Comment by sheasy95** [comment]
Hi. 

Did you have any luck in finding a solution for this issue ? My requirements are quite similar to yours and any help would be great !

Thanks

**Comment by thierryH91200** [comment]
look at Grid background #645 i think that this is the same problem but with the soluce

**Comment by sheasy95** [comment]
Great will look into it now thank you !
