### ISSUE TITLE
leftAxis and value overlap in lineChartView

### ISSUE THREAD

**Issue by Huang-Libo** [danielgindi/Charts#2080]
### I think the first value for lineChart can be draw inside the leftAxis( and same for rightAxis ) to avoid this problem.

![img_0046](https://cloud.githubusercontent.com/assets/12227130/21973287/821fa0e0-dbfa-11e6-8d62-052595f0d08b.png)

**Comment by liuxuan30** [comment]
Known issues. Currently you can turn on `clipValuesToContentEnabled` to avoid overlap.

**Comment by Huang-Libo** [comment]
`clipValuesToContentEnabled ` seems not work well.

![img_0049](https://cloud.githubusercontent.com/assets/12227130/22006472/574d7a16-dca6-11e6-9c07-93c99b97d719.png)

I have a better idea to avoid overlap, just set `lineChartView.xAxis.axisMinimum` to a smaller value, maybe it is useful for some user.

![img_0048](https://cloud.githubusercontent.com/assets/12227130/22006482/5f2015a0-dca6-11e6-8a59-13a1dd27037a.png)

**Comment by liuxuan30** [comment]
`clipValuesToContentEnabled` just clip the label text not to overlap, it solves right :)
setting some margin via axisMinimum is also nice if you don't mind :)

**Comment by gamzerd** [comment]
Hi,

I have a problem about clipping. How can I solve it?

<img width="375" alt="screen shot 2017-03-16 at 13 29 29" src="https://cloud.githubusercontent.com/assets/1108153/23992122/cffade12-0a4c-11e7-8753-f7074e6087b7.png">
