### ISSUE TITLE
accessing .rightAxis gives EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by mcsquaredjr** [danielgindi/Charts#2082]
Hello,

I'm trying to build a BarChart, which is embedded into a UITableViewCell. The code below works fine, but when I'm trying to disable rightAxis, I'm getting EXC_BAD_ACCESS. Doing the same for the left axis works just fine. Any ideas? 

Another funny observation. When I'm disabling the leftAxis, the right axis disappears on my chart.

I'm trying to wrap my head around this for the last couple of days, but no luck so far... Help is much appreciated. Here the code:

import UIKit
import Charts

class ChartCell: UITableViewCell {

    @IBOutlet weak var chart: BarChartView!
    override func awakeFromNib() {
        super.awakeFromNib()
    }

    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)
        configureChart()
    }
    
    func buildChart(data: [DiffPoint]) {
        var diffEntries = [ChartDataEntry]()
        var diffMonth = [String]()
        var i = 0
        for diffPoint in data {
            let diffEntry = BarChartDataEntry(x: Double(i), y: diffPoint.value)
            diffEntries.append(diffEntry)
            diffMonth.append(diffPoint.date)
            i += 1
        }
        
        let chartDataSet = BarChartDataSet(values: diffEntries, label: "")
        chartDataSet.colors = ChartColorTemplates.material()
        let chartData = BarChartData(dataSets: [chartDataSet])
        chartData.setDrawValues(false)
        chart.data = chartData
        // TODO: Animation
    }
    
    func configureChart() {
        chart.chartDescription?.text = ""
        chart.xAxis.drawGridLinesEnabled = false
        chart.xAxis.labelTextColor = UIColor.white
        chart.leftAxis.drawGridLinesEnabled = true
        chart.leftAxis.enabled = false
        // the following line gives me error!!!
        chart.rightAxis.enabled = false
        chart.backgroundColor = WWColors.Asphalt
        chart.legend.enabled = false
        chart.highlighter = nil
    }    
}

Thanks a lot!

**Comment by mossby** [comment]
Interesting. What happens if instead of disabled the `rightAxis` you simply disable all it's `draw*` Bools? I think it has more or less the same effect (visually) as outright disabling the axis

```
rightAxis.enabled = true // you could skip this line altogether
rightAxis.drawLabelsEnabled = false
rightAxis.drawGridLinesEnabled = false
rightAxis.drawAxisLineEnabled = false
```

**Comment by mcsquaredjr** [comment]
I cannot even access the rightAxis property itself as I m getting the same bad access error.

**Comment by liuxuan30** [comment]
as far as I can tell,
```swift
    internal override func initialize()
    {
        super.initialize()
        
        _leftAxis = YAxis(position: .left)
        _rightAxis = YAxis(position: .right)
```
is where you start debugging.

**Comment by mcsquaredjr** [comment]
I spent some time debugging the issue -- my observations made me to believe that somehow Xcode and carthage screwed up my environment. I was able to access the property in debugger, but not when I was running the code on the device. 

Anyways, I re-created the project and it all started to work. I'm closing the issue. Thank, everyone, who responded.
