### ISSUE TITLE
In BarChartView leftAxis labels cutdown, does-not fit on screen. 

### ISSUE THREAD

**Issue by ASHISH389** [danielgindi/Charts#2086]
In below Bar-Chart my left-axis values are cutdown. How do I resolve this issue.

In X-axis I want to show values like this. i.e 1,3,5,7,9,11...

**SetChart function :-** 

func setChart(dataPoints: [String], values: [Float])
    {
        barChartView.noDataText = "You need to provide data for the chart."
        
        for i in 0..<dataPoints.count
        {
            let dataEntry = BarChartDataEntry(x: Double(i), yValues: [Double(Float(values[i]).round(decimalPlace: 2))])
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "INR Rates(₹)/$")
        let chartData = BarChartData(dataSet: chartDataSet)
        
        barChartView.data = chartData
        barChartView.leftAxis.axisMinimum = 67
        barChartView.leftAxis.axisMaximum = 70
        barChartView.xAxis.labelPosition = .bottom
        barChartView.rightAxis.enabled = false
        barChartView.data?.setDrawValues(false)
        barChartView.leftAxis.granularityEnabled = true
        barChartView.leftAxis.granularity = 1.0
        barChartView.chartDescription?.text = ""
        chartDataSet.colors = [UIColor(red: 0/255, green: 76/255, blue: 153/255, alpha: 1)]
    }

![img_4208](https://cloud.githubusercontent.com/assets/8068857/22015070/8bf993c4-dcc6-11e6-9ad9-ff3bb86cec5e.JPG)

**Comment by liuxuan30** [comment]
put barChartView.data = chartData at last line.
