### ISSUE TITLE
oh, no!!!!!!  Demo code can't run  

### ISSUE THREAD

**Issue by yyjyyj** [danielgindi/Charts#2087]
I successfully installed the Carthage ，then I try to run，the program is alway   "running 1 of 1 custom shell scripts"  ，I waited for an hour the state has not changed. anyone  help me？

**Comment by petester42** [comment]
When did you get the code? There was done fixes to running the demo done yesterday

**Comment by yyjyyj** [comment]
I get the latest code，it  is still freeze‘s  on this step. "running 1 of 1 custom shell scripts"  

I think this led to the program cannot be run,but I have no idea to fixes. Maybe the configuration path, i use xcode 8.2.1 and carthage 0.18.1

#!/bin/sh

case "$PLATFORM_NAME" in
macosx) plat=Mac;;
iphone*) plat=iOS;;
watch*) plat=watchOS;;
appletv*) plat=tvOS;;
*) echo "error: Unknown PLATFORM_NAME: $PLATFORM_NAME"; exit 1;;
esac

for (( n = 0; n < SCRIPT_INPUT_FILE_COUNT; n++ )); do
VAR=SCRIPT_INPUT_FILE_$n
framework=$(basename "${!VAR}")
export SCRIPT_INPUT_FILE_$n="$SRCROOT"/../Carthage/Build/$plat/"$framework".framework
done

/usr/local/bin/carthage copy-frameworks || exit

for (( n = 0; n < SCRIPT_INPUT_FILE_COUNT; n++ )); do
VAR=SCRIPT_INPUT_FILE_$n
source=${!VAR}.dSYM
dest=${BUILT_PRODUCTS_DIR}/$(basename "$source")
ditto "$source" "$dest" || exit
done

**Comment by petester42** [comment]
Run `Carthage bootstrap` before running the demo and see if that works.

**Comment by yyjyyj** [comment]
the demo still can't run,my colleague gave me a demo of the old version ,it can be running . I think my project missing some static library or network error .

Shell Script Invocation Error "Command /bin/sh failed with exit code 1"
Building dependencies...
*** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
*** Downloading realm-cocoa.framework binary at "v2.1.1"
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out."

**Comment by petester42** [comment]
You need an internet connection to download the dependencies 😛

**Comment by wangxumin** [comment]
I have an internet connection to run Carthage bootstrapm

**Comment by wangxumin** [comment]
I have an  internet connection to run `Carthage bootstrap`,but the result is

**Comment by wangxumin** [comment]
I have an internet connection to run `Carthage bootstrap`,but the result is                                             *** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
*** Downloading realm-cocoa.framework binary at "v2.1.1"
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost."  how can I do

**Comment by dirtmelon** [comment]
@wangxumin because of GFW,Chinese can't use realm with carthage directly.You should use VPN or ss to download that.
