### ISSUE TITLE
error to Methode 

### ISSUE THREAD

**Issue by J-Arji** [danielgindi/Charts#2089]
when install charts 2.3 in app
error to code:

`Method does not override any method from its superclass`

code : 

`		public final override func touchesCancelled(touches: Set<NSUITouch>, withEvent event: NSUIEvent?)
`

**Comment by liuxuan30** [comment]
well.. just check your compatibility of the library and swift vresion.

**Comment by cuddle-sujeet** [comment]
@ J-Arji   did u get the solution, I am using Xcode .73.1
