### ISSUE TITLE
How to set xAxis values from array in Swift 3.0

### ISSUE THREAD

**Issue by ASHISH389** [danielgindi/Charts#2090]
In Swift 2.3 I'm able to set xAxis values from array. Now in Swift 3.0, not able to set. 

I want to assign custom values from my array.

dataPoints = ["18","17","16","15","14","13","12"...] // It contains last 30 days from current date, that's why it contain 18 1st because 18 is current date.

values = [65.66,68.78,64.66,63.37...] 

```
func setChart(dataPoints: [String], values: [Float])
 {
          barChartView.noDataText = "You need to provide data for the chart."
          for i in 1..<dataPoints.count
        {
            let dataEntry = BarChartDataEntry(x: Double(i), yValues: [Double(values[i])])
            dataEntries.append(dataEntry)
        }
        print("ChartDataEntry :\(dataEntries)")
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "INR Rates(₹)/$")
        let chartData = BarChartData(dataSet: chartDataSet)
        barChartView.data = chartData](url)
}
```
Please help me to assign values for x-Axis using swift 3.0

**Comment by MikePT28** [comment]
You need to implement the interface `IChartAxisValueFormatter` and `- (NSString * _Nonnull)stringForValue:(double)value axis:(ChartAxisBase * _Nullable)axis`

Then you return the string you want. If there are no custom X values, usually the `value` will just be the position of the data in the array it comes from, which you could use to determine what string you want for that position.

**Comment by talisk** [comment]
Please see [here](https://github.com/danielgindi/Charts/issues/2094) :)

**Comment by ASHISH389** [comment]
Thanks

**Comment by ASHISH389** [comment]
Couple of days, I'm struggling for this, but now I got the solution, so I'm updating here.

In Swift 3.0 we can set x-axis values like this by passing array.

```
barChartView.xAxis.valueFormatter = IndexAxisValueFormatter(values: dataPoints)
barChartView.xAxis.granularityEnabled = true
barChartView.xAxis.granularity = 2
```
That's it.
