### ISSUE TITLE
Demo in Swift 3

### ISSUE THREAD

**Issue by frederic-adda** [danielgindi/Charts#2092]
Since the library is written in Swift, why not issue a demo project in Swift ?

**Comment by petester42** [comment]
It's to make sure the objective-c still works.

**Comment by frederic-adda** [comment]
ok, but that's not really consistent with advertising about the framework being written in Swift.
I mean, a lot of developers are using this library BECAUSE it's written in Swift, and therefore expect to find some Swift in the demo project. 
Also, the big changes in Charts 3.0.1 are related to Swift 3.
I agree that it's not that difficult to re-translate from obj-C to Swift, but, once you have chosen the future, why look back? ;-)

**Comment by kevinburandt** [comment]
It would be very helpful if there were Swift 3 examples.

**Comment by danielgindi** [comment]
The framework is written in Swift. Demos are in ObjC to make sure and to demonstrate interoperability. If you are a developer you can take a function name from ObjC and call it in Swift, it's not rocket science.
