### ISSUE TITLE
Charts 3.0.1 - Align x labels (dates) with plots

### ISSUE THREAD

**Issue by frederic-adda** [danielgindi/Charts#2094]
I am having a hard time to migrate Charts from version 2 (Swift 2.3) to 3 (Swift 3).

Basically, I can't have the x labels (dates) aligned correctly with the corresponding plots.

This is what I had before in version 2:
https://i.stack.imgur.com/wOL3t.png

In version 2, I had values for days 7, 8, 10 and 11. So I was missing a day in the middle, but the labels were correctly alined with the plots. 

And here is what I have in version 3:
https://i.stack.imgur.com/arIL2.png

In version 3, the "labels" in the x axis have now been replaced by double (for dates, it's a timeInterval since 1970), and formatted via a formatter. So, indeniably, the graph is more "correct" now, since the chart correctly extrapolates the value for the 9th, but I can't find how to put the labels under the corresponding plots. 

This is my code for the x axis:

 ```
let chartView = LineChartView()
 ...
 let xAxis = chartView.xAxis
 xAxis.labelPosition = .bottom
 xAxis.labelCount = entries.count
 xAxis.drawLabelsEnabled = true
 xAxis.drawLimitLinesBehindDataEnabled = true
 xAxis.avoidFirstLastClippingEnabled = true

 // Set the x values date formatter
 let xValuesNumberFormatter = ChartXAxisFormatter()
 xValuesNumberFormatter.dateFormatter = dayNumberAndShortNameFormatter // e.g. "wed 26"
 xAxis.valueFormatter = xValuesNumberFormatter
```

Here is the ChartXAxisFormatter class I created:

```
import Foundation
import Charts

class ChartXAxisFormatter: NSObject {
    var dateFormatter: DateFormatter?
}

extension ChartXAxisFormatter: IAxisValueFormatter {

    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        if let dateFormatter = dateFormatter {

            let date = Date(timeIntervalSince1970: value)
            return dateFormatter.string(from: date)
        }

        return ""
    }

}
```
So, the values here are correct, the formatting is correct, the shape of the chart is correct, but the alignment of the labels with the corresponding plots is not good.

Thanks for your help

**Comment by 4np** [comment]
I ran in the same issue using timestamps before and it is caused because what is being rendered on the x-axis is an interpolated timestamp causing the labels not to match up. I solved the issue on my end by resorting to using array indexes instead.

**Comment by frederic-adda** [comment]
Thanks a lot for your answer!
And the very clear explanation about the timestamps being interpolated, it really makes sense.
I'll try your solution tomorrow, and let you know.

Thanks!

**Comment by frederic-adda** [comment]
@4np I guess that you then have to define your array of ChartDataEntry with xValues as indices too, right ?
Like so : 
```
// Define chart yValues
        var entries = [ChartDataEntry]()
        for (index, score) in scores.enumerated() {
            let yValue = score.value
            let entry = ChartDataEntry(x: Double(index), y: yValue)
            entries.append(entry)
        }
```
Is this correct?

Thanks
Frederic

**Comment by frederic-adda** [comment]
OK, that worked!
But, I had to add 2 more things to my xAxis:
```
  // Show the limit lines behind each plot
  xAxis.drawLimitLinesBehindDataEnabled = true

  // Make sure that only 1 x-label per index is shown
  xAxis.granularityEnabled = true
  xAxis.granularity = 1
```

Thanks for your help.
Also, I opened an issue at StackOverflow there: 
http://stackoverflow.com/questions/41720445/ios-charts-3-0-align-x-labels-dates-with-plots

If you have a SO account and want to copy / paste your answer there, I'd be glad to accept your answer there too.

Thanks
Fred

**Comment by frederic-adda** [comment]
Also, I left this issue open until the Charts devs have a look at it, and maybe introduce a way to choose how the labels should be aligned.
Because I have to choose between 2 poor solutions:
- either use time intervals as xValues (which is the spirit in which the DataEntry should now be constructed), but with misaligned labels,
- or use indices as xValues (which is a way to revert to Charts 2.0), but with the risk that consecutive indices may represent non-consecutive days (as in my example).

Please let us know what you think.

**Comment by thierryH91200** [comment]
@frederic-adda 


I managed to solve the problem
XAxis.granularity = 1.0 must be one day. that is the most important
The smallest date must be 0

(TimeInSeconds - miniDate) / (3600.0 * 24.0)
<img width="612" alt="capture d ecran 2017-01-30 a 12 35 22" src="https://cloud.githubusercontent.com/assets/6251463/22421674/a3a0d902-e6e8-11e6-9466-c4b94ab6d724.png">


And all the trick is in the formatter
We do the opposite operation to retrieve the date
Let date2 = Date (timeIntervalSince1970: (value * 3600 * 24) + miniTime)
         Return dateFormatter.string (from: date2)
do not forget
DateFormatter.timeZone = NSTimeZone (abbreviation: "GMT + 0: 00") as TimeZone!
The demo is macOS
The link is https://github.com/thierryH91200/Charts-log
Line Date tab

**Comment by frederic-adda** [comment]
@thierryH91200 Thanks Thierry !
I'll try to implement your solution right away.

**Comment by frederic-adda** [comment]
It worked! Fantastic!
Thanks for your help!

**Comment by 4np** [comment]
Cool @thierryH91200, that does indeed seem the way to go forward 👍

**Comment by ethanfox** [comment]
This does not work for me

**Comment by Rj707** [comment]
@frederic-adda did you find the solution for your issue?? 
actually I have issue when showing dates on X-Axis. I am showing dates on X-Axis by setting ChartDataEntry's X-value as TimeInterval, but then chart doesn't show data properly. While setting ChartDataEntry's X-value as array index shows the data. 

Here is my code for setting ChartDataEntry's X-value as TimeInterval
for (int i = 0; i < self.temperatureUpdates.count; i++)
    {
        SFTemperatureUpdate *temperatureUpdate = [self.temperatureUpdates objectAtIndex:i];
        double yVal = [temperatureUpdate.value floatValue];
        NSTimeInterval timeInterval = [temperatureUpdate.careatedAt timeIntervalSince1970];
        double xVal = timeInterval;
        [yVals1 addObject:[[ChartDataEntry alloc] initWithX:xVal y:yVal]];
     
    }

![dummydata](https://user-images.githubusercontent.com/9985642/33015564-0a5bcd30-ce0d-11e7-93f7-d4a7be077e18.PNG)
![properdata](https://user-images.githubusercontent.com/9985642/33015565-0aaf7d86-ce0d-11e7-91ce-a7fe771e214c.PNG)

**Comment by Steveybrown** [comment]
Trying to get the above solutions working when using multiple LineChartDataSets on the one graph, has anyone been able to get it successfully working? 

I'm having problems finding a solution when one dataset might differ in size compared to the other.
i.e 

```
let x = LineChartDataSet(values: values1, label: "test 1") // count 5
let y = LineChartDataSet(values: values2, label: "test 2") // count 8
```
