### ISSUE TITLE
Fatal error when providing multiple data sets in PieChartData

### ISSUE THREAD

**Issue by aubm** [danielgindi/Charts#2099]
Hey,

Thank you for open sourcing such a work!
I'm quite new in Swift so I would really appreciate if someone could help me figuring out some strange behavior.

Basically, what I'm trying to do is to initialize a pie chart data with multiple data sets. Here is the code that I use:

```
pieChart.data = PieChartData(dataSets: [
    PieChartDataSet(values: [PieChartDataEntry(value: 30)], label: "Foo"),
    PieChartDataSet(values: [PieChartDataEntry(value: 70)], label: "Bar")
])
```

When I do that, I get this error: `fatal error: unexpectedly found nil while unwrapping an Optional value`.

It seems to happen [here](https://github.com/danielgindi/Charts/blob/a540403f0d531f29ce01007dbccf2d6a26ad8253/Source/Charts/Renderers/LegendRenderer.swift#L47), on the second iteration, when `i` equals `1`.

I reproduced it in an example project that can be found [here](https://github.com/aubm/My-iOS-Charts).

Cheers!

**Comment by rjong** [comment]
Ik have the same problem in my project. Waiting on a fix :)

**Comment by rjong** [comment]
Is there more information about this bug? Is there a fix?

**Comment by aubm** [comment]
It doesn't seem to :/

**Comment by yazankhayyat** [comment]
Hey guys Im experiencing the same issue here, any fix recommendations?

**Comment by liuxuan30** [comment]
As far as I remember, pie chart only allow 1 data set.
```swift
    open override func getDataSetByIndex(_ index: Int) -> IChartDataSet?
    {
        if index != 0
        {
            return nil
        }
        return super.getDataSetByIndex(index)
    }
```
