### ISSUE TITLE
BarChartView: xAxis values are not aligned with bars

### ISSUE THREAD

**Issue by SvenMuc** [danielgindi/Charts#2106]
I migrated my diagrams to Charts 3.0.1. It worked quite smoothly, but I cannot manage to align the bar charts to my xAxis values. The following diagram should show a histogram of values between 0 and 10 (11 bars).

**Variant 1**
``` Swift
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.setLabelCount(11, force: true)
```

All index values are shown, but not aligned with the bars.

![bildschirmfoto 2017-01-22 um 19 06 29](https://cloud.githubusercontent.com/assets/13385716/22184699/ca169a2a-e0d7-11e6-91b5-32f1d038504b.png)

**Variant 2 (centerAxisLabelsEnabled)**
``` Swift
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.centerAxisLabelsEnabled = true
                barChart.xAxis.setLabelCount(11, force: true)
```

The index 10 is missing on the xAxis.

![bildschirmfoto 2017-01-22 um 19 16 36](https://cloud.githubusercontent.com/assets/13385716/22184711/14b326de-e0d8-11e6-8bea-f5424e0e1328.png)

**Variant 3 (fitBars)**
``` Swift
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.centerAxisLabelsEnabled = true
                barChart.xAxis.setLabelCount(11, force: true)
                barChart.fitBars = true
```
The xAxis starts with -1

![bildschirmfoto 2017-01-22 um 19 24 59](https://cloud.githubusercontent.com/assets/13385716/22184733/a61df388-e0d8-11e6-9ee8-de78608e11e4.png)

**Variant 4 (axisMinimum and axisMaximum)
```Swift
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.centerAxisLabelsEnabled = true
                barChart.xAxis.setLabelCount(11, force: true)
                barChart.xAxis.axisMinimum = 0.0
                barChart.xAxis.axisMaximum = 10.0
                barChart.fitBars = true
```

The bars are not centered any more and the last xAxis value 10 is not shown.

![bildschirmfoto 2017-01-22 um 19 30 14](https://cloud.githubusercontent.com/assets/13385716/22184768/596176f4-e0d9-11e6-8d82-f00e6bff969d.png)

I tried a couple of other combinations but was not able to align the bars with my numbers 0...10 on the xAxis. Someone has any idea?

**Comment by SvenMuc** [comment]
Another trial. Looks close to my expected result, but the first an last bars are shown only half (see also isst #2105).

```Swift
               barChart.xAxis.axisMinimum = 0.0
                barChart.xAxis.axisMaximum = 10.0
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.labelCount = 11
                barChart.fitBars = true
```

![bildschirmfoto 2017-01-22 um 19 55 57](https://cloud.githubusercontent.com/assets/13385716/22184994/0d2c37e8-e0dd-11e6-9205-3fb7363f5e41.png)

**Comment by SvenMuc** [comment]
The closest diagram layout compared to Charts 2.x gives me the following code. But how can I move the gridlines between the bars as it is done in Charts 2.x? I tried `xAxis.centerAxisLabelsEnabled = true` and `fitBars = true`. Both attributes corrupted my xAxis/bar layout.

```Swift
                barChart.xAxis.granularity = 1.0
                barChart.xAxis.granularityEnabled = true
                barChart.xAxis.labelCount = 11
```

![bildschirmfoto 2017-01-22 um 20 06 19](https://cloud.githubusercontent.com/assets/13385716/22185049/69eb39d8-e0de-11e6-8ae5-e51b7dedcfd6.png)

**Comment by deepakthumbmunkeys** [comment]
@SvenMuc  I'm also facing the same issue with Combined Chart (Bar and Line chart)... First and Last bar width is just half.. if you found the solution please help me out

**Comment by ryanwaggoner** [comment]
For anyone else struggling with this, I found that I couldn't use this combination of granularity and setLabelCount() or labels would be misaligned and/or left & right bars cut off.

However, this seems to work for me:

```
self.periodGraphView.xAxis.labelCount = barValues.count
self.periodGraphView.xAxis.spaceMin = 0.5
self.periodGraphView.xAxis.spaceMax = 0.5
self.periodGraphView.xAxis.granularityEnabled = true
self.periodGraphView.xAxis.granularity = 1
```

**Comment by poojab** [comment]
Hey Thanks this helped me to get x axis labels centre to the bar but how about last bar getting cut?
How you fixed it?

**Comment by levanAmateur** [comment]
> Hey Thanks this helped me to get x axis labels centre to the bar but how about last bar getting cut?
> How you fixed it?

barChart.xAxis.axisMaximum = Double(values.count)

**Comment by levanAmateur** [comment]
barChart.xAxis.centerAxisLabelsEnabled = false
this fixed in my case.
Do not set centerAxisLabelsEnabled true

**Comment by liuxuan30** [comment]
refer charts demo.

**Comment by poojab** [comment]
chartView.xAxis.axisMinimum = -0.5 //to avoid issue of last bar getting half cut

this worked for me

**Comment by Khushtar786** [comment]
Can Any One Give me the Whole Code of the Graph Actually I Applied These But Didn't Work
