### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by nandawys** [danielgindi/Charts#2109]
![image](https://cloud.githubusercontent.com/assets/1567894/22233205/b4e6f55c-e229-11e6-86f6-1d9927804176.png)

Empty dataSet cause this crash.
So I have to add this judge statement. It works, but I'm not sure what's behind this ...

open override func entryForIndex(_ i: Int) -> ChartDataEntry?
    {
        if _values.count < i + 1 {
            return nil
        }
        return _values[i]
    }

**Comment by petester42** [comment]
I agree that this function could be better. Since it returns an optional the check should be done in the function. I believe that the actual intent is that the function should be marked as throws and the return type should not be optional.

**Comment by AtharvaVaidya** [comment]
I'm still facing this issue. Is this going to be resolved?

**Comment by liuxuan30** [comment]
first we need to know why it's oob. Empty data set should not go in there

**Comment by jjatie** [comment]
Given Swift Arrays expect the user to either check that the index is within bounds, that the Charts API should do the same. This allows the DataSet to return a non-optional ChartDataEntry.

**Comment by liuxuan30** [comment]
no update for half year. closing
