### ISSUE TITLE
SocketIOClientConfiguration.swift wont compile

### ISSUE THREAD

**Issue by orensha** [danielgindi/Charts#2113]
Hi, im using Xcode 8.2.1 and your project newest version and yet cant compile it.
thats the error im getting. can you help? see image attached...

![screen shot 2017-01-24 at 6 26 37 pm](https://cloud.githubusercontent.com/assets/16323011/22256479/90e2a446-e263-11e6-9225-a8c1c034ca3f.png)

**Comment by petester42** [comment]
`SocketIOClientConfiguration.swift` does not come from our library. This is an issue with your code. If range is ambiguous you can use `Charts.Range` to specify they Charts one or `Swift.Range` to specify the swift one. 

Hope that helps :)

**Comment by orensha** [comment]
hey, sorry for the mistake i ment sending it to the socket io group :)
