### ISSUE TITLE
Undefined symbols for architecture arm64 - Charts 3.0 CocoaPods

### ISSUE THREAD

**Issue by dkowalsky92** [danielgindi/Charts#2117]
So my code won't compile and I can't seem to figure out what causes the problem. I'm using CocoaPods with the master branch, without Realm, already fixed all the issues regarding 3.0 version changes.  I attach screenshots for reference:
![screen shot 2017-01-25 at 14 58 54](https://cloud.githubusercontent.com/assets/22548305/22293264/49da9ed0-e30f-11e6-9a58-c636a764f225.png)
![screen shot 2017-01-25 at 14 59 25](https://cloud.githubusercontent.com/assets/22548305/22293268/4f5fc434-e30f-11e6-923a-448497e469f7.png)
![screen shot 2017-01-25 at 14 59 40](https://cloud.githubusercontent.com/assets/22548305/22293271/50e7340e-e30f-11e6-9199-bf96c902197f.png)
![screen shot 2017-01-25 at 15 00 00](https://cloud.githubusercontent.com/assets/22548305/22293272/520d328e-e30f-11e6-892d-f0748ca2efc4.png)

**Comment by petester42** [comment]
Have you tried deleting your derived data and cleaning the project?

**Comment by petester42** [comment]
Also why are you not using the tagged version of charts that on cocoapods?

**Comment by dkowalsky92** [comment]
Deleting derived data seems to have worked, thanks for your help. Appreciated.

**Comment by petester42** [comment]
Solves almost all problems :p
