### ISSUE TITLE
Can i use the framework without including the whole project ?

### ISSUE THREAD

**Issue by Ahmad-Dari** [danielgindi/Charts#2118]
I was wondering if its possible to use the framework only without including the whole Charts project in my Objective C project, if YES how can i do that ?

**Comment by petester42** [comment]
You can use Carthage or cocoapods to do so. Those would be the easiest ways to do so.

**Comment by Ahmad-Dari** [comment]
So there is no way to just drag and drop the charts framework file in my project and use it like i use most libraries and frameworks ?

**Comment by petester42** [comment]
You can but if there are the same type already available in your project then you have to take care of that. By prefixing them

**Comment by petester42** [comment]
This seems addressed.
