### ISSUE TITLE
Simple Radar Chart causing hang / cpu 99%

### ISSUE THREAD

**Issue by royherma** [danielgindi/Charts#2121]
Trying to create and load a simple RadarChartView, however when assigning data to it, it causes the app to freeze / cpu goes to 99%.

```
@IBOutlet var radarChart : RadarChartView!

let entries = [
                ChartDataEntry(value: 0.8, xIndex: 0),
                ChartDataEntry(value: 1.8, xIndex: 1),
                ChartDataEntry(value: 2.8, xIndex: 2),
                ChartDataEntry(value: 3.8, xIndex: 3),
                ChartDataEntry(value: 4.8, xIndex: 4),
                ChartDataEntry(value: 5.8, xIndex: 5)
                ]
            
let dataSet : RadarChartDataSet = RadarChartDataSet(yVals: entries, label: nil)
dataSet.drawFilledEnabled = true
dataSet.drawValuesEnabled = false
let data = RadarChartData(xVals: ["1","2","3","4","5","6"], dataSets: [dataSet])
            
self.radarChart.data = data
```

When no data is assigned, the chart loads and display the valid "no data text", however as mentioned assigning data to it (i've tried multiple forms) causes the problem.

Would love some help, thanks!

**Comment by thierryH91200** [comment]
try that

       let entries = [
            RadarChartDataEntry(value: 0.8),
            RadarChartDataEntry(value: 1.8),
            RadarChartDataEntry(value: 2.8),
            RadarChartDataEntry(value: 3.8),
            RadarChartDataEntry(value: 4.8),
            RadarChartDataEntry(value: 5.8)
       ]
        
        let data = RadarChartData()
        let dataSet = RadarChartDataSet(values: entries, label: nil)
        dataSet.drawFilledEnabled = true
        dataSet.drawValuesEnabled = false
        
        data.addDataSet(dataSet)
        
        self.radarChart.data = data

**Comment by royherma** [comment]
Don't have RadarChartDataEntry, so did this:

```
let entries = [
                ChartDataEntry(value: 0.8, xIndex: 0),
                ChartDataEntry(value: 1.8, xIndex: 1),
                ChartDataEntry(value: 2.8, xIndex: 2),
                ChartDataEntry(value: 3.8, xIndex: 3),
                ChartDataEntry(value: 4.8, xIndex: 4),
                ChartDataEntry(value: 5.8, xIndex: 5)
            ]
            
            
            let data = RadarChartData()
            let dataSet = RadarChartDataSet(yVals: entries, label: nil)
            
            data.addDataSet(dataSet)
            
            self.radarChart.data = data
```


Got this (it's the cell with the corresponding values):

![image](https://cloud.githubusercontent.com/assets/3466248/22407157/a4dd9cd0-e669-11e6-8d7e-75c60bcb4ec9.png)

**Comment by thierryH91200** [comment]
You have a version that is obsolete
update to chart 3.0

**Comment by royherma** [comment]
that's probably it...updating

**Comment by petester42** [comment]
Interesting. What version are you using 2.3? I can try it out.

**Comment by royherma** [comment]
@petester42 using 2.3.1

**Comment by royherma** [comment]
any luck @petester42 ?

**Comment by petester42** [comment]
Im just trying it now. And I don't see this problem. Im using an iPhone 6 to test and its never goes over 2. Maybe you're doing too much stuff on the main thread in your app?

**Comment by petester42** [comment]
I suggest you update to 3.0 soon since swift 2.3 is deprecated and will be removed in Xcode 8.3
