### ISSUE TITLE
LineChartData(dataSets: dataSets)  Missing xVals

### ISSUE THREAD

**Issue by holiday-sunrise** [danielgindi/Charts#2124]
In the version for swift 2.3 it was still possible to define xValues. This option is no longer available. How xValues are formatted. After the migration the grid is displayed but the lines are not displayed Whats wrong!
In the migration statement I found no hint.

**Comment by holiday-sunrise** [comment]
no bug was a mistake

**Comment by schmitzoide** [comment]
How did you solve this? Where are you putting the x-values @holiday-sunrise?
