### ISSUE TITLE
How to add TrackBall and edit label above BarCharts in Charts swift2 and swift 3??

### ISSUE THREAD

**Issue by goel232** [danielgindi/Charts#2126]
I am working on project where I have used danielgindi/Charts a third party library now the challenge here is I need to present a track ball like shown in the image on highest point of the chart.How can I achieve this any suggestions ??[http://stackoverflow.com/questions/41979926/how-to-achieve-trackball-on-charts-in-swift-3x](url)

**Comment by Markus-Ewert** [comment]
You could use a IValueFormatter

**Comment by goel232** [comment]
Sir sorry can you guide me with the codes??

**Comment by goel232** [comment]
@Markus-Ewert Sir sorry can you guide me with the codes??

**Comment by goel232** [comment]
![screen shot 2017-02-01 at 6 53 43 pm](https://cloud.githubusercontent.com/assets/20591185/22508411/c970a9be-e8af-11e6-8224-f9c9c2669eff.png)
How to access these labels where yAxis points are mentioned(16.0,18.0)

**Comment by goel232** [comment]
@Markus-Ewert 
@liuxuan30 
@danielgindi 
http://stackoverflow.com/questions/41979926/how-to-achieve-trackball-on-charts-in-swift-3x please help sir

**Comment by Markus-Ewert** [comment]
It's possible to change the text of the value above a bar to a String. You can achieve this by extending your ChartController with an IValueFormatter:

```{swift}
class ChartController {

weak var valueFormatter: IValueFormatter?

override func viewDidLoad() {
        super.viewDidLoad()

        valueFormatter = self
    }
}

extension ChartController: IValueFormatter {
func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String {
      switch value {
      case 3.0: return "🙂"
      case 2.0: return "😐"
      case 1.0: return "🙁"
      default: return "\(value)"
      }
  }
}
```

Unfortunately, there is no way to set an image instead of a String or Double.

**Comment by goel232** [comment]
@Markus-Ewert

Sir How can i achieve the same thing in swift 2x ??

**Comment by goel232** [comment]
http://stackoverflow.com/questions/41979926/how-to-achieve-trackball-and-access-label-above-bar-on-bar-charts-in-swift-3x/42019505#42019505
by IOS Singh
