### ISSUE TITLE
Any one try to integrate with SpriteKit/SKScene ?

### ISSUE THREAD

**Issue by harryhow** [danielgindi/Charts#2129]
Want to integrate Chart with SpriteKit/SKScene (in Swift) but can't make it work. 

Any one has this experience? 

Thanks!

**Comment by clayheaton** [comment]
All I've been able to do is to add a chart view as a subview to an SKView. Attaching a chart to an SKNode would be far more powerful, but I haven't figured that out.

**Comment by liuxuan30** [comment]
This library is all about UIKit and CoreGraphics. as long as you can use them, you can integrate
