### ISSUE TITLE
Any Demo of all charts in Swift 3

### ISSUE THREAD

**Issue by srijan12345** [danielgindi/Charts#2132]
Is there any available demo which will show all 8 types of chart written in Swift 3. Currently, I just check your repository and it has code in obj-c.

**Comment by srijan12345** [comment]
Guyz, if you don't have then I had created one demo for my personal use. If anyone wants then I can publish here.

**Comment by thierryH91200** [comment]
look at demo os x

**Comment by f15handch1p5** [comment]
@srijan12345 That would be great! Thanks

**Comment by petester42** [comment]
The macOS demo is in swift and the interface for charts is exactly the same in both languages. It is just syntax differences.
