### ISSUE TITLE
Distance between chart legend and the horizontal bar chart is to big in case of rotated labels

### ISSUE THREAD

**Issue by SvenMuc** [danielgindi/Charts#2138]
I rechecked the issue with Charts 3.0.1. The behavior is the same. See images below.

```Swift
chart.xAxis.labelRotationAngle       = -90.0           // rotate label
chart.xAxis.centerAxisLabelsEnabled  = true
```

![bildschirmfoto 2017-02-04 um 22 16 43](https://cloud.githubusercontent.com/assets/13385716/22621622/1404da20-eb28-11e6-8756-777a847ede7a.png)

```Swift
chart.xAxis.centerAxisLabelsEnabled  = true
```

![bildschirmfoto 2017-02-04 um 22 19 45](https://cloud.githubusercontent.com/assets/13385716/22621624/1cc077e6-eb28-11e6-97ac-b44451fe0082.png)

See also my old issue #1360

**Comment by SvenMuc** [comment]
I tried to investigate the `HorizontalBarChartView.calculateOffsets()` function. The offset results depend strongly on xAxis label rotation. The `calculateOffset()` is called 4 times. As you can see, the `offsetBottom` parameter strongly depends on the `xAxis.labelRotationAngle`. It increases with a higher rotation angle.

For me it looks like a bug in the `calculateLegendOffsets`function (see debugging results below). I'll investigate this topics this evening.

**chart.xAxis.labelRotationAngle = 0.0**
```swift
calculateLegendOffsets: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 29.93359375  offsetLeft: 0.0
Before Extra Offset: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 41.8671875  offsetLeft: 70.0
After Extra Offset:  offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 41.8671875  offsetLeft: 70.0
restrainViewPort:    offsetTop: 10.0   offsetRight: 10.0  offsetBottom: 41.8671875  offsetLeft: 70.0
```

**chart.xAxis.labelRotationAngle = -45.0**
```swift
calculateLegendOffsets: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 63.93359375  offsetLeft: 0.0
Before Extra Offset: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 75.8671875  offsetLeft: 63.0
After Extra Offset:  offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 75.8671875  offsetLeft: 63.0
restrainViewPort:    offsetTop: 10.0   offsetRight: 10.0  offsetBottom: 75.8671875  offsetLeft: 63.0
```

**chart.xAxis.labelRotationAngle = -90.0**
```swift
calculateLegendOffsets: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 69.93359375  offsetLeft: 0.0
Before Extra Offset: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 81.8671875  offsetLeft: 29.0
After Extra Offset:  offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 81.8671875  offsetLeft: 29.0
restrainViewPort:    offsetTop: 10.0   offsetRight: 10.0  offsetBottom: 81.8671875  offsetLeft: 29.0
```

**Comment by SvenMuc** [comment]
I think the root cause can be found in the function `calculateLegendOffsets`in `BarLineChartViewBase`. The switch case `.bottom` calculates the `offsetBottom` value by adding the `xAxis_labelRotatedHeight`which in case of an horizontal bar chart the left axis. The correct distance can be calculated by using the right axis label height.

Is there a way to find out if we have a horizontal or vertical chart?

What's the difference between `_legend.orientation`and `_legend.verticalAlignment` in the switch cases?

```Swift
          case .horizontal:
                
                print("calculateLegendOffsets->horizontal")
                
                switch _legend.verticalAlignment
                {
                case .top:
                    offsetTop += min(_legend.neededHeight, _viewPortHandler.chartHeight * _legend.maxSizePercent) + _legend.yOffset
                    if xAxis.isEnabled && xAxis.isDrawLabelsEnabled
                    {
                        offsetTop += xAxis.labelRotatedHeight
                        print("calculateLegendOffsets(horizontal,top): offsetTop: \(xAxis.labelRotatedHeight)")
                    }
                    
                case .bottom:
                    offsetBottom += min(_legend.neededHeight, _viewPortHandler.chartHeight * _legend.maxSizePercent) + _legend.yOffset
                    if xAxis.isEnabled && xAxis.isDrawLabelsEnabled
                    {
                        offsetBottom += xAxis.labelRotatedHeight
                        print("calculateLegendOffsets(horizontal,bottom): offsetBottom: \(xAxis.labelRotatedHeight)")
                    }
```

**Comment by SvenMuc** [comment]
One possible solution can be the following (`case .bottom:`):
```swift
if rightAxis.isEnabled && rightAxis.isDrawLabelsEnabled
{
    offsetBottom += rightAxis.getRequiredHeightSpace()
}
```

By this modification I get the correct offset values for a horizontal chart.

```swift
calculateLegendOffsets: offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 29.8671875  offsetLeft: 0.0
Before Extra Offset:    offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 41.80078125  offsetLeft: 29.0
After Extra Offset:     offsetTop: 0.0   offsetRight: 0.0  offsetBottom: 41.80078125  offsetLeft: 29.0
restrainViewPort:       offsetTop: 10.0   offsetRight: 10.0  offsetBottom: 41.80078125  offsetLeft: 29.0
```

But how do I detect the horizontal chart view in `BarLineChartViewBase.calculateLegendOffsets()`?

**Comment by liuxuan30** [comment]
Thanks @SvenMuc ! Seems you did a lot of work. Mind to file a PR to fix?

**Comment by SvenMuc** [comment]
I can do so. But I don't like my solution (see above) very much. Is there a better way to identify whether the xAxis is really the xAxis or the rightAxis @liuxuan30 ?

**Comment by liuxuan30** [comment]
I saw some code like ` let didUserDrag = (self is HorizontalBarChartView)` to know whether it's horizontal or vertical bar chart.
Also, not sure why you ask 'better way' to identify xAxis is really the xAxis or the rightAxis. Just using the Class.self can know which class it is. But I wonder this seems not an answer to your question.

**Comment by SvenMuc** [comment]
Filed pull request #2214
