### ISSUE TITLE
Repeating Xaxis values

### ISSUE THREAD

**Issue by sahabe1** [danielgindi/Charts#2143]
Hi daniel,

I am trying to plot values on chart. it its fine when plotting multiple values but in case of single value the xAxis label is repeating. pleas help me how can i resolve 

![img_4228](https://cloud.githubusercontent.com/assets/1065015/22656569/c7489c74-ecb9-11e6-8d7f-58dc61337709.PNG)

**Comment by CodeLiar** [comment]
Same for me

**Comment by JiteshBharadiya** [comment]
> ```swift
>  // Make sure that only 1 x-label per index is shown
>   xAxis.granularityEnabled = true
>   xAxis.granularity = 1
> ```
> 
> I use these codes to solve this problem
> [#2094 (comment)](https://github.com/danielgindi/Charts/issues/2094#issuecomment-273612724)

@CodeLiar  Thanks. It is also works for me.
