### ISSUE TITLE
Piechart with smooth edges?

### ISSUE THREAD

**Issue by sree127** [danielgindi/Charts#2146]
Hey,

I was wondering if there was a way to render a piechart with smooth edges like below :
![screen shot 2017-02-07 at 3 48 01 pm](https://cloud.githubusercontent.com/assets/3157263/22687150/ee4b9b6c-ed4c-11e6-8721-b3e70757ec9d.png)

All I could achieve was this one : 

![screen shot 2017-02-07 at 3 47 56 pm](https://cloud.githubusercontent.com/assets/3157263/22687164/f6d090c6-ed4c-11e6-8832-dd7c378b638a.png)

below is the code : 

```
func reloadPieChart() {
 
        var dataEntries : [ChartDataEntry] = []
        let dataEntry : ChartDataEntry?
        let dataEntry2 : ChartDataEntry?

        dataEntry = ChartDataEntry(x: 0, y: 80)
        dataEntry2 = ChartDataEntry(x: 0, y: 20)
        dataEntries.append(dataEntry!)
        dataEntries.append(dataEntry2!)

        let dataSet  = PieChartDataSet(values: dataEntries, label: "")
        dataSet.addColor(Utility().hexStringToUIColor(hex: "#00B1EB"))
        dataSet.addColor(Utility().hexStringToUIColor(hex: "#CFD7D9"))

        let pieChartData = PieChartData(dataSet: dataSet)
        pieChartData.setValueFormatter(self)
        pieChartData.setValueFont(UIFont(name: "VWText-Bold", size: 10)!)
        pieChartView.usePercentValuesEnabled = true
        pieChartView.drawSlicesUnderHoleEnabled = false
        pieChartView.holeRadiusPercent = 0.85
        pieChartView.chartDescription?.enabled = false
        pieChartView.drawCenterTextEnabled = false
        pieChartView.drawEntryLabelsEnabled = false
        pieChartView.legend.enabled = false
        pieChartView.rotationAngle = -255
        pieChartView.maxAngle = 330;

        pieChartView.delegate = self
        pieChartView.data = pieChartData
        
        pieChartView.animate(yAxisDuration: 1.3, easingOption: ChartEasingOption.easeOutBack)
    }
```
Any help would be much appreciated. TIA. 

@liuxuan30 @danielgindi

**Comment by Kadi0** [comment]
Hi sree127,
I'm trying to get the minimum code to only display one graph just like you've done in the above. I followed an older tutorial but it was for swift 2, not 3. All I get is arguments does not match...etc.

So, could you help me out with the rest of the code to display your graph ?

I'd really appreciate that,

**Comment by liuxuan30** [comment]
Pie chart in this library does not work this way.
Yours seems is just a arc, so you can just use rounded corner for your arc, that's provided by CoreGraphics

**Comment by iad24** [comment]
@sree127 Hi. Have u managed to do the smooth edge or the arc?

**Comment by iad24** [comment]
Anyone who managed to do this? noob on core graphics here.
