### ISSUE TITLE
y-Values and x-Values as string in barchart,

### ISSUE THREAD

**Issue by RameshMoblity** [danielgindi/Charts#2147]
Hi,

I have used Mpcharts in swift and after converting to Swift3.0 in xcode 8 i am unable to modify x-values and y-values in barchart please let me know the process to change x-values and y-valeus in barchart.

Thanks
Ramesh.

**Comment by RameshMoblity** [comment]
hi Please reply

**Comment by petester42** [comment]
Please refer to the ChartsDemo. There is an example on how to setup every type of chart.
