### ISSUE TITLE
GitHub API request failed

### ISSUE THREAD

**Issue by wangxumin** [danielgindi/Charts#2149]
I have an internet connection to run Carthage bootstrap,but the result is *** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
*** Downloading realm-cocoa.framework binary at "v2.1.1"
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1005 "The network connection was lost." how can I do

**Comment by petester42** [comment]
This is not a charts issues. If your Carthage has something wrong which I suggest you open an issue with them. Otherwise it's something wrong with your setup since it can't connect to GitHub.
