### ISSUE TITLE
how to add Values to Pie Chart? and how to show complete pie chart instead of doughnut

### ISSUE THREAD

**Issue by mohdumarj** [danielgindi/Charts#2150]
Hi, I am trying to show xValues(datapoints) like before but i am not able to find the function. also I want to show full pie chart without central area. (full circle, instead of doughnut). can you please point me in right direction. 
thanks

**Comment by weisunOW** [comment]
For your second question set `PieChartView.holeRadiusPercent` to 0.0

**Comment by liuxuan30** [comment]
pie chart already abandoned x axis in 3.0 I remember.
