### ISSUE TITLE
Fixing the Segmentation fault issue after Convert to Swift 3.0

### ISSUE THREAD

**Issue by Md-Sadham** [danielgindi/Charts#2151]
I was fixed the Segmentation fault issues by commenting a line in *ChartData.swift* file.

Commented line:
// In calcXValAverageLength() method definition
// below line is commented
sum += _xVals[i] == nil ? 0 : count(_xVals[i]!);

How should i convert that commented line to swift 3.0 myself? Also i noticed that count() method is not exist after conversion.

**Comment by petester42** [comment]
The current version of charts is already using swift 3.0
