### ISSUE TITLE
Demo crush !!!

### ISSUE THREAD

**Issue by wangxumin** [danielgindi/Charts#2154]
dyld: Library not loaded: @rpath/FBSnapshotTestCase.framework/FBSnapshotTestCase
  Referenced from: /var/containers/Bundle/Application/968CFB58-AFD6-4960-9727-57700BC4C99D/ChartsDemo.app/ChartsDemo
  Reason: image not found

**Comment by petester42** [comment]
Cannot reproduce. The demo doesn't even use that library. It's for the tests. You might need to use Carthage to download dependencies.
