### ISSUE TITLE
Set line cap to CGMutablePath

### ISSUE THREAD

**Issue by Lukaz32** [danielgindi/Charts#2159]
Hi,
I'm trying to achieve an effect like that to my pie chart: 
<img width="471" alt="captura de tela 2017-02-13 as 16 29 23" src="https://cloud.githubusercontent.com/assets/544727/22897124/a73d43bc-f209-11e6-8f8b-c01394350d99.png">
( I mean the rounded edges)

I've tried to add `context.setLineCap(.round)` to the `PieChartRenderer` but it makes no difference.

Does anyone know how I can achieve that?

Thanks.

**Comment by liuxuan30** [comment]
where and how do you add it? It should work though.

**Comment by liuxuan30** [comment]
I did a quick check, the pie chart is not simply an arc with rounded cap. It may contains two arc and draw the lines to connect them.

You might need to replace `addLine()` with arcs as the rounded effect in `open func drawDataSet(context: CGContext, dataSet: IPieChartDataSet)`. You have to calculate your arc though.

I stroke the path so you know the edges:
<img width="347" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/22911716/1780e150-f29c-11e6-917f-108c9ec80acc.png">

**Comment by rbarbish** [comment]
@Lukaz32 - Do you have any snippets of code you wouldn't mind sharing that you used to make this happen?
