### ISSUE TITLE
How to show label on x-axis at regular interval and tail end on the graph line

### ISSUE THREAD

**Issue by shivang2902** [danielgindi/Charts#2160]
![screen shot 2017-02-14 at 11 19 57 am](https://cloud.githubusercontent.com/assets/18008508/22916902/a193d8c4-f2a7-11e6-9258-ebefa602b88d.png)
I am building the above graph by using the awesome Charts, but i am failing in few points -
1. Show label on x-axis at regular interval
2. Show tail end on the graph line

@danielgindi can you please help me on this, thanks

**Comment by liuxuan30** [comment]
tail end needs you to override some methods to just draw the last circle.
for the labels - it's already showing labels at a regular interval. Not sure your meaning.

**Comment by shivang2902** [comment]
@liuxuan30 this is the image of the graph i need to draw not what i have build, i am not able to show xAxis labels at regular interval. Please mention the methods i need to override to show tail end also the mechanism. I know i am asking a lot but believe me i have researched all over google for this solution, you are my last resort!! 

Thanks in advance

**Comment by liuxuan30** [comment]
to draw circles, there is method `drawCircles()` when highlight. You can refer that, and draw the tail circle in `drawExtras()` maybe. Just find a place you feel fine.

For the labels, please explain why you can't draw it in fixed interval. ChartsDemo already did that.

**Comment by shivang2902** [comment]
![screen shot 2017-02-28 at 7 10 11 pm](https://cloud.githubusercontent.com/assets/18008508/23407370/a4f9d412-fde9-11e6-9963-caac047e4e2c.png)

@danielgindi @liuxuan30  Can you please help me to remove the bottom line with continuous 0 in it. I am not sure what it is and what i have done to produce it but believe me i have removed and added each line of code 1 by 1 to debug it.

Thanks

**Comment by liuxuan30** [comment]
try axisLine, gridLine, zeroLine etc to see whether you turned it on

**Comment by shivang2902** [comment]
As i was debugging this error i came to know that whenever graph data contains all 0 values then this appears, i means the line is drawn on x-Axis and 0 appears just the drawn line now can you please tell how to eliminate them

Thanks in advance :)

**Comment by shivang2902** [comment]
//MARK: - Data Set Initial Setup
extension LineChartDataSet {
    
    /* -------------- Line chart data set initial setup ----------------*/
    func initialSetUp() {
        
        self.drawCirclesEnabled = false
        self.drawCircleHoleEnabled = false
        self.setColor(UIColor.orange)
        self.mode = .cubicBezier
        self.drawCirclesEnabled = false
        self.lineWidth = dataSetLineWidth
        self.circleRadius = dataSetCircleRadius
        self.drawHorizontalHighlightIndicatorEnabled = false
        self.cubicIntensity = dataSetCubicIntensity
        self.drawValuesEnabled = false     //  --------------->>>> THIS HELPED TO REMOVE THE ZERO'S
    }
}

**Comment by shivang2902** [comment]
@liuxuan30 is it possible to draw the tail small circle at the end of the line, i have tried but me was not successful, please guide, thanks

**Comment by liuxuan30** [comment]
just override drawDataSets
