### ISSUE TITLE
BarChartView with TableView

### ISSUE THREAD

**Issue by newbiebie** [danielgindi/Charts#2161]
if I use BarChartView with TableView， the tableView Can't scroll any more！ BarChartView can scale while the tableView can't scroll. How can I solve this problem?

**Comment by liuxuan30** [comment]
take a look at `@objc fileprivate func panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)` and decide what switch you want to turn off. By default it's intended to do so.
