### ISSUE TITLE
"clipValuesToContentEnabled" does not work

### ISSUE THREAD

**Issue by ricpi** [danielgindi/Charts#2163]
![a](https://cloud.githubusercontent.com/assets/5546157/22959521/fd8f6db2-f371-11e6-8f14-389997da24ef.png)

**Comment by newbiebie** [comment]
You can try the offset attribute,
  _barView.extraLeftOffset = 20;

**Comment by newbiebie** [comment]
You can try the offset attribute

**Comment by liuxuan30** [comment]
I need screenshot what does not work. reopen with viewable ones. Your link is broken.

**Comment by gamzerd** [comment]
Hi,

I have a problem about clipping. How can I solve it?

<img width="375" alt="screen shot 2017-03-16 at 13 29 29" src="https://cloud.githubusercontent.com/assets/1108153/23992062/a0d04ece-0a4c-11e7-944d-8d980021486d.png">
