### ISSUE TITLE
Crash Observed when AxisRenderer interval is becoming NaN

### ISSUE THREAD

**Issue by nanduahmed-sikka** [danielgindi/Charts#2168]
I have a chart graph and based upon Segment Controller, We change the value of graph. When the axis graphs values are changed and segment is changed, the zoom level remains the same as it was earlier zoomed to. The following line is crashing in AxisRendererBase.swift since variable are becoming NaN. 
        let intervalSigDigit = Int(interval / intervalMagnitude)
My Chart Release shows following in Lock file
  - Charts (3.0.1):
    - Charts/Core (= 3.0.1)

**Comment by nanduahmed-sikka** [comment]
This is one of the lldb log: fatal error: Double value cannot be converted to Int because it is either infinite or NaN

**Comment by liuxuan30** [comment]
need more info why some of the values become NaN or inf.

**Comment by nanduahmed-sikka** [comment]
Not sure. I am just using the API and it was crashing on this If in near future I get to reproduce I will surely paste the info. As of now I would like someone to fix it for invalid values. Any help would be appreciated.

**Comment by liuxuan30** [comment]
yep but we need more info on how this happens

**Comment by capecrawler** [comment]
Also getting few crashes from fabric that is somehow related to this.

![screen_shot_2017-04-20_at_10_58_43_am](https://cloud.githubusercontent.com/assets/1147223/25211652/c067ce10-25b8-11e7-84b9-3775813b10a7.png)

**Comment by liuxuan30** [comment]
are you having same issue as in #2356?

**Comment by capecrawler** [comment]
I am not sure since I was not able to replicate this crash and it points to different line of code which is `let intervalSigDigit = Int(interval / intervalMagnitude)`. My guess is that intervalMagnitude value is 0.0 or NaN that is causing the crash.

**Comment by liuxuan30** [comment]
that's weird, I need to know when `let intervalMagnitude = ChartUtils.roundToNextSignificant(number: pow(10.0, Double(Int(log10(interval)))))` will make `intervalMagnitude` zero. I don't see obvious number will do so.

**Comment by josman185hotm** [comment]
Hello @liuxuan30 , @danielgindi 
I'm getting an error in line 125: fatal error: Double value cannot be converted to Int because it is either infinite or NaN

this is the line: let intervalMagnitude = ChartUtils.roundToNextSignificant(number: pow(10.0, Double(Int(log10(interval)))))

please if you have any suggestions I'll be very thankful.

here you have more data:
![captura de pantalla 2017-06-16 a las 19 28 41](https://user-images.githubusercontent.com/17994629/27248514-3e49780e-52ca-11e7-8e9b-f38dc06d27f5.png)

**Comment by liuxuan30** [comment]
Can you check if https://github.com/danielgindi/Charts/pull/2377 fix the issue? It has been sometime and I don't remember if they are the same.

**Comment by atalayasa** [comment]
@josman185hotm did you solve your issue ?

**Comment by liuxuan30** [comment]
closing now. reopen with updates

**Comment by jessmarie** [comment]
The same thing happened for me when dismissing a viewController and returning to the view that included the chart in 

> let intervalMagnitude = pow(10.0, Double(Int(log10(interval)))).roundedToNextSignficant()

Is there any particular reason why the log10() function (which returns a double) is converted to an Int and then again to a double. I am trying to understand the problem so any hint will help!

**Comment by ivan-pavliuk** [comment]
Hello. The same crash!

STR: 
1. Zoom in the chart
2. Change count lines in the chart (update LineChartView.data value with new points)

**Comment by ivan-pavliuk** [comment]
The solution for me:
set self.chartView.zoom(scaleX: 0, scaleY: 0, x: 0, y: 0) when updating the chart

**Comment by laurenyew-ua** [comment]
Hitting this crash as well. 
let intervalMagnitude = pow(10.0, Double(Int(log10(interval)))).roundedToNextSignficant()
        let intervalSigDigit = Int(interval / intervalMagnitude) 
is crashing. intervalMagnitude is coming back as NaN.

**Comment by ciumexan** [comment]
same here... i think is related to the interval value not getting the default (minimal) init. 
So the "interval" is nil.
