### ISSUE TITLE
Fixed BarWidth based on Pixel for BarChart

### ISSUE THREAD

**Issue by aelam** [danielgindi/Charts#2170]
When I am drawing MACD indicators in Stock Charts. I've found I can't set fixed barWidth based on Pixel 
I'm wandering if there is a way can make it base on XValues so the barWidth won't change when the chart is zoomed out or zoomed in 

It's like the opposite of #2169. 

This is the code snippet of the barWidth part , obviously you know it.
```
    /// The width of the bars on the x-axis, in values (not pixels)
    ///
    /// **default**: 0.85
    open var barWidth = Double(0.85)
```

**Comment by aelam** [comment]
Finally my solution is 
set barWidth = 0   //  xValue
set barBorderWidth = 1 // pixels
add borderColor for Index in BarChartDataSet
override BarChartRenderer. let it draw based on the borderColor for each index 

It's a bit weird.

**Comment by liuxuan30** [comment]
guess I can close this
