### ISSUE TITLE
How to set different colors for intervals on LineChart?

### ISSUE THREAD

**Issue by jmamegroot** [danielgindi/Charts#2172]
I m using Charts Library (swift) and I need to add a specific color as background color for each interval in line chart like heartrate zones (see url image). Any one has an idea?

[http://imgur.com/a/kNpBj](url)

**Comment by thierryH91200** [comment]
look at Grid background #645 i think that this is the same problem but with the soluce

**Comment by liuxuan30** [comment]
Thank you!
