### ISSUE TITLE
Stacked bar marker returns entry.y of entire stack

### ISSUE THREAD

**Issue by acegreen** [danielgindi/Charts#2173]
Hey guys, 

Not sure if I'm missing something, but I added a marker for a bar chart and was expecting that the marker would show the value of the highlighted entry in a stacked bar. Instead it shows the y value of the entire stack. Looked around in entry as well as highlight but couldn't catch anything. The idea is to get the value of the highlighted. highlight.y seems to return the same value as entry.y

barChartView.highlightFullBarEnabled = false 

Just to be clear, the intention here is to display the value of the highlighted stack and not the y value of the highlighted 

```
open override func refreshContent(entry: ChartDataEntry, highlight: Highlight) {
        
        if highlight.isStacked {
            setLabel(String(highlight.y))
        } else {
            setLabel(String(entry.y))
        }
}
```

![simulator screen shot feb 18 2017 7 18 42 pm](https://cloud.githubusercontent.com/assets/10794609/23097924/2b486250-f60f-11e6-80aa-e4a8d72ddcc6.png)

**Comment by liuxuan30** [comment]
are you able to see how '100' is passed to the marker? 

here's the code where it fetch the entry and draw marker:
```swift
    /// draws all MarkerViews on the highlighted positions
    internal func drawMarkers(context: CGContext)
    {
        // if there is no marker view or drawing marker is disabled
        guard
            let marker = marker
            , isDrawMarkersEnabled &&
                valuesToHighlight()
            else { return }
        
        for i in 0 ..< _indicesToHighlight.count
        {
            let highlight = _indicesToHighlight[i]
            
            guard let
                set = data?.getDataSetByIndex(highlight.dataSetIndex),
                let e = _data?.entryForHighlight(highlight)
                else { continue }
            
            let entryIndex = set.entryIndex(entry: e)
            if entryIndex > Int(Double(set.entryCount) * _animator.phaseX)
            {
                continue
            }

            let pos = getMarkerPosition(highlight: highlight)

            // check bounds
            if !_viewPortHandler.isInBounds(x: pos.x, y: pos.y)
            {
                continue
            }

            // callbacks to update the content
            marker.refreshContent(entry: e, highlight: highlight)
            
            // draw the marker
            marker.draw(context: context, point: pos)
        }
    }
```
You need to debug it first to see how the lighlight to entry object is created. Thanks

**Comment by KaZu404** [comment]
Hi,

I've got the same issue, the entry.y value that is sent to the refreshContent function is the sum of all the values in stack. I think it's because for a stack each entry is as follow : 

`BarChartDataEntry(x: Double(i), yValues: stackValues)`

I think it comes from your drawMarkers function that get the wrong highlight value. Can you indicate me in which file/folder it is please ?

Thank you in advance :)

**Comment by drewster99** [comment]
I thought this was a bug as well.  And maybe it is, because the usage is pretty non-obvious.
But here's my solution -- no changes to Charts project needed:

`open override func refreshContent(entry: ChartDataEntry, highlight: Highlight) {
        guard highlight.isStacked else {
            setLabel(valueFormatter.stringForValue(entry.y, axis: nil))
            return
        }

        guard let barChartDataEntry = entry as? BarChartDataEntry,
            let stackData = barChartDataEntry.yValues,
            barChartDataEntry.isStacked else {
                return
        }

        setLabel(valueFormatter.stringForValue(stackData[highlight.stackIndex], axis: nil))
    }`

**Comment by liuxuan30** [comment]
mind to file a PR and perhaps a bug description?
This thread is posted about 2 years - and suddenly alive now. Lots of things changed, so I'd expect a refresh of the bug report.

**Comment by drewster99** [comment]
My solution included no changes to the Charts framework.  Just a little extra work inside the refreshContent of the handler.

**Comment by Kingamattack** [comment]
It works like a charm. Thanks @drewster99 !!!
