### ISSUE TITLE
Bottom Label is not printing whole array list.

### ISSUE THREAD

**Issue by Avinashoo7** [danielgindi/Charts#2175]
I have 5 months in my array list to print on bottom label.
let months = ["Aug", "Sep", "Oct", "Nov", "Dec"]

Bottom Label is not printing whole array list.

I have used grouped bar chart with bar space and group space.

![bar graph](https://cloud.githubusercontent.com/assets/19885451/23120518/a1f11f04-f782-11e6-9833-65a82770006a.png)

Moreover I am facing problem with LINE GRAPH as well. is not showing properly with group spacing.

**how to fix this?**

**Comment by liuxuan30** [comment]
Check ChartsDemo first. Should be your setup issue.
