### ISSUE TITLE
Line Chart not show empty values - Charts 3.0

### ISSUE THREAD

**Issue by cepages** [danielgindi/Charts#2176]
Hi,

I'm trying to achieve show empty values in my chart. This is the closest I can get:

![screen shot 2017-02-20 at 11 19 33](https://cloud.githubusercontent.com/assets/5259830/23123067/c4a7e268-f75e-11e6-9d4d-e3f1507efad4.png)

In this example when there is not data about, I set it to `0` and initially I set the minimum to 0.1 = `    yAxis.axisMinimum = 0.01;`

I would like that the values different to 0 are joined together in the same line. So I tried to add only the values bigger than 0:

![screen shot 2017-02-20 at 11 20 15](https://cloud.githubusercontent.com/assets/5259830/23123155/2dd85178-f75f-11e6-8c8b-94cd3c492358.png)

Because for the Chart 3.0 I need to add a value for X, I can't start with null values at the beginning of the Chart.

So, reading other issues I thought to create a second `LineChartDataSet` just with 0 values and hide it with clear color and alpha = `0`.

Yeah! this is exactly the Chart a I want:
![screen shot 2017-02-20 at 11 38 22](https://cloud.githubusercontent.com/assets/5259830/23123639/2298505e-f761-11e6-8edf-4ee81ea48aa7.png)

But there are two problems with this way:

- Firstly it doesn't seem right to have to create a `LineChartDataSet` for zero values and then hide that `LineChartDataSet` one. Actually one of the consequences is I had to change the speed of the animation (faster) because obviously it takes longer to paint ( with clear color ).

- Secondly I have one legend with two labels. I tried to remove the Zero Values one ( unsuccessfully), but again it seems I'm trying the wrong approach. 

Any ideas?

Thanks :)

**Comment by liuxuan30** [comment]
hmm, you are talking about line breaking right?
To achieve your third image, you can just insert these two points, and set x axis minimum and maximum, so you have the same visual.
We don't support line breaking officially yet, because it's not that easy to think about. I tried to implement this last year, also encountered many issues (like negative values, filling the rect below the line, etc)
Currently the quick around is to use multiple data sets ti simulate. Once there is a good solution for line breaking, we will do it.

**Comment by cepages** [comment]
@liuxuan30 thanks.

I don't think it's line breaking. To be honest the real issue it's my points don't start on the day 6 of Feb, but I want to show that there is no data for those days, that's why I have that empty space.

I was trying with:

`xAxis.axisMinimum` and ` xAxis.axisMaximum` and works!

Thanks for the idea 👍

**Comment by irshad9998** [comment]
@cepages  how to display `Kg` on top of yAxis
