### ISSUE TITLE
"noDataText" does not work

### ISSUE THREAD

**Issue by ricpi** [danielgindi/Charts#2179]
![nodatatext](https://cloud.githubusercontent.com/assets/5546157/23157219/2e028a8c-f855-11e6-8e57-66d2dc049fd3.png)
I set "noDataText", but it does not work, it always be "no chart data available." when the chart is empty even i change the value of "noDataText" in ChartViewBase.swift

**Comment by liuxuan30** [comment]
How do you change it. It should be working:
```
    /// text that is displayed when the chart is empty
    open var noDataText = "No chart data available."
```

**Comment by ricpi** [comment]
@liuxuan30 I set a value for "noDataText", it does not work, and i try to change source code like this:
/// text that is displayed when the chart is empty
    open var noDataText = "Other Value"
it does not work too, the empty chart always display "No chart data available"

**Comment by liuxuan30** [comment]
I just tried and it works just fine. I believe you made some simple mistakes. Check from:
```swift
    open override func draw(_ rect: CGRect)
    {
        let optionalContext = NSUIGraphicsGetCurrentContext()
        guard let context = optionalContext else { return }
        
        let frame = self.bounds

        if _data === nil && noDataText.characters.count > 0
        {
            context.saveGState()
            defer { context.restoreGState() }
            
            ChartUtils.drawMultilineText(
                context: context,
                text: noDataText,
                point: CGPoint(x: frame.width / 2.0, y: frame.height / 2.0),
                attributes:
                [NSFontAttributeName: noDataFont,
                 NSForegroundColorAttributeName: noDataTextColor],
                constrainedToSize: self.bounds.size,
                anchor: CGPoint(x: 0.5, y: 0.5),
                angleRadians: 0.0)
            
            return
        }
```
debug into here to see how `noDataText` is fed.

**Comment by codepushr** [comment]
Got the same issue. Setting `noDataText` or `noDataTextColor` doesn't change anything.
All the other attributes work as expected.

```swift
// Works
cell.chartView.backgroundColor = UIColor.clear
cell.chartView.chartDescription!.enabled = false
cell.chartView.drawGridBackgroundEnabled = false
cell.chartView.dragEnabled = false
cell.chartView.pinchZoomEnabled = false
cell.chartView.setScaleEnabled(false)
cell.chartView.xAxis.enabled = false
cell.chartView.rightAxis.enabled = false
cell.chartView.leftAxis.enabled = false
cell.chartView.legend.enabled = false
// Doesn't work
cell.chartView.noDataText = "Foo"
cell.chartView.noDataTextColor = UIColor.white
```

**Comment by codepushr** [comment]
Nevermind, got it working by placing it before draw().

**Comment by Josevin-infosys** [comment]
> Nevermind, got it working by placing it before draw().

How ? do we directly calling draw method ? where did you placed the noDataText ?

**Comment by nguyentanhoangnth** [comment]
I have same this problem . I called chart.nodatatext = "text" at ViewdidLoad . It work for me. Hope it useful . Thanks

**Comment by zahidshabbir** [comment]
> I have same this problem . I called chart.nodatatext = "text" at ViewdidLoad . It work for me. Hope it useful . Thanks

worked for me, Thanks man

**Comment by sparke16** [comment]
I am using a chart in a table view cell and found I needed to set the noData parameters in awakeFromNib() for them to properly reflected.

**Comment by MallikarjunaMore** [comment]
Hi Team, facing same problem, I am using PieChart in TabBarController, same noDataText is not displaying. I tried to place in viewdidload and viewwillappear both. Assist me.
statusPieChart.noDataText = "Something"

**Comment by sanketk2020** [comment]
You can set no data by using following code

'''

self.vwChart.centerAttributedText = nil
            self.vwChart.noDataText = "No Data"
            self.vwChart.noDataFont = UIFont.customFont(ofType: .medium, withSize: 14.0)
            self.vwChart.noDataTextColor = .black1D242C
            self.vwChart.data = nil
'''

Here **vwChart** is object of my chart view.
