### ISSUE TITLE
Increase space between bars with only one dataset and assign font for specific value and xAxis label

### ISSUE THREAD

**Issue by nico75005** [danielgindi/Charts#2184]
How can I assign a value and a label on xAxis with a specific font as it is on this chart with the latest value?

<img width="622" alt="screen shot 2017-02-22 at 14 21 31" src="https://cloud.githubusercontent.com/assets/1647328/23192826/6823f132-f90a-11e6-8385-223502bd23bb.png">

Thanks

**Comment by liuxuan30** [comment]
just override `drawLabels` and feed the font for specific ones.
