### ISSUE TITLE
Bar Chart with dual axis

### ISSUE THREAD

**Issue by vinodha88** [danielgindi/Charts#2188]
Hi ,

Is there a way I can use the ioscharts for the following requirment ,

A Stacked Negative Bar Chart with Dual Axis (sharing the same 0 line )
Bar chart with two data sets ( like mirror image)
One data set is positive and the other negative  , each data set having a different scales
But both bar charts should meet at the xaxis zero line and look like negative chart.

Following are the things I have tried ,

1.Created two positive (negating the negative values) data set each having dependency on different axis (one left and one right) sharing the same xaxis - for the following case , the graph does not look like a mirror 

2.Created one positive , one negative data set , each have different axis dependency sharing the same xaxis - since scales are different the graph is not looking like a mirror 

I am not sure if the above description was clear but in short bar chart with dual axis , one postive , one negative having the same zero axis .

Thanks.

**Comment by liuxuan30** [comment]
for dual axis, we just have left and right axis for y axis. X axis has top and bottom axis.
You can take a look at ChartsDemo for ideas
