### ISSUE TITLE
is two sided bar graph possible ?

### ISSUE THREAD

**Issue by hupptech** [danielgindi/Charts#2192]
I'm using this : Horizontal-BarChart
I want this charts to appear in 1st and 2nd quadrant both. does this chart support it ? if yes then how ?
attaching sample here 
![screen shot 2017-02-23 at 5 36 38 pm](https://cloud.githubusercontent.com/assets/13198352/23258563/d1c24b54-f9ee-11e6-9460-c15d8d4b6020.png)

**Comment by liuxuan30** [comment]
despite the menu list in the middle and the gradient bars, the horizontal bars are supported

**Comment by hupptech** [comment]
@liuxuan30  that is the only main question, how to implement those horizontal bars. forget about menu bar in between, just tell me the method in current sdk that can be used to implement this horizontal bar but remember, they have their y axis in middle at zero. on graph goes from y axis to right side and the other on left side. 
That is our main question. We can leave without gradient bars.

**Comment by liuxuan30** [comment]
You can take a look at ChartsDemo, I remember there are examples like yours
