### ISSUE TITLE
Hide labels - Pie chart

### ISSUE THREAD

**Issue by valeIT** [danielgindi/Charts#2193]
It's probably easy, but I can't figure out how to hide the labels in the pie chart (PieChartView):

<img width="158" alt="screen shot 2017-02-23 at 14 20 45" src="https://cloud.githubusercontent.com/assets/2276140/23260706/61ad4b2c-f9d3-11e6-8b4e-101de93140ea.png">

**Comment by petester42** [comment]
I believe it's `drawEntryLabelsEnabled` and set it to false.

**Comment by valeIT** [comment]
I tried that already, but they still show. Alternatively if there is a way to hide the ones smaller than a certain % so the doing overlap would be nice.

**Comment by mohuifen** [comment]
self.pieChartView.drawSliceTextEnabled = NO;
dataSet.drawValuesEnabled = NO

**Comment by tsaievan** [comment]
you have to set `dataSet.drawValuesEnabled` to `false`, only setting drawEntryLabelsEnabled false doesn't work
