### ISSUE TITLE
External lines - Pie Chart

### ISSUE THREAD

**Issue by valeIT** [danielgindi/Charts#2194]
1. Is there a way to have anything similar to this (the while curved lines), next to each section?
2. Is there a way to add spacing between each section like in the image?

<img width="126" alt="screen shot 2017-02-23 at 17 34 17" src="https://cloud.githubusercontent.com/assets/2276140/23268567/6e0753b6-f9ee-11e6-92cc-763558b4ec15.png">

**Comment by liuxuan30** [comment]
Well it's possible as long as you know how this lib works and this needs massive methods override and work.
