### ISSUE TITLE
Is it enable to keep the origin visible X Range when I appended more data 

### ISSUE THREAD

**Issue by aelam** [danielgindi/Charts#2198]
For example 
1. a DataSet with XIndex from 0 to 100, Set axis Range like below then I can see all data in Chart 
```
 _chartView.xAxis.axisMinimum = 0;
 _chartView.xAxis.axisMaximum = 100;
```
2. I append a group of data with XIndex from -100 to -1 to this DataSet. Then I change the XAxis Range  like the below 
```
 _chartView.xAxis.axisMinimum = -100;
 _chartView.xAxis.axisMaximum = 100;
```
here is the problem 
If I change axisMinimum, axisMaximum like the step 2, I can zoom in/out, move left/right. But I lost the origin visible range 
If I don't change I can keep the origin visible range, but the data from -100 to -1 won't be enable to scroll to be seen.

My current solution is keeping the origin  axisMinimum, axisMaximum the origin values , when I scroll the chart, I change the axisMinimum, axisMaximum at the same time to keep the xAxisRange not changed. 

I'm wondering if the best way is modify the matrix in the step 2 ?
I also notice that there are two not used ivar. are they used to track the origin position?
```
    fileprivate var _autoScaleLastLowestVisibleX: Double?
    fileprivate var _autoScaleLastHighestVisibleX: Double?
```

**Comment by liuxuan30** [comment]
I feel that you changed the data, and then change the chart property, and then you should call 'notifyDataSetChanged()`, or you should set axisMaximum and then update the data to make sure the calculation reflect correctly. Can this solve your issue?

**Comment by aelam** [comment]
The main point is move to the origin place after appended points. I've tried like the step 2 and moveView and it works. I hope I am using the API correctly
