### ISSUE TITLE
Charts not showing on tvOS

### ISSUE THREAD

**Issue by samtout** [danielgindi/Charts#2201]
I added `pod 'Charts'` into my Podfile for my tvOS target and I'm able to add a UIView and change its type to BarChartView and create an outlet for it after I `import Charts` in the ViewController swift code and add test entries in the code, all that no problem. But when I run it in the Apple TV simulator, the barView doesn't even appear. I tested adding other controls and they do appear.

**Comment by samtout** [comment]
I guess as experienced as we get, the delegate = self tends to be a continuous challenge to remember. Never mind, for the benefit of others I left the question and answer in case you run into this problem. However, I would suggest adding this to the sample provided under the following link since it's missing: https://medium.com/@skoli/using-realm-and-charts-with-swift-3-in-ios-10-40c42e3838c0#.uq60b4r4w

**Comment by liuxuan30** [comment]
thanks, closing.
