### ISSUE TITLE
Legend vertical offset

### ISSUE THREAD

**Issue by valeIT** [danielgindi/Charts#2202]
Is there a way to have a vertical (y-)offset for the legend for the PieChart? I have it top-left aligned and I wanted to add some spacing from the top, is it possible?

**Comment by liuxuan30** [comment]
```swift
    /// The offset this component has on the x-axis
    /// **default**: 5.0
    open var xOffset = CGFloat(5.0)
    
    /// The offset this component has on the x-axis
    /// **default**: 5.0 (or 0.0 on ChartYAxis)
    open var yOffset = CGFloat(5.0)
```
This is found in ComponentBase, and legend honors it.
Can you try?

**Comment by valeIT** [comment]
It works, thanks. Could have also thought of setting it to centered instead of top. ;)
