### ISSUE TITLE
My ipa(used Charts) is 40M ;another ipa(unused Charts) is 13M,how to be sliming???

### ISSUE THREAD

**Issue by Kaelzzs** [danielgindi/Charts#2203]
My ipa(used Charts) is 40M ;another ipa(unused Charts) is 13M.
Shocked！
How to reduce its weight?

**Comment by aelam** [comment]
Packed the swift library inside ?

**Comment by liuxuan30** [comment]
do your ipa without Charts use swift?
Most of the size is swift lib. Check https://github.com/danielgindi/Charts/issues/2015

**Comment by Kaelzzs** [comment]
yes ,my project (used OC), Most of the size of ipa is swift lib.What shall I do?

**Comment by liuxuan30** [comment]
Just let it be and wait for Apple to integrate the lib. There's nothing you can do
