### ISSUE TITLE
Line Graph is not showing line on the Chart

### ISSUE THREAD

**Issue by shivang2902** [danielgindi/Charts#2209]
Hi @danielgindi , @liuxuan30 
Sorry for disturbing you again n again but it requires your attention
what i am doing is on loading the view controller i am hitting an API and after the successful response  i am populating the Chart with the values. But in my case the line graph is being populated 1 in 10 attempts

I am adding my code here plss have a look guys
`
      
       import Foundation
       import Charts
       //MARK: - Constants
       let axisColor = UIColor(hex : "#D0C0C1")
       let bgColor = UIColor.white.withAlphaComponent(0.17)
       let yAxisMaximum = 100.0
       let yAxisMinimum = 0.0
       let noDataText = ""
       let dataSetLineWidth : CGFloat = 2.0
       let dataSetCircleRadius : CGFloat = 0.0
       let dataSetCubicIntensity : CGFloat = 0.1

       //MARK: - Chart Initial Setup
       extension LineChartView {
    
    /* -------------- Line chart initial setup ----------------*/
    func initialSetUp() {
        
        self.rightAxis.drawLabelsEnabled = false
        self.legend.enabled = false
        self.chartDescription?.enabled = false
        self.xAxis.gridColor = axisColor
        self.xAxis.axisLineColor = axisColor
        self.xAxis.labelTextColor = axisColor
        self.leftAxis.gridColor = axisColor
        self.leftAxis.axisLineColor = axisColor
        self.leftAxis.labelTextColor = axisColor
        self.rightAxis.gridColor = axisColor
        self.rightAxis.axisLineColor = axisColor
        self.rightAxis.labelTextColor = axisColor
        self.xAxis.labelPosition = .bottom
        self.drawGridBackgroundEnabled = true
        self.drawBordersEnabled = true
        self.gridBackgroundColor = bgColor
        self.borderColor = axisColor
        self.leftAxis.axisMaximum = yAxisMaximum
        self.leftAxis.axisMinimum = yAxisMinimum
        self.leftAxis.labelCount = 5
        self.leftAxis.axisMaximum = 100.0
        self.leftAxis.axisMinimum = 0.0
        self.leftAxis.drawZeroLineEnabled = false
        self.setScaleEnabled(false)
        self.noDataText = noDataText
        self.rightAxis.drawZeroLineEnabled = false
        self.rightAxis.enabled = false
    }
    }

       //MARK: - Data Set Initial Setup
       extension LineChartDataSet {
    
    /* -------------- Line chart data set initial setup ----------------*/
    func initialSetUp() {
        
        self.drawCirclesEnabled = false
        self.drawCircleHoleEnabled = false
        self.setColor(UIColor.white)
        self.mode = .cubicBezier
        self.drawCirclesEnabled = false
        self.lineWidth = dataSetLineWidth
        self.circleRadius = dataSetCircleRadius
        self.drawHorizontalHighlightIndicatorEnabled = false
        self.cubicIntensity = dataSetCubicIntensity
        self.drawValuesEnabled = false
    }
    }

        **------------------- function from View Controller ---------------------------** 

       /* -------------- Setting Up of Chart view ----------------*/
    func setUpChart(arrayGraphPoints : [GraphModel]?) {
      
        guard let validArrayGraph = arrayGraphPoints else {
            self.lblNoGraphData.isHidden = false
            return }
        
        self.prepareChartData(from: validArrayGraph) { (dataEntries, isNoGraphDataHidden) in
          
            self.lineChartView.initialSetUp()
            self.lblNoGraphData.isHidden = isNoGraphDataHidden
            let lineChartDataSet = LineChartDataSet(values: dataEntries, label: "")
            lineChartDataSet.initialSetUp()
            var dataSets = [IChartDataSet]()
            dataSets.append(lineChartDataSet)
            let lineChartData = LineChartData(dataSets: dataSets)
            lineChartView.data = lineChartData
            self.lineChartView.notifyDataSetChanged()
        }
    }
    
    func prepareChartData(from arrayGraph : [GraphModel], onCompletion : (_ dataEntries : [ChartDataEntry], _ shouldHideNoGraphLbl : Bool)->()) {
        
        var dataEntries: [ChartDataEntry] = []
        var isNoGraphDataHidden = false
        for (i,point) in arrayGraph.enumerated() {
            
            let dateFromTimestamp = point.time?.toHour
            if point.percentageFilled ?? 0 > 0 {
                isNoGraphDataHidden = true
            }
            let x = Double(dateFromTimestamp ?? "0") ?? 0.0
            let y = Double(i * 10) // point.percentageFilled ?? 0
            let dataEntry = ChartDataEntry(x: x, y: y)
            dataEntries.append(dataEntry)
            if i == arrayGraph.count - 1 {
                onCompletion(dataEntries, isNoGraphDataHidden)
            }
        }
    }

`

**Comment by shivang2902** [comment]
toHour function used above

`extension Int {
    
    func toBool () ->Bool? {
        return self == 1
    }
    
    private func formatType(form: String) -> DateFormatter {
        let dateFormatter = DateFormatter()
        dateFormatter.locale = Locale.current
        dateFormatter.dateFormat = form
        return dateFormatter
    }
    var dateFull: Date {
        return Date(timeIntervalSince1970: Double(self))
    }
    var toHour: String {
        return formatType(form: DateFormat.hh.rawValue).string(from: dateFull)
    }
    var toDay: String {
        return formatType(form: DateFormat.mmddyyyy.rawValue).string(from: dateFull)
    }
}`

**Comment by liuxuan30** [comment]
Don't abuse using @. We will answer when someone has time.
I don't fully understand what's your issue.
If you can't show a line chart, just take a look at ChartDemo first and follow it.
Posting lots of code don't help, as I have no idea what's it for and no time to walk through line by line.
