### ISSUE TITLE
How can I have these values in positive? Thanks.

### ISSUE THREAD

**Issue by HuppDevelopers** [danielgindi/Charts#2212]
![screen shot 2017-03-02 at 1 56 06 pm](https://cloud.githubusercontent.com/assets/26135696/23499506/6ab23f28-ff52-11e6-91b3-32b2c736ee38.png)

**Comment by aelam** [comment]
Set your formatter for xAxis

**Comment by liuxuan30** [comment]
Take a look at ChartsDemo
