### ISSUE TITLE
why the zero can't show at the first

### ISSUE THREAD

**Issue by Jamie-Ling** [danielgindi/Charts#2218]
![001](https://cloud.githubusercontent.com/assets/10615007/23550539/780cf5e6-004c-11e7-98c1-ea747a2666d6.jpg)
![002](https://cloud.githubusercontent.com/assets/10615007/23550548/80feb0d6-004c-11e7-9e99-70071bfb2972.jpg)

**Comment by liuxuan30** [comment]
seems because you have negative value...
or you are using bezier, however you should use horizontal bezier

**Comment by Jamie-Ling-iOS** [comment]
the problem is solved, thank you
