### ISSUE TITLE
Bar chart with limit line for each Bar

### ISSUE THREAD

**Issue by Mayur-Bendale** [danielgindi/Charts#2219]
@danielgindi  I am trying to implement Bar chart with limit line for each Bar. Can someone please help me how should I achieve this. I have to also do all rounded corners for bar.  #Please go through the attached screenshot which I have to achieve.
![bar chart with limit line for each bar](https://cloud.githubusercontent.com/assets/18009358/23552216/bca15500-0040-11e7-9d87-1cf8e698de39.JPG)

**Comment by liuxuan30** [comment]
there is rounded bar PR, you acn take a look.
As for the limit line, when drawing the barRect, you should be able to know its width, and you already know the y point value, so should be doable by yourself

**Comment by Mayur-Bendale** [comment]
@liuxuan30 
Thanks for your input. I will try those things.
