### ISSUE TITLE
Horizontal Bar Chart lines not visible with two BarChartDataSet in chart data

### ISSUE THREAD

**Issue by devilknight26** [danielgindi/Charts#2220]
I am trying to show horizontal bar chart with two datasets and but when I run my code with shows the only text of lines but lines are not visible. I can see text animate but no lines.
This is my code:
`chartView.noDataTextColor = .orange`
`chartView.chartDescription?.text = ""`
`let dataSet = getDataSet(budget: totalBudget, spending: totalSpend)`
`let chartData = BarChartData(dataSets: dataSet)`
`chartData.setValueTextColor(.white)`
`chartView.data = chartData`

This is my getDataSet Method:
        func getDataSet(budget: Double, spending: Double) -> [BarChartDataSet] {
        
        var budgetEntryList = [BarChartDataEntry]()
        let budgetEntry = BarChartDataEntry(x: budget, y: budget)
        budgetEntryList.append(budgetEntry)
        
        let budgetDataSet = BarChartDataSet(values: budgetEntryList, label: "Total Budget")
        budgetDataSet.setColor(.orange)
        
        var spendingEntryList = [BarChartDataEntry]()
        let spendEntry = BarChartDataEntry(x: spending, y: spending)
        spendingEntryList.append(spendEntry)
        
        let spendingDataSet = BarChartDataSet(values: spendingEntryList, label: "Total Spending")
        spendingDataSet.setColor(.green)
        
        return [budgetDataSet,spendingDataSet]
        
        }

<img width="358" alt="screen shot 2017-03-03 at 7 16 00 pm" src="https://cloud.githubusercontent.com/assets/7988401/23554329/6c54e91c-0046-11e7-9b2e-7b831e7a68b9.png">

**Comment by liuxuan30** [comment]
Take a look at ChartsDemo, there are examples already.
