### ISSUE TITLE
Default backgroundColor (nil) displays as black instead of clear.

### ISSUE THREAD

**Issue by cpboyd** [danielgindi/Charts#2222]
As the title states, the default backgroundColor of a view is nil, which shows in the Storyboard as transparent.

It seems counter-intuitive that this would be `UIColor.black` rather than `.clear`

Obviously, it's easy to work-around with a simple `chartView.backgroundColor = .clear`.

However, it seems like the "default" should match other views, which use a clear color.

**Comment by liuxuan30** [comment]
Just saw
```swift
    public override init(frame: CGRect)
    {
        super.init(frame: frame)

		#if os(iOS)
			self.backgroundColor = NSUIColor.clear
		#endif
        initialize()
    }
```
when init, it will be clear

**Comment by cpboyd** [comment]
@liuxuan30 
Hmm.  It doesn't seem to do that when instantiated via a Storyboard.

Perhaps this is relevant?
http://stackoverflow.com/questions/8373176/how-is-view-initialized-when-loaded-via-a-storyboard

Maybe this init should also be called from initWithCoder, e.g.:
```swift
required init?(coder: NSCoder) {
		super.init(coder: coder)
		#if os(iOS)
			self.backgroundColor = NSUIColor.clear
		#endif
}
```

**Comment by liuxuan30** [comment]
I had a PR for this, move the color setter to initialize()

**Comment by liuxuan30** [comment]
@danielgindi please review this, I am not sure why it's just seen in `initWithFrame()`

**Comment by euri16** [comment]
I just updated to version 3.0.2 and still have a default black background behind my chart. I added a UIView in storyboard and set the class to `LineChartView`, modules `Charts`, what I have to do to remove that black background?

I also have tried doing this:

`self.lineChart.backgroundColor = .clear`

**Comment by liuxuan30** [comment]
This change is not in 3.0.2. Pull from master
