### ISSUE TITLE
Legend vertical offset for horizontally aligned legends

### ISSUE THREAD

**Issue by slxl** [danielgindi/Charts#2223]
Trying to offset the legend from chart view using:

`chartLegend.yOffset = 36`

and instead of margin between chart and legend I got an emptiness below legend with desired value [of 36] while legend keeps sticking to chart view with no margin at all

<img width="543" alt="2017-03-05 00 04 48" src="https://cloud.githubusercontent.com/assets/3089985/23580617/aadf9f50-0137-11e7-8e9d-7698bb788949.png">

is it a bug or am I doing it wrong?
Thanks!

**Comment by liuxuan30** [comment]
I can barely understand...
you set 36 y offset, and it did the job.

**Comment by slxl** [comment]
@liuxuan30 actually I expected a gap between chart and legend, bcs curent (external margin) could be achieved by using of just a different frame for chart

**Comment by liuxuan30** [comment]
oh, please take a look at `open func renderLegend(context: CGContext)` for how the position is calculated. It has been a while and I don't remember how it calculates.
