### ISSUE TITLE
Legend Label problem when the device changes orientation

### ISSUE THREAD

**Issue by mirceabarba** [danielgindi/Charts#2224]
Hi,
I am trying to remove one entry from the legend and I've used the following lines of code:
scatterChartView.data = data
scatterChartView.legend.entries.remove(at: 1)

This works the first time the Chart is rendered, but if i switch the orientation of my iPhone the legend displays all the entries.

In the pictures you can see that the first one does not show the "Cluster" DataSet, but in the second one it appears.

Can you maybe tell me what I am doing wrong?

Thank you very much

![first](https://cloud.githubusercontent.com/assets/22076194/23586165/f596aa40-018f-11e7-922a-c947672148da.PNG)
![after](https://cloud.githubusercontent.com/assets/22076194/23586166/f5bc17b2-018f-11e7-88cd-b9f1cade188e.PNG)

**Comment by mirceabarba** [comment]
Worked around the problem by creating custom Legend.

**Comment by liuxuan30** [comment]
My theory is you manually removed one legend entry, however the data entry is still there. When rotating, the legend is re-calculated, so it adds back the removed legend entry.
You should be careful when doing this unless you know how it works.
