### ISSUE TITLE
demo can not run

### ISSUE THREAD

**Issue by L-Jovi** [danielgindi/Charts#2227]
I follow [this issue](https://github.com/danielgindi/Charts/issues/2066) and finish carthage step, but I also encounter below error as image show.

![image](https://cloud.githubusercontent.com/assets/7262199/23612952/55d2affc-02b8-11e7-916a-b8497d92f6b8.png)

how should I fix it?

thanks for your time.

**Comment by liuxuan30** [comment]
just read README

**Comment by L-Jovi** [comment]
@liuxuan30  thanks for your reply, I already follow README, but I also get `not found` issue after

`carthage checkout`,

maybe I did something wrong, wound you mind provide some suggestion for me?

thanks for your time.

**Comment by liuxuan30** [comment]
it can't be... you sure you downloaded and installed Realm? Can you see ChartsRealm files?

**Comment by L-Jovi** [comment]
@liuxuan30  thanks for your patience,

I ensure execute `carthage checkout` and download Realm framework, and I could find it in my project link item.

![image](https://cloud.githubusercontent.com/assets/7262199/23781752/69b28824-058a-11e7-9d78-d9d94cd87a32.png)

from README, I don't know how to fix the dependency of `import RealmSwift`

![image](https://cloud.githubusercontent.com/assets/7262199/23781779/946045e8-058a-11e7-9dbd-245351787fe6.png)

**Comment by liuxuan30** [comment]
hmm.. Do you install Realm Swift? I am not sure either. However I used to run carthage bootstrap to install. Never tried check out. But it should install RealmSwift for you..

**Comment by L-Jovi** [comment]
@liuxuan30  thanks again for your reply :)

I ensure that `RealmSwift` not exist after `carthage checkout`, I just see Realm framework, and I also try your idea `carthage bootstrap` which takes a long time to finish download, and I see `RealmSwift` framework!

![image](https://cloud.githubusercontent.com/assets/7262199/23839749/35c8884e-07db-11e7-9440-01c399daf8c2.png)

then I drag them to __Embedded Binaries__ without __copy if needed__

![image](https://cloud.githubusercontent.com/assets/7262199/23839793/6521cb64-07db-11e7-9a02-f7605115efb4.png)

I clean and compile project again, but also encounter some __not found__ error like below image show.

![image](https://cloud.githubusercontent.com/assets/7262199/23839738/215df2b8-07db-11e7-852b-7edf253395ac.png)

I'm not ensure that I'm on right workflow to build, but how should I fix it?

regards.

**Comment by liuxuan30** [comment]
That's weird, you have too many Realm framework
That's what mine looks like:
![image](https://cloud.githubusercontent.com/assets/4375169/23882520/19b06b06-089c-11e7-8ce1-1a43969dc480.png)

However in project settings, I just have ChartsRealm:
![image](https://cloud.githubusercontent.com/assets/4375169/23882474/c96a3780-089b-11e7-8654-0f5cb5287d17.png)

I suggest you just clean it up and start it over again.

**Comment by elanpang** [comment]
I think the issue because "Incompatible Swift version - framework was built with 3.0.1 and the local version is 3.0.2.", so the build script can't find the swift file in the build folder of carthage.

How to fix it for me ?

I opened the Cartfile and Cartfile.resolved files, change 2.1.1 to 2.4.4 , then carthage checkout  again, it works for me.

tips:
ReaIm 2.4.4  at 17.03.15

**Comment by liuxuan30** [comment]
@petester42 do you think we could delete Cartfile.resolved to let Carthage generate it up to date?

**Comment by petester42** [comment]
That's an option. I'll look into it when I have time.

**Comment by AdrianBinDC** [comment]
@L-Jovi I've encountered the same problem. I'm just going to install the CocoaPod and look at the code in the demo project. I wish it were easier to run the demo project without having to jump through a bunch of installation hoops. Once I installed Carthage, I ran into a bunch of Realm warnings.

**Comment by L-Jovi** [comment]
@AdrianBinDC  Carthage is a bit different with CocoaPod, the latter more automatic.

if you encounter the same issue, I suggest that you could notice the solution from __@elanpang__ , although I also failed :(

**Comment by petester42** [comment]
seems like ignoring the cartfile.resolved is not a great idea. #2199 should fix demo issues. if not then clean the project and try again

**Comment by lidaren** [comment]
hi, I download the new project, but demo can not run...“No such module 'RealmSwift'”.what's problem?

**Comment by liuxuan30** [comment]
@lidaren read README

**Comment by lidaren** [comment]
@liuxuan30 thanks, Due to the error:Incompatible Swift version
