### ISSUE TITLE
Custom xAxisRenderer

### ISSUE THREAD

**Issue by quaddef** [danielgindi/Charts#2230]
I'm trying to set my custom xAxisRenderer like this:

      class CustomXAxisRenderer: XAxisRenderer{
      }

      chart.xAxisRenderer = CustomXAxisRenderer(viewPortHandler: chart.viewPortHandler, xAxis: chart.xAxis, transformer: Transformer(viewPortHandler: chart.viewPortHandler))

But after that I can't see any xAxis labels or grid lines, because of incorrect valueToPixelMatrix. What is correct way to set custom renderer?

**Comment by quaddef** [comment]
Ok, I solved it.

      chart.xAxisRenderer = CustomXAxisRenderer(viewPortHandler: chart.viewPortHandler, xAxis: chart.xAxis, transformer: transformer: chart.getTransformer(forAxis: .left))

**Comment by hernanarber** [comment]
VERY HELPFUL! Thanks
