### ISSUE TITLE
how to join XAxisLabel in MultipleBarChart under every Bar

### ISSUE THREAD

**Issue by TomWang1** [danielgindi/Charts#2232]

**Comment by liuxuan30** [comment]
by default, not every label will be displayed due to space reason. If you really want to do so, you can override `computeAxisValues` to feed your own

**Comment by TomWang1** [comment]
thanks    ,now   i want to add control everyBar'color  ,what should i do

**Comment by liuxuan30** [comment]
there are colors already..
