### ISSUE TITLE
Set vertical legend

### ISSUE THREAD

**Issue by CosmicYogi** [danielgindi/Charts#2233]
Is it possible to set vertical legend I mean I want to display Speed , Distance and some other properties in different graphics on the Vertical axis (y-axis) in vertical alignment i.e.., text from top to bottom.
I am adding the screenshot of the code I am trying and result I am getting below.

<img width="313" alt="screen shot 2017-03-08 at 9 38 50 pm" src="https://cloud.githubusercontent.com/assets/7416058/23712446/f4a4a6e4-0448-11e7-9f05-bce40ee4ee2d.png">
<img width="404" alt="screen shot 2017-03-08 at 9 39 00 pm" src="https://cloud.githubusercontent.com/assets/7416058/23712453/fa8fb90e-0448-11e7-82b0-484e8d28d478.png">

as you can see in the image that the legend text i.e.., Distance(km) is appearing on the left of graph that is fine but it's appearing horizontally the thing is I want to make it appear vertically.
How would it be possible if I am not wrong then I had tried everything.

**Comment by liuxuan30** [comment]
I don't understand, are you saying Orientation.vertical does not work?

**Comment by CosmicYogi** [comment]
Actually what my intension was - https://github.com/danielgindi/Charts/issues/35
I wanted to make that legent verticle so I can somehow make it look like a label to Y-Axis
I searched all the issues and finally found the one I had listed above is what I actually wanted to say.

**Comment by liuxuan30** [comment]
I see. However it's not supported yet.. I will try find some time to do that.

**Comment by CosmicYogi** [comment]
@liuxuan30 would it be okay if I send a pull request to do that?
I mean I would try to do that.
Do you people accept pull requests?

**Comment by liuxuan30** [comment]
Of course! Just remember it might take a long time, due to everyone is busy and have to port to Android portion as well..
But we definitely needs help and PRs

I used to develop this for my previous company, however in terms of named axis feature, I have to think about every x and y axis (bottom and top, left and right), support full label rotation (not just 0 and 90 degrees rotation) that's where I paused
