### ISSUE TITLE
Tableview stuttering when rendering a pie chart

### ISSUE THREAD

**Issue by dimitryvin** [danielgindi/Charts#2234]
I thought initially the stuttering was coming from the fact that I was processing the chart data in the table view cell from JSON but even after preprocessing my data in the view controller on load, I'm still suffering from scroll performance when rendering a pie chart in my tableview. 

I'm only working with a dataset smaller than 10 points.

**Comment by yazankhayyat** [comment]
Are you still experiencing this difficulty?
