### ISSUE TITLE
Convert to Current Swift Syntax

### ISSUE THREAD

**Issue by ccabanero** [danielgindi/Charts#2242]
When using version 3.0.1 in Xcode 8.2.1 I receive the following warning: "Convert to Current Swift Syntax? The target contains source code developed with an earlier version of Swift"

Charts was installed with Cocoa Pods using:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'charts' do
 pod 'Charts', '~> 3.0.1'
end

Thanks for the great work!

**Comment by liuxuan30** [comment]
this has nothing to do with this library. It's already swift 3 crafted
