### ISSUE TITLE
Problems with creating CombinedChart (Line + grouped BarChart) in Swift 3.0

### ISSUE THREAD

**Issue by MargaretaKusan** [danielgindi/Charts#2243]
I am trying to draw a combined chart that will display a grouped bar chart and a line chart on one chart. I can make a bar chart, and it works as expected, however when I try to make a Combined chart (add the lineChart in the chart) nothing shows except for the xaxis labels?

    @IBOutlet weak var combChartView: CombinedChartView!

    func setChart(dataPoints: [String], valuesUser: [Double], valuesCommunity: [Double], average: Double) {
        
        self.combChartView.chartDescription = nil
        self.combChartView.doubleTapToZoomEnabled = false
        self.combChartView.pinchZoomEnabled = false
        self.combChartView.drawGridBackgroundEnabled = false
        self.combChartView.rightAxis.enabled = false
        self.combChartView.drawValueAboveBarEnabled = false
        var dataEntriesUser: [BarChartDataEntry] = []
        var dataEntriesCommunity: [BarChartDataEntry] = []
        var dataEntriesAverage: [ChartDataEntry] = []
        
        //legend
        let legend = barChartView.legend
        legend.enabled = true
        legend.horizontalAlignment = .right
        legend.verticalAlignment = .top
        legend.orientation = .horizontal
        legend.drawInside = false

        // xaxis
        let xAxis = combChartView.xAxis
        xAxis.drawLabelsEnabled = true
        xAxis.drawGridLinesEnabled = false
        xAxis.labelCount = dataPoints.count
        xAxis.valueFormatter = IndexAxisValueFormatter(values: names)
        xAxis.labelPosition = .bottom
        xAxis.labelFont = UIFont.init(name: "HelveticaNeue", size: 9.0)!
        xAxis.labelTextColor = UIColor.black
        xAxis.centerAxisLabelsEnabled = true
        xAxis.axisMinimum = 0.0
        xAxis.axisMaximum = Double(2 * dataPoints.count) + 0.5
        
        // yaxis
        let yaxis = combChartView.leftAxis
        yaxis.spaceTop = 0.35
        yaxis.axisMinimum = 0
        yaxis.drawGridLinesEnabled = true
        
        for i in 0..<9 {
            var dataEntry = BarChartDataEntry(x: Double(i), y: valuesUser[i])
            dataEntries1.append(dataEntry)
            dataEntry = BarChartDataEntry(x: Double(i), y: valuesCommunity[i])
            dataEntries2.append(dataEntry)
            dataEntries3.append(ChartDataEntry(x: Double(i), y: average))
        }
        
        let chartDataSet3 = LineChartDataSet(values: dataEntries3, label: "Average")
        let chartDataSet1 = BarChartDataSet(values: dataEntries1, label: "You")
        let chartDataSet2 = BarChartDataSet(values: dataEntries2, label: "Community")
        
        chartDataSet1.setColor(UIColor.green)
        chartDataSet2.setColor(UIColor.blue)
        chartDataSet3.setColor(UIColor.black)

        let barData = BarChartData(dataSets: [chartDataSet1, chartDataSet2])
        
        let lineData = LineChartData()
        lineData.addDataSet(chartDataSetAverage)
        
        let groupSpace = 0.27
        let barSpace = 0.01
        let barWidth = 0.8
        
        barData.groupBars(fromX: 0, groupSpace: groupSpace, barSpace: barSpace)
        barData.setDrawValues(false)
        barData.barWidth = barWidth
        
        let data: CombinedChartData = CombinedChartData()
        data.lineData = lineData
        data.barData = barData
        
        self.combChartView.data = data
        self.combChartView.notifyDataSetChanged()
    }

Btw, thanks for your work :)

**Comment by liuxuan30** [comment]
`self.combChartView.data = data` will call `self.combChartView.notifyDataSetChanged()`, so remove it to gain performance

For grouped bars, check out ChartsDemo, there is already example

**Comment by MargaretaKusan** [comment]
Thanks for advice, I removed the `self.combChartView.notifyDataSetChanged()`. The chart is still not working though. Yes, I checked out ChartsDemo earlier and I already said that grouped bar chart is working fine with the same data that I am sending to combined bar chart. For some reason nothing works when I add the line chart and change bar chart to combined.

**Comment by liuxuan30** [comment]
well ChartsDemo already supports grouped bars plus lines and other charts, you should look at the demo to figure out what's wrong.

**Comment by MargaretaKusan** [comment]
Yes, I have taken a look at ChartsDemo-OSX earlier, for swift 3.0 there is no example for combined chart. Separately, grouped bar chart and line chart are working fine so there is not much help there, and the objective C example in ChartsDemo I used as a reference to produce the code I posted above.

**Comment by thierryH91200** [comment]
These 2 lines are incorrect
 ```
   let lineData = LineChartData()
    lineData.addDataSet(chartDataSetAverage)

```
chartDataSetAverage Is never initialized

it would be better
```
    let lineData = LineChartData()
    lineData.addDataSet(chartDataSet3)

```


I think there is a small improvement

 ```
               let groupSpace = 0.27
                let barSpace = 0.01
                let barWidth = 0.8
```

        // x2 dataset
        // (0.8 + 0.01) * 2 + 0.27 > 1.00 -> interval per "group"

 Take that as values for example
```
      let groupSpace = 0.06
        let barSpace = 0.02
        let barWidth = 0.45

```
        // x2 dataset
        // (0.45 + 0.02) * 2 + 0.06 = 1.00 -> interval per "group"

**Comment by MargaretaKusan** [comment]
@thierryH91200  thanks for advice! :) The groupSpace values do seem confusing to me. 
However "chartDataSetAverage" wasn't the problem, when I copied the code here I renamed datasets for the code to be more readable, and I forgot to rename at that particular place :) I will edit the code.
