### ISSUE TITLE
Multiline axis labels are cut off

### ISSUE THREAD

**Issue by claudioredi** [danielgindi/Charts#2244]
Thanks for writing this library! It's a really great component :)

I'm having an issue with multiline labels. Depending on the amount of data to be shown on x axis, labels are cut off or not. Here you have two examples

**Working Labels**
<img width="371" alt="2017-03-14_1911" src="https://cloud.githubusercontent.com/assets/1825057/23924942/99ac9c04-08eb-11e7-97b1-85766b046212.png">

**Non Working Labels**
<img width="369" alt="2017-03-14_1913" src="https://cloud.githubusercontent.com/assets/1825057/23924939/979796ee-08eb-11e7-8f91-b02fb8d96d70.png">

Data is exactly the same, on second chart I limited the amount of X items to be shown. If I tap on the second chart, it gets fixed but points and labels still unaligned.

<img width="373" alt="2017-03-14_2002" src="https://cloud.githubusercontent.com/assets/1825057/23926116/3e0beec6-08f1-11e7-8791-9b4fc5a1bb53.png"> 

Is there any way to be sure that label won't be ever cut off? I was looking a way to force the height of the chart to be sure it's always the same but couldn't find any.

Also, I see that on the first chart labels and points are vertically aligned while on the second they are not. Is it possible also to force 1 point -> 1 label and make them aligned vertically?

**Comment by liuxuan30** [comment]
Have you changed any library code? Or just using world wrapping feature? It looks like the offset is wrong.
For aligning - by default x axis labels are not the same as data values, so no guarantee, unless you return x axis values the same as data values
I don't know why your first image is aligned so well

**Comment by claudioredi** [comment]
@liuxuan30: thanks for your answer. I haven't changed anything on the library. I'm using value formatter to convert numbers into that multiline string you see on X axis (words separated by "\n")

Not sure what you mean with "unless you return x axis values the same as data values". I really need X axis labels to be aligned to points, otherwise my chart make no sense. Could you please clarify?

I could add some code if necessary.

**Comment by claudioredi** [comment]
I Resolved the alignment problem using granularity property = 1. I still have the issue of labels being cut off. On double tap problem gets resolved as you can see on this video

https://www.screencast.com/t/g7G00TogO4dX

**Comment by claudioredi** [comment]
Fixed the cutt off problem. I was calling `_mChart.SetVisibleXRangeMaximum(4);` (this is Xamarin, C#) before defining the chart frame. Moving that line later in my code fixed the label issue. This can be closed.

Thanks.

**Comment by liuxuan30** [comment]
glad to close :)
