### ISSUE TITLE
Xaxis Label value in range (2.5-5.0,5.0-7.5)

### ISSUE THREAD

**Issue by anurag1991** [danielgindi/Charts#2246]
Hi I am trying to achieving like this 
![screen shot 2017-03-15 at 12 39 34 pm](https://cloud.githubusercontent.com/assets/8223368/23937236/78fdaf34-097c-11e7-8507-c34598547607.png)

But i am not able to create xaxis label value.

**Comment by liuxuan30** [comment]
use formatter

**Comment by anurag1991** [comment]
Hi Thanks , i used formatter for that and its working very Cool.
