### ISSUE TITLE
Highlight particular X and Y coordinations in the iOS charts

### ISSUE THREAD

**Issue by aprabhakar-eoxys** [danielgindi/Charts#2250]
**Hello World..!!**
I am very new to swift. I am trying to bring the exact output as I attached Image.
I am using iOS charts API. I brought up the line charts with all the options, but I need to highlight only the **_particular X Y coordinations which is tappable_** (user clickable)
Anyone please guide me if you can. 

Thanks in advance.
![metricgraphcropped](https://cloud.githubusercontent.com/assets/14069723/23983024/815aada6-0a37-11e7-8262-8630304a4330.png)

**Comment by liuxuan30** [comment]
just take your time and check charts demo. lien chart already support highlight when tapping on the data entry
