### ISSUE TITLE
How to include a gap between data points & lines

### ISSUE THREAD

**Issue by JohnW808** [danielgindi/Charts#2251]
I'm using iOS-Charts with Swift to draw line charts, and I'm looking for a way to place a gap between the data points (circles) and the lines themselves.

Something like this: [Example](https://i.imgur.com/tEgcZ2L.png)

I've tried playing around with some values under the drawLinear section of LineChartRenderer.swift, but I don't know enough about Core Graphics to do anything useful.

Having a white outline for the circles is unfortunately not an option, since I'm displaying multiple datasets with images containing transparent layers, and the datasets need to be able to overlap (as in the example image)

Apologies if this is was not the right place to ask this, I'm new here. Any help would be greatly appreciated :)

**Comment by liuxuan30** [comment]
I used to do something similar. Just take a look at 
```swift
    /// The radius of the drawn circles.
    open var circleRadius = CGFloat(8.0)
    
    /// The hole radius of the drawn circles
    open var circleHoleRadius = CGFloat(4.0)
```
and the `drawCircles()` function to know how it applies those radius.
