### ISSUE TITLE
Dynamic generate Int values for axis

### ISSUE THREAD

**Issue by LiborZ** [danielgindi/Charts#2253]
Hi, I like this library but I am not sure how to fix my problem. It's better if I describe it with image:
![screenshot 2017-03-17 at 08 38 13](https://cloud.githubusercontent.com/assets/620987/24033470/51991e2a-0aed-11e7-9073-d7e0c0202ace.png)

I would like to have integers in x and y axis. I can change it by setting valueFormatter to change double value to integer value and then to string. Thats what I have done for y axis. But the problem is that originally values generated are 1.7,  2.3 etc. so there could be same values twice or more times and line chart points aren't in same level as y or x axis.

How can I fix it? How can I generate only integer values for axis?

**Comment by liuxuan30** [comment]
take a look at `computeAxisValues()`, where generate the axis values. You can override this method, or tweak the original method like `forceLabelEnabled` feature to get what you want.
