### ISSUE TITLE
Custom yAxis values

### ISSUE THREAD

**Issue by ukmarn** [danielgindi/Charts#2254]
I was searching in issues but couldn't find anything similar to this.
So I have a chart, which has 2 yAxis - one on left and one on right. Left axis can show values from 0 - 360. Right axis can show values from 0 to 100.
Here is a screenshot of what am I trying to achieve - right axis is on the half of the left one.

![screenshot 2017-03-17 11 33 34](https://cloud.githubusercontent.com/assets/20947571/24039727/82791766-0b06-11e7-9b57-f60dab71f145.png)

Current code:
```
    let temperatureAxis = lineChartView.leftAxis
    temperatureAxis.axisMaximum = 360
    temperatureAxis.axisMinimum = 0
    temperatureAxis.labelTextColor = UIColor.red
    temperatureAxis.axisLineColor = UIColor.darkGray
    
    let sliderAxis = lineChartView.rightAxis
    sliderAxis.labelCount = 5
    sliderAxis.drawAxisLineEnabled = true
    sliderAxis.labelTextColor = UIColor.blue
    sliderAxis.axisLineColor = UIColor.darkGray
    sliderAxis.granularityEnabled = true
    sliderAxis.axisRange = 100
```
Also is there a way I could only show few labels I want inside axis? I can limit and set few, but what if lets say I want to show 83 too?

**Comment by liuxuan30** [comment]
check `axisDependency`, and override `computeAxisValues()` maybe
