### ISSUE TITLE
axisDependency does not work

### ISSUE THREAD

**Issue by sunynator** [danielgindi/Charts#2258]
I'm trying to create combined chart but the yValue from LineChart and BarChart are alway have the same projection even I set axisDependency for both line dataset and bar dataset. This problem happens in the sample project.

![1](https://cloud.githubusercontent.com/assets/17984236/24079330/b1d5e22a-0cb7-11e7-8c06-409eac1c7ea2.jpg)

    LineChartData *d = [[LineChartData alloc] init];
    NSMutableArray *entries = [[NSMutableArray alloc] init];
    for (int index = 0; index < ITEM_COUNT; index++)
    {
        [entries addObject:[[ChartDataEntry alloc] initWithX:index + 0.5 y:(arc4random_uniform(15) + 5)]];
    }
    LineChartDataSet *set = [[LineChartDataSet alloc] initWithValues:entries label:@"Line DataSet"];
    set.axisDependency = AxisDependencyLeft;
    [d addDataSet:set];

`

    NSMutableArray<BarChartDataEntry *> *entries1 = [[NSMutableArray alloc] init];
    for (int index = 0; index < ITEM_COUNT; index++)
    {
        [entries1 addObject:[[BarChartDataEntry alloc] initWithX:index y:(arc4random_uniform(25) + 1000000)]];

    }
    BarChartDataSet *set1 = [[BarChartDataSet alloc] initWithValues:entries1 label:@"Bar 1"];
    set1.axisDependency = AxisDependencyRight;

    
    BarChartData *d = [[BarChartData alloc] initWithDataSets:@[set1]];

**Comment by thierryH91200** [comment]
look at PR : fix the issue with axis dependencies #2049

**Comment by liuxuan30** [comment]
closing. soon to merge https://github.com/danielgindi/Charts/pull/2874
