### ISSUE TITLE
lineChart.leftAxis.startAtZeroEnabled is not available in Swift 3 library

### ISSUE THREAD

**Issue by shivang2902** [danielgindi/Charts#2262]
Hi @danielgindi , @liuxuan30 

I wanted to skip the 0 of the left axis and i found the solution "lineChart.leftAxis.startAtZeroEnabled = false" but it is not available in the Swift 3 branch of Charts. 

Is this removed or have been changed to other function ? 
Thanks

**Comment by thierryH91200** [comment]
in v2

```
 /// This is deprecated now, use `axisMinValue`
    @available(*, deprecated=1.0, message="Use axisMinValue instead.")
    public var isStartAtZeroEnabled: Bool { return startAtZeroEnabled }
```

in v3

   ```
 /// This property is deprecated - Use `axisMinimum` instead.
    @available(*, deprecated: 1.0, message: "Use axisMinimum instead.")
    open var axisMinValue: Double
        {
        get { return axisMinimum }
        set { axisMinimum = newValue }
    }
```

**Comment by shivang2902** [comment]
Thanks @thierryH91200 , but i have used my custom left axis value formatter to eliminate 0.
Thanks anyways

**Comment by shivang2902** [comment]
![screen shot 2017-03-21 at 5 56 43 pm](https://cloud.githubusercontent.com/assets/18008508/24147340/c74dc2fe-0e5f-11e7-882e-82f0ae403695.png)

@thierryH91200 Can you help me stop the line just before the 12 xAxis mark, i tried various things but does not help, thanks a lot

**Comment by shivang2902** [comment]
@thierryH91200 , @danielgindi , @liuxuan30 can you please help me on the above issue
The situation is that i need to show the data of 4 hours [3 hours past, 1 hour future], suppose the current time is 11 so the line graph will be plotted from 9 - 11, but 11 -12 will have no line graph, for now i am giving 0 value for data ahead of 11 which makes the graph drop on xAxis. As i saw the MPAndroidChart can accepts separate values for x and y axis which makes this scenario possible. Please help me to achieve this one guys !!

P.S : i am using  iOS Swift 3.0

**Comment by shivang2902** [comment]
@danielgindi is this possible to achieve with ios-charts ?

**Comment by liuxuan30** [comment]
you can set your x to be 12h and have y value. You can also use axisMimimum/max to set the axis range.

Reopen a closed issue with a different question is NOT a good habit.
