### ISSUE TITLE
Increasing bar width in grouped sets of BarChartView

### ISSUE THREAD

**Issue by Mourad-Khalfallaoui** [danielgindi/Charts#2263]
I'm trying to increase the bar width in chartBarView . there is my code :
`let groupSpace = 0.01
let barSpace = 0.01
let barWidth = 0.32
// (0.32 + 0.01) * 3 + 0.01 = 1.00

let groupCount = 9
let startMonth = 0

chartData.barWidth = barWidth;
barChartView.xAxis.axisMinimum = Double(startMonth)
let spaceIndividualBar = chartData.groupWidth(groupSpace: groupSpace, barSpace: barSpace)
print("spaceIndividualBar must be equan to 1 : \(spaceIndividualBar)")
barChartView.xAxis.axisMaximum = Double(startMonth) + spaceIndividualBar * Double(groupCount)

chartData.groupBars(fromX: Double(startMonth), groupSpace: groupSpace, barSpace: barSpace) 
`
I want to double the width of the individual bars than this result :

![fullsizerender](https://cloud.githubusercontent.com/assets/12232577/24139328/fb4e97d4-0e1b-11e7-9d40-1d55bec11fe5.jpg)

**Comment by liuxuan30** [comment]
Try other numbers.. as you already know how to calculate it

**Comment by Mourad-Khalfallaoui** [comment]
Whuy have you close my question ? 0.32 for barWidth is the maximum that I can put , if I try with 0.329 and 0.001 for barSpace and groupSpace, the frame vue outside the frame and the grouped set outside group frame

**Comment by liuxuan30** [comment]
closing does not mean we will not update any more. 
You already know the properties and values and I think you are good to go.
BarWidth default is 0.85, but you ask how to 'increase bar width' while you said 0.32 is your max input, what could I say..
