### ISSUE TITLE
Line Chart Highlight, Remove X axis line and display label

### ISSUE THREAD

**Issue by harpangell7** [danielgindi/Charts#2266]
Dear Charts Moderators and contributors,

How do I remove the X axis of the highlight/drag lines. Also, how do I display a label on top of the y axis on the highlight/drag lines?

I'm at work right now so I cannot edit my code, however I was just thinking maybe I use

self.lineChartView.xAxis.isLabelEnabled? 

Basically I want to display the time/date for the highlighted amount on my line chart, and I only want a vertical line showing when I drag. 

Thank you for the help. I apologize if this is a really easy answer. I did look through the resources files but could not find the label anywhere in the highlight/highlighted files.

**Comment by liuxuan30** [comment]
Have you checked ChartsDemo? You better post an image to explain what you ask, some of your words are not easy to understand

**Comment by liuxuan30** [comment]
for highlighted stuff, check out `drawHighlgithed()` to see what you want to disable, like `isVerticalHighlightIndicatorEnabled`
