### ISSUE TITLE
ChartsDemo Buildtime Error: No such module 'RealmSwift'

### ISSUE THREAD

**Issue by AdrianBinDC** [danielgindi/Charts#2268]
I initially tried to run the ChartsDemo from the repo I downloaded and I encountered a Carthage error. Upon installing Carthage, I encountered the error referenced above. I was hopeful I could just fire up the demo app and look at the basics of how it works.

**Comment by fvvliet** [comment]
same here...

**Comment by fvvliet** [comment]
In Cartfile and Cartfile.resolved change realm/realm-cocoa version to "v2.4.4" and run [carthage checkout] again.

**Comment by petester42** [comment]
#2199 should fix this issue. clean the project if you still get issues

**Comment by r0b5ter** [comment]
I have the same issue. Updated the cartfiles but the error is still there
