### ISSUE TITLE
when i install pod 'Charts'. its install Old Version Of library 2.3 and give me error convert code into latest swift.

### ISSUE THREAD

**Issue by vishalkalola1** [danielgindi/Charts#2269]
Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
target 'vishalk' do
Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 Pods for vishalk
pod 'Charts','~>3.0.1'
use_frameworks!
end

**Comment by HuppDevelopers** [comment]
you should write this line in pod file, then install it.

pod 'Charts', '~>3.0.1'

**Comment by vishalkalola1** [comment]
already do that. @HuppDevelopers

**Comment by petester42** [comment]
Try running `pod repo update` first

**Comment by vishalkalola1** [comment]
same error gives me. @petester42

**Comment by petester42** [comment]
Works for me delete your Podfile.lock and try again

Tested with podfile:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test
  pod 'Charts', '~>3.0.1'
end
```

output:
<img width="570" alt="screen shot 2017-03-26 at 5 58 51 pm" src="https://cloud.githubusercontent.com/assets/296718/24335573/e8ab4dd0-124d-11e7-9731-62b7965ad342.png">

**Comment by vishalkalola1** [comment]
its install but after open project into xcode8.2.1 its give me below error.
![screen shot 2017-03-27 at 4 55 19 pm](https://cloud.githubusercontent.com/assets/26406461/24354115/4d15519c-130e-11e7-8e8d-5a4eff082afc.png)

**Comment by petester42** [comment]
You need to update your project settings to "use legacy swift" to no before doing pod install
