### ISSUE TITLE
How to draw circle at the end of a data set on line chart 

### ISSUE THREAD

**Issue by shivang2902** [danielgindi/Charts#2270]
![screen shot 2017-03-21 at 5 56 43 pm](https://cloud.githubusercontent.com/assets/18008508/24194840/90d94f4a-0f1d-11e7-8e51-431478f89092.png)
@thierryH91200 , @danielgindi , @liuxuan30, @petester42, @AlBirdie 
The situation is that i need to show the data of 4 hours [3 hours past, 1 hour future], suppose the current time is 11 so the line graph will be plotted from 9 - 11, but 11 -12 will have no line graph, for now i am giving 0 value for data ahead of 11 which makes the graph drop on xAxis. As i saw the MPAndroidChart can accepts separate values for x and y axis which makes this scenario possible.
let data: LineChartData = LineChartData(xVals: months, dataSets: dataSets)
The above function has been removed from latest version of the library or it could have solved my purpose. Now at the end of the line or dataset i have to show a circle also

P.S : i am using iOS Swift 3.0

**Comment by thierryH91200** [comment]
you can use scatter chart on the last point

**Comment by shivang2902** [comment]
@thierryH91200 can you please be more specific, how can i change the Chart to another type ?, there is method to draw circle on x,y interaction but can i customise it to show only one circle ?

**Comment by liuxuan30** [comment]
>How to draw circle at the end of a data set on line chart 
just take a look at drawCircles() and override `drawDataSets` to draw the last data.
