### ISSUE TITLE
place image at top of each bar in bar graph

### ISSUE THREAD

**Issue by jainrohit2292** [danielgindi/Charts#2271]
Hi, 
I need to implement the graph as shown in image below. The code to display bars is done. I need to know how can I display image on top of each bar.

Thanks for the help in advance

![individual activity week](https://cloud.githubusercontent.com/assets/26617321/24233998/d575a9d4-0fbb-11e7-892b-20d21b3a6b6e.png)

**Comment by liuxuan30** [comment]
It' already supported. https://github.com/danielgindi/Charts/pull/1793

**Comment by jainrohit2292** [comment]
@liuxuan30 I have updated my pods -  **pod update Charts** but I can find any property or method related to icon such as drawIconsEnabled

**Comment by liuxuan30** [comment]
looks like it's not populated to pod. @petester42 do you know when pod will get updated?
