### ISSUE TITLE
Line chart - LineChartDataSet Background color.

### ISSUE THREAD

**Issue by Kiee79** [danielgindi/Charts#2272]
Hi , 

I am new with charts so is it maybe easy way to have different background colors for each LineChartDataSet ? @liuxuan30

**Comment by harpangell7** [comment]
Yeah, you would just have to set the chart data for the different data sets...

**Comment by Kiee79** [comment]
No , I mean change grid background for different sets ,no line color etc :)

**Comment by harpangell7** [comment]
self.lineChartView.gridBackgroundColor = UIColor.darkGray

**Comment by Kiee79** [comment]
Yes but I want to divide grid by sets and set different color for different part of grid :)

**Comment by harpangell7** [comment]
Right so just use a bool...

**Comment by harpangell7** [comment]
So first set:

var dataSetFirst: Bool = false
var dataSetSecond: Bool = false

Then in your code set your bools:

dataSetFirst = true

Then when you initialize your graphs use

if dataSetFirst == true {
self.lineChartView.gridBackgroundColor = UIColor.darkGray
} else if dataSetSecond == true {
self.lineChartView.gridBackgroundColor = UIColor.darkGray
}

**Comment by Kiee79** [comment]
It won't work when I have 3 sets on 1 chart and I need 3 colors at the same time.

**Comment by harpangell7** [comment]
Wait different "part" of the grid? I dont know if thats possible

**Comment by harpangell7** [comment]
I get it now, sorry...

**Comment by Kiee79** [comment]
Yes. 1 chart , 3 sets , 3 grid colors at the same time

**Comment by harpangell7** [comment]
You could remove the grid and change the color of the line maybe?

**Comment by harpangell7** [comment]
But Im not sure you can achieve what you want

**Comment by Kiee79** [comment]
I guess I need to do sth with method "drawGridBackground" but i 
I counted that someone had already done it.

**Comment by harpangell7** [comment]
Hmm, well please post here if you figure it out, I would be interested in checking it out.

**Comment by liuxuan30** [comment]
if you mean fill beneath the line, enable `drawFilledEnabled`
if you are asking drawGridBackground, it's in the code.
The library does not have something called data set grid background.
