### ISSUE TITLE
Getting the percentage and label for a slice

### ISSUE THREAD

**Issue by 4rihant** [danielgindi/Charts#2273]
I want to add a unit test in my application that allows me to verify that the data on the Piechart is being correctly displayed. 

I would therefore need to get the name and percentage value of each slice. What is the simplest way to do it? 

Currently I can only extract the name of the slice and not the percentage. The name extraction too is very complex: 

((statsView.chart.data?.dataSets[0] as! PieChartDataSet).values[0] as! PieChartDataEntry).label!

((statsView.chart.data?.dataSets[0] as! PieChartDataSet).values[0] as! PieChartDataEntry).value

Thanks

**Comment by liuxuan30** [comment]
add whatever code you need to get.. The library can't forecast you need to get a label and give you a short way in advance.
