### ISSUE TITLE
Demo for Swift 3

### ISSUE THREAD

**Issue by sasquatchgit** [danielgindi/Charts#2274]
Hi,
I am new to Charts and want to use for Horizontal Bar Chart.
I couldn't find any sample for Swift 3. [This](http://www.appcoda.com/ios-charts-api-tutorial/) is outdated and doesn't work. Can someone please provide basic setup code for Swift 3?

Thanks

**Comment by harpangell7** [comment]
You need to look in the library and find out what the problem is... Where are you receiving an error?

**Comment by thierryH91200** [comment]
here is an example

[HorizontalBarChartViewController.swift.zip](https://github.com/danielgindi/Charts/files/867171/HorizontalBarChartViewController.swift.zip)

**Comment by sasquatchgit** [comment]
Thanks @thierryH91200.
