### ISSUE TITLE
I want to un-highlight a line chart when dragging has stopped, among other things. Am I missing it?  Thanks

### ISSUE THREAD

**Issue by harpangell7** [danielgindi/Charts#2276]
I want to un-highlight a line chart when dragging has stopped, among other things. Am I missing it?

Thanks

**Comment by harpangell7** [comment]
I tried setting up my own pangesturerecognizer but it wouldnt let me drag in the chart. I'm using swift 3 and I just want to remove the highlight when the panning/dragging stops.

**Comment by liuxuan30** [comment]
Have you checked ChartsDemo line chart? I don't see what you asked happens.

**Comment by quintonpryce** [comment]
I landed here when trying to remove the highlight lines after the drag had stopped. This is what I figured out works:

```
extension LineChart1ViewController: ChartViewDelegate {
    func chartViewDidEndPanning(_ chartView: ChartViewBase) {
        print("Did Finish selection")
        chartView.highlightValues(nil)
    }
}
```
