### ISSUE TITLE
Only allow slice space for the selected item in a pie chart

### ISSUE THREAD

**Issue by nwtsai** [danielgindi/Charts#2278]
How do you do this? I see the screenshot on the README of just the selected piece being separated from the rest of the chart, but it seems like only PieChartDataSet has a .sliceSpace, but this value will set the slice space for the entire chart. Thanks!

**Comment by liuxuan30** [comment]
have no idea what are you asking.

**Comment by nwtsai** [comment]
Hey, thanks for the reply. Does [this](http://stackoverflow.com/questions/43011059/how-do-you-add-slice-spacing-to-just-the-selected-item-of-a-pie-chart-with-ios-c) help clarify the question?
Thanks!

**Comment by liuxuan30** [comment]
Still, pieChartDataSet.sliceSpace is the property for highlight and other rendering. I don't know why it bothers. pie chart should only have one data set if I remember correctly.

**Comment by patwhitehead1** [comment]
I don't think this question has been clearly answered, but the issue is closed. @nwtsai were you able to figure this out? I've got the same issue.

**Comment by JorgeLuisR-97** [comment]
@liuxuan30 What is the solution for add slice spacing only for the selected item? Currently, pieChartDataSet.sliceSpace adds space to all elements

@nwtsai and @patwhitehead1 were you able to figure this out? I've got the same issue
