### ISSUE TITLE
Get current axis interval between labels

### ISSUE THREAD

**Issue by acegreen** [danielgindi/Charts#2281]
In my case I'm setting both granularity and labelcount, with the intention of having an even grid, 20x20 grids (labels) and a certain minimum granularity. This seems to work but I can display the current interval. 

Doing leftAxis.granularity would display the minimum I set and  not the current axis interval. Is there any way to get that or do I have to do some computation like getting two values on that axis and subtracting them?

        leftAxis.granularityEnabled = true
        leftAxis.granularity = granularityY
        leftAxis.forceLabelsEnabled = true
        leftAxis.labelCount = labelCount

**Comment by liuxuan30** [comment]
```SWIFT
    open func setLabelCount(_ count: Int, force: Bool)
    {
        self.labelCount = count
        forceLabelsEnabled = force
    }
```
use this to set labelCount.

**Comment by acegreen** [comment]
@liuxuan30 thats not the point though. I wanted to find a way to get the current interval (granularity) of my chart. As mentioned, the granularity I set is in my case not respected and thats fine since I want to force the labels but I would like to add the real granularity to my charts legend

**Comment by liuxuan30** [comment]
sorry I missed. No idea what's the convenient way to get interval. But one trick is to get two neighbor x values and use the ChartTransformer to calculate the interval in screen pixels.

**Comment by acegreen** [comment]
Thanks for the reply. So I got two neighbouring values. What property of ChartTransformer could I use? On a side note, shouldn't the _granularity property be updated to reflect the "real" granularity as opposed to granularity which we define as the minimum?

**Comment by liuxuan30** [comment]
I don't fully understand about granularity yet, granularity used to be designed to filter repeated axis labels. so I am just thinking about getting intervals.
ChartTransformer has something like `pointValuesToPixel` and `pixelsToValues` to do convert.
