### ISSUE TITLE
Swift 3.1 Build

### ISSUE THREAD

**Issue by cliftonlabrum** [danielgindi/Charts#2287]
Xcode 8.3 is out now, along with Swift 3.1. The iOS Charts module won't build without downgrading the swift version. 

Can we please get a Swift 3.1 build of this? Thank you! :)

**Comment by txaiwieser** [comment]
How did you do downgrade the module swift version?

**Comment by cliftonlabrum** [comment]
Actually, never mind on the swift version downgrade. It doesn't look like that's possible.

**Comment by cliftonlabrum** [comment]
It looks like there's an Xcode 8.3 branch: https://github.com/danielgindi/Charts/tree/xcode-8.3

I'll give that a try and see if it works.

**Comment by ronflima** [comment]
I found that it can be compiled, but with a bunch of warnings, most of them deprecation warnings.

**Comment by txaiwieser** [comment]
Great, gonna try this branch then! 👍

**Comment by cliftonlabrum** [comment]
Has anyone done a Carthage build with the 8.3 branch? That's all I'm after. :)

**Comment by ronflima** [comment]
I have added this stuff as a dependency to my project using git submodules. It came to compile in tag 3.0.1 but with a bunch of warnings.

**Comment by txaiwieser** [comment]
Yes, I'm using Carthage and just built the branch "xcode-8.3"

**Comment by ronflima** [comment]
Upgraded to the xcode-8.3 branch also. Compiled just fine.

**Comment by krystianpaszek** [comment]
Just used Carthage to build "xcode-8.3" branch and it worked well. Took a lot of time, though. Just use 
`github "danielgindi/Charts" "xcode-8.3"` in your Cartfile.

**Comment by cliftonlabrum** [comment]
Got it. Thanks everyone!
