### ISSUE TITLE
Swift 3.1 support

### ISSUE THREAD

**Issue by saldous** [danielgindi/Charts#2288]
After upgrading to xcode 8.3 there are ~62 build errors, e.g.:

M_PI and M_PI_2 is deprecated
DBL_MAX is deprecated
DBL_EPSILON is deprecated

**Comment by liuxuan30** [comment]
should work with https://github.com/danielgindi/Charts/pull/2279

**Comment by saldous** [comment]
It's not showing up in pod update yet.

**Comment by liuxuan30** [comment]
well, you have to point to master in your pod.

**Comment by saldous** [comment]
So, `pod 'Charts'` on its own doesn't pull the latest?

**Comment by saldous** [comment]
Ah, thanks! My bad.
