### ISSUE TITLE
“Swift Language Version”

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#2290]
![8af473aa-19f1-4056-8a24-a3cbffe45247](https://cloud.githubusercontent.com/assets/8455023/24389488/82893b12-13b4-11e7-92e0-9b530aa8f6d7.png)
I upgrade macOC sierra 10.12.4 Xcode upgrade to Version 8.3 I use Charts Version number V2.2.5 result my project error, how do I solve?Thank you for your guidance

**Comment by githubkiven** [comment]
![b1f1ae52-b8c9-4ce4-ba9a-e566aea6fb09](https://cloud.githubusercontent.com/assets/8455023/24389545/effbda2e-13b4-11e7-9865-22ce7bc2664c.png)
I chose the Later still will report the error

**Comment by githubkiven** [comment]
I must update the Charts?

**Comment by githubkiven** [comment]
@danielgindi

**Comment by thierryH91200** [comment]
> **I  must update the Charts?** 


YES

**Comment by gsolanki1509** [comment]
Hi..githubkiven... better you just create new function in Swift and then install charts via cocoapods. I guess then you don't need to upgrade like this. Cuz upgrading doesn't work all the time.

**Comment by githubkiven** [comment]
@thierryH91200  How do i update? How to replace charts2.2.5

**Comment by githubkiven** [comment]
what should I do？Dear @thierryH91200

**Comment by githubkiven** [comment]
Xcode8.3 does not support swift2.3
![522e7fd6-18f8-46cf-a8af-0ea5c8a5681e](https://cloud.githubusercontent.com/assets/8455023/24396362/837f5152-13d5-11e7-963c-c045229dabb0.png)

**Comment by githubkiven** [comment]
I think I should Xcode8.3 restore to Xcode8.2 ha ha ha @thierryH91200

**Comment by teacherlinprogramming** [comment]
if restore your xcode you can't deliver your app to appstore

**Comment by liuxuan30** [comment]
latest master has already merged 3.1
