### ISSUE TITLE
Fix warning for Xcode8.3

### ISSUE THREAD

**Issue by dimohamdy** [danielgindi/Charts#2292]
please fix warnings that generated aftere using Xcode8.3 

![screen shot 2017-03-28 at 12 21 45 pm](https://cloud.githubusercontent.com/assets/1476754/24400609/504f79a2-13b1-11e7-8765-940c0e5f98dd.png)

**Comment by Huang-Libo** [comment]
You can try the `Xcode 8.3` branch

**Comment by liuxuan30** [comment]
this has fixed in latest mster.
