### ISSUE TITLE
Xcode 8.3: 62 deprecation warnings

### ISSUE THREAD

**Issue by ghowen** [danielgindi/Charts#2293]
Xcode 8.3 generates 62 warning when using the Charts 3.0.1 pod. They are all deprecation warnings related to constants. Here are the constants that need replacing for Swift 3.1 compatibility:

'M_PI_2' is deprecated: Please use 'Double.pi / 2' or '.pi / 2' to get the value of correct type and avoid casting.

'DBL_MAX' is deprecated: Please use 'Double.greatestFiniteMagnitude' or '.greatestFiniteMagnitude'.

'DBL_EPSILON' is deprecated: Please use 'Double.ulpOfOne' or '.ulpOfOne'.

**Comment by dimohamdy** [comment]
please pull the last version  you can check last commit https://github.com/danielgindi/Charts/commit/aa2243916790a50e38ebe4cab2314351af5886f4

**Comment by oviroa** [comment]
are you going to make this available via cocoapods?

**Comment by liuxuan30** [comment]
@petester42 usually manages pods. but you can point it to master in your pod.

**Comment by ghowen** [comment]
Thank you all. Pointing the pod to master did the trick. As I had to look up how to do it, here is the modified line from the podfile for anyone else wanting to do so:

`  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git'
`
