### ISSUE TITLE
Modify Marker before showing value

### ISSUE THREAD

**Issue by gsolanki1509** [danielgindi/Charts#2294]
Hi Guys, 
 
How can i get the customize the value of selected bar before it gets shown in marker?

As i'm passing double values to x-Axis but when user click on particular bar i have to convert it to hh:mm

Thanks in advance..!!

**Comment by gsolanki1509** [comment]
For more info. Please check below screenshot

![screen shot 2017-03-28 at 1 57 18 pm](https://cloud.githubusercontent.com/assets/10267448/24409138/60f5b1b6-13e0-11e7-90ba-124f78b1e9e8.png)

**Comment by thierryH91200** [comment]
[YMarkerView.swift.zip](https://github.com/danielgindi/Charts/files/875940/YMarkerView.swift.zip)
[HourValueFormatter.swift.zip](https://github.com/danielgindi/Charts/files/875941/HourValueFormatter.swift.zip)


<img width="1038" alt="capture d ecran 2017-03-28 a 16 19 25" src="https://cloud.githubusercontent.com/assets/6251463/24410153/99f371c8-13d2-11e7-951a-bf17966f51bb.png">



and add

           ```

           values = ["28800", "32400", "36000", "34000", "30000", "42000", "45000"]
            let  marker = YMarkerView( color: #colorLiteral(red: 0, green: 0, blue: 0, alpha: 1), 
                                      font:      NSUIFont.systemFont(ofSize: 12.0),
                                        textColor: NSUIColor.white,
                                        insets: EdgeInsets(top: 8.0, left: 8.0, bottom: 8.0, right: 8.0),
                                        yAxisValueFormatter: HourValueFormatter())

            
            marker.minimumSize = CGSize(width: CGFloat(80.0), height: CGFloat(40.0))
            barChartView.marker = marker
```

**Comment by gsolanki1509** [comment]
Thanks man for your solution. :)

I could show the values now. But still in marker there is unwanted value like (Y:) which i want to remove it. That was one of the reason i was looking for function before showing marker.

![screen shot 2017-03-29 at 9 29 56 am](https://cloud.githubusercontent.com/assets/10267448/24440054/f59f3e86-1462-11e7-9b1a-0bae920ab809.png)


As you can see i want to remove "y" from marker view. Just selected bar value.

**Comment by thierryH91200** [comment]
look at YMarkerView

Make a little effort please
it's not complicated

**Comment by gsolanki1509** [comment]
Gotcha... Sorry to post that issue. :)

**Comment by liuxuan30** [comment]
guess we can close this
