### ISSUE TITLE
Charts 2.3 with Swift 3 (xCode 8.3)

### ISSUE THREAD

**Issue by roimulia** [danielgindi/Charts#2295]
xCode 8.3 removed the support for Swift 2.3. 
My project already integrated Charts 2.3 (based on Swift 2.3), and as far as I understand Charts 3 changed the behavior of Charts 2.3 completely.
I have this fear that upgrading to Charts 3 won't work due to the specific integration we made with Charts 2.3.
Is there an Charts 2.3 that is updated to Swift 3? 
Or i've made a bad conclusion, and Charts 3 didn't made this big change from 2.3?

**Comment by petester42** [comment]
There was a breaking change in charts 3.0. Because swift 3.0 was also a breaking change we decided that would would do both at once. So therefore we never supported swift 3.0 and charts 2.3. Charts 2.3 is legacy and won't be converted to swift 3.0.

**Comment by liuxuan30** [comment]
if you are using xcode 8.3, you better upgrade your swift or just stick to xcode 8.2 
chart 3.0 has breaking changes, so you should get short term plans and long term plans.

**Comment by roimulia** [comment]
Hey @liuxuan30  , Thank you for responding. I'm guessing converting Charts 2.3 to Swift 3 is too much of an hassle, right? I

**Comment by liuxuan30** [comment]
yes, of course.
