### ISSUE TITLE
Remove color label in pie-chart

### ISSUE THREAD

**Issue by iceman201** [danielgindi/Charts#2297]
I want remove this part color intro label, I have searched on stackoverflow seens it doesnt allow.
And also I couldnt find and function can do it.

![image](https://cloud.githubusercontent.com/assets/5027957/24441749/98aef54a-14b7-11e7-8d6d-7a0c17fa51ff.png)

Anyone help?

**Comment by ArturBaghdas** [comment]
try this chartView.legend.enabled = false

**Comment by liuxuan30** [comment]
@ArturBaghdas is right.

**Comment by iceman201** [comment]
@ArturBaghdas Thank you man
