### ISSUE TITLE
Running 1 of 1 custom shell scripts

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#2302]
Why when I run ChartsDemo has been prompted to run 1 of custom shell scripts？
![8bc7ac36-8c6f-4f64-afa2-e87c57b1e8b5](https://cloud.githubusercontent.com/assets/8455023/24485906/cf1a61be-1539-11e7-9584-e95f25d343ec.png)

**Comment by githubkiven** [comment]
Charts  Version3.0.1

**Comment by githubkiven** [comment]
@petester42

**Comment by githubkiven** [comment]
I'm using Xcode8.3

**Comment by petester42** [comment]
Because people can't read the readme about running commands before running the demo. So we run it for them to reduce the issues that get filed about it.

**Comment by githubkiven** [comment]
@petester42 How can i do it to run？

**Comment by githubkiven** [comment]
Now there will not be the above problems, and then how to solve this Thank you @petester42 
![4dff0bc5-94f1-4917-a542-dcf1b556de55](https://cloud.githubusercontent.com/assets/8455023/24533026/7bc60068-15f7-11e7-9ca3-1e98a6cb347b.png)
