### ISSUE TITLE
Ambiguous use of 'data'

### ISSUE THREAD

**Issue by srinathp90** [danielgindi/Charts#2304]
Hi i used to get this error while compiling, when we set optimization level to  None [-Onone] it would work.

![screen shot 2017-03-30 at 2 40 37 pm](https://cloud.githubusercontent.com/assets/9376405/24496802/eddd1764-1556-11e7-929f-400720181249.png)

**Comment by liuxuan30** [comment]
what Xcode version and code base?

**Comment by OlingCat** [comment]
I have the same issue.
My environment:
macOS 10.12.5
Xcode version 9.0 beta 2 (9M137d)
Swift version 4.0 beta (swiftlang-900.0.45.6 clang-900.0.26)
Charts 3.0.2 (from cocoapods)

**Comment by liuxuan30** [comment]
Please don't use beta to mix things up..
there is a PR for you to use if you want to test swift 4 already.

**Comment by exaland** [comment]
Same error with Xcode 10.1 (10B61) with old build system
