### ISSUE TITLE
Set the x axis data problems, and 2.3.0 apis are quite different.Need your help

### ISSUE THREAD

**Issue by huyabin** [danielgindi/Charts#2307]
` xVals = @[@"2016-11",@"2016-12",@"2017-01",@"2017-02",@"2017-03",@"2016-04",]
 //     LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
        LineChartData *data = [[LineChartData alloc] initWithDataSets:dataSets];        
        _chartView.xAxis.valueFormatter = [ChartIndexAxisValueFormatter withValues:xVals];`

**Comment by liuxuan30** [comment]
reopen when you state it clearly.
