### ISSUE TITLE
*PieChart* Get color of top 3 largest percent

### ISSUE THREAD

**Issue by giathienpham** [danielgindi/Charts#2308]
I want to show top 3 percent in legend. So how can I get the color of longest slice? 
Thank you all.

**Comment by liuxuan30** [comment]
the library's legend don't have such feature if I am correct. 
Just to get the top 3, this is no related, as the first color is for the first data value, so you can just get it directly.

**Comment by giathienpham** [comment]
@liuxuan30 Got it. Thank you
