### ISSUE TITLE
Adjust spacing between axis labels and axes?

### ISSUE THREAD

**Issue by simonbromberg** [danielgindi/Charts#2310]
Is there a way to adjust (increase) the spacing/padding between the axis labels and the axes? The margins around the labels are a bit tight in my case:

![image](https://cloud.githubusercontent.com/assets/2942298/24561588/50def97c-1615-11e7-8efa-a76056ff50cf.png)

**Comment by liuxuan30** [comment]
looks like you are asking `xAxis.yOffset`
