### ISSUE TITLE
Please give option for installing via Swift Package Manager too

### ISSUE THREAD

**Issue by nikhilpandey4** [danielgindi/Charts#2313]
Please give option for installing via Swift Package Manager too

**Comment by petester42** [comment]
As far as I know SPM doesn't support app development since it UIKit/CoreGraphics isn't open source. Am I wrong? We need CoreGraphics and UIKit/AppKit for this library. If they are available for SPM I'd gladly support it.

**Comment by danielgindi** [comment]
There's actually an open task https://github.com/danielgindi/Charts/issues/753
