### ISSUE TITLE
Limit Line after update to 3.0.2 no longer shown

### ISSUE THREAD

**Issue by ventuz88** [danielgindi/Charts#2319]
Hi, after the update to 3.0.2, limit line is not longer shown. I've tried to discard all changed (so I returned to 3.0.1) and all works fine.

There's another way to get it? Thanks.

**Comment by liuxuan30** [comment]
<img width="361" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/24687103/6b07a97e-19ea-11e7-91cc-ac1fadf31358.png">
I can see it in ChartsDemo. Can you double check on your side?

**Comment by NallapatiMalleswari** [comment]
let lowLimitLine = ChartLimitLine(limit: 100, label: "Low Threshold")
        lowLimitLine.lineWidth = 3.0
//        lowLimitLine.lineDashLengths = [20, 2]
        lowLimitLine.lineColor = UIColor.green
//        lowLimitLine.valueTextColor = UIColor.lightGray
        charts.leftAxis.addLimitLine(lowLimitLine)
If you want to make it as line instead dots  ,uncomment the above two lines
