### ISSUE TITLE
BarChart xAxis labels a moving

### ISSUE THREAD

**Issue by kimdv** [danielgindi/Charts#2321]
Hello, 

I have the xAxis labels at the bottom position in my barChart. 
But when the bars have a low value, the is more spacing between the bars and the labels.

![screen shot 2017-04-03 at 18 59 29](https://cloud.githubusercontent.com/assets/5477711/24621012/3c94cc02-18a0-11e7-9f18-76db10474e54.png)

![screen shot 2017-04-03 at 19 17 59](https://cloud.githubusercontent.com/assets/5477711/24623336/5c3120bc-18a8-11e7-8596-130c8c2302ee.png)

**Comment by liuxuan30** [comment]
have you tried to turn on y axis to see whats the y axis min value?
You can try set y axis axisMinValue to 0 to let it start above 0.
