### ISSUE TITLE
Labels to PieChart? v 3.0.2

### ISSUE THREAD

**Issue by JesusAdolfo** [danielgindi/Charts#2323]
I am using the latest Charts version after updating a project to Swift 3.1.
However, the dataset initializer not longer takes the labels as it did before

before:  
`                    let pieChartData = PieChartData.init(xVals: labels, dataSets: [dataSet])
`

now
`let pieChartData = PieChartData.init(dataSets: [dataSet])
`

 Reference to code/docs with the updated way to do this?

**Comment by abdallahnh** [comment]
Hi,

Try this:

`let pieChartDataSet = PieChartDataSet(values: dataEntries, label: nil)
  let pieChartData = PieChartData(dataSets: [pieChartDataSet])`

**Comment by JesusAdolfo** [comment]
Still the question remains. Where Do I add the labels?

**Comment by JesusAdolfo** [comment]
Ok this was hard to find out... In the newest version one should use:

`let entry = PieChartDataEntry(value: Double(yourValue), label: label)`

before, the initializer for any chart was **ChartDataEntry** which did not take the label parameter
