### ISSUE TITLE
Skipped installing realm-cocoa.framework binary due to the error:

### ISSUE THREAD

**Issue by angus2651** [danielgindi/Charts#2326]
I cannot run the demo in ChartsDemo/ChartsDemo.xcodeproj, it shows many errors.

So, I ran carthage checkout and show the following result:
*** Checking out ios-snapshot-test-case at "da629211c17a4c507e2e866e8a19ed3122af770b"
*** Downloading realm-cocoa.framework binary at "v2.1.1"
*** Skipped installing realm-cocoa.framework binary due to the error:
	"Incompatible Swift version - framework was built with 3.0.1 and the local version is 3.0.2."
*** Checking out realm-cocoa at "v2.1.1"

**Comment by liuxuan30** [comment]
you should be checking out Realm by carthage with ~> v2.4.0
