### ISSUE TITLE
How to remove Grid 

### ISSUE THREAD

**Issue by rwh23** [danielgindi/Charts#2329]
I want to remove default grid lines of StackedBarChart in BarChartView background.

**Comment by thierryH91200** [comment]
try

```
xAxis.drawGridLinesEnabled = false / true
leftAxis.drawGridLinesEnabled = false / true
```

**Comment by rwh23** [comment]
Thanks.
But leftAxis has only one line vertically. How I can remove the line also?

**Comment by metrue** [comment]
@nodahikaru 
How did you remove the leftAxis left line in the end?

**Comment by metrue** [comment]
Find the answer here https://github.com/danielgindi/Charts/issues/3294#issuecomment-368180401
```swift
chartView.leftAxis.axisLineColor = .clear

```
