### ISSUE TITLE
Module Charts not found XCODE 8.1 Error

### ISSUE THREAD

**Issue by yogesh2209** [danielgindi/Charts#2330]
I added Charts through pods.
It was working fine till yesterday. Then i updated XCODE to 8.3 Since then It started giving me this error - Module not found.
Then i downgraded my XCODE to 8.1 again but now it's not even working on this version of XCODE.
//URGENT HELP NEEDED

Please help.
<img width="889" alt="screen shot 2017-04-06 at 12 10 19 am" src="https://cloud.githubusercontent.com/assets/8548476/24721289/7537d04a-1a5d-11e7-80b8-d9298fca2cf2.png">

**Comment by petester42** [comment]
You probably need to run `pod install` again

**Comment by liuxuan30** [comment]
FYI Xcode 8.3 uses swift 3.1, and old module might not be compatible. reinstall and use Xcode 8.3, point your pod to master if necessary, and you should be fine

**Comment by yogesh2209** [comment]
AN ADVICE : Before closing an issue, you should confirm that issue has been resolved or not or atleast wait for the user to react.

I am using XCODE 8.1 and using Charts 3.0.0 version - which both runs on swift 3.0 i guess.
Now, when i run, it is giving me an error - Framework not found Charts

Please help me !!

<img width="876" alt="screen shot 2017-04-06 at 11 48 02 am" src="https://cloud.githubusercontent.com/assets/8548476/24741391/4f35b766-1ac3-11e7-9227-6739747e667d.png">

**Comment by yogesh2209** [comment]
Hi,
I removed Charts from pod. Instead, i dragged .xcodeproj to my project.
Now, it is working fine.

Thanks.

**Comment by liuxuan30** [comment]
Thanks for your advice. Usually we mark it as closed as we think it is solved or no further response. If we leave it open and no user reponse, it will be another huge effort to walk through the issues and close again. 

It's not easy to manage the issues, as I have tried so hard to answer and close, the issues still goes up to 200+. We just wanted to keep the real issues open, and for those we have seen a lot and just general questions, we usually close it but it does not mean we will not response then.

As for your question, pod needs to point to master branch to get the latest code.
