### ISSUE TITLE
AxisDependencyRight  Question~~

### ISSUE THREAD

**Issue by Hi-World** [danielgindi/Charts#2331]
I want to make a lineData using CombinedChartView from right to left.But i have some trouble with "set.axisDependency = AxisDependencyRight". I use this code ,but it does't works.Help me,Thanks!

`NSMutableArray *sellYArray = [NSMutableArray arrayWithArray:_sellDataArray_Y];
NSMutableArray *sellyVals = [NSMutableArray array];
        for (int i = 0; i < sellYArray.count; i++) {
            [sellyVals addObject:[[ChartDataEntry alloc] initWithValue:[sellYArray[i] doubleValue] xIndex:i]];
        }
        LineChartDataSet *set2 = [[LineChartDataSet alloc] initWithYVals:sellyVals label:@""];

        [set2 setColor:kUIColorFromRGB(0x83ce01)];

        [set2 setCircleColor:[UIColor whiteColor]];
        set2.drawCirclesEnabled = NO; //是否显示坐标点
        set2.lineWidth = 2.f;         //线宽
        set2.circleRadius = 1.0;
        set2.drawCircleHoleEnabled = YES; //坐标点是否填充
        set2.valueFont = [UIFont systemFontOfSize:9.f];
        set2.axisDependency = AxisDependencyRight;
        set2.highlightColor = [self.dk_manager.themeVersion isEqualToString:DKThemeVersionNight] ? kUIColorFromRGB(0xaeaeae) : kUIColorFromRGB(0xf75b08);
NSMutableArray *dataSets = [NSMutableArray array];
        [dataSets addObject:set2];
        lineData = [[LineChartData alloc] initWithXVals:timeArray dataSets:dataSets];
`

**Comment by Hi-World** [comment]
i pod  'Charts/Realm','~> 2.2.5'.Has it something to do with this?

**Comment by petester42** [comment]
Well it could be many things. It could be because 2.2.5 is old and doesn't work with newer versions of Xcode/swift. The other thing could be because of [this](https://github.com/danielgindi/Charts/blob/master/README.md#another-heads-up-chartsrealm-is-now-in-a-separate-repo-pods-is-also-now-charts-and-chartsrealm-instead-of-chartscore-and-chartsrealm).

**Comment by liuxuan30** [comment]
first, 2.2.5 is too old and not work with swift 3.0. 
Second, please use  ChartsDemo first to see how it works. 
last but not least, whenever you ask a question, `but it does't works` will never be useful for what does not work.
