### ISSUE TITLE
xcode 8.3 swift 3.1

### ISSUE THREAD

**Issue by shadyk** [danielgindi/Charts#2332]
on converting i am getting more than 2000 errors. is there an update for this?

**Comment by bestimmaa** [comment]
+1

**Comment by bestimmaa** [comment]
Checked using version swift version 3.0 - works for me!

**Comment by aelam** [comment]
#2293    and set in your Podfile with ```pod 'Charts', :git=> 'https://github.com/danielgindi/Charts.git'```

**Comment by petester42** [comment]
Charts 3.0.2 is fully Xcode 8.3 and swift 3.1 compatible. Try that version out.
