### ISSUE TITLE
Extra space to the right of chart

### ISSUE THREAD

**Issue by moon47usaco** [danielgindi/Charts#2333]
I would like to add extra space to the right of the chart, not the margin but in the chart itself.

Here are two screen shots of a program that has a setting for this.

The first is what I get by default in Charts and second is what I would like to get. Only extra space on the right side of the chart.

![screen shot 2017-04-06 at 7 16 44 pm](https://cloud.githubusercontent.com/assets/15712871/24753918/80eb9a06-1afe-11e7-9c84-356b434c4e1f.png)

![screen shot 2017-04-06 at 7 17 27 pm](https://cloud.githubusercontent.com/assets/15712871/24753922/8617524a-1afe-11e7-995a-2dcd23665136.png)

**Comment by liuxuan30** [comment]
I think it can be done by using below properties.
```swift
        self.xAxis.spaceMin = 5
        self.xAxis.spaceMax = 5
```
Tried in 
```swift
open class LineChartView: BarLineChartViewBase, LineChartDataProvider
{
    internal override func initialize()
    {
        super.initialize()
        
        renderer = LineChartRenderer(dataProvider: self, animator: _animator, viewPortHandler: _viewPortHandler)

        self.xAxis.spaceMin = 5
        self.xAxis.spaceMax = 5
    }
```

**Comment by moon47usaco** [comment]
How can I apply that to only the right side? I do not want the space on the left side as in the screen shot #2 above.

**Comment by liuxuan30** [comment]
well, `spaceMax` has no effect means you made mistakes. Try with ChartsDemo.

**Comment by moon47usaco** [comment]
I see.

I usually have all the variables set in a function that is called from inside "viewDidLoad"

IE:
`
     open class LineDemoViewController: NSViewController
     {
         @IBOutlet var lineChartView: LineChartView!
    
    override open func viewDidLoad()
    {
        super.viewDidLoad()
        setData()    
    }

    func setData() {
        ...
        lineChartView.doubleTapToZoomEnabled = false
        lineChartView.xAxis.labelTextColor = NSUIColor.white
        lineChartView.xAxis.labelPosition = .bottom
        lineChartView.xAxis.spaceMax = 10
`

It appears that this will not work like "labelPosition" and other variables and it must be set inside the "viewDidLoad()"

IE:

`open class LineDemoViewController: NSViewController
     {
     @IBOutlet var lineChartView: LineChartView!
    
    override open func viewDidLoad()
    {
        super.viewDidLoad()
        setData()    
        lineChartView.xAxis.spaceMax = 10
    }
`

**Comment by moon47usaco** [comment]
FYI the spaceMax does not work on the iOS demo either for the combined chart.

adding `_chartView.xAxis.spaceMax = 10;` to the "LineChart1ViewController.m" works but not to the "CombinedChartViewController"... =[

With all the problems I am having with combined charts I am considering ditching them all together and just layering charts on top of one another to get the same visual result.

**Comment by liuxuan30** [comment]
combined chart does not work on my side is because in the controller, it set `axisMinimum` and `axisMaximum`, once you comment them out, it would work:
(ignore the granularity issue)
<img width="362" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/24888787/4f5fd022-1e98-11e7-82e5-83cadb24e9f7.png">

**Comment by moon47usaco** [comment]
Got it thank you.
