### ISSUE TITLE
Set diffent style to single line graph 

### ISSUE THREAD

**Issue by ajaysinghthakur** [danielgindi/Charts#2336]
trying to achieve below and is available in android
![ng45](https://cloud.githubusercontent.com/assets/8075509/24797383/a902d684-1bae-11e7-979f-130667d24d3a.gif)
http://stackoverflow.com/questions/33011210/set-diffent-style-to-single-line-graph-in-mpandroidchart

**Comment by liuxuan30** [comment]
This just requires you to override `drawLinear` to use different line dash.

**Comment by liuxuan30** [comment]
Or, make two line data sets, one is solid and one is dashed, and use
```swift
    /// This is how much (in pixels) into the dash pattern are we starting from.
    var lineDashPhase: CGFloat { get }
    
    /// This is the actual dash pattern.
    /// I.e. [2, 3] will paint [--   --   ]
    /// [1, 3, 4, 2] will paint [-   ----  -   ----  ]
    var lineDashLengths: [CGFloat]? { get set }
```
