### ISSUE TITLE
Remove Highlight from bar graph

### ISSUE THREAD

**Issue by HEIDEMAN** [danielgindi/Charts#2337]
I currently have a storyboard where the first page contains a bar graph, when the user selects a bar I push to the next page. When I go back from that page the selected bar is still highlighted and I have to click it again to remove that highlight.

I was trying to remove the highlight in the function:
-(void)chartValueSelected:(ChartViewBase *)chartView entry:(ChartDataEntry *)entry highlight:(ChartHighlight *)highlight;
but I am not having any luck.

I am using Objective C. How do I go about doing this? I don't want to disable the highlighting all together just remove that highlight from the selected bar.

**Comment by liuxuan30** [comment]
`chartValueSelected` is delegate method, calling it by yourself is not supposed to work.
You can remove the highlight by passing nil or empty highlight objects into `open func highlightValue(_ highlight: Highlight?, callDelegate: Bool)`

**Comment by HEIDEMAN** [comment]
How do I call that using objective c?

**Comment by liuxuan30** [comment]
well, check out apple's documentation.
