### ISSUE TITLE
Not all labels shown on horizontal bar chart with large datasets

### ISSUE THREAD

**Issue by tobsterH** [danielgindi/Charts#2339]
Hi,

I have a horizontal bar chart that works perfectly fine for up to 37 bars.
Starting with 38 bars, not all labels are shown on the xAxis anymore.

The code is always the same and I'm setting labelCount to the number of bars I want to show:

`xAxis.labelCount = numberEntries`

Is there a maximum number of bars that can be shown? Or any other ideas?

Many thanks!

**Comment by liuxuan30** [comment]
there is no limit for bars. But there are limits for labels:
```
    /// the number of label entries the axis should have
    /// max = 25,
    /// min = 2,
    /// default = 6,
    /// be aware that this number is not fixed and can only be approximated
```
in `open var labelCount: Int`

However, I need to know what you mean by `not all labels are shown on the xAxis anymore.` if it's expected, or bugs.

Usually, it will not show every label, it will do some calculation to make sure the labels are not overlapped.

**Comment by hernanarber** [comment]
Hi:

I Solved this By Commenting out the Hardcoded limit for the LabelCount within AxisBase.swift, Like this:
```

    open var labelCount: Int
    {
        get
        {
            return _labelCount
        }
        set
        {
            _labelCount = newValue
            // WHY?
            // Thi limits the Amount of Labels We can Display: (Removing)
//            
//            if _labelCount > 25
//            {
//                _labelCount = 25
//            }
//            if _labelCount < 2
//            {
//                _labelCount = 2
//            }
//            
            forceLabelsEnabled = false
        }
    }

```
// I Hope this Helps :-)

**Comment by HPRaval** [comment]
worked for me too....thnx...this should be changed
