### ISSUE TITLE
Population Pyramid

### ISSUE THREAD

**Issue by ottz972** [danielgindi/Charts#2340]
Is there anyone who has been able to make a population pyramid graph something like this?: 
![united_states_population_pyramid](https://cloud.githubusercontent.com/assets/27085691/24831613/16ccc596-1c6b-11e7-86ed-9b8f121cd780.jpg)

Right now I have two horizontal bar charts in my app, one for each gender, but I cannot figure out how to invert the x-axis of the left bar chart (male) in order to make a pyramid shape.

**Comment by liuxuan30** [comment]
Look at ChartsDemo - stacked bar chart negative, similar to yours.
You can either:
1. use value formatter to remove '-' for negative ones like
```objective-c
    customFormatter.negativePrefix = @"";
```
2. use `yAxis.inverted = YES`
like 
<img width="375" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/24843853/3023055e-1dd9-11e7-9722-682fab963a2f.png">
