### ISSUE TITLE
different Bar color based on values

### ISSUE THREAD

**Issue by gsolanki1509** [danielgindi/Charts#2342]
Dear all, 

    I want to show different colors for bars based on its values.

![screenshot_2017-04-09-09-03-06](https://cloud.githubusercontent.com/assets/10267448/24835178/2b180330-1d0b-11e7-89d4-0022f007d956.png)

Can anyone help me please...!!

**Comment by gsolanki1509** [comment]
Currently, im doing as below:



func loadBarChart(_ count: Int, range: Double)
    {
        var yVals = [BarChartDataEntry]()
        for i in 0..<count //).reversed()
        {
            let val = Double((arrBarValues[i]))
            yVals.append(BarChartDataEntry(x: Double(i), y: val!))
        }
        
        var set1 = BarChartDataSet()
        
        if barChartView.data == nil
        {
       
            set1.colors = [UIColor(red: 255.0/255.0, green: 245.0/255.0, blue: 118.0/255.0, alpha: 1.0)  ]
            set1.drawValuesEnabled = false
     
            
            var dataSets = [ChartDataSet]()
            dataSets.append(set1)
            let data = BarChartData(dataSets: dataSets)
            
            let groupSpace = 0.1                 // space between bar groups
            let barSpace = 0.09                  // space between bars within a group
            
            data.barWidth = (1.0 - groupSpace) / 1.75 - barSpace         // 2 = number of bars within a group
            data.groupBars(fromX: 0.0, groupSpace: groupSpace, barSpace: barSpace)
            
            let  marker = YMarkerView( color: NSUIColor.black,
                                       font:  NSUIFont.systemFont(ofSize: 12.0),
                                       textColor: NSUIColor.white,
                                       insets: UIEdgeInsets(top: 8.0, left: 0.0, bottom: 8.0, right: 0.0),
                                       yAxisValueFormatter: HourValueFormatter())
  
            
            
            marker.minimumSize = CGSize(width: CGFloat(80.0), height: CGFloat(40.0))
            barChartView.marker = marker
            
            barChartView.data = data
            barChartView.fitBars = true
            
        }
        else
        {
            set1 = (barChartView.data!.dataSets[0] as! BarChartDataSet )
            set1.values = yVals
            
            barChartView.data?.notifyDataChanged()
            barChartView.notifyDataSetChanged()
            
        }
        
        barChartView.setNeedsDisplay()
    }

**Comment by aelam** [comment]
You can overwrite the colorForIndex 
Or set two yValues for each entry. and colors.first for one yValues[0] the last for yValues[1]

发自我的 iPhone

**Comment by gsolanki1509** [comment]
can you please elaborate ???

**Comment by gsolanki1509** [comment]
My concern is to show bar color as blue if its timing is after 9:00 AM. how can i get the value of that particular bar in that function?

**Comment by gsolanki1509** [comment]
Got it... thanks ..!! :)

**Comment by anasimtiaz** [comment]
@gsolanki1509 Would be nice if you can share the solution

**Comment by thierryH91200** [comment]
@anasimtiaz look at #2334 It is the same principle
 func colorPicker(value : Double) -> NSUIColor etc....

**Comment by anasimtiaz** [comment]
@thierryH91200 Thanks!

**Comment by gsolanki1509** [comment]
Hi @anasimtiaz ,

   Please find my code as below:

I'm using an Array for colors "arrBarColors". And then adding colors to it based on chart Values.

func loadBarChart(_ count: Int, range: Double)
    {
        var yVals = [BarChartDataEntry]()
        for i in 0..<count //).reversed()
        {
            let val = Double((arrBarValues[i]["time"])!)
            print(val!)
            yVals.append(BarChartDataEntry(x: Double(i), y: val!))
            if (Int(arrBarValues[i]["time"]!)!) > 34200 {  // 09:30 AM
                arrBarColors.append(UIColor(red: 234.0/255.0, green: 23.0/255.0, blue: 38.0/255.0, alpha: 1.0))
                
            }else if (Int(arrBarValues[i]["time"]!)!) == 28801 { // 08:00 AM
                arrBarColors.append(UIColor(red: 0.0/255.0, green: 0.0/255.0, blue: 0.0/255.0, alpha: 0.0))
                
            }else{
                arrBarColors.append(UIColor(red: 255.0/255.0, green: 245.0/255.0, blue: 118.0/255.0, alpha: 1.0))
            }
        }
        
        var set1 = BarChartDataSet()
        
        if barChartView.data == nil
        {
            print(yVals)
            
            set1 = BarChartDataSet(values: yVals, label: "DataSet")
            set1.colors = arrBarColors //[UIColor(red: 255.0/255.0, green: 245.0/255.0, blue: 118.0/255.0, alpha: 1.0)  ]//ChartColorTemplates.vordiplom() 255,245,118
            set1.drawValuesEnabled = false
          
            
            var dataSets = [ChartDataSet]()
            dataSets.append(set1)
            let data = BarChartData(dataSets: dataSets)
            
            let groupSpace = 0.1                 // space between bar groups
            let barSpace = 0.09                  // space between bars within a group
            
            data.barWidth = (1.0 - groupSpace) / 1.75 - barSpace         // 2 = number of bars within a group
            data.groupBars(fromX: 0.0, groupSpace: groupSpace, barSpace: barSpace)
            
            let  marker = YMarkerView( color: NSUIColor.black,
                                       font:  NSUIFont.systemFont(ofSize: 12.0),
                                       textColor: NSUIColor.white,
                                       insets: UIEdgeInsets(top: 8.0, left: 0.0, bottom: 8.0, right: 0.0),
                                       yAxisValueFormatter: HourValueFormatter())
     
            
            
            marker.minimumSize = CGSize(width: CGFloat(80.0), height: CGFloat(40.0))
            barChartView.marker = marker
            
            barChartView.data = data
            barChartView.fitBars = true
            
        }
        else
        {
            set1 = (barChartView.data!.dataSets[0] as! BarChartDataSet )
            set1.values = yVals
            
            barChartView.data?.notifyDataChanged()
            barChartView.notifyDataSetChanged()
            
        }
        
        barChartView.setNeedsDisplay()
    }



Hope it helps us :)

**Comment by anasimtiaz** [comment]
Thank you. That helped a lot!
