### ISSUE TITLE
The direction of the two BarChart

### ISSUE THREAD

**Issue by leejayID** [danielgindi/Charts#2345]
I want try do the direction of the two BarChart

![tmp6e7a1b14](https://cloud.githubusercontent.com/assets/9814636/24857366/9345141a-1e1a-11e7-8536-8cda7602138e.png)

How do I do?

**Comment by liuxuan30** [comment]
have no idea what are you saying.

**Comment by leejayID** [comment]
I want to make a chart, there are two barChart, this chart has two Y axis, a reverse order, a positive sequence, As shown in the above

**Comment by liuxuan30** [comment]
it's called stacked chart. Take a look at ChartsDemo.
