### ISSUE TITLE
PieChart overlay lines or dots for select slices in the pie chart

### ISSUE THREAD

**Issue by amidcgcg** [danielgindi/Charts#2347]
Is it possible to draw lines or dots for select (one or more) slices in the pie chart? I want to do something similar to the image. One of the slices has white diagonal lines.
<img width="181" alt="screen shot 2017-04-10 at 10 34 19 am" src="https://cloud.githubusercontent.com/assets/23128769/24874640/3aea5752-1dda-11e7-93c0-d58f63cf6d13.png">

Any help is appreciated.

**Comment by liuxuan30** [comment]
you need to override pie chart renderer `drawDataSets()` to fill something you want.
