### ISSUE TITLE
Limit the number of bars to 10 when the x-axis is made of strings

### ISSUE THREAD

**Issue by amaurySaugrain** [danielgindi/Charts#2351]
Hi there,

I am having an issue, I created a barchartview graph and I would like to limit the number of visible bars to 10 (which is the minimum in setVisibleXRange) and scroll after that. The problem is that my x-axis is made of strings (basically dates and time) therefore it doesn't take in count when I use **barChartView.setVisibleXRange(minXRange: 10.0, maxXRange: 10.0)**.
Do you guys have any idea of how I could manage to do that? 

<img width="369" alt="screen shot 2017-04-11 at 7 59 44 pm" 
src="https://cloud.githubusercontent.com/assets/12099195/24939325/740f19c4-1ef1-11e7-90d2-832ebb49bc72.png">

**Comment by liuxuan30** [comment]
As I don't see your code, first read:
```swift
    /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    ///
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    open func setVisibleXRange(minXRange: Double, maxXRange: Double)
```
Try again after setting your data please.
