### ISSUE TITLE
charts2.5 bottom line render issue

### ISSUE THREAD

**Issue by billxie1988** [danielgindi/Charts#2352]
![2017-04-12 11 42 42](https://cloud.githubusercontent.com/assets/8359662/24940381/5012046c-1f75-11e7-958c-918357772bde.png)
when I fast scroll the chartview it behavior this way

**Comment by billxie1988** [comment]
I tested same code 2.3 is fine

**Comment by danielgindi** [comment]
Yes but have you tested on 3.0? 2.5 is pretty much outdated. How do you even manage to still compile for Swift 2? You need to update your Xcode...

**Comment by billxie1988** [comment]
my Xcode is 8.3，OK I‘m going to try 3.0

**Comment by billxie1988** [comment]
3.0 is OK，but We need to stuff quiet a lot things on adaption. I still want to know the reason why cause this problem. Or is there any trick way to avoid this problem.Thanks
