### ISSUE TITLE
Why my LineChartDataSet's line is behind the bar?

### ISSUE THREAD

**Issue by zip520123** [danielgindi/Charts#2354]
![2017-04-12 3 24 53](https://cloud.githubusercontent.com/assets/1498003/24949790/74b00d2e-1fa1-11e7-9c03-339de0b156b2.png)

I follow the demo code "Combined Chart".
There is my "LineChartDataSet" setting below.
```swift
set1 = LineChartDataSet(values: yVals, label: "")
set1?.lineDashLengths = [1 ,0]
set1?.lineWidth = 1.0
set1?.circleRadius = 4.0
set1?.drawCircleHoleEnabled = false
set1?.formSize = 15.0
set1?.setColors(UIColor.red)
set1?.setCircleColor(UIColor.red)
set1?.mode = .stepped
set1?.drawValuesEnabled = false
```
and BarChartDataSet setting.
```swift
set1 = BarChartDataSet(values: yVals, label: "")
set1?.setColors(UIColor(red: 0.071, green: 0.459, blue: 0.835, alpha: 1.00))
set1?.drawValuesEnabled = false
```
How can I bring LineChartDataSet's line to front?

**Comment by thierryH91200** [comment]
set1
    let dataLine = LineChartData()
....  what you want...
    dataLine.addDataSet(set1)

set2 = BarChartDataSet(values: yVals, label: "")
... what you want ..
    let dataBar = BarChartData()
    dataBar.addDataSet(set2)

and

   let data = CombinedChartData()
    data.lineData = dataLine
    data.barData = dataBar

**Comment by zip520123** [comment]
My fault.
I fix it by change
```swift
chartView.drawOrder = [DrawOrder.line.rawValue ,DrawOrder.bar.rawValue ]
```
to 
```swift
chartView.drawOrder = [DrawOrder.bar.rawValue ,DrawOrder.line.rawValue ]
```
