### ISSUE TITLE
Crash in YAxisRendererRadarChart

### ISSUE THREAD

**Issue by owenbirdsall** [danielgindi/Charts#2356]
Crashes on line 137: axis.decimals = Int(ceil(-log10(interval)))

When interval is 0.
In my case this is happening when rawInterval is 0.05, interval then gets set to 0, and -log10(0) results in NaN which causes ceil to crash.

**Comment by liuxuan30** [comment]
why rawInterval is 0.05 leads to interval 0?

**Comment by owenbirdsall** [comment]
That's what I believe I saw in the debugger when I trapped the exception... I will try again to verify the exact value for you. Any case would it not make sense to guard against zero here?

**Comment by owenbirdsall** [comment]
If you set range to be 0.05, then rawInterval becomes 0.0083* and in turn interval becomes 0. Which results in a crash.

**Comment by owenbirdsall** [comment]
Presumably changing line 135 to:
`
        if interval > 0 && interval < 1
`
Would fix the issue?

**Comment by liuxuan30** [comment]
I need you to give more details on how this leads to crash, and what's the test data, so we can reproduce with ChartsDemo. There has been a long time for this kind of issue.

**Comment by owenbirdsall** [comment]
There is a vulnerability because of this piece of code on line 137 of YAxisRendererRadarChart:
`axis.decimals = Int(ceil(-log10(interval)))`

There is no guard against interval being zero, and if it is zero it will cause a crash. As far as I can see there is nothing preventing data being used in a radar chart that can result in an interval of zero.

In my case I had a range of 0.05, which caused rawInterval to be 0.0083* and hence interval is zero... hence the crash.

A simple guard against zero whenever you use this `Int(ceil(-log10(interval)))` piece of code should fix your issues.

**Comment by liuxuan30** [comment]
Why `interval` in your case is `Int 0`? It's supposed to be Double value. 

I tried with 0.05 range like below, it still does not crash.
```swift
(lldb) po range
0.050000000000000003

(lldb) po rawInterval
0.01

(lldb) po interval
0.01

(lldb) po Int(ceil(-log10(interval)))
2
```
The interval is a float decimal value, not as Int 0.

**Comment by owenbirdsall** [comment]
It's not an integer, it's a double - but a double can still be zero (i.e. 0.0)
...and -log10(0.0) results in a NaN
...and ceil(NaN) causes a crash

**Comment by owenbirdsall** [comment]
Here are the values I have in my debugger at the point of my crash:
<img width="379" alt="screen shot 2017-04-19 at 11 21 32" src="https://cloud.githubusercontent.com/assets/11388290/25175379/705a0f3a-24f2-11e7-9bf7-b010dd0ea38c.png">

**Comment by owenbirdsall** [comment]
From what I can see interval is >0.0 until it reaches the following block of code:

`        // Normalize interval
        let intervalMagnitude = ChartUtils.roundToNextSignificant(number: pow(10.0, floor(log10(interval))))
        let intervalSigDigit = Int(interval / intervalMagnitude)
        
        if intervalSigDigit > 5
        {
            // Use one order of magnitude higher, to avoid intervals like 0.9 or
            // 90
            interval = floor(10 * intervalMagnitude)
        }`

This floor operation can cause interval to go to 0.0

**Comment by liuxuan30** [comment]
Well range=0.05 will not crash, but range=0.3785 will. Looks like we missed some corner cases
As rawInterval is 0.06308, the interval is 0.06, and intervalMagnitude=0.01, intervalSigDigit=6

Now the problem is intervalSigDigit=6 will trigger:
>        if intervalSigDigit > 5
        {
            // Use one order of magnitude higher, to avoid intervals like 0.9 or
            // 90
            interval = floor(10 * intervalMagnitude)
        }

and unfortunately, floor(10 * 0.01) is 0.0 indeed

I can't say this is a bug or design flaw, but right now you can use
`interval = floor(10 * intervalMagnitude) == 0.0 ? interval : floor(10 * intervalMagnitude)` to workaround.

**Comment by owenbirdsall** [comment]
Thanks for looking into this, much appreciated.
