### ISSUE TITLE
Horizontal Bar Chart rightAxis default maximum space

### ISSUE THREAD

**Issue by thierrykoppenol** [danielgindi/Charts#2363]
Hi, 

I'm trying to create a Horizontal Bar Chart where both ends (right and left axis) are aligned to the left and right side of the screen, with some offset. I've used the following code to remove both axises and set the axis minimum to zero. 

` self.leftAxis.enabled = false`
` self.leftAxis.axisMinimum = 0`
` self.rightAxis.enabled = false`
` self.rightAxis.axisMinimum = 0`

The leftAxis is aligned the way is expecting it. However, the rightAxis is still showing some blank space. I can check this size with:

`self.rightAxis.getRequiredHeightSpace()`

Is there a way to remove or set this required space? I've tried to set spaceTop without success.

Here is an image as an example:

![img_0010](https://cloud.githubusercontent.com/assets/22367581/25037613/6b3c04be-20fa-11e7-896d-c441f486cfe6.PNG)

**Comment by thierryH91200** [comment]
<img width="1752" alt="capture d ecran 2017-04-14 a 10 02 09" src="https://cloud.githubusercontent.com/assets/6251463/25037511/bf83fb36-20f9-11e7-975a-91bcaca9f28a.png">

xAxis is Green
leftAxis is Blue
rightAxis is Red

Do you agree ??

**Comment by thierrykoppenol** [comment]
Agree. When i enable the xAxis is will show the following: 

![img_0011](https://cloud.githubusercontent.com/assets/22367581/25037830/9b05da02-20fb-11e7-86e5-b15e5b7176e2.PNG)

Maybe i wasn't clear before, but i want to remove the white space on the right side of the chart. I've added the current situation without the xAxis enabled in the Question above.

**Comment by thierryH91200** [comment]
ok i have understand 


<img width="1974" alt="capture d ecran 2017-04-14 a 10 57 58" src="https://cloud.githubusercontent.com/assets/6251463/25038935/7b5beba0-2101-11e7-8a90-60fb68e8a6c6.png">

**Comment by thierryH91200** [comment]
and now it's ok

<img width="1971" alt="capture d ecran 2017-04-14 a 11 07 58" src="https://cloud.githubusercontent.com/assets/6251463/25039195/bd652100-2102-11e7-8987-026c2c986337.png">

**Comment by thierrykoppenol** [comment]
Thanks, didn't know I had to set both the leftAxis and rightAxis Spaces

**Comment by thierryH91200** [comment]
After a few tests
In fact there is only the left side that walks
The right side has no effect



```
//: ### LeftAxis
let leftAxis = chartView.leftAxis
leftAxis.labelFont = NSUIFont.systemFont(ofSize: CGFloat(12.0))
leftAxis.drawAxisLineEnabled = true
leftAxis.drawGridLinesEnabled = true
leftAxis.axisMinimum = 0.0
leftAxis.enabled = true
leftAxis.spaceTop    = 0.0
leftAxis.spaceBottom = 0.0


//: ### RightAxis
let rightAxis                  = chartView.rightAxis
rightAxis.labelFont            = NSUIFont.systemFont(ofSize: CGFloat(12.0))
rightAxis.drawAxisLineEnabled  = true
rightAxis.drawGridLinesEnabled = false
rightAxis.axisMinimum          = 0.0
rightAxis.enabled              = true
rightAxis.spaceTop    = 0.5
rightAxis.spaceBottom = 0.5

```
