### ISSUE TITLE
How to properly reset zoom on data refresh?

### ISSUE THREAD

**Issue by RedditGithub** [danielgindi/Charts#2367]
I only want to show the last 5 bars in my bar chart initially. My code works on the chart's initial data load but when I change its data and try zoom in on only the last 5 bars of the new data it zooms in too much and only 2 bars are shown. Here's how I've implemented it:

```
let chartData = BarChartData(dataSet: chartDataSet)

barChartView.data = chartData
barChartView.notifyDataSetChanged()

//fetchedResultsController.sections?.count is total number of bars

let xScale: Float = Float((fetchedResultsController.sections?.count)! / 5)
barChartView.resetZoom()
barChartView.zoom(scaleX: CGFloat(xScale), scaleY: 1.0, x: 0.0, y: 0.0)
barChartView.moveViewToX(Double((fetchedResultsController.sections?.count)! - 5))
```

This is called every time the chart's data is changed. However it zooms in too much even though I'm caling resetZoom(). Can anybody help me properly zoom in the the desired location every time?

**Comment by seenoevo** [comment]
@RedditGithub did you figure this out?..I'm trying to do the same thing

**Comment by ZaidSA** [comment]
[This](https://github.com/danielgindi/Charts/issues/267) helped me.
