### ISSUE TITLE
Crash on computeAxisValues of Bar Chart

### ISSUE THREAD

**Issue by MarksCode** [danielgindi/Charts#2368]
My app is crashing when I call `barChartView.notifyDataSetChanged()`. This is the specific line it crashes on.

`let intervalMagnitude = ChartUtils.roundToNextSignificant(number: pow(10.0, Double(Int(log10(interval)))))` in the `open func computeAxisValues(min: Double, max: Double)` function.

The error message is 

> fatal error: Double value cannot be converted to Int because it is either infinite or NaN

This happens when I call `notifyDataSetChanged()` after setting the chart's `data` to a `BarChartDataSet` with 0 entries.

Anybody know how to get around this?

**Comment by MarksCode** [comment]
Extra info on my graph's configuration:

```
        let xaxis = barChartView.xAxis
        xaxis.labelPosition = .bottom
        xaxis.drawGridLinesEnabled = false
        xaxis.granularity = 1.0
        barChartView.rightAxis.enabled = false
        barChartView.legend.enabled = false
        barChartView.chartDescription?.text = ""
        barChartView.leftAxis.granularityEnabled = true
        barChartView.leftAxis.granularity = 1.0
        barChartView.scaleYEnabled = false
```

**Comment by josman185hotm** [comment]
hello @MarksCode , did you find the solution to this?

**Comment by laurenyew-ua** [comment]
What was the solution @MarksCode

**Comment by mccarron** [comment]
@MarksCode also been seeing this crash, what was your solution?

**Comment by dkawashima** [comment]
Also seeing this crash @MarksCode
