### ISSUE TITLE
Compile error on Release build configuration

### ISSUE THREAD

**Issue by capecrawler** [danielgindi/Charts#2372]
Running on device or simulator when developing works but when archiving, throws an error.

![screen shot 2017-04-19 at 11 23 52 am](https://cloud.githubusercontent.com/assets/1147223/25162099/b8254a1e-24f2-11e7-8294-941895eeac9f.png)

Using the code v3.0.2, I have manually imported source files for this project for the reason that I need to subclass and override some private methods.

**Comment by capecrawler** [comment]
Found out that when trying to build on Release build configuration, it throws this error.

**Comment by capecrawler** [comment]
Changing optimization level for the Swift compiler-Code generation from (Fast, Whole Module Optimization) to (Fast, Single-File Optimization) somehow fixes the issue.

**Comment by liuxuan30** [comment]
have no idea :) should be swift problem..
