### ISSUE TITLE
Graph is being drawn outside of visible area

### ISSUE THREAD

**Issue by daffodilistic** [danielgindi/Charts#2373]
![](http://i.imgur.com/ntTBxZ5.png)

Hi,

I'm using the charts library as a custom renderer in a PCL project. As seen in this screenshot, the render area for the line chart seems to be drawn offscreen. Before data is loaded however, the text saying "No data is available" is shown.

The pie chart and bar chart are also exhibiting this "offscreen drawing" behavior as well. Am I coding the custom renderer wrongly somewhere?

**Comment by liuxuan30** [comment]
Start with your UIView frame first.
