### ISSUE TITLE
y-labels position is wrong，when i set autoScaleMinMaxEnabled = YES

### ISSUE THREAD

**Issue by KevinZK** [danielgindi/Charts#2379]
i set autoScaleMinMaxEnabled = YES ,scaleYEnabled = NO and scaleXEnabled = YES, i set "setVisibleXRangeMaximum"and "setVisibleXRangeMinimum" after it have data. y-labels position is wrong, i must touch View  or scale view to make it correct position。i don't know  is this a bug, or i don't use it correctly。
Look forward to your reply

**Comment by liuxuan30** [comment]
can you explain y-labels position is wrong with a screenshot?

**Comment by KevinZK** [comment]
![right](https://cloud.githubusercontent.com/assets/15150546/25259746/90981b50-267a-11e7-964f-e538366894c1.jpeg)
![wrong](https://cloud.githubusercontent.com/assets/15150546/25259747/909bbfb2-267a-11e7-9c23-af7aec70f863.jpeg)
show 5 y_labels ,is normal . The other is wrong

**Comment by KevinZK** [comment]
in the YAxisRenderer.swift file, when show the view for the first time, the positions[i].y 's value is inaccurate in function drawYLabels.  then，when i touch view or zoom  the view，the positions[i].y 's value will be right. I don't know how the internal implementation,I can't find the method to solve this problem

**Comment by liuxuan30** [comment]
I can't tell what's wrong, but you can check some places:
```swift
        if _autoScaleMinMaxEnabled
        {
            autoScale()
        }
```
`autoScaleMinMaxEnabled` just call `autoScale()`, no other things when I search in the library.
You can start debug here.

For y axis labels, take a look at `computeAxisValues()` to check how `axis.entries` is generated, when the label count is wrong.

**Comment by liuxuan30** [comment]
BTW, are you able to reproduce it with ChartsDemo? 
Basically, you enabled many features, while I am not sure if they are conflict.

**Comment by KevinZK** [comment]
[
![wechatimg19](https://cloud.githubusercontent.com/assets/15150546/26052143/13b859e4-3997-11e7-9453-d8c36d7cbbd4.jpeg)
](url)

@liuxuan30  i fixed YAxis labels position and cooperate with LimitLine。values is not corresponding,

**Comment by thirdson** [comment]
hi @liuxuan30  seam like after adjust the viewport -- either scale or realtime feed in , although the Y axis's max and min value recalculated,  but the Y axis not refresh or redraw,  if you manually scale the view the Y axis will adjust correctly.

**Comment by thirdson** [comment]
@KevinZK  possible you should parse all the configuration flag initialized or changed between here.

**Comment by thierryH91200** [comment]
_autoScaleMinMaxEnabled can not work if the right axis is used and not left

 ```
  internal func autoScale()
    {
        guard let data = _data
            else { return }
        
        data.calcMinMaxY(fromX: self.lowestVisibleX, toX: self.highestVisibleX)
        
.....
}
```


  ```
 /// - returns: The highest x-index (value on the x-axis) that is still visible on the chart.
    open var highestVisibleX: Double
    {
        var pt = CGPoint(
            x: viewPortHandler.contentRight,
            y: viewPortHandler.contentBottom)
        
        getTransformer(forAxis: .left).pixelToValues(&pt)
        
        return min(xAxis._axisMaximum, Double(pt.x))
    }
```
