### ISSUE TITLE
Chart Won't Display

### ISSUE THREAD

**Issue by pktrkts** [danielgindi/Charts#2381]
Hi,

I have a class hierarchy that looks complex.  I have a ChartViewBase object in a UIView.  I have a ChartViewControllerBase, which is a base class for all the chart view controllers.  I have a LineAndBarChartViewControllerBase, a BarChartViewControllerBase, and a class I'll call DerivedBarChartViewController.  Each of these classes has code in it that contributes to the chart, with the bulk of the code in LineAndBarChartViewControllerBase.  I have the UIView as the delegate of the ChartViewBase object (though I'm not sure this is correct).  Any ideas on why the chart won't display?  All I see is a black box, and I've spent a few hours debugging and getting nowhere.  Any ideas on what I might be doing wrong would be greatly appreciated.  Thanks!

Sincerely,
Sean

**Comment by liuxuan30** [comment]
usually you need to post a demo project so we know what's going on.
