### ISSUE TITLE
Does it support XO line(American CandleStick)?

### ISSUE THREAD

**Issue by aelam** [danielgindi/Charts#2382]
![timg](https://cloud.githubusercontent.com/assets/232337/25272787/cb4c68c8-26bb-11e7-9bbe-1f469debc19c.jpeg)

**Comment by liuxuan30** [comment]
No I think. But you can write on based on the framework.

**Comment by aelam** [comment]
It does support! I've found the CandleDataSet.showCandleBar is what I want
Thanks!

**Comment by liuxuan30** [comment]
what? Exactly the same as your screenshot?

**Comment by thierryH91200** [comment]
with my playground 

![capture d ecran 2017-04-25 a 05 12 01](https://cloud.githubusercontent.com/assets/6251463/25367423/d8657e02-2975-11e7-913f-ecd6b72583d7.png)

**Comment by aelam** [comment]
@liuxuan30 Right, I think so. (No need of the texts of high, low, open, close )
@thierryH91200  I've done already. Thanks anyway !

**Comment by liuxuan30** [comment]
Great to know we already supported this :)
