### ISSUE TITLE
"chartValueSelected" is not getting called. 

### ISSUE THREAD

**Issue by SatishBirajdar** [danielgindi/Charts#2383]
I did all things asked on [http://stackoverflow.com/questions/35038724/tap-callback-on-bar-in-barchart-in-ios-charts](url) . @danielgindi  did you do any changes in the library, preventing to detect the Bar tap event? Thanks in advance.

```
import UIKit
import Charts

class QuarterlyForecastOverviewViewController: UIViewController, ChartViewDelegate {
    
    @IBOutlet weak var barChartView: BarChartView!
    
    var months: [String]!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        months = ["Jan", "Feb", "Mar", "Apr"]
        let unitsSold = [20.0, 4.0, 6.0, 3.0]
        
        setChart(dataPoints: months, values: unitsSold)
        
        barChartView.notifyDataSetChanged()

        barChartView.pinchZoomEnabled = false
        barChartView.dragEnabled = false
        barChartView.setScaleEnabled(false)
        
        barChartView.xAxis.labelPosition = XAxis.LabelPosition.bottom
        barChartView.xAxis.labelTextColor = UIColor.gray
        barChartView.xAxis.axisLineColor = UIColor.white
        barChartView.leftAxis.axisMinValue = 0
        barChartView.leftAxis.axisLineColor = UIColor.red
        barChartView.leftAxis.removeAllLimitLines()
        barChartView.leftAxis.drawZeroLineEnabled = false
        barChartView.leftAxis.drawLimitLinesBehindDataEnabled = true
        barChartView.leftAxis.labelTextColor = UIColor.white
        barChartView.rightAxis.enabled = false
        barChartView.extraBottomOffset = 10.0
        barChartView.extraRightOffset = 10.0
        barChartView.highlightPerTapEnabled = true
        barChartView.drawGridBackgroundEnabled = false
        barChartView.xAxis.drawGridLinesEnabled = false
        barChartView.leftAxis.drawGridLinesEnabled = false
        barChartView.descriptionText = ""
        
        barChartView.xAxis.granularity = 1
        barChartView.xAxis.granularityEnabled = true
        barChartView.xAxis.labelCount = 4
        
        barChartView.delegate = self
    }
    
    func setChart(dataPoints: [String], values: [Double]) {
        
        let formatter = BarChartFormatter()
        formatter.setValues(values: dataPoints)
        let xaxis:XAxis = XAxis()
        
        barChartView.noDataText = "You need to provide data for the chart."
        var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<dataPoints.count
        {
            let dataEntry = BarChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "Billing Hours")
        
        let chartData = BarChartData(dataSet: chartDataSet)

        xaxis.valueFormatter = formatter
        barChartView.xAxis.labelPosition = .bottom
        barChartView.animate(xAxisDuration: 1.0, yAxisDuration: 1.0, easingOption: .easeInBounce)
        chartDataSet.colors = [UIColor(red: 230/255, green: 126/255, blue: 34/255, alpha: 1)]
        barChartView.xAxis.drawGridLinesEnabled = false
        barChartView.xAxis.valueFormatter = xaxis.valueFormatter
        barChartView.chartDescription?.enabled = false
        barChartView.legend.enabled = true
        barChartView.rightAxis.enabled = false
        barChartView.data = chartData
  
    }
    
    func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: Highlight) {
        print("Bar selected")
    }
    
}


@objc(BarChartFormatter)
public class BarChartFormatter: NSObject, IAxisValueFormatter
{
    var names = [String]()
    
    public func stringForValue(_ value: Double, axis: AxisBase?) -> String
    {
        return names[Int(value)]
    }
    
    public func setValues(values: [String])
    {
        self.names = values
    }
}
```

**Comment by liuxuan30** [comment]
This is nothing changed for the delegate. Please debug on your side to give proofs.

**Comment by SatishBirajdar** [comment]
Okay, I have re-arranged barChartView.xAxis.labelCount = 4 and setChart(dataPoints: months, values: unitsSold), thanks for the suggestion. But the issue isn't fixed yet.

In ChartViewBase Class - 

delegate!.chartValueSelected?(self, entry: entry!, highlight: h!) = nil       , but, 
delegate = SatishChartsDemo.QuarterlyForecastOverviewViewController

So my concern:
1. why is delegate!.chartValueSelected?(self, entry: entry!, highlight: h!) = nil, since we already have func chartValueSelected defined in QuarterlyForecastOverviewViewController class ?

2. In QuarterlyForecastOverviewViewController, am I defining the function chartValueSelected, correctly?

Thanks in advance.

**Comment by thierryH91200** [comment]
try 

```
    public func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        print("Bar selected")
    }
```
and not

    func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: Highlight) {
        print("Bar selected")
    }

**Comment by SatishBirajdar** [comment]
@thierryH91200 Yes, I tried 

```
    public func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        print("Bar selected")
    }
```

Didn't worked. Can you please provide the link of the sample project in Swift, where function chartValueSelected() is working? 

Thanks in advance.

**Comment by thierryH91200** [comment]
[BarChartViewController.swift.zip](https://github.com/danielgindi/Charts/files/952302/BarChartViewController.swift.zip)

**Comment by SatishBirajdar** [comment]
@thierryH91200 Thanks, this is really helpful. :)

**Comment by anoo-radha** [comment]
@SatishBirajdar did you get the delegate chartValueSelected to work? I ran into the same problem of the delegate not being called.
Thanks in advance

**Comment by SatishBirajdar** [comment]
@anoo-radha Try the .zip sample that @thierryH91200 uploaded

**Comment by pabloruan0710** [comment]
@anoo-radha and @SatishBirajdar 
I have this same problem, did you manage to solve it?

**Comment by renish007** [comment]
I have applied all above mentioned steps but it's not working. Please review code on below attached link and let Mme know what I'mm missing
https://stackoverflow.com/questions/67197708/chartvalueselected-chartview-chartviewbase-entry-chartdataentry-highlight

**Comment by esma01** [comment]
Even the sample project is not working! Only the last and middle data points can be selected. For other data points, I see `chartValueNothingSelected` in the console.

**Comment by tolgaytoklar** [comment]
> Even the sample project is not working! Only the last and middle data points can be selected. For other data points, I see `chartValueNothingSelected` in the console.

I have the exact same problem

**Comment by esma01** [comment]
The latest version has a data selection bug. I downgraded to 3.5.0 and the selections work now. @tolgaytoklar

**Comment by tolgaytoklar** [comment]
> The latest version has a data selection bug. I downgraded to 3.5.0 and the selections work now. @tolgaytoklar

Thank you so much, it also works for me now.

**Comment by sparke16** [comment]
I've just run into this issue with a line chart and assume it's the same issue, had upgraded from the cocoapod to the Swift Package Manager 4.0.2 and banged my head against the table for several hours trying to find out what was up. Hopefully this is rectified soon!

**Comment by trunghvbk** [comment]
Hi, is this issue fixed on the stable version. I found `chartValueSelected` not called still in ver `4.1`.

**Comment by MorGoren** [comment]
Hi. Ver 4.1.1 still has this problem, is there an update for the fix?
