### ISSUE TITLE
Is having a ChartViewBase inside a custom UIView even possible?

### ISSUE THREAD

**Issue by pktrkts** [danielgindi/Charts#2384]
Hi,

I posed as an issue recently what I'm trying to do, and someone responded that it might not be possible to do, but they didn't sound certain.  I need to know if what I'm trying to do is even possible.  I have a custom uiview that holds other gui elements as well as a ChartViewBase.  Can this work?  If so, which class would be the ChartViewDelegate- the UIView that holds the ChartViewBase or the ViewController that holds UIView that holds the ChartViewBase?  I do really need to know the answer to these questions, and it is DEFINITELY a relevant topic as someone else might want to do something similar.  Also, any relevant details on how you might make such an arrangement work would be fantastic.  Thanks for your consideration of this matter.

Sincerely,
Sean

PS If you are feeling ambitious and want to see the code for what I'm trying to do, it's at [http://stackoverflow.com/questions/43554368/trouble-getting-chart-object-to-work-in-custom-uiview]

**Comment by liuxuan30** [comment]
You can just reply to the closed thread next time, I will reply when it has update. A UIView can absolutely hold sub UIViews, by `addSubView()`.

It feels like you are not very familiar with UIView, so I suggest you take a look at it first.

The point is you need to know your sub view's frame in order to see it. Using Xcode view debugging can help you understand where's your sub view.

**Comment by pktrkts** [comment]
Okay, I do have some experience with custom UIViews.  I have two other ones and both of them work correctly.  You seemed to indicate that what I was trying to do was impossible, but you didn't seem definitive or certain on that point.  If what I'm trying to do cannot be done, I most certainly need to know that.  It seems to me that what I'm trying to do should be possible, but by no means am I an expert with the chart library that we are talking about.

It is an interesting idea to add the Chart programmatically.  At the moment, I have a UIView of type ChartViewBase inside my UIView in the xlb file.  Maybe the correct way to do this is to not have the chart view in the xlb file and add the chart view programmatically?  I would like to think the way I'm trying to do it should work, but the black rectangle in the middle of my view controller says I'm definitely doing something wrong.  

Thank you for your consideration of this matter.  I hope you are having a good day. =)

**Comment by pktrkts** [comment]
I've got it to work now.  Thanks for your suggestion to add the chart programmatically instead of through the xlb file! =)
