### ISSUE TITLE
Y Axis range calculation is incorrect for Bar Charts

### ISSUE THREAD

**Issue by franqueli** [danielgindi/Charts#2386]
When calculating the y axis range in the YAxis.swift calculate function if only one chart value is provided to the chart the range calculation is always 2.0.
This is because the dataMin and dataMax values passed to the method are the same. 

It seems to me the range should always be calculated from the zero value. 
If both dataMin and dataMax passed to the calculate method are positive, the range should be (dataMax - 0). 
If both dataMin and dataMax passed to the calculate method are negative, the range should be 0 -dataMin.
if dataMin is negative and dataMax is positive, the  range should be dataMax - dataMin.

Is the current behavoir expected?
![barchartsmallrange](https://cloud.githubusercontent.com/assets/74138/25320646/eaf72e9e-2876-11e7-8aa5-61ebe9b84d56.png)

**Comment by liuxuan30** [comment]
As you just have one value, it's expected.
>It seems to me the range should always be calculated from the zero value.

If you want from 0, just set `axisMinValue = 0`

**Comment by franqueli** [comment]
I don't think that works. The values I'm consuming come from a service. I don't know beforehand if the values are positive or negative. If I get a negative value from the service setting axisMinValue to 0 makes the chart not render correctly.

**Comment by liuxuan30** [comment]
You just want pure negative value or positive value to start from 0, and some other people don't want this. We can't make the decision so it's you to make. The library will use the max/min value to decide the range if you don't touch anything, so it usually works. 

For your case, you can add a simple scan of your data to see if you want to start from 0 before displaying the chart.
