### ISSUE TITLE
Chart Top label Issue

### ISSUE THREAD

**Issue by farazhaider88** [danielgindi/Charts#2392]
hi everyone,
very nice chart library, i really admire the work you guys put on this library. i have an issue using a chart library, i need this below chart.
<img width="376" alt="screen shot 2017-04-26 at 10 14 07 am" src="https://cloud.githubusercontent.com/assets/1468654/25424462/7292dab6-2a79-11e7-8281-91e9512a1426.png">
after playing around with the chart library (linechart1) i have get this below figure.
<img width="300" alt="screen shot 2017-04-26 at 12 12 25 pm" src="https://cloud.githubusercontent.com/assets/1468654/25424614/f7c9fef8-2a79-11e7-9414-207e84cdd9d5.png">
can anyone please let me know how can i get date on top of the chart. as 25 may is here?

**Comment by liuxuan30** [comment]
two ways:
1. enabled `drawValues()`  and override the method to change the location and for only some values
2. to have more flexibility, or just need when highlighted, use `ChartMarker`. There are some demo markers available in the demo.
