### ISSUE TITLE
Appending Units(i.e. m/s, mpg, etc) to yaxis??

### ISSUE THREAD

**Issue by xutedin253** [danielgindi/Charts#2394]
Hey I was wondering if there was a way to append units to my y axis? not the data points but on the y axis. I've been looking through these issues and I can't seem to find any.
I'm working with a line chart btw

Cheers,
Thomas

**Comment by linfeng** [comment]
how to di it?

**Comment by coolcool1994** [comment]
Yeah it seems like value formatter only works for bar charts
