### ISSUE TITLE
moveViewToX() has no affect on a chart whose frame has not been set yet

### ISSUE THREAD

**Issue by feosuna1** [danielgindi/Charts#2395]
If you call `moveViewToX()`, on a chart that does not have a frame yet, the `moveViewToX()` doesn't do anything.  

In my use case, I have a chart view that is laid out using constraints. The data is set on the chart before auto layout engine has had a chance to layout the view.  The view effectively has CGRect.zero for its frame.

The problem is that the view port jobs are ran [before](https://github.com/danielgindi/Charts/blob/5288c2500c56d18e2a166b6783cee2626e522354/Source/Charts/Charts/ChartViewBase.swift#L916) `notifyDataSetChanged()`. If the jobs were ran afterwards, `moveViewToX()` would work as expected.

**Comment by feosuna1** [comment]
This is the expected result:

![image](https://cloud.githubusercontent.com/assets/12620/25461176/7a81a630-2ab5-11e7-9fc0-6974e4a7cc0b.png)

This is the actual result:

![image](https://cloud.githubusercontent.com/assets/12620/25461197/90bdfcd2-2ab5-11e7-8cbc-2fdae815f967.png)

Here's a sample project demonstrating the behavior: [MoveViewToX.zip](https://github.com/danielgindi/Charts/files/960018/MoveViewToX.zip)

**Comment by liuxuan30** [comment]
why `chart that does not have a frame yet` in the first place? What's the scenario?

**Comment by feosuna1** [comment]
@liuxuan30 The attached project (https://github.com/danielgindi/Charts/files/960018/MoveViewToX.zip) reproduces the problem.

Inside of my root view's `viewDidLoad()` I do the following:
1. Create the chart
2. Set the data
3. Restrict the chart's visible min and max x-range
4. Call `moveViewToX()`
5. Add the chart view to the view controller's view
6. Add constraints to the chart view

Initially the chart has no constraints, eventually the layout engine will assign it a frame.  When it does assign it a frame, `ChartViewBase.observeValue(forKeyPath:of:change:context:)` will fire. This function first runs all the view port jobs (in my case the view port job is the `moveViewToX()`) then it will run `notifyDataSetChanged()` that eventually calls `calculateOffsets()`.  This `calculateOffsets()` call mutates properties on the view port handler. My operating theory is that `calculateOffsets()` is stomping all over the changes made in `moveViewToX()`. By deferring the view port jobs to after calling `notifyDataSetChanged()`, `moveViewToX()` behaves as I expect.

**Comment by liuxuan30** [comment]
I see. However I guess @danielgindi need to take a look to avoid any side effect. I'm not familiar with the view port jobs.

**Comment by RamblinWreck77** [comment]
I just ran into this and it was driving me nuts. 

I was calling my setupChart function (which eventually calls moveViewToX) inside viewDidLoad and it would occationally do nothing (or for large values of X, seemingly greater than 50% of xMax... as well as more often on iPad than iPhones).

Moving my setup function to viewDidLayoutSubviews fixed the problem in 100% of scenarios. This is on 3.2.2/Swift 5/iOS 12.2. 

I'm not sure this is a bug with Charts, but perhaps the documentation could be updated to warn devs to not make this (IMO) easy-to-do mistake.

**Comment by drewster99** [comment]
viewDidLayoutSubviews didn't work for me, nor did putting it immediately after notifyDataSetChanged.
I can make it work on a delay (DispatchQueue.main.asyncAfter(.now() + (1.0/60.0)) but not otherwise.
