### ISSUE TITLE
 'Charts/Charts.h' file not found when tried build using "XCODEBUILD" command in terminal

### ISSUE THREAD

**Issue by Naveen-kosuri** [danielgindi/Charts#2397]
Hi Daniel,

Thanks for the super framework.

I am trying create CI for my project using jenkins. Build is failing continuously because of the below mentioned issue.  I have integrated charts as mentioned in USAGE tab. I can also reproduce the issue using terminal with 'XCODEBUILD' command. Kindly look into the issue.

Configuration details:
xcode 8.2
Objective c project

fatal error: 
      'Charts/Charts.h' file not found
#import <Charts/Charts.h>
        ^
1 error generated.

Thanks,
Naveen

**Comment by liuxuan30** [comment]
It's obscure to say what's wrong. You can try our CI instructions first. I don't see any issues using xcodebuild cmd.

**Comment by Naveen-kosuri** [comment]
I followed all the instructions in Usage section, it is working fine when i run it using Xcode . Kindly let me know if there are any CI specific instructions. I tried to 'Xcodebuild' on ChartsDemo project it give me the below error.

/Users/Naveen/Downloads/Charts-3.0.0/Source/ChartsRealm/Data/RealmBarLineScatterCandleBubbleDataSet.swift:14:8: error: no such module 'Charts'
import Charts
       ^

** BUILD FAILED **

**Comment by liuxuan30** [comment]
I don't have 3.0.0 code right now, as we have already move ChartsRealm to a different repo to remove the dependency. If you don't need Realm, you can use latest code and use Xcode 8.3.

I have no trouble running 
>xcodebuild -project 'ChartsDemo.xcodeproj' -scheme 'ChartsDemo' -configuration 'Debug' -sdk iphonesimulator -destination name='iPhone 7' clean build 

with branch master.

If you need Realm, then, you need to know your build settings, target dependencies, etc. Better to check up xcodebuild parameters on your side.

**Comment by Naveen-kosuri** [comment]
Hi, I have integrated 3.0.2. now i am able to build using the above command for my project. But build is failing for 'Release' configuration. Kindly let me know if i am missing something.

**Comment by liuxuan30** [comment]
We have no idea as well. You better start from your error logs.

**Comment by Andy1984** [comment]
> > I followed all the instructions in Usage section, it is working fine when i run it using Xcode . Kindly let me know if there are any CI specific instructions. I tried to 'Xcodebuild' on ChartsDemo project it give me the below error.
> > /Users/Naveen/Downloads/Charts-3.0.0/Source/ChartsRealm/Data/RealmBarLineScatterCandleBubbleDataSet.swift:14:8: error: no such module 'Charts'
> > import Charts
> > ^
> > ** BUILD FAILED **
> 
> > I followed all the instructions in Usage section, it is working fine when i run it using Xcode . Kindly let me know if there are any CI specific instructions. I tried to 'Xcodebuild' on ChartsDemo project it give me the below error.
> > /Users/Naveen/Downloads/Charts-3.0.0/Source/ChartsRealm/Data/RealmBarLineScatterCandleBubbleDataSet.swift:14:8: error: no such module 'Charts'
> > import Charts
> > ^
> > ** BUILD FAILED **
> 
> I have the same error. Xcode 10 , run success on phone but failed on jenkins

I have the same error. May I know how you fixed the problem with jenkins?
