### ISSUE TITLE
help with labels

### ISSUE THREAD

**Issue by SirComet** [danielgindi/Charts#2400]
I am using the library and want to add labels next to the last value of the linechart.
currently overriding drawExtras inside a newLineChartRenderer

but I have overlapping of the labels when the last values are very close. I am trying to workaround this, but if you can provide any help it would be greatly appreciated. 

![screen shot 2017-04-27 at 6 02 20 pm](https://cloud.githubusercontent.com/assets/22453986/25508004/f7bc86a0-2b74-11e7-8cff-905dbd25acb9.png)

**Comment by liuxuan30** [comment]
Check out `ChartMarker` or `ChartLimitLine` which suits better. To me, ChartLimitLine may be better, just not sure the line, only the text. e.g. use clear color, or override drawLimitLine() to not to draw lines, just text.
