### ISSUE TITLE
Adding line/dataset on line chart that already has a line

### ISSUE THREAD

**Issue by Kalvin126** [danielgindi/Charts#2401]
There does not seem to be a way to add a new line to a line chart that already has a line. We have a use case where pressing a button would add essentially a "compare to last year" line. We have to reset chart data to add the second line then animate it in. The issue is that the first line disappears, then the animation occurs on both lines.

Correct me if there is a way to do this.

**Comment by liuxuan30** [comment]
`open func addDataSet(_ dataSet: IChartDataSet!)` in ChartData

**Comment by Kalvin126** [comment]
Using `addDataSet` and then `animate(x` redraws the existing dataSet though :(
