### ISSUE TITLE
Draw bar line even though the value is zero

### ISSUE THREAD

**Issue by marbetschar** [danielgindi/Charts#2403]
I got a grouped bar chart and this works like a charm. However, to indicate there is data - even though the value of the data is zero - I'd like to have a bar drawn on every occasion.

Right now, the charting library draws the following:

<img width="600" alt="wrong" src="https://cloud.githubusercontent.com/assets/392542/25577657/2fe57668-2e68-11e7-9ca6-90e667b917a2.png">

But it should behave like follows - how can I achieve this? Unfortunately I've not found anything pointing me into the right direction :(

<img width="600" alt="right" src="https://cloud.githubusercontent.com/assets/392542/25577686/72bf1804-2e68-11e7-96db-59271428900e.png">

**Comment by marbetschar** [comment]
Doh! Got the solution: I just check the yValue during `BarChartDataEntry` creation and set it to a value slightly above zero.

```
BarChartDataEntry(x: xValue, y: yValue == 0.0 ? 0.01 : yValue)
```

Are there any downsides to this approach? Maybe this does not work, if the range of yValues are very widely spread?

**Comment by liuxuan30** [comment]
I want to just say use 0.01 or 0.1 instead of 0. Some thing may happen is that, when your yMax is very large, e.g. 1 million, 0.01 can be ignored as well, so maybe use percentage like (yMax - yMin) * 0.01?

**Comment by marbetschar** [comment]
@liuxuan30 that's an awesome idea!! Thank you!
