### ISSUE TITLE
chartValueSelected Delegate Method Not Called

### ISSUE THREAD

**Issue by socaljoker** [danielgindi/Charts#2404]
When tapping on a bar using the BarChartView, the chartValueNothingSelected delegate method gets called instead of the chartValueSelected delegate method because the highlight is null in the highlightValue method. I've tried everything to get it to not be null but cannot figure it out.

**Comment by liuxuan30** [comment]
check 
```swift
        if callDelegate && delegate != nil
        {
            if h == nil
            {
                delegate!.chartValueNothingSelected?(self)
            }
            else
            {
                // notify the listener
                delegate!.chartValueSelected?(self, entry: entry!, highlight: h!)
            }
        }
```

**Comment by socaljoker** [comment]
I did check that. h is always null no matter what. I've set a highlighter on the chart.

**Comment by liuxuan30** [comment]
well.. you could add breakpoints and trace back to see how it generates highlight object. Please refer ChartsDemo as well.
