### ISSUE TITLE
How to use gradient colors for each column in a histogram?

### ISSUE THREAD

**Issue by LPfly** [danielgindi/Charts#2407]
The color of each column in the histogram of the demand is filled by the gradient color.
I did not find the relevant interface can modify a single color gradient color.
So come to help, thank you.

**Comment by liuxuan30** [comment]
where do you see it?

**Comment by LPfly** [comment]
what ?

**Comment by liuxuan30** [comment]
I don't see this library support gradient bars.

**Comment by LPfly** [comment]
May be updated later
Sit back and wait
