### ISSUE TITLE
Bar width

### ISSUE THREAD

**Issue by zykis** [danielgindi/Charts#2410]
Any way i can force bar width to be wider?
<img width="361" alt="screen shot 2017-05-03 at 23 08 03" src="https://cloud.githubusercontent.com/assets/5877248/25680312/09aa1092-3059-11e7-8cfd-3ac4b1762d09.png">

Yet, dataset with 1 entity works pretty well:
<img width="358" alt="screen shot 2017-05-03 at 23 36 14" src="https://cloud.githubusercontent.com/assets/5877248/25680398/5c309f7a-3059-11e7-81ea-9d148ca46eff.png">

**Comment by hernanarber** [comment]
Hi @zykis:

First of All Set your barWidth for the BarChartDataSet:

 `          chartData.barWidth = defaultbarwidth // I Put is as 0.4`

Then what you can do is make an Outlet for the Width of the Chart Constraint like this:
(Drag from Storyboard)
`    @IBOutlet weak var layoutBarChartWidth: NSLayoutConstraint! `

Then you can Set the Width of the Chart According to the Amount of Data you have

```
            let dataBars = <YOUR DATA OBJECTS>
            let realBarWidth = 20.0
            // Chart Width:
            let fullWidth = CGFloat(realBarWidth*Double(dataBars.count))
            layoutBarChartWidth.constant = max(fullWidth, view.frame.size.width)
            layoutBarChartWidth.constant = fullWidth

```

Hope this Helps :-)

**Comment by zykis** [comment]
Thanks, @hernanarber !
I'll try it this evening, but still got some quesitons:
1) I can't find barWidth property in BarChartDataSet class. Even inspecting IBarChartDataSet.swift file shows only "barBorderWidth", "barBorderColor" etc. May be it was removed from new API?
2) I did declare IBOutlets of different UI objects in my Storyboard, but as for NSLayoutConstraint. How it can be actually ctrl-dragged from Storyboard, if it's not an UIView inheritor? I mean, if i ctrl-drag any point of BarChartView, IB will suggest me to create BarChartView outlet only

**Comment by hernanarber** [comment]
The .barWidth Property is not part of the ChartDataSet, but of the BarChartData :-)
`            let chartData = BarChartData(dataSet: chartDataSet) `
Try it

**Comment by hernanarber** [comment]
For the constraint Go to the EXPLORER in the Storyboard so you can Ctrl+Drag the Constraint

**Comment by zykis** [comment]
@hernanarber oh, man!
Thank you a lot!!

**Comment by aelam** [comment]
setting the visible range is what you want
checkout the `BarLineChartViewBase.swift`
```   
     open func setVisibleXRange(minXRange: Double, maxXRange: Double)
```

**Comment by zykis** [comment]
@aelam Oh, thanks! I'll try that.

**Comment by hernanarber** [comment]
@aelam Can you explain me more about this?

I think this is what we need....

Thanks :-)

**Comment by zykis** [comment]
@hernanarber 
 ```
   /// Limits the maximum and minimum value count that can be visible by pinching and zooming.
    ///
    /// e.g. minRange=10, maxRange=100 no less than 10 values and no more that 100 values can be viewed
    /// at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    open func setVisibleXRange(minXRange: Double, maxXRange: Double)
    {
        let minScale = _xAxis.axisRange / maxXRange
        let maxScale = _xAxis.axisRange / minXRange
        _viewPortHandler.setMinMaxScaleX(
            minScaleX: CGFloat(minScale),
            maxScaleX: CGFloat(maxScale))
    }
```

That's what source tells us

**Comment by liuxuan30** [comment]
can be close now

**Comment by zykis** [comment]
Well, BarChartData.barWidth not helps here. 
Manipulations with setXVisibleRange can't change situation neither. I believe, it's connected with huge timestamps x-values. Any idea, where it's calculated in sources?
Timestamps are used since 1970

**Comment by liuxuan30** [comment]
Played with ChartsDemo, it's working:
```swift
        BarChartData *data = [[BarChartData alloc] initWithDataSets:dataSets];
        [data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:10.f]];
        
        data.barWidth = 1.0f;
        
        _chartView.data = data;
```
<img width="372" alt="image" src="https://cloud.githubusercontent.com/assets/4375169/25739101/f3fe1ca6-31b2-11e7-84fd-eb04e3afee36.png">

**Comment by zykis** [comment]
Well, barWidth works, if i use dataset with 1 entity. I could set it to 0.5 and it would be half width. But in my case, there should be 7 of them. And they should be calculated, depending on X values, and bar count i believe somewhere

**Comment by zykis** [comment]
Well, the solution is pretty simple: BarCharData.barWidth is NOT evaluated as percentages. It's actually a POINTS. So, calculate it appropriately:
```
double xMin = [dataSet xMin];
double xMax = [dataSet xMax];
double w = xMax - xMin; // width of x-axis in seconds
double spacing = 0.05; // 5% of barWidth
double barWidth = w / [dataSet values].count - (spacing * w / ([dataSet values].count - 1));
```

**Comment by zykis** [comment]
You have a full-width entity just because your X-axis width is equal to 1.0. Just a coincidence.
The thing is ChartBarData.barWidth is POINT-BASED value, where X-axis width = [dataSet xMax] - [dataSet xMin]. You can test it out by setting entities values with e1(x=0, y=1) and e2(x=1000,y=0.7) and barWidth = 1;

**Comment by aelam** [comment]
@zykis
I don't think it's a good solution, 
The bar width is a percentage, 
What you need to do is handle the visible range of xAxis. 
For example,
If xAxis visible range is 0,100, and bar width is 0.8
Then AN entry full pixel width is chartWidth / 100 , and the bar pixel width is chartWidth /100 * barWidth. 

I don't think it's good that you change the barWidth dynamically. The dataSet part once is set, then done. Then take care of the view. The view handles how wide a full bar width is.  To approach that, set an appropriate visibleRange. 


发自我的 iPhone

**Comment by aelam** [comment]
I think you have got two issues, 
One is get the bar wider,
One is get bar narrow .

If you you want the bar narrow. You can try set the barWidth = 0 , and borderwidth = 3


发自我的 iPhone

**Comment by hernanarber** [comment]
I Tried Setting the Visible Range:
` barChartView.setVisibleXRange(minXRange: 0.0, maxXRange: 5.0) `

But as a Result the BarWidth is Changing depending on the amount of bars, What I Wanted was a CONSTANT Bar Width regardless of how much data was on the Chart :-(

**Comment by zykis** [comment]
Well, actually the bar width is not in PERCENTAGES, but it's in POINTS.
BarChartRenderer.swift:71 prepareBuffer()

```
let barWidthHalf = barData.barWidth / 2.0
let left = CGFloat(x - barWidthHalf)
let right = CGFloat(x + barWidthHalf)
barRect.origin.x = left
barRect.size.width = right - left
barRect.origin.y = top
barRect.size.height = bottom - top
```

**Comment by billylo1** [comment]
I ran into the exact issue with first/last bar cutted in half and barWidth problems (I also have timeIntervalSince1970 as xValues.) 

Eventually got what my desired effect by storing # of days since the first bar as xValues; and use my custom formatter to translate xValue back to a String.

Hope this helps.

![image](https://user-images.githubusercontent.com/5649557/28856085-eec3d874-770e-11e7-861c-e8051ed9221a.png)

![image](https://user-images.githubusercontent.com/5649557/28856232-beb2f97a-770f-11e7-9152-8e6bbdbccc40.png)

**Comment by aelam** [comment]
@zykis  set the xAxisMin to -0.5 if you current minXValue is 0, then it wouldn't be cut, same as maxValue 
and the unit of these -0.5, 0 , 0.5 are based on point not pixel, I said percentage before. But now I think you know what I mean now.

**Comment by aelam** [comment]
@zykis maybe you can try to keep every POINT in same pixels each time, then you can have a constant result that's what I meant

**Comment by zykis** [comment]
@billylo1 That's a nice point. I need cut some decades from my start value for sure :D
`double ti = [date timeIntervalSince1970];`
@aelam It worked fine for me. But i can't remember, when this solution was broken and by what circumstances.
My final solution fixed problem, by manipulating values of the bar:
```
BarChartData* data = [[BarChartData alloc] initWithDataSet:dataSet];

double xMin = [dataSet xMin]; // seconds since 1970x
double xMax = [dataSet xMax]; // seconds since 1970 + few days
double w = MAX(1, xMax - xMin); // if we have 7 days in xaxis, then its 7 * 24 * 60 * 60
double spacing = 0.05; // 5% of barWidth
double barWidth = w / [dataSet values].count - (spacing * w / ([dataSet values].count + 1)); // actual bar width
data.barWidth = barWidth;
[_chartView setFitBars:YES];

xaxis.spaceMin = barWidth / 10.0;
xaxis.spaceMax = barWidth / 10
xaxis.xOffset = barWidth;

_chartView.data = data;
```

![screenshot_20170807_103654](https://user-images.githubusercontent.com/5877248/29016826-bd3a9dcc-7b5c-11e7-9500-bab13605f91a.png)

**Comment by sshivanshu992** [comment]
I am not able to add the fixed the barWidth of while using the groupBars & groupWidth.
`/// Assigning  `barWidth`
        barChartData.barWidth = groupBarSpace.barWidth
        /// - Configure the group bar width and group spacing  ..!
        /// This method returns the `space an individual group` of bar needs on the `x-axis`.
        let interval = barChartData.groupWidth(groupSpace: groupBarSpace.groupSpace,
                                               barSpace: groupBarSpace.barSpace)
        /// The maximum value for this `xAxis`
        let axisMaximum: Double = 0.0 + interval * groupBarSpace.groupCount
        print("Interval per group: ", interval)
        print("Group space : ", axisMaximum)
        /// Group the all BarDataSet Objects
        barChartData.groupBars(fromX: 0.0, groupSpace: groupBarSpace.groupSpace,
                               barSpace: groupBarSpace.barSpace)

////////////////////
return (groupSpace: 0.36, barSpace: 0.02, barWidth: 0.3, groupCount: Double(labelsCount))
`
![Screenshot 2023-07-13 at 01 39 19](https://github.com/danielgindi/Charts/assets/41211881/ae0ed4b2-bb1e-4320-9728-4c5d39a03333)
