### ISSUE TITLE
How can I add the xVals to LineChartData object?

### ISSUE THREAD

**Issue by vanvanj** [danielgindi/Charts#2412]
I was using a old version charts and there is a "initWithXVals: dataSets:" method in LineChartData so I can add the xVals into the chartView.  But after I updated the Charts, the "initWithXVals: dataSets:" is gone. So how can I add xVals to a chartView now?

**Comment by liuxuan30** [comment]
You can't now. #1474

**Comment by leszarna** [comment]
I think people often go from google straight here. It would seem much better to answer ticket with 2 line example than to write answers like go to #1474. Most people doesn't use this library much, and searching some changelog is simply waste of time. It's not easy to find solution in 15 minutes for me so probably same for others.

**Comment by liuxuan30** [comment]
if the question is complex we will post code. But for APIs that already are gone, devs should check changelog or the new ChartsDemo code themselves. It's much more efficient than google and open an issue and wait for response. I admit I am not following the good habit very well but I'm trying to.

Using the demo code and walk through the change log will not take you 15 mins I guess

**Comment by leszarna** [comment]
`xAxis.valueFormatter = IndexAxisValueFormatter(values: xVals)`

It's shorter than your wordy essay.
Thank you
