### ISSUE TITLE
Track Scroll Left or Right

### ISSUE THREAD

**Issue by abrez** [danielgindi/Charts#2415]
![screen shot 2017-05-06 at 12 50 55 pm](https://cloud.githubusercontent.com/assets/12423023/25770716/b412fb54-325a-11e7-9d2f-aaf594fc82f8.png)

Is there anyway to track Left to right or right to left scroll within LineChartView

**Comment by akeskiner** [comment]
In your gesture handler method, you can check the sign of the velocity:

```swift
    func handleGesture(recognizer: UIPanGestureRecognizer) {
        var velocity : CGPoint = recognizer.velocity(in: self.view)
        if velocity.x > 0 {
            print("Gesture went right")
        } else {
            print("Gesture went left")
        }
    }
```
