### ISSUE TITLE
Components folder in the demo is not included in pod?

### ISSUE THREAD

**Issue by ShaiGivati464** [danielgindi/Charts#2418]
I am using the library with pod and when I tried to implement something from the demo app (XYMarkerView) I've noticed it is not part of the pod library. Am I missing something?

**Comment by liuxuan30** [comment]
have point your pod to master? If so, I guess the demos are excluded.

**Comment by pmairoldi** [comment]
This is on purpose since they are not core to the library. They are just an example on how you can extend the library. If you really want the same exact thing just copy the file to your project.
