### ISSUE TITLE
Is it possible to extend the gesture handler?

### ISSUE THREAD

**Issue by akeskiner** [danielgindi/Charts#2419]
Hi,
I want to add additional behaviour to built in gesture handlers. Is that possible? For example when there is a UIPanGesture, I want to zoom out while I'm scrolling through the chart.

```swift
lineChartView.addGestureRecognizer(UIPanGestureRecognizer(target: self, action: #selector(handleGesture)))
```
If I add a gesture recognizer like this, it conflicts with scrolling behaviour.
Thanks.

**Comment by aelam** [comment]
You can add a view above the chart, do whatever you want 
Since the gesture behaviors in chart is not meet my requirements, I did so

**Comment by akeskiner** [comment]
I see, but I still have the problem of not having both recognizers (chart's recognizer and mine).

The code I have is:

```swift
let additionalView = UIView(frame: self.lineChartView.frame)
additionalView.addGestureRecognizer(UIPanGestureRecognizer(target: self, action: #selector(handleGesture)))

self.view.addSubview(additionalView)
```

**Comment by liuxuan30** [comment]
The gesture handler is `fileprivate`, so you can provide your own for sure. Just rebind to the handler in your sub class
