### ISSUE TITLE
Line Chart show value on specific coordinate

### ISSUE THREAD

**Issue by WilsonCP** [danielgindi/Charts#2420]
I'm kinda new on using this project, I do have a problem on displaying the value inside the graph itself. Here's a screenshot that shows what I want to do.

![screen shot 2017-05-09 at 10 55 42 am](https://cloud.githubusercontent.com/assets/22924808/25833873/f2ccd682-34a6-11e7-9e92-986250ed12ec.png)

As you can see on the image, the value that i want to show is inside the red circle (circle will not be shown), I want to show the value on that coordinate. Can anyone tell me how to achieve this on Swift3? Thanks in advance

**Comment by liuxuan30** [comment]
just use the highlighted method or delegate, or ChartMarker to show. Just check ChartsDemo..
