### ISSUE TITLE
Show Two Circles in Pie Chart

### ISSUE THREAD

**Issue by applepeopletsai** [danielgindi/Charts#2424]
Hi, everyone
I'm trying to show two circles in pie chart like the photo
Is there way to do this?
thanks

![pie chart](https://cloud.githubusercontent.com/assets/19483534/25881652/cee5afbc-3570-11e7-819d-fc19a8a681da.png)

**Comment by liuxuan30** [comment]
It's not a pie chart I suppose, and it's easy to write one on your own by Coregraphics, or CALayers

**Comment by applepeopletsai** [comment]
Ok, I'll try.
Thank you for you reply :)
