### ISSUE TITLE
Legend leak in version 3.0.1

### ISSUE THREAD

**Issue by laizf** [danielgindi/Charts#2425]
![image](https://cloud.githubusercontent.com/assets/436318/25885475/22fb9d4a-358b-11e7-980a-ccd1bef83f13.png)
When use instruments to analyze memory leak,  found Legend is leaked, but cannot find the reason. The stack trace is shown in the image above.

**Comment by laizf** [comment]
It's seems the same bug with issue:#2416 "Memory Leak in BarChartView Data". 
![image](https://cloud.githubusercontent.com/assets/436318/25889231/aa5321cc-359b-11e7-9a08-47b195b34054.png)

**Comment by laizf** [comment]
My XCode Version is 8.3 (8E162). I ever used old version XCode to check memory leak about two month ago, and no leak found that time. I think you should update your XCode to the latest version if you want to reproduce this bug.

**Comment by thierryH91200** [comment]
this is the latest version sorry

![capture d ecran 2017-05-10 a 10 38 12](https://cloud.githubusercontent.com/assets/6251463/25890231/11dc0ce8-356d-11e7-8696-7e94d20178e6.png)

**Comment by laizf** [comment]
And can you reproduce or solve this problem? @thierryH91200

**Comment by laizf** [comment]
@liuxuan30

**Comment by liuxuan30** [comment]
Are you using ChartsDemo to reproduce? And also can you click the objects that saying leak, to display the malloc/free history? I tried one, but the history shows the last one is free, so it's not leak, but something wrong with instruments.

I need to know do you use ChartsDemo to reproduce, or whatever projects you can share so I can take a look, or just save instruments and upload it so I can take a look directly.

**Comment by laizf** [comment]
The ref count is -1 finally, but instruments still mark it as leak. The instruments file is too large to upload, so I just show you the screenshot:
![image](https://cloud.githubusercontent.com/assets/436318/26039513/448269a0-394e-11e7-99d0-1b1f476fac63.png)
![image](https://cloud.githubusercontent.com/assets/436318/26039515/528bb308-394e-11e7-97c6-d61b1d667604.png)

**Comment by liuxuan30** [comment]
No, I tried when you pop back, the leaked object is freed then:
![image](https://cloud.githubusercontent.com/assets/4375169/26039600/640dca20-394f-11e7-8b35-355008b1d98b.png)

When your chart is displaying, I can't say it's our problem, as when the chart get destroyed, the objects saying leak is also freed.

**Comment by laizf** [comment]
Copy

**Comment by liuxuan30** [comment]
If you sure it's freed, I will close the related issues.

**Comment by laizf** [comment]
I think so!
![image](https://cloud.githubusercontent.com/assets/436318/26039971/67a14960-3953-11e7-8631-7178bb5644ed.png)
