### ISSUE TITLE
Marker points on wrong position

### ISSUE THREAD

**Issue by WilsonCP** [danielgindi/Charts#2426]
I'm using the class BalloonMarker: MarkerImage you have provided, but I'm having issue that the xy position of highlight is not the same as the arrow of marker. What do you think am i doing wrong? And to add to that, the marker is being cut (not shown in the image) when it is on the left/right most portion of the chart, been looking to other issues but still no luck on solving this.

![screen shot 2017-05-10 at 5 15 47 pm](https://cloud.githubusercontent.com/assets/22924808/25891987/8d72bef0-35a5-11e7-8ddf-df017ad87762.png)

**Comment by liuxuan30** [comment]
BalloonMarker is just a demo, so you may found some offset, which I am not sure as well. Please take a look at the code and see if the position fits.
