### ISSUE TITLE
Animate 3 dataSets one by one

### ISSUE THREAD

**Issue by Kiee79** [danielgindi/Charts#2428]
Hey , I tried but nothing. Is possible animate 1 dataSet if it finish then next second dataSet etc ? 
I have 3 data sets and if i call animate on xAxis that cause animate all 3 data set and it looks bad. I want to animate line from left to right smoothly

**Comment by liuxuan30** [comment]
seems we don't support this right now. But you can take a look at the animator job and possibly write one
