### ISSUE TITLE
How to set labels based on max and min value of the plot?

### ISSUE THREAD

**Issue by klemenzagar91** [danielgindi/Charts#2434]
Im using Charts - 3.0.2 to plot line graph. On the left side I want to have 3 labels. Min, max and one in the middle of the graph.

<img width="377" alt="screen shot 2017-05-12 at 13 29 45" src="https://cloud.githubusercontent.com/assets/5512848/25997417/30422ff4-371c-11e7-9ad4-95fd769a184f.png">

I set the granulation based on the min and max value:
`graphView.leftAxis.granularity = (data.yMax - data.yMin)/2.0`
So the spacing is now correct, but the problem still left with the grid offset. Because it starts drawing at 0.0 but I want it to start a the minimum value of the graph.

Is it possible? Do you know any workaround?

**Comment by liuxuan30** [comment]
Sounds like you need `ChartLimitLine` and just make the limit line clear

**Comment by klemenzagar91** [comment]
<img width="370" alt="screen shot 2017-05-15 at 11 14 52" src="https://cloud.githubusercontent.com/assets/5512848/26050662/c4d5e5bc-395f-11e7-9267-58332eba315a.png">
ok, but in that case, the label to the line cannot be placed on the left side of the axis, where other labels are. without this, I cannot limit lines.

**Comment by thierryH91200** [comment]
try that
for me it's ok

```
leftAxis.axisMinimum = min
leftAxis.axisMaximum = max
leftAxis.granularity = (max - min)/2
leftAxis.labelCount = 3
leftAxis.forceLabelsEnabled = true
```

**Comment by klemenzagar91** [comment]
Ok, but in this case some parts of chart are cut off. 
<img width="378" alt="screen shot 2017-05-15 at 12 15 00" src="https://cloud.githubusercontent.com/assets/5512848/26053237/5e0c057e-3968-11e7-899e-430a49dcee0a.png">
