### ISSUE TITLE
Change color label over circle

### ISSUE THREAD

**Issue by ulisescarreonalvarez** [danielgindi/Charts#2436]
I need change the color and size of the Label over the circle on the Line Chart
What property is it?

![archivo 12-05-17 4 16 41 p m](https://cloud.githubusercontent.com/assets/25987364/26017308/841d0146-372e-11e7-9536-d401a044a084.png)

Regards

**Comment by liuxuan30** [comment]
why not search
```swift
    /// The radius of the drawn circles.
    open var circleRadius = CGFloat(8.0)
    
    /// The hole radius of the drawn circles
    open var circleHoleRadius = CGFloat(4.0)
    
    open var circleColors = [NSUIColor]()
```
