### ISSUE TITLE
Got Error : “_OBJC_CLASS_$__TtC10ChartsDemo12XYMarkerView” in Charts

### ISSUE THREAD

**Issue by Yasika** [danielgindi/Charts#2437]
I have used “Charts” library in to my project to display Stacked Bar Chart and it is woking fine. 
Now, I want to add **tool tip** to my project to display values.

Like :
![tooltip](https://cloud.githubusercontent.com/assets/8788277/26022796/cdda9abc-37cb-11e7-9875-ed9c1ae266e4.png)

**I  have already followed these steps :**

- Drag the Charts.xcodeproj to your project.
- Go to your target's settings, hit the "+" under the "Embedded Binaries" section, and select the Charts.framework
- @import Charts
- When using Swift in an ObjC project:
• You need to import your Bridging Header. Usually it is "YourProject-Swift.h", so in ChartsDemo it's "ChartsDemo-Swift.h".
• Do not try to actually include "ChartsDemo-Swift.h" in your project :-)
• (Xcode 8.2+) Under "Build Options", mark "Always Embed Swift Standard Libraries"

**But i got this error:**

![error](https://cloud.githubusercontent.com/assets/8788277/26022814/1cbab874-37cc-11e7-8a0c-36f7dfaef6d9.png)
Could you please help me out? How to fix this?
Thanx

**Comment by liuxuan30** [comment]
XYMarkerView is under ChartsDemo repo.

**Comment by shivangpandya9** [comment]
I have got same error . Please help me how to fix it

**Comment by shivangpandya9** [comment]
I have got same error . Please help me how to fix it. I already import XYMarkerView (component) folder to my project
![screen shot 2017-07-21 at 8 10 33 am](https://user-images.githubusercontent.com/30236980/28447055-20a42cda-6dec-11e7-94c7-5ebfbda5df58.png)
 but still got error .

Please help to fix it. I am waiting for your reply.

**Comment by liuxuan30** [comment]
due to https://github.com/danielgindi/Charts/issues/2611#issuecomment-316884751
