### ISSUE TITLE
show tooltip on click

### ISSUE THREAD

**Issue by HPRaval** [danielgindi/Charts#2438]
I want to show tooltip with some meaningful information on click of any point. Is it possible? if yes then how?

**Comment by liuxuan30** [comment]
check out ChartMarker

**Comment by HPRaval** [comment]
Thnx a lot for quick help. I am able to show tooltip with this and it works great. But with stacked bar chart its not working as expected. It shows only highest value. What should i do if i want to show something like this for stacked bar.

![screen shot 2017-05-15 at 12 12 56 pm](https://cloud.githubusercontent.com/assets/24671241/26045501/3aa3f218-3968-11e7-95ba-c88fe8e3162e.png)

**Comment by liuxuan30** [comment]
Time for you to dig into this stacked bar chart properties and write a proper one.

**Comment by minhDTN** [comment]
@HPRaval Can I know how to make corner radius for the tooltip?
