### ISSUE TITLE
Help with custom graphic/chart

### ISSUE THREAD

**Issue by Jabelriera** [danielgindi/Charts#2442]
Hi everyone and thank you for all the work done in this repo, it is really amazing.

I am now developing a section of an app that has several charts and some of them are as the following image:

![Ilustration example](http://i.imgur.com/74SjxeP.png?1)

I know it is not the type of charts this repo is built for, but if anyone know any way I could use it to implement it that would be amazing. The *big problem* that I see is the line below the _bar_ that shows the actual value of the client.

Thank you everyone in advance!

**Comment by liuxuan30** [comment]
this is beyond - but you can take a look at how the axis and lines and bars are displayed and write your own.
