### ISSUE TITLE
Bug in line chart yAxis when range are less than 1

### ISSUE THREAD

**Issue by rolyanos** [danielgindi/Charts#2445]
Hello, maybe I doing something wrong, but I am think that there are small bug in y-axis. 
![screen shot 2017-05-16 at 17 14 40](https://cloud.githubusercontent.com/assets/17070078/26110494/32b56a5c-3a5b-11e7-9263-c9917da5ab69.png)

here is the code:
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let data = generateLineData()
        testLineChartView.data = data
        
    }
    
    func generateLineData() -> LineChartData {
        let data: LineChartData = LineChartData()
        
        
        var entries: [ChartDataEntry] = []
        
        var dataArr: [Double] = []
        dataArr.append(0.1)
        dataArr.append(0.001)
        dataArr.append(0.8)
        dataArr.append(0.02)
        dataArr.append(1)
        
        
        for index in 0..<5 {
            entries.append(ChartDataEntry(x: Double(index)+0.5,  y: Double(dataArr[index]) ) )
        }
        
        let set: LineChartDataSet = LineChartDataSet(values: entries, label: "Label")
        set.setCircleColor(UIColor.blue)
        set.lineWidth = 1
        set.circleRadius = 5
        set.drawCircleHoleEnabled = false
        set.valueTextColor = UIColor.blue
        set.valueFont = UIFont(name: "Verdana", size: 12.0)!
        set.drawFilledEnabled = true
        set.mode = Charts.LineChartDataSet.Mode.linear
        set.axisDependency = Charts.YAxis.AxisDependency.left
        
        data.addDataSet(set)
        
        return data
    }

**Comment by liuxuan30** [comment]
What's the issue? seems totally fine to me.

**Comment by rolyanos** [comment]
There are no 0 number before "," symbol.

Needs 0,1 but there are ,1
<img width="214" alt="screen shot 2017-05-17 at 12 18 17" src="https://cloud.githubusercontent.com/assets/17070078/26147039/ef32728e-3afa-11e7-82d0-94856343ee4f.png">

**Comment by thierryH91200** [comment]
check out **valueFormatter**

**Comment by rolyanos** [comment]
@thierryH91200, why? there are no needs of customization, just fix a bug with wrong numbers that less than 1. There are wrong numbers in yAxis,xAxis and in value label.

**Comment by thierryH91200** [comment]
no it's correct 
x = 0.5, 1.5, 2.5 etc...
y = 0.1,0.001, 0.8, 0.02,1
format the values

**Comment by rolyanos** [comment]
Yep, it works with formatter, thanks. Strange, that it is not show 0 before "," by default.
