### ISSUE TITLE
chart 3.0 xAxis labels not mapped

### ISSUE THREAD

**Issue by yanjf90** [danielgindi/Charts#2447]
when I use _[[BarChartDataEntry alloc] initWithX: **x** y: y]_ add to dataset, and set the xaxis formatter.
[ChartDefaultAxisValueFormatter withBlock:^NSString * _Nonnull(double **value**, ChartAxisBase * _Nullable axis) ,

but the value does not equals to x. it seems value is recalculated ? for example I pass x from 0-7, but the value may be (0, 0.9, 1.8. 2.7 ...), sometimes , when I removed the labelCount is works well, but not always. Is somethis wrong?

**Comment by liuxuan30** [comment]
x axis labels(entries) are calculated in `calculateAxisValues()`, and it has its own algorithm by default. You can override it or use `forceLabelEnabled` if the logic suits you. Just take a look.
