### ISSUE TITLE
What is relation between the BubbleSize and the axis value?Can we control the size of Bubble in Bubble Chart?

### ISSUE THREAD

**Issue by SamSundar1** [danielgindi/Charts#2448]
I don't know what is happening.
 let set1: BubbleChartDataSet = BubbleChartDataSet(yVals: dataEntries1, label: "First Set")      set1._maxSize = 30
Even though i have set max size to 30 bubbles are larger according to the data values

**Comment by thierryH91200** [comment]
A bubble chart is a variation of a scatter chart in which the data points are replaced with bubbles, and an additional dimension of the data is represented in the size of the bubbles. Just like a scatter chart, a bubble chart does not use a category axis — both horizontal and vertical axes are value axes. In addition to the x values and y values that are plotted in a scatter chart, a bubble chart plots x values, y values, and z (size) values.


<img width="797" alt="capture d ecran 2017-05-17 a 11 37 47" src="https://cloud.githubusercontent.com/assets/6251463/26147928/543ac7d6-3af5-11e7-8c4b-6c5272da3669.png">



```
var entries = [BubbleChartDataEntry]()
for index in 0..<ITEM_COUNT
{
    let y = Double(arc4random_uniform(100)) + 50.0
    let size =  Double(arc4random_uniform(5)) + 1
    entries.append(BubbleChartDataEntry(x: Double(index) + 0.5, y: y, size: CGFloat(size)))
}
```

**Comment by SamSundar1** [comment]
for i in 0..<dataPoints.count {
            if values1[i] != 0
            {
            let dataEntry = BubbleChartDataEntry(xIndex: i, value: values1[i], size: 30.0)
            dataEntries1.append(dataEntry)
        }
        }
let set1: BubbleChartDataSet = BubbleChartDataSet(yVals: dataEntries1, label: "First Set") set1._maxSize = 30

The bubbles varies according to the data.. What is happening ..?

**Comment by thierryH91200** [comment]
size is not a constant.

that does not make sense this is the 3rd dimension

**Comment by SamSundar1** [comment]
can you please go through my code

**Comment by thierryH91200** [comment]
update Charts in first to 3.0.2
you use v2

**Comment by SamSundar1** [comment]
@thieeryH91200,Sorry for late reply but how the sizes(1 to 5) are set to the bubbles??

**Comment by thierryH91200** [comment]
let size =  Double(arc4random_uniform(5)) + 1
entries.append(BubbleChartDataEntry(x: Double(index) + 0.5, y: y, **size: CGFloat(size)**))
here--------------------------------------------------------------->---------------------

**Comment by SamSundar1** [comment]
i don't mean that, we have sizes ranging from 1 to 5. How the sizes are choosen..?

**Comment by thierryH91200** [comment]
4 data series, each containing 3 values:

Risk	Probability	Impact	Exposure
Foo	10	               6	        60
Bar	30	              8	        240
Baz	90	              5	        450
Spong	50	      2	        100


Probability = axe OX
Impact = axe OY
Exposure = size is the 3rd dimension / column

one data series => 3 values 


<img width="554" alt="capture d ecran 2017-05-17 a 17 39 09" src="https://cloud.githubusercontent.com/assets/6251463/26162718/cb67b9cc-3b27-11e7-9e83-75f81433bf20.png">

**Comment by SamSundar1** [comment]
Thank you..Got it :)

**Comment by liuxuan30** [comment]
Thanks @thierryH91200 !
