### ISSUE TITLE
How to implement Gantt charts using iOS-Charts?

### ISSUE THREAD

**Issue by gauraveleven** [danielgindi/Charts#2451]
@danielgindi @liuxuan30  Can you suggest me, How to implement Gantt charts [like this](https://www.bryntum.com/examples/gantt-latest/examples/advanced/#en)
I also  saw all example in iOS charts. please help me

**Comment by liuxuan30** [comment]
basically you need to understand how CoreGraphics works and how this library works, and you can write one referring bar chart.
