### ISSUE TITLE
Plotting large amount of data slows down the Graph.

### ISSUE THREAD

**Issue by zohaibbrohi** [danielgindi/Charts#2454]
I have large amount of data to plot. Currently I am plotting 2000 points but it can be larger then that. When I am plotting 2000 points, amount of response time is very high. it takes 1 to 3 seconds to interact. but when I scale the graph it works really good. Is there any solution how to make it fast.
Is there any function to reduce amount of plotting point on overall chart but when scale it shows all the points. 
Thank you.

**Comment by liuxuan30** [comment]
This is known issue, as it is CPU intensive. soution/workaround is reduce your entry count to like 200 by yourself.

**Comment by zohaibbrohi** [comment]
Yeah thats what i had to do in the end. Thanks for your response.
