### ISSUE TITLE
Bubble charts: Can i set the size same to all the bubbles? 

### ISSUE THREAD

**Issue by 01sunjon** [danielgindi/Charts#2456]
i have a bubble chart and some bubbles are very large.i want to set the bubble chart size same for all. i have tried to use 
        var dataEntries1 : [BubbleChartDataEntry] = [BubbleChartDataEntry]()
 for i in 0..<dataPoints.count {
            if values1[i] != 0
            {
                let dataEntry = BubbleChartDataEntry(xIndex: i, value: values1[i], size: 5.0)
                dataEntries1.append(dataEntry)
                
            }
        }
        let set1: BubbleChartDataSet = BubbleChartDataSet(yVals: dataEntries1, label: "First Set")
        set1._maxSize = 30

even i have tried to set all the bubbles value to its size 30. The bubble sizes are varying its sizes. I want all of them to be a same size.Can i do this.??

**Comment by thierryH91200** [comment]
it's ok for me
update chart V3.0.2

 ```
       for index in 0..<4
        {
            entries.removeAll()
            let x = datas[index][0]
            let y = datas[index][1]
            entries.append(BubbleChartDataEntry(x: x, y: y, size: CGFloat(15  )))
            
            // MARK: BubbleChartDataSet
            let set = BubbleChartDataSet(values: entries, label: label[index])
            set.setColor(colors[index])
            set.valueTextColor = NSUIColor.black
            set.valueFont = NSUIFont.systemFont(ofSize: CGFloat(10.0))
            set.drawValuesEnabled = true
            set.normalizeSizeEnabled = false
            set.formSize = 30.0
            
            data.addDataSet(set)
        }
```


<img width="1557" alt="capture d ecran 2017-05-19 a 09 27 03" src="https://cloud.githubusercontent.com/assets/6251463/26237458/81e2493a-3c75-11e7-9088-57da6b0f2ee6.png">

**Comment by liuxuan30** [comment]
Thanks!
