### ISSUE TITLE
Plotband support

### ISSUE THREAD

**Issue by HPRaval** [danielgindi/Charts#2458]
I want to show and style Plotband like this, is it possible?

![screen shot 2017-05-19 at 4 15 41 pm](https://cloud.githubusercontent.com/assets/24671241/26244700/743c0c56-3cae-11e7-9f0e-8ff06e10cc1c.png)

**Comment by liuxuan30** [comment]
there is old issue about grid background stripes, it's doable. You just need to override some methods to fill the colors.
