### ISSUE TITLE
Cubic Line Distorted 

### ISSUE THREAD

**Issue by sz-ashik440** [danielgindi/Charts#2459]
I was trying to plot a cubic line chart. But it got distorted after some value and after that if I add more value, it gets disappear(couldn't render in iphone). Did I miss something?? Or it's a bug?  
![distorted-chart](https://cloud.githubusercontent.com/assets/9111027/26274634/cccdd752-3d6f-11e7-99d9-8926c4062cd4.PNG)

        func drawLineChart() {
            let populationData: [Int: Int] = [ 10: 29, 11: 28, 12: 28, 13: 28, 14: 27, 15: 27, 16: 27, 17: 27, 18: 27, 19: 27, 20: 28, 21: 30, 22: 31 ]
        
            let entries = populationData.map{ x,y in
                return ChartDataEntry(x: Double(x), y: Double(y))
            }
        
            let data = LineChartData()
            //----------------------------- dataset intensified ---------------------------------------
            let dataset = LineChartDataSet(values: entries, label: nil)
            dataset.axisDependency = .left
            dataset.colors = [.yellow]
            dataset.mode = .cubicBezier
            dataset.cubicIntensity = 0.1
        
            // kicked out circlre from line
            dataset.drawCirclesEnabled = false
        
            dataset.lineWidth = 2.0
            dataset.fillAlpha = 100
            dataset.drawFilledEnabled = true
            dataset.fillColor = UIColor.orange
            dataset.highlightColor = UIColor.brown
        
            dataset.drawValuesEnabled = false
        
            data.addDataSet(dataset)
        
            dailyTempView.data = data
        
            //----------------------------- removing background gridline -------------------------------
            dailyTempView.drawGridBackgroundEnabled = false
            dailyTempView.drawBordersEnabled = false
        
            dailyTempView.gridBackgroundColor = UIColor.white
            dailyTempView.xAxis.drawGridLinesEnabled = false
            dailyTempView.leftAxis.drawGridLinesEnabled = false
            dailyTempView.leftAxis.granularityEnabled = true
            dailyTempView.leftAxis.granularity = 1.0
        
            dailyTempView.rightAxis.enabled = false
        
            dailyTempView.chartDescription?.text = ""
            dailyTempView.legend.enabled = false
            dailyTempView.xAxis.labelPosition = .bottom
        }

**Comment by thierryH91200** [comment]
`let populationData: [Int: Int] = [ 10: 29, 11: 28, 12: 28, 13: 28, 14: 27, 15: 27, 16: 27, 17: 27, 18: 27, 19: 27, 20: 28, 21: 30, 22: 31 ]`
it's a dictionary

the soluce
```
let populationData : [[Int]] = [[ 10, 29], [11, 28], [12, 28], [13, 28], [14, 27], [15, 27], [16, 27], [17, 27], [18, 27], [19, 27], [20, 28], [21, 30], [22, 31 ]]

var entries = [ChartDataEntry]()
for i in 0..<populationData.count
{
    entries.append(ChartDataEntry(x: Double(populationData[i][0]), y: Double(populationData[i][1])))
}
```

**Comment by sz-ashik440** [comment]
Thanks it worked. I forgot that swift dictionary is un-ordered
