### ISSUE TITLE
How to scroll between charts on carousel

### ISSUE THREAD

**Issue by vinhtnk** [danielgindi/Charts#2465]
I have implemented an icarousel that contain 3 charts, the problem is I can not swipe left or right to go to next chart. Is there any way to handle this case?

**Comment by liuxuan30** [comment]
if it's in UIScrollView, check @objc fileprivate func panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)
```swift
if didUserDrag && !performPanChange(translation: translation)
                {
                    if _outerScrollView !== nil
                    {
                        // We can stop dragging right now, and let the scroll view take control
                        _outerScrollView = nil
                        _isDragging = false
                    }
                }

```
the outer scroll view is disabled. Change it if needed

**Comment by vinhtnk** [comment]
@liuxuan30 thanks for you reply, I found the solution, it worked: https://stackoverflow.com/questions/30910033/uiscrollview-wont-scroll-when-dragging-on-ios-charts-subview
