### ISSUE TITLE
Device Orientation not detected when using Charts module

### ISSUE THREAD

**Issue by aravinth02** [danielgindi/Charts#2469]
Device orientation works well with the ChartDemo sample app  but the orientation is not detecting when i create a own sample charts by  having the chart module in separate application.

I don't know what's been missing  when compared with ChartDemo sample app ? 

I think the orientation was handled by using value change observer on keys "frame" or "bound". Please correct me if am wrong

Thanks !!

**Comment by liuxuan30** [comment]
I don't understand, the orientation should be handled by you.

**Comment by aravinth02** [comment]
Could you please tell how and where the device orientation was handled in ChartsDemo app 

Thanks

**Comment by liuxuan30** [comment]
In the view controllers
