### ISSUE TITLE
Loading a blank chart

### ISSUE THREAD

**Issue by davidra7** [danielgindi/Charts#2472]
Hi,
I loading the line chart at the beginning of the app and I get the next messages:

2017-05-25 10:10:42.704201+0300 XXX[2808:1326160] CGAffineTransformInvert: singular matrix.
May 25 10:10:42  XXX[2808] <Error>: CGAffineTransformInvert: singular matrix.
2017-05-25 10:10:42.704270+0300 XXX[2808:1326160] CGAffineTransformInvert: singular matrix.
May 25 10:10:42  XXX[2808] <Error>: CGAffineTransformInvert: singular matrix.
2017-05-25 10:10:42.707405+0300 XXX[2808:1326160] CGAffineTransformInvert: singular matrix.
May 25 10:10:42  XXX[2808] <Error>: CGAffineTransformInvert: singular matrix.
2017-05-25 10:10:42.707460+0300 XXX[2808:1326160] CGAffineTransformInvert: singular matrix.
May 25 10:10:42  XXX[2808] <Error>: CGAffineTransformInvert: singular matrix.

I changed it to XXX from my app.

My code:

        self.m_LineChart = graph
        self.m_LineColor = linecolor
        self.m_LineChart.delegate = parent
        m_LineChartDataSet = LineChartDataSet()
        m_LineChartDataSet.label = "";
        m_LineChartDataSet.drawCirclesEnabled = false
        m_LineChartDataSet.drawValuesEnabled = false
        m_LineChartDataSet.drawFilledEnabled = false
        m_LineChartDataSet.lineWidth = 1.8
        m_LineChartDataSet.setColor(m_LineColor)
        m_LineChartDataSet.drawIconsEnabled = false
        m_LineChartDataSet.drawCircleHoleEnabled = false
        m_LineChartDataSet.drawVerticalHighlightIndicatorEnabled = false
        m_LineChartDataSet.drawHorizontalHighlightIndicatorEnabled = false
 
        //_ = m_LineChartDataSet.addEntry(ChartDataEntry(x: Double(1) , y: Double(0) ))
        //m_LineChartData = LineChartData()
        //m_LineChartData.addDataSet(m_LineChartDataSet)
        
        // set the dataset
        self.m_LineChart.data = LineChartData()
        self.m_LineChart.data?.addDataSet(m_LineChartDataSet)
        //self.m_LineChart.notifyDataSetChanged()
        
        self.m_LineChart.noDataText = ""
        self.m_LineChart.chartDescription?.text = ""
        
        self.m_LineChart.dragEnabled = false
        self.m_LineChart.pinchZoomEnabled = false
        self.m_LineChart.doubleTapToZoomEnabled = false
        self.m_LineChart.isMultipleTouchEnabled = false
        self.m_LineChart.isUserInteractionEnabled = false
        self.m_LineChart.highlightPerTapEnabled = false
        
        
        // Right Axis
        self.m_LineChart.rightAxis.drawLabelsEnabled = false
        self.m_LineChart.rightAxis.drawGridLinesEnabled = false
        self.m_LineChart.rightAxis.drawZeroLineEnabled = false
        self.m_LineChart.rightAxis.drawLimitLinesBehindDataEnabled = false
        self.m_LineChart.rightAxis.drawTopYLabelEntryEnabled = false
        self.m_LineChart.rightAxis.drawBottomYLabelEntryEnabled = false
        self.m_LineChart.rightAxis.drawAxisLineEnabled = false
        // LEft Axis
        self.m_LineChart.leftAxis.drawLabelsEnabled = false
        self.m_LineChart.leftAxis.drawGridLinesEnabled = false
        self.m_LineChart.leftAxis.drawZeroLineEnabled = false
        self.m_LineChart.leftAxis.drawLimitLinesBehindDataEnabled = false
        self.m_LineChart.leftAxis.drawTopYLabelEntryEnabled = false
        self.m_LineChart.leftAxis.drawBottomYLabelEntryEnabled = false
        self.m_LineChart.leftAxis.drawAxisLineEnabled = false
        //X axis
        self.m_LineChart.xAxis.drawLabelsEnabled = false
        self.m_LineChart.xAxis.drawGridLinesEnabled = false
        self.m_LineChart.xAxis.drawLimitLinesBehindDataEnabled = false
        self.m_LineChart.xAxis.drawAxisLineEnabled = false
        
        // Disable legend
        self.m_LineChart.legend.enabled  = false
        
        //set background color transperent
        self.m_LineChart.backgroundColor = UIColor.black.withAlphaComponent(0.0)
        self.m_LineChart.drawBordersEnabled = true
        self.m_LineChart.borderColor = UIColor.white.withAlphaComponent(0.3)
        //self.m_LineChart.borderLineWidth = 0.1
        self.m_LineChart.autoScaleMinMaxEnabled = true

Thanks,
David

**Comment by liuxuan30** [comment]
always put self.m_LineChart.data = LineChartData() at last or call notifyDataSetChanged() bafter you chnge the chart properties.

**Comment by davidra7** [comment]
Hi,
Thanks for answer but it didn't work .
I tried to move it last and add notifyDataSetChanged() or just add notifyDataSetChanged().
If I disable the autoScale option the error disappear.

Any suggestions ?

Thanks,
David

**Comment by thierryH91200** [comment]
m_LineChartDataSet no data x and y ???

```
 //_ = m_LineChartDataSet.addEntry(ChartDataEntry(x: Double(1) , y: Double(0) ))
    //m_LineChartData = LineChartData()
    //m_LineChartData.addDataSet(m_LineChartDataSet)
```

**Comment by davidra7** [comment]
m_LineChartDataSet is blank without data.
Even if I add data it has the same error

**Comment by thierryH91200** [comment]
modify

![capture d ecran 2017-05-28 a 10 40 26](https://cloud.githubusercontent.com/assets/6251463/26527335/1e4b3b88-4392-11e7-9029-d1157e509d71.png)


```
var yVals1 = [ChartDataEntry]()

var mult = 10 * 2.0
for i in 0..<20 {
    let val = Double(arc4random_uniform(UInt32(mult))) - 30
    yVals1.append(ChartDataEntry(x: Double(i), y: val))
}

var m_LineChartDataSet = LineChartDataSet()

m_LineChartDataSet = LineChartDataSet(values: yVals1, label: "DataSet 1")
m_LineChartDataSet.label = "Test";
m_LineChartDataSet.drawCirclesEnabled = false
m_LineChartDataSet.drawValuesEnabled = false
m_LineChartDataSet.drawFilledEnabled = false
m_LineChartDataSet.lineWidth = 1.8
m_LineChartDataSet.setColor(NSUIColor.black)
m_LineChartDataSet.drawIconsEnabled = false
m_LineChartDataSet.drawCircleHoleEnabled = false
m_LineChartDataSet.drawVerticalHighlightIndicatorEnabled = false
m_LineChartDataSet.drawHorizontalHighlightIndicatorEnabled = false

var dataSets = [LineChartDataSet]()
dataSets.append(m_LineChartDataSet)

// set the dataset
let data = LineChartData(dataSets: dataSets)
m_LineChart.data = data

```

**Comment by davidra7** [comment]
Thanks for the help , but I want a blank line chart at the beginning.

**Comment by thierryH91200** [comment]
`m_LineChart.data = nil`

m_LineChart.noDataText = "no data"




![capture d ecran 2017-05-28 a 10 56 13](https://cloud.githubusercontent.com/assets/6251463/26527419/53fe27f2-4394-11e7-91ee-0c9d415b2208.png)

**Comment by davidra7** [comment]
It works , but the first time that I create the LineChartDataSet the error appears again.

I can't load all the data before because it is real time line chart
