### ISSUE TITLE
Show Integer values on LineChart

### ISSUE THREAD

**Issue by wadheraswati** [danielgindi/Charts#2473]
I have integrated LineChart in my project and it is working fine although I am not able to have non-float integer values in my graph. I have attached a screenshot for the same. I have added these settings for xlabel.

```
![screen shot 2017-05-25 at 4 53 59 pm](https://cloud.githubusercontent.com/assets/4290856/26448467/0a57aed2-416b-11e7-9f9a-e6567a31264a.png)

ChartXAxis *xAxis = leadsChartView.xAxis;
    xAxis.labelPosition = XAxisLabelPositionBottom;
    xAxis.labelFont = [UIFont fontWithName:@"HelveticaNeue-Light" size:12.f];
    xAxis.labelTextColor = [UIColor blackColor];
    xAxis.drawAxisLineEnabled = YES;
    xAxis.drawGridLinesEnabled = YES;
    xAxis.centerAxisLabelsEnabled = NO;
    xAxis.gridColor = [[UIColor blackColor] colorWithAlphaComponent:0.1];
    xAxis.labelRotationAngle = 25;
    xAxis.granularityEnabled = YES;
    xAxis.granularity = 1.0;
    xAxis.forceLabelsEnabled = YES;
```

**Comment by wadheraswati** [comment]
@danielgindi please help soon

**Comment by thierryH91200** [comment]
use formatter

```
 //Current Values                    what you want
            let format = NumberFormatter()
            format.numberStyle = NumberFormatter. none
            let formatter = DefaultValueFormatter(formatter: format)
            xAxis.setValueFormatter(formatter)
```

https://developer.apple.com/reference/foundation/numberformatter.style/1408907-none

**Comment by wadheraswati** [comment]
I am using Objective C and this sets the xaxis values formatter not what is shown in the graph.

**Comment by liuxuan30** [comment]
Check out  ChartsDemo. There are plenty of them.

**Comment by wadheraswati** [comment]
I have solved the issue. Here is the code.
     ```
   set1 = [[LineChartDataSet alloc] initWithValues:values label:@""];
        set1.drawIconsEnabled = NO;
        set1.valueFormatter = [[SetValueFormatter alloc] init];
```

In SetValueFormatter

```
@interface SetValueFormatter : NSObject <IChartValueFormatter>

@end


@implementation SetValueFormatter
- (NSString * _Nonnull)stringForValue:(double)value entry:(ChartDataEntry * _Nonnull)entry dataSetIndex:(NSInteger)dataSetIndex viewPortHandler:(ChartViewPortHandler * _Nullable)viewPortHandler {
    return [NSString stringWithFormat:@"%d",(int)entry.y];
}

@end

```

Hope it helps other people as well.

**Comment by wadheraswati** [comment]
I have solved the issue. Here is the code.
     ```
   set1 = [[LineChartDataSet alloc] initWithValues:values label:@""];
        set1.drawIconsEnabled = NO;
        set1.valueFormatter = [[SetValueFormatter alloc] init];
```

In SetValueFormatter

```
@interface SetValueFormatter : NSObject <IChartValueFormatter>

@end


@implementation SetValueFormatter
- (NSString * _Nonnull)stringForValue:(double)value entry:(ChartDataEntry * _Nonnull)entry dataSetIndex:(NSInteger)dataSetIndex viewPortHandler:(ChartViewPortHandler * _Nullable)viewPortHandler {
    return [NSString stringWithFormat:@"%d",(int)entry.y];
}

@end

```

Hope it helps other people as well.

**Comment by wadheraswati** [comment]
![screen shot 2017-05-25 at 4 53 59 pm](https://cloud.githubusercontent.com/assets/4290856/26488595/aaadf2ae-4221-11e7-96b7-2f10a8c8aff6.png)

**Comment by RubyRoshan** [comment]
Hi,

I am using the below code : 
`-(NSString * _Nonnull)stringForValue:(double)value entry:(ChartDataEntry * _Nonnull)entry dataSetIndex:(NSInteger)dataSetIndex viewPortHandler:(ChartViewPortHandler * _Nullable)viewPortHandler{
    if(_SelectedGraph.type==FPStationGraphTypeWind){
        return [NSString stringWithFormat:@"%@",[_SelectedGraph.arrayDirections objectAtIndex:dataSetIndex]];
    }
    else{
        return [NSString stringWithFormat:@"%@",@""];
    }
}`

` LineChartDataSet *dataSet  = [[LineChartDataSet alloc]initWithValues:arrayXYValue label:_SelectedGraph.graphLineText];
    [dataSet setValueColors:@[[UIColor whiteColor]]];
    [dataSet setValueFont:[UIFont fontWithName:@"HelveticaNeue" size:13.0]];
    dataSet.valueFormatter = self;`
but it did not  get called on this method.
