### ISSUE TITLE
Two markers on one line [LineChartView]

### ISSUE THREAD

**Issue by xRena** [danielgindi/Charts#2476]
Hello,

I have a problem with showing more than one marker on my line chart. I need first marker at the end of the line and second marker in specific point. How I can do this? Is this even possible?

Thanks!

**Comment by liuxuan30** [comment]
I'd say possible, but you have to write some code to get it work. e.g draw two markers at the same time. Just look at  `drawMarkers` and override it.

**Comment by lanmoyingsheng** [comment]
so import Charts with Source code but not Cocoapods?
oh...
