### ISSUE TITLE
Pinch to Zoom is not working as expected over Bar Chart

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [danielgindi/Charts#2479]
Hi,

I have used bar chart. And currently set the following properties of it:

```
self.barChart?.doubleTapToZoomEnabled = false
self.barChart?.pinchZoomEnabled = false
barChart.dragEnabled = false
```
        
But still the zoom is happening. One of the reason that I have not tried out might be disable the individual axis scaling. Can some one please provide me the code for that or any other solution that will work ?

**Comment by liuxuan30** [comment]
Are you saying if you turn off `pinchZoomEnabled`, pinch zoom gesture still work? I doubt that.

**Comment by CavalcanteLeo** [comment]
you may forgot to use this:

Objective-c:

```objective-c
    self.chartView.scaleXEnabled = NO;
    self.chartView.scaleYEnabled = NO;
```



swift: 
```swift
    self.barChart?.scaleYEnabled = false
    self.barChart?.scaleXEnabled = false
```
