### ISSUE TITLE
Display header label on xAxis and yAxis

### ISSUE THREAD

**Issue by irshad9998** [danielgindi/Charts#2485]
Hello,

I want to set header title as like below image
![screen shot 2017-05-30 at 11 21 39 am](https://cloud.githubusercontent.com/assets/11401920/26575636/ab259c80-4543-11e7-9b20-d4c8216f7b44.png)

Show 

> Distance 

> Oct 

title as respective

**Comment by zykis** [comment]
Hello! Good for you!

**Comment by irshad9998** [comment]
@zykis  thanks but what you mean to say?

**Comment by liuxuan30** [comment]
check ChartMarker
