### ISSUE TITLE
How to round corner in Radar Charts?

### ISSUE THREAD

**Issue by reza-khalafi** [danielgindi/Charts#2487]
Hello  
How to round corners of polygon in Radar mode like this:  
<img width="366" alt="screen shot 2017-05-30 at 5 11 18 pm" src="https://cloud.githubusercontent.com/assets/8235321/26583645/4d05c25c-455b-11e7-8fcc-3c7ad2d95ee1.png">

**Comment by liuxuan30** [comment]
That would be drawing arc instead of connect dots.
