### ISSUE TITLE
Graph x-axis values not displaying in swift 3.0

### ISSUE THREAD

**Issue by Aanchaljain9988** [danielgindi/Charts#2488]
@danielgindi : ![simulator screen shot may 30 2017 8 14 02 pm](https://cloud.githubusercontent.com/assets/18482407/26589077/aeade8cc-4574-11e7-9c3a-cc3b66b33591.png)

I have added values for all bars but its not showing x-values corresponding to every bar. I am using this code : 
class ChartStringFormatter: NSObject, IAxisValueFormatter {
    
    var nameValues  = [String]()
    
    public func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        
        let index = Int(value.rounded())
        
        if index < 0 || index >= nameValues.count || index != Int(value)
        {
            return ""
        }
        
        print("arry is",nameValues)
        return String(describing: nameValues[Int(value)])
    }
}

**Comment by liuxuan30** [comment]
Not every bar can show x value by default due to space limit. Check out ChartsDemo and `computeAxisValues` to see how the x entries are generated, and override it and supply what you need
