### ISSUE TITLE
I used Charts in my iOS project and when I start to zoom the chart labels on xAxis get repeated again and again. How can I fix my problem?

### ISSUE THREAD

**Issue by mengruirui** [danielgindi/Charts#2493]
![f5d3c537-63fc-4372-a79f-81d8406d8c24](https://cloud.githubusercontent.com/assets/15345294/26712268/a90f8ab2-4798-11e7-92b7-f065b61b670b.png)

**Comment by liuxuan30** [comment]
use `granularity`
