### ISSUE TITLE
Bar values inside bar horizontally?

### ISSUE THREAD

**Issue by Sachin0912** [danielgindi/Charts#2494]
Hello 
I just want the values inside the bar horizontally in Bar graph.
Please help me out.
Thanks

**Comment by thierryH91200** [comment]
try

chartView.drawValueAboveBarEnabled = false

**Comment by Sachin0912** [comment]
![ochbedekfiffabej](https://cloud.githubusercontent.com/assets/17583565/26721771/c23c1af2-47aa-11e7-98af-9a09542a67df.png)

please check this screen we need this .

**Comment by thierryH91200** [comment]
is' is a HorizontalBarChartView

<img width="725" alt="capture d ecran 2017-06-02 a 15 03 53" src="https://cloud.githubusercontent.com/assets/6251463/26726829/d4265d46-47a4-11e7-9477-a00fe216bdc6.png">

**Comment by liuxuan30** [comment]
@Sachin0912 this is not supported as it's highly customized. But it's doable to override bar chart renderer `drawValues()`

**Comment by Sachin0912** [comment]
drawValues() function have y axis value and bar values both. how can we differentiate those?

**Comment by liuxuan30** [comment]
why you said y axis? It's just for bar values.
