### ISSUE TITLE
PieChart render very small

### ISSUE THREAD

**Issue by sudhir9026** [danielgindi/Charts#2495]
I took UIView size 55*55 for pie chart but i show my chart(circle) very small. can i do something without increase size of view?

**Comment by liuxuan30** [comment]
what it looks like?

**Comment by sudhir9026** [comment]
Yes, I think piechart is making  size 18*18 that look very small.

**Comment by liuxuan30** [comment]
Have you tried to reduce some margins, like `minOffset`

**Comment by sudhir9026** [comment]
Yes i did R &D and found in PieRadarChartViewBase.swift a variable declared **var minOffset = CGFloat(10.0)**.this is hardcoded when i reduce value then perfect for me. but when i change this file it effect all piechart that use my project but i want change for only this chart.

**Comment by thierryH91200** [comment]
chartView.minOffset = 0.0
