### ISSUE TITLE
Chart points are being clipped out in ScatterChart

### ISSUE THREAD

**Issue by Eranot** [danielgindi/Charts#2496]
Hey, awesome work with the library, but I'm stuck with this problem, when the Entry X is equal to  the AxisX.axisMaximum half of the point is clipped out, like this:
![captura de tela 2017-06-02 as 17 21 48](https://cloud.githubusercontent.com/assets/13923596/26743417/1407c73e-47b8-11e7-909c-c4867f6b692f.png)
I honestly tried a lot of things but couldn't find a way to make this right. Thank you for the help.

**Comment by liuxuan30** [comment]
Since you set axisMaximum, when it reaches the edge, everything will be clipped, that's by design in `draw()` line 224. either you incrase your `axisMaximum` or not clipped, but it will have side effects when zooming and scrolling.
