### ISSUE TITLE
How to change the label colors of certain XAxis values?

### ISSUE THREAD

**Issue by praveenbroski** [danielgindi/Charts#2498]
I want the change the XAxis label colors. I want it like the following diagrampicture.

Please provide a way to change the color of certain XAxis labels.
Thanks in advance.

![sdgsdg](https://cloud.githubusercontent.com/assets/14329980/26751658/2f1619f0-485c-11e7-92dd-4f6f08a236c9.png)

**Comment by liuxuan30** [comment]
just override `drawLabels()` or add xAxis.labelTextColors array instead of sole `xAxis.labelTextColor`
