### ISSUE TITLE
Chart not in centre of view

### ISSUE THREAD

**Issue by kateNgo** [danielgindi/Charts#2502]
My chart is not in the centre of chart view. It is at upper half of view. Anyone help me please
This is landscape:
![landscape](https://cloud.githubusercontent.com/assets/3839067/26812441/162deec0-4abb-11e7-943f-2a25c2b95d17.png)
This is portrait
![portrait](https://cloud.githubusercontent.com/assets/3839067/26812442/162fe428-4abb-11e7-9d33-1dad1ab7194c.png)

**Comment by thierryH91200** [comment]
the height of longest label "Data, Measurement..........." Corresponds to the space between the axis and the legend with
` xAxis.labelPosition  = .bottomInside`


bug i think

**Comment by kateNgo** [comment]
Thanks thierryH91200. 
I do not think bug is from
 xAxis.labelPosition = .bottomInside. When I change this into .top or .insideTop , the problem is the same:
![simulator screen shot 6 jun 2017 9 02 16 am](https://cloud.githubusercontent.com/assets/3839067/26807035/376e2b3c-4a97-11e7-8eba-e5c865dc9ac3.png)

**Comment by kateNgo** [comment]
I removed 8 lines in charts in class BarLineChartViewBase as your suggestion but the problem is still. Please help me to have a look.
Actually, the isssue does not happen if I do not make a 90 of rotate label ( xaxis.labelRotationAngle = CGFloat(90))

**Comment by thierryH91200** [comment]
Have you built charts only again?
This is the only change I made
for me no problem

<img width="1570" alt="capture d ecran 2017-06-06 a 07 50 27" src="https://cloud.githubusercontent.com/assets/6251463/26815497/f890401c-4a8c-11e7-9ee0-81d70d74b61a.png">

**Comment by kateNgo** [comment]
I have just cut these chart from the screens. I also tried to fixed as your recommendation but It does not work for me. When I debug, this function is not called when these charts created.

**Comment by thierryH91200** [comment]
If the legend is true it is forced to pass in the function for calculateLegendOffsets
try
 Just to see if you are entering this function
Regardless of the result

print ( offsetBottom )
 offsetBottom += min(_legend.neededHeight, _viewPortHandler.chartHeight * .... etc
//                    if xAxis.isEnabled && xAxis.isDrawLabelsEnabled
 //                   {
 //                       offsetBottom += xAxis.labelRotatedHeight
 //                   }
 print ( offsetBottom )

**Comment by thierryH91200** [comment]
other solution

legend.enabled = false

**Comment by kateNgo** [comment]
when legend.enabled = false, the chart is at right position where I want
![legendfalse](https://user-images.githubusercontent.com/3839067/26861705-047f57f8-4b89-11e7-8943-60b1a32510c6.png)

However, I need legend to show more infor about the chart like the below:
![legendtrue](https://user-images.githubusercontent.com/3839067/26861717-1f209d4c-4b89-11e7-8fad-a2b677173503.png)

**Comment by thierryH91200** [comment]
try

 ```
// MARK: legend
        let legend = chartView.legend
        legend.enabled = true
        legend.orientation = .horizontal
        legend.horizontalAlignment = .left
        legend.verticalAlignment = .top
        legend.drawInside = true
```

**Comment by kateNgo** [comment]
Thanks for your time. The problem is gone. You helped me a lot.
