### ISSUE TITLE
How to remove decimals from y values in iOS Charts?

### ISSUE THREAD

**Issue by jonsonasMafjiozas** [danielgindi/Charts#2506]
in the line chart if the yValue is less than 3 digits it shows decimal, How can I remove the decimal from the yValues? Im using the latest release with swift 3
Thanks in advance!!
<img width="292" alt="c9jqj" src="https://user-images.githubusercontent.com/15992747/26841152-7c202612-4a9d-11e7-803d-c2ebb3f4358a.png">

**Comment by liuxuan30** [comment]
use valueFormatter...
