### ISSUE TITLE
Inserting dataPoint "labels" in Radar Chart

### ISSUE THREAD

**Issue by tiagoguy** [danielgindi/Charts#2508]
Hello,

I've been struggling to place the "labels" (not sure that  is what they're called) to each of the Radar Chart's axis in this new version of Charts. Formerly, I was able to do so by through the XVals parameter in RadarChartData (ie: radarChartData = RadarChartData(xVals: dataPoints, dataSet: radarChartDataset), where dataPoints is my string array); in this version, I would assume this could be done through the "data" section of RadarChartDataEntry(value: , data: ); however, upon placing my dataPoints in the aforementioned section, all I get is numbers from 0 up to the size of the array.

Thanks in advance.

**Comment by Rovel** [comment]
fix #1840
