### ISSUE TITLE
Swift 3 Cubic line chart 

### ISSUE THREAD

**Issue by hemanthalluri** [danielgindi/Charts#2510]
is there any example for cubic line chart in Swift 3

**Comment by liuxuan30** [comment]
line chart support cubic mode already.

**Comment by hemanthalluri** [comment]
could you please give any swift example. charts demo is in objective-C. Or atleast tell me where can I find swift example...

**Comment by liuxuan30** [comment]
The api keeps the same and you can also search cubic in Swift code. you don't have to know how to write objC, but reading objC should not be a problem.
