### ISSUE TITLE
Right Align Y Value Labels for Horizontal Bar Chart

### ISSUE THREAD

**Issue by AaronVinh** [danielgindi/Charts#2512]
Is it possible to right align the y value labels for Horizontal Bar Chart?  Currently now my labels are displayed to directly to the right of the bar.
<img width="446" alt="screen shot 2017-06-10 at 2 55 59 pm" src="https://user-images.githubusercontent.com/14302659/27006601-09354986-4ded-11e7-8c48-6ddd36ff4f19.png">

however, I would like them to be right aligned like in this image.  Is this possible?
<img width="295" alt="screen shot 2017-06-10 at 2 54 53 pm" src="https://user-images.githubusercontent.com/14302659/27006607-18cd3e4e-4ded-11e7-913c-f29d915eb3dc.png">

**Comment by liuxuan30** [comment]
No, it has to be done by you, overriding `drawValues()` in renderer code
