### ISSUE TITLE
Not working with Xcode 9 Beta1

### ISSUE THREAD

**Issue by nikhilpandey4** [danielgindi/Charts#2514]
Hi,
Libraries are not working with Xcode 9 Beta1. Please have a look.

Regards,
Nikhil

**Comment by petester42** [comment]
We will make sure everything works fine with Xcode 9 but don't expect us to fix all the issues now since Xcode 9 is far from finished. The only guarantee that we can make is that for the Xcode 9 release version the library will work.

**Comment by liuxuan30** [comment]
refer #2507 
I don't know why you ask 'not work' as Swift 4 is compatible with Swift 3. Yes there are changes in Swift 4, but at least current library will work on Xcode 9 fore sure.

**Comment by nikhilpandey4** [comment]
Hi
Library is not compiling in Xcode 9 beta, as its giving errors.

**Comment by liuxuan30** [comment]
Well, you should choose Swift 3 for it.
