### ISSUE TITLE
How to run in Xcode 9 (beta)

### ISSUE THREAD

**Issue by xoniq** [danielgindi/Charts#2520]
I have the target iOS version for my project set-up to iOS 9.0.

But I cannot build it with the charts (installed using CocoaPods), it gives errors, but thought I read somewhere it should be compatible with former Swift versions.

**Comment by surayashivji** [comment]
+1

**Comment by liuxuan30** [comment]
I am not sure. Have you change to swift 3.0 compatibility in xcode 9? I can build and run the ChartsDemo without any changes.

**Comment by xoniq** [comment]
What's the proper way of doing this? Never used the compatibility mode before.

**Comment by liuxuan30** [comment]
In Xcode 9 build settings, 
![image](https://user-images.githubusercontent.com/4375169/27363105-119abc52-5665-11e7-9dff-96b15aab67ca.png)
But I am not sure if this is the cause. Honestly I just compile and run without any errors except warnings.

**Comment by xoniq** [comment]
Yes, that was the solution!
When selecting the 'Pods' project, select the 'Charts' target and there I set the Swift Compiler to 3.2. Now the errors are gone.

**Comment by macro-dadt** [comment]
my  'Charts' target already set to 3.2 Swift Compiler to 3.2  initially. Then i select  the 'Pods' project, select the 'Charts' target and there I set the Swift Compiler to 4.0. Build again and errors gone

**Comment by wonder2011** [comment]
@liuxuan30 Please help. When i add this pod, my project not compoling. I change the Swift version to 3.2, clean, recompile, nothing. I try Swift 3.2, crean, recompile, nothing. I'm using XCode 9.2 targeting iOS 11.0. Help please !

**Comment by macro-dadt** [comment]
@wonder2011 on add to your pod file 
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        target.build_configurations.each do |config|
            if ['Charts'].include? target.name
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end`

**Comment by wonder2011** [comment]
@macro-dadt thanks a lot, but i'm updating to XCode 9.4.1. This lib compile on this version with no problems?
