### ISSUE TITLE
Delegate Memory Leak

### ISSUE THREAD

**Issue by MikasaAckerman** [danielgindi/Charts#2523]
lineChartView.delegate = self
lineChartView.xAxis.valueFormatter = self

if this two lines are added，deinit() isn't executed……
sorry，how to do 啊……

**Comment by MikasaAckerman** [comment]
sorry to open the issue.
i have solved this problem by
override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        lineChartView.delegate = nil
        lineChartView.xAxis.valueFormatter = nil
}
sorry to bother you...

**Comment by paktree** [comment]
We ran into this issue also. To me, this feels like an issue with the valueFormatter not having weak property. Could this be fixed in the SDK instead of setting those values to nil in the dealloc/viewWillDisappear function?

Thanks
