### ISSUE TITLE
What is the equivalent of "onChartDoubleTapped"?

### ISSUE THREAD

**Issue by ibrahimyilmaz7** [danielgindi/Charts#2524]
I can't find any detail about onChartDoubleTapped on swift version.

How can i listen doubleTapped gesture of chart?

**Comment by liuxuan30** [comment]
I don't know where you saw onChartDoubleTapped, there is only 
>@objc fileprivate func doubleTapGestureRecognized(_ recognizer: NSUITapGestureRecognizer)
