### ISSUE TITLE
Changing BarChart xAxis label position

### ISSUE THREAD

**Issue by thierrybucco** [danielgindi/Charts#2526]
Hello,

Here is what I am be able to do:

![capture d ecran 2017-06-15 a 15 31 41](https://user-images.githubusercontent.com/12764744/27198638-05747392-51e1-11e7-93bc-8420617a54a8.png)

I would to have labels like this:

![capture d ecran 2017-06-15 a 15 31 41 copie](https://user-images.githubusercontent.com/12764744/27198649-1a88f582-51e1-11e7-808a-909d7a682589.png)

Do you know how to do this?

Thanks

**Comment by liuxuan30** [comment]
enable `centerLabelEnabled`
