### ISSUE TITLE
BarGraph - 0 values - Bar Offset

### ISSUE THREAD

**Issue by denebj** [danielgindi/Charts#2528]
I have an issue of the weird spacing when I have 0 values in my bar graph.

So I just created a default bar chart with a 0 value and I have the issue - I tried to get as close as possible to a simple bar to see what was the issue.

It looks like the demo but a soon as I put a 0 value , I get a padding.

Here the sample code :

   @IBOutlet var barChartView: BarChartView!

 func viewDidLoad() {
        super.viewDidLoad()
         self.styleChart()
         self.configureChart()
    }

    internal func styleChart() {
        self.barChartView.xAxis.labelPosition = .bottom
        self.barChartView.xAxis.labelCount = 2
    }
    
    internal func configureChart() {
        
        var xValues = [String]()
        var entries: [ChartDataEntry] = Array()

         xValues.append("TEST 5")
         xValues.append("TEST 0")
         entries.append(BarChartDataEntry(x: Double(0), y: Double(5) ))
         entries.append(BarChartDataEntry(x: Double(1), y: Double(0) ))
        
        
        let dataSet = BarChartDataSet(values: entries, label: "")
        dataSet.drawIconsEnabled = false
        dataSet.drawValuesEnabled = true

        let formatter = NumberFormatter()
        formatter.numberStyle = NumberFormatter.Style.decimal
        dataSet.valueFormatter = DefaultValueFormatter(formatter: formatter)

        let barChartData = BarChartData(dataSet: dataSet)
        barChartData.barWidth = 0.2        
         self.barChartView.data = barChartData
    }
Pretty straightforward.

It is a bug ?

Issue with 0 :
![27046056-aa244e9c-4f68-11e7-9dba-eb8910082ce4](https://user-images.githubusercontent.com/14078617/27236870-4c843a28-528c-11e7-8945-6990dfd74b8e.png)

No 0 :
![27046346-acd37e6e-4f69-11e7-9403-b18616dd74ef](https://user-images.githubusercontent.com/14078617/27236875-4ffa05b6-528c-11e7-9292-5b2c9c55c9e1.png)

**Comment by liuxuan30** [comment]
not really. The y axis range is calculated by your data range. To keep your chart inside the canvas, the axis range will be larger than your data range. Check out `computeAxisValues()` to have a good understanding how it generate the ranges.

If you want the y axis starts from 0, set `leftAxis.axisMinimum = 0`

**Comment by denebj** [comment]
Ah ok :) Thank you for the explanation !
