### ISSUE TITLE
zoom programatically, reset the zoom, set the highlight and moving the X-Axis and the Y-Axis to the middle

### ISSUE THREAD

**Issue by MFJones21** [danielgindi/Charts#2529]
The last few days I worked with your, absolutely awesome, iosCharts library and I am doing an App that Plots Graphs. I have a few funcitionalitys that I need bit could not find anywhere how to make happen. 

1. How can I reset the zoom reliably I tried multiple things that did not work. How do I do it properly ?

2. How can I get the „from“ and to „values“ of the X and Y Axis when the view is getting zoomed

3. How can I zoom programatically

4. How can I programatically set the Highlight to a Point on X-Axis ?

5. Is it possible to move the X-Axis and the Y-Axis to the middle of the Chart ? And if yes, how ?

Thanks a lot for your help in advance and for contributing to this awesome library !

**Comment by liuxuan30** [comment]
Most of your zoom requirement is implemented in `ViewPortHandler` so check it out like
>open func resetZoom() -> CGAffineTransform
open func setZoom(scaleX: CGFloat, scaleY: CGFloat) -> CGAffineTransform

highlight can be code using highlight funcs inside `ChartViewBase` like
>open func highlightValues(_ highs: [Highlight]?)
open func highlightValue(x: Double, y: Double, dataSetIndex: Int)

By default you can't move xAxis or yAxis in to the middle. But there are something can do it:
1. use ChartLimitLine to draw the line, if you don't need the labels.
2. if you really need, then you have to change the code to draw them in the middle by overriding some methods inside AxisRenderer. To calculate the middle point, you can refer to UIView's center or `contentRect`'s center.
