### ISSUE TITLE
Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<NSArray>' to expected argument type 'AutoreleasingUnsafeMutablePointer<NSArray?>?'

### ISSUE THREAD

**Issue by surayashivji** [danielgindi/Charts#2530]
I'm getting this issue while trying to run the iOS example code (Objective-C) on the Xcode 9 beta. 

Cannot convert value of type 'AutoreleasingUnsafeMutablePointer<NSArray>' to expected argument type 'AutoreleasingUnsafeMutablePointer<NSArray?>?'

<img width="1673" alt="screen shot 2017-06-17 at 2 45 11 pm" src="https://user-images.githubusercontent.com/12003060/27256499-96e68ee2-536b-11e7-9371-8c23866c5035.png">

Does anyone have any idea on a fix?

**Comment by liuxuan30** [comment]
I really don't know why you can't run it while I just downloaded xcode 9 beta and simply clicked build and run without any issue.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4375169/27313460-7d2318b8-55a0-11e7-83df-921d74b1190c.png">
Have you touched anything?

**Comment by thierryH91200** [comment]
```
open class func viewFromXib() -> MarkerView?
    {
        #if !os(OSX)
            return Bundle.main.loadNibNamed(
                String(describing: self),
                owner: nil,
                options: nil)?[0] as? MarkerView
        #else
            
            var loadedObjects = NSArray()
            let loadedObjectsPointer = AutoreleasingUnsafeMutablePointer<NSArray?>(&loadedObjects)
            
            if Bundle.main.loadNibNamed(
                String(describing: self),
                owner: nil,
                topLevelObjects: loadedObjectsPointer)
            {
                return loadedObjects[0] as? MarkerView
            }
            
            return nil
        #endif
    }

```
Types that are pointed to are not bridged. For example, NSString ** comes over to Swift as AutoreleasingUnsafeMutablePointer<NSString?>, not AutoreleasingUnsafeMutablePointer<String?>.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithCAPIs.html

**Comment by liuxuan30** [comment]
@thierryH91200 what's the cause? I don't see any error on my side.

**Comment by surayashivji** [comment]
Worked with that fix! Thanks @thierryH91200 and @liuxuan30

**Comment by thierryH91200** [comment]
Actually I do not know but I have encountered this problem
I did not do anything extraordinary
Can be a clean build or something else
Without answer
