### ISSUE TITLE
Replace the value label without redraw the bar.

### ISSUE THREAD

**Issue by JakeToWork** [danielgindi/Charts#2535]
<img width="375" alt="screen shot 2017-06-20 at 1 09 17 am" src="https://user-images.githubusercontent.com/28650820/27300171-5e765ff4-5561-11e7-8f2f-889eeec00110.png">
the bars are unreadable
so I add codes to range the value
`

func range(_ value: Double) -> Double{

        if value >= 100.00 {
             return ((value / 100.00) + 40)
        }else if value >= 10 && value < 100 {
            return (value/10.0 + 30)
        }else if value >= 1 && value < 10{
            return (value + 20)
        }else if value >= 0.1 && value < 1{
            return ((10 * value) + 10)
        }else if value < 0.1 {
            return (100 * value)
        }
        return 0
    }
`
it becomes 
<img width="366" alt="screen shot 2017-06-20 at 12 57 06 am" src="https://user-images.githubusercontent.com/28650820/27300299-d6adfaa4-5561-11e7-803f-cb2d3452a2ba.png">

but how do I replace the label of values back to it's original value?

**Comment by liuxuan30** [comment]
use `valueFormatter` 
however what you did just twisted the value and bars it should be...
You have 750 for one bar, and 0.x - 1.x for several bars, so the first image reflects the reality.
