### ISSUE TITLE
Pie Chart Highlighted region 

### ISSUE THREAD

**Issue by ashkhan13** [danielgindi/Charts#2536]
Hello, 

This is more of a question than an issue. I am using a Pie chart in my app and for some reason when I run it, the slice I select on the pie chart doesn't highlight (or doesn't do anything at all). How do I fix this?

**Comment by liuxuan30** [comment]
Try add break point at the delegate method to see if it's get invoked. It's hard to say where goes off. But you should be able to track adding some breakpoints. Do play with ChartsDemo and the code.

**Comment by ashkhan13** [comment]
Thanks a lot for your help. Apparently, I had this line chartDataSet.selectionShift = 0 in my code for some bizarre reason. Its working perfectly now.
