### ISSUE TITLE
Need swift combined chart demo.

### ISSUE THREAD

**Issue by sanjay07dce050** [danielgindi/Charts#2540]
I am using this charts library. I am using combined chart. In combined chart, I am using line and bar chart. Is there any swift demo of that?

**Comment by liuxuan30** [comment]
there is one PR aimed for swift version, you can check it out.

**Comment by thierryH91200** [comment]
I will be nice
The playground is for my tests
The other is an obj c conversion to swift
There is no modification for Charts to be able to use it (macOS) which is not the case for iOS

[CombinedChartViewController.storyboard.zip](https://github.com/danielgindi/Charts/files/1090269/CombinedChartViewController.storyboard.zip)

[PlaygroundChart.playground.zip](https://github.com/danielgindi/Charts/files/1090261/PlaygroundChart.playground.zip)

[CombinedChartViewController.swift.zip](https://github.com/danielgindi/Charts/files/1090262/CombinedChartViewController.swift.zip)
