### ISSUE TITLE
Swift language upgrade required 

### ISSUE THREAD

**Issue by tlandsmancars** [danielgindi/Charts#2544]
Xcode 9 can still work with projects in Swift 3.2 but not Swift 3.1.
When can it be updated to at least Swift 3.2 if not Swift 4?

**Comment by liuxuan30** [comment]
it's already 3.2, don't you check the master branch first?

**Comment by tlandsmancars** [comment]
Hi,

If I’m looking at the wrong place, please let me know.
This link https://github.com/danielgindi/Charts/tree/master suggests I’m looking at master.  The read me says Xcode 8.0 / Swift 3.1



Sincerely,

Tanya Landsman
Professional Mobile Application Developer
_________________________
Cars.com
300 S. Riverside Plaza | Suite 1000 |Chicago, IL 60606
T (312) 601.5248 | C (773) 807.4161 |
LinkedIn<https://www.linkedin.com/company/cars-com> | Twitter<https://twitter.com/carsdotcom> | Facebook<https://www.facebook.com/CarsDotCom> | YouTube<http://www.youtube.com/user/Carscom>

[cid:image001.png@01D2EE68.3A8CC840]

**Comment by liuxuan30** [comment]
You can open the project on Xcode 9 and simply compile and run.

**Comment by liuxuan30** [comment]
There is a PR #2507 ongoing, but it generates lots of warnings, so I shall wait for a while. But it's already on Swift 4 and you can use it.
