### ISSUE TITLE
Hide graph label if value fall below a certain threshold/minimum

### ISSUE THREAD

**Issue by VincentV89** [danielgindi/Charts#2547]
I want to hide graph label when value fall below a certain integer. I tried setting the **formatter.minimum** attribute to 12 & 0.12 which doesnt work. Please advise.

<img width="272" alt="screen shot 2017-06-21 at 12 31 52 am" src="https://user-images.githubusercontent.com/17560003/27416660-61b25d58-5741-11e7-80e9-0d333729a017.png">

**Comment by liuxuan30** [comment]
try this https://github.com/danielgindi/Charts/pull/944, not merged yet.
