### ISSUE TITLE
How to set the label count for X axis ?

### ISSUE THREAD

**Issue by samarth220194** [danielgindi/Charts#2548]
In my data, I have hundreds of values for the x-axis, but I want to show only 6 or 7 of them at equal intervals so that my whole range of x-axis values are covered, but I am facing an issue as I am not able to show a limited number of values on the x-axis . I tried these 
`      lineChartView.xAxis.spaceMin = 4
        lineChartView.xAxis.spaceMax = 7
        lineChartView.xAxis.xOffset = 6
        lineChartView.xAxis.labelCount = 6
        lineChartView.xAxis.labelCount = 6` 
, but it is not working .Here is my screenshot for the display 
![screen shot 2017-06-22 at 10 18 47 am](https://user-images.githubusercontent.com/17960987/27417834-cfde3700-5734-11e7-8f84-35acbdf6fe75.png)

**Comment by cartmanguo** [comment]
try this:                       
`lineChartView.xAxis.setLabelCount(7, force: true)`

**Comment by samarth220194** [comment]
I got it right .I was not parsing the data properly .The above shown data in the x axis is a string separated with commas.Thats why it was causing problems .Thank man 👍

**Comment by samarth220194** [comment]
One question i wanted to ask : How to remove the value being written on the chart .That "110" in the above screenshot

**Comment by liuxuan30** [comment]
disable `drawValuesEnabled`

**Comment by ioskunal** [comment]
I was getting one less value at the end. The reason was I had set `lineChartView.xAxis.centerAxisLabelsEnabled = true`. Setting it to `false` if the trick.
