### ISSUE TITLE
Duplicates x-axis labels are plotted separately in graph?

### ISSUE THREAD

**Issue by SamSundar1** [danielgindi/Charts#2549]
<img width="285" alt="screen shot 2017-06-22 at 1 37 18 pm" src="https://user-images.githubusercontent.com/28752883/27423129-574f7b52-5750-11e7-9d3f-fcb5cfd49dc7.png">
I have a issue while plotting the graph.The Xaxis values are plotted separately for same date. How can i merge same date into one so that values for same dates are plotted in same line in graph. I can i overcome the problem as shown in the figure above. I using chart version 2. Can i solve this issue in this version rather than updating to version 3???

**Comment by liuxuan30** [comment]
you just check where the label starts repeat and take a look at how `granularity` is implemented.

**Comment by SamSundar1** [comment]
can you provide some demo?please

**Comment by liuxuan30** [comment]
it's in ChartsDemo, you can try zoom and change `granularity`

**Comment by SamSundar1** [comment]
@liuxuan30 
Please tell me.
What can i do beside this??
  func setChart(dataPoints: [String], values: [Double])
    {
        lineChartView.noDataText = "You need to provide a dataFor linechart"
        lineChartView.legend.enabled = true
        lineChartView.descriptionText = ""
        lineChartView.leftAxis.granularity = 1
        lineChartView.leftAxis.axisMinValue =  0
        lineChartView.rightAxis.axisMinValue = 0
        lineChartView.doubleTapToZoomEnabled = false
        var dataEntries : [ChartDataEntry] = [ChartDataEntry]()
        for i in 0..<dataPoints.count{
            dataEntries.append(ChartDataEntry(value: values[i], xIndex: i))
            
        }
        let set1: LineChartDataSet = LineChartDataSet(yVals: dataEntries, label: "Done Dates")
        
        var dataSets : [LineChartDataSet] = [LineChartDataSet]()
        dataSets.append(set1)
        let data: LineChartData = LineChartData(xVals: dataPoints, dataSets: dataSets)
        data.setValueTextColor(UIColor.whiteColor())
        //5 - finally set our data
        set1.circleRadius = 6.0
        set1.fillColor = UIColor.redColor()
        lineChartView.data = data
        lineChartView.xAxis.labelPosition = .Bottom
        lineChartView.setVisibleXRangeMaximum(2)
    }

**Comment by thierryH91200** [comment]
update to v3.0.2

**Comment by SamSundar1** [comment]
@thierryH91200 you mean it is not possible in version 2,If i am not wrong???
