### ISSUE TITLE
How to set space between x axis labels in IOS Charts?

### ISSUE THREAD

**Issue by samarth220194** [danielgindi/Charts#2550]
I have been facing this problem for a long time. I wish to set equal space between the x-axis labels in my ios chart. I referred to this solution and applied the code as lineChartView.xAxis.avoidFirstLastClippingEnabled = true, but it didn't work out. Then I did set the value to be false then it gave me somewhat equal spacing but now my first and last x-axis label is being hidden in the chart. Please help me out with this solution.These are my screenshots.

When : lineChartView.xAxis.avoidFirstLastClippingEnabled = true

![screen shot 2017-06-22 at 6 42 26 pm](https://user-images.githubusercontent.com/17960987/27435950-4acfdc2a-577b-11e7-9cae-984ce30fc724.png)

When : lineChartView.xAxis.avoidFirstLastClippingEnabled = false

![screen shot 2017-06-22 at 6 40 30 pm](https://user-images.githubusercontent.com/17960987/27435986-5aee2832-577b-11e7-983c-2002e218bad4.png)

**Comment by liuxuan30** [comment]
I think this is an old bug, the label will overlap. Currently we are short handed.. so you are welcome to fix it

**Comment by samarth220194** [comment]
Is there any way to fix it for the time being

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/issues/1969

**Comment by amirsiddi** [comment]
@samarth220194 Hi, can you help me out with two things: 
1) x-axis values in your chart are 'text' values (e.g 23 Nov 16) , how did you achieve that?
2) not all x-axis values are showing (23 Nov 2016 , then 24 Jan 2017) which is a good thing. How can i do the same? 

Thanks in advance.

**Comment by samarth220194** [comment]
In my case, I have retrieved the x-axis values from the API by a string with different values separated by commas then I have split that string into an array.
for eg : 23-10-2016,24-01-2017 and so on this is my string , i have saved all these values into a array and then converted all these date format into my desired date format
