### ISSUE TITLE
One label for each data point - Line Chart

### ISSUE THREAD

**Issue by ethanfox** [danielgindi/Charts#2553]
How to I make it to where there is only one label for each data point in my linechart? 

Below is what I have.
![img_4142](https://user-images.githubusercontent.com/22962600/27510380-0d07bb16-58dd-11e7-821e-7da24cf478c0.PNG)

This is what I am trying to get:
<img width="343" alt="screen shot 2017-06-24 at 12 58 30 pm" src="https://user-images.githubusercontent.com/22962600/27510376-f97e712a-58dc-11e7-9025-a04d1c8c658b.png">

**Comment by thierryH91200** [comment]
If this is what you want to do here the solution in archive.zip
 do not consider some options these are PRs in progress

see #2094 

<img width="1557" alt="capture d ecran 2017-06-24 a 19 46 49" src="https://user-images.githubusercontent.com/6251463/27510679-43c624c4-5916-11e7-8610-56890d2f0dc2.png">

[Archive.zip](https://github.com/danielgindi/Charts/files/1099917/Archive.zip)

**Comment by ethanfox** [comment]
setting granularity = 1 did not fix it for me. What else could it be??

**Comment by thierryH91200** [comment]
all the trick is in the formatter
look at archive.zip

**Comment by ethanfox** [comment]
I'm getting my dates from my Firebase database. It's the date of whenever someone reviewed a business. So they will not always be the same time apart - if that makes sense. And I am saving them into an array. So would I need the date formatter still?

**Comment by thierryH91200** [comment]
Yes the whole solution is in the formatter
Go slowly
Read the #2094

**Comment by ethanfox** [comment]
@thierryH91200 
Would I need this also?
`chartView.xAxis.valueFormatter = DateValueFormatter(miniTime : from, interval: hourSeconds)`

**Comment by thierryH91200** [comment]
this is the soluce....
try and see
read the #2094

**Comment by ethanfox** [comment]
I guess I'll never know. If you're only going to allude to random crap then don't reply

**Comment by thierryH91200** [comment]
I am tired I wanted to help you and well so much worse
goodbye
It works for other people

**Comment by ethanfox** [comment]
Here's what I got:
`class CustomLabelsAxisValueFormatter : NSObject, IAxisValueFormatter {
    
    var labels: [String] = []
    
    
    var dateFormatter : DateFormatter
    var miniTime: Double
    
    
    public init(miniTime: Double) {
        //super.init()
        self.miniTime = miniTime
        self.dateFormatter = DateFormatter()
        self.dateFormatter.dateFormat = "dd/MM HH:mm"
        self.dateFormatter.dateFormat = "dd/MM"
        dateFormatter.timeZone = NSTimeZone(abbreviation: "GMT+0:00") as TimeZone!
    }
    
    
    
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
       
        let date2 = Date (timeIntervalSince1970: (value * 3600 * 24) + miniTime)
        
        let count = self.labels.count
        
        guard let axis = axis, count > 0 else {
            
            return dateFormatter.string (from: date2)
        }
        
        let factor = axis.axisMaximum / Double(count)
        
        let index = Int((value / factor).rounded())
        
        if index >= 0 && index < count {
            
            return self.labels[index]
        }
        
        return dateFormatter.string (from: date2)
        
        
        

        
    }
    
}
`

**Comment by ethanfox** [comment]
I found a **simple** solution. :) 
`func setChart(dataPoints: [String], values: [Double]) {
    chartView.noDataText = "You need to provide data for the chart."

    var dataEntries: [ChartDataEntry] = []

    for i in 0..<dataPoints.count {
        let dataEntry = ChartDataEntry(x: Double(i)+0.5, y: values[i])
        dataEntries.append(dataEntry)
    }

    let chartDataSet = LineChartDataSet(values: dataEntries, label: "")
    let chartData = LineChartData(dataSets: [chartDataSet])


    chartDataSet.colors = [red]
    chartDataSet.drawCirclesEnabled = true
    chartDataSet.circleRadius = 16
    chartDataSet.circleColors = [red]
    chartDataSet.circleHoleRadius = 12
    chartDataSet.circleHoleColor = UIColor.white
    chartDataSet.lineWidth = 4
    chartView.data = chartData

    }`
Notice the +0.5.
