### ISSUE TITLE
How to add X axis values in the balloon marker view in IOS Charts?

### ISSUE THREAD

**Issue by samarth220194** [danielgindi/Charts#2554]
I am able to show the y-axis values on the marker view, but how to show the x-axis values in it. This is the code which I have used to show y-axis values. I used the refreshContent method of balloon marker view to show the x axis values , but it is still not working.

`let marker:BalloonMarker = BalloonMarker(color: UIColor.white, 
    font: UIFont(name: "Helvetica", size: 10)!, textColor: UIColor.black,
 insets: UIEdgeInsets(top: 2.0, left: 3.0, bottom: 2.0, right: 3.0))
                marker.arrowSize = CGSize(width : 5.0, height : 8.0)
                marker.minimumSize = CGSize(width : 50.0, height : 25.0)
                lineChartView.marker?.refreshContent(entry: DataEntry, highlight: Highlight(x : Double(i) , y : Values[i] , dataSetIndex : i))
               lineChartView.marker = marker`

This is the screenshot

![rh2gl](https://user-images.githubusercontent.com/17960987/27511315-c0a7120a-593e-11e7-9b62-ef74212e2840.png)

**Comment by liuxuan30** [comment]
That's because balloon marker only show y value... You need to provide your own marker to show other values...
```swift
    open override func refreshContent(entry: ChartDataEntry, highlight: Highlight)
    {
        setLabel(String(entry.y)) // change to x
    }
```

**Comment by NallapatiMalleswari** [comment]
You converted yaxis value to percentage right,can you send that code .Thankyou

**Comment by ibrahimzak** [comment]
how to add the name of the entry description instead of the x or y value?
