### ISSUE TITLE
charts uses iphone show "No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=i386 x86_64 )".

### ISSUE THREAD

**Issue by highplay** [danielgindi/Charts#2557]
<img width="687" alt="b9a098a2-d850-4600-8069-ca3ed2a43970" src="https://user-images.githubusercontent.com/13444353/27521743-e17b826c-5a52-11e7-8de3-b4a020f8534b.png">

**Comment by liuxuan30** [comment]
reset your project setting, you are building on simulator but the active arch is only arm64.
