### ISSUE TITLE
Ugly spikes in LineChart

### ISSUE THREAD

**Issue by laxmorek** [danielgindi/Charts#2561]
I drew LineChartView with LineChartData. I added dots on data points but for some reason line go beyond the dots.

Can be removed?

![img_0042](https://user-images.githubusercontent.com/4774319/27579940-80cece24-5b29-11e7-9f13-0441a7e1f3b5.PNG)

**Comment by liuxuan30** [comment]
Known issue. Don't have idea yet. #2180
