### ISSUE TITLE
How to create a custom marker view in line chart for showing x values as well

### ISSUE THREAD

**Issue by samarth220194** [danielgindi/Charts#2562]
I want to show the x values in the line chart as well, how do i create a markerview for that

**Comment by thierryH91200** [comment]
try

```
import Foundation
import Charts

open class XYMarkerView1: BalloonMarker
{
    open var xAxisValueFormatter: IAxisValueFormatter?
    open var yAxisValueFormatter: IAxisValueFormatter?
    fileprivate var yFormatter = NumberFormatter()
    
    public init(color: NSColor, font: NSFont, textColor: NSColor, insets: EdgeInsets, xAxisValueFormatter: IAxisValueFormatter, yAxisValueFormatter : IAxisValueFormatter)
    {
        super.init(color: color, font: font, textColor: textColor, insets: insets)
        self.xAxisValueFormatter = xAxisValueFormatter
        self.yAxisValueFormatter = yAxisValueFormatter
         yFormatter.minimumFractionDigits = 1
        yFormatter.maximumFractionDigits = 1
    }
    
    open override func refreshContent(entry: ChartDataEntry, highlight: Highlight)
    {
        let x = entry.x
        let y = entry.y
        
        setLabel("x: " + xAxisValueFormatter!.stringForValue(x, axis: nil) + ", y: " + yAxisValueFormatter!.stringForValue(y, axis: nil))
    }
}

```

**Comment by samarth220194** [comment]
When I am calling the function refreshContent(entry: ChartDataEntry, highlight: Highlight ) then it is showing the error: "Extra function highlight in call"

**Comment by thierryH91200** [comment]
Normally there is no problem

https://github.com/danielgindi/Charts/blob/master/ChartsDemo/Classes/Components/XYMarkerView.swift

**Comment by samarth220194** [comment]
Sir see this, i called the function like this : 
`  let c_marker = XYMarkerView1(color: UIColor.white, font: UIFont(name: "Helvetica", size: 10)!, textColor: UIColor.black, insets: UIEdgeInsets(top: 2.0, left: 3.0, bottom: 2.0, right: 3.0), xAxisValueFormatter: <#IAxisValueFormatter#>)
            
            c_marker.refreshContent(entry: DataEntry, highlight: Highlight (x : Double(i) , y : Values[i] , dataSetIndex : i))
            {
                let x = DataEntry.x
                let y = DataEntry.y
                
            }
`
It gave me error : extra argument 'highlight' in call

**Comment by thierryH91200** [comment]
The correct syntax is:

```
 let  marker = XYMarkerView( color:  NSUIColor.yellow, 
                                   font: NSUIFont.systemFont(ofSize: 12.0),
                                    textColor: NSUIColor.blue,
                                    insets: UIEdgeInsets(top: 2.0, left: 3.0, bottom: 2.0, right: 3.0),
                                    xAxisValueFormatter: yourFormatter,
                                    yAxisValueFormatter: yourFormatter)
        marker.minimumSize = CGSize( width: 80.0, height :40.0)
        marker.chartView = chartView
        chartView.marker = marker

```

it's all

**Comment by samarth220194** [comment]
Okk i got it , but why didnt we used the function refresh content ?

**Comment by thierryH91200** [comment]
it's automatic

**Comment by samarth220194** [comment]
Okk thank you Sir for the help :)
