### ISSUE TITLE
Cropping left axis labels and missing some values

### ISSUE THREAD

**Issue by ratka6** [danielgindi/Charts#2563]
I've created BarChart in code and have a problem: when it is displayed it crops left yaxis labels and last value is missing. There are only 7 values showed, rest is shown when scrolling using setVisibleXRangeMaximum and setVisibleXRangeMaximum to 7, then I use moveViewToX. After that this is what I get:
![zrzut ekranu 2017-06-27 o 15 56 44](https://user-images.githubusercontent.com/12432245/27591273-725b79c8-5b51-11e7-886b-1247a4292e36.png)
But then after scrolling left to the last value view is "refreshed" and I get this:
![zrzut ekranu 2017-06-27 o 15 56 52](https://user-images.githubusercontent.com/12432245/27591489-235f66ee-5b52-11e7-8ca1-cb0c586a0358.png)
Is there a way to set the view on create?

**Comment by ratka6** [comment]
Found solution - I just needed to call notifyDataSetChanged before moving to X!

**Comment by tommyguan** [comment]
Is this solved ? Could somebody share a workaround ?
