### ISSUE TITLE
Range float bars

### ISSUE THREAD

**Issue by CavalcanteLeo** [danielgindi/Charts#2564]
Which chart is this?
Is it possible to make it?

There are some range bars values, with some float bullets inside or outside the bars. Bars are horizontal.

![captura de tela 2017-06-27 as 12 23 13](https://user-images.githubusercontent.com/1735944/27595685-c164a1fc-5b33-11e7-996c-625c736bba23.png)

**Comment by CavalcanteLeo** [comment]
On Excel it is actual vs target

**Comment by liuxuan30** [comment]
Don't know how to read it, but in terms of a chart, this is easy to implement based on this framework. You already got horizontal bar chart, as long as you figure out what are the circles and where to put them, you can override the method and add them. Refer scattered chart as well.

**Comment by CavalcanteLeo** [comment]
Does this chart supports float bars?  
Or only one value?

This chart i need is like actual vs target

**Comment by liuxuan30** [comment]
float bars are not supported. Like I said, it's not that hard to write one if you know how it works. Take a look at the renderer code.
