### ISSUE TITLE
How to show LineChart with icon

### ISSUE THREAD

**Issue by guanyanlin** [danielgindi/Charts#2566]
![linechartwithicon](https://user-images.githubusercontent.com/16291120/27627402-3f622922-5c1e-11e7-96cf-9de9bcf040a6.png)
how to show the function Like this?
every corner has a different icon?

**Comment by liuxuan30** [comment]
it's already supported I guess. #1793

**Comment by guanyanlin** [comment]
Yeah,have already get it.
But really thank you also the same for your reply！
