### ISSUE TITLE
Barchart fixed interval in left axis

### ISSUE THREAD

**Issue by iad24** [danielgindi/Charts#2574]
Hello. I have a simple bar chart but I need the left axis values to be a multiple of 0.5.

Like this:
3.0 |
2.5 |
2.0 |
1.5 |
0.0 |

How to do this?

**Comment by liuxuan30** [comment]
use `forceLabelEnabled` and set the label count by:
>    open func setLabelCount(_ count: Int, force: Bool)
    {
        self.labelCount = count
        forceLabelsEnabled = force
    }
