### ISSUE TITLE
horizontal barchart each bar have different maximum value

### ISSUE THREAD

**Issue by iad24** [danielgindi/Charts#2575]
I want to achieve this:
![screen shot 2017-07-03 at 10 13 03 pm](https://user-images.githubusercontent.com/15226261/27796540-f1e570fa-603c-11e7-878a-979dd333dee3.png)

Each bar could have a different max value.
And could have any number of bars in the cart.
Is this possible with the current horizontal bar chart?

**Comment by liuxuan30** [comment]
no, you have to write your own.
