### ISSUE TITLE
Hide specific legend not all

### ISSUE THREAD

**Issue by zohaibbrohi** [danielgindi/Charts#2576]
I have a graph with 3 different values. 
I have 3 legends but I want to hide 1 legend. Is it possible
For hiding all I can use legend.enable = false. But I want to hide it when setting LineChartDataSet. 
In this picture I have 2 legend. One with text speed and other without text. I want to disable the dot as well. 

![screen shot 2017-07-04 at 1 34 27 pm](https://user-images.githubusercontent.com/988509/27828666-98ca8f6a-60bd-11e7-8954-8c5dbcb7a314.png)

**Comment by liuxuan30** [comment]
you need to override the legend renderer e.g.
>open func renderLegend(context: CGContext)

to ignore certain values
