### ISSUE TITLE
CenterText/Description Text overruns onto PieChart

### ISSUE THREAD

**Issue by mingsai** [danielgindi/Charts#2577]
I'm using the latest API with Swift. When modifying the Description and the CenterText of a PieChart, I am seeing displacement issues where the text overruns the Chart area. Rather than create a workaround I wondered if I might be missing something obvious, which would correct the issue? 

![piechart](https://user-images.githubusercontent.com/1871108/27835861-b31e3ba4-6091-11e7-9a8c-8cc9388e6489.png)

If not then perhaps some new API properties to better manage the organization, sizing, and alignment of CenterText and Description may be required.

**Comment by liuxuan30** [comment]
on my side in ChartsDemo, it's clipped:
<img width="264" alt="image" src="https://user-images.githubusercontent.com/4375169/27940081-2f7e62e4-62fb-11e7-81a4-a49b10dd60c4.png">
