### ISSUE TITLE
Error Library not loaded: @rpath/libswiftAppKit.dylib

### ISSUE THREAD

**Issue by javalizard** [danielgindi/Charts#2578]
When following the instructions to include Charts.framework this is the error I was getting:

>2017-07-04 14:14:51.808884-0400 MyApp[75253:2033672] Error loading /Users/...../MyApp.app/Contents/MacOS/MyApp, 265): Library not loaded: @rpath/libswiftAppKit.dylib
>  Referenced from: /Users/...../MyApp/Build/Products/Debug/Charts.framework/Versions/A/Charts
  Reason: image not found

This might be an error if when using objective C rather than swift.

# The Solution

Change the settings in the Charts Project "Always Embed Swift Standard Libraries" from No => YES.  On the Charts Build Target, Click Build Settings, search for the keyword "Embed", and then set "Always Embed Swift Standard Libraries" equal to YES.  Here is the visual.

<img width="870" alt="rpath libswiftappkit dylib fix" src="https://user-images.githubusercontent.com/5497719/27840043-e6ee2480-60c3-11e7-86a9-4e303be82139.png">

Setting the flag in the main project won't do it.  It must be set in the framework project.  This is why I am recommending that the project be updated with this flag for general use in objective-c environments.

It could be implemented in the main project minimal effort and would save a lot of head aches for some.

**Comment by liuxuan30** [comment]
well, I think it should be the user app to embed the swift libraries for the moment. As long as Swift is embedded into iOS, this can be ignored. But make the framework embed swift library is not a good idea to me right now.

**Comment by hongyu315** [comment]
把 Bitcode设置成No就好了
