### ISSUE TITLE
'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting. 

### ISSUE THREAD

**Issue by MiladFaridnia** [danielgindi/Charts#2580]
Hi 
I've got this warning in `ChartUtils.swift` Class when I build my project:

> 'M_PI' is deprecated: Please use 'Double.pi' or '.pi' to get the value of correct type and avoid casting. 

 Please Fix it.

**Comment by thierryH91200** [comment]
update to v3.0.2
