### ISSUE TITLE
Line chart with blank data show Y axis label incorrect on iPhone 5

### ISSUE THREAD

**Issue by ybqboy** [danielgindi/Charts#2583]
I met this issue, when I create a line chart with blank data, only on iPhone 5, it shows like this
![img_0001](https://user-images.githubusercontent.com/11812236/27948419-505253e6-632c-11e7-928a-d8d040c56ccb.PNG)
as you can see, the Y axis label are all in the corner.
I debugged into the code and found it seems like there is an issue in here, the trans got two NAN values.
![image](https://user-images.githubusercontent.com/11812236/27948527-ae507ea0-632c-11e7-83e0-6b0c7a8d527c.png)
![image](https://user-images.githubusercontent.com/11812236/27948539-b82df416-632c-11e7-97d7-c1379a46c268.png)

one more thing, if has data, the issue gone and everything seems good. and on iPhone 6 and iPhone 7 everything is fine.

**Comment by ybqboy** [comment]
can anybody help to check this issue?
also with blank data, the chart will crash if the scale is enabled. so am i wrong to use the blank data chart? here is my code
` _chartView.delegate = self;
    
    _chartView.chartDescription.enabled = NO;
    
    _chartView.dragEnabled = YES;
    [_chartView setScaleEnabled:YES];
    _chartView.pinchZoomEnabled = NO;
    _chartView.drawGridBackgroundEnabled = NO;
    _chartView.highlightPerDragEnabled = YES;
    _chartView.scaleYEnabled = NO;

    _chartView.backgroundColor = UIColor.whiteColor;
    
    _chartView.legend.enabled = NO;
    _chartView.maxVisibleCount = 4000;
    
    
    ChartXAxis *xAxis = _chartView.xAxis;
    xAxis.labelPosition = XAxisLabelPositionBottom;
    xAxis.labelFont = [UIFont fontWithName:@"HelveticaNeue-Light" size:10.f];
    xAxis.labelTextColor = [UIColor colorWithRed:255/255.0 green:192/255.0 blue:56/255.0 alpha:1.0];
    xAxis.drawAxisLineEnabled = NO;
    xAxis.drawGridLinesEnabled = NO;
    xAxis.centerAxisLabelsEnabled = YES;
    xAxis.granularity = 180.0;
    xAxis.valueFormatter = [[DateValueFormatter alloc] init];
    
    NoOverlappingLabelsXAxisRenderer *render = [[NoOverlappingLabelsXAxisRenderer alloc] initWithViewPortHandler:_chartView.viewPortHandler xAxis:_chartView.xAxis transformer:_chartView.xAxisRenderer.transformer];
    _chartView.xAxisRenderer = render;
    
    
    ChartYAxis *leftAxis = _chartView.leftAxis;
    leftAxis.labelFont = [UIFont fontWithName:@"HelveticaNeue-Light" size:12.f];
    leftAxis.labelTextColor = [UIColor colorWithRed:51/255.0 green:181/255.0 blue:229/255.0 alpha:1.0];
    leftAxis.drawGridLinesEnabled = YES;
    leftAxis.granularityEnabled = YES;
    leftAxis.axisMinimum = 0;
    leftAxis.axisMaximum = 25;
    leftAxis.labelCount = 5;
    
    _chartView.rightAxis.enabled = NO;
    
    _chartView.legend.form = ChartLegendFormLine;
    
    LineChartData *data = [[LineChartData alloc] initWithDataSets:@[]];
    _chartView.data = data;`

thanks

**Comment by liuxuan30** [comment]
check out ChartsDemo, when you fill empty data sets, it won't crash.
And the y label shows well.. so double check your code, and post where it crashes and reopen.

**Comment by liuxuan30** [comment]
I checked what you said, with `Line Chart` in ChartsDemo:

On iPhone 5S:
![image](https://user-images.githubusercontent.com/4375169/28253553-b22fc0fa-6ad7-11e7-8a2d-1895e6be4236.png)

On iPhone 5:
![image](https://user-images.githubusercontent.com/4375169/28253635-64c059e6-6ad8-11e7-8c39-9e2d312be7b1.png)

So I suspect it's due to 32bit and 64bit precising issue.

**Comment by aelam** [comment]
have you fixed this?  I've got this problem too.
