### ISSUE TITLE
Scrolling chart

### ISSUE THREAD

**Issue by navrozhuda** [danielgindi/Charts#2587]
How can we able to scroll this charts?

**Comment by surayashivji** [comment]
+1

**Comment by mosn** [comment]
set `setVisibleXRangeMaximum` to a number lower than the charts and you should be able to scroll. 
Use `pinchZoomEnabled` and zoom in to scroll

**Comment by navrozhuda** [comment]
can I use scroll without zoom in and pinchZoomEnabled?

**Comment by liuxuan30** [comment]
if the values are displayed, you can't scroll, that said you have to zoom in first.
You can programmaticly use API to zoom in

**Comment by pranav0705** [comment]
Hi @navrozhuda , did you manage to make it work? I am having some problem implementing the scrolling, could you please share you logic? Thank you
