### ISSUE TITLE
Use Charts in App Extension

### ISSUE THREAD

**Issue by jack-blackson** [danielgindi/Charts#2590]
Hey!

First of all, thanks for this great project and your work on it!

I am using your chart in my iOS app, and wanted to add them now too to a custom view of an app extension. Unfortunately, this leads to a warning at the moment:
"warning: linking against dylib not safe for use in application extensions"

As far as I found out, the reason for that is, that Apple seems to see Charts as one of the "Unavailable for App Extensions APIs" (see https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6)

Do you think there is a way to adjust the API, that it conforms with their requirements? Or is there any way to do this myself? This would be really great. If this warning appears, Apps will be rejected for App Store Review.

Thanks,
Jack

**Comment by liuxuan30** [comment]
I am curious about this, can you do some research and maybe make a pull request for this?

**Comment by jack-blackson** [comment]
This is quite strange - this is the error message I receive in xcode.
![problem charts](https://user-images.githubusercontent.com/13975634/28473709-0f87ad64-6e46-11e7-8654-ad352f16f90f.jpg)

**Comment by jack-blackson** [comment]
Hey! It seems I fixed it..it was somewhere connected incorrectly in the app.

**Comment by petester42** [comment]
seems resolved. closing
