### ISSUE TITLE
Stacked bar always show last value

### ISSUE THREAD

**Issue by icefox57** [danielgindi/Charts#2592]
I want to create a stacked bar 
i followed the demo finish the coding.
but stacked bar always show last value.

so i remove my value and use static value , but same problem.
could anyone help me ?

`func bulidBarChartDataSet(dataPoints: [String],
                              values: [[Double]] ,
                              labels:[String]) -> BarChartDataSet {`
        
        `var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<dataPoints.count {
            
            let d1:Double = 23.3
            let d2:Double = 41.2
            let demoV = [d1,d2]
            
            let dataEntry = BarChartDataEntry(x: Double(i), yValues: demoV)//values[i])
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "")
        chartDataSet.stackLabels = labels
        chartDataSet.colors = [RandomFlatColor(),RandomFlatColor()]
        chartDataSet.valueFont = NSUIFont.systemFont(ofSize: 11)
        return chartDataSet
    }`

this is what i got now.
![4d6d5815-2ee0-4861-8fa4-1b4e2a05f85a](https://user-images.githubusercontent.com/1716737/28008214-31acdfa6-6589-11e7-81f6-e7c7e26c5ab7.png)

**Comment by thierryH91200** [comment]
no problem for me

You took what demo?

<img width="1557" alt="capture d ecran 2017-07-10 a 10 37 39" src="https://user-images.githubusercontent.com/6251463/28009478-dd2a7cc2-655b-11e7-8bdc-c96d635609b5.png">


       // MARK: BarChartDataEntry
        var yVals = [BarChartDataEntry]()
        for i in 0..<count
        {
            let d1:Double = 23.3
            let d2:Double = 41.2
            let demoV = [d1,d2]
            
            let dataEntry = BarChartDataEntry(x: Double(i), yValues: demoV)//values[i])
            yVals.append(dataEntry)
            
        }

**Comment by icefox57** [comment]
i only found oc demo at Chart's github home page. 
Is there swift demo?

**Comment by icefox57** [comment]
I found my problem!.
                chartView.autoScaleMinMaxEnabled = true
remove this line everything works perfect

**Comment by thierryH91200** [comment]
> i only found oc demo at Chart's github home page.
> Is there swift demo?
> 

yes in pull request
