### ISSUE TITLE
About stacked bar value label postion 

### ISSUE THREAD

**Issue by icefox57** [danielgindi/Charts#2595]
![image](https://user-images.githubusercontent.com/1716737/28048414-71e4b4d2-6623-11e7-854c-1959ed34f0cc.png)

is there a way to move value label left on the bar? 
like this 

![image](https://user-images.githubusercontent.com/1716737/28048478-c12466dc-6623-11e7-8144-f9283cd4efdf.png)

**Comment by liuxuan30** [comment]
override the horizontal bar chart renderer to make your own.

**Comment by icefox57** [comment]
i found 
chartView.isDrawValueAboveBarEnabled = false 
is what i need.

**Comment by liuxuan30** [comment]
sorry, I forgot this is about the top though it's horizontal 😂
