### ISSUE TITLE
Not able to see yAxis label while changing position of that label

### ISSUE THREAD

**Issue by dhaneshgosai** [danielgindi/Charts#2596]
Hello,

I am using `CubicLineChart` in my application and every thing works fine.

Bus as and when I change position of `YAxis` from `YAxisLabelPositionInsideChart` to `YAxisLabelPositionOutsideChart` its not showing any `YAxis` on chart.

I have tried may option here but  still same issue.

Also same issue facing in your demo app.

Please check it once.

Thanks,
Dhanesh Gosai.

**Comment by dhaneshgosai** [comment]
Also Please check attched screen shots for more reference on same.

![with label](https://user-images.githubusercontent.com/1092509/28055661-87656252-6637-11e7-8dfa-62bb094bc66c.png)
![without label](https://user-images.githubusercontent.com/1092509/28055662-876e3f94-6637-11e7-9f55-1f96a37705af.png)

Thanks,
Dhanesh Gosai.

**Comment by Chren** [comment]
Same issue here:
YAxisLabelPositionInsideChart works but outside nothing shows up
