### ISSUE TITLE
Spacing between left axis labels

### ISSUE THREAD

**Issue by zohaibbrohi** [danielgindi/Charts#2601]
Hello. 
Does anyone know if it is possible to change the y-axis from linear to logarithmic scaling? (Please see example below.)

![2017-07-14 14 22 07](https://user-images.githubusercontent.com/988509/28212043-f7486154-689f-11e7-8858-73e2da8ac450.jpg)

**Comment by liuxuan30** [comment]
there is one old thread: #109
