### ISSUE TITLE
Memory Leak in Legend and ArrayBufferProtocol

### ISSUE THREAD

**Issue by osianSmith** [danielgindi/Charts#2606]
Hello
I am having a few memory leaks in my application. They are in:

`cialized specialized _ArrayBufferProtocol._arrayOutOfPlaceUpdate<A where ...> (inout_ContiguousArrayBuffer<A.Element>, Int, Int, A1) -> ()`

`specialized Array._copyToNewBuffer(oldCount : Int) -> ()
`

`specialized Legend.calculateDimensions(labelFont : UIFont, viewPortHandler : ViewPortHandler) -> ()`

`specialized Legend.calculateDimensions(labelFont : UIFont, viewPortHandler : ViewPortHandler) -> ()`

This was found in the inspector. I don't think it was causing an issue, but it was something I found. I am currently using LineGraphs

Here is a shot from instruments: 

![screen shot 2017-07-13 at 5 36 41 pm](https://user-images.githubusercontent.com/20597684/28177388-8bf03eca-67f2-11e7-8005-fbc4b465b869.png)

Thanks

Osian

**Comment by liuxuan30** [comment]
you can pop pack or make the holder of your chart to deinit, and see shall the chart deinit itself as well.

**Comment by osianSmith** [comment]
Hey, I don't know why but Xcode has seemed to stop detecting these Data leaks after a reinstall of Xcode on my laptop.
I will keep an eye on it and reopen this if it becomes an issue again, but I'll close it in the meantime 😄
