### ISSUE TITLE
Is there any way to get the xaxis value when chart scroll end specific area?

### ISSUE THREAD

**Issue by Stu-JuLiaoY** [danielgindi/Charts#2607]
Hi

First of all, thank you so much for this library.Charts is very great! Now,I meet a issue, I want to get the xaxis value when chart scrolling or scroll end,and this value is every point that across specific area.For example: I specific this area is chart center,I can get per ChartDataEntry instance when across this center area. I'm used "- chartTranslated:dX:dY",but it seems not work. Is there any way to get it?

Thank you.

**Comment by liuxuan30** [comment]
there is something simiar I guess:
```swift
    /// - returns: The highest x-index (value on the x-axis) that is still visible on the chart.
    open var highestVisibleX: Double
    {
        var pt = CGPoint(
            x: viewPortHandler.contentRight,
            y: viewPortHandler.contentBottom)
        
        getTransformer(forAxis: .left).pixelToValues(&pt)

        return min(xAxis._axisMaximum, Double(pt.x))
    }
```
You can figure out what's your center and convert the pixel to values. Notice, it might fail or you have to search for closest values.
