### ISSUE TITLE
i wanna display Char form with no data. but with Y Values. 

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#2608]
and i will insert data gradually.

when i set the   ChartView.data  = nil;

it's disPlay a String.. no data balabala

**Comment by dadigua2333** [comment]
change title

**Comment by liuxuan30** [comment]
no data, no chart.
or use a empty data sets to display y axis values.

**Comment by c1800054work** [comment]
Hi

it will draw the line if there has data and the title is nil.
But there is no y-axis to the line.

Does it possible to show y-axis line?
