### ISSUE TITLE
when i  Creat one LineChartData objc. it's draws Three points 

### ISSUE THREAD

**Issue by dadigua2333** [danielgindi/Charts#2609]
![123123123](https://user-images.githubusercontent.com/12544035/28254001-667c3e28-6adb-11e7-9cd1-ba96cc7aa90c.png)

the Result:
![2222](https://user-images.githubusercontent.com/12544035/28254139-9332f866-6adc-11e7-91ff-b991aee9f857.png)

**Comment by liuxuan30** [comment]
be sure you run ChartsDemo first to check the usage
