### ISSUE TITLE
Linker Command Fail error 

### ISSUE THREAD

**Issue by shivangpandya9** [danielgindi/Charts#2611]
I got linker command fail error with following message : 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$__TtC10ChartsDemo12XYMarkerView", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuxuan30** [comment]
then you have to add x86_64 in your arch..

**Comment by shivangpandya9** [comment]
I already add x86_64 in architecture.
But still get same error .
![screen shot 2017-07-21 at 7 57 43 am](https://user-images.githubusercontent.com/30236980/28446750-83409d62-6dea-11e7-976d-d58443417c32.png)

**Comment by shivangpandya9** [comment]
I have got same error . Please help me how to fix it. I already import XYMarkerView (component) folder to my project
![screen shot 2017-07-21 at 8 10 33 am](https://user-images.githubusercontent.com/30236980/28447084-50d34c2e-6dec-11e7-9c4e-b5b66e494b6b.png)

but still got error .

Please help to fix it. I am waiting for your reply.

**Comment by liuxuan30** [comment]
Please refer ChartsDemo build settings and try rebuild. `BarChartViewController` is using `XYMarkerView` and it works fine.
