### ISSUE TITLE
Want to display circles at data points on a line graph only if the data has changed or is about to change

### ISSUE THREAD

**Issue by pktrkts** [danielgindi/Charts#2613]
Hi,

Thanks for the wonderful chart library.  Your work is appreciated.

I want to know if it's possible to only display the circles on a line graph at data points where the value has changed or is about to change, or if the data point is a start or end point.  The rest of the time I want the chart to behave as if there are points there, only no circles.  Any help on how to accomplish this would be appreciated.

Thanks,
Sean

**Comment by liuxuan30** [comment]
this requires you override a bunch of methods to do so. You have the code already.

**Comment by pktrkts** [comment]
I figured it out.
