### ISSUE TITLE
About gradient color for lineChartView

### ISSUE THREAD

**Issue by asdfeng** [danielgindi/Charts#2615]
Hi 
   How can i use the Charts library to draw gradient colors for lineChartView like this? The colors depend on Y-axis value，for example, use red color when the value of the Y-axis is greater than 300.very thanks
![ssss](https://user-images.githubusercontent.com/17334138/28367614-2dd168c4-6cc4-11e7-9afd-a726d2d69b7e.jpeg)

**Comment by liuxuan30** [comment]
there is one pr for this, you can check out #649
