### ISSUE TITLE
How to give all pie-slices a rounded edge?

### ISSUE THREAD

**Issue by Gaantz** [danielgindi/Charts#2620]
Please need help for round all pie slice from PIE CHART like this [example](https://i.stack.imgur.com/Fl2IZ.png).

**Comment by Gaantz** [comment]
MPAndroidChart method reference

https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/main/java/com/github/mikephil/charting/renderer/PieChartRenderer.java#L957

**Comment by liuxuan30** [comment]
looks like you have to override pie chart rendrer rect code to draw one arch for each.
