### ISSUE TITLE
How to adjust RadarChartView text from the bottom of the height？

### ISSUE THREAD

**Issue by githubkiven** [danielgindi/Charts#2621]
I set the cell height to 240，I set the RadarChartView height to 240，But there is a blank at the bottom，I want to keep the bottom of the pitch smaller，How should i set it up?thank you very much
![91631928-e9d7-4fc6-a7f2-46cd80ff23fc](https://user-images.githubusercontent.com/8455023/28404534-4f459938-6d5c-11e7-963b-1e94f324f0c8.png)

**Comment by githubkiven** [comment]
@danielgindi

**Comment by githubkiven** [comment]
@petester42

**Comment by githubkiven** [comment]
@liuxuan30

**Comment by githubkiven** [comment]
I want the effect
![04d66292-9149-4fa2-b6c9-6ce32a751a9b](https://user-images.githubusercontent.com/8455023/28406023-5adc1e7a-6d61-11e7-95c6-057f2d4f722e.png)

**Comment by liuxuan30** [comment]
use `extraBottomOffset` should help
But  I suggest you look at how the blank is calcuated, either if it's in legend offset, or just the contentRect offset

**Comment by githubkiven** [comment]
self.radarChartView = [PPWUtils radarChartView];
            self.radarChartView.backgroundColor = [UIColor orangeColor];
            [self.radarChartView setDrawMarkers:YES];
            self.radarChartView.frame = CGRectMake(20, 0, kScreenWidth-40, 246);
            [self.contentView addSubview:self.radarChartView];
            self.radarChartView.delegate = self;

**Comment by githubkiven** [comment]
I just set the size of the radarChartView to the bottom of the blank so much

**Comment by githubkiven** [comment]
I just set the size of the radarChartView, the bottom of the blank so much @liuxuan30
