### ISSUE TITLE
计算柱形图的宽度和设定间隙

### ISSUE THREAD

**Issue by chenshuangsmart** [danielgindi/Charts#2622]
使用CombinedChartView画柱形图，通过barWidth设定柱形图的宽度，但是如何转化成像素，并且设定柱形图之间的间隙，谢谢。

**Comment by aelam** [comment]
MACD吗 设置边框宽度 

发自我的 iPhone

**Comment by chenshuangsmart** [comment]
你好，使用CombinedChartView绘制柱形图的时候，无论如何设置柱形图的宽度，当前屏幕都是显示7条数据，而且柱形图的宽度最大只能显示屏幕宽度/7个像素，但是我想设置更大，比如一个屏幕只显示4个柱形图，应该如何设置，并且可以设置柱形图之间的间隙。 #

**Comment by liuxuan30** [comment]
It's in `ChartTransformer` to convert.

**Comment by chenshuangsmart** [comment]
can you explain more detail?

**Comment by liuxuan30** [comment]
Just take a look at the class and `open func groupBars(fromX: Double, groupSpace: Double, barSpace: Double)`
