### ISSUE TITLE
Unable to use this library in Objective-c .

### ISSUE THREAD

**Issue by zeeshansuleman** [danielgindi/Charts#2623]
hello guyz i tried using this library in my objective c project . it does not work with cocoapods and static way either. plz guide me how can i use it in my obj-c project.

**Comment by liuxuan30** [comment]
check out charts demo. It's objc.

**Comment by zeeshansuleman** [comment]
i dont want to use in static way . i want to integrate through cocoapod.

**Comment by liuxuan30** [comment]
I close because it's answered already, and easy to track "real issues". README already give steps to use pods. Did you see it?

**Comment by zeeshansuleman** [comment]
i did check but there are issues of legacy swift versions.

**Comment by liuxuan30** [comment]
Charts library keep sync with latest stable swift and Xcode.
