### ISSUE TITLE
I need this method: setShowOnlyMinMax

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#2624]
Hi,

I'm doing a lot of charts for a client. He is changing his library to use yours. All of his charts display only the Min and Max values on the X and Y Axis. He wants the **same** result.

I saw in the Android doc that this method exists: **setShowOnlyMinMax**.

We don't have it in iOS.

Is it scheduled to do it? Is there a workaround?

Thanks for your help!

Regards,

FoG

**Comment by liuxuan30** [comment]
dup https://github.com/danielgindi/Charts/issues/2164
