### ISSUE TITLE
Does PieChart support multiple columns of vertical legend?

### ISSUE THREAD

**Issue by lynnleelhl** [danielgindi/Charts#2625]
I am trying to draw a pie chart like the following.
![image](https://user-images.githubusercontent.com/10272065/28458317-e60adf7e-6e3b-11e7-87a9-977c45bee2de.png)
I want the vertical legend to break into multiple columns when there are too many labels to show, but I can only got one column.
Here's my code.
```        
        let legend = view.legend
        legend.horizontalAlignment = .right
        legend.verticalAlignment = .center
        legend.orientation = .vertical
        legend.xEntrySpace = 0
        legend.yEntrySpace = 8
        legend.xOffset = 0
        legend.yOffset = 0
        legend.form = .circle
```
I wonder if there's any way to what I said, I'd be pretty appreciated if I got your kind help :)

**Comment by lynnleelhl** [comment]
![image](https://user-images.githubusercontent.com/10272065/28458808-9f2a1d02-6e3d-11e7-8157-17368a8a4b65.png)
This is what I got by code posted above.

**Comment by liuxuan30** [comment]
I remember it does not support two column. You are welcome to contribute!
