### ISSUE TITLE
Using Charts in NSStackView

### ISSUE THREAD

**Issue by jwr1995** [danielgindi/Charts#2626]
I am trying to display multiple line charts in a stack view but I am having problems with the charts collapsing and only displaying one chart at a time. I have established the frame is zero sized and the layout is ambiguous so I thought perhaps it just needed NSLayoutConstraints adding to it, however I tried this for the width and height of the chart and I have tried using chart .setFrameSize as well but still only one chart would display in the stack view at any one time and would fill the entire view even though the stack view was set to fill equally.

Here is the type of thing I am trying to code for each required LineChartView where chartViewArray holds and array of LineChartViews:

```
 for i in 0...numberOfChannels-1 {
                    chartViewArray[i].noDataText = "Could not load channel \(i+1) data"
                    chartViewArray[i].data = setChart(values: self.audioArray[i], channel: i+1)
                    chartViewArray[i].chartDescription = nil
                    chartViewArray[i].setFrameSize(NSSize(width: 2, height: 2))
                    stackView.addView(chartViewArray[i], in: NSStackViewGravity.bottom)
                }
```

**Comment by liuxuan30** [comment]
This should be asked on StackOverflow. Looks like you are using NSSTackView incorrectly.

**Comment by atalayasa** [comment]
@jwr1995 Did you find a solution for your problem ?

**Comment by jwr1995** [comment]
@atalayasa nope couldn't figure it out
