### ISSUE TITLE
Changing chart's type without creating a new object...

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#2627]
I was wondering if there is a way to change the type of a chart (Going from BarChart to LineChart) without creating a new object?

Is there a more generic Class (Like ChartView) I could use and change only the type?

Since I'm replacing my chart library with this one, I was used to work this way.

Thanks!

**Comment by kscheff** [comment]
use `CombinedChartView()` class for doing this. Then, when you switch from e.g. line to graph call .initialize() to clean out the view. Pay attention that previous highlights are not removed, though cleaning them manually works by calling `.highlightValues(nil)`

**Comment by liuxuan30** [comment]
check out ChartsDemo's CombinedChartView as @kscheff said. Thanks
there is one method called `clear()` as well in `ChartViewBase`
```swift
    /// Clears the chart from all data (sets it to null) and refreshes it (by calling setNeedsDisplay()).
    open func clear()
    {
        _data = nil
        _offsetsCalculated = false
        _indicesToHighlight.removeAll()
	    lastHighlighted = nil
	
        setNeedsDisplay()
    }
```
