### ISSUE TITLE
How to set group width in multiple bar chart?

### ISSUE THREAD

**Issue by sacrificar** [danielgindi/Charts#2631]
So, I try to create multiple bar chart in objective-c. I look into the example project. But some how, the x axis label is not in the right position.

![9l33whzu](https://user-images.githubusercontent.com/8979317/28509255-2962aa96-706b-11e7-9064-af6792c5c1b7.jpg)

You can see at the image above. The position of the label and the grouped bar is not in the same position. How I can fix this problem?

**Comment by liuxuan30** [comment]
check out `@interface MultipleBarChartViewController`
