### ISSUE TITLE
unable to set string values on x-axis in grouped bar chart .

### ISSUE THREAD

**Issue by zeeshansuleman** [danielgindi/Charts#2632]

**Comment by liuxuan30** [comment]
Check out ChartsDemo `@interface MultipleBarChartViewController`

**Comment by zeeshansuleman** [comment]
@liuxuan30 i did checked but there is not any string formatter.

**Comment by liuxuan30** [comment]
Check one example like `IntAxisValueFormatter` in ChartsDemo -> formatters. There are some others as well.

**Comment by zeeshansuleman** [comment]
@liuxuan30 i want to set today and yesterday only. how can i do that.

**Comment by liuxuan30** [comment]
no idea. It's supposed to be your work
