### ISSUE TITLE
OHLC charts...

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#2635]
Is it possible to do an OHLC chart like this one?

![image](https://user-images.githubusercontent.com/4366227/28544980-29418078-7093-11e7-8b59-e007e10f42a6.png)

**Comment by aelam** [comment]
It’s done already. There is a property in CandleChart view or dataset. 

发自我的 iPhone

**Comment by thierryH91200** [comment]
dataset.showCandleBar = false

**Comment by Harmonium** [comment]
Thanks! It is what I was looking for!
