### ISSUE TITLE
使用CombinedChartView绘制柱形图，如何只让当前bar视图显示灰色背影。

### ISSUE THREAD

**Issue by chenshuangsmart** [danielgindi/Charts#2636]
使用CombinedChartView绘制柱形图，如果设置属性drawBarShadowEnabled为true，则全部的bar视图都有灰色背影，如何只让当前高亮bar视图显示灰色背影，其余bar没有显示灰色背影。谢谢。

**Comment by liuxuan30** [comment]
override the methods to only show some.

**Comment by chenshuangsmart** [comment]
重用哪一个方法来指定当前高亮bar绘制灰色背影？

**Comment by liuxuan30** [comment]
search where `drawBarShadowEnabled` is being used.

**Comment by chenshuangsmart** [comment]
thank you
