### ISSUE TITLE
Swift based Charts library increased application size when used for objective c based project

### ISSUE THREAD

**Issue by smindia1988** [danielgindi/Charts#2637]
Hello Daniel,

I have used your Swift based Charts library. It has awesome features for chart drawing.

Can you share Objective - C based library for same?

**The issue for swift based chart library is that when i used it for objective - c based application, it increases application size almost double as "Swift Support" folder was added in app bundle when we used it with swift bridging.**

So it is really appreciable if we got Objective - C based library for same. 👍

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/issues/2015

**Comment by smindia1988** [comment]
Yes, i know the reason and that why requested for objective c based library if possible.

Obviously chart library size is less approx to 6M after submitting to apple.

My application is fully developed in objective c and only for the chart functionality i have used Chart swift classes hence my application size is increased 10M due to Swift Libs only.  

For the native application if size increase 10M more is obviously sensitive. :) (:

17M normal app size + 6M Chart Lib = 23M  => 10M Swift Libs(Extra due to bridging only) => 33M

**Comment by liuxuan30** [comment]
Yeah, that's the decision for you to make. I have the same experience two years ago, but no offence, who care an app from 17M to 33M to download? If a user don't want to pay for 33M, he won't pay for 17M neither.

This library will not be rewritten with ObjC I believe, as it's clear Apple is pushing swift very hard. As I said earlier, when swift is ABI stabled the swift lib should be removed from the app. However Swift 4 has deferred ABI stability FYI.

You can follow the ABI dashboard: https://swift.org/abi-stability/
Or you are lazy: https://www.infoq.com/news/2016/10/swift-4-roadmap
https://www.infoq.com/news/2017/02/swift-4-release-process
