### ISSUE TITLE
I am not able to set values on the bar in simple bar chart.

### ISSUE THREAD

**Issue by zeeshansuleman** [danielgindi/Charts#2638]
hello there , i am facing a weired issue i cant print values on the bar in simple bar chart , i do not want to use the grouped bar chart.i am also using     _chartView.drawValueAboveBarEnabled = YES;
but still there does not display any value..help me

**Comment by liuxuan30** [comment]
Have you checked ChartDemo? I notice you are asking similar questions and it seems ChartsDemo already demoed them.
And you question is too vague

**Comment by zeeshansuleman** [comment]
@liuxuan30 in chart demo no value print out in simple bar chart.it only prints in multiplebarchart. thanks

**Comment by liuxuan30** [comment]
are you asking `drawValuesEnabled`?

**Comment by zeeshansuleman** [comment]
i also enabled drawvalues but still bar does not show values on its top.

**Comment by liuxuan30** [comment]
can't be.. screenshots?

**Comment by zeeshansuleman** [comment]
@liuxuan30 here is the screen shot.
<img width="375" alt="screen shot 2017-08-11 at 12 23 22 pm" src="https://user-images.githubusercontent.com/12757747/29204410-486d3e32-7e90-11e7-830e-2431d4d9f781.png">

**Comment by liuxuan30** [comment]
Alright, if you enabled `drawValuesEnabled`, debug `drawValues()` func to see if it's drawing. BTW, did you change the text color to be visible?
