### ISSUE TITLE
How to implement custom dataset in objective-c?

### ISSUE THREAD

**Issue by CavalcanteLeo** [danielgindi/Charts#2639]
I've read the documentation, but even with that, I didn't figured out.

Is there any exemple in objective-c?

https://github.com/PhilJay/MPAndroidChart/wiki/Custom-DataSets (Android documentation)

**Comment by liuxuan30** [comment]
I recommend you implement sub DataSet class in swift to avoid any incompatible issue while sub classing. It's not hard.
