### ISSUE TITLE
Why not contain Funnel Chart?

### ISSUE THREAD

**Issue by wjxfhjxy** [danielgindi/Charts#2641]
Funnel Chart is very userful for intuitively show the stages of sales channels !

**Comment by liuxuan30** [comment]
No ETA :( But you are welcome to contribute.

I used to write one based on this framework, but it's my previous company's properties and customized.

What I did is using BarChartView as the base and change its shape to funnels..

**Comment by liuxuan30** [comment]
due to https://github.com/danielgindi/Charts/issues/1038 as well.
