### ISSUE TITLE
I have a problem with compiling

### ISSUE THREAD

**Issue by AntonioChen0419** [danielgindi/Charts#2643]
Hi~
I like "Charts" ,it good!
but when i was build
![2017-07-26 5 37 33](https://user-images.githubusercontent.com/27674544/28614744-7031e076-7229-11e7-93f4-70855eb301a4.png)

What should I do ？？？
Thank you for your help
Antonio

**Comment by AntonioChen0419** [comment]
PS:
xocde: 8.3.3  
swift: 3.0

**Comment by liuxuan30** [comment]
seems you have duplicated frameworks compiled. Try search those duplicated classes
