### ISSUE TITLE
Combined chart with horizontal bar and bubble 

### ISSUE THREAD

**Issue by CavalcanteLeo** [danielgindi/Charts#2644]
How to implement combined chart with `horizontal bar` and `bubble`?

I could only set with vertical bars, not horizontal

I created a horizontal bar like this:

![img_4122](https://user-images.githubusercontent.com/1735944/28648050-60ee4b0a-7241-11e7-88af-7b813cb40bd5.PNG)

This is a pure `HorizontalBarChartView`

But i need to use CombinedChartView to look like this:
![captura de tela 2017-07-26 as 20 32 13](https://user-images.githubusercontent.com/1735944/28648062-875431ec-7241-11e7-99ff-47a75e0e13e8.png)

Thanks in advance

**Comment by liuxuan30** [comment]
combined chart does not support horizontal bars.
