### ISSUE TITLE
autoScaleMinMaxEnabled, axisMaximum and axisMinimum

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#2651]
I would like to know if it is a normal behaviour...

I set autoScaleMinMaxEnabled to true. If I set an axisMinimum and axisMaximum value, the autoScale is not working anymore.

I set an axisMinimum and axisMaximum in order to have a buffer. I don't want my graphic to touch the top of my chart. So I add a 5% to the maximum value just to have a little space between the top of my chart and the chart.

I tried to set the spaceTop but  I don't have the expected behaviour.

Thanks for your help!

**Comment by liuxuan30** [comment]
I think yes, autoScaleMinMaxEnabled will recalculate:
```swift
    /// Performs auto scaling of the axis by recalculating the minimum and maximum y-values based on the entries currently in view.
    internal func autoScale()
    {
        guard let data = _data
            else { return }
        
        data.calcMinMaxY(fromX: self.lowestVisibleX, toX: self.highestVisibleX)
        
        _xAxis.calculate(min: data.xMin, max: data.xMax)
        
        // calculate axis range (min / max) according to provided data
        
        if _leftAxis.isEnabled
        {
            _leftAxis.calculate(min: data.getYMin(axis: .left), max: data.getYMax(axis: .left))
        }
        
        if _rightAxis.isEnabled
        {
            _rightAxis.calculate(min: data.getYMin(axis: .right), max: data.getYMax(axis: .right))
        }
        
        calculateOffsets()
    }
```

**Comment by liuxuan30** [comment]
since you have the code, I suggest modify or override so to get you desired behaviours
