### ISSUE TITLE
YAxisValues:"Zero" of the integer part is not displayed when the YAxis coordinate is zero

### ISSUE THREAD

**Issue by gpszzzc** [danielgindi/Charts#2653]
"Zero" of the integer part is not displayed when the YAxis coordinate is zero
![wx20170731-140724](https://user-images.githubusercontent.com/18419255/28764765-d60d7a6c-75f9-11e7-8f16-f4e8ce986248.png)

**Comment by liuxuan30** [comment]
![image](https://user-images.githubusercontent.com/4375169/28806245-76af6032-76a1-11e7-9e41-e3af981ff001.png)
there is '.0' already, repeat your question and reopen again.

**Comment by gpszzzc** [comment]
I want they are "0.0,0.6",not ".0,.6".

**Comment by liuxuan30** [comment]
use valueFormatter...
