### ISSUE TITLE
How to add marker to center position in ios charts while scrolling horizontally with increasing scaleX and enabling drag

### ISSUE THREAD

**Issue by hananRiazz** [danielgindi/Charts#2658]
I am scrolling chart horizontally by increasing scaleX value and enabled drag as described in answer of this question

https://stackoverflow.com/questions/36884745/set-an-horizontal-scroll-to-my-barchart-in-swift/36907495#36907495

I want to add marker at center position when user scrolls horizontally. I know "chartTranslated" delegate is called whenever user drags the chart but it doesn't contain the value of "ChartDataEntry" and "Highlighted" like in "chartValueSelected" delegate method.

**Comment by liuxuan30** [comment]
markers has nothing to do with your scale or scrolling. To draw markers you only need to give highlight object
```swift
    /// draws all MarkerViews on the highlighted positions
    internal func drawMarkers(context: CGContext)
```
But notice if you want to use marker not on what you have highlighted, you may need to create another highlight object and manually passed to
```swift
            // callbacks to update the content
            marker.refreshContent(entry: e, highlight: highlight)
            
            // draw the marker
            marker.draw(context: context, point: pos)
```

**Comment by hananRiazz** [comment]
Thanks a lot for help but while dragging 'chartTranslated' is called which doesn't provide the value of entry or highlight or even chart current bounds.

func chartTranslated(_ chartView: ChartViewBase, dX: CGFloat, dY: CGFloat){

**Comment by hananRiazz** [comment]
Thanks a lot for your support. Can you tell please how to find graph (x) from pixels (xPx) ?
