### ISSUE TITLE
Bitcode Problem

### ISSUE THREAD

**Issue by RichardPeter** [danielgindi/Charts#2660]
While I am trying to archive an app using Charts, it came out as:

![2017-08-01 3 58 44](https://user-images.githubusercontent.com/25895836/28815044-8894cb9e-76d2-11e7-83e8-60dc67ac4847.png)

I AM SURE that I have enabled Bitcode for Charts.

![2017-08-01 4 00 04](https://user-images.githubusercontent.com/25895836/28815043-889076c0-76d2-11e7-8cf7-86be694b96a6.png)

How can I  solve it?

**Comment by zhoujun951236** [comment]
I met the same problem，i create a sample project which only contain charts.framework.when i archive ,error come out

**Comment by liuxuan30** [comment]
disable your app with bitcode, or rebuild Charts with bitcode enabled

**Comment by zhoujun951236** [comment]
https://forums.developer.apple.com/message/7038#7038,
i resolve it by this site

**Comment by wuhengheng** [comment]
O
