### ISSUE TITLE
Display programatically a marker on a chart

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#2662]
I want to display a marker on a long press gesture...

I want to drag my finger on a chart and display a marker. This can be done very easily but when my chart is zoomed it is the chart that is dragged and not the marker anymore. How can we do that?

So how can we display and hide a marker on a chart manually?

**Comment by liuxuan30** [comment]
marker is shown for a specific data entry. If you scrolled and that data entry disappeared, so does the marker.
for more flexible control, refer
>public protocol IMarker: NSObjectProtocol
