### ISSUE TITLE
Custom highlighter/marker

### ISSUE THREAD

**Issue by VanHoutte1337** [danielgindi/Charts#2663]
Hello

I need to create a linechart with specific design.
<img width="719" alt="screen shot 2017-08-01 at 18 15 53" src="https://user-images.githubusercontent.com/9484483/28835399-7b39b154-76e5-11e7-8491-24b6ed902723.png">
<img width="717" alt="screen shot 2017-08-01 at 18 15 33" src="https://user-images.githubusercontent.com/9484483/28835400-7b483378-76e5-11e7-9d6b-ded7a5df0a07.png">

I was able to fix the design for the axis, etc but I'm having trouble on how to achieve the custom highlighter/marker.

Requirements
- the highlighted value should have a circle on the value
- the highlighted value should have a line from the value to the bottom
- when changing the highlighted value, the top half of the highlighter should have a dashed line + a marker on the top of the view indicating it's value.

Any help is welcome!

Kind regards

**Comment by liuxuan30** [comment]
refer
>public protocol IMarker: NSObjectProtocol

Write your own marker. You can take a look at how BalloonMarker is implemented. For the dashed line, one option is override `drawHighlightLines()` only enable the vertical highlight line and make it dashed.

**Comment by minhDTN** [comment]
@VanHoutte Did you make the tooltip successfully?

**Comment by Ramprasathselvam** [comment]
@VanHoutte did you archive this design?

https://user-images.githubusercontent.com/9484483/28835400-7b483378-76e5-11e7-9d6b-ded7a5df0a07.png

**Comment by MathiasPawshake** [comment]
> @VanHoutte did you archive this design?
> 
> https://user-images.githubusercontent.com/9484483/28835400-7b483378-76e5-11e7-9d6b-ded7a5df0a07.png

I no longer work at the company that I needed this design. I think I switched to a different library. I suppose that almost 8 years later there is a library that supports this 😅
