### ISSUE TITLE
Use Charts in Swift3,Error

### ISSUE THREAD

**Issue by HuangYanQi** [danielgindi/Charts#2664]
ld: warning: directory not found for option 'xxx/备份/Diao3/build/Debug-iphoneos/pop'
ld: warning: directory not found for option 'xxx/备份/Diao3/build/Release-iphoneos/Alamofire'
ld: warning: directory not found for option 'xxx/备份/Diao3/build/Debug'
ld: warning: ignoring file /Users/xxx/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/Charts.framework/Charts, file was built for i386 which is not the architecture being linked (x86_64): /Users/xxx/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphonesimulator/Charts.framework/Charts
Undefined symbols for architecture x86_64:
  "type metadata accessor for Charts.BarChartView", referenced from:
      type metadata accessor for Charts.BarChartView! in StatisitcController.o
  "type metadata accessor for Charts.BarChartDataEntry", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
      type metadata accessor for [Charts.BarChartDataEntry] in StatisitcController.o
  "Charts.BarChartDataEntry.__allocating_init (x : Swift.Double, y : Swift.Double) -> Charts.BarChartDataEntry", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
  "type metadata accessor for Charts.BarChartData", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
  "type metadata accessor for Charts.BarChartDataSet", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
  "Charts.BarChartData.__allocating_init (dataSets : [Charts.IChartDataSet]?) -> Charts.BarChartData", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
  "type metadata accessor for Charts.ChartDataEntry", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
  "Charts.BarChartDataSet.__allocating_init (values : [Charts.ChartDataEntry]?, label : Swift.String?) -> Charts.BarChartDataSet", referenced from:
      Diao3.StatisitcController.viewDidLoad () -> () in StatisitcController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

pod 'Charts' install the Charts ，and write some chartview code ，it can't be compiled. How can I fixed it?What happened with my Project?I can not use it in XCode Simulator ？

**Comment by liuxuan30** [comment]
`Undefined symbols for architecture x86_64` check your archs and build settings.
