### ISSUE TITLE
Is it possible to scroll without Zooming/ Scaling ?

### ISSUE THREAD

**Issue by hananRiazz** [danielgindi/Charts#2666]

**Comment by thierryH91200** [comment]
chartView. dragEnabled = true

and #2413 

        ```
        chartView.scaleYEnabled = false
        chartView.scaleXEnabled = true
        chartView.dragYEnabled = false
        chartView.dragXEnabled = true
```

**Comment by hananRiazz** [comment]
Thanks for reply. It won't scroll until I scaleX. I am avoiding scaleX because I want to get center (X) points after zooming/Scaling which is not available... I am trying to achieve  https://github.com/danielgindi/Charts/issues/2659

**Comment by liuxuan30** [comment]
It's not possible to scroll without Zooming/ Scaling. Scroll means you have more content to show. But if the scale is 1, all data are displayed on your screen, so no more content to show.
