### ISSUE TITLE
How to add texts/image into a chart?

### ISSUE THREAD

**Issue by joe528** [danielgindi/Charts#2667]
For example, I have a CandleStick chart and I want to add an arrow & a text like "Buy Signal" into the chart, as shown in the attached picture.

How to achieve this?

![buyholdsellchart](https://user-images.githubusercontent.com/5201083/28870648-a9b19c30-77b3-11e7-892d-24e7fd016e12.jpg)

**Comment by liuxuan30** [comment]
use chartMarker.

**Comment by joe528** [comment]
I thought Marker can only mark something on one highlighted entry?

How to do something illustrated in the images to show multiple markers (without users clicking)? Is there any example?

**Comment by mikaelhellqvist** [comment]
@liuxuan30 Just started to use this library. By `ChartMarker` you mean `IMarker`?

@joe528 Did you get this to work?

**Comment by liuxuan30** [comment]
yeah IMarker is the protocol. But there are already some demo markers, like `BalloonMarker` in ChartsDemo.
