### ISSUE TITLE
Graphing just a part of the data

### ISSUE THREAD

**Issue by egmonterrubio** [danielgindi/Charts#2669]
Hello, I'm learning to use the Charts  API, (by the way thanks for such an excellent resource), and I wonder if it's possible to chart just part of the data (let's say the last 10 values) and leave the rest ready to be shown if the user ¿scrolls or makes a zoom out?

**Comment by liuxuan30** [comment]
sounds like `open func setVisibleXRange(minXRange: Double, maxXRange: Double)` and combo with `moveViewToX()`
