### ISSUE TITLE
Show only 2 labels on xAxis in CombinedChartView

### ISSUE THREAD

**Issue by seboslaw** [danielgindi/Charts#2670]
Hey guys,

I'm displaying a dataset of ~300 double/date data pairs. Because I wanted to highlight the maximum value and the minimum value in that range I used a CombinedChartView (LineChart for the 300 values, and ScatterChart for the 2 max/min values).
What I'd like to accomplish now is to get only the 2 date strings of the max/min values displayed on the xAxis (as labels like "2015-05-03" below the left max value and "2016-04-22" below the right min value).
Is there a way to tell the CombinedChartView to only use the data from the ScatterChart for the labels on the x-Axis? Then it would only display the 2 min/max value labels.

What I've tried so far is to implement a custom IAxisValueFormatter and then only return a date String if stringForValue gets hit with either my min or my max value (otherwise just return "").
But for some reason stringForValue only gets called with 5 unique values - I guess the width estimation figured there's only room for 5 labels on the screen? And those 5 values don't contain my min/max values -> so no label is displayed at all.
<img width="355" alt="screenshot 2017-08-02 21 37 41" src="https://user-images.githubusercontent.com/97770/28891769-eab1d9b2-77cb-11e7-8fd7-e45fd8e6d3c2.png">

**Comment by liuxuan30** [comment]
If I were you, I'd like to override x axis to only generate the min/max values and display it.
override `computeAxisValues(min: Double, max: Double)` and feed `axis.entries` only the x point of you min/max value
