### ISSUE TITLE
Change Scale on Y Axis for CombinedChart

### ISSUE THREAD

**Issue by egmonterrubio** [danielgindi/Charts#2672]
Hello, I'm making a combined chart with a line and bar chart, the line chart is used for magnitudes in the order of 100s, while the bar chart is used for magnitudes in the order of 10. So I set each chart dependent to the right and left axis respectevley. But both axis show the same values; is it possible to set different scales for each axis? 

Thanks!

**Comment by thierryH91200** [comment]
see #2049  and #1830

**Comment by egmonterrubio** [comment]
Thanks!
