### ISSUE TITLE
ChartFill - I would like to fill above the line

### ISSUE THREAD

**Issue by pbamma** [danielgindi/Charts#2674]
I would like to be able to draw a fill gradient above the dataset.  I'm not seeing this supported anywhere directly.  Any tips on how I could get to an eventual chart like the attached?
![screen shot 2017-08-03 at 11 51 55 am](https://user-images.githubusercontent.com/3640619/28938193-2ec24be8-7842-11e7-8199-7ce942acc40e.png)

**Comment by pbamma** [comment]
So I'm guessing I'll have to dig into the library to figure out how to flip the mask... but I'll bet if I can do that, then I can draw two of the same dataset... one with a gradient masked down and the other masked up... while ensuring that the gradient drop off happens at Y==0. Thoughts?

**Comment by liuxuan30** [comment]
it's not a easy one. You have to add hidden line path to make a closed rect and then fill.

**Comment by pbamma** [comment]
Turns out it will draw like this out of the box.  You must simply have a dataset that is above and below zero.  (which means you've got to be careful with your chart max and min (to keep them abs equal) and take care with your gradient draw (by targeting the center point to a white or clear color)).

**Comment by pbamma** [comment]
If anyone has questions, I can help you out.
