### ISSUE TITLE
Dashed border on highlighted bar - BarChart

### ISSUE THREAD

**Issue by gustavo-yy** [danielgindi/Charts#2675]
Hi, I'm trying to add a dashed border when I click on a barchart, at the moment I was abble to add a border but not the way a want.

I've tried this inside BarChartRenderer->drawHighlighted:
context.setStrokeColor(UIColor.white.cgColor)
context.stroke(barRect)
context.setLineDash(phase: 0.0, lengths: [5.0])

This is what i got:
![captura de pantalla 2017-08-03 a la s 13 53 53](https://user-images.githubusercontent.com/25230289/28938377-82d8effa-7853-11e7-95f4-65187d07c688.png)

But I want it lo look like this:
![captura de pantalla 2017-08-03 a la s 13 54 26](https://user-images.githubusercontent.com/25230289/28938406-91a0fe92-7853-11e7-82f6-a8fa7e71ceef.png)

**Comment by liuxuan30** [comment]
we already support bar border
```swift
    /// the color used for drawing the bar-shadows. The bar shadows is a surface behind the bar that indicates the maximum value
    var barShadowColor: NSUIColor { get set }
    
    /// the width used for drawing borders around the bars. If borderWidth == 0, no border will be drawn.
    var barBorderWidth : CGFloat { get set }

    /// the color drawing borders around the bars.
    var barBorderColor: NSUIColor { get set }
```
you only need to apply dash
