### ISSUE TITLE
Horizontal bar charts 'Y' values are getting overlapped with '0'

### ISSUE THREAD

**Issue by JarvisTheAvenger** [danielgindi/Charts#2691]
Hi ,

I have used charts library to plot the horizontal bar chart in the app , but in the special scenario when one of the attribute values in Y axis is zero it's getting overlapped with the  previous attributes 

Using  latest version of charts for swift3  from cocoa pods 

![screen shot 2017-08-09 at 12 38 20 pm](https://user-images.githubusercontent.com/25341882/29109206-d8b1d378-7cff-11e7-9f25-b626e48e48c6.png)

**Comment by liuxuan30** [comment]
yes this is known issue. But we don't have to fix this so far. you can manually add some offset if you found its zero. Try search old issues for this
