### ISSUE TITLE
xAxis scrolling in combineChartView

### ISSUE THREAD

**Issue by renjiale1214** [danielgindi/Charts#2695]
I want set rightAxis.axisMaximum & rightAxis.axisMinimum when scrolling chartView,
how to do that?(i have 200 data but my maxVisibleCount==60 ) 

PS: by Objc
- (void)chartTranslated:(ChartViewBase *)chartView dX:(CGFloat)dX dY:(CGFloat)dY
when log dx and dy print 0

**Comment by liuxuan30** [comment]
then when you scrolling, set it in `performPanChange`. What's the problem?

**Comment by renjiale1214** [comment]
thanks, i have an new issue about "Charts-Swift.h",please teach me.
