### ISSUE TITLE
LineData - plotting very large data sets (DataApproximator?)

### ISSUE THREAD

**Issue by kzhaowmm** [danielgindi/Charts#2697]
When plotting very large datasets (5000+ datapoints), some of which update in real time, there is significant graphical lag.

What is the most efficient way to reduce the number of points being plotted (based on a changing viewport)? Should the dataset be dynamically changed before being fed into the chart (based on viewport size), or should the pixel rendering be changed after the dataset has already been set?

In the case of changing pixel rendering, would the DataApproximator class come in handy (for reducing an array of CGPoints? (I'm not entirely sure how to use it)

Much thanks!

**Comment by liuxuan30** [comment]
This is known issue as it's cpu intensive work. You have to reduce the size by sampling by you should be the most efficient way?

**Comment by kanshenmekan** [comment]
5000+? I just tested 1000 points, and then I added one point per second, notifyDataSetChanged, and CPU utilization was almost 99%, and I tested it on the iphone6.
