### ISSUE TITLE
Disable bar selection or highlight?

### ISSUE THREAD

**Issue by seenoevo** [danielgindi/Charts#2699]
I'm trying to disable the user from selection of any bars in a `BarChartView`. 

In following #2337, I did the following with no results: `barChartView.highlightValue(nil, callDelegate: true)` as well as `barChartView.highlightValue(nil)`

In following stackoverflow's answer [How to disable selection of bar char?](https://stackoverflow.com/a/43946764/2373410) I also did the following `barChartView.delegate?.chartValueNothingSelected!(barChartView)` with no results.

What is the right away to disable selection/highlight in a `BarChartView`?

**Comment by seenoevo** [comment]
`chartDataSet.highlightEnabled = true`

**Comment by seenoevo** [comment]
```
chartDataSet = BarChartDataSet(values: dataEntries, label: "")
chartDataSet.highlightEnabled = false
```

`chartDataSet.highlightEnabled = false` needs to be called AFTER initializing the `BarChartDataSet` object

**Comment by ZaidSA** [comment]
`chartDataSet.highlightAlpha = 0` worked for me.
