### ISSUE TITLE
IValueFormatter text showing More than one Time 

### ISSUE THREAD

**Issue by viswanath3344** [danielgindi/Charts#2700]
I am tried to patrician yAxis as 3or 4 separate blocks with limit lines . for this i am given different  hardcoded values. But i need to display original values on top of bars . For this i used IValueFormatter to get customized text . 
But here problem is , It showing text overlap. 

Could you please help me the approach.

![screen shot 2017-08-10 at 2 23 24 pm](https://user-images.githubusercontent.com/8588641/29157170-3fd16d88-7dd8-11e7-91f9-5801264f83e0.png)

**Comment by liuxuan30** [comment]
double check your formatters and check ChartDemo. We don't know what you have changed.

**Comment by viswanath3344** [comment]
It's mistake done by my side. I am fixed those . I took more chartdataset than required. So value formatter called many times  . Thanks your response.
