### ISSUE TITLE
Balloon Marker: making it work in line chart inside combined view

### ISSUE THREAD

**Issue by egmonterrubio** [danielgindi/Charts#2703]
Hello; I'm learning to use Charts, it's an amazing tool, thanks for sharing it. 

I created a CombinedChart with bars and lines, and it's working fine, then I added the BallonMarker and it works with the bar chart but it doesn't consider the line chart, I added the option to select  if the user wants bar and line, just bar or just line charts, and with the option of just bars selected it still works, but I can't make it work with the line chart, is there something that need to be changed in the Balloon Marker code? 

This is the code I use to create it: 

```
let marker:BalloonMarker = BalloonMarker(color: UIColor.red, font: UIFont(name: "Helvetica", size: 12)!, textColor: UIColor.white, insets: UIEdgeInsets(top: 7.0, left: 7.0, bottom: 7.0, right: 7.0))
        marker.minimumSize = CGSize(width: 75.0, height: 35.0)
        combinedChartView.marker = marker

```
Also, one more thing, is it possible to make the BallonMarker change position if there is not enough space to be shown, like this case? 

<img width="668" alt="captura de pantalla 2017-08-11 a la s 11 20 42" src="https://user-images.githubusercontent.com/29031137/29222229-468bc2fe-7e87-11e7-89cd-edfa4fbef398.png">

Thanks!!

**Comment by liuxuan30** [comment]
Balloon marker is just a demo marker. You can create your own marker class and do whatever you like to display and where. 

For bar/line chart issue, you may want to take a look at https://github.com/danielgindi/Charts/issues/2692
