### ISSUE TITLE
BarChart does not render with multiple data sets

### ISSUE THREAD

**Issue by software-2** [danielgindi/Charts#2705]
I'm trying to create a bar chart using multiple data sets, but when I try to provide multiple sets to the `BarChartView` no bars are rendered. 
```Swift
let barView = BarChartView()

let set1 = BarChartDataSet()
set1.addEntry(BarChartDataEntry(x: 1, y: 1))
let set2 = BarChartDataSet()
set2.addEntry(BarChartDataEntry(x: 2, y: 2))

barView.data = BarChartData(dataSets: [set1, set2])

contentView = barView
```

In the above example, I would expect two bars to be displayed. However, no bars will appear at all. 

If I provide only one data set, the chart will render as expected.
```Swift
barView.data = BarChartData(dataSets: [set1])
```

**Comment by liuxuan30** [comment]
take a look at ChartsDemo multiple bars chart if you missed anything.

**Comment by 9527001** [comment]
@liuxuan30  📊支持左右两侧Y轴值不一样  比如，左侧是最大是100 右侧最大值是1 000 000 ？
