### ISSUE TITLE
Add horizontal line at certain value on Y-Axis?

### ISSUE THREAD

**Issue by ridley1224** [danielgindi/Charts#2706]
![line](https://user-images.githubusercontent.com/386803/29237145-e12058c6-7ee5-11e7-8331-ae40209938da.png)

I want to add an overlapping line like in the attached candlestick chart, but I can't find where the side labels are being generated to expose their Y positions on the chart to add the line to the UIView. I'll be updating the line's Y position at runtime so I don't need it drawn in the chart context.

For example I want in the attached image I want to add the yellow line at a specific position from a variable (1.181). Is this possible?

**Comment by fuacici** [comment]
you should try LimitLine

**Comment by ridley1224** [comment]
works great thank you
