### ISSUE TITLE
where do I find ioscharts.framework?

### ISSUE THREAD

**Issue by peppermintbunny** [danielgindi/Charts#2707]
Where do I find ioscharts.framework.
I cant get started with ioscharts today.  I had previous versions working.  Now I'm confused with Carthage and new changes.  Can you please update the installation for IOS?

**Comment by liuxuan30** [comment]
If you use carthage, it's here: `ios-charts/build/Release`
Or you just download the project and build it and find it under your Xcode derived data:
`~/Library/Developer/Xcode/DerivedData`

**Comment by peppermintbunny** [comment]
Many thanks for your helpful reply!  Kind regards
