### ISSUE TITLE
How to format values on barchart

### ISSUE THREAD

**Issue by BaranBerk** [danielgindi/Charts#2708]
If I have big numbers in values they shown on top of each other. I would like to show them like 1M, 2.3K and etc. Is there any way to format values on barchart
![barchartvalues](https://user-images.githubusercontent.com/10603380/29242178-bdae1e86-7f90-11e7-8824-a6c113b94f77.png)

**Comment by liuxuan30** [comment]
Use `valueFormatter` for you data sets

**Comment by BaranBerk** [comment]
My format changes according to value and cannot set different formatter for different values. For 1000 I would like to use 1K and 1000000 I would like to use 1M but formatter doesn't get a formatter array. Thanks

**Comment by thierryH91200** [comment]
If it can help you

[LargeValueFormatter.swift.zip](https://github.com/danielgindi/Charts/files/1224371/LargeValueFormatter.swift.zip)

and

 ```
data.setValueFont( NSUIFont(name: "HelveticaNeue-Light", size: CGFloat(10.0)))
            data.setValueFormatter(LargeValueFormatter())
```

<img width="1557" alt="capture d ecran 2017-08-15 a 09 16 08" src="https://user-images.githubusercontent.com/6251463/29305821-f7a8acb2-819a-11e7-89ed-c25b6a32f671.png">

**Comment by BaranBerk** [comment]
This is exactly what I am looking for thank you

**Comment by AppCodeZip** [comment]
> barchart

I think it can help you.
https://www.appcodezip.com/2021/06/YAxis-format-values-K-Lakh-crore.html
