### ISSUE TITLE
Runtime EXC_BAD_ACCESS with barchart whiles zoom in 

### ISSUE THREAD

**Issue by ReneVella** [danielgindi/Charts#2709]
During run time a EXC_BAD_ACCESS dump is experienced while you try to zoom on the chart using Xcode 8.3.3 and ioscharts 3.0.2. The App has no errors, complies and build successfully. Any help will be very much appreciated as i have been days trying to fix this issue. 

<img width="358" alt="screen shot 2017-08-13 at 05 53 01" src="https://user-images.githubusercontent.com/30633629/29246265-0eb068c4-7fec-11e7-9294-d9ef2bc431f7.png">
<img width="726" alt="screen shot 2017-08-13 at 05 54 11" src="https://user-images.githubusercontent.com/30633629/29246266-0ed684fa-7fec-11e7-8c43-763257c971b4.png">

**Comment by liuxuan30** [comment]
Did you changed ChartsDemo or ChartsDemo just crashes?
You have to look at `months` first..

**Comment by ReneVella** [comment]
Hi,
i did not change ChartsDemo but copied the relevant code into my App. The ChartsDemo work well with no issues. 

what do you mean by "without other ops" ?

**Comment by ReneVella** [comment]
I managed to replicate and isolate the issue. It seems that this issue only occurs when i'm not using Storyboards. That is i'm using xib Files in the project navigation. Sill would like to find a solution to this bug ?

**Comment by liuxuan30** [comment]
I still think you have out of bounds issue for `months[(int)value % months.count];` as I don't have your code, you can easily debug on your side.

**Comment by ReneVella** [comment]
Hi,

the content of months is the following:- 

months = @[
               @"Jan", @"Feb", @"Mar",
               @"Apr", @"May", @"Jun",
               @"Jul", @"Aug", @"Sep",
               @"Oct", @"Nov", @"Dec"
               ];

**Comment by ReneVella** [comment]
mode debug info
Printing description of self->months:
(NSObject) NSObject = {
  isa = 0xbadd09d9c5a5bead
}
Printing description of self->months:
(NSArray *) months = 0x00000001700cb2f0
Printing description of self->months->isa:
-2.31330477153741e+16
Printing description of self->months->isa:
-2.31330477153741e+16
Printing description of self->months:
(NSObject) NSObject = {
  isa = 0xbadd09d9c5a5bead
}
(lldb)

**Comment by ReneVella** [comment]
@liuxuan30

is it possible to disable the zooming on the Graph ?

**Comment by thierryH91200** [comment]
try
`chartView.doubleTapToZoomEnabled    = false`

**Comment by ReneVella** [comment]
@thierryH91200

thanks but no luck, i also tried the following:-

   _chartView.doubleTapToZoomEnabled = NO;
    _chartView.pinchZoomEnabled = NO;
