### ISSUE TITLE
How to decrees column width size in LineChart

### ISSUE THREAD

**Issue by vahids** [danielgindi/Charts#2710]
Hi, 
I just migrated from Swift 2 to Swift 3.
after some modification I succeed drawing chart.
 
the columns with is higher than `Charts Version 2` :
<img width="660" alt="screenshot of simulator" src="https://user-images.githubusercontent.com/1405424/29249693-c517cbcc-8049-11e7-8d1c-d9dbcddff494.png">

Is there any way to make it lower ?

Look at the picture I attached. I just have 7 point: 0:00, 2:30, 5:00, 7:30,...
I want to make it double. something like: 0:00, 1:00, 2:30, 3:30, 5:00, 6:20, 7:30,...

Thanks ;-)

**Comment by liuxuan30** [comment]
take a look at `computeAxisValues()`, where it gets the axis entries. You can use `isForceLabelsEnabled` or just override this func to get what you want.

You may want to revisit your values and its formatted strings, as the interval looks strange...
