### ISSUE TITLE
Fail to display any thing in line chart.

### ISSUE THREAD

**Issue by eeyrw** [danielgindi/Charts#2712]
After investigating the demo of osx and ios for a while, I wrote the minimal function code to show a simple line. But it seems far from normality :
![image](https://user-images.githubusercontent.com/2088817/29251610-4a84efca-808a-11e7-91f5-ea26383ab6e9.png)

 Here is my code:
```
...
@property (weak) IBOutlet LineChartView *lv;
...
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification {
    NSMutableArray *values = [[NSMutableArray alloc] init];
    
    for (int i = 0; i < 200; i++)
    {
        double val = i;
        [values addObject:[[ChartDataEntry alloc] initWithX:i y:val]];
    }
    
    LineChartDataSet *set1 = [[LineChartDataSet alloc] initWithValues:values label:@"DataSet 1"];
    NSMutableArray *dataSets = [[NSMutableArray alloc] init];
    LineChartData *data = [[LineChartData alloc] initWithDataSet:set1];
   
    self.lv.data = data;
    [self.lv animateWithXAxisDuration:0 yAxisDuration:1];
    
    
}
```

**Comment by liuxuan30** [comment]
You should follow what the demo shows you... I don't know what's going on your chart neither. You have to check many things to make sure the chart is correctly initialized, rendered on your side.
