### ISSUE TITLE
Showing actual value IN ADDITION to percentage, in a pie slice?

### ISSUE THREAD

**Issue by seenoevo** [danielgindi/Charts#2713]
Currently my PieChart looks like this:

![untitled](https://user-images.githubusercontent.com/8109158/29253497-6c7b28da-8033-11e7-82d9-b998c7bcda8f.png)

where I do the standard code:

```
let dataEntry = PieChartDataEntry(value: costs, label: date)
     
 dataEntries.append(dataEntry)

chartDataSet = PieChartDataSet(values: dataEntries, label: "")
            
chartData = PieChartData(dataSet: chartDataSet)

pieChartView.data = chartData
```

The library does its calculations to determine the "percentage" of each pie slice based on the total `costs`.

I know it calculates this in `PieChartRenderer` using:
```
let value = usePercentValuesEnabled ? e.y / yValueSum * 100.0 : e.y
let valueText = formatter.stringForValue(
      value,
      entry: e,
      dataSetIndex: i,
      viewPortHandler: viewPortHandler)

...

ChartUtils.drawText(
        context: context,
        text: valueText,
        point: labelPoint,
        align: align,
        attributes: [NSFontAttributeName: valueFont, NSForegroundColorAttributeName: valueTextColor]
)
```

How can I show the actual `costs` Double value in addition to the percentage in the slice?

For example, the `costs` value for the label `2017` is **100.0** and the `costs` value for the label `2016` is **50.0**.

How can I show those 2 values in the pie slices near its labels also, similar to the screenshot in #1084, without modifying the original code?

**Comment by liuxuan30** [comment]
subclass pie chart and override the methods you found

**Comment by seenoevo** [comment]
@liuxuan30 looked at the code, but not exactly sure how to implement it?..I've just started learning this library recently

any more help you can provide?
