### ISSUE TITLE
Label Position xAxis Radar Chart

### ISSUE THREAD

**Issue by AaronVinh** [danielgindi/Charts#2714]
I am having trouble adjusting the label distance from the chart.  I would like the chart to be bigger, but it automatically adjust to fit the labels which makes the chart too small.  I would like to decrease the distance of the label to the chart and increase the radius of the radar chart.  I have tried adjusting the labelPosition of the xaxis but it doesn't seem to change anything.  

Any pointers could be helpful. 
<img width="372" alt="screen shot 2017-08-13 at 4 40 23 pm" src="https://user-images.githubusercontent.com/14302659/29254246-2c97e0d8-8046-11e7-8728-5b81f197e732.png">

**Comment by liuxuan30** [comment]
That's because the text length is large so the contentRect shrinks.
 You can workaround this by limiting your text largest size by overriding `open func computeSize()` in `XAxisRendererRadarChart`. By default it touches nothing but it's a good place for you to override there.

**Comment by albidev** [comment]
Hi @AaronVinh did you solve that?
