### ISSUE TITLE
Different Charts-Swifg.h when simulator and iphone

### ISSUE THREAD

**Issue by renjiale1214** [danielgindi/Charts#2720]
There is a issue about a method **-(void)calcMinmax**, I used it when running on simulator what's called by @class CombineChartView, but when i want to run on my iphone, 
it have an error told me that"No visible @interface for 'CombinedChartView' declares the selector 'calcMinmax' "
I found that there have diffrent "Charts-Swift.h" project between 
"Debug-iphoneos/Charts/Charts.framework/Headers" and 
"Debug-iphonesimulator/Charts/Charts.framework/Headers"

so, is there anyway to solve this?

**Comment by renjiale1214** [comment]
@liuxuan30   Please help me, 大神

**Comment by renjiale1214** [comment]
well, i found another method "notifyDataSetChanged" can solve this problem,is it correct way to calculate when zooming?

**Comment by liuxuan30** [comment]
notifyDataSetChanged is needed when you changed your data.
Based on your first question,  I think you need to clean and rebuild... also it's `calcMinMax`
