### ISSUE TITLE
Draw bar chart from axisMinimum instead of 0

### ISSUE THREAD

**Issue by hananRiazz** [danielgindi/Charts#2721]
I am using combine line bar chart. Negative values are drawing lines from 0. I have set the axisMinimum to a negative value which has moved x-axis up which looks fine. But I want to draw the bar chart lines from not from x-axis

![screen shot 2017-08-15 at 3 01 43 pm](https://user-images.githubusercontent.com/30617336/29305528-c12f9570-81cb-11e7-84e0-c1602f63b0d9.png)

I want to make It something like this 

![screen shot 2017-08-15 at 3 33 24 pm](https://user-images.githubusercontent.com/30617336/29306250-36b75564-81cf-11e7-8175-4b72d5460a6f.png)

**Comment by seenoevo** [comment]
can you show the before/after with the whole graph axis labels?..

I'm having a hard time understanding what exactly you want to do.

also show some sample code of what you currently have

**Comment by liuxuan30** [comment]
line chart and bar chart could use left and right axis so you can have two y axis by setting `axisDependency`.
If you share the same y axis, then you need to understand the bar starts from 0.
