### ISSUE TITLE
Add gradient to bar chart

### ISSUE THREAD

**Issue by gustavo-yy** [danielgindi/Charts#2722]
Hi, I'm trying to add a gradient to my bar charts but I can only draw the first bar:

![captura de pantalla 2017-08-15 a la s 17 35 25](https://user-images.githubusercontent.com/25230289/29339722-277820da-81e1-11e7-880c-82293d934d61.png)

I added the gradient at _BarChartRenderer->drawDataSet_ right after if _!isSingleColor{}_

```
let fillColors = [UIColor.white.cgColor, UIColor.yellow.cgColor]
let locations:[CGFloat] = [0.0, 1.0]
            
context.clip(to: barRect)
let gradient:CGGradient
let colorspace:CGColorSpace
colorspace = CGColorSpaceCreateDeviceRGB()
            
gradient = CGGradient(colorsSpace: colorspace, colors: fillColors as CFArray, locations: locations)!
            
//Vertical Gradient
let startPoint:CGPoint = CGPoint(x: 0.0, y: viewPortHandler.contentBottom)
let endPoint:CGPoint = CGPoint(x: 0.0, y: viewPortHandler.contentTop)
            
context.drawLinearGradient(gradient, start: startPoint, end: endPoint, options: .init(rawValue: 0))
```

**Comment by liuxuan30** [comment]
why can't you apply the code to other bars? What's the issue?

**Comment by gustavo-yy** [comment]
That's the problem, i don't know why it's only taking effect to the first bar, in the image i should have around 16 bars but it looks like the others are transparent

**Comment by liuxuan30** [comment]
how about you remove the gradient? All bars appear? Maybe better ask on SO... 
Also maybe check the context state?

**Comment by gustavo-yy** [comment]
yes, if i remove the gradient all the bars appear normally

**Comment by gustavo-yy** [comment]
I've added an **if(j==10){}** to draw the gradient at the bar 11 and it looks like this:
![captura de pantalla 2017-08-28 a la s 12 37 51](https://user-images.githubusercontent.com/25230289/29785581-bfc77136-8bed-11e7-8a26-7d253f6e3c2d.png)

I should have 28 bars but it stops at the 11 bar

**Comment by liuxuan30** [comment]
it looks like a CoreGraphics issue to me. Have you tried to save/clean the state every time you want to render a bar? I don't know the reason yet..

**Comment by liuxuan30** [comment]
BTW, I just came across https://github.com/danielgindi/Charts/issues/2515, when someone us using CALayer to draw gradient, and it works though.. CoreGraphics is underlying CALayer gradient so I guess you can refer something, or at least a work around.

**Comment by sokalyambda** [comment]
I played with save/restore gState as mentioned before and now it works!Hope, this will help someone, thank you guys.

if !isSingleColor
            {
                let fillColors = [dataSet.color(atIndex: 0).cgColor, dataSet.color(atIndex: 1).cgColor]
                let locations:[CGFloat] = [0.0, 1.0]
                
                context.saveGState()
                context.clip(to: barRect)
                let gradient:CGGradient
                let colorspace:CGColorSpace
                colorspace = CGColorSpaceCreateDeviceRGB()
                
                gradient = CGGradient(colorsSpace: colorspace, colors: fillColors as CFArray, locations: locations)!
                
                //Vertical Gradient
                let startPoint:CGPoint = CGPoint(x: 0.0, y: viewPortHandler.contentBottom)
                let endPoint:CGPoint = CGPoint(x: 0.0, y: viewPortHandler.contentTop)
                
                context.drawLinearGradient(gradient, start: startPoint, end: endPoint, options: .init(rawValue: 0))
                context.restoreGState()
            } else {
                context.fill(barRect)
            }

**Comment by gustavo-yy** [comment]
@sokalyambda thank you, it works!

**Comment by alxarsnk** [comment]
@sokalyambda thx, it's really works
