### ISSUE TITLE
Can I use Charts in Swift 4?

### ISSUE THREAD

**Issue by tjluozhongjin** [danielgindi/Charts#2723]
Can I use Charts in Swift 4?

**Comment by seenoevo** [comment]
I'm using the library on Swift 4 right now and it's fine!

**Comment by liuxuan30** [comment]
You can use swift 3.2 first. There is a PR #2507 but it's a WIP. After Xcode 9 is released, we could upgrade to 4.

**Comment by coty10** [comment]
They released a GM seed version of xcode... will you upgrade any soon?

**Comment by youresolutions** [comment]
Xcode 9 GM seed is here, please advise if there will be any update for the library soon

**Comment by liuxuan30** [comment]
it's merged already
