### ISSUE TITLE
Problems encountered with charts

### ISSUE THREAD

**Issue by shanyulaile** [danielgindi/Charts#2724]
1. when the chart is added to tableview's cell, it will conflict with the gestures of the chart on cell when tableview is sliding up and down. How do you solve this problem?

2. How do you use multiple segments of different colors on the same fold when using a line chart

**Comment by liuxuan30** [comment]
1. there is `_outerScrollView` inside to avoid some conflicts in pan gesture. you can take a look at `panGestureRecognized` and `open func gestureRecognizer(_ gestureRecognizer: NSUIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: NSUIGestureRecognizer) -> Bool`

2. I am not sure what's your question...
