### ISSUE TITLE
Custom Text Axis X Horizontal Bar Chart

### ISSUE THREAD

**Issue by choungchamnab** [danielgindi/Charts#2726]
Is there a way that I can customize this part ?

<img width="352" alt="screen shot 2017-08-17 at 5 07 12 pm" src="https://user-images.githubusercontent.com/8243358/29407494-c44f2186-836e-11e7-8446-dbecead5e229.png">

**Comment by seenoevo** [comment]
please use the search function...there are multiple issues regarding this: 

#1852, #2094, #1604, #1527, #1340

those are a few of the many I found
