### ISSUE TITLE
Can't subclass BarChartRenderer due to 'fileprivate' status of many properties

### ISSUE THREAD

**Issue by cegiela** [danielgindi/Charts#2731]
Thank you for your work on this -- I'd like to customize the appearance of the bars, but can't do it by subclassing the renderer cleanly. It has to be initialized with things that are unavailable to me unless I subclass them and their dependancies, and on it goes. I'd like to just feed the existing properties on BarChartView back into the initialization of the renderer. On a broader note: Really almost all properties should be open in open-source software.

**Comment by seenoevo** [comment]
I am also fixing the same issue, I'm trying to subclass `BarChartRenderer` and override `drawValues`, but `fileprivate class Buffer` and `fileprivate var _buffers = [Buffer]()`.

It's most likely we have to change the source at least for `BarChartRenderer` if we want to subclass it, but I like to hear from @danielgindi @PhilJay @liuxuan30 if there's a better to not touch the source code.

**Comment by seenoevo** [comment]
@cegiela resolved it

just re-declare all the `fileprivate` variables/functions in your subclass, i.e.:

```
public class CustomBarChartRenderer: BarChartRenderer
{
    fileprivate class Buffer
    {
        var rects = [CGRect]()
    }
   
    fileprivate var buffers = [Buffer]()
    
    fileprivate var barShadowRectBuffer = CGRect()
    
    override public func initBuffers()

   ...
}
```

**Comment by cegiela** [comment]
Thanks @seenoevo, but then how do you make an instance of CustomBarChartRenderer with all the required parameters? Did you get that figured out?

**Comment by seenoevo** [comment]
@cegiela not following you, provide me with your sample code and the issue you're having and I can try to assist you

**Comment by seenoevo** [comment]
@cegiela I think I realized what you're saying:

here's what you do:

The `CustomBarChartRenderer` has the following in its parameters:

`CustomBarChartRenderer(dataProvider: BarChartDataProvider?, animator: Animator?, viewPortHandler: ViewPortHandler?)`

just pass in your `BarChartView`'s object member variables like so:

```

var barChartView = BarChartView()
....
let customRenderer = CustomBarChartRenderer(dataProvider: barChartView,
                                                        animator: barChartView.chartAnimator,
                                                        viewPortHandler: barChartView.viewPortHandler)
```

**Comment by aelam** [comment]
I have the same problem 
So I copy the whole buffer class in my sub bar chart class

发自我的 iPhone

**Comment by seenoevo** [comment]
@aelam yup that is the way to do it since it's declared as `fileprivate` in the parent class

**Comment by liuxuan30** [comment]
`fileprivate` is something private if you really need to override, just modify them to interval. Redeclare in your child class also works
