### ISSUE TITLE
How do I change the color of the text on top of the bars?

### ISSUE THREAD

**Issue by doriansgithub** [danielgindi/Charts#2732]
I've looked everywhere, and can't find how to change the color or font size of the text on top of the bars.

![img_0722](https://user-images.githubusercontent.com/5715600/29481120-bda36c38-8432-11e7-8a94-8bd480ceaa00.PNG)

**Comment by seenoevo** [comment]
look in demo...for example `BarChartViewController.m`:

objective-c:
```
BarChartData *data = [[BarChartData alloc] initWithDataSets:dataSets];
[data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:10.f]];
```

swift:
```
var chartData = BarChartData(dataSet: chartDataSet)
chartData.setValueTextColor(UIColor.white)
```

**Comment by doriansgithub** [comment]
Excellent!  Got it with this:

            chartData.setValueTextColor(UIColor .cyan)

Thank you!
