### ISSUE TITLE
You can't slide along the X-axis

### ISSUE THREAD

**Issue by adfjxx1234** [danielgindi/Charts#2735]
I can't slide along the X-axis, and the X-axis can only show partial data

**Comment by seenoevo** [comment]
what do you mean by slide?...are you talking about scrolling the x-axis?

look here: #2587, #1897

if that's not what you mean, then re-clarify

**Comment by adfjxx1234** [comment]
I can not scroll along the X axis, thank you

**Comment by liuxuan30** [comment]
just zoom your chart in x direction and you can scroll then.
