### ISSUE TITLE
How can I set ValuePosition for individual slices?

### ISSUE THREAD

**Issue by skhillon** [danielgindi/Charts#2736]
When using Pie Charts, sometimes I have values that are too small to display a label inside a slice. For example, the slice for 2% is too small to show a label saying "2%".

I would like labels to be inside slices **unless** the data value is less than some threshold. 

Issue #944 suggested hiding these labels entirely, but I would prefer not to go that route. [This pull request](https://github.com/danielgindi/Charts/pull/869) added the ability to show labels outside slices, but it seems to do so for _every_ slice. 

Is it possible to be selective about displaying labels inside and outside the slice depending on its value?

**Comment by seenoevo** [comment]
if you want that, you're going to have to implement your own logic by subclassing `PieChartRenderer` and overriding `drawValues`, as the original code does not easily allow you to do that.

**Comment by liuxuan30** [comment]
as @seenoevo said, if you want to have more controls, you have to subclass and override some methods
