### ISSUE TITLE
Pie chart entry icon get cut

### ISSUE THREAD

**Issue by sky0926a** [danielgindi/Charts#2738]
HI,
I have a problem with entry's icon get cut, like this:
![img_0434](https://user-images.githubusercontent.com/3715996/29502568-93c9b006-8663-11e7-9179-3b22b9a66933.PNG)
How can I do to fix it? thank you.

my settings:
> self.pieChartView.legend.enabled = NO;
    self.pieChartView.delegate = self;
    self.pieChartView.rotationEnabled = NO;
    self.pieChartView.chartDescription = nil;
    [self.pieChartView setHoleRadiusPercent:0.9];
    [self.pieChartView setTransparentCircleRadiusPercent:0.9];

**Comment by liuxuan30** [comment]
reduce your pie chart radius by override:
```swift
    /// - returns: The diameter of the pie- or radar-chart
    open var diameter: CGFloat
    {
        var content = _viewPortHandler.contentRect
        content.origin.x += extraLeftOffset
        content.origin.y += extraTopOffset
        content.size.width -= extraLeftOffset + extraRightOffset
        content.size.height -= extraTopOffset + extraBottomOffset
        return min(content.width, content.height)
    }
```

**Comment by sky0926a** [comment]
thank you ,it'll be very helpful to me !!
