### ISSUE TITLE
Resize chart after adding limit line

### ISSUE THREAD

**Issue by dexterslabor** [danielgindi/Charts#2739]
Hi,
Thanks for your great work. 

I add a limit line when pressing a button. However, whenever the value is outside of the chart boundaries, I do not see it. I have tried the following to update the chart:
 lineChart.data?.notifyDataChanged()
 lineChart.notifyDataSetChanged()
 _and_
 lineChart.setNeedsLayout()
 lineChart.setNeedsDisplay()
without success. Any ideas how to approach this?

**Comment by liuxuan30** [comment]
>whenever the value is outside of the chart boundaries, I do not see it

Why should we see the limit line when the value is outside of the bound?

**Comment by dexterslabor** [comment]
Completely true, thanks for unlocking my mental blockage.

I solved it with a workaround, by simply adding hidden variables. 
Sorry for the late reaction.
