### ISSUE TITLE
Bar chart click on outside of bar calling delegate 

### ISSUE THREAD

**Issue by perlasivakrishna** [danielgindi/Charts#2741]
I implemented bar chart. If i selected out side area of bar also "chartValueSelected delegate" 
is calling. 
1. Is there any way to avoid that ?(example https://stackoverflow.com/questions/40232200/charts-get-selected-bar-data-only-when-tapped-inside-the-bar)
2. Is it possible to achieve the following design,  (On click of bar i want to show the y value with arrow as shown in image. click on that want to redirect to seperate view)..
![screen shot 2017-08-21 at 4 39 46 pm](https://user-images.githubusercontent.com/6779941/29516773-6384a08c-868f-11e7-9d50-0ac098136eaf.png)

Thank you....

**Comment by liuxuan30** [comment]
1. I remember the current design is choosing the closet entry to highlight. You can take a look at `BarHighlighter` and maybe override 
```swift
open func getHighlight(xValue xVal: Double, x: CGFloat, y: CGFloat) -> Highlight?
    {
        guard let chart = chart
            else { return nil }
        
        let closestValues = getHighlights(xValue: xVal, x: x, y: y)
        if closestValues.isEmpty
        {
            return nil
        }
        
        let leftAxisMinDist = getMinimumDistance(closestValues: closestValues, y: y, axis: YAxis.AxisDependency.left)
        let rightAxisMinDist = getMinimumDistance(closestValues: closestValues, y: y, axis: YAxis.AxisDependency.right)
        
        let axis = leftAxisMinDist < rightAxisMinDist ? YAxis.AxisDependency.left : YAxis.AxisDependency.right
        
        let detail = closestSelectionDetailByPixel(closestValues: closestValues, x: x, y: y, axis: axis, minSelectionDistance: chart.maxHighlightDistance)
        
        return detail
    }
```
2. You can write your own `ChartMarker` to show the popup when highlighting

**Comment by augustocadini** [comment]
> 1. I remember the current design is choosing the closet entry to highlight. You can take a look at `BarHighlighter` and maybe override
> 
> ```swift
> open func getHighlight(xValue xVal: Double, x: CGFloat, y: CGFloat) -> Highlight?
>     {
>         guard let chart = chart
>             else { return nil }
>         
>         let closestValues = getHighlights(xValue: xVal, x: x, y: y)
>         if closestValues.isEmpty
>         {
>             return nil
>         }
>         
>         let leftAxisMinDist = getMinimumDistance(closestValues: closestValues, y: y, axis: YAxis.AxisDependency.left)
>         let rightAxisMinDist = getMinimumDistance(closestValues: closestValues, y: y, axis: YAxis.AxisDependency.right)
>         
>         let axis = leftAxisMinDist < rightAxisMinDist ? YAxis.AxisDependency.left : YAxis.AxisDependency.right
>         
>         let detail = closestSelectionDetailByPixel(closestValues: closestValues, x: x, y: y, axis: axis, minSelectionDistance: chart.maxHighlightDistance)
>         
>         return detail
>     }
> ```
> 
> 1. You can write your own `ChartMarker` to show the popup when highlighting

You edited this function? I saw the code and actually is different of it.
