### ISSUE TITLE
Can not inherit Charts to subclass some cutomize charts

### ISSUE THREAD

**Issue by firetheworld** [danielgindi/Charts#2743]
Hi , I'm using this wonderful libary, but it still not totally meet some  requirement. For example, bar chart highlight is highlight the bar not like  candle stick chart has dash vertical and horizon line , how can I subclass barchart and add candle stick highlight code in it?

I have make a subclass base on BarChartView but got error on internal var and method which is restricted by Swift access control.

Does any one fix this problem?

**Comment by liuxuan30** [comment]
modify the source code make it open or subclass within the module.
