### ISSUE TITLE
Chart displays values, but no bars

### ISSUE THREAD

**Issue by FasterThanLlamas** [danielgindi/Charts#2744]
```
func updateChartWithData() {
    for diaper in realm.objects(SubmittedEntry.self).filter("diaperWasChanged = true") {
        diaperEntries.append(diaper.submissionTime!)
    }
    for i in 0..<diaperEntries.count {
        let timeIntervalForDate: TimeInterval = diaperEntries[i].timeIntervalSince1970
        let dataEntry = BarChartDataEntry(x: Double(timeIntervalForDate), y: 1.0)
        dataEntries.append(dataEntry)
    }
    let chartDataSet = BarChartDataSet(values: dataEntries, label: "Diaper count")
    let chartData = BarChartData(dataSet: chartDataSet)
    barView.data = chartData

    let xaxis = barView.xAxis
    xaxis.valueFormatter = axisFormatDelegate
}

```

<img width="342" alt="screen shot 2017-08-21 at 6 50 20 pm" src="https://user-images.githubusercontent.com/19563780/29568541-7977d08c-8705-11e7-96a8-15553bb84877.png">

**Comment by seenoevo** [comment]
show code of what your `stringForValue` looks like, you're probably not formatting it correctly

look at similar code here if you need guidance: #2215

**Comment by FasterThanLlamas** [comment]
```
extension ChartsViewController: IAxisValueFormatter {
    
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM d, yyyy"
        return dateFormatter.string(from: Date(timeIntervalSince1970: value))
    }
}
```

**Comment by seenoevo** [comment]
you are incorrectly passing in `timeIntervalForDate`  instead of the index `i` into `BarChartDataEntry(x: Double(timeIntervalForDate), y: 1.0)`

look at BarChartViewController.m and its associated DayAxisValueFormatter.m to see how it's done, it's very to how you're doing it

**Comment by FasterThanLlamas** [comment]
Are there Swift versions?

**Comment by seenoevo** [comment]
no there is not, but you can see that the code is very similar

for example you can see in `BarChartViewController.m`:

```
    for (int i = start; i < start + count + 1; i++)
    {
        double mult = (range + 1);
        double val = (double) (arc4random_uniform(mult));
        if (arc4random_uniform(100) < 25) {
            [yVals addObject:[[BarChartDataEntry alloc] initWithX:i y:val icon: [UIImage imageNamed:@"icon"]]];
        } else {
            [yVals addObject:[[BarChartDataEntry alloc] initWithX:i y:val]];
        }
}
```
Notice it is passing in the index `i` in `initWithX:i`

As I mentioned, give it a `barWidth` and see what happens because I dont see that in your code, so the chart does not know how to size the bar correctly

**Comment by fabio90h** [comment]
can put your code up as an example?
Im still confused on what to do.
