### ISSUE TITLE
Memory Leak in Horizontal Bar Chart

### ISSUE THREAD

**Issue by chuynadamas** [danielgindi/Charts#2745]
### Leak in horizontal bar chart 

I just find a leak on the horizontal bar chart, you can reproduce it if you open your demo project hit the horizontal bar chart example multiple times and then check the memory graph, i'll add some screen about how it looks.

## Retain cycle 
![screen shot 2017-08-22 at 8 02 05 pm](https://user-images.githubusercontent.com/5713880/29594263-63ec250e-8775-11e7-88c3-3f15ebb43eff.png)

## Objects created 

![screen shot 2017-08-22 at 8 02 13 pm](https://user-images.githubusercontent.com/5713880/29594270-7447ec76-8775-11e7-9246-9567fc2e1264.png)

I checked on your history issues, it seems that you guys have one related an apple bug, is this the same problem #2425 I'm using your latest version. 

Thanks in advance :)

**Comment by liuxuan30** [comment]
How to read this graph, especially `malloc`?

I tried instruments, it indeed looks like CALayer has leak:
![image](https://user-images.githubusercontent.com/4375169/29596117-2f9b1192-87ee-11e7-87e4-6b4fa07dcc6b.png)

Also, I added `dealloc` in horizontal bar chart view controller, when popping back, `dealloc` is called, but the chart view seems hold by something and cannot released:
```
2017-08-23 10:37:06.365 ChartsDemo[60964:24310892] hori. dealloc!
(lldb) po self
<HorizontalBarChartViewController: 0x7fde16f36e50>

(lldb) po self.chartView
<Charts.HorizontalBarChartView: 0x7fb064e033e0; frame = (0 47; 375 437); autoresize = RM+BM; gestureRecognizers = <NSArray: 0x60800005dbe0>; layer = <CALayer: 0x6000002241a0>>
```
After `dealloc` is finished, in runtime:
```
(lldb) po 0x7fde16f36e50
140591844519504

(lldb) po [0x7fb064e033e0 retainCount]
0x0000000000000001

(lldb) po [0x6000002241a0 retainCount]
0x0000000000000001
```

I am not sure what causes the leak right now, as we don't touch CALayer. Can someone help?

**Comment by liuxuan30** [comment]
I checked CALayer's stack trace, there is one unpaird group which looks like to your memory graph, but I don't understand right now.
![image](https://user-images.githubusercontent.com/4375169/29597016-8b955756-87f2-11e7-84c3-1bb32c2c92bd.png)

**Comment by liuxuan30** [comment]
@chuynadamas can you try on a real device with older iOS version? I don't have old simulator right now nor device. I can try find a iOS 9 device maybe tomorrow.

**Comment by chuynadamas** [comment]
@lixuan30 I did the test with a real device running 10.3.3 I don't have devices with older versions, sorry :(

**Comment by liuxuan30** [comment]
I asked a UIKit dev on twitter but no response at all.. Seems need a DTS or bug report

**Comment by liuxuan30** [comment]
filed a radar: 34298100

**Comment by DamirDjozicCoing** [comment]
I posted a comment on this memory leak on other thread. Please check this and let me know if that solves the issue.

https://github.com/danielgindi/Charts/issues/2772

Hope that helps!

**Comment by liuxuan30** [comment]
this issue seems more like for #3078 rather than #2772

**Comment by liuxuan30** [comment]
@chuynadamas reopen if this does not solve yours.
