### ISSUE TITLE
iOS8 simulator crashed iOS 8模拟器崩溃在画Y轴线的地方

### ISSUE THREAD

**Issue by MikasaAckerman** [danielgindi/Charts#2746]
是模拟器的问题吗
Is it the simulator's problem？

崩溃在charts/core/YAxisRenderer.swift 226行
crashed at charts/core/YAxisRenderer.swift 226 line

Assertion failed: (CGFloatIsValid(x) && CGFloatIsValid(y)), function void CGPathMoveToPoint(CGMutablePathRef, const CGAffineTransform *, CGFloat, CGFloat), file Paths/CGPath.cc, line 254.

**Comment by liuxuan30** [comment]
Reproducible on ChartsDemo? How about on real device?

**Comment by MikasaAckerman** [comment]
@liuxuan30 err..no, ChartsDemo uses OC, but i'm using Swift..

i changed the code `lineChartView.leftAxis.drawGridLinesEnabled = false`(origin is true but not ok) and it'ok, but i added `leftAxis.drawGridLinesEnabled = NO;` in Charts demo, there is no problem ether, is it Swift's problem?

```
open func drawGridLine(context: CGContext,  position: CGPoint)  {
        guard let viewPortHandler = self.viewPortHandler else { return }
        context.beginPath()
        context.move(to: CGPoint(x: viewPortHandler.contentLeft, y: position.y)) ## // crashed here.  And i don't have iOS 8 iPhone, ether, so i'm not sure is there problem on real device... 
        context.addLine(to: CGPoint(x: viewPortHandler.contentRight, y: position.y))
        context.strokePath()
    }
```

**Comment by liuxuan30** [comment]
Well I need you to debug on your side. You have the tools already.

**Comment by MikasaAckerman** [comment]
after a week, there is no problem at here, i didn't change any code so i don't no what happened......................................................................................................................................is it the simulator's problem? - -

**Comment by liuxuan30** [comment]
I don't know
