### ISSUE TITLE
How to disable scale of left YAxis?

### ISSUE THREAD

**Issue by webersson** [danielgindi/Charts#2748]
I have a CombinedChartView with CandleStickChartView and BarChartView: 

<img width="651" alt="bildschirmfoto 2017-08-24 um 14 52 25" src="https://user-images.githubusercontent.com/29067765/29667938-a37acbd4-88de-11e7-8c3f-a377a3aa012b.png">

The right YAxis values are changed with valueFormatter.
I set the axisDependencies like this:

```
    candleChartSet.axisDependency = combinedView.rightAxis.axisDependency
    barChartSet.axisDependency = combinedView.leftAxis.axisDependency
```

Is there a way to prevent only the left YAxis from scaling?
If I scale now, the barChart disappears under the bottom of the chart:

<img width="648" alt="bildschirmfoto 2017-08-24 um 14 53 11" src="https://user-images.githubusercontent.com/29067765/29667932-9e41215e-88de-11e7-8acb-4ce779240f62.png">

I thought maybe there is a way to disable the scaling just for the left Axis.
Would be great to get some advice.

**Comment by Visangle** [comment]
try to set leftAxis like this 
```
        bar.leftAxis.axisMinimum = 0
        bar.leftAxis.axisMaximum = 5
        bar.leftAxis.calculate(min: 0, max: 5)
```
hope have some help.

**Comment by liuxuan30** [comment]
when you scale, it's scaling the y direction, which means you cannot scale only one of them.
