### ISSUE TITLE
Create Simple Bar Chart

### ISSUE THREAD

**Issue by martheli** [danielgindi/Charts#2749]
I have been looking all over the place and theres no where where theres an example of how to create a simple bar graph in Swift 3. So far I have this but am getting nil errors. Does anyone have any documentation on how to make simple bar graphs with Swift 3?

```
func setChart() {

        let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0]
        
        let test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        
        
        var dataEntries: [BarChartDataEntry] = []
   
        
        for i in 0..<months.count {
            
            let dataEntry = BarChartDataEntry(x: Double(test[i]), y: Double(unitsSold[i]))
            
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "Visitor count")
        
        let chartData = BarChartData(dataSet: chartDataSet)
        
        barChartView.data = chartData
        
    }
```

**Comment by seenoevo** [comment]
Not sure how you're getting a nil, I copied your code into my demo and it works just fine.

```
class BarChartViewController: UIViewController
{
    let markerView = MarkerView()
    
    var months: [String]!

    override func viewDidLoad()
    {
        super.viewDidLoad()
        months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

       setChart()
    }

    func setChart()
    { 
        let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0]
        
        let test = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
        
        var dataEntries: [BarChartDataEntry] = []
        
        for i in 0..<months.count 
       {
            let dataEntry = BarChartDataEntry(x: Double(test[i]), y: Double(unitsSold[i]))
            
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "Visitor count")
        let chartData = BarChartData(dataSet: chartDataSet)
        
        barChartView.data = chartData  
    }
}
```

You must be doing something wrong...recheck your code

**Comment by martheli** [comment]
your graph doesn't show the months on the x-axis.

**Comment by seenoevo** [comment]
@martheli: that was just an example based on the code you showed

if you are receiving a nil somewhere else, show me the whole function where it's receiving a nil

**Comment by seenoevo** [comment]
@martheli glad you figured it out 👍

**Comment by martheli** [comment]
do you know if there is a simple way to remove the Y axis on the right hand side of the graph? id like the Y axis labels to only show up on the left side of the graph.

**Comment by seenoevo** [comment]
`BarChartViewController.m` shows the following:

```
    ChartYAxis *rightAxis = _chartView.rightAxis;
    rightAxis.enabled = YES;
```

Now use that as reference and convert to your swift code.

If you want to change things, play around with the Charts demo and you'll start to figure out how the charts are displayed the way they are.

**Comment by muhammadawais790** [comment]
It is not working for me it shows no chart data available. please help me out. I am very worry about my final year project and it is totally graph projects.

**Comment by froymetal** [comment]
How you delete the numbers above each bar?
