### ISSUE TITLE
Barchart starting above X-Axis

### ISSUE THREAD

**Issue by martheli** [danielgindi/Charts#2751]
The image below shows my two charts. The bars start a little bit above the X-Axis. How do I get them to sit on the X-Axis?

![image](https://user-images.githubusercontent.com/20176169/29751469-b081cdb6-8b1b-11e7-87a9-2be7b1f6af35.png)

**Comment by seenoevo** [comment]
Show your function code on how you set up the bar chart and I'll see if I can help

**Comment by martheli** [comment]
```
 func setChart(chartview: BarChartView, xarray: [String], yarray: [Double]){
        
       
        var dataEntries: [BarChartDataEntry] = []
        
        
        for i in 0..<xarray.count {
            
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(yarray[i]))
            
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "")
        
        let chartData = BarChartData(dataSet: chartDataSet)
        
        chartview.xAxis.valueFormatter = IndexAxisValueFormatter(values:xarray)
        
        chartview.xAxis.labelPosition = .bottom
        
        chartview.chartDescription?.enabled = false
        
        chartview.rightAxis.enabled = false
        
        chartview.legend.enabled = false
        
        chartview.data = chartData
        
    }

```

**Comment by seenoevo** [comment]
hmm I don't see anything wrong with that code...are you sure you configured the bar chart's frame correctly?

**Comment by martheli** [comment]
I just have a view on my storyboard with BarChartView class. Pics below:


<img width="259" alt="screen shot 2017-08-27 at 7 45 05 pm" src="https://user-images.githubusercontent.com/20176169/29755094-50f9516c-8b60-11e7-98df-2b4802964cf0.png">

<img width="673" alt="screen shot 2017-08-27 at 7 44 50 pm" src="https://user-images.githubusercontent.com/20176169/29755097-56bfc4c8-8b60-11e7-900a-a492b25f125c.png">

**Comment by kjakm** [comment]
I'm facing the same issue. It seems like the bars are starting just above where the chart description sits by default (although I have the description disabled).

**Comment by martheli** [comment]
Have you found a solution to bring the bars back down?

**Comment by kjakm** [comment]
@martheli Not yet unfortunately.

**Comment by martheli** [comment]
@kjakm Someone provided the answer to me. You have to use this:

```
chartview.rightAxis.axisMinimum = 0.0
        
chartview.leftAxis.axisMinimum = 0.0
```

**Comment by kjakm** [comment]
@martheli excellent, that works. Thank you.

**Comment by seenoevo** [comment]
@martheli sorry for the late reply

I didn't need to use `axisMinimum` at all. I just copied your exact code and ran that function, but I didn't get the floating bars.

However, I'm glad you got it working!
