### ISSUE TITLE
How to use custom view for labels of xAxis?

### ISSUE THREAD

**Issue by mohsenasm** [danielgindi/Charts#2755]
I want to create a lineChart like this:
![01-edited-2 dragged](https://user-images.githubusercontent.com/9164422/29805768-f3621b00-8ca0-11e7-8eb1-bfaf407ef3e8.png)
but the problem is labels of xAxis can only be 'strings' . How can I use a custom view for this labels? for example to showing ![a](https://user-images.githubusercontent.com/9164422/29806257-b118a0ae-8ca3-11e7-8e3e-a3ed0c0623c3.jpg).

**Comment by thierryH91200** [comment]
try


add in a file
```
import Foundation
import Charts

open class HourValueFormatter : NSObject, IAxisValueFormatter
{
    var dateFormatter : DateFormatter
    
    public override init() {
        self.dateFormatter = DateFormatter()
        self.dateFormatter.dateFormat = "HH:mm"
        dateFormatter.timeZone = NSTimeZone(abbreviation: "GMT+0:00") as TimeZone!
    }
    
    public func stringForValue(_ value: Double, axis: AxisBase?) -> String
    {
        let date2 = Date(timeIntervalSince1970 : (value ))
        let strDate = dateFormatter.string(from: date2)
        print(strDate)
        let strAMPM = strDate > "11:59" ? "PM" : "AM"
        return dateFormatter.string(from: date2) + "\n" + strAMPM
    }
}

```

and 
in your controller

`xAxis.valueFormatter       = HourValueFormatter()`

**Comment by mohsenasm** [comment]
@thierryH91200  thanks for fast replying

According to the design, `numbers` should be bigger than  `AM/PM` and with a single `String` which is the output of `stringForValue` that seems to be impossible.

**Comment by thierryH91000** [comment]
This is possible try

**Comment by liuxuan30** [comment]
If you wan to make different font size, then you have to change some stuff to do so. Like render numbers and AM/PM independently.
