### ISSUE TITLE
TableView does not scroll vertically after graph is rendered to cells

### ISSUE THREAD

**Issue by ikyh** [danielgindi/Charts#2757]
Hello..! Thank you for this wonderful and useful library.  I want to **plot live data** on  the graph.
 I have referred to the solution of this issue (https://github.com/danielgindi/Charts/issues/754)
 and have rendered graph to tableView.  
Problem is:
1. I can scroll the tableView vertically before `maxXRange` data of `open func 
    setVisibleXRange(minXRange: Double, maxXRange: Double)`  is set to the graphView . After the 
    max range is attended the graph starts scrolling automatically to the left side.  
2. If I try to scroll the tableView vertically downwards, the graph gets scrolled to the right 
    side(backwards) instead but the tableView does not scroll. 
3. Also the graph stops moving when I click on any other UI or while scrolling(scrolls when user 
    touches the padding spaces to scroll up or down).

 I have done this so far:

    class TableGraphViewCells: UITableViewCell, ChartViewDelegate {
      @IBOutlet weak var graphView: LineChartView!

      override func awakeFromNib() {
        super.awakeFromNib()
        graphView.delegate = self
        let graphData: LineChartDataSet = LineChartDataSet(values: [ChartDataEntry(x: Double(0), y: Double(0))], label: "")
        graphData.drawCirclesEnabled = false
        graphData.setColors(UIColor.cyan)
        graphData.mode = LineChartDataSet.Mode.cubicBezier
        graphData.lineWidth = 2
        graphData.drawVerticalHighlightIndicatorEnabled = false
        graphData.drawHorizontalHighlightIndicatorEnabled = false   
     
        self.graphView.data = LineChartData(dataSets: [graphData])
        let timer = Timer.scheduledTimer(timeInterval: 0.20, target: self, selector: #selector(updateCounter), userInfo: nil, repeats: true)
    }

    // add point
    var i = 0
    func updateCounter() {
        let degrees: Double = (Double(arc4random_uniform(2)) * 2 - 1) * Double(arc4random_uniform(4))
        self.graphView.data?.addEntry(ChartDataEntry(x: Double(i), y: (degrees)), dataSetIndex: 0)
        self.graphView.setVisibleXRange(minXRange: Double(CGFloat(1)), maxXRange: Double(CGFloat(50)))
        self.graphView.notifyDataSetChanged()
        self.graphView.moveViewToX(Double(CGFloat(i)))
        self.graphView.legend.enabled = false
        self.graphView.doubleTapToZoomEnabled = false
        i = i + 1
    }}
I have shown 10 graph cell rows in the table. Even though I have hidden the `legend`, it still  appears only for 6th row initially and after I scroll, legend disappears and graph starts plotting the points. It happens only for 6th row. For 5 visible rows on the screens it works fine, but when I scroll to see next 5 rows for 6th row this happens. `tableView.realodData()` does not work. Graph is not rendered to tableView. **here** (Image appears to be rotated)
![img_0061](https://user-images.githubusercontent.com/29946749/29816475-d3eec10c-8cd1-11e7-8d18-586e501551e6.JPG)

Also I don't want to see the values of graph plotted on it. I tried to fix this but couldn't
![3](https://user-images.githubusercontent.com/29946749/29817687-9a17bbaa-8cd6-11e7-9808-dfd2d8bd8766.png)

I want to plot **different graph** for **different cells** with **different colours**. 
What I get:
![1](https://user-images.githubusercontent.com/29946749/29816512-f652c6f8-8cd1-11e7-8624-3618777c6e15.png)

**Expected Output :**
![2](https://user-images.githubusercontent.com/29946749/29816603-54c2285a-8cd2-11e7-8b87-73b74d5b72d3.png)

Help or suggestions appreciated. Thanks :)

**Comment by liuxuan30** [comment]
that's because we disabled it. you can disable `dragEnabled`. Details are within `panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)`

**Comment by liuxuan30** [comment]
I just came across https://github.com/danielgindi/Charts/pull/2413/, you can try this
