### ISSUE TITLE
How to set the position of the values top on BarChartView? 

### ISSUE THREAD

**Issue by guanyanlin** [danielgindi/Charts#2759]
Today,our company has required me to change the position of the values top on BarChartView?And now I have no idea ,how to get it....

**Comment by thierryH91200** [comment]
in the file


<img width="314" alt="capture d ecran 2017-08-29 a 17 03 48" src="https://user-images.githubusercontent.com/6251463/29828172-3c44cc38-8cdc-11e7-88d0-cd20c891aaf3.png">


modify  the line 439

<img width="765" alt="capture d ecran 2017-08-29 a 17 04 06" src="https://user-images.githubusercontent.com/6251463/29828198-4e6ac994-8cdc-11e7-9cab-f368f9147f7f.png">

and in your controller

        chartView.drawValueAboveBarEnabled = true


<img width="938" alt="capture d ecran 2017-08-29 a 17 04 49" src="https://user-images.githubusercontent.com/6251463/29828235-66b130ec-8cdc-11e7-9268-8f1eade8018c.png">

**Comment by seenoevo** [comment]
@thierryH91200 nice job for pointing in the right direction

@guanyanlin you can also subclass BarChartRenderer and copy the function that contains the `posOffset` into your subclass and override it there, that way you won't modify the original source code and any future updates in Charts won't wipe out your modifications.

**Comment by liuxuan30** [comment]
great people are helping :)
