### ISSUE TITLE
chartValueSelected not getting value from Max Value

### ISSUE THREAD

**Issue by 47BulletProof** [danielgindi/Charts#2762]
I really tried alot for getting the value of the value selected but I am not getting the value from the max value and after that no entry is returning the label value. But the entries before the max bar entry is returning the value? Here is the code.

`

      func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight){
        //print("clickdsL",entry)

        let index = Int(entry.x)

        print(index)

        let selectedBarText = chartView.xAxis.getFormattedLabel(index)

        print("click:", chartView.xAxis.getFormattedLabel(index))

        lblChartLabel.frame = CGRect(x: 0, y: (chartView.frame.maxY - (chartView.frame.height / 2)), width: chartView.frame.maxX, height: 40)

        lblChartLabel.textAlignment = .center

        view.addSubview(lblChartLabel)

        lblChartLabel.text = selectedBarText

    }
`

**Comment by liuxuan30** [comment]
you need to debug `drawHighlighted` to make sure the max value is being chosen first.

**Comment by shuaigerui** [comment]
I have question your Highlight Line is tap show ? or long press show ?
