### ISSUE TITLE
Changing x-label formats from one line to word-wrapped is awkward

### ISSUE THREAD

**Issue by lesiva** [danielgindi/Charts#2763]
Would appreciate a workaround for this one. Is there any way to force the labels to redraw?

Repro:
1. change line chart labels from one-line to word-wrapped multi-line
2. notice that only one line of text is shown
3. drag graph slightly, and then back to the edge
4. release finger to prompt re-drawing of axis

Explanation of this gif: I used an external button to change the domain so that we zoomed into the last 12 months. The labels changed to months instead of years, and the new labels wrap to a second line. I have to drag the graph and then lift my finger before it updates.

I have set `graph.xAxis.wordWrapEnabled = false` for the zoomed out graph, and I change it to `true` when I change the text for the labels (otherwise the years are drawn in the zoomed-out graph with one letter per line).

![labelspop](https://user-images.githubusercontent.com/13716081/29942814-ffa832f8-8e4b-11e7-8fcd-2257e217909e.gif)

**Comment by lesiva** [comment]
Workaround: `graph.notifyDataSetChanged()`

**Comment by lesiva** [comment]
Leaving this open to notify the project, feel free to close if the workaround is considered enough.

**Comment by liuxuan30** [comment]
that's correct one if you updated your data sets
