### ISSUE TITLE
I want to change ValueFormat of BarChartDataSet. I can't change it.

### ISSUE THREAD

**Issue by patelmonika006** [danielgindi/Charts#2764]
**I want to set BLUE Box value Format same as RED Box. But I can't change Value format of BarChartDataSet**

![simulator screen shot 01-sep-2017 1 26 11 am](https://user-images.githubusercontent.com/10842489/29944362-e4a9e0ae-8eba-11e7-9ec8-819f2a191b3b.png)

- (void)setDataCount:(int)count range:(double)range ValuesArr:(NSMutableArray*)valArr
{
    BarChartDataSet *set1 = nil;
    if (_chartView.data.dataSetCount > 0)
    {
        set1 = (BarChartDataSet *)_chartView.data.dataSets[0];
        set1.values = valArr;
        [_chartView.data notifyDataChanged];
        [_chartView notifyDataSetChanged];
    }
    else
    {
        set1 = [[BarChartDataSet alloc] initWithValues:ValuesArr label:@"2014"];
        [set1 setColors:@[Blue_Color,Yellow_Color,Red_Color]];
         _chartView.barData.dataSets=@[[UIColor clearColor]];
        set1.drawIconsEnabled = NO;
         NSMutableArray *dataSets = [[NSMutableArray alloc] init];
        [dataSets addObject:set1];
        BarChartData *data = [[BarChartData alloc] initWithDataSets:dataSets];
        [data setValueFont:[UIFont fontWithName:Font_Regular size:(isIphone) ? 10.f : 22.0f]];
        data.barWidth = 0.7;
         _chartView.data = data;
  }
    
    [super handleOption:@"animateY" forChartView:_chartView];

}](url)

**Comment by seenoevo** [comment]
If you want to add a comma, you can do something like this, but it's written in Swift, so you have to convert it to Objective-C:

```
let decimalCostValue = NumberFormatter()
decimalCostValue.numberStyle = .decimal
         
chartData.setValueFormatter( DefaultValueFormatter(formatter: decimalCostValue) )
```

**Comment by patelmonika006** [comment]
@seenoevo 
        comma_fmt = [[NSNumberFormatter alloc] init];
        [comma_fmt setNumberStyle:NSNumberFormatterDecimalStyle]; // to get commas (or locale equivalent)
        [comma_fmt setMaximumFractionDigits:0]; // to avoid any decimal

-------- please give some hint what value I have to passed in id<IChartValueFormatter> _Nullable
         [data setValueFormatter:(id<IChartValueFormatter> _Nullable)];

**Comment by seenoevo** [comment]
search for `ChartDefaultValueFormatter` in demo and you can see other graphs using it, then apply it to your own code

**Comment by patelmonika006** [comment]
@seenoevo Thanks I fonund the solution

**Comment by seenoevo** [comment]
@patelmonika006 great!....please close if resolved

**Comment by ramohanreddy** [comment]
Hi @seenoevo and @IAmMonika 
How to show this value 2040000 to $2.04M like this

Thanks&Regards
Ramohan Reddy
