### ISSUE TITLE
Cannot rescale Y-axis even if changing axisMinimum and axisMaximum

### ISSUE THREAD

**Issue by tomkowz** [danielgindi/Charts#2766]
Hello,

I am trying to convert the code to the newest version. My current goal is to scale Y-axis, but it look like the framework is ignoring my settings.

Here is how it look like right now without setting `rightAxis.axisMinimum` and `rightAxis.axisMaximum`:
![screen shot 2017-09-01 at 14 33 40](https://user-images.githubusercontent.com/2303177/29988607-35f246be-8f23-11e7-908c-90798f754290.png)

When I set it to some custom values of min and max like 0 to 300 it should scale it so there is a lot of blank space on the top and some blank space on the bottom of the chart, but... these values are seems to be ignored completely.

![screen shot 2017-09-01 at 14 34 21](https://user-images.githubusercontent.com/2303177/29988632-61703d32-8f23-11e7-91bb-32b0629c8189.png)

Here is a code snippet with right axis configuration:

```obj-c
    chartView.rightAxis.axisLineColor = [UIColor clearColor];
    chartView.rightAxis.labelFont = [UIFont mavenProLight300WithFontSize:12];
    chartView.rightAxis.labelTextColor = [UIColor whiteColor];
    chartView.rightAxis.gridColor = [UIColor colorWithWhite:1 alpha:0.3];

    chartView.rightAxis.axisMinimum = minValue;
    chartView.rightAxis.axisMaximum = maxValue;

    chartView.rightAxis.labelCount = 3;
```

Could you please guide me what's wrong in here?
Thank you in advance.

**Comment by liuxuan30** [comment]
Don't use chartView.rightAxis.labelCount = 3; use `open func setLabelCount(_ count: Int, force: Bool)` instead.

second you need to call `setNeedsDisplay` to trigger a redraw or call `notifyDataSetsChanged`

**Comment by tomkowz** [comment]
@liuxuan30 I just set axisMinimum = 0, axisMaximum = 300, as before, added following calls after I set it:
```obj-c
    [chartView.rightAxis setLabelCount:3];
    [chartView notifyDataSetChanged];
    [chartView setNeedsDisplay];
```

and nothing happen, no changes, it just looks the same with 0-300 on a right axis.

**Comment by liuxuan30** [comment]
did you specify `axisDependency` for your data sets?

**Comment by tomkowz** [comment]
@liuxuan30 that was it. Thank you. I have to set it to Right. Never heard about this property before.
