### ISSUE TITLE
how to use HorizontalBarChart with decimal number as xAxis 

### ISSUE THREAD

**Issue by firetheworld** [danielgindi/Charts#2768]
I am using HorizontalBarChart with xAxis show price which is decimal,  it show bars overlap with each other.
![image](https://user-images.githubusercontent.com/7941843/29969563-44e9b514-8f53-11e7-8a6e-85086ac80ee1.png)

how can i fix this issue?

**Comment by liuxuan30** [comment]
check out charts demo first. Seems you don't use it correctly.
