### ISSUE TITLE
How can I get current viewport shown x range and scale value

### ISSUE THREAD

**Issue by firetheworld** [danielgindi/Charts#2770]
Hi, I am use combinedchart and bar chart to show candle stick and volumn, I want there two charts zoomin or zoomout sync and show the same range x when pinch gesture, How can I get current viewport shown x range and scale value?

**Comment by liuxuan30** [comment]
there are people used to ask similar question, you can search.
Commonly just look at ViewPortHandler functions and ChartTransformer functions
