### ISSUE TITLE
X Values Hidden On Bar Graph

### ISSUE THREAD

**Issue by martheli** [danielgindi/Charts#2774]
I assume the values are hidden because of space issues but there looks to be enough space. Is there a way to force the x values to show up?

I have the following in my code:

```
chartview.xAxis.granularityEnabled = true
chartview.rightAxis.axisMinimum = 0.0
chartview.leftAxis.axisMinimum = 0.0
```
But it still hides the values.

<img width="313" alt="screen shot 2017-09-06 at 7 47 06 pm" src="https://user-images.githubusercontent.com/20176169/30139511-4f2808a4-933c-11e7-96d9-48b8acef1a4a.png">

**Comment by seenoevo** [comment]
you need to set the xAxis `labelCount`, i.e.:

`barChartView.xAxis.setLabelCount(array.count, force: false)`

problem solved! :)

**Comment by martheli** [comment]
@seenoevo worked like a charm :) Thanks!
