### ISSUE TITLE
How to break line the legends ? 

### ISSUE THREAD

**Issue by kyokid** [danielgindi/Charts#2775]
Hi everyone,
Is the any way to break line the legend ? I mean when I have 3 or more legends, I set `orientation = vertical` and what I have is:

[label legend 1]
[label legend 2]
[label legend 3]

But what I want is:

[label legend 1]       [label legend 3]
[label legend 2]

It organize the Legend with column or row. I read the document but can't find anything to do that :(

**Comment by seenoevo** [comment]
refer here: #2625
