### ISSUE TITLE
Cannot subscript a value of type '[String : AnyObject]' with an index of type 'NSAttributedStringKey'

### ISSUE THREAD

**Issue by bhumit1709** [danielgindi/Charts#2777]
I am getting such errors when I convert to current swift version in Xcode 9 beta

Cannot subscript a value of type '[String : AnyObject]' with an index of type 'NSAttributedStringKey'

ChartViewBase.swift

  attrs[NSAttributedStringKey.font] = description.font
   attrs[NSAttributedStringKey.foregroundColor] = description.textColor

**Comment by mmlmml1** [comment]
I found the same issue, I think that's because the new swift 4 gramma. I changed the swift version from 4.0 to 3.2 in the build settings page, and that solves my problem

**Comment by jjatie** [comment]
Charts is not currently updated for Xcode 9 and Swift 4. This issue has already been resolved in the Swift 4 branch if you would like to see the solution.

**Comment by liuxuan30** [comment]
yes. Use swift 4 branch or migrate yourself. We are waiting for Xcode 9 final release to bump our code base.

**Comment by youresolutions** [comment]
I am new here, Can you please show when I can find swift 4 branch?

**Comment by liuxuan30** [comment]
it's merged

**Comment by mmuldoon1** [comment]
I just upgraded to XCode 9 and Swift 4.  Charts won't build.
I'm getting the same error:

> Cannot subscript a value of type '[String : AnyObject]' with an index of type 'NSAttributedStringKey'
In ChartViewBase.swift.

I unistalled the Pod and reinstalled to insure I had the most up to date branch.

Please advise.
Thanks!

**Comment by kiraninfogird** [comment]
Cannot subscript a value of type 'Dictionary<String, AnyObject?>' with an index of type 'Int'

I am getting an error when handling json, Please help me to solve it?

                    if  let mObject = (data as? [String : AnyObject]){
                        if let dictionaryArray = data as? Dictionary<String, AnyObject?> {
                            if dictionaryArray.count > 0 {
                                for i in 0..<dictionaryArray.count{
                                    let Object = dictionaryArray[i]
                                    if let empAllotedLeaves = Object["empAllotedLeaves"] as? Int{
                                        print("empAllotedLeaves: \(empAllotedLeaves)")
                                    }
                                    if let empGetedLeave = Object["empGetedLeave"] as? Int{
                                        print("empGetedLeave: \(empGetedLeave)")
                                    }
                                }
                            }
                        }
                    }

**Comment by jjatie** [comment]
@kiraninfogird This is not the appropriate forum for this.

**Comment by kiraninfogird** [comment]
Thanks...!
