### ISSUE TITLE
App crashes while using Charts swift library in Objective C Project

### ISSUE THREAD

**Issue by aventador-dawn** [danielgindi/Charts#2778]
i am trying to add Charts library to my Objective C project.

demo i referred https://github.com/dmsurti/ChartsObjCSample/tree/master/ChartsObjCSample

Project i created is SingleView project

i installed library using Cocoapods 

       use_frameworks!
       pod 'Charts'

I added a swift file named `File.swift` as **Bridging header**

i set following option in build settings

[![enter image description here][1]][1]

Then i tried to run sample code in ViewController.m provided below 

        //ViewController.m
    ....
    #import "chart4-Swift.h" // projectname-Swift.h
    @import Charts;
    
    BarChartView* barChartView = (BarChartView*)self.view;
    
    NSMutableArray* dataEntries = [[NSMutableArray alloc] init];
    for(int i = 0; i < 100; i++) {
        BarChartDataEntry* dataEntry = [[BarChartDataEntry alloc] initWithX:5.0 * arc4random_uniform(12) y:100.0];
        [dataEntries addObject:dataEntry];
    }
    
    BarChartDataSet* dataSet = [[BarChartDataSet alloc] initWithValues:dataEntries label:@"Visitor Count"];
    
    BarChartData* barChartData = [[BarChartData alloc] initWithDataSet:dataSet];
    barChartView.data = barChartData;

but App crashes with following error **-[UIView setData:]: unrecognized selector sent to instance, Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setData:]: unrecognized selector sent to instance** 

 

    chart4[4975:74168] -[UIView setData:]: unrecognized selector sent to instance 0x7f9f02600790
     chart4[4975:74168] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setData:]: unrecognized selector sent to instance 0x7f9f02600790'

  [1]: https://i.stack.imgur.com/dLFSj.jpg

**Comment by ralbertini** [comment]
After a Headache with this problem, i created a UIView subclass in swift with chartview inside, and problem was "solved".
