### ISSUE TITLE
Zero Value is under BarChart

### ISSUE THREAD

**Issue by Bingo25** [danielgindi/Charts#2779]
Hi I apologize if the problem has already been solved, but I actually haven't found the solution for this! Could someone help with this? I have the values that have to be topInside the barChart! To obtain this I use  barChartView.drawValueAboveBarEnabled = false

If I try to set charData.axisDependancy = .right , I am getting extra space at the bottom, which also cannot be solved by setting barChar.leftAxis.spaceBottom to zero

Thank you in advance
![zokhnvd-mxg](https://user-images.githubusercontent.com/31818014/30247879-bc00808c-9625-11e7-9609-37e9446f8774.jpg)

**Comment by liuxuan30** [comment]
>If I try to set charData.axisDependancy = .right , I am getting extra space at the bottom, which also cannot be solved by setting barChar.leftAxis.spaceBottom to zero

What space are you saying? How about your left axis look? BTW, not sure if it's your typo, but `setting barChar.leftAxis.spaceBottom to zero` will not change rightAxis at all... Try set `rightAxis.axisMinimum = 0` as well.
