### ISSUE TITLE
No type or protocol named 'IChartAxisValueFormatter'

### ISSUE THREAD

**Issue by DangOnGitHub** [danielgindi/Charts#2780]
My project compiled fine but when I create a class conformed to protocol `IAxisValueFormatter`, I get that error in the XCode-generated header "Project-Swift.h". The only way I can make it compiled is manually `#import "Charts-Swift.h"` in the generated header. I know this is stupid since that file is generated automatically :(
I'm using XCode 8.3.3 and Cocoapods 1.3.1. Do I need to follow Usage note if I install by Cocoapods?
<img width="1065" alt="screen shot 2017-09-11 at 5 28 12 pm" src="https://user-images.githubusercontent.com/7124022/30270427-baef7896-9716-11e7-8797-613022e16d40.png">

**Comment by liuxuan30** [comment]
Why not import the chart header in your code file? You don't need to touch generated header. no matter you use pods or others, this is about swift and objc by Apple, so follow apple's guide. I think ChartsDemo already give enough information.

**Comment by DangOnGitHub** [comment]
In the Swift class `ElevationXAxisValueFormatter`, I did `import Charts` and it can recognize the protocol (I can even Cmd click on the protocol). I only use this class in another Swift class but when compile, the generated header "Project-Swift.h" in one ObjC file gives this error. My project is mixed Swift & ObjC.

**Comment by liuxuan30** [comment]
Would you just take a look at ChartsDemo? It's mixed as well. And check your build settings about swift. Especially your project name ("Project-Swift.h")

**Comment by macro-dadt** [comment]
@DangOnGitHub make sure that you didn't mix Swift Language Version in Your Project and Charts target Build Settings. They should be the same Swift Language Version

**Comment by macro-dadt** [comment]
I face the same issue. I try to make a new project and install Charts by pod. Everything work great until a make Bridging-Header. Im using xcode 9.2, swift language version 3.2 for project level and 4.0 for Charts target.

**Comment by macro-dadt** [comment]
@liuxuan30 I face the same issue. i figure out that this issue happens when i try to add `#include "MyProjectName-Swift.h"`
Im using xcode 9.2, swift 3.2 for project level and 4.0 for Charts target

**Comment by gongdandan** [comment]
is this issue fixed?

**Comment by iTSangar** [comment]
same here...
