### ISSUE TITLE
Graphs gets cut from both ends

### ISSUE THREAD

**Issue by poojaagarwal1331** [danielgindi/Charts#2785]
Like this:- http://prntscr.com/gknml4

But by changing these two lines will resolve the issue but for that, I have to unlock the pods as accessing and changing the variable from my view doesn't reflect the required change.

> Change in Pod:- 

/// Extra spacing for `axisMinimum` to be added to automatically calculated `axisMinimum`
    `open var spaceMin: Double = 0.45`
    
    /// Extra spacing for `axisMaximum` to be added to automatically calculated `axisMaximum`
`    open var spaceMax: Double = 0.45
`in AxisBase.swift file.

> Changing from view:-

`combineChartView.xAxis.axisMinimum = combineChartView.xAxis.axisMinimum - 0.45     combineChartView.xAxis.axisMaximum = combineChartView.xAxis.axisMaximum + 0.45`

Thanks in advance.

**Comment by tuanla6242** [comment]
Thank you!

**Comment by liuxuan30** [comment]
not sure what's this for.

**Comment by poojaagarwal1331** [comment]
It's just I want to know whether any solutions apart from this as I need to change every time from pods after pod updations.

**Comment by liuxuan30** [comment]
there are ways like subclassing.

**Comment by poojaagarwal1331** [comment]
I did that but its not working, although took the default value only.
Any other help would be appreciated.

**Comment by liuxuan30** [comment]
both `axisMinimum` and `spaceMin` are open vars which have the highest access level, you can do whatever you like in your sub classes from anywhere. If you still see it's default value, you shall set it after the super class finish.
