### ISSUE TITLE
Charts “3.0.2” cannot find "BalloonMarker" 

### ISSUE THREAD

**Issue by LeeLom** [danielgindi/Charts#2786]
hello, I want to declare a marker like below:

`       
    let marker = BalloonMarker(color: UIColor.customBlue(), font: UIFont.systemFont(ofSize: 12.0), 
    insets: UIEdgeInsetsMake(top: 8, left: 8, bottom: 20, right: 8))
`
but Xcode remind error, "Use of unresolved idtentifier 'BallonMarker'"
and I cannot find BallonMarker.swift either.

I install the Charts use pod. like "pod 'Charts', '~> 3.0.2'"

**Comment by seenoevo** [comment]
I don't use pods, I drag everything manually into my project.

However, you might want to drag BallonMarker.swift from Classes -> Components folder directly into your project and see if that helps.

**Comment by liuxuan30** [comment]
it's in ChartsDemo.

**Comment by umairsuraj** [comment]
It's in ChartsDemo. But not in "pod 'Charts'. Can you please include it there. Or any separate POD for components? Thanks.
