### ISSUE TITLE
How can I control the number of decimals?

### ISSUE THREAD

**Issue by qixizhu** [danielgindi/Charts#2787]
怎样才能控制图表中数字的小数位数；在柱形图中，当数据为0时，怎样隐藏不显示 0.0。求作者大大告知，非常感谢。

**Comment by seenoevo** [comment]
can you write in English?

Maybe I can help if I understand what you're saying?

@liuxuan30?

**Comment by liuxuan30** [comment]
We should encourage writing in English on a global website @qixizhu if you want in time hlep.

He's asking: how to control number's decimals; the answer is simple: use valueFormatter. But thank you for your helping attitude! @seenoevo

**Comment by qixizhu** [comment]
Thank you very much for your answer. I will use English next time.

**Comment by shilpashreeamt** [comment]
how to use value formatter for pie-charts?
