### ISSUE TITLE
Charts.framework: No such file or directory

### ISSUE THREAD

**Issue by bilawal-liaqat** [danielgindi/Charts#2789]
App is running smoothly on Simulator. 
Getting error when Archiving app.
![screen shot 2017-09-15 at 4 15 55 pm](https://user-images.githubusercontent.com/4446705/30480053-52a0f3fa-9a31-11e7-9c60-63f73c91e51e.png)

Note : already followed that (https://github.com/danielgindi/Charts/issues/1548) but its not work.

**Comment by liuxuan30** [comment]
check your build phases and build settings, if you put them under frameworks correctly. It's clearly missing on your side. Simulator can be tricky, as the derived data can have "module cache" so your simulator is working.

**Comment by EMakadiya** [comment]
Hi @liuxuan30 

I am having save issue while archive project.
It says module not found.
I am using pod to install this library.
Project is running fine in simulator and device.

Please help me.

Thanks

**Comment by liuxuan30** [comment]
check your build setting and build scripts, did they put Charts under correct place. read README as well
