### ISSUE TITLE
Chart Grid Lines Don't Always Draw

### ISSUE THREAD

**Issue by martheli** [danielgindi/Charts#2791]
I have two graphs that are set up identically but if you notice the left chart has a border around the entire chart but the right chart doesn't have the top border line (grid line). How do I get the top border to appear on the right chart?

![screen shot 2017-09-15 at 2 01 51 pm](https://user-images.githubusercontent.com/20176169/30496767-72d15006-9a1e-11e7-95c0-a4ab2ef2e7d0.png)

**Comment by liuxuan30** [comment]
becuase the label is different. Set axis.axisMaximum to force them have same max value.

**Comment by martheli** [comment]
This is the function that I use to set up the charts:

```
func setChart(chartview: BarChartView, xarray: [String], yarray: [Double], count: Int){
        
       
        var dataEntries: [BarChartDataEntry] = []
        
        
        for i in 0..<xarray.count {
            
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(yarray[i]))
            
            dataEntries.append(dataEntry)
        }
        
        
        let chartDataSet = BarChartDataSet(values: dataEntries, label: "")
        
        chartDataSet.drawValuesEnabled = true
        
        
        let chartData = BarChartData(dataSet: chartDataSet)
        
        let format = NumberFormatter()
        
        format.numberStyle = .none
        
        let formatter = DefaultValueFormatter(formatter: format)
        
        chartData.setValueFormatter(formatter)
        
        chartview.xAxis.valueFormatter = IndexAxisValueFormatter(values:xarray)
        
        chartview.xAxis.granularityEnabled = true
        
        chartview.xAxis.labelPosition = .bottom
        
        chartview.chartDescription?.enabled = false
        
        chartview.rightAxis.axisMinimum = 0.0
        
        chartview.leftAxis.axisMinimum = 0.0
        
        
        chartview.legend.enabled = false
        
        chartview.xAxis.drawGridLinesEnabled = false
        
        chartview.rightAxis.drawLabelsEnabled = false
        
        chartview.rightAxis.drawGridLinesEnabled = true
        
        chartview.xAxis.setLabelCount(count, force: false)
        
        chartview.data = chartData

        
    }

```

I tried adding the following and it made the labels on top not visible:

`chartview.leftAxis.axisMaximum = (yarray.max()!)`

**Comment by liuxuan30** [comment]
after you set `chartview.leftAxis.axisMaximum = (yarray.max()!)`, call `notifyDataSetChanged()` or put `chartview.data = chartData` at last line. Changing anything that impact the axis range requires recalcuation.

**Comment by martheli** [comment]
![screen shot 2017-09-28 at 9 26 29 am](https://user-images.githubusercontent.com/20176169/30969026-2d981b62-a42f-11e7-9e92-6c6604c3a243.png)

I made the change but now the labels are going off the top of the graph and it looks like there are additional horizontal bar lines near the 40 and 60 levels.

**Comment by liuxuan30** [comment]
did you add any limit line or anything?  axisMaximum just impact the axis range, it will not draw any lines for you.

**Comment by JCMcLovin** [comment]
@martheli I don't know if you were able to fix this but I had a similar problem with multiple y-axis gridlines. It happened to me because I did not disable the right axis properties:
