### ISSUE TITLE
How to change the entrylabel(i.e, 90%) color in PieChart

### ISSUE THREAD

**Issue by mob-rockstar** [danielgindi/Charts#2794]
I tried to change the color of percentage label.
I think the default color is white.
So I have used following code(Swift 3.1) to change the color.
chartView.entryLabelColor = UIColor.black

but the color didn't change as black color.
Please let me know the solutions

**Comment by liuxuan30** [comment]
```swift
                let valueTextColor = dataSet.valueTextColorAt(j)
                let entryLabelColor = dataSet.entryLabelColor
```
you should use valueTextColor
