### ISSUE TITLE
how tomake leftAxis.inverted and LineChartDataSet.fillColor not inverted

### ISSUE THREAD

**Issue by MrCoderMSH** [danielgindi/Charts#2798]
this picture is normal:
![normal](https://user-images.githubusercontent.com/13232963/30580700-105ea2e0-9d50-11e7-99fe-c5d9e582262e.png)

and this picture is make chartView.leftAxis.inverted = true
![inverted](https://user-images.githubusercontent.com/13232963/30580723-22f21950-9d50-11e7-8bbe-b087ec9e58cd.png)

we can see that left.inverted make the fillColor also inverted, I want the fillColor not inverted. how to make that style?

**Comment by liuxuan30** [comment]
This is the correct implementation so far. If you want the opposite filling, you have to override the filling method yourself.

**Comment by MrCoderMSH** [comment]
ok, I want to know how to override the filling method by myself. which class or which prootocal. thank you

**Comment by liuxuan30** [comment]
it's not that easy. You have to understand how the line chart renderer works. But basically, start from `drawLinear()` which contains the filling func.
