### ISSUE TITLE
How to get y-axis values "Int" to "Double"

### ISSUE THREAD

**Issue by Sreekanth1234** [danielgindi/Charts#2799]
<img width="465" alt="screen shot 2017-09-19 at 8 12 55 pm" src="https://user-images.githubusercontent.com/23524697/30599449-1fe31dc0-9d7a-11e7-8ff8-7b3d66f66b26.png">

Here is code :-
 
    func setChart(_ lineChartView: LineChartView, dataPoints: [String], values: [Double]) {
        
        let graphDataList = GraphDataWeekly.getGraphDataList()
        if graphDataList?.count == 0 {
            return
        }
        
        var count = 0
        var dataEntries: [ChartDataEntry] = []
        var xAxisDataPoints = [Any]()
        
        for graphData in graphDataList! {
            let dataEntry = ChartDataEntry(x: Double(count), y: graphData.kwh! )
            dataEntries.append(dataEntry)
            xAxisDataPoints.append(DataPointFormatter.javaUtilDateFromDateString(graphData.createdOn!))
            count += 1
        }

But y-axis data coming in console in double value,

<img width="941" alt="screen shot 2017-09-19 at 8 34 45 pm" src="https://user-images.githubusercontent.com/23524697/30599521-617e467e-9d7a-11e7-8ce3-dba50d25fa3c.png">

Then finally, how to get y-axis values "int" to "Double"  ?

**Comment by liuxuan30** [comment]
It's Double(Int)

**Comment by Sreekanth1234** [comment]
Ok thanks for the suggestion ......I'll learn.... But, tell me code or logic for regards to my issue...
