### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by franigam** [danielgindi/Charts#2801]
Hi,

Hi, I have 33 errors for the module Charts, is it going to update this project to Swift 4?

Thanks

Check dependencies:

"The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and then disable inference by changing the "Swift 3 @objc Inference" build setting to "Default" for the "Charts" target."

**Comment by mkrivacek** [comment]
Hi, 

also there is compilation error:
**Cannot convert value of type '[String : AnyObject]?' to expected argument type '[NSAttributedStringKey : Any]?'**

for example in ChartUtils.swift, line 132... 136... 141... etc. Total 14 issues.

Thanks for update to Swift 4 :)

**Comment by thierryH91200** [comment]
please for "The use of Swift 3 @objc inference ....."

this is very simple.......

 https://makeapppie.com/2017/09/18/this-old-app-update-to-xcode-9/

**Comment by nicoara** [comment]
I have multiple errors as well.
One of them is "ambigous reference to member 'data' " in ChartDataEntryBase:
        if (object! as AnyObject).data !== data && !((object! as AnyObject).data??.isEqual(self.data))!

**Comment by nicoara** [comment]
When will there be a version of Charts for Swift 4? 

I just added a new pod to my project and doing pod install triggered the Xcode Swift compiler to interpret the Charts library as Swift 4 and not Swift 3, which it did not do before. So I expect many people to have this problem on Xcode 9 when adding new pods. I have a few errors, one of which I posted, that I would prefer not to handle myself. Thanks

**Comment by h-soran** [comment]
Hi Daniel
Thank you all for the great library. 
I am sure you are aware of the lovely Swift 4 issues (18 to be precise) popped out recently. No doubt you are on the case. Just wondering when will we get the updates for your awesome library.
Thanks in advance
![chartsissues](https://user-images.githubusercontent.com/30659115/30646681-b08b88fc-9e11-11e7-963a-c7f81a88cb7d.png)

**Comment by Spiderbezno** [comment]
I have the same problems

**Comment by bardonadam** [comment]
Guys, we get it, no need to bump this issue every 10 minutes...

**Comment by Visakeswaran** [comment]
Check out this link, it clearly explains how to get rid of the error
https://youtu.be/T7TyB-R_rOk

**Comment by liuxuan30** [comment]
swift 4 #2507  has been merged into master. closing.
