### ISSUE TITLE
cocoaPod can not install branch of swift4

### ISSUE THREAD

**Issue by Mosaics** [danielgindi/Charts#2802]

**Comment by GuiAfonso** [comment]
For me `pod 'Charts'` was installing the 3.0.2 version. So used   `pod 'Charts', '~> 3.0.3’` and worked.

**Comment by Mosaics** [comment]
Maybe it was a network problem. I installed it for more than half an hour. Like this:
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'swift4'

**Comment by liuxuan30** [comment]
master is now swift 4.

**Comment by Mosaics** [comment]
@liuxuan30 tks
