### ISSUE TITLE
module 'Charts' not found when dray it into target

### ISSUE THREAD

**Issue by shimxMoyi** [danielgindi/Charts#2803]
my target have cocoapods already, i dray Charts floder into my target，and import Charts in Bridging-Header.h，but it show module 'Charts' not found。
![default](https://user-images.githubusercontent.com/26248100/30631919-b8886410-9e18-11e7-800e-30835c974fa4.png)

**Comment by thierryH91200** [comment]
In order to correctly compile:

Drag the Charts.xcodeproj to your project
Go to your target's settings, hit the "+" under the "Embedded Binaries" section, and select the Charts.framework
@import Charts

**Comment by shimxMoyi** [comment]
![default](https://user-images.githubusercontent.com/26248100/30637331-98fefaf2-9e2a-11e7-841a-764dfa41d912.png)
![default](https://user-images.githubusercontent.com/26248100/30637339-a1e1e4c2-9e2a-11e7-97ef-4d83e413ac21.png)
![default](https://user-images.githubusercontent.com/26248100/30637347-a8191400-9e2a-11e7-8a59-ea21da160ad0.png)
i m in correct step。but，when i install a pod in project，then，its fail 
![default](https://user-images.githubusercontent.com/26248100/30637443-eb6ec718-9e2a-11e7-9980-a06570a0dbcd.png)

**Comment by liuxuan30** [comment]
check your pod configuration and where's the framework.
