### ISSUE TITLE
Version 3.0.4 doesn't appear via Cocoapods

### ISSUE THREAD

**Issue by Spiderbezno** [danielgindi/Charts#2807]
I refresh the repo of CocoaPods but the last version is 3.0.2

**Comment by liuxuan30** [comment]
it's merged. #2802

**Comment by Spiderbezno** [comment]
COnsole messge of POds:

[!] Unable to satisfy the following requirements:

- `Charts (~> 3.0.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Charts (~> 3.0.4)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

And I relod de pods with pod repo update, and try instal again with this configuration pod 'Charts'

but the resume of installation is that

Analyzing dependencies
Downloading dependencies
Using Charts (3.0.2)

**Comment by Spiderbezno** [comment]
Charts 3.0.3 can find but not find 3.0.4

**Comment by Spiderbezno** [comment]
IN the web of Cocoapods you can see that the last version is 3.0.3

http://cocoapods.org/pods/charts

**Comment by franigam** [comment]
I have the same issue

"[!] Unable to satisfy the following requirements:

- `Charts (~> 3.0.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Charts (~> 3.0.4)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default."

**Comment by Spiderbezno** [comment]
PLease some date when this work again, I need to compile a new version of my app thx

**Comment by RyanHop3** [comment]
Same issue here.

**Comment by liuxuan30** [comment]
wait for update dup to #2814
