### ISSUE TITLE
I have the version 3.0.4 but when compile project I has an error

### ISSUE THREAD

**Issue by Spiderbezno** [danielgindi/Charts#2809]
Module compiled with Swift 3.1 cannot be imported in Swift 4.0: /Users/Jorge1Old/Library/Developer/Xcode/DerivedData/myAndorraTelecom-codtmudrxqhapldhakapfamqpywy/Build/Products/Debug-iphonesimulator/Charts.framework/Modules/Charts.swiftmodule/x86_64.swiftmodule

**Comment by Spiderbezno** [comment]
IF someone else has the problem I found it the solution:

1. CMD+SHIFT+K to clean the build
2. Restart Xcode 9 <-- make sure you do this step, that's critical. `

**Comment by liuxuan30** [comment]
yeah you need rebuild.

**Comment by jcmartinac** [comment]
Not working in my project. I have just update pods and charts 3.04 throws 51 swift compiler errors. Any help? please
<img width="358" alt="captura de pantalla 2017-10-18 a las 17 43 02" src="https://user-images.githubusercontent.com/6225136/31728261-15ebf706-b42c-11e7-9fa6-35d84e55565b.png">
<img width="305" alt="captura de pantalla 2017-10-18 a las 17 44 10" src="https://user-images.githubusercontent.com/6225136/31728264-16523d72-b42c-11e7-81e4-8631fba29182.png">

**Comment by liuxuan30** [comment]
what's your swift compiler version in your build settings?

**Comment by jcmartinac** [comment]
It was set to 3.2... change it to 4.0 solve the issues. Thanks!
