### ISSUE TITLE
Still getting Version 3.0.3 from Cocapods

### ISSUE THREAD

**Issue by osianSmith** [danielgindi/Charts#2811]
Hey, Im trying to update the pods in my pod file and I still keep keep getting version 3.0.3. in my pod file charts is down like:
pod 'Charts' 

any way for me to update this or do I need to wait for the servers to update or something (I'm not super experienced with pods)

Thanks

Osian

**Comment by RamblinWreck77** [comment]
@osianSmith  I ran into this issue as well, they have to push it to cocoapods.

You can see the current version here:

https://cocoapods.org/?q=charts

**Comment by liuxuan30** [comment]
yeah I am not in the owner list so my push failed at last. Need they add me in or push, stay tuned. But you can easily point your pod to the specific commit. like in #2814
