### ISSUE TITLE
Cocoapod 3.0.4

### ISSUE THREAD

**Issue by panleya** [danielgindi/Charts#2814]
pod update pulls down version 3.0.3, not 3.0.4.  I'm moved over now to swift 4 and Xcode 9.  What do I need to do to pull in the newest swift 4 compatible version using cocoa pods?

**Comment by WillMays1** [comment]
need to know this too

**Comment by RyanHop3** [comment]
same here

**Comment by WillMays1** [comment]
The developer hasn't pushed 3.0.4 to Cocoapods yet.
See here:

https://cocoapods.org/?q=charts

**Comment by WillMays1** [comment]
Mine still pulls 3.0.2

**Comment by WillMays1** [comment]
UPDATE: Cocoapods still has 3.0.2 as the latest version

To get 3.0.4 change your podfile from:

pod 'Charts'

to

pod 'Charts', :git => 'https://github.com/danielgindi/Charts/', commit: '54171609c2f7d987a46eab60eb0422318d08d266'

**Comment by liuxuan30** [comment]
@petester42 turned out I am not in the owner list so my push hangs and fails. Please help add me.

**Comment by petester42** [comment]
I can't add you because you are not registered on cocoapods. I tried the email on your profile.

**Comment by petester42** [comment]
im pushing the new version now

**Comment by liuxuan30** [comment]
@petester42 it's liuxuan30@gmail.com, thanks

**Comment by petester42** [comment]
you need to do `pod trunk register` first for me to add you

**Comment by petester42** [comment]
released!

**Comment by liuxuan30** [comment]
I see I am in the list now. Thanks :)

**Comment by Janoz94** [comment]
I'm not sure how to give You know but still when I try to install by cocoapods I get 3.0.2 version so the problem wasn't solve. Huge thanks to @WillMays1 for giving an solution for the problem, but still it's not good for longer time and it take time to get what happens when you are begginer swift dev. ;)

**Comment by petester42** [comment]
For cocoapods issues please check with cocoapods issues for help. The most recent version is on there.
