### ISSUE TITLE
StackedBarChart isn't stacking bars

### ISSUE THREAD

**Issue by rossmooney** [danielgindi/Charts#2815]
I'm trying to create a stacked bar chart, but the bars won't stack.  I just get alternating colors for adjacent bars, and the values are summed from the array passed into it.  I pass in an array of x values (indexes) and an array of y value arrays as items.  A coworker ran into the same issue on the Android platform, but I don't see this issue mentioned anywhere else so maybe we aren't setting something correctly?

<img width="342" alt="screen shot 2017-09-21 at 2 15 24 pm" src="https://user-images.githubusercontent.com/3248040/30711807-ecb4096e-9ed7-11e7-89c4-42b84fcbec01.png">

```
        //Get x values and y value arrays
 		guard let chart = chart as? BarChartView,
            case .stackedY(let yValues) = data.yValues,
        case .index(let xValues, _) = data.xValues else { return }

        //Create entries
        let entries = yValues.enumerated().map { index, items in
            BarChartDataEntry(x: Double(xValues[index]), yValues: items)
        }
                
        //Build set
        let set = BarChartDataSet(values: [], label: config.title)
        set.setColors(self.chartColors, alpha: 1.0)
        set.drawValuesEnabled = false

        //Update with entries
        entries.forEach { entry in _ = set.addEntry(entry) }
        barChartData?.dataSets[0] = set
        
        //Labels and legends
        set.stackLabels = ["Source1", "Source2"]
        chart.legend.enabled = !set.stackLabels.isEmpty
        chart.legend.xEntrySpace = chartWidth / 4
        chart.legend.xOffset = 20
        chart.legend.form = .circle

        //Update data on chart
        barChartData.barWidth = 0.5
        chart.data = barChartData
```

**Comment by liuxuan30** [comment]
check out ChartDemo; you don't setup correctly. The stacked y values should be in an array.

**Comment by rossmooney** [comment]
Thanks for your response, but I am using an array of y-values for each entry.  

Turns out my issue was that I was not using the initializer of BarChartDataSet to pass in the values.  The stack size is only calculated there, which is a requirement for bar chart stacking to work.

**Comment by liuxuan30** [comment]
How so? In your code:
>        //Build set
        let set = BarChartDataSet(values: [], label: config.title)

 BarChartDataSet initializers all call `initialize()` to calculate the stack size. Next time post the real code..

**Comment by liuxuan30** [comment]
all I see. I don't realize this. Sorry
