### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

### ISSUE THREAD

**Issue by snehageorge** [danielgindi/Charts#2816]
When updated Charts to 3.0.4 getting this error in Xcode 9.

Other errors are:

1.  Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')
2. Cannot convert value of type '[NSAttributedStringKey : Any]?' (aka 'Optional<Dictionary<NSString, Any>>') to expected argument type '[String : Any]?'

**Comment by karthikwifin** [comment]
I am also facing errors in most of the Charts classes,

**Incorrect argument label in call (have 'withAttributes:', expected 'attributes:')**

**Comment by klemenzagar91** [comment]
I also noticed this. I fix it by setting swift version to 4.0 in the charts build settings in xcode
<img width="693" alt="screen shot 2017-09-22 at 09 42 09" src="https://user-images.githubusercontent.com/5512848/30734212-87f681ca-9f7a-11e7-920b-845cf719f865.png">

**Comment by snehageorge** [comment]
I also fixed it.  Thank You

**Comment by primax79** [comment]
how to fix in an ObjectiveC project?

**Comment by liuxuan30** [comment]
it should have @objc tag to use, so update your code

**Comment by thaihauit** [comment]
attributes: [NSFontAttributeName: label.font]

**Comment by MerinoA** [comment]
This issue solvable by updating the swift version in the build settings of spring to swift 4

<img width="788" alt="screen shot 2017-11-19 at 1 16 58 am" src="https://user-images.githubusercontent.com/7399893/32989258-af8ea878-ccc7-11e7-87df-b169fe6e8371.png">

**Comment by glaucomunsberg** [comment]
For Swift 3 use `pod 'Charts','= 3.0.3'`

**Comment by jonnyijapan** [comment]
I guess this should be fixed in this framework.

**Comment by jonnyijapan** [comment]
Btw, if using Pods:

1. Select the Pods project in the left-most viewer in Xcode.
2. Select Charts target.
3. Build Settings
4. Swift Language Version

**Comment by JoseVf** [comment]
Ran into this problem with `v. 3.1.1`, I'm using `Swift 4.2`
