### ISSUE TITLE
ChartMarkerView not able to subclass of swift class 

### ISSUE THREAD

**Issue by Atchu** [danielgindi/Charts#2817]
Hi 

I am not able to subclass of Markview into swift class to override the Selection point check attached screen shoot 
<img width="609" alt="screen shot 2017-09-22 at 2 09 40 pm" src="https://user-images.githubusercontent.com/5966039/30736287-bcee9b2c-9f9f-11e7-9285-a401f6cb5462.png">

Help me on this point

**Comment by liuxuan30** [comment]
```
@objc(ChartMarkerView)
open class MarkerView: NSUIView, IMarker
{
```
it's open already. Seems your import not work.
