### ISSUE TITLE
Unable to update Chart library 

### ISSUE THREAD

**Issue by sudhir9026** [danielgindi/Charts#2823]
I am using old chart library that contains swift 2.2 0r 2.0.Now I am trying to update with your latest version. but I am getting lots of problems.

I am following these steps:-
1.Remove previous Chart folder from my repository.
2.Download Project from here: https://github.com/danielgindi/Charts
3.Drag the Charts.xcodeproj to your project
4.Hit the "+" under the "Embedded Binaries" section, and select the Charts.framework

Now my Project based on Objective-C so I also Import **ProjectName-Swift.h.**

First Getting this error:- **compiled with newer version of Swift language (3.0) than previous files (2.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**

Can you help me How to update easily

**Comment by osianSmith** [comment]
Hey, This is down to the issues that Charts is now written in Swift 3 while the compiler can only work with swift 2 code.

**Comment by liuxuan30** [comment]
It's written in Swift 4 now. Pick old release yourself. But I think upgrade your project to latest Swift is higher priority as I don't think you can keep using old Xcode for long.

**Comment by sudhir9026** [comment]
Now I am using Xcode9 and follow all steps but still, I am getting error **Unknown class: _TtC6Charts12PieChartView in interface building file**. any suggestions?

**Comment by liuxuan30** [comment]
TtC6Charts12PieChartView this is mangled class name. You should check your project setting first and maybe rebuild. Check out ChartsDemo for ref
