### ISSUE TITLE
Swift: Different colours for circles in one LineChartDataSet

### ISSUE THREAD

**Issue by high5Fly** [danielgindi/Charts#2824]
![screen shot 2017-09-25 at 3 10 51 pm](https://user-images.githubusercontent.com/11722811/30807729-c25a87b8-a203-11e7-8d5b-71e43c05de9b.png)
Hi,

Currently I am trying to set different colours for the values of a DataSet. The colours depends on the range of the values. For example if we have a positive range of 70 up to 100, all values in this range will be green, below will be purple and above will be red.
Could you please assist me here?

KR,
Miroslav

**Comment by thierryH91200** [comment]
it's #2334  without the highlight point

i don't know the author


    **input your own logic for how you actually want to color**


```
func colorPicker(value : Double) -> NSUIColor {
   
        if value > 100 || value < 50 {
            return NSUIColor.red
        }
        else {
            return NSUIColor.black
        }
    }
```

**Comment by high5Fly** [comment]
Hi @thierryH91200,

Thanks for the help.
Just to be on the safe side, you suggest the same approach like https://github.com/denrase/Charts/commit/84409e451ce72972b464b118854a924ea2f79f79
Basically to subclass renderer?

**Comment by thierryH91200** [comment]
it's not the same approach like denrase/Charts@84409e4

not subclass renderer

**Comment by high5Fly** [comment]
Yes, I saw. I was browsing the wrong tab. Your suggestion worked perfectly! Thank you very much!
