### ISSUE TITLE
LineChart 填充

### ISSUE THREAD

**Issue by zbc101** [danielgindi/Charts#2825]
当y值有正负时 ，渐变的填充就不是从最下面填充，而是从y为0时 ，有没有方法解决 从最下面填充

**Comment by zbc101** [comment]
就是填充时，y有正负时，填充以y=0时填充，能不能设置从最下面填充，不管y值正负

**Comment by liuxuan30** [comment]
use English to gain help in time. the filling is around the 0 axis line, it's by design.
You have to override the methods to just fill from bottom. It's in `drawLinearFill()`. Just try pass `contentRect` bottom for `fillMin`
