### ISSUE TITLE
does not support new Objective-C project with Xcode 9

### ISSUE THREAD

**Issue by yiliazhang** [danielgindi/Charts#2830]
does not support new Objective-C project with Xcode 9

**Comment by yiliazhang** [comment]
v3.0.4 does not support new Objective-C project with Xcode 9

**Comment by jiandi1234567890** [comment]
v3.0.4 also not support new Swift project with Xcode 9

**Comment by jack-blackson** [comment]
I also have lots of compiler errors when building the app with version 3.0.4 in Xcode 9.

**Comment by amcalgates** [comment]
Have you looked into this? https://github.com/danielgindi/Charts/issues/2816

**Comment by jack-blackson** [comment]
thanks, setting the swift version fixed it for me.

**Comment by iStone188** [comment]
change the swift version 4.0 in Pods->Charts->Build setting->Swift Language Version :Swift4.0 . errors are gone.

**Comment by keeshux** [comment]
Apparently 3.0.4 requires Swift 4.0, which breaks Swift 3.x projects. Wouldn't a proper `.swift-version` do the job?

**Comment by liuxuan30** [comment]
pod has been updated to 3.0.4. So just pull it
