### ISSUE TITLE
Grouped Bar chart X-axis and Bar Alignment

### ISSUE THREAD

**Issue by sharatkannan** [danielgindi/Charts#2832]
In the demo chart application,Combined graph bar chart end bar not fully showing. 
Demo bar chart data like this. 

- I only need grouped bar chart. 
- This alignment issue also in bar chart example. 

Setting Grouped Barchart:
```
- (BarChartData *)generateBarData
{
    NSMutableArray<BarChartDataEntry *> *entries1 = [[NSMutableArray alloc] init];
    NSMutableArray<BarChartDataEntry *> *entries2 = [[NSMutableArray alloc] init];
    
    for (int index = 0; index < ITEM_COUNT; index++)
    {
        [entries1 addObject:[[BarChartDataEntry alloc] initWithX:index y:(arc4random_uniform(25) + 25)]];
        
        // stacked
        [entries2 addObject:[[BarChartDataEntry alloc] initWithX:index   yValues:@[@(arc4random_uniform(13) + 12), @(arc4random_uniform(13) + 12)]]];
        
    }

    BarChartDataSet *set1 = [[BarChartDataSet alloc] initWithValues:entries1 label:@"Bar 1"];
    [set1 setColor:[UIColor colorWithRed:60/255.f green:220/255.f blue:78/255.f alpha:1.f]];
    set1.valueTextColor = [UIColor colorWithRed:60/255.f green:220/255.f blue:78/255.f alpha:1.f];
    set1.valueFont = [UIFont systemFontOfSize:10.f];
    set1.axisDependency = AxisDependencyLeft;
    
    BarChartDataSet *set2 = [[BarChartDataSet alloc] initWithValues:entries2 label:@""];
    set2.stackLabels = @[@"Stack 1", @"Stack 2"];
    set2.colors = @[
                    [UIColor colorWithRed:61/255.f green:165/255.f blue:255/255.f alpha:1.f],
                    [UIColor colorWithRed:23/255.f green:197/255.f blue:255/255.f alpha:1.f]
                    ];
    set2.valueTextColor = [UIColor colorWithRed:61/255.f green:165/255.f blue:255/255.f alpha:1.f];
    set2.valueFont = [UIFont systemFontOfSize:10.f];
    set2.axisDependency = AxisDependencyLeft;

    float groupSpace = 0.06f;
    float barSpace = 0.02f; // x2 dataset
    float barWidth = 0.45f; // x2 dataset
    // (0.45 + 0.02) * 2 + 0.06 = 1.00 -> interval per "group"
    
    
    BarChartData *d = [[BarChartData alloc] initWithDataSets:@[set1, set2]];
    
    d.barWidth = barWidth;
    
    // make this BarData object grouped
    [d groupBarsFromX:0.0 groupSpace:groupSpace barSpace:barSpace]; // start at x = 0
    
    return d;
}
```
But getting result like:
![simulator screen shot 28-sep-2017 10 21 36 am](https://user-images.githubusercontent.com/11643986/30951081-a96e0ae4-a43e-11e7-9a26-4df35faf903b.png)

The last bar not showing. 
I changed the bar width. in that time changing the x alignment.  X - Axis are not aligned to the bars. 
![simulator screen shot 28-sep-2017 10 20 57 am](https://user-images.githubusercontent.com/11643986/30951132-f3658f5a-a43e-11e7-9a28-289f51180e58.png)

**Comment by syowoo** [comment]
I have like same issue.
![2017-09-29 5 10 13](https://user-images.githubusercontent.com/21093875/31009300-ec984bb4-a541-11e7-911e-e1bab61f3c88.png)

even I put this option. But it does not work.
![2017-09-29 6 02 27](https://user-images.githubusercontent.com/21093875/31009311-f45792c4-a541-11e7-83e3-beca302b5e41.png)

**Comment by roxanajula** [comment]
Have you tried setting the ```chartView.xAxis.centerAxisLabelsEnabled = true ``` ?

**Comment by sharatkannan** [comment]
yes. I set centerAxisLabelsEnabled as true.

**Comment by liuxuan30** [comment]
have you updated the library code to latest? I am not sure why but on my side, it looks fine:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/4375169/31976334-855efc9a-b969-11e7-95a5-67eac1ded2cb.png">
