### ISSUE TITLE
getTransformer function doesn't work properly when AxisDependency is set to right

### ISSUE THREAD

**Issue by ludovic-coder** [danielgindi/Charts#2833]
**Context**
Last version of Charts, using a CombinedChartView with a grouped BarChart and a LineChart.

**Problem**
`getTransformer` function doesn't work properly when `AxisDependency` is set to `right`. The AxisDependency still to left axis.

**It should be**
The AxisDependency should return a right axis based transformer.

**Exemple code**
```
let transformer = barChartView.getTransformer(forAxis: YAxis.AxisDependency.right)
let point = transformer.pixelForValues(x: groupWidth, y: 0)
```

It seems like it's not implemented yet,

```
internal override func initialize()
{
    super.initialize()       
    _leftAxisTransformer = Transformer(viewPortHandler: _viewPortHandler)
    _rightAxisTransformer = Transformer(viewPortHandler: _viewPortHandler)
}
```

**Comment by liuxuan30** [comment]
you are using barChartView instead of combined chart view.
