### ISSUE TITLE
How to show BarChartDataSet with descending x values?

### ISSUE THREAD

**Issue by castus** [danielgindi/Charts#2834]
Could you please help me with drawing a data when `x` is descending, rather than ascending.
I have a BarChartDataSet:

```
ChartDataEntry, x: 2.0, y 1.0
ChartDataEntry, x: 1.0, y 1.0
ChartDataEntry, x: 0.0, y 3.0
```

but when I want to draw a bar chart with that data, it is always presented as:

```
 _
| |
| |   _    _
| |  | |  | |
----------------- x axis
 0    1    2
```

but it should be:

```
           _
          | |
 _    _   | |
| |  | |  | |
----------------- x axis
 2    1    0
```

How can I achieve it?

Thanks

**Comment by castus** [comment]
Anyone?

**Comment by liuxuan30** [comment]
x y are just coordinates, x is not index anymore. Think that way.
