### ISSUE TITLE
Pass String to LineChartData

### ISSUE THREAD

**Issue by Mahan3340** [danielgindi/Charts#2841]
hi , I'm seeing this in every tutorial but seems I cant set array of string to LineChartData , whats the problem ? is the Library changed since then ?

` let data: LineChartData = LineChartData(xVals: months, dataSets: data)
`which month is an Array of strings

**Comment by liuxuan30** [comment]
the tutorial is old then. Since chart 3.0, x are only double type. use valueFormatter for its strings

**Comment by Mahan3340** [comment]
would u give an example as im new to swift please ?

**Comment by liuxuan30** [comment]
look at OS X demos and ChartsDemos for details. It's swift and oc code.
