### ISSUE TITLE
xcode 9.0 compile ERROR: "static var 'defaultFormatter' is not public"

### ISSUE THREAD

**Issue by ecoenghk** [danielgindi/Charts#2842]
Everything was fine on Xcode 8.
However, Errors show up after compiled to pod Version 3.0.3.
After the release of pod Version 3.0.4, I updated the pod and still show the following errors.

They are the same type of errors - "static var 'defaultFormatter' is not public".
And showing "Static var 'defaultFormatter' is internal and cannot be referenced from a default argument value" inside the Charts files.
Sometime show 6 errors and sometime show 8 errors.

I am kind of newbie in swift and not sure how to solve this problems.
Any help or suggestion will be highly appreciated.
Thanks!

Errors shows in:
ChartAxisLabelGeneratorDate.swift
ChartAxisLabelsGeneratorNumber.swift
ChartAxisLabelsGeneratorNumberSuffix.swift
ChartAxisValueDouble.swift (2 times)
ChartAxisValueDoubleScreenLoc.swift
ChartAxisValueFloat.swift
ChartAxisValueFloatScreenLoc.swift

![2017-10-03 4 16 03](https://user-images.githubusercontent.com/24453087/31117073-07136b42-a85b-11e7-8d33-03601378da61.png)
![2017-10-03 4 13 38](https://user-images.githubusercontent.com/24453087/31117091-1da55e2e-a85b-11e7-8bd8-0baf8b138c07.png)

![2017-10-03 4 11 11](https://user-images.githubusercontent.com/24453087/31117099-2185830c-a85b-11e7-9830-985a270de538.png)

**Comment by ethanfox** [comment]
Having the same issue. How do I fix this?????

**Comment by ethanfox** [comment]
Found a solution that may help others: 

- I had SwiftCharts in my Podfile (so remove that if you have it)

- Comment out that Charts pod - # pod 'Charts'
- Open your Xcode Project and clean it 
- Reinstall the Charts Pod

**Comment by ecoenghk** [comment]
Thanks ethanfox .

I find out the problem now. I have 2 chart library, i-schuetz/SwiftCharts & danielgindi/Charts. But I'm using only danielgindi/Charts now. I thought it is the compile problems of danielgindi/Charts, but actually it is the compile problems of i-schuetz/SwiftCharts.

Sorry for my low level mistake. Thanks for everyone helps!
