### ISSUE TITLE
Install charts via cocapods pulls back old version 3.0.2

### ISSUE THREAD

**Issue by AdamMak** [danielgindi/Charts#2843]
I am trying to install Charts via cocoapods rather than manually, however when I do, it pulls back version 3.0.2. I am using Xcode 9 and Swift 4 and as a result I am getting a good few errors.

Cocoapod file looks like this

```
target 'ChartsTesting' do
	pod 'Charts'

    use_frameworks!
end
```

Anyone know how to fix this? Would much rather install framework through cocoapods 

Thanks in advance

**Comment by Triipaxx** [comment]
I don't know what exactly causes the issue, but you could change your pods file:

`pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :tag => 'v3.0.4'`

this will request the version 3.0.4 directly

**Comment by liuxuan30** [comment]
pod has been updated to 3.0.4 now.
