### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

### ISSUE THREAD

**Issue by VinayAzuga** [danielgindi/Charts#2844]
Charts/Source/Charts/Renderers/BarChartRenderer.swift:620:121: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

**Comment by GerardoMR** [comment]
Having the same issue, just updated to Xcode 9, running Charts version 3.0.4.

**Comment by GerardoMR** [comment]
Ok, so the issue happens because NSAttributedStringKey was introduced in Swift 4 for a more convenient handling of the attribute keys.

I was using Swift 3.2, but after updating my application, all the problems went away.

**Comment by assisjeferson** [comment]
Change `Swift Language Version` to `Swift 4.0`

**Comment by CarlinhaCamargo** [comment]
Is there any alternative to not update to swift 4.0?

**Comment by LJYes** [comment]
![image](https://user-images.githubusercontent.com/18663185/31364716-3e27d052-ad2c-11e7-90dc-481e147b85bf.png)
Build Settings --> user-defined --> SWIFT_VERSION.
Change  to  4.0

**Comment by NadyaCherniavskaya** [comment]
Had the same issue. Fixed by using an older version of Charts.

**Comment by fangzhengwang** [comment]
how to change Swift Language Version to Swift 4.0?

**Comment by liuxuan30** [comment]
any one who uses 3.0.4 must use Swift 4. If there are any frameworks requires lower, you should roll back chart or upgrade those old frameworks.

**Comment by rafperezsi83** [comment]
In swift 4 i hace the issue but i swicht to 3.2 an fix it

**Comment by thaihauit** [comment]
attributes: [NSFontAttributeName: label.font] with swift 3.2 .

**Comment by Bijiabo** [comment]
My project use swift 3.2 now. ..
