### ISSUE TITLE
In Multiple bar chart Unable to set Values more than 4 bar in under given year..

### ISSUE THREAD

**Issue by Saravana181187** [danielgindi/Charts#2847]
In multiple bar charts, i want to show 6 bars per group. But if the number of bars count increases beyond four, the bars exceeds to next group. Please help me on this.

![img_0039](https://user-images.githubusercontent.com/8847867/31230086-84dbb042-aa00-11e7-9bf3-9c029ce8009f.PNG)

**Comment by roxanajula** [comment]
Can you post some code on how you are setting your chart?

**Comment by liuxuan30** [comment]
check out ChartsDemo - multiple bar chart:
```
    float groupSpace = 0.08f;
    float barSpace = 0.03f;
    float barWidth = 0.2f;
    // (0.2 + 0.03) * 4 + 0.08 = 1.00 -> interval per "group"
```
where 4 is the data set count. you can change it but make sure it sums to 1.0

**Comment by Saravana181187** [comment]
ok Thanks...
