### ISSUE TITLE
Updating Charts to 3.0.4 and Swift 4 doesn't work

### ISSUE THREAD

**Issue by Wh1rlw1nd** [danielgindi/Charts#2851]
Hi, and thanks for this great library!

I have updated Charts to 3.0.4 version, and in Pods -> Targets -> Charts have set Swift Language version to 4.0. This is how related section looks like:

![screen shot 2017-10-07 at 01 31 47 po podne](https://user-images.githubusercontent.com/10575475/31307392-032b2b8a-ab64-11e7-80dc-0f22e0e1eae1.png)

And these are errors I am seeing when I try build :
![issue](https://user-images.githubusercontent.com/10575475/31307446-e3479ea6-ab64-11e7-89aa-8d2c137edc77.png)

This is my **Podfile** :

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.2'
pod 'Charts'
use_frameworks!

project 'myProject.xcodeproj'

target 'myProject' do
  pod 'Charts'
end
```

and this is how **Podfile.lock** looks like:

```
PODS:
  - Charts (3.0.4):
    - Charts/Core (= 3.0.4)
  - Charts/Core (3.0.4)

DEPENDENCIES:
  - Charts

SPEC CHECKSUMS:
  Charts: 0705898046257443f0afbbc3179f4b67507b6e48

PODFILE CHECKSUM: 2550099e0fb5ee6e78531ab01d41df014f8df3c4

COCOAPODS: 1.3.1
```

Any idea why I am getting these errors ?

**Comment by liuxuan30** [comment]
you don't use Charts 3.0 right? The method name seems 2.x style and has been removed.
