### ISSUE TITLE
xcode9 pod install have a problem

### ISSUE THREAD

**Issue by WM520** [danielgindi/Charts#2856]
/Users/wangmiao/Library/Developer/Xcode/DerivedData/test-dwfmkogupoggbpanfqurtzghmnnz/Build/Products/Debug-iphonesimulator/Charts.framework: No such file or directory

**Comment by andrealufino** [comment]
Try to clean the project and to empty the Derived Data folder

**Comment by cwinUser** [comment]
I am getting same issue. 
@andrealufino  it it not working after cleaning project or making empty derived data..

Can anyone please suggest any fixed on priority?

**Comment by liuxuan30** [comment]
just clear DerivedData and module cache and rebuild with latest code. It's swift 4 already.

**Comment by WM520** [comment]
thanks
