### ISSUE TITLE
How can I make the chart rotate completely, 360, 720 on a button click ?

### ISSUE THREAD

**Issue by SatishBirajdar007** [danielgindi/Charts#2861]
The thing that I want to do is,

A "Spin" button is clicked
The pie chart starts rotating random 'n' times, and stops after sometime. And one slice is highlighted.
So question is, how can I make the chart rotate completely, 360, 720 on a button click ?

**Comment by SatishBirajdar007** [comment]
Was able to do with `spin(duration: 3, fromAngle: 0, toAngle: 720)`

**Comment by liuxuan30** [comment]
there are many ways, like rotating the UIView, or update the CTM matrix like `CGAffineTransformRotate` to rotate yourself.
