### ISSUE TITLE
How can I highlight a specific slice of the PieChart?

### ISSUE THREAD

**Issue by SatishBirajdar007** [danielgindi/Charts#2862]
How can I highlight a specific slice of the PieChart?

**Comment by SatishBirajdar007** [comment]
Solved it by `highlightValue(x: 4.0, y: 0.0, dataSetIndex: 0)`

**Comment by codeliu6572** [comment]
if dataSetIndex above zero,it does not work, why?

**Comment by liuxuan30** [comment]
because pie chart ONLY support one data set
