### ISSUE TITLE
Filled Line Chart

### ISSUE THREAD

**Issue by sunynator** [danielgindi/Charts#2863]
I'm trying to draw a filled line chart, you guys can see the picture for more clarity.
<img width="598" alt="screen shot 2017-10-09 at 23 02 38" src="https://user-images.githubusercontent.com/17984236/31370104-3c957e78-ad46-11e7-947e-7c8384546b8f.png">
So, I saw the example and they are using IFillFormatter protocol to get y-axis position where the filled line of dataset end. But, it was a fixed position, not dynamic at all. How can I can this position depend on the each element of dataset. For instance, if index == 0 then we have a the end of filled position A, if index == 1 then we have a different end value of a filled position.
Or, any other suggestion to draw a chart like the picture above.

**Comment by liuxuan30** [comment]
take a look at `drawLinearFill` where it draw the fill rect. It calculates the fill rect within `generateFilledPath` and `getFillLinePosition`. ideally  you should override those methods to get your rect between lines, you are good to go

**Comment by rob-k** [comment]
I managed to achieve this by following @liuxuan30 's suggestions by subclassing `LineChartRenderer` and adding a variable to the class implementing `IFillFormatter`, which let's me pass a second data set as indicator for the fill line and draw the path accordingly (only for linear, but I assume you could do the same thing for Bezier).

```Swift
class AreaFillFormatter: IFillFormatter {

    var fillLineDataSet: LineChartDataSet?
    
    init(fillLineDataSet: LineChartDataSet) {
        self.fillLineDataSet = fillLineDataSet
    }
    
    public func getFillLinePosition(dataSet: ILineChartDataSet, dataProvider: LineChartDataProvider) -> CGFloat {
        return 0.0
    }
    
    public func getFillLineDataSet() -> LineChartDataSet {
        return fillLineDataSet ?? LineChartDataSet()
    }
    
}
```

```Swift
class CustomLineChartRenderer: LineChartRenderer {
    
    override open func drawLinearFill(context: CGContext, dataSet: ILineChartDataSet, trans: Transformer, bounds: XBounds) {
        guard let dataProvider = dataProvider else { return }
        
        let areaFillFormatter = dataSet.fillFormatter as? AreaFillFormatter
        
        let filled = generateFilledPath(
            dataSet: dataSet,
            fillMin: dataSet.fillFormatter?.getFillLinePosition(dataSet: dataSet, dataProvider: dataProvider) ?? 0.0,
            fillLineDataSet: areaFillFormatter?.getFillLineDataSet(),
            bounds: bounds,
            matrix: trans.valueToPixelMatrix)
        
        if dataSet.fill != nil
        {
            drawFilledPath(context: context, path: filled, fill: dataSet.fill!, fillAlpha: dataSet.fillAlpha)
        }
        else
        {
            drawFilledPath(context: context, path: filled, fillColor: dataSet.fillColor, fillAlpha: dataSet.fillAlpha)
        }
    }
    
    fileprivate func generateFilledPath(dataSet: ILineChartDataSet, fillMin: CGFloat, fillLineDataSet: ILineChartDataSet?, bounds: XBounds, matrix: CGAffineTransform) -> CGPath
    {
        let phaseY = animator?.phaseY ?? 1.0
        let isDrawSteppedEnabled = dataSet.mode == .stepped
        let matrix = matrix
        
        var e: ChartDataEntry!
        var fillLineE: ChartDataEntry?
        
        let filled = CGMutablePath()
        
        e = dataSet.entryForIndex(bounds.min)
        fillLineE = fillLineDataSet?.entryForIndex(bounds.min)
        
        if e != nil
        {
            if let fillLineE = fillLineE
            {
                filled.move(to: CGPoint(x: CGFloat(e.x), y: CGFloat(fillLineE.y * phaseY)), transform: matrix)
            }
            else
            {
                filled.move(to: CGPoint(x: CGFloat(e.x), y: fillMin), transform: matrix)
            }
            
            filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(e.y * phaseY)), transform: matrix)
        }
        
        // Create the path for the data set entries
        for x in stride(from: (bounds.min + 1), through: bounds.range + bounds.min, by: 1)
        {
            guard let e = dataSet.entryForIndex(x) else { continue }
            
            if isDrawSteppedEnabled
            {
                guard let ePrev = dataSet.entryForIndex(x-1) else { continue }
                filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(ePrev.y * phaseY)), transform: matrix)
            }
            
            filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(e.y * phaseY)), transform: matrix)
        }
        
        // Draw a path to the start of the fill line
        e = dataSet.entryForIndex(bounds.range + bounds.min)
        fillLineE = fillLineDataSet?.entryForIndex(bounds.range + bounds.min)
        if e != nil
        {
            if let fillLineE = fillLineE
            {
                filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(fillLineE.y * phaseY)), transform: matrix)
            }
            else
            {
                filled.addLine(to: CGPoint(x: CGFloat(e.x), y: fillMin), transform: matrix)
            }
        }
        
        // Draw the path for the fill line (backwards)
        if let fillLineDataSet = fillLineDataSet {
            for x in stride(from: (bounds.min + 1), through: bounds.range + bounds.min, by: 1).reversed()
            {
                guard let e = fillLineDataSet.entryForIndex(x) else { continue }
                
                if isDrawSteppedEnabled
                {
                    guard let ePrev = fillLineDataSet.entryForIndex(x-1) else { continue }
                    filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(ePrev.y * phaseY)), transform: matrix)
                }

                filled.addLine(to: CGPoint(x: CGFloat(e.x), y: CGFloat(e.y * phaseY)), transform: matrix)
            }
        }
        
        filled.closeSubpath()
        
        return filled
    }
}
```

**Comment by liuxuan30** [comment]
perfect example to mastering the project :)

**Comment by jjy4880** [comment]
how to resolve/ use this solution?

**Comment by bhargavsejpalindianic** [comment]
@rob-k can you please provide usage example for this

**Comment by rob-k** [comment]
Sure, I use the code as follows:

```Swift
let maxDataSet = LineChartDataSet()
let minDataSet = LineChartDataSet()

// ... fill the data sets

maxDataSet.drawFilledEnabled = true
maxDataSet.fillFormatter = AreaFillFormatter(fillLineDataSet: minDataSet)
```

**Comment by bhargavsejpalindianic** [comment]
i installed this manually and followed each step as per example still looks like its not working @rob-k

**Comment by bhargavsejpalindianic** [comment]
@rob-k i tried to debug using break points any of function from CustomLineChartRenderer not being called

**Comment by rob-k** [comment]
I updated my comment to include setting the `LineChartRenderer`

**Comment by bhargavsejpalindianic** [comment]
still no luck man @rob-k

**Comment by bhargavsejpalindianic** [comment]
@rob-k here is my code and i want color between ucb and lcb 
` 

        for i in 0..<x.count {
            
            
            guard !ucb[i].isNaN && !lcb[i].isNaN else { continue }
            
            let dataEntry = ChartDataEntry(x: x[i], y: y[i])
            let ucbEntry = ChartDataEntry(x: x[i], y: ucb[i])
            let lcbEntry = ChartDataEntry(x: x[i], y: lcb[i])

            dataEntries.append(dataEntry)
            ucbEntries.append(ucbEntry)
            lcbEntries.append(lcbEntry)

        }
        
        let lineChartDataSet = LineChartDataSet(entries: dataEntries, label: "")
        let ucbDataSet = LineChartDataSet(entries: ucbEntries, label: "")
        let lcbDataSet = LineChartDataSet(entries: lcbEntries, label: "")
        
        lineChartDataSet.setColor(LineColor)
        lineChartDataSet.mode = .horizontalBezier
        lineChartDataSet.drawCirclesEnabled = false
        lineChartDataSet.lineWidth = 2.0
//        lineChartDataSet.drawValuesEnabled = false
      
      
        
        ucbDataSet.setColor(UIColor.graph.circleGreen)
        ucbDataSet.mode = .horizontalBezier
        ucbDataSet.drawCirclesEnabled = false
        ucbDataSet.lineWidth = 2.0

        ucbDataSet.drawFilledEnabled = true
        ucbDataSet.fillAlpha = 0.4
        
        lineChartView.renderer = CustomLineChartRenderer(dataProvider: lineChartView, animator: lineChartView.chartAnimator, viewPortHandler: lineChartView.viewPortHandler)
        
        ucbDataSet.fillFormatter = AreaFillFormatter(fillLineDataSet: ucbDataSet)

       
        
        lcbDataSet.setColor(UIColor.graph.circleGreen)
        lcbDataSet.mode = .horizontalBezier
        lcbDataSet.drawCirclesEnabled = false
        lcbDataSet.lineWidth = 2.0
//        lcbDataSet.drawValuesEnabled = false
       


        // Hide x-axis
        let xAxis = lineChartView.xAxis
        xAxis.labelPosition = .bottom
        xAxis.enabled = true
        xAxis.drawGridLinesEnabled = true
        xAxis.drawAxisLineEnabled = false
        xAxis.gridColor = UIColor.init(hex: "c8cdea")
        xAxis.gridColor = UIColor.init(hex: "c8cdea")
        xAxis.labelTextColor = UIColor.app.main
        xAxis.avoidFirstLastClippingEnabled = true

        lineChartView.isUserInteractionEnabled = false
        lineChartView.rightAxis.enabled = false
        lineChartView.leftAxis.drawAxisLineEnabled = false
        lineChartView.leftAxis.drawGridLinesEnabled = false
        lineChartView.leftAxis.enabled = true
        lineChartView.legend.enabled = false
        lineChartView.xAxis.valueFormatter = DefaultAxisValueFormatter(block: {(index, _) in
            return String(Int(index)) + " Mins"
        })

        lineChartView.leftAxis.spaceBottom = 0.0

        let linechartDatas = LineChartData(dataSets: [ucbDataSet,lcbDataSet,lineChartDataSet])
        
        lineChartView.data = linechartDatas`

**Comment by rob-k** [comment]
If you want the color between `ucbDataSet` and `lcbDataSet` you need to pass the second data set to the formatter of the first one.  You are passing the dataset to the formatter of itself. Try to do the following:

```swift
ucbDataSet.fillFormatter = AreaFillFormatter(fillLineDataSet: lcbDataSet)
```
(or the other way around)

**Comment by bhargavsejpalindianic** [comment]
already tried what i am trying to explain is 
 i tried to debug using break points any of function from CustomLineChartRenderer class not being called

**Comment by rob-k** [comment]
I see that you are using Bezier mode in your code:

```Swift
lineChartDataSet.mode = .horizontalBezier
ucbDataSet.mode = .horizontalBezier
lcbDataSet.mode = .horizontalBezier
```

The code I provided only works for linear mode. You will have to change the mode to `.linear` or override `drawHorizontalBezier` and adjust the code accordingly.

**Comment by bhargavsejpalindianic** [comment]
@rob-k got it just worked thanks very much man for finding it out

**Comment by michal-th** [comment]
Would it be possible to implement this using CombinedChart ?

**Comment by Chakib-Temal** [comment]
> Would it be possible to implement this using CombinedChart ?

did you find the solution ? the CombinedChart use the CombinedChartRender , not the LinearChartRender , so the call back is not called `drawLinearFill` , it use the default Render 

the method `drawLinearFill` doesn't exist , it's take many of renders when you search in the library

**Comment by Chakib-Temal** [comment]
> Would it be possible to implement this using CombinedChart ?

solution combinedChart : https://github.com/PhilJay/MPAndroidChart/issues/338

**Comment by komunamu** [comment]
@rob-k  Thank you for sharing the example. It works perfectly for the first drawing. If I change the dateset, it looks like the old chart and the new chart are mixed or duplicated. How to clean the preview chart and draw the new chart using the new dataset? Thank you for your help in advance. 

<img width="595" alt="issue" src="https://user-images.githubusercontent.com/2301552/119400466-3a164e00-bca8-11eb-9162-d48fbfc09e26.png">

**Comment by rob-k** [comment]
@komunamu can your share the code that you use to update the chart data? If you simply replace the data set arrays and call `lineChart.notifyDataSetChanged()` this should be sufficient.

**Comment by AlexChzuang** [comment]
@komunamu hello, could you share your code of the amazing charts? Thanks a lot!

**Comment by komunamu** [comment]
@AlexChzuang Sorry I don't have the source code. I think the updated demo code has the sample code that filled the line chart. Good luck!

**Comment by suryasahu92** [comment]
This has been a great help
