### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by michael-snapptec** [danielgindi/Charts#2866]
This appears to show up 7 times in the current version.

One instance is specifically at `AxisBase.swift:137`.

I am not a Swift developer (Obj-C for the win!), but it appears that this can be corrected by changing this:

    if longest.characters.count < text.characters.count

to this:

    if longest.count < text.count

**Comment by liuxuan30** [comment]
interesting, what's your swift version? As my swift 4 and xcode9 does not warn this at all.

**Comment by saldous** [comment]
Please re-open, Xcode 9.1 is now released and shows these warnings.

**Comment by liuxuan30** [comment]
not updated yet; but you are welcome to file a PR for this update
