### ISSUE TITLE
Set names of X-axis and Y-axis itself (not their labels)

### ISSUE THREAD

**Issue by vkosmirak** [danielgindi/Charts#2867]
Hi guys,

Are there any build-in way to set this labels?

<img width="812" alt="1111111___salesforce" src="https://user-images.githubusercontent.com/6514929/31436792-b8adba5c-ae8b-11e7-904e-9a201a86a915.png">

**Comment by seenoevo** [comment]
please search, there are plenty of questions regarding this

I'll provide a few: #299, #35, #2387

**Comment by vkosmirak** [comment]
Thanks!

I have used  #2452's solution. Hope it will be merged

```
pod 'Charts', :git => 'https://github.com/vkosmirak/Charts.git', :branch => 'master1'
```
