### ISSUE TITLE
Change scroll direction HorizontalBarChartView x-axis from top to bottom chart

### ISSUE THREAD

**Issue by Schabaani** [danielgindi/Charts#2868]
I have a **HorizontalBarChartView** in a collection view that each cell has 330 height that works very well. But it shows at the end of chart. I have to scroll to top to see visa card. I need reverse of it. How can I start it at top? I did not post my codes here. You can Find it on other question that I [asked](https://github.com/danielgindi/Charts/issues/2849).

Please see the gif below:
![ezgif-5-40d6571a40](https://user-images.githubusercontent.com/16123923/31439077-b39a9a10-ae97-11e7-9975-73a11d4cc13e.gif)

**Comment by Schabaani** [comment]
There is nobody to help me?

**Comment by vkosmirak** [comment]
Please check #2070

**Comment by Schabaani** [comment]
No, this is not my question. I need to change scroll direction. When it shows chart I see end of charts (actually first item) and I should scroll up, however, I need the reverse. Showing visa card and scrolling down. I want to change position of viewing.

**Comment by liuxuan30** [comment]
just reversed the order when you add them in your data sets

**Comment by L-ZHIJIAN** [comment]
I have the same problem, HorizontalBarChartView shows at the end of chart, but I need to start at the top. How do I get it to start at the top？

**Comment by L-ZHIJIAN** [comment]
Hello @Schabaani , I met the same problem that needs to be solved. Could you tell me how you solved it？
