### ISSUE TITLE
xcode 9.0 errors after installing pod 'Charts'

### ISSUE THREAD

**Issue by jmtaverne** [danielgindi/Charts#2869]
Hi,

I'm receiving following errors after installing the pod-file.

![1](https://user-images.githubusercontent.com/26202418/31491912-4ad36734-af49-11e7-9b24-18dc030ee0ed.jpeg)
![2](https://user-images.githubusercontent.com/26202418/31491914-4af4e8fa-af49-11e7-8c21-63b0d79a23c0.jpeg)

Any ideas what the problem is or any ideas how to solve it?

Thank you in advance.

**Comment by cwinUser** [comment]
I  am getting same issue. Can anyone please suggest any fixed on priority.

**Comment by siroroman** [comment]
Change  Swift Language Version in Pods/Charts/Build Settings to Swift 4.0.

**Comment by aelam** [comment]
@siroroman Do it every time?

**Comment by balkarov** [comment]
I have the same problem. Now I have xcode 9.2. And cannot change swift version
