### ISSUE TITLE
LineChartView: Using two different colors in one dataset

### ISSUE THREAD

**Issue by mako9** [danielgindi/Charts#2871]
Hey there,
I'm trying to produce a LineChartView like in the image. It's a continuous moving line chart which changes the color when reaching a specified y-value.
How can I achieve something like this? 
I already tried using two datasets combined but it doesn't work well.

<img width="478" alt="bildschirmfoto 2017-10-12 um 16 01 03" src="https://user-images.githubusercontent.com/26220415/31500212-1ebe882c-af67-11e7-8ba3-a1f143b0df5c.png">

Thank you,
Mario

**Comment by wjacker** [comment]
Hi Marrio, I think you can try override drawLinearFill method for implement different color fill.

**Comment by liuxuan30** [comment]
yes, but it seems requires lots of overriding. but you can get some idea from drawLinearFill though
