### ISSUE TITLE
Swift 4 issue

### ISSUE THREAD

**Issue by mob-rockstar** [danielgindi/Charts#2876]
Dear danielgindi.
I just installed the Charts library using cocoapods in Xcode 9.
but I am seeing many errors in Charts/Core/ when I build project.

![screen shot 2017-10-13 at 9 51 54 am](https://user-images.githubusercontent.com/16888110/31557055-38916dba-affc-11e7-9413-5dc9602db3e7.png)

How can I solve this errors.
Regards

**Comment by Ercules76** [comment]
same for me

**Comment by FENGXIANGLI** [comment]
Same for me

**Comment by seenoevo** [comment]
please search: #2819, #2816, #2801

**Comment by liuxuan30** [comment]
just clean up your project and use 3.0.4

**Comment by mob-rockstar** [comment]
Hi Xuan.
I am getting same error in v.3.0.4
How can I fix this issue?

Regards

**Comment by thierryH91200** [comment]
https://user-images.githubusercontent.com/5512848/30734212-87f681ca-9f7a-11e7-920b-845cf719f865.png

 fix it by setting swift version to 4.0 in the charts build settings in xcode

**Comment by mob-rockstar** [comment]
How can I find the charts build settings in xcode?

**Comment by mob-rockstar** [comment]
![screen shot 2017-11-24 at 12 30 00 am](https://user-images.githubusercontent.com/16888110/33201748-ab065338-d0ae-11e7-8d9f-b00cd03b353b.png)
you mean this section?

**Comment by thierryH91200** [comment]
yes

**Comment by jonnyijapan** [comment]
It's in the Pods project. Doh.
