### ISSUE TITLE
Scrolling chart after setting lineChart.xAxis.axisMaximum = someValue

### ISSUE THREAD

**Issue by CosmicYogi** [danielgindi/Charts#2879]
I want to set the maximum value for `lineChart.xAxis.axisMaximum = 5`
But when I do so the graph stops scrolling.

What I mean is suppose I am having dataset [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15] for xAxis and [array or any 15 random numbers] for yAxis. 

Then I achieve what I want i.e.., the chart should have max value of 5.
But what problem I face is that graph stops scrolling and I can't see values corresponding to values greater than 5 i.e.., 6,7,8,9... and so on.

**Comment by liuxuan30** [comment]
1. you can scroll when your chart zooms in. You cannot scroll if it's scaled at 1.
2. changing axisMaximum will limit your y max to 5. And you should not see any value beyond 5, that's what does axisMaximum mean right?

**Comment by 29satnam** [comment]
Here's my two cents on the subject.
`chart.setVisibleXRangeMaximum(5)`
This however needs to be set after the data has been set in the chart (not in a configure before).
This did the trick for me
