### ISSUE TITLE
help about performance issues about line charts

### ISSUE THREAD

**Issue by wx-liubin** [danielgindi/Charts#2881]
I should get the data from background and display in the line charts, about 10240 data should update each time, but it seems that redraw is very slow, the refresh code is like below

```
view.data?.notifyDataChanged()
view.notifyDataSetChanged()
view.setNeedsDisplay()
```
anything wrong with this code?

**Comment by liuxuan30** [comment]
it will be slow for sure. Currently there is no better options but reduce your data sets by sampling.
