### ISSUE TITLE
Large Whitespace Between X-Axis Labels and Legend

### ISSUE THREAD

**Issue by semireg** [danielgindi/Charts#2882]
Can someone help me understand which setting affects this gap between the bottom of the x-axis labels and the top of the legend? I would like this gap to be smaller.

![2017-10-15 at 3 20 pm](https://user-images.githubusercontent.com/1819762/31588810-e0d7e226-b1bc-11e7-8a03-e3a55fc1bba1.png)

**Comment by thierryH91200** [comment]
see #2414 

other solution
legend.enabled = false
