### ISSUE TITLE
drawing xAxis ratio values

### ISSUE THREAD

**Issue by sss989870** [danielgindi/Charts#2885]
i have datas [0, 10, 5, 4, 3, 50, 5000, 5400, 4900, 7000]

so scatterchartview drawing xAxis [0, 10, 20 ,30 ,40, 50, 60... ~ 7000]
It appears to be divided into two parts.
but i want to draw xAxis ratio.
example that's data xAxis range should [0~ 100, 4500 ~ 8500]

**Comment by liuxuan30** [comment]
you can use valueFormatter to format axis values.
