### ISSUE TITLE
Problem with BalloonMarker in lineChart

### ISSUE THREAD

**Issue by Schabaani** [danielgindi/Charts#2892]
I am using [this](https://github.com/danielgindi/Charts/blob/0a56492109e95a40ab9dd67e6eb91536df22e793/ChartsDemo/Classes/Components/BalloonMarker.swift) version of BalloonMarker.
You see 3 images below. The last image doesn't show very well. What change in codes can solve my problem?

<img width="613" alt="screen shot 2017-10-17 at 10 10 00 am" src="https://user-images.githubusercontent.com/16123923/31650293-8b009bf0-b323-11e7-9644-e01c954e7873.png">
<img width="613" alt="screen shot 2017-10-17 at 10 09 53 am" src="https://user-images.githubusercontent.com/16123923/31650298-9019c828-b323-11e7-91d3-7915a2dda06b.png">
<img width="613" alt="screen shot 2017-10-17 at 10 10 05 am" src="https://user-images.githubusercontent.com/16123923/31650360-d71b50c0-b323-11e7-889b-042dca236d9a.png">

**Comment by Schabaani** [comment]
I don't know why chart is nil.

` let chart = self.chartView`

any suggestion?

**Comment by Schabaani** [comment]
I guess there is a bug in BalloonMarker initializer. It needs one more parameter for chartView.

```
    public init(color: UIColor, font: UIFont, textColor: UIColor, insets: UIEdgeInsets, chart: Charts.ChartViewBase)
    {
        super.init()
        
        self.color = color
        self.font = font
        self.textColor = textColor
        self.insets = insets
        self.chartView = chart
        
        _paragraphStyle = NSParagraphStyle.default.mutableCopy() as? NSMutableParagraphStyle
        _paragraphStyle?.alignment = .center
    }
```
When initializing marker, pass your chart as last parameter:
```
let marker = BalloonMarker(color: UIColor.red, font: UIFont.systemFont(ofSize:12.0), textColor: UIColor.darkText, insets: UIEdgeInsetsMake(8.0, 8.0, 20.0, 8.0), chart: chartView)
```

and now **self.chart is not nil**

**Comment by thierryH91200** [comment]
you have forget
chartView.marker = marker
marker.chartView = chartView

**Comment by thierryH91200** [comment]
try my balloon marker



[RectMarker.swift.zip](https://github.com/danielgindi/Charts/files/1390806/RectMarker.swift.zip)

and change
set1 = LineChartDataSet(values: yVals1, label: "what you want")

<img width="1795" alt="capture d ecran 2017-10-17 a 13 24 39" src="https://user-images.githubusercontent.com/6251463/31662464-c2f45bbc-b33e-11e7-9485-4f9ad3743a69.png">


<img width="1795" alt="capture d ecran 2017-10-17 a 13 24 32" src="https://user-images.githubusercontent.com/6251463/31662480-d03e1c0e-b33e-11e7-9dc6-b66f8d0bf2f9.png">

**Comment by Schabaani** [comment]
Thanks, I forget `marker.chartView = chartView`.
I guess it is better to set this value in initializer, like me. This is safer.
Thanks again

**Comment by liuxuan30** [comment]
be careful creating a retain cycle `marker.chartView = chartView`

**Comment by fabien-ml** [comment]
`MarkerImage` class have `@objc open weak var chartView: ChartViewBase?'` it avoid the retain cycle problem , no ?

**Comment by PrashanthPasi** [comment]
Finally one Line of code save
 `Savemarker.chartView = chartView`
