### ISSUE TITLE
Pie chart full view

### ISSUE THREAD

**Issue by petar-petrov** [danielgindi/Charts#2895]
I am trying to extend the pie chart upto the edge of the view. How could I accomplish this.
<img width="259" alt="screen shot 2017-10-18 at 14 41 14" src="https://user-images.githubusercontent.com/2332137/31716890-72c353da-b412-11e7-8213-97fd3797aa83.png">

**Comment by liuxuan30** [comment]
that's basically a new view, not pie chart anymore. I would rather create a new view for this than change pie chart.
