### ISSUE TITLE
Dynamically set the bar width

### ISSUE THREAD

**Issue by nibin666** [danielgindi/Charts#2898]
## How can I set the bar width dynamically like [echarts](http://echarts.baidu.com/demo.html#custom-profit).

Is there any idea? Thx.

<img width="944" alt="jietu20171020-155222" src="https://user-images.githubusercontent.com/15081119/31810828-c4e79c26-b542-11e7-9c09-bbfb301f7384.png">

**Comment by liuxuan30** [comment]
we don't support this. But you can try overriding bar chart renderer to change the barRect

**Comment by jessicafrank204** [comment]
@nibin666 Hi, I'm also looking to dynamically set the bar width. Were you able to solve this issue? Thanks.
