### ISSUE TITLE
xcode9 alert swift question

### ISSUE THREAD

**Issue by Canxr** [danielgindi/Charts#2900]
<img width="435" alt="1" src="https://user-images.githubusercontent.com/22272438/31814358-f83a840c-b5bb-11e7-97a5-dceb04a2f7ee.png">
I don't have xcode8 and I see Charts can use in xcode9;
<img width="214" alt="podfile" src="https://user-images.githubusercontent.com/22272438/31814359-f870567c-b5bb-11e7-8a6e-98d76f7f4818.png">
This is my Podfile.

**Comment by Canxr** [comment]
<img width="958" alt="2" src="https://user-images.githubusercontent.com/22272438/31814485-609c049e-b5bc-11e7-9a93-3839f2ce6391.png">
When I building my project, xcode bring out an error.

**Comment by petester42** [comment]
try `pod repo update` and then `pod install` again.

**Comment by Canxr** [comment]
I have been updated, but there are the same problems...

**Comment by liuxuan30** [comment]
update your pod itself maybe. it's your env issue.
