### ISSUE TITLE
Update cocoapods.org version

### ISSUE THREAD

**Issue by ChaosPredictor** [danielgindi/Charts#2902]
Overview of cocoapods.org show 
`Version 3.0.4, synced to MPAndroidChart #f6a398b`

but it's install 3.0.3 that not working with swift 4 (#2801)

**Comment by petester42** [comment]
try `pod repo update` and do a `pod install` again.

**Comment by ChaosPredictor** [comment]
@petester42, thanks. it's work.

**Comment by ArsalanWahid** [comment]
Tired the pod repo update with pod install getting version 3.0.2

**Comment by petester42** [comment]
Delete your Podfile.Lock and try again.

**Comment by ArsalanWahid** [comment]
Hey @petester42 Thank you

Surprising when nothing else was working, using the specific target worked ! 

**pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :tag => 'v3.0.4'**

Though Some issue with the process of installing the latest v3.0.4 via cocoapods for some users like myself still persists which leads to all sort of POD relates issues that I've read here. 

Hope this feedback helps future users.

-Regards

**Comment by ChaosPredictor** [comment]
Not sure if it's helpful but I'm using:
Xcode 9.0 beta 6
Swift 4.0
Cop 1.3.1

by default I got 3.0.3
after uninstall (remove from Podfile and `pod install`), install and update (`pod repo update`) it's update  to 3.0.4

**Comment by ArsalanWahid** [comment]
@ChaosPredictor  Finally got v3.0.4
