### ISSUE TITLE
A way to add values to labels on x axis?

### ISSUE THREAD

**Issue by beltik** [danielgindi/Charts#2903]
Hi, 

I have been struggle for hours, but i cant find solution.
I have pulse graph, that contain, for example, 30 entries.
What i want is, to add x axis labels which is hours, separate by 2.
So, it will be 0,2,4,6,8,10,12,14 etc.. up to 24
I can't find a way to set those values. Can you please help me?

**Comment by liuxuan30** [comment]
take a look at `computeAxisValues()` it generate the raw entries and used in valueFormatter. You can check `forceLabelEnabled` as well, or override `computeAxisValues` for your x axis.
