### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by SatishBirajdar007** [danielgindi/Charts#2904]
I am really a fan of your Chart.framework and created a 2 screen app and now want to submit my first (free) app on Appstore. But while submitting on AppStore, Apple asked if I have the right permission to use Chart.framework in Canada, USA, UK, and India. So was wondering to ask you, whether the framework is available for free or charged? If its free, I would love to donate some contribution towards your effort.
Thanks again for an amazing framework. Cheers 👍

**Comment by zjdavid** [comment]
It's under Apache-2.0 license, so feel free to use it in your app. It is free.

**Comment by SatishBirajdar007** [comment]
@zjdavid Thanks for your comment.
Actually, this is my first time submitting an application to iTunes. 
As you said its free, should I select "Yes" for both question, as shown in the attachment?

<img width="1049" alt="screen shot 2017-10-23 at 4 39 32 pm" src="https://user-images.githubusercontent.com/29895237/31912243-399da8a0-b811-11e7-94f8-62a9991574d8.png">

**Comment by liuxuan30** [comment]
It should be fine, apache and MIT will not cause trouble for you.

**Comment by SatishBirajdar007** [comment]
@liuxuan30 Okay sounds good. Thanks. :) 👍
