### ISSUE TITLE
How to disconnect data points? 

### ISSUE THREAD

**Issue by guanyanlin** [danielgindi/Charts#2905]
Excuse me,I want to know how to disconnect data points? 
can our this Charts get this function?

**Comment by liuxuan30** [comment]
Do you mean for line chart? I have an old request about this, however in Chart 3.0, it seems easier?
Just use different data set for each line segment. I found it might be easier to write a whole new "line breaking" feature.

**Comment by guanyanlin** [comment]
I do not understand the "line breaking",you just said...
and where is the "ine breaking"feterature?

**Comment by liuxuan30** [comment]
when you asked `disconnect data points`, it implies me it's for line chart, breaking one line into two.
There is no line breaking feature, just use two data sets for each line segment.

**Comment by guanyanlin** [comment]
Oh，ok！
Thank you so much.
