### ISSUE TITLE
LineChartDataSet Multi color

### ISSUE THREAD

**Issue by amrabdelaal** [danielgindi/Charts#2906]
I want to make LineChartDataSet support Multi color

**Comment by liuxuan30** [comment]
it does support multi colors:
```swift
@objc open func drawLinear(context: CGContext, dataSet: ILineChartDataSet)
{
        ...
        // more than 1 color
        if dataSet.colors.count > 1 {
```
check if it meet your goals.

**Comment by amrabdelaal** [comment]
@liuxuan30 Please I need more clarifications

**Comment by liuxuan30** [comment]
what clarifications? You can locate to the code and see how to draw multiple colors
