### ISSUE TITLE
Barchart DefaultValueFormatter dataSetIndex always 0

### ISSUE THREAD

**Issue by karthiknew01** [danielgindi/Charts#2907]
I'm using BarChart and displaying label over the plot, while setting ValueFormatter for the chartview using DefaultValueFormatter, dataSetIndex in stringForValue method is always 0. Currently using 3.0.1 library version.

**Comment by liuxuan30** [comment]
need more details, or reproduce with ChartsDemo.
Reopen it when you have more updates
