### ISSUE TITLE
how can I unhighlight any slice selected before in PieChart ?

### ISSUE THREAD

**Issue by SatishBirajdar007** [danielgindi/Charts#2908]
I am using, `pieChartView.highlightValue(x: aRandomInt, y: 0.0, dataSetIndex: 0)` to highlight a slice.

How can I unhighlight any (not specific slice) slice selected before in PieChart?

**Comment by liuxuan30** [comment]
just pass nil for highlight object I remember.

**Comment by SatishBirajdar007** [comment]
Ohk, Thanks. I tried the otherway, I used

`chartView.highlightValue(x: -1, y: -1, dataSetIndex: 0)`

:)

**Comment by codeliu6572** [comment]
chartView.highlightValue(x: -1, y: -1, dataSetIndex: 0)

:)
I tried and when dataSetIndex above zero, it not work.
