### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vudinhluat1802** [danielgindi/Charts#2910]
There is an issue in file AxisRendererBase.swift. I don't know why.

If you want to get more information, send me an email.
Email address: vudinhluat7394@icloud.com.

Please fix it. Thanks

![untitled](https://user-images.githubusercontent.com/22373743/32034988-60431216-ba40-11e7-861b-f65119b4ad66.png)

**Comment by liuxuan30** [comment]
what did you do? post the full stack trace, or reproduce it with ChartsDemo.
 But it looks like something wrong with your outside code. there is deinit method called, which seems should not happen when drawing.

Anyway, you should debug first as you have the crime scene.

**Comment by vudinhluat1802** [comment]
Sorry I don't know when it occurred. Furthermore I saw another bug that is associated with 'rects' of buffer. But it did not occurred frequent. 
You can close this issue, I will log issue when I know why it happens.

Thank a lot.

**Comment by liuxuan30** [comment]
it's just complains an unsafe mutable pointer in your log. however we are not sure what it points to. It can be mistake on your side releasing anything but you use it later. It's the first time I saw such crash. So, need your debug effort first.

**Comment by liuxuan30** [comment]
we don't know what the pointer points to.
based on what you said, it could be a mistake on your side, releasing some  objects but you refer it again later. It's my first time seeing such crash footprint, so we need your debug effort anyway.
