### ISSUE TITLE
Barchart with unique style

### ISSUE THREAD

**Issue by Ajithkattacherry** [danielgindi/Charts#2912]
Can I create a graph as given below?

![screen shot 2017-10-26 at 11 55 10 am](https://user-images.githubusercontent.com/14244319/32037829-b5f77018-ba44-11e7-9036-18c2a8f48e99.png)

**Comment by liuxuan30** [comment]
#1917

**Comment by Ajithkattacherry** [comment]
Thanks for the reply, Xuan.

I went through the latest git code. But couldn't find the implementation for rounded corners when I installed the Charts lib via cocoa pods. 

Can you help me if I missed any

**Comment by liuxuan30** [comment]
they are not merged. You have to put them in a sub class on your side.

**Comment by arvinndkumar** [comment]
@liuxuan30 i am using pod and unable to subclass it due to access protection level.
