### ISSUE TITLE
Use of unresolved identifier NSAttributedStringKey in Xcode 8.3.2 for swift 3

### ISSUE THREAD

**Issue by hanumants-iprogrammer** [danielgindi/Charts#2915]
Migration of code from swift 2.x to swift 3 on Xcode 8.3.2

- Previous version of Charts library for swift 2.x is:  2.3.0 

- Using Charts 3.0 for swift 3.0

Please suggest! 
![screenshot 2017-10-26 19 10 38](https://user-images.githubusercontent.com/15625569/32056132-7f876a14-ba81-11e7-96d9-52ddb4ba47a3.png)

**Comment by thierryH91200** [comment]
look at #2876
