### ISSUE TITLE
How to use IValueFormatter in stacked bar chart

### ISSUE THREAD

**Issue by hiralnaik** [danielgindi/Charts#2916]
Hi there 

I am trying to use IValueFormatter in stacked bar chart but dataSetIndex is always retuning 0. I want to display different text for different stacked bar. I have max 2 stacked bar. Value is coming properly but I want to display text on it.

`public func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String {
        
        if let index = chartValues.index(of: value) {
            formatter.numberStyle = .percent
            formatter.maximumFractionDigits = 0
            formatter.minimumIntegerDigits = 1
            print(dataSetIndex) //this return 0 ever time
            print(entry.x)
            print(entry.y)
            return "\(formatter.string(from: NSNumber.init(value: value))!)\n\(self.stringsValues[index])"
        }
        return ""
    }`

Any help.

Thanks

**Comment by liuxuan30** [comment]
how many data sets you have in the first place.. a stacked bar should only have one data set for sure..  Why don't you check stacked bar chart in ChartsDemo? It's already a good demo

**Comment by hiralnaik** [comment]
I checked that demo. It doesn't have that solution what I am looking for. I am display value + text on bar. In the current demo it displays only number with formatter.
For example 
I have values [10, 20] and I want to display on stack bar like this

10                                                       |                     20 
Vegetables                                        |                    Fruits 

Thanks

**Comment by liuxuan30** [comment]
two things:
1. it already have formatter, so you can format the string with percentage + value;
2. wrapping seems not supported yet. You might need to override `drawValues` to enable two line texts.

**Comment by hiralnaik** [comment]
That's right. But think about situation in this function, 
`public func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String` 

when value will be same how can I identify if the value is for 1st stack or 2nd stack. 

something like 
value for 1st stack = 0.5
value for 2ns stack = 0.5

**Comment by phanindra92** [comment]
let data = BarChartData(dataSet: set)
        let format = NumberFormatter()
        format.numberStyle = .none
        let formatter = DefaultValueFormatter(formatter: format)
        data.setValueFormatter(formatter)

**Comment by chinghoi** [comment]
> That's right. But think about situation in this function,
> `public func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String`
> 
> when value will be same how can I identify if the value is for 1st stack or 2nd stack.
> 
> something like
> value for 1st stack = 0.5
> value for 2ns stack = 0.5

I also encountered this problem, how did you solve it in the end?
