### ISSUE TITLE
How to draw a diagram above the axis labels?

### ISSUE THREAD

**Issue by populius** [danielgindi/Charts#2918]
How to draw a diagram above the axis labels
![img_5218](https://user-images.githubusercontent.com/2752484/32102419-684b01d8-bb46-11e7-870b-dfcc80d82ed0.PNG)

**Comment by liuxuan30** [comment]
I recommend you take a look at ChartsDemo first.

**Comment by populius** [comment]
mm nice answear, I'm watching a demo project, but cant' find information about this problem. Can you tell where to look?

**Comment by liuxuan30** [comment]
first is to tell what does not satisfy？I don't see your image is any different than line chart in terms of features

**Comment by populius** [comment]
![img_5226](https://user-images.githubusercontent.com/2752484/32361598-93b9185c-c094-11e7-968e-bda33601506e.jpg)

Axis labels drawn above lines. Can i draw labels under chart lines? @liuxuan30

**Comment by liuxuan30** [comment]
I think currently no. but you can easily override the draw method to swtich the order to:
```swift
        ...
        _xAxisRenderer.renderAxisLabels(context: context)
        _leftYAxisRenderer.renderAxisLabels(context: context)
        _rightYAxisRenderer.renderAxisLabels(context: context)

        context.saveGState()
        context.clip(to: _viewPortHandler.contentRect)
        renderer?.drawData(context: context)
        ...
```
