### ISSUE TITLE
Build framework from project

### ISSUE THREAD

**Issue by sbeff** [danielgindi/Charts#2919]
Hi all,
I'm using this fantastic framework to build a chart into my app, and I was wondering if I could build the framework selecting "General iOS Device" as build target, and then put the generated Charts.framework into my app's project, and add it in the embedded binaries. This is because I'd avoid to put the entire Charts project into mine.
Thanks!
Emanuele

**Comment by petester42** [comment]
You could use Carthage to do that for you. That is its purpose. If you want to do it manually you can too. It should work if you can find where the framework gets built to.

**Comment by liuxuan30** [comment]
yes if you don't need to touch the code, carthage can do that perfectly. But be careful if you encounter framework missing issue. Have to make sure the framework is copied with your app bundle. details can be seen on carthage README
