### ISSUE TITLE
y axis range not automatically recalculated when adding entry to data set

### ISSUE THREAD

**Issue by nickngithub** [danielgindi/Charts#2920]
Hi guys,

When I add a data entry to a entry data set of a line plot the y axis range of the chart data is not recalculated.

```
let dataSet = lineChartView.data!.getDataSetByIndex(0)
let dataEntry = ChartDataEntry(x: 12.0, y: 30.0) // where 30.0 > maximum of other y values
dataSet?.addEntryOrdered(dataEntry)
lineChartView.data?.calcMinMax() // if i do not call this the y axis range is wrong
lineChartView.notifyDataSetChanged()
```

I have to call `calcMinMax()` to recalculate the range of the y axis. The x axis seems to be fine.

Is it intended or a bug?

Best,
Nick

**Comment by liuxuan30** [comment]
it's intended. as you have add new data, you can call `lineChartView.data?.notifyDataChanged` actually. it will call calcMinMax() for you.
