### ISSUE TITLE
Gradient colour for stroke line horizantally .It is possible in  android 

### ISSUE THREAD

**Issue by NallapatiMalleswari** [danielgindi/Charts#2921]
![screen shot 2017-10-28 at 6 27 05 pm](https://user-images.githubusercontent.com/31246172/32134600-dcfa5afc-bc0d-11e7-8784-11a5b01af200.png)
In android it is like this  :   https://github.com/danielgindi/Charts/issues/537

**Comment by liuxuan30** [comment]
this is not android repo
