### ISSUE TITLE
Adding corner radius on top of Bar

### ISSUE THREAD

**Issue by richardadiguna** [danielgindi/Charts#2924]
Hi Everyone, 

I need some help for using this awesome library, i have some requirement to build a bar chart like this ;

![screen shot 2017-10-30 at 16 52 05](https://user-images.githubusercontent.com/28172187/32164821-356b111e-bd93-11e7-8727-a3dbc98cfb1d.png)

i have searched through the issues, read the demo project code, and try to google it. is there any capabilities to build a bar chart like that? I really need help for get done for it.

**Comment by liuxuan30** [comment]
looks you have to know how to draw graident; #2722 #1917
