### ISSUE TITLE
Bar chart does not start at zero.

### ISSUE THREAD

**Issue by ltonl** [danielgindi/Charts#2927]
anyone can help me?
I try several time to solve the problem
<img width="132" alt="screen shot 2560-10-30 at 21 11 09" src="https://user-
<img width="139" alt="screen shot 2560-10-30 at 21 14 28" src="https://user-images.githubusercontent.com/33226296/32175381-5ff0b8c0-bdb7-11e7-8a1a-d6311afd12d3.png">

this is my code

 func setChart(dataPoints: [String], values: [Double]) {
        barChartView.delegate = self
        barChartView.chartDescription?.enabled = false
        barChartView.highlightPerTapEnabled = false
        barChartView.drawValueAboveBarEnabled = false
        barChartView.fitBars = true
        barChartView.drawBarShadowEnabled = false
        barChartView.drawGridBackgroundEnabled = false
        barChartView.pinchZoomEnabled = false
        barChartView.doubleTapToZoomEnabled = false
//        barChartView.autoScaleMinMaxEnabled = true
//        barChartView.scaleYEnabled = false
//        barChartView.scaleXEnabled = false
        barChartView.animate(xAxisDuration: 0.5, yAxisDuration: 0.5, easingOption: .easeInBounce)
        
        let axisMinimum = 0.0
        let axisMaximum = 3.0
        
        let rightAxis = barChartView.rightAxis
        rightAxis.enabled = false
        rightAxis.axisMinimum = axisMinimum
        rightAxis.drawAxisLineEnabled = false
        rightAxis.drawGridLinesEnabled = false
        rightAxis.drawZeroLineEnabled = true
        
        let yAxis = barChartView.leftAxis
        yAxis.enabled = false
        yAxis.axisMinimum = axisMinimum
        yAxis.spaceBottom = 0.0
        yAxis.drawAxisLineEnabled = true
        yAxis.drawGridLinesEnabled = true
        yAxis.drawZeroLineEnabled = true
    
        let xAxis = barChartView.xAxis
        xAxis.drawLabelsEnabled = true
        xAxis.drawAxisLineEnabled = true
        xAxis.drawGridLinesEnabled = true
        xAxis.labelTextColor = .white
        xAxis.granularity = 1.0
        xAxis.centerAxisLabelsEnabled = true
        xAxis.axisMinimum = axisMinimum
        xAxis.axisMaximum = axisMaximum
        xAxis.labelPosition = .top
        
        let legend = barChartView.legend
        legend.enabled = false
        
        var dataEntries: [BarChartDataEntry] = []
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(values[i]), data: dataPoints as AnyObject?)
            dataEntries.append(dataEntry)
        }
                
        let chartDataSet = BarChartDataSet(values: dataEntries, label: nil)
        let chartData = BarChartData(dataSet: chartDataSet)
        chartData.setValueTextColor(NSUIColor.clear)
        barChartView.xAxis.valueFormatter = IndexAxisValueFormatter(values: dataPoints)
        barChartView.drawBordersEnabled = false
        barChartView.data = chartData
    
        var colors: [UIColor] = []
        colors = [zeroColor, firstColor, secondColor]
        chartDataSet.colors = colors
        chartData.barWidth = 1
    }

thank for your help

**Comment by liuxuan30** [comment]
try `yAxis.axisMinimum = 0`
