### ISSUE TITLE
Xcode 9.1 - Characters is deprecated

### ISSUE THREAD

**Issue by saldous** [danielgindi/Charts#2933]
7 new Xcode warnings:

> 'characters' is deprecated: Please use String or Substring directly

**Comment by thierryH91200** [comment]
see #2866

**Comment by saldous** [comment]
@thierryH91200 that issues was closed but not resolved... Xcode 9.1 is now GA and these warnings now show. Please re-open #2866

**Comment by liuxuan30** [comment]
closing this
