### ISSUE TITLE
line charts with many gradients according the value

### ISSUE THREAD

**Issue by AndreaMiotto** [danielgindi/Charts#2934]
is it possibile to draw a single line chart with different colors depending on the value and the transition between colors as gradient?

something like the image

<img width="511" alt="schermata 2017-11-01 alle 00 08 16" src="https://user-images.githubusercontent.com/11211914/32253003-dedf6cda-be98-11e7-855d-d47f466172e9.png">

**Comment by liuxuan30** [comment]
people are asking for this for a long time #537 . I plan to revisit that PR to see if we can pull it off.
