### ISSUE TITLE
xAxis value is started with 0 but it not coordinate with y axis 0 value

### ISSUE THREAD

**Issue by iOSTest321** [danielgindi/Charts#2935]
xAxis value is started with 0 but it not coordinate with y axis 0 value getting a space before the xAxis value
help me
![screen shot 2017-11-01 at 12 30 40 pm](https://user-images.githubusercontent.com/18207213/32263654-ea56c3ac-bf00-11e7-89d1-de31e2000c17.png)

**Comment by liuxuan30** [comment]
try `xAxis.axisMinimum = 0`
