### ISSUE TITLE
Errors after conversion to Swift4 NSAttributedStringKey

### ISSUE THREAD

**Issue by akanksharma** [danielgindi/Charts#2937]
Errors after conversion to Swift4
/..../Pods/Charts/Source/Charts/Renderers/XAxisRendererHorizontalBarChart.swift:360:71: Cannot convert value of type 'String' to expected dictionary key type 'NSAttributedStringKey'

**Comment by liuxuan30** [comment]
maybe try xcode 9.1. I just merged one for 9.1

**Comment by ahmadabudawod** [comment]
I have the same issue and my Xcode 9.1
