### ISSUE TITLE
when dataset value is increases then the graph value is misplace . and i am showing three bar in one group. and also show the  integer value in particular bar above.

### ISSUE THREAD

**Issue by Raj14737** [danielgindi/Charts#2938]

**Comment by liuxuan30** [comment]
can barely understand. give more details and we will update.
if you change your data set, call `chartData.notifyDataChanged`
for drawing values, check out ChartsDemo.

**Comment by Raj14737** [comment]
let take an example , if i have an data set {"jan", "feb" ,"mar" ,"apr" , "may", "june"}. and i set the graph as look and feel for setting 3 bar as a group.

2 - if data set value {"jan", "feb" ,"mar","apr" ,"may" ,"june" ,"july" ,"aug" ,"sep"} , then my whole view of graph is disturbed , and all bars are overlaped .

**Comment by liuxuan30** [comment]
give a screenshot. take a look at multiple bar chart btw. make sure bar space, group space, bar width formula sums to 1.0

**Comment by Raj14737** [comment]
![screen shot 2017-11-10 at 10 11 51 am](https://user-images.githubusercontent.com/33280908/32643245-12d1a80a-c600-11e7-8d55-167650517a2e.png)


this graph comes when data set value comes more than - 4

**Comment by Raj14737** [comment]
![screen shot 2017-11-10 at 10 13 04 am](https://user-images.githubusercontent.com/33280908/32643260-33a123d0-c600-11e7-9a45-95f43fb632f2.png)


this graph come when dataset value come - 4, because i will set (as above formula you said equal to 1),


and i used this type --

            let groupSpace = 0.16
            let barSpace = 0.05
            let barWidth = 0.23

**Comment by Raj14737** [comment]
![screen shot 2017-11-10 at 10 22 23 am](https://user-images.githubusercontent.com/33280908/32643381-177432be-c601-11e7-9ecf-2c77724a132c.png)

this graph comes - when i used this 

let groupSpace = 0.16
        let barSpace = 0.05
        let barWidth = 0.23
startPoint = 0

and when i used this method to found groupwidth -

let group_space = chartData.groupWidth(groupSpace: groupSpace, barSpace: barSpace)

**Comment by Raj14737** [comment]
i want to that it set perfectally , it dont be depended how many dataset it comes .

**Comment by liuxuan30** [comment]
I barely understand. check out charts demo, play with it first.
