### ISSUE TITLE
Change LineChartDataSet label color not value color.

### ISSUE THREAD

**Issue by zubingala** [danielgindi/Charts#2944]
`let line1 = LineChartDataSet(values: lineChartEntry, label: "TP Data")`

I want to change the label which is in my case "TP Data" color which is black. I don't want to change the value color.

**Comment by liuxuan30** [comment]
where do you display your label?

**Comment by coolcool1994** [comment]
By default it gets displayed in the bottom of the graph. Is there a way to change the color of the label of LineChartDataSet? (Funny my exact question was right here waiting for me.)

**Comment by liuxuan30** [comment]
The label here you refer the label on legend? I don't remember we support display data set label on the shape? 
if it's legend, then it's `legend.textColor`. Looks like you have to add an array to display different colors

**Comment by sabrinatuli** [comment]
Same. I want to change the label color. But couldn't.

**Comment by liuxuan30** [comment]
you need to override it with an color array.

**Comment by keshu1024** [comment]
chartView.legend.textColor = .white
