### ISSUE TITLE
Display high and low value in chart but Displayed one only

### ISSUE THREAD

**Issue by SagarDabhi** [danielgindi/Charts#2947]
![screen shot 2017-11-02 at 3 08 37 am](https://user-images.githubusercontent.com/21338586/32313851-30a5e110-bf7b-11e7-9f2f-f767862d821a.png)

trying to display high and low value on linechart but display only one value at a time
Code : 
            
```
var highlight: Highlight? = nil
highlight = Highlight(x: maxValx, y: MaxvaL, dataSetIndex: 0)
highlight = Highlight(x: minValx, y: minVaL, dataSetIndex: 0)
viewChart.highlightValue(highlight)
```

**Comment by liuxuan30** [comment]
don't understand. What you do want?

**Comment by SagarDabhi** [comment]
@liuxuan30 Thanks For your response, i wanna highlight two value in graph without touch , right now able to highlight only one value without touch.
hope you can help me.

Thanks.

**Comment by SagarDabhi** [comment]
@liuxuan30  understand or not?

**Comment by SagarDabhi** [comment]
@danielgindi  @liuxuan30  @feosuna1 @msanders  @franqueli  Please help me to solve this.

**Comment by liuxuan30** [comment]
don't abuse using `@`. use `@objc open func highlightValues(_ highs: [Highlight]?)` to highlight by code

**Comment by SagarDabhi** [comment]
Hello Liuxuan, Sorry but i did't want say what you undestand.

I already highlight the value in graph but my question is how i highlight the two value at a time?

**Comment by liuxuan30** [comment]
and I already said, use `@objc open func highlightValues(_ highs: [Highlight]?)` to highlight multiple values.

**Comment by SagarDabhi** [comment]
Thank you so much @liuxuan30, really I didn't see this is array.
