### ISSUE TITLE
PieChart value labels are overlaping when values are between 0 to 9

### ISSUE THREAD

**Issue by serhatsezer** [danielgindi/Charts#2948]
Hi,

I'm using PieChart but when values are between 0 to 9 side by side they are overlaping. Is there any solution to fix this? I've added screenshot and my implementation below.

<img width="309" alt="screen shot 2017-11-02 at 15 10 38" src="https://user-images.githubusercontent.com/1409961/32326863-77159b26-bfe5-11e7-83a3-b83189c06e96.png">

**Here it is my implementation:**

`let chartView = PieChartView()
        let screenFrame = view.frame
        chartView.frame = CGRect(x: 0, y: 10, width: screenFrame.width, height: screenFrame.height - 100)
        chartView.usePercentValuesEnabled = false
        chartView.drawSlicesUnderHoleEnabled = false
        chartView.chartDescription?.enabled = false
        chartView.setExtraOffsets(left: 25.0, top: 10.0, right: 25.0, bottom: 0.0)
        chartView.drawCenterTextEnabled = true
        chartView.noDataText = "Veri girişi yok."
        chartView.drawHoleEnabled = false
        chartView.rotationAngle = 10.0
        chartView.rotationEnabled = true
        chartView.highlightPerTapEnabled = true
        chartView.entryLabelColor = .white;
        chartView.entryLabelFont = UIFont.defaultAppFont(size: 18)
        
        
        let l = chartView.legend
        l.horizontalAlignment = .center;
        l.verticalAlignment = .bottom;
        l.orientation = .vertical;
        l.drawInside = false
        l.xEntrySpace = 7.0
        l.font = UIFont.defaultAppFont(size: 16)
        l.yEntrySpace = 0.0
        l.yOffset = 0.0
        
        var values = [PieChartDataEntry]()
        var colors = [UIColor]()
      
        for item in reports {
            let color = UIColor.hexString(hex: item.textColor)
            colors.append(color)
            let pieChartData = PieChartDataEntry(value: Double(item.carCount), label: item.carText)
            values.append(pieChartData)
        }
        
        let dataSet = PieChartDataSet(values: values, label: "")
//        dataSet.xValuePosition = .outsideSlice
        dataSet.yValuePosition = .outsideSlice
        dataSet.valueLinePart1Length = 0.6
        dataSet.valueLinePart2Length = 0.9
        dataSet.valueLineColor = UIColor.bgBlackColor
        dataSet.sliceSpace = 1.0
        dataSet.colors = colors
        dataSet.entryLabelColor = UIColor.clear
        
        
        let data = PieChartData(dataSet: dataSet)
        data.setValueFont(UIFont.defaultAppBoldFont(size: 15))
        data.setValueTextColor(UIColor.black)
        chartView.data = data;
        chartView.highlightValues(nil)
        
        chartView.animate(yAxisDuration: 0.95, easingOption: .easeInExpo)
        view.addSubview(chartView)`

**Comment by jackCaptian** [comment]
Is the problem solved, brother

**Comment by liuxuan30** [comment]
I don't think this can be easily solved, as the slices are too thin to hold a font that has a bigger height. Think about the math. Either you manually change the offset, if overlap happens. But there will always be corner cases, so.. 
but I will keep this open if someone have better solutions.

**Comment by liuxuan30** [comment]
crap, I just found https://github.com/danielgindi/Charts/pull/2062, seems a PR to hide small slice labels. but as I said, it solve the issue by hiding the label, not showing two labels without overlap. up to you.

**Comment by serhatsezer** [comment]
@liuxuan30 Yeah. I saw this when I first face this issue. But I think this can be solved if pie chart a little bigger. But this approach makes other pieces shrink their size. I did some tweaks in this project but I couldn't make it. I don't have enough math knowledge to solve this. :/

**Comment by liuxuan30** [comment]
how do you want to make the pie chart bigger? in terms of radius? It has to be restrained with the contentRect, and the labels, and the parent view.

**Comment by serhatsezer** [comment]
@liuxuan30 Nope. I don't want to make the whole chart bigger I just want to make only pieces who has %1 percentage value a bit bigger than others. Thus label can appear without any overlapping.

**Comment by liuxuan30** [comment]
the arc length and eventually  depends on the radius as well

**Comment by jjatie** [comment]
I think the solution would be to move the label further away from the chart to prevent it from overlapping. I don't think anyone has time to implement a solution for this, and I don't think it's critical.
@serhatsezer It would be appreciated if you can PR an implementation and discussion can continue there.
