### ISSUE TITLE
Add Two Custom Marker views on linechart graph

### ISSUE THREAD

**Issue by NallapatiMalleswari** [danielgindi/Charts#2951]
I want to add two marker images (ring,label type image)in linegraph, how to do like in the bellow image.
![screen shot 2017-10-28 at 6 27 05 pm](https://user-images.githubusercontent.com/31246172/32364932-a7640250-c09d-11e7-8082-ab52da99634d.png)

**Comment by liuxuan30** [comment]
just create your own chart marker class.
