### ISSUE TITLE
Remove or change line color in chart

### ISSUE THREAD

**Issue by guzfernandez** [danielgindi/Charts#2953]
Hello. Is there a way to remove these lines? Or at least change their color?
Thanks.

![30aa958087664cacba013a3fc650a605](https://user-images.githubusercontent.com/20564272/32377261-cb1f0518-c085-11e7-9006-cc93033fe164.jpg)

**Comment by liuxuan30** [comment]
is this drawn by our library? I don't remember.. but seems like a limit line? grid line? axis line?

**Comment by guzfernandez** [comment]
Tried everything, but none of them work.

**Comment by liuxuan30** [comment]
well how do you draw it with this library? Give code that we can draw in ChartDemo. I don't remember we have this.
