### ISSUE TITLE
Cannot align chart description on left instead of right

### ISSUE THREAD

**Issue by dbrisinda** [danielgindi/Charts#2956]
Trying to align the chart description text to the lower left of the chart instead of the default lower right of the chart, but neither of these work. Text stays on right, and then behaves badly (truncated).

    self.chartView.descriptionTextAlign = NSTextAlignmentLeft;

and

    self.chartView.chartDescription.textAlign = NSTextAlignmentLeft;

**Comment by liuxuan30** [comment]
did you set `_chartView.chartDescription.enabled = YES;`?

**Comment by dbrisinda** [comment]
Yes. For clarification, the description text is showing up, but it's not being aligned to the left when that alignment mode is indicated.

**Comment by liuxuan30** [comment]
please post a screenshot. I suspect your drawing rect is not on left, so it looks like not aligned.
check `@objc internal func drawDescription(context: CGContext)`
```swift
            position = CGPoint(
                x: frame.width - _viewPortHandler.offsetRight - description.xOffset,
                y: frame.height - _viewPortHandler.offsetBottom - description.yOffset - description.font.lineHeight)
```
you can stroke the rect or draw the position so you know where it starts. I don't think it's a bug.
