### ISSUE TITLE
Marker with multiple datasets

### ISSUE THREAD

**Issue by montagao** [danielgindi/Charts#2962]
Is there an easy way to implement a custom marker with multiple datasets such that it shows the value of a point for each dataset? Something like below.
<img width="409" alt="screen shot 2017-11-01 at 10 28 53 am" src="https://user-images.githubusercontent.com/9814181/32455120-313b1cb8-c2d6-11e7-817e-367de7fa01c7.png">

Thanks!

**Comment by liuxuan30** [comment]
the easiest way is you write your own marker and add some methods to pass the data to marker I think.

**Comment by Boobesh** [comment]
how I give different colors to different datasets.

**Comment by thierryH91200** [comment]
[RectMarker.swift.zip](https://github.com/danielgindi/Charts/files/1702846/RectMarker.swift.zip)

and look the movie  #3197 not the issue
this is just a begin
