### ISSUE TITLE
How can I don't draw lines when data absent at some point?

### ISSUE THREAD

**Issue by willard1218** [danielgindi/Charts#2968]
If I have frequently data, but sometimes data absent at some point.
For example:

<img width="338" alt="2017-11-08 10 34 11" src="https://user-images.githubusercontent.com/14361902/32529215-398ea5c2-c472-11e7-9562-6183932b5574.png">

The interval of the dataset are same, in this case is 1.
So the data absent at x = 5, 6.

How can I don't draw line between x = 4 and x = 7 ?
Just like this:

<img width="338" alt="2017-11-08 10 34 11" src="https://user-images.githubusercontent.com/14361902/32529217-3d6c22a0-c472-11e7-9ac0-453aaa1a3a50.png">

**Comment by liuxuan30** [comment]
create two data sets for each line segment.

**Comment by willard1218** [comment]
If I have data at these point: 
x = 0, 1, 2
x = 4, 5
x = 8, 9

So the data absent at x = 3, 7 

then I have to create three data sets?

**Comment by liuxuan30** [comment]
I'm afraid so. one set for one line segment. I used to add this feature, however it's kind of buggy when thinking about filling beneath line area, so the workaround is use multiple data sets so far.

if you don't need filling, that's easier you can just override `drawLinear` to add those break points. warning: you have to fully understand how it works and then you know how to break the lines.

**Comment by willard1218** [comment]
Finally, I modify the `LineChartRenderer.swift`,
here is the [change](https://gist.github.com/willard1218/42b2047f2babde2e679f21fee0adf026/revisions)

I define data not existed if y == -999,
So, when y = -999, I just `move(to: pt)` instead of `addLine(to: pt)`.

Here is result 
<img width="331" alt="2017-11-15 10 04 43" src="https://user-images.githubusercontent.com/14361902/32815026-ca0a5bd0-c9ec-11e7-814c-042843cbca08.png">

The dataSet of Heartbeat are [80,90,-999,80,68,-999,-999,95]

**Comment by liuxuan30** [comment]
you can use `NSNotFound` instead of -999. have you tested both positive values and negative values together? As I said, evil in the filling part.

**Comment by willard1218** [comment]
Yes, i will use NSNotFound instead of -999.
As you said, when I fill the chart.
<img width="331" alt="2017-11-15 10 04 43" src="https://user-images.githubusercontent.com/14361902/32815407-f00b431a-c9ee-11e7-8c79-d357c5c88a10.png">
the green area has fill color, but I don't want this.
So this is a problem...
