### ISSUE TITLE
PieChart:- PieChart not completely show. 

### ISSUE THREAD

**Issue by pavanpky** [danielgindi/Charts#2972]
when i'm set the PieChart Value but some case not complete show like that type?

![screen shot 2017-11-09 at 12 16 01 pm](https://user-images.githubusercontent.com/33508716/32592003-d7022024-c547-11e7-9e2d-785c113597ec.png)

**Comment by liuxuan30** [comment]
seems your colors or data has issues? a 119% slice in pie chart??
