### ISSUE TITLE
Pie chart monochrome or gradient fill not support 

### ISSUE THREAD

**Issue by shubhamKhelfie** [danielgindi/Charts#2973]
hii i am trying to fill piechartdataset with gradient or monochrome but i think it is not supporting the both of the above fills any suggestion to do like this image 
![screen shot 2017-11-09 at 4 08 19 pm](https://user-images.githubusercontent.com/33124478/32601329-433b52fe-c568-11e7-9fd7-8e7bad2a3b58.png)

**Comment by liuxuan30** [comment]
take a look at pie chart renderer. 
`@objc open func drawDataSet(context: CGContext, dataSet: IPieChartDataSet)` already created each slice rects, so you can start from there and add some gradient?
```swift
...
                    path.closeSubpath()
                    
                    context.beginPath()
                    context.addPath(path)
                    context.fillPath(using: .evenOdd)
...
```

**Comment by AlphaPranav-del** [comment]
How to add gradient colour instead of the above code, Can you give me an example? I have tried but didn't get any solution.
