### ISSUE TITLE
Stacked bar chart value label clipped 

### ISSUE THREAD

**Issue by BunsSlider** [danielgindi/Charts#2974]
I changed demo StackedBarChartViewController as follows:
1. Set Bottom Space Constraint of ChartView to 300
2. Set _chartView.drawValueAboveBarEnabled = YES;
3. Set data value font size to 12

Value label of second bar is clipped now

![screenshot](https://user-images.githubusercontent.com/739803/32601582-2b8f2982-c554-11e7-83ff-dba2479a4303.png)

How can I make value label always visible with any font size and ChartView height?

**Comment by liuxuan30** [comment]
turn on `clipValuesToContentEnabled`

**Comment by BunsSlider** [comment]
`clipValuesToContentEnabled` is false by default, so `_chartView.clipValuesToContentEnabled = NO;` doesn't change anything

**Comment by liuxuan30** [comment]
I double check your question again. can you debug `drawValues` if
```swift
if !viewPortHandler.isInBoundsY(rect.origin.y)
                                || !viewPortHandler.isInBoundsLeft(x)
                            {
                                continue
                            }
```
this is not met? I suspect viewPortHandler.isInBoundsY(rect.origin.y) is false

**Comment by MasterWatcher** [comment]
```
if !viewPortHandler.isInBoundsY(rect.origin.y)
                                || !viewPortHandler.isInBoundsLeft(x)
                            {
                                continue
                            }
```
from BarChartRenderer calls only if `!dataSet.isStacked` or `// we still draw stacked bars, but there is one non-stacked in between`. I have stacked bars only so this code doesn't even call.
