### ISSUE TITLE
ScatterChartDataSet troubles with alignments.

### ISSUE THREAD

**Issue by ThinkwikDev** [danielgindi/Charts#2976]
Dots in charts are not aligning up proper with actual dates.
Some of dots are working proper with dates and some off left, some off right.

In screen shot, you can see plot with value 120 is aligned proper but other dots are misplaced.
Can you please help out on this ?

![unadjustednonraw_thumb_2](https://user-images.githubusercontent.com/33564824/32686781-232760be-c6d2-11e7-842c-ac7e2debda9d.jpg)

**Comment by ThinkwikDev** [comment]
Is there anyone who can help out in this ?

**Comment by liuxuan30** [comment]
did you check if the circle center and your x grid line share the same value? otherwise there will be offset, as axis label is not the same as your data value.
maybe override `computeAxisValues` to make `axis.entries` be your data values, instead of calculating one for you.
