### ISSUE TITLE
What is the compatible version with Xcode 8.3.3 ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [danielgindi/Charts#2977]
I'm using Xcode 8.3.3 I had a lot of problems during the compilation !
Is there any idea how to solve this without upgrading to swift 4 ?

**Comment by liuxuan30** [comment]
check old releases. like 3.0.2

**Comment by yigitserin** [comment]
When I try to install 3.0.2 via Pods, it installs 3.0.5 by default for some reason. Any idea why this happens?
