### ISSUE TITLE
ChartViewDelegate

### ISSUE THREAD

**Issue by alimardani1994** [danielgindi/Charts#2978]
Value of type 'ViewController' does not conform to 'ChartViewDelegate' in assignment

I've implement ChartViewDelegate but horizontalbarchart cannot recognise it and show me above error.

**Comment by liuxuan30** [comment]
Check out ChartsDemo for ref.

**Comment by alimardani1994** [comment]
class RiseAndFallViewController: UIViewController,ChartViewDelegate {
 func chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: Highlight) {
        print("")
    }

    @IBOutlet weak var RiseAndFall: HorizontalBarChartView!
override func viewDidLoad() {
RiseAndFall.delegate = self
}
}

this is my code, and I'm getting above error, could you help me?
