### ISSUE TITLE
Showing .0, .00 accoding the the decimal places insted of 0 in graphs

### ISSUE THREAD

**Issue by CosmicYogi** [danielgindi/Charts#2987]
When I am plotting the values in graphs then it is showing ".00" or ".0" when there are no values at the moment in LineChart.

It shows 0 if there are values with one decimal else it shows ".0" if there are values with one decimal else it shows ".00" if there are values with two decimals

Images are added for the reference.
<img width="186" alt="screen shot 2017-11-13 at 8 23 05 pm" src="https://user-images.githubusercontent.com/7416058/32732140-b77cf6a8-c8b1-11e7-94ef-a9a7a7196085.png">
<img width="188" alt="screen shot 2017-11-13 at 8 23 16 pm" src="https://user-images.githubusercontent.com/7416058/32732141-b8cce84c-c8b1-11e7-88d2-6c9d0eaa1d34.png">
<img width="185" alt="screen shot 2017-11-13 at 8 23 25 pm" src="https://user-images.githubusercontent.com/7416058/32732142-b90b40d8-c8b1-11e7-824f-f2b1c3631ee2.png">

What I want is I want it to be either 0.00 or the best can be done is it can be "0" in every case when the value of the graph is 0.

**Comment by liuxuan30** [comment]
use valueFormatter will do the job.

**Comment by CosmicYogi** [comment]
Thanks man.
Finally worked.

**Comment by lee727n** [comment]
how to resove this problem , i meet the same problem . how to  control every point Y value shows 0; i don't know how to use valuefomatter. i think this function use in Y axis . don't use in point Y

**Comment by fanmaoyu0871** [comment]
> how to resove this problem , i meet the same problem . how to control every point Y value shows 0; i don't know how to use valuefomatter. i think this function use in Y axis . don't use in point Y

i also  have this question.
