### ISSUE TITLE
Line Chart View not drawn because Date values in xAxis (not sorted Ascending/Descending) ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [danielgindi/Charts#2988]
I'm using version  `3.0.2` for swift 3
I have this format for the date from the api as `String` : `"2017-11-04 16:48:55"`

       ["2017-11-09 14:22:54","2017-11-09 14:22:07","2017-11-09 14:21:20","2017-11-04 18:58:01","2017-11-04 16:48:55","2017-11-04 16:35:00"]
So I convert the string to date through formatter
             
            let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd HH:mm:ss"
            dateFormatter.timeZone = TimeZone(abbreviation: "GMT+0:00")

            let date = dateFormatter.date(from: updatedAt)
            let timeInerval = date?.timeIntervalSince1970
            let hour = Int(timeInerval!)
            dates.append(Double(hour))

if I printed the dates array I'll get :
            
      [1510237374.0, 1510237327.0, 1510237280.0, 1509821881.0, 1509814135.0, 1509813300.0]

            let dateFormatterForXAxis = DateValueFormatter()
            chartView.xAxis.valueFormatter = dateFormatterForXAxis

where DateValueFormatter class :

            import Foundation
            import Charts

            class DateValueFormatter: NSObject, IAxisValueFormatter {
    
                var dateFormatter: DateFormatter!
    
                override init() {
                    dateFormatter = DateFormatter()
                    dateFormatter.dateFormat = "h"
                }
    
                func stringForValue(_ value: Double, axis: AxisBase?) -> String {
                    return dateFormatter.string(from: Date(timeIntervalSince1970: value))
                }
            }

The chartView haven't drawn, because the values not sorted Ascending/Descending
Any ideas how to solve this issue ?

**Comment by liuxuan30** [comment]
seems you have to make it ordered?

**Comment by Mohammed-Eliass** [comment]
@liuxuan30  when I use something like `xAxisValues = [12,23,44,10,11,22]` the chat didn't draw,
when I user sorted array the chart drawn with no sweat.

**Comment by liuxuan30** [comment]
need to take a look at Xbounds how it calculates form your x values. But I guess we don't support this. imaging a line that will turn back, kind of wierd?

**Comment by Mohammed-Eliass** [comment]
Thanks for your time man, But I solved it 2 days ago with `ChartDataEntry(x: ,y: ,data:)` where I generate the values of x through `for` loop then send the date in `data` parameter.
and inside the balloon marker I show the date and the price.

Feel free to close this issue ! :)
