### ISSUE TITLE
How to align yAxis at zero point?

### ISSUE THREAD

**Issue by jonasman** [danielgindi/Charts#2989]
I have the following line chart with 2 datasets. One data set is dependent on the left yAxis the other one on the right yAxis.

Now i want them both to have the zero value in the same line. 
The rest of the chart doesn't need to be aligned, only the zero line.
How can i do that?

Code:
```swift
    let speedLine = LineChartDataSet(values: speedEntries, label: "Speed")
    speedLine.colors = [UIColor.white]
    speedLine.drawCirclesEnabled = false
    speedLine.axisDependency = .left

    let powerLine = LineChartDataSet(values: powerEntries, label: "Power")
    powerLine.colors = [UIColor.green]
    powerLine.drawCirclesEnabled = false
    powerLine.axisDependency = .right

    let data = LineChartData()
    data.addDataSet(speedLine)
    data.addDataSet(powerLine)

    chartView.data = data
    chartView.xAxis.labelTextColor = UIColor.white
    chartView.xAxis.labelCount = 20
    chartView.leftAxis.labelTextColor = UIColor.white
    chartView.rightAxis.labelTextColor = UIColor.green
    chartView.legend.textColor = UIColor.white

    chartView.chartDescription?.text = ""
```

![iczja](https://user-images.githubusercontent.com/1762910/32746725-30aa8772-c8bf-11e7-9a14-546b4f2537c1.jpg)

**Comment by liuxuan30** [comment]
because you are using different axis, so the axis range is different as well. you have to make sure both axis share the same axis range, like setting `axisMinimum` and `axisMaximum`.

**Comment by jonasman** [comment]
Hi @liuxuan30 maybe i didnt explain correctly.

What i want is this:
![wind-speed-frequency-distribution-diagram](https://user-images.githubusercontent.com/1762910/32849452-d8a29b58-ca37-11e7-9a6f-274abb90f94e.png)

2 scales but the zero must be on the same line. 
Is it possible on this library?

I dont want to make max and min the same because that would be the same as having just one yAxis.

**Comment by liuxuan30** [comment]
set both yAxis.axisminiMum = 0

**Comment by TouchFriend** [comment]
My solution is to set `axisMinimum` and `axisMaximum`, keep the zero lines in the middle.

/// 更新左右轴的值范围
/// @param chartView BarLineChartViewBase示例
- (void)updateLeftRightAxisRange:(BarLineChartViewBase *)chartView {
    ChartData *chartData = chartView.data;
    CGFloat leftAxisMax = [chartData getYMaxWithAxis:AxisDependencyLeft];
    CGFloat leftAxisMin = [chartData getYMinWithAxis:AxisDependencyLeft];
    CGFloat rightAxisMax = [chartData getYMaxWithAxis:AxisDependencyRight];
    CGFloat rightAxisMin = [chartData getYMinWithAxis:AxisDependencyRight];
    // 左右两轴的最小值是否都大于等于0
    BOOL biggerZeroFlag = leftAxisMin >= 0 && rightAxisMin >= 0;
    // 设置左轴值范围
    CGFloat leftAxisAbsoluteMax = MAX(fabs(leftAxisMax), fabs(leftAxisMin));
    leftAxisMax = leftAxisAbsoluteMax;
    leftAxisMin = biggerZeroFlag ? 0 : -leftAxisMax;
    [self updateYAxisRange:chartView.leftAxis dataMin:leftAxisMin dataMax:leftAxisMax];
    // 设置右轴值范围
    CGFloat rightAxisAbsoluteMax = MAX(fabs(rightAxisMax), fabs(rightAxisMin));
    rightAxisMax = rightAxisAbsoluteMax;
    rightAxisMin = biggerZeroFlag ? 0 : -rightAxisMax;
    [self updateYAxisRange:chartView.rightAxis dataMin:rightAxisMin dataMax:rightAxisMax];
}

/// 更新y轴值范围
/// @param yAxis y轴
/// @param dataMin 数据最小值
/// @param dataMax 数据最大值
- (void)updateYAxisRange:(ChartYAxis *)yAxis dataMin:(CGFloat)dataMin dataMax:(CGFloat)dataMax {
    CGFloat range = fabs(dataMax - dataMin);
    CGFloat topSpace = range * yAxis.spaceTop;
    yAxis.axisMaximum = dataMax + topSpace;
    CGFloat bottomSpace = range * yAxis.spaceBottom;
    // 左右轴最小值都大于0，才设置最小值为0
    yAxis.axisMinimum = dataMin == 0 ? 0 : MIN(dataMin - bottomSpace, 0);
}

All values are greater than 0:
<img width="432" alt="QQ20201214-180241@2x" src="https://user-images.githubusercontent.com/17745878/102067913-b887dd80-3e36-11eb-981b-3ed95c17ae41.png">

There are values less than 0:
<img width="389" alt="QQ20201214-180319@2x" src="https://user-images.githubusercontent.com/17745878/102067998-d81f0600-3e36-11eb-9bd8-63e5714c3efb.png">
