### ISSUE TITLE
Crashing in X-axis render method.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [danielgindi/Charts#3004]
Hi,

I am facing a crash issue in Charts lib that occurs from some kind of method call in the library as in the below snap:

<img width="449" alt="screen shot 2017-11-14 at 11 24 53 am" src="https://user-images.githubusercontent.com/15869731/32765080-e22ae5cc-c92e-11e7-88ab-99ae88e0ac82.png">

The crash was reported in xAxisRenderer.drawLabels(). Couldn't gather much info about this. Any idea on why this crash could have happened.

**Comment by liuxuan30** [comment]
well we need the stack trace and error message.

**Comment by GABHISEKBUNTY** [comment]
I am closing this issue as this was an issue of updating Charts UI from background thread rather from main thread.
