### ISSUE TITLE
How can I scroll to previous data?

### ISSUE THREAD

**Issue by willard1218** [danielgindi/Charts#3006]
I have a frequently data.
Just like that:

![nov-14-2017 14-49-38](https://user-images.githubusercontent.com/14361902/32767087-d1a37188-c94c-11e7-8e91-e53d1be575a3.gif)

The data will not update when I click stop monitor button.
how do I scroll from right to left to view previous data ?

The only way can scroll when I zoom out the chartView.
But I don't want to zoom out the chartView.

In my project, I will drop first data after 7th data enter,
because I would like the interval of xAxis are always same.
so the xAxis.axisMinimum will be change when data increase,
but I think that is correct way, 
I don't like drop any data because when I click stop monitor button,
I would like scroll from right to left to view previous data.

So i would like : 
1. The interval of xAxis are always same.
2. The visible data count <= 6, always
3. when I click stop monitor button, I can scroll from right to left to view previous data.

**Comment by liuxuan30** [comment]
`moveViewToAnimated` and `moveViewToX`

**Comment by willard1218** [comment]
The data continues to come in, 
if I don't drop first data after 7-th data come in,
The chart view will become: 

![nov-15-2017 10-57-21](https://user-images.githubusercontent.com/14361902/32816607-81e58976-c9f4-11e7-92d3-5e998e46b65a.gif)

but I would like when 7-th data come in, 1-st data will disappear in chartView,
when 8-th data come in, 2-nd data will disappear in chartView,

The max data count of chart view is 6.
and I click stop monitor button, I can scroll from right to left to view previous data.

How can I do this?

**Comment by liuxuan30** [comment]
have you tried `setVisibleXRange`?

**Comment by willard1218** [comment]
Finally, I got a solution.

```swift
let numOfVisiableData : CGFloat = 6
let scaleX = CGFloat(dataSet.values.count) / numOfVisiableData

chartView.setScaleMinima(scaleX, scaleY: 1.0)
chartView.xAxis.axisMinimum = xValueOfLastEntry - (numOfVisiableData - 1) * intervalOfX
```
