### ISSUE TITLE
Error NSAttributedStringKey.font on Xcode 9.1 Swift 4 with Charts (3.0.4)

### ISSUE THREAD

**Issue by amycheong19** [danielgindi/Charts#3014]
Searched with all the issues in here and stackoverflow but I still can't find the latest version (3.0.4) compatible with current Xcode 9.1 Swift 4. There is one similar ticket but it has been closed and no longer being attend to. 

<img width="1093" alt="screen shot 2017-11-16 at 4 12 12 pm" src="https://user-images.githubusercontent.com/9781961/32880525-f27628c2-cae8-11e7-8da2-a734bff629c5.png">

**Comment by CHENDONGY** [comment]
I also encountered the same problem, the language my project uses is OC. Have you solved this mistake, what is the solution?

**Comment by amycheong19** [comment]
@CHENDONGY  I solved it by switching it to 4.0 for the charts framework. I was switching to Swift 4 on my pods hence the errors were still there.
<img width="716" alt="screen shot 2017-11-17 at 9 25 22 am" src="https://user-images.githubusercontent.com/9781961/32924784-44bc358c-cb79-11e7-84d2-bb15b6b2e064.png">

Proceed to close this ticket now.

**Comment by Prathapreddy26** [comment]
Please help me out with this error!!!

            NSDictionary(object: UIFont(name: "Roboto-Medium", size: 14)!,forKey: NSAttributedStringKey.font as NSCopying) as? [String : Any];

Error showing like this...

Cannot assign value of type '[String : Any]?' to type '[NSAttributedStringKey : Any]?
