### ISSUE TITLE
Swift 4.0.2 not compatible

### ISSUE THREAD

**Issue by carlos0193** [danielgindi/Charts#3015]
Hi, Recently i update my xcode, when open xcode show this error.
what i can do?

![screen shot 2017-11-16 at 4 34 22 pm](https://user-images.githubusercontent.com/33667509/32923482-aab037ae-caec-11e7-8156-bffc446c9aa8.png)

**Comment by petester42** [comment]
You have to rebuild charts when a new swift version is released because it is not ABI stable yet. It sucks but that is how it works right now. If you are using carthage or cocoapods then rerunning the install commands for each should do the trick.
