### ISSUE TITLE
Installation error through cocapods

### ISSUE THREAD

**Issue by Geethanjali14** [danielgindi/Charts#3016]
My CocoaPods all work fine until I try to install a new one. If I try to install a new pod, then there are several issues in charts pod, else it works fine. How do I overcome it? The errors show up as below:
![screen shot 2017-11-16 at 2 46 21 pm](https://user-images.githubusercontent.com/18215847/32929040-496dd46c-cb7b-11e7-9a1c-1f30620562a5.png)

My pod is as below:

`
platform :ios, '9.0'
use_frameworks!

target 'Tranquil' do
   pod 'GooglePlaces'
  pod 'UICircularProgressRing', '~> 1.7'
  pod 'Alamofire', '~> 4.5'
  pod 'Charts', '~> 3.0'
end`

**Comment by petester42** [comment]
What version of xcode are you using?

**Comment by keeper4** [comment]
the same Version 9.1 (9B55) (Release)

**Comment by pardhu423** [comment]
I am also getting the mentioned errors in Charts library after adding new pod.

**Comment by Geethanjali14** [comment]
Is it necessary to convert to swift 4? It works fine with swift 3.2 until a new pod is added. When a new pod is installed these errors appear.

**Comment by petester42** [comment]
It’s not. Just point to the swift 3.2 version explicitly. It’s 3.0.3.

**Comment by petester42** [comment]
For the issue. Running a pod install again when your project is set to swift 4 should fix this and make charts use swift 4. Please check with cocoapods if you still have issues.
