### ISSUE TITLE
饼状图数组有3个值,怎么设置只显示2个值的百分比

### ISSUE THREAD

**Issue by China-meng** [danielgindi/Charts#3020]
饼状图数组有3个值,怎么设置只显示2个值的百分比
比如 let arr = [10,15,25]
我想让饼状图的UI只显示前两条数据: 
10 / 50 = 20% 
15 / 50 = 30% 
并且这两条数据填满整个饼状图
第三条数据50%在饼状图上不显示
请问这个可以实现吗

**Comment by liuxuan30** [comment]
don't put 25 in you arr in the first place.
But:
10 takes 20% and 15 takes 30%, what about the other 50% of pie?
why you don't want to display one value but want to put it in a pie chart anyway? it makes no sense.
