### ISSUE TITLE
How to change position xAxis Label on the Top Bar Chart ?

### ISSUE THREAD

**Issue by durul** [danielgindi/Charts#3022]
I have a custom design HorizontalBarChartView, I build this design with UIBezierPath and CAShapeLayer. I am sharing below. 

![simulator screen shot - iphone 6s plus - 2017-11-17 at 18 53 10](https://user-images.githubusercontent.com/1297785/32984878-efd22d88-cc7c-11e7-8ed4-0a27c36c2279.png)

I worked with HorizontalBarChartView and closed to same looks. 

![simulator screen shot - iphone 8 plus - 2017-11-18 at 16 25 52](https://user-images.githubusercontent.com/1297785/32984891-36b86384-cc7d-11e7-8b36-f3efd42655df.png)

My questions is **how to change xAxis Label position to generate on BarChart ?** I try to generate cars model name on BarCharts

**Comment by liuxuan30** [comment]
looks like we don't support putting x axis labels on top of each bar like your first image.
but we do have `.bottomInside` similarly. you can override the method to apply some x/y offset.

however, remember not every bar is thin like this and leave you much blank space for the labels. It will take the whole `contentRect` to draw all bars, so the more bars you have, the thinner the bar is, and less bar space as well.

**Comment by jw10126121** [comment]
May I ask, how did you achieve it? I have the same problem now. Does not work after xAxis. YOffset is set.
