### ISSUE TITLE
Multiple charts in a collection view

### ISSUE THREAD

**Issue by jeyashrinatarajan** [danielgindi/Charts#3028]
Is it possible to create 5 different charts(bar chart,pie chart,line chart ..) in a single collection view?
If so,how can we approach it?As each view has to be of the (class) of the chart.How can we use one single view in the collection view to do the above?

**Comment by liuxuan30** [comment]
it seems beyond our scope. you can do whatever you like in a single collection view. They are UIViews before they are chart views.
