### ISSUE TITLE
Please provide an example for pieradarchart

### ISSUE THREAD

**Issue by alexjonser** [danielgindi/Charts#3029]
Hello Daniel,

first thanks for your implementation. I am searching for an way to create a chart like in the attached screenshot. Is the class pieradarchart what i need?
If it be, can you please add an demo for this in the project and a screenshot of an example in the description?

Best regards
Alex

![auswertungen](https://user-images.githubusercontent.com/33891118/33115018-a7f26484-cf5f-11e7-93ef-5f7a97e6b136.png)

**Comment by liuxuan30** [comment]
pieradarchart is just the base class, not this; but this seems pie chart is enough.
