### ISSUE TITLE
Only disable animation for adding values

### ISSUE THREAD

**Issue by gtaspider** [danielgindi/Charts#3031]
Hey,

I have a tool which gets time values from a tcp server.  to relive the tcp server I want the software to get the data of an entire day, eventhough the user just watches one hour. Everytime the user gets to the next day and the old values are beeing deleted, and the new values are beeing added to the LineSeries, there are animations on the LineSeries which look quite buggy:
![Alt Text](https://img2.picload.org/image/drlcldci/lvcharts.gif)

Is there a way to just disable the animations of the LineSeries, but not the overall chart (with DisableAnimations)? 

Thanks in advance,
Spider

**Comment by liuxuan30** [comment]
I just saw someone posted the animation seems just fine. But I don't know yours. maybe start with checking if you use the right APIs.

**Comment by liuxuan30** [comment]
like this https://github.com/danielgindi/Charts/issues/2859
