### ISSUE TITLE
Add charts to UIView programatically

### ISSUE THREAD

**Issue by jeyashrinatarajan** [danielgindi/Charts#3033]
Hi can we add the charts to a UIView programatically,instead of adding it as class to the UIView it through the IB.Can it be done programatically?I tried ,but apparently it doesn't call.

      var chartView = BarChartView()

      override func viewDidLoad() {

     super.viewDidLoad()
        chartView.noDataText = "No text"
        self.view.addSubview(chartView)

    }

**Comment by liuxuan30** [comment]
call what? Take a look at ChartsDemo first
