### ISSUE TITLE
lineChartView only enables one data set to be with icons

### ISSUE THREAD

**Issue by yuvalcropx** [danielgindi/Charts#3036]
let data = LineChartData()
data.addDataSet(line1)
data.addDataSet(line2)
data.addDataSet(line3)

the third line (line 3) has a data set with icons (i.e. each data point entry is ChartDataEntry(x: Double(i), y:  values[i] , icon: UIImage))
the other 2 lines has a data set without icons (i.e. each data point entry is ChartDataEntry(x: Double(i), y:  values[i] )

When I add all three lines I see all the data but not the icon next to the points of line 3
When I'm only adding line 3 to the chart I see the data + the icon.

**Comment by liuxuan30** [comment]
you have to provide more details. start from debugging `open override func drawValues(context: CGContext)`, where it will draw icon at last. You can check if the drawIcon is called, and why it does not appear; or can it be reproduced with ChartsDemo?

**Comment by liuxuan30** [comment]
I tried charts demo, it simply working; makre sure you don't draw anything above your icon. or change the order to see if it's covered.

**Comment by yuvalcropx** [comment]
Hi @liuxuan30 thank you for your quick reply.
And thank for the tip about debugging open override func drawValues(context: CGContext).
turns out this method 
isDrawingValuesAllowed(dataProvider: ChartDataProvider?)
returned false
dut to this condition
return data.entryCount < Int(CGFloat(dataProvider?.maxVisibleCount ?? 0) * (self.viewPortHandler?.scaleX ?? 1.0))

So I changed maxVisibileCount for my lineChartView and that fixed the problem.
But I think there might be something wrong with this condition:
1) isDrawingValuesAllowed shouldn't effect icon drawing (at least that what I understand from the method name).
2) I'm not sure how maxVisibleCount is calculated. is it a default value?
When I was debugging the value was 100 (don't know where that came from).

Again thanks a lot!

**Comment by liuxuan30** [comment]
yes ` @objc internal var _maxVisibleCount = 100` 100 is default

icon drawing is along with drawValues when the author filed the PR, without thinking too much about this. It seems should be separate.
