### ISSUE TITLE
Create an image of the entire chart

### ISSUE THREAD

**Issue by sbeff** [danielgindi/Charts#3037]
Hello everyone, I need to create an image of the entire chart like this:
![correct](https://user-images.githubusercontent.com/15926323/33180974-e29f93f8-d06e-11e7-9806-fde6d14b9ce8.png)
If I use the getChartImage function, I only get an image of the chart that is currently displayed on the screen, like this one:
![wrong](https://user-images.githubusercontent.com/15926323/33181048-1afbf778-d06f-11e7-9f97-0366d93eee3d.png)
Thanks in advance to everyone!
Emanuele

**Comment by liuxuan30** [comment]
I'm confused. You already got what is rendered. For those not showing up, use `renderInContext`

**Comment by sbeff** [comment]
I edited that screenshot, it was not taken with getChartImage function.

**Comment by liuxuan30** [comment]
oh you mean what you shot is not the full data entries? 

If you already zoomed and scrolled, `NSUIGraphicsGetImageFromCurrentImageContext` just takes whatever is on the screen *right now*

If you want to take the original chart, you have to reset the scale and offset and do it again. Or you manually create another ghost view to use `renderInContext` render off screen, however this will also take CPU power just like what you rendered on screen, but not showing actually.
