### ISSUE TITLE
Charts library is not working in Swift 4 Xcode 9

### ISSUE THREAD

**Issue by mob-rockstar** [danielgindi/Charts#3048]
I just tried to implement the line charts using charts library.
I have installed library using 
          pod 'Charts'
But I got many errors in charts library.
How can I solve this issue?
![screen shot 2017-11-24 at 12 14 02 am](https://user-images.githubusercontent.com/16888110/33201325-da124d3c-d0ac-11e7-8d37-ade4654bf7d6.png)

Regards

**Comment by kavin06** [comment]
same error for me also.How can you overcome with that error
