### ISSUE TITLE
Can't change the border width of circle point in line chart.

### ISSUE THREAD

**Issue by mob-rockstar** [danielgindi/Charts#3049]
I am going to increase the border width of circle point in line chart.
My code is followings:

        lineChartDataSet.lineWidth      = 2.0
        lineChartDataSet.circleRadius   = 5.0        
        lineChartDataSet.setColor(UIColor.red)
        lineChartDataSet.setCircleColor(UIColor.red)
        lineChartDataSet.mode = .cubicBezier

![screen shot 2017-11-24 at 1 45 25 am](https://user-images.githubusercontent.com/16888110/33204725-453dfe10-d0b9-11e7-9a5d-da3f41c5f640.png)

But I can't change the border width of circle point.
Regards

**Comment by liuxuan30** [comment]
use circleHoleRadius and circleRadius to adjust the width. take a look at `fileprivate func drawCircles(context: CGContext)`
