### ISSUE TITLE
dyld library not loaded @rpath/charts.framework/charts reason : image not found XCode 9.1 MacOS version 10.12.6

### ISSUE THREAD

**Issue by BugFinder27** [danielgindi/Charts#3050]
I tried all the solutions but still facing same error. I have already added charts.framework to general -> linked frameworks and libraries but no change please help.

**Comment by liuxuan30** [comment]
have you tried OS X demo?
this kind of issue is easy to fix; open your app packages and check if the framework is copied to your destination. 

use `otool -L $your_binary` to list where it reads the framework.
