### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by h-soran** [danielgindi/Charts#3057]
Hi there

Still getting the warning when using "pod 'Charts', '~> 3.0.4'". 
I am using the specific commit '98552bb44b47c2e80bb482ea97fa0552a996bff7' which has a fix. I am planning a release soon, what do you suggest I should do? 

Thanks for your help

**Comment by liuxuan30** [comment]
we are refining swift code styles, after that should comes a new release.

**Comment by rameswar54** [comment]
I'm interested to help in code refinement. Let me know if we can divide up tasks. :)

**Comment by liuxuan30** [comment]
@jjatie is leading the refactoring, and you can see lots of PRs come from him. You can help provide feedback or review comments :)

**Comment by jjatie** [comment]
@h-soran Charts 3.0.4 does not have any use of the deprecated `String().characters` property. My only recommendation would be to try deleting your pods, run `pod repo update` and then `pod install`.

**Comment by h-soran** [comment]
@jjatie I did what you suggested. Unfortunately, it didn't fix the issue, please see the attachments.

![bitmap](https://user-images.githubusercontent.com/30659115/33612722-672b225e-d9ca-11e7-8606-8761553e7ed0.png)
![chartspodupdate](https://user-images.githubusercontent.com/30659115/33612724-6b6eb402-d9ca-11e7-8592-fa43d06a44ed.png)

**Comment by jjatie** [comment]
It's curious as just going to your errors in the source on GitHub, the issues aren't there (e.g. https://github.com/danielgindi/Charts/blob/master/Source/Charts/Components/AxisBase.swift )

**Comment by abhishekbanthia** [comment]
I tried the steps outlined in your previous comment @jjatie and I still see the warning "characters is deprecated" for the following classes:

1. AxisBase.swift
2. ChartViewBase.swift
3. XAxisRenderer.swift
4. YAxisRenderer.swift
5. YAxisRendererHorizontalBarChart.swift

**Comment by h-soran** [comment]
@jjatie yes, I have deleted all the pods including the project that is created by the pods.

**Comment by luispadron** [comment]
Just adding to this, version 3.0.4 does indeed still use the `characters` member of the `String` class. 

Here is just one example, in `ChartViewBase.swift`

```swift
if _data === nil && noDataText.characters.count > 0
```

CocoPods can be a bit finicky, are you sure you pushed the latest changes to the trunk?

**Comment by liuxuan30** [comment]
pod just has 3.0.4 and what you asked are merged into master. 
if you use pod, point it to the right commit or branch.

**Comment by luispadron** [comment]
Why can't you? I would say fixing deprecations isn't a "small" fix, it's deprecated for a reason.

Also, releasing to CocoaPods isn't that bad.

I'm more than happy to fix the deprecations and send you all a pull request if you would like me to.

**Comment by jjatie** [comment]
@luispadron Once again, there are no uses of `.characters` in the 3.0.4 code base, so there are no deprecations to be fixed. There clearly is an issue with the pod on CocoaPods and that needs to be addressed. I'm not sure who is responsible for that @liuxuan30 @petester42 @danielgindi ?

**Comment by luispadron** [comment]
@jjatie, There are uses of `.characters` in the 3.0.4 code base though.
If you look at the source [here](https://github.com/danielgindi/Charts/releases/tag/v3.0.4) you can see that this source code, in version `3.0.4` uses `.characters` . 

This is the same tag that CocoaPods uses to install `3.0.4` when using `pod install`, thus why we are all getting deprecation warnings. I understand that `master` doesn't use `.characters` but version `3.0.4` tag does.

**Comment by jjatie** [comment]
Ah, you're right. 3.0.4 was released Sept 21, and `characters` was replaced on Nov 3.

**Comment by luispadron** [comment]
Yeah, it's not a huge priority to have it fixed. I just wanted to make you all aware of the issue.

**Comment by liuxuan30** [comment]
yes we are and already merged. Thanks

**Comment by luispadron** [comment]
Great job guys!
