### ISSUE TITLE
Line chart with bottom spacing and custom position y-labels at min and max values

### ISSUE THREAD

**Issue by blau2** [danielgindi/Charts#3059]
First off, thanks for the work you've all done on this incredible library! It's been a pleasure to use and has suited our use case perfectly.

I've scoured the wiki and issues and haven't been able to find a solution to this. I'm trying to create a line chart that looks as follows:
![image](https://user-images.githubusercontent.com/1384321/33332128-4409c97c-d418-11e7-87d2-af0fe0e39cd1.png)

There is a minimum offset at the bottom of the chart so that the line does not overlap the xAxis labels (they're positioned as `.bottomInside` because we don't want the line to shift when we hide the xAxis on drag). I'm achieving this as follows:

```
lineDataSet.axisDependency = .right
lineChartView.rightAxis.axisMinimum = graphData.minPrice
lineChartView.rightAxis.axisMaximum = graphData.maxPrice
lineChartView.data = LineChartData(dataSet: lineDataSet)
lineChartView.rightAxis.spaceBottom = 0.2
lineChartView.rightAxis.resetCustomAxisMin()
```

This gives me the spacing as intended, however now I want to modify the yAxis labels so that they indicate the min and max of the chart and are positioned accordingly. Currently, the minimum label is placed right at the bottom, and after adding the `spaceBottom` it no longer displays the value of the minimum y value.

![image](https://user-images.githubusercontent.com/1384321/33332525-5903b2d8-d419-11e7-9a4b-e8160911d7d8.png)

Any suggestions for how I might achieve this would be greatly appreciated!

**Comment by liuxuan30** [comment]
I don't quite understand your issue with second image.

**Comment by blau2** [comment]
I would like to make it so that the bottom label on the y-axis reflects the minimum chart value (in this case, $1.2K), not the lower bound of the scale. Ideally I would also like to set the position of the bottom label to be at the same y-position as the chart minimum.

**Comment by liuxuan30** [comment]
setting `axisMinimum` will not give you the same value for label?
I remember a long time ago there is a property `showOnlyMinMax`. However it seems removed in Chart 3.0
You may want to add this back in your project, so override `computAxisValues()` to return the min max values, `axis.entries` are the values to display on axis.
