### ISSUE TITLE
Cannot Select barChar column

### ISSUE THREAD

**Issue by mdtuyen** [danielgindi/Charts#3065]
Hi,
Here is my setup for barChart:

barChart.chartDescription?.enabled = false
        barChart.drawGridBackgroundEnabled = false
        
        barChart.dragEnabled = true
        barChart.setScaleEnabled(false)
        barChart.pinchZoomEnabled = false
        barChart.rightAxis.enabled = false
        barChart.delegate = self;
        
        barChart.drawBarShadowEnabled = false;
        barChart.drawValueAboveBarEnabled = true;
        
        barChart.maxVisibleCount = 60;
        
        let xAxis = barChart.xAxis;
        xAxis.labelPosition = .bottom;
        xAxis.labelFont = UIFont.systemFont(ofSize: 10)
        xAxis.granularity = 0.01;
        xAxis.labelCount = 7;
        xAxis.valueFormatter = TimeValueFormatter();
        
        let leftAxisFormatter = NumberFormatter();
        leftAxisFormatter.minimumFractionDigits = 0;
        leftAxisFormatter.maximumFractionDigits = 1;
        
        let leftAxis = barChart.leftAxis;
        leftAxis.labelFont = UIFont.systemFont(ofSize: 10);
        leftAxis.labelCount = 8;
        leftAxis.valueFormatter = DefaultAxisValueFormatter(formatter: leftAxisFormatter);
        leftAxis.labelPosition = .outsideChart;
        leftAxis.spaceTop = 0.15;
        leftAxis.axisMinimum = 0.0;

And i see that some colume chart of me can't select or difficuit to select it.
Why?
Please help me setup it is correct.

**Comment by liuxuan30** [comment]
use ChartsDemo first.
