### ISSUE TITLE
Unable to make chart look like IOS Stock App after trying every mode (LineChartModeLinear = 0,   LineChartModeStepped = 1,   LineChartModeCubicBezier = 2,   LineChartModeHorizontalBezier = 3) of LineChartDataSet

### ISSUE THREAD

**Issue by Rj707** [danielgindi/Charts#3066]
![img_2966 jpg](https://user-images.githubusercontent.com/9985642/33554211-9b67e85c-d91d-11e7-8cae-f2cee0895a5e.jpg)

![test](https://user-images.githubusercontent.com/9985642/33554256-cd87708c-d91d-11e7-9ae9-d922ef720d21.png)

**Comment by Rj707** [comment]
My chart doesn't look like a cubic bezier one at all.

**Comment by liuxuan30** [comment]
the stock app just seems linear. and you second image shows exactly cubic.

**Comment by Rj707** [comment]
@liuxuan30 thanks for your reply, but even if I set mode as linear, I can't get chart like IOS Stock App (like showing minor changes very clearly and other things like corner edges).

**Comment by liuxuan30** [comment]
well, It's just a fact of grid lines, axis lines, limit lines, gradient filling, etc differences. Charts has support them already, but does not mean to get everything looks like the stock app. You can try ChartsDemo to put different pieces together, also you might need to override several methods to get what you wanted.

**Comment by Rj707** [comment]
Thanks a lot @liuxuan30 for your time, I have studied grid lines, axis lines, limit lines, gradient filling, etc differences and made a custom chart with the help of that awesome things. And you are right, I was not specific about my question. Actually I want  Or should I say, whether charts library support minor data changes like IOS stock App (You can see in the image it shows a lot of points between 16.55 and 17.05 ) . Plus after every change in data point, there is a corner edge, which shows clearly that there is a change.

**Comment by liuxuan30** [comment]
yes, you can just set axis.axisMinimum/Maximum to 16.55 and 17.05. then feed enough data

**Comment by Rj707** [comment]
thanks @liuxuan30 , and what about my other Question? 

> Plus after every change in data point, there is a corner edge, which shows clearly that there is a change.

**Comment by liuxuan30** [comment]
what's corner edge you refer? Don't understand

**Comment by Rj707** [comment]
![img_2966 jpg](https://user-images.githubusercontent.com/9985642/33754044-56dc5e56-dc0c-11e7-8de6-982c28495b09.jpg)
 look at the white solid line which is representing data points and having  sharp edges.

**Comment by liuxuan30** [comment]
![image](https://user-images.githubusercontent.com/4375169/33754121-bfaaa92e-dc25-11e7-91da-d5ebc5f3b6b9.png)
if you add one more entry out of the axis range and same as last value, then you have the effect. Just set x axis maximum smaller than the last one. So it will looks clipped.

**Comment by Rj707** [comment]
@liuxuan30 I think you misunderstood my point or question. But, m not sure.
Actually I don't want the smooth blue line like below
![test](https://user-images.githubusercontent.com/9985642/33754517-5a43ecd8-dc0e-11e7-93a1-11b66003828f.png)
I want the line to look like the below one 
![img_2966 jpg](https://user-images.githubusercontent.com/9985642/33754531-6cc8e23c-dc0e-11e7-8e6f-2c5082f10827.jpg)

**Comment by liuxuan30** [comment]
then use linear instead..
