### ISSUE TITLE
Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3

### ISSUE THREAD

**Issue by nickinylin** [danielgindi/Charts#3068]
Hello! I have a problem after updating to Xcode 9.2 from 9.01, before i could compile but after the update when trying to import it, it says:

Module compiled with Swift 4.0 cannot be imported in Swift 3.2.3: 

Im using the chart version 3.0.4 with cocoa pods and xcode 9.2 

Thanks! Best regards Nicki

**Comment by thierryH91200** [comment]
verify 
![capture d ecran 2017-12-05 a 15 05 21](https://user-images.githubusercontent.com/6251463/33611214-d6eaf71a-d9cd-11e7-92b7-f4d118d3ef44.jpg)

look at #2883

**Comment by nickinylin** [comment]
It has been set to compile with version 4.0

**Comment by nickinylin** [comment]
The problem was apparently that I had some old files in the “derivedData” folder. I deleted that and recompiled and it worked

**Comment by SushmithaRaja** [comment]
I have the same problem but deleting derived data didn't work for me
