### ISSUE TITLE
How can I have a chart like this one?

### ISSUE THREAD

**Issue by Harmonium** [danielgindi/Charts#3070]
I would like to know how can I have that kind of chart? I mean a chart that does not go till the end of the Xaxis. It has to follow the hour.

Is it possible?

![graph](https://user-images.githubusercontent.com/4366227/33615570-7ba5632e-d9a8-11e7-96d6-effeeb023cf5.png)

**Comment by KevinZK** [comment]
you  can  use this  CombinedChartView class, CombinedChartData set lineData and BarChartData .
 you must inherit LineChartRenderer to change the last point's style，you need draw the mark of xAxis .

**Comment by liuxuan30** [comment]
you need to add custom marker/limit line marker and different background. Someone already mentioned the background effect, so it's doable as long as what to override.
