### ISSUE TITLE
[LineChart] Ignore / don't plot first or end value

### ISSUE THREAD

**Issue by tienlenan** [danielgindi/Charts#3075]
Hi everyone,

How can I create Line Chart like this?
![line_chart](https://user-images.githubusercontent.com/10125208/33709344-a8224a66-db6f-11e7-85b9-2753f655c572.PNG)

I try many ways, but chart always connect from start column to my start point.

**Comment by tienlenan** [comment]
I found the way to create it.
We can create two data sets.

**Comment by TheMangoGirl** [comment]
@tienlenan Hey tienlenan, I have the same issue. 
But when I add two data sets, the part from leftAxis to the first DataEntry of the second data set shows up anyway.
Can you please show me a code example, how you did it?
