### ISSUE TITLE
Clipping of values in line graph

### ISSUE THREAD

**Issue by KhushbooDhote** [danielgindi/Charts#3077]
Hi,
I am facing problem to manage huge data in multiline graph. Values are getting clipped, can any one please help me to sort this out. TIA
![screen shot 2017-11-30 at 3 11 32 pm](https://user-images.githubusercontent.com/20533117/33753586-fbef8f0c-dc0d-11e7-9c51-b2003dc5ff4d.png)

**Comment by liuxuan30** [comment]
looks like you don't use it right. double check and refer ChartsDemo.
