### ISSUE TITLE
Scrolling axis

### ISSUE THREAD

**Issue by balkarov** [danielgindi/Charts#3081]
Hello!

Thank you for your awesome library!

Is it possible implement scroll on Xaxis? With fixed left/right axis and legend?
I implemented with "hack": put chart view to UIScrollView. But left/right axis and legend scrolling too 
:(

**Comment by liuxuan30** [comment]
it's already supported, as long as you zoom the chart in, only allow x scroll while disable Y. Just play with ChartsDemo. Like `scaleXEnabled` `scaleYEnabled`

**Comment by balkarov** [comment]
Hello!

I want scroll without zoom.

**Comment by liuxuan30** [comment]
scroll without zoom does not make sense, what you think?
scroll means you have more to display, while if you don't zoom, chart already displayed all data. What to scroll?
But you can set `maxVisibleXRange` etc first so it can scroll, but it's still zoomed behind the scene.

**Comment by balkarov** [comment]
Did you see example? 
I want set max visible data and see scroll. 
For example: I set max xAxis data = 6, But my data has 100 values. And I will see scroll with first 6 values

**Comment by liuxuan30** [comment]
Did you see my answer? I said use `setVisibleXRange`

**Comment by balkarov** [comment]
Hello.
This is does not work. Scroll (without zoom) does not work.
I want show scroll in chart without some zoom.

**Comment by balkarov** [comment]
setVisibleXRange
/// Limits the maximum and minimum value count that can be visible by pinching and zooming.

But I want scroll without zooming

**Comment by pateljinal1844** [comment]
I just found out, ordering matters for this to work. You need to call setVisibleXRangeMaximum after chartView.data = data or notifyDataSetChanged

**Comment by badrinathvm** [comment]
@balkarov  Can i see the code of adding the scrollView ? 
@pateljinal1844  I tried setting setVisibleXRangeMaximum after the data is set , but still not able to scroll any working example i can have a look ?

**Comment by kevinrenskers** [comment]
I got it to work, but I want the chart to start scrolled all the way to the right. Is this possible? I have a bar chart with hundreds of bars, and I only want 14 of them visible at once.

``` swift
chartView.xAxis.labelCount = valuesSet.count
chartView.dragXEnabled = true
chartView.data = BarChartData(dataSet: valuesSet)
chartView.setVisibleXRangeMaximum(14)
```

This makes it scroll, but it starts to the left.
