### ISSUE TITLE
how to use String in YAxis， rather than Double?

### ISSUE THREAD

**Issue by guoyutao** [danielgindi/Charts#3082]
how to use String in YAxis， rather than Double?

**Comment by guoyutao** [comment]
![image](https://user-images.githubusercontent.com/11513385/33802693-764fcdd4-ddb7-11e7-9d35-2b915296cbe8.png)

**Comment by balkarov** [comment]
Hello.
Look my [answer](https://github.com/danielgindi/Charts/issues/2586) 
Did you mean it?

**Comment by guoyutao** [comment]
@balkarov  I understand what you mean.Thank you very much

**Comment by liuxuan30** [comment]
us
