### ISSUE TITLE
how to cancel highlights when the drag gesture ends

### ISSUE THREAD

**Issue by freedomwindy** [danielgindi/Charts#3089]

**Comment by liuxuan30** [comment]
disable highlight feature. or override the pan gesture

**Comment by zzmasoud** [comment]
also you can use ChartViewDelegate:

```
    func chartViewDidEndPanning(_ chartView: ChartViewBase) {
        chartView.highlightValue(nil)
    }

```

**Comment by panncherry** [comment]
I did `chartViewDidEndPanning` but both `chartValueNothingSelected` and `chartViewDidEndPanning` are not getting called.

chartValueSelected is working fine, it is being called and chartView.delege = self is in called in viewDidLoad.
