### ISSUE TITLE
Line Chart point colours depend on value at each point

### ISSUE THREAD

**Issue by lukecsmith** [danielgindi/Charts#3090]
Hi, wondering if this is currently possible with your fine library.  My line chart data consists of y values that are integers between 0 and 7.  My requirements are that the colour of the point is directly related to the value - so y at 0 means a red point, y at 1 means an orange point, y at 2 means a yellow point, etc - regardless of what the x value is.  Is this currently possible or can I customize a line chart to achieve this, and if so how?  Thanks, Luke.

**Comment by thierryH91200** [comment]
see #2824 and #2334

**Comment by lukecsmith** [comment]
@thierryH91200 thankyou, having a look now.

**Comment by lukecsmith** [comment]
@thierryH91200 works perfectly, thanks!
