### ISSUE TITLE
Combined Chart, when highlight is active, bars hides line

### ISSUE THREAD

**Issue by vCrespoP** [danielgindi/Charts#3091]
Hi, I've set this:
self.graph.drawOrder = [DrawOrder.bar.rawValue, DrawOrder.line.rawValue]

And I have two data sets which appear correctly when nothing is highlighted
![image](https://user-images.githubusercontent.com/7558064/33892947-6ec365ae-df5a-11e7-9924-4576236dc0b2.png)

but when I select something (highlight) it gets hidden by the highlighted bar:
![image](https://user-images.githubusercontent.com/7558064/33892954-73917508-df5a-11e7-8de8-7ae2668ffc7b.png)

How could I keep the highlighted bar **behind** the line, as in the normal state? Any special property, delegate, something ovbious I'm missing?

Thanks a lot for your effort!

**Comment by liuxuan30** [comment]
It seems a defect. highlight is called after drawing the data. If you give a solid color, it will cover the shape. take a look at `open override func draw(_ rect: CGRect)`. To work around, you can change the order on your side.
I think this can be done using a switch either highlight before drawing the data or after. But not sure if there are any side effects.
Are you able to try?

**Comment by vCrespoP** [comment]
Seems to be working, thanks for your support :)

**Comment by liuxuan30** [comment]
it's a defect. Let's keep it open
