### ISSUE TITLE
how to display the integer values on pie chart instead of float?

### ISSUE THREAD

**Issue by shilpashreeamt** [danielgindi/Charts#3093]
![screen shot 2017-12-13 at 10 34 19 am](https://user-images.githubusercontent.com/34499390/33922495-3a2233d8-dff1-11e7-9e90-e7b2b52514b7.png)
Hi,
I tried to customise the library in order to display the int values(Above image represents my requirement)...in some links they mentioned to follow NSNumberFormatter.But i failed to use that solution am not getting which class i should customise to get the required solution...can any one help me to resolve this issue.
I spent more than a day to find solution but no use.
Thanks in advance

**Comment by shilpashreeamt** [comment]
After many trials i found the answer

let track = ["Passed", "Failed", "Pending"]
        let money = [10, 6, 10]
        var entries = [PieChartDataEntry]()
        for (index, value) in money.enumerated() {
            let entry = PieChartDataEntry()

            entry.y = Double(value)
           
           entry.label = track[index]
            entries.append( entry)
        }
 let set = PieChartDataSet( values: entries, label: "")
        let data = PieChartData(dataSet: set)
         pieChartView.data = data
let formatter = NumberFormatter()
formatter.minimumFractionDigits = 0
   data.setValueFormatter(DefaultValueFormatter(formatter:formatter))

**Comment by chanoktrue** [comment]
thank you
