### ISSUE TITLE
数据空值处理问题

### ISSUE THREAD

**Issue by xiaowasly** [danielgindi/Charts#3094]
我在用linechartview遇到一些问题，我的数据源是这样的x:[1,2,3,4,5,6,7,8,9,10]  y:[189,33,null,null,null,null,null,21,2,10]     但是charts画出来的图会把“null”变成“0“，这并不是我的需求，我想请教大神们，有什么好的方法来跳过“null”吗？

**Comment by aelam** [comment]
重写你的valueformatter  默认内部用的numberformatter

发自我的 iPhone

**Comment by liuxuan30** [comment]
use multiple data sets.

**Comment by xiaowasly** [comment]
How to use I did not find a way
