### ISSUE TITLE
How to scroll bar chart if max values to show?

### ISSUE THREAD

**Issue by mubashar26** [danielgindi/Charts#3101]
I wan t to use Bar Chart in android and IOS(swift3). but when i have more values x-axis labels skip and also chart don't scroll right untill i double tap on chart. on double tap it zoom and then scroll. Is there any option that without double tap, scrolling enable in chart nad values/x-axis labels don't skip and merge.

please let me How to do it. if feature available.

**Comment by liuxuan30** [comment]
scroll means you have more to show. If you already displayed all of your bars, there is no reason to scroll.

**Comment by pateljinal1844** [comment]
I just found out, ordering matters for this to work. You need to call setVisibleXRangeMaximum after chartView.data = data or notifyDataSetChanged
