### ISSUE TITLE
Draw dotted x-axis timeline

### ISSUE THREAD

**Issue by mrmrdolph** [danielgindi/Charts#3102]
Hello!
Is it possible to use the Chats API to draw this kind of dotted x-axis timeline?

![reports - savings - statistics 16](https://user-images.githubusercontent.com/3897168/33990975-22364de0-e0cd-11e7-9470-b6eb608c85dc.png)

**Comment by rameswar54** [comment]
You may achieve the above I believe with playing around the below properties.

```
chartView.leftAxis.spaceBottom = 0.15
chartView.xAxis.axisLineDashLengths = [1, 1]
```

Else just extend the XAxis to add the dot behavior you want.

**Comment by liuxuan30** [comment]
just override drawAxisLines or do like what @rameswar54 said
