### ISSUE TITLE
Multiple charts in same view

### ISSUE THREAD

**Issue by atalayasa** [danielgindi/Charts#3103]
I need to have different charts in same view and these different charts data's are different from each other. I created a custom table view cell and I have putted UIView into inside. However, that view's type is UIView but as far as I understood from library if one view needs to be bar chart view its class needs to inherit from BarChartView. How can I change that type for both line chart and bar chart. Shall I create a view programmatically or is it possible to have it using storyboard table view?

**Comment by SeRG1k17** [comment]
A similar problem.
I need to place a linear graph at the top of the chart, and in the lower part of the bars.
Graphs(line, bars) may overlap slightly
![screen shot 2017-12-15 at 13 01 53](https://user-images.githubusercontent.com/13317173/34037395-b2808b0a-e199-11e7-9ec7-18bb97ce104b.png)

**Comment by jjatie** [comment]
Seems like two different questions. If you want to have multiple data sets displayed on the same graph with different graph types, use the `CombinedChartView`. If you need to two graphs next to each other, use two separate views.

**Comment by SeRG1k17** [comment]
@jjatie Use two different graphics, and then have to synchronize them (scrolling, pinch, zoom). I think my option CombinedChartView.
Thank you.

**Comment by atalayasa** [comment]
Problem solved. https://stackoverflow.com/questions/47819397/multiple-charts-in-same-view-ios-charts/

**Comment by liuxuan30** [comment]
I don't find https://stackoverflow.com/questions/47819397/multiple-charts-in-same-view-ios-charts/ actually solved the sync problem. It just puts several views together. The evil is insdie syncing the panning/zooming. If they have the same x axis values, should be easier then.

**Comment by liuxuan30** [comment]
We might come with a protocol or something in the future, if time allowed, for syncing the charts.

**Comment by jjatie** [comment]
#3177
