### ISSUE TITLE
LineChart with different colors based on values.

### ISSUE THREAD

**Issue by praveenbroski** [danielgindi/Charts#3107]
![untitled-1](https://user-images.githubusercontent.com/14329980/34067507-b1f25966-e24d-11e7-8dd6-e493af1a0133.jpg)

Can we create a LineChart like the one in above pic?

I managed to draw a linechart with white line like in the following pic.

I've searched for this and couldn't find a way. So if anyone know please help me with this.

Thanks.

![untitled-1](https://user-images.githubusercontent.com/14329980/34067516-086b851a-e24e-11e7-978b-5c1197a18781.jpg)

**Comment by high5Fly** [comment]
var dataEntries: [ChartDataEntry] = []
        var valueColors = [NSUIColor]()
        var circleColors = [NSUIColor]()
        for i in 0..<yValues.count {
            print(yValues[i])
            let dataEntry = ChartDataEntry(x: Double(i), y: yValues[i])
            dataEntries.append(dataEntry)
            valueColors.append(UIColor.colorPicker(value: yValues[i]))
            circleColors.append(UIColor.colorPicker(value: yValues[i]))
        }

Hope it helps.

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/pull/3142
