### ISSUE TITLE
PieChart size is extremely small in a UITableViewCell

### ISSUE THREAD

**Issue by AlanLoyc** [danielgindi/Charts#3108]
I tried to render a PieChart in my UITableViewCell, the PieChartView's size is set to 44 x 44 with constraints in xib, and the result is like:

<img width="571" alt="screen shot 2017-12-18 at 2 32 55 am" src="https://user-images.githubusercontent.com/9067252/34082566-cd8e4b7c-e39b-11e7-82b7-8d0096370590.png">

How to make the PieChart extend and use the full width of the view? I tried setting minOffset, extraOffset, etc, but they didn't work, below is how I set the PieChartView in my UITableViewCell:
```
@IBOutlet var pieChart: PieChartView! {
        didSet {
            pieChart.legend.enabled = false
            pieChart.chartDescription?.enabled = false
        }
}
```

Thanks!

**Comment by AlanLoyc** [comment]
I've just managed to extend the chart closer to the edges by setting a negative extra offset, but it feels kind of inappropriate to me, is this the right way to do it? Where do those margin comes from?

**Comment by liuxuan30** [comment]
This seems a known issue, as when the view's bound is smaller than usual, the offset becomes a big percentage. What you can workaround is, changing `minOffset`, or `extraLeft/Top/..Offset` to be negative to adjust.

**Comment by wlisac** [comment]
I'm running into the same issue. Is there a way to capture this as an enhancement request?
