### ISSUE TITLE
pieChart Data name overlap

### ISSUE THREAD

**Issue by jackCaptian** [danielgindi/Charts#3109]
As shown in the picture
![wechatimg4276](https://user-images.githubusercontent.com/19648101/34086562-aced5a0c-e3d7-11e7-906a-54f2754822c4.jpeg)

If I want to achieve the following effect, how to set up
![wechatimg4281](https://user-images.githubusercontent.com/19648101/34086579-d363e160-e3d7-11e7-8f8e-42626e919ce6.jpeg)

**Comment by liuxuan30** [comment]
smaller the font size. I don't think you can put all label on the screen, as the total space is there. Either you use small font size, or you hide some of the labels, like by interval 2.

**Comment by liuxuan30** [comment]
take a look at https://github.com/danielgindi/Charts/pull/2062, it hides the label.
