### ISSUE TITLE
HorizontalBarChartView displays bar shadow when left and right axis hidden

### ISSUE THREAD

**Issue by dukemike** [danielgindi/Charts#311]
When displaying a horizontal bar chart, I always see a shadow under the bar.

<img width="321" alt="screenshot_8_21_15__1_23_am" src="https://cloud.githubusercontent.com/assets/11562781/9401819/42f1de02-47a3-11e5-91d1-f0f5daba4319.png">

If I enable the left and right axis, I can colorize them, but setting them to white or the clear color still shows the shadow. When the left and right axis is enabled, the shadow disappears.

<img width="330" alt="screenshot_8_21_15__1_22_am" src="https://cloud.githubusercontent.com/assets/11562781/9401812/241802cc-47a3-11e5-861f-5599689b416b.png">

My chart is configured as shown below, and includes a legend.

```
    _chartView.userInteractionEnabled = NO;
    _chartView.drawGridBackgroundEnabled = NO;
    _chartView.drawBarShadowEnabled = NO;
    _chartView.drawBordersEnabled = NO;
    _chartView.leftAxis.enabled = NO;
    _chartView.leftAxis.startAtZeroEnabled = YES;
    _chartView.leftAxis.axisMaximum = 100.f;
    _chartView.rightAxis.enabled = NO;
    _chartView.rightAxis.startAtZeroEnabled = YES;
    _chartView.rightAxis.axisMaximum = 100.f;
```

Setting the max and min values for each axis does not seem to have any impact at all.

Any ideas on what I can do to remove the shadow? I am using the latest ios-charts on the master branch.

**Comment by liuxuan30** [comment]
Do you still have such problem? If possible, could you provide a sample code with ChartsDemo's view controllers? I don't see the shadow quite clear. and `If I enable the left and right axis, I can colorize them, but setting them to white or the clear color still shows the shadow. When the left and right axis is enabled, the shadow disappears.` is not clear about `When the left and right axis is enabled, the shadow disappears`
