### ISSUE TITLE
PieChartView Can not highlight which i want to highlighted

### ISSUE THREAD

**Issue by codeliu6572** [danielgindi/Charts#3110]
I use PieChartView and want to highlighted one after init.I see lineChar can use 
    [self.chartView highlightValueWithX:0.0f y:0.0f dataSetIndex:3 callDelegate:NO];
and I test in piechart ,because piechart don't have an x and y,so,I give x and y 0.0f,and give SetIndex the index in the array, but it does not work except index=0,i want to know how to highlighted some one i wanted in piechart.Thankyou!

Expect your reply!

**Comment by codeliu6572** [comment]
@liuxuan30

**Comment by liuxuan30** [comment]
don't use coordinate if you are not familiar with. There are plenty of highlight methods, so use others. like `@objc open func highlightValue(_ highlight: Highlight?)`

**Comment by codeliu6572** [comment]
@liuxuan30 I tried this 
  ChartHighlight *high = [[ChartHighlight alloc]init];
        high.dataIndex = maxIndex;
        [self.chartView highlightValue:high];
dataSetIndex is readonly and can not use,I searched on the internet and find nothing about it, can you show me how to use hight on piechart?Thank you.

**Comment by liuxuan30** [comment]
I think you misunderstood? usually what you need to provide is data set index and entry index, etc, to only identify which entry in which data set to be used. DataIndex is only used in combined chart, in pie chart, dataSetIndex and dataIndex should always be 0 I suppose.

**Comment by liuxuan30** [comment]
BTW, Try debug ChartDemo - pie chart, it has all the steps how highlight are created and highlighted. You can add a breakpoint at `drawHighlighted` method

**Comment by codeliu6572** [comment]
@liuxuan30 You mean If i need to highlight one part of Piechart , i have to rewrite some method? If ChartDemo - pie chart has method ,can you tell me how to use it? I found highlight method contains x,y,even  highlightValue(_ highlight: Highlight?) ,I googled bug found nothing useful,I suggest you add highlight method on PIeChartView.

**Comment by codeliu6572** [comment]
@liuxuan30 I have solved this problem by using
    [_chartView highlightValueWithX:4 dataSetIndex:0];

dataSetIndex is zero, and X is the index, but i don not understand why this work, but it solved my problem.Thanks anyway!Here I was to suggest your team write right method in the Demo to help developer, like me,I think most of developer will meet this problem,and your team certainly hope to let Charts more better.
Best wishes for you and your team!

**Comment by liuxuan30** [comment]
`highlightValue` API series eventually lead to the same final call. You can take a look at `open override func drawHighlighted(context: CGContext, indices: [Highlight])` how your code work, and maybe you can find a better one. 
Thanks for your input. We will improve that. Well, if we got enough complains about that :)

**Comment by codeliu6572** [comment]
Haha，I have seen some issues on GitHub,Really hope you improve that .Although it worked,i still worried some unknown question. If i rewrite this method, but you update some code ,you know, maybe
have other question. Hope your update.
