### ISSUE TITLE
Rounded line chart

### ISSUE THREAD

**Issue by mdnjustin** [danielgindi/Charts#3115]
I have this:
![screen shot 2017-12-18 at 4 26 34 pm](https://user-images.githubusercontent.com/2393981/34130801-2e83ff6e-e417-11e7-9c3b-09461bde0331.png)

Is there a way of rounding off the corners to make it look more like this?
![screen shot 2017-12-18 at 4 28 01 pm](https://user-images.githubusercontent.com/2393981/34130813-3cf869d6-e417-11e7-85ce-dc0246ec1690.png)

I've tried using 
`set.mode = .cubicBezier` 
but it doesn't create the flat lines I want.

**Comment by liuxuan30** [comment]
hmm, it seems not a easy one. bezier curve and your goal is different. Have you tried line cap? it might make the corner smooth, but not like your curve.
@jjatie any idea?

**Comment by jjatie** [comment]
I think this is an outlying case. If we don't come up with more pressing features to add, it would be a neat feature to add for 4.x (I'm hoping to get a ChartRenderer refactor in 4.0). It makes sense to me that line graphs get more line options.

**Comment by liuxuan30** [comment]
eh line cap we already added in (by me I remember)

**Comment by jjatie** [comment]
I do not. It's not something I would use when plotting data because it incorrectly represents discontinuous data as continuous.

**Comment by mdnjustin** [comment]
Alright, thanks for your help guys.

**Comment by mcat345** [comment]
does anyone found a solution for this?
