### ISSUE TITLE
ChartsDemo doesn't compile

### ISSUE THREAD

**Issue by valeriyvan** [danielgindi/Charts#3116]
ChartsDemo target of ChartsDemo project is not compiling after last changes

**Comment by liuxuan30** [comment]
what.. The CI indicates it's all green and then could I merge. Why not compiling

**Comment by liuxuan30** [comment]
I just checked the CI log. I just compile the framework and run UT, not compiling the demos. I think we should avoid that in the future. Like adding a UT to build demos.

**Comment by jjatie** [comment]
Sounds like a good idea to add compiling demos to the CI. I often forget to check them.

**Comment by jjatie** [comment]
I just checked the master and the demos (Mac and iOS objc/swift) are building fine.

**Comment by liuxuan30** [comment]
Shall we merge #3121 then? BTW, please check #3121 comments, do you know anything we can reduce the compile times?
