### ISSUE TITLE
BarChart - Show X-Axis with Step as 1

### ISSUE THREAD

**Issue by mrimadali** [danielgindi/Charts#3122]
Hi Team,

How can I show Barchart X-values continuously with the step as 1, currently the X-Values display with step 2 mean displays alternate values like Feb, Apr, Jun, Aug etc., I want all the months to be displayed like Jan, Feb, Mar etc.,

<img width="352" alt="screen shot 2017-12-20 at 8 53 21 am" src="https://user-images.githubusercontent.com/7879031/34192236-40c55588-e566-11e7-8c0f-ba66b7132405.png">

  ```
  let months = ["","Jan", "Feb", "Mar",
                  "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep",
                  "Oct", "Nov", "Dec"]
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return months[Int(value)]
    }


```

**Comment by mrimadali** [comment]
I have fixed this by using property `labelCount` as:

`barChart.xAxis.labelCount = 12`

**Comment by sylvan-d-ash** [comment]
```
class AllResultsViewController {
    let xAxisValues = ["W1", "W2", "W3"]
}

extension AllResultsViewController: IAxisValueFormatter {
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        return self.xAxisValues[Int(value)]
    }
}
```

This is an excerpt of what I have. But I still can't get the `x-axis labels` to be displayed using strings. In fact, the `stringForValue` code doesn't seem to be getting executed at all. My questions are therefore:
1. What could I be doing wrong?
2. What was the reason behind making this entire process so complicated?
3. Why were the `xValues` removed from `BarChartData(xVals: months, dataSet: chartDataSet)`?
