### ISSUE TITLE
why bar chart non start at zero

### ISSUE THREAD

**Issue by lapoPaolacci** [danielgindi/Charts#3123]
hi why graph start here

![schermata 2017-12-20 alle 10 56 04](https://user-images.githubusercontent.com/23437476/34201391-9f395d04-e574-11e7-8fc9-62efbe7196d1.png)

and not here?

![schermata 2017-12-20 alle 10 56 19](https://user-images.githubusercontent.com/23437476/34201392-9f51f314-e574-11e7-9ee6-933692ced5c5.png)

**Comment by liuxuan30** [comment]
by default there axis range is lower than 0, if you need this, just set your `yAxis.axisMinimum = 0`
