### ISSUE TITLE
Plotting the bar from top to bottom (in reverse manner)

### ISSUE THREAD

**Issue by aravinth02** [danielgindi/Charts#3125]
Currently,  in Horizontal bar chart, all bars are rendered from bottom to top ,i.e, first bar entry starts from bottom of the view. I need to plot the horizontal-bar from top to bottom along the x-axis.

Is there any way to change or reverse the rendering flow along x-axis  ? 

Current horizontal bar image

<img width="809" alt="screen shot 2017-12-21 at 12 59 35 pm" src="https://user-images.githubusercontent.com/5636890/34245212-ea8e6dfa-e64e-11e7-8d4e-b2151aac0839.png">

Expected one as follows

<img width="808" alt="screen shot 2017-12-21 at 12 59 56 pm" src="https://user-images.githubusercontent.com/5636890/34245236-096d4926-e64f-11e7-9a4a-e7969cbd6421.png">

Any suggestions

Thanks !!!

**Comment by aravinth02** [comment]
Any idea on plotting the bar reverse flow ? And interactions like zoom/pan ? 

Thanks in advance !!

**Comment by jjatie** [comment]
Please provide your code sample.

**Comment by aravinth02** [comment]
@jjatie 

`var barChartView:HorizontalBarChartView = = HorizontalBarChartView(frame: self.view.bounds)
        barChartView.xAxis.labelRotationAngle = 0
        barChartView.leftAxis.enabled = false
        barChartView.rightAxis.enabled = true
        barChartView.xAxis.wordWrapEnabled = true
        barChartView.xAxis.labelPosition = .bottom
        barChartView.xAxis.granularityEnabled = true
        barChartView.xAxis.granularity = 1.0
        barChartView.xAxis.labelCount = 5
        
        let count = 20
        let range = 54
        var dataEntries1: [BarChartDataEntry] = []
        
        for i in 0..<count {
            
            let lab = "Item " + String(Double(i+1))

            let val1 = arc4random_uniform(UInt32(range)) + 3    
            dataEntries1.append(BarChartDataEntry(y: Double(val1),data:lab as AnyObject))                    
        }
        
        let set1:BarChartDataSet = BarChartDataSet(values: dataEntries1, label: "Set1")
        set1.colors = [ChartColorTemplates.myColor()[6]]
        set1.axisDependency = .right
        
        let chartData = BarChartData(dataSet: set1)
        chartData.barWidth = 0.6
    
        barChartView.data = chartData

        barChartView.animate(xAxisDuration: 1.0, yAxisDuration: 1.0)`


By default, chart plots the bar data from viewport content bottom to content top. But i wanted to render the bars from viewport content top to content bottom .

Thanks

**Comment by liuxuan30** [comment]
just reorgnize the order you add them, like using a sort. The order is fixed so far, so you have to do it yourself.
