### ISSUE TITLE
HorizontalBarChartView labels for rightAxis are clipped

### ISSUE THREAD

**Issue by sohayb** [danielgindi/Charts#3133]
For some reason, the labels for `rightAxis` are clipped, I tried the same code in the sample app but they are still clipped.
<img width="371" alt="screen shot 2017-12-25 at 9 54 59 pm" src="https://user-images.githubusercontent.com/2195533/34339955-a3e5ef68-e9be-11e7-8507-716419f2b16b.png">
This is my chart setup:
```swift
    private func setupChart() {
        chartView.drawBarShadowEnabled = false
        chartView.drawValueAboveBarEnabled = true
        chartView.chartDescription?.enabled = false
        chartView.maxVisibleCount = 10
        chartView.pinchZoomEnabled = false
        chartView.doubleTapToZoomEnabled = false
        chartView.drawGridBackgroundEnabled = false
        chartView.isUserInteractionEnabled = false
        chartView.legend.enabled = false
        
        chartView.xAxis.labelPosition = .bottom
        chartView.xAxis.drawAxisLineEnabled = true
        chartView.xAxis.drawGridLinesEnabled = false
        chartView.xAxis.granularity = 10.0
        chartView.xAxis.valueFormatter = chartFormatter
        
        chartView.leftAxis.drawAxisLineEnabled = false
        chartView.leftAxis.drawGridLinesEnabled = false
        chartView.leftAxis.drawLabelsEnabled = false
        chartView.leftAxis.axisMinimum = 0
        
        chartView.rightAxis.drawAxisLineEnabled = false
        chartView.rightAxis.drawGridLinesEnabled = false
        chartView.rightAxis.axisMinimum = 0
        
        chartView.fitBars = true
        chartView.data = ChartData()
    }
```
The chart is displayed in a `UICollectionView` cell. Tried to make the `chartView` height bigger, that also didn't work, like the height allocated for the labels is fixed, just the chart got bigger.

**Comment by liuxuan30** [comment]
Can you debug `internal override func calculateOffsets()`
```swift
        // offsets for y-labels
        if leftAxis.needsOffset
        {
            offsetTop += leftAxis.getRequiredHeightSpace()
        }
        
        if rightAxis.needsOffset
        {
            offsetBottom += rightAxis.getRequiredHeightSpace()
        }
```
the label's height has been considered, should not happen. And I don't personally remember someone report the same issue. So please try to help if possible. If you are busy, just workaround by changing the `extraOffsetBottom`, just take a look at that func.

**Comment by sohayb** [comment]
@liuxuan30 the issue is in the below function call
```swift
        calculateLegendOffsets(offsetLeft: &offsetLeft,
                               offsetTop: &offsetTop,
                               offsetRight: &offsetRight,
                               offsetBottom: &offsetBottom)
```
Let me expand that, in my setup, I disable legend (`chartView.legend.enabled = false`) so the above function won't return any `offsetBottom` thus, the height is just the label's height. When legend is enabled, all looks normal (see below image). For now, I guess I'll just use your workaround. Thanks! 👍 
<img width="371" alt="screen shot 2018-01-31 at 9 51 12 pm" src="https://user-images.githubusercontent.com/2195533/35624168-88b5f244-06d1-11e8-8093-cbf2a8b65ab7.png">

**Comment by sohayb** [comment]
@abdbinrus93 you can do something simple as this:
```swift
final class ScoreGroupValueFormatter: NSObject, IAxisValueFormatter {
    
    var groupsNames: [String]?
    
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        if let groupsNames = groupsNames {
            let index = Int(value)
            if index >= 0 && index < groupsNames.count {
                return groupsNames[index]
            }
        }
        return String(format: "%.2f", value)
    }
}
```

**Comment by pepejeria** [comment]
FWIW: I had the same issue and solved this by `chartView.extraBottomOffset` value.
