### ISSUE TITLE
Charts demo ipa file request

### ISSUE THREAD

**Issue by tiefighter201** [danielgindi/Charts#3137]
I don't see this app on the itunes app store anywhere.

Can someone provide me the .ipa file for the demo project please?  I would really appreciate it.

I plan to use dropbox to install the app in case you are wondering.

**Comment by jjatie** [comment]
This will not be on the App Store. You can compile and install this yourself with a free developer account from Apple.

**Comment by liuxuan30** [comment]
Seriously we can submit a demo app to AppStore? I would like to add one in my account lol

**Comment by tiefighter201** [comment]
I've done my research and practically the **only** way to make an .ipa file is to use Xcode which **requires** a Mac (real or virtual).

I don't want to go through the hassle of buying/loaning a Mac just to do a quick one-time build and install. I just want the app for demo purposes to allow my colleagues to get a better idea of what new ideas we could implement in our projects using charts in the future.

So I must ask again ,May I please have the file?

**Comment by liuxuan30** [comment]
wait a moment, you "could implement in our projects using charts" without Xcode?
What platform is yours?

**Comment by jjatie** [comment]
You can refer to [MPAndroidChart](https://github.com/PhilJay/MPAndroidChart) for a version that doesn't require a Mac.

**Comment by tiefighter201** [comment]
1. @jjatie, MPAndroidChart is for android devices it won't work with IOS devices as far as I'm aware of(Different ways of installations for the two devices that are incompatible with their counter parts). My colleagues are almost entirely composed of IOS users and I don't see the possibility of them either switching phones or carrying two different phones at once in their own free time just to see what these projects have to offer. 

2. @liuxuan30, My platform is a windows OS and just to clarify on that quotation you made; We **used** to have someone work on IOS projects using Objective C, but that was a long while ago and we are probably not going to touch the language or get a Mac in either several months or possibly years due to other important tasks. The reason I want this .ipa file is for letting them brainstorm on future ideas for additions to our mobile projects. I worked with android and MPAndroidChart and I want them to see and play around with these charts are truly capable are not just get a quick glance.

**Comment by liuxuan30** [comment]
ok.. a rare case, https://pan.baidu.com/s/1dFjNtfz, expire after 7 days

**Comment by tiefighter201** [comment]
@liuxuan30, thank you.  Also I'll see if can find a workaround to install it if I can.
