### ISSUE TITLE
PieChart `highlightValue(x:y:dataSetIndex:)` should provide error for dataSetIndex > 1

### ISSUE THREAD

**Issue by jjatie** [danielgindi/Charts#3146]
The issue in #2862 should provide feedback in the console that PieCharts can only accept an `dataSetIndex == 0`

**Comment by liuxuan30** [comment]
I'm trying to add some issues you mentioned and can be fixed for 3.1

**Comment by liuxuan30** [comment]
I believe you can solve this right?
I'm taking #3244 tomorrow.

**Comment by liuxuan30** [comment]
Turned out #3244 is invalid so far, so I finish off this
