### ISSUE TITLE
Color grid by grid 

### ISSUE THREAD

**Issue by hairui19** [danielgindi/Charts#3147]
Hi, I wish to color each grip (in years in this case) by different color as shown in the image 

[
<img width="408" alt="screen shot 2018-01-03 at 4 44 01 pm" src="https://user-images.githubusercontent.com/24172260/34513882-6ea449ba-f0a5-11e7-9f2d-a4f9df6856e4.png">
](url)

We can see that each grid is colored with alternated colors in this case (grey and milky grey) to make it more stand out. 

How to do that in Charts?

**Comment by liuxuan30** [comment]
we don't support it yet. someone asked this a long time ago and another one gave a implementation. You can try search gird background to find.

**Comment by liuxuan30** [comment]
like https://github.com/danielgindi/Charts/issues/2634
