### ISSUE TITLE
Add a shadow to the line chart

### ISSUE THREAD

**Issue by AndreaMiotto** [danielgindi/Charts#3148]
<img width="640" alt="schermata 2018-01-03 alle 10 47 59" src="https://user-images.githubusercontent.com/11211914/34515636-518608dc-f073-11e7-9b74-161fa311b1dd.png">

is it possible to add a shadow like the one in the image?

Thanks

**Comment by shakked** [comment]
Could probably accomplish this pretty easily by make a `UIView` parent and adding a shadow to that

**Comment by jjatie** [comment]
This is not a planned feature.

From a data visualization perspective this is a nightmare. What value is January? If I had to guess it would be somewhere around 70.
