### ISSUE TITLE
Stop axis labels duplicating.

### ISSUE THREAD

**Issue by steprescott** [danielgindi/Charts#315]
Within the App I have an issue where the labels on the left axis of either a `BarChartView` or a `LineChartView` repeats.

I first added the snippet below to ensure that the number of labels on the axis does not exceed the maximum value in the y data.

```
self.chartView.leftAxis.labelCount = self.chartView.data.yMax > YAxisMaxLabelCount ? YAxisMaxLabelCount : self.chartView.data.yMax;
```

This ensured that if the maximum value in the y data was `3` then there would only be `3` labels within the axis. Now this worked fine if the graph was not interactive, i.e. the user could not zoom the chart.

As soon as the user zooms obviously the count of the labels remains the same and the value formatter fills in the gaps allowing a value to repeat.

*Example of axis with no duplicated values*
![screen shot 2015-08-24 at 5 07 29 pm](https://cloud.githubusercontent.com/assets/1131458/9445187/b72e7c6c-4a82-11e5-934d-fb2a8a0fa691.png)

*Example of same chart but zoomed in*
![screen shot 2015-08-24 at 5 07 54 pm](https://cloud.githubusercontent.com/assets/1131458/9445197/c545bd92-4a82-11e5-9405-aac26c850be0.png)

The screenshots show the left axis repeating the value `2`. What is your best suggestion on solving this repeating label issue? Any help would be grateful. If you need any further information let me know.

Thanks

**Comment by liuxuan30** [comment]
I think it is not the label duplicated, but it contains decimal values and a integer formatter? You need to check what's the raw value for each x axis label and how you format it.

**Comment by steprescott** [comment]
I was able to do this by adding a check to ensure the interval each label is always a whole value.
The change is within the `computeAxisValues()` function of the `ChartYAxisRenderer` class

```
var interval = ChartUtils.roundToNextSignificant(number: Double(rawInterval))
if(_yAxis.valueFormatter?.maximumFractionDigits == 0)
{
    interval = interval < 1 ? 1 : floor(interval)
}
```

If the value formatter request there to be no fractional digits then it floors the intervals and if it is less then the whole number 1 it sets it the interval to `1`.

Would you like a pull request?

**Comment by liuxuan30** [comment]
If you are having decimal values, why maximumFractionDigits is 0? I think it's the formatter issue.

**Comment by steprescott** [comment]
I don't want decimal values that is why I set `maximumFractionDigits = 0`

**Comment by liuxuan30** [comment]
pal, your data is decimal, and you just want to use formatter to abandon the fraction digits, it does not make sense. Why not try to convert your data to integers?

**Comment by steprescott** [comment]
The y values I give to the chart are 
```
(1, 3, 2, 0, 0, 7, 0)
```
Once I create a `ChartDataSet` these values are then doubles.

```
ChartDataSet, label: , 7 entries:
ChartDataEntry, xIndex: 0, value 1.0
ChartDataEntry, xIndex: 1, value 3.0
ChartDataEntry, xIndex: 2, value 2.0
ChartDataEntry, xIndex: 3, value 0.0
ChartDataEntry, xIndex: 4, value 0.0
ChartDataEntry, xIndex: 5, value 7.0
ChartDataEntry, xIndex: 6, value 0.0
```

This is because your `ChartDataEntry` Class holds the value as a `Double`
```
/// the actual value (y axis)
public var value = Double(0.0)
```
Although the values have been changed to a double the charts do show the correct increment of labels at first but as soon a the chart is zoomed in, the `ChartYAxisRenderer ` wishes to fill in the gaps and as my value formatter removed any fractional digits it shows as a duplicated value.

I do not want the chart to assume I want additional values in-between the whole numbers as only want to show a label for a whole number.

So this leads me to see that I am supplying the correct data to the chart, but the chart is making assumptions on what I want to do. This is fine for a default but should provide the option to only show whole numbers on the axis too. 

By adding the check against the value formatter it allows this behaviour. You might know of a better way to provide this behaviour rather than checking the value formatter but it is a use case some people my want.

**Comment by steprescott** [comment]
I have just noticed that I am using the code base at commit `a7e30dd16fbfaecb8e44c01ad8618a3a745fd101` and when this change is implemented into the latest commit of Charts it does not act as expected.

**Comment by steprescott** [comment]
I have attached a gif of the expected behaviour.

Below you can see that no labels show the same value and the chart is not attempting to place any label in-between other labels as there is the requirement that the labels are whole values.

![chart](https://cloud.githubusercontent.com/assets/1131458/9548318/d60b9b84-4d97-11e5-8f07-27ac4b695cdf.gif)

**Comment by liuxuan30** [comment]
Ah I see. If you zoom to let's say [3,4], the range would be [3,4] and the axis wants to display [3.0, 3.2, 3.4, 3.6, 3.8, 4.0], and you don't want fractional digits, is it?

It's actually nothing I can do... since your data is quite small, and we have to display 4-6 labels there... What if the range is [0,1], and you need to display 5 labels, what can you display other than fractional digits?

I think it's fine to display fractional digits if the range is too small, but if you truely don't want it, then you can do it like your did. Or you would accept only show the max and min label called `showOnlyMinMaxEnabled`

**Comment by liuxuan30** [comment]
BTW, your screenshots works great, solved your problem

**Comment by liuxuan30** [comment]
There is also some properties to help you limit the label count. You can try modify and fit for different scale levels.
```Swift
    public func setLabelCount(count: Int, force: Bool)
    {
        _labelCount = count
        
        if (_labelCount > 25)
        {
            _labelCount = 25
        }
        if (_labelCount < 2)
        {
            _labelCount = 2
        }
    
        forceLabelsEnabled = force
    }
```

**Comment by noais** [comment]
To have the same behaviour on the Y axis is necessary to set a Y zoom limit. #382

**Comment by noais** [comment]
#388

**Comment by liuxuan30** [comment]
@steprescott, is #388 solved your problem?

**Comment by steprescott** [comment]
From looking at the commit for issue #388 the only change is a new property on viewport.

How would I get the intended behaviour that is shown in the gif but with your changes?

**Comment by noais** [comment]
Hi @steprescott, try with  [_chartView.viewPortHandler setMaximumScaleY: 2.f]; for example, like this the granularity of the zoom isn't so big to show repeated values. A good example is when you have a horizontal char line without a limit all Y values are repeated with maxScale this repetition doesn't happen.

Whiteout limit:
![screen shot 2015-09-22 at 23 29 16](https://cloud.githubusercontent.com/assets/1105727/10033559/13e57f3a-6182-11e5-985d-bbecadd0d9bc.png)
 
With limit 2f:
![screen shot 2015-09-22 at 23 30 07](https://cloud.githubusercontent.com/assets/1105727/10033573/28d5b4aa-6182-11e5-850e-2940cf7911ce.png)

**Comment by steprescott** [comment]
That works on a dataset that has a lager range of values but if you have a small range of values, example being an array of values 0 - 7, zooming in by a factor of 2 could potentially provide duplicate labels.

Although by limiting the zoom factor has solved your issue, it dose not solve the issue of repeating whole values.

I did get my expected results when editing the `ChartYAxisRenderer ` class pointing at commit a7e30dd16fbfaecb8e44c01ad8618a3a745fd101.

This was done by flooring the value.

```
var interval = ChartUtils.roundToNextSignificant(number: Double(rawInterval))
if(_yAxis.valueFormatter?.maximumFractionDigits == 0)
{
    interval = interval < 1 ? 1 : floor(interval)
}
```

Although this worked (but not when using HEAD of this repo) I feel that you guys will know a better place within your framework to place this to provide the same result as shown in the gif.

Maybe a property `allowRepeatingValues` `BOOL` on a axis. You guys will know better.

**Comment by noais** [comment]
Yes you right this was one work around. Let me try to see if is easy to create some method like allowRepeatingValues.

**Comment by steprescott** [comment]
That would be most helpful, thank you.

**Comment by steprescott** [comment]
Hey @noais and @liuxuan30. Have you had chance to investigate this? I was able to get the required effect using the framework but I don't know of where best this property should sit within the framework and if there is a better way to achieve the same result.

Thanks for your time.

**Comment by liuxuan30** [comment]
I am still thinking it's because the formatter that produced duplicated labels with small digits, not the algorithm. If you delete the formatter, it will display the number correctly, right?
You can solve it with your code, but I am not sure if it's a good one for every one.
@danielgindi what do you think

**Comment by injectios** [comment]
Hi guys, voting for allowRepeatingValues, I have small numbers and don't want to display duplicated y-axis valuse

**Comment by davem2020** [comment]
When all my values are zero, the y axis repeats 0 and 1-
![chart](https://cloud.githubusercontent.com/assets/1378780/10264285/41d034f4-69c4-11e5-83c6-ea4351ccb4f7.jpg)

**Comment by davem2020** [comment]
When all my values are zero, I get these repeating axis labels-
![chart](https://cloud.githubusercontent.com/assets/1378780/10264293/6bc7d9c4-69c4-11e5-93ec-60da45522f93.jpg)

**Comment by steprescott** [comment]
Also, I've noticed that although the code snippet I have does what I need, it is not removing duplicate values simply only allowing whole numbers. So by checking against the number formatter isn't a horrible way of adding this.

What that snippet doesn't' allow is removing of duplicated values so if the values were `1.1, 1.2, 1.2, 1.3` and you wished to keep the single decimal digit it would not work. You guys will know the best place and implementation for this feature and for people to spend time looking at the current issues of the framework and for them to then up vote it shows it's an option others want too.

**Comment by Np2x** [comment]
allowRepeatingValues :+1:

**Comment by steprescott** [comment]
@noais @liuxuan30 Do you have a better solution to this than what I have suggested?

**Comment by liuxuan30** [comment]
nope, except for allowRepeatingValues.. Because your original problem is about the formatters. you don't want decimal digits but your data actually has

**Comment by vigyanhoon** [comment]
Ideally graph should't show repeating values, ever! Can repeating values be hidden with some logic, thus resulting in only unique values?

**Comment by liuxuan30** [comment]
@vigyanhoon it's not 'repeating' values behind, it's formatter that causes the value to be 'repeated'. If you don't want repeat, give a decimal formatter can solve it.

**Comment by steprescott** [comment]
@liuxuan30 Can you explain what you mean by "_give a decimal formatter_"? With my data I gave a formatter that set the `maximumFractionDigits = 0`. I'm not sure how to get the expected results with what is currently there? Have you been able to produce a chart with the framework as it is that gives the same results as my gif I posted on the 28th August?

**Comment by injectios** [comment]
Did you mean to use numberFormatter.allowsFloats = NO, if yes, it didn't help me, I still see duplicated ints

**Comment by liuxuan30** [comment]
@steprescott sorry if I'm not clear. `MaximumFractionDigits` should not be 0, otherwise it will only show the integer part. I did met similar issues, if the data range is small and 5~6 labels needed, giving maximumFractionDigits = 0 will have repeated values. There is no easy way to fix this I guess. think about if the data range is [0,2], and I have to display 5 labels: 0, 0.4,0.8,1.2,1.6, 2.0. If we apply maximumFractionDigits = 0, it maybe 0, 0, 1, 1, 2, 2

**Comment by jpros** [comment]
Hey everyone!
I'm having this same issue.

@liuxuan30 depending on the type of data, it doesn't make sense to have decimals. Like a chart of humans, you will never have 1.5 humans, its either 1 or 2.

**Comment by liuxuan30** [comment]
@jpros you got a point, but from the math point, we cannot have 4 labels without decimals in range [0,2]. 

If you have troubles

So either turn on `yAxis.showOnlyMinMaxEnabled` to avoid repeated values as work around for now, 
Or you implement your logic to calculate your own values in `ChartYAxisRenderer.computeAxis` to avoid,
Or we have to wait for feature 'allowRepeatValues'

**Comment by danielgindi** [comment]
@PhilJay do we have any solution for that currently? :-)

**Comment by PhilJay** [comment]
From an Android (and ofc iOS) POV, this line here: https://github.com/PhilJay/MPAndroidChart/blob/master/MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRenderer.java#L108

Could be a location to tackle this problem. There have the `float interval`of the axis labels calcualted, and could use it to prevent further changes to the labels if two labels would be formatted equally.

**Comment by vigyanhoon** [comment]
I got rid of duplication by setting a max value

leftAxis.customAxisMax = maxYLabelCount

**Comment by liuxuan30** [comment]
@vigyanhoon it's a bad one, values could be millions, while maxYLabelCount can't

**Comment by natanrolnik** [comment]
+1 for solving the rendering issue. I have also a graph of people, and I'm having [0, 0, 1, 1, 2, 2]. Setting the `numberFormatter.maximumFractionDigits ` to anything other than 0 doesn't make any sense.

**Comment by natanrolnik** [comment]
The following code suggested by @steprescott fixed for me as well:

```swift
var interval = ChartUtils.roundToNextSignificant(number: Double(rawInterval))
if(_yAxis.valueFormatter?.maximumFractionDigits == 0) {
    interval = interval < 1 ? 1 : floor(interval)
}
```

Would a PR be able to close this issue? What do you think @danielgindi @liuxuan30 @steprescott ? Are there cases this code doesn't fix? If so, what are better solutions?

**Comment by liuxuan30** [comment]
@natanrolnik I think one scenario it can't fix is that, if I zoom in a lot, when it comes to a small range, the granularity can't be guaranteed because of the smallest interval 1, while it should be 0.5, 0,1, etc?

**Comment by liuxuan30** [comment]
@natanrolnik if user specificly set max fraction number to 0, what if the user zoom in and range become [0.2, 0.3]? The interval would be 1.0 while it should be, say 0.02. I didn't test negative values though.

**Comment by natanrolnik** [comment]
I agree regarding `allowRepeatedValues`!

**Comment by noais** [comment]
I think the @steprescott is a good solution. Only needs to adjust the value one to a granularity variable.

With this @liuxuan30 problem don't exists any more.

**Comment by noais** [comment]
If we put this code on line 75 in ChartYAxisRenderer:
```
interval = interval < granuality ? granuality : floor(interval)        
if(interval == granuality){
    return ;
}
```

**Comment by steprescott** [comment]
Ok, so this is now closed but it isn't merged into master. When would this be likely to happen?

**Comment by noais** [comment]
https://github.com/danielgindi/ios-charts/pull/640
I'm waiting for some help...

**Comment by noais** [comment]
https://github.com/danielgindi/ios-charts/pull/648

**Comment by danielgindi** [comment]
This is released in 2.2.4, as the `granularity` feature

**Comment by Aaimek** [comment]
I'm not sure if I should post this issue here but it makes sense to me.

I have a very similar problem with my xAxis labels. I have a custom IAxisValueFormatter that returns strings for time, it gives hours like this "22:00", "23:00" for some charts, week dayslike this "Mon.", "Thu." for others etc..

When the chart is zoomed in too much, the values start to duplicate like shown here:

![Screenshot 2019-07-19 at 17 59 11](https://user-images.githubusercontent.com/21154939/61548844-eb198500-aa4e-11e9-8fc9-c859cba1c0d5.png)


In this case the `granularity` feature doesn't work since it works with the difference between numbers.

Do you have any Idea of how I could stop those labels from repeating?

Thanks

**Comment by mickaelhero** [comment]
Set granularityEnabled to false work for me
`leftAxis.granularityEnabled = true`

**Comment by aymenbraham** [comment]
Hello guys , i want to make xAxis value not repeating when zoom in
        my Formater : 
      func stringForValue(_ value: Double, axis: AxisBase?) -> String {
    let date = Date(timeIntervalSince1970: value)
         return date.formattedString(withDateFormat: .daymonth)
} 
     also i use granularity , but i still have the same issue 
        xAxis.granularity = 1.0
        xAxis.granularityEnabled = true 

can anyone know how to solve it plz ?

**Comment by aymenbraham** [comment]
@Aaimek 
i have the same issue , did you  find the solution ?

**Comment by adarshjayan7574** [comment]
I have the same issue when I force x-axis label count, and plots a few points.
