### ISSUE TITLE
How to make highlight scrolling on chart not trigger parent scrollView? [help]

### ISSUE THREAD

**Issue by shakked** [danielgindi/Charts#3153]
So I’m having this issue where in a scrollView, I have a bar chart. In the charts, you can slide left to right to highlight different values in the bar chart. What happens though is by sliding left to right, if you go up or down, the scroll view will scroll as well. How can I make it so that when I’m sliding on the chart left to right, the scroll view won’t scroll vertically?

[Demo](https://imgur.com/a/PhG6Y)

**Comment by s1m-0n** [comment]
Having the same problem - keen to get to know the answer :)

**Comment by jjatie** [comment]
You need to make the scrollview's gesture recognizer require the chart's gesture recognizer to fail. For [more information](https://developer.apple.com/documentation/uikit/uigesturerecognizer)

**Comment by raisezhang** [comment]
@shakked   I have the save problem， Do you have  some code snippet  on it?   Thanks~

**Comment by Args** [comment]
save problem + 1
