### ISSUE TITLE
HorizontalBarChart doesn't display bar draw values when bar is partially off ViewPort

### ISSUE THREAD

**Issue by software-2** [danielgindi/Charts#3155]
I have a HorizontalBarChart with draw values enabled. The problem is that these values disappear when any part of the bar is no longer within the viewport.

![screen shot 2018-01-04 at 3 48 44 pm](https://user-images.githubusercontent.com/20566902/34590159-ccecc76c-f169-11e7-9aa4-a219f9651bc5.png)
![screen shot 2018-01-04 at 3 48 55 pm](https://user-images.githubusercontent.com/20566902/34590163-cff36600-f169-11e7-962d-7f7ac5215729.png)
![screen shot 2018-01-04 at 3 49 17 pm](https://user-images.githubusercontent.com/20566902/34590168-d4131d66-f169-11e7-90e4-dc4ede453b9c.png)

Looking at the HorizontalBarChartRenderer class's drawValues function, it looks like there is code specifically to abort drawing if this is the case:

```
if !viewPortHandler.isInBoundsX(rect.origin.x)
{
    continue
}
```

**Comment by liuxuan30** [comment]
yes, that's how it works. either you override the method, or increase your axis range.

**Comment by software-2** [comment]
It seems like the intent here is to avoid drawing/processing for values that wouldn't appear on the screen anyway. But this method of determining bounds is too aggressive and omits values that are still on the screen. If this is indeed the design, could you please explain the design reason for this?

**Comment by liuxuan30** [comment]
there is no any particular reason for this. ASAIK it uses a simple condition to check, which I'm start understanding not quite good.

But if you think any of it is not correct way to do it, you can file a PR to fix it, and we would be grateful to review and merge.
