### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by ewerton16** [danielgindi/Charts#3156]
Hey,

I can run my app on virtual devices (Iphone 5S or others devices), perfectly.
I'm trying to run my app on my physical device (iPhone 7Plus) but Xcode returns me this message:

-------------------------------
> sent 4341295 bytes  received 70 bytes  8682730.00 bytes/sec
> total size is 4340527  speedup is 1.00
> Code Signing /Users/ewertongorski/Library/Developer/Xcode/DerivedData/FinanceJE2-cxfvqzcxapnxghffbvbhvpsyqczf/Build/Products/Debug-iphoneos/FinanceJE2.app/Frameworks/Charts.framework with Identity iPhone Developer: Ewerton Gorski (9K3FEBZSCP)
> /usr/bin/codesign --force --sign 224C41EEBD6F9C41F9334F23523CABE8B700FB5C  --preserve-metadata=identifier,entitlements '/Users/ewertongorski/Library/Developer/Xcode/DerivedData/FinanceJE2-cxfvqzcxapnxghffbvbhvpsyqczf/Build/Products/Debug-iphoneos/FinanceJE2.app/Frameworks/Charts.framework'
> /Users/ewertongorski/Library/Developer/Xcode/DerivedData/FinanceJE2-cxfvqzcxapnxghffbvbhvpsyqczf/Build/Products/Debug-iphoneos/FinanceJE2.app/Frameworks/Charts.framework: unknown error -1=ffffffffffffffff
> Command /bin/sh failed with exit code 1
-------------------------------

And here my Podfile:
-------------------------------
> ## Uncomment the next line to define a global platform for your project
> platform :ios, '10.0'
> inhibit_all_warnings!
> use_frameworks!
> 
> target 'FinanceJE2' do
> 
>   # Pods for FinanceJE2
>   pod 'Firebase'
>   pod 'Firebase/Database’
>   pod 'Charts'
>   pod 'ChartsRealm'
> 
> end
-------------------------------

I don't have any idea what to do to fix this error. Could you help me?

**Comment by liuxuan30** [comment]
I can say nothing from your log: 
>Charts.framework: unknown error -1=ffffffffffffffff

Missing Xcode version and please try clean and point Charts to master

**Comment by liuxuan30** [comment]
And regards ChartsRealm, I just have pushed 2 commits fixing it on Xcode 9.2 with Realm.
I'd say if you don't need ChartsRealm, just delete it, because Realm itself does not release a prebuilt framework, so we need to build one from source, really time consuming.

**Comment by ewerton16** [comment]
It's strange, because I've already done the framework in my app for 1 year and It doesn't work from 3 days ago. I've already removed the ChartsRealm and updated Charts to master... I develop my app in ObjC, using Swift 4.0 in Charts
