### ISSUE TITLE
Bar coloring

### ISSUE THREAD

**Issue by drewg233** [danielgindi/Charts#3157]
I am trying to achieve the same look and feel as the following image:

<img width="410" alt="screen shot 2018-01-05 at 5 33 07 pm" src="https://user-images.githubusercontent.com/6364990/34632978-92ce28b6-f23e-11e7-8d0a-d9a7615c1792.png">

I have achieved most of this except the coloring. It seems as though you can't set the colors for a specific bar. Only set the colors for all the bars at once. Is that correct? As you can see I what I need from the image that the colors are not in order. So I need to set the coloring for each value on a bar.

**Comment by alekzuz** [comment]
Yes, you have to prepare all colors at once. Flatmap your data and assign color for each value.
