### ISSUE TITLE
bar chat 

### ISSUE THREAD

**Issue by AlonMoveo** [danielgindi/Charts#3158]
Contextual type 'IChartDataSet' cannot be used with array literal 
should i implement all functions of 'IChartDataSet'? i mean, do i have to inherit this protocol in order to build up bar chart?

**Comment by jjatie** [comment]
I think you should look at the examples in the demo.

**Comment by liuxuan30** [comment]
it's just a base protocol. you should use BarChartDataSet as the standard implementation.
