### ISSUE TITLE
ChartLimitLine Label Position

### ISSUE THREAD

**Issue by diogoAntunes** [danielgindi/Charts#3161]
Is it possible to have the `ChartLimitLine` labelPosition to `.right` to have something like:

![Image of chart](https://i.imgur.com/2sFMNhn.png)

**Comment by liuxuan30** [comment]
you add override it or implement it and file a pull request for us 
Closing for now, and if you decide to file a PR, reopen it, thanks :)

**Comment by SubrahmanyaSrinivasKasanna** [comment]
I have the same requirement. Please post solution here if you had any.
