### ISSUE TITLE
StackedBarChart Value on middle of each stacked bar chart 

### ISSUE THREAD

**Issue by avjiang** [danielgindi/Charts#3162]
Hi, very great library!

Btw, how can I set the chart value position on the middle of it? 

i try to dig and found this code, but i dont know how to make it appear on the middle of the each barchart. Currently, the value will be displayed on the top of the chart (still inside the chart) 

barChartView.drawValueAboveBarEnabled = false

```swift
               if dataSet.isDrawValuesEnabled
                        {
                            drawValue(
                                    context: context,
                                    value: formatter.stringForValue(
                                        e.y,
                                        entry: e,
                                        dataSetIndex: dataSetIndex,
                                        viewPortHandler: viewPortHandler),
                                    xPos: x,
                                    yPos: y,
                                    font: valueFont,
                                    align: .center,
                                    color: dataSet.valueTextColorAt(index))
                        }
```

**Comment by jjatie** [comment]
To clarify, are you asking how to draw a bar's value label in the middle of the bar OR are you asking how to draw all the value labels in the middle of the chart?

**Comment by avjiang** [comment]
hi, what I mean is how to draw a bar's value label in the middle of a bar. so if there is 5 bars in 1 bar chart, the value of 5 bars will be drawn in the middle of each bar. thanks!

**Comment by jjatie** [comment]
@liuxuan30 ?

**Comment by liuxuan30** [comment]
I think you already found the right place to override. Just pass the desired y position to draw the labels. use barRect calculation to calculate where is your half bar y position.

**Comment by BestieSingh** [comment]
Can you explain what that drawValue method is??

**Comment by BestieSingh** [comment]
@liuxuan30 ?
