### ISSUE TITLE
dash line (separators) in between in bars.

### ISSUE THREAD

**Issue by JayeshThanki** [danielgindi/Charts#3163]
Hello,
need help in displaying separators between bars.

For example : in attached image, there is 28 bars for 4 weeks,

![screen shot 2018-01-08 at 3 57 47 pm](https://user-images.githubusercontent.com/8011134/34666936-bbbc94d8-f48c-11e7-95c0-bff9cdfde301.png)

**Comment by jjatie** [comment]
Are you referring to the ticks on the x-axis?

**Comment by liuxuan30** [comment]
you have to override `drawAxisLine` to draw those tiny ticks.
