### ISSUE TITLE
ChartViewDelegate not called when barChart is out of screen

### ISSUE THREAD

**Issue by ludovic-coder** [danielgindi/Charts#3165]
I got a horizontal scrollView with a BarChartView like :
- ScrollView
  - ContentView
    - View (with Labels and a button to scrollTo) frame: (0,0, ScreenWidth, ScreenHeight)
    - BarChartView frame: (ScreenWidth, 0, ScreenWidth, ScreenHeight)

On viewDidLoad() I'm calling a setChart methods

    func drawActivityChart() {

        activityChart.chartDescription?.text = ""
        activityChart.noDataText = "Aucunes données à afficher"
        activityChart.doubleTapToZoomEnabled = false
        activityChart.drawValueAboveBarEnabled = false
        activityChart.drawBarShadowEnabled = false
        activityChart.dragYEnabled = false
        activityChart.dragXEnabled = false
        activityChart.legend.enabled = false
        activityChart.drawGridBackgroundEnabled = false

        activityChart.xAxis.drawLabelsEnabled = false
        activityChart.xAxis.drawAxisLineEnabled = false
        activityChart.xAxis.drawGridLinesEnabled = false

        activityChart.leftAxis.drawGridLinesEnabled = false
        activityChart.leftAxis.drawAxisLineEnabled = false
        activityChart.leftAxis.drawLabelsEnabled = false

        activityChart.rightAxis.drawGridLinesEnabled = false
        activityChart.rightAxis.drawAxisLineEnabled = false
        activityChart.rightAxis.drawLabelsEnabled = false

        //activityChart.animate(yAxisDuration: 0.5)

        // Draw graph
        let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
        let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0]

        var dataEntries: [BarChartDataEntry] = []

        for i in 0..<months.count {
          let dataEntry = BarChartDataEntry(x: Double(i), y: unitsSold[i])
          dataEntries.append(dataEntry)
        }

        let chartDataSet = BarChartDataSet(values: dataEntries, label: nil)
        chartDataSet.drawValuesEnabled = false
        chartDataSet.colors = [UIColor].init(repeating: Default.white.withAlphaComponent(0.2), count: 12)
        chartDataSet.highlightColor = Default.white
        chartDataSet.highlightEnabled = true

        let chartData = BarChartData(dataSets: [chartDataSet])
        chartData.highlightEnabled = true
        activityChart.data = chartData

    }

Tap on graph to hilight a bar is not working at all (like all gesture). It the barChart is visible on screen everything works properly of course.

**Comment by liuxuan30** [comment]
need some context first. why the bar chart view is out of screen, yet you still can see and tap it?

**Comment by ludovic-coder** [comment]
Because graph is on an horizontal scrollview, in page mode. I need to set a custom gesture when the scrollview scrolled to the graph. I'm not sure it's a Charts bug, it's probably a workaround with UIGesture.

**Comment by liuxuan30** [comment]
You don't clear the paradox here. You don't see the bar on the screen yet you can tap it.
>Tap on graph to hilight a bar is not working at all (like all gesture). It the barChart is visible on screen everything works properly of course.

This sounds works expected to me. But you should be able to debug I believe.
