### ISSUE TITLE
Add Axis description to Charts Framework

### ISSUE THREAD

**Issue by rameswar54** [danielgindi/Charts#3168]
I searched in the code to add description line for X & Y Axis but it seems this feature is not included in the framework (Correct me if I'm wrong). Do you guys think adding a description for each Axis will be good feature. I'm interested to know in case anything stopped the inclusion of this into Charts.
 
This is issue is an idea and would like to have a discussion and I'm interested to contribute if this gets approved.

**Comment by thierryH91200** [comment]
look at #2477  or #2452

**Comment by rameswar54** [comment]
@thierryH91200 Thanks for the reference. I did check the code base and but forgot to check the PRs. As it's review in pending state, I'm closing this issue. :)
