### ISSUE TITLE
How to show/hide Stacked Bar Chart yValue?

### ISSUE THREAD

**Issue by kuldeep13990** [danielgindi/Charts#3175]
Currently it show all values like in 1st Image but I want to show only selected bar value like 2nd image, once i deselect it value is gone.

![simulator screen shot - iphone 6 - 2018-01-12 at 19 11 10](https://user-images.githubusercontent.com/5965337/34877510-5d53a2f4-f7cc-11e7-9ede-51ff9a604d65.png)

![pasted image at 2018_01_13 10_45 am](https://user-images.githubusercontent.com/5965337/34903098-26906d54-f850-11e7-8f20-fcbe73882280.png)

I tried but not able to do this.
Please help me to achieve this.

**Comment by liuxuan30** [comment]
what you have tried..? You can disable `drawValues` and just show value when highlighted.
either override `drawHighlighted` or `drawValues()` in bar chart renderer.
