### ISSUE TITLE
Want to delete color set beside legend label

### ISSUE THREAD

**Issue by mononomo** [danielgindi/Charts#3180]
Hello everyone, I have some problem with my Horizontal Chart. I want to close the color beside a legend below chart but I can't find a way to delete it.

Is it has a way to close it or can't. Thank you.

<img width="292" alt="screen shot 2561-01-15 at 4 54 16 pm" src="https://user-images.githubusercontent.com/1757963/34936769-3153c62a-fa15-11e7-8972-e0d6f84c3eba.png">

**Comment by liuxuan30** [comment]
please check `drawForm()`, if 
```swift
        /// Avoid drawing a form
        case none
        
        /// Do not draw the a form, but leave space for it
        case empty
```
suits you
