### ISSUE TITLE
How to asynchronous drawings LineChart?

### ISSUE THREAD

**Issue by AfraXu** [danielgindi/Charts#3192]
How to asynchronous drawings LineChart?

**Comment by AfraXu** [comment]
How to asynchronous drawings.

**Comment by Karpot** [comment]
Drawing must be done in the main thread. You can do all none drawing calculation in another thread but than dispatch the draw call into the main thread.

**Comment by liuxuan30** [comment]
reopen with more details. Not quite sure the meaning.
