### ISSUE TITLE
Bar charts with different column widths

### ISSUE THREAD

**Issue by wltrup** [danielgindi/Charts#3204]
Hi Daniel.

I'd like to create a bar chart where the columns have different widths.

From what I can tell, `BarChartDataEntry` only has initialisers with a single value of `x`, the centre value of the column for the corresponding data point, and the common width of all columns is set using `BarChartData`'s `barWidth` method.

Is there a way to create such a chart? I was expecting an initialiser along the lines of `init(xmin: Double, xmax: Double, y: Double)` and was surprised not to find one.

Thanks!

**Comment by vilapuigvila** [comment]
Hi, I'm in the same situation..

**Comment by liuxuan30** [comment]
it's not supported with different bar width. you can try create one and file a PR. We would be grateful to review and merge.
But before doing that, I don't see it's very reasonable or popular to see different width bars.

**Comment by jessicafrank204** [comment]
@wltrup @vilapuigvila 
Hi, I'm also looking to create a chart with different bar widths. Were you able to solve this issue? Thanks.

**Comment by wltrup** [comment]
@jessicafrank204 @vilapuigvila 

Our workaround is to render several bars next to each other, all with the same height, to simulate a single bar of that height and a custom width.

**Comment by jessicafrank204** [comment]
@wltrup 
Ok, thank you.
