### ISSUE TITLE
Cannot set double value in Combined chart line chart.

### ISSUE THREAD

**Issue by sharatkannan** [danielgindi/Charts#3205]
Set double value in combined chart line chart. chart shows rounded value. 
Is any way to show the double value in line chart in combine chart?

**Comment by liuxuan30** [comment]
check demo. showing just means its uses formatter,  but it's always double.

**Comment by sharatkannan** [comment]
In combined chart demo: just give line graph data entry x value as 2.790 it shows as 3 in graph.

**Comment by jjatie** [comment]
Look at the `DefaultValueFormatter` and `DefaultAxisValueFormatter` (depending on which values you’re trying to format). There is a `decimals` property you can set to choose how many decimal places you want.
