### ISSUE TITLE
Recent release with my Swift3 project

### ISSUE THREAD

**Issue by NikhilManapure** [danielgindi/Charts#3208]
How can I use most recent release with my Swift3 project?

**Comment by jjatie** [comment]
You can’t. You need to use the last version that supports swift 3 (Charts 3.0.2 I believe)

**Comment by liuxuan30** [comment]
It's pain in the a** that if one of your 3rd framework not updated, you are kidnapped by the swift compiler.
You could check out the old commit which is last on swift 3, and manually add what you needed...
