### ISSUE TITLE
Unable to Hide PieChart Legends. 

### ISSUE THREAD

**Issue by ZUCheema** [danielgindi/Charts#3209]
The legend.isEnabled can not be set as its get only property neither I can find drawLegends property.

**Comment by jjatie** [comment]
the current API is `legend.enabled = false`. There are issues with the current boolean naming in Swift, and will be resolved for Charts 4.0 in late spring.

**Comment by ZUCheema** [comment]
Thanks. It worked.

**Comment by ZUCheema** [comment]
Its hides legend text only. Not the colour squares. Moreover, My Pie chart is not showing properly, can you help about what is wrong?
![screen shot 2018-01-25 at 6 40 15 pm](https://user-images.githubusercontent.com/21374887/35391105-7c9c9c1e-01ff-11e8-9cc5-b37d23b1f7e2.png)

**Comment by neodave** [comment]
> Thanks. It worked.

I am having the same issue, but don't understand the answer. Which API? How do you call that? Obviously I am missing something because I have searched the code for how to call the API and come up empty. Sorry if this seems obvious to you...
