### ISSUE TITLE
Release 3.0.5 contains version number inconsistencies

### ISSUE THREAD

**Issue by sortingthoughts** [danielgindi/Charts#3210]
The version number of release 3.0.5 is not used in the whole project:

- Changelog hangs in version 3.0.3
- Charts/Source/Supporting Files/Info.plist contains also 3.0.3

This makes it hard to check the used version of Charts in an existing project, especially without dependency manager.

**Comment by liuxuan30** [comment]
seems Changelog depends on Info.plist? it's auto-generated.

**Comment by liuxuan30** [comment]
I have bumped Info.plist version. Sorry I forgot to update it.
