### ISSUE TITLE
BarChartView bug if set barWidth was 1.0?

### ISSUE THREAD

**Issue by freecnpro** [danielgindi/Charts#3213]
it seems the simulator did not have this problem :(
![bug](https://user-images.githubusercontent.com/3022374/35429239-27bdb674-02ae-11e8-93a5-fa76f4c5dfe5.jpeg)

**Comment by jjatie** [comment]
You have not provided a question or issue for us to help you with.

**Comment by freecnpro** [comment]
@jjatie sorry, I want remove space between bars, but not working fine. There is a line between bars, like below the image. (running on iPhone 6)
![bug](https://user-images.githubusercontent.com/3022374/35496089-9592963a-04ff-11e8-818a-d69b1c46d0f6.jpeg)

**Comment by liuxuan30** [comment]
I remember I saw similar issues before.we are drawing bars, so bars appear. I'm not sure if this is pixel alignment issue or not. If it is, you can try round x values to remove?
But if you don't want those bars, why using a bar chart view?
line chart view has a stepped mode, which does the same thing. All you have to do is to fill the path then.
