### ISSUE TITLE
How easy is to add some technical indicators?

### ISSUE THREAD

**Issue by acidos** [danielgindi/Charts#3219]
How can I add technical indicators like Bollinger Bands overlaying candlestick charts? Is it something foreseen for this framework? I would like to assess how much efforts it requires to add technical indicators or signals on top of chart.

**Comment by liuxuan30** [comment]
are you referring to `ChartMarker`?

**Comment by acidos** [comment]
If `ChartMarker` is persistent and not depending on click, then yes.
![image](https://user-images.githubusercontent.com/298480/35503006-247c6482-04df-11e8-803b-44a455c34a56.png)
But also as you can see above, technical indicators are consisting of area series on top of candlestick + line series in the middle.

**Comment by liuxuan30** [comment]
well... An image like above is not supported. But this library is also a good platform or framework you can add your own stuff in `drawExtra`, or just override some methods, as long as you understand how it works.. But I'd say it's not a easy one, but the idea is straightforward.

You have to figure out those points and positions you want to draw, and use the API to render them.
