### ISSUE TITLE
Why is the xAxis Value Formater so often called?

### ISSUE THREAD

**Issue by dadidu67** [danielgindi/Charts#3220]
A chart with only 20 values and 6 xAxis labels calls the formatter many time with the same value. Waste of resources: 

func stringForValue(_ value: Double, axis: AxisBase?) -> String

value: 3.0
value: 6.0
value: 9.0
value: 12.0
value: 15.0
value: 18.0
value: 3.0
value: 6.0
value: 9.0
value: 12.0
value: 15.0
value: 18.0

**Comment by jjatie** [comment]
Please provide a reproducible code sample.

**Comment by liuxuan30** [comment]
close as no update since then. reopen with details. only pasting a lot of logs does not help at all.
