### ISSUE TITLE
Make specific pieChart segment stick out and go back to normal size, animated

### ISSUE THREAD

**Issue by kalmurzayev** [danielgindi/Charts#3224]
I need to animate sticking out for one of the PieChart segments and vice versa. See image.

<img width="249" alt="screen shot 2018-01-29 at 6 42 47 pm" src="https://user-images.githubusercontent.com/2243005/35510826-e30e434a-0523-11e8-89b5-5ffde5e16f5f.png">

The purple one with 28 percents needs to go from normal state to popped-out state animated. If anyone ever came across such feature, please help.
Thanks.

**Comment by liuxuan30** [comment]
please check animator classes and pie chart renderers to see if you can create an animation for that. And a PR is more then welcome!

**Comment by kalmurzayev** [comment]
Thanks. I should make a PR to master, right?

**Comment by kalmurzayev** [comment]
Ok, I looked through the code and found out that:
- you can set PieChartView's renderer property to your own custom renderer
- but you can't set PieChartView's animator, as it is a read-only property. So yeah, I guess I'll have to make a PR with my changes
