### ISSUE TITLE
Pin the graph on one side while zooming

### ISSUE THREAD

**Issue by jackguo709** [danielgindi/Charts#3232]
Hi,

Is there a way to pin the line graph on the right side while zooming? So when I zoom it, it only scales and extends towards left, rather than extending both ways. Thank you

**Comment by liuxuan30** [comment]
hmm... that's an interesting question. you can try `setVisibleXRange` and `MoveViewToX` functions. more likely, you will want to take a look how they are implemented so you might implement something you need.

**Comment by jjatie** [comment]
StackOverflow might be your best bet.

**Comment by liuxuan30** [comment]
yup, we are encouraging people to use SO for general questions, we are overwhelmed by reading and answering them by just two of us and leave the real issues unsolved.
