### ISSUE TITLE
Carthage Charts

### ISSUE THREAD

**Issue by MonekyHou** [danielgindi/Charts#3234]
Why use Carthage introduced Charts run Ben crash error Can not find the class library image not found, added the link framework and run sript still been reported

**Comment by liuxuan30** [comment]
Take a look at how ChartsDemo refer the framework. And don't forget to check out Carthage's home page. Basically you don't embed the framework in your project. Linking just linked with the binary, but not guaranteed to be part of your ipa. You can refer dynamic library or static library as reference as well.
