### ISSUE TITLE
How to do  multiple  data on x axis?

### ISSUE THREAD

**Issue by chuejay** [danielgindi/Charts#3241]
Hi,
Thanks to watching my issue.
I have a problem on x axis of charts.I have already builded charts, but that is only one string on x axis.
I need multiple  data on x axis.How to do  multiple  data on x axis?

I provide part of code.
<img width="958" alt="2018-02-05 15 33 36" src="https://user-images.githubusercontent.com/32698179/35792450-8cdab702-0a90-11e8-925e-070f201ca9af.png">
<img width="721" alt="2018-02-05 15 34 25" src="https://user-images.githubusercontent.com/32698179/35792455-936174f8-0a90-11e8-8804-b4cf13a34ff6.png">
<img width="1081" alt="2018-02-05 15 37 12" src="https://user-images.githubusercontent.com/32698179/35792458-97f642fa-0a90-11e8-8a9b-cf71a0e0cc29.png">

Already builded chart
<img width="400" alt="2018-02-05 3 42 39" src="https://user-images.githubusercontent.com/32698179/35792212-41fd31d4-0a8f-11e8-87bc-7eee53ebab7d.png">

I would like this chart
![img_0641](https://user-images.githubusercontent.com/32698179/35792307-ced170c0-0a8f-11e8-90c0-d19b42815bf4.JPG)

Thank you for your consideration of this matter.
Sincerely,

**Comment by MananPatel95** [comment]
I believe you will need implement a custom XAxisRenderer. There are many issues similar to this, so search up the issues and you will find what you are looking for (my issue !3193 had a custom XAxisRenderer that might help you)

**Comment by liuxuan30** [comment]
actually, the x axis labels supports wrapping. but image is not supported.
