### ISSUE TITLE
Error in Library When added pod file

### ISSUE THREAD

**Issue by kavin06** [danielgindi/Charts#3242]
![screen shot 2018-02-05 at 3 43 17 pm](https://user-images.githubusercontent.com/31436737/35799450-bde0fb68-0a8b-11e8-9cbf-ef21e1ce94d7.png)

I tried alot but i cant fix this bug.please help me

**Comment by Boobesh** [comment]
Use Correct Version of Charts. That Charts Swift Version equal to your projects swift version. example you are using swift 4.0.x project then add Charts 3.0.5 (Swift Version is Swift 4.0.x).

**Comment by liuxuan30** [comment]
For anyone seeing this comment: As if you are just new to open source frameworks or just get started to use 3rd package manager, avoid using pods if you don't know how it works, and you don't know how to check what version suits you, as once you run pod install and things get messed up, you have to clean up the mess then.
Directly use the source code or carthage would makes it easier to do disaster recovery.

**Comment by kavin06** [comment]
Xcode 9.2 I am Using and added Charts 3.0.5 version but i am getting that same error. please check in that version
