### ISSUE TITLE
Got totally 50 errors after install CocoaPods ..! I am using Swift 4.0

### ISSUE THREAD

**Issue by naveen488** [danielgindi/Charts#3243]
![screen shot 2018-02-06 at 4 28 19 pm](https://user-images.githubusercontent.com/17079664/35856041-d036cc8c-0b5a-11e8-9d1d-62e8f84c993d.png)

**Comment by gvermesan** [comment]
Hi,

In your pod file just add:

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == "Charts"
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end

**Comment by liuxuan30** [comment]
use 3.0.5 charts. or point to master.
we are planning release 3.1 after I could swipe my notification inbox.
