### ISSUE TITLE
avoidFirstLastClippingEnabled not working and set last circleColor a different value

### ISSUE THREAD

**Issue by rankinit** [danielgindi/Charts#3244]
2 Questions:

1. Using a LineChartView and my xAxis values get clipped on the right and left sides.  I have enabled the following:

chartView.xAxis.avoidFirstLastClippingEnabled = true

yet the issue still persists.  Is this the correct way of making sure the the left and right side xAxis values do not get clipped? (See Image)

![helpcharts](https://user-images.githubusercontent.com/166776/35880303-2c3c09ce-0b43-11e8-83a0-0a3223e50d5f.png)

2.  For my rightmost xAxis value (in LineChartDataSet) will be a point in time in the future.  Therefore I would like to have a seperate color for the circleColor and the text of the xAxis value. How could I do this?  (at least change the circleColor will be sufficient)

Thanks!

**Comment by liuxuan30** [comment]
1. have you set axisMaximum? if not, please help debug and maybe a fix. It's in x axis renderer's drawLabels function.
2. either override the methods and feed your own color, or you change the source code.

**Comment by rankinit** [comment]
I checked and I'm not setting the "axisMaximum". For the chart in the image I have attached, I have 3 values 212.00, 208.00 & 205.0.  What would be an appropriate axisMaximum ?

Thanks for your reply!

**Comment by liuxuan30** [comment]
are you able to reproduce with ChartsDemo? I'm going to look into this and a few others in 3.1 release pool from tomorrow.

**Comment by liuxuan30** [comment]
I checked current implementation and your screenshot again, and I believe `avoidFirstLastClippingEnabled` works as expected, as your first and last x axis label is at the correct position:
![image](https://user-images.githubusercontent.com/4375169/36514911-edf3a20a-17b1-11e8-9bb2-632869ccf777.png)

I think the real problem for you is the chart view is on the screen edges, which would be cut off for sure. Look at ChartsDemo Line chart 1 and disable both y axis:
<img width="331" alt="image" src="https://user-images.githubusercontent.com/4375169/36515031-8109754c-17b2-11e8-813a-4be8e014c700.png">

I'm still feeling you have set axisMinimum/maximum.
