### ISSUE TITLE
x-axis label jumps when zoomed in and side scrolling.

### ISSUE THREAD

**Issue by Anachid** [danielgindi/Charts#3245]
The x-axis label jumps when i am zoomed in and scrolling sideways. Have a look at the gif attached.

![chartszoom](https://user-images.githubusercontent.com/1037341/35884915-060c187c-0b41-11e8-9712-1322950de81c.gif)

Any idea why this is happening?

**Comment by MananPatel95** [comment]
I had an issue similar to this, try this:

Remove:
LineChart.xAxis.avoidFirstLastClippingEnabled = true

Add in:
LineChart.xAxis.centerAxisLabelsEnabled = true

and add this to format the starting and ending x position of the graph if you want:
LineChart.xAxis.spaceMin = 0.5
LineChart.xAxis.spaceMax = 0.5

**Comment by Anachid** [comment]
Removing `LineChart.xAxis.avoidFirstLastClippingEnabled = true` fixes it. Other stuff is not needed for me.
