### ISSUE TITLE
How to realize the Line and the bar Chart in the same one Chart?

### ISSUE THREAD

**Issue by guoyutao** [danielgindi/Charts#3259]
How to realize the Line and the bar Chart in the same one Chart?(line value point in the bar center)
![wechatimg61](https://user-images.githubusercontent.com/11513385/36070205-3d88c252-0f31-11e8-8ea1-7725e7feb193.jpeg)

**Comment by liuxuan30** [comment]
that's called combined chart... have you look at the home page, or ChartsDemo?
