### ISSUE TITLE
setScatterShape applied to Legend also

### ISSUE THREAD

**Issue by BertPorter** [danielgindi/Charts#3261]
I'm just starting to use Charts. Working with hard-coded data as I create interface.

My code:
let line1 = ScatterChartDataSet(values: [ChartDataEntry(x: 208.97, y: 11017)], label: "Empty Wt")
line1.colors = [NSUIColor.blue] 
line1.setScatterShape(.circle)
line1.drawValuesEnabled = false

The correct shape appears inside the Chart but the default shape appears in the Legend.
Any way to have the Legend reflect this change also.

Thank you.

<img width="266" alt="setscattershape example" src="https://user-images.githubusercontent.com/19476837/36123290-0389cbfc-1001-11e8-88fd-3a01574d2a8b.png">

**Comment by liuxuan30** [comment]
look at ChartsDemo if you are a new comers. 
```swift
    /// The form/shape of the legend forms
    @objc open var form = Form.square
```
this should help you
