### ISSUE TITLE
is it support the ios 7???

### ISSUE THREAD

**Issue by helinyu** [danielgindi/Charts#3263]
Specs satisfying the `Charts (~> 3.0.4)` dependency were found, but they required a higher minimum deployment target.

**Comment by liuxuan30** [comment]
If iOS 7 supports Swift 4.0.3, then yes, and use source files rather than pod.
An advice to you: use iOS 9 at least

**Comment by jjatie** [comment]
@helinyu If you're being pressured by a client to support iOS 7, you can show them [this](https://developer.apple.com/support/app-store/). iOS 10/11 account for 93% of active devices.
