### ISSUE TITLE
Scatter Bar Char - Plots on axis (0,0) partially visible

### ISSUE THREAD

**Issue by praveenkumar1599** [danielgindi/Charts#3266]
Hi Guys
I am facing an issue in implementing the scatter graph. I am trying to plot graphs on axis (0,0)
But in the current implementation, The plots are only partially visible for me in the graph at (0,0)
Expected: Plots at (0,0) to be drawn over the line

Please let me know if there any parameters that i can use to make this change
Thanks in Advance
<img width="309" alt="screen shot 2018-02-13 at 12 23 41 pm" src="https://user-images.githubusercontent.com/16882544/36164509-8a3fbd14-10ba-11e8-963a-e47c237e5613.png">
<img width="645" alt="screen shot 2018-02-13 at 12 26 28 pm" src="https://user-images.githubusercontent.com/16882544/36164517-8c76c64a-10ba-11e8-9280-5f462d9fce8b.png">

**Comment by liuxuan30** [comment]
it's by design, everything will be clipped if it's beyond the axis.
if you don't like it, override `draw()` not to clip it, but do expect many side effects.
