### ISSUE TITLE
LineChartRenderer - drawHighlighted:context:indices:

### ISSUE THREAD

**Issue by klenovdima** [danielgindi/Charts#3267]
Hi, 
Thank you for porting the lib.

There is an error in LineChartRenderer class drawHighlighted:context:indices:

I got the error: 

> this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.

because of following lines of code:

```
let x = high.x // get the x-position
let y = high.y * Double(animator.phaseY)
```

Seems the lines should be following:

```
let x = e.x // get the x-position
let y = e.y * Double(animator.phaseY)
```

Please fix.

Thank you.

**Comment by liuxuan30** [comment]
you have to first figure out why your high contains NaN.
Please help debug how highlight object is generated, to see if it's your fault or ours; if latter, we will fix it.

**Comment by klenovdima** [comment]
Can't reopen issue.

**Comment by liuxuan30** [comment]
@klenovdima lineChartView.highlightValue(x: someIntValue, dataSetIndex: 0, callDelegate: false) calling this won't trigger NaN, unless your x is NaN, which is not allowed in the first place.
