### ISSUE TITLE
LineChart: How to fix space between point on  xAxis

### ISSUE THREAD

**Issue by Lapat1560700104** [danielgindi/Charts#3269]
<img width="415" alt="screen shot 2018-02-15 at 5 44 48 pm" src="https://user-images.githubusercontent.com/28327806/36252719-1fe8d4ae-1278-11e8-86c0-4327b85d854c.png">

I can't see the 3nd point in line graph how to fix it

**Comment by praveenkumar1599** [comment]
Reduce your axisMaximum to your maximum value to be displayed in graph
set your axis range to display based on your maximum
For eg:
If i need to plot the below points 
XAxis: [2,4,6,8,10]
YAxis: [2,4,6,8,10] 

Set you axisMaximum = 10
set your axisRange = 2

**Comment by Lapat1560700104** [comment]
how to fix width screen because right now my linechartview have over frame

**Comment by Lapat1560700104** [comment]
<img width="1198" alt="screen shot 2018-02-16 at 12 02 41 pm" src="https://user-images.githubusercontent.com/28327806/36294161-59024592-1311-11e8-90a8-82d686cd64b1.png">

**Comment by praveenkumar1599** [comment]
You need to reduce your Graph View size in the Storyboard/Xib
and try setting

   Xaxis.setLabelCount((No of columns required in XAxis) + 1, force: true)
For Eg:
  Xaxis.setLabelCount(5 + 1, force: true)

and set axisRange = valuedata.Max()! / (No of columns required in XAxis)

For Eg:
axisRange = valuedata.Max()! / 5

Note:
I have assumed that you will require total five columns in the xAxis

**Comment by liuxuan30** [comment]
This seems a UIView bound issue. I believe @praveenkumar1599 pointed it out.
And refer ChartsDemo.
