### ISSUE TITLE
How to custom axis' label in horizontal bar chart

### ISSUE THREAD

**Issue by dekphoenix** [danielgindi/Charts#3270]
here is my horizontal bar chart
![img_0283](https://user-images.githubusercontent.com/8720116/36297512-bda30e32-1325-11e8-9bd2-8db22225747e.PNG)
but I want custom to it
<img width="361" alt="screenshot at feb 16 14-30-12" src="https://user-images.githubusercontent.com/8720116/36297552-eae9f0c2-1325-11e8-9471-6c1f5a4d9bb7.png">

My horizontal bar chart doesn't zoom and scrollable
I try to use `chartView.xAxis.valueFormatter = IndexAxisValueFormatter(values: ["2551","2552","2553","2554","2555","2556","2557","2558","2559","2560"])`

but it only works at the first bar only

what should I do for customize like 2nd image

**Comment by liuxuan30** [comment]
just debug stringForValue to see anything wrong. 
for the interval, you have to override `computeAxisValues` to return every value for your bars to axis.entries. So every bar will have a x axis label.

@jjatie I'm feeling too many people asking how to set x label for every line dot/bar. We might want to support that in 4.0 release.

**Comment by annjawn** [comment]
I think that would be a splendid idea. Right now, it's a little unclear how to use the `IndexAxisValueFormatter` feature. Atleast, some documentation where it says that we must use the `IAxisValueFormatter` protocols `stringForValue()` method in order to compute the xAxis labels based on the data points and the labels array.

The one response that helped me solve the problem is - https://github.com/danielgindi/Charts/issues/1909#issuecomment-269771746

**Comment by liuxuan30** [comment]
apparently there are many things we could improve, but not without everyone's help. Usually it's just jjatie and me doing daily maintenance. You are welcome to add some documentation and maybe improve the sample formatters.

**Comment by annjawn** [comment]
@liuxuan30 absolutely. I just started using the lib. I will be more than happy to add some documentation, but I am not sure if there is a separate Github wiki or you guys hope to have [Github Pages](https://pages.github.com/), or is it just the md file you want to update.

**Comment by liuxuan30** [comment]
not sure haha. It used to refer its android portion for documentation
