### ISSUE TITLE
LineChart : How to show the grid in right axis

### ISSUE THREAD

**Issue by Lapat1560700104** [danielgindi/Charts#3271]
I want line chart look like this 
<img width="371" alt="screen shot 2018-02-16 at 4 08 46 pm" src="https://user-images.githubusercontent.com/28327806/36300402-ccd11846-1333-11e8-927c-2ea40f0e5dd0.png">

Now I can make this
<img width="409" alt="screen shot 2018-02-16 at 4 10 45 pm" src="https://user-images.githubusercontent.com/28327806/36300465-ff3eb324-1333-11e8-98e7-a81d09b67ff8.png">
I want  line chart view is width same width of View.

**Comment by liuxuan30** [comment]
just set axisMaximum = 2.
your have too few entries to draw, so the axis range is a bit strange.
