### ISSUE TITLE
How to add gap between chart and legend?

### ISSUE THREAD

**Issue by czater** [danielgindi/Charts#3274]
Hello!
I want to add gap between charts and legend but...I don't know how :s I tried xOffset, yOffset but it does nothing for me :/
I ended with something like this:
<img width="334" alt="screen shot 2018-02-19 at 18 57 08" src="https://user-images.githubusercontent.com/13368387/36391478-f65659c2-15a6-11e8-8213-752758bf178a.png">
How to set minimum offset or something like that? Thanks in advance :)

**Comment by liuxuan30** [comment]
does `extraBottomOffset` work for you?

**Comment by czater** [comment]
thanks you!
