### ISSUE TITLE
Question: LineChart variable line thickness?

### ISSUE THREAD

**Issue by mikeCalvir** [danielgindi/Charts#3285]
Apologies for creating an issue for a question (I'll repost if I should ask this elsewhere?), but I am wondering if there is a simple way to achieve variable line thicknesses?

I typically only want two actual thicknesses applied, so a section of say thickness 4 and sections of thickness 8, and switching between them multiple times through the series.

Thanks for any thoughts/advice on how to go about this :)

**Comment by liuxuan30** [comment]
Everyone is encouraged to ask on SO now. For your question, it's more like a customization for your needs. So you can override the line chart renderer and add an array of line width.

**Comment by mikeCalvir** [comment]
That should give me enough to go on, thanks Xuan, appreciated!
