### ISSUE TITLE
color in BalloonMarker is never used

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#3287]
got a warning saying `if let color = color` is never used in BalloonMarker.
I take a look at it and found `color` is never used as well. 
I'm not sure why we have `if let color = color` and did nothing. Any idea what's the color is supposed to do? @danielgindi @jjatie

**Comment by thierryH91200** [comment]
it's the background color

`context.fillPath()`

**Comment by liuxuan30** [comment]
hi @thierryH91200 thanks, may I ask where did you get `context.setFillColor(color.cgColor)`, you write it yourself, or it used to exist in the library, and removed by mistake?

**Comment by thierryH91200** [comment]
https://github.com/danielgindi/Charts/blob/master/ChartsDemo/Swift/Components/BalloonMarker.swift

I do not know if we're talking about the same thing

**Comment by liuxuan30** [comment]
@thierryH91200 you are refering swift demo's. seems we have a big diff between Objc demo's balloon marker and Swift demo's.
Seems we should port the swift one into objc demo.
