### ISSUE TITLE
Better way to manage Stacked Bar Chart Value labels?

### ISSUE THREAD

**Issue by annjawn** [danielgindi/Charts#3295]
First of all, thanks for this great library. I am still learning the nuances of using this, so please bear with me. I have successfully rendered a Stacked Barchart using data, but when I am pushing some production data into my tests, I am noticing that there are situations where the barcharts value labels are overlapping.

![image](https://user-images.githubusercontent.com/26977294/36633976-83f6d924-1952-11e8-9bec-8d00ade109be.png)

I can display the values label in the bottom by setting `chartView.drawValueAboveBarEnabled` to `false`, but the net outcome is the same i.e. the labels still overlap. The only other solution for this for me is to - `data.setDrawValues(false)` but it makes me sad that I can't show these values on the chart itself.

Is there a way to define the position of the values based on individual stack? for example for the top stack the value should appear above the bar, and for the bottom stack the value should appear below the bar? Or is there already some other way to do it correctly that I am missing.

**Comment by liuxuan30** [comment]
not yet. But you are welcome to file a PR to support this. The label overlapping is a known issue, as the top stack is very short, the space is not enough then.

**Comment by mackyfamous** [comment]
any updates in this issue?
