### ISSUE TITLE
Bug in ZoomViewJob?

### ISSUE THREAD

**Issue by wuxudong** [danielgindi/Charts#3299]
In  [an react native wrapper project](https://github.com/wuxudong/react-native-charts-wrapper) , It use Charts as underlying lib. 

After updating Charts from 3.0.3 to 3.0.5, the zoom is not behaving as expected.
  
	barLineChart.zoom(scaleX: CGFloat(json["scaleX"].floatValue),
	                    scaleY: CGFloat(json["scaleY"].floatValue),
	                    xValue: json["xValue"].doubleValue,
	                    yValue: json["yValue"].doubleValue,
	                    axis: axisDependency)

In Charts 3.0.5, it doesn't center at (xValue, yValue), but in Charts 3.0.3, it works well.

After dig a little further, I found in commit #3041 ,  the code in ZoomViewJob changed from 

    var pt = CGPoint(
        x: CGFloat(xValue - xValsInView / 2.0),
        y: CGFloat(yValue + yValsInView / 2.0)
    )

to 

     var pt = CGPoint(
		x: CGFloat(xValue - xValsInView) / 2.0,
		y: CGFloat(yValue + yValsInView) / 2.0
    )

notice the position of brackets, the computed pt is totally different.

is it an unintentional wrong typing ? please fix it.

**Comment by liuxuan30** [comment]
will this cause this big difference? `CGFloat(xValue - xValsInView / 2.0)` and `CGFloat(xValue - xValsInView) / 2.0` are merely the same I think.

**Comment by wuxudong** [comment]
/(divide) is prior to -(minus).

eg. xValue = 20, xValsInView = 20

CGFloat(xValue - xValsInView / 2.0) => CGFloat (20-20/2.0) => CGFloat(10)

CGFloat(xValue - xValsInView) / 2.0 = CGFloat(20-20) / 2.0 = CGFloat(0) / 2.0 = CGFloat(0)

**Comment by liuxuan30** [comment]
oops, good catch. This is a mistake. will be taken care of in 3.1
