### ISSUE TITLE
Horizontal Bar Chart legend issue

### ISSUE THREAD

**Issue by mallow76** [danielgindi/Charts#3301]
Have just updated to v3.0.5 (from 3.0.3) and one of my charts now has a slight overlap with the legend. Is this a known issue (I can see similar though different issues have been raised) and is there a setting that I could use to apply some padding/margin?

![img_1672](https://user-images.githubusercontent.com/16882814/36696365-e5239b34-1b3b-11e8-8284-3b91184bf3f4.png)

**Comment by liuxuan30** [comment]
>Have just updated to v3.0.5 (from 3.0.3)

are you saying it's a regression? Can you confirm and maybe help?

**Comment by mallow76** [comment]
> are you saying it's a regression? 

yes - worked as expected in previous version. i found a screenshot from earlier version. Happy to help if i can. Is there a quick fix I can apply in meantime?

![2018-02-27_09-56-30](https://user-images.githubusercontent.com/16882814/36722314-1a52dba8-1ba5-11e8-97da-e0bfaeeb256b.png)

**Comment by mallow76** [comment]
> What is the value of your horizontal bar chart?

What do you mean?

**Comment by mallow76** [comment]
@liuxuan30 is there something that I can do to help / test this?

**Comment by liuxuan30** [comment]
go back to old versions and check if the issue is gone. as you said 
> Have just updated to v3.0.5 (from 3.0.3)

**Comment by mallow76** [comment]
@liuxuan30 yes - reverting to 3.0.3 fixes the issue.

**Comment by thierryH91200** [comment]
see #3351

**Comment by liuxuan30** [comment]
you could help debug and maybe fix it. I just release 3.1, but seems not fixing this issue, as I didn't know what's the regression

**Comment by jjatie** [comment]
@mallow76 Does the issue still exist in 3.1?

**Comment by mikeiasNS** [comment]
as a temporary fix i just used `chart.extraBottomOffset`

**Comment by mikemike396** [comment]
Any update on this?

**Comment by SvenMuc** [comment]
I have the same issue in my actual app with Charts v3.2.1.
The fix is quite easy. I can create a pull request at the weekend which fixes the issue.
