### ISSUE TITLE
Values on X axis issue

### ISSUE THREAD

**Issue by milakovicmilosOviva** [danielgindi/Charts#3304]
I use ScatterChart. On the x axis labels should be hours (00:00, 06:00, 12:00, 18:00). But, If I put minimum = 0 and maximum = 1440 (minutes in day) and  and label count to 5 I get graph like this: 

![graph](https://user-images.githubusercontent.com/31532895/36778445-fd8db7cc-1c6c-11e8-98d8-d28e4d1026d2.jpg)

If I set labelCount to 4, labels on xAxis are: 00:00, 06:40 (400), 13:20 (800), 20:00 (1200). 
If labelCount = 3 axis are 00:00, 08:20 (500), 16:40 (1000) 

This is my setup:
`
        vwChart.xAxis.axisMinimum = 0
        vwChart.xAxis.axisMaximum = 1440
        vwChart.setVisibleXRangeMaximum(1440)
       vwChart.setVisibleXRangeMinimum(1440)
        vwChart.xAxis.labelCount = 4  // 5, 6, 3, 2
`

Is there a way to specify interval between labels, so I can display each 6h?

**Comment by liuxuan30** [comment]
check `computeAxisValues()`, where it generate the x axis labels. You can override it with your own

**Comment by JCMcLovin** [comment]
@liuxuan30 - does the demo project have an example that overrides `computeAxisValues()`? I can't seem to find one that does.

**Comment by liuxuan30** [comment]
no, it's default one. The logic is simple, just do math or none

**Comment by crystalztl** [comment]
So when we need to manually override the computeAxisValues() for the XAxisRenderer. Here is an example:
`
class NonUniformXAxisRenderer: XAxisRenderer {
    override func computeAxisValues(min: Double, max: Double) {
        super.computeAxisValues(min: min, max: max)
 
        guard let axis = self.axis else { return }
         
        let labelCount = axis.labelCount
        let interval = 86400000.0
         
        // Ensure stops contains at least n elements.
        axis.entries.removeAll(keepingCapacity: true)
        axis.entries.reserveCapacity(labelCount)
         
        var v = min + 26423301
         
        for _ in 0 ..< labelCount - 2
        {
            axis.entries.append(v)
            v += interval
        }
         
    }
}`

`let viewPortHandler = ViewPortHandler(width: bounds.size.width, height: bounds.size.height)
let transformer = Transformer(viewPortHandler: viewPortHandler)
transformer.prepareMatrixValuePx(chartXMin: xAxis.axisMinimum, deltaX: (CGFloat(xAxis.axisMaximum - xAxis.axisMinimum)), deltaY: CGFloat(leftAxis.axisMaximum - leftAxis.axisMinimum), chartYMin: leftAxis.axisMinimum)
chartView.xAxisRenderer = NonUniformXAxisRenderer(viewPortHandler: viewPortHandler, xAxis: chartView.xAxis, transformer: transformer)`

Take note you need to prepareMatrixValuePx for your own transformer instance.

ChartXAxis Value Not Displayed
So first check xAxis.entries in computeAxisValues(), and then drawLabels()
You can try debug xAxis.drawLabels() at if viewPortHandler.isInBoundsX(position.x) to see if it meets the condition.
