### ISSUE TITLE
Select circles on line chart

### ISSUE THREAD

**Issue by delox** [danielgindi/Charts#3307]
Is there a way to render only some circles on the line chart, and not for all point?

i.e. I want to render only 2 circles in my chart with 500 points

**Comment by jeetdholakia** [comment]
That is exactly the issue I am trying to solve, does anyone have any pointers on this?

**Comment by liuxuan30** [comment]
the only way is you override the method to so. We cannot satisfy all custom demand. you are welcome to send a pull request  afterward.
