### ISSUE TITLE
Can't show Label text in XAxis

### ISSUE THREAD

**Issue by AlanMoMo** [danielgindi/Charts#3308]
In IndexAxisValueFormatter.swift line 56.

```swift
 guard values.indices.contains(index), index != Int(value) else { return "" }
```

there always return "".

when user "IndexAxisValueFormatter(values: values)" to set xAixs.valueFormatter.

**Comment by AlanMoMo** [comment]
I think there should be " `guard values.indices.contains(index), index == Int(value) else { return "" }` "

**Comment by liuxuan30** [comment]
It's fixed in master.
