### ISSUE TITLE
Horizontal Bar Chart xAxis formatted label textColor

### ISSUE THREAD

**Issue by ChrisHPollak** [danielgindi/Charts#3317]
Hi,

Is there any way to set specific color for a formatted xAxis label? 

xAxis.labelTextColor sets color for all labels, but i need to change the color for one specific label. For example if bar is highlighted.

![img_2557 2](https://user-images.githubusercontent.com/22461860/36948815-1bd1c3c2-1fbf-11e8-990a-5b87a6b607b7.jpg)

Thanks

**Comment by liuxuan30** [comment]
you have to override the methods to do so then. We cannot satisfy all customizations
