### ISSUE TITLE
Unable to get horizontal scrolling in bar chart

### ISSUE THREAD

**Issue by sneha255** [danielgindi/Charts#3319]
I am creating bar chart with huge data (approx 3000) when I am double tapping the chart , shows only some data not all so for this I need to scroll bar chart . 

Can you suggest me how to achieve this.

Thanks for your support.

**Comment by liuxuan30** [comment]
when you zoomed in, just scroll.

**Comment by pateljinal1844** [comment]
I just found out, ordering matters for this to work. You need to call setVisibleXRangeMaximum after chartView.data = data or notifyDataSetChanged
