### ISSUE TITLE
HorizontalBarChartView  display partial data

### ISSUE THREAD

**Issue by littleObsession** [danielgindi/Charts#3320]
when i use HorizontalBarChartView, i need display partial data, scroll to display other data. But i set setVisibleXRangeMaximum or setVisibleXRangeWithMinXRange:<#(double)#> maxXRange:<#(double)#> still doesn't work.but i can pinch zoom it to scroll. can you help me how to solve it? thank.

**Comment by liuxuan30** [comment]
can you explain what does not work? Myabe a video or image

**Comment by ninjazoete** [comment]
@liuxuan30 
I think I need similar functionality. I used visibleRange to display X bars with data I have and rest of the bars are greyed out non value bars which can user scroll to. I want user to interactively scroll left and right to first show grey bars with no data and instantly show a loading indicator to load new data with animation.

Problem is I cannot find any handler for content offset anywhere. Is there a way to get to the inner scroll view?

**Comment by Leo007Lee** [comment]
you should set dataSource for chartview, then set setVisibleXRangeMaximum or setVisibleXRangeWithMinXRange. It works @littleObsession
