### ISSUE TITLE
Two Horizontal grid lines always appear above Base Axis line

### ISSUE THREAD

**Issue by jaggudada1992** [danielgindi/Charts#3322]
I have made drawGridLinesEnabled = false for xAxis, leftAxis, rightAxis in my project but still two grid lines above axis line always appear. How to fix the issue? I only want to display xAxis & yAxis axis lines & not to show any grid lines elsewhere.

**Comment by liuxuan30** [comment]
post an image, have no idea what you said.

**Comment by jaggudada1992** [comment]
![screen shot 2018-03-09 at 9 52 06 am](https://user-images.githubusercontent.com/12625829/37190501-172462c0-2380-11e8-9998-61b0a9c0f255.png)

**Comment by liuxuan30** [comment]
this seems a ChartLimitLine to me.
