### ISSUE TITLE
Show the last x axis label on bar chart 

### ISSUE THREAD

**Issue by HsiaoAi** [danielgindi/Charts#3324]
Hi I would like to show the last x axis label  on bar chart 
as this issue https://github.com/danielgindi/Charts/issues/2006 but it didnt work for me 
![img_5932](https://user-images.githubusercontent.com/8043896/37192084-5c75e182-239e-11e8-80f5-dd2fc1624191.PNG)
how could I modify the chart as the upper one? 
Thanks in advance!

**Comment by kvnbra** [comment]
You can try `barChartView.xAxis.avoidFirstLastClippingEnabled = true` and `barChartView.xAxis.forceLabelsEnabled = true` that's made the trick for me.

However, you lose dynamic label count when zooming (and so lose precision). 
To fix that, I added a delegate to the chart view with the `chartScaled` method like this :
```
extension ChartViewController: ChartViewDelegate {
    func chartScaled(_ chartView: ChartViewBase, scaleX: CGFloat, scaleY: CGFloat) {
            // Only enable fixed label count when fully zoomed out
            chartView.xAxis.forceLabelsEnabled = self.barChartView.isFullyZoomedOut
    }
}
```
