### ISSUE TITLE
I want to make Multiple Bar, and write it in the way of Demo. Why the effect is StackedBar

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#3325]
The code I wrote is not correct, and I copied the Multiple Bar code in the Demo. It is also the effect of Stacked Bar. My version is 3.0.1. Is there a bug in this version?

I Pod 3.0.4 but I got an error.

- `Charts (~> 3.0.4)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Charts (~> 3.0.4)`.

**Comment by liuxuan30** [comment]
it's 3.1 now. Check it out

**Comment by shenyufei** [comment]
My swift Version is 3.2. I can't install 3.1.
Do I need upgrade?
Is there a compatible swift 3.0 version?
