### ISSUE TITLE
ChartsDemo-Swift crashes

### ISSUE THREAD

**Issue by valeriyvan** [danielgindi/Charts#3327]
ChartsDemo-Swift crashes when in Line Chart in option choose Toggle Data option and then choose, Toggle Cubic option.

**Comment by liuxuan30** [comment]
That's because you niled out the chartData and then try to unwrap it:
```swift
        case .toggleCubic:
            for set in chartView.data!.dataSets as! [LineChartDataSet] {
                set.mode = (set.mode == .cubicBezier) ? .linear : .cubicBezier
            }
```
@jjatie this is no big deal. But I checked many of the view controllers uses `chartView.data!.dataSets`,  do you have any smart fix for this? Or we have to fix it one by one

**Comment by jjatie** [comment]
Looks like we'll need to guard each `handleOption` implementation.

**Comment by jjatie** [comment]
@liuxuan30 @valeriyvan I've thought about this some more. It's easy to imagine a case where a user wants to temporarily hide a given `ChartData`. It seems to me that `ChartData` should have an `isEnabled` property or something. If `isEnabled == false` then it's data sets are not drawn.z

Once this implemented, the demos should not be setting the data to nil, but simply toggling `chartData.isEnabled`

**Comment by valeriyvan** [comment]
Does it sound like data should’t be optional anymore?

**Comment by jjatie** [comment]
That's a different discussion, but I've been thinking yes.

**Comment by jjatie** [comment]
This seems like a corner case and optionality of many properties are changing in 4.0. As we have limited resources to keep making changes for non-critical areas, I am closing this. After 4.0 is released, we will have more time to reevaluate issues like this.
