### ISSUE TITLE
Code signing is required for product type 'Application' in SDK 'iOS 11.2'

### ISSUE THREAD

**Issue by vrobles2008** [danielgindi/Charts#3333]
I am trying to run the demo, but I keep getting an error "Code signing is required for product type 'Application' in SDK 'iOS 11.2"

This is my first time every building an app in Xcode so I am new to the whole code signing thing. Thanks in advance.

**Comment by jjatie** [comment]
StackOverflow is the place to ask programming support questions. There are likely already numerous answer to this.
