### ISSUE TITLE
Line chart with solid and dashed line

### ISSUE THREAD

**Issue by charlesburks** [danielgindi/Charts#3334]
Is there a way to draw a solid line that also has a dashed segment?
Here is an [example.](http://www.andypope.info/ngs/ng45.gif)

**Comment by jjatie** [comment]
The only way to currently achieve this is to use two datasets (one for the solid line, one for the dashed line)

**Comment by Artfire** [comment]
I think that the easiest way is to create two separate LineChart. You just need to separate all X and Y values for solid and dashed arrays.
1) 
`let lineChartDataSet1 = LineChartDataSet(...)
lineChartDataSet1.setColor(.blue)`
2)
`let lineChartDataSet2 = LineChartDataSet(...)
lineChartDataSet2.lineDashLengths = [5, 5]
lineChartDataSet2.setColor(.blue)`

`let lineChartData =  LineChartData(dataSets: [lineChartDataSet1, lineChartDataSet2])`
