### ISSUE TITLE
When the number of numeric numbers on the Y axis does not agree, the right of the multiple charts will not be aligned.

### ISSUE THREAD

**Issue by Leo007Lee** [danielgindi/Charts#3347]
Thanks for your job. It is a great library.

I added two chartView in a view , hoping they can synchronize when they slide or zoom.
With the same number of data sources, if the number of digits displayed on their Y axis is not consistent, the right side of the two charts will not be aligned.
￼
![1521200174003](https://user-images.githubusercontent.com/11954248/37518755-740a007c-2951-11e8-995d-7a75a4780c23.jpg)

I'm using the latest Swift Library

What should I do to solve this problem.
 Thanks again.

**Comment by liuxuan30** [comment]
I don't understand the question nor the image.
