### ISSUE TITLE
Remove value labels padding

### ISSUE THREAD

**Issue by jonohayon** [danielgindi/Charts#3350]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
I tried to hide the value labels using the `dataSet.setDrawValues` method.

## What did you expect to happen?
I expected that the values will be hidden and the line chart's coordinates will be aligned to the grid.

## What happened instead?
The coordinates are a bit off, as it looks like the value labels had some padding around them.

## Charts Environment

**Charts version/Branch/Commit Number: 3.0.4**
**Xcode version: 9.2**
**Swift version:4**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: 10.13.1**

## Demo Project
https://github.com/Team3316/kassandra-ios

**Comment by jonohayon** [comment]
I currently solved the problem by adding a variable offset to the values, but this is a bad practice.

**Comment by frc3316** [comment]
+1, had the same problem.

**Comment by Virtue86** [comment]
offset is ok

**Comment by jonohayon** [comment]
Nevermind, this was a problem due to forcing a certain number of labels in the left y-axis.
