### ISSUE TITLE
Layout issue with chart legend 

### ISSUE THREAD

**Issue by floriangbh** [danielgindi/Charts#3359]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Update to v3.1. 

## What did you expect to happen?

No regression :) 

## What happened instead?

Before v3.1 
<img width="378" alt="before 3 1" src="https://user-images.githubusercontent.com/14054997/37775539-81264ef0-2de3-11e8-9be1-771c4f7cc1e1.png">
After v3.1
<img width="359" alt="after 3 1" src="https://user-images.githubusercontent.com/14054997/37775581-98c8b99e-2de3-11e8-9687-d4525141f197.png">

Issue happen with chart legend. 

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1 with Carthage 
**Xcode version:** 9.2
**Swift version:** 4.0.3
**Platform(s) running Charts:** iPhone 
**macOS version running Xcode:** 10.13.3

**Comment by geberl** [comment]
Can confirm. Updated **from 3.0.5 to 3.1.1** and see something similar.

It seems to be more an issue of _the chart being taller now_ than _the legend being positioned too far up_. Can't tell from @floriangbh  screenshots.

![charts_legend_issue](https://user-images.githubusercontent.com/7255425/38352385-4c94e7c0-38b3-11e8-985e-d080a3a7225b.png)

For the meantime I found that adding an `extraBottomOffset` of `CGFloat(32)` to the chart leads to the previous result.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1 with CocoaPods
**XCode version:** 9.3
**Swift version:** 4.1
**Plattform(s) running Charts:** iPhone, iPad
**macOS version running Xcode:** 10.13.4

**Comment by floriangbh** [comment]
Fixed with `setExtraOffsets`.
