### ISSUE TITLE
inconsistent include of UIKit vs AppKit

### ISSUE THREAD

**Issue by solas** [danielgindi/Charts#3362]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

It appears this project grabs many UI object definitions (e.g. NSTextAlignment) through Charts.h, yet includes for iOS UIKit separately in many files:

#if !os(OSX)
    import UIKit
#endif 

Either Charts.h should include all, else the above swift import should be changed to the following, and perhaps imported in a separate included swift module to avoid duplication:

#if !os(OSX)
    import UIKit
#else
    import AppKit
#endif

## Charts Environment

**Charts version/Branch/Commit Number:**
3.1
**Xcode version:**
9.2
**Swift version:**
4.0
**Platform(s) running Charts:**
macOS
**macOS version running Xcode:**
10.13.3

**Comment by liuxuan30** [comment]
I'm not clear what's your issue. Have checked Charts-OSX demo? And, better to provide a PR to demonstrate. You are the FIRST one reporting this.

**Comment by jjatie** [comment]
I'm not sure what the issue is either. Most, if not all, of the 
```
#if !os(OSX)
import UIKit
#endif
```
are leftover from older versions of the library and can be removed. They don't impact anything as the `UIKit` and `AppKit` imports are done in `Platform.swift`
