### ISSUE TITLE
Compile error on newest ChartsDemo-iOS project

### ISSUE THREAD

**Issue by JCMcLovin** [danielgindi/Charts#3373]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I downloaded the latest version of the library (4.1) and attempted to run the ChartsDemo-iOS-Swift project.

## What did you expect to happen?

I expected it to build and run.

## What happened instead?

I got a compile error. In DataApproximator+N.swift, Xcode complains about the `func reduceWithDouglasPeukerN(_ points: [CGPoint], resultCount: Int) -> [CGPoint]` saying:

>> Value of type 'EnumeratedSequence<[CGPoint]>' has no member 'compactMap'

## Charts Environment

**Charts version/Branch/Commit Number:** 4.1/Master/#3370
**Xcode version:** 9.2
**Swift version:** 4.0.3
**Platform(s) running Charts:** iOS 11.2
**macOS version running Xcode:** High Sierra 10.13.3

## Demo Project

https://github.com/danielgindi/Charts/tree/master/ChartsDemo-iOS

**Comment by thierryH91200** [comment]
see #3372 
try with 
Xcode version : 9.3
Swift version: 4.1

**Comment by liuxuan30** [comment]
it's done.
>      - 3.1.1 (2018-04-03 01:22:23 UTC)

**Comment by wuxudong** [comment]
Sure? Still get this error in 3.1.1

**Comment by suhaspathak** [comment]
It's not support Xcode 9.2. need to update Xcode version.
