### ISSUE TITLE
Charts Pod not working with Xcode 9.3 (Swift 4.1)

### ISSUE THREAD

**Issue by jamiedaniel** [danielgindi/Charts#3376]
## What did you do?

ℹ Updated to the new version of Xcode which is Xcode 9.3. Added Charts to the Podfile, installed pods and attempted to build the project.

## What did you expect to happen?

ℹ I expected to build the project successfully.

## What happened instead?

ℹ When the project is built an error is displayed:  Charts compiled with older version of Swift language (4.0) than previous files (unknown ABI version 0x06)

## Charts Environment

**Charts version/Branch/Commit Number: 3.1.0**
**Cocoapods version: 1.5**
**Xcode version: 9.3**
**Swift version: 4.1**
**Platform(s) running Charts: iOS 11.3**

## Demo Project

ℹ Any new project in Xcode behaves like this.

**Comment by jamiedaniel** [comment]
Update the CocoaPod spec

**Comment by jjatie** [comment]
Update

**Comment by jjatie** [comment]
Update pod to 3.1.1 for Swift 4.1 compatibility.
