### ISSUE TITLE
Line chart fill color goes above/below zeroline

### ISSUE THREAD

**Issue by steve509** [danielgindi/Charts#3377]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
I've set the `fillColor` property of an instance of `LineChartDataSet`.

## What did you expect to happen?
I expected the line chart to fill with the specified color.

## What happened instead?
The line chart fills with the specific color but it goes above/below the zero line. 

See below:
![fill-issue-caption](https://user-images.githubusercontent.com/6761111/38212527-04dafccc-368c-11e8-8966-76657b5bfd2d.png)

## Charts Environment

**Charts version/Branch/Commit Number:** Charts, 3.0.5
**Xcode version:** Xcode 9.2
**Swift version:** Swift 4
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** macOS High Seirra 10.13.3

**Comment by steve509** [comment]
Found a solution to this:

```
class LineChartFillFormatter: IFillFormatter {
    func getFillLinePosition(dataSet: ILineChartDataSet, dataProvider: LineChartDataProvider) -> CGFloat {
        return 0
    }
}
```


```
dataSet.fillFormatter = LineChartFillFormatter()
```

**Comment by lieudd** [comment]
This save my day when I try always to fill color below the line. Thank!
