### ISSUE TITLE
Grouped bar chart shows up as stacked bar chart after migration.

### ISSUE THREAD

**Issue by yigitserin** [danielgindi/Charts#3380]
Hey there, I just recently migrated my app from Swift 2.3 to 4.1, and some api changes broke how my bar chart worked. Basically it shows up as a stacked bar chart instead of grouped bar chart and x axis labels are not gone.

Details and code is here:
https://stackoverflow.com/questions/49653956/how-to-create-a-grouped-bar-chart-in-swift

**Comment by liuxuan30** [comment]
well you have to look at chart demos and see #1474
