### ISSUE TITLE
missing property in latest LineChartView 

### ISSUE THREAD

**Issue by lee727n** [danielgindi/Charts#3383]
when  i update for latest charts suppor swift 4.1，this command is fault    //chartview.legend.position = 9 ; then i check the legend property can't find the property position，do you delete this property?i want to know how can i  change the legend positon .

**Comment by jjatie** [comment]
This property was deprecated for quite some time and has been removed in 3.1.
     `/// This property is deprecated - Use `horizontalAlignment`, `verticalAlignment`, `orientation`, `drawInside`, `direction`.`
