### ISSUE TITLE
Unable to compile swift 3.2 code from xcode  9.3. I am using 3.1.1 version of charts.

### ISSUE THREAD

**Issue by prati691** [danielgindi/Charts#3387]
![screen shot 2018-04-09 at 12 38 30 pm](https://user-images.githubusercontent.com/37064297/38485325-f347e9fa-3bf6-11e8-86d1-54908497745c.png)

**Comment by anjusr** [comment]
Even I have encounter the same issue.. Got any solution for this?

**Comment by prati691** [comment]
No, not yet :(

**Comment by jjatie** [comment]
As per the [README](https://github.com/danielgindi/Charts/blob/master/README.md), Charts 3.1.1 requires Xcode 9.3 / Swift 4.1.
