### ISSUE TITLE
How to install charts Framework using Xcode 9.1 

### ISSUE THREAD

**Issue by DivyaSaraswati** [danielgindi/Charts#3388]
By manual installation it is giving error "**No Such Modules Charts**" and through pods it is not compilable. through pod version Charts (3.1.0) is installed.

Error:
BarLineChartViewBase.swift:70:76: Cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available

BarLineChartViewBase.swift:81:72: Cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available

BarChartRenderer.swift:611:121: Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

**Comment by dgaedcke** [comment]
I'm getting same error.  What is the solution?

**Comment by liuxuan30** [comment]
```
      - 3.1.0 (2018-03-22 03:10:15 UTC)
      - 3.1.1 (2018-04-03 01:22:23 UTC)
```
