### ISSUE TITLE
Remove noDataText

### ISSUE THREAD

**Issue by black-lotus** [danielgindi/Charts#3396]
* [yes] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ set "noDataText" to empty String, to remove "No chart data available."

## What did you expect to happen?

ℹ When my chart data is empty "No chart data available." should be gone

## What happened instead?

ℹ "No chart data available." still displayed even my chart data is empty or nil 

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1.1
**Xcode version:** 9.3
**Swift version:** 4.1
**Platform(s) running Charts:** iOS
**macOS version running Xcode:**

## Demo Project

```
func initChart() {
        // prepare chart data container
        let data = LineChartData()

        // configure linechart
        self.chartView.noDataText = "" // this should be remove "No chart data available."
        self.chartView.scaleYEnabled = false
        self.chartView.scaleXEnabled = false
        self.chartView.pinchZoomEnabled = false
        self.chartView.doubleTapToZoomEnabled = false
        self.chartView.dragEnabled = false
        self.chartView.legend.enabled = false
        self.chartView.isUserInteractionEnabled = false
        self.chartView.fitScreen()

        // add data set
        data.addDataSet(EMPTY_DATA)

       // set chart view data
       self.chartView.data = data
}
```

Any help would be appreciated,
Thank you

**Comment by black-lotus** [comment]
Fixed, it was my fault.

I should call initChart() on awakeFromNib() instead of after asynchronous call

**Comment by m-montoya** [comment]
This lead me in the right direction. For others where they add it as a class on a view from the interface and it is an outlet, the value need to be set in the viewDidLoad.

**Comment by bazilhassan** [comment]
i'm Using BarChart and setting noDataText value empty but value is not changing? Can you please tell me how to fix this ?
BarChartView.noDataText = ""
