### ISSUE TITLE
Value of type 'EnumeratedSequence<[CGPoint]>' has no member 'compactMap'

### ISSUE THREAD

**Issue by saldous** [danielgindi/Charts#3402]
## What did you do?
Updated charts to v3.1.1 via pods. Build and run project and the build fails with error.

## What did you expect to happen?
No error.

## What happened instead?
Error in file 'DataApproximator+N.swift' on line 115:

`Value of type 'EnumeratedSequence<[CGPoint]>' has no member 'compactMap'`

## Charts Environment
v3.1.1
Swift 4.0
Xcode 9.2

**Comment by thierryH91200** [comment]
look for the mistake

**readme**

- Xcode 9. 3 / Swift 4.1
-  iOS >= 8.0 (Use as an Embedded Framework)
- tvOS >= 9.0
- macOS > = 10.11

**Comment by saldous** [comment]
oh, whoops! Sorry.

**Comment by leamerluck** [comment]
@saldous I saw this as well. When I updated to Xcode 9.3 Swift 4.1, this error was resolved.
