### ISSUE TITLE
compactMap build error

### ISSUE THREAD

**Issue by GoodLuckBobe** [danielgindi/Charts#3405]
let reducedEntries = points.enumerated().compactMap { (index: Int, point: CGPoint) -> CGPoint? in
            return keep[index] ? point : nil

Please add a swift judgment
#if swift(>=4.1)

#else

#endif

**Comment by liuxuan30** [comment]
I'm trying to understand this. You still use swift <4.1, but using latest chart code? 

If so, you shouldn't, as we only support latest swift in master. it will create overhead if we have to support different swift versions, and there is no reason to do this.

or you can pick up the source code into your projects, so you have full control.
