### ISSUE TITLE
BarLineChartViewBase doubleTapGestureRecognized 

### ISSUE THREAD

**Issue by 757388559** [danielgindi/Charts#3417]
This is source code for charts:
    @objc private func doubleTapGestureRecognized(_ recognizer: NSUITapGestureRecognizer)
    {
        if _data === nil
        {
            return
        }
        
        if recognizer.state == NSUIGestureRecognizerState.ended
        {
            if _data !== nil && _doubleTapToZoomEnabled && (data?.entryCount ?? 0) > 0
            {
                var location = recognizer.location(in: self)
                location.x = location.x - _viewPortHandler.offsetLeft
                
                if isTouchInverted()
                {
                    location.y = -(location.y - _viewPortHandler.offsetTop)
                }
                else
                {
                    location.y = -(self.bounds.size.height - location.y - _viewPortHandler.offsetBottom)
                }
                
                self.zoom(scaleX: isScaleXEnabled ? 1.4 : 1.0, scaleY: isScaleYEnabled ? 1.4 : 1.0, x: location.x, y: location.y)
            }
        }
    }

we can know the scale factor is fixed, we can't set it，And the doubleTapGestureRecognized don't
use scale delegate。
The question:
1.How to set the scale factor?
2.hope the scale delegate is used

**Comment by liuxuan30** [comment]
it's in ChartTransformer and ViewPortHanlder.
