### ISSUE TITLE
can we animate SelectionShift when selecting a segment of pie chart?

### ISSUE THREAD

**Issue by robertTyrell** [danielgindi/Charts#3420]
## What did you do?

When selecting a section of a pie chart I would like the view to grow.  

I have tried 
`    func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
        chartView.animate(xAxisDuration: 1)
// and also  chartView.animate(yAxisDuration: 1)

    }`

## What did you expect to happen?

I was hoping when I selected a section of pie chart it would grow and shrink.

## What happened instead?

The pie chart animation was redrawing itself around the centre of the chart.

## Charts Environment

**Charts version/Branch/Commit Number:3.1.1
**Xcode version:9.3
**Swift version:4.1
**Platform(s) running Charts:**
**macOS version running Xcode:10.13.4

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/pull/3290
