### ISSUE TITLE
Error: cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available

### ISSUE THREAD

**Issue by castus** [danielgindi/Charts#3434]
After update I have two error during compiling. Please see info below.

* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
Update pod to Charts 3.1.1 (was 3.0.3)

## What did you expect to happen?
It will compile as before ;)

## What happened instead?
Two errors during compilation:
1. Error:(75, 76) cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available in `BarLineChartViewBase.swift`
2. Error:(611, 121) type 'NSAttributedStringKey' (aka 'NSString') has no member 'font' in `BarChartRenderer.swift`

## Charts Environment

**Charts version/Branch/Commit Number: 3.1.1**
**Xcode version: 9.3**
**Swift version: 3.3**
**Platform(s) running Charts: ios**
**macOS version running Xcode: High Sierra**

**Comment by thierryH91200** [comment]
find the mistake
read readme

- Xcode 9.3 / Swift 4.1
- iOS >= 8.0 (Use as an Embedded Framework)
- tvOS >= 9.0
- macOS >= 10.11

**Comment by castus** [comment]
🤦‍♂️  Now I see, thanks.

But, don't you think that versioning is wrong?
3.0.4 was a first release with Swift 4 which was backwards-uncompatible. In my opinion it should be 3.1 then. I had `~> 3.0.3` in my podfile so it should work up to 3.1, but after an update the project stops to compile.
What do you think?

**Comment by liuxuan30** [comment]
We don't provide support for legacy swift. I tried on my side, changing to Swift 3.3 won't compile as well. So if you think it should, report to Apple.
