### ISSUE TITLE
Show grid with axis deactivated

### ISSUE THREAD

**Issue by gmoraleda** [danielgindi/Charts#3436]
I'm working with this great library but I'm facing an issue I cannot solve.
I deactivated my Y and X axis so that the graph goes till the screen margins:

```
    mainChartView.rightAxis.enabled = false
    mainChartView.leftAxis.enabled = false
    mainChartView.leftAxis.axisMaximum = 1.2
    mainChartView.leftAxis.axisMinimum = 0
    mainChartView.xAxis.enabled = false
```
Nevertheless I want to draw a background grid. Is that possible?

This is my current graph:
![screen shot 2018-04-30 at 15 30 29](https://user-images.githubusercontent.com/25835012/39429741-246238d8-4c8c-11e8-956f-adcaaaa77816.png)

And this is how I would like it to be:
![screen shot 2018-04-30 at 15 36 09](https://user-images.githubusercontent.com/25835012/39429805-55f6d23c-4c8c-11e8-8a65-6c1f1e06c2a5.png)

Thanks in advance!

**Comment by liuxuan30** [comment]
grid background is not supported yet. We are planning but it should be a long time.
Either you change the source code and maybe a PR for us, or just wait.
