### ISSUE TITLE
Axis label alignment with labelRotationAngle

### ISSUE THREAD

**Issue by amolloy** [danielgindi/Charts#3437]
I want to have my x axis labels rotated 45 degrees, but want them to be aligned so the left edge of the text is lined up with the axis line. Currently, if I set labelRotationAngle to 45, the labels are rotated as expected, but are still centered on the line, like this:

![xaxisrotationoffset](https://user-images.githubusercontent.com/701717/39472539-14904f1c-4d18-11e8-8b53-04e7c7d9da7b.png)

What I'd like is for it to look like this:

![xaxisrotationoffsetwhatiwant](https://user-images.githubusercontent.com/701717/39472563-2b60fa3e-4d18-11e8-86e3-6acdd3cd8a51.png)

Sorry if I'm missing something obvious, but I didn't see a way to accomplish this. Thanks!

**Comment by liuxuan30** [comment]
have you tried `centerAxisLabelsEnabled`? If it's not working, then i guess it's just by design.
You can modify `drawLabels` and maybe a PR for us

**Comment by erfanwakka** [comment]
I have the same problem
