### ISSUE TITLE
Candlestick doesn't work when x does not start at 0

### ISSUE THREAD

**Issue by mannyveloso** [danielgindi/Charts#3441]
## What did you do?

We're attempting to make a candlestick graph where the x-axis is a date value. We added a datevalueformatter so the x-axis would display DD-MMM-YYYY.

## What did you expect to happen?

The date formatter would display the date on the x-axis.

## What happened instead?

The graph axis labels were 01-Jan-1970. In addition, the candlestick graph was drawn oddly. The red dot that was normally there was gone.

From a quick look at the code, the renderer seems to assume that x is a monotonically increasing value that starts at 0.

## Charts Environment

**Charts version/Branch/Commit Number:**
Charts 3.1.1
Xcode 9.3
Swift 4.1
iOS 11.3
Mac OS 10.13.4

**Comment by liuxuan30** [comment]
take a look at the demo. You can workaround by modifying the value formatter to start from 0.

And what number you start with?

**Comment by liuxuan30** [comment]
post more details and images and reopen it.

**Comment by mannyveloso** [comment]
So, image #1 is when the x coordinate is a straight-up 0-1-2-3-4-5-etc.

Image #2 is when the x-coordinate is the time since 1970. The red bars are missing and it's oddly offset.

![img_0149](https://user-images.githubusercontent.com/10236863/40484279-a140ee9e-5f8d-11e8-9676-1f3c96c80758.PNG)
![img_0148](https://user-images.githubusercontent.com/10236863/40484280-a172e020-5f8d-11e8-84fe-8843478f1deb.PNG)
So

**Comment by mannyveloso** [comment]
Can't reopen the issue. Should I just open a new issue?

**Comment by mannyveloso** [comment]
Dup of #1742
