### ISSUE TITLE
Chart callback events

### ISSUE THREAD

**Issue by sashberd** [danielgindi/Charts#3443]
Is there is a way to know that chart is ready?

E.g. onChartReady/onChartDraw?

Thanks

**Comment by liuxuan30** [comment]
it's not supported I suppose. What's the point here?

**Comment by sashberd** [comment]
For example I would like to show some other elements on the screen only after chart is ready or chart animations is ended.
It is good feature that i think could enlarge todays functionality

**Comment by liuxuan30** [comment]
hmm, it seems you can easily override `ChartViewDelegate` to add the methods and in `draw` to call the delegate. You are the first one to ask this. Let's keep an eye on

**Comment by ghubaddole** [comment]
+1
