### ISSUE TITLE
how to use 'LineChartView' to draw a line between nonzero values?

### ISSUE THREAD

**Issue by zq190693370** [danielgindi/Charts#3448]
Hi there~

if the chart data array contains zero values, 'LineChartView' will draw a line from one value to next one, include zero value! now my requirement is ignoreing zero values and drawing a line between nonzero values, like this:
![default](https://user-images.githubusercontent.com/6028259/39754948-825ec102-52f6-11e8-8bcd-407fdfc8fa98.png)
how should i do? thks!

**Comment by liuxuan30** [comment]
use two data sets as workaround.
