### ISSUE TITLE
Using SPM results in a "dependency graph is unresolvable" error.

### ISSUE THREAD

**Issue by sbromberger** [danielgindi/Charts#3470]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Following #2950, I added
```
dependencies: [
   .package(url: "https://github.com/danielgindi/Charts.git", from: "3.1.1")
]
```

to a brand-new Package.swift created by `swift package init`, and attempted to download the dependency and build the project using `swift build`.

## What did you expect to happen?

I expected `swift build` to succeed.

## What happened instead?

I received the following output:

```
Updating https://github.com/danielgindi/Charts.git
error: dependency graph is unresolvable; found these conflicting requirements:

Dependencies: 
    https://github.com/danielgindi/Charts.git @ 3.1.1..<4.0.0

```

## Charts Environment

**Charts version/Branch/Commit Number:**
n/a (trying to use 3.1.1)

**Xcode version:**
9.3 (9E145)
**Swift version:**
4.1.1
**Platform(s) running Charts:**
MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)
**macOS version running Xcode:**
MacOS High Sierra (10.13.4)

## Demo Project
Here's the full `Package.swift`:

```
// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "ChartTest",
    products: [
        .library(
            name: "ChartTest",
            targets: ["ChartTest"]),
    ],
    dependencies: [
        .package(url: "https://github.com/danielgindi/Charts.git", from: "3.1.1")
    ],
    targets: [
        .target(
            name: "ChartTest",
            dependencies: ["Charts"]),
        .testTarget(
            name: "ChartTestTests",
            dependencies: ["ChartTest"]),
    ]
)
```

**Comment by liuxuan30** [comment]
any swift pkg expert could help? Not sure it's about our issue.

**Comment by petester42** [comment]
The v in our tags is the problem. I just pushed a rename of the latest release as `3.1.1` instead of `v3.1.1`
