### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Shubham1992** [danielgindi/Charts#3472]
## What did you do?

installed graph library using pod

## What did you expect to happen?

build project and see a graph

## What happened instead?

project didnot build ang i got this error 
/Users/shubhamgoel/Documents/core-bizmanager-ios/Pods/Charts/Source/Charts/Charts/BarLineChartViewBase.swift:70:76: Cannot use instance member '_viewPortHandler' within property initializer; property initializers run before 'self' is available

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: 9**
**Swift version: 4**

**Comment by thierryH91200** [comment]
just read readme
Xcode 9.3 / Swift 4.1
iOS >= 8.0 (Use as an Embedded Framework)
tvOS >= 9.0
macOS >= 10.11
