### ISSUE TITLE
getValuesByTouchPoint / UIView coords to graph coords

### ISSUE THREAD

**Issue by XReyRobert** [danielgindi/Charts#3474]
Hi,
It seems that in the android version there are functions to go from chart coords to view coords and the opposite. I can't find equivalent functions in the ios version. 

Highlight got xPx and yPx properties that allows to go from highlight coords to view coords, but I can't find a way to go from view coords to graph coords... 

Anyone with some hints about how this could be achieved ?

**Comment by liuxuan30** [comment]
I have replied in the other post. Just look at ChartTransformer and ViewPortHandler.
