### ISSUE TITLE
xAxis label is croped  when using custom valueFormatter

### ISSUE THREAD

**Issue by fvisticot** [danielgindi/Charts#3485]
I'm using an HorizontalBarChartView

I have set a value formatter:
`[cell.chartView.xAxis setValueFormatter: self];`

The formatter is correctly triggered 

The pb is that the String label returned by the formatter is cropped and the label is not correctly displayed.

How to recompute labels size/width on the xAxis after calling the value formatter ?

**Comment by liuxuan30** [comment]
there are functions getting the size of label before render:    open override func computeSize()

look at the implementation to know why it does not compute correctly.
