### ISSUE TITLE
Is there a better way to easily add highest and lowest value in candlestick chart

### ISSUE THREAD

**Issue by AttackOnDobby** [danielgindi/Charts#3488]
![default](https://user-images.githubusercontent.com/1487627/40952836-9e40ecdc-68af-11e8-8b45-bdac17d8faed.png)

so how to add the max and min value circled in the picture above, thanks

**Comment by Leo007Lee** [comment]
[http://note.youdao.com/noteshare?id=eed07e5170848bf76bd7150f7a3ea2f0](url)

**Comment by AttackOnDobby** [comment]
@Leo007Lee exactly what I want！！

**Comment by lanmoyingsheng** [comment]
@AttackOnDobby 
Leo007Lee is "唐巧"。。。

**Comment by lanmoyingsheng** [comment]
Cool！

**Comment by Leo007Lee** [comment]
290673004 @AttackOnDobby
