### ISSUE TITLE
Errors when trying to compile a project using Charts

### ISSUE THREAD

**Issue by tonucha** [danielgindi/Charts#3496]
## What did you do?
I have two Swift Projects with Charts in them.
Project 1 contains views added to the demo project, cloned from Github. This works fine with hardcoded data on a barchart showing 'Expected' and 'Actual' levels of activity.
Project 2 is my 'real' project. It uses a number of AWS functions, retrieves data from the cloud, etc and I need to replicate the bar chart with the two datasets. This  already had a pod file. 
- I added " pod 'Charts' " to the podfile (excluding the " ")
- I ran "pod install" at the terminal --- all fine
- I opened my xcworkspace and added a view to one of the View Controllers. I selected  BarChartView in the Class, and saw 'Charts' in the Module (all looking good!)
-I created a new file and entered "import Charts" - Error: No such Module.
- I commented it out and tried to compile.

## What did you expect to happen?
I expected the project to compile (!) -- for once the problem was not caused by me (that's a first!) 

## What happened instead?
I got 5 errors in the file ChartUtils.swift
Ambiguous Operator +
Use of undeclared type NSAttributedStringKey (in 4 different places)
I then opened the corresponding file in my 'working test project' and realised that the two files are different. 
 

## Charts Environment
**Charts version/Branch/Commit Number:**
3.0
**Xcode version:**
8.2.1
**Swift version:**
10.9
**Platform(s) running Charts:**

**macOS version running Xcode:**
OSX El Capitan 10.11.6
## Demo Project

GN_IOS_Light copy.zip

**Comment by tonucha** [comment]
ps... the number of compilation errors goes up and down. 
-Cannot use instance member '_viewPortHandler' within property initializer...'
-count is unavailable: there is no universally good answer...'

**Comment by thierryH91200** [comment]
please read "readme"

Xcode 9.3 / Swift 4.1
iOS >= 8.0 (Use as an Embedded Framework)
tvOS >= 9.0
macOS >= 10.11
