### ISSUE TITLE
LineChartView setup  "set.mode = LineChartModeCubicBezier",The wave-peak trough of the smooth chart shows no value and deviates from these points

### ISSUE THREAD

**Issue by ziyanliu** [danielgindi/Charts#3497]
LineChartView setup  "set.mode = LineChartModeCubicBezier",The wave-peak trough of the smooth chart shows no value and deviates from these points，The following figure
<img width="233" alt="2018-06-08 2 01 11" src="https://user-images.githubusercontent.com/17906822/41141812-f56adcd4-6b25-11e8-9838-41449f0fcc04.png">

**Comment by liuxuan30** [comment]
use the other bezier mode.
