### ISSUE TITLE
App Crash in release mode not in debug mode 

### ISSUE THREAD

**Issue by RubyRoshan** [danielgindi/Charts#3499]
@#Please help . I am getting this exception  while in release mode of my application .

![screen shot 2018-06-09 at 5 35 04 pm](https://user-images.githubusercontent.com/20574966/41191519-70270a18-6c0e-11e8-89de-f1a59d92e8e0.png)

**Comment by RubyRoshan** [comment]
`context.setFillColor(dataSet.getCircleColor(atIndex: j)!.cgColor)`

This line in LineChartRenderer is causing crash in ios 10.0.3 iPhone 7 .Please check and update

**Comment by liuxuan30** [comment]
what's the reason? OOB? I don't see the stack trace is the same as your quote

**Comment by RubyRoshan** [comment]
I just commented this line  `context.setFillColor(dataSet.getCircleColor(atIndex: j)!.cgColor)` 

and its working .but now color of hole (dots are not same as previous)They are white in color now. Previously They match exactly the line color

**Comment by liuxuan30** [comment]
I don't think you understand how to reproduce; commenting the line out only impact the feature. if you sure it's because this function, then you have to make sure you have enough colors. *OOB is not our fault, but yours*

**Comment by NSAmit** [comment]
Its same for me too. It does crash in release mode but not it debug mode. I could not get the symbolicated crash yet. But will definitely upload once have more updates.
