### ISSUE TITLE
32 bit Device not handling high x-values

### ISSUE THREAD

**Issue by mumphus** [danielgindi/Charts#3507]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I have a graph representing live data values. Every second a new point is added to the data, x-value being time in seconds, and y-value being a measured value from an external device. This was working perfectly when I was using a different system to represent time(first datapoint was 0 seconds) but I changed it so that my data source stores all the points with their time in seconds(since 1970 I believe) because I wanted to be able to save the data set and view it in other places and so the time needed to be stored since 1970 and not starting at 0. The issue was not immediately showing as I was using a 64 bit device(iPhone 6S+) and this new system I implemented worked exactly as it should. But as I was testing on other devices for compatibility a 32 bit iPod was not able to work with this new system.

## What did you expect to happen?

Here is what it should look like:
![img_0036](https://user-images.githubusercontent.com/40215561/41314579-63e87d16-6e4a-11e8-86cc-82aab965b409.png)
Here is what the data set looks like(only posted a few values):
ChartDataEntry, x: 1361.0, y 8.0
ChartDataEntry, x: 1362.0, y 18.0
ChartDataEntry, x: 1363.0, y 22.0
ChartDataEntry, x: 1365.0, y 22.0
ChartDataEntry, x: 1365.0, y 26.0
ChartDataEntry, x: 1366.0, y 30.0

What I did to get this to work here was take the stored x value and subtract 1528833000 from it, technically I could just subtract the the greatest multiple of 86400(24 hours) still less than the value, therefore still getting me the correct time of day, but I would rather find a better fix to this issue.

## What happened instead?

Here is what it does look like:
![img_0037](https://user-images.githubusercontent.com/40215561/41314621-8ec10fa8-6e4a-11e8-8bf8-bc197b4ec43a.png)

Here is what the data set looks like(only posted a few values):
ChartDataEntry, x: 1528833342.0, y 128.0
ChartDataEntry, x: 1528833343.0, y 126.0
ChartDataEntry, x: 1528833344.0, y 128.0
ChartDataEntry, x: 1528833345.0, y 130.0
ChartDataEntry, x: 1528833346.0, y 132.0
ChartDataEntry, x: 1528833347.0, y 138.0
ChartDataEntry, x: 1528833348.0, y 136.0

If you really want I can post what it looks like on the iPhone 6S+ I can, but I can assure you that it looks exactly like it does in the first screenshot but without subtracting from the x-values, so they would be something in the size of this(x: 1528833348.0). Now I am not sure if this is to do with the iPod being a 32 bit device but that is my best guess. Also the entries were gotten from "Graph.data?.dataSets[0]" and so up to that point the values looked fine, and I wasn't sure where I could go to find where the x-values go wonky

## Charts Environment

**Charts version/Branch/Commit Number:Version 3.1.1**
**Xcode version:9.2 (9C40b)**
**Swift version:4.0**
**Platform(s) running Charts:iPhone 6S+(iPhone7,1), iPod5,1**
**macOS version running Xcode:10.13.5 (17F77)**

## Demo Project

My project requires the connection to a bluetooth device in order to function, It should be easily reproducible if I understand it correctly. Just create a chart using a line chart data set with very high x-values on a 32bit device

**Comment by mumphus** [comment]
I was really getting confused by this, because 32 bit device should still be able to hold that size of integer, but realizing it now the Entry stores it as a Double. Ive been looking around for a while and from what I can tell 32 bit devices cant actually use doubles, but instead use floats. Could this be the issue that the 32bit device is restricted to floats, which possibly restricts the max size for the x-value?

**Comment by liuxuan30** [comment]
I remember we used to see users reporting 32bit device issues like #https://github.com/danielgindi/Charts/issues/2583, https://github.com/danielgindi/Charts/issues/1737, https://github.com/danielgindi/Charts/issues/1679. 

I am feeling if you are sure it's about 32bit and 64bit. There's basically nothing we can do as it's a closed hardware and software of Apple. Either it's a bug or by design.

What I suggest is you simply move on, as iPhone 5 is in history. You don't have to worry about it or just abandon the support. If you think you should support that, then follow what #1679 does or subtract 1528833000 to make some tricks to make it work on a 32bit device.

**Comment by mumphus** [comment]
@liuxuan30 Is there any way to have the x-value stored as an Int? for my use case I don't need it to be CGFloat and the extra significant figures I gain from using an Integer would fix my issue I belive

**Comment by liuxuan30** [comment]
I don't think it's about Int. Int is way more smaller than even float. And drawing on screen require CGFloat. You will do the convert anyway.
