### ISSUE TITLE
Bar chart is plotting for empty value and Line chart is not appeared in CombinedChartView

### ISSUE THREAD

**Issue by muthusabarinathan** [danielgindi/Charts#3511]
## What did you do?
I would like to create a chart for stocks price and volume. So I chooses combinedChartView. I would like to show date in xAxis. I tried it with charts-swift demo code.

## What did you expect to happen?
My expectation is to show price value as LineChart and Volume value as Bar chart like below mentioned Image.

![screen shot 2018-06-13 at 5 28 46 pm](https://user-images.githubusercontent.com/7147681/41350045-673f855a-6f2f-11e8-82c0-6a8a0e5c35e4.png)
  

## What happened instead?
But when i tried the demo chart using my values, I got bar chart alone instead of combine the line chart. 

And also am passing only 5 values. But chart shows 7 values, Jun 9 and Jun 10 is also plotting with no bar(I don't pass Jun 9 and Jun 10).

![screen shot 2018-06-13 at 5 23 17 pm](https://user-images.githubusercontent.com/7147681/41350099-9f17db6c-6f2f-11e8-9e1d-a2c651ee945d.png)

Herewith I attached my demo project file:

[CombinedChartViewController.swift.zip](https://github.com/danielgindi/Charts/files/2097985/CombinedChartViewController.swift.zip)

## Charts Environment

**Charts version/Branch/Commit Number:**  **_3.1.1_**
**Xcode version:** **_9.2_**
**Swift version:** **_3.2_**
**Platform(s) running Charts:** **_iOS_**
**macOS version running Xcode:** _**10.13.1**_

Please help me to achieve this.

**Comment by thierryH91200** [comment]
you are confusing date and interval

change 

```
extension ChartXAxisFormatter: IAxisValueFormatter {
    func stringForValue(_ value: Double, axis: AxisBase?) -> String {
        var date: [String]! = ["2018-06-12","2018-06-11","2018-06-08","2018-06-07","2018-06-06"]
        
        public func stringForValue(_ value: Double, axis: AxisBase?) -> String
        {
            return date[ Int(value) ]
        }
    }
}
```

and 
 date -> i


```
       for i in 0 ..< dateArr.count {
            let date = dateFormatter.date(from: dateArr[i])
            let yValue1: Double = Double(priceArr[i])
            let yValue2: Double = Double(volumeArr[i])
            let dataPoints = DataPointsValue(_xDate: i, _value1: yValue1, _value2: yValue2)
            chartData.append(dataPoints)
        }

```

**Comment by muthusabarinathan** [comment]
@thierryH91200 - Thank you so much. It perfectly works. Can you have any idea to draw bar chart in bottom like my expectation image.

**Comment by thierryH91200** [comment]
I did not understand the question sorry

**Comment by muthusabarinathan** [comment]
Nothing. I fixed it. Thanks for your valuable solutions.
