### ISSUE TITLE
Line chart with LineChartView the line is lower than the minimum values

### ISSUE THREAD

**Issue by frfuentes** [danielgindi/Charts#3513]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I'm working on a line graph using LineChartView, in CubicBezier mode

## What did you expect to happen?

I try to obtain a graph allowing curves, but respecting the limits

## What happened instead?

![captura de pantalla 2018-06-13 a la s 13 37 30](https://user-images.githubusercontent.com/5440425/41366261-e9446a34-6f11-11e8-9145-a91d207f5aed.png)

In many cases the line is lower than the minimum values generating confusion, as you can see in the image, the line seems to have values below 0

## Charts Environment

Charts version/Branch/Commit Number: 3.3.1 Release
Xcode version: 8.2.1
Swift version: 2
Platform(s) running Charts: iOS
macOS version running Xcode: 10.13.4

**Comment by thierryH91200** [comment]
try to play... with Intensity for cubic lines 

**default**: 0.2

dataset.cubicIntensity = (min = 0.05, max = 1)
I think 0.1 should be fine

**Comment by thierryH91200** [comment]
it's impossible to be Swift version: 2 
please read readme

Xcode 9.3 / Swift 4.1
iOS >= 8.0 (Use as an Embedded Framework)
tvOS >= 9.0
macOS >= 10.11

**Comment by thierryH91200** [comment]
your issue is completely normal
see https://en.wikipedia.org/wiki/Bézier_curve

**Comment by frfuentes** [comment]
Thanks @thierryH91200, yes you are rigth is swift 3, but i tested whit 0.05 cubicIntensity but still having the same problem !

**Comment by thierryH91200** [comment]
stop it's not a problem it is a CubicBezier
![bezier_2_big](https://user-images.githubusercontent.com/6251463/41420387-8f010634-6ff4-11e8-9094-624e1db86d03.gif)

**Comment by liuxuan30** [comment]
try horizontal bezier. the cubic one is a little buggy.
