### ISSUE TITLE
First and Last Bars are not displaying full bars in CombinedChartView

### ISSUE THREAD

**Issue by muthusabarinathan** [danielgindi/Charts#3515]
## What did you do?
I would like to create a chart for stocks price and volume. So I chooses combinedChartView. 

## What did you expect to happen?
I would like to show price as LineChart and Volume as BarChart. And I created by using CombinedChartView.

## What happened instead?
Here First and Last Bars are not displaying full bars.

1st Issue:
![screen shot 2018-06-14 at 12 44 54 pm](https://user-images.githubusercontent.com/7147681/41397656-898911fa-6fd2-11e8-9bec-a3da776f115b.png)

 So I changed xAxis.axisMinimum value as -0.5. Now bars are looking good but line chart is moved.
2nd Issue:
![screen shot 2018-06-14 at 12 46 04 pm](https://user-images.githubusercontent.com/7147681/41397722-bf7f79a2-6fd2-11e8-9fa6-02b753a38324.png)

## Expectation:
I want to change BarChart xAxis minimum value alone without affecting LineChart xAxis.

## Charts Environment

**Charts version/Branch/Commit Number:**  **_3.1.1_**
**Xcode version:** **_9.2_**
**Swift version:** **_3.2_**
**Platform(s) running Charts:** **_iOS_**
**macOS version running Xcode:** _**10.13.1**_

Please help me to achieve this.

**Comment by liuxuan30** [comment]
check out ChartsDemo #323
