### ISSUE TITLE
Scrolling of bar chart is not working initially. 

### ISSUE THREAD

**Issue by NPhadtare** [danielgindi/Charts#3532]
I create a bar chart using using this library. and want to show minimum 7 bars initially. But show all data  at once after load. Please help me to achieve this.

**Comment by nastassia-kavaliova** [comment]
Try this:

chartView.xAxis.labelCount = 7

**Comment by asheesh-gupta-kranti** [comment]
We are facing the same issue, we want to show only 4 bars and want to have scroller to scroll for rest of the bars. Is there any way to do this?

**Comment by nastassia-kavaliova** [comment]
@asheesh-gupta-kranti  have you tried setting labelCount property?
chartView.xAxis.labelCount = 4

**Comment by asheesh-gupta-kranti** [comment]
Yes, I have but it's only changing the number of labels not the number of bars.

**Comment by liuxuan30** [comment]
please ask on stack ovreflow next time.

This, time, it should be
```
    /// Sets the size of the area (range on the x-axis) that should be minimum visible at once (no further zooming in allowed).
    ///
    /// If this is e.g. set to 10, no less than a range of 10 values on the x-axis can be viewed at once without scrolling.
    ///
    /// If you call this method, chart must have data or it has no effect.
    @objc open func setVisibleXRangeMinimum(_ minXRange: Double)
    {
        let xScale = _xAxis.axisRange / minXRange
        _viewPortHandler.setMaximumScaleX(CGFloat(xScale))
    }
```

**Comment by pateljinal1844** [comment]
I just found out, ordering matters for this to work. You need to call setVisibleXRangeMaximum after chartView.data = data or notifyDataSetChanged

**Comment by CavalcanteLeo** [comment]
dude, @pateljinal1844 , i was like an hour crying because it wasn't working, shit, there is no doc at all
