### ISSUE TITLE
Horizontal Bar Chart Bar Collapsing

### ISSUE THREAD

**Issue by rupalchanpreet** [danielgindi/Charts#3535]
![screen shot 2018-06-26 at 5 11 37 pm](https://user-images.githubusercontent.com/40599427/41909422-9d33f31e-7964-11e8-85f1-17615aa1bec6.png)

Set barChart data on graph, value with lower count takes too little space/bar height as compare to bar with higher count.  

Any solution to make bar height slightly bigger so that smaller values will be visible and distinguishable.

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: - 9.4/9.2
**Swift version: - 4.0
**Platform(s) running Charts: - iOS 11
**macOS version running Xcode: - 10.13.4/10.13.5

**Comment by liuxuan30** [comment]
known issue, but no solution yet, as it's too small. imagine how you draw them with percentage. I would say either you change your chart type.
