### ISSUE TITLE
disable gradient fill Linechart

### ISSUE THREAD

**Issue by Atchu** [danielgindi/Charts#3537]
**Can you help me how to remove the numbers(yValues) above the LineChart.**

<img width="366" alt="screen shot 2018-06-28 at 10 43 54 am" src="https://user-images.githubusercontent.com/5966039/42014489-34d994a6-7ac0-11e8-9fbc-5a872a9dd872.png">

**I want to show a LineChart graph without numbers on the graph**

**Comment by thierryH91200** [comment]
try
dataset.drawValuesEnabled = false

**Comment by Atchu** [comment]
Thanks It's works
