### ISSUE TITLE
Highlighting on a scrollable line graph

### ISSUE THREAD

**Issue by varunknarayanswamy** [danielgindi/Charts#3539]
So I am using the the ios charts library and limiting the view to about 20 data points at a time. Because of that I of course have a scrollable view. Furthermore, I am restraining the y of the chart so that the user can't get lost if they go too far up. Now with the work I am doing, I am trying to highlight portions of the graph by dragging my finger over them. I already have an implementation which will allow me to long tap and drag over the chart and reads the data points from it. However, I want to have the background of the chart where I drag change color so I know what dragged over. Is there a way to change the color of the background for a portion of the graph.
**Xcode version: 9.4.1
**Swift version: 4

**Comment by liuxuan30** [comment]
Jesus, would you reorg your words? Not able to read at all.

**Comment by varunknarayanswamy** [comment]
I shortened it and reworded my question so that it would be easier to read. Thanks for being super considerate. (That was sarcastic if you didn't realize it. And if you didn't realize it I can try and "reorg" it   so that it's more obvious)

**Comment by liuxuan30** [comment]
man, use multiple lines, putting them into one line takes too long to read.

**Comment by liuxuan30** [comment]
the background color by default is for the chart view, we don't have `color of the background for a portion of the graph.`
