### ISSUE TITLE
Value of type 'EnumeratedSequence<[CGPoint]>' has no member 'compactMap'

### ISSUE THREAD

**Issue by xiuzhongjin** [danielgindi/Charts#3543]
pod install后编译报错，提示Value of type 'EnumeratedSequence<[CGPoint]>' has no member 'compactMap'

**Comment by CodingEleven** [comment]
I have the same problem after updating version from 3.0.5 to  3.1.1 !!!
why?

**Comment by thierryH91200** [comment]
Haye you read "readme" ?

- Xcode 9.3 / Swift 4.1
- iOS >= 8.0 (Use as an Embedded Framework)
- tvOS >= 9.0
- macOS >= 10.11

**Comment by CodingEleven** [comment]
@thierryH91200 thanks ! I find my Xcode version is 9.2

**Comment by Su-Huanzhen** [comment]
ge men,qing Shuo yingyu
