### ISSUE TITLE
X or Y axis interval of the labels 

### ISSUE THREAD

**Issue by sultan-arshi** [danielgindi/Charts#3547]
As we know that charts library auto calculate the labels/values on X-Axis and Y-Axis according to the values we provide in array 

I Want to know the interval it is using on x-axis and on y-asix

is it possible ?

and I also looking to set the interval 

## Charts Environment

**Charts version/Branch/Commit Number: latest**
**Xcode version: 9.4**
**Swift version: 4**
**Platform(s) running Charts: IOS**
**macOS version running Xcode: hight Sarria**

**Comment by sultan-arshi** [comment]
I am using 

- chartView.xAxis.granularityEnabled = true

- chartView.notifyDataSetChanged()

- let interval = chartView.xAxis.granularity

- interval always is 1 I don't know why it is happening

**Comment by thierryH91200** [comment]
the default value of granulatary is 1.0

        If granularity is enabled, then do not allow the interval to go below specified granularity.
       This is used to avoid repeated values when rounding values for display.

look at 

YAxisRenderer :  @objc open func computeAxisValues(min: Double, max: Double)

**Comment by sultan-arshi** [comment]
can you please explain it 
I want to know the interval of the x-axis and y-axis
is it possible ?

**Comment by georgmay** [comment]
@sultan-arshi I'm pretty sure you need to set the actual `xAxis.granularity` value, as per documentation:
```
The minimum interval between axis values.
This can be used to avoid label duplicating when zooming in.
```
