### ISSUE TITLE
Switch from Grouped Bar chart back to normal

### ISSUE THREAD

**Issue by elliotcz97** [danielgindi/Charts#3551]
## What did you do?
I made a Grouped Bar chart, and its working fine. I also have a Bar chart which works also.
And i have a segmented controller which when changed sets the dataset for the chart
## What did you expect to happen?
I wanted to have all of my 3 kinds of dataset presented how it should be.
This is how the Grouped Bar chart looks:
<img width="375" alt="bildschirmfoto 2018-07-08 um 03 45 40" src="https://user-images.githubusercontent.com/40901589/42421499-d9c64e14-82d6-11e8-9a07-0491c0a72f51.png">
This is the normal Bar Chart
<img width="374" alt="bildschirmfoto 2018-07-08 um 03 45 14" src="https://user-images.githubusercontent.com/40901589/42421500-d9f68afc-82d6-11e8-9f26-860ec708f56d.png">

## What happened instead?

After i switch from the grouped back to the normal my bars get thicker and the view looks zoomed in, but when i tried to set the zoom to 0 it still looked the same.

<img width="370" alt="bildschirmfoto 2018-07-08 um 03 46 03" src="https://user-images.githubusercontent.com/40901589/42421534-567d1a14-82d7-11e8-979b-196bca4afead.png">

## Charts Environment

**Charts version/Branch/Commit Number: 3.0.2
**Xcode version: 8.3.2
**Swift version: 3
**Platform(s) running Charts: iOS
**macOS version running Xcode: Sierra

## Demo Project
To be honest i also Posted a Question on StackOverflow and there i have posted the relevat functions.
https://stackoverflow.com/questions/51228333/how-to-switch-from-grouped-bar-chart-to-simple-bar-charts

Thanks in Advance for your answers!

**Comment by liuxuan30** [comment]
how do you switch? seems like you didn't call `notifyDataSetChanged`?
