### ISSUE TITLE
How to fill the area between two lines on LineChart

### ISSUE THREAD

**Issue by BharatJagtap** [danielgindi/Charts#3561]
## What did you do?

ℹ I tried to fill the area between two lines in a line chart with a color. I tried to follow this solution in Swift suggested for android [android-implementation-for-filled-line-graph](https://stackoverflow.com/questions/43342597/android-fill-the-color-between-two-lines-using-mpandroidchart/50118570#50118570)

## What did you expect to happen?

ℹ I wanted to get a line chart like this 

![filled_line_chart](https://user-images.githubusercontent.com/953491/42799718-82617a40-89b6-11e8-8dd3-03614a30030d.png)

## What happened instead?

ℹ But does not seem to be working well

**Comment by liuxuan30** [comment]
looks like we didn't support this filling yet. You can write your own filling algorithm in line chart renderer.

**Comment by rob-k** [comment]
Also see my comment to this issue: https://github.com/danielgindi/Charts/issues/2863#issuecomment-344574991
