### ISSUE TITLE
the x axis label is not in the right position when I used groupBarChart

### ISSUE THREAD

**Issue by ganjmeng** [danielgindi/Charts#3564]
I try to create multiple bar chart in objective-c. I look into the example project. But some how, the x axis label is not in the right position.
![image](https://user-images.githubusercontent.com/12026835/42860897-402b0ce2-8a8b-11e8-9ab8-5ad503327722.png)
You can see at the image above. The position of the label and the grouped bar is not in the same position. How I can fix this problem?

![image](https://user-images.githubusercontent.com/12026835/42860917-5796ed60-8a8b-11e8-87a6-510ade9a5723.png)
![image](https://user-images.githubusercontent.com/12026835/42860931-697d8d4a-8a8b-11e8-9ed4-ba1b9a84f2b5.png)

**Comment by liuxuan30** [comment]
be sure to follow what's in multiple bar chart:
```
        let groupSpace = 0.08
        let barSpace = 0.03
        let barWidth = 0.2
        // (0.2 + 0.03) * 4 + 0.08 = 1.00 -> interval per "group"
```

I'm not sure if your value sum to 1.0.

**Comment by ganjmeng** [comment]
![](https://user-images.githubusercontent.com/12026835/42860917-5796ed60-8a8b-11e8-87a6-510ade9a5723.png)
I'm sure

**Comment by liuxuan30** [comment]
post your calculation of this.
