### ISSUE TITLE
CandleChart In CombinedChartView not work

### ISSUE THREAD

**Issue by yanglfree** [danielgindi/Charts#3567]
In Objective-C Demo, CandleChart can not work

![](http://ww1.sinaimg.cn/large/0068ixCrgy1fte3dzqjwhj319y0yu0yp.jpg)

![](http://ww1.sinaimg.cn/large/0068ixCrgy1fte3eambbgj309d0jyq3f.jpg)

**Comment by liuxuan30** [comment]
I tried on my side, it's working.
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4375169/42978694-edde2024-8c00-11e8-99a5-cb7647faa0d2.png">

**Comment by Sum123** [comment]
I test my side  In Objective-C Demo and swift Demo, CandleChart can not work    
I just do this :

    func setChartData() {
        let data = CombinedChartData()
//        data.lineData = generateLineData()
//        data.barData = generateBarData()
//        data.bubbleData = generateBubbleData()
//        data.scatterData = generateScatterData()
        data.candleData = generateCandleData()
        
        chartView.xAxis.axisMaximum = data.xMax + 0.25
        chartView.data = data
    }

why?
@liuxuan30

**Comment by Sum123** [comment]
I found the problem.  Fixed this place.

` @objc open func drawDataSet(context: CGContext, dataSet: ICandleChartDataSet)
    {
        
        guard let dataProvider = dataProvider else {
            return;
        }
        
        if !(dataProvider is CombinedChartView || dataProvider is CandleStickChartView) {
            return;
        }
      ...
    }`

**Comment by Sum123** [comment]
I found the problem. Fixed this place. 

@objc open func drawDataSet(context: CGContext, dataSet: ICandleChartDataSet)
    {
        guard let dataProvider = dataProvider else {
            return;
        }
        
        if !(dataProvider is CombinedChartView || dataProvider is CandleStickChartView) {
            return;
        }
      ...
    }

**Comment by sharks-cha** [comment]
> I found the problem. Fixed this place.
> 
> @objc open func drawDataSet(context: CGContext, dataSet: ICandleChartDataSet)
> {
> guard let dataProvider = dataProvider else {
> return;
> }
> 
> ```
>     if !(dataProvider is CombinedChartView || dataProvider is CandleStickChartView) {
>         return;
>     }
>   ...
> }
> ```

Hello, I change according to your prompt, but error, can you provide the original code, thank you very much

**Comment by Sum123** [comment]
你好，这是demo中的问题，我发现release里没有问题。 
在demo测试代码的时候CandleStickChartView会不显示


| |
Sum123
|
|
18612254512@163.com
|
签名由网易邮箱大师定制


On 09/24/2018 09:46，sharks-cha<notifications@github.com> wrote：

I found the problem. Fixed this place.

@objc open func drawDataSet(context: CGContext, dataSet: ICandleChartDataSet)
{
guard let dataProvider = dataProvider else {
return;
}

    if !(dataProvider is CombinedChartView || dataProvider is CandleStickChartView) {
        return;
    }
  ...
}


Hello, I change according to your prompt, but error, can you provide the original code, thank you very much

**Comment by JiaLcrown** [comment]
I also met the problem in last release version. When I copied the combinedChart code in iOS swift demo to a new project, all the charts displayed well except the candleChart. I found that the CocoaPods install version is different from the demo one.

**Comment by lucasmpaim** [comment]
+1
