### ISSUE TITLE
Grid background color extends beyond data sets

### ISSUE THREAD

**Issue by ArunRajasekhar84** [danielgindi/Charts#3572]
## What did you do?

I had created a line graph with two data sets and brought a color within the range of two graphs. That works perfectly fine. But for range outside the data point the background color spreads the graph (as in image below).
<img width="532" alt="screen shot 2018-07-20 at 4 56 07 pm" src="https://user-images.githubusercontent.com/29298738/43000122-d8809c10-8c3d-11e8-82c8-260ba8f7291f.png">

## What did you expect to happen?

Is there a way to change the background color of grid outside the data set ? I would like the background color only within the data sets

## What happened instead?

As if now the background color of grid expands outside data sets

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1.0
**Xcode version:** 9.4
**Swift version:** 4.2
**Platform(s) running Charts:** Mac OS
**macOS version running Xcode:** 10.13.4

## Demo Project

The code is not available public as if now. Let me know if I can help you with code snippet.

**Comment by liuxuan30** [comment]
I'm not sure what you try to say. But the background is within the chart view. And from your screnshot, I don't think it's just a "background" color? Seems you are filling the area between the lines, but somehow after the last point, it become a normal rect.
