### ISSUE TITLE
Data labels not shown when mutable array of entries used. 

### ISSUE THREAD

**Issue by milesper** [danielgindi/Charts#3573]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Created data set for scatter plot using mutable array of ChartDataEntry objects and the DataSet constructor.

## What did you expect to happen?

ℹ Data labels to be shown by each point.

## What happened instead?

ℹ No labels shown unless array changed to immutable array.

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: 9.4.1**
**Swift version: **
**Platform(s) running Charts: iOS**
**macOS version running Xcode: 10.13.6**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by liuxuan30** [comment]
`No labels shown unless array changed to immutable array.`

You should answered yourself. Apparently you changed it, or, if you think we changed it, please provide code snippet so we can reproduce with ChartsDemo.

**Comment by liuxuan30** [comment]
I'm closing for now, reopen when you have more details.
