### ISSUE TITLE
swift library added successfully, but can't reach any of the interfaces

### ISSUE THREAD

**Issue by Phaptlq** [danielgindi/Charts#3605]
i build swift library added successfully, but can't reach any of the interfaces  

SWIFT_CLASS("_TtC8cscharts13BalloonMarker")
@interface BalloonMarker : ChartMarkerImage
@property (nonatomic, strong) UIColor * _Nonnull color;
@property (nonatomic) CGSize arrowSize;
@property (nonatomic, strong) UIFont * _Nonnull font;
@property (nonatomic, strong) UIColor * _Nonnull textColor;
@property (nonatomic) UIEdgeInsets insets;
@property (nonatomic) CGSize minimumSize;
- (nonnull instancetype)initWithColor:(UIColor * _Nonnull)color font:(UIFont * _Nonnull)font textColor:(UIColor * _Nonnull)textColor insets:(UIEdgeInsets)insets OBJC_DESIGNATED_INITIALIZER;
- (CGPoint)offsetForDrawingAtPoint:(CGPoint)point SWIFT_WARN_UNUSED_RESULT;
- (void)drawWithContext:(CGContextRef _Nonnull)context point:(CGPoint)point;
- (void)refreshContentWithEntry:(ChartDataEntry * _Nonnull)entry highlight:(ChartHighlight * _Nonnull)highlight;
- (void)setLabel:(NSString * _Nonnull)newLabel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

Don't reach BalloonMarker Interface.

**Comment by liuxuan30** [comment]
I don't know what are you talking about. BalloonMarker is not part of the library, it's a demo.
