### ISSUE TITLE
How can I combine two lineCharts？

### ISSUE THREAD

**Issue by Args** [danielgindi/Charts#3607]
## What did you do?

I try to use `CombinedChartView`,but it doesn't seem to combine two charts of the same type

## What did you expect to happen?

I want to combined two lineCharts,and can update data together.Code like this
```
    CombinedChartData *data = [[CombinedChartData alloc] init];
    data.lineData0 = [self generateLineData0];
    data.lineData1 = [self generateLineData1];
```
or
```
    CombinedChartData *data = [[CombinedChartData alloc] init];
    data.lineDataArr = [self generateLineDataArr];
```

## What happened instead?

```
    CombinedChartData *data = [[CombinedChartData alloc] init];
    data.lineData = [self generateLineData];
```

## Charts Environment

**Charts version/Branch/Commit Number:3.1.1
**Xcode version:9.4.1
**Swift version:4.1
**Platform(s) running Charts:iOS
**macOS version running Xcode:10.13.5

**Comment by suvan92** [comment]
Use the demo app for examples. What you're looking for is in LineChart2. You can initialize LineChartData with multiple LineChartDataSets:

`let data = LineChartData(dataSets: [set1, set2, set3])`
`chartView.data = data`

where chartView is a an instance if LineChartView

**Comment by liuxuan30** [comment]
Just use two line chart data sets. There are examples in multiple line chart

**Comment by Rajneesh071** [comment]
Hi @liuxuan30 
How to do the same with along with bar chart?
I want to set 2 line data set and 1 bar data set.
And overlapping would be like this "Line 1 , Bar 1, Line 2"
