### ISSUE TITLE
Installation with carthage error!!!

### ISSUE THREAD

**Issue by SimonKsss** [danielgindi/Charts#3610]
I add

github "danielgindi/Charts" == 3.1.1

in my carthage file, then I run

carthage build --no-skip-current && carthage archive Charts

but I get this error in console:
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/Desktop/Carthage/Checkouts/Charts/Charts.xcworkspace -scheme Charts -configuration Release -derivedDataPath /Users/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/Charts/v3.1.1 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/8t/9vypgvz93m3b4vb34ym_p9440000gn/T/Charts SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/Desktop/Carthage/Checkouts/Charts)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8t/9vypgvz93m3b4vb34ym_p9440000gn/T/carthage-xcodebuild.8pJt1P.log

How can I solve this problem. I'm using Swift4.0 and Xcode 9.2

**Comment by Max0u** [comment]
Did you solved your problem ?
