### ISSUE TITLE
PieChart with value lines with very small values render values on top of each other

### ISSUE THREAD

**Issue by luiseduardoglez** [danielgindi/Charts#3613]
## What did you do?

Created a pie chart with value lines to display de values outside the chart. Some of the values i'm getting now are very low (0.5%, 1.5%)

## What did you expect to happen?

Draw a pie chart with values.

## What happened instead?

The two values that are very low can't be understood as they render on top of each other. As it's visual i let you a screenshoot of how the chart renders

![graph_issue](https://user-images.githubusercontent.com/2504420/44693950-eca61d00-aa38-11e8-872a-db62fa034fcb.png)

## Charts Environment

**Charts version/Branch/Commit Number:** 3.1.1
**Xcode version:** 9.3.1
**Swift version:** 4.1
**Platform(s) running Charts:** iOS 11.3.1
**macOS version running Xcode:** macOS 10.13.3

## Demo Project

Attached a demo project with my PieChart implementation that reproduces this  #behavior
[piechartdemo.zip](https://github.com/danielgindi/Charts/files/2326114/piechartdemo.zip)

**Comment by liuxuan30** [comment]
it seems unavoidable? just like bar chart values, similar value lead to similar position.

**Comment by AhmadOdeh93** [comment]
you solved it ?? i have the same issue
