### ISSUE TITLE
Charts ScaleX problem

### ISSUE THREAD

**Issue by quoctc** [danielgindi/Charts#3616]
I want to auto scale chart by scaling X to fixing the size of my data. So my charts will not zoom in too much. It's will keep the same space between two points of x values in the chart. But when I call to scaleX by call this func: 

> chartView.zoomToCenter(scaleX: scale, scaleY: 1.0). It generates weird scaleX number, not my expected number

Here is the debug:
https://screencast.com/t/hGJv2Rl5

## What did you expect to happen?

It's should be my scale nubmer that I'm giving. Or there is any function in the lib support it

## What happened instead?

It's scale with a bigger number

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:*9.4*
**Swift version:*4.0*
**Platform(s) running Charts:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by quoctc** [comment]
I know where is the issue. You are using scale by. So, I can fixed it now.

**Comment by liuxuan30** [comment]
then please file a PR, than you

**Comment by quoctc** [comment]
?

**Comment by liuxuan30** [comment]
@quoctc 
>I know where is the issue. You are using scale by. So, I can fixed it now.

**Comment by quoctc** [comment]
Oh, It does not need to create a PR, I just use a formula to change it
