### ISSUE TITLE
Reg: Display Min and Max Point in a PopUp

### ISSUE THREAD

**Issue by SravanPeddi** [danielgindi/Charts#3617]
I would like to display Min and Max Point like attached image. How can we acheive the same ?

![screen shot 2018-08-30 at 11 59 26 am](https://user-images.githubusercontent.com/13622491/44834435-d5d91380-ac4e-11e8-8d32-11d66c204bf7.png)

**Comment by liuxuan30** [comment]
`ChartMarker`
