### ISSUE TITLE
Add labels to marker or create custom marker view

### ISSUE THREAD

**Issue by Bogdan59** [danielgindi/Charts#3620]
How to create custom marker with labels?
Now I use BalloonMarker, but it does not fit
```
`open class MarkerView1: BalloonMarker
{
  public override init(color: UIColor, font: UIFont, textColor: UIColor, insets: UIEdgeInsets)
    {
        super.init(color: color, font: font, textColor: textColor, insets: insets)
 }
    
    open override func refreshContent(entry: ChartDataEntry, highlight: Highlight)
    {
  setLabel(String(entry.y))
    }
}`
```
Want to create
![banlgrafff](https://user-images.githubusercontent.com/32238897/45034719-eaf3df00-b060-11e8-87d5-ec7974ead41c.png)

**Comment by Bogdan59** [comment]
How to create custom marker with labels?
Now I use BalloonMarker, but it does not fit
Want to create 
![banlgrafff](https://user-images.githubusercontent.com/32238897/45034687-dadbff80-b060-11e8-86a6-825ed5f95f09.png)

**Comment by thierryH91200** [comment]
try to work with

[RectMarker.swift.zip](https://github.com/danielgindi/Charts/files/2349522/RectMarker.swift.zip)
   

```
 let marker = RectMarker(color: #colorLiteral(red: 0.9994240403, green: 0.9855536819, blue: 0, alpha: 1), font: NSFont.systemFont(ofSize: CGFloat(12.0)), insets: NSEdgeInsets(top: 8.0, left: 8.0, bottom: 4.0, right: 4.0))
        marker.chartView = chartView
        marker.minimumSize = CGSize(width: CGFloat(60.0), height: CGFloat(30.0))
        chartView.marker = marker

```



<img width="1788" alt="capture d ecran 2018-09-04 19 07 42" src="https://user-images.githubusercontent.com/6251463/45046231-dc63f280-b075-11e8-90c9-86bc8ab927a1.png">

**Comment by Bogdan59** [comment]
thierryH91200 - Thanks a lot, it works!

**Comment by DevboiDesigns** [comment]
The date is the example does not work
