### ISSUE TITLE
Is it possible to add a vertical label for Y-Axis? Or anyone working on it?

### ISSUE THREAD

**Issue by abhi137** [danielgindi/Charts#3627]
<img width="662" alt="screen shot 2018-09-06 at 6 31 17 pm" src="https://user-images.githubusercontent.com/500999/45193564-6c837280-b203-11e8-838f-f240449fa9cd.png">

## Charts Environment

**Charts version/Branch/Commit Number: 3.1.1 Master**
**Xcode version: 9.4.1**
**Swift version: 4.2**
**Platform(s) running Charts: macOS**
**macOS version running Xcode: 10.14 Beta 9**

**Comment by liuxuan30** [comment]
it's called `gridLine`. We supported that.
