### ISSUE TITLE
where is the code for draw the xAxis and yAxis indicateLine

### ISSUE THREAD

**Issue by milkatgit** [danielgindi/Charts#3628]
![img_2979](https://user-images.githubusercontent.com/25073103/45195353-aeef9280-b289-11e8-9d85-6f87637f58c6.PNG)

**Comment by milkatgit** [comment]
I have seen the drawRect method in ChartViewBase file, But I don't know where the code of draw the xAxis and yAxis
![390aab79-d0ad-4903-9594-ecf766af6d77](https://user-images.githubusercontent.com/25073103/45195486-5c62a600-b28a-11e8-9192-81caf9f68b0e.png)
 line

**Comment by abhi137** [comment]
Look for XAxisRenderer.swift

**Comment by LuoPengFei** [comment]
'if leftAxis.isEnabled
        {
            leftYAxisRenderer.computeAxis(min: leftAxis._axisMinimum, max: leftAxis._axisMaximum, inverted: leftAxis.isInverted)
        }
        
        if rightAxis.isEnabled
        {
            rightYAxisRenderer.computeAxis(min: rightAxis._axisMinimum, max: rightAxis._axisMaximum, inverted: rightAxis.isInverted)
        }
        
        
        if _xAxis.isEnabled
        {
            xAxisRenderer.computeAxis(min: _xAxis._axisMinimum, max: _xAxis._axisMaximum, inverted: false)
        }
        
        xAxisRenderer.renderAxisLine(context: context)
        leftYAxisRenderer.renderAxisLine(context: context)
        rightYAxisRenderer.renderAxisLine(context: context)

        // The renderers are responsible for clipping, to account for line-width center etc.
        xAxisRenderer.renderGridLines(context: context)
        leftYAxisRenderer.renderGridLines(context: context)
        rightYAxisRenderer.renderGridLines(context: context)
        '

**Comment by LuoPengFei** [comment]
`BarLineChartViewBase.swift` 

`if leftAxis.isEnabled
        {
            leftYAxisRenderer.computeAxis(min: leftAxis._axisMinimum, max: leftAxis._axisMaximum, inverted: leftAxis.isInverted)
        }
        
        if rightAxis.isEnabled
        {
            rightYAxisRenderer.computeAxis(min: rightAxis._axisMinimum, max: rightAxis._axisMaximum, inverted: rightAxis.isInverted)
        }
        
        
        if _xAxis.isEnabled
        {
            xAxisRenderer.computeAxis(min: _xAxis._axisMinimum, max: _xAxis._axisMaximum, inverted: false)
        }
        
        xAxisRenderer.renderAxisLine(context: context)
        leftYAxisRenderer.renderAxisLine(context: context)
        rightYAxisRenderer.renderAxisLine(context: context)

        // The renderers are responsible for clipping, to account for line-width center etc.
        xAxisRenderer.renderGridLines(context: context)
        leftYAxisRenderer.renderGridLines(context: context)
        rightYAxisRenderer.renderGridLines(context: context)
        `

**Comment by liuxuan30** [comment]
you mean `renderGridLines`
