### ISSUE TITLE
Help building Charts Demo 

### ISSUE THREAD

**Issue by coop44483** [danielgindi/Charts#3643]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I am new to XCode and MacOS so please forgive the stupid question, but I am stuck.  I have downloaded and unzipped Charts onto the desktop.  When I open Charts.xcworkspace and try to build, I get 29 error messages 
Swift Compiler Error Group
/Users/mac/Desktop/Charts/Source/Charts/Animation/Animator.swift:73:52: Type 'RunLoop' has no member 'Mode'

I also tried to load just the ChartsDemo-macOS with the same results.

I know that I am doing something stupid (or not doing something) but being a NOOB I do not know where to look.

## What did you expect to happen?

I was hoping to see a 'Build Succeeded and be able to run the Demo MacOs program.

## What happened instead?

build fails with 29 error messages 
Swift Compiler Error Group
/Users/mac/Desktop/Charts/Source/Charts/Animation/Animator.swift:73:52: Type 'RunLoop' has no member 'Mode'

## Charts Environment

3.2
Xcode 9.4.1
4.?  I do not know how to discover this.  I just downloaded xcode from Apple a week ago
**Platform(s) running Charts:**
High Sierra

## Demo Project

I am using the project(s) from this github site.

**Comment by cythb** [comment]
Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

**Comment by liuxuan30** [comment]
@cythb be aware that repo still work on Xcode 9.4 only because we don't update that repo *yet*, as the 4.0 branch is a big change for us. The master branch make sure it will work with the latest Xcode, not the old ones. 

If you wake up tomorrow and find 4.0 is on Xcode 10, don't be surprised.

**Comment by imzyf** [comment]
maybe you can use v3.1.1
