### ISSUE TITLE
As of todays update, I am running into this issue. 'common' renamed RunLoopMode.commonModes

### ISSUE THREAD

**Issue by sdevo619** [danielgindi/Charts#3647]
## What did you do?

Updated to new version of Charts on an iOS 12 project by running pod update in terminal

## What did you expect to happen?

no errorrs

## What happened instead?

![screen shot 2018-09-17 at 7 34 57 pm](https://user-images.githubusercontent.com/7008354/45661249-7cc40900-bab1-11e8-8fe1-38fbe856d473.png)

![screen shot 2018-09-17 at 7 42 45 pm](https://user-images.githubusercontent.com/7008354/45661329-ec39f880-bab1-11e8-96c5-7b19c77f9062.png)

**Charts version/Branch/Commit Number:**
**Xcode version:** 10
**Swift version:** 4.1
**Platform(s) running Charts:** 12
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by muzoman** [comment]
Me too

**Comment by srn214** [comment]
在pod 添加

 post_install do |installer|
      
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if target.name == 'Charts'
                  config.build_settings['SWIFT_VERSION'] = '4.2'
                  else
                  config.build_settings['SWIFT_VERSION'] = '4.1'
              end
          end
      end
  end

**Comment by muzoman** [comment]
> 在pod 添加
> 
> post_install do |installer|
> 
> ```
>   installer.pods_project.targets.each do |target|
>       target.build_configurations.each do |config|
>           if target.name == 'Charts'
>               config.build_settings['SWIFT_VERSION'] = '4.2'
>               else
>               config.build_settings['SWIFT_VERSION'] = '4.1'
>           end
>       end
>   end
> ```
> end

Where is this code placed?

**Comment by srn214** [comment]
![image](https://user-images.githubusercontent.com/14295747/45673893-72137d80-bb5e-11e8-8fa9-08d2a544bd8c.png)

**Comment by cythb** [comment]
Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

**Comment by liuxuan30** [comment]
@cythb stop asking people to try 4.0 branch. IT'S NOT FOR PUBLIC. Next time I saw you post like this, I will delete it.

**Comment by liuxuan30** [comment]
Please note, our job is to make sure master branch always work with latest  Xcode and Swift; if you plan to upgrade your EVERY swift library to 4.2, you can take the new code. Otherwise, stick to old Chart library.

**Comment by SURYAKANTSHARMA** [comment]
@srn214 , @muzoman   thanks for solution, Could you please explain a bit more. Is this is setting swift version in build setting to 4.2 but why its working. Any help appreciated.

**Comment by Jovisx** [comment]
i just correct the code with

`forMode: RunLoop.Mode.common`
