### ISSUE TITLE
Type 'RunLoop' has no member 'Mode'

### ISSUE THREAD

**Issue by rajasekharpidikitios** [danielgindi/Charts#3648]
I am trying to use charts for ios app. I am using cocoa pod for dependency setup. After setup i am trying to build the code it throwing compile errors. 

Below I am Adding my Codebase for reference. can anyone help me. thanks in advance.

Charts Environment

**Charts version/Branch/Commit Number: 
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
**macOS version running Xcode:**

## Demo Project
 download that reproduces the issue.
https://github.com/rajasekharpidikitios/Customcharts.git

**Comment by shayneoneill** [comment]
DOesn't appear to exist in the MacOs api either.

**Comment by rajasekharpidikitios** [comment]
> DOesn't appear to exist in the MacOs api either.

I am using iOS domain only.

**Comment by cythb** [comment]
Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

**Comment by AwaisFayyaz** [comment]
> Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

This solution works. I just used the following link and it compiled without any issues.

**Comment by liuxuan30** [comment]
is this solved?

**Comment by rajasekharpidikitios** [comment]
No Not at can please help me out.

**Comment by rajasekharpidikitios** [comment]
> Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

is It 

> Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0

Its not a master Branch.  Even it not working.

**Comment by rajasekharpidikitios** [comment]
> > Please try this version:https://github.com/danielgindi/Charts/tree/4.0.0
> 
> This solution works. I just used the following link and it compiled without any issues.


Its not a master Branch. Even it not working.

**Comment by AwaisFayyaz** [comment]
I DID NOT use pods to install. instead, followed the usage section and it compiled.

https://github.com/danielgindi/Charts#usage

Carefully read the usage section. Let me know if you need any help

**Comment by liuxuan30** [comment]
Guys, 4.0 branch is not for public yet.

Please note, we try to make sure master branch always work with latest Xcode and Swift; if you plan to upgrade your EVERY swift library to 4.2, you can take the new code. Otherwise, stick to old Chart library. 

The new commits for Swift 4.2 will not work with lower versions.

This library hasn't get any new features or updates for quite a while, you are safe to stay on v3.1, or old commit. 

What we did is just to update master and make sure it works with latest Xcode and Swift version.

**Comment by rajasekharpidikitios** [comment]
I am trying to use charts for ios app. I am using cocoa pod for dependency setup. After setup i am trying to build the code it throwing compile errors.

Below I am Adding my Codebase for reference. can anyone help me. thanks in advance.

Charts Environment

**Charts version/Branch/Commit Number:
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
macOS version running Xcode:

Demo Project
download that reproduces the issue.
https://github.com/rajasekharpidikitios/Customcharts.git

**Comment by liuxuan30** [comment]
then check out Chart 3.1. Checking out master is not a good idea all the time.

**Comment by rajasekharpidikitios** [comment]
> is this solved?
I am trying to use charts for ios app. I am using cocoa pod for dependency setup. After setup i am trying to build the code it throwing compile errors.

Below I am Adding my Codebase for reference. can anyone help me. thanks in advance.

Charts Environment

**Charts version/Branch/Commit Number:
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
macOS version running Xcode:

Demo Project
download that reproduces the issue.
https://github.com/rajasekharpidikitios/Customcharts.git

**Comment by rajasekharpidikitios** [comment]
> then check out Chart 3.1. Checking out master and saying it's not working with old tools is not a good idea all the time.

**Charts version/Branch/Commit Number:
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
macOS version running Xcode:

**Comment by AwaisFayyaz** [comment]
@rajasekharpidikitios If you are still struggling to integrate charts in your project. Please follow Along

My Codebase is same as yours. i am using xcode 9.4.1 and swift 4.1

1. Go to release  [3.1.1](https://github.com/danielgindi/Charts/releases/tag/v3.1.1) and Download Source code. Unzip the file. Copy the contents of zip file into root of your project directory.

2. Right click on your project in xcode and click on 'Add files to ....' See the attached pic

![add files](https://user-images.githubusercontent.com/11820112/45749631-a605a600-bc25-11e8-80a2-e9e7def9a842.png). 
File selector window will open

3. Find the folder name "Charts-3.1.1" in root directory of your project. Open it and select "Charts.xcodeproj" file

4. Select your target and select General tab if not selected. Now hit the "+" under the "Embedded Binaries" section, and select the Charts.framework

5. build and enjoy

Let me know if you need help

**Comment by rajasekharpidikitios** [comment]
> 1. 3.1.1

Can i use same steps for xcode 10.0 and swift 4.2

**Comment by rajasekharpidikitios** [comment]
> then check out Chart 3.1. Checking out master and saying it's not working with old tools is not a good idea all the time.

Tanks for reply.

**Comment by OneStromberg** [comment]
@rajasekharpidikitios what was the solution? on Xcode 10?
