### ISSUE TITLE
[3.2.0] Excessive Memory leaks in Swift 4.2 related to LineChartView, not present in 3.1.1 w/Swift 4

### ISSUE THREAD

**Issue by RamblinWreck77** [danielgindi/Charts#3649]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Existing project has charts inside a collection view cell primarily consisting of a LineChartView. 

## What did you expect to happen?

No leaks

## What happened instead?

With no other code changes, the exact same project generates 100's of leaks in Swift 4.2/v3.2.0 and zero in Swift 4.0 / 3.1.1.

The leaks seem to revolve around data items strongly retaining a reference to their parent chart view. Dismissing the page/complete deinit on the UICollectionView works fine, but the more items that go into the chart the more leaks you end up with. 

## Charts Environment

**Charts version/Branch/Commit Number: 3.2.0**
**Xcode version: 10.0**
**Swift version: 4.2**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: 10.13.6**

## Demo Project

-Will Update Tomorrow with sample

**Comment by liuxuan30** [comment]
about memory leak is a bit tricky, you can look at #2772 #2745. Sometimes it's not Charts problem, but swift library's. You need to give detailed logs, graphs to illustrate. 

Also, what I found to make sure the real leak is if you try to pop the current view controller, if chart related objects are still there, that's what you should look into.

**Comment by rajasekharpidikitios** [comment]
can please let me know which version i can use for below configuration.

*Charts version/Branch/Commit Number:
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
macOS version running Xcode:

I hope u can understand my problem.

**Comment by liuxuan30** [comment]
IAxisValueFormatter will create retain cycle if you are not very careful.

**Comment by RamblinWreck77** [comment]
Note: This also occurs in 3.2.1

**Comment by liuxuan30** [comment]
please check if #3680 fixed it

**Comment by liuxuan30** [comment]
thanks for help confirm!

**Comment by RamblinWreck77** [comment]
@liuxuan30 +1, I would love to switch back to normal charts in my podfile. I've been using the fix in production for months.
