### ISSUE TITLE
Module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 

### ISSUE THREAD

**Issue by boatt** [danielgindi/Charts#3651]
module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler: /Users/macmi001/Library/Developer/Xcode/DerivedData/bideyun-ahsowbwhchwotzhbvhqlqexqtynx/Build/Products/Debug-iphonesimulator/Charts/Charts.framework/Modules/Charts.swiftmodule/x86_64.swiftmodule

**Comment by liuxuan30** [comment]
I think you got your answer. module compiled with Swift 4.1.2 cannot be imported by the Swift 4.2 compiler

**Comment by Hcaepllams** [comment]
https://stackoverflow.com/questions/46726077/module-compiled-with-swift-4-0-cannot-be-imported-in-swift-4-0-1

I solved this error by following the voted answer.
