### ISSUE TITLE
Type 'RunLoop' has no member 'Mode'

### ISSUE THREAD

**Issue by rajasekharpidikitios** [danielgindi/Charts#3652]
I am trying to use charts for ios app. I am using cocoa pod for dependency setup. After setup i am trying to build the code it throwing compile errors.

Below I am Adding my Codebase for reference. can anyone help me. thanks in advance.

Charts Environment

**Charts version/Branch/Commit Number:
**Xcode version:9.4.1
**Swift version:swift 4.1
**Platform(s) running Charts: ios
macOS version running Xcode:

Demo Project
download that reproduces the issue.
https://github.com/rajasekharpidikitios/Customcharts.git

**Comment by liuxuan30** [comment]
dup.
