### ISSUE TITLE
Incorrect behavior for AxisBase.axisMaxLabels

### ISSUE THREAD

**Issue by UweMeier** [danielgindi/Charts#3656]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

```
chartView.rightAxis.axisMinLabels = 10
chartView.rightAxis.axisMaxLabels = 15
```

## What did you expect to happen?

`axisMinLabels` to be 10
`axisMaxLabels` to be 15

## What happened instead?

`axisMinLabels == 15`
`axisMaxLabels == 15`

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.0
**Xcode version:** 10.0 (10A255)
**Swift version:** 4.2
**Platform(s) running Charts:** iOS 11

## Solution

looks like axisMaxLabels' didSet has some erroneous code inside:

https://github.com/danielgindi/Charts/blob/5087a04bbefc9f15995113954ce217bbfb445577/Source/Charts/Components/AxisBase.swift#L222-L224

Shouldn't it be `axisMaxLabels = axisMaxLabels > 0 ? axisMaxLabels : oldValue` in Line 223?

**Comment by liuxuan30** [comment]
Seems a bug. Would you mind a fix and file a PR?
