### ISSUE TITLE
Bar Chart with horizondal scroll on clicking button.

### ISSUE THREAD

**Issue by ais9226** [danielgindi/Charts#3660]
Need to add a button on sides of x axis (like the arrow in picture shown below)  so that on clicking them scroll of graph should happen. As shown in fig, graph for rest of months should be dispalyed on clicking the arrow button.
![screen shot 2018-09-21 at 5 49 51 pm](https://user-images.githubusercontent.com/43202283/45880836-ea7c7780-bdc6-11e8-88ae-065bfed65a97.png)

**Comment by muzammilsahib** [comment]
hi anyone implemented the above scroll options
