### ISSUE TITLE
Getting error after updating XCode to 10 from 9.4 

### ISSUE THREAD

**Issue by lekhakmukesh** [danielgindi/Charts#3661]
> ℹ I updated the Xcode and now I am getting an error in Charts Library. 

I have updated the Chart to v3.2 using pod update and still, I am getting an error like this please check the screenshot. 

** Screenshot: https://imgur.com/a/bDu96UF

I am using Charts v3.2.0

**Comment by gregacucnik** [comment]
Changing Charts pod Swift language version from 4 to 4.2 and cleaning build folder fixed it for me.

**Comment by lekhakmukesh** [comment]
> Changing Charts pod Swift language version from 4 to 4.2 and cleaning build folder fixed it for me.

I did it but still the same issues

**Comment by sdevo619** [comment]
I am still having the same issue, even after cleaning the build. I have even completely reinstalled both Xcode and the newest version of CoocaPods, which is currently 1.6(beta) I believe. Please advise. If I need to go back to the non beta Cocoa Pods version I will, but I don't believe it fixes this issue though.

![screen shot 2018-09-25 at 9 30 07 am](https://user-images.githubusercontent.com/7008354/46028501-9bc02d80-c0a5-11e8-8377-bed7edc52dbd.png)

**Comment by kienvanba** [comment]
I'm having the same issue, does anyone have any solution for this yet?

**Comment by wangxumin** [comment]
I'm having the same issue

**Comment by RPGLiker** [comment]
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'

**Comment by liuxuan30** [comment]
master should  be the same as 3.2.0.

Is this an issue of pod itself? Has anyone tried 
>Changing Charts pod Swift language version from 4 to 4.2 and cleaning build folder fixed it for me.

**Comment by kienvanba** [comment]
> Changing Charts pod Swift language version from 4 to 4.2 and cleaning build folder fixed it for me.

Can somebody show me how to do this?
sorry for the dump question, i'm an iOS newbie. 
Thanks in advance.

**Comment by RPGLiker** [comment]
Charts 3.1.0
Pods -> build settings -> swift language version -> swift 4

Wait for the author to update it.

**Comment by petester42** [comment]
Try updating to the last est cocoapods and see if that fixes your problem. I did have problems publishing 3.2 but updating to the beta of cocoapods fixed my issues.

**Comment by petester42** [comment]
Apart from that try the normal stuff. Delete derived data, clean the project and rebuild. You could also delete all your pod stuff from your folder and doing `pod install` again

**Comment by djbe** [comment]
Hi,

The podspec is missing the `swift_version` key, which should be set to `4.2`. And to ensure that works, you may also want to add a minimum `cocoapods_version`, so:
```ruby
  s.swift_version = '4.2'
  s.cocoapods_version = '>= 1.4.0'
```

See here for example:
https://github.com/SwiftGen/StencilSwiftKit/blob/master/StencilSwiftKit.podspec#L19

**Comment by djbe** [comment]
Also note that the `.swift-version` file has been deprecated by CocoaPods (since 1.4.0).

**Comment by petester42** [comment]
Thanks for the info!

**Comment by npabion** [comment]
While waiting for the podspec to be updated, in my podfile I use:

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Set missing swift version for Charts
            if ['Charts'].include? target.name
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end
```

**Comment by petester42** [comment]
Due to signing issues related to (https://github.com/CocoaPods/CocoaPods/issues/7708) we are requiring cocoa pods 1.6.0.beta.1 or greater.

**Comment by yuanhh90** [comment]
When I updated Xcode 12 and Charts 3.2.0, I did not finded some properties and some classes that in Charts 3.1.1 had. For example, the property drawRoundedBarEnabled, the class ChartBalloonMarker. How can i fixed?

**Comment by petester42** [comment]
3.2.1 release with these changes

**Comment by yuanhh90** [comment]
Thanks!

**Comment by frogg** [comment]
Nothing worked. Then, out of frustration, I deleted my `Pod` directory and ran `pod install` again.
Now it works again 🥵

**Comment by petester42** [comment]
The joys of dependency management. Glad you found a solution!
