### ISSUE TITLE
CombinedChartView's  candleData don't display in v3.2.0

### ISSUE THREAD

**Issue by Michael-Du** [danielgindi/Charts#3662]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I use CombinedChartView, but candleData don't display

## What did you expect to happen?

ℹ CombinedChartView's  candleData display

## Charts Environment

**Charts version Number:*3.2.0*
**Xcode version:*10.0*
**Swift version:*4.2*
**Platform(s) running Charts:*iOS*
**macOS version running Xcode:*10.14*

## Demo Project

ℹI find this problem in https://github.com/danielgindi/Charts/tree/master/ChartsDemo-iOS/Swift

**Comment by liuxuan30** [comment]
Are you able to reproduce with ChartsDemo?

**Comment by Michael-Du** [comment]
> Are you able to reproduce with ChartsDemo?

You can find this bug in your ChartsDemo
![screen shot 2018-09-27 at 10 31 14 am](https://user-images.githubusercontent.com/17307261/46120176-0c4f8180-c241-11e8-842f-d1ef84256f12.png)

**Comment by vcmilani** [comment]
I have same problem here, with example and my code!

**Comment by boatt** [comment]
I have same problem here

**Comment by petester42** [comment]
fixed by #3664
