### ISSUE TITLE
Failed to verify bitcode in Charts.framework

### ISSUE THREAD

**Issue by EricM-VR** [danielgindi/Charts#3663]
I try to distribute an Ad Hoc app including charts framework.

If I select the "Rebuild from bitcode" option, I get the error message => "Failed to verify bitcode in Charts.framework/Charts"

If I de-select this option, I get this error message => "Code signing "Charts.framework" failed."
In the logs, I have

            code = 0;
            description = "Failed to verify bitcode in Charts.framework/Charts:\nerror: Cannot extract bundle from /var/folders/0h/41gh6_zn0hn7j8lngfm_mqlh0000gn/T/IDEDistributionOptionThinning.csC/Payload/Travel.app/Frameworks/Charts.framework/Charts (i386)\n\n";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";

It happens since I moved to Xcode 10.
I try to rebuild from Carthage (carthage update --platform iOS), reinstalled the framework, but issue is still the same.

Did anyone experienced the same behavior ?

Thanks a lot
Eric

**Comment by liuxuan30** [comment]
This is relatively new to us. We didn't receive many bitcode issue, nor we paid attention to it.

I checked the framework build settings, nothing for bitcode. The ChartsDemo build settings do have bitcode settings, and it's enabled.

Why you have to select "Rebuild from bitcode"? If you uncheck it, it should works fine, I don't see others complain about Code signing "Charts.framework" failed a lot.

BTW, I do remember one issue from https://github.com/Carthage/Carthage/issues/1619 saying you shouldn't check code sign for the framework. And, if you are using carthage, do remember check out their homepage for detailed instructions. There are some scripts like `/usr/local/bin/carthage copy-frameworks` to run.

If you are not sure, refer ChartsDemo settings and try to build it.

**Comment by petester42** [comment]
I have no idea why this would be but we don't sign the framework in our project so it would use your app's signing.

**Comment by vamositamas** [comment]
Hi. I have same error (Code signing "Charts.framework" failed.), but I didn't select the "Rebuild from bitcode" option. I use XCode 10. How can I solve this issue? Thanks.

**Comment by prgorasiya** [comment]
Facing the same issue, can't achieve the binary.
Any solution?

**Comment by vamositamas** [comment]
Yes. If you include the Charts source files direct your project without Charts.framework, then will works the "Archive" function without error message. This isn't not really elegant solution but deal with it.

**Comment by petester42** [comment]
Seems like a carthage problem. Are you at the latest version https://github.com/airbnb/lottie-ios/issues/639

**Comment by petester42** [comment]
Ok. I found the solution. You have to follow the steps here if you didn't (https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos). I got the same issue as you without doing so.

**Comment by shafqat-muneer** [comment]
Issue exists if we use Carthage. If i use cocoa pod then will it work? Anyone experience it?
