### ISSUE TITLE
DrawValuesEnabled variable unreachable (Swift 4.2)

### ISSUE THREAD

**Issue by Jordanwayne** [danielgindi/Charts#3665]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I wanted to implement PieCharts into my app without many of the labels associated. I tried many of the available functions but couldn't find any that would turn off the values (not just the value names) on the pie chart itself. Looking into the library, I found that if I set drawValues on line 335 of Source > Charts > Renderers > PieChartRenderer.swift to false (overriding dataSet.isDrawValuesEnabled) it achieves the solution I was looking for. 

I imagine there is probably a function call that was meant to achieve this for the user but it appears in Swift 4.2 it isn't reachable anymore. I'm not sure of this fix but I thought I'd bring it to your attention.

## What did you expect to happen?

I thought that by turning off drawEntryLabelsEnabled, it would disable both the label and the value from the pie chart.

## What happened instead?

The value label remained and there didn't seem to be a function call that would disable them.

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:**
**Swift version:**
**Platform(s) running Charts:**
**macOS version running Xcode:**

**Comment by petester42** [comment]
`drawValuesEnabled` would be the property that you would need to change but it does seem that setting that to `false` still keeps the label. Don't really know if this is a bug though. @liuxuan30 what do you think? Should we add a new option for the label or just use `isDrawValuesEnabled` for both value and label?

**Comment by petester42** [comment]
To turn off both value and labels you can do the following: 
```
chartDataSet.drawValuesEnabled = false
chart.drawEntryLabelsEnabled = false
```

**Comment by Jordanwayne** [comment]
Ok thanks, I'll try that instead.

**Comment by liuxuan30** [comment]
I don't think it's a bug
```swift
                let drawXOutside = drawEntryLabels && xValuePosition == .outsideSlice
                let drawYOutside = drawValues && yValuePosition == .outsideSlice
                let drawXInside = drawEntryLabels && xValuePosition == .insideSlice
                let drawYInside = drawValues && yValuePosition == .insideSlice
```
`drawEntryLabels` seems only affect x values, if you want to turn off value labels, it should be `drawValuesEnabled = false`.
