### ISSUE TITLE
PieChartView settings color is Invalid 

### ISSUE THREAD

**Issue by AflyingApple** [danielgindi/Charts#3668]
1. What did you do?
I want to change the color of the text individually and distinguish percentages of colors and text colors.

2. What did you expect to happen?

Can not set the text color alone, invalid

Like this（DEMO）：
#import "PieChartViewController.h"
PieChartViewController

    _chartView.entryLabelColor = UIColor.blackColor;
    _chartView.entryLabelFont = [UIFont fontWithName:@"HelveticaNeue-Light" size:12.f];

    [data setValueFont:[UIFont fontWithName:@"HelveticaNeue-Light" size:11.f]];
    [data setValueTextColor:UIColor.whiteColor];

![5eba502a-7956-4e24-83b0-4c38ef05fe3e](https://user-images.githubusercontent.com/26787047/46242411-73b13100-c3fb-11e8-81c2-42b8954dae52.png)

3. Charts Environment

**Charts version Number:3.2.0
**Xcode version:10.0
**Swift version:4.2
**Platform(s) running Charts:iOS
**macOS version running Xcode:10.14

**Comment by liuxuan30** [comment]
```swift
                        {
                            ChartUtils.drawText(
                                context: context,
                                text: pe!.label!,
                                point: CGPoint(x: labelPoint.x, y: labelPoint.y + lineHeight),
                                align: align,
                                attributes: [
                                    NSAttributedString.Key.font: entryLabelFont ?? valueFont,
                                    NSAttributedString.Key.foregroundColor: entryLabelColor ?? valueTextColor]
```
you shouldn't set two color at the same time.
