### ISSUE TITLE
ChartData ValueTextColor can not achieve a variety of colors

### ISSUE THREAD

**Issue by AflyingApple** [danielgindi/Charts#3669]
## What did you expect to happen?

I want to set many colors for labels.

## What happened instead?

But no method is found, but the Android framework（MPAndroidChart） can be implemented.

## Charts Environment

**Charts version Number:3.2.0
**Xcode version:10.0
**Swift version:4.2
**Platform(s) running Charts:iOS
**macOS version running Xcode:10.14

## Demo Project

![a022b921-32bc-4b63-ab2d-a210178b8be3](https://user-images.githubusercontent.com/26787047/46243054-1076cd00-c402-11e8-8ce5-1fe2bc21e0b6.png)

![3f491ea6-bf8c-493f-878e-81a8ace0e082](https://user-images.githubusercontent.com/26787047/46243056-14a2ea80-c402-11e8-92ca-d037eb05f438.png)

**Comment by liuxuan30** [comment]
```swift
    /// - returns: The color at the specified index that is used for drawing the values inside the chart. Uses modulus internally.
    open func valueTextColorAt(_ index: Int) -> NSUIColor
    {
        var index = index
        if index < 0
        {
            index = 0
        }
        return valueColors[index % valueColors.count]
    }
```
