### ISSUE TITLE
Memory leaks were detected also in the demo project

### ISSUE THREAD

**Issue by JunsW** [danielgindi/Charts#3671]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Displaying pie chart, line chart, horizontal bar chart in my project.

## What did you expect to happen?

No memory leak. 

## What happened instead?
Massive memory leaks were found when I used instruments to check my project that contains lots of different charts.
The similar leaks were found when I used instruments to check the demo project.

Those leaks were found around the initialization of `ChartViewBase`, `DefaultValueFormatter ` and `ChartDataEntry`.
The rest seems to be related to the data set.

**Demo Leaks:** 
<img width="991" alt="demo_leaks_backtree" src="https://user-images.githubusercontent.com/6113815/46252706-44540000-c49f-11e8-9fe0-8a0d35715c8c.png">
<img width="1015" alt="demo_leaks_calltree" src="https://user-images.githubusercontent.com/6113815/46252709-44540000-c49f-11e8-8c8d-469f1d9a8b4f.png">
**My Project Leaks:** 
<img width="1003" alt="myproject_leaks_calltree" src="https://user-images.githubusercontent.com/6113815/46253707-5ccf1500-c4b5-11e8-964c-9dc632b33a0d.png">

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.0 (Mine ) / 3.1.1 (Demo)
**Xcode version:** Version 10.0 (10A254a)
**Swift version:** 4.2 (Mine) / 4.0 (Demo)
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.13.6

## Demo Project

Leaks should be caught after randomly clicked several charts in the demo list.

**Comment by StefaniOSApps** [comment]
me@same issue ...

**Comment by RamblinWreck77** [comment]
I had to roll back to 3.1.1 after testing out 3.2.0 because I found the same problem.

**Comment by liuxuan30** [comment]
please check if #3680 fixed it
