### ISSUE TITLE
CandleStickChartRenderer drawDataSet method does not work with CombinedChartView

### ISSUE THREAD

**Issue by smwallace** [danielgindi/Charts#3673]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Created a CombinedChartView with a CandleStickChartRenderer to draw the candlesticks.  

## What did you expect to happen?

ℹ I expected the candle sticks to be drawn in the CombinedChartView.  

## What happened instead?

ℹ No candle sticks were drawn. The drawDataSetMethod incorrectly assumes that the chart is a CandleStickChartView, and in this case the chart is a CombinedChartView, so the drawDataSetMethod returns without drawing any candle sticks.

## Charts Environment

**Charts version/Branch/Commit Number:** Version 3.2.0, installed via CocoaPods
**Xcode version:** Xcode Version 10.0 (10A255)
**Swift version:** Swift 4.0
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** macOS High Sierra 10.13.6 (17G65)
[Broken drawDataSet Method.txt](https://github.com/danielgindi/Charts/files/2436089/Broken.drawDataSet.Method.txt)

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
I have attached a file that shows the changes I made to fix the issue.

**Comment by liuxuan30** [comment]
seems it has been fixed recently.
