### ISSUE TITLE
Getting issues after pod update.

### ISSUE THREAD

**Issue by hadwanihardik** [danielgindi/Charts#3677]
I just updated cocoapod  today to add new library. But as soon as I updated cocoa pods it started showing me errors in chart library. Compile time errors as attached in screen shot.

## What did you do?

Updated cocoa pod "Pod update"

## What did you expect to happen?
Must be compile and run properly.
## What happened instead?
Compile time error as per attached screenshot.

## Charts Environment

![screen shot 2018-10-03 at 12 49 13 pm](https://user-images.githubusercontent.com/5634693/46395705-d875cf80-c70a-11e8-8088-91653187412e.png)
**Xcode version:** 9
**Swift version:**  3
**Platform(s) running Charts:** ios

**Comment by hadwanihardik** [comment]
I know this that it has updated to 4.2
I don't want to update my project to swift 4.2 as of now. So any other chances?

**Comment by jobika** [comment]
not you project buddy :) just the pod swift version

**Comment by petester42** [comment]
Try version 3.2.1. Should be better now.
