### ISSUE TITLE
Pie Chart - Slices are not drawn and values are overlapping

### ISSUE THREAD

**Issue by StanislavGg** [danielgindi/Charts#3679]
Hello, im using the latest version of the framework and xCode version: 10.0.

**What did you do?**

Im populating values into a pie chart.

**What did you expect to happen?**

I expected to be able to draw slices for every value in the dataSet, with applied sliceSpace and without them overlapping.

**What happened instead?**

In case some of the values are lower than (for example) 0.02% of the total value, no slices are drawn for them, no slice space is applied and they overlap. If the values don't have such huge difference everything is being displayed just fine.

Is there a way to fix this, or am i doing something wrong?

Thanks in advance.
![img_0016](https://user-images.githubusercontent.com/28005163/46468890-71275080-c7da-11e8-9d89-2ecf8f68d46f.jpg)

**Comment by nikhilmaurya10** [comment]
I have the same problem. Additionally I can't figure out a way to hide labels which are used to create PieChartDataEntry, this label is used in legends as well as the marking on the slice. I just want to show the Y axis value on the slice.

**Comment by liuxuan30** [comment]
it's never easy when you have a very small value and you need to draw two labels around the same position. You can choose to hide small value anyway. But I don't have a good idea how to avoid overlap. Need your help if you can come up with any solutions and file a PR.
