### ISSUE TITLE
Getting Errors in Xcode 9.2

### ISSUE THREAD

**Issue by TusharManiyar** [danielgindi/Charts#3684]
Hello,

 I am Getting Build Error when I am trying to run project .

Can any one help me ? I am uploading screen shots so you can check errors and Xcode version 9.2 . 

Thanks

![screen shot 2018-10-10 at 12 00 07 am](https://user-images.githubusercontent.com/5292076/46690358-b48d1f00-cc1f-11e8-87fd-bcd6f5c85d2c.png)
![screen shot 2018-10-10 at 12 00 16 am](https://user-images.githubusercontent.com/5292076/46690360-b48d1f00-cc1f-11e8-8ee1-c3d38f4dabec.png)

**Comment by liuxuan30** [comment]
check release page and pick a version whatever suits your env.
