### ISSUE TITLE
XCode 10 app crash.

### ISSUE THREAD

**Issue by OlionCompany** [danielgindi/Charts#3686]
After update Xcode and Charts, app crashes every time in this place:
BarLineChartViewBase.draw(_:) ->  BarChartRenderer.drawData(context:) -> HorizontalBarChartRenderer.drawDataSet(context: context, dataSet: set as! IBarChartDataSet, index: i) -> BarChartRenderer.createAccessibleElement(...) -> let stackLabel = dataSet.stackLabels[idx % stackSize]

![screenshot 2018-10-11 at 11 56 45](https://user-images.githubusercontent.com/2388327/46793524-97a33980-cd4e-11e8-8caf-f750bfc2063c.png)

"Charts was compiled with optimization - stepping may behave oddly; variables may not be available."

**Comment by liuxuan30** [comment]
did you touch anything so it's out of bound? I don't see other people complain this.

**Comment by petester42** [comment]
Update to the latest version (3.2.1) this should be fixed in that one. Let us know if you still have problems.
