### ISSUE TITLE
how to make a combine chart (line chart +  bar chart) with leftAxis taking the top half area of the combined graph and right axis taking the bottom half 

### ISSUE THREAD

**Issue by amirsiddi** [danielgindi/Charts#3690]
## What did you do?

I want to make a combine chart (line chart +  bar chart) of stock price history where stock price is shown in line chart and number of shares traded as bar chart. The line chart needs to be in top half of the graph, and bar chart needs to be on bottom half. Sort of typically how stock historical prices are usually shown. Images are provided of what i want.

## What did you expect to happen?

[this is something i want where bar chart takes the bottom half of the combined chart and line charts takes the upper half](https://firebasestorage.googleapis.com/v0/b/testing-project-e5ae9.appspot.com/o/desired%20combine%20chart.png?alt=media&token=6960cf55-a3f6-4734-a285-0e56d71c0e72)

## What happened instead?

[This is what i have been able to get ](https://firebasestorage.googleapis.com/v0/b/testing-project-e5ae9.appspot.com/o/what%20i%20get.png?alt=media&token=e663dc3d-17a9-4500-9780-cb4aca6ac7ba)

## Charts Environment

**Charts version/Branch/Commit Number:**
Charts-Demo-iOS-Swift
**Xcode version:**
10
**Swift version:**
4
**Platform(s) running Charts:**
**macOS version running Xcode:**
High Sierra
## Demo Project
Yes

**Comment by liuxuan30** [comment]
check out charts demo for combined chart.
