### ISSUE TITLE
How to draw a line chart in sections?

### ISSUE THREAD

**Issue by CHENDONGY** [danielgindi/Charts#3706]
## What did you do?
I want to hide the left and right sides of the middle line in a line chart.

Such an effect
![wx20181023-115125](https://user-images.githubusercontent.com/26021469/47334865-10918200-d6bb-11e8-962b-23bdaa731d04.png)

## What happened instead?

I looked at all but didn't find a good way. How do you achieve this effect?

## Charts Environment

Charts version: 3.2
Swift version: 4.2

**Comment by liuxuan30** [comment]
use multiple data sets for line segments.
