### ISSUE TITLE
[Feature request] Continue line chart beyond x-axis limits

### ISSUE THREAD

**Issue by patLoeber** [danielgindi/Charts#3708]
Hi,

would be nice to have an easy option to continue the line chart beyond the x-axis limits.

At the moment, the line stops at the first/last data point (first pic).
But instead, line the line should continue beyond the limits (second pic).
I can make a workaround by changing the viewportOffsets, but then I also need dataPoints with 0 for the first and last point, which produces unwanted circles and axis labels at this position.

Thanks!

![bildschirmfoto 2018-10-23 um 23 18 12 2](https://user-images.githubusercontent.com/41892138/47392043-b248bb80-d71b-11e8-8067-38eb143f2abe.png)
![bildschirmfoto 2018-10-23 um 23 05 02 2](https://user-images.githubusercontent.com/41892138/47392048-b4ab1580-d71b-11e8-8055-95242d389339.png)

**Comment by liuxuan30** [comment]
well... I don't think it should be us to add some more 'data' to continue the line. Instead, it should be you. If you want to continue, you can simply add some more data and manually set the axisMaximum to hide it, so it looks like what you said.
