### ISSUE TITLE
xAxis grid line in-between bar rather than center of bar

### ISSUE THREAD

**Issue by chungfk** [danielgindi/Charts#3713]
Hi, trying out the demo for bar chart, I can see that the xAxis grid line are at the centre of the bar. 

Is it possible for it to be situated in-between each bar, much like grouped bar chart. Since I'm only using 1 data set, so its not suitable to use grouped bar chart.

<img width="329" alt="screen shot 2018-10-25 at 11 00 08 am" src="https://user-images.githubusercontent.com/2288909/47473585-d0aad600-d845-11e8-83cc-f0b8d0e04203.png">

**Comment by liuxuan30** [comment]
but the x value is the center of the bar. But you could override the x axis renderer to shift the grid line.

for multiple bars, the trick is described:
```swift
    /// Groups all BarDataSet objects this data object holds together by modifying the x-value of their entries.
    /// Previously set x-values of entries will be overwritten. Leaves space between bars and groups as specified by the parameters.
    /// Do not forget to call notifyDataSetChanged() on your BarChart object after calling this method.
    ///
    /// - parameter the starting point on the x-axis where the grouping should begin
    /// - parameter groupSpace: The space between groups of bars in values (not pixels) e.g. 0.8f for bar width 1f
    /// - parameter barSpace: The space between individual bars in values (not pixels) e.g. 0.1f for bar width 1f
    @objc open func groupBars(fromX: Double, groupSpace: Double, barSpace: Double)
```
