### ISSUE TITLE
Draw Line chart for non linear X-axis

### ISSUE THREAD

**Issue by shashidhar34** [danielgindi/Charts#3717]
## What did you do?
Trying to plot the line chart with non linear x-axis scale. The sample data set it
(5,100)
(10,200)
(15,100)
(10, 50)
(5, 100)

## What did you expect to happen?
The result of the data should be drawn as a Rhombus.

## What happened instead?
No line is drawn on the chart. Does the Charts framework expect the x-axis values to be always sorted in ascending order?

## Charts Environment

**Charts version/Branch/Commit Number:** 3.0.5
**Xcode version:** 10.0
**Swift version:** 4.0
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.13.6

**Comment by liuxuan30** [comment]
Yes, should be sorted
