### ISSUE TITLE
The `open var noDataTextAlignment: NSTextAlignment = .left` is missing the `@objc` so it's not exposed in Objective C.

### ISSUE THREAD

**Issue by Pranoy1c** [danielgindi/Charts#3719]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

https://github.com/danielgindi/Charts/pull/3199 provides text alignment for the noDataText. However it's missing the @objc and hence not exposed in Objective C Project.

## What did you expect to happen?

Please add the `@objc` before `open var noDataTextAlignment: NSTextAlignment = .left`.

## What happened instead?

`noDataTextAlignment` is not available in Objective C project.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.1
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running Charts:** iOS 12

**Comment by liuxuan30** [comment]
@jjatie please have a quick check.
@Pranoy1c maybe you could file the PR together, if it's valid.

**Comment by hiralnaik** [comment]
You can create helper class and method and expose in Objective-C until they fix in actual library. 

```
@objc class ChartHelper: NSObject {
     @objc static func setChartAlignment(alignment: NSTextAlignment, forChart chartview: HorizontalBarChartView) {
        chartview.noDataTextAlignment = alignment
    }
}
```

**Comment by liuxuan30** [comment]
so we should have @objc right?

**Comment by hiralnaik** [comment]
@liuxuan30 yes please. Need to add @objc for `noDataTextAlignment`
