### ISSUE TITLE
Align both right and left axis in the same line

### ISSUE THREAD

**Issue by DenZuck** [danielgindi/Charts#3720]
## What did you do?

I have a line chart with left and right axises with different range (for example left range is [0..200] and right range is [0..900]).

## What did you expect to happen?

I want right and left axis labels aligned to the same line.

## What happened instead?

Right axis labels are not aligned with left axis labels.

![image](https://user-images.githubusercontent.com/7376037/47623333-a3de1380-db10-11e8-85d5-3210b66b1362.png)

## Charts Environment

**Charts version/Branch/Commit Number: 3.0.5
**Xcode version: 9.2
**Swift version: 4.0
**Platform(s) running Charts: iOS 12
**macOS version running Xcode: 10.13.6

## Demo Project

You can reproduce the issue in your demo: LineChart2ViewController, setting 
`rightAxis.axisMinimum = 0.0; `
instead of 
`rightAxis.axisMinimum = -200.0; `

**Comment by liuxuan30** [comment]
Try out 
```swift
    @objc open func setLabelCount(_ count: Int, force: Bool)
    {
        self.labelCount = count
        forceLabelsEnabled = force
    }
```

**Comment by DenZuck** [comment]
That's not what I want. Setting a fixed number of lines I lose the granurality and I don't like how zoom and pan works in this situation.



![image](https://user-images.githubusercontent.com/7376037/47878157-e4de6c80-de1d-11e8-98d0-7f0e7dbb6927.png)

**Comment by liuxuan30** [comment]
well either you stick to the same line or use same range/fixed count for the axis.
Imagine yourself if you have two different ranges for left and axis, how can you make sure the interval is fixed and at the same line.
