### ISSUE TITLE
When using CombinedChartView, CandleChartData cannot be displayed

### ISSUE THREAD

**Issue by huhghg** [danielgindi/Charts#3729]
The latest version -（3.2.1），When using CombinedChartView，Other types of graphs can be displayed，But CandleChartData cannot be displayed。 3.1.1 version can be！

**Comment by JiaLcrown** [comment]
I also met this problem, It seems like that when you use cocoapods to import Charts, the code is different from the code in Samples

**Comment by kkongchi5** [comment]
+1

**Comment by andysharp** [comment]
Agree with this issue.  Seems to be caused in CandleStickChartRenderer:drawDataSet.  The guard assumes that the dataProvider is a CandleStickChartView which is will not be when you are using a CombindChartView.

**Comment by liuxuan30** [comment]
it should be fixed already in master.

**Comment by lh948** [comment]
I also met this problem.but has been resolved in master,thank you
