### ISSUE TITLE
Different colors for above and below 0 when filling a Line Chart

### ISSUE THREAD

**Issue by erickva** [danielgindi/Charts#3733]
I love that when you fill the Line Chart it automatically separates what is below and above 0 in the Y axis.
Is there a way to use different colours for above and below 0?
<img width="582" alt="screen shot 2018-11-06 at 9 47 14 pm" src="https://user-images.githubusercontent.com/7539409/48059619-cad1cf00-e20d-11e8-9716-7ab783c8b994.png">

**Comment by liuxuan30** [comment]
you have to override the methods I suppose.

**Comment by pepejeria** [comment]
@liuxuan30 what methods would that be?
