### ISSUE TITLE
Bar Chart Drawing is wrong without setting axisminimum

### ISSUE THREAD

**Issue by laurentmorvillier** [danielgindi/Charts#3751]
## What did you do?

Hello, I've built the following graph using iOS Charts and this dataset:
<img width="312" alt="d1" src="https://user-images.githubusercontent.com/3283998/48767609-6ad03380-ecb7-11e8-9a0d-08f05a57119e.png">

Here is what I get with my current code:
![g2](https://user-images.githubusercontent.com/3283998/48767179-6e16ef80-ecb6-11e8-96fc-0e70c48afd12.png)
The selection selects the correct value but all bars have the same size

## What did you expect to happen?

Now if I add the following line:
self.leftAxis.axisMinimum = -1140.0

The chart is correctly drawn:
![g1](https://user-images.githubusercontent.com/3283998/48767183-71aa7680-ecb6-11e8-8b1f-b13d95c797ea.png)

Are we expected to dynamically set the axisMinimum at all times? Graphs with positive and negative are correctly drawn, but it looks like positive only dataset or negative only datasets requires an axisMinimum.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.1
**Xcode version:** 10
**Swift version:** 4.2
**Platform(s) running Charts:**
**macOS version running Xcode:**

**Comment by zhangzhang711** [comment]
the demo don’t set axisMinimum is ok.i copy demo into my project, it dosen’t work,i don’t understand

**Comment by zhangzhang711** [comment]
i found solution，copy demo charts source cover your project source,it,ok

**Comment by laurentmorvillier** [comment]
I reproduce the issue in AnotherBarChartViewController, projects attached

    func setDataCount(_ count: Int, range: Double) {
        
        var yVals: [BarChartDataEntry] = []
        let values: [Double] = [-90, -700, -130, -150, -565, -550, -1140]
        for (i, v) in values.enumerated() {
            yVals.append(BarChartDataEntry(x: Double(i), y: v))
        }
        
//        let yVals = (0..<count).map { (i) -> BarChartDataEntry in
//            let mult = range + 1
//            let val = Double(arc4random_uniform(UInt32(mult))) + mult/3
//            return BarChartDataEntry(x: Double(i), y: val)
//        }


[ChartsDemo-iOS.zip](https://github.com/danielgindi/Charts/files/2603645/ChartsDemo-iOS.zip)

**Comment by liuxuan30** [comment]
this should be tested already with recent fix. have you called `chartView.dataSetChanged` after you call `self.leftAxis.axisMinimum = -1140.0`?

**Comment by liuxuan30** [comment]
sorry it's a bit confusing about your issue. I will take a look

**Comment by liuxuan30** [comment]
Hey, I grabbed your code from Another Bar Chart, it's drawing fine:
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4375169/48931724-d3771480-ef32-11e8-8d85-48c35cff00bb.png">

I guess you need to update your library. We recently had a fix about negative bars, not sure if the bug impact you as well, but currently it's drawing fine.

**Comment by laurentmorvillier** [comment]
Hey liuxuan30, thanks for your help. Updating did fix the problem!
May I ask why don't you bump the version after fixes? This could help avoiding such situation

**Comment by liuxuan30** [comment]
we had a release already. but we usually push a new version when Xcode require changes, or we had major updates. just bug fixes are not enough for a release I suppose.

**Comment by liuxuan30** [comment]
my advice would be use source code directly; it's easier to change. if you use pods or carthage, no problem, but fixing issues would be harder compared to source code
