### ISSUE TITLE
this counter will make your app being crash in particular case

### ISSUE THREAD

**Issue by Vaianaa** [danielgindi/Charts#3752]
//my granularity is setGranularity(5);
                    //this is my problem and i don't know why. so, i have to make the counter start from zero
                    //like this                
                    counter++
                    int c = counter - 1;
                 
_Originally posted by @Vaianaa in https://github.com/danielgindi/Charts/issues/1742#issuecomment-439580240_

**Comment by liuxuan30** [comment]
reopen if you can explain.
