### ISSUE TITLE
Chart spacing between xAxis Labels

### ISSUE THREAD

**Issue by yassine112** [danielgindi/Charts#3755]
**I try to personalize the space between the labels of xAxis in iOS Charts.**
I fill my graph with a random size data. and i want to make sure the space between each label.

<img width="329" alt="capture d ecran 2018-11-22 a 09 35 56" src="https://user-images.githubusercontent.com/15075583/48891015-3a60d480-ee32-11e8-8a0c-77612d7034d2.png">

**Comment by liuxuan30** [comment]
it seems fixed already.
