### ISSUE TITLE
Is it possible to make some gaps on a same line plot?

### ISSUE THREAD

**Issue by kocharyanvahe** [danielgindi/Charts#3765]
Dear Daniel,

I'd like to know is it possible to make an empty plots for some points?
Also, I'd like to know can I colorise the same line plot. (E.g. starting with red colour then the same line will change it's colour to black colour or clear colour)?
Like here in photo
![graph](https://user-images.githubusercontent.com/33868040/49338769-5d0f9c00-f62f-11e8-90e8-8cb29fea8e24.png)

**Comment by liuxuan30** [comment]
use two datasets can solve.
