### ISSUE TITLE
Xcode 10.1  pod install Charts  open project error!!!

### ISSUE THREAD

**Issue by akwynn** [danielgindi/Charts#3769]
when I pod install Charts and open project, xcode10.1 show warning as follow:

The target “Charts” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

please help me!

**Comment by liuxuan30** [comment]
You have the error msg and explained to you. use latest ones.

**Comment by akwynn** [comment]
Thanks!
