### ISSUE TITLE
Crash on the function isDrawingValuesAllowed

### ISSUE THREAD

**Issue by nijoshjose** [danielgindi/Charts#3772]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ I'm adding points around 50 or more in the line chart. The points are placed adjacent to another point and space between point is less. After that, I'm clicking on any points it becomes **crash**.

## What did you expect to happen?

ℹ **I want to run my application smoothly without the crash.**

## What happened instead?

ℹ I got crash from this line  

> return data.entryCount < Int(CGFloat(dataProvider?.maxVisibleCount ?? 0) * viewPortHandler.scaleX)

in this line **CGFloat(dataProvider?.maxVisibleCount ?? 0) * viewPortHandler.scaleX** it become infinity.
 here is the full function
```
@objc open func isDrawingValuesAllowed(dataProvider: ChartDataProvider?) -> Bool
    {
        guard let data = dataProvider?.data else {
            return false
        }
        return data.entryCount < Int(CGFloat(dataProvider?.maxVisibleCount ?? 0) * viewPortHandler.scaleX)
    }
```
So what i'm supposed to do?
## Charts Environment

**Charts version:**  3.1.1
**Xcode version:** 10.1
**Swift version:** 4.2
**macOS version running Xcode:** macOS Mojave (10.14.1)

**Comment by dtmp** [comment]
@nijoshjose ran into a similar problem. managed to find a solution?

**Comment by dtmp** [comment]
in my case, the error was related to trying to set visibleXRangeMaximum to an empty dataset

**Comment by TalibDev** [comment]
I am getting this crash when I use the charts for a longer time, like zooming in and zooming out multiple times, does anyone found any solution? @dtmp @nijoshjose @

**Comment by alimumtaz** [comment]
anyone resolved this issue?

**Comment by elericuz** [comment]
hi @alimumtaz, it seems that you have to give a value for setMaximumScaleX as well as the maxVisibleCount. It worked for me.

```
chartView.maxVisibleCount = 30
chartView.viewPortHandler.setMaximumScaleX(CGFloat(1.5))
```
hope it work for you too.
