### ISSUE TITLE
How to change value line length for each value in pieChartView

### ISSUE THREAD

**Issue by whatya** [danielgindi/Charts#3776]
when many value are equal and they are too small, all the value label and line are overlaped , i want to archive the piechart like the image below: 

<img width="497" alt="2018-12-10 10 38 51" src="https://user-images.githubusercontent.com/4310745/49708480-cb291400-fc6a-11e8-9a55-2d22fa0b28fc.png">

**Comment by liuxuan30** [comment]
Currently we don't. you can improve it and provide a PR for everyone.

**Comment by soareseneves** [comment]
I hope someone address this issue, I would if my UI skills didn't suck haha.
