### ISSUE TITLE
Feature: Add option to draw limit lines on top of data

### ISSUE THREAD

**Issue by siltrifork** [danielgindi/Charts#3781]
Is there any chance that the existing Android feature "drawGridlinesBehindData" is coming to the Swift library as well? https://github.com/PhilJay/MPAndroidChart/pull/3451/files

**Comment by liuxuan30** [comment]
`drawLimitLinesBehindDataEnabled`

**Comment by siltrifork** [comment]
No, that feature doesn't do what I want. I want the grid lines above the data like asked her:
https://github.com/PhilJay/MPAndroidChart/issues/3446
