### ISSUE TITLE
How to disable Accessibility support?

### ISSUE THREAD

**Issue by mecid** [danielgindi/Charts#3782]
I would like to disable Accessibility support because it overrides my own implementation.
Is it possible?

**Comment by liuxuan30** [comment]
I don't know what you mean by `it overrides my own implementation`? If you had your own, it should be override by yours actually.

**Comment by mecid** [comment]
@liuxuan30 I mean, when I use code like this it is not working now. Chart still use own implementation, but it works with the previous release.

`    func setupDetailedAccessibility(for statistics: [HKStatistics], with userAge: Int, and activity: Activity) {
        accessibilityElements = statistics.enumerated().map { index, statistic in
            let value = statistic.averageQuantity()?.doubleValue(for: .heartRate()) ?? 0
            let zone = value.calculate(for: activity, with: userAge)
            let frame = CGRect(x: 0, y: CGFloat(index * 30) + 10, width: bounds.width, height: 30)
            let element = UIAccessibilityElement(accessibilityContainer: self)
            element.accessibilityLabel = DateFormatter.shortTime.string(from: statistic.endDate)
            element.accessibilityValue = "\(Int(value)), \(zone.description)"
            element.accessibilityFrameInContainerSpace = frame
            return element
        }
    }`

**Comment by liuxuan30** [comment]
are you able to find what's the difference?

**Comment by liuxuan30** [comment]
We had a bug fix for Accessibility, but not likely to impact your saying.

**Comment by mecid** [comment]
@liuxuan30 your current implementation of Accessibility is too general and not working for every case. We have to be able to customize it or override.

**Comment by liuxuan30** [comment]
@mecid your saying 
>Chart still use own implementation, but it works with the previous release.

is kind of vague, I don't remember what change could lead to this. since you have the right code here, I'm asking you to help identify what is changed

**Comment by mecid** [comment]
@liuxuan30 it was broken after 2.3 release, when you introduce Accesssibility support out of the box.
I can't override your implementation with my own.

**Comment by liuxuan30** [comment]
What function you cannot override. I cannot find your `setupDetailed...`

**Comment by mecid** [comment]
@liuxuan30 this is my extension func, which sets accessibilityElements on ChartView. But it is not working since 2.3.

**Comment by liuxuan30** [comment]
you have to check out latest master branch to see what's broken then. 

We are not responsible for your extension func. If there is a conflict, you should fix it. If it's the library bug, you are welcome to fix it as well. or point it out what's the issue.
