### ISSUE TITLE
how to center legend text of LineChartView?

### ISSUE THREAD

**Issue by faeldix** [danielgindi/Charts#3789]
I want to center my legend text relative of all graph not only canvas width.

I use this code to do this:

```
            let legend = graph.legend
            legend.drawInside = false
            legend.wordWrapEnabled = true
            legend.form = .circle
            legend.orientation = .horizontal
            legend.verticalAlignment = .top
            legend.horizontalAlignment = .center
```

But i have this result:

![image](https://user-images.githubusercontent.com/1892707/50232728-dbdb3780-0398-11e9-97ba-15a1b649ce78.png)

**Comment by liuxuan30** [comment]
I guess you need to override some code. The legend in this library is not as smart as you think. I admit there is a lot to improve, but we don't have the man power to do that.
