### ISSUE TITLE
LineChartView Y-Aixs label'number inaccuracy

### ISSUE THREAD

**Issue by LCDelegate** [danielgindi/Charts#3794]
`self.LineChartView.rightAxis.enabled = NO;
ChartYAxis *leftAxis = self.LineChartView.leftAxis;
leftAxis.forceLabelsEnabled = NO;
leftAxis.axisMinimum = 0;`

if "val" about 25000000~30000000，and run next code：
`[values addObject:[[ChartDataEntry alloc] initWithX:i y:val]];` leftY-Axis inaccuracy。

![Uploading IMG_7452.jpg…]()

please help

**Comment by liuxuan30** [comment]
don't understand. reopen with more details

**Comment by LCDelegate** [comment]
我发现，我按照上面的参数配置图表。
左边Y轴显示数值异常，大概就是当数值超过2500,0000的时候出现的

**Comment by liuxuan30** [comment]
it's just a matter of the nature of double. If you want to format, just you `valueFormatter`
