### ISSUE TITLE
Highlight per drag not working!

### ISSUE THREAD

**Issue by CLships** [danielgindi/Charts#3805]
Hi,

I'm probably doing something wrong here, but I can't get the highlighting per drag to work on my line chart. Highlighting per tap works perfectly, I get the events in the ValueSelectedListener, but not when dragging.

The chart must be fully zoomed out and unable to drag in either direction for highlighting to work.

 Am I supposed to get the drag highlights somewhere else than the ChartValueSelectedListener?

**Comment by liuxuan30** [comment]
take a look at the drag gesture handler. or provide your own.
and maybe just use `highlightPerDragEnabled`
