### ISSUE TITLE
When y value is equal ，HorizontalBarChartView only show integer

### ISSUE THREAD

**Issue by chilewen** [danielgindi/Charts#3806]
`NSMutableArray *yVals = [[NSMutableArray alloc] init];`
    `for (int i = 0; i < count; i++)`
   ` {`
       ` double val = (double) 10.5;`
        `[yVals addObject:[[BarChartDataEntry alloc] initWithX:i * spaceForBar y:val icon: [UIImage imageNamed:@"icon"]]];`
   ` }`

When I set all BarChartDataEntry's y value = 10.5 in BarChartDataSet, the HorizontalBarChartView show the value is 10.

**Comment by liuxuan30** [comment]
use `valueVormatter`.
