### ISSUE TITLE
A Question to contribution

### ISSUE THREAD

**Issue by lobodpav** [danielgindi/Charts#3808]
For my project, I need quite a few new features.

I'm happy to code them, but wanted to ask a question: When I develop something that's not in `MPAndroidChart`, how and will it ever be synced to `MPAndroidChart`?

Is this a problem? I'm not sure how you sync both projects.

Thanks.

**Comment by liuxuan30** [comment]
basically, we don't so far. It became kind of independent now.

We cannot ask contributors to provide both android and iOS implementations for a new feature or enhancements. and I don't think we have the resource to port them into Android as well.. the original authors seem silent and busy with other things.

If you have the time on both platforms, we appreciate your work and time. but it's not forced. so as long as you are helping, we are thankful

**Comment by lobodpav** [comment]
Thanks for clarifying. I am no good at Android, that’s why I asked my question. Allright, I’ll do pull requests once ready.
