### ISSUE TITLE
How to show break in line chart for more than one graph?

### ISSUE THREAD

**Issue by pratik-jaiswal** [danielgindi/Charts#3810]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
I know there is a way that to break a chart into separate data sets but it will complicate lot of things for 4 lines in the same screen.

## What did you expect to happen?
i want to know is there anything you can suggest instead of above. So that i can break the line chart with less of a complexity.

## Charts Environment

**Charts version/Branch/Commit Number:3.2.1**
**Xcode version:10.1**
**Swift version:4.2**
**Platform(s) running Charts:macOs high sierra**
**macOS version running Xcode:10.13.6**

**Comment by liuxuan30** [comment]
currently, use multiple data sets. Or you have to write the feature by yourself. I used to write one, but it's more complex so far with 3.0, so I suggest use multiple data sets

**Comment by RabiChourasiaOgma** [comment]
> currently, use multiple data sets. Or you have to write the feature by yourself. I used to write one, but it's more complex so far with 3.0, so I suggest use multiple data sets

yes...I have used multiple data sets in the chart..... I have only requirement is charts color dynamic with Yaxis value...like that attached images....please tell me how can I do that

**Comment by pratik-jaiswal** [comment]
Please elaborate it properly or share some images so that we can understand what you are trying to do.

**Comment by RabiChourasiaOgma** [comment]
![c448b068-dbd4-11e6-897a-ddc4ed5b27e5](https://user-images.githubusercontent.com/35031111/53154837-aa255d80-35e1-11e9-93df-7b37a7062266.png)
@pratik-jaiswal  I want try like this.....I want to add colours to the background of the chart. The colour zones depend on the y values.

**Comment by pratik-jaiswal** [comment]
See as far as I know this is not possible in this library. But still you can ask @liuxuan30 if he knows any thing about it.

**Comment by anton-filimonov** [comment]
@RabiChourasiaOgma you can make chart view transparent and add your properly colored view behind it. You'll have to implement drawing (or just combining some views and their layout) yourself, using chart methods for coordinates transformation.
