### ISSUE TITLE
Multiple colors for the same line

### ISSUE THREAD

**Issue by cyril94440** [danielgindi/Charts#3816]
Hi there

I am trying to draw a single line with a different color according to a y-value-threshold.
Is there a way to achieve such a thing?

This is the UI I am currently using but it is not beautiful, that is why I am trying to apply the background color directly on the line.

Thanks !!!

![Screenshot](https://i.ibb.co/yhs25QM/Capture-d-cran-2019-01-14-18-46-50.png)

**Comment by liuxuan30** [comment]
check
```swift
    /// All the colors that are used for this DataSet.
    /// Colors are reused as soon as the number of Entries the DataSet represents is higher than the size of the colors array.
    var colors: [NSUIColor] { get }
```

**Comment by cyril94440** [comment]
I may be wrong, but this will not color a single set/line with multiple colors.

Like this:

![Example](https://d13ot9o61jdzpp.cloudfront.net/images/multi-colored_line_chart_with_gradient_fill.png)

**Comment by liuxuan30** [comment]
eh you are talking about gradient lines? that's a different story then. There is a PR but we didn't review yet.

**Comment by rameswar54** [comment]
@liuxuan30 Are there any plan to review/merge the PR?

**Comment by seanhamstra** [comment]
Looking for this feature too! Love the library.

**Comment by YongTaiSin** [comment]
> eh you are talking about gradient lines? that's a different story then. There is a PR but we didn't review yet.

请问有没有这个折线渐变色的分支呢大佬？
