### ISSUE TITLE
How to save image of scrollable graph

### ISSUE THREAD

**Issue by pcmanik** [danielgindi/Charts#3819]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I'm saving LineChartView as image into user photo library using
```
let chartImage = chartView.getChartImage(transparent: false)
UIImageWriteToSavedPhotosAlbum(chartImage, nil, nil, nil)
```
Content of this chart can't fit into chart view so user is able to scroll it.

## What did you expect to happen?

I'm excepting that the resulting image will contain the whole chart. Or at least multiple images. 

## What happened instead?

Resulting image contains only the visible portion of the chart

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.1
**Xcode version:** 10.1
**Swift version:** 4.2.1
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.1

**Comment by vaibhav-nickelfox** [comment]
Hey @pcmanik you got the solution of this?

**Comment by pcmanik** [comment]
@vaibhav-nickelfox I've used one "hack". Before requesting the image i expand the width constraint of the view to the full width of chart. Than I create the image. After it's processed I shrink the width constraint back to original width.

But there were still some issues so in the end I've created my own simple library for plotting ECG graph.
