### ISSUE TITLE
chartTranslated in a Pie Chart is not called

### ISSUE THREAD

**Issue by jgbrittos** [danielgindi/Charts#3821]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I have created a simples Pie Chart, but chartTranslated is never called even thou the other ChartViewDelegate methods are working fine.

I have set pieChartView's delegate in the viewDidLoad of ViewController

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    pieChartView.delegate = self
}

//...

func chartTranslated(_ chartView: ChartViewBase, dX: CGFloat, dY: CGFloat) {
    print("Point (\(dX), \(dY))")
}
```

## What did you expect to happen?

I was expecting chartTranslated to be called whenever I drag the Pie chart and print every point variation in console.

## What happened instead?

Nothing happens! chartTranslated method is not called and the print("") I have put inside it doesn't print anything.

## Charts Environment

**Charts version/Branch/Commit Number:**3.2.1
**Xcode version:**10.1
**Swift version:**4.2
**Platform(s) running Charts:**iOS
**macOS version running Xcode:**10.13.6

**Comment by liuxuan30** [comment]
`chartTranslated` is never called in pie chart.

**Comment by 9SL9** [comment]
> `chartTranslated` is never called in pie chart. I'm not sure why, but if you want it, you can override some methods and add it in your sub pie chart class.

Any tips on how to get chartTranslated called from a piechart? How would I override 'some methods'?
