### ISSUE TITLE
Regarding to label of axis, I think it displays .03 instead of 0.03

### ISSUE THREAD

**Issue by alexliubj** [danielgindi/Charts#3824]
when it has decimal places and smaller than 1.
I want it to be 0.03 or 0.15 instead of .03, .15
I couldn't find a way to handle it.

**Comment by liuxuan30** [comment]
use valueFormatter....

**Comment by alexliubj** [comment]
Awesome, thank you so much.
Just put what I did at the end and hope this will help someone else has the same issue. 

```
leftAxis.valueFormatter = DefaultAxisValueFormatter(block: { (value, _) -> String in
            return "\(value.toString(AppConstants.decimals))" //.toString() is a function I coded to convert double to string with decimal places. 
        })
```
