### ISSUE TITLE
Multiline value labels on BarChart.

### ISSUE THREAD

**Issue by IgorShvetsov-Noveo** [danielgindi/Charts#3826]
I want to use multiline value labels above chart bars. If I put multiline value (with '\n' inside) value overlaps bar. So I subclassed BarChartRenderer and added offset to the y position of the point.

```
public class MultilineLabelBarChartRenderer: BarChartRenderer {
    @objc
    open override func drawValue(context: CGContext, value: String, xPos: CGFloat, yPos: CGFloat, font: NSUIFont, align: NSTextAlignment, color: NSUIColor) {        
        ChartUtils.drawText(context: context, text: value, point: CGPoint(x: xPos, y: yPos - 15), align: .center, attributes: [NSAttributedString.Key.font: font, NSAttributedString.Key.foregroundColor: color])
    }
}
```
So now I have 2 lines labels above bars. But they are not center aligned because the point calculates wrong.

Is there's a way to have multiline labels above bars center aligned?

Charts version 3.2.1
Xcode version: 10.0
Swift version: 4.2
ios 11, 12
![multiline_chart_labels](https://user-images.githubusercontent.com/34641419/51979922-07d1f880-24c1-11e9-870f-d21f0fcce4e1.png)

**Comment by anton-filimonov** [comment]
Try adding text alignment attribute to what you sent as `attributes` like this:
```
public class MultilineLabelBarChartRenderer: BarChartRenderer {
    @objc
    open override func drawValue(context: CGContext, value: String, xPos: CGFloat, yPos: CGFloat, font: NSUIFont, align: NSTextAlignment, color: NSUIColor) {      
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = .center  
        ChartUtils.drawText(context: context, text: value, point: CGPoint(x: xPos, y: yPos - 15), align: .center, attributes: [NSAttributedString.Key.font: font, NSAttributedString.Key.foregroundColor: color, NSAttributedString.Key.paragraphStyle: paragraphStyle])
    }
}
```

**Comment by IgorShvetsov-Noveo** [comment]
@anton-filimonov thank you for response. Unfortunately, it didn't help. The same result as on screenshot.

**Comment by IgorShvetsov-Noveo** [comment]
It helped me to use drawMultilineText methods from ChartUtils. But they marked with internal. So I had to copy them. I would prefer another way to have multiline value labels.

**Comment by liuxuan30** [comment]
you have to override the `drawValues` method to do it yourself.
