### ISSUE TITLE
In line chart, can I make all labels in Chart area even with changing yOffset?

### ISSUE THREAD

**Issue by alexliuxe** [danielgindi/Charts#3829]
If I set yOffset, all values on y-axis will move up but I want the highest value stay still inside my line chart rectangle area.(instead of highest displayed out of line area) Is there a way I can do it?

Thanks in advanced.

**Comment by alexliubj** [comment]
<img width="295" alt="screen shot 2019-02-07 at 1 13 39 pm" src="https://user-images.githubusercontent.com/447106/52433160-65c29980-2ada-11e9-9d4f-13d44c70df30.png">

This is the first one, it will be out of range.

**Comment by liuxuan30** [comment]
you have to override a few methods to do so.
