### ISSUE TITLE
The right Y axis displays incorrect values that does not fit the chart

### ISSUE THREAD

**Issue by waterbender** [danielgindi/Charts#3835]
## What did you do?

ℹ I tried to build the chart with custom Max and Min and also with dynamic one and I get the wrong axes for both of the cases. Also I stetted the 
**dataSet.axisDependenc**y = .right AND used
**chartView.notifyDataSetChanged()** after the data is set

because I am using right axis to display Y position

## What did you expect to happen?

ℹ I want that the chart fill the axes and the chart is in bounds with axes with correct values
finally I found that the problem is in the method for set labels count
**self.chartView.rightAxis.setLabelCount(3, force: true)** but I am not sure how to fix it

## What happened instead?

ℹ I got wrong value for Y axis

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: Version 10.1 (10B61)** 
**Swift version: 4.2**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: Mac OS Mojave 10.14.3 (18D42)**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
<img width="392" alt="screen shot 2019-02-11 at 4 02 01 pm" src="https://user-images.githubusercontent.com/10553529/52568054-6c247e80-2e16-11e9-93d6-7035c904c2c2.png">

**Comment by waterbender** [comment]
Also it shows the right value if I use custom formatter for Right axis

**Comment by liuxuan30** [comment]
try charts demo first. This should be your setup problem.
