### ISSUE TITLE
Y-axis values draw error

### ISSUE THREAD

**Issue by KevinZK** [danielgindi/Charts#3837]
<img width="375" alt="wechat40d4a769a018cf9bbcbd0b959ae7a21a" src="https://user-images.githubusercontent.com/15150546/52626076-62217f00-2eed-11e9-9916-ca75251391ca.png">

**Comment by LiubovFedorchuk** [comment]
Hi, @KevinZK, perhaps, you can add companion code, this can speed up and simplify the problem solving process.
