### ISSUE TITLE
Why is there a maximum on lineWidth in LineRadarChartDataSet?

### ISSUE THREAD

**Issue by tkctrifork** [danielgindi/Charts#3839]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
I am trying to draw a thick line below another line. I am doing this by adding the same values in two different DataSets. I'd like to set the `lineWidth` to `15` on the thick lined DataSet.

## What did you expect to happen?
The line should be drawn with a line width of `15`.

## What happened instead?
The line is drawn with a line width of `10`. I can see that the `lineWidth` is clamped by `_lineWidth = newValue.clamped(to: 0...10)`. I just don't understand why? Is there any reason to limit this? Is there any way for me to work around this? I know I can implement a custom renderer, but I'd like to avoid that if possible :) 

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.1
**Xcode version:** 10.1 (10B61)
**Swift version:** 4.2
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.1 (18B75)

**Comment by liuxuan30** [comment]
apparently there is no reason but 'let's do so first'. You can simply override the method to give a new implementation. not many line charts would have a line with 15 width.. so you got my point.
