### ISSUE TITLE
Swift 4.2: 'values' is deprecated Warnings

### ISSUE THREAD

**Issue by seenoevo** [danielgindi/Charts#3840]
I'm running Xcode 10.1 with Swift 4.2, and I'm receiving many warnings related to:

> values' is deprecated: Use `subscript(position:)` instead.

![untitled](https://user-images.githubusercontent.com/8109158/52696065-ecd0a100-2f22-11e9-8eb4-98a7e3c4d8a6.png)

I thought this was address with the Swift 4.2 update, but apparently not.

Can this please be addressed?

**Comment by liuxuan30** [comment]
yes. We will address this next. @jjatie

**Comment by riley-usagi** [comment]
How can we ignore this warnings?

Thanks.

**Comment by cluelessoodles** [comment]
Also getting the same warnings. Hope you'll add a fix for it to the 2.2.3 release.

**Comment by liuxuan30** [comment]
should be addressed in https://github.com/danielgindi/Charts/pull/3847
But it could be a breaking change.
