### ISSUE TITLE
BarChartDataEntry Equatable implementation returns false positives

### ISSUE THREAD

**Issue by jboulter11** [danielgindi/Charts#3841]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Comparing the equality of two `BarChartDataEntry`  returns incorrect answers when `x` and `y` are equal but `yValues` are not equal.  Example `yValues` would be `[0.0, 1.0, 0.0, 0.0]` and `[0.0, 1.0, 0.0]`.  `BarChartDataEntry` should override `ChartDataEntry`'s `isEqual` implementation comparing `yValues`.

## What did you expect to happen?

Two `BarChartDataEntry` objects with different `yValues` are not equal.

## What happened instead?

Only the members `x` and `y` in `ChartDataEntry` are compared and the equality is a false positive.

## Charts Environment

**Charts version/Branch/Commit Number:** 9f2c13009f8230c40cc31c25b330ccda6ad18ff6 (A couple commits after 3.2.1 becasue we needed a bugfix.) and 3.2.1
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.1

## Demo Project

https://github.com/jboulter11/ChartsInequalityBugExample
```swift
        let entry1 = BarChartDataEntry(x: 0, yValues: [0.0, 1.0, 0.0, 0.0])
        let entry2 = BarChartDataEntry(x: 0, yValues: [0.0, 1.0, 0.0])
        
        // Comment me out for next example
        assert(entry1 != entry2)

        // Real world application example.
        let dataSet1 = BarChartDataSet(values: [entry1], label: nil)
        let dataSet2 = BarChartDataSet(values: [entry2], label: nil)

        // Here we see they are not the same, but this assert will fail.
        assert(dataSet1.values != dataSet2.values)
```

## Proposed Solution

Extend `BarChartDataEntry` to override it's super's implementation and check additional values.  If there are additional parameters besides `yValues`, we should check them as well.  If this solution is acceptable, I'll create a pull request.

```swift
extension BarChartDataEntry {
    open override func isEqual(_ object: Any?) -> Bool {
        guard let object = object as? BarChartDataEntry else { return false }
        let superIsEqual = super.isEqual(object)
        guard superIsEqual else { return superIsEqual }
        
        return self.yValues == object.yValues
    }
}
```

**Comment by liuxuan30** [comment]
I don't support this as y value matters as well in bar chart data set. What you think @jjatie

**Comment by jjatie** [comment]
why not just
```
return super.isEqual(object)
    && self.yValues == object.yValues
```
