### ISSUE TITLE
How to hide those icons? 

### ISSUE THREAD

**Issue by renjingkai** [danielgindi/Charts#3842]
How to hide those two icons, i can't find any way to hide them! Please help,I hope future could have more simple API to use [
<img width="1198" alt="wechatc5bb8dbf76834e79a2bca2af4782a3a1" src="https://user-images.githubusercontent.com/14341914/52767220-cadf3780-3064-11e9-8789-b7b875f18018.png">
](url)

**Comment by KevinCoderX** [comment]
```swift
yourChartView.legend.enabled = false
yourChartView.hartDescription?.enabled = false
```
It will be hide.

**Comment by renjingkai** [comment]
It works,save my day!!!!
