### ISSUE TITLE
BarChartView showing consecutive values in xAxis

### ISSUE THREAD

**Issue by jiffy-arti** [danielgindi/Charts#3843]
## What did you do?

ℹ I am using a bar chart and line chart to draw few values. I have 12 months in x-axis but when ran it reduces the count to 6 and showing alternate values.

## What did you expect to happen?
ℹ I want to show user full 12 values all the time and zoom user from zooming.

## Bar Chart Code
        barChartView.noDataText = noDataText
        barChartView.chartDescription?.text = ""
        //legend
        let legend = barChartView.legend
        legend.enabled = true
        legend.horizontalAlignment = .right
        legend.verticalAlignment = .top
        legend.orientation = .vertical
        legend.drawInside = true
        legend.yOffset = 10.0;
        legend.xOffset = 10.0;
        legend.yEntrySpace = 0.0;
        
        // X - Axis Setup
        let xaxis = barChartView.xAxis
        self.months = xAxisData
        xaxis.valueFormatter = IndexAxisValueFormatter(values: xAxisData)
        
        xaxis.labelPosition = .bottom
        xaxis.centerAxisLabelsEnabled = true
        xaxis.granularity = 1
        xaxis.drawGridLinesEnabled = false
        xaxis.enabled = true
        xaxis.drawGridLinesEnabled = false
        xaxis.drawLabelsEnabled = true
        barChartView.rightAxis.enabled = false

        // Y - Axis Setup
        let yaxis = barChartView.leftAxis
        yaxis.spaceTop = 0.35
        yaxis.axisMinimum = 0
        yaxis.drawGridLinesEnabled = false
        
        //Create data entries here
        var dataEntries: [BarChartDataEntry] = []
        var dataEntries1: [BarChartDataEntry] = []
        
        for i in 0..<xAxisData.count {
            let dataEntry = BarChartDataEntry(x: Double(i) , y: yAxisData1[i])
            dataEntries.append(dataEntry)
            
            let dataEntry1 = BarChartDataEntry(x: Double(i) , y: yAxisData2[i])
            dataEntries1.append(dataEntry1)
        }
        
        let noZeroFormatter = NumberFormatter()
        noZeroFormatter.zeroSymbol = ""
        noZeroFormatter.numberStyle = .decimal

        let chartDataSet = BarChartDataSet(values: dataEntries, label: label1)
        chartDataSet.valueFormatter = DefaultValueFormatter(formatter: noZeroFormatter)

        let chartDataSet1 = BarChartDataSet(values: dataEntries1, label: label2)
        chartDataSet1.valueFormatter = DefaultValueFormatter(formatter: noZeroFormatter)

        let dataSets: [BarChartDataSet] = [chartDataSet, chartDataSet1]
        chartDataSet.colors = [colorChart1]
        chartDataSet1.colors = [colorChart2]
        
        let chartData = BarChartData(dataSets: dataSets)
        let groupSpace = 0.4
        let barSpace = 0.03
        let barWidth = 0.2
        
        chartData.barWidth = barWidth;
        chartData.groupBars(fromX: 0.0, groupSpace: groupSpace, barSpace: barSpace)
        barChartView.data = chartData
        barChartView.xAxis.granularity = 0.5
        barChartView.notifyDataSetChanged()
        //barChartView.setVisible  //setVisibleXRangeMaximum(14)
        //chart animation
        barChartView.animate(xAxisDuration: 1.5, yAxisDuration: 1.5, easingOption: .linear)

## Charts Environment

**Charts version/Branch/Commit Number: Latest version**
**Xcode version:10.1**
**Swift version:4**
**Platform(s) running Charts:**
**macOS version running Xcode:10.14.2**

![screenshot 2019-02-14 at 4 26 09 pm](https://user-images.githubusercontent.com/33309350/52782603-7abca100-3075-11e9-9c61-55bb21c92830.png)
![screenshot 2019-02-14 at 4 29 11 pm](https://user-images.githubusercontent.com/33309350/52782823-f61e5280-3075-11e9-8a16-040b2aba2b1a.png)

**Comment by drewster99** [comment]
try this:

    barChartView.xAxis.granularity = 1
    barChartView.xAxis.labelCount = 12

**Comment by jiffy-arti** [comment]
Resolved thanks a lot...
