### ISSUE TITLE
Piechart rounded corners for each slice

### ISSUE THREAD

**Issue by umutozbek** [danielgindi/Charts#3845]
Hello,
I implemented the library and using PieChart. I want to add rounded corners for each slices or draw small circles to front&rear side of slices. How can i do this ? Can you help me pls. 
Something like that ; 
<img width="60" alt="screen shot 2019-02-15 at 12 20 44" src="https://user-images.githubusercontent.com/47630939/52847001-1ef92300-311c-11e9-9cee-62591c9614e8.png">

**Comment by liuxuan30** [comment]
well it could be a big question. You can try to start with a rounded arch. But this is beyond our support.
