### ISSUE TITLE
Unexpected crash on 3.2.2

### ISSUE THREAD

**Issue by acegreen** [danielgindi/Charts#3855]
## What did you do?

<img width="1860" alt="screen shot 2019-02-20 at 10 14 50 am" src="https://user-images.githubusercontent.com/10794609/53101817-85a18680-34f8-11e9-810b-4bb0d40c1786.png">

## What did you expect to happen?

No crash after upgrade. This exact code works on 3.2.1. Going back to 3.2.1, everything works fine.

## What happened instead?

Crash `objc[625]: Attempt to use unknown class 0x12ddfbf00` after upgrade from 3.2.1 to 3.2.2

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.2
**Xcode version:** Xcode 10.2
**Swift version:** Swift 4.2
**Platform(s) running Charts:** iOS
**macOS version running Xcode:**

**Comment by liuxuan30** [comment]
cannot see the crash log. post it in text

**Comment by acegreen** [comment]
@liuxuan30 there is nothing to post, just that one line error and the stack trace on that screenshot.

**Comment by liuxuan30** [comment]
@acegreen at the breakpoint, type `bt` to print the stack

**Comment by cruisediary** [comment]
> Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x20).
The process has been returned to the state before expression evaluation.

**Comment by acegreen** [comment]
Deleting derived folder and cleaning project indeed works.
