### ISSUE TITLE
CandleChart do not render the first candle in CombineChartView

### ISSUE THREAD

**Issue by yogalau** [danielgindi/Charts#3857]
## What did you do?

i'm using combineChartView to display some data with candleChart.

## What did you expect to happen?

I would like to display fully data and candle stick at chart.

## What happened instead?

After combineChartView data loaded, candle chart data is fully loaded, but the first candle did not rendered. 

![image](https://user-images.githubusercontent.com/28782154/53158605-f92dbb80-35fe-11e9-8615-e60c879062e4.png)

When selecting the value of chart, it can read the entry data.

![image](https://user-images.githubusercontent.com/28782154/53161392-e3bb9000-3604-11e9-86f3-8faeceed0f8c.png)

log::

![image](https://user-images.githubusercontent.com/28782154/53162708-9391fd00-3607-11e9-8da9-65e75bdacb36.png)

## Charts Environment

**Charts version/Branch/Commit Number:Charts 3.2.2
**Xcode version:Version 10.1 (10B61)
**Swift version:4.2
**Platform(s) running Charts:iOS 12.1
**macOS version running Xcode:macOS 10.14 (18A391)

## Demo Project

    NSMutableArray *candleVals = [NSMutableArray array];
    
    for (int i = 0; i < 10; i++) {
        double high = [candleData[i][@"high"] doubleValue];
        double low = [candleData[i][@"low"] doubleValue];
        double open = [candleData[i][@"open"] doubleValue];
        double close = [candleData[i][@"close"] doubleValue];
        
        [candleVals addObject:[[CandleChartDataEntry alloc] initWithX:i shadowH:high shadowL:low open:open close:close icon: nil]];
    }
    
    CandleChartDataSet *candleDataSet = [[CandleChartDataSet alloc] initWithValues:candleVals];
    [candleDataSet setColor:[UIColor colorWithWhite:1 alpha:0.5]];
    
    candleDataSet.shadowWidth = 0.8;
    candleDataSet.decreasingColor = GREEN_COLOR;
    candleDataSet.decreasingFilled = YES;
    candleDataSet.increasingColor = RED_COLOR;
    candleDataSet.increasingFilled = YES;
    candleDataSet.drawValuesEnabled = NO;
    
    CandleChartData *candleData = [[CandleChartData alloc] initWithDataSet:candleDataSet];
    
    CombinedChartData *combinedData = [[CombinedChartData alloc] init];
    combinedData.candleData = candleData;
    _combinedChartView.data = combinedData;

**Comment by shoujs** [comment]
I second the issue. The first candle is not diplayed in the iOS-swift-demo project. I am using 3.2.2.

**Comment by jjatie** [comment]
@yogalau can you check the master branch for this issue? #3891 Should resolve this.

**Comment by liuxuan30** [comment]
we could close it now I suppose.
