### ISSUE TITLE
Smoothly moving a slowly changing linechart

### ISSUE THREAD

**Issue by thirstyone** [danielgindi/Charts#3859]
I want to display a slowly moving signal (sine wave 0.5-2Hz) over the last say 5 seconds.  
Let's suppose I receive new values 10 times a second (which might not necessarily be different). 
I am increasing x value (i) using a timer, which is fired each 1/24th of a second. 
Upon changing the y value, in the didSet observer I do the following: 
```
            v?.data?.addEntry(ChartDataEntry(x: Double(i), y: V), dataSetIndex: 0) 
            v?.notifyDataSetChanged()
            v?.moveViewToX(Double(i))
            v?.setVisibleXRange(minXRange: Double(0), maxXRange: Double(6))  
```
How do I change the X axis legend, so that it displays actually the seconds? 
What are the ways to optimize CPU usage in such scenario? (with a relatively small chart, somewhat 260x150 pixels I see 90% CPU utilization, which doesn't seem right to me. 

How do I change the Y legend, so that it displays traling 0 in values from 0 to 1, and displays only 0, 0.5 and 1, not each 1/10?

**Comment by liuxuan30** [comment]
>How do I change the X axis legend, so that it displays actually the seconds?

just use double and maybe a format

>What are the ways to optimize CPU usage in such scenario

you don't. as long as it's not lagging.

>How do I change the Y legend

that's not up to you. But you can override `computeAxisValues` to set `entries` to be [0,0.5,1]
