### ISSUE TITLE
Pie chart with vertical orientation clips last legend entry

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [danielgindi/Charts#3860]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Configure the pie chart legend to have a vertical orientation

## What did you expect to happen?

The legend should appear without any contents clipped

## What happened instead?

The last entry in the legend is clipped - not fully visible

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.2 (also occurred in 3.2.1)
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running Charts:** iOS 12.1
**macOS version running Xcode:** 10.14.3

## Demo Project

I have modified the example to easily reproduce this. In PieChartViewController.swift I modified viewDidLoad to not call setup, and simply set the legend to be vertical. For your convenience here is a modified version. 

[Charts-master.zip](https://github.com/danielgindi/Charts/files/2891245/Charts-master.zip)

## Screenshot

![simulator screen shot - iphone x - 2019-02-21 at 13 48 12](https://user-images.githubusercontent.com/15804476/53201538-88c47180-35e1-11e9-9a0d-6e755207349a.png)

**Comment by liuxuan30** [comment]
should be a bug
