### ISSUE TITLE
delete the Charts-master files download , the  dragged Charts.xcproject in my project also cannot used   

### ISSUE THREAD

**Issue by xiaoheziQH** [danielgindi/Charts#3870]
xcode10,swift4.2
how to "drag Charts.xcproject to my project"? because I found after I drag that, delete the Charts-master files , the  dragged Charts.xcproject in my project also cannot used

**Comment by xiaoheziQH** [comment]
@danielgindi 您能看到么

**Comment by xiaoheziQH** [comment]
@liuxuan30 啊 我看到你在 麻烦看下我这个问题吧

**Comment by liuxuan30** [comment]
refer Charts workspace.
