### ISSUE TITLE
Clipping first and last circle from line chart IOS.

### ISSUE THREAD

**Issue by NPhadtare** [danielgindi/Charts#3873]
Clipping first and last circle from line chart IOS. I try lots of thing but never get any solution. I also make true to "avoidFirstLastClippingEnabled" but this not work. giving space disturb UI. Please provide me solution sooner.
please find attached screen shot of issue.
![screenshot 2019-02-28 at 4 04 29 pm](https://user-images.githubusercontent.com/19524773/53560792-3223de00-3b73-11e9-8706-f11d89e65abb.png)

**Comment by liuxuan30** [comment]
`avoidFirstLastClippingEnabled` is not `Clipping first and last circle`

>/// if set to true, the chart will avoid that the first and last label entry in the chart "clip" off the edge of the chart
