### ISSUE TITLE
support ECG demo?

### ISSUE THREAD

**Issue by somessss** [danielgindi/Charts#3880]
![qq _20190305165418 2019-03-05 17_01_06](https://user-images.githubusercontent.com/19978628/53794068-26b52600-3f6a-11e9-8f6d-b8eafcb0b7da.gif)

**Comment by liuxuan30** [comment]
you are welcome to contribute and file a pull request

**Comment by HardikKMT** [comment]
Hello @LCSomeSSSS i want same so can you help me?

Thanks in advance
