### ISSUE TITLE
Circle view is not showing for first point of line chart

### ISSUE THREAD

**Issue by praveenkumar5430** [danielgindi/Charts#3881]
![simulator screen shot - iphone xs max - 2019-03-05 at 15 47 52](https://user-images.githubusercontent.com/41812980/53798784-f0be7480-3f5e-11e9-8b0a-1fdd85a28307.png)

is this an issue or anything i missed in my code?

**Comment by phughes** [comment]
I am also seeing this issue in line & scatter charts.

**Comment by phughes** [comment]
This looks to be fixed in https://github.com/danielgindi/Charts/pull/3865

**Comment by sahabe1** [comment]
how to solve this issues still not showing first cirle

**Comment by yas375** [comment]
We had the same issue and I'm confirming that #3891 has fixed it.

I think this issue can be closed now.

**Comment by sahabe1** [comment]
Its happening again in v 3.2.2 it was working in 3.0.4

**Comment by yas375** [comment]
@sahabe1 have you tried latest `master` of the library? It has fixed the problem for me. There was no new release since it was fixed yet. So you will need to do something like this in order to pick it up:

```ruby
pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :commit => '34dafbc6'
```

**Comment by NektariosEvangelou** [comment]
@yas375 I also had this problem with a LineChart and your solution worked for me. After updating the Podfile my application kept crashing when declaring a new LineChartDataSet, but after cleaning the build folder of my app it worked perfectly!

**Comment by ZaidSA** [comment]
This worked for me:
`pod 'Charts', '~> 3.3.0'`

If `pod install` doesn't work try `pod install --repo-update`.

**Comment by SangKarthi94** [comment]
pod update clear this issue.

**Comment by parveencse** [comment]
pod 'Charts', '~> 3.3.0' and also pod update
it works for me..thanks @ZaidSA

**Comment by mostafatabal** [comment]
@praveenkumar5430 
can give me code of line chart draw please I want to add label on x axis as you did (Jan , Feb ) like that
