### ISSUE TITLE
Draw circle only on last value

### ISSUE THREAD

**Issue by MickaelCruzDB** [danielgindi/Charts#3887]
Hi, I'm working on a graph LineChartView. I goal to achieve it's the image below :
![t9pxk](https://user-images.githubusercontent.com/2611373/53938460-a816d080-40b0-11e9-83e5-47f7558e3602.png)
Today my actual status is :
![xmg1l](https://user-images.githubusercontent.com/2611373/53938481-b82eb000-40b0-11e9-88d2-cb4e6e6d6cd0.png)

Via LineChartDataSet I achieved to create the circle exactly as expected with the value. But, the problem is for each value of the LineChartDataSet the circle and the value are displayed. I need to only have the last circle visible. Reading lot of similar issues it seems to be mandatory to override `drawHighlighted () `or `drawCircles()` but someone could explain me really in details how to manage that? Thanks in advance!

**Comment by liuxuan30** [comment]
the only thing is you have to read the code how to only draw a circle at last entry.
