### ISSUE TITLE
Cannot set labels for RadarChart

### ISSUE THREAD

**Issue by jekoehler** [danielgindi/Charts#3893]
## What did you do?

I was playing around with example playgrounds, especially with `RadarChart.playground` and I am trying to set string labels to x-axis.

Following the example I can set `RadarChartData` with two different `RadarChartDataSet`s

    var chartView = RadarChartView(frame: rect)
    let data = RadarChartData(dataSets: [set1, set2])
    chartView.data = data

It shows a chart with labels set to x-axis as numbers which range from 0.0 to 4.0.
The labels that should be drawn around the `RadarChart` at the end of each web line should be set like this:

    data.setLabels("X1", "X2", "X3", "X4", "X5")

## What did you expect to happen?

I would expect to set string labels but there are still numbers.

## What happened instead?

There are still numbers. Setting labels isn't working although it is a feature of class `RadarChartData` to set the desired labels.  

## Charts Environment

**Charts version/Branch/Commit Number:** v3.2.2
**Xcode version:** 10.1
**Swift version:**  4.2
**Platform(s) running Charts:** macOS
**macOS version running Xcode:** 10.14.3

## Demo Project

ChartsDemo-macos

**Comment by liuxuan30** [comment]
it seems you have to use valueFormatter.
