### ISSUE TITLE
The pie chart hides the label when the scale is 0. How to deal with it?

### ISSUE THREAD

**Issue by ifgyong** [danielgindi/Charts#3894]
The pie chart hides the label when the scale is 0. How to deal with it?

![image](https://user-images.githubusercontent.com/16182908/54108876-0a0c6880-4418-11e9-98f0-6e7f978bd4af.png)

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/pull/3218

This is targeted for 4.0 release, so either you wait or pick up the code from there and use on your side.
