### ISSUE TITLE
Chart legend 

### ISSUE THREAD

**Issue by Marioliniya** [danielgindi/Charts#3896]
In my application in the legend of the diagram, I want to show a lot of information, but all the legend does not fit on the screen. How to make it so that the legend would appear complete and the diagram was of normal size? How to make the colors in the diagram do not repeat?

![Uploading Screen Shot 2019-03-11 at 9.15.18 PM.png]()
#

**Comment by liuxuan30** [comment]
I think maybe you should write your own legend.
