### ISSUE TITLE
Straight Line in third quadrant does't show up

### ISSUE THREAD

**Issue by ArduinoManager** [danielgindi/Charts#3898]
## What did you do?

Simple LineChart with negative x and y values.

`
            
            let ds1 = LineChartDataSet(values: [], label: "I [mA]")
            ds1.mode = .linear
            ds1.drawCirclesEnabled = true
            ds1.drawCircleHoleEnabled = false
            ds1.circleRadius = 2
            ds1.setCircleColor(.black)
            ds1.colors = [NSUIColor.red]
            ds1.append(ChartDataEntry(x: 0, y: 0))
            ds1.append(ChartDataEntry(x: -50, y: -50))
            ds1.append(ChartDataEntry(x: -100, y: -100))

            chartData.addDataSet(ds1)
            self.lineChartView.data = chartData            
            self.lineChartView.gridBackgroundColor = NSUIColor.white`

## What did you expect to happen?

A straight line in the third quadrant

## What happened instead?

Nothing. The chart is empty.

Replacing:

`ds1.append(ChartDataEntry(x: 0, y: 0))`
`ds1.append(ChartDataEntry(x: -50, y: -50))`
`ds1.append(ChartDataEntry(x: -100, y: -100))`

with:

`ds1.append(ChartDataEntry(x: 0, y: 0))`
`ds1.append(ChartDataEntry(x: 50, y: 50))`
`ds1.append(ChartDataEntry(x: 100, y: 100))`

a straight line  shows up in the first quadrant, as expected.

## Charts Environment

**Charts version/Branch/Commit Number: Pod 3.2.2**
**Xcode version:** 10.1
**Swift version:** 4.2 
**Platform(s) running Charts:** macOS 10.14.3
**macOS version running Xcode:** macOS 10.14.3

## Demo Project

NA

**Comment by liuxuan30** [comment]
seems the order of your x values matters. use -100,-50,0
