### ISSUE TITLE
x Axis grid line origin is wrong !  maybe  a bug,  anxious!!!

### ISSUE THREAD

**Issue by ruigeyun** [danielgindi/Charts#3904]
I set the position of x Axis bottom, but the x Axis grid line origin still is top ，how to fix?? help 
    my setting:       
       xAxis.labelPosition = .bottom
        xAxis.drawGridLinesEnabled = true
        xAxis.gridLineDashPhase =  0.0
        xAxis.gridLineDashLengths = [15, 10000]

<img width="342" alt="A0FF27B41046C5E7A906F4A95CF348A9" src="https://user-images.githubusercontent.com/6257129/54515535-494a3480-4997-11e9-8318-e66a61e85e3d.png">

**Comment by liuxuan30** [comment]
I don't understand.. and I don't find this is an issue for a long time. closing.
I will reply if you get more details.

**Comment by ruigeyun** [comment]
大佬，我的意思是，x轴默认是顶部的，它的网格线起始位置也是顶部。现在我把x轴的位置设置在底部，他的网格线起始位置还是顶部！我是想让网格线作为坐标轴刻度，如上图，Y轴是的刻度有了，x轴的刻度没有

**Comment by ruigeyun** [comment]
> I don't understand.. and I don't find this is an issue for a long time. closing.
> I will reply if you get more details.
大佬，我的意思是，x轴默认是顶部的，它的网格线起始位置也是顶部。现在我把x轴的位置设置在底部，他的网格线起始位置还是顶部！理应跟随到底部才对。我是想让网格线作为坐标轴刻度，如上图，Y轴是的刻度有了，x轴的刻度没有。我在MPAndroidChart 端，使用同样的操作，是可以实现的。
