### ISSUE TITLE
How to display single data when using LineChartView

### ISSUE THREAD

**Issue by iDanielLam** [danielgindi/Charts#3910]
## What did you do?

Using LineChartView

## What did you expect to happen?

Display a horizontal line like this

![image](https://user-images.githubusercontent.com/26591525/54889803-66c05680-4ee1-11e9-9465-587f11b9cd24.png)

## What happened instead?

Display nothing like this

![image](https://user-images.githubusercontent.com/26591525/54889887-be5ec200-4ee1-11e9-90a7-4c977df3844c.png)

## Charts Environment

**Charts version/Branch/Commit Number:**3.2.2
**Xcode version:** 10.1
**Swift version:**4.2
**Platform(s) running Charts:**
**macOS version running Xcode:**

## Demo Project

None

**Comment by zhangjianjun056** [comment]
I have the same problem. Have you solved it。（V3.2.2）

**Comment by friendshipzhang** [comment]
I have the same problem too.

**Comment by friendshipzhang** [comment]
use v3.2.0

**Comment by liuxuan30** [comment]
<img width="368" alt="image" src="https://user-images.githubusercontent.com/4375169/57590724-3bacc780-7560-11e9-9804-4e84772446b7.png">
this is what I got with ChartsDemo. So I think it's fine. about the rendering, it has to be done by yourself.
