### ISSUE TITLE
How to listen to the end of a chart swipe to call a method

### ISSUE THREAD

**Issue by zuqiu123** [danielgindi/Charts#3911]
I want to refresh the corresponding interface data after the chart slide ends, so I need to listen to the chart slide end to call the method, but this method does not stop when I listen.
- (void)chartTranslated:(ChartViewBase *)chartView dX:(CGFloat)dX dY:(CGFloat)dY
I hope you can help me thank you.

**Comment by liuxuan30** [comment]
you can add your own delegate methods in your sub classes to do this.

**Comment by zuqiu123** [comment]
Can you elaborate or give an example, or do not understand a bit
