### ISSUE TITLE
The first dot doesn't show up when I use lineChart

### ISSUE THREAD

**Issue by zhangjianjun056** [danielgindi/Charts#3912]
The first dot doesn't show up when I use lineChart，Please help me, thank you.（V3.2.2  Swift4.0  Xcode10.1）

**Comment by d0x90** [comment]
same problem here

**Comment by Rumanity** [comment]
same problem...

**Comment by FominNickolai** [comment]
same problem.......

**Comment by rainyx** [comment]
same problem.......

**Comment by MrVlad001** [comment]
This looks to be fixed in #3881
