### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [danielgindi/Charts#3913]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Built the pod with Xcode 10.2

## What did you expect to happen?

No warning to convert Charts.framework to Swift 5

## What happened instead?

Xcode created a warning to migration Charts.framework to Swift 5

## Charts Environment

Charts version/Branch/Commit Number: Cocoapod version 3.2.2
Xcode version: 10.2
Swift version: 5
Platform(s) running Charts: iOS
macOS version running Xcode: 10.14.3

## Demo Project

any project running in Xcode 10.2 will display the warning.

**Comment by liuxuan30** [comment]
let's route swift 5 PRs to #3874 add anything you found missing in that PR. thanks

**Comment by jlaws** [comment]
Works great, thanks!
