### ISSUE TITLE
carthage support lagging - needs updating for Xcode 10.2 & Swift5

### ISSUE THREAD

**Issue by heckj** [danielgindi/Charts#3914]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I downloaded and opened IOSCharts with Xcode 10.2 to get an updated build for a project dependency (`Charts.xcworkspace`)

## What did you expect to happen?

I expected to be able to compile and run all the tests and demo code with Xcode 10.2

## What happened instead?

This existing carthage linkage is to the `github "facebook/ios-snapshot-test-case" "master"`, which explicitly lists SWIFT_VERSION as 3.0, no longer supported with Xcode 10.2. The specific failure is:

`carthage update`:
```
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FBSnapshotTestCase tvOS')
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/heckj/src/IOSCharts/Carthage/Checkouts/ios-snapshot-test-case/FBSnapshotTestCase.xcworkspace -scheme "FBSnapshotTestCase tvOS" -configuration Release -sdk appletvsimulator -destination "platform=tvOS Simulator,id=7CE0ED59-A3D7-4866-A9CD-D77FFA225271" -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **
```

The project appears to have moved (per comments in https://github.com/danielgindi/Charts/pull/3874) to https://github.com/uber/ios-snapshot-test-case.

I tried updating the `cartfile.private` to the latest version of that repository, with no success, and started to make my own fork updated to Swift5 to see what might be needed (https://github.com/heckj/ios-snapshot-test-case/tree/swift5). However, I don't appear to know enough about the carthage system to update and use it directly - my attempts to migrate to a variant location have failed - the local Xcodebuild compiles and doesn't fail, but running `carthage update` with my swift5 fork/branch of the project results in:

```
Failed to write to /Users/heckj/src/IOSCharts/Carthage/Build/iOS/FBSnapshotTestCase.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “FBSnapshotTestCase.framework” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/heckj/Library/Developer/Xcode/DerivedData/FBSnapshotTestCase-cmnejvoemuyoakhifvicyofllvhg/Build/Products/Release-iphoneos/FBSnapshotTestCase.framework, NSUnderlyingError=0x7fc6b76cbdb0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

## Charts Environment

**Charts version/Branch/Commit Number:** `5d0b99adb860406059e42149520ce9c0cb847feb` (master branch, current HEAD)
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running Charts:** Mac/IOS
**macOS version running Xcode:** 10.14.4

## Demo Project

- https://github.com/heckj/IOSCharts/tree/Xcode10.2
(work in progress for a PR, migrating the projects per Xcode migrator)

**Comment by juancazalla** [comment]
It seems it's already in PR: https://github.com/danielgindi/Charts/pull/3874

**Comment by liuxuan30** [comment]
use 3.3.0 or latest master
