### ISSUE TITLE
The first dot doesn't show up when I use lineChart

### ISSUE THREAD

**Issue by d0x90** [danielgindi/Charts#3915]
## What did you do?
Create a LineChart
## What did you expect to happen?
Circle on each dot on the graph

## What happened instead?
Circle is not showed up on the first element (left )

## Charts Environment
Charts version/Branch/Commit Number: latest
Swift version: 3.0
Platform(s) running Charts: ios 12
macOS version running Xcode: high sierra

![image](https://user-images.githubusercontent.com/9494313/55042827-661ee180-5001-11e9-8aff-c62064203c5f.png)

**Comment by diaoerlangdang** [comment]
me too

**Comment by FominNickolai** [comment]
same issue

**Comment by rainyx** [comment]
same issue

**Comment by MrVlad001** [comment]
same

**Comment by andreadotlopez** [comment]
I first tested the line chart in a fresh project (installed Charts manually as described in the usage section) and the first dot appears.

When I installed Charts using pods in my larger project the first dot is missing using the same code.

**Comment by nstrm** [comment]
I have the same issue

**Comment by d0x90** [comment]
solved  https://github.com/danielgindi/Charts/issues/3848

**Comment by parveencse** [comment]
pod 'Charts', '~> 3.3.0' and also pod update...it works fine
