### ISSUE TITLE
Remove slices text in pieChart

### ISSUE THREAD

**Issue by shivanand217** [danielgindi/Charts#3918]
Can you please suggest how to not show slices text on a pie chart like android has setDrawSliceText(boolean enabled).

**Comment by ishdemon** [comment]
Refer to Android repo's documentation.

**Comment by liuxuan30** [comment]
there should be switch to do that. So you can take a look at the code.

**Comment by kevinliu23** [comment]
Did anyone figure out how to remove the text in the pie chart?

**Comment by kevinliu23** [comment]
Found the solution: chartView.drawEntryLabelsEnabled = false

**Comment by mouchegmouradian** [comment]
> Found the solution: chartView.drawEntryLabelsEnabled = false

That removes the labels outside of the pie. To remove the text from the slices you need to call this:

`dataSet.drawValuesEnabled = false`

**Comment by mouchegmouradian** [comment]
> Found the solution: chartView.drawEntryLabelsEnabled = false

That's not it. To remove the text from the slices you need to call this:

dataSet.drawValuesEnabled = false
