### ISSUE TITLE
LineChartView with a line that goes backwards

### ISSUE THREAD

**Issue by davidebalistreri** [danielgindi/Charts#3919]
## What did you do?

I need to draw the FVC graph (flow-volume) for a macOS app.

The graph should represent the loop-curve which measures the amount (volume) and speed (flow) of the air that was exhaled and inhaled by a patient during a breathing test.

Example:
![image](https://user-images.githubusercontent.com/553446/55095927-43500400-50b9-11e9-8226-8f1903bd4360.png)

I managed to draw the **exhalation phase** correctly and effortlessly (in the example it starts from 0 and it goes forward and upward, reaching the Peak expiratory flow at 12 liters per seconds, then slowly decreases until it almost reaches the 6 liters maximum volume).

## What did you expect to happen?

After the exhalation phase, the graph should draw a line that goes backwards and below the x-axis, for the **inhalation phase** (in the example it starts from almost 6 liters of volume, goes backwards, reaches the -7 liters per seconds flow, then reconnects at 0).

## What happened instead?

During the inhalation phase the values go backwards. Sometimes one value is drawn properly, sometimes not, either way when a second value is passed the graph ceases to work, and it removes all drawn lines (I think it crashes).

I tried to simulate this behavior in the ChartsDemo-macOS app, by creating a simple LineChartView with these values:
```
x: 0, y: 0
x: 2, y: 2
x: 4, y: 4
x: 2, y: 6
x: 0, y: 8
```

![Schermata 2019-03-27 alle 18 05 16](https://user-images.githubusercontent.com/553446/55096835-e6ede400-50ba-11e9-9c26-c3b77f9c5948.png)

The fourth value (x: 2, y: 6) isn't drawn at all.

The fifth value (x: 0, y: 8) makes the app crash:

![Schermata 2019-03-27 alle 17 48 26](https://user-images.githubusercontent.com/553446/55096524-662ee800-50ba-11e9-8727-00458bd94bc2.png)

`Fatal error: Can't form Range with upperBound < lowerBound
`

## Charts Environment

**Charts version/Branch/Commit Number:** 3.2.2 (branch: master, commit: 5d0b99adb860406059e42149520ce9c0cb847feb)
**Xcode version:** 10.1, 10.2
**Swift version:** 4.2
**Platform(s) running Charts:** macOS
**macOS version running Xcode:** 10.14.3 (18D109), 10.14.4 (18E226)

## Demo Project

Demo project with the values described above:
[ChartsDemo-macOS-linebug.zip](https://github.com/danielgindi/Charts/files/3014458/ChartsDemo-macOS-linebug.zip)

**Comment by lucasmpaim** [comment]
Hi,

I get this error too, the error that is occurring is because your X values is not sorted on your dataset,
this is a restriction of library in both plataforms.

Something like this:
```swift
entries.sort(by: { $0.x < $1.x })
```
will fix the error

**Comment by davidebalistreri** [comment]
Hi @lucasmpaim, and thank you for your feedback!

Unfortunately I shouldn't sort the values, otherwise I'll get a wrong graph:

![Schermata 2019-04-08 alle 12 57 36](https://user-images.githubusercontent.com/553446/55719251-175c4900-59fe-11e9-80f7-b09d69aa7f7b.png)

Anyway I managed to achieve my goal by manually setting the proper "min" and "max" values in the **BarLineScatterCandleBubbleRenderer.XBounds** class:

![Schermata 2019-04-08 alle 12 56 06](https://user-images.githubusercontent.com/553446/55719363-55596d00-59fe-11e9-84e2-f28ba6cdfe36.png)

This is the resulting graph, representing the input values just as expected:

![Schermata 2019-04-08 alle 12 56 58](https://user-images.githubusercontent.com/553446/55719390-6c985a80-59fe-11e9-9520-cdd848e7d260.png)

I don't quite understand how the **XBounds class** calculates its "min" and "max" values, but if we enhance that we can support datasets that go backwards.

Let me know if I can help!

**Comment by liuxuan30** [comment]
sees we can close now

**Comment by davidebalistreri** [comment]
The bug is still there, but thank you anyway.

**Comment by TerletskyIgor** [comment]
I had the same problem.
How I solved this problem:
I needed to keep my point in order. I had two arrays. I created a dictionary in which I placed the first array as keys, the second array as values.
Then I sorted the dictionary by keys: this eliminated this problem.
//your value
let l0 = [Double]()
let l1 = [Double]()

var temp = [Double: Double]()

 for i in 0..<multiplicativeTypeDate.lambda0.count {
            if i < multiplicativeTypeDate.lambda1.count {

                let key = l0[i]
                let value = l11[i]

                temp[key] = value
            }
        }
let sortDic = temp.sorted {$0.key < $1.key}

<img width="616" alt="Screenshot 2019-11-04 at 23 31 09" src="https://user-images.githubusercontent.com/37902473/68159820-2fc42000-ff5b-11e9-98d8-69e494486ee9.png">

After rendering, the following problem arose that the function graph is filled out and inside
To fix this, I added:
line1.drawCirclesEnabled = true // Default value
line1.colors = [UIColor (red: CGFloat (0/255), green: CGFloat (0/255), blue: CGFloat (0/255), alpha: 0)]

When you set the color to transparent, you will get your schedule and it will not be filled inside
In my case there was a lot of point and all drawCircles seem like a solid line.
<img width="618" alt="Screenshot 2019-11-04 at 23 33 52" src="https://user-images.githubusercontent.com/37902473/68160020-90ebf380-ff5b-11e9-80a1-aac62da40233.png">

**Comment by YulinLiu1998** [comment]
> I had the same problem.
> How I solved this problem:
> 
> * I needed to keep the order of my points.
> * I had two arrays of points.
> * I created a dictionary. In which the first array was keys, the second array was values.
> 
> Then I sorted the dictionary by keys. It solved this problem.
> 
> ```
> //your value
> let l0 = [Double]()
> let l1 = [Double]()
> 
> var temp = [Double: Double]()
> 
>  for i in 0..<l0.count {
>     let key = l0[i]
>     let value = l1[i]
>     temp[key] = value
> }
> temp.sorted {$0.key < $1.key}
> ```
> 
> <img alt="Screenshot 2019-11-04 at 23 31 09" width="616" src="https://user-images.githubusercontent.com/37902473/68159820-2fc42000-ff5b-11e9-98d8-69e494486ee9.png">
> 
> After that, there was a problem that the function graph was filled in and inside.
> To fix this, I added:
> 
> ```
> let line1 = LineChartDataSet(entries: lineChartEntry1, label: nil)
> line1.drawCirclesEnabled = true // Default value
> line1.colors = [UIColor (red: CGFloat (0/255), green: CGFloat (0/255), blue: CGFloat (0/255), alpha: 0)]
> ```
> 
> When you set the color to transparent, you will get your function graph that won`t be filled inside.
> In my case there was a lot of point and all drawCircles seem like a solid line.
> <img alt="Screenshot 2019-11-04 at 23 33 52" width="618" src="https://user-images.githubusercontent.com/37902473/68160020-90ebf380-ff5b-11e9-80a1-aac62da40233.png">
> 
> I know that this is not the best solution =)

Sorry,I don't understand what you mean. Can you tell me more in detail?
