### ISSUE TITLE
Not Drawing Chart With Exact Axis

### ISSUE THREAD

**Issue by jayeshkanzariya** [danielgindi/Charts#3921]
In image 7000-8000 have different difference and starting value to 7000 have different difference.

in second chart it is working perfectly

![Screen Shot 2019-03-29 at 11 49 07 AM](https://user-images.githubusercontent.com/23113012/55213567-b2dd0500-5219-11e9-8280-73c5741ba849.png)

**Comment by liuxuan30** [comment]
don't understand. The chart tells nothing.
