### ISSUE TITLE
ChartUtils.swift line 225

### ISSUE THREAD

**Issue by LokiIMS** [danielgindi/Charts#3922]
Crash:ChartUtils.swift line 225

> This issue is causing crash in Charts pod file 
`22 Charts                         0x102dbc78c specialized static ChartUtils.drawText(context:text:point:attributes:anchor:angleRadians:) (ChartUtils.swift:225)
23 Charts                         0x102e60a78 specialized XAxisRendererHorizontalBarChart.drawLabels(context:pos:anchor:) (XAxisRendererHorizontalBarChart.swift:157)
24 Charts                         0x102e61828 specialized XAxisRendererHorizontalBarChart.renderAxisLabels(context:) (XAxisRendererHorizontalBarChart.swift:112)
25 Charts                         0x102e5cd10 XAxisRendererHorizontalBarChart.renderAxisLabels(context:) (XAxisRendererHorizontalBarChart.swift)
26 Charts                         0x102d76b70 BarLineChartViewBase.draw(_:) (BarLineChartViewBase.swift:258)
27 Charts                         0x102d7733c @objc BarLineChartViewBase.draw(_:) (BarLineChartViewBase.swift)
28 UIKitCore                      0x2636ea4cc -[UIView(CALayerDelegate) drawLayer:inContext:] + 464`
So please let me know how to fix this issue.

**Comment by liuxuan30** [comment]
don't understand. reopen when more details
