### ISSUE TITLE
最新版更新后的问题

### ISSUE THREAD

**Issue by 123LI** [danielgindi/Charts#3927]
open override func copyWithZone(_ zone: NSZone?) -> AnyObject
    {
        let copy = super.copyWithZone(zone) as! RealmBaseDataSet
        
        copy._results = _results
        copy._yValueField = _yValueField
        copy._xValueField = _xValueField
        copy._yMax = _yMax
        copy._yMin = _yMin
        copy._xMax = _xMax
        copy._xMin = _xMin
        
        return copy
    }

**Comment by 123LI** [comment]
open class RealmPieDataSet: RealmBaseDataSet, IPieChartDataSet
{

**Comment by 123LI** [comment]
Type 'RealmPieDataSet' does not conform to protocol 'IPieChartDataSet'

 func copyWithZone(_ zone: NSZone?) -> AnyObject。Method does not override any method from its superclass

let copy = super.copyWithZone(zone) as! RealmBaseDataSet   Static member 'copyWithZone' cannot be used on instance of type 'ChartBaseDataSet'

**Comment by XiaoArea** [comment]
I also have this situation, need I change it manually?

**Comment by 123LI** [comment]
> I also have this situation, need I change it manually?
解决了没有 😄

**Comment by liuxuan30** [comment]
RealmBaseDataSet is about Realm. So you should ask on ChartsRealm btw.

ChartsRealm didn't get updated yet, is this the reason?
