### ISSUE TITLE
Gradient and round corner in bar chart

### ISSUE THREAD

**Issue by mayankgoyal3** [danielgindi/Charts#3928]
Multiple bar chart needs to implement Gradient color in the bar and also the bar should be corner radius.

Let me know the stable branch name if that is already implemented or provide me the extension class if you can.

**Comment by qinqi777** [comment]
I have the same requestion

**Comment by liuxuan30** [comment]
there are PRs, but pending review.

**Comment by zdmjerry** [comment]
I have the same requestion

**Comment by EzioChen** [comment]
I have the same requestion
