### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

### ISSUE THREAD

**Issue by ange521** [danielgindi/Charts#3932]
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 4.0, 4.2, 5.0. This setting can be set in the build settings editor.

**Comment by simbo64** [comment]
Any update on when Charts will be updated for Swift 5? Anyone forsee an issue with me forking it and doing it myself manually?

**Comment by LeftRightHand** [comment]
> Any update on when Charts will be updated for Swift 5? Anyone forsee an issue with me forking it and doing it myself manually?

xcode 10.2 , targets -> search Swift Languange Version = Swift 4 ,  pod install --no-repo-update ->   pod 'ChartsRealm', '~> 3.1.1'

**Comment by liuxuan30** [comment]
3.3 release is already Swift 5
