### ISSUE TITLE
why？？？？？

### ISSUE THREAD

**Issue by Menrol** [danielgindi/Charts#3934]
Installing Charts (3.2.2)
Installing ChartsRealm (3.2.1)
Installing Masonry (1.1.0)
Installing Realm (3.11.2)
[!] /bin/bash -c 
set -e
sh build.sh cocoapods-setup

core is not a symlink. Deleting...
Downloading dependency: sync 3.13.3
Downloading sync failed:
	https://static.realm.io/downloads/sync/realm-sync-cocoa-3.13.3.tar.xz
	curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to static.realm.io:443

**Comment by liuxuan30** [comment]
nothing to do with us.
