### ISSUE TITLE
Fatal error: removeEntry is not implemented in ChartBaseDataSet:

### ISSUE THREAD

**Issue by kristipati** [danielgindi/Charts#3937]
In the below function delegate when I select any bar or line inside the chart I am getting a crash in release version number  3.2.2. I don't see the same crash in 3.2.1.

func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight)

When crash's below is the log.

**Fatal error: removeEntry is not implemented in ChartBaseDataSet:**

**Comment by liuxuan30** [comment]
can you try 3.3.0?
