### ISSUE TITLE
 the first point of LineChartView is not displayed, and so is demo

### ISSUE THREAD

**Issue by DKJone** [danielgindi/Charts#3938]
What can I do to be the same as the previous version ？   

| 3.2.1  LineChartView 1 |3.2.2  LineChartView 1 |
| --- | --- |
| ![Simulator Screen Shot - iPhone 8 Plus - 2019-04-10 at 14 41 43](https://user-images.githubusercontent.com/15855089/55857565-077c6a80-5ba0-11e9-9269-b35a69d80d3d.png) |![Simulator Screen Shot - iPhone 8 Plus - 2019-04-10 at 14 40 38](https://user-images.githubusercontent.com/15855089/55857623-2e3aa100-5ba0-11e9-9c0f-a9b10472ea27.png) |

**Comment by chandanaMurthy** [comment]
same here

**Comment by AravindBG** [comment]
This works for me
https://github.com/danielgindi/Charts/issues/3881#issuecomment-472646493

**Comment by DKJone** [comment]
@AravindBG It works, thanks!
