### ISSUE TITLE
Linhas de sobreposição PieChart 

### ISSUE THREAD

**Issue by AnyAmbria** [danielgindi/Charts#3942]
Estou enfrentando um problema no ios(swift), em que as linhas e valores do PieChart  ficam sobrepostos, como na imagem. 
![Screen Shot 2019-04-10 at 08 24 38](https://user-images.githubusercontent.com/42413679/55874958-2fe97200-5b6a-11e9-93c7-94d304806657.png)

alguma solução?

**Comment by liuxuan30** [comment]
English please..
