### ISSUE TITLE
Balloon Marker Swift errors

### ISSUE THREAD

**Issue by dpirpiris** [danielgindi/Charts#3947]
Hey, so I had updated xcode and was receiving errors regarding the  compile level specifically with this pod. I updated the pod and explicitly set the swift compile level which removed just about all the errors that were popping up after the update, however, there still seems to be an issue with the BalloonMarker.swift file using older syntax. Specifically with the lines 108, and 125-130:

108:
//        labelns?.draw(in: rect, withAttributes: _drawAttributes)
125-130:
//        _drawAttributes[NSFontAttributeName] = self.font
//        _drawAttributes[NSParagraphStyleAttributeName] = _paragraphStyle
//        _drawAttributes[NSForegroundColorAttributeName] = self.textColor
        
        
//        _labelSize = labelns?.size(attributes: _drawAttributes) ?? CGSize.zero

Any chance this can be updated? Seems like a quick fix. If you're busy, I can make a pull request.

Thanks

**Comment by liuxuan30** [comment]
TRY 3.3.0
