### ISSUE TITLE
xcode10.2,swift5,chart version 3.3.0

### ISSUE THREAD

**Issue by Mosaics** [danielgindi/Charts#3948]
archive error:

Undefined symbols for architecture armv7:
  "method descriptor for Charts.ChartViewBase.initialize() -> ()", referenced from:
      nominal type descriptor for aa.xxxView in xxxView.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuxuan30** [comment]
I can archive ChartsDemo-iOS without issue:
![image](https://user-images.githubusercontent.com/4375169/56627376-20911b00-6678-11e9-96c3-d632a837c796.png)

so you better check your build settings.

**Comment by kemchenj** [comment]
@liuxuan30 I create a [demo](https://github.com/kemchenj/ChartsDemo) to reproduce this compile error. Pod install and run this command in command line:

```sh
xcodebuild -workspace Demo.xcworkspace -scheme Demo | xcpretty
```

And compiler will throw an error like this:

```
▸ Linking Demo

❌  Undefined symbols for architecture arm64
> Symbol: method descriptor for Charts.ChartViewBase.initialize() -> ()
> Referenced from: l_got.$s6Charts13ChartViewBaseC10initializeyyFTq in ViewController.o

❌  ld: symbol(s) not found for architecture arm64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

 This is a simple demo, the only I've done is subclassing `CombinedChartView` and override the `initialize` method.

The access level of `initialize` method was marked as `internal` in `ChartViewBase` and `open` in `CombinedChartView`. It looks like a bug from swift compiler.

**Comment by DTown** [comment]
@Mosaics Did you solve this by editing the settings?
I get the exact same message with xCode10.3 and after switching to 3.3.0 & Swift5.
I cleared everything, also reinstalled my pods completely new but still have this message on archiving. 
I do not have very special build settings, that should cause this. 
----------------
Undefined symbols for architecture armv7:
  "method descriptor for Charts.ChartViewBase.initialize() -> ()", referenced from:
      nominal type descriptor for XXX.XXXXXXXView in XXXXXXXView.o
ld: symbol(s) not found for architecture armv7
----------------
