### ISSUE TITLE
incorrect display in LineChartView When all yAxis data being 0

### ISSUE THREAD

**Issue by EJParadise** [danielgindi/Charts#3950]
<img width="888" alt="WeChat2965381e62cfb2e4b4fb9b2ad079a654" src="https://user-images.githubusercontent.com/16640653/56283867-7b40e900-6145-11e9-96b4-d07465b72faf.png">

**Comment by EJParadise** [comment]
if I set leftAxis.minimumValue = 0.0,  the line goes to zero. but the leftAxis values being all 0;

**Comment by liuxuan30** [comment]
If I try it with ChartsDemo, I get this:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/4375169/57591195-c7bfee80-7562-11e9-8406-f23951990276.png">
So I assume it's correct by design. as for your issue, I suggest you try latest code.
