### ISSUE TITLE
demo can not run

### ISSUE THREAD

**Issue by ange521** [danielgindi/Charts#3951]
dyld: Library not loaded: /usr/lib/libauto.dylib
  Referenced from: /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
  Reason: no suitable image found.  Did find:
	/usr/lib/libauto.dylib: mach-o, but not built for iOS simulator

**Comment by ange521** [comment]
sudo mkdir '/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS8.4.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift'

**Comment by liuxuan30** [comment]
nothing to do with us.
