### ISSUE TITLE
drawing asynchronous

### ISSUE THREAD

**Issue by milkatgit** [danielgindi/Charts#3952]
Hi, I have two questions.1. Is the drawing asynchronous? 2. How to know that a drawing has been completed.

**Comment by liuxuan30** [comment]
You must know all UI related tasks are performed on main thread, right?

There are plenty of methods or design patterns to let  you know when the drawing is complete. I don't think we provide one yet; not getting any requirement for that. Besides, what's your demand to know it's finished?

By concept, I don't think UIKit or CoreGraphics is designed this way.
