### ISSUE TITLE
No Such Module 'Charts'

### ISSUE THREAD

**Issue by dmacpro91** [danielgindi/Charts#3955]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to compile the stock ChartsDemo-iOS.xcodeproj project.

I also tried removing and readding the embedded binary after a clean.  I've been messing with getting this demo project to compile for a few hours now and can't get it working.

## What did you expect to happen?

For it to compile.

## What happened instead?

1 error "No such module 'Charts'".

## Charts Environment

**Charts version/Branch/Commit Number:** 3.3
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running Charts:** 12.2 iOS simulator
**macOS version running Xcode:** 10.14.3

## Demo Project

This is with the current stock iOS Charts demo.

**Comment by dmacpro91** [comment]
The only workaround I've found so far is to manually add the path to the framework to 'Framework Search Paths'.  Hopefully someone can point out a more elegant solution.

**Comment by liuxuan30** [comment]
There is no reason you cannot compile ChartsDemo if you didn't change anything.

Can you post the log and screenshot? We never found this is an issue.
