### ISSUE TITLE
Charts Pagination

### ISSUE THREAD

**Issue by ZaidSA** [danielgindi/Charts#3957]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Looked for charts pagination.

## What did you expect to happen?

![T7t1g](https://user-images.githubusercontent.com/21195104/56420597-41deb980-62bc-11e9-9475-135cc5269113.jpg)

## What happened instead?

No pagination feature found.

## Charts Environment

**Charts version/Branch/Commit Number:*3.2.2*
**Xcode version:*10.1*
**Swift version:*4.2*
**Platform(s) running Charts:*iOS*
**macOS version running Xcode:*10.14.4*

**Comment by liuxuan30** [comment]
you are welcome to add this feature.
