### ISSUE TITLE
Horizontal Bezier Line Graph Not Drawing Through All Points

### ISSUE THREAD

**Issue by amkomatz** [danielgindi/Charts#3960]
## What did you do?

Set `LineChartDataSet.mode` to `.horizontalBezier`. 

## What did you expect to happen?

The line would connect all points in a horizontal-bezier fashion.

## What happened instead?

The first point is being skipped and is not connected to the line at all.
![Screen Shot 2019-04-22 at 9 28 51 AM](https://user-images.githubusercontent.com/39735311/56503690-3bcb2180-64e4-11e9-943e-28e1333f9442.png)

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.3

## Demo Project

[ChartsTesting.zip](https://github.com/danielgindi/Charts/files/3103529/ChartsTesting.zip)

**Comment by shrop21** [comment]
![Screen Shot 2019-04-25 at 12 56 06 PM](https://user-images.githubusercontent.com/14985674/56757307-8903f900-6759-11e9-9acd-28eda917708c.png)

I'm having the same issue after this most recent update. The screenshot above is also displaying the issue that the first dot is not displaying either.

Thank you!

**Comment by samassaroni** [comment]
I'm having the same issue. In the first screenshot, the leftmost point is missed. In the second, by scrolling to the left slightly and bringing the next point into the view, the line is adjusted to correctly hit the previously missed point.

![Screen Shot 2019-04-26 at 11 52 43 AM](https://user-images.githubusercontent.com/28791404/56820467-f6775e80-6819-11e9-8bfd-74933004a764.png)
![Screen Shot 2019-04-26 at 11 52 54 AM](https://user-images.githubusercontent.com/28791404/56820468-f6775e80-6819-11e9-9225-dbbc752db2ca.png)

**Comment by xeyuez** [comment]
Me too, the second point will not be drawn!!!

<img width="354" alt="WX20190509-134147@2x" src="https://user-images.githubusercontent.com/15902056/57429833-4c0f2a80-7260-11e9-803c-0acdbfc1436b.png">
<img width="337" alt="WX20190509-134202@2x" src="https://user-images.githubusercontent.com/15902056/57429834-4ca7c100-7260-11e9-9bac-c208174cfeae.png">
<img width="349" alt="WX20190509-134213@2x" src="https://user-images.githubusercontent.com/15902056/57429835-4ca7c100-7260-11e9-997a-7873a6cd44fa.png">

**Comment by xeyuez** [comment]
I am using version 3.2.2.
<img width="755" alt="WX20190509-155131@2x" src="https://user-images.githubusercontent.com/15902056/57437499-7ff44b00-7274-11e9-8a68-bba6bb7b90ea.png">
I found that the problem is here.
Commented on ".dropFirst()" , the view is fine
However, I don’t know if other problems will occur.




In version 3.1.1, the code does not appear this problem. as shown
![image](https://user-images.githubusercontent.com/15902056/57437511-8682c280-7274-11e9-9e63-f4ebda62f09b.png)

**Comment by Fedenieto90** [comment]
I'm having the same problem. It worked ok with older versions, but I had to update it to support swift 4 and it is not working anymore. Any hints?

**Comment by liuxuan30** [comment]
Can someone help if this happens in master?

**Comment by liuxuan30** [comment]
are these the same issue? https://github.com/danielgindi/Charts/issues/4073

**Comment by liuxuan30** [comment]
Hi there, I tried with latest master, and seems it's fine:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/4375169/62588542-a029b980-b8f8-11e9-9f0a-250177a5eae8.png">
it's horizontal bezier though I use 1,2,3...10 to see if any entry is missed, but they are all there.

can someone double check?
