### ISSUE TITLE
折线图能分页吗 就是滑动到最左边 网络请求再加载数据

### ISSUE THREAD

**Issue by wjx1018960145** [danielgindi/Charts#3961]
折线图能分页吗 就是滑动到最左边 网络请求再加载数据

**Comment by liuxuan30** [comment]
not really. It's drawn in a plain UIView, not a scroll view.

**Comment by wjx1018960145** [comment]
可以设置折线图自动滑动到最右边吗 就是首先显示最大时间的数据
