### ISSUE TITLE
version 3.3 using spm results invalid string error

### ISSUE THREAD

**Issue by wangkezun** [danielgindi/Charts#3962]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

use spm to get version 3.3

## What did you expect to happen?

spm download version 3.3 as expected

## What happened instead?

spm shows that ```Invalid version string: 3.3```

I think spm supported version number should be like 'x.y.z', not 'x.y'

## Charts Environment

**Charts version/Branch/Commit Number:3.3
**Xcode version:10.2.1
**Swift version:5.0
**Platform(s) running Charts:macos
**macOS version running Xcode:10.14.4

**Comment by liuxuan30** [comment]
I have re-tagged the master. try again.
