### ISSUE TITLE
zero value in bar chart

### ISSUE THREAD

**Issue by JavidDavoud** [danielgindi/Charts#3967]
Hi 

When my values are zero the bar chart has bad style

![Simulator Screen Shot - iPhone Xʀ - 2019-04-24 at 17 08 07](https://user-images.githubusercontent.com/48619317/56660000-bd24de80-66b3-11e9-9c00-af8222163f9c.png)

 what do I do to fix this problem? 
Many thanks

**Comment by liuxuan30** [comment]
I don't see this with ChartsDemo 
<img width="375" alt="image" src="https://user-images.githubusercontent.com/4375169/57591431-e8d50f00-7563-11e9-82fa-9ffb4a18513a.png">
