### ISSUE TITLE
Installing version 3.3  from Pods not found

### ISSUE THREAD

**Issue by stevencurtis** [danielgindi/Charts#3968]
Looks like an issue, installing the following does not work through pods
  pod 'Charts'
  pod 'Charts', '3.3'
  pod 'Charts', '3.3.0'
  pod 'Charts', '3.3.0.'

warning: Could not find remote branch v3.3 to clone.
fatal: Remote branch v3.3 not found in upstream origin

so had to specify the previous version
  pod 'Charts', '3.2.2'

**Comment by liuxuan30** [comment]
```
      - 3.2.0 (2018-09-17 02:07:03 UTC)
      - 3.2.1 (2018-10-08 20:02:33 UTC)
      - 3.2.2 (2019-02-13 02:17:58 UTC)
      - 3.3.0 (2019-04-24 02:35:02 UTC)
```
I re-uploaded 3.3.0 yesterday. I don't know why you cannot find it.

**Comment by benoist** [comment]
For me running pod update worked
