### ISSUE TITLE
change line chart legend text color

### ISSUE THREAD

**Issue by JasperCDR** [danielgindi/Charts#3971]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
I attempted to change the text colors of each of the legend entries.
## What did you expect to happen?
I expected to be able to change each of the entries' text colors, in my case it would correspond like so:
Entry 1: "Solves", color: UIColor.blue
Entry 2: Average of Five", color: UIColor.orange
## What happened instead?
I could not find the relevant customizable property that allowed for changes to the color of each label in the legend. Instead, there was one that changed the color of all labels at once (Chart.legend.textColor).

## Charts Environment

**Charts version/Branch/Commit Number: Version 3.3.0**
**Xcode version: 10.2.1**
**Swift version: 4**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: Mojave**

**Comment by liuxuan30** [comment]
@objc open var font: NSUIFont = NSUIFont.systemFont(ofSize: 10.0)
    @objc open var textColor = NSUIColor.black
