### ISSUE TITLE
Charts 3.3.0 not running on Xcode 10.2

### ISSUE THREAD

**Issue by croossin** [danielgindi/Charts#3972]
## What did you do?

Installed `Charts 3.3.0` via cocoapods 

## What did you expect to happen?

It to compile on Xcode 10.2

## What happened instead?

Received 17 errors - mostly `'common' has been renamed to 'RunLoopMode.commonModes'`

## Charts Environment

**Charts version/Branch/Commit Number:** 3.3.0
**Xcode version:** 10.2
**Swift version:** 5
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.4

## Demo Project

NA

## Screenshot
![Screen Shot 2019-04-25 at 8 35 11 AM](https://user-images.githubusercontent.com/7241069/56748880-78da2280-6735-11e9-972a-3d22021eca24.png)

**Comment by liuxuan30** [comment]
check your swift versions. nothing wrong with the library.

**Comment by MoennigQ** [comment]
how to fix it, I have the same bug

**Comment by chiseller** [comment]
how to fix it, I have the same bug
