### ISSUE TITLE
PieChart highlightEnabled flag operation is reverse of setting

### ISSUE THREAD

**Issue by drewster99** [danielgindi/Charts#3975]
PieChartView / PieChartDataSet.highlightEnabled boolean flag works the opposite of how one would expect.

Setting this flag to true DISABLES highlighting.
Setting it to false ENABLES highlighting.  

I would expect it to be reversed.

Seems like a bug.

## What did you do?

let dataset = PieChartDataSet()
dataset.highlightEnabled = false

## What did you expect to happen?

I expected highlighted to be disabled.

## What happened instead?

Highlighting was enabled.

## Charts Environment

**Charts version/Branch/Commit Number:** 34dafbc6aaac4316656748f1a864426ac42e3d2d
**Xcode version:**  10.2
**Swift version:**  5.0
**Platform(s) running Charts:**  iOS 12.2
**macOS version running Xcode:** 10.14.4

## Demo Project

(trivial, as above)

**Comment by liuxuan30** [comment]
Thanks for reporting. it should be fixed in #3996

**Comment by drewster99** [comment]
Ok it's extra weird.  It works normally if markers/annotations are on, but works reversed if they are off.
