### ISSUE TITLE
this version is 3.2.2 in pods, this version has problem

### ISSUE THREAD

**Issue by KevinZK** [danielgindi/Charts#3977]
> ℹ Please fill out this template when filing an issue.
i create a CombinedChartView, draw a lineData and candleData，candle is unable to draw,.

I checkde  Demo ,i found this code "guard
            let dataProvider = dataProvider,
            let chart = dataProvider as? CandleStickChartView
            else { return }" in this function "drawDataSet"  at CandleStickChartRenderer this file,
run this here ，Always return， ”let chart = dataProvider as? CandleStickChartView“  because type mismatch .but The demo is not has this code .
I guess this is not the latest version. I modified this code， candle is able drawed.

I hope to update the version as soon as possible for pods.

ℹ Please replace this with what you did.  

I modified this code，

ℹ Please replace this with what you expected to happen.  

I modified this code， candle is able drawed.

ℹ Please replace this with of what happened instead.  

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:10.1
**Swift version:4.2
**Platform(s) running Charts:iphone 8

![image](https://user-images.githubusercontent.com/15150546/56858209-391b7100-69a9-11e9-8b87-386c6df115d7.png)

**Comment by liuxuan30** [comment]
please reorganize your question. I cannot understand what's the issue.

**Comment by KevinZK** [comment]
> please reorganize your question. I cannot understand what's the issue.

very sorry，the v3.2.2 ，CombinedChartView cannot draw candleStick 。

**Comment by liuxuan30** [comment]
refer ChartsDemo and maybe use 3.3.0
