### ISSUE TITLE
Value labels are not always showing in horizontal bar chart

### ISSUE THREAD

**Issue by melkon90** [danielgindi/Charts#3981]
## What did you do?

I'm using a horizontal bar chart to show some data. In my case, I've created an array with key value pairs. I've set the setDrawValues to true so that I can see the value labels next to the bar. 

## What did you expect to happen?

I expect to see the value labels next to the bars 

## What happened instead?

Depending on the values I provide, sometimes I can see the labels and other times I can't. For example:
This input shows the value labels (the difference is the value in the first key value pair): 
        let test: [(key: String, value: Double)] = [(key: "123", value: 10), (key: "456", value: 152), (key: "333", value: 153), (key: "890", value: 20)]

This input does not show the value labels: 
        let test: [(key: String, value: Double)] = [(key: "123", value: 30), (key: "456", value: 152), (key: "333", value: 153), (key: "890", value: 20)]

The difference is (what I have found till now is) that the array that works I get a false in this if statement within the HorizontalBarChartRenderer and a true in the other case: 
                        if !viewPortHandler.isInBoundsX(rect.origin.x)
                        {
                            continue
                        }
## Charts Environment

**Charts version/Branch/Commit Number:** 3.3.0
**Xcode version:** 10.2.1 (10E1001)
**Swift version:** 4.2/5
**Platform(s) running Charts:** iOS 11.2/12.2
**macOS version running Xcode:**

## Demo Project

https://github.com/melkon90/Charts-ValueLabelsNotAlwaysShowing

## Images
<img width="535" alt="Screenshot 2019-05-01 at 12 01 09" src="https://user-images.githubusercontent.com/50167575/57012892-edff9900-6c08-11e9-9798-25682332f0cb.png">
<img width="535" alt="Screenshot 2019-05-01 at 12 01 33" src="https://user-images.githubusercontent.com/50167575/57012901-f2c44d00-6c08-11e9-9d0f-5e1d4a633966.png">

**Comment by melkon90** [comment]
I don't know why, but the value labels are shown when I change the pod version to 3.2.2. But it only works in the sample project that I've provided here, but not in my own project. Perhaps this info might help you find the issue..

**Comment by liuxuan30** [comment]
please try latest version. I remember we had some bug fix for horizontal bar chart recently.

**Comment by MelkonYoussif** [comment]
Yes I'm sure. See the demo project that I've uploaded. Currently, I've solved this problem by adding 
`leftAxis.axisMinimum = 0`

**Comment by waveChand** [comment]
> Yes I'm sure. See the demo project that I've uploaded. Currently, I've solved this problem by adding
> `leftAxis.axisMinimum = 0`

Thank you, This solution worked.
