### ISSUE TITLE
compiling for iOS 8.0, but module 'Charts' has a minimum deployment target of iOS 8.4:

### ISSUE THREAD

**Issue by shh230** [danielgindi/Charts#3992]
## What did you do?

I downloaded and opened IOSCharts with Xcode 10.2 to get an updated build for a project dependency (Charts.xcworkspace)

## What did you expect to happen?

I expected to be able to compile and run project code on ios8.0 and above using Xcode 10.2.

## What happened instead?

![image](https://user-images.githubusercontent.com/38716757/57498800-e9756780-730f-11e9-9c0b-da57a8c01763.png)

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:10.2
**Swift version:swift 5.0
**Platform(s) running Charts:Mac/IOS
**macOS version running Xcode:Mac os 10.14.4

**Comment by liuxuan30** [comment]
> 'Charts' has a minimum deployment target of iOS 8.4

bump your iDevice iOS version.
