### ISSUE TITLE
BarChartView shows on UI when y value is zero

### ISSUE THREAD

**Issue by txm5586** [danielgindi/Charts#4000]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I'd like to know if it's possible to the draw a bar just to indicate the value zero. 
By using a `BarChartView`, I'm able to achieve this result:

![IMG_2423](https://user-images.githubusercontent.com/34381292/57706251-c1ea0c00-763b-11e9-8b30-d480d5042d49.jpg)

Notice that on "jan" the positive and negative values are zero. But visually, it doesn't show anything (since is zero of course)

## What did you expect to happen?

I want a a bar indication even when value is zero. Like this:

![IMG_2423](https://user-images.githubusercontent.com/34381292/57706432-1bead180-763c-11e9-88f7-2144f6a0126a.jpg)

Is it possible? Thank you.

## Charts Environment
**Charts version/Branch/Commit Number:** 3.2.2
**Xcode version:** 10.1
**Swift version:** 4.2
**Platform(s) running Charts:** iPhone 6s Plus
**macOS version running Xcode:** macOS 10.14.5 (Mojave)

**Comment by shivamKp** [comment]
I am also trying to do the same thing .

**Comment by liuxuan30** [comment]
then you have to modify the code yourself like provide a small rect if rect is zero.
