### ISSUE TITLE
Line chart issue

### ISSUE THREAD

**Issue by dodia119** [danielgindi/Charts#4005]
## What did you do?

ℹ I'd like to know if it's possible to the draw a value break in line chart
By using a LineChartView, I'm able to achieve this result:

![IMG_42F5EB1A7FAE-1](https://user-images.githubusercontent.com/31475393/58178926-be522700-7cc4-11e9-8dd0-ecb61ddbd2c4.jpeg)

## What did you expect to happen?

ℹ I want below result :
![result](https://user-images.githubusercontent.com/31475393/58178793-7501d780-7cc4-11e9-889f-0f3393da70c3.png)

is it possible thanks 

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:*10.1*
**Swift version:*4.0*
**Platform(s) running Charts:*iPhone*
**macOS version running Xcode:* 10.14.4*

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
![Screenshot 2019-05-22 at 6 30 53 PM](https://user-images.githubusercontent.com/31475393/58179575-189fb780-7cc6-11e9-9e9a-323c2e8791f5.png)
![Screenshot 2019-05-22 at 7 16 57 PM](https://user-images.githubusercontent.com/31475393/58179666-4553cf00-7cc6-11e9-82d4-6ef547e7fa39.png)
![Screenshot 2019-05-22 at 7 17 05 PM](https://user-images.githubusercontent.com/31475393/58179667-45ec6580-7cc6-11e9-9823-125e7d74a8d9.png)

**Comment by dodia119** [comment]
Any Solution ?

**Comment by liuxuan30** [comment]
from your screenshot, I could only say you can subclass it and use CoreGraphics to draw it yourself
