### ISSUE TITLE
BarChartRenderer FatalError: Index out of range

### ISSUE THREAD

**Issue by francescodestino92** [danielgindi/Charts#4013]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Hello everyone, i used a `BarChartView` inside a `UITableViewCell`, I have two section in my `UITableView` and 1 row for section, the BarChart in first section have 4 index, chart in second section got 3 index,  every time i reload the view i reload the UITableView with new data for my charts and i got the error on line 790 (`let range = e.ranges?[high.stackIndex]`) of file `BarChartRenderer` `Fatal error: index out of range`
This error doesn't appear every time, but only after few times i reload my view.

## What did you expect to happen?

The view to reload normally without crash

## What happened instead?

The app crash in that line

## Charts Environment

**Charts version/Branch/Commit Number:** 3.3.0
**Xcode version:** 10.2.1
**Swift version:** 5
**Platform(s) running Charts:** Every iPad
**macOS version running Xcode:** Mojave 10.14.5

## Demo Project

I can't give you the repository because it's a work project and i can't share it, but I can show some images
![Schermata 2019-06-04 alle 16 35 53](https://user-images.githubusercontent.com/51373575/58888219-5ac5f180-86e7-11e9-8264-59f063288b6c.png)
![Schermata 2019-06-04 alle 16 36 09](https://user-images.githubusercontent.com/51373575/58888220-5ac5f180-86e7-11e9-8740-8a60d7f68d51.png)

**Comment by liuxuan30** [comment]
Have your tried anything like calling chart.clear() or just re-set the chartData. normally it's beyond our scope to answer this. It's your duty to figure out what's causing the OOB situation.
