### ISSUE TITLE
Cannot subclass LineChartRenderer with Clang 11

### ISSUE THREAD

**Issue by fpg1503** [danielgindi/Charts#4018]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹCreate a new Xcode Project (i.e. Single View iOS Application)
ℹ Build a framework out of v3.2.0
ℹ Create an iOS Framework Target
ℹ Create a file inside this Target that subclasses `LineChartRenderer`
ℹ Create a bridging header on the Application Target that imports the generated Objective-C framework module header
ℹ Build

## What did you expect to happen?

ℹ The application builds and runs just fine

## What happened instead?

ℹ Clang emits the following error:
`<#DerivedDataPath#>/<#DebugProduct#>/ChartsFramework.framework/Headers/ChartsFramework-Swift.h:204:22`: Cannot find interface declaration for '`LineChartRenderer`', superclass of '`Trigger`'

## Charts Environment

**Charts version/Branch/Commit Number:** `3.2.0` (also happens on `3.3.0`, but `3.2.0`is better to highlight the issue since I can build in on older versions of Xcode just fine)
**Xcode version:** Version 11.0 beta (11M336w)
**Swift version:** Apple Swift version 5.1 (swiftlang-1100.0.38.29 clang-1100.0.20.14)
**Clang version:** Apple clang version 11.0.0 (clang-1100.0.20.17)
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** macOS Mojave Version 10.14.5 (18F132)

## Demo Project

ℹ https://github.com/fpg1503/ObjectiveCModuleBug

## Notes

ℹ This seems to be a bug in the Clang Compiler, I've already filed a radar but I thought it'd be interesting to share it here in case anyone stumbles upon the same issue.

**Comment by liuxuan30** [comment]
have you tried https://github.com/danielgindi/Charts/pull/4017?
