### ISSUE TITLE
Last xAxis label cutting

### ISSUE THREAD

**Issue by iOSVikas** [danielgindi/Charts#4023]
I am using Line Chart view In my demo application.
I have set the axis to bottom of chart view  

xAxis values should be displayed properly
It is showing proper values for all labels except last label. Its cutting the text on the last label.
Example:: I want to display “28May”, it displays “28Ma” and half “y”
## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:** 10.2
**Swift version:** 4
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.14.5

I have not added code to gut hub but I am sharing screenshot indicating issue.
![8860543B-D2E8-40FC-8419-1ADE98402DA7](https://user-images.githubusercontent.com/15924692/59292496-dbae5b80-8c9a-11e9-9db9-0d25aab173fc.jpeg)

**Comment by Silvia4** [comment]
I have the same problem, and using avoidFirstLastClippingEnabled causes misunderstanding in matching labels with values.

**Comment by chakaban** [comment]
ChartView.extraRightOffset = 30
     ChartView.extraLeftOffset = 10
     ChartView.extraTopOffset = 10

working for me
