### ISSUE TITLE
Last value and highlight/selected values in candlestick chart

### ISSUE THREAD

**Issue by junaid4art** [danielgindi/Charts#4036]
I am trying to add two last value label functionality for candlesticks chart. Also when moving the highlighted value it should display its values on x-axis and y-axis. 
Also the last value of candle which has a verticle green line and its value on the y-axis. 
Highlighted by me with red circles

What I am looking for is 
<img width="572" alt="Screenshot 2019-06-20 at 8 56 52 PM" src="https://user-images.githubusercontent.com/50867955/59863791-e3f34e80-939e-11e9-9c10-ca34dd0c4bbd.png">

a reference chart is here. 
https://www.tradingview.com/chart/

**Comment by junaid4art** [comment]
This is what I would do with this lib.
<img width="666" alt="Screenshot 2019-06-20 at 9 21 14 PM" src="https://user-images.githubusercontent.com/50867955/59864971-5b29e200-93a1-11e9-901e-fa1a0425b55b.png">

**Comment by liuxuan30** [comment]
You should be able to customize using ChartLimitLine, and ChartMarker
