### ISSUE TITLE
leftAxis line disappears when filling area between two line charts.

### ISSUE THREAD

**Issue by hachinobu** [danielgindi/Charts#4037]
## What did you do?
i use filling area between two line charts.

## What did you expect to happen?
A fill should appear between the two line graphs, and the leftAxis line should appear.

## What happened instead?
leftAxis line disappears.

|not filled|filled|
|:--:|:--:|
|![Simulator_Screen_Shot_-_iPhone_X_-_2019-06-21_at_11_41_31](https://user-images.githubusercontent.com/1317847/59896351-2e1e1380-9423-11e9-8515-a077341ca8e5.png)|![Simulator_Screen_Shot_-_iPhone_X_-_2019-06-21_at_11_42_06](https://user-images.githubusercontent.com/1317847/59896356-324a3100-9423-11e9-9d1c-c49cc1589d1e.png)|

ℹ Please replace this with of what happened instead.  

## Charts Environment

**Charts version/Branch/Commit Number: 3.3.0**
**Xcode version:10.2**
**Swift version:5.0**
**Platform(s) running Charts:iOS 12.2**
**macOS version running Xcode: 10.14.5**

Is there an easy way to solve this problem?

Is it better to customize it according to IFillFormatter or make it inherit from LineChartRenderer?

**Comment by hachinobu** [comment]
To solve this problem, it is necessary to advance the timing of calling renderer.drawData(context: context) in the draw(_ rect: CGRect) method of BarLineChartViewBase.

However, I am worried about the degradation caused by this change.

I will send a PR if there is no problem, how is it?

```BarLineChartViewBase.swift

    // BarLineChartViewBase.swift
    open override func draw(_ rect: CGRect)
    {
        super.draw(rect)

        guard data != nil, let renderer = renderer else { return }
        
        let optionalContext = NSUIGraphicsGetCurrentContext()
        guard let context = optionalContext else { return }

        // execute all drawing commands
        drawGridBackground(context: context)
        renderer.drawData(context: context) // <-- solve this issue.

```

![Simulator Screen Shot - iPhone X - 2019-06-22 at 16 18 54](https://user-images.githubusercontent.com/1317847/59960825-73b50c00-9509-11e9-9a0a-b5b9dab40536.png)

**Comment by liuxuan30** [comment]
please send us a PR, thanks
