### ISSUE TITLE
Line chart line color array issue

### ISSUE THREAD

**Issue by amaanmakhani** [danielgindi/Charts#4052]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

What I need to happen is the line connecting dots to change between data points. So what I am trying to do is if it is a negative slope the line connecting the dots is red, if not the line would be green.

What I tried to do it set the dataset.colors and add many colors in the array so it alternates that pattern.

## What did you expect to happen?

The colors of the line should have alternated, however, it does not.

## What happened instead?

It chooses the first color in the array and displays that.

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: 10.2
**Swift version:3.3.0
**macOS version running Xcode: 10.14.5

**Comment by MiZhen007** [comment]
yes, exactly, it does not support alternate color in one line, instead, I create multiple lines, and combined them by different X values, you could set different color for different sub lines
