### ISSUE TITLE
iOS13 port

### ISSUE THREAD

**Issue by appsird** [danielgindi/Charts#4056]
I receive numerous new warnings when compiling under iOS13 Xcode Version 11.0 beta 3 (11M362v) - see below. Most of the warnings regard var which should be let.

Would appreciate an iOS13 compatible update.

<img width="699" alt="Screen Shot 2019-07-03 at 1 04 57 PM" src="https://user-images.githubusercontent.com/8471833/60621872-bb525800-9d93-11e9-8c78-4bd62f8bb039.png">

**Comment by liuxuan30** [comment]
there is PR for it. but chill, don't have to upgrade
