### ISSUE TITLE
Build error on Xcode 11 beta 3 - macOS app

### ISSUE THREAD

**Issue by MoonAndEye** [danielgindi/Charts#4071]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Add charts from Swift package manager

## What did you expect to happen?

Build successfully and run the app

## What happened instead?

Build error, there are 63 errors need to be modify

<img width="265" alt="螢幕快照 2019-07-16 下午3 54 51" src="https://user-images.githubusercontent.com/9646258/61277478-d5088c00-a7e4-11e9-9964-ea92ef5b2c32.png">

## Charts Environment

**Charts version/Branch/Commit Number:** 3.3.0/master
**Xcode version:** Xcode 11 beta 3
**Swift version:** 5
**Platform(s) running Charts:** macOS App
**macOS version running Xcode:** 10.15 beta 3

## Demo Project

[ChartsTestSwiftPackageManager.zip](https://github.com/danielgindi/Charts/files/3395994/ChartsTestSwiftPackageManager.zip)

**Comment by waterskier2007** [comment]
same issue in Xcode 11 beta 4

**Comment by arakweker** [comment]
same issue here with Xcode 11 beta 4.
can you please share your planning for supporting Xcode 11 / SwiftUI?

**Comment by mickspecial** [comment]
Xcode 11 beta 4 - same issues as above using SPM

**Comment by myanalysis** [comment]
I was so excited to start using SwiftUI but without Charts I am screwed.  Bummer.
Hope it will be updated soon - until then my plans are on hold.
Good luck.

**Comment by liuxuan30** [comment]
Xcode 11 will only be supported once it's released. We don't have the manpower to support  betas, and not efficiency. 

There is a PR for it I remember, so you could use that one. But generally we don't want to get involved a lot in beta.

With this in mind, you are on your own for Xcode betas.. And welcome to file PR for us. I'm sorry but this is the best we can offer. We have to work for living :(

For SwiftUI - it's a good one but seems we need a total rewrite, and this should not happen in near future. But it's my interest to keep an eye on.
