### ISSUE TITLE
No chart data available (displaying large data sets)

### ISSUE THREAD

**Issue by varunjitsingh6410** [danielgindi/Charts#4075]
Hi all, I am attempting to generate a line chart but keep getting a no chart data message. I have tested the code and made sure the data is present. 

During one of the tests I attempted to print out the contents of dataPoints (declaration: var dataPoints: [ChartDataEntry] = []) which caused huge lag in the console and was not finished printing after ~10 minutes. 

The data set has 162239 pairs of X and Y coordinates. My theory is that the large size of the data set is the issue based on the laggy print statement described above and the fact the code works on smaller data sets. 

The code structure is something as follows if that helps: 
1) Populate dataPoints with X/Y coordinates 
2) Initialize LineChartDataSet with dataPoints 
3) Initialize LineChartData object with the set 
4) Set graph.data equal to the data object 

Print statements set between the above steps in my code print in a reasonable time frame so my guess is that its something in the Charts visualization process that's causing my bug. The code needs to be able to plot around ~4 million data points by the end of the project. 

Are there any work arounds that will let me display large data sets using Charts? I can not sacrifice any of the data points due to the nature of the project. Thank you in advance for any assistance!

**Comment by LiuZhangpeng** [comment]
I have the same problem like you, but I only have 2188 points. I can feel that my phone is very hard to show my view. I can easily display 400 points.

**Comment by varunjitsingh6410** [comment]
Hi Liu, I am still seeking a solution. Did you figure anything out?

**Comment by liuxuan30** [comment]
>The data set has 162239 pairs of X and Y coordinates

I doubt you can draw this on a smart phone screen... just sampling it to 1622 or smaller

**Comment by varunjitsingh6410** [comment]
I was able to visualize the data set when I switched it from a line to a scatterplot. I tested the scatterplot with data up to 4 million X-Y pairs, although it started to lag noticeably once we got into the millions.

**Comment by LiuZhangpeng** [comment]
> Hi Liu, I am still seeking a solution. Did you figure anything out?

I tried another way. No matter how many points I have, I only show 200 points. Users need to scroll the view to see more.
After I set data to the charts view, call the method  [_lineView setVisibleXRangeMaximum:200];
Search "setVisibleXRangeMaximum" in your project and try it
