### ISSUE TITLE
Compiling Chart with Swift 5.1 raises compilation error

### ISSUE THREAD

**Issue by aqjune** [danielgindi/Charts#4090]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Compiling Chart with Swift 5.1 raises compilation error

## What did you expect to happen?

ℹ Compiles successfully

## What happened instead?

ℹ Has following errors:

```
~/Charts/Source/Charts/Utils/ChartUtils.swift:76:22: error: static member 'log10' cannot be used on instance of type 'Double'
        let d = ceil(log10(self < 0 ? -self : self))
                     ^~~~~
                     Double.
~/Charts/Source/Charts/Utils/ChartUtils.swift:98:26: error: static member 'log10' cannot be used on instance of type 'Double'
        return Int(ceil(-log10(i))) + 2 
                         ^~~~~
                         Double.

```

## Charts Environment

**Charts version/Branch/Commit Number:**: 8c28cfa5dcbef6e528bba5ccdd6247ff1c372475
**Swift version:**: swift-DEVELOPMENT-SNAPSHOT-2019-07-30-a.xctoolchain

**Comment by liuxuan30** [comment]
we don't handle beta versions.

**Comment by BinaryHammer** [comment]
@liuxuan30 Now it is released.

**Comment by liuxuan30** [comment]
I have merged #4153

**Comment by BinaryHammer** [comment]
@liuxuan30 Yay it works again in my macOS app. Thanks.

**Comment by liuxuan30** [comment]
yep, but pod still need wait. I have two issues pending before releasing a new one.
