### ISSUE TITLE
Line charts: Line sections disappear when zoomed in (has PR).

### ISSUE THREAD

**Issue by 4np** [danielgindi/Charts#4099]
# Line sections disappear when zoomed in

Regularly, line sections of line-based charts (line, area) will disappear when zoomed in (make sure `scaleXEnabled = true`, `scaleYEnabled = true` and `dragEnabled = true`). 

Possibly related issues: #3253, #3933, #3898?

# Steps to reproduce

1. Launch the iOS Charts demo app
2. Open the `Line Chart` demo
3. Zoom in deep (so that the left y-axis ranges from 20 to 70, zoom level > 3.8)
4. Drag the chart so that a sharp line corner will _just_ go below the x-axis
5. Observe the left line section will disappear

![issue-4099](https://user-images.githubusercontent.com/1049693/62709905-a00fe380-b9f6-11e9-80c9-81bbc83f34a3.gif)

(View the [full video](https://www.dropbox.com/s/c8fbmt8m7i5q31x/iOS%20Charts%20Issue%204099.MOV?dl=0) for more context)

# Cause of the issue

The issue is caused by some logic in [LineChartRenderer.swift](https://github.com/danielgindi/Charts/blob/master/Source/Charts/Renderers/LineChartRenderer.swift#L356) that determines whether or not a line should be rendered. It does so by checking if a line lies outside the viewport, however it does not take into account that lines might _intersect_ the viewport while its start and endpoint lie outside of the viewport.

In the above gif, the start point of the line was outside of the viewport while the end point lies within the viewport. Dragging the chart downward makes the end point move outside of the viewport, causing the logic below to skip rendering.

```swift
if (!viewPortHandler.isInBoundsRight(_lineSegments[0].x))
{
    break
}

// make sure the lines don't do shitty things outside bounds
if !viewPortHandler.isInBoundsLeft(_lineSegments[1].x)
    || (!viewPortHandler.isInBoundsTop(_lineSegments[0].y) && !viewPortHandler.isInBoundsBottom(_lineSegments[1].y))
{
    continue
}
```

# Fix

In Pull Request #4100 I have improved the logic to determine whether or not a line's start- or endpoint lie within the viewport, _or_ if the line intersects the viewport.

# Environment

- Charts version 3.3.0 (it is also present in 3.2.2)
- Xcode 10.3
- Swift 5
- macOS Mojave 10.14.16

**Comment by 4np** [comment]
The pull request ☝🏻 improves the logic that determines whether or not (a) line (sections) should be rendered by determining if the line intersect the viewport.

**Comment by 4np** [comment]
@liuxuan30: if you have time, can you please review the pull request? It would be great if this could make the `3.3.1` release. Thanks! :)

**Comment by 4np** [comment]
Actually, the logic to skip rendering of lines will cause trouble when rendering datasets as `horizontal bezier`s as well. Because lines are skipped from rendering, the uibezier paths will change while panning when zoomed in.

![Aug-22-2019 15-49-45](https://user-images.githubusercontent.com/1049693/63520236-a2913380-c4f4-11e9-837b-729d063fe95d.gif)

**Comment by 4np** [comment]
@liuxuan30: Could you please review the pull request and merge it in?

**Comment by liuxuan30** [comment]
Sure. I will take a look. Thank you in advance!

**Comment by 4np** [comment]
Thanks Xuan!

**Comment by liuxuan30** [comment]
hi, I plan review and possibly merge this week. Can you pull master and rebase on it? I fixed the Xcode11 CI failures. Just in case it does not break anything
