### ISSUE TITLE
entries属性只能readonly了吗  能不能改成可以读写

### ISSUE THREAD

**Issue by BabyWong** [danielgindi/Charts#4108]
![image](https://user-images.githubusercontent.com/14861974/63075507-8de8f480-bf64-11e9-90ce-1ac1e88a647d.png)

**Comment by BabyWong** [comment]
![image](https://user-images.githubusercontent.com/14861974/63075788-752d0e80-bf65-11e9-8ac4-297f279bcc46.png)

**Comment by mangireddy58** [comment]
@BabyWong Have you resolved the issue?

**Comment by myiosemail** [comment]
how to resolved the issue ?

**Comment by myiosemail** [comment]
how to resolve the issue ?

**Comment by liuxuan30** [comment]
yes, use new APIs please
