### ISSUE TITLE
Top and bottom grid line diverging widths

### ISSUE THREAD

**Issue by lucaswehmuth** [danielgindi/Charts#411]
Hello there,
I'm currently struggling to change the implementation of the function renderGridLines found in ChartYAxisRenderer.swift in order to prevent this from happening:

http://i.imgur.com/yASDJAm.png

As you can see, the top and bottom lines have different widths and I'd like all of them to look exactly the same. I tried fixing this by editing the values of the CGContext but I couldn't find out how :( 
Can anyone give me a light on this? Or maybe at least point me a direction on how to solve this problem.

**Comment by danielgindi** [comment]
I guess that the line is just clipped because of being drawn from its middle. It's the default behaviour of graphics drawing. I'll see if we can handle that gracefully.

**Comment by liuxuan30** [comment]
Quick around is move your desired grid lines outside of `CGContextClipToRect(context, _viewPortHandler.contentRect)`, like after `CGContextRestoreGState(context)`. But it may have side effect, since it cannot clipped the additional stuff.

**Comment by vvit** [comment]
I have the same problem, but my chart grid line is clipped on the bottom:
http://i.imgur.com/51whtKb.png

Indeed, placing `_leftYAxisRenderer?.renderGridLines(context: context)` before `CGContextClipToRect(context, _viewPortHandler.contentRect)` helps. But this could only be a temporary solution.

**Comment by danielgindi** [comment]
Well this needs some careful considerations. I thought about adding an offset to the lines, the size of half the line width. But that would lose the center focus of the value on the line. 

So we need a partial clipping of the grid lines. Just adjust the clipping rect for the grid, vertically, by half the line width.

I hope to take care of this soon

**Comment by odedharth** [comment]
Also have this problem.
Wandering if there was a progress on this or  fix that doesn't requires forking the library? 

![fullsizerender 2](https://cloud.githubusercontent.com/assets/624023/14761529/863d947c-096c-11e6-9eab-1143aaa54a19.jpg)
