### ISSUE TITLE
Removing LineChartView to save memory?

### ISSUE THREAD

**Issue by seanngpack** [danielgindi/Charts#4114]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## General question:

Is there an elegant way to unload a LineChartView object to save memory?

Say I have 3 chart views I want to toggle between (chart1, chart2, chart3).
Chart1 is displayed by default. So now I want to see chart2, I would hide chart1 (chart1.isHidden = true) and load chart2. Then I want to see chart3 so I hide chart2, however chart1 and chart2 are still in memory, so how can I offload them?

Thanks!

**Comment by cachobong** [comment]
Why not changed the Data Set dynamically instead?
