### ISSUE TITLE
BarChartView have interval between bar and xaxis

### ISSUE THREAD

**Issue by mengdc0001** [danielgindi/Charts#4115]
How can I eliminate the interval, thanks.

**Comment by mengdc0001** [comment]
<img width="527" alt="屏幕快照 2019-08-22 下午6 21 00" src="https://user-images.githubusercontent.com/43328213/63507242-e6426800-c509-11e9-9970-21cccc18acc7.png">

**Comment by judges** [comment]
@mengdc0001 - did you find a solution?

**Comment by qq432591** [comment]
试试 _chart_View.leftAxis.axisMinimum = 0.0;设置该属性
@mengdc0001 
@judges
