### ISSUE TITLE
Default Colors Should Support Dark Mode [iOS 13]

### ISSUE THREAD

**Issue by swupnil** [danielgindi/Charts#4133]
## What did you do?

ℹ Run project in Xcode 11, on a iOS 13 device.

## What did you expect to happen?

ℹ Black text should invert to white (i.e. Charts should use `UIColor.label` instead of `UIColor.black`).

## What happened instead?

ℹ Black text remains black. 

## Charts Environment

**Charts version/Branch/Commit Number: 3.2.1**
**Xcode version: 11.0**
**Swift version: 4**
**Platform(s) running Charts: iOS**
**macOS version running Xcode: 10.14.4**

**Comment by liuxuan30** [comment]
a pull request is always wanted!

**Comment by ybeapps** [comment]
Those merged commits are very important now since Apple announced that they won't keep apps that don't compile with iOS 13.0 SDK.
Now we want Charts to give us the labels colors for free..
Are you going to make a release soon?
Thanks!!

**Comment by liuxuan30** [comment]
@ybeapps what you mean? The label colors already support Dark mode, see #4171 is merged above?

**Comment by ybeapps** [comment]
I meant that those changes aren’t “released” yet in a new version
If I install from cocoapods I won’t get it.

**Comment by liuxuan30** [comment]
I pushed a new version.

I personally suggest if you like to try new stuff, use swift package or carthage, not relying on we build it for pods
