### ISSUE TITLE
I can't set static count of y axes and labels

### ISSUE THREAD

**Issue by guolingege** [danielgindi/Charts#4139]
I can't set static count of y axes and labels
And I need pinch function disabled
What properites should I set?!
The UI design is like the following picture:
<img width="665" alt="屏幕快照 2019-09-08 下午5 16 26" src="https://user-images.githubusercontent.com/13193905/64486193-7dbeef00-d25c-11e9-8ecf-e53d6c6ce49f.png">

**Comment by liuxuan30** [comment]
take a look at ChartsDemo and code.
