### ISSUE TITLE
I have two ChartLimitLine and I need to know how to fill the area between them  I'm using LineChartView

### ISSUE THREAD

**Issue by BilalSalam** [danielgindi/Charts#4142]

**Comment by QuyetND** [comment]
I have same issue. I have LIneChartView with 4 data set about temp and humidity, and i need show range dangerous.
How to set width ChartLimitLine with xAxis value (not pixel) and show it in legend chart?

**Comment by liuxuan30** [comment]
I don't think we have this feature yet. You have to customize it
