### ISSUE TITLE
BarChartRenderer FatalError: Index out of range 

### ISSUE THREAD

**Issue by mangireddy58** [danielgindi/Charts#4146]
## What did you do?
I have updated my pods to the 
recent one and changed to target swift 5.0 and everything is working fine except about error.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

             I am getting an error on 
             //Handles empty array of yValues
            let yValue = vals.isEmpty ? 0.0 : vals[idx % stackSize]

            elementValueText = dataSet.valueFormatter?.stringForValue(
                yValue,
                entry: e,
                dataSetIndex: dataSetIndex,
                viewPortHandler: viewPortHandler) ?? "\(e.y)"

## Charts Environment

Charts version/Branch/Commit Number: 3.3.0
Xcode version: 10.3
Swift version: 5
Platform(s) running Charts: iPhone/iPad
macOS version running Xcode: Mojave 10.14.6

## Demo Project

 I am attaching a screenshot, please find it.

<img width="1300" alt="Screenshot 2019-09-16 at 4 58 38 PM" src="https://user-images.githubusercontent.com/14342272/64954788-3a8bfe00-d8a4-11e9-900f-097fbf59cc72.png">

**Comment by laiminhlai1110** [comment]
I get the bug same to you

**Comment by matheda** [comment]
I ran into the same crash:

![image](https://user-images.githubusercontent.com/1895008/65042672-54225980-d927-11e9-9e56-068249c0b03c.png)

**Comment by liuxuan30** [comment]
what's causing the crash? Have you identified?

**Comment by mangireddy58** [comment]
@liuxuan30 Yes. in my point of view mismatching stack size.

**Comment by liuxuan30** [comment]
so should be fine now?

**Comment by mangireddy58** [comment]
@liuxuan30 yes it's working fine.
