### ISSUE TITLE
Could not find module 'Charts' for target 'arm64-apple-ios'; found: x86_64-apple-ios-simulator, x86_64

### ISSUE THREAD

**Issue by SunsgneDZ** [danielgindi/Charts#4154]
use oc.
the error message appreas on xcode11 ，ios 13 
i only drag the charts.framework to my project not use pod

**Comment by SunsgneDZ** [comment]
On the simulator can be normal use, use real machine operation appear this mistake

**Comment by SunsgneDZ** [comment]
![屏幕快照 2019-09-23 16 27 27](https://user-images.githubusercontent.com/24729554/65411289-12118000-de1f-11e9-9f81-9fac59b13042.png)

**Comment by SunsgneDZ** [comment]
the reason why cause the error  is i choose the error framework ,i see the current version only includes x86_64-apple-ios-simulator.swiftdoc/x86_64-apple-ios-simulator.swiftmodule/x86_64.swiftdoc/x86_64.swiftmodule.it does not include arm64.swiftdoc/arm64.swiftmodule so on ,so where can i downlond these all ? 
thanks

**Comment by 276023272** [comment]
i have meet this issue.how did you figure it out?

**Comment by SLEEGit** [comment]
Hi! Did you solve this problem???
