### ISSUE TITLE
How to properly subclass XAxis?

### ISSUE THREAD

**Issue by bardonadam** [danielgindi/Charts#4155]
I made a subclass of the XAxis:
```
class CustomXAxis: XAxis {
// empty, no custom implementation yet
}
```

And assigned it to my renderer:
```
let xAxis = CustomXAxis()
barChart.xAxisRenderer = CustomXAxisRenderer(viewPortHandler: barChart.viewPortHandler, xAxis: xAxis, transformer: barChart.getTransformer(forAxis: .left))
```

The problem is that my renderer overrides computeSize() function, but it has no/incorrect effect on xAxis height. When I initialize my renderer with `barChart.xAxis` instead of my custom one, it works as expected.

Is there anything left to do when subclassing XAxis?

**Comment by LeeCenY** [comment]
OC project, ask how to inherit xAxisRenderer
Error message: Cannot subclass a class that was declared with the 'objc_subclassing_restricted' attribute

**Comment by liuxuan30** [comment]
```
@objc(ChartXAxis)
open class XAxis: AxisBase
{
```
