### ISSUE TITLE
UITableView does not scroll when dragging within chart for iOS 13.

### ISSUE THREAD

**Issue by davem2020** [danielgindi/Charts#4156]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
Place several charts in UITableView
ScaleYEnabled set to false
Drag vertically on chart

## What did you expect to happen?
UITableView should scroll up and down. This was the behavior previously in iOS 12

## What happened instead?
UITableView does not scroll in iOS 13.

## Charts Environment

**Charts version/Branch/Commit Number: Master 3.3.0
**Xcode version: 11
**Swift version: 4.2
**Platform(s) running Charts: 13
**macOS version running Xcode:  10.14.6

**Comment by Conan-R** [comment]
I meet the same problem!!!!

**Comment by Orackle21** [comment]
Had the same problem, fixed with the lates Xcode update.

**Comment by liuxuan30** [comment]
thanks @Orackle21
