### ISSUE TITLE
PieChartRenderer - Fatal Crash iOS 13 / Xcode 11

### ISSUE THREAD

**Issue by Neilfau** [danielgindi/Charts#4160]
I have an existing project with a piechart that now crashes on iOS 13 / Xcode 11 in the PieChartRenderer class. The fatal error is 

> -[__SwiftValue set]: unrecognized selector sent to instance

the breakpoint seems to show its something with **drawCenterText(context: context)** but can't be sure.

Anyone else having this issue or knows how to fix?

**Comment by liuxuan30** [comment]
i need you to use latest master and test with ChartsDemo, to reproduce.
