### ISSUE TITLE
Xcode asking for constants instead of variables in Charts code

### ISSUE THREAD

**Issue by Ardevlp** [danielgindi/Charts#4161]
Hi all,

First of all thanks for the awesome work with this framework!

Now, I recently installed Xcode 11 and loads of warnings have appeared, most of them because of the declaration of variables, while Xcode thinks that constants would be better.
Is there anything that the I can do or we just need to wait for a update?

Thanks in advance!

**Comment by liuxuan30** [comment]
the master has merged support for Xcode11.

I still have 1-2 issues/fix WIP. So the best way is to merge from master, if you want to get rid of the warnings.
