### ISSUE TITLE
How to control colors within a single dataSet?

### ISSUE THREAD

**Issue by theofficejackpot** [danielgindi/Charts#4166]
* [ x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I have one dataset that I display in a pie chart. I am trying to get (or set) the colors for each index so I can align other areas of the app with color-coding.

## What did you expect to happen?

ability to get/set colors for individual entries within a single dataset

## What happened instead?

Automatic color wheel (changes each refresh) randomly 

## Charts Environment

**Charts version/Branch/Commit Number: master as of oct1
**Xcode version:**
**Swift version: 5
**Platform(s) running Charts:**
**macOS version running Xcode:**

**Comment by rikyfocil** [comment]
Assuming a set of type PieChartDataSet (called set in this example) just do 

`set.colors = <array of UIColor>`
