### ISSUE TITLE
Should Version 4.0.0 be updated to include changes from recent releases?

### ISSUE THREAD

**Issue by ChristianVinterly** [danielgindi/Charts#4167]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Looking at the branch for version 4.0.0, it is still on swift 4 and the last commit was in January.

## What did you expect to happen?

I would expect the new major version to be up-to-date, so we can use it in our apps and contribute to making it stable. I think it would help pushing this version forward, and hopefully towards a release.

## What happened instead?

`This branch is 82 commits ahead, 105 commits behind master.`
This version does not have the Swift 5 and Xcode 11 fixes and the bug fixes from the last year, but I assume it would be preferred to use version 4.0.0 for new apps?

It would be greatly appreciated if the 4.0.0 branch got updated with the fixes that are currently on master.

**Comment by liuxuan30** [comment]
Charts 4.0 was supposed to have full modern Swift syntax and refactorings, and some MVP features, however due to the lack of man power, it's far behind. 

Meanwhile, we have to maintain the v3 with Apple's pace. So, you should use v3 for latest.

**Comment by jjatie** [comment]
Short answer: Yes.
Long answer: Refer to @liuxuan30 answer

We would love some help in getting 4.0.0 back in sync with master.

**Comment by ChristianVinterly** [comment]
That is totally understandable. Unfortunately our app requires gradients in line charts, and that feature was only merged into the 4.0 branch. I assume merging new features into master is not a priority? Its difficult to chose branch when master gets all the bug fixes and not any new features, while 4.0 gets the opposite and your app relies on those new features :/

**Comment by liuxuan30** [comment]
Maybe @danielgindi is the captain in cheif to decide? I'm fine to merge, but I remember there are PRs that need to review and merge. and finally merge into master.

@jjatie do you think the PRs for swift refactoring is all there? If so maybe we can spend some time to merge them all into 4.0. and decide when into master

**Comment by danielgindi** [comment]
I'll try to take a look the next week

**Comment by liuxuan30** [comment]
@danielgindi we have a [swift refator project](https://github.com/danielgindi/Charts/projects/4) to make the framework more swift; there is only one PR left, but not sure if @jjatie have more in his branch. These PRs are targeted for 4.0 branch I remember.

we also have [4.0 project](https://github.com/danielgindi/Charts/projects/7 ), which aims to provde a big update including more features as well as above swift refactoring. 

We planned to finish swift project and then continue 4.0 project. But since then we have been busy with coroperate jobs and delayed a lot :(
