### ISSUE TITLE
Candlestick xAxis label's too small when zoomed out

### ISSUE THREAD

**Issue by CryoCodex** [danielgindi/Charts#4176]
## What did you do?
Use the candlestick chart with multiline text enabled, however if it's enabled or not, the xAxis is still getting small width labels when zoomed out, from what I see it seems to be the same width as the assigned's candle width

## What did you expect to happen?
For the xAxis to show the labels correctly whatever the zoom level is, what I've done to kind of circumvent this is to set the X minimum range to 6 candles but I actually need to freely zoom the xAxis too

## What happened instead?
The xAxis gets rendered like this
[xAxis wrong label width](https://imgur.com/a/W4Dnsx3) 
with the candle's width instead of the text's width 

## Charts Environment

**Charts version/Branch/Commit Number: 3.4.0**
**Xcode version:10.2**
**Swift version:5**
**Platform(s) running Charts:iOS**
**macOS version running Xcode:Mojave 10.14.5**

**Comment by liuxuan30** [comment]
are you able to debug a little?

**Comment by CryoCodex** [comment]
Actually nevermind, my bad for not closing the issue this was a mistake on my end, the labels work properly when I set multiline (which I readed somewhere it was wordWrapEnabled) property to false, I thought that you needed to set it up to true in order for labels have multiple lines, but the labels work as intended with the \n to make the line break
