### ISSUE TITLE
I need to draw peichart like below image

### ISSUE THREAD

**Issue by amit04kumar** [danielgindi/Charts#4177]
<img width="234" alt="Screenshot 2019-10-15 at 8 19 27 PM" src="https://user-images.githubusercontent.com/3490881/66846008-c0c45e80-ef8e-11e9-96d2-6c5493101e60.png">
<img width="231" alt="Screenshot 2019-10-15 at 8 19 09 PM" src="https://user-images.githubusercontent.com/3490881/66846010-c0c45e80-ef8e-11e9-9367-48506800cbeb.png">

below chart there is table view and on selection of cell, pei chart will get spin & point to selected index. Please ignore the background chart.

Thanks in advance.

**Comment by liuxuan30** [comment]
this is your duty to figure it out.
