### ISSUE TITLE
Add Line Cap to Bar for Horizontal Bar Chart

### ISSUE THREAD

**Issue by poojab** [danielgindi/Charts#4183]
Hi ,

I want to add line cap as rounded for bars of horizontal bar chart. So it should look something like below image. Let me know what can be done.

![Screenshot 2019-10-18 at 11 37 48 AM](https://user-images.githubusercontent.com/951599/67069766-c6db5a80-f19b-11e9-93c7-178c3ba5ef6e.png)

**Comment by liuxuan30** [comment]
check a PR called rounded bar

**Comment by poojab** [comment]
How do I get those changes in actual POD?
