### ISSUE TITLE
iOS Charts not showing all xAxis Value

### ISSUE THREAD

**Issue by poojab** [danielgindi/Charts#4187]
Hi I want custom labels for xAxis I am creating my own IAxisValueFormatter but it is skipping last label. 

> func stringForValue(_ value: Double, axis: AxisBase?) -> String

 not getting called for last label.

used below solution to show custom lables for xaxis

[https://stackoverflow.com/questions/55693095/ios-charts-not-showing-all-xaxis-value](url)

**Comment by liuxuan30** [comment]
please check why it's cutting the last one. e.g. your axis range is not big enough

**Comment by poojab** [comment]
I resolved above issue. Problem was I was setting barspace more than 10. I set barspace to 10 and also added  chartView.xAxis.axisMinimum = -0.5 //to avoid issue of last bar getting hal fcut
so it resolved my issues.
