### ISSUE TITLE
How to set only given values to xAxis, set equal distance between those values?

### ISSUE THREAD

**Issue by rafplu** [danielgindi/Charts#4190]
Hi guys, I have some trouble in configuring x axis of line chart. I want it to have just a few specific given values and I want equal spacing between those values. The effect I think about is presented in the picture below.

Each of my data entry consists of x-axis value from a data set [250, 500, 1000, 2000, 4000, 8000] and an y-axis value (from 0 to 100).

How can I display lines on x-axis only for given values and skip other values? Also, if it can be done, how to set equal distance on x-axis between those points, no matter on value difference (250 to 500 and 4000 to 8000 should have the same distance)?

Thanks a lot for your help.

![pic025](https://user-images.githubusercontent.com/26260771/67375899-915fb400-f583-11e9-928b-2e75e0e954b7.gif)

**Comment by liuxuan30** [comment]
use `@objc open func setLabelCount(_ count: Int, force: Bool)` explicitly.

**Comment by Young-Li-90** [comment]
the same expectation
