### ISSUE TITLE
Is this possible to use with project catalyst?

### ISSUE THREAD

**Issue by gheorghecr** [danielgindi/Charts#4193]
I am trying to run my app on my Mac, but I get this error : 

/Pods/Realm/core/librealmcore-ios.a(bptree.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64

I am wondering if this has something to do with this framework

**Comment by liuxuan30** [comment]
this is realm repo.

**Comment by nosnahoj** [comment]
did you ever get this to going with catalyst?
