### ISSUE TITLE
Is there a way to add to the datapoint label in a line chart?

### ISSUE THREAD

**Issue by cluelessoodles** [danielgindi/Charts#4196]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

I have a line chart that maps temperature values over time, and shows the temperature value in the dataPoint label. I want to also add the time label in the dataPoint label so that the label looks like a multiline string at each dataPoint.
```
tempValue
timeValue
```

I have implemented IValueFormatter but this only allows me to customize the dataEntry value (temperature) used to map out the line chart. It doesn't allow me to add an unrelated second value to the dataPoint label.

class ChartsFormatterToDegrees: IValueFormatter {
    func stringForValue(_ value: Double, entry: ChartDataEntry, dataSetIndex: Int, viewPortHandler: ViewPortHandler?) -> String {
        // Hour & Temp labels on every data point
        return """
        \(Int(value))°
        \(Int(value))°
        """
    }
}

Here's what the chart looks like right now: https://imgur.com/a/sONRA4k

## Charts Environment

**Charts version/Branch/Commit Number:** 
**Xcode version:** 11
**Swift version:** 5
**Platform(s) running Charts:** iOS
**macOS version running Xcode:**

**Comment by liuxuan30** [comment]
maybe ChartMarker, or customize it. or simply put two values into one string.
