### ISSUE TITLE
BarChart bottom space when having a small value

### ISSUE THREAD

**Issue by nastasiupta** [danielgindi/Charts#4198]
[*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I just configured BarChartView with basic data as following:

`        var dataEntries: [BarChartDataEntry] = []

        let values: [Double] = [50.0, 100.0, 123.0, 313.0, 104.0, 180.0]
        for i in 0 ..< values.count {
            let dataEntry = BarChartDataEntry(x: Double(i), y: Double(values[i]))
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(entries: dataEntries)
        chartDataSet.colors = [UIColor(red: 55.0/255.0, green: 148.0/255.0, blue: 252.0/255.0, alpha: 1.0)]
        let chartData = BarChartData(dataSet: chartDataSet)
        barChartView?.xAxis.labelPosition = .bottom
        barChartView?.xAxis.valueFormatter = axisFormatDelegate
        barChartView?.xAxis.labelTextColor = Color.main.color
        barChartView?.xAxis.labelFont = AppFonts.regular.font.withSize(7)
        barChartView?.xAxis.gridColor = UIColor(red: 224.0/255.0, green: 231.0/255.0, blue: 255.0/255.0, alpha: 1.0)
        barChartView?.leftAxis.labelTextColor = Color.main.color
        barChartView?.leftAxis.labelFont = AppFonts.regular.font.withSize(9)
        barChartView?.leftAxis.gridColor = UIColor(red: 224.0/255.0, green: 231.0/255.0, blue: 255.0/255.0, alpha: 1.0)
        barChartView?.rightAxis.enabled = false
        barChartView?.legend.enabled = false
        barChartView?.data = chartData
        barChartView?.isUserInteractionEnabled = false`

## What did you expect to happen?

To see the chart but having the BarChart starting from XAxis 

## What happened instead?

I have a some space on the bottom
![Screenshot 2019-10-28 at 16 20 27](https://user-images.githubusercontent.com/13376064/67686408-530d2f00-f99f-11e9-9e94-7d516a6cfcc3.png)

But if I try with bigger values, it works properly:
![Screenshot 2019-10-28 at 16 24 05](https://user-images.githubusercontent.com/13376064/67686441-5ef8f100-f99f-11e9-8542-26d6141fc4f7.png)
 

## Charts Environment

**Charts version/Branch/Commit Number: 3.4.0**
**Xcode version: 11.1 (11A1027)**
**Swift version: 5.0**
**Platform(s) running Charts: iPhone X iOS 13.1**
**macOS version running Xcode: macOS Catalina 10.15**

**Comment by liuxuan30** [comment]
set axis min.
