### ISSUE TITLE
Issue creating IPA archive with Xcode 11.1 (Swift 5.1)

### ISSUE THREAD

**Issue by qualiture** [danielgindi/Charts#4204]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Included Charts library via CocoaPods to Xcode 11.1 (Swift 5.1) project.

## What did you expect to happen?

 * Building for a generic device : working
 * Building for a specific device : working
 * Creating an IPA archive : working

## What happened instead?

 * Building for a generic device : **not working**
 * Building for a specific device : working
 * Creating an IPA archive : **not working**

Build failed with `Command CompileSwift failed with a nonzero exit code` message.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.4.0
**Xcode version:** 11.1
**Swift version:** 5.1
**Platform(s) running Charts:** iOS 12+
**macOS version running Xcode:** 10.14.6 (Mojave)

## Demo Project

N/A

As it worked with Xcode 10 / Swift 5.0, I suspect the library isn't yet compiled against Swift 5.1 yet? When do you expect to have a Swift 5.1 compatible version available?

**Comment by liuxuan30** [comment]
Can you post the compile log? `Command CompileSwift failed with a nonzero exit code` is not enough to know what's wrong.

**Comment by pmairoldi** [comment]
No response, old issue. Closing
