### ISSUE TITLE
Create special line chart

### ISSUE THREAD

**Issue by appcelerate** [danielgindi/Charts#4207]
Creating a chart with unequals x labels and x data points.

I want to create a chart like the nokia health mate app ->
https://images.app.goo.gl/twfBjeq9KyQwfyir6

and i dont know how to do it because 

`let dataEntry = ChartDataEntry(x: Double(int), y: values[int], data: dataPoints[int] as AnyObject)`

can not contain nil values and i dont know how to do it without.
Any ideas how to solve that.

<img width="283" alt="Bildschirmfoto 2019-11-06 um 15 51 16" src="https://user-images.githubusercontent.com/9802659/68318067-79784c00-00bc-11ea-89d1-0fa7de170a83.png">

**Comment by ispiropoulos** [comment]
Hi bud, did you figure out a way to do it?

**Comment by anirudhamahale** [comment]
I am also looking for the same thing

**Comment by anirudhamahale** [comment]
You can do this by giving number of points you want to show on the Y axis
```  
chartView.xAxis.axisMinimum = 0
chartView.xAxis.axisMaximum = daysData.count()
```

Then you can create array of `ChartDataEntry`
```
var dataEntries: [ChartDataEntry] = []
for (index, dayData) in daysData.enumerated() { // Iterate through the data list
  if dayData.value > 0 { 
    /* 
      Check if the weight or the value is greater then zero, then only add it to data set.
      Since you pass index as x, respected value will be shown at y position.
    */
    let dataEntry = ChartDataEntry(x: Double(index), y: Double(dayData.value))
    dataEntries.append(dataEntry)
  }
}
let dataSet = LineChartDataSet(entries: dataEntries, label: "Weight")
let data = LineChartData(dataSet: dataSet)
chartView.data = data
```
