### ISSUE TITLE
CombinedChartRenderer property : _renderers should be set open

### ISSUE THREAD

**Issue by opann** [danielgindi/Charts#4208]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Try to replace CombinedChartRenderer using custom LineChartRenderer

## What did you expect to happen?

ℹ I override the function createRenderers() and replace the LineChartRenderer
, but I found out that it still using the default renderers to draw charts because _renderers 
cant be override. So I change the _renderers property prefix from "internal" to "open"
Issue Fixed.
I recommend to change the _renderers property prefix to "open" that makes people can 
using custom CombinedChartRenderer

## What happened instead?

ℹ _renderers still generate default renderers so I cant using my own LineChartRenderer

## Charts Environment

**Charts version/Branch/Commit Number:3.3.0
**Xcode version: 10.3
**Swift version:4.2
**Platform(s) running Charts:iPhone 8
**macOS version running Xcode:10.14.6

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by liuxuan30** [comment]
if you are heavily customizing the library, you should grab the source code and make any modifications you want.
