### ISSUE TITLE
Contains is not implemented in ChartDataSet, crashes when called

### ISSUE THREAD

**Issue by dannyiss** [danielgindi/Charts#4212]
We are getting crashes when we call "contains(_ e: ChartDataEntry) -> Bool" on a LineChartDataSet in 3.4.0. This problem does not happen in 3.2.1 of the library. This is happening because contains is not implemented anywhere up the chain of parent classes of LineChartDataSet, including in ChartDataSet where it used to be implemented in 3.2.1.

We were able to fix the issue locally by reimplementing contains in ChartDataSet like so, but it seems like this should be reverted back to the way it was before.

```
    override open func contains(_ e: ChartDataEntry) -> Bool {
        return entries.contains(e)
    }
```

Is there any reason why this function is no longer implemented anywhere anymore?

Thanks.

**Comment by liuxuan30** [comment]
it's removed in #3815. ChartDataSet has adopted some collection types, you should be able to still use
![image](https://user-images.githubusercontent.com/4375169/72694657-b5c23100-3b70-11ea-8dbf-3441d4e3e180.png)
