### ISSUE TITLE
SwiftCharts: How to set space between x axis equally ?

### ISSUE THREAD

**Issue by Kaliyarajalu** [danielgindi/Charts#4218]
![Simulator Screen Shot - iPhone 11 Pro - 2019-11-16 at 10 36 13](https://user-images.githubusercontent.com/18463172/68989308-abcb3b80-086a-11ea-9fa4-7e1367bae805.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-11-16 at 10 37 40](https://user-images.githubusercontent.com/18463172/68989309-abcb3b80-086a-11ea-9796-f3cbccdba2ac.png)

  Am used SwiftCharts pod to customize the chart, but the width issue occur, it give more space between x labels, how to reduce it dynamically ?

**Comment by Kaliyarajalu** [comment]
![Simulator Screen Shot - iPhone 11 Pro - 2019-11-16 at 10 36 13](https://user-images.githubusercontent.com/18463172/68989210-111e2d00-0869-11ea-8881-53b727208e28.png)
![Simulator Screen Shot - iPhone 11 Pro - 2019-11-16 at 10 37 40](https://user-images.githubusercontent.com/18463172/68989211-11b6c380-0869-11ea-8fd6-07260880bf73.png)

 The above graph customized using SwiftCharts pod, the width is changing keep on and increased space, so how to reduce it ?

**Comment by liuxuan30** [comment]
wrong repo.

**Comment by Kaliyarajalu** [comment]
> wrong repo.

Can you explain ? then, which one want to use instead ? thanks in advance
