### ISSUE TITLE
How to render radar-chart with live data and dynamic array entries?

### ISSUE THREAD

**Issue by PGandhi30** [danielgindi/Charts#4220]
## What did you do?

chartView is RadarChartView Object

chartView.clear()
chartView.clearValues()
let set1 = RadarChartDataSet(entries: arrRadarProduct, label: "XXX")
let data = RadarChartData(dataSets: [set1])
data.notifyDataChanged()
chartView.data = data
chartView.notifyDataSetChanged()

refresh X Values on the refresh button sometimes it 6 value or 8 value of X at that time accessibilityXLabels vale not change.

## What did you expect to happen?

accessibilityXLabels value change on every refresh.  

## What happened instead?
 
library crash on refresh.
let accessibilityAxisLabelValueTuples = zip(accessibilityXLabels, accessibilityEntryValues).map { ($0, $1.0, $1.1) }.sorted { $0.1 > $1.1 }

## Charts Environment

**Xcode version:**  11.2.1
**Swift version:**  5.1

@danielgindi @liuxuan30

**Comment by liuxuan30** [comment]
search old issues, especially tagged with 'Good Example'.
