### ISSUE TITLE
Source not able to compile

### ISSUE THREAD

**Issue by jp-dubey07** [danielgindi/Charts#4221]
I've downloaded attached source code and done carthage update for ChartsDemo-iOS-Swift project. So its showing compile time error 'Type UIColor has no member label.'

Check attached screenshot.

<img width="970" alt="Screenshot 2019-11-19 at 18 55 05" src="https://user-images.githubusercontent.com/5441735/69150556-ecdb7e00-0afe-11ea-9647-689a124dae0a.png">

<img width="1106" alt="Screenshot 2019-11-19 at 19 00 28" src="https://user-images.githubusercontent.com/5441735/69150697-290ede80-0aff-11ea-85de-eda5e5fe6b2d.png">

**Comment by kaystd** [comment]
Same issue

**Comment by liuxuan30** [comment]
it's working on my Xcode 11.3.1.

**Comment by bazilhassan** [comment]
Same issue . I'm using xcode 10.3 . What should i do resolve this issue ?? Should i update my xcode ?

**Comment by Sikandarkhan** [comment]
XCode 10.3. The issue is still exists. Any suggestions on this?

**Comment by liuxuan30** [comment]
I would suggest update to Xcode 11. The swift syntax might changed, so either you pick an older version or upgrade Xcode.

I don't find obvious reasons not to update Xcode though.
