### ISSUE TITLE
Can BarChartDataEntry with multiple Y values render icon once instead of for each Y value?

### ISSUE THREAD

**Issue by ben-r-cc** [danielgindi/Charts#4225]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Created a `BarChartDataEntry` with multiple Y values and an icon.

## What did you expect to happen?

ℹ `BarChartView` renders the icon once per `BarChartDataEntry`, something like this:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-19 at 12 02 23](https://user-images.githubusercontent.com/54448500/69253935-6fa61c80-0b83-11ea-8a65-c98bd2148345.png)

## What happened instead?

ℹ `BarChartView` renders the icon once per Y value.
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-19 at 13 07 32](https://user-images.githubusercontent.com/54448500/69253948-73d23a00-0b83-11ea-9dd7-8bce5fbf8da5.png)

## Charts Environment

**Charts version/Branch/Commit Number:**
3.4.0
**Xcode version:**
11.0
**Swift version:**
5
**Platform(s) running Charts:**
iPhone
**macOS version running Xcode:**
N/A
## Demo Project
[chartsTest.zip](https://github.com/danielgindi/Charts/files/3870103/chartsTest.zip)

**Comment by liuxuan30** [comment]
by default, draw icon and draw values are the same behavior. however, you can tweak the code so to only draw one icon. the function you should look for is `open override func drawValues(context: CGContext)`
