### ISSUE TITLE
X-Axis setLabel with force enabled not working

### ISSUE THREAD

**Issue by yudhvirsingh-chicmic** [danielgindi/Charts#4228]
IndexAxisValueFormatter values : ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"]

code :
lineChartView.xAxis.setLabelCount(15, force: true)
lineChartView.xAxis.axisMinimum = 0
lineChartView.xAxis.axisMaximum = 29

screenshot: 
![Screenshot 2019-11-22 at 5 34 54 PM](https://user-images.githubusercontent.com/52695397/69424366-6ddc8480-0d4e-11ea-9f70-5fe4a94a8a99.png)

same properties are working fine in android.

please let me know if any other property needs to be set

**Comment by liuxuan30** [comment]
no it works just fine on my side. refer charts demo.

**Comment by yudhvirsingh-chicmic** [comment]
> no it works just fine on my side. refer charts demo.

is there any other property that needs to be set other than this ?
