### ISSUE TITLE
CombinedChartView Legend only shows line data info not info for other types

### ISSUE THREAD

**Issue by robertschmid23** [danielgindi/Charts#4230]
I have created a CombinedChartView with lineDataSets and CandleDataSets. The CandleDataSets are used to highlight certain data points.

This has all worked fine except for the Legend. When I enable the legend it only shows legend information for the LineDataSets.

I looked into the LegendRenderer and discovered the problem arises here ->

    @objc open func computeLegend(data: ChartData)
    {
        guard let legend = legend else { return }

        if !legend.isLegendCustom
        {
            var entries: [LegendEntry] = []

            // loop for building up the colors and labels used in the legend
            for i in 0..<data.dataSetCount
            ...

The dataSetCount only counts lineDataSets and ignores the candleDataSet. So any data sets after the line data are ignored.

My setup looks like this;

    self.chartView.data = CombinedChartData()

    if let chartView = self.chartView
    {
        let allData = CombinedChartData()
        allData.lineData = LineChartData()
        for line in lineData.values
        {
            if line.isVisible
            {
                allData.lineData.addDataSet(line)
            }
        }
        allData.candleData = CandleChartData()
        for fiducialMark in buttonData.values
        {
            if fiducialMark.isVisible
            {
                allData.candleData.addDataSet(fiducialMark)
            }
        }
        chartView.data = allData
        chartView.chartDescription?.text = self.fileLabel.stringValue
        chartView.needsDisplay = true
        chartView.rightAxis.enabled = false
        chartView.legend.enabled = true
    }

**Comment by liuxuan30** [comment]
refer ChartsDemo, the combined chart legends seems fine.
<img width="355" alt="image" src="https://user-images.githubusercontent.com/4375169/72695301-020e7080-3b73-11ea-906c-1dc827cb27a0.png">
