### ISSUE TITLE
How to set space between Y-Axis labels and graph

### ISSUE THREAD

**Issue by Sinan-Noureddine** [danielgindi/Charts#4237]
Hello, How can i add padding/space between YAxis-labels and the graph. By default the labels are sticking to the graph as shown in the first image.

<img width="714" alt="Screen Shot 2019-12-02 at 12 35 04 AM" src="https://user-images.githubusercontent.com/22674620/69921583-ed2f2e00-149b-11ea-89b1-ef19f8e2745e.png">

How can i add space so that it becomes something like this

<img width="719" alt="Screen Shot 2019-12-02 at 12 30 20 AM" src="https://user-images.githubusercontent.com/22674620/69921591-ffa96780-149b-11ea-93aa-9669dd2e92e5.png">

**Comment by Sinan-Noureddine** [comment]
I found the answer for that. You need to add Offset to the labels as below

`lineChart.leftAxis.xOffset = 10.0`

**Comment by alejandrocabriales** [comment]
this don't work for me
