### ISSUE TITLE
数据源都是0的时候有问题

### ISSUE THREAD

**Issue by CoderWZF** [danielgindi/Charts#4241]
LineChartView当模式设为LineChartModeCubicBezier，数据源都是0的情况会少绘制一条线
![1575640254669](https://user-images.githubusercontent.com/5017724/70327788-88484f00-1872-11ea-88ac-0997bd98ada4.jpg)

**Comment by CoderWZF** [comment]
![image](https://user-images.githubusercontent.com/5017724/70328268-8f239180-1873-11ea-8a0f-278827abeb8f.png)

demo has the same issue

**Comment by CoderPby** [comment]
I have the same problem,hope the author can fix it

**Comment by Andy1984** [comment]
How do you reproduce? Can you explain more? I did not reproduce in the demo.
你怎么复现的， 我在demo里没复现

**Comment by liuxuan30** [comment]
you have to either try multiple data sets or try what @Andy1984 said horizontalBezier instead of cubicBezier. What you mentioned in your screenshot is not the way bezier curves works.
