### ISSUE TITLE
Access level of ChartViewBase's API 

### ISSUE THREAD

**Issue by ChaoLiao** [danielgindi/Charts#4243]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I needed to display 2 data sets in the marker (tooltip) of `LineCharView`. So I created a subclass of `LineChartView` and needed to override `drawMarkers(context: CGContext)` to display 2 data sets. Since `drawMarkers(context: CGContext)` is `internal` in `ChartViewBase` and `CombinedChartView` and therefore cannot be overridden, I changed the source code to make it `open`.

## What did you expect to happen?

Changing the source code works, but it's not ideal. It makes updating the pod problematic. Also, my Android partner told me the same method is `open` in the Android library.

## What happened instead?

Changing the source code works, but when we updated the pod version it broke. 

## Charts Environment

**Charts version/Branch/Commit Number:** 3.4.0
**Xcode version:** 10.3/11
**Swift version:** 5
**Platform(s) running Charts:** iPhone
**macOS version running Xcode:**

## Demo Project
<img width="399" alt="Screen Shot 2019-11-05 at 11 55 23 AM" src="https://user-images.githubusercontent.com/2403605/70752792-57986780-1d01-11ea-832d-0b7819f7294a.png">

**Comment by liuxuan30** [comment]
well... it's hard to tell if we should to mark it open or internal... as you can see `drawMarkers` IMP is not ideal to mark it open. too much details for a public method.
normally, I'd encourage if you need heavy customizations, you should grab the source code. Pod is just for grab-and-use or light weight overriding.
