### ISSUE TITLE
x轴从数据量多切换到数据量少的时候 x轴间距变大

### ISSUE THREAD

**Issue by lessSource** [danielgindi/Charts#4245]

**Comment by lessSource** [comment]
![WechatIMG17](https://user-images.githubusercontent.com/18695890/70877928-6d0bdb00-1ffa-11ea-8c77-c6d52831efaf.jpeg)
![WechatIMG16](https://user-images.githubusercontent.com/18695890/70877930-6e3d0800-1ffa-11ea-9ac3-2b2837605375.jpeg)

**Comment by liuxuan30** [comment]
this is what your data tell the axis how many x values you want. You'd better check your data first.
