### ISSUE TITLE
Using charts with Mac Catalyst generate many deprecated warnings.

### ISSUE THREAD

**Issue by gossmer** [danielgindi/Charts#4249]
After working around it wanting to load AppKit, the Chart code generated 25 warnings about deprecation in Mac Catalyst. 
<img width="451" alt="Screen Shot 2019-12-18 at 3 11 29 PM" src="https://user-images.githubusercontent.com/10172186/71131218-e812f400-21a8-11ea-8bb1-ba2ac05cb0b2.png">

**Comment by liuxuan30** [comment]
is there any replacement available? Can you try to find the equivalent replacments?

**Comment by ohomaidi** [comment]
For just two there is:
'statusBarOrientationUserInfoKey' was deprecated in Mac Catalyst 13.0: Use viewWillTransitionToSize:withTransitionCoordinator: instead.
'willChangeStatusBarOrientationNotification' was deprecated in Mac Catalyst 13.0: Use viewWillTransitionToSize:withTransitionCoordinator: instead.

I add my vote to get this fixed! a million thanks :)

**Comment by Dzamir** [comment]
I have the same problem compiling with iOS 13.4 as deployment target

**Comment by liuxuan30** [comment]
latest release should resolved the warnings. I'm not sure if catalyst still has. but generally... since it supports macOS, why bother catalyst?
