### ISSUE TITLE
Can we set two fill colors for line chart?

### ISSUE THREAD

**Issue by hungcaohnc** [danielgindi/Charts#4260]
I need to set two fill colors for upper and lower values like image below:
![Screen Shot 2020-01-09 at 11 11 54 AM](https://user-images.githubusercontent.com/13977238/72037932-55123900-32d2-11ea-8482-5257393d602a.png)
Do we have any solutions for this case?

**Comment by liuxuan30** [comment]
you have to subclass and override the fill methods
