### ISSUE TITLE
AxisRange and drag

### ISSUE THREAD

**Issue by baha-che** [danielgindi/Charts#4264]
![Screenshot at Jan 16 12-28-55](https://user-images.githubusercontent.com/43853709/72521732-47256080-385c-11ea-87c1-5a87fe9c6c96.png)

Hello, I want to make a drag xAxis that show very time a 4 months and when I drag, it should show the another 4! I add 4 months but the drag is disabled and I don't know why?  

yearChartView.dragEnabled = true
        yearChartView.setScaleEnabled(false)
        yearChartView.pinchZoomEnabled = false
        yearChartView.maxHighlightDistance = 500
        let xAxis = yearChartView.xAxis
        xAxis.labelFont = UIFont(name: "MetroSans-Book", size:10)!
        xAxis.setLabelCount(self.baha.count - 1, force: false)
        xAxis.labelTextColor = #colorLiteral(red: 0.5254901961, green: 0.5568627451, blue: 0.5882352941, alpha: 1)
        xAxis.labelPosition = .bottom
        xAxis.axisLineColor = #colorLiteral(red: 0.9529411765, green: 0.9607843137, blue: 1, alpha: 1)
        xAxis.gridLineWidth = 1
        xAxis.gridColor = #colorLiteral(red: 0.9529411765, green: 0.9607843137, blue: 1, alpha: 1)
        xAxis.axisRange = 3.0

I want to get something like that:

![Screenshot at Jan 16 12-26-48](https://user-images.githubusercontent.com/43853709/72521959-d599e200-385c-11ea-931a-5785505a5439.png)
![Screenshot at Jan 16 12-27-18](https://user-images.githubusercontent.com/43853709/72521960-d599e200-385c-11ea-89f5-830398b87efd.png)

**Comment by aaronsheah** [comment]
@baha-che did you manage to get something? I would love to implement something similar
