### ISSUE TITLE
BarChart.setData() not working

### ISSUE THREAD

**Issue by SebGM2018** [danielgindi/Charts#4284]
Hi, I'm using a vertical Bar Chart to display data. However, it is not displaying it correctly.
I need to say that I checked with breakpoints the value of this BarData, and it is not 0 (One bar has Y = 0, but another one has Y = 1), however, this values seem to be ignored, and when that line gets executes, the BarChart only shows 0's.
As you can see in the screenshots, the Set and the BarData have one Bar with a Y value of 1:
When the program passes the line BarChart.setData(data), it displays zeroes 
   [Screenshots](https://imgur.com/a/1RJoIZ0)

**Comment by liuxuan30** [comment]
I don't see we have setData(). If you are calling data setter, it should be fine. didn't get similar report before.
