### ISSUE TITLE
CGAffineTransformInvert: singular matrix

### ISSUE THREAD

**Issue by schooltech** [danielgindi/Charts#4290]
hi, 
error repeatedly with a LineChartView:
`[Unknown process name] CGAffineTransformInvert: singular matrix.`

and my code is as below:
`struct ZLineChartView: UIViewRepresentable {
    
    var title: String
    var dataPoints: [String]
    var values: [Double]
    var drawValueLabel: Bool
    
    func makeUIView(context: Context) -> LineChartView {
        
        let chartView = LineChartView()
        chartView.noDataText = "no data"
    
        chartView.chartDescription?.enabled = false
       
        chartView.legend.yOffset = 0
        chartView.autoScaleMinMaxEnabled = false
        
        chartView.xAxis.drawLabelsEnabled = true
        chartView.xAxis.enabled = true
        //lineChartView.xAxis.valueFormatter = IndexAxisValueFormatter(values: dataPoints)
        chartView.xAxis.granularity = 1.0
        chartView.xAxis.labelPosition = .bottom
        chartView.xAxis.drawGridLinesEnabled = true
        chartView.xAxis.labelTextColor = UIColor(named: "checkAxisColor")!
        
        chartView.leftAxis.labelTextColor = UIColor(named: "checkAxisColor")!
        
        chartView.legend.textColor = UIColor(named: "checkAxisColor")!
        
        chartView.rightAxis.drawAxisLineEnabled = false
        chartView.rightAxis.enabled = false
        
        chartView.scaleXEnabled = false
        chartView.scaleYEnabled = false
        
        chartView.animate(xAxisDuration: 1)
        
        return chartView
    }
    
    func updateUIView(_ uiView: LineChartView, context: Context) {
        
        var dataEntries: [ChartDataEntry] = []
        
        for i in 0..<dataPoints.count {
            let dataEntry = ChartDataEntry(x: Double(i), y: values[i])
            dataEntries.append(dataEntry)
        }
        
        let lineChartDataSet = LineChartDataSet(entries: dataEntries, label: self.title)

        lineChartDataSet.fillColor = UIColor(named: "chartBar")!
        lineChartDataSet.lineWidth = 1
        lineChartDataSet.drawValuesEnabled = self.drawValueLabel
        
        lineChartDataSet.drawCirclesEnabled = false
        lineChartDataSet.circleHoleColor = UIColor(named: "chartBar")
        lineChartDataSet.drawCircleHoleEnabled = false
        
        lineChartDataSet.colors = [UIColor(named: "chartBar")!]
        
        let lineChartData = LineChartData(dataSet: lineChartDataSet)
        
        uiView.data = lineChartData
        
    }
}`

**Comment by liuxuan30** [comment]
well.. need log rather than code sample. For such issues, it's usually the data casues the matrix invalid. So you probably want to check your data entry first

**Comment by ccworld1000** [comment]
This problem should be opened. I also have this problem. The original problem of illegal data also has the problem of singular matrix

**Comment by ccworld1000** [comment]
I made a demo to demonstrate the existence of this problem
[demo git](https://github.com/ccworld1000/CCSingularMatrixProblem.git)

**Comment by bogdandovgopol** [comment]
getting the same errors when my dataset is empty.

**Comment by xsleonard** [comment]
This occurs if there are 2 or more data entries and all entries have the same y value
