### ISSUE TITLE
how to set the legend's position?

### ISSUE THREAD

**Issue by LuDamon** [danielgindi/Charts#4292]
![Simulator Screen Shot - iPhone 11 - 2020-02-17 at 14 01 15](https://user-images.githubusercontent.com/14227723/74627509-0b98f180-518e-11ea-86b7-50a4f5ce3f55.png)

I want set the legend at the right of pieChartView, but I don't know how to set? help~  thank you~

**Comment by danielgindi** [comment]
The demos are there for a reason. So is the property accessors on the chart views.
