### ISSUE TITLE
can i customise your chart?

### ISSUE THREAD

**Issue by krutitrivedi** [danielgindi/Charts#4301]
Hello i want to develop chart which i attached in screen short, so can i achieve that design using your library?
![Screenshot 2020-02-25 at 5 12 10 PM](https://user-images.githubusercontent.com/28212734/75517926-d742f200-5a25-11ea-97a2-f08e1f5588f2.png)
 the issue.

**Comment by liuxuan30** [comment]
well you have to override a bunch of methods to do so. Of course you can since it's open source
