### ISSUE TITLE
Error when running on a phone

### ISSUE THREAD

**Issue by amydowse** [danielgindi/Charts#4304]
When I run my application on the simulator on my laptop, everything works as expected.

However when I try to run the same application on my phone it does not run and the error is:

dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /private/var/containers/Bundle/Application/D6B5A566-43D6-42C7-8B02-98DD2FCE901F/Here.app/Here
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/D6B5A566-43D6-42C7-8B02-98DD2FCE901F/Here.app/Frameworks/Charts.framework/Charts: code signature invalid for '/private/var/containers/Bundle/Application/D6B5A566-43D6-42C7-8B02-98DD2FCE901F/Here.app/Frameworks/Charts.framework/Charts'

## What did you do?
I have cleaned the build folder, updated CocoaPods and update Charts within CocoaPods.

## What did you expect to happen?
I hoped the update would mean that the app would run on my phone. 

## What happened instead?
The app won't run at all on my phone - it used to. It runs perfectly fine on the simulator on my mac.

## Charts Environment

**Charts version/Branch/Commit Number: 3.4.0
**Xcode version: 11.2.1
**Swift version: 5
**Platform(s) running Charts: ?Not sure what you mean
**macOS version running Xcode: 10.15.3

**Comment by kudzaiTnexus** [comment]
did you find a solution to this, im having the same issue

**Comment by amydowse** [comment]
Hi - it was an issue with the iOS version on my phone. I believe at the time of the issue I was running iOS14. When there was an update for iOS it solved the issue. My phone is now running 14.2 and it all works fine.
