### ISSUE TITLE
Compatibility with SwiftUI

### ISSUE THREAD

**Issue by famictech2000** [danielgindi/Charts#4305]
Is this library compatible with SwiftUI? Or only with swift and storyboards?

**Comment by philipengberg** [comment]
Any ordinary `UIView` is by default SwiftUI compatible using the `UIViewRepresentable` protocol provided by Apple.

**Comment by liuxuan30** [comment]
But I think the performance cannot compare to SwiftUI?  rewriting the framework for SwiftUI is too much as we checked last year
