### ISSUE TITLE
Module compiled with Swift 5.1.2 cannot be imported by Swift 5.2 compiler

### ISSUE THREAD

**Issue by afridikhalid** [danielgindi/Charts#4317]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Updated to Xcode 11.4 and run Carthage update  

## What happened instead?

ℹ importing chart Xcode gives the following error: 
Module compiled with Swift 5.1.2 cannot be imported by Swift 5.2 compiler: /User/username/ios/Carthage/Build/iOS/Charts.framework/Modules/Charts.swiftmodule/arm64-apple-ios.swiftmodule  

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: 11.4
**Swift version: 5.2
**Platform(s) running Charts: iOS
**macOS version running Xcode:10.15.4

**Comment by liuxuan30** [comment]
damn. I will see if we can release a new build. Such things still waiting to be done after the full ABI support is enabled.

**Comment by gk-brown** [comment]
Have you considered converting to an XCFramework?

**Comment by gk-brown** [comment]
I was able to resolve the compilation issues. They were all method visibility issues (internal vs. open/public). Would be happy to submit a pull request.
