### ISSUE TITLE
The Demo app Doesn't compile for tvOS

### ISSUE THREAD

**Issue by reubensjohn** [danielgindi/Charts#4320]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Try building the demo for tvOS

## What did you expect to happen?

ℹ I was expecting the code to compile for tvOS and I could run the demo in AppleTV as th etarget

## What happened instead?

ℹ The demo project failed to compile. with error UISlider not available in tvOS

## Charts Environment

**Charts version 3.4.0/Branch-master/Commit Number:** NA
**Xcode version: 11.3.1**
**Swift version: 5.1**
**Platform(s) running Charts: tvOS**
**macOS version running Xcode: catalina 10.15.4**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by liuxuan30** [comment]
I don't think we have a TV demo app
