### ISSUE TITLE
Build error Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by Annelies1** [danielgindi/Charts#4322]
## What did you do?

I updated XCode to 11.4

## What did you expect to happen?

Charts should compile, like it did on previous version of Xcode.

## What happened instead?

I get a build error:
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

## Charts Environment

**Charts version/Branch/Commit Number: 3.4.0 Release
**Xcode version: 11.4
**Swift version: 5.2
**Platform(s) running Charts: iOS
**macOS version running Xcode: Catalina 10.15.3 

## Demo Project
none

**Comment by afridikhalid** [comment]
I have the same issue I had opened an issue but they have closed that I don't know when a fix will be out because anyone using charts can not update their Xcode version

**Comment by liuxuan30** [comment]
should solved with latest release
