### ISSUE TITLE
How to remove top grid line for line chart

### ISSUE THREAD

**Issue by josmanperez** [danielgindi/Charts#4343]
Hi!, I just cant find the option to remove the top grid line from the linechart. 

I want to remove this line here: 

<img width="473" alt="Screenshot 2020-04-18 at 22 10 30" src="https://user-images.githubusercontent.com/5773453/79670202-92377280-81c1-11ea-9a64-a99cac49e332.png">

I've done this, but this just remove the right and left grid but not the one on top:

```  
        chartView.leftAxis.drawGridLinesEnabled = false
        chartView.leftAxis.drawLabelsEnabled = false
        chartView.leftAxis.drawGridLinesBehindDataEnabled = false
        chartView.leftAxis.gridColor = .clear
        chartView.leftAxis.axisLineColor = .clear
        chartView.rightAxis.drawGridLinesEnabled = false
        chartView.xAxis.drawGridLinesEnabled = false
        chartView.xAxis.drawGridLinesBehindDataEnabled = false
        chartView.rightAxis.drawLabelsEnabled = false
        chartView.rightAxis.drawGridLinesBehindDataEnabled = false
        chartView.rightAxis.gridColor = .clear
        chartView.rightAxis.axisLineColor = .clear
```

Thank you

**Comment by josmanperez** [comment]
Hello, I'm answering my own question.

This two lines made the trick:
```
        chartView.xAxis.drawAxisLineEnabled = false
        chartView.xAxis.labelTextColor = .clear
```

Thank you!

**Comment by navasiloy** [comment]
instead of        
`chartView.xAxis.labelTextColor = .clear`

better to use 
`chartView.leftAxis.drawLabelsEnabled = false`
