### ISSUE TITLE
Set images on xAxis on HorizontalBarChartView

### ISSUE THREAD

**Issue by inigollamosas** [danielgindi/Charts#4353]
I dont see anywhere nothing like it, but just in case. Has anybody ever achieved such thing?

**Comment by tiagorc** [comment]
have you tried icon while creating DataEntry?

BarChartDataEntry(x: <#T##Double#>, y: <#T##Double#>, icon: <#T##NSUIImage?#>, data: <#T##Any?#>)

**Comment by inigollamosas** [comment]
For anybody coming up with this problem. The solution I found is to create a custom XAxisRenderer and add and UIImage on index position on drawLabels() method.
