### ISSUE TITLE
SwiftUI tutorial Bar Chart

### ISSUE THREAD

**Issue by Basistiy** [danielgindi/Charts#4360]
Hi, Daniel! I have created a guide concerning Charts + SwiftUI.
Can you, please, review it? Can it be published in third party tutorials section?

https://medium.com/@zzzzbh/plotting-in-ios-using-charts-framework-with-swiftui-222034a2bea6?sk=acccb92cff5083ac4fe146f057ef7a6b

**Comment by liuxuan30** [comment]
seems duplicate. Please just file a PR (change README markdown in the right section)

**Comment by Basistiy** [comment]
Sorry about the problem with my first PR! I have created a new one.

пн, 22 июн. 2020 г. в 04:58, Xuan <notifications@github.com>:
