### ISSUE TITLE
Chart load with large amounts of data takes to much time

### ISSUE THREAD

**Issue by pratik-123** [danielgindi/Charts#4372]
Chart load with large amounts of data takes to much time

- I have plotted 50000 line chart data
- When screen load at that time "No chart data available" display for chart
- After takes some times (around 40-50 seconds) chart will be display and screen also squeezed

Is there any notifications or delegate method for chart render success completion method available?

If chart render complain method available then we show loader and hide loader when completion notify.

**Comment by liuxuan30** [comment]
I have plotted 50000 line chart data

this is a known issue as we cannot hold that much. besides, you might want to sampling it, as showing 50k dots for a line is kind of meaningless. the resolution of the screen is yet around 1080p.

**Comment by pratik-123** [comment]
Screen size doesn't matter but we need to display at least data.
Any way I can display loader based on calculating time for data.
