### ISSUE TITLE
why y asix value is getting more and more high, how to disable it

### ISSUE THREAD

**Issue by neatlife** [danielgindi/Charts#4425]
![image](https://user-images.githubusercontent.com/4076198/88351853-4aa91f80-cd8a-11ea-88ac-e6c0865a105d.png)

## What did you do?

make a lineChartView with Charts,  replace the chart data every second, when chart display y asix, it happen y asix is all data sum value, and very high value at start point

## What did you expect to happen?

do not need sum y asix

**Comment by bivant** [comment]
Seems like a data issue. Have a link to a sample to reproduce?

**Comment by neatlife** [comment]
thanks, my problem
