### ISSUE TITLE
MacOS: scrollbars

### ISSUE THREAD

**Issue by lienbacher** [danielgindi/Charts#4426]
Hello!
I am new to writing Mac apps and am trying to write a Mac-os app utilizing charts. I manage to zoom and scale the x axis, however I have some very detailed data an once zoomed it is very hard to see the actual location of the x-axis. Is there a way to show a scrollbar in the bottom to see and quickly adjust the current x-position? I am also having trouble to get scrolling with gestures working. 
Any pointers would be highly appreciated!

**Comment by bivant** [comment]
Hello.
Which chart type do you use?
BarChartView has method `setVisibleXRange`. You can add logic to "sync" scroll bar position to the chart scroll through it. I do not for sure, but saw no mentions of a scroll bar in the issues of the library. Probably it is not supported. 

This library is made after [the android counterpart](https://github.com/PhilJay/MPAndroidChart#documentation) so it makes sense to search for the solution there as it has [documentation](https://javadoc.jitpack.io/com/github/PhilJay/MPAndroidChart/v3.1.0/javadoc/).
[Similar question](https://stackoverflow.com/questions/33195553/how-can-i-make-my-horizontalbarchart-scrollable)
[Another scroll bar question](https://github.com/PhilJay/MPAndroidChart/issues/2777)

**Comment by lienbacher** [comment]
I'm using a lineview chart. It scrolls fine when using mouse-drag, calling the zooming api is also not a problem. I've found some code-examples for the gestures as well, guess I should get that done. Just the scrollbar is a huge question mark, but I guess I'll have to implement a custom NSScroller on top of the chart and link it to the visible x-range ...
