### ISSUE TITLE
3.5.0 from 3.4.0 introduced a regression in pan handling

### ISSUE THREAD

**Issue by heumn** [danielgindi/Charts#4442]
First of, thanks for an *AWESOME* library 🚀 

`chartViewDidEndPanning` is not being called in 3.5.0 after this change: 

https://github.com/danielgindi/Charts/pull/4271

if anyone is interested, I am using this fork for now: https://github.com/GetBlast/Charts/commit/22e8eca5af55e11c41644a498bc941dd859c2680 from @tsorencraig

**Comment by espitia** [comment]
Having the same issue with `LineChartView`'s delegate (`chartViewDidEndPanning` not getting called).

**Comment by Archez** [comment]
Would be nice to have a new delegate method to handle when highlight drag has ended or maybe add a new parameter to the existing `chartViewDidEndPanning` to differentiate which panning action happened.

**Comment by Donkov76** [comment]
Yes, a new delegate method, please!
Not nice but this "workaround" helped me:
`      let pan =  lineChartView.gestureRecognizers?.first { $0 is UIPanGestureRecognizer }
        pan?.addTarget(self, action: #selector(gestureRecognized(_:)))

    @objc func gestureRecognized(_ recognizer: UIPanGestureRecognizer) {
        if recognizer.state == .ended || recognizer.state == .cancelled {
            // Pan Ended
        }
    }

`
