### ISSUE TITLE
If you get an element of the histogram, then change the color

### ISSUE THREAD

**Issue by xieguangming** [danielgindi/Charts#4446]
![IMG_0148](https://user-images.githubusercontent.com/13427559/90122607-212f5280-dd90-11ea-8013-563c252af031.PNG)

我选择第一条柱状图时，图选中状态，颜色变深，底下列表对应的数据也会变深

反过来，我点击下面列表某条数据，柱状图对应的数据颜色加深可以实现吗？

从外部单独获取柱状图某条数据，然后设置其颜色，要实现这个功能

**Comment by xieguangming** [comment]
When I select the first bar graph, the color of the graph becomes darker when the graph is selected, and the data corresponding to the list below also becomes darker

Conversely, if I click on a piece of data in the list below, can the color of the data corresponding to the histogram be darkened?

Obtain a piece of histogram data separately from the outside, and then set its color, to achieve this function

**Comment by bivant** [comment]
Hello @xieguangming 

ChartViewBase.swift
```swift
    /// Highlights the values at the given indices in the given DataSets. Provide
    /// null or an empty array to undo all highlighting. 
    /// This should be used to programmatically highlight values.
    /// This method *will not* call the delegate.
    @objc open func highlightValues(_ highs: [Highlight]?)
```

**Comment by xieguangming** [comment]
> 你好@xieguangming
> 
> ChartViewBase.swift
> 
> ```swift
>     ///突出显示给定数据集中给定索引处的值。提供
>     ///为 null或一个空数组，以撤消所有突出显示。
>     ///这应该用于以编程方式突出显示值。
>     ///此方法*不会*调用委托。
>     @objc  开 FUNC  highlightValues（_  高位：[光] ？）
> ```
Okay thank you
