### ISSUE TITLE
Xcode 12 beta Gives Deployment Target Warning

### ISSUE THREAD

**Issue by nicolas-miari** [danielgindi/Charts#4448]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Built my app using Xcode 12 beta. 

## What did you expect to happen?

No new warnings.

## What happened instead?

I got this warning:

> The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.  

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:** 12.0 beta 3 (12A8169g)
**Swift version:** 5
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 10.15.6 (19G73)

## Demo Project

---

**Comment by Ettariella** [comment]
This is a CocoaPods issue: [https://github.com/CocoaPods/CocoaPods/issues/9884](url) caused by Xcode dropping iOS 8 support.

Until CocoaPods is updated to fix this, the workaround is to either change the pod's deployment target, or have CocoaPods remove the deployment target from the pod entirely by adding the following to the podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
````

**Comment by nicolas-miari** [comment]
@Ettariella 
Perhaps I should have mentioned that my project integrates Charts using Swift Package Manager, not Cocoapods.

**Comment by Mozahler** [comment]
Also Swift Package Manager produces same warning

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods
