### ISSUE TITLE
How can i set each slice percentage different color?

### ISSUE THREAD

**Issue by Rylaa** [danielgindi/Charts#4451]
Hi everyone,

I have two slices on pie chart. I want to set percentage text to different color on pie chart.  
Can i change percentage text location on the slices?

![Screen Shot 2020-08-21 at 08 46 37](https://user-images.githubusercontent.com/33103001/90856558-db274f80-e38a-11ea-9077-39ef0a232ad2.png)

**Comment by amoshsueh** [comment]
Hi @Rylaa, do you have any idea to achieve this?
