### ISSUE TITLE
Charts not supported by xcode 12 and swift compiler version 5.3

### ISSUE THREAD

**Issue by brams-9** [danielgindi/Charts#4471]
## What did you do?

update to Xcode 12 and update swift compiler to version 5.3

Current workaround: revert back to xcode 11.7 and use toolchain to revert to swift 5.2.4

## What did you expect to happen?
i expect it to build successfully

## What happened instead?
![Screen Shot 2020-09-20 at 10 55 03](https://user-images.githubusercontent.com/56192259/93693895-edcea900-fb2f-11ea-9e7d-2b892a035844.png)

## Charts Environment

**Charts version/Branch/Commit Number: 3.5.0/Master/14da743 **
Xcode version:12
Swift version: 5.3
Platform(s) running Charts: iOS
macOS version running Xcode: 10.15.6

**Comment by 5teveroy** [comment]
I do use this version of Charts with Xcode 12 and SPM without problems.

This might just be a case of stale object files. Have you tried doing a clean build or deleting the derived data?

**Comment by brams-9** [comment]
> I do use this version of Charts with Xcode 12 and SPM without problems.
> 
> This might just be a case of stale object files. Have you tried doing a clean build or deleting the derived data?

well i already did clean build and deleting the derived data the result is still the same,it still showing error "module compiled with swift 5.2.4 cannot be imported by the swift 5.3 compiler"
@5teveroy

**Comment by liuxuan30** [comment]
I'm going to release one soon for Xcode 12
