### ISSUE TITLE
Charts not found in  Xcode 12

### ISSUE THREAD

**Issue by MichalMisiaszek** [danielgindi/Charts#4480]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Updated Xcode to 12

## What did you expect to happen?

Nothing. 

## What happened instead?

Chart module not found anymore when compiling Obj-C code.

## Charts Environment

**Charts version/Branch/Commit Number:** 3.3.0 and master
**Xcode version:** 12.0
**Swift version:**?
**Platform(s) running Charts:** iOS
**macOS version running Xcode:**Catalina

## Demo Project

I don't have it.

**Comment by EthanHess** [comment]
Yea same is happening for me, usually adding $(inherited) to Header Search Paths does the trick but not this time, I reverted back to Xcode 11.7.

**Comment by MichalMisiaszek** [comment]
I managed to make it work on xcode 12 buy changing auto generated
 Swift Header name and include it.

**Comment by MichalMisiaszek** [comment]
I changed settings in Chart project and then included `#import "Charts/Charts-Swift.h"` in my code. It fixed the issue of the chart module not found.
![image](https://user-images.githubusercontent.com/11050727/94997277-e0b5af00-055e-11eb-8c61-9e6248fc1b8f.png)
