### ISSUE TITLE
Weird bar width after setting `setVisibleXRangeMaximum` for Barchart

### ISSUE THREAD

**Issue by lalkrishna** [danielgindi/Charts#4506]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Added this line after data is set for Barchart's iOS swift Example project.
`chartView.setVisibleXRangeMaximum(3)`

Move sliderX to increase bars and reset to initial count.

## What did you expect to happen?

Showing 3 bars and can able to scroll horizontally to view other bars., even if the xValues counts changed.

## What happened instead?

3 bars are visible for the first time when I set new large values for X axis.(move slider forward).
But when I move back the slider to initial position, the bar's width is increased drastically.

Related Stackoverflow question: https://stackoverflow.com/questions/64911914/barchart-not-working-as-expect-after-calling-setvisiblexrangemaximum

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version:** 12.1
**Swift version:** 5.2
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** BigSur

## Demo Project

Check project's ChartsDemo-iOS-Swift

**Comment by lalkrishna** [comment]
Any update on this?

**Comment by kazi05** [comment]
Make `chartView.fitScreen()` before every time that you set `setVisibleXRangeMaximum(_)`

**Comment by lalkrishna** [comment]
Thanks for you comment @kazi05 . It works :)

**Comment by lalkrishna** [comment]
Thanks for you comment @kazi05  . It works :)

**Comment by gurpreetKobe** [comment]
Does not seem to work in version 4.0.3. I call fitScreen before calling setVisibleRangeMaximum() but the bar width seems to keep on increasing every time I setVisibleRangeMaximum. Facing this issue in iOS. @danielgindi  @liuxuan30
