### ISSUE TITLE
Master branch doesn't compile

### ISSUE THREAD

**Issue by ChristianVinterly** [danielgindi/Charts#4521]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Updated Pods project to 4.0 and built from master branch

## What did you expect to happen?

Project to compile

## What happened instead?

<img width="383" alt="Screenshot 2020-12-03 at 10 11 22" src="https://user-images.githubusercontent.com/12391750/100988684-44089100-3550-11eb-8b97-db064c6cb137.png">

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0/Master
**Xcode version:** 12.2
**Swift version:** 5.3
**Platform(s) running Charts:** iOS
**macOS version running Xcode:**

**Comment by ChristianVinterly** [comment]
For instance is the `Double`- extension `roundedToNextSignificant` misspelled as `roundedToNextSignficant` at call site at `AxisRendererBase`.

**Comment by quifago** [comment]
I have the same issue. Not compiling the v4.0.0 tag using SPM. I get the same errors reported by @ChristianVinterly and a few more.

**Comment by scinfu** [comment]
Me too
