### ISSUE TITLE
iOS 14's WidgetKit support

### ISSUE THREAD

**Issue by Kanunnikoff** [danielgindi/Charts#4529]
Good afternoon!

It would be great to have a WidgetKit support. Right now it is impossible to use this library with iOS 14's widgets.

Regards.

**Comment by jjatie** [comment]
Widgets are supposed to be lightweight, and as such embedding a ChartView in some way is probably not ideal. A common solution is to use an image of a ChartView which can be obtained from the `    open func getChartImage(transparent: Bool) -> NSUIImage?` method on `ChartViewBase`
