### ISSUE TITLE
Fill Color in linear chart different color for above and below values

### ISSUE THREAD

**Issue by PedroCavaleiro** [danielgindi/Charts#4535]
I'm currently using the latest version o Charts for Swift with SwiftUI, I created a NSViewRepresentable (it's for macOS) and I want to use multiple colors for one data set (Line Chart) so far I was able to get the line with multiple colors by overriding the function `drawLinear` but I want to use a filling but I want the same color as the line. This is what I have so far

![Screen Shot 2020-12-17 at 15 12 53](https://user-images.githubusercontent.com/1993871/102505839-61724a80-407a-11eb-8835-7bc449320847.png)

What I want now is when the line color changes, also changes the area color, if possible with a gradient, if not just a color, meaning when the line is red the filling is red and so on...

I also have the functions `drawLinearFill` and `generateFilledPath` ready to be overridden but I'm not sure how to replace them properly

**Comment by andreyleganov** [comment]
Same case, I need to display one line with different colors and gradients above and below the zero line.
@PedroCavaleiro Hey, can you show your overridden drawLinear function code please

**Comment by PedroCavaleiro** [comment]
This is how I did it, there are functions specific to my needs but they are easily changed, I'm still unable to change the color of the area though. [ColoredLineChartRenderer](https://gist.github.com/PedroCavaleiro/5dad7ba55bcf1498089f177a08f5e5e6)
I hope it helps
