### ISSUE TITLE
Xcode 12 issue

### ISSUE THREAD

**Issue by NerminEngineer** [danielgindi/Charts#4542]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I tried to build project on Xcode 12 with Charts version 4.0.0 and got this error:

**Module compiled with Swift 5.2.4 cannot be imported by the Swift 5.3.1 compiler** 

## What did you expect to happen?

Project should build successfully.

## What happened instead?

Build failed.

## Charts Environment

**Charts version/Branch/Commit Number: 4.0.0**
**Xcode version: 12.2** 
**Swift version: 5.3.1**
**Platform(s) running Charts:**
**macOS version running Xcode: macOS Catalina 10.15.7**

**Comment by k0syan** [comment]
@NerminEngineer got the same issue. Do you have any solution for this?

**Comment by dudenamedjune** [comment]
same

**Comment by jjatie** [comment]
Unable to reproduce on current `master`. Feel free to report a new issue if this persists.
