### ISSUE TITLE
How to change icon legend from square to circle?

### ISSUE THREAD

**Issue by shin1412** [danielgindi/Charts#4545]
Hello, I’ve implemented the Charts library for the pie chart in my project.
I have shown it like this:
![Screen Shot 2020-12-30 at 11 31 09](https://user-images.githubusercontent.com/38929797/103330170-eefa6500-4a92-11eb-8bd9-7bc76b84e2c7.png)
but, I want:
![Screen Shot 2020-12-30 at 11 34 41](https://user-images.githubusercontent.com/38929797/103330218-118c7e00-4a93-11eb-9ea0-c9f119617ebc.png)
Here is my code:
```
chartView.delegate = self
        chartView.rotationEnabled = false
        chartView.transparentCircleRadiusPercent = 0
        chartView.drawEntryLabelsEnabled = false

        // set label entry
        let l = chartView.legend
        l.horizontalAlignment = .right
        l.verticalAlignment = .center
        l.orientation = .vertical
        l.yEntrySpace = 10
        l.yOffset = 30
        l.xOffset = 20
        l.font = UIFont.systemFont(ofSize: 12)

        chartView.holeRadiusPercent = 0.40
```
How can I do it?

**Comment by shin1412** [comment]
I have found the solution!
```
chartView.legend.form = .circle
```

**Comment by techacharya** [comment]
let l = chartView.legend
        l.horizontalAlignment = .right
