### ISSUE TITLE
Error importing module after SPM install

### ISSUE THREAD

**Issue by sjdevlin** [danielgindi/Charts#4547]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines]
* [ X] ## What did you do?

I added Charts to my xcode project using the SPM.  This installed correctly and the dependency appears to be correct in the config screens.  Then tried to add the library to the ViewController.swift file in my empty project with "import Charts" 

## What did you expect to happen?

I expected to be able to then import the Charts library and start referencing its structs and classes.  *note* this is not an issue with my xcode config as I have successfully added other swift packages in exactly the same way and then was able to import their libraries

## What happened instead?

Immediately get Xcode build error "no such module Charts" 

## Charts Environment

**Charts version/Branch/Commit Number: 3.6
**Xcode version: Version 12.2 (12B45b)
**Swift version: 5.2
**Platform(s) running Charts: OSX
**macOS version running Xcode: 11.1

ℹ Please link to or upload a project we can download that reproduces the issue.

This does not appear to be related to my project code.  I replicate the same error if I create a brand new iOS App project, which is completely empty.

**Comment by boveylisi2013** [comment]
I could resolve this issue by "install from the master branch instead of the release version 4.0.0".
Also, select install product "Charts" into your Target. Do not select "ChartDynamics".
Happy coding!

**Comment by jjatie** [comment]
#4533 Should resolve this

**Comment by sjdevlin** [comment]
Thank you Jacob and Daniel.  That is great .

And thank you for this wonderful library.  

Best wishes from Cornwall, UK

Stephen
