### ISSUE TITLE
how can i remove data entry label and color list displayed under the bar chart?

### ISSUE THREAD

**Issue by RaniaAAH** [danielgindi/Charts#4554]
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-14 at 18 48 49](https://user-images.githubusercontent.com/32203545/104622603-27589080-569a-11eb-9275-6b6e8f0d6428.png)

Please how can I remove the highlighted color?

**Comment by aaparth** [comment]
@RaniaAAH 

may be you can try the following line of code

`viewBarChart.legend.enabled = false`

**Comment by RaniaAAH** [comment]
@aaparth Thanks a lot
