### ISSUE TITLE
Following old real time example problems

### ISSUE THREAD

**Issue by poml88** [danielgindi/Charts#4561]
Hi,

I am trying to follow this example
https://github.com/danielgindi/Charts/issues/2859#issuecomment-336403810
using xcode 12 and Charts 3.6.0

I get two issues:
`set1 = LineChartDataSet(values: yEntries, label: "DataSet 1")` is giving me
`Incorrect argument label in call (have 'values:label:', expected 'entries:label:')`
So I guess it should be
`set1 = LineChartDataSet(entries: yEntries, label: "DataSet 1")` now.
So far so good.

But then at
`var set1 = LineChartDataSet()
        set1 = (chartView.data?.dataSets[0] as? LineChartDataSet)!
        
        set1.entries = yEntries
 
        chartView.data?.notifyDataChanged()
        chartView.notifyDataSetChanged()`
I get for 
`set1.values = yEntries`
`Cannot assign to property: 'values' is a get-only property`

and I am not able to figure out how to fix this. Any ideas?
Maybe also other people trying that example will run into this issue.
Thanks

**Comment by thierryH91200** [comment]
look at https://github.com/thierryH91200/DemoChartOSX-4

**Comment by poml88** [comment]
That was a quick reply, just one minute. Thank you!
I'll check it out.
Maybe you can add a link to your demo in the other issue?

**Comment by poml88** [comment]
Ahhh, it has to be
`set1.replaceEntries(yEntries)`
now I get it.
