### ISSUE TITLE
Detect if no chart value is selected?

### ISSUE THREAD

**Issue by brettfazio** [danielgindi/Charts#4562]
I'm currently using `chartValueSelected` to detect what value the user selects on my chart so I can update a label. 

When the user stops dragging / tapping among entries on my `LineChartView` I would like to return the label to the last entry in the chart.

I've tried `chartValueNothingSelected` but this does not work for me. Basically when the user lifts their finger off the chart and moves it to elsewhere the UI I would like to set my label/state back to the last entry.

Is there a good way people are doing thing? Perhaps a delegate method I am missing or just using a gesture recognizer (if using a gesture recognizer, what exactly are you doing with it?).

**Comment by JanC** [comment]
hey,
I was looking for the same behaviour and it looks like it's not supported by default. As you noticed, `chartValueNothingSelected` is called only when the user explicitly taps outside of any value but not when he stops dragging.

I've achieved the result by adding a new `UIPanGestureRecognizer` to the view where I call `view?.highlightValue(nil, callDelegate: true)` when the user stops dragging. This calls the `chartValueNothingSelected`

To avoid that your new `UIPanGestureRecognizer` "intercepts" the gestures used by the `LineChartView`, you need to implement the `UIGestureRecognizerDelegate` delegate `shouldRecognizeSimultaneouslyWith` and return `true`.

```swift
func setupGesture(view: LineChartView) {
    let unselectGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(panGestureRecognized(_:)))
    unselectGestureRecognizer.delegate = self
    view.addGestureRecognizer(unselectGestureRecognizer)
}


@objc func panGestureRecognized(_ recognizer: UIPanGestureRecognizer) {
    print("My gesture")
    if recognizer.state == .ended {
        view?.highlightValue(nil, callDelegate: true)
    }
}

// MARK: - UIGestureRecognizerDelegate

func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
}

// MARK: - ChartViewDelegate
func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
    print("Selected: \(entry), highlight: \(highlight), highlight.dataSetIndex: \(highlight.dataSetIndex)")
}
func chartValueNothingSelected(_ chartView: ChartViewBase) {
    print("unselect")
}

```

Then the result is
![2021-01-26 08 42 38](https://user-images.githubusercontent.com/707703/105815004-8da2b480-5fb2-11eb-9066-5f64aaa4648a.gif)


Hope it helps

**Comment by brettfazio** [comment]
Thank you for such a thorough response @JanC ! By adding the gesture recognizer you described to my `UIViewRepresentable` I was able to add the selector to my coordinator and it properly get the call whenever I lift my finger.

However, I no longer see the vertical line as I drag my finger across the screen, in fact `chartValueSelected` doesn't seem to be called at all now that the recognizer is there. I'm not really sure of the root cause. Maybe it has something to do with the fact I'm doing `UIViewRepresentable`?

Below is how I'm going about implementing it. If I just remove all code that has to deal with the gestures then `chartValueSelected` is properly called again.

```swift
struct LineView: UIViewRepresentable {
    typealias UIViewType = LineChartView
    
    var entries: [ChartDataEntry]
    
    @Binding var entry: ChartDataEntry
    
    @State var shouldReset: Bool = false
    
    class Coordinator: NSObject, ChartViewDelegate, UIGestureRecognizerDelegate {
        
        var parent: LineView
        
        public var reset: Bool = false
        
        init(_ parent: LineView) {
            self.parent = parent
        }
        
        func chartValueSelected(_ chartView: ChartViewBase, entry: ChartDataEntry, highlight: Highlight) {
            // This is no longer printed.
            print("selected\(entry.y)")
            parent.entry = entry
        }
        
        @objc func chartValueNothingSelected(_ chartView: ChartViewBase) {
            // This is not called
            if let last = parent.entries.last {
                parent.entry = last
            }
        }
        
        @objc func panGestureRecognized(_ recognizer: UIPanGestureRecognizer) {
            if recognizer.state == .ended {
                // This is printed at the proper time
                print("ended")
            }
        }
        
    }
    
    func makeCoordinator() -> Coordinator {
        Coordinator(self)
    }

    func makeUIView(context: Context) -> LineChartView {
        let view = LineChartView()
        
        view.drawGridBackgroundEnabled = false
        
        view.legend.enabled = false

        view.xAxis.enabled = false
        view.rightAxis.enabled = false
        view.leftAxis.enabled = false
        
        view.dragEnabled = true
        
        view.xAxis.drawGridLinesEnabled = false
        view.leftAxis.drawGridLinesEnabled = false
    
        view.delegate = context.coordinator
        
        view.doubleTapToZoomEnabled = false
        // Gesture code
        let unselectGestureRecognizer = UIPanGestureRecognizer(target: context.coordinator, action: #selector(Coordinator.panGestureRecognized(_:)))
        unselectGestureRecognizer.delegate = context.coordinator

        view.addGestureRecognizer(unselectGestureRecognizer)

        view.data = addData()
        return view
    }
    
    func addData() -> LineChartData {
        let data = LineChartData()
        let dataset = LineChartDataSet(entries: entries)

        dataset.drawHorizontalHighlightIndicatorEnabled = false
        
        dataset.highlightColor = UIColor.teal
        
        data.addDataSet(dataset)
        
        return data
    }
    
    func updateUIView(_ uiView: LineChartView, context: Context) {
        // Handle resetting here
        uiView.data = addData()
    }
}

```

**Comment by JanC** [comment]
> Maybe it has something to do with the fact I'm doing UIViewRepresentable?

 I'm also using a `UIViewRepresentable` and the `Context` is my delegate. You are missing this `UIGestureRecognizerDelegate` method

```swift
// MARK: - UIGestureRecognizerDelegate

func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
    return true
}
```

**Comment by brettfazio** [comment]
Wow that works perfect! That you again!

I guess `Charts` is using a gesture recognizer as well so this prevented theirs from working? If so maybe this functionality could be added as a method in `LineChartView`

**Comment by JanC** [comment]
yeah that's the reason. This delegate tells the `UIPanGestureRecognizer` that both "yours" and the ChartView's gesture recogniser should work at the same time.

>  If so maybe this functionality could be added as a method in 

Probably yes.

**Comment by brettfazio** [comment]
Wow that works perfect! Thank you again!

I guess `Charts` is using a gesture recognizer as well so this prevented theirs from working, maybe this functionality could be added as a method in `LineChartView`

> You also need to tell chartView to unselect the value when your gesture ends:
Are you calling this from your Coordinator? At least with the way I set mine up and how I've seen others set theirs up it doesn't have direct access to the underlying view of the view.

**Comment by JanC** [comment]
> Are you calling this from your Coordinator? 

Yes, 

>  it doesn't have direct access to the underlying view of the view.

That's true indeed because the `UIViewRepresentable.makeCoordinator()` is called before the `makeUIView(context: Context)`.

However, you can set the chartView as a `var` on the Coordinator and then set in in the `makeUIView`

```swift
    func makeCoordinator() -> Coordinator {
        Coordinator(selection: $selection)
    }

    func makeUIView(context: Context) -> LineChartView {
        let chartView = LineChartView()
        chart.delegate = context.coordinator
        context.coordinator.chartView = chartView
       ...
       
       }
```

and in your Coordinator

```
    class Coordinator: NSObject, ChartViewDelegate, UIGestureRecognizerDelegate {
        weak var view: LineChartView?
```

**Comment by JanC** [comment]
@brettfazio does it answer your questions? If yes, can you close the ticket?

**Comment by brettfazio** [comment]
Yep that works for me. Thanks.
