### ISSUE TITLE
Line chart displaying two datasets leads to fatal error index out of range

### ISSUE THREAD

**Issue by poml88** [danielgindi/Charts#4571]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Run the below code example

## What did you expect to happen?

A nice plot with two graphs

## What happened instead?

Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
2021-02-01 21:11:49.285724+0100 testCharts[11213:212535] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444

## Charts Environment

**Charts version/Branch/Commit Number: 4.0.0 **
**Xcode version: 12.3 **
**Swift version: 5 **
**Platform(s) running Charts: iOS **
**macOS version running Xcode: 10.15.6 **

## Demo Project

I'll post it below.

Hi, I just upgrade from 3.6.0 to 4.0.0 and found out that I have trouble with the below chart.
I have two datasets, and it worked fine with 3.6.0, but with 4.0.0 I get a
```
Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
2021-02-01 21:20:12.111618+0100 testCharts[11321:217641] Fatal error: Index out of range: file Swift/ContiguousArrayBuffer.swift, line 444
```

Xcode points me to ChartDataSet.swift to this section:
```
public subscript(position: Index) -> Element {
        get {
            // This is intentionally not a safe subscript to mirror
            // the behaviour of the built in Swift Collection Types
            return entries[position]
        }
        set {
            calcMinMax(entry: newValue)
            entries[position] = newValue
        }
    }
```

the error being in line 411 `return entries[position]`.

My example code runs fine, when I replace 
`let chartData = LineChartData(dataSets: [chartDataSet0, chartDataSet1])`
with
`let chartData = LineChartData(dataSets: [chartDataSet0])`
so the problem seems to be the two data sets.

A bug?

```
import UIKit
import Charts

class ViewController: UIViewController {
    
    @IBOutlet weak var chartView2: LineChartView!
    
    //    var dataEntries = [ChartDataEntry]()
    var chartDataSet0 = LineChartDataSet()
    var chartDataSet1 = LineChartDataSet()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        
        setupECGChartDataSet0()
        setupECGChartDataSet1()
        setupECGChartData()
    }
    
    func setupECGChartDataSet0() {
        
        
        let dataEntries = [ChartDataEntry(x: 0, y: 0), ChartDataEntry(x: 1, y: 1), ChartDataEntry(x: 2, y: 2)]
        chartDataSet0 = LineChartDataSet(entries: dataEntries, label: "bla")
        chartDataSet0.drawCirclesEnabled = false
        chartDataSet0.setColor(NSUIColor.black)
        chartDataSet0.drawValuesEnabled = false
        chartDataSet0.axisDependency = .left
    }
    
    func setupECGChartDataSet1() {
        let dataEntries = [ChartDataEntry(x: 3, y: 3), ChartDataEntry(x: 4, y: 4), ChartDataEntry(x: 5, y: 5)]
        chartDataSet1 = LineChartDataSet(entries: dataEntries, label: "bla")
        chartDataSet1.drawCirclesEnabled = false
        chartDataSet1.setColor(NSUIColor.black)
        chartDataSet1.drawValuesEnabled = false
        chartDataSet1.axisDependency = .left
        
    }
    
    func setupECGChartData() {
        
        let chartData = LineChartData(dataSets: [chartDataSet0, chartDataSet1])
        chartView2.data = chartData
    }
}

```

**Comment by YongbaoWang** [comment]
I also encountered the same error, which was caused by the latest swift algorithm library update.  Hope the author can fix this problem.

**Comment by hungnb94** [comment]
This bug still happens on version 5.0.0
