### ISSUE TITLE
CocoaPods not longer working (Master / v4.0.0)

### ISSUE THREAD

**Issue by StefaniOSApps** [danielgindi/Charts#4572]
## What did you do?

Build current Master Branch with Cocoapods.

## What did you expect to happen?

I can integrate this framework with cocoa pods. Like

```
  pod 'Charts',
    :git => 'https://github.com/danielgindi/Charts.git',
    :branch => 'master'
```

## What happened instead?

"import Algorithms" not working - can find Algorithms framework

## Charts Environment

**4.0.0/master/b8dba5930f293277d40ea4fb7b09af76a688ce44*
**Xcode version: 12.4 **
**Swift version: 5.3 **
**Platform(s) running Charts: iOS**
**macOS version running Xcode: 11.1**

## Reason
Frameworks were added in SPM, which were unfortunately forgotten in the PodSpec. Therefore, this framework will no longer work with CocoaPods 

## Workaround
```
  pod 'Charts',
    :git => 'https://github.com/danielgindi/Charts.git',
    :commit => '857db248f8eab9293e7845a53900ad109dc5cade'
```

**Comment by Agoer** [comment]
me too. wait for my hero.

**Comment by jstheoriginal** [comment]
For reference, it doesn't seem possible to use the Swift Algorithms library from Apple using CocoaPods, which is the blocker.

https://github.com/apple/swift-algorithms/issues/74

**Comment by sinhpn92** [comment]
So We only use v3.6.0 by cocoapods?

**Comment by Karpot** [comment]
What about the 4.0.1?

I still got to warnings in XCode with: "Using 'class' keyword for protocol inheritance is deprecated; use 'AnyObject' instead".

**Comment by StefaniOSApps** [comment]
@sinhpn92 See Workaround in main post

**Comment by StefaniOSApps** [comment]
@Karpot the topic only applies to cocoapods. You are describing something else.

**Comment by 417-72KI** [comment]
Carthage is also unavailable...

```
❌  path/to/file.swift:9:8: missing required module 'Algorithms'
import Charts
       ^
```

**Comment by liuxuan30** [comment]
hmm.. I think when I update, pod didn't support SPM. not sure what's the state now?

**Comment by liuxuan30** [comment]
Validating podspec
 -> Charts (4.0.1)
    - ERROR | [Charts/Core] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [Charts/Core] xcodebuild:  note: Using new build system
    - NOTE  | [Charts/Core] xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [Charts/Core] xcodebuild:  note: Build preparation complete
    - NOTE  | [Charts/Core] xcodebuild:  note: Planning
    - NOTE  | [Charts/Core] xcodebuild:  note: Building targets in parallel
    - ERROR | [Charts/Core] xcodebuild:  Charts/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift:12:8: error: no such module 'Algorithms'
    - NOTE  | [Charts/Core] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - NOTE  | [Charts/Core] xcodebuild:  note: Using codesigning identity override: 

[!] The spec did not pass validation, due to 2 errors.

**Comment by liuxuan30** [comment]
it seems as the last day of 2021, pod still not suppot SPM. 

So we have a hard decision to make, either drop the SPM dependency and not enjoy the efficiency from thew SDKs, or pod has to support this way of dependency.

I'm not a fan of pod but my current company invest heavily on pod, so I feel some work could only be done by pod, so I changed my view. however, this seems not possible to find a quick fix for this.

@jjatie sorry I'm long offline-ning. I probably will have a few time on this project every week or few weeks. I would hope to enjoy the new fancy tools ,but pod is still playing an important role. is it possibe to make pod support SPM/algorithm?

I will try search on pod team side or file one

**Comment by liuxuan30** [comment]
I came across CocoaPods/CocoaPods#10049 not sure if this will be a workaround. But I have no time to look deeper.. anyone  want the challenge?

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods
