### ISSUE TITLE
Support Swift Package Manager binary distribution

### ISSUE THREAD

**Issue by pokryfka** [danielgindi/Charts#4582]
Please support Swift Package Manager binary distribution.

Swift Package Manager does work correctly but Xcode keeps reloading the packages inefficiently and Charts being quite big takes long time to download.

https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by pokryfka** [comment]
BTW version 4.0.0 does not seem to be supported by SPM, also not deployed to Cocoapods

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods
