### ISSUE TITLE
No such module 'Algorithms'

### ISSUE THREAD

**Issue by Mr-Persona** [danielgindi/Charts#4611]
I updated Charts today. An error occurred while compiling the project, error tip is no such module 'Algorithms'. I installed Charts through pods. 
I next install swift-algorithms by Swift Page Manager, but still can't solve the problem.

Charts version: 4.0.0

**Comment by leo150** [comment]
Same issue. Linking Charts with Algorithms doesn't help.

**Comment by Mr-Persona** [comment]
> Same issue. Linking Charts with Algorithms doesn't help.

4.0.0 does not support the pods, only user Swift Package. Because the latest version depend on Algorithms, Algorithms is Apple's open source library, unfortunately, Algorithms can only be installed through Swift Package.

**Comment by philipbel** [comment]
Thanks for the info, @Mr-Persona!
Should the pod then be removed altogether?

**Comment by SchwartzLizer** [comment]
![CleanShot 2021-05-05 at 11 30 45](https://user-images.githubusercontent.com/54163797/117097282-64ee4000-ad95-11eb-84b7-427706f1f5b5.png)
Same problem I use SPM but still got error

**Comment by rodgutierrez** [comment]
has anyone found a solution to this yet? i'm using Carthage and running into the same issue.

**Comment by leo150** [comment]
@rodgutierrez yes, import it as Swift Package instead of a pod.

**Comment by dhruvilbol** [comment]
@leo150 Hey, I have installed via SPM still it's showing same error: `No such module 'Algorithms`

**Comment by pateldhruvil96** [comment]
@leo150 Hey, I have installed via SPM still it's showing same error: `No such module 'Algorithms`

**Comment by nick-havz** [comment]
answered in #4646

**Comment by zhen-easytag** [comment]
I forked the repo and cocoapod to my project, but always having "no such module 'algorithms' ", even I added Algorithms package. But no problem with original repo. Anyone has solution? Thanks~

**Comment by dbquarrel** [comment]
I think in your app's project you need to go to File > Swift Packages  and try some of the menu items there. When you're done you should see the swift packages showing up on the bottom of your project file listing.

<img width="211" alt="Screen Shot 2021-06-26 at 15 29 37" src="https://user-images.githubusercontent.com/5317653/123513050-91d31b00-d693-11eb-9429-ac81b0d9b723.png">

After this you should be able to build. I am having a problem after this though, I can't build using xcodebuild anymore. 

In terms of this project maintenance you guys should really make some notes on the front page of the project like:

1. we're not supporting CocoaPods anymore
2. migration info to get off of CocoaPods 

This kind of thing is a bloody nightmare for those who do not use swift.

**Comment by dbquarrel** [comment]
Xcode itself can build a release version of my app, but using xcodebuild at the commandline, there has to be some extra magic, I get this error, even after I can see xcodebuild build the swiftmodule, it can't find it.

    xcodebuild -destination generic/platform=iOS -scheme 'Release Builder' -sdk iphoneos -archivePath /tmp archive

Generates this eventually

    /Users/samurai/Projects/misc/Charts/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift:12:8: error: no such module 'Algorithms'
    import Algorithms
           ^

    ** ARCHIVE FAILED **

**Comment by Turas** [comment]
1. remove Charts from Swift Packages
2. add Swift Algorithms "https://github.com/apple/swift-algorithms"
3. add Charts 

for me works that

**Comment by raffaelps** [comment]
One solution for this?

**Comment by liuxuan30** [comment]
Yeah as the last day of 2021, there is still no solution. I came across https://github.com/CocoaPods/CocoaPods/issues/10049 not sure if this will be a workaround. But I have no time to look deeper.. anyone ? thanks

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by howlho** [comment]
> 1. remove Charts from Swift Packages
> 2. add Swift Algorithms "https://github.com/apple/swift-algorithms"
> 3. add Charts
> 
> for me works that

works for me

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by mankarth004** [comment]
> 

Works for me as well, thanks

**Comment by EmilioDelCastillo** [comment]
I'm working on migrating a project from Cocoapods to SPM, unfortunately Charts remains the only package that prevents the completion of this task. I've tried all the differents solutions given on this thread to no avail. I even tried previous versions of Charts but it only caused different problems. Cleaning build folder, cleaning Derived Data, even restarting my machine, nothing seems to fix it.

Is there a solution to this issue ?

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by mavrakis** [comment]
I confirm I have the same issue using SPM. I installed first Charts without swift-algorithms and swift-numerics, got the issue. After looking at this thread, I installed swift-algorithms and swift-numerics, deleted Charts, installed Charts again. I got the same compile time error No such module 'Algorithms'
Thanks for your help

**Comment by novinfard** [comment]
> I confirm I have the same issue using SPM. I installed first Charts without swift-algorithms and swift-numerics, got the issue. After looking at this thread, I installed swift-algorithms and swift-numerics, deleted Charts, installed Charts again. I got the same compile time error No such module 'Algorithms'
> Thanks for your help

Use explicit version 4.1.0 for Charts
<img width="698" alt="Screenshot 2023-02-05 at 11 10 21" src="https://user-images.githubusercontent.com/611607/216815454-cfe9efae-ce0e-4b79-b06d-97b989e12e87.png">

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by carlos0193** [comment]
> > I confirm I have the same issue using SPM. I installed first Charts without swift-algorithms and swift-numerics, got the issue. After looking at this thread, I installed swift-algorithms and swift-numerics, deleted Charts, installed Charts again. I got the same compile time error No such module 'Algorithms'
> > Thanks for your help
> 
> Use explicit version 4.1.0 for Charts <img alt="Screenshot 2023-02-05 at 11 10 21" width="698" src="https://user-images.githubusercontent.com/611607/216815454-cfe9efae-ce0e-4b79-b06d-97b989e12e87.png">

Don't work for me

**Comment by carlos0193** [comment]
> > I confirm I have the same issue using SPM. I installed first Charts without swift-algorithms and swift-numerics, got the issue. After looking at this thread, I installed swift-algorithms and swift-numerics, deleted Charts, installed Charts again. I got the same compile time error No such module 'Algorithms'
> > Thanks for your help
> 
> Use explicit version 4.1.0 for Charts <img alt="Screenshot 2023-02-05 at 11 10 21" width="698" src="https://user-images.githubusercontent.com/611607/216815454-cfe9efae-ce0e-4b79-b06d-97b989e12e87.png">

it doesn't work for me

**Comment by Mr-Persona** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by pmairoldi** [comment]
> I chose only Charts and no ChartsDynamic, now I get this error,
> 
> Cannot find type 'IAxisValueFormatter' in scope. I am using Charts 4.1.0. It doesn't work.

Same issue as https://github.com/danielgindi/Charts/issues/4986. There was a name change in Charts 4 for interfaces.
