### ISSUE TITLE
Pie chart gradient colors for the slices

### ISSUE THREAD

**Issue by vishnupxminds** [danielgindi/Charts#4616]
Hi,
 Is there a way to create gradient colors for the pie slices in piechart.

**Comment by powercode-team** [comment]
@vishnupxminds Have you found a solution?

**Comment by kirti301290** [comment]
same problem to set gradient color 
any one found solution  ?
Thanks

**Comment by kirti301290** [comment]
Hello  @liuxuan30 @AlBirdie  @PeterKaminski09 
 can you help me how to show gradient color in pie chat
 Thanks

**Comment by r0otx** [comment]
I also need this feature. How can I satisfy with a gradient color?

**Comment by liuxuan30** [comment]
And in the power of GPT 3.5, I believe this repo has been trained and you could try chatGPT to do that for you 😃

**Comment by liuxuan30** [comment]
![image](https://user-images.githubusercontent.com/4375169/227194082-db923011-55b9-4aa6-87df-8149826147fd.png)
should give you a start point to do the rest, LOL

**Comment by r0otx** [comment]
> ![image](https://user-images.githubusercontent.com/4375169/227194082-db923011-55b9-4aa6-87df-8149826147fd.png)
> 
> should give you a start point to do the rest, LOL

PieChartDataSet don't have sliceGradient method, I'm too asked ChatGpt about them, but he wasn't help me with this problem.
