### ISSUE TITLE
Swift linking error with XCode 12.5 when used with a react native wrapper

### ISSUE THREAD

**Issue by smadan** [danielgindi/Charts#4636]
## What did you do?

Used react-native-charts-wrapper in my React Native app for iOS. Tried to build and run on XCode 12.5. Linker failed with this error:

Undefined symbols for architecture x86_64:
“Swift._ArrayBuffer._copyContents(initializing: Swift.UnsafeMutableBufferPointer) -> (Swift.IndexingIterator<Swift._ArrayBuffer>, Swift.Int)“, referenced from:
generic specialization <serialized, Swift._ArrayBuffer<Swift.Int8>> of Swift._copyCollectionToContiguousArray(A) -> Swift.ContiguousArray<A.Element> in libCharts.a(ChartUtils.o)

react-native-charts-wrapper is a React Native wrapper library built on top of Charts for iOS. The only extra step that library requires is the creation of a bridging header in XCode and an extra line in the Podfile: https://github.com/wuxudong/react-native-charts-wrapper/blob/master/installation_guide/README.md#ios. Unsure if those instructions are the source of the problem, or if it's coming from Charts.

## What did you expect to happen?

I expected the app to link correctly.

## What happened instead?

Linker error, see above.

## Charts Environment

React-Native 0.63.3 (happens with other versions of RN too)
Xcode 12.5
react-native-charts-wrapper (master)
Underlying pod Charts 3.3.0 (or 3.6.0)
MacOS: 11.2.3

Reported on the wrapper library's issues page here: https://github.com/wuxudong/react-native-charts-wrapper/issues/801

**Comment by Zestpond** [comment]
Same issue

**Comment by mateogianolio** [comment]
Same error, different library: https://github.com/raspu/Highlightr/issues/83

**Comment by webyonet** [comment]
For now I think it is necessary to downgrade to xcode 12.4 to fix this problem. Because the project was not compiled in 12.5 and I never got past this error 😔

**Comment by mateogianolio** [comment]
After *a lot* of digging I found a solution: https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518

**Comment by smadan** [comment]
> After _a lot_ of digging I found a solution: [Iterable/react-native-sdk#86 (comment)](https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518)

This did not work for me.

**Comment by mateogianolio** [comment]
Sorry to hear that! It solved the problem for me, both on `x86_64` (simulator) and `arm64` (my iPhone 12)

**Comment by my-name-is-nheo** [comment]
For those who are running to this issue, what is your temporary solution?

**Comment by smadan** [comment]
I wrote up a detailed note on how to get past this here: https://github.com/facebook/react-native/issues/31179#issuecomment-829536845.

**Comment by treeleaf-prajwal** [comment]
> After _a lot_ of digging I found a solution: [Iterable/react-native-sdk#86 (comment)](https://github.com/Iterable/react-native-sdk/issues/86#issuecomment-744829518)
This worked for me
