### ISSUE TITLE
Markers not appearing as expected

### ISSUE THREAD

**Issue by orolhawion** [danielgindi/Charts#4645]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?
In my project I updated Charts with Swift Package Manager from 3.6.0 to 4.0.1 and found that markers on line charts and bar charts are not appearing reliably.

## What did you expect to happen?
When I tap an entry in a bar chart or line chart, the marker appears reliably in v3.6.0 but not in v4.0.1. However I could not find this issue with pie charts, this seems to be working as before.

## What happened instead?
Nothing, no errors in the log

## Charts Environment
**Charts version/Branch/Commit Number:**
4.0.1

**Xcode version:**
12.5 (12E262)

**Swift version:**
5

**Platform(s) running Charts:**
iOS 14.5+

**macOS version running Xcode:**
Big Sur 11.3.1

## Demo Project
Since I did not change any charts related code in my project, I expect this to be reproducible with any project that you guys have that use markers.

This might be related to https://github.com/danielgindi/Charts/issues/4641#issue-885984081

**Comment by Lee-Waire-Health** [comment]
var entries: [ChartDataEntry] = []
        
        
        var i = 0
        while i < 38 {
            entries.append(ChartDataEntry(x: Double(round(1621858800.0+(Double(i)*60.0))), y: Double(Float.random(in: 70...73))))
            i+=1
        }
        
        let set = ChartDataSet(entries: entries)
        
        let res = set.entriesForXValue(Double(1621860300))
        
        let test1 = entries.partitioningIndex { $0.x == Double(1621860300) }
        let test2 = entries.partition { $0.x >= Double(1621860300) }

**Comment by astarsoftware** [comment]
I also ran into this bug when updating to 4.0.1.

**Comment by samdogg7** [comment]
I ran into this same bug as well on 4.0.0

**Comment by drewster99** [comment]
I have this issue also on 4.0.1.  None of the markers appear correctly when tapped.  Either they don't appear at all or they appear int he wrong place entirely (or perhaps it's a different marker that appears).  Updated from 3.6.0 to 4.0.1.

**Comment by samdogg7** [comment]
@drewster99 I ended up downgrading to 3.6.0 on SPM as a workaround. Still no word on a fix.
