### ISSUE TITLE
No such module 'Algorithms' with SPM

### ISSUE THREAD

**Issue by eduls7** [danielgindi/Charts#4646]
## What did you do?

ℹ Add Charts with SPM.

## What did you expect to happen?

ℹWork.  

## What happened instead?

ℹ No such module 'Algorithms' 

## Charts Environment

**Charts version/Branch/Commit Number:**
4.0.1
**Xcode version:**
12.5
**Swift version:**
5
**Platform(s) running Charts:**
iOS
**macOS version running Xcode:**
11.3

**Comment by nick-havz** [comment]
When you add the repo to SPM and it lists the packages available, just choose the Charts library, not the ChartsDynamic option. 
<img width="737" alt="Screen Shot 2021-05-28 at 11 31 16 AM" src="https://user-images.githubusercontent.com/7213127/120008100-9e872500-bfa8-11eb-830b-c2305ad0612e.png">

**Comment by eduls7** [comment]
Mark only the Charts library works without error import. Thanks @nick-havz.

**Comment by bias** [comment]
How is this a fix? Now I can't use IValueFormatter (presumably that's in charts dynamic?).

**Comment by SavvasPyth** [comment]
> How is this a fix? Now I can't use IValueFormatter (presumably that's in charts dynamic?).
i cannot even begin to comprehend that someone offered that solution... i'm using dynamic charts as well... no solution yet.

**Comment by sirisb** [comment]
I chose only Charts and no ChartsDynamic, now I get this error,

Cannot find type 'IAxisValueFormatter' in scope

**Comment by anubhavmishram** [comment]
in 4.1 it's just AxisValueFormatter
