### ISSUE TITLE
The use of special character in folder name don't allow unzip correctly

### ISSUE THREAD

**Issue by rquesada** [danielgindi/Charts#4660]
Found an issue when try to unzip a .zip file of the library, because an folder used in Examples use a special character

Zip: https://github.com/danielgindi/Charts/archive/refs/tags/v4.0.1.zip

<img width="273" alt="Screen Shot 2021-06-11 at 10 52 03 AM" src="https://user-images.githubusercontent.com/1158703/121758397-6fab9b80-cade-11eb-913f-4dfc200212b4.png">

* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

unzip -d DestinationFile Charts-4.0.1.zip

## What did you expect to happen?   

The Library unzip correctly

## What happened instead?

I got the following error:
checkdir error:  cannot create OUT/Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__
                 Illegal byte sequence
                 unable to process Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__/.
checkdir error:  cannot create OUT/Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__
                 Illegal byte sequence
                 unable to process Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__/BarChartTests/.
checkdir error:  cannot create OUT/Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__
                 Illegal byte sequence
                 unable to process Charts-4.0.1/Tests/ChartsTests/__Snapshots__??+Silicon__/BarChartTests/testDefaultBarDataSetLabels-iOS_390-0_844-0.1.png.
....

## Charts Environment

**Charts version: 4.0.1** 
**Xcode version: 12.4**
**Swift version: 5.3**
**Platform(s) running Charts: iOS Platfrom**
**macOS version running Xcode: 11.4**

**Comment by pmairoldi** [comment]
Closed by #4881
