### ISSUE TITLE
entriesForXValue() not finding point with matching xValue when it should

### ISSUE THREAD

**Issue by darbysauter** [danielgindi/Charts#4668]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Tapped a point on my LineChart 

## What did you expect to happen?

Highlight a point 

## What happened instead?

Failed to highlight point

## Charts Environment

**Charts version/Branch/Commit Number:master**
**Xcode version:Latest**
**Swift version:Latest**
**Platform(s) running Charts:iPhoneX**
**macOS version running Xcode:BigSur**

## Demo Project

Unable to produce

## Reason for this to happen

In entriesForXValue(_ xValue: Double) -> [ChartDataEntry] of ChartDataSet
it uses partitioningIndex() to find the first index that matches the xValue.

The xValue is from:
closest = set.entryForXValue(xValue, closestToY: .nan, rounding: rounding)

Which I have verified is working properly:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/40215561/123013096-c2a80d00-d380-11eb-9c82-611ea8241b33.png">

As you can see xValue matches the x value of the entry at index 3. using firstIndex() also produces index 3, but partitioningIndex() returns the the index after the last of entries.

So to debug this, after the case where it could not find the index I manually check every entry and Int round them, If I find a match I then test firstIndex() using the same predicate as partitioningIndex() (so no Int rounding), and this works.

partitioningIndex() does work sometimes but I couldn't figure out a common cause.

Assuming my assumption that partitioningIndex() and firstIndex() should do the same thing then partitioningIndex() is broken.

Any ideas how to properly fix this? for the meantime I may just use firstIndex() on my fork.

**Comment by ggorlim** [comment]
I have same issue, so as workaround i rewrite method entriesForXValue, using code from older lib version:

`override func entriesForXValue(_ xValue: Double) -> [ChartDataEntry]
    {
        var entries = [ChartDataEntry]()
        var low = startIndex
        var high = endIndex - 1        
        while low <= high...`

This work, but we have some other issues, i m not think they are related to this, like rendering only first from multiple graphs..

I think this issue also have same problem : #4645 Markers not appearing as expected

**Comment by lancelot9527** [comment]
> I have same issue, so as workaround i rewrite method entriesForXValue, using code from older lib version:
> 
> override func entriesForXValue(_ xValue: Double) -> [ChartDataEntry]
> {
> var entries = ChartDataEntry
> var low = startIndex
> var high = endIndex - 1
> while low <= high...
> 
> This work, but we have some other issues, i m not think they are related to this, like rendering only first from multiple graphs..
> 
> I think this issue also have same problem : #4645 Markers not appearing as expected

It work,thanks
I use 3.6.0 version fix this problem

**Comment by logancautrell** [comment]
I can confirm that 3.6.0 fixes the selection issue. 4.x.x version are busted.

**Comment by dudenamedjune** [comment]
https://github.com/danielgindi/Charts/issues/4719#issuecomment-1107433833
