### ISSUE TITLE
Charts 4.0 not supported via Cocoapods

### ISSUE THREAD

**Issue by kammodze** [danielgindi/Charts#4688]
* [ x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I tried to add Charts 4.0 to my project using Cocoapods

## What did you expect to happen?

Successfully resolved 4.0 version by Cocoapods

## What happened instead?

Error. The latest version on Cocapods is 3.6. The pod specs repo needs to be updated.

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0.1
**Xcode version:** 12.5
**Swift version:** 5.4
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 11.4

**Comment by pikacode** [comment]
@liuxuan30 麻烦将 4.0 更新到 cocoapods

**Comment by LuMingGit** [comment]
-> Charts (3.6.0)
   Charts is a powerful & easy to use chart library for iOS, tvOS and OSX (and
   Android)
   pod 'Charts', '~> 3.6.0'
   - Homepage: https://github.com/danielgindi/Charts
   - Source:   https://github.com/danielgindi/Charts.git
   - Versions: 3.6.0, 3.5.0, 3.4.0, 3.3.0, 3.2.2, 3.2.1, 3.2.0, 3.1.1, 3.1.0,
   3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3,
   2.2.2, 2.2.1, 2.1.6, 2.1.5, 2.1.4, 2.1.4a, 2.1.3, 2.1.2, 2.1.0, 2.0.9 [master
   repo]
   - Subspecs:
     - Charts/Core (3.6.0)

**Comment by yangdehui** [comment]
cocoapods只支持到3.6.0吗？
我升级了pod版本至1.11.2
本地库也做了更新 -> repo udate

**Comment by yangdehui** [comment]
-> Charts (3.6.0)
   Charts is a powerful & easy to use chart library for iOS, tvOS and OSX (and
   Android)
   pod 'Charts', '~> 3.6.0'
   - Homepage: https://github.com/danielgindi/Charts
   - Source:   https://github.com/danielgindi/Charts.git
   - Versions: 3.6.0, 3.5.0, 3.4.0, 3.3.0, 3.2.2, 3.2.1, 3.2.0, 3.1.1, 3.1.0,
   3.0.5, 3.0.4, 3.0.3, 3.0.2, 3.0.1, 3.0.0, 2.3.1, 2.3.0, 2.2.5, 2.2.4, 2.2.3,
   2.2.2, 2.2.1, 2.1.6, 2.1.5, 2.1.4, 2.1.4a, 2.1.3, 2.1.2, 2.1.0, 2.0.9
   [cocoapods repo]
   - Subspecs:
     - Charts/Core (3.6.0)

**Comment by liuxuan30** [comment]
the issue is, the pod is not pushed since 4.0.0, as pod not supports SPM, and one of the new package we use is Swift Algorithm, which is a SPM dependency, and pod cannot support it.. so we are not able to push
