### ISSUE TITLE
How to get chartValue using mouse hover instead of mouse click in MacOS

### ISSUE THREAD

**Issue by sergeydi** [danielgindi/Charts#4715]
I have `CombinedChartView` with `candleData`. When I click by mouse a candle, `chartValueSelected` executed and I can receive information about selected candle. I need to do the same using `UIHoverGestureRecognizer` instead click mouse. How get information about a `chartValue` that mouse is hover?

**Comment by FelixHerrmann** [comment]
What I did (with Charts 3.6.0 on iOS):

1. Add a `UIHoverGestureRecognizer` to your chart view
```swift
let hoverGestureRecognizer = UIHoverGestureRecognizer(target: self, action: #selector(handleChartHover(_:)))
chartView.addGestureRecognizer(hoverGestureRecognizer)
```

2. Highlight manually
```swift
@objc private func handleChartHover(_ recognizer: UIHoverGestureRecognizer) {
    let location = recognizer.location(in: chartView)
    if location == .zero {
        chartView.highlightValue(nil)
    } else {
        let highlight = chartView.getHighlightByTouchPoint(location)
        chartView.highlightValue(highlight, callDelegate: true)
    }
}
```

3. Handle the selected entry in your `ChartViewDelegate`'s `chartValueSelected(_:entry:highlight:)` implementation.

**Comment by sergeydi** [comment]
@FelixHerrmann Thanks, Issue may be closed.
