### ISSUE TITLE
Xcode 13 RC - Module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5 compiler

### ISSUE THREAD

**Issue by osmar106** [danielgindi/Charts#4718]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ Build my app on Xcode 13 RC and get an error.

## What did you expect to happen?

ℹ Be able to build my app

## What happened instead?

ℹI am getting this error: _"Module compiled with Swift 5.4.2 cannot be imported by the Swift 5.5 compiler: /Users/orodrgut/Library/Developer/Xcode/DerivedData/AM8-MonsantoSeedsman-gdqehxniwlzvxvecvoiitysszrst/Build/Products/Debug-iphonesimulator/Charts.framework/Modules/Charts.swiftmodule/x86_64-apple-ios-simulator.swiftmodule"_ 

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0.1
**Xcode version:** 13 RC
**Swift version:** The project is build in Objective-C
**Platform(s) running Charts:** iPadOS and using Carthage
**macOS version running Xcode:** macOS Big Sur 11.5.1

## Demo Project

ℹ I can't share my code but I am getting the error here: "import Charts"

**Comment by osmar106** [comment]
Check this repo, **Charts** branch to test this error https://github.com/yeyocp/CarthageTestForXcode13/commits/Charts

**Comment by moyerr** [comment]
You need to rebuild your Carthage dependencies (should be `carthage update` but you may need to add certain options depending on your specific use case)

Make sure you're pointing Xcode to the 13.0 command line tools (Xcode Preferences > Locations > Command Line Tools) before you do this.

**Comment by Kolch** [comment]
@moyerr Have any ideas for cocoapods case ? Update doesn't help in this case

**Comment by dorianck** [comment]
Does anyone find some solution to this issue @osmar106 ?

**Comment by liuxuan30** [comment]
I will find a time recently(this weekend or next) to try test Xcode and maybe update

**Comment by liuxuan30** [comment]
or, any of you could make a PR so I could review and merge soon.

**Comment by pmairoldi** [comment]
outdated closing
