### ISSUE TITLE
cocopods 3.6.0  but master 4.0.0

### ISSUE THREAD

**Issue by icc-tips** [danielgindi/Charts#4740]
https://github.com/CocoaPods/Specs/tree/32dd6638f41eca5716a1bd72506c6adbec10ebea/Specs/5/1/e/Charts

**Comment by willieWen** [comment]
I think there is a bug with ChartValueSelected delegate on v.4.0.0 according to https://github.com/danielgindi/Charts/issues/4579.
so 3.6.0 is the most stable one.

**Comment by icc-tips** [comment]
ok ,thank you

**Comment by Breiby** [comment]
[4.0.0 doesn't support CocoaPods](https://github.com/danielgindi/Charts/issues/4572)

**Comment by pmairoldi** [comment]
Version 4.0.2 now available on cocoapods
