### ISSUE TITLE
Using 'class' keyword to define a class-constrained protocol is deprecated - Xcode 13.1

### ISSUE THREAD

**Issue by saldous** [danielgindi/Charts#4745]
## What did you do?
Build project in Ccode 13.1

## What happened instead?
Warnings thrown for files: IHighlighter.swift, IValueFormatter.swift, IAxisValueFormatter.swift
`Using 'class' keyword to define a class-constrained protocol is deprecated `
![image](https://user-images.githubusercontent.com/3334306/139668734-30540696-7c5c-41cf-b8bb-764b182b50e8.png)

## Charts Environment
3.6.0

**Charts version/Branch/Commit Number:** 3.6.0
**Xcode version:** 13.1
**Swift version:** 5
**macOS version running Xcode:** 12.0.1

**Comment by saldous** [comment]
Still getting this warning in Xcode for IMarker.swift and IValueFormatter.swift files.

**Comment by pmairoldi** [comment]
closing outdated
