### ISSUE TITLE
spaceMin and spaceMax (xAxis) not working when setting new data 

### ISSUE THREAD

**Issue by francyrho11** [danielgindi/Charts#4753]
## What did you do?

I'm using `xAxis.spaceMin` and `xAxis.spaceMax` to add some extra spacing. 
axisMaximum are calculated automatically. 

## What did you expect to happen?

spaceMin and spaceMax will add extra spacing even when setting new data

## What happened instead?

Spacing is correct first time i set some data inside the graph.
Once I set new data inside the graph (e.g. `lineChartView.data = chartData`) the additional space disappear.

**Comment by Rajneesh071** [comment]
Is it solved ? Because It's not working for me in latest code.

Only spaceMin working for me.
e.g. chartView.xAxis.spaceMin = 10

If I add Max, line in not drawing.
