### ISSUE TITLE
Fatal access conflict detected

### ISSUE THREAD

**Issue by pathanrasool** [danielgindi/Charts#4756]
Hi Charts team,

I am using Charts in native code, and it is wokring. Where as i am using this native code as custom library for my React Native application. But the app is crashing with the below logs. If i am commenting the chars code then it is working. 
I am using xCode 12.4.

Simultaneous accesses to 0x126437910, but modification requires exclusive access.
Previous access (a modification) started at Charts`BarChartDataSet.barBorderColor.modify + 72 (0x1076f6f70).
Current access (a read) started at:
0    libswiftCore.dylib                 0x00000001a41762b0 swift_beginAccess + 548
1    Charts                             0x00000001076f6dc4 BarChartDataSet.barBorderColor.getter + 76
2    Charts                             0x00000001076f6d80 @objc BarChartDataSet.barBorderColor.getter + 32
3    Charts                             0x00000001076fbc3c BarChartRenderer.drawDataSet(context:dataSet:index:) + 708
4    Charts                             0x00000001076fad98 BarChartRenderer.drawData(context:) + 1852
5    Charts                             0x00000001077121e8 BarLineChartViewBase.draw(_:) + 4252
6    Charts                             0x0000000107713bd4 @objc BarLineChartViewBase.draw(_:) + 96
7    UIKitCore                          0x00000001a31f9340 <redacted> + 584
8    QuartzCore                         0x00000001a36fef30 <redacted> + 308
9    QuartzCore                         0x00000001a35d04f8 <redacted> + 176
10   QuartzCore                         0x00000001a3708570 <redacted> + 52
11   QuartzCore                         0x00000001a36fe154 <redacted> + 1680
12   QuartzCore                         0x00000001a371165c <redacted> + 416
13   QuartzCore                         0x00000001a365cbdc <redacted> + 416
14   QuartzCore                         0x00000001a3686c68 <redacted> + 728
15   UIKitCore                          0x00000001a2d20438 <redacted> + 140
16   CoreFoundation                     0x00000001a040485c <redacted> + 32
17   CoreFoundation                     0x00000001a03fecf4 <redacted> + 604
18   CoreFoundation                     0x00000001a03ff0d8 <redacted> + 960
19   CoreFoundation                     0x00000001a03fe964 CFRunLoopRunSpecific + 572
20   GraphicsServices                   0x00000001b71674f8 GSEventRunModal + 160
21   UIKitCore                          0x00000001a2cefed8 <redacted> + 1052
22   UIKitCore                          0x00000001a2cf57d0 UIApplicationMain + 164
23   Apollo 247                         0x0000000104e48c4c main + 128
24   libdyld.dylib                      0x00000001a00dd564 <redacted> + 4
Fatal access conflict detected.
2021-11-24 12:43:12.110443+0530 Apollo 247[2719:92295] Fatal access conflict detected.

**Comment by pmairoldi** [comment]
Sorry we do not support React Native. You will have to find help elsewhere. Wish we could be of more help.
