### ISSUE TITLE
Thread 1: Fatal error: Range requires lowerBound <= upperBound

### ISSUE THREAD

**Issue by hkbk** [danielgindi/Charts#4761]
How fix this issue? 
I'm run version 4.0.0
thanks 
![Screen Shot 2021-11-28 at 17 11 40](https://user-images.githubusercontent.com/3271316/143763899-54eb0378-252a-420b-9c9f-420315f4661a.png)

**Comment by McWare** [comment]
same problem here!

**Comment by d-palanisamy** [comment]
I didn't even update the pod version, getting same issue on my current v3.6.0. I didn't get this crash until yesterday.

**Comment by hkbk** [comment]
> 

it's on swift package version 4.0.0,
I have see been it's fixed at https://github.com/hkbk/Charts/tree/bugfix/xbounds-iterator , But not merger to master.

**Comment by alicelovalvo** [comment]
I have the same issue. Anyone that solve it? And how?
