### ISSUE TITLE
Charts.framework

### ISSUE THREAD

**Issue by Rigadin** [danielgindi/Charts#4765]
Hello,

In the "Usage" paragraph it says:
"Go to your target's settings, hit the "+" under the "Embedded Binaries" section, and select the Charts.framework "

However, I can't find the "Charts.framework" file anywhere. 

Where is it?

**Comment by pmairoldi** [comment]
You can check out of the ChartDemo-iOS integrates the library in it's project. It uses this method the test out the library.
