### ISSUE TITLE
Swift Compiler Warning 

### ISSUE THREAD

**Issue by abdorizak** [danielgindi/Charts#4788]
### Notice in iOS 15
>` Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead`

- [ ] change all class protocol into AnyObject

**Xcode version 13.2.1
**Swift version:5.5.2
**Platform(s) running Charts: 3.6.0
**macOS version running Xcode: M1 Macbook Air

**Comment by treydin6** [comment]
@abdorizak curious, Does the charts library support the apple silicon chips? I run an intel chip and I have someone telling me charts is not working on their m1 chip. I cant find anything saying the charts library doesn't support the apple chips.

**Comment by pmairoldi** [comment]
obsolete closing
