### ISSUE TITLE
How to setup charts and data to be able to be ready by voice over?

### ISSUE THREAD

**Issue by bencmorrison** [danielgindi/Charts#4790]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

Is there any documentation that guides us on how to successfully configure our charts and data to be read correctly by voice over?

Currently I have a line chart and it displays everything correctly. However when I select the chart to be read out it just says "Line chart, one data set, data set heading" is all I get. I have tried setting Accessibility Labels, Values, and Hints on the charts and data. Nothing other than the same thing over and over again.

It would be great if I could get some guidance on the correct way to setup Charts and Data to be successfully read by Voice Over.

Thank you!

**Comment by pmairoldi** [comment]
By default it should just work out of the box with the values you configure in your data. If some customization is needed you can override the values in the data. The properties can found here https://github.com/danielgindi/Charts/blob/e91ba716190836b013ef8a9ca53e220ad5051e21/Source/Charts/Data/Implementations/Standard/ChartData.swift#L26-L40

**Comment by bencmorrison** [comment]
Interesting, I am getting no read out of the data at all. The chart renders as expected.

I am unsure if there is something I am doing wrong on my end or am not using the voice over things correctly. I have attached the demo project I am using to test out charts and the capabilities. Perhaps someone would be able to look it over quickly and maybe see something? It is very weird that it isn't working. I don't have a lot of experience with voice over and how to correctly get the data there for it to work correctly.


I couldn't seem to get this in my own repo so attached here:
[Charts Demo.zip](https://github.com/danielgindi/Charts/files/8236358/Charts.Demo.zip)

**Comment by pmairoldi** [comment]
I tested it when the support was first merged but haven't since. So maybe something changed. When I have time I'll check the demo you provided.

**Comment by bencmorrison** [comment]
Ta mate, much appreciated!

**Comment by pmairoldi** [comment]
Ok it seems like you need to have points drawn on your chart in order to get voice over for points. 

So instead of doing 
```Swift
set.drawCirclesEnabled = false
``` 
do 
```Swift
set.drawCirclesEnabled = true
set.circleRadius = 0
```
