### ISSUE TITLE
Compiling for iOS 10.0, but module 'Charts' has a minimum deployment target of iOS 12.0

### ISSUE THREAD

**Issue by YurchukV** [danielgindi/Charts#4796]
Support will now start with ios 12?

charts version : "4.0.2"

**Comment by OliviaHourcade-o** [comment]
I have the same question. I can't upgrade to 4.02 because my min requirement is iOS 11.

**Comment by harmancode** [comment]
I have the same question. I can't build for iOS 11 with Charts 4.0.2.

**Comment by fabiorodella** [comment]
I intended to upgrade from 3.6.0 to 4.0.3 as part of a general dependency maintenance pass, but our app has a minimum deployment target of iOS 11 and I ran into the same issue. Can anyone confirm if this was an intended change or just a bug? If the latter, are there any workarounds?

**Comment by pmairoldi** [comment]
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0
