### ISSUE TITLE
chartValueSelected not calling for all clicking on hole in graph in v.4.0.2 (v3.6.0 works perfectly)

### ISSUE THREAD

**Issue by tarasChernysh** [danielgindi/Charts#4804]
## What did you do?

ℹ I try to create line chart. 

## What did you expect to happen?

ℹ When click on hole view I want to see view with value of this graph.  

## What happened instead?

ℹ I see this view with not from all hole in graph. It works perfectly with `Charts` v3.6.0 . 
ℹ`chartValueSelected` does not call for all hole view. 
ℹ`chartValueNothingSelected` calls instead of `chartValueSelected `

## Charts Environment

**Charts version/Branch/Commit Number:** master, v4.0.2
**Xcode version:** 13.2
**Swift version:** 5
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** Monterey (12.3)

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

https://user-images.githubusercontent.com/32072147/160397283-9eacc251-597f-4949-8e06-eb135f099ab1.mp4

**Comment by thierryH91200** [comment]
#4795

**Comment by abdorizak** [comment]
can we see the project if it's available on github

**Comment by tarasChernysh** [comment]
@abdorizak that project is private. So I made a little demo with some logic from that project. 
In demo I use v4.0.2. You can check the same result as I showed in video before. 
Here is repo https://github.com/tarasChernysh/GraphTest

**Comment by tarasChernysh** [comment]
I found PR that solving my issue 
https://github.com/danielgindi/Charts/issues/4719

**Comment by liuxuan30** [comment]
seems the new release contain a possible fix from #4719?
