### ISSUE TITLE
Upgrading from 3.5.0 to 4.0.2 breaks highlighting

### ISSUE THREAD

**Issue by Ludotrico** [danielgindi/Charts#4805]
I am using a super simple Bar Chart. 

Highlighting works fine in 3.5.0 but is definitely broken in 4.0.2. By broken I mean it doesn't highlight on tap and barely highlights on drag.

**Comment by kallik** [comment]
Same for me, even broken in sample app, maybe related to these:
https://github.com/danielgindi/Charts/issues/4795
https://github.com/danielgindi/Charts/issues/4804
Downgraded to 3.6.0 for the time being

**Comment by kcome** [comment]
@kallik @Ludotrico This has been reported as #4719 and there is a fix [PR](https://github.com/danielgindi/Charts/pull/4721) pending merge. If you could test [this branch](https://github.com/kcome/Charts/tree/4719-highlighter-fix) that would be wonderful.

**Comment by Ludotrico** [comment]
@kcome It works ok. The issue is that your branch have lost the ability to unhighlight!

**Comment by kcome** [comment]
@Ludotrico Thanks for your feedback. I've found the reason of unable to unhighlight. The fix is pushed to [this branch](https://github.com/kcome/Charts/tree/4719-highlighter-fix) already. Could you have a try?

**Comment by Ludotrico** [comment]
@kcome works!

**Comment by Ludotrico** [comment]
@danielgindi @pmairoldi @liuxuan30 @jjatie please review the branch fix from @kcome

**Comment by wangzhi8910** [comment]
When will this “4719-highlighter-fix”  branch be released

**Comment by RobertBernardini** [comment]
@danielgindi, @pmairoldi, @liuxuan30: 
It would be very welcomed if this [PR 4719 - Highlighter Fix](https://github.com/danielgindi/Charts/pull/4721) fix could be given priority and merged into the release as soon as possible. The line chart interaction/highlighting functionality is integral to our app, like many others, and has been broken since updating to 4.0.2 and downgrading back to 3.0.6 is really no longer an option for many.

**Comment by dimohamdy** [comment]
@kcome This solution doesn't work well with stackbar, Please check the attached gif

![Simulator Screen Recording - iPhone 13 - 2022-04-11 at 12 45 55](https://user-images.githubusercontent.com/1476754/162724680-0a1ab9b0-0607-41a0-a1c8-af641d4ca6b8.gif)
r

**Comment by kcome** [comment]
@dimohamdy Thanks for your feedback. I found the issue and fixed it in a new commit in [that PR](https://github.com/danielgindi/Charts/pull/4721). Could you please try the [fix branch](https://github.com/kcome/Charts/tree/4719-highlighter-fix) and let me know the result?

**Comment by dudenamedjune** [comment]
Think I have a proper fix open for this https://github.com/danielgindi/Charts/pull/4817
https://github.com/danielgindi/Charts/issues/4719#issuecomment-1107433833

**Comment by dudenamedjune** [comment]
@dimohamdy I would be a bit weary to change the stacked bar, if by doesn't work well with stacked bar do you mean highlighting the entire bar? If so there are a few lines of code that actually implement this behavior specifically https://github.com/danielgindi/Charts/blob/e91ba716190836b013ef8a9ca53e220ad5051e21/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift#L241-L264 but at the least if we merge something then we can having a working selection. Think someone was mentioning in issues to create a way to highlight the whole bar, makes me think it should be a part of the api or just an override

**Comment by pmairoldi** [comment]
Closed by https://github.com/danielgindi/Charts/pull/4721
