### ISSUE TITLE
Is there support swift 5.0 plan?

### ISSUE THREAD

**Issue by jrjohn** [danielgindi/Charts#4813]
* [ *] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Compile the project

## What did you expect to happen?

Show deprecated warning.
![image](https://user-images.githubusercontent.com/6859844/163917263-cc255676-6998-4b2a-9f40-d7aa43c99326.png)

## What happened instead?

Warning message

## Charts Environment

**Charts version/Branch/Commit Number: 4.0.2
**Xcode version: 13.3.1
**Swift version: 5.0
**Platform(s) running Charts: iOS 15.4.1
**macOS version running Xcode: 12.1

**Comment by liuxuan30** [comment]
I think we have been updated to Swift 5 already. Not sure why missed this warning. Is it really Swift 5.0 warning, or like 5.3+?

**Comment by pmairoldi** [comment]
obsolete closing
