### ISSUE TITLE
How to highlight a whole stacked bar with 3 different colors?

### ISSUE THREAD

**Issue by emeng00** [danielgindi/Charts#4816]
How to highlight a whole stacked bar with 3 different colors? And the other bars are greyed out, like the image below?
![b1345c8467f5eb2c306c95aef19a23f](https://user-images.githubusercontent.com/66827569/164588121-4b40958f-a568-40ae-96c7-72ec61fc8b00.png)

**Comment by emeng00** [comment]
Done!

**Comment by naingminoo99** [comment]
may i know ow did u do it ?
