### ISSUE TITLE
pod install on terminal fails on mac

### ISSUE THREAD

**Issue by Ubaid-Javaid** [danielgindi/Charts#4820]
**Pod install fails on Xcode 13**

![Image 11-05-2022 at 4 20 PM](https://user-images.githubusercontent.com/41649416/167837885-c8a85605-19ed-4fad-8d04-f5c332617402.jpg)

**Comment by adriatikgashi** [comment]
This does not have to do with the Charts pod, it was something related to the CocoaPods itself and it was fixed some hours ago. 

Check more here:
https://status.cocoapods.org/
https://github.com/CocoaPods/CocoaPods/issues/11355
