### ISSUE TITLE
CombinedChartView don't show line chart

### ISSUE THREAD

**Issue by ssrybak1** [danielgindi/Charts#4837]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Open demo app ios swift. Select Combined Chart

## What did you expect to happen?

Open combined chart with all graphs

## What happened instead?

I don't see line chart. Line chart render only one dot. If i zoom it, all line graph render

## Charts Environment

**Charts version/Branch/Commit Number:**4.0.3
**Xcode version:**Version 13.4 (13F17a)
**Swift version:**5
**Platform(s) running Charts:**iOS 15.5
**macOS version running Xcode:**12.1 (21C52)

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.
<img width="310" alt="Снимок экрана 2022-06-10 в 16 39 52" src="https://user-images.githubusercontent.com/40515045/173037988-fec87ebd-4399-4772-b98b-25f50614b02e.png">
<img width="314" alt="Снимок экрана 2022-06-10 в 16 40 05" src="https://user-images.githubusercontent.com/40515045/173038004-77c59e9c-fc06-4d13-941b-1fd1d16b70f1.png">

**Comment by FelixHerrmann** [comment]
#4829 fixes that!

**Comment by ssrybak1** [comment]
Thanks 👍 it helped.
