### ISSUE TITLE
Support for Xcode 14

### ISSUE THREAD

**Issue by lukelabonte** [danielgindi/Charts#4860]
## What did you do?

Build the project with Xcode 14 Beta 3

## What did you expect to happen?

For the project to successfully build.

## What happened instead?

There are 2 types of build errors

1) Build error around `CandleStickChartRenderer`'s and `RadarChartRenderer`'s `drawData(context: CGContext)` where the `IndexingIterator` are not equivalent. Raw message:
> error build: Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<ChartData>' and 'IndexingIterator<RadarChartData>' be equivalent

2) Build error around `ChartDataSet` not conforming to `RangeReplaceableCollection` as `replaceSubrange(_:with:)` is missing. Raw messages:
> error build: Type 'ChartDataSet' does not conform to protocol 'RangeReplaceableCollection'

> error build: Unavailable instance method 'replaceSubrange(_:with:)' was used to satisfy a requirement of protocol 'RangeReplaceableCollection'

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0.3
**Xcode version:** Xcode 14 Beta 3 (14A5270f)
**Swift version:** 5.7
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** 12.4 (21F79)

**Comment by dingtianran** [comment]
Saw the same error this morning after upgraded to beta3.
Beta 2 is fine, I guess for now I'll stick to beta 2 until this got resolved

**Comment by gsbernstein** [comment]
I resorted to just unlocking the files and resolving locally. Lasts until the pod gets reinstalled. For each:
1. Commenting out the whole `for case let...` block
2. Added this function to the bottom of the extension.
```
    public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
        fatalError()
    }
```
I know these aren't solutions, just unblocks me for now.

**Comment by Brett-Best** [comment]
@gsbernstein https://github.com/danielgindi/Charts/blob/c3701a4e5ce111c29dd7af9e19e6a346ccf0ad52/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift#L427-L431
from

**Comment by Brett-Best** [comment]
Xcode 14 beta 3 fixed the issue with `EaseOutBack` closure not resolving types in time.

So the only issues are the `replaceSubrange` which I linked to a potential fix above and I haven’t found a workaround for:
> Build error around CandleStickChartRenderer's and RadarChartRenderer's drawData(context: CGContext) where the IndexingIterator are not equivalent.

**Comment by liuxuan30** [comment]
> Xcode 14 beta 3 fixed the issue with `EaseOutBack` closure not resolving types in time.
> 
> So the only issues are the `replaceSubrange` which I linked to a potential fix above and I haven’t found a workaround for:
> 
> > Build error around CandleStickChartRenderer's and RadarChartRenderer's drawData(context: CGContext) where the IndexingIterator are not equivalent.

#4823 is definitely something I would merge fast, but have to think about older swift versions, if nothing special, will get it merged. I have to squeeze my drive to make some pace for beta first...

**Comment by lchamp** [comment]
> Xcode 14 beta 3 fixed the issue with `EaseOutBack` closure not resolving types in time.

Not on my side (and I do have those two new errors too).

**Comment by juhanh** [comment]
`for case let set as CandleChartDataSetProtocol in (candleData as ChartData) where set.isVisible
  {
        drawDataSet(context: context, dataSet: set)
  }`

Makes `CandleStickChartRenderer` build.

**Comment by gesabo** [comment]
Just ran into this in Xcode 14 Beta 3 as well...and can't go back as I can't submit updates in Beta 2, beta season always fun 🤦‍♂️

**Comment by dobiho5** [comment]
Xcode 14 beta 4 as well.

**Comment by nucauthu** [comment]
Xcode beta 5 doesn't fix it

**Comment by kevinho96** [comment]
Will there any chance that the fix will be applied and solved before the Xcode 14 public release?

**Comment by michalnowak061** [comment]
> Will there any chance that the fix will be applied and solved before the Xcode 14 public release? 

If not it's good time to say "good bye" for this library.

**Comment by robnadin** [comment]
> Xcode beta 5 doesn't fix it

It won't ever be fixed by a new release of Xcode because it was a known bug in Swift for quite some time, and has only recently been fixed in Swift 5.7

You can check out the original bug here:
https://github.com/apple/swift/pull/38950

**Comment by logancautrell** [comment]
Any updates on if this is going to be addressed soon? Xcode 14 is a month out.

**Comment by werkaflute** [comment]
On XCode 14.6 is still problem

**Comment by werkaflute** [comment]
> On XCode 14.6 is still problem

Does it work for someone on XCode 14.6?

**Comment by waterskier2007** [comment]
It looks like said PRs have been merged. Any timeline on a new release?

**Comment by phoenisis** [comment]
@waterskier2007 Indeed and code just works fine. 

If you do not want to wait until public release you can simply specify branch "master" and not the version.

**Comment by pmairoldi** [comment]
I will release a new version when Xcode gm become available

**Comment by waterskier2007** [comment]
@pmairoldi any updates?

**Comment by pmairoldi** [comment]
I was off for the last couple days. I will look at it tonight.

**Comment by pmairoldi** [comment]
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0

**Comment by DanieleCiti** [comment]
> closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0

It is installing the 3.6.0 with pod 'Charts'.

**Comment by jonnokim17** [comment]
@DanieleCiti - try increasing the minimum deployment target to 14.0 in your podfile. that should resolve the issue.

**Comment by DanieleCiti** [comment]
Done it and I only have one error now: No such module 'Algorithms'

**Comment by DanieleCiti** [comment]
> @DanieleCiti - try increasing the minimum deployment target to 14.0 in your podfile. that should resolve the issue.

Done it and I only have one error now: No such module 'Algorithms'

**Comment by jonnokim17** [comment]
@DanieleCiti - i ran into that as well. i just deleted the charts pod and went with swift package instead, which worked.

**Comment by DanieleCiti** [comment]
> @DanieleCiti - i ran into that as well. i just deleted the charts pod and went with swift package instead, which worked.

I'm gonna do the same -> Adding a package with "Up to next major 4.1.0 < 4.0.0" from https://github.com/danielgindi/Charts.git. That's what you did too?

**Comment by jonnokim17** [comment]
@DanieleCiti - yep!

**Comment by DanieleCiti** [comment]
> @DanieleCiti - yep!

Thanks a lot for your time! It taking a bit of time on the "fetching https://github.com/danielgindi/Charts.git" screen. How long did it takes for you to finish?

**Comment by tfonfara** [comment]
@DanieleCiti `Up to next major 4.1.0 < 4.0.0` is definitely wrong, it needs to be `Up to next major 4.1.0 < 5.0.0` (which works fine for me btw.)

**Comment by DanieleCiti** [comment]
> @DanieleCiti `Up to next major 4.1.0 < 4.0.0` is definitely wrong, it needs to be `Up to next major 4.1.0 < 5.0.0` (which works fine for me btw.)

Actually the package manager won't let me choose the version after the < which is set to 4.0.0... I can only set the previous one like my_version < 4.0.0

**Comment by tfonfara** [comment]
`4.1.0 < 4.0.0` can never be true, so maybe you can try to re-adding it. It should look like this: 
<img width="463" src="https://user-images.githubusercontent.com/728683/189911536-63da051d-479e-451f-806d-5c17325de29f.png">

**Comment by MHamayun** [comment]
> @gsbernstein
> 
> https://github.com/danielgindi/Charts/blob/c3701a4e5ce111c29dd7af9e19e6a346ccf0ad52/Source/Charts/Data/Implementations/Standard/ChartDataSet.swift#L427-L431
> 
> 
> from #4823

OutStanding.....
