### ISSUE TITLE
Minimum version while targeting iOS 10 and Cocoapods install

### ISSUE THREAD

**Issue by NicolasBoutin** [danielgindi/Charts#4865]
## What did you do?

pod install command while targeting iOS 10 and importing Charts 4.0.3

## What did you expect to happen?

Charts 4.0.3 is successfully imported into my project

## What happened instead?

This error message : 
Specs satisfying the `Charts (~> 4.0.3)` dependency were found, but they required a higher minimum deployment target.

## Charts Environment

**Charts version/Branch/Commit Number: release 4.0.3
**Xcode version: 14 beta 3
**Swift version: 5.7
**Platform(s) running Charts: iOS
**macOS version running Xcode: 12.4

**Comment by dingtianran** [comment]
Xcode 14 completely dropped 32 bit armv7 and iOS 10 support.
Time to move on, or stick to Xcode 13

**Comment by NicolasBoutin** [comment]
Thanks for your answer. Unfortunatly I am facing the same issue with xcode 13.2.1

**Comment by zuoyou1314** [comment]
The platform of the target `xxx` (iOS 11.0) may not be compatible with `Charts (4.0.3)` which has a minimum requirement of iOS 12.0 - tvOS 12.0 - macOS 10.12.

**Comment by pmairoldi** [comment]
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0
