### ISSUE TITLE
Not able to install Chart in Xcode 14 beta 4

### ISSUE THREAD

**Issue by nicoflemming** [danielgindi/Charts#4887]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I added Charts to my Podfile:
pod 'Charts', '~> 4.0.3'

I run pod install and it installed Charts in my Pod directory: Pods/Charts

I did not find Charts in "Framworks, Libraries and Embeded Content" section.
I created a view and used several objects from chart library, but the compiler reports all Objects as missing.

## What did you expect to happen?

I expect to find a section "Embedded Binaries" in the target setup, but it is missing. I googled that and found out, that one should use "Framworks, Libraries and Embeded Content" instead because "Embedded Binaries"  is obsolete and has been removed.

## What happened instead?

I expected to find Charts in "Framworks, Libraries and Embeded Content" but it does not exists.
I expected to find Charts in the left navigation i package dependencies, but it is not there.

## Charts Environment

**Charts version/Branch/Commit Number:** 4.0.3
**Xcode version:** 14 beta 4
**Swift version:** 5
**Platform(s) running Charts:** Apple M1 silicon
**macOS version running Xcode:** Montery 12.5

**Comment by MyHZ** [comment]
extension ChartDataSet: RangeReplaceableCollection {
    public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
        entries.replaceSubrange(subrange, with: newElements)
        notifyDataSetChanged()
    }

**Comment by pmairoldi** [comment]
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0
