### ISSUE TITLE
Not able to compile Xcode 14 beta 6

### ISSUE THREAD

**Issue by GiordanoVicoli** [danielgindi/Charts#4892]
Errors in the class RadarChartRenderer

Regards,
Giordano

**Comment by sharva89** [comment]
Yes,
errors in CandleStickChartRenderer and RadarChartRenderer with error - 

Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<ChartData>' and 'IndexingIterator<CandleChartData>' be equivalent

**Comment by honkmaster** [comment]
BTW: Is this component dead? This bug has been reported on Jul 14 and is not fixed yet. 
@danielgindi @pmairoldi

**Comment by pmairoldi** [comment]
I merged most of the fixes for Xcode 14 last week. I will only make a release after Xcode 14 GM to avoid having to create intermediate versions. 

The component is not dead but I don't see new features being added in the near future. I will try my best to keep updating the versions and such when new Xcode/Swift comes out though. 

For myself I do not work on anything related to the ecosystem anymore so I don't always feel confortable merging code I'm unsure about. Also keep in mind that everyone here is doing this out of the kindness of their heart and on their own time.

**Comment by honkmaster** [comment]
@pmairoldi Thank you very much for the answer. I worked on a popular OSS myself for a long time. Eventually there comes a point where you move on to the next job. That's good and right. I know the situation very well, but because the resulting state of limbo is not good. Thus, I like to ask the provocative question of what happens next. Please don't take my last question as an attack.

**Comment by pmairoldi** [comment]
All good. You asked some very good questions. Personally I would look at what Apple has provided with SwiftUI, from experience less dependencies usually leads to less headaches. As long as SwiftUI works properly which is not always the case :p

**Comment by MyHZ** [comment]
// MARK: RangeReplaceableCollection
extension ChartDataSet: RangeReplaceableCollection {
    public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
        entries.replaceSubrange(subrange, with: newElements)
        notifyDataSetChanged()
    }

**Comment by MyHZ** [comment]
`// MARK: RangeReplaceableCollection
extension ChartDataSet: RangeReplaceableCollection {
    public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
        entries.replaceSubrange(subrange, with: newElements)
        notifyDataSetChanged()
    }
`

**Comment by pchelnikov** [comment]
@pmairoldi hey, the release candidate is out. Do you think it's good enough to draft a new Charts release? :)

**Comment by wrightak** [comment]
Xcode Cloud is using the release candidate so our builds are failing because Charts fails to compile. Will try updating the Podfile to point at the latest commit instead of the release.

**Comment by pchelnikov** [comment]
@wrightak you can choose which Xcode version to use:

<img width="574" alt="Screen Shot 2022-09-11 at 20 36 44" src="https://user-images.githubusercontent.com/1557594/189543628-3974c207-8102-41c6-9ea9-a640d57d1a64.png">

**Comment by JoGoFo-** [comment]
Hello, Xcode 14 and iOS 16 have now been publicly released but still no new Charts release? Ideally this would be have released prior to now so that we don't have to scramble for full iOS 16 support.

Apple stopped doing "GM" releases last year I think, replaced with RC nomenclature.

**Comment by pmairoldi** [comment]
Yeah the GM came out pretty late in relation to the full release. Should be out tonight or tomorrow. 

Keep in mind that I am volunteering my time for this and that I don’t even work on anything Apple related anymore. I get that you want to ship iOS 16 ASAP but if you need a release ASAP just point your package to master. The code for Xcode 14 has been there for over a week at least.

**Comment by pmairoldi** [comment]
closed by https://github.com/danielgindi/Charts/releases/tag/v4.1.0
