### ISSUE TITLE
Xcode 14 Issues

### ISSUE THREAD

**Issue by shuaishuaihenan** [danielgindi/Charts#4906]
RadarChartRenderer.Swift 
line :55
for case let set as RadarChartDataSetProtocol in radarData where set.isVisible
 {
      drawDataSet(context: context, dataSet: set, mostEntries: mostEntries)
 }

Referencing instance method 'makeIterator()' on 'Collection' requires the types 'IndexingIterator<ChartData>' and 'IndexingIterator<RadarChartData>' be equivalent

**Comment by asifhabib** [comment]
Update to latest Charts. It will work.

**Comment by EarthHeroOrg** [comment]
...and if not check out the conversation here:

https://github.com/danielgindi/Charts/issues/4903

**Comment by pmairoldi** [comment]
Closed due to being resolved with latest version already.
