### ISSUE TITLE
ChartViewDelegate & IChartValueFormatter

### ISSUE THREAD

**Issue by JorgenAndreasson** [danielgindi/Charts#4911]
When updating to Chart 4.1.0 Xcode can't find protocol definition for;
ChartViewDelegate
IChartValueFormatter

This is in old OBJ-C code

## Charts Environment

**Charts version/Branch/Commit Number:**
**Xcode version: 14.0 **
**Swift version: 5.7 **
**Platform(s) running Charts: iOS **
**macOS version running Xcode: 12.5.1 **

**Comment by aungyelin** [comment]
Same to me
Cannot find type (IAxisValueFormatter, IValueFormatter) in scope.

**Comment by ravkooashishraval** [comment]
Same to me
Cannot find type (IAxisValueFormatter, IValueFormatter) in scope.
<img width="1056" alt="Screenshot 2022-09-15 at 5 16 21 AM" src="https://user-images.githubusercontent.com/111400313/190281912-c8015222-640d-4967-9372-3c3c8deb45d5.png">

**Comment by KoichiroKAMADA** [comment]
Exactly same to me.
Cannot find type (IAxisValueFormatter, IValueFormatter) in scope.

**Comment by ElCaliph1255** [comment]
- I guess if you want to solve the problem it's about  removing #import bridging header of files contained in you're pods libraries..and there's another solution ( Go to build settings and build after setting Precompile Bridging Header YES -> NO. You can show no errors. But codes defined by objec aren't recognized. It is not able to jump to definition.)

**Comment by nailaobaba** [comment]
Hey guys, I was confused too before I noticed that they are renamed to (AxisValueFormatter, ValueFormatter)
https://github.com/danielgindi/Charts/issues/4775#issuecomment-1026495171

**Comment by aungyelin** [comment]
@nailaobaba you are right, it works by replacing the name. Thank you.

**Comment by JorgenAndreasson** [comment]
@nailaobaba Any update to the ChartViewDelegate name?

**Comment by nailaobaba** [comment]
@JorgenAndreasson 
Sorry, no idea about that

**Comment by ravkooashishraval** [comment]
I found one solution please follow:
1. pod 'Charts', '3.6.0'
2.Find below code and add code after that

```
extension ChartDataSet: RangeReplaceableCollection {
// add this method
        public func replaceSubrange<C>(_ subrange: Swift.Range<Index>, with newElements: C) where C : Collection, Element == C.Element {
            entries.replaceSubrange(subrange, with: newElements)
            notifyDataSetChanged()
        }
```

**Comment by pmairoldi** [comment]
Seems resolved closing
