### ISSUE TITLE
Type 'any Fill' has no member 'fillWithRadialGradient'

### ISSUE THREAD

**Issue by abdorizak** [danielgindi/Charts#4916]
Type 'any Fill' has no member 'fillWithRadialGradient'
<img width="1101" alt="Screen Shot 2022-09-15 at 11 49 43 AM" src="https://user-images.githubusercontent.com/59319407/190359628-ff18b8b1-024c-4999-905b-1a8350708702.png">

**Comment by santieduardo** [comment]
If you are using the latest release version, try to update your `Fill.fillWithRadialGradient()` to the new class `RadialGradientFill`.

You can check all new classes in `Charts/Core/Fill.swift`

**Comment by abdorizak** [comment]
> Core

Can you please give me Example?
