### ISSUE TITLE
Will Charts be compatible with iOS 16?

### ISSUE THREAD

**Issue by ivarvanwooning** [danielgindi/Charts#4917]
Apple is developing a [Charts library](https://developer.apple.com/documentation/charts) with the same name as this repository. It is also imported using 'import Charts'. When iOS 16 is released, will we have an issue importing this library, since there is now an identical library included from Apple?

**Comment by treydin6** [comment]
There is an issue with the imports as we are trying to use both chart libraries. Have you had any luck on a solution to this? @ivarvanwooning

**Comment by ivarvanwooning** [comment]
@treydin6 No, I haven't yet.

**Comment by yveslym** [comment]
So as for now, Charts is not compatible with Xcode 14?

**Comment by ivarvanwooning** [comment]
Looks like it. Perhaps this will work? Changing the Pod name: https://stackoverflow.com/questions/28789807/how-to-rename-a-cocoapod

**Comment by priya-mobiquity** [comment]
How to we fix the import for this library?
As I am using both iOS Charts and this library in my project and I am facing issue with iOS charts import due to this library which I am using it using Swift package manager

**Comment by treydin6** [comment]
You have to pull the package into your project and rename it from Charts to whatever you like(DGCharts is what I named it). @priya-mobiquity i think you could review the stackoverflow post above and it might help achieve this. I am using both charts on an app thats published to the app store. Good luck!

**Comment by pmairoldi** [comment]
Closed by #5027
