### ISSUE TITLE
No such module 'Algorithms' when installed with Swift Package Manager

### ISSUE THREAD

**Issue by Granluke** [danielgindi/Charts#4918]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Tried to implement Charts with SPM and updated from version 3.6 to 4.1

## What did you expect to happen?

No errors while compiling

## What happened instead?

Xcode throws an error while compiling in ChartDataSet, with: No such module 'Algorithms'
When I install that package from the package manager, the problem still exists.

## Charts Environment

**Charts version/Branch/Commit Number: 4.1
**Xcode version: 14.0
**Swift version: 5
**Platform(s) running Charts: iOS
**macOS version running Xcode: 12.5.1

**Comment by Granluke** [comment]
Including the package from branch and not the specific version 4.1.0 fixed it for me (don't know why though...)

**Comment by Kedar-27** [comment]
Facing same issue... above solution didnt work

**Comment by roberthartman** [comment]
I have this issue as well on Xcode 14.0 using `v4.1.0`, and also using `master`. In both cases `swift-algorithms` v1.0 clearly shows up in the packages list.  The build error is against ChartDataSet.swift: `No such module 'Algorithms'`
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/4998988/196236183-0d39a801-3552-4d4d-97cc-e79d64412ced.png">
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/4998988/196236488-6cf462f8-49e6-4052-87c5-3388c3c07bb1.png">

**Comment by alisonqiu** [comment]
> This solution worked for me: #4646
> Delete the Charts dependency and re-add it, but only select the Charts package product.

I tried your solution, but I still got No such module 'RangeReplaceableCollectionCharts'

**Comment by pmairoldi** [comment]
Closing since it seems resolved.
