### ISSUE TITLE
SwiftAlgorithms Bitcode_disabled

### ISSUE THREAD

**Issue by afridikhalid** [danielgindi/Charts#4919]
## What did you do?

ℹ I did a pod update with charts '~> 4.1.0`

## What did you expect to happen?

ℹ I expected that everything should work smoothly. but found out that Charts 4.1.0 has many breaking changes. which I have now updated everything. no more errors regarding Charts it self

## What happened instead?

ℹ When I use Pods install it installs SwiftAlgorithms together with Charts 4.1.0 and that's when I try to run the project I get the error that SwiftAlgorithms should enable bitcode and I don't know how to change that.

## Charts Environment

**Charts version/Branch/Commit Number:** 4.1.0
**Xcode version:**  14.0
**Swift version:** 5
**Platform(s) running Charts:**  iOS

**Comment by afridikhalid** [comment]
I had to iterate through all my targets and set ENABLED_BITCODE  to true and now everything works :)

**Comment by areejsadaqa66** [comment]
I am still facing a  problem with SwiftAlgorithms some files showing errors as: 'let' property 'base' may not be initialized directly; use "self. init(...)" or "self = ..." instead

and I tried to get all BITCODE to enable true and it still didn't work

**Comment by mugikhan** [comment]
> 

I am having the same issue as bove

**Comment by tejua** [comment]
I am having the same issue 
did you find any solutions? @mugikhan @afridikhalid

**Comment by mounou19** [comment]
This should help bypassing the issue until SwiftAlgorithms get updated to support new swift 5.7 I think !
To add at the end of your Podfile

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "SwiftAlgorithms"
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      end
    end
  end
end
```
