### ISSUE TITLE
When i scroll x direction on line chart, tableview to scrolls same time to up or down

### ISSUE THREAD

**Issue by Rylaa** [danielgindi/Charts#4920]
Hi everyone,

I've searched and tried some ways but I don't find any solution.

I have a line chart in a tableView. When I scroll x direction on the line chart, tableView to scrolls the same time up. I want to when the user starts dragging on the line chart prevent to tableView scroll. 

I tried gestures, scrollView delegate, and chartValueSelected but didn't work the way I wanted

What can I do? 

Thanks for answers

**Comment by GFGWin** [comment]
I also encountered the same problem, but after testing, I found a solution, which is to change the dynamic row height of tableView to a fixed row height
