### ISSUE TITLE
After updating the app in Appstore in iOS 9.3.5, it appears that the app restarts and then disappears. There is a problem showing charts. How to solve the problem?

### ISSUE THREAD

**Issue by qimiao2012** [danielgindi/Charts#4923]
After updating the app in Appstore in iOS 9.3.5, it appears that the app restarts and then disappears. There is a problem showing charts. How to solve the problem?

Incident Identifier: 4539FB2E-2F87-4204-A86D-CAF790A34443
CrashReporter Key:   baf6dbe688f57ba8331324a8f5af148d7bb6bdc8
Hardware Model:      iPhone8,1
Version:             1 (1.3.11)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2022-09-16 14:54:45.45 +0800
Launch Time:         2022-09-16 14:54:45.45 +0800
OS Version:          iOS 9.3.5 (13G36)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000120071088
Triggered by Thread:  0

Filtered syslog:
None found

Dyld Error Message:
Dyld Message: Library not loaded: /usr/lib/swift/libswiftCoreData.dylib
  Referenced from: /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/BaseProject
  Reason: image not found
  Dyld Version: 390.7

Binary Images:
0x10007c000 - 0x10079bfff BaseProject arm64  <a560da52bc623d2e960278630e0121d7> /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/BaseProject
0x100a34000 - 0x100eebfff NIMSDK arm64  <ed587634b89e37fb8948e7fc39b9db79> /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/Frameworks/NIMSDK.framework/NIMSDK
0x1010b8000 - 0x101417fff QYSDK arm64  <1ecc28da2b783833b5a079735ea2e555> /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/Frameworks/QYSDK.framework/QYSDK
0x101588000 - 0x101673fff Charts arm64  <74f3d0386fb53aa78a459b1ae7f6a931> /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/Frameworks/Charts.framework/Charts
0x101700000 - 0x101a3bfff libswiftCore.dylib arm64  <607fd5d0918834c695f1341bf74e1423> /var/containers/Bundle/Application/BB574847-2B60-4228-A1D3-6090B1C91AA3/BaseProject.app/Frameworks/libswiftCore.dylib
0x120070000 - 0x12009ffff dyld arm64  <a1862e29910f3f069a363730df77dad7> /usr/lib/dyld

**Comment by pmairoldi** [comment]
Currently we do not support iOS 9. The minimum is iOS 12. Sorry about that.
