### ISSUE TITLE
RadarChartDataSet  左下角图例无法隐藏

### ISSUE THREAD

**Issue by Cillianer** [danielgindi/Charts#4935]
RadarChartDataSet * set1 =[[RadarChartDataSet alloc]initWithEntries:yVals1 label:@""];

    RadarChartDataSet * set1 =[[RadarChartDataSet alloc]initWithEntries:yVals1];

  都无法隐藏左小脚图例

**Comment by Cillianer** [comment]
RadarChartDataSet * set1 =[[RadarChartDataSet alloc]initWithEntries:yVals1 label:@""];

  RadarChartDataSet * set1 =[[RadarChartDataSet alloc]initWithEntries:yVals1];

都无法隐藏左小脚图例

**Comment by binbins** [comment]
try below code:

`chart.legend.enabled = NO`
