### ISSUE TITLE
iAxisValueFormat issue when Building the app

### ISSUE THREAD

**Issue by karthikeyan1425** [danielgindi/Charts#4954]
Hello,

Facing below issues, kindly check the screenshot,

![Screenshot 2022-10-28 at 4 43 53 PM](https://user-images.githubusercontent.com/12165055/198574352-36ccf7fb-1838-4266-9c4d-6ebc202347ce.png)

![Screenshot 2022-10-28 at 4 44 00 PM](https://user-images.githubusercontent.com/12165055/198574305-d3ca77a5-f44e-4378-b308-1883ae1d2ac3.png)

Charts version/Branch/Commit Number: 3.6
Xcode version: 14.0.1
Swift version: iOS 16
Platform(s) running Charts: -
macOS version running Xcode: macOS Monterey v12.6

**Comment by odanu** [comment]
`IAxisValueFormatter` got renamed to `AxisValueFormatter`.

**Comment by pmairoldi** [comment]
Yup it was renamed.
