### ISSUE TITLE
No Such Module Algorithms

### ISSUE THREAD

**Issue by bitw14** [danielgindi/Charts#4959]
## What did you do?

Added charts v4.1.0 via SPM

## What did you expect to happen?

It should compile

## What happened instead?

No Such Module algorithms in multiple classess

## Charts Environment

**Charts version/Branch/Commit Number:4.1.0
**Xcode version:14.0
**Swift version:5.0
**Platform(s) running Charts:iOS
**macOS version running Xcode:12.6

## Demo Project

[TestSPM.zip](https://github.com/danielgindi/Charts/files/9927705/TestSPM.zip)

**Comment by iPhoneNoobDeveloper** [comment]
I am facing the same issue after installing pod version 4.1.0.

**Comment by WGFcode** [comment]
I am facing the same issue with manual installation

**Comment by ariarora14** [comment]
I am also facing this issue. @iPhoneNoobDeveloper @WGFcode were any of you able to figure it out?

**Comment by WGFcode** [comment]
> I am also facing this issue. @iPhoneNoobDeveloper @WGFcode were any of you able to figure it out?

I solved this problem by adding Algorithms dependencies via SMP @ariarora14

**Comment by ariarora14** [comment]
@WGFcode Btw I found the solution. I had also installed using SPM first but the second time you should only import Charts and not ChartsDynamic. Found it in #4646

**Comment by LebonNic** [comment]
I was facing the same issue using `CocoaPod` and I finally solved it by running a `pod deintegrate` from this [repo](https://github.com/CocoaPods/cocoapods-deintegrate), followed by a `pod install` and now it builds. 

I hope this can help you, although I'm not at all sure I understand why it worked...

**Comment by liuxuan30** [comment]
seem duplicated as https://github.com/danielgindi/Charts/issues/4951
I was able to build now. reopen if needed
