### ISSUE TITLE
XcodeGen SPM - No such module Charts

### ISSUE THREAD

**Issue by 22Round** [danielgindi/Charts#4967]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

using [XcodeGen](https://github.com/yonaskolb/XcodeGen/) for my project
```
packages:
  Charts:
    url: https://github.com/danielgindi/Charts
    branch: master
```
## What did you expect to happen?

build the project!

## but when I add Charts manually in SPM and select Charts it works!

<img width="1082" alt="Screenshot 2022-11-09 at 11 19 19" src="https://user-images.githubusercontent.com/5682469/200765924-547b50f6-f62c-4407-b6e1-b87ce27632de.png">

## What happened instead?

No such module 'Charts'

## Charts Environment

**Charts version/Branch/Commit Number:** master
**Xcode version:** 13.4.1
**Swift version:** 5.6.1
**Platform(s) running Charts:** iOS
**macOS version running Xcode:** macOS Monterey 12.6.1 (21G217)

**Comment by pmairoldi** [comment]
It sounds like and XcodeGen issue if you are able to do it manually and it works.
