### ISSUE TITLE
Facing crash in charts latest version

### ISSUE THREAD

**Issue by manpreetsains6446** [danielgindi/Charts#4982]
Crashed: com.apple.main-thread
0  Charts                         0x9f648 $s6Charts18RadarChartRendererC11drawDataSet7context04dataG011mostEntriesySo12CGContextRefa_AA0bcfG8Protocol_pSitF + 3904
1  Charts                         0x9e5a0 $s6Charts18RadarChartRendererC8drawData7contextySo12CGContextRefa_tF + 696
2  Charts                         0x9e6ec $s6Charts18RadarChartRendererC8drawData7contextySo12CGContextRefa_tFTo + 52
3  Charts                         0xa3cf0 $s6Charts14RadarChartViewC4drawyySo6CGRectVF + 684
4  Charts                         0xa3f5c $s6Charts14RadarChartViewC4drawyySo6CGRectVFTo + 68
5  UIKitCore                      0x1ae7a4 -[UIView(CALayerDelegate) drawLayer:inContext:] + 508
6  QuartzCore                     0x1e174 CABackingStoreUpdate_ + 204
7  QuartzCore                     0x9db40 invocation function for block in CA::Layer::display_() + 64
8  QuartzCore                     0x1d95c -[CALayer _display] + 1740
9  QuartzCore                     0x1d1a8 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 412
10 QuartzCore                     0x2e5b0 CA::Context::commit_transaction(CA::Transaction*, double, double*) + 456
11 QuartzCore                     0x635ec CA::Transaction::commit() + 652
12 QuartzCore                     0x4c8cc CA::Transaction::flush_as_runloop_observer(bool) + 88
13 CoreFoundation                 0x91d60 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
14 CoreFoundation                 0x1a2d0 __CFRunLoopDoObservers + 532
15 CoreFoundation                 0x7bc7c __CFRunLoopRun + 1048
16 CoreFoundation                 0x80ed4 CFRunLoopRunSpecific + 612
17 GraphicsServices               0x1368 GSEventRunModal + 164
18 UIKitCore                      0x3a23d0 -[UIApplication _run] + 888
19 UIKitCore                      0x3a2034 UIApplicationMain + 340
20 Grintafy                       0x50728 main + 49 (AppDelegate.swift:49)
21 ???                            0x1d1cb0960 (Missing)

**Comment by manpreetsains6446** [comment]
?

**Comment by ShubhCSDeveloper** [comment]
You can find solution here https://freelightupcamp.com/index.php/2023/02/19/bar-chart/

**Comment by pmairoldi** [comment]
Closing due to lack of details so solution has been provided.
