### ISSUE TITLE
Cannot find type 'BarChartView' in scope xcode 14.0.1

### ISSUE THREAD

**Issue by MohanNB** [danielgindi/Charts#4985]
[i'm](u
<img width="1378" alt="Screenshot 2022-12-14 at 10 36 02 PM" src="https://user-images.githubusercontent.com/80029732/207660730-c19f62fb-3972-4e88-9223-65df649669d2.png">
rl) facing issue Charts adding on viewcontroller .

i have installed pod file in xcode 14.0.1 sample app . try use barChart using storyboard .

get this issue "Cannot find type 'BarChartView' in scope"

how to solve it 

## Charts Environment

**Charts version/Branch/Commit Number:**
**14.0.1**
**5.6**
**ios:**

**Comment by Magy-Elias** [comment]
Same issue .. 
Any Help?

**Comment by diegopereiraeng** [comment]
same here

**Comment by ZacYoutube** [comment]
any help?

**Comment by eandflores** [comment]
For me the problem disappear when I added Charts in Target Libraries (Tested only with Mac os Ventura, XCode 14.3 and Charts 4.1.0)

Choose the project root, in Targets choose your target.  Then choose General tab ->  Frameworks, Libraries and Embedded Content -> + button. 
Add Charts (Don't add Charts Dynamic to target, it's not necessary for compile and produce this dependency problem https://github.com/danielgindi/Charts/issues/4845)

**Comment by pmairoldi** [comment]
Closed by #4845
