### ISSUE TITLE
Swift Charts module with valueFormatter iOS16

### ISSUE THREAD

**Issue by GuriSarao** [danielgindi/Charts#4986]
I am not able to assign a custom valueFormat to graph 

view_barGraph.xAxis.valueFormatter = DayAxisValueFormatter()

This line is giving me error Cannot assign value of type 'DayAxisValueFormatter' to type '(any AxisValueFormatter)?'

I want month names on xAxis. it was working fine before but after upgrade xcode 14 it shows me this error

**Comment by corteggo** [comment]
I had the same issue and I had to change `DayAxisValueFormatter` conformance from `IAxisValueFormatter` to `AxisValueFormatter` since they differ from 3.x to 4.x.

**Comment by pmairoldi** [comment]
Closing as resolved
