### ISSUE TITLE
Consider renaming library (e.g. DGCharts)

### ISSUE THREAD

**Issue by lukeredpath** [danielgindi/Charts#5015]
The name of this library is now in conflict with Swift Charts.

I have found that if you have another third-party dependency that uses Swift Charts, the compiler is unable to disambiguate between Swift Charts and this library when it encounters an `import Charts` library. I have worked around this issue by forking this repo and renaming the SPM library to `DGCharts`.

**Comment by liuxuan30** [comment]
https://github.com/danielgindi/Charts/pull/5009 on it
