### ISSUE TITLE
Include swift-numerics and swift-algorithms

### ISSUE THREAD

**Issue by nanditovelvet** [danielgindi/Charts#5024]
- [x]  I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I created an XCFramework using ```carthage build --no-skip-current --plattform iOS && carthage archive Charts``` but when I try to use it the swift-algorithms libraries and swift-numerics are missing

## What did you expect to happen?

Create an XCFramework with those libraries included 

## What happened instead?

 Libraries are missing

## Charts Environment

**Charts version/Branch/Commit Number: 4.1.0**
**Xcode version: 14.1**
**Swift version: .57**
**Platform(s) running Charts: iOS**
**macOS version running Xcode:  13.2.1 Ventura**

**Comment by pmairoldi** [comment]
Those frameworks have been removed for 5.0. This problem should not happen anymore.
Closed by #5069
