### ISSUE TITLE
Package name collision with Apple Charts 

### ISSUE THREAD

**Issue by narcistabarasi** [danielgindi/Charts#5054]
When trying to use both this package using SPM and Apple's Charts framework in the same project, there's a collision when importing `Charts`. Is there a known workaround for this?

**Comment by xjki** [comment]
Renaming is work in progress see:
https://github.com/danielgindi/Charts/pull/5028

Meanwhile you can see workaround using CocoaPods here:
https://github.com/xjki/Charts/commit/e7404598e2c5bd2f6f26ce2a4f095ac1be6f4bac

**Comment by xjki** [comment]
Resolved in v5.0.0 https://github.com/danielgindi/Charts/releases/tag/5.0.0
