### ISSUE TITLE
Percentage symbol

### ISSUE THREAD

**Issue by NVAT** [danielgindi/Charts#5073]
###       Hi, thank you for the great lib, but this part did not work, I can't show the percentage symbol. Thank you.
      I have used UIKIt
      
```
      let pFormatter = NumberFormatter()
               pFormatter.numberStyle = .percent
               pFormatter.maximumFractionDigits = 1
               pFormatter.multiplier = 1
               pFormatter.percentSymbol = " %"
        pieChartData.setValueFormatter(DefaultValueFormatter(formatter: pFormatter))
             
        pieChartData.setValueFont(.systemFont(ofSize: 11, weight: .light))
        pieChartData.setValueTextColor(.black)
```
<img width="378" alt="Screenshot 2023-06-14 at 13 11 17" src="https://github.com/danielgindi/Charts/assets/16933227/599da221-dca0-488b-9794-cb1a513b8f20">

**Comment by xingren66** [comment]
Hi, were you able to solve this issue? I had the same problem

**Comment by NVAT** [comment]
> Hi, were you able to solve this issue? I had the same problem

Not, this problem still actual

**Comment by xingren66** [comment]
> > Hi, were you able to solve this issue? I had the same problem
> 
> Not, this problem still actual

I found the answer elsewhere.

```
barChartView.data = data
data.setValueFormatter(valueFormatter)
```
https://github.com/danielgindi/Charts/issues/4690#issuecomment-897744617

**Comment by NVAT** [comment]
> > > Hi, were you able to solve this issue? I had the same problem
> > 
> > 
> > Not, this problem still actual
> 
> I found the answer elsewhere.
> 
> ```
> barChartView.data = data
> data.setValueFormatter(valueFormatter)
> ```
> 
> [#4690 (comment)](https://github.com/danielgindi/Charts/issues/4690#issuecomment-897744617)

Thank you its work
