### ISSUE TITLE
Apple silicon Macs support issue

### ISSUE THREAD

**Issue by kleber-maia** [danielgindi/Charts#5102]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Upgraded to 5.0

## What did you expect to happen?

For my app to keep being supported on silicon Macs.

## What happened instead?

The app no longer runs on `My Mac (Designed for iPad)` target:

```
No such file or directory: '/Users/klebermaia/Library/Developer/Xcode/DerivedData/Cash_Predict-cbxqrzsefmsduudxmvxsedneiazn/Build/Products/Debug-iphoneos/PackageFrameworks/DGChartsDynamic.framework/DGChartsDynamic'
```

Upon pushing a build to Test Flight, I've also received this email from Apple:

```
ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:

- /Volumes/workspace/DerivedData/Build/Intermediates.noindex/ArchiveIntermediates/Cash Predict/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/DGChartsDynamic.framework/DGChartsDynamic

After you’ve corrected the issues, you can upload a new binary to App Store Connect.
```

## DGCharts Environment

**DGCharts version/Branch/Commit Number:**
```
        "revision" : "0a229f8c914b0ec93798cee058cf75b339297513",
        "version" : "5.0.0"
```
**Xcode version:** 15.0 Beta 8
**Swift version:** Swift 5
**Platform(s) running DGCharts:** macOS
**macOS version running Xcode:** Sonoma

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by Shirayo** [comment]
Delete package and add it again but select only DGCharts. It fixed problem for me
<img width="296" alt="image" src="https://github.com/danielgindi/Charts/assets/38223217/5e3ed4a4-cd84-4970-99bd-4545c77905e8">

**Comment by kleber-maia** [comment]
> Delete package and add it again but select only DGCharts. It fixed problem for me <img alt="image" width="296" src="https://user-images.githubusercontent.com/38223217/268680571-5e3ed4a4-cd84-4970-99bd-4545c77905e8.png">

Thanks. I've already migrated all my charts to `SwiftUI`'s `Chart`. 🤠

p.s. `DGCharts` was a blessing and I'm really grateful for having it for the past several years, but times have changed.

**Comment by Shirayo** [comment]
That's great! 🤠 But for me it's not a solution since my application should be supported from iOS 14.

**Comment by JensWii** [comment]
Hi, unfortunately I have the same problem and deleting the package and only installing DGCharts did not help. Has anybody another solution?

**Comment by davita00101110dmg** [comment]
> Delete package and add it again but select only DGCharts. It fixed problem for me <img alt="image" width="296" src="https://private-user-images.githubusercontent.com/38223217/268680571-5e3ed4a4-cd84-4970-99bd-4545c77905e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDI2NzgsIm5iZiI6MTcwMzUwMjM3OCwicGF0aCI6Ii8zODIyMzIxNy8yNjg2ODA1NzEtNWUzZWQ0YTQtY2Q4NC00OTcwLTk5YmQtNDU0NWM3NzkwNWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MWI1ODFhMGI1NTYzODQ5NmY2Mjg3YTlmZDRkODJhYjYwNWZkNzFkMjg2OTYzODZiMDlmOWMwM2Q3NWZhOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pUd8Q57gfKbVJxOkbfhVdDcXsN04F2XpRHb-T-Yp-DQ">

Worked for me! Thanks!

**Comment by pmairoldi** [comment]
Seems like a solved problem closing.
