### ISSUE TITLE
After upgrade to 5.0 all charts crash on <Chart>.delegate = self in ViewDidLoad()

### ISSUE THREAD

**Issue by perbrondum** [danielgindi/Charts#5104]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

After upgrade to DGCharts 5.0, all my IB defined charts crash when assigning ' <chart>.delegate = self' in ViewDidLoad()

## What did you expect to happen?

Same code has been working in 3.0/4.0 of Charts

## What happened instead?

Crash

## DGCharts Environment

**DGCharts version/Branch/Commit Number:** Master
**Xcode version:**  Version 15.0 beta 8 (15A5229m)
**Swift version:**
**Platform(s) running DGCharts:** Mac Studio
**macOS version running Xcode:**  Version 14.0 Beta (23A5337a)

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by oleksandr-kosylov** [comment]
For me crashing on every usage of **PieChartView** properties:
Error message says: _[Storyboard] Unknown class _TtC6Charts12PieChartView in Interface Builder file._

**Comment by perbrondum** [comment]
I see the same error message in the console.

**Comment by perbrondum** [comment]
Solved: In my case (an most likely all) the Module name change caused this. Change 'Module name' in all IB charts to DGCharts and it works just fine.

**Comment by perbrondum** [comment]
Closed.

**Comment by devssun** [comment]
> Solved: In my case (and most likely all) cases, the Charts 'Module Name' change caused this. Change 'Module Name' in all IB chart elements from 'Charts' to 'DGCharts' and it should work.

it works. thank you.
