### ISSUE TITLE
Privacy Manfiest

### ISSUE THREAD

**Issue by amcalgates** [danielgindi/Charts#5131]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

Read [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc), which say:

> From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

Wasn't sure, so thought I'd ask (feature request?): does Charts use any APIs mentioned here? If so, are there plans to include a privacy manifest? I'm not 100% sure what that'd even look like, but [this thread](https://developer.apple.com/forums/thread/733537) maybe has a little insight.

## What did you expect to happen?
N/A

## What happened instead?

N/A

## DGCharts Environment

N/A

## Demo Project

N/A

**Comment by LionWY** [comment]
+1

**Comment by ag-drivequant** [comment]
Charts is on the list "SDKs that require a privacy manifest" provided by Apple 
https://developer.apple.com/support/third-party-SDK-requirements/
not clear if one of the "required reason API" is being used

**Comment by wlxo0401** [comment]
@ag-drivequant 

https://developer.apple.com/support/third-party-SDK-requirements/

It seems that Charts is on the list mentioned by Apple.

**Comment by wlxo0401** [comment]
+1

**Comment by ojun9** [comment]
+1

**Comment by wlxo0401** [comment]
@danielgindi 

Any support/plan of Privacy Manifest?

**Comment by wlxo0401** [comment]
@danielgindi @pmairoldi 

Any support/plan of Privacy Manifest?

**Comment by pmairoldi** [comment]
Yeah I have no issue with it. I don’t really work on anything swift right now so I have no idea what this entails. So if someone can create a pull request for this I’ll merge and create a new release.

**Comment by wlxo0401** [comment]
[Apple Doc](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)

Everyone.

Is there anything in DGCharts(Charts) that corresponds to the document above?? 

Please feel free to share your opinions.

**Comment by wlxo0401** [comment]
> Yeah I have no issue with it. I don’t really work on anything swift right now so I have no idea what this entails. So if someone can create a pull request for this I’ll merge and create a new release.

Thank you so much for spending your time in your busy daily life.
Thank you so much for just releasing a new version. 
I'm glad you have authority.


----

[Apple Doc](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files)

Everyone.

Is there anything in DGCharts(Charts) that corresponds to the document above?? 

Please feel free to share your opinions.

(Please understand that I use a translator because my English is not good enough.)

**Comment by wlxo0401** [comment]
I created a PR (as mentioned above), please feel free to take a look.🙏

**Comment by GH-Ong** [comment]
@danielgindi @pmairoldi 
From what i understand from apple's document a code signature is required as well in addition to the privacymanifest.
Will there be a release with the code signature and privacymanifest provided?

**Comment by pmairoldi** [comment]
I’ve quickly read up on the topic and there does not seem to be way to do so right now. I’ve found a similar issue https://github.com/Alamofire/Alamofire/issues/3761

**Comment by pmairoldi** [comment]
Yeah we can do both at once. Still unsure how to make the signature work. It has always been a problem with open source development. I have my own developer account but not one for this GitHub project. I’ll look around other projects to see what’s up there.

**Comment by mjburghard** [comment]
@pmairoldi Is the signature required for Charts?
> **SDKs that require a privacy manifest and signature**
> The following are commonly used SDKs in apps on the App Store. Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. **_Signatures are also required in these cases where the listed SDKs are used as binary dependencies_**. Any version of a listed SDK, as well as any SDKs that repackage those on the list, are included in the requirement.
From [Upcoming third-party SDK requirements](https://developer.apple.com/support/third-party-SDK-requirements/)

I don't know about Carthage, but for SPM and Cocoapods the sentence above sounds like the signature is not required.

**Comment by pmairoldi** [comment]
Nice catch! Thanks for the info

**Comment by wlxo0401** [comment]
How do I fix this? "Some checks were not successful"

https://github.com/danielgindi/Charts/pull/5141

**Comment by wlxo0401** [comment]
I discovered a new fact while testing. Until now, most of the libraries that have added PrivacyInfo have not been marked in PrivacyReport. 

However, when an item is added to the 'Personal Information Nutrition Label Type', the library name is displayed in the personal information protection report. 

Many libraries have updated PrivacyInfo without adding anything from Privacy Nutrition Label Types.

Does anyone know about this? Is "Privacy Nutrition Label Types" a must-have item?

Please feel free to leave your opinion.

**Comment by pmairoldi** [comment]
Seems like this is for the consuming app no? It would be good to test if generating the report after integrating the library works properly.

**Comment by tummalaguntimahesh** [comment]
Looking for this change

**Comment by wlxo0401** [comment]
@pmairoldi 

Hello, I think the time has come..

I think I'll have to apply it and see how it works. 

How are you going to proceed?? 

Even if it is applied, it is necessary to constantly check that Apple app reviews are passed properly for a while.

I would appreciate it if you could share your plans or thoughts.

**Comment by wlxo0401** [comment]
Thank you for accepting the PR. 

However, I think it is also necessary to make sure that this is applied properly as Apple demanded. 

And I think other users will have to check it out a lot. 

If this is wrong, an immediate response may also be needed..

When is the new release that includes this?? 

Once again, thank you for your care in a busy time.
