### ISSUE TITLE
Crash when running on 10.13

### ISSUE THREAD

**Issue by WhisperCF** [danielgindi/Charts#5138]
* [ x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

I created a simple line chart view using Xcode 15.1 and macOS Sonoma 14.2. I've set the deployment target to 10.13. The test project runs and displays the expected chart in Sonoma, but crashes on launch in macOS 10.13

EDIT: Sample Project in the repository also crashes 

## What did you expect to happen?

I expected the test app to run and display the same chart as when run on Sonoma.

## What happened instead?

Application crashes. 

## DGCharts Environment

**DGCharts version/Branch/Commit Number:**
DGCharts 5.0.0, master branch, e515b048
**Xcode version:**
15.1
**Swift version:**
Swift 5
**Platform(s) running DGCharts:**
macOS
**macOS version running Xcode:**
macOS Sonoma 14.2

## Demo Project

Also reproduces on sample project in repository.
[testDGCharts.zip](https://github.com/danielgindi/Charts/files/13730059/testDGCharts.zip)

**Comment by pmairoldi** [comment]
10.13 is pretty old at this point I am going to close this and suggest supporting only higher versions.
