### ISSUE TITLE
line break

### ISSUE THREAD

**Issue by iBiLin** [danielgindi/Charts#5140]
how to do break line when non data ?
![WeChat51f3d614192c85b8dfcf64d51e1629e2](https://github.com/danielgindi/Charts/assets/13670910/98ba75fd-5c4a-4bed-9fac-a4858af170c0)

**Comment by wtuyp** [comment]
add a new dataset

**Comment by pmairoldi** [comment]
You can create a dataset from for example [0 - 5] and then a second one from [10 - 15] and it should do what you want.
