### ISSUE TITLE
facing problem with PieChart.noDataText is not display

### ISSUE THREAD

**Issue by MallikarjunaMore** [danielgindi/Charts#5145]
Hi Team, facing same problem, I am using PieChart in TabBarController, same noDataText is not displaying. I tried to place in viewdidload and viewwillappear both. Assist me.
statusPieChart.noDataText = "Something"

## What did you do?

statusPieChart.noDataText = "No chart data available"

## What did you expect to happen?

when getting nil response, need to showing No chart data available

## What happened instead?

getting empty screen

## DGCharts Environment

**DGCharts version/Branch/Commit Number:** DGCharts (5.0.0)
**Xcode version:** Version 14.3.1 (14E300c)
**Swift version:** Swift 5
**Platform(s) running DGCharts:** iOS
**macOS version running Xcode:** 13.6.3

**Comment by pmairoldi** [comment]
I think the problem is that you are missing a `chart.setNeedsDisplay()`. Some operations do not automatically redraw the chart it seems like. 

This seems to work:
```swift
let chart = PieChartView(frame: CGRect(x: 0, y: 0, width: 200, height: 200));
chart.noDataText = "No Data";
chart.setNeedsDisplay()
```
