### ISSUE TITLE
Need Privacy Manifest

### ISSUE THREAD

**Issue by tummalaguntimahesh** [danielgindi/Charts#5147]
Read [Apple docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc), which say:

From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

* [&#x2713;] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

## What did you do?

N/A

## What did you expect to happen?

A new version with Privacy manifest changes to be available. I also see there is an [Open PR](https://github.com/danielgindi/Charts/pull/5141) regarding this Privacy manifest changes. Is there any plan date for this change to be merged?
If not can these Privacy Manifest changes added to 3.4.0 version and publish a new version which is based of 3.4.0?

## What happened instead?

N/A

## DGCharts Environment

N/A

## Demo Project

N/A

**Comment by gabors** [comment]
+1

**Comment by juntec** [comment]
Our app also needs PrivacyManifest.
If the Pull Request is not merged, our app will need to switch to another SDK.

**Comment by wlxo0401** [comment]
> Our app also needs PrivacyManifest. If the Pull Request is not merged, our app will need to switch to another SDK.

Is there a quick switchable SDK in Charts?

**Comment by pmairoldi** [comment]
closed by [#5.1.0](https://github.com/danielgindi/Charts/releases/tag/5.1.0)
