### ISSUE TITLE
DGCharts.framework/Headers/DGCharts-Swift.h:4769:2: Unsupported Swift architecture

### ISSUE THREAD

**Issue by zanivanov** [danielgindi/Charts#5148]
Hello,
i have a problem. 

I use j2objc and apple mac with M1. In order to build the project, I have to use excluded for ios simulator. Unfortunately, I get the error that this platform is not supported. Am I doing something wrong or is there a bug in the project? Thanks

**Comment by pmairoldi** [comment]
I don't understand the problem here. If you have a repo project then we can look into it but since you are using `j2objc` I am leaning towards we cannot help you. You might find more help with people who know how `j2objc` works.
