### ISSUE TITLE
Draw gradient line in line chart

### ISSUE THREAD

**Issue by luhui** [danielgindi/Charts#537]
I want to draw a gradient line chart like the picture below:
![image](https://cloud.githubusercontent.com/assets/2842522/10997006/986cd680-84c4-11e5-8ae9-c80768622f6e.png)

It is a human temperature record. The gradient value follow the temperature, the color guide is the picture below:

![image](https://cloud.githubusercontent.com/assets/2842522/10997109/5654897c-84c5-11e5-8e6d-763c991ab735.png)

In MPAndroidChart, below code will be work:

```
Paint paint = mChart.getRenderer().getPaintRender();
        paint.setShader(new LinearGradient(0, 0, 0, height, Color.RED, Color.BLUE, Shader.TileMode.REPEAT));
```

Did iOS-charts support these feature?

**Comment by liuxuan30** [comment]
Currently, no. But it will be a good feature to have.

**Comment by ondrejhanslik** [comment]
In my opinion, ios charts need a more stable internal API and then removal of the `internal` keyword from most renderer methods. Then it will be simple to override a method with custom implementation. A chart library can never cover all use cases but it should be customizable.

**Comment by danielgindi** [comment]
We need to look into CoreGraphics and see if there's something similar to that shader effect

The problem with it though (on Android also!) is that it does not correlate to the colors that you have specified on your yAxis. It advances with the line, but not specifically on the yAxis.

I'm guessing that on both platforms it should be much more complex, as we'll need to break this stuff down ourselves and interpolate the colors.

Anyway, all the stuff in the renderers is public since v2.2.0!

**Comment by ondrejhanslik** [comment]
Thanks for the info, I am still on v2.1.x and didn't notice this. Good job! Then I believe this issue could be closed. On iOS everything is drawn through `CGContext` and for drawing gradients there is a special function `CGContextDrawLinearGradient`. Overriding the line drawing method is probably the only solution.

**Comment by liuxuan30** [comment]
@danielgindi Do we support such gradient line already? I took some days off, not sure if we can close this.

**Comment by mobidever** [comment]
Hey do we have any update on the integration of the gradient lines?

**Comment by owenhay** [comment]
I'm interested in this issue, and I'm doing a chart UI implementation this week with a gradient, and I'll try the CGContextDrawLinearGradient override approach and report back.

**Comment by rohinb** [comment]
Any update on this? I'm working on a design with line charts using a gradient where the lines simply fades away toward the end.

**Comment by liuxuan30** [comment]
@rohinb do you see the PR already? It's not merged yet. But you could give a try, overriding some methods

**Comment by coolioxlr** [comment]
any update on this?

**Comment by hananRiazz** [comment]
any update on this issue?

**Comment by thierryH91200** [comment]
see #649

**Comment by jjatie** [comment]
#3141

**Comment by abhiccc5** [comment]
I have created a video tutorial for this task. Kindly refer to my video.

https://www.youtube.com/watch?v=zT6zMyYpkXM&t=13s

**Comment by Maxim-Gorin** [comment]
any update on this?

**Comment by liuxuan30** [comment]
this is implemented in 4.0 branch, we are working on 4.0 merge, so stay tuned.

**Comment by a1049145827** [comment]
Is it finished now？

**Comment by YutaLin** [comment]
Hi @liuxuan30, In previous version api I can set gradient color, but can't use it now. I got error when I fetch branch 4.0.0 currently. 

Here's how I did, please help me, I implement in production app and can't work after I try pod install now, thanks!

pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => '4.0.0'
<img width="1789" alt="Screen Shot 2021-02-24 at 3 37 00 PM" src="https://user-images.githubusercontent.com/11587886/108964208-257ce680-76b6-11eb-8282-4785fce7fb4c.png">

**Comment by DhavalUmraliya** [comment]
> Hi @liuxuan30, In previous version api I can set gradient color, but can't use it now. I got error when I fetch branch 4.0.0 currently.
> 
> Here's how I did, please help me, I implement in production app and can't work after I try pod install now, thanks!
> 
> pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => '4.0.0' <img alt="Screen Shot 2021-02-24 at 3 37 00 PM" width="1789" src="https://user-images.githubusercontent.com/11587886/108964208-257ce680-76b6-11eb-8282-4785fce7fb4c.png">

have you found any solution
