### ISSUE TITLE
Drop iOS 7 support in readme

### ISSUE THREAD

**Issue by petester42** [danielgindi/Charts#601]
iOS 7 is only a few percent of the market share right now and there are a lot of people having issues with how to install the library. Since this library is built with frameworks in mind we should consider dropping iOS 7 support since they aren't available for iOS 7. 

Obviously it is still possible to use with iOS 7 but the only supported ways of installation would be the framework methods (import Xcode project, cocoapods, Carthage). This should maybe reduce all the issues we get about ios 7 installation.

**Comment by liuxuan30** [comment]
I guess we have to wait until Apple offically killed the iPhones which installed iOS 7 by default. Some people just won't upgrade iOS and use the apps, especially who paid for the app. At least I was told to support iOS 7 until it's dead. I got 5 iOS 7 online every day.

**Comment by petester42** [comment]
What I'm saving is that it is possible to do so if you really want to but if you are a beginner and don't know much about swift or Xcode it is not easy. The other methods are way easier and many other libraries have moved to not supporting iOS7 for this very reason. See alamofire for example. 

It's just to reduce the number of issues we get for something that is really not about this library. It's an Xcode issue.

**Comment by liuxuan30** [comment]
What if some people start asking is it possible to support iOS 7?

**Comment by petester42** [comment]
We say we don't officially support it but that it is possible. With maybe a link to apple docs about how to do it.

**Comment by danielgindi** [comment]
I don't believe that this will change the amount of issues on the matter - it may even produce more of them...
The amount of those issues will go down as iOS 7 support gets dropped by Apple and as more people move to iOS 9.

I think maybe we need to declare a specific date and time or a specific version where iOS 7 support will be dropped. When it is dropped - deployment target should also be raised to 8.0.

**Comment by liuxuan30** [comment]
the library deployment target is already at 8.0, I just saw it yesterday.

**Comment by petester42** [comment]
It has to be since iOS 7 does not support dynamic frameworks.

**Comment by petester42** [comment]
I am fine with your suggestion to give it a timeline. After iOS 10 maybe?

**Comment by danielgindi** [comment]
Yes, i'd say the release day of iOS 10 is a great deadline :)
בתאריך יום ה׳, 17 בדצמ׳ 2015 ב-3:36 מאת Pierre-Marc Airoldi <
notifications@github.com>:

**Comment by danielgindi** [comment]
Charts 3.0 release is a good deadline too, and close enough to iOS 10 ;-)
