### ISSUE TITLE
Support for Xamarin.Forms

### ISSUE THREAD

**Issue by Bogidon** [danielgindi/Charts#606]
Hello ios-charts contributers and users!

First, congrats on all the work @PhilJay and @danielgindi put into these libraries. High quality products, both.

I wanted to explore the possibility of porting both libraries to [Xamarin.Forms](https://xamarin.com/forms). Xamarin.Forms is a relatively new C# API made by Xamarin that provides cross-platform sharing of UI code. The supported platforms are iOS, Android and Windows.

While I've witnessed Xamarin.Forms substantially lessen overhead in cross-platform development, the project currently has a relatively scant selection of open-source components. With a common API between the iOS and Android versions, this project seems like it could make Xamarin.Forms much more useful.

**I'm interested in knowing if  anyone has tried using ios-charts in a Xamarin.Forms (or Xamarin.iOS) project.** If so, could you explain how you did this?

The main problem I'm running that Xamarin seems to be [unable to import Swift frameworks](https://developer.xamarin.com/guides/ios/advanced_topics/embedded_frameworks/). For Objective-C frameworks, C# bindings must be written for Xamarin to recognize the classes. I'm unsure whether C# bindings can be written for bridging ObjC headers in a Swift framework.

For MPAndroidChart, the process is much more straightforward as bindings for .JAR files are [well supported](https://developer.xamarin.com/guides/android/advanced_topics/java_integration_overview/binding-a-java-library/binding-a-jar/).

Let me know what you think!

---

#### This issue is dedicated for Xamarin support, any info and discussions on this matter should go here

**Comment by Bogidon** [comment]
And I should add, if anyone wants to help out with this I'd be more than happy to collaborate!

**Comment by danielgindi** [comment]
Looks to me like you should also try to tag here someone with a know-how from the Xamarin team, so that he can offer insights on the progress of Swift support in Xamarin. As I'm guessing you wouldn't want to just rewrite everything for C#...

**Comment by danielgindi** [comment]
#929
