### ISSUE TITLE
Annotations issues and asking for supporting more types of markers

### ISSUE THREAD

**Issue by 4np** [danielgindi/Charts#722]
Hi Daniel,

I have been investigating exactly the same thing as Simon in (closed) ticket #175 and I ended up at the same conclusion (it does not seem to be possible). Observe the following Line Chart (rendered using [HighCharts](http://www.highcharts.com/)) I am looking to replicate using iOS Charts.

![screen shot 2016-01-27 at 5 33 09 pm](https://cloud.githubusercontent.com/assets/1049693/12620325/28ecc516-c51c-11e5-8778-16f60b76e84b.png)

You have a ```ChartMarker``` on the chart on the right that highlights the point in the graph on touch. In addition there are ```Annotations``` in this chart represented by the speech bubbles. Those also support touch events. 

Note that this shown graph has two types of markers: a blue dot and a speech bubble. Right now, in iOS Charts you can only define one _type_ of ChartMarker for a Line Chart, e.g.:

```
        let lineChartView = LineChartView(frame: myFrame)
        ...
        
        // configure marker
        lineChartView.marker = BlueCircleChartMarker()
```

Where the ```BlueCircleChartMarker``` implementation is something like this:

```
import Foundation
import UIKit
import Charts

public class BlueCircleChartMarker: ChartMarker {
    public override var size: CGSize {
        return CGSize(width: 6, height: 6)
    }
    
    public override func draw(context context: CGContext, point: CGPoint) {
        CGContextSaveGState(context)
        
        CGContextSetLineWidth(context, 1.0)
        CGContextSetFillColorWithColor(context, UIColor.blueColor().CGColor)
        CGContextAddArc(context, point.x, point.y, 3.0, 0.0, CGFloat(M_PI * 2.0), 0)
        CGContextFillPath(context)
        
        CGContextRestoreGState(context)
    }
}
```

I have tried using ```highlightValues``` to try to add in annotations like the screen shot above even though that will render with the same ```BlueCircleChartMarker``` (the blue circle) as the on-touch highlight marker, but at least it was worth a try:

```
var highlights = [ChartHighlight]()
// some logic that determine where those three annotations need to show {
highlights.append(ChartHighlight(xIndex: xIndex, dataSetIndex: datasets.count))
// }
lineChartView.highlightValues(highlights)
```

However this approach does not seem to lead to the desired result. The logic in [ChartData.swift](https://github.com/danielgindi/ios-charts/blob/ff94c797fd236f9938274924c8326d9ab7606346/Charts/Classes/Data/Implementations/Standard/ChartData.swift#L435) seems to expect the ```_indicesToHighlight``` to have ```ChartHighlight``` instances for every ```xIndex```, or none.

Am I overlooking something? Is there any way to get Annotations working like this?

Thank you! :)

ps. It would be good, for example, to be able to annotate a particular score in a dataset with a specific marker. I am sure there are use cases where annotating a chart with different marker types are desired. Something like this:

```
let marker = SpeechBubbleChartMarker()
ChartDataEntry(value: someValue, xIndex: someXIndex, annotationMarker: marker)
```

**Comment by liuxuan30** [comment]
let me answer it later. I have did that :)

**Comment by liuxuan30** [comment]
I know you have two types of markers, which does not support yet, and it's nice to put markers into data sets, not chart itself. But what's the other issues? I am not clear what's your problems about ChartHighlight. 

When you touch the screen, it will try get the closest data set (first calculate the closest xIndex), and use this data set combining xIndex to know which data value to be highlighted.

**Comment by liuxuan30** [comment]
how do you want to draw the three markers? I'm sorry but it's a lot of words and I'm lost what's the true problem...
So I once needed to add as much markers as it needs, I did some customizations:
```swift
    internal override func drawMarkers(context context: CGContext)
    {
        if (!drawMarkers)
        {
            return
        }
        
        let myMarkers = (delegate as? MyChartViewDelegate)?.markerInfoArray?(self)
        
        if let markers = BDPMarkers
        {
            for (var i = 0; i < markers.count; i++)
            {
                let marker = markers[i]
                let xIndex = marker.xIndex
                let dataSetIndex = marker.dataSetIndex
                
                if (xIndex <= Int(_deltaX) && xIndex <= Int(_deltaX * _animator.phaseX))
                {
                    let d = _data.getDataSetByIndex(dataSetIndex)
                    let e = d.entryForXIndex(xIndex)
                    if (e == nil)
                    {
                        continue
                    }
                    
                    let highlight = ChartHighlight(xIndex: xIndex, dataSetIndex: dataSetIndex)
                    
                    let pos = getMarkerPosition(entry: e!, highlight: highlight)
                    
                    // check bounds
                    if (!_viewPortHandler.isInBounds(x: pos.x, y: pos.y))
                    {
                        continue
                    }
                    
                    // callbacks to update the content
                    marker.refreshContent(entry: e!, highlight: highlight)
                    
                    let markerSize = marker.size
                    if (pos.y - markerSize.height <= 0.0)
                    {
                        let y = markerSize.height - pos.y
                        marker.draw(context: context, point: CGPoint(x: pos.x, y: pos.y + y))
                    }
                    else
                    {
                        marker.draw(context: context, point: pos)
                    }
                }
            }
        }
    }
```

**Comment by liuxuan30** [comment]
And for your question, drawHighlighted is the line chart renderer func to get called when you call highlightValue triggering a needsDisplay; so in drawHighlighted, it will loop [ChartHighlight], get the data set and entry, check positions, and draw highlight, which I think is not a good place to draw your markers. You have to look at how `drawHighlighted` implemented if you didn't do it before.

**Comment by 4np** [comment]
Thanks for your reply Xuan :) 

Unfortunately ```drawMarkers``` is an internal method of iOS Charts and can only be changed by patching the iOS Charts source directly. It would be acceptable if such functionality could be added by using Swift extensions, but ideally I would like to refrain from patching the source of libraries.

As it clearly does not seem to be possible without patching the source, could we change this issue into a feature request for supporting annotations and multiple marker types?

**Comment by liuxuan30** [comment]
you can file one. or just file a PR to make drawMarkers public :) daniel has made a lot of methods to be public recently.

**Comment by danielgindi** [comment]
In Charts 3.0, markers are now something way more configurable, and protocol-based.

**Comment by infinitybrad** [comment]
> In Charts 3.0, markers are now something way more configurable, and protocol-based.

how to draw two kinds of markers on one line?
I am worried all day long for this problem.
please Show me the example code ~

**Comment by aymenbraham** [comment]
Hello , i want to draw circle only on point selected . like the screenshot 
Any one know how to do it ? plz i need help 
<img width="516" alt="Screenshot 2020-04-15 at 16 27 20" src="https://user-images.githubusercontent.com/35614403/79355745-fd6d1480-7f35-11ea-9c26-889dd3e41905.png">

**Comment by 4np** [comment]
You probably should not ask here, but you could create your own chart marker:

```swift

import UIKit
import Charts

class MyChartMarker: UIView, IMarker {
    /// Get the marker offer before rendering.
    func offsetForDrawing(atPoint: CGPoint) -> CGPoint {
        // We don't use this, but it needs to be in here to conform to IMarker.
        return atPoint
    }

    /// Refresh the marker's properties before rendering.
    func refreshContent(entry: ChartDataEntry, highlight: Highlight) {
        ...
    }
    
    /// Render the marker.
    func draw(context: CGContext, point: CGPoint) {
        context.saveGState()
        
        defer {
            context.restoreGState()
        }
        
        ...
    }
}
```
