### ISSUE TITLE
The label value position with the same yAxis and different value.

### ISSUE THREAD

**Issue by pisces3ng** [danielgindi/Charts#724]
Hi Daniel,
I have done my Bar Chart as below with using your source library.
<img width="602" alt="screen shot 2016-01-29 at 17 29 48" src="https://cloud.githubusercontent.com/assets/16677378/12672015/57f970f0-c6ae-11e5-8a5b-dcc0a5d40245.png">

I would like to ask, it is possible can make same like my prototype as below?
The percentage's value is with the Bar Chart, but it show the label on the bar. I would like the the percentage label same line (yAxis) together and the position is above the bar as the mention as below.
<img width="249" alt="stackbar" src="https://cloud.githubusercontent.com/assets/16677378/12671738/aa98a8f0-c6ac-11e5-9c2e-ff08e1851b53.png">

Thank you very much!

**Comment by liuxuan30** [comment]
For your question, I think you need to override drawValues to display the sum value. The chart should calculated that for you, but it just does not support draw sum value. @danielgindi this feature is being asked a few times.

**Comment by nthegedus** [comment]
Hi guys @liuxuan30  @danielgindi any news about that? If there isn't, there is any tip to override drawValues?

**Comment by nthegedus** [comment]
Hi guys.

I've overridden drawValues, but I got some problem. Some values are being cut.
Any ideia, how to fix it?

![captura de tela 2016-09-05 as 17 18 10](https://cloud.githubusercontent.com/assets/1063383/18256561/4b0cba6e-738d-11e6-8dda-44cd2988625f.png)

**Comment by liuxuan30** [comment]
'being cut' seems you override something would leads to not enough `contentRect`? Have you touched anything?
@danielgindi this is not resolved in v3 right?
