### ISSUE TITLE
ChartEasingOption properties (animate)

### ISSUE THREAD

**Issue by siideffect** [danielgindi/Charts#726]
Hello, i wanted to report some bug about the charteasingoptions, i am on Xcode 7.2
Some of the charteasingoption parameters make the app crash, others not. So , considering chartView is a BarChartView object

    @IBOutlet weak var chartView: BarChartView!

when i use the animate property with these particular parameters:

chartView.animate(xAxisDuration: 2, yAxisDuration: 2, easingOption: ChartEasingOption.EaseInOutBack)

chartView.animate(xAxisDuration: 2, yAxisDuration: 2, easingOption: ChartEasingOption.EaseInOutElastic)

chartView.animate(xAxisDuration: 2, yAxisDuration: 2, easingOption: ChartEasingOption.EaseOutBack)

chartView.animate(xAxisDuration: 2, yAxisDuration: 2, easingOption: ChartEasingOption.EaseOutElastic)

my app crashes at beginning
Thanks for the attention (the library is awesome, but is not easy for me understand android documentation, some methods don't offer any documentation, even if i read "Currently there's no need for documentation for the iOS version, as the API is 95% the same as on Android." i am not really agree with this :) )

**Comment by danielgindi** [comment]
This is not about the documentation, but about a crash...
These specific animation curves go over the edge, and it crashes on an out-of-bounds. We need to just avoid those out-of-bounds.
