### ISSUE TITLE
Stacked bar chart with different number of rects

### ISSUE THREAD

**Issue by zaplitny** [danielgindi/Charts#744]
I have daily bar chart displaying 2 bars with different number of rects inside, e.g
- yellow, red, green on bar 1
- red, green on bar 2

As I understand there's no way to do it right now. I tried to collect all colors into single array and set it in dataset but it gets only first colors from the array:
`CGContextSetFillColorWithColor(context, dataSet.colorAt(k).CGColor)`
where _k_ is index of current bar's entry

I did quick local fix - pass array of all colors and add colorIndex increment in BarChartRenderer but it doesn't look good. What about adding _colors_ property to BarChartDataEntry and if it's set use it instead?

**Comment by danielgindi** [comment]
I don't understand your problem. Look at the stacked bar demo.
