### ISSUE TITLE
Support custom formatting of chart labels

### ISSUE THREAD

**Issue by franqueli** [danielgindi/Charts#750]
We have a use case where we need some custom logic when displaying a label on a bar chart. A zero value would at times need to be labeled N/A. I don't think the current interface makes it easy to support this. 

I've implemented this functionality modeled after MPAndroidChart's ValueFormatter interface. 
Changes can be viewed in this git repo. 
https://github.com/franqueli/ios-charts/tree/ValueFormatterProtocol

**Comment by danielgindi** [comment]
Implemented in Charts 3.0 (v3 branch)
