### ISSUE TITLE
If data is not set (e.g. public var noDataText = "No chart data available.")

### ISSUE THREAD

**Issue by sabiland** [danielgindi/Charts#756]
If data is not set (e.g. public var noDataText = "No chart data available."), graph is not re-drawn after rotating device. That means "No chart data available." text is stretched /squeezed.

**Comment by liuxuan30** [comment]
in controller code, use following (though deprecated in iOS 8.0)
```Objective-C
-(void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration {
    [_chartView setNeedsDisplay];
}
```
will redraw the chart can solve the issue.
ChartDemo does not provide this support yet.

**Comment by danielgindi** [comment]
Does this mean that the `UIView` does not `setNeedsDisplay` when changing frame? Looks like a given that the OS should do that
