### ISSUE TITLE
How to remove these white/gray lines

### ISSUE THREAD

**Issue by Luke47** [danielgindi/Charts#758]
I can not figure out, what produces this "frames" around my bars. How can I disable them?

Thank you! :)

![screen shot 2016-02-16 at 19 40 11](https://cloud.githubusercontent.com/assets/5190003/13086832/4d3e986c-d4e5-11e5-806b-f9572714d41c.png)

**Comment by liuxuan30** [comment]
did you draw gird line or axis line? Check them out.
```swift
public var drawGridLinesEnabled = true
public var drawAxisLineEnabled = true
```

**Comment by Luke47** [comment]
@liuxuan30 Thank you for your reply!
I have disabled the axis completely:

`chartView.leftAxis.enabled = false
chartView.rightAxis.enabled = false`

I've added your code as well, but nothing changed. Guess it's not something related with the axis? Maybe some property of the bars? I also tried to disabled the shadows, but that did also not help.

**Comment by liuxuan30** [comment]
I don't remember bar chart has such bounding rect... it's like grid lines.
Have you tried with charts demo?

**Comment by danielgindi** [comment]
You should disable `drawGridLinesEnabled` on both xAxis and yAxis, and `drawGridBackgroundEnabled` on the chart itself.

**Comment by narekyan** [comment]
@danielgindi 
what about these lines
seems there is small padding between every LineChartDataSets
I have LineChartData with multiple LineChartDataSets
and every LineChartDataSet has two ChartDataEntry

I didnt find the other way to draw this
![simulator screen shot 14 feb 2017 17 27 46](https://cloud.githubusercontent.com/assets/12446012/22930781/6d0a5dba-f2db-11e6-84ad-7980f163630e.png)

**Comment by liuxuan30** [comment]
those small lines seems your pixel is not aligned. Check from there.

**Comment by narekyan** [comment]
but I have that lines even If I have small amount of data
and simulator is in 100% scale
![simulator screen shot 16 feb 2017 10 34 02](https://cloud.githubusercontent.com/assets/12446012/23010181/72e54dea-f433-11e6-9d49-f40a5d3a7320.png)

**Comment by liuxuan30** [comment]
sorry, but it seems irrelevant to this topic. and I don't quite understand what's the issue then.
