### ISSUE TITLE
Pie chart Y values overlap

### ISSUE THREAD

**Issue by cichys** [danielgindi/Charts#779]
Hi
In pie chart is it possible to hide Y labels only for values that are less than 2% to prevent text overlap?

![pie](https://cloud.githubusercontent.com/assets/1255483/13356751/438c207c-dca7-11e5-83f9-837144539898.png)

Thanks

**Comment by KerryJava** [comment]
#90 maybe this issue has the same problem.

**Comment by wjacker** [comment]
@cichys maybe you can try this pr: #869 :)
