### ISSUE TITLE
Being OSX too, should we rename repo to just `Charts`?

### ISSUE THREAD

**Issue by danielgindi** [danielgindi/Charts#787]
Your thoughts please :-)

**Comment by petester42** [comment]
Sounds good to me. Makes sense.

**Comment by liuxuan30** [comment]
will it be too short to pronounce? lol
It coms across my mind that there are auto layout frameworks, and often have a prefix, sounds fancy

**Comment by pixelspark** [comment]
Hm, just 'Charts' seems too generic. Perhaps there is a way to make this more Apple-ish, e.g. 'SwiftCharts' or 'ChartCore' or something like that.

**Comment by danielgindi** [comment]
Well, I don't want to go the "CorePlot" direction ;-)

**Comment by liuxuan30** [comment]
just curious, is iCharts available? iPhone, iMac, iCharts

**Comment by danielgindi** [comment]
Seems like iCharts is not used anywhere...
So we could choose either Charts or iCharts? Is there a voting system here? :-)

@petester42 how will a repo rename affect Pods? Can they redirect?

**Comment by petester42** [comment]
According to this it should be redirected https://github.com/blog/1508-repository-redirects-are-here but we should also update the pod when the change is made.

**Comment by petester42** [comment]
I don't really like iCharts if we want to go with something more appley then Charts would align more with their current naming style.

**Comment by danielgindi** [comment]
I also do not like iCharts much, seems childish in my eyes for some reason

**Comment by liuxuan30** [comment]
:laughing:

**Comment by pixelspark** [comment]
Well how about "MyCharts2000 XP"? :grin:

**Comment by danielgindi** [comment]
Lol

**Comment by danielgindi** [comment]
Any other suggestions than Charts? 
Charts is also the easiest since internally it's already called that way, and in Pods too...

**Comment by sochalewski** [comment]
Charts sounds perfect to me. Easy and finally exactly the same as pod name.

**Comment by danielgindi** [comment]
Okay, I see no objections here... The name will change with next release. :-)

**Comment by wjacker** [comment]
'Charts' sounds good 😄

**Comment by gianues** [comment]
if rumours are true and **OS X** will be renamed to **macOS** to match the **iOS**, **watchOS**, **tvOS** pattern, **ios-charts** could be renamed to **appleos-charts**

**Comment by danielgindi** [comment]
Okay we've just been renamed! I'm working on the Carthage compilation - which is unstable - and there's a new release.
