### ISSUE TITLE
How to display Negative X-Axis on LineChart

### ISSUE THREAD

**Issue by Monika-Tapadiya** [danielgindi/Charts#797]
Hello,

I am able to show positive X, Y and negative Y axis on LineChart but I am unable to find any property of ChartXAxis to show negative values on negative X Axis.I want to show all Quadrants on graph.Please help me for this.

Thanks

**Comment by liuxuan30** [comment]
currently, x axis is index based, so it starts from 0. a negative value is just a string for x axis.

**Comment by liuxuan30** [comment]
but seems support four Quadrants smells like a feature? adding tags

**Comment by Monika-Tapadiya** [comment]
Ok thanks for the reply :)

**Comment by kkpan11** [comment]
Sorry, if I want to modify that to support the negative X-Axis on the chart, just let it can be scrolled back to negative value. How can I achieve that, or which part of the classes I can find the information? Any ideas would be appreciated.

Thanks a lot.

**Comment by liuxuan30** [comment]
this is an old topic. You should be able to have a netagive X-Axis, as in 3.0, the x values and labels can be different, using the valueFormatter. e.g. x value: [0,1,2,3,4], but you can format to [-4,-3,-2,-1,0]
