### ISSUE TITLE
Is there any possibility for grouping x axis values in line chart?

### ISSUE THREAD

**Issue by rajesh055** [danielgindi/Charts#798]
![screen shot 2016-03-04 at 1 19 26 pm](https://cloud.githubusercontent.com/assets/15665704/13522971/8c58b75e-e218-11e5-8718-11678bf9a6b4.png)

This is my requirement in iPhone and iPad, I've got it upto plotting the values based on weeks as in,

![trials](https://cloud.githubusercontent.com/assets/15665704/13522984/a82bc2dc-e218-11e5-88f1-962d981ceb3a.png)

I've included iOS charts FM in my objective - c code, I've been searching for a long time now to group axis values without any luck. I just want a confirmation, if there is a possibility by default or should I customise the chart's area? I 'should' say this, this is one great framework, thank you for the effort!

**Comment by liuxuan30** [comment]
are you saying you want to groups 'week #1' for every month? If so, you can wirte your own logic to get the sum values for each week, and put them into one single data set?

**Comment by rajesh055** [comment]
No no sorry for not being clear, of course I can group the values, I just want to make sure if there is any options to include a multi-line label? to display the months as in the first image. I referred to one of the issues and now I've managed to include a lengthy label to show the month in the second line of the xaxis label, so is there any other way to do this?

**Comment by liuxuan30** [comment]
I see. It does not support such groups. You can try customize it yourself. take a look at x axis renderer code. Should not be hard for you

**Comment by rajesh055** [comment]
That's great, I'll try to customise the part myself. Thank you once again, for the suggestion.

**Comment by danielgindi** [comment]
You have several ways to achieve this. You can do this with another view below the chart, taking position data from the transformer. Or you can actually print another line of labels, or add `\n` new lines to your labels.
