### ISSUE TITLE
Could not cast value of type 'Charts.BarChartData' (0x10bbd31f0) to 'MYPROJ.BarChartData' (0x10aeed700).

### ISSUE THREAD

**Issue by indrajitv** [danielgindi/Charts#825]
please i want urgent help

**Comment by indrajitv** [comment]
internal override func calcMinMax()
    {
        super.calcMinMax()
        
        if (_data === nil)
        {
            return
        }
        
        let barData = _data as! BarChartData
        
        //HERE EXCEPTION THROWS
        _deltaX += 0.5
        
        // extend xDelta to make space for multiple datasets (if ther are one)
        _deltaX *= CGFloat(_data.dataSetCount)
        
        let groupSpace = barData.groupSpace
        _deltaX += CGFloat(barData.xValCount) * groupSpace
        _chartXMax = Double(_deltaX) - _chartXMin
    }

**Comment by liuxuan30** [comment]
would you check ` let barData = _data as! BarChartData`? 
the error message is saying the casting on BarChartData failed, but I have no idea yet;

**Comment by danielgindi** [comment]
You are importing the framework twice. 
The first time as an actual framework, the second as source compiled as part of your project.

**Comment by partyspy** [comment]
In "Identity Inspector", the custom class' **module** related to your chart view in IB might not be rightly set.
In my situation, the module part is somehow automatically set to _MyProjectName_ instead of _Charts_, which caused the same issue as indrajtv encountered.
