### ISSUE TITLE
Double tap to zoom into the chart should center to Point that was tapped  

### ISSUE THREAD

**Issue by MartinPajak** [danielgindi/Charts#83]
When tapping to zoom into a chart (especially in deeper zoom scales), the chart zooms in, but moves the tapped values outside of the view. It would be more user friendly to take care of the tapped position and center to the value range that was tapped.

**Comment by danielgindi** [comment]
We may implement this as an opt-in feature

**Comment by marcantoinefortier** [comment]
:+1: For this feature.

**Comment by danielgindi** [comment]
This is now fixed
