### ISSUE TITLE
Piechart with vertical legend

### ISSUE THREAD

**Issue by evixar** [danielgindi/Charts#840]
Hi,

I'm trying to display the legend of a pie chart vertically but I can't find any option to do it.

It looks like Google Analytics app uses MPAndroidChart (it looks very familiar) and their legend below a pie chart is shown vertically.

Is there anyway to do this ?

Regards

**Comment by liuxuan30** [comment]
public enum ChartLegendPosition: Int
    {
        case RightOfChart
        case RightOfChartCenter
        case RightOfChartInside
        case LeftOfChart
        case LeftOfChartCenter
        case LeftOfChartInside
        case BelowChartLeft
        case BelowChartRight
        case BelowChartCenter
        case AboveChartLeft
        case AboveChartRight
        case AboveChartCenter
        case PiechartCenter
    }
there is no one good to you? I don't know what you mean vertically

**Comment by Tj3n** [comment]
What he meant is the same like the `RightOfChart ` but in below (Vertical not Horizontal), im also looking for a way to do this but doesnt look really promise

**Comment by liuxuan30** [comment]
if you want different position, you can change on your own. Or you can also make it a good implementation and file a PR :)

**Comment by danielgindi** [comment]
With the latest changes on `master`, you can do this by setting it to `Center/Center`, `orientation = Horizontal`, and `wordWrapEnabled = true`
