### ISSUE TITLE
Overlapping bar chart

### ISSUE THREAD

**Issue by jemcelroy** [danielgindi/Charts#857]
Is it possible to create an overlapping bar chart? I took a look at the demo, but didn't see that as an option. Can the grouped bar chart be altered currently to overlap?

**Comment by liuxuan30** [comment]
take a look at how barSpace and groupSpace impact the bar rect. You may find a way to modify the barRect.Not sure if you use a negative value for barSpace and groupSpace, how much work you need.

**Comment by danielgindi** [comment]
If by "overlapping" you mean something like this:
![image 49](https://cloud.githubusercontent.com/assets/366926/13877269/53c3d86a-ed12-11e5-9579-6af25b9abbcb.png)

Or this:
![overlapbar](https://cloud.githubusercontent.com/assets/366926/13877271/56b322b0-ed12-11e5-895d-66dd3ac2fedc.png)


Then I guess it would be pretty easy to implement. Something in the area of `barSpace` etc- to allow playing with offsets too - on a dataset basis.
The more complicated thing could be to deal with grouped bars, but I'm not convinced that they will actually be offended by this change...

**Comment by liuxuan30** [comment]
it seems a nice feature though :)

**Comment by jemcelroy** [comment]
@danielgindi The first example is what I was looking for. After experimenting with negative values in the bar spacing (and managing to get something like the second example) I ended up throwing together a subclass of BarChartRenderer to change bar widths and positions to get something like the first example. I'd still love to see this as a built-in option, though.

**Comment by danielgindi** [comment]
Implemented in Charts 3.0 (v3 branch), you can now set the barWidth as a percentage. :-)

**Comment by jemcelroy** [comment]
@danielgindi can you help me out with how setting barWidth can provide the effect in the first example you posted in March? It looks like barWidth is only a property of BarChartData, when I want to set the relative width of a BarChartDataSet.

**Comment by liuxuan30** [comment]
@jemcelroy can you look at `open func groupBars(fromX: Double, groupSpace: Double, barSpace: Double)` to see if it can achieve by changing barSpace, groupSpace etc?
I'm curious as well, but `barWidth` is on `BarChartData` like you said.

**Comment by jemcelroy** [comment]
@liuxuan30 I have only been able to achieve something like the second example using the groupBars function. It seems impossible to achieve something like in the first example without being able to set the width of a BarChartDataSet.

**Comment by liuxuan30** [comment]
OK, it seems like it's not supported? need @danielgindi confirm

**Comment by furszy** [comment]
Hello, I was looking for this feature too, seems that there is no visible method to overlap bars of the same category.

**Comment by jemcelroy** [comment]
Still would love to see this as a feature. Unsure as to why this was closed.
