### ISSUE TITLE
Bar chart missing y axis label

### ISSUE THREAD

**Issue by jemcelroy** [danielgindi/Charts#858]
This bar chart does not seem to be calculating the correct number of y axis labels. The largest value on the y axis is about 1.4 million, so the top line should indicate 1M. However, it is only showing 5 labels when it should be 6.

![screen shot 2016-03-17 at 4 12 42 pm](https://cloud.githubusercontent.com/assets/17460636/13859762/5b6f31a2-ec5b-11e5-8c33-39bea958b194.png)

This is my data set: [1186645.1996, 487553.6624, 1184759.34, 1381902.321, 419279.6614, 920688.6186, 1159724.5976, 1297496.6188, 570605.956, 962006.3724, 570605.956, -4171430.6358]

**Comment by liuxuan30** [comment]
could you try debug computeAxis() in y axis renderer, to see how it calculate the yMin, yMax and the range?

**Comment by danielgindi** [comment]
No response for a few months now...
