### ISSUE TITLE
ChartLegend yEntrySpace not work

### ISSUE THREAD

**Issue by tcper** [danielgindi/Charts#886]
In ChartsDemo project, PieChartViewController
 I set the _chartView.legend.yEntrySpace = 30.f;
It seems no change, is there some tricks to make yEntrySpace work?

**Comment by liuxuan30** [comment]
```
neededHeight = labelLineHeight * CGFloat(calculatedLineSizes.count) + yEntrySpace * CGFloat(calculatedLineSizes.count == 0 ? 0 : (calculatedLineSizes.count - 1))
```
and later used in `calculateOffsets()`: 
```
offsetBottom += min(_legend.neededHeight + yOffset, _viewPortHandler.chartHeight * _legend.maxSizePercent)
```
So it's working I think, just not what you think? You can read the code.

**Comment by danielgindi** [comment]
Yes, it is ignore, I guess we forgot that way back when changing a lot about the legend. I'll try to make it work again
