### ISSUE TITLE
Plotting Realm data in Swift. RLMResults not available

### ISSUE THREAD

**Issue by bb-git** [danielgindi/Charts#898]
I get the following error when trying to use the constructor:
Cannot convert value of 'Results<()>' to expected argument type 'RLMResults?'

```
let historyItems = realm.objects(History)     
let dataSet = RealmLineDataSet(results: historyItems, yValueField: "row1", xIndexField: "row2", label: nil)
```

Has anybody managed this? I can't find a solution

**Comment by danielgindi** [comment]
Due to some limitations to Realm's implementation, we couldn't support the Swift `Results` class, but only the `RLMResults`. With the latest version I have to check- they may have fixed that and maybe we can too.

**Comment by StevenMasini** [comment]
Do we have a solution or a work-around for this issue ?

**Comment by danielgindi** [comment]
Not at the moment.

**Comment by AndyDunn** [comment]
Does this effectively mean that Realm Charts can't currently be used with Swift? I'm having the same issue and have converted everything else to work but this one line of code.

**Comment by bb-git** [comment]
You can use it using Realm for objective-c. Realm for objective-c will also work in Swift. I didn’t do it, had to many adaptions anyway.

**Comment by AndyDunn** [comment]
@bb-git I'm thinking of just using regular Charts for Swift (no Realm) and converting my existing Realm dataset into normal arrays for the data. That seems like the option with the least amount of effort.

**Comment by StevenMasini** [comment]
Yes it's what I've done too.

**Comment by bb-git** [comment]
I created the datasets directly iterating over the results, without using arrays

**Comment by danielgindi** [comment]
https://github.com/realm/realm-cocoa/issues/4232
