### ISSUE TITLE
Can we show Pie chart Value out of slice instead showing inside the slice ?

### ISSUE THREAD

**Issue by BurhanMughal** [danielgindi/Charts#90]
Self explanatory question.

Can we show slice values of pie chart out side the slice and not in the slice ?
Thanks.

**Comment by danielgindi** [comment]
I think we'll be implementing that soon

**Comment by BurhanMughal** [comment]
Ok thanks.

**Comment by krahabb** [comment]
I've written an algorithm to spread out labels on pie charts in a rather reasonable layout. It works by pushing out labels from each other but still trying to keep them aligned to their respective slice. I could push the feature in few days if needed (it's actually working on top of the original algorithm so I would prefer to add a property in 'somewhere' (haven't yet think about it) to control the application of the algorithm before pushing to master)

**Comment by yuercl** [comment]
@danielgindi ,  does this feature have supported ? i check document , but not found .

**Comment by kexoth** [comment]
@danielgindi  :+1:  for this feature.

**Comment by NSri** [comment]
@danielgindi :+1:  When can we expect this feature?

**Comment by wjacker** [comment]
@BurhanMughal @yuercl  @kexoth @NSri  maybe you can try this pr:  #869 :)

**Comment by danielgindi** [comment]
This is now implemented in `master`
