### ISSUE TITLE
Real number x axis line for BarChartView

### ISSUE THREAD

**Issue by amitvyawahare** [danielgindi/Charts#901]
Do you support bar graphs with a real number x axis line. All I have found is support for "labeled/NSObject" bars, but I would like to be able to give a bar a double value and have it plotted on a real number line, same as y axis. In a similar vein, is there a way for me to plot a ChartLimitLine on the xaxis at a real number location rather than an index when using the bar graph.

If I want to plot price (X-Axis) and quantity (Y-Axis)
        price = [1, 2, 5]
        quantity = [1.0, 2.0, 5.0]

I am getting following graph
<img width="374" alt="screen shot 2016-03-30 at 6 26 56 pm" src="https://cloud.githubusercontent.com/assets/635098/14159786/eba7f37c-f6a5-11e5-9833-58f2e32b284e.png">

But I want something like this
<img width="375" alt="screen shot 2016-03-30 at 6 28 51 pm" src="https://cloud.githubusercontent.com/assets/635098/14159788/f670a790-f6a5-11e5-8b91-dd45f76376df.png">

I am using the correct Chart Type? I am using BarChartView.

**Comment by Aft3rmathpwnz** [comment]
https://github.com/danielgindi/ios-charts/issues/860

**Comment by amitvyawahare** [comment]
So basically there is no way to do this, I have to insert some zero quantity data on the x axis. What about ChartLimitLine on the x axis at a real number's location rather than an index when using the bar graph.

**Comment by petester42** [comment]
NSObject can be anything even a float value. Try using an NSNumber to achieve what you are looking for. But maybe I am misunderstanding your question.

**Comment by liuxuan30** [comment]
@petester42 seems he is talking about the float x axis style. 
Currently we don't support this, but some peole are working on it. You can insert the intermediate x values but not insert entry for it, and you can get what you want.

e.g. price = [1, 2, 5] -> [1,2,3,4,5]
quantity = [1.0, 2.0, 5.0]  -> [1.0 for xIndex 0, 2.0 for 1, 5.0 for 4]

**Comment by surayashivji** [comment]
Are there any updates on this?
