### ISSUE TITLE
Add Lines between labels

### ISSUE THREAD

**Issue by marcomonanto** [danielgindi/Charts#902]
I want to create a chart like this one, with lines between the labels and the last label without the line, tried for like 4 hours to create the lines but with no success...

can you help me?

![screen shot 2016-03-31 at 09 43 39](https://cloud.githubusercontent.com/assets/17854952/14171322/3f23f8fa-f72a-11e5-8ed8-49f27d4034ce.png)

**Comment by marcomonanto** [comment]
Already got the lines with limits, how can i change the space between the stackedlabels?

**Comment by liuxuan30** [comment]
what you mean stackedlabels? take a look at the bar chart renderer code.
