### ISSUE TITLE
Feature request :) blur shadow for line chart

### ISSUE THREAD

**Issue by YHSX88** [danielgindi/Charts#903]
I just thought it will be super great if the line chart can have blur shadow.
I'm so newbie with iOS so I do not know how to do it but pretty sure it will be piece of a cake for some of you :) 

My thought after I saw this :)
https://dribbble.com/shots/1917999-iOS-Data-Exploration?list=shots&sort=popular&timeframe=month&offset=109

**Comment by liuxuan30** [comment]
wow it's fancy. is this just a design or open source or private code?

**Comment by YHSX88** [comment]
I really don't know but i saw major diff is the blur shadow on the line, evrything else is just colors at least to me :)

**Comment by danielgindi** [comment]
It's a design prototype. Usually done customly for specific data, with a CALayer with shadow.
It would be very to move our code to layer, and not on our plate right now.
