### ISSUE TITLE
Do pod install with cocoapods

### ISSUE THREAD

**Issue by LvJianfeng** [danielgindi/Charts#904]
![image](https://cloud.githubusercontent.com/assets/9586013/14199169/a8bbe4b8-f814-11e5-9620-bd1dd5e00c1d.png)

**Comment by danielgindi** [comment]
Okay. People. Please READ the README. You have to update to Xcode 7.3.

**Comment by LvJianfeng** [comment]
oh no, I didn't upgrade, because my iphone, but thank you and thank you for your sharing.

**Comment by danielgindi** [comment]
The iPhone does not orevent you from updating your Xcode version...
Have fun using Charts!

**Comment by LvJianfeng** [comment]
OKay, Thank you.
