### ISSUE TITLE
Bar chart starting point non zero

### ISSUE THREAD

**Issue by keyv** [danielgindi/Charts#905]
Can I set the initial point different from zero of stacked multiple bar chart?
Want to make smth like [this (Waterfall chart)](https://camo.githubusercontent.com/8478b196ab38754c1a17fb68b618a468ef4b9d04/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3733363138352f3736313834392f36656265366563302d653764632d313165322d393631302d3861336665366632373264342e706e67) with optional negative Y values

**Comment by charlesa101** [comment]
Yeah i am having this issue too... non zero starting point in the API

@keyv any solution yet ?

**Comment by danielgindi** [comment]
We are working on it, but on `master` you can already set `xAxis.axixMinValue`

**Comment by danielgindi** [comment]
Though `xAxis.axisMaxValue` will not work yet

**Comment by charlesa101** [comment]
Thanks @danielgindi: i have a graph shown below i want it all to start at the min-value i.e -30 on the y-axis not 0 will that fix it ?

<img width="542" alt="screen shot 2016-04-01 at 10 04 28 am" src="https://cloud.githubusercontent.com/assets/445532/14210986/3e70c34e-f7f1-11e5-9e19-a4841ddc795e.png">

**Comment by ergihervi** [comment]
let leftAxis = yourGraphView.leftAxis
 leftAxis.axisMinValue = -30

**Comment by danielgindi** [comment]
I though that you meant the X axis. On the Y axis as well you can set axisMinValue to whatever minimum you want.

**By default**, though, the chart will auto-calculate the min/max of your values, and show negative values **correctly**.
