### ISSUE TITLE
noDataTextDescription not display

### ISSUE THREAD

**Issue by dzungpv** [danielgindi/Charts#906]
I tested latest sample, when no data fill, the text not display.

**Comment by danielgindi** [comment]
This will show only when `data` is nil. It is meant for when you put your first chart view - and want to see what happens...

**Comment by dzungpv** [comment]
It not like in Android API, which show the message when data is empty.
I like that feature because in one of my app user must wait some hours before app collect data and display.

**Comment by danielgindi** [comment]
Look closer in Android's code:
`if (mData == null) {`

**Comment by dzungpv** [comment]
But in Android it show the message and iOS not, i mean null or empty data. That why i open this issues.

**Comment by petester42** [comment]
You can set data to nil when your data point count is equal to 0

**Comment by dzungpv** [comment]
Thank @petester42 It ok now when i set data to nil.
