### ISSUE TITLE
Symbol not Found on Xcode 7.3

### ISSUE THREAD

**Issue by nevillco** [danielgindi/Charts#907]
I just updated to Xcode 7.3, and now whenever I attempt to run my project on my device (iOS 9.3), it crashes immediately with the following message:
`dyld: Symbol not found: __TMPdSQ
  Referenced from: /private/var/containers/Bundle/Application/EF486FEC-9BC6-47C8-93F1-325BDD2657D9/ClockIn.app/Frameworks/Charts.framework/Charts
  Expected in: /private/var/containers/Bundle/Application/EF486FEC-9BC6-47C8-93F1-325BDD2657D9/ClockIn.app/Frameworks/libswiftCore.dylib
 in /private/var/containers/Bundle/Application/EF486FEC-9BC6-47C8-93F1-325BDD2657D9/ClockIn.app/Frameworks/Charts.framework/Charts`

Edit: I should add, I've tried cleaning/rebuilding, clearing the build folder, and deleting derived data.

**Comment by danielgindi** [comment]
Maybe try a clean build?

**Comment by nevillco** [comment]
I did, to no success. Also deleted derived data.

**Comment by danielgindi** [comment]
Are you using Carthage?

**Comment by nevillco** [comment]
No, I manually installed the dependency. I did just remove it and go with a Cocoapods install, which is now working, so I'll close this issue. Thanks
