### ISSUE TITLE
Unable to display empty bars in barcharts

### ISSUE THREAD

**Issue by mavencode01** [danielgindi/Charts#911]
Failed to draw bar at specify xIndex when there is no data in between.

    //Initialise all the x-axis so each bar is drawn on each point if exist  <-- doesn't work!
    for (int i = 0; i < biodata.count; i++){
        NSInteger val = ...
        [_xVals addObject:@(val)];
    }

    // draw the bar at a particular xIdx and with gaps e.g |...||.....||||.....|
    for (int i = 0; i < biodata.count; i++)
    {
        float y = ... 
        NSInteger xIdx = ....
        BarChartDataEntry *entry = [[BarChartDataEntry alloc] initWithValue:val xIndex:xIdx];     
        [_yAxisVals addObject:entry];
    }
    ....

**Comment by mavencode01** [comment]
So basically, if you are drawing a bar on the x-Axis, it should calculate the space/gaps based on the x-axis maximum or chart width before drawing the bar at that point.

    ....................................

    ...I............II...........I......

it doesn't seems to do this, instead it draws the bar to fill the entire width and recalculate the bar widths when new points is added to the dataset.

**Comment by danielgindi** [comment]
I don't understand what the problem is here.

**Comment by danielgindi** [comment]
You don't have to add values for each xIndex.

**Comment by mavencode01** [comment]
@danielgindi I've a requirement to display bar at a particular x-axis, for example:

I've got an x-axis in the range of `1-100`

What I want to do is for each update, draw a bar at a particular point once data is available and putting spaces between those points with no data:

    .......||..........|.............
    0                              100

**Comment by danielgindi** [comment]
So where is the problem?...

**Comment by liuxuan30** [comment]
Are you looking for ignoring bars at specific index?
```swift
for (int i = 0; i < biodata.count; i++)
{
    float y = ... 
    NSInteger xIdx = ....
    if ([self hasDataAt:xIndx]) {
        BarChartDataEntry *entry = [[BarChartDataEntry alloc] initWithValue:val xIndex:xIdx];     
        [_yAxisVals addObject:entry];
    }
}
```
should do the job. `[self hasDataAt:xIndx]` is what you have to implement
there are `groupSpace` and `barSpace` to control the space between bars and bar groups.

**Comment by liuxuan30** [comment]
I think this can be closed. If it's a bug you think, just reopen
