### ISSUE TITLE
Line chart yAxis data interval

### ISSUE THREAD

**Issue by ergihervi** [danielgindi/Charts#912]
Hi! I have a problem with the 'y' data interval. Before to update, the intervals where the same: 

<img width="285" alt="captura de pantalla 2016-04-02 a las 7 33 24 p m" src="https://cloud.githubusercontent.com/assets/14208368/14230201/c46c4544-f90a-11e5-8063-092a8944c4c9.png"> 

0+3 = 3
3+3 = 6
6+3 = 9
9+3 = 12 
12+3 = 15 

And now, the intervals are different: 
<img width="342" alt="captura de pantalla 2016-04-02 a las 6 28 21 p m" src="https://cloud.githubusercontent.com/assets/14208368/14230209/f603ad2c-f90a-11e5-9df9-77144cd030c4.png">

0+3 = 3
3+4 = 7
7+3 = 10
10+4 = 14 
14+3 = 17

Also, it used to have a little space between the last value and the top of the graph view. 

How could I fix this? here is my code from the left axis: 

let leftAxis = graphView.leftAxis
leftAxis.drawGridLinesEnabled = false
leftAxis.labelFont = UIFont.systemFontOfSize(10)
leftAxis.valueFormatter = yFormatter
leftAxis.forceLabelsEnabled = true
leftAxis.axisMinValue = 0

**Comment by danielgindi** [comment]
Seems like the range of the data changed, or the zoom, or maybe the size of the device you're testing?

**Comment by ergihervi** [comment]
No, is the same data, same phone, same graph view size (no zoom) :S

**Comment by liuxuan30** [comment]
how about the formatter? You are using a percent style. the interval should not change at all. change to decimal style to see how the number is.

**Comment by liuxuan30** [comment]
@ergihervi for the space, because the y axis range defines the contentRect, so yMax may < max data. It depends. There is a small algorithm calcuating the range in `computeAxisValues()` of y axis renderer.

**Comment by ergihervi** [comment]
@liuxuan30  Thanks for your answer! I updated to swift 2.2 and the last 'Charts' update. I didn't set the extra top off set before, but it looks that I have to do it now in order to have a little space from the last yValue to the top.

I printed the left axis entries, and this was the result:  [0.0, 0.033846153846153845, 0.067692307692307691, 0.10153846153846154, 0.13538461538461538, 0.16923076923076924]. I guess the size of the number is the problem, this probably could be fixed in the algorithm that calculates this values by (maybe) formatting the number to "0.03"?

**Comment by liuxuan30** [comment]
not really, while calculating the number is the number, no need to round (even you round, there's still the same issue). It's the value formatter that causes this, as you see 0.0338 -> 3% and 0.067 -> 7%, 0.101->  10%. You can write your own formatter to solve this.

I'm going close this, since it's releated to formatter.

**Comment by liuxuan30** [comment]
@danielgindi Actually, what you think we limit the decimals to some digits? Like adding a property to specify how many digits we want to keep? So we only keep them. e.g. if we specify maxDigits = 2, 0.0338  -> 0.03, 0.067 -> 0.06, we don't do round at all. just abandon the addtional portion directly.
