### ISSUE TITLE
start animation at minimum visible y-Position

### ISSUE THREAD

**Issue by bb-git** [danielgindi/Charts#914]
The animations seem always to start at zero. First it looks like there is happening nothing and then the chart is flying in very fast (my y range is from 65 to 69). It would look much nicer if the animation would start at the axisMinimum  and grow from there.

**Comment by danielgindi** [comment]
@PhilJay I think maybe we should do same range calculation for bar-based charts like we do in the line renderer? (minx/maxx)

**Comment by bb-git** [comment]
I have this problem with line charts.

**Comment by danielgindi** [comment]
We've fixed it in line charts
