### ISSUE TITLE
@import Charts: could not build module "Charts"

### ISSUE THREAD

**Issue by LvJianfeng** [danielgindi/Charts#916]
cocoapods
![image](https://cloud.githubusercontent.com/assets/9586013/14272167/06553a68-fb33-11e5-9e6b-1e486afce38a.png)
![image](https://cloud.githubusercontent.com/assets/9586013/14272170/1409994c-fb33-11e5-9314-b6464be240ab.png)
 
please help me, thank you!

**Comment by wekancodemohammed** [comment]
Try this
pod 'Charts/Realm'

**Comment by LvJianfeng** [comment]
No, I tried to use this alone. If separate use charts, the import will not go wrong

**Comment by liuxuan30** [comment]
follow README
and If you want to compile for iOS 7:

    Drag the code itself (.swift files) to your project. As sadly, Swift currently does not support compiling Frameworks for iOS 7.
    Make sure that the files are added to the Target membership.

**Comment by LvJianfeng** [comment]
Thank you, I have already solved, Thanks to the open source

**Comment by deepp** [comment]
@LvJianfeng can you share how did you solve it. Did you add using pod or dragged all swift file?

**Comment by LvJianfeng** [comment]
@deepp  dragged all swift files to your project.
