### ISSUE TITLE
if use pod Charts/Realm ,than @import Charts: could not build module "Charts"

### ISSUE THREAD

**Issue by LvJianfeng** [danielgindi/Charts#917]
cocoapods
![image](https://cloud.githubusercontent.com/assets/9586013/14272167/06553a68-fb33-11e5-9e6b-1e486afce38a.png)
![image](https://cloud.githubusercontent.com/assets/9586013/14272170/1409994c-fb33-11e5-9314-b6464be240ab.png)
 
please help me, thank you!

**Comment by liuxuan30** [comment]
dup to 916. Please don't duplicate issues.
