### ISSUE TITLE
Could the label of the LineChartDataSet be hidden

### ISSUE THREAD

**Issue by Xwoder** [danielgindi/Charts#918]
LineChartDataSet *dataSet = [[LineChartDataSet alloc] initWithYVals:yVals label:@"Data Set 1"];

after this ,the text Data Set 1 will  show below the chart, but I want to hidden it.

Thank you very much.

**Comment by liuxuan30** [comment]
then why do you pass a string... and enable legend?
to turn off legend, chartView.legend = false
to not display text, use @""
you are a developer, and you can do better exploring the code :)
