### ISSUE TITLE
groupspace doesn't work 

### ISSUE THREAD

**Issue by channak** [danielgindi/Charts#919]
Hi,everyone!! I have two datatsets for the barchart and i try to set groupspace to 0 for the my chartdata but it doesn't work. Could you help?

**Comment by liuxuan30** [comment]
what you mean not work? post a screenshot and what groupSpace you set.

**Comment by channak** [comment]
var dataEntries: [BarChartDataEntry] = []
        var dataEntries2: [BarChartDataEntry] = []
  
        
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: values[i], xIndex: i)
            dataEntries.append(dataEntry)
        }
        
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: values2[i], xIndex: i)
            dataEntries2.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(yVals: dataEntries, label: "Stress Level")
        let chartDataSet2 = BarChartDataSet(yVals: dataEntries2, label: "Stress Label")
        
        chartDataSet.colors =  [UIColor(red: 255/255, green: 0/255, blue: 0/255, alpha: 1)]
        chartDataSet2.colors =  [UIColor(red: 0/255, green: 255/255, blue: 0/255, alpha: 1)]

        let dataSets: [BarChartDataSet] = [chartDataSet,chartDataSet2]
        let chartData = BarChartData(xVals: daytime, dataSets: dataSets)
        
        chartData.groupSpace = 0.0
        barChart.data = chartData

![12968630_10206344976760244_1714631040_n](https://cloud.githubusercontent.com/assets/17492833/14309550/7450f9e4-fbdd-11e5-9e4c-09fd42b2201b.jpg)


what i want is to set no space between all the bar in the graph. 
is it possible to do something like this in the bar chart?
![12935292_10206344984760444_1175422832_n](https://cloud.githubusercontent.com/assets/17492833/14309625/ed4e8b36-fbdd-11e5-9b22-382cdc2077c1.jpg)

**Comment by liuxuan30** [comment]
I tested with ChartsDemo with similar code, it works fine. I don't know what you mean from your screenshot.
I guess you misunderstand what groupSpace means. It means the space between each bar groups, which means one xIndex stands for oue bar group, so for two bar data sets, every group will have two bars. e.g. if groupSpace is 4 space, the bar looks like ||----||----||, while it's 0, it's just like ||||||
So you just set barSpace and groupSpace to 0.
for single data set, groupSpace works like barSpace, and it's locked as 0.0 if one one set.
