### ISSUE TITLE
Vertical bar chart: capture of scrollView delegate callbacks and load additional data

### ISSUE THREAD

**Issue by nspassov** [danielgindi/Charts#920]
Hey guys,

I have a vertical bar chart. It has lots of data that doesn't fit the screen width so I have enabled scaling on the X axis. Is it possible to capture the scrollView offset when chart scaling is on as I would like to trigger a request for more data when the scrolling reaches the bounds of the chart?

**Comment by liuxuan30** [comment]
it's a good quesiton. I'm not sure I understand it correctly, but when you reach the end, you will know it's the last xIndex, and then you can add more data entries by `addEntry`. 
you can take a look at how `panGestureRecognized` `performPanChange` are implemented. It should be helpful. It seems like it does have a delegate called `chartTranslated(chartView: ChartViewBase, dX: CGFloat, dY: CGFloat)` so you know the offset.

**Comment by nspassov** [comment]
The dX value that `chartTranslated` method gives is not the content offset like in a tableView, but something else. It is some kind of delta and this method also gets triggered when swiping that does not result in actual change of the position (swiping at the edge of the chart). This is what I am currently using but so far it doesn't quite do the job.

**Comment by liuxuan30** [comment]
yes, it's not about content offset. You have to do some math to know if it reaches the end. It seems like this part can be improved in the future.

**Comment by shardul89** [comment]
@liuxuan30 is the re any specific methoid which gets called to load next set of chart data when chart reaches end of the scroll?

**Comment by liuxuan30** [comment]
I don't remember, but maybe you can bind some methods from ViewPortHandler to see if possible. 
Maybe `highestVisibleX` could help as well.
