### ISSUE TITLE
Use of undeclared 'CGFloat'

### ISSUE THREAD

**Issue by edulpn** [danielgindi/Charts#923]
Looking around I saw that some time ago this issue has already shown up last year and "import UIKit" did the trick back then and a PR was made and merged (as shown in https://github.com/danielgindi/Charts/issues/44).
Updated now to get rid of the Swift 3 incompatibilities and the issue came back. Importing UIKit worked, but why it actually happened again (build targeting iOS8)?

thanks,
Eduardo.

**Comment by liuxuan30** [comment]
which class reports this?

**Comment by edulpn** [comment]
RadarChartDataSet.swift and IRadarChartDataSet.swift

**Comment by danielgindi** [comment]
I don't know why one Xcode compiles fine and the other refuses - but it should work now
