### ISSUE TITLE
How to set the scaling for the left/right axis.

### ISSUE THREAD

**Issue by tommanuel** [danielgindi/Charts#924]
Suppose in my case I have values ranging from 0-100 in my left axis.My left axis is using a scale of 1 unit = 40.But instead I would like to use a scale of 1 unit = 20,so that it shows the values 0,20,40,60,...... and not 0,40,80..

Anyone??

**Comment by liuxuan30** [comment]
Writing a custom value formatter should solve your question, since it's just a matter of formatting. you just x2 or /2 before you format.

**Comment by tommanuel** [comment]
hey I resolved the issue.Thanks for your help though.
I resolved it by setting the customAxisMax and customAxisMin and then setting the labelCount.

barChartView.leftAxis.customAxisMax = 100
barChartView.leftAxis.customAxisMin = -100
barChartView.leftAxis.labelCount = 11
