### ISSUE TITLE
Coloring bars and not stacks in a StackBar chart

### ISSUE THREAD

**Issue by A1exandre** [danielgindi/Charts#925]
Hi all, and thanks @danielgindi & @PhilJay  for this great piece of work :)

I have a chart with stack bars and I'm trying to have each bar with a different color.

However, when we have stack bars the barChartDataSet.colors property does not set the colors for the bars anymore but for the stacks. 

Is there anyway to set the colors independently for each bar?
Thanks!

**Comment by PhilJay** [comment]
`dataSet.setStackColors(...)`

**Comment by A1exandre** [comment]
Sorry I wasn't verry clear.
I use dataSet.colors =  ...
However, I get this because i have stacks 
![screen shot 2016-04-07 at 10 24 59](https://cloud.githubusercontent.com/assets/15021331/14345099/7e521de6-fcab-11e5-8a9d-75ddd5718938.png)

And what I want is this 
![screen shot 2016-04-07 at 10 24 06](https://cloud.githubusercontent.com/assets/15021331/14345074/5cf08b10-fcab-11e5-9ff3-2a17fc5e4b0c.png)

I found a temporary fix by modifying the drawDataSet function of BarChartRenderer.swift. 
Line 237 was `CGContextSetFillColorWithColor(context, dataSet.colorAt(k).CGColor)` and I replaced it with 
`CGContextSetFillColorWithColor(context, dataSet.colorAt(j).CGColor)`

However, having a  dataSet.colorByBar  or dataSet.colorByStack  property to do this would be nice.

**Comment by liuxuan30** [comment]
your cae is different, stack bar chart will repeat the value, but you don't want it. Then you have to customized it your self. 
BTW, to me, it does not make sense(?) that a stacked bar chart should have the same color, unless you have other ways to distinguish them. However, from your screenshot, it looks just like a normal bar chart. Why using stack not normal for this case?
