### ISSUE TITLE
Drawing value for the WholeStack only

### ISSUE THREAD

**Issue by A1exandre** [danielgindi/Charts#926]
Hi,

The Android doc points to a setDrawValuesForWholeStack property that allows us to  have values drawn only for the wholestack in a StackBar chart.

The Android version also allowed to do this by setting a specific ValueFormatter to the BarChartDataSet.

Unfortunately, the ios version does not has the setDrawValuesForWholeStack and the valueformatter used for the BarChartDataSet is just a NSValueFormatter that cannot have drawForWholeStack property either.

Is there any other way to do this or is this a feature that has not been ported to ios yet?

Thanks!

Edit: If anyone has the same issue, I found a dirty fix for this by modifying the BarChartRenderer's drawvalue function. I Modified the if statement `if (!dataSet.isStacked)...` so that the function always behave as if the data set is not stacked even if it is.

**Comment by danielgindi** [comment]
There's no `setDrawValuesForWholeStack` in the Android api

**Comment by liuxuan30** [comment]
I remember some people are asking such feature. show sum and individual

**Comment by iamZoltanVaradi** [comment]
A1exandre Good workaround! Thank You!
Let's hope they bring back the setDrawValuesForWholeStack feature. Even though they say it can be done with custom formatter, it's not true, because the chart API don't pass contextual information to it.
