### ISSUE TITLE
Line chart with 2 colours

### ISSUE THREAD

**Issue by NotYaz** [danielgindi/Charts#928]
Hello. I'm trying to implement line chart with 2 colours. Positive values should be coloured in blue and negative in red. 

<img width="448" alt="screen shot 2016-04-08 at 14 16 10" src="https://cloud.githubusercontent.com/assets/1261116/14382171/e8185fe6-fd9c-11e5-81f1-8376f73b7a38.png">

Is there any way to do this? 

Thanks

**Comment by liuxuan30** [comment]
the way is to customize the line chart renderer your self.
