### ISSUE TITLE
Binding for Xamarin

### ISSUE THREAD

**Issue by Flash3001** [danielgindi/Charts#929]
Many of you may need to use this library in Xamarin. I did a binding and it can be found at [https://github.com/Flash3001/iOSCharts.Xamarin](https://github.com/Flash3001/iOSCharts.Xamarin) or [https://www.nuget.org/packages/iOSCharts/](https://www.nuget.org/packages/iOSCharts/)

The Android version can also be found at [https://github.com/Flash3001/MPAndroidChart.Xamarin](https://github.com/Flash3001/MPAndroidChart.Xamarin) or [https://www.nuget.org/packages/MPAndroidChart/](https://www.nuget.org/packages/MPAndroidChart/)

**Comment by petester42** [comment]
What to send a pr adding these links to the readme?
