### ISSUE TITLE
Bubbles size of bubble chart

### ISSUE THREAD

**Issue by marcomonanto** [danielgindi/Charts#930]
Hi,

I'm doing  a Bubble Chart but I got a problem when I set the size of the bubble after I updated the framework to 2.2.4.

here is a chunk of my code

```
for i in 0..<legend.count{
            
            let val: Double = (Double(i)+1);
            
            let bubbleChartDataEntry: BubbleChartDataEntry = BubbleChartDataEntry.init(xIndex: i, value: val, size: 0.01)
            
            var iChartDataEntry: [BubbleChartDataEntry] = [BubbleChartDataEntry]()
            iChartDataEntry.append(bubbleChartDataEntry)
            
            let colorsClipped: Array = WSCUtils.getPieSlicesColors(legend.count)
            
            set1 = BubbleChartDataSet.init(yVals: iChartDataEntry , label: nil);
            set1.setColor(colorsClipped[i]);
            set1.drawValuesEnabled = false;
        
            dataSets.addObject(set1);
            yVals1.removeAllObjects();

        }

```

i'm passing that 0.01 in size so something is not right and i cant find what...

![screen shot 2016-04-08 at 14 52 35](https://cloud.githubusercontent.com/assets/17854952/14385689/a3981f9e-fd99-11e5-8fe1-38412f1d0333.png)

**Comment by danielgindi** [comment]
What happens right now is that these are normalized against the max size in the dataset.
Which of course does not make sense, as there may be "smaller" bubbles without any full-size bubble.
