### ISSUE TITLE
Crash on zoom

### ISSUE THREAD

**Issue by calkinssean** [danielgindi/Charts#931]
Hi, if I zoom in too fast and far my app crashes. The error I am getting is fatal error: stride must not be zero. I noticed on your demo apps there seems to be a max zoom which eliminates this crash. I am wondering how I can implement this.

**Comment by liuxuan30** [comment]
please paste the stack trace when crashing.

**Comment by danielgindi** [comment]
I'm assuming it's because of the move to Swift 2.2.
Apple failed to mention that when they automatically convert a for loop to a Stride, the result is far from the same. Because Stride insists on throwing exceptions when it has nothing to loop over, instead of just doing nothing.

@calkinssean If you can point us to which line of code produces the exception - it could be easily fixed.

**Comment by liuxuan30** [comment]
@danielgindi not sure if I understand you crrectly, but stride can handle empty cases on my side, e.g. below 4 loops:
```swift
        for i in 0.stride(through: 0, by: 1) {
            print(i)
        }
        for i in 0.stride(through: -1, by: 1) {
            print(i)
        }
        for i in 0.stride(to: 0, by: 1) {
            print(i)
        }
        for i in 0.stride(to: -1, by: 1) {
            print(i)
        }
```
Only the first loop will print "0", others will print nothing. so for the crash, I am not sure why we need to judge first and last?

**Comment by danielgindi** [comment]
Well the stride I know crashes- and you can see it in Stride's source
code... I've sent a PR to Apple
בתאריך יום ב׳, 11 באפר׳ 2016 ב-6:23 מאת Xuan <notifications@github.com>:

**Comment by liuxuan30** [comment]
I see that. the stride cannot be 0, but old c loop will has infinite loop.

**Comment by danielgindi** [comment]
Why an infinite loop?

```
for (var i = 0; i < 0; i +=0) {
  // This will not be called, as "i < 0" is not satisfied
}
```

**Comment by liuxuan30** [comment]
oops, my bad. I mean <= when I said infinite loop

**Comment by danielgindi** [comment]
Oops - it's actually *my* bad, as I didn't see that it's a case of `through` which is `<=`.

I'll have to look at the code again to make sure that the extra axis line is not missing in cases where last-first is an exact multiplication of interval.

I'll also need to make tests for Swift Stride to make sure that there are no infinite loop cases.

**Comment by danielgindi** [comment]
After running some tests I'm writing for the PR - it looks like the Swift precondition is meant for checking the `interval`, not the `to` or `through`. Will almost definitely cause an infinite loop... Unless the test is `less than`

**Comment by liuxuan30** [comment]
We evolved from crash/not responding after a few minutes to crash directly :)
