### ISSUE TITLE
Don't see updates in PieChartDataSet from 2.2.4

### ISSUE THREAD

**Issue by Dalein** [danielgindi/Charts#933]
I've updated my pod to 2.2.4, and I saw in terminal log that Charts was realy updated to 2.2.4, but when I added new code for pieChart:
```
dataSet.valueLinePart1OffsetPercentage = 0.8;
    dataSet.valueLinePart1Length = 0.4;
    dataSet.valueLinePart2Length = 0.5;
    //dataSet.xValuePosition = PieChartValuePositionOutsideSlice;
    dataSet.yValuePosition = PieChartValuePositionOutsideSlice;
```

I got errors. Then I went to my Pod folder - Charts - Core - PieChartDataSet.swift -  I see 78 lines of code (versus 99 here https://github.com/danielgindi/Charts/blob/master/Charts/Classes/Data/Implementations/Standard/PieChartDataSet.swift). There is no properties for OutsideSlice stuff.

Deployment target in Pod settings and in project - 8.0. Tried to delete Charts from pod, change to 9.0 and install - result the same.
Xcode 7.3 (7D175)

**Comment by danielgindi** [comment]
It's not in 2.2.4, but on `master`.
