### ISSUE TITLE
我想用charts显示的数据为'int'类型

### ISSUE THREAD

**Issue by shenyufei** [danielgindi/Charts#936]
我有一个需求，需要显示整数数据(Values)，不要小数点(Double),我要怎么设置？ @liuxuan30

**Comment by liuxuan30** [comment]
you only have to change the value formatter in y axis or data set. Make `maximumFractionDigits` to 0.
BTW, I encourage you write English, it will only have benefits.
I can't watch github all day, and many people can help you.

**Comment by danielgindi** [comment]
He sent me an email privately, but he cannot communicate much in English, so I told him to come here and ask someone who knows Chinese :-)

**Comment by liuxuan30** [comment]
I got one too. Let me reply that in email.

**Comment by shenyufei** [comment]
thank you






At 2016-04-11 14:38:59, "Xuan" <notifications@github.com> wrote:


you only have to change the value formatter in y axis or data set. Make maximumFractionDigits to 0.
BTW, I encourage you write English, it will only have benefits.
I can't watch github all day, and many people can help you.

**Comment by shenyufei** [comment]
thank you
