### ISSUE TITLE
highlight last data in bar chart 

### ISSUE THREAD

**Issue by narri007** [danielgindi/Charts#938]
Hi, 
Thanks for the Charts. I am using the Bar charts in my project and its working very well. I have one doubt is, After loading the data to **BarChartView** how can i highlight the last record. Please see the attached images for reference, 

I am getting like, 
![img_6083](https://cloud.githubusercontent.com/assets/5907338/14447014/7829da9e-008e-11e6-8ea7-f2bca58d5aa2.jpg)

But, i want to show like, 
![img_6082](https://cloud.githubusercontent.com/assets/5907338/14447017/89ddf0cc-008e-11e6-993f-960a35f69a10.jpg)

Is there any method to set the bar highlighted at the time of initialization. Please help me on this. 

Thanks,

**Comment by AntiMoron** [comment]
@narri007  Hi , I ran into the same problem. How did you get that achieved?

**Comment by narri007** [comment]
@AntiMoron, Use the delegate method, 
`- (void)highlightValueWithXIndex:(NSInteger)xIndex dataSetIndex:(NSInteger)dataSetIndex callDelegate:(BOOL)callDelegate;
`

**Comment by AntiMoron** [comment]
@narri007 Great thanks.

**Comment by Vay-Minzhou** [comment]
nice, the perfect solution to my problem
