### ISSUE TITLE
highestVisibleXIndex is smaller than lowestVisibleXIndex

### ISSUE THREAD

**Issue by lionhylra** [danielgindi/Charts#940]
I just downloaded the demo app, adding one line ` _chartView.autoScaleMinMaxEnabled = YES;` to the BarChartViewController.m at line:56.

And I run the demo app, and open the bar chart, zoom in. It crashes.
The screenshot:
[screenshot](https://dl.dropboxusercontent.com/s/dqtwiw9ix4qmyql/Screenshot%202016-04-12%2017.23.11.png)
Back trace:
[back trace](https://dl.dropboxusercontent.com/1/view/uchzyycy27rgm96/Screenshots/Screenshot%202016-04-12%2018.03.11.png
)

**Comment by liuxuan30** [comment]
send out the back trace, so we know where it crashes.

**Comment by lionhylra** [comment]
I’ve added back trace.

**Comment by liuxuan30** [comment]
oh man, I met a total different place to crash with what you said

**Comment by liuxuan30** [comment]
you can simply post the text rather than image.
It crashes at BarChartDataSet.calcMinMax(), not highestVisibleXIndex is smaller than lowestVisibleXIndex

**Comment by lionhylra** [comment]
Yes, exactly. And in my own project, when I apply 'autoScaleMinMaxEnabled = true' to my bar chart, it crashes directly for the same reason.

**Comment by lionhylra** [comment]
In the screenshot above, the end value is smaller than start value in the for loop.

**Comment by lionhylra** [comment]
I don't think changing 'for in range' to 'stride' will fix

**Comment by liuxuan30** [comment]
why not? I did a quick test, it won't crash then.

**Comment by liuxuan30** [comment]
```
        _lastStart = start
        _lastEnd = end
        
        _yMin = yMin(entries[start])
        _yMax = yMax(entries[start])
        
        for i in start.stride(through: endValue, by: 1)
        {
```
if endValue < startValue, we won't hit the loop, and yMin, yMax is from entries[start]. So I think it is harmless.

**Comment by lionhylra** [comment]
ok, I will try it later. Thanks
