### ISSUE TITLE
setVisibleXRangeMinimum cause crash

### ISSUE THREAD

**Issue by lionhylra** [danielgindi/Charts#946]
In the demo, adding line: `[_chartView setVisibleXRangeMinimum:5];` to _LineChart1ViewController.m_ causes crash

**Comment by danielgindi** [comment]
Well you were calling it before `notifyDataSetChanged` were called (when `data` was set), so axisRange was 0.0, and it caused a division by zero.

So: 1. Call it in a proper place, 2. We'll fix the crash :-)
