### ISSUE TITLE
Updating version alters bar chart layout

### ISSUE THREAD

**Issue by iamZoltanVaradi** [danielgindi/Charts#950]
I recently updated from v2.1.6 to v2.2.4
Without changing anything in my code, the layout of bar charts and line charts got changed. I assumed it's the auto scale min max feature being defaulted to true from false, but even after i set 

> chartView.autoScaleMinMaxEnabled = false

The issue stayed the same. Changing that property didn't effect the layout. See images:

Before (v2.1.6)
![before](https://cloud.githubusercontent.com/assets/1964469/14520840/d72e45e0-0226-11e6-96b1-51687c9f93b2.png)
After (v2.2.4)
![after](https://cloud.githubusercontent.com/assets/1964469/14520841/d73218a0-0226-11e6-8ba5-a7c73e4272d1.png)

**Comment by liuxuan30** [comment]
To me, looks like it's related to axisMinValue of y axis is not 0 in second screen, while it's 0 for first one. try set to 0. StartAtZero is deprecated.

**Comment by danielgindi** [comment]
`autoScaleMinMaxEnabled` is still `false` by default, and has nothing to do with it.
This probably has to do with the range of your data

**Comment by iamZoltanVaradi** [comment]
But it's the same data. How come the layout changes?

**Comment by danielgindi** [comment]
I cannot tell without seeing the code before and after.
Try to set the yAxis' `axisMinValue` to `0`

**Comment by iamZoltanVaradi** [comment]
That's what i wrote initially. The code is the same.

**Comment by danielgindi** [comment]
Are you trying with 2.2.4 or with `master`?

**Comment by iamZoltanVaradi** [comment]
pods said 2.2.4.

**Comment by liuxuan30** [comment]
@iamZoltanVaradi 2.1.6 is quite a old release, and not changing your code may have the issues. Because recently there are changes, like deprecated startAtZeroEnabled, and move to axisMinValue. 

Could you just set your left or right y axis with axisMinValue = 0 and see what's the result?

If you want help, I still suggest you turn on displaying y axis values for debug purpose to see what the y range is.
