### ISSUE TITLE
Line Chart Dynamic Updating

### ISSUE THREAD

**Issue by asdfasdf126** [danielgindi/Charts#951]
I am trying to create a line graph that updates as it gets points. The problem I'm having is the graph will not update unless i am interacting with it. Either moving the graph or even tapping it. I'm out of ideas on how to remedy this problem and i have not been able to find anything that comes close to working.
    
    LineChartData *data = self.chartView.data;
    
    if(data != nil)
    {
        LineChartDataSet *set = [data getDataSetByIndex:0];
        
        if(set == nil)
        {
            set = [[LineChartDataSet alloc] init];
            
            set.drawCirclesEnabled = false;
            set.drawValuesEnabled = false;
            [set setColor:UIColor.blackColor];
            set.lineWidth = 1.0;
            set.valueFont = [UIFont systemFontOfSize:9.f];
            set.drawCubicEnabled = true;
            
            NSArray *gradientColors = @[
                                        (id)[ChartColorTemplates colorFromString:@"#00ff0000"].CGColor,
                                        (id)[ChartColorTemplates colorFromString:@"#ffff0000"].CGColor
                                        ];
            CGGradientRef gradient = CGGradientCreateWithColors(nil, (CFArrayRef)gradientColors, nil);
            
            set.fillAlpha = 1.f;
            set.fill = [ChartFill fillWithLinearGradient:gradient angle:90.f];
            set.drawFilledEnabled = true;
            
            CGGradientRelease(gradient);

            [data addDataSet:set];
        }
        
        [self.chartView setVisibleXRangeMaximum:MAXVALUES];
        [self.chartView setVisibleXRangeMinimum:MAXVALUES];
        
        [data addXValue:[NSString stringWithFormat:@"%.f", xVal]];
        [data addEntry:[[ChartDataEntry alloc] initWithValue:yVal xIndex:xVal] dataSetIndex:0];
        
        int move = [[set entryForIndex:[set entryCount] - 1] xIndex];
        
        [self.chartView notifyDataSetChanged];
        [self.chartView moveViewToX:(move - MAXVALUES < 0)?0:move - MAXVALUES];
    }
    else
        self.chartView.data = [[LineChartData alloc] init];

**Comment by liuxuan30** [comment]
just search 'Dynamic' in issues, you will see some options.
