### ISSUE TITLE
A "divide by 0" bug

### ISSUE THREAD

**Issue by lionhylra** [danielgindi/Charts#952]
In the file _ChartYAxisRenderer.swift_, _line 136_ : There is a small chance that the `interval` is 0(e.g. I set `rightYAxis.granularity = 0.001` or a smaller number).

I recommend adding ` guard interval != 0 else {return}` at _line 136_ .

Otherwise it might cause error when calculating last which finally crash app.

[Screenshot](https://dl.dropboxusercontent.com/s/k3ohd4d5i3dnsia/Screenshot%202016-04-15%2015.12.48.png?dl=0)

**Comment by danielgindi** [comment]
The problem seems to actually be the interval of the for-loop. It should be converted to a `stride`

**Comment by lionhylra** [comment]
Even when the for loop is converted to a stride, if the interval is 0, then start and end will become "NaN" which break the stride leading to a crash

**Comment by danielgindi** [comment]
This does not happen anymore with the latest changes, you can checkout the code from `master`.
