### ISSUE TITLE
XAxis Values label rotation

### ISSUE THREAD

**Issue by schech-a** [danielgindi/Charts#953]
Hi,

I see that the labels of the X and Y can be rotated with that : xAxis.labelRotationAngle = Angle in degree;
I am trying to rotate the value labels of the X-Axis. With a very long ChartGraph, with consequent strings, the strings becomes unreadable(see attached pic)

![e3040eba-3172-4447-aeec-a1452015eb77](https://cloud.githubusercontent.com/assets/3235673/14563572/e6d84624-0322-11e6-9fe9-cb2291d4953e.jpeg)
.

Is there any way to rotate those value label to make them more visible?

Thanks a lot for your precious help guys!

Alexis

**Comment by dxclancy** [comment]
That code that draws barChart values doesn't currently support rotation.  I wonder if your values are hours and maybe you could format them as 30h instead of 30:00?

**Comment by schech-a** [comment]
Unfortunately I can't because it has to be displayed like that... Moreover,
if I have to display 30h40 the issue stays the same.

I'll maybe try to explore the source code a bit to see if I can manage to
tweak it if there is no other option.

Thanks for your help

**Comment by dxclancy** [comment]
If you have to display like that, this won't help, but another option would to format it with a new line, so that it shows up as
30h
40m
and/or use a smaller font.  but probably not helpful.

If you end up needing help on the rotation tweet, let me know.

**Comment by liuxuan30** [comment]
Before you get started, you should first figure out how many text you want to display. As in your screenshot, it's like 45 degree rotation, and only 3-4 chars can be displayed. If you want to display the full value, you have to use a smaller font size.
If the bars becoming more, the bar width is shorter, and x value's drawing rect's width is smaller too. So you might want to figure out the logic first, and you can continue.
