### ISSUE TITLE
Cannot pass in struct to ChartDataEntry

### ISSUE THREAD

**Issue by YileiHeOMT** [danielgindi/Charts#954]
In the class `ChartDataEntry`: 
The initialiser is
```swift
public init(value: Double, xIndex: Int, data: AnyObject?)
    {
        super.init()
        
        self.value = value
        self.xIndex = xIndex
        self.data = data
    }
```
For the third parameter, I can only pass in a class type object. That makes it impossible to pass in a struct or a tuple. So I recommend changing the type or `data` to `Any?`

**Comment by liuxuan30** [comment]
well why you want to use struct or tuple? you can convert it to a Object and move on

**Comment by YileiHeOMT** [comment]
My case is:
In my line chart, the value for each XIndex is a `double` type value(certainly it is). When I click on the chart, I want the pop-up overlay(aka. marker) to show more details like "date". 

Let's see a example: 
```swift
struct CarSalesHistoryItem {
 var profit:Double
 var date: NSDate
 var numberOfCarsSold:Int
//...
}
```
In the chart, I get a array of CarSalesHistoryItem. I use profit as yAxis value and date as xAxis value. When I tap on a point, I want it to display all the information of that history item.
You may say, changing `CarSalesHistoryItem` to `class` type will fix it. But in many projects, we use `struct` as data model. Because `struct` is "value type" while `class` is "reference type".

**Comment by liuxuan30** [comment]
yeah, then it's your duty to take care of them. It's very easy for you to sub class the entry class that can take a struct and send back to you.

**Comment by YileiHeOMT** [comment]
Fair enough

**Comment by petester42** [comment]
I'm not sure but I believe it might be anyobject for technical reasons. I don't think any translates to objc
