### ISSUE TITLE
Cubic line chart is not full bleed 

### ISSUE THREAD

**Issue by jathu** [danielgindi/Charts#956]
The line chart does not extend all the way to the end of the view. I *disabled* the ```rightAxis.enabled```, ```leftAxis.enabled```, ```xAxis.drawAxisLineEnabled``` and ```xAxis.drawGridLinesEnabled```. Here is what I mean (the whole teal box is the view):

![img_3350](https://cloud.githubusercontent.com/assets/4391247/14631966/09203e3a-05e4-11e6-9306-df52894eb058.PNG)

**Comment by liuxuan30** [comment]
can you check what's your `contentRect`?  there would be a small gap and contentRect is smaller than the chart view bounds. I remember there is a minOffset =10.0 by default to restrain the contentRect. You can change it to 0.0 and see
