### ISSUE TITLE
x axis label gets cut

### ISSUE THREAD

**Issue by odedharth** [danielgindi/Charts#958]
x axis label gets cut

<img width="880" alt="file_19-04-2016__2_12_54_pm_png" src="https://cloud.githubusercontent.com/assets/624023/14640238/51bb6862-0649-11e6-9656-a3ac1c40a6a6.png">

How can this be fixed? 
Is there a way to move it to the left? Maybe enlarge the width of the chart?

**Comment by jathu** [comment]
```xAxis.avoidFirstLastClippingEnabled = true```
