### ISSUE TITLE
Overriding Highlight 

### ISSUE THREAD

**Issue by arjunnayak** [danielgindi/Charts#960]
Is it possible to override a LineChartView's highlight to draw and call the delegate's 'chartValueSelected' method even if there is no data at that specific xIndex? I've attempted to make changes in the actual highlight code logic but it feels way too hacky.

**Comment by liuxuan30** [comment]
well if there is really no data (NOT data that value = zero), from the definition:
```
chartValueSelected(chartView: ChartViewBase, entry: ChartDataEntry, dataSetIndex: Int, highlight: ChartHighlight)
```
no arguments are allowed optional, how do you deal with it?

**Comment by danielgindi** [comment]
You can always supply your own Highlighter object.
The Highlighter object is a pretty new thing in Charts, and we'll be modifying the interfaces a bit soon. So head up!

**Comment by liuxuan30** [comment]
@danielgindi oh man what changes? I just sync my library to 2.2.4.

**Comment by danielgindi** [comment]
interface-wise- nothing big. Currently the types are wrong (Float/Double), and one of the function has an additional parameter to accept a data index for better supporting combined chart

**Comment by liuxuan30** [comment]
speaking of combined chart - we might be careful because a data(set?) index seems not additonal to me, considering the multiple bars support. These are the pain points when I have to think about markers and highlight for combined chart individual shape and dot.

**Comment by danielgindi** [comment]
Well at first stage I want to allow highlighting individual values, bars, shapes etc.

Then after that- to add a property "highlightFullBars" to bar/line based charts- that will allow to select anywhere on the bar to select the whole thing. In combined chart it will allow the current behavior of selecting the full bar with all its values.

The first stage is actually read, there's a PR on the Android side waiting for review @PhilJay.

**Comment by liuxuan30** [comment]
OK. But I do think we should get started thinking of grouped bar support in combined chart. Sometimes it's just get more complicated or inconvenient when we refactor the code without thinking grouped bar support

**Comment by danielgindi** [comment]
Yeah I know :-) 
Problem is Phil is working on making x indices more flexible. Using Doubles instead of Integers, and allowing for x-axis with steps that are now "whole".
Well this is not a problem, it's a major feature that's the first one going into v3, but we cannot do any work on Group bars in Combined chart before that's completed :-)

**Comment by liuxuan30** [comment]
alright, let's see!
