### ISSUE TITLE
changing bottom 'key' label?

### ISSUE THREAD

**Issue by 128keaton** [danielgindi/Charts#962]
![screen shot 2016-04-20 at 3 54 21 pm](https://cloud.githubusercontent.com/assets/1402918/14690129/33681776-0710-11e6-86a5-7e088617623f.png)
At the bottom, there is a key for colors, based on the labels set in your data set. Is there any way I can change those colors? You cannot see mine since the color is black..

**Comment by liuxuan30** [comment]
are you talking about legend? you can change colors in ChartLegend

**Comment by 128keaton** [comment]
@liuxuan30 thanks man!
