### ISSUE TITLE
Don't show the horizontal line

### ISSUE THREAD

**Issue by fs123456** [danielgindi/Charts#964]
![12345](https://cloud.githubusercontent.com/assets/17874054/14702294/38800800-07dc-11e6-8c1c-196ae2cfd2f6.png)
Hi：
     I don't want to show the horizontal line，how to do it in this case. I don't kown the correst English grammar,so ignore the wrong part! 
     Thanks!

**Comment by liuxuan30** [comment]
I remember it's: `set.isHorizontalHighlightIndicatorEnabled`
