### ISSUE TITLE
Getting Error cannot load underlying module XCTest

### ISSUE THREAD

**Issue by FrancisZamora** [danielgindi/Charts#965]
Getting Error in my BarChartTests which says that the underlying module for XCTest cannot be loaded. What should I do?

**Comment by petester42** [comment]
You most likely adding BarChartTests to a target that is not a test target.

**Comment by FrancisZamora** [comment]
So what should I do to BarChartTests? I just did file..add files to project and added charts to my project and put import Charts in my view controller and thats all I did. I'm just trying to see if it will run like that.

**Comment by petester42** [comment]
Just add the classes folder nothing else.

**Comment by FrancisZamora** [comment]
Alright perfect... I have another question. So I should put the import Charts in my ViewContoller.swift file or should I make a new file for the view controller which I made in the story board and added a view with its class set to bar chart view?

**Comment by petester42** [comment]
See #966
