### ISSUE TITLE
The horizontal bar graph data values are exceeding the graph space.

### ISSUE THREAD

**Issue by wganeshb** [danielgindi/Charts#967]
Hello everyone. 
Currently I am implementing the horizontal bar graph.

My graph is showing time in hh:mm:ss format. But the time displayed on graph is exceeding the graph view region as shown below. How can I fit this into graph region.

![screen shot 2016-04-22 at 7 54 45 am](https://cloud.githubusercontent.com/assets/3005149/14729912/92c3abfe-085f-11e6-9e4b-a9e730085408.png)

Any suggestions are highly appreciated.

**Comment by liuxuan30** [comment]
I suggest set yAxis.customMaxValue a little bigger (like 10% bigger) just to make sure it had enough space for your max value's text.

**Comment by wganeshb** [comment]
@liuxuan30 Thanks for the update.
Didn't get any yAxis.customMaxValue.

**Comment by liuxuan30** [comment]
customMaxValue is in latest release. If you are with old verions, it's called customAxisMin/Max
