### ISSUE TITLE
Where and how can I set a y axis custom max value?

### ISSUE THREAD

**Issue by FrancisZamora** [danielgindi/Charts#968]
Where and how can I set a y axis custom max value?
Should I change the view controller I am using for the bar graph or should I make the declaration in my classes folder from charts?

**Comment by liuxuan30** [comment]
use yAxis.customMaxValue

**Comment by FrancisZamora** [comment]
Well.... Where should I make that declaration?

**Comment by dxclancy** [comment]
Francis, a lot of your questions seem to be general programming questions instead of questions relating to Charts.

**Comment by liuxuan30** [comment]
after you create your chart view object. Man, it's too easy to find out
