### ISSUE TITLE
Help with customizing 

### ISSUE THREAD

**Issue by hevertonrodrigues** [danielgindi/Charts#970]
Someone can help-me or saying if I can add a "padding" between my last label ("17/04") and right margin to doesn't crop the text?

And another thing, it's possible add a fixed label to left Axis with a measure (like 120.0kg)?

Thanks

![screen shot 2016-04-22 at 2 08 13 pm](https://cloud.githubusercontent.com/assets/3950909/14749062/b48af236-0893-11e6-9496-ee05cb131ce3.png)

**Comment by FrancisZamora** [comment]
How did you modify your y axis and the scaling?

**Comment by hevertonrodrigues** [comment]
![screen shot 2016-04-22 at 11 13 02 pm](https://cloud.githubusercontent.com/assets/3950909/14758729/fe3bfad2-08df-11e6-96c7-4ab279358985.png)
![screen shot 2016-04-22 at 11 13 17 pm](https://cloud.githubusercontent.com/assets/3950909/14758728/fe386cf0-08df-11e6-8480-d462f48a15e2.png)

**Comment by liuxuan30** [comment]
1. for the first and last label, try `avoidFirstLastClippingEnabled`
2. you can use your own formatter to add $ or kg tag. Check out the Demo project, it has $ there

**Comment by hevertonrodrigues** [comment]
Solved perfectly! Thanks @FrancisZamora and @liuxuan30
