### ISSUE TITLE
Overlapping with multiple data styles

### ISSUE THREAD

**Issue by 128keaton** [danielgindi/Charts#972]
![screen shot 2016-04-22 at 8 50 26 pm](https://cloud.githubusercontent.com/assets/1402918/14758741/8be22f2a-08cf-11e6-9a8a-720250421341.png)
As you can see, I am experiencing some overlapping with the Bar Graph, and the Data Point with text. Is there a value I can set that defines the spacing? Thanks!

**Comment by danielgindi** [comment]
There is currently no way to solve this - it is a very complex problem as you can imagine.
But what you can do is add a Marker view, so when the user taps the point, he gets a beautiful marker with the data about the point.
