### ISSUE TITLE
Unexpected problem with Import Charts

### ISSUE THREAD

**Issue by FrancisZamora** [danielgindi/Charts#973]
I have been running iOS simulator to test my app, but when I switched over to my phone I started receiving the error No Such Module Charts.. It was working before when I used the iOS simulator but it stops working when I want to test it on my own phone.. I don't get it.

**Comment by jdmarshall90** [comment]
If you build the Charts framework scheme by itself for your device first and then build the scheme for your app target (which will need to link to Charts), this should fix it.

**Comment by FrancisZamora** [comment]
The thing is I imported the classes folder from charts so I do not have the option to build the charts framework scheme by itself.

**Comment by FrancisZamora** [comment]
I have the option to build Charts iOS which is a separate file from my project and is not in my project.

**Comment by jdmarshall90** [comment]
Oh I see. Is there a reason you can't just add Charts, as a whole, as a separate project in your Xcode workspace? That would allow you to do this.

**Comment by petester42** [comment]
If you have copied all the files to your project you shouldn't use `import Charts` since your aren't importing anything. The code is already in your app. It probably still works on the simulator since there is a chached version of the framework somewhere.
