### ISSUE TITLE
Show empty Chart when there are no data

### ISSUE THREAD

**Issue by cepages** [danielgindi/Charts#975]
Hi I'm working with LineChartData and I would like to show the axis even when there are not data in the chart, in my case:
```
po listOfLineChart
<__NSArrayM 0x7faf5dcb9340>(
ChartDataSet, label: Weight, 0 entries:
)
```

I don't want to show the message: `You need to provide data for the chart. No chart data available`

Thanks

**Comment by dxclancy** [comment]
I am not one of the authors of the library, but in the demo, I see that there is this setting:
    _chartView.noDataTextDescription = @"You need to provide data for the chart.";
So it seems like you could turn off this text by setting it to @"";

Perhaps if you detect the chart is empty, you could set an empty value to get the chart to draw.

**Comment by cepages** [comment]
The problem is I don't want to paint 0's, because currently I'm adding
empty values, if I add 0's the graph will paint them.

Maybe I taking the fact of empty values wrong, what do you mean exactly
with empty values?

Thanks

**Comment by dxclancy** [comment]
I actually meant adding just one value of 0 (and configure all other things so that it won't draw things.)

However, I just tried this:If you replace this line in the Demo LineChart1ViewContoller:
`        
LineChartData *data = [[LineChartData alloc] initWithXVals:xVals dataSets:dataSets];
`
with 
`        
LineChartData *data = [[LineChartData alloc] init];
`
it seems to behave as you want.

**Comment by liuxuan30** [comment]
If you don't have any data, the axis will be displayed as 0-1, which may be meanless. Currently, there is a check to make sure you have data. If you really want the axis displayed, you have to delete those checks, starting from data setter and drawRect

**Comment by cepages** [comment]
Hi @liuxuan30 when you mean `there is a check` could you point me what exactly should I change?

I was checking [here](https://github.com/danielgindi/Charts/blob/cefa901847bf3ed795ab8339f75aef1d32b065fe/Charts/Classes/Data/Implementations/Standard/ChartData.swift#L88) but I'm not really sure.

@dxclancy I tried with the demo and to change that you commented, as you said it's showing the chart. I tried in my one but shows the message instead of the char:

![screen shot 2016-04-27 at 18 05 21](https://cloud.githubusercontent.com/assets/5259830/14860948/febe96a6-0ca2-11e6-8dd4-c9298a22a6c3.png)

I will try to know what is different. Thanks

**Comment by cepages** [comment]
Thanks both, in the end I could check the new version of the library is not showing the message. I wasn't using the new version due to a (problem with translations in XCode 7.3)
