### ISSUE TITLE
BarChartView height is not reflecting the values assigned to it.

### ISSUE THREAD

**Issue by LekhaP** [danielgindi/Charts#977]
Hi,

Currently what i have right now is
![image](https://cloud.githubusercontent.com/assets/11720692/14789882/4c8e1814-0ad4-11e6-8b27-f17b9e08da4d.png)

The values i am sending to the chart is :
            var str: [String] = ["1","2"];
            var score: [Double] = [1,0.5];
            setChart(str, values: score)

And i have used the formatter as:
        let percentageNumberFormatter = NSNumberFormatter()
        percentageNumberFormatter.numberStyle = .PercentStyle
        chartDataSet.valueFormatter = percentageNumberFormatter

Its not reflecting 100% and 50% in proportion. It rather looks like 100% and 5%.

Could somebody help me understand what i might be doing wrong.

Thank you advance.

**Comment by liuxuan30** [comment]
can you check ChartsDemo? I think you must missed something.

**Comment by LekhaP** [comment]
Here is the code i used for the charts.

    @IBOutlet var barChartView: BarChartView!
 func setChart(dataPoints: [String], values: [Double]) {
        
        var dataEntries: [BarChartDataEntry] = []
        for i in 0..<dataPoints.count {
            let dataEntry = BarChartDataEntry(value: Double(values[i]), xIndex: i)
            dataEntries.append(dataEntry)
        }
        
        let chartDataSet = BarChartDataSet(yVals: dataEntries, label:"Quiz Scores on chapters(%)")
        let chartData = BarChartData(xVals: dataPoints, dataSet: chartDataSet)
        barChartView.data = chartData
        
        
        // valueFormatter
        let percentageNumberFormatter = NSNumberFormatter()
        percentageNumberFormatter.numberStyle = .PercentStyle
        chartDataSet.valueFormatter = percentageNumberFormatter
        
        
        barChartView.data?.setValueFont(UIFont.systemFontOfSize(9.0))
        barChartView.data?.setValueTextColor(UIColor(red: 216/255, green: 76/255, blue: 62/255, alpha: 1))
        chartDataSet.colors = [UIColor(red: 216/255, green: 76/255, blue: 62/255, alpha: 1)]
        
        barChartView.descriptionText = ""
        barChartView.drawBarShadowEnabled = false;
        barChartView.drawValueAboveBarEnabled = true;
        
        let xAxis:ChartXAxis = barChartView.xAxis
        xAxis.labelPosition = .Bottom
        xAxis.labelFont = UIFont.systemFontOfSize(9.0)
        xAxis.drawGridLinesEnabled = false
        xAxis.spaceBetweenLabels = 0
        xAxis.labelTextColor = UIColor(red: 77/255, green: 85/255, blue: 95/255, alpha: 1)
        
    
        //hide left and right axis
        barChartView.leftAxis.enabled = false
        barChartView.leftAxis.drawGridLinesEnabled = false
        barChartView.rightAxis.enabled = false
        barChartView.rightAxis.drawGridLinesEnabled = false
        
        barChartView.legend.enabled = false;
        barChartView.userInteractionEnabled = false
    }


Thats pretty much all i have.
I looked at the ChartsDemo. It din really help much.

**Comment by liuxuan30** [comment]
try put barChartView.data = chartData at last line.

**Comment by danielgindi** [comment]
You chart is probably being offset. Either by limiting the Y axis with a minimum value that's around 45%, or viewport translations.
