### ISSUE TITLE
NaN makes highestVisibleXIndex crash

### ISSUE THREAD

**Issue by iangmaia** [danielgindi/Charts#980]
In some scenarios, when scrolling from the rightmost side of a CandleStick chart to the leftmost side, I'm getting a crash when reaching the beginning of the chart at the `highestVisibleXIndex` in the `calcXBounds` method callend when drawing.

In the `highestVisibleXIndex` getter:
```
        getTransformer(.Left).pixelToValue(&pt)
```
This line results in pt.x and pt.y being NaN, and then it crashes when it tries to round it.

Any ideas on why could this happen?

**Comment by liuxuan30** [comment]
if pixelToValue returns NaN, have you checked pt itself, or the matrix messed up.
Need you to debug more on this, we have limited knowledge right now

**Comment by danielgindi** [comment]
Does this still happen?
I cannot reproduce this issue. Maybe put in a piece of code that triggers it in the Demo?

**Comment by iangmaia** [comment]
It still does happen.
One thing that probably is affecting / causing it (it shouldn't, I would expect) is that I'm changing the zoom / doing a refresh on the viewPortHandler as the user moves the map.
That is done to adjust the candlesticks heights dynamically and making all the candles fit in the screen at the same time (this is google finance and many other apps behaviour).

The problem is somewhat rare but it happens in some cases I couldn't identify yet.

**Comment by liuxuan30** [comment]
well could you capture the crash stack? We have to know more to locate the issue

**Comment by iangmaia** [comment]
I could reproduce it quite easily when I reported originally but now I can't anymore :( it seems that it happened with some specific data pattern that isn't happening any longer.

Anyway, I guess you guys can close this issue if you want until I can get a stack trace, simulate it or something like that.

**Comment by liuxuan30** [comment]
sure thing. When you see the crash(hopefully not), please debug as possible as you can, especially the chart transformers matrix values.

**Comment by chrisozenne** [comment]
Ran into this crash today. Only happens when I have `yAxis.startAtZeroEnabled = NO;`. If I set it to `YES`, the problem goes away.

**Comment by danielgindi** [comment]
If you are using `startAtZeroEnabled` then this crash did not happen... Because you are not using the latest version, or even the version before that! :)
