### ISSUE TITLE
fatal error: stride size must not be zero

### ISSUE THREAD

**Issue by andertsk** [danielgindi/Charts#981]
When i zoom line chart by pinchinch gesture i got this error. On this line of code:

> -> for _ in first.stride(through: last, by: interval)
> {
> ...
> }
In file ChartYAxisRenderer.swift

**Comment by liuxuan30** [comment]
coud you be more specific? Like which func. Could it be reproduced by ChartsDemo?

**Comment by andertsk** [comment]
Hello, i see that you fixed it but when i use "pod install" i see in that file only these lines of code:
![2016-05-17 16 20 54](https://cloud.githubusercontent.com/assets/705208/15319322/15a77d5c-1c4c-11e6-9e24-8620afdb8836.png)
and no "if" statement

**Comment by danielgindi** [comment]
You are not using the latest code. It is not released yet. Also please don't double post.
