### ISSUE TITLE
Conflicting other pod depencies

### ISSUE THREAD

**Issue by deepp** [danielgindi/Charts#983]
HI,

When I install pod on xcode 7.3 it gives linker error library not found lAFNetworking.

With xcode 7.2 When I drag project and add it get this
<img width="666" alt="screen shot 2016-04-27 at 6 07 34 pm" src="https://cloud.githubusercontent.com/assets/249790/14852283/0657d652-0ca3-11e6-8557-e8c9e0bb1785.png">

Please let me know which step is wrong.

**Comment by deepp** [comment]
Please would appreciate if anybody can share their solution to this.

**Comment by danielgindi** [comment]
On Xcode 7.3: That's not really our problem. It's probably IAFNetworking that does not support 7.3 yet for some reason.
On Xcode 7.2: You are using a version of Charts that's too new, as the latest release depends on Swift 2.2, and Xcode 7.2 only support Swift 2.1.
