### ISSUE TITLE
gesture conflict when lineChartView in tableView

### ISSUE THREAD

**Issue by alanz1982** [danielgindi/Charts#984]
i have a tableView
each cell has a lineCharView
after lineChartView zoom in and horizontal scroll,
tableView can not vertical scroll when tap on linechartView
how can i fix it? thanks 100 times.

**Comment by liuxuan30** [comment]
I remember there is some code for it.

check `gestureRecognizer(gestureRecognizer: NSUIGestureRecognizer, shouldRecognizeSimultaneouslyWithGestureRecognizer otherGestureRecognizer: NSUIGestureRecognizer)`
but I don't remember is there any property for this. please take a look at the code

**Comment by danielgindi** [comment]
The code automatically handles cases where there are zoom-pan on the chart. When you reach the end of the chart - it will stop panning and enable the scrolling on the parent.

If you want to be able to scroll *while panning the chart*, then do what @liuxuan30 suggested. There are also other discussions in *issues*, so you can search for it and gain some insights.

**Comment by alanz1982** [comment]
3q for all

**Comment by inix** [comment]
@alanz1982 
hi, I have similar scenario with you,that,I disable Y axis scale,but I can not scroll tableview in the chart.
I just do a simple hack,that if chart disable Y axis scale,enable UITableView vertically scrolling.

```
		if !self.isScaleYEnabled {
			_outerScrollView?.nsuiIsScrollEnabled = true
		} else {
			_outerScrollView?.nsuiIsScrollEnabled = false
		}
```
in func `@objc fileprivate func panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)`
of `BarLineChartViewBase.swift` file

diff:
```
@@ -688,7 +688,11 @@ open class BarLineChartViewBase: ChartViewBase, BarLineScatterCandleBubbleChartD
                     if _outerScrollView !== nil
                     {
                         // Prevent the parent scroll view from scrolling
-                        _outerScrollView?.nsuiIsScrollEnabled = false
+                                               if !self.isScaleYEnabled {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = true
+                                               } else {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = false
+                                               }
                     }
                 }
                 
```

**Comment by alanz1982** [comment]
thanks！！it help me so much，


发自我的 iPhone

在 2016年12月1日，下午7:11，Inix John <notifications@github.com<mailto:notifications@github.com>> 写道：


@alanz1982<https://github.com/alanz1982>
hi, I have similar scenario with you,that,I disable Y axis scale,but I can not scroll tableview in the chart.
I just do a simple hack,that if chart disable Y axis scale,enable UITableView vertically scrolling.

                if !self.isScaleYEnabled {
                        _outerScrollView?.nsuiIsScrollEnabled = true
                } else {
                        _outerScrollView?.nsuiIsScrollEnabled = false
                }


in func @objc fileprivate func panGestureRecognized(_ recognizer: NSUIPanGestureRecognizer)
of BarLineChartViewBase.swift file

diff:

@@ -688,7 +688,11 @@ open class BarLineChartViewBase: ChartViewBase, BarLineScatterCandleBubbleChartD
                     if _outerScrollView !== nil
                     {
                         // Prevent the parent scroll view from scrolling
-                        _outerScrollView?.nsuiIsScrollEnabled = false
+                                               if !self.isScaleYEnabled {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = true
+                                               } else {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = false
+                                               }
                     }
                 }

**Comment by shanyulaile** [comment]
I tried it your way, but the tableview is still not sliding vertically, and I'm adding the following code to the BarlinechartViewBase

@@ -688,7 +688,11 @@ open class BarLineChartViewBase: ChartViewBase, BarLineScatterCandleBubbleChartD if _outerScrollView !== nil { // Prevent the parent scroll view from scrolling - _outerScrollView?.nsuiIsScrollEnabled = false + if !self.isScaleYEnabled { + _outerScrollView?.nsuiIsScrollEnabled = true + } else { + _outerScrollView?.nsuiIsScrollEnabled = false + } } }

**Comment by pratik-jaiswal** [comment]
Hi, I tried with your hack but its not working. Do you have any other way of achieveing that?
Or is there any other way to do this? @liuxuan30 @danielgindi @inix 

  if _outerScrollView !== nil
                     {
                         // Prevent the parent scroll view from scrolling
-                        _outerScrollView?.nsuiIsScrollEnabled = false
+                                               if !self.isScaleYEnabled {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = true
+                                               } else {
+                                                       _outerScrollView?.nsuiIsScrollEnabled = false
+                                               }
                     }
                 }
