### ISSUE TITLE
highestVisibleXIndex has regression issue

### ISSUE THREAD

**Issue by liuxuan30** [danielgindi/Charts#985]
@danielgindi 
for https://github.com/danielgindi/Charts/commit/375d7baea85618258790abe6ba2a77d5543a4025, you mentioned this closes for #785, #794

However, my old PR: https://github.com/danielgindi/Charts/commit/862de8907b9397a6732512e001d3e914e81043c1 was trying to fix other issue.

I think we need review these two commits for highestVisibleXIndex? I had regression on my side:

pt.x now is 25.0, if we print it, but in the mem, it looks like 24.999999993, so floor(pt.x) would be 24, while it should be 25.0?

**Comment by liuxuan30** [comment]
So I checked #785, #794, they are related to lowestVisibleXIndex I think, because old code has "+1" appended. The latest code removed +1.
However, I think highestVisibleXIndex should stick to round as mentioned above.

**Comment by danielgindi** [comment]
Implemented in Charts 3.0 (v3 branch)

**Comment by liuxuan30** [comment]
Is it a fix or a new implementation so this is solved automatically?

**Comment by danielgindi** [comment]
The whole X concept changed, so it's a new implementation. 
There's no "whole" x index, there are floating point x values, so we don't need to consider rounding to either side...

For x indexes there were reasons for both sides, used in multiple situations- now the situation does not exist :)
