### ISSUE TITLE
Max Value Y - Axis = 1  , How to set Y-Axis increment Y- Value ?

### ISSUE THREAD

**Issue by paneaktae** [danielgindi/Charts#989]

**Comment by liuxuan30** [comment]
please explain what you want to achieve. I can't understand.

**Comment by aastein** [comment]
I think @paneaktae means that he wants to have custom increments for number values on the y-axis. 

Ex: If your y-axis ranges from 0 to 10, incremented by 1, you have (0,1,2,3,4,5,6,7,8,9,10). 

With custom increment, I assume when zoomed in enough to display the increment, it would display axis values with that custom increment. 

Ex: custom increment is 0.2, your y-axis ranges from 0 to 10. When zoomed in on 0 to 2, the y-axis would have labels/gridlines at (0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0)

Is that correct @paneaktae?

**Comment by Satish273** [comment]
Yes I also want the same.
