### ISSUE TITLE
XY Bubble Chart

### ISSUE THREAD

**Issue by Eflet** [danielgindi/Charts#990]
I know there already have a floatXAxis branch but it seems still use the index based x-axis.
Is it possible to change the x-axis to y-axis, I mean , use two y-axis on the graph, one on left and one on bottom? I fond there is a render called ChartYAxisRendererHorizontalBarChart, may be we can use this.

**Comment by liuxuan30** [comment]
of course you can. I already did that. But it depends on your demands, and it's kind of workaround rather than a solution.

**Comment by Eflet** [comment]
I have tried myself, I try to modified the bubble chart only but I failed. I found it need to write almost every thing if I want to remove the index based x-axis.
At last I write a new series of chart type for XY plot.

I'm not familiar with swift, but now it can show a bubble at any point by x and y.
![screenshot](https://cloud.githubusercontent.com/assets/17873441/15039239/03a3dc94-12de-11e6-8d3f-c0390f398623.png)

XYBubbleChart code:
[https://github.com/Eflet/Charts/tree/v2.2.3](url)

**Comment by Eflet** [comment]
By the way, you said you already did that, do you mean floatXAxis? 
I tried the floatXAxis but it seems not finished...

Or is there any other branch?

**Comment by liuxuan30** [comment]
@Eflet, I just took the horizontal y axis acts as the x axis :) It's kind of hacky, but it works.

**Comment by Eflet** [comment]
OK, Thanks.
