### ISSUE TITLE
Y-Axis labels zooming issue

### ISSUE THREAD

**Issue by Monika-Tapadiya** [danielgindi/Charts#991]
Hello,
I am using LineChartView to draw linear equation graph and enabled     **_chartView.pinchZoomEnabled = YES;** for zooming graph but when i am trying to zoom it, it is showing y numbers twice or thrice.Please check the screen shot.It is happening on with the number from 0 -10, if I put max value more than 10 on yAxis then zooming is not causing the issue. 
I also tried with  ** [_chartView.viewPortHandler setMaximumScaleY: 2.f];** but if I pass 1 graph won't zoom , if I pass 3 in it repeats value thrice on zooming. 
I am not getting what causes the problem here.
Please help.

Thanks!

![screen shot 2016-04-29 at 2 41 05 pm](https://cloud.githubusercontent.com/assets/1327009/14912168/de283628-0e13-11e6-9ed2-9e64854db94b.png)
![screen shot 2016-04-28 at 4 14 25 pm](https://cloud.githubusercontent.com/assets/1327009/14912167/de27b612-0e13-11e6-973c-7797b2c08fb6.png)

**Comment by liuxuan30** [comment]
disable allowRepeatValues or, use decimal formatters.
