### ISSUE TITLE
Scale or zoom to particular axis or point in Combined chart view

### ISSUE THREAD

**Issue by domadiya-ashok** [danielgindi/Charts#993]
I am trying to implement zooming or scaling at particular point because of too many data plotting on graph. I have tried many way to scale or zoom at start of position but couldn't.

Can you please help me out from this ?  how can we zoom at position or any axis by programmatically ?

Thank you for providing wonderful library on graph. love it.

**Comment by liuxuan30** [comment]
well, could you take a look at the pinch gesture handler? It has a full workflow. You can also check ChartTransformer and ChartViewPortHandler for more APIs

**Comment by domadiya-ashok** [comment]
Thanks for reply. but i have tried it out. want to zoom by aromatically. 

Can that possible ?

**Comment by liuxuan30** [comment]
yes, that's why I asked you to take a look at the code. You just need to figure out your way, or new api

**Comment by danielgindi** [comment]
There are handy moveTo/zoomTo functions on the charts. I'm not sure whether they're on the release or just on `master`, but they are there - and with animations!
