### ISSUE TITLE
Emergency Problem

### ISSUE THREAD

**Issue by AZ-Sci-Tech** [danielgindi/Charts#996]
I use iOS-Chart (latest version) in my custom ObjC project has met some problems. When I use bar chart、line char and pie chart, everything is okay. But when I use radar chart and scatter chart ,there is a problem that my project normally run on simulator but will crash on my iPhone, and Xcode will log an error information "fatal error: NSArray element failed to match the Swift Array Element type". Xcode version is 7.3, and iOS version is 9.3.1. What should I do? Thanks!!!!!!!!!!!!!!!!!

**Comment by danielgindi** [comment]
The move to Swift 2.2 made things a little less stable.
The next release of the framework will hopefully fix most of those new issues. In the meanwhile - please try to compile from `master` branch.
