### ISSUE TITLE
Left Axis not showing labels after update to Swift 2.3

### ISSUE THREAD

**Issue by damfinkel** [danielgindi/Charts#997]
Hi, 

I've extended BarChartView. The problem I'm having is that, since I've updated to the last version, in some cases I can't see the leftAxis labels. All my bar charts are a subclass of BarChatView. I'm pasting the code below:

```swift
import UIKit
import Charts

class ProgressBarChartView: BarChartView {

    let minimumOffset = CGFloat(38.0)
    
    internal required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        initializeChartStyle()
        initializeYAxisStyle()
    }
    
    internal func populateChartWithYVals(yValues : Array<ChartDataEntry>, xValues: Array<ChartDataEntry>, label: String) {
        let dataSet = BarChartDataSet.init(yVals: yValues, label: label)
        self.styleDataSet(dataSet)
        
        data = BarChartData.init(xVals: xValues, dataSets: [dataSet])
    }
    
    private func initializeChartStyle() {
        minOffset = minimumOffset
        backgroundColor = UIColor.clearColor()
        gridBackgroundColor = UIColor.clearColor()
        xAxis.labelPosition = .Bottom
        xAxis.drawGridLinesEnabled = false
        rightAxis.enabled = false
        leftAxis.enabled = true
        dragEnabled = false
        pinchZoomEnabled = false
        doubleTapToZoomEnabled = false
        scaleXEnabled = false
        scaleYEnabled = false
        leftAxis.labelTextColor = UIColor.lightGrayColor()
        xAxis.labelTextColor = UIColor.lightGrayColor()
        infoTextColor = UIColor.primeGrayColor()
        legend.enabled = false
    }
    
    private func initializeYAxisStyle() {
        leftAxis.labelPosition = .OutsideChart
        leftAxis.valueFormatter = NSNumberFormatter.chartNumberFormatter()
        leftAxis.drawGridLinesEnabled = true
        leftAxis.drawLabelsEnabled = true;
        leftAxis.labelCount = 4
    }
    
    private func styleDataSet(dataSet: BarChartDataSet) {
        dataSet.colors = [UIColor.primeBlueColor().colorWithAlphaComponent(0.8)]
        dataSet.drawValuesEnabled = false
        dataSet.highlightColor = UIColor.primeColor()
        dataSet.axisDependency = .Left
    }
    
}
```

Here's a screenshot where the labels are not showing:

![image](https://cloud.githubusercontent.com/assets/5349650/14930596/88abc3d6-0e3b-11e6-9293-42b537eac42d.png)

I've tried changing a lot of stuff (from the background color, to the axis configuration) but nothing worked. Also, when I change the axisDependency to .Right, it does show the labels. I'd really appreciate the help.

Thanks!

**Comment by liuxuan30** [comment]
```
since I've updated to the last version, in some cases I can't see the leftAxis labels
```
so in some cases you can see, and some you can't - this should be something wrong in your code, but we don't have any knowledge. It could be clipped or something else. Can you try ChartsDemo?

**Comment by danielgindi** [comment]
Please report back if you've found the issue, and if it still exists

**Comment by AdamMak** [comment]
I had the same issue when I first updated to the latest version of the charts, I was able to fix it by adding this

chartView.leftAxis.forceLabelsEnabled = true

This solved the issue for me

**Comment by prabhatk** [comment]
I am too getting same problem even if i am using

chartView.leftAxis.forceLabelsEnabled = true
![simulator screen shot jun 13 2017 12 07 19 pm](https://user-images.githubusercontent.com/246486/27069108-e2c7db9c-5030-11e7-8d69-f977233b54e6.png)



override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view.
        
        let months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"]
        let unitsSold = [20.0, 4.0, 6.0, 3.0, 12.0, 16.0]
        
        setChart(dataPoints: months, values: unitsSold)
        
    }
    
    func setChart(dataPoints: [String], values: [Double]) {
        
        let values: [Double] = [8, 104, 81, 93, 52, 44, 97, 101, 75, 28,
                                76, 25, 20, 13, 52, 44, 57, 23, 45, 91,
                                99, 14, 84, 48, 40, 71, 106, 41, 45, 61]
        
        var entries: [ChartDataEntry] = Array()
        
        for (i, value) in values.enumerated()
        {
            entries.append(ChartDataEntry(x: Double(i), y: value, icon: UIImage(named: "icon", in: Bundle(for: self.classForCoder), compatibleWith: nil)))
        }
        
        dataSet = LineChartDataSet(values: entries, label: "First unit test data")
        dataSet.drawIconsEnabled = false
        dataSet.iconsOffset = CGPoint(x: 0, y: 20.0)
        
        chart = LineChartView(frame: CGRect(x: 50, y: 0, width: 600, height: 350))
        chart.backgroundColor = UIColor.white

        chart.data = LineChartData(dataSet: dataSet)
        chart.leftAxis.forceLabelsEnabled = true;
        chart.leftAxis.axisLineColor = .green
        chart.leftAxis.xOffset = 30
        chart.leftAxis.labelTextColor = UIColor.black
        chart.leftAxis.drawLabelsEnabled = true;
        chart.rightAxis.drawLabelsEnabled = true;
        
        print("count \(chart.xAxis.labelCount)")
        print("count \(chart.leftAxis.labelCount)")
        self.view.addSubview(chart)
    }

**Comment by harariyakamal** [comment]
I dont see any closing comments but this issue is closed. I am also facing the same issue. Its clipped. 
The Yaxis labels are visible when I set the labelPosition = .insideChart, but I cant see the yaxis labels when labelPosition = .outsideChart. 

Setting yAxis `chartView.leftAxis.forceLabelsEnabled = true` didnt help. 

I tried debugging, and it looks like the labels are drawn but clipped. Could you please help me to fix this.
