### ISSUE TITLE
Demo crashed when running on phone( iOS 9.0),but can run on iPhone (iOS 7.0)

### ISSUE THREAD

**Issue by alanz1982** [danielgindi/Charts#998]
Demo can run on simulator and on iPhone iOS 7.0,
but crash  when it run on phone (ios9.0)
i test many ways,recreate cer and provision,clean cache, change bulidSetting.....not work

xcode 7.3, iOS 9
crash log below:
dyld: Library not loaded: @rpath/Charts.framework/Charts
  Referenced from: /var/containers/Bundle/Application/0465A508-83DB-47A0-A60C-1A70CE571189/ChartsDemo.app/ChartsDemo
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/0465A508-83DB-47A0-A60C-1A70CE571189/ChartsDemo.app/Frameworks/Charts.framework/Charts: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/0465A508-83DB-47A0-A60C-1A70CE571189/ChartsDemo.app/Frameworks/Charts.framework/Charts'

**Comment by liuxuan30** [comment]
please search old issues, should be your problem.

**Comment by alanz1982** [comment]
cer problem! rebuilt cer and provision profile on other's computer, it works!
