### ISSUE TITLE
Crash when debug build, works on release build

### ISSUE THREAD

**Issue by Dean151** [danielgindi/Charts#999]
I use iOS-Charts with Carthage, and with my app, when I want to draw a Chart from a debug build, I obtain `fatal error: call of deleted method` crash.

The crash doesn't occurs when I build in release mode or when I archive my app.

**Comment by petester42** [comment]
Probably something that is being kept in cache try deleting your Carthage folder and download the dependencies again. And then if that doesn't work try nuking the Xcode derived data.

**Comment by Dean151** [comment]
Carthage and project clean didn't made it.
But nuking derived data did the job. Thanks!
